### ISSUE TITLE
Support quantization at the write_weights and loadWeights level.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#100]
To reduce network payload by 4x, let's quantize / dequantize at the network boundary in write_weights and loadWeights.

After we do that, we can investigate activation / weights quantization in-memory.

@adarob

**Comment by adarob** [comment]
We should also allow for 2x since I found in some cases that 4x was too
imprecise. I can probably work on this tomorrow.

**Comment by nsthorat** [comment]
Would you mind syncing with @pyu10055 first? He's near by you so it should be easy.

**Comment by adarob** [comment]
Sure. I'm mostly out today and in SF tomorrow, but I will reach out to him
before doing anything.

**Comment by pyu10055** [comment]
the support for weight compression is added.
