### ISSUE TITLE
tfjs-vis: Need a tfvis.render.* function to plot 2D data as images

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1000]
This is a feature request for a function under tfvis.render.*, similar to https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html

for displaying 2D data as an image. This would be useful for cases including but not limited to:

- Showing a sequence in which each item is a one-hot encoded vector (common in sequence models)
- Showing attention matrix from attention models
- Any generic type of 2D data.

Ideally, it should offer some commonly used color maps including the default gray scale and "jet".
Also, it should allow custom labeling of the rows and columns.

There is `confusionMatrix` function under tfvis.render.*, but it seems to be too specific to confusion matrix.

**Comment by tafsiri** [comment]
Adding some comments from our discussion. The need here is more related to being able to plot heatmap like data (hence the need for labels), somewhat separate from generic image plotting which i think is also useful and is in the pipeline.
