### ISSUE TITLE
Support decoding/resizing image data

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1003]

**Comment by chenqing** [comment]
@kangyizhang  any idea of support keras.preprocessing.image.ImageDataGenerator in tfjs?

**Comment by kangyizhang** [comment]
hi @chenqing we are planning to support keras.preprocessing but don't have a certain answer yet.

**Comment by kangyizhang** [comment]
The ops has been added. [tf.browser.fromPixels](https://js.tensorflow.org/api/latest/#browser.fromPixels) and [tf.node.decodeImage](https://js.tensorflow.org/api_node/1.2.6/#node.decodeImage)
