### ISSUE TITLE
[Documentation/Feature] Add documentation about saving a trained model

### ISSUE THREAD

**Issue by theunreal** [tensorflow/tfjs#101]
#### TensorFlow.js version
any

#### Browser version
any

#### Describe the problem or feature request
I trained a model and fed it with data. How can I save the model I just trained to use it later in my application? 
Can the process of saving and using a trained model be documented?

#### Code to reproduce the bug / link to feature request
Irrelevant

**Comment by dsmilkov** [comment]
Hi @theunreal,

This is very high on our list and stay tuned for updates soon. In the meantime, you can check out our [FAQ](https://js.tensorflow.org/faq/) for this and similar questions.

**Comment by nsthorat** [comment]
Have you seen our tutorials?

https://js.tensorflow.org/tutorials/import-keras.html
https://github.com/tensorflow/tfjs-converter

**Comment by dsmilkov** [comment]
Duplicate of #13

**Comment by theunreal** [comment]
Thanks @dsmilkov !

**Comment by dsmilkov** [comment]
Just to clarify, this question is about training the model in the browser, and exporing it out of the browser, right?

**Comment by theunreal** [comment]
@dsmilkov that's incorrect, I trained my model in the browser and I want to use the trained model later.

For example, I followed the ["Transfer learning"](https://js.tensorflow.org/tutorials/webcam-transfer-learning.html) tutorial, and I am able to train my model from my web camera on top of the MobileNet model.

Now I have a model that knows more, and I want to export it and use the "smarter" model with my new training data later in my web app.

**Comment by nsthorat** [comment]
Yep, I think you're talking about the same thing. This is the issue, it's a high priority: https://github.com/tensorflow/tfjs/issues/13

**Comment by talvasconcelos** [comment]
Even better, export the all thing to work independently from the library. See Synaptics way to save a model to Json (https://github.com/cazala/synaptic/wiki/Networks#tojsonfromjson) and to use the standalone function that works as a normal fn on jsvascript (https://github.com/cazala/synaptic/wiki/Networks#standalone)

Would something like this be possible with TF ?

**Comment by nsthorat** [comment]
Yeah, we're working on it. The challenge is we want to make sure we're compatible with TensorFlow and Keras (models are completely portable between browser / python). The issue is here and we're prioritizing it: https://github.com/tensorflow/tfjs/issues/13

**Comment by batrlatom** [comment]
Do you have some time frame for this? month, quartal?

**Comment by nsthorat** [comment]
Exporting models from the browser is slated for this quarter (next 2 months).
