### ISSUE TITLE
Make tf.data.csv returned dataset compatible with model.fitDataset

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1010]
Currently there is a mismatch between tf.data.csv returning dicts, and model.fitDataset expecting arrays. We could either 

1) add a optional argument in CsvConfig to make tf.data.csv return the array form
2) or make model.fitDataset accept the dict form
3) or provide a utility function to translate automatically

**Comment by dan-ryan** [comment]
Is this in the 1.0 version?
