### ISSUE TITLE
Provide easier syntax to extract values from DataElements

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1013]
This is a bit of a pain:

```
features = trainData.map(
    (row: {features: ..., target: ...}) => row.features)
    );
```

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Apologize for the delayed response and we're re-visiting the older issues to check whether those issues got resolved or not, It seems like we have updated our official documentation w.r.t [tf.data.csv](https://js.tensorflow.org/api/4.10.0/#data.csv) and added below note, It seems like we have taken care of this issue if I'm not wrong. Thank you!

`Note: If isLabel in columnConfigs is true for at least one column, the element in returned CSVDataset will be an object of {xs:features, ys:labels}: xs is a dict of features key/value pairs, ys is a dict of labels key/value pairs. If no column is marked as label, returns a dict of features only.`
