### ISSUE TITLE
Write  tutorial/guide for tfjs-data

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1014]

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Apologize for the delayed response and we're re-visiting the older issues to check whether those issues got resolved or not, It seems like we have updated our [official documentation ](https://js.tensorflow.org/api/4.10.0/#Data:~:text=tf.regularizers.l2-,DATA,.toArray,-VISUALIZATION) w.r.t `tfjs-data` if I'm not wrong. Thank you!
