### ISSUE TITLE
Implicit 0-based column names when header is not present

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1015]
I know we went back and forth on this one and decided to pun it for later, so I'm putting it in an issue to track.

**Currently**
We require user-provided `columnNames` when the header not present. Thus the user has to do:
`tf.data.csv(url, {header: false, columnNames: [....]})`

**Proposal**
When header is not present, we should have implicit column names `0` to `N-1`. Thus the user will only have to do:
`tf.data.csv(url, {header: false})` and each element will have keys from 0 to N-1

**Comment by gaikwadrahul8** [comment]
Hi, @dsmilkov 

Apologize for the delayed response and we're re-visiting the older issues to check whether those issues got resolved or not, It seems like we have updated our official documentation w.r.t [tf.data.csv](https://js.tensorflow.org/api/4.10.0/#data.csv).

If I'm not wrong we are taking care of this issue with the help of `csvConfig` parameter in that we have 

`hasHeader (boolean) : A boolean value that indicates whether the first row of provided CSV file is a header line with column names, and should not be included in the data.` 

If Am I missing something here, please let me know ? Thank you!
