### ISSUE TITLE
Move and polish the boston housing example into tfjs-examples

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1016]
We should move and polish the Boston Housing Example into tfjs-examples before launch. It can be pending PR that should be committed right after launch.

**Comment by davidsoergel** [comment]
It looks like there was progress on this in https://github.com/tensorflow/tfjs-examples/pull/193 but that was never submitted.  What's the status?

**Comment by kangyizhang** [comment]
Previously there are some possible concerns about using the boston housing dataset related to fairness issues (there is a column in the dataset that may have to do with racial profiling). 

@caisq is there any updates on using the boston housing dataset?

**Comment by kangyizhang** [comment]
We'll not update the boston housing example because of potential fairness issues. Shanqing added another [example](https://github.com/tensorflow/tfjs-examples/tree/master/data-csv) using the tf.data.csv api.
