### ISSUE TITLE
Infer dtype from first n records, when it's not specified

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1017]
Python tf.data already does this: https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/data/experimental/ops/readers.py?rcl=215304249&l=129

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!
