### ISSUE TITLE
Evaluate and improve parity with tf.data

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1022]
For API completeness we need to implement at least:
- Dataset.flat_map()
- Dataset.dense_to_sparse_batch()
- Dataset.group_by_window()
- Dataset.padded_batch()

Maybe there are more (especially recently added) public methods that we've overlooked?

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Apologize for the delayed response and we're re-visiting the older issues and checking whether those issues got resolved or not yet so May I know have we taken care of this issue or still are we working on this issue please ?

It seems like we have updated our official documentation w.r.t [tf.data.Dataset](https://js.tensorflow.org/api/4.10.0/#class:data.Dataset) and we have added multiple api's w.r.t `tf.data.Dataset` [here](https://js.tensorflow.org/api/4.10.0/#class:data.Dataset:~:text=.columnNames-,tf.data.Dataset,.toArray,-VISUALIZATION). Thank you!
