### ISSUE TITLE
Provide a benchmark demo to measure streaming performance

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1026]

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Apologize for the delayed response and we're re-visiting older issues and checking whether we have taken care of those issues and if I'm not wrong, we have updated our official documentation w.r.t `Benchmarks` [here](https://github.com/tensorflow/tfjs#benchmarks)

We have added [Local benchmark tool](https://tfjs-benchmarks.web.app/) and [Multi-device benchmark tool](https://github.com/tensorflow/tfjs/tree/master/e2e/benchmarks/browserstack-benchmark/README.md) sections with benchmark custom models by following this [guide](https://github.com/tensorflow/tfjs/blob/master/e2e/benchmarks/local-benchmark/README.md). If I'm not wrong we have taken care of this issue or Am I missing something here ? 

Thank you!
