### ISSUE TITLE
Make statistics work for nested structures (i.e., TensorContainers).

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1027]
Per prior discussions, stats are considered lower priority and may need a separate design doc; tracking here anyway.

**Comment by davidsoergel** [comment]
When we revisit stats, we should coordinate with Facets since they already have code to do much of what we need: https://github.com/PAIR-code/facets/blob/master/facets_overview/common/feature_statistics_generator.ts

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

Apologize for the delayed response and we're re-visiting older issues and checking whether we have taken care of those issues and if I'm not wrong, we have updated our official documentation and we added tfjs-vis api [here](https://js.tensorflow.org/api_vis/1.5.1/)

If Am I missing something here please let me know ? Thank you!
