### ISSUE TITLE
Kaggle integration.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1028]
We have an email thread with the Kaggle folks from April explaining how to download data via direct HTTP requests to their API.

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!
