### ISSUE TITLE
feature request: toPixels

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#103]
_From @oveddan on March 11, 2018 16:19_

Right now deeplearn.js has a method [fromPixels](https://deeplearnjs.org/docs/api/index.html#dl.fromPixels) which takes an `ImageData` and converts it into a `Tensor3D`.

It would be nice to have something that does the inverse, like `toPixels` - which would take a 2d or 3d tensor and convert it to an `ImageData`

_Copied from original issue: tensorflow/tfjs-core#845_

**Comment by nsthorat** [comment]
_From @carlthome on April 3, 2018 18:7_

Yes, this would be handy! Particularly if `tf.toPixels` could handle RGB, RGBA and grayscale images like [`tf.summary.image`](https://www.tensorflow.org/api_docs/python/tf/summary/image).

This mess is what I'm using, and I'd gladly replace it:
```js
function toPixels(tensor) {
  const pixels = tensor.dataSync();
  const imageData = new ImageData(tensor.shape[0], tensor.shape[1]);
  if (tensor.shape.length == 2 || tensor.shape[2] == 1) {
    // Grayscale
    for (let i = 0; i < pixels.length; i++) {
      imageData.data[i*4+0] = pixels[i];
      imageData.data[i*4+1] = pixels[i];
      imageData.data[i*4+2] = pixels[i];
      imageData.data[i*4+3] = 255;
    }
  } else if (tensor.shape[2] == 3) {
    // RGB
    for (let i = 0; i < pixels.length / 3; i++) {
      imageData.data[i*4+0] = pixels[i*3+0];
      imageData.data[i*4+1] = pixels[i*3+1];
      imageData.data[i*4+2] = pixels[i*3+2];
      imageData.data[i*4+3] = 255;
    }
  } else if (tensor.shape[2] == 4) {
    // RGBA
    imageData.data = pixels;
  }
  return imageData;
}
```

**Comment by mlajtos** [comment]
Constructor for ImageData takes (width, height) as arguments and you are passing rows (shape[0]) as width and columns (shape[1]) as height..? That doesn't seem right.
