### ISSUE TITLE
Using JSON.stringify for multiple dataset.forEach cause ReferenceError: _JSON$stringify is not defined

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1039]
When using forEach to go through multiple datasets, JSON.stringify error occurs:

```
for (let i = 0; i < IRIS_CLASSES.length; ++i) {
    const dsThisClass = rawDataset.filter(e => e[4] === i).shuffle(100);
    testDatasetsByClass.push(dsThisClass.take(numTestExamples));
    trainDatasetsByClass.push(dsThisClass.skip(numTestExamples));
    // A
    dsThisClass.take(2).forEach(element => {
      console.log(JSON.stringify(element));
    });
    // B
    trainDatasetsByClass[i].take(2).forEach(element => {
      console.log(JSON.stringify(element));
    });
  }
```

> Uncaught (in promise) ReferenceError: _JSON$stringify is not defined
>     at r.trainDatasetsByClass.(:1236/anonymous function).take.forEach.element [as transform] (http://localhost:1236/iris.e31bb0bc.js:153242:15)
>     at r.<anonymous> (lazy_iterator.ts:698)
>     at browser.js:8
>     at Object.next (browser.js:8)
>     at s (browser.js:8)
> 

Comment out eighter A or B the code will work. Print out without using `JSON.stringify` is fine.

**Comment by caisq** [comment]
This is a problem with .babelrc and package.json. How you can solve the problem: copy the dependencies in package.json and the the content of .babelrc to the repo you are having the issue with.

You need a line like the following in your .babelrc:
```
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
```
