### ISSUE TITLE
[tfjs-data] tf.data.array()'s batching doesn't handle typed arrays correctly

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1041]
Currently, if you do the following, the batching doesn't give the right-shaped tensor. Instead it gives `undefined`.

```js
  const xArrays = [];
  for (let i = 0; i < 100; ++i) {
    xArrays.push(new Float32Array(10));
  }
  const ds = tf.data.array(xArrays).batch(5);
  ds.forEach(x => console.log(x));
```

But it works if you change ` xArrays.push(new Float32Array(10));` to ` xArrays.push(Array.from(new Float32Array(10)));`.

We need to make it work for typed arrays.

**Comment by caisq** [comment]
cc @davidsoergel

**Comment by davidsoergel** [comment]
This is sort of like #1046, in that we need to detect the type of the argument to `tf.data.array()` and handle certain types specially.

**Comment by kangyizhang** [comment]
This has been fixed by https://github.com/tensorflow/tfjs-data/pull/128
