### ISSUE TITLE
engine.ts:580 Uncaught TypeError: Cannot read property 'backend' of undefined

### ISSUE THREAD

**Issue by cpury** [tensorflow/tfjs#1048]
#### TensorFlow.js version
0.14.1

#### Browser version
Latest Chrome and latest Firefox both show this issue

#### Describe the problem or feature request
This is a tough one...

Using Keras, I have trained two similar models with different structures but the same inputs and outputs. Let's call them A and B. They work great in Python.

I use the latest `tensorflowjs_converter` to convert the models to TFJS format and load them in TFJS.

Model A works great!

When running model B with exactly the same code, I get:

```
engine.ts:580 Uncaught TypeError: Cannot read property 'backend' of undefined
    at e.readSync (engine.ts:580)
    at e.moveData (engine.ts:121)
    at Object.moveData (environment.ts:424)
    at e.get (backend.ts:49)
    at backend_webgl.ts:551
    at Array.every (<anonymous>)
    at e.shouldExecuteOnCPU (backend_webgl.ts:550)
    at e.slice (backend_webgl.ts:585)
    at ENV.engine.runKernel.$x (slice.ts:164)
    at engine.ts:206
```

Switching the backend to `cpu`, it works without error, but the output of the model is always the same, no matter the input. In Python, the model performs well!

Downgrading to tfjs 0.13.0 and lower, the behavior is similar but the error is different:

```
VM27465 tf.min.js:2 Uncaught TypeError: Cannot read property 'texture' of undefined
    at VM27465 tf.min.js:2
    at Array.map (<anonymous>)
    at e.compileAndRun (VM27465 tf.min.js:2)
    at e.slice (VM27465 tf.min.js:2)
    at ENV.engine.runKernel.$x (VM27465 tf.min.js:2)
    at VM27465 tf.min.js:2
    at e.scopedRun (VM27465 tf.min.js:2)
    at e.runKernel (VM27465 tf.min.js:2)
    at slice_ (VM27465 tf.min.js:2)
    at slice (VM27465 tf.min.js:2)
```

#### Code to reproduce the bug / link to feature request

**I will attach a reproduction repo shortly.**

I assume the problem lies in the model, though I don't see why. The only layer that I use in B that's not in A is the `Add()` layer.

**Comment by cpury** [comment]
Wow, while writing the reproduction code I found out what was wrong: When using model B, I somehow forgot to convert the input buffer to a tensor with `.toTensor()`. Now that I added it, it works fine. Sorry for the confusion.

Since this could happen to others as well, I would propose catching this earlier and printing a nicer error message, or automatically calling `.toTensor()`.

**Comment by cawfree** [comment]
For anyone else who encountered this issue, I've found that it can happen if you specify a `validationSplit` with an insufficient number of batches to split by.
