### ISSUE TITLE
Edit layers after adding them

### ISSUE THREAD

**Issue by bkazi** [tensorflow/tfjs#105]
In the high level layer API is it possible to change configs on the layers after they have been added to the model? Something like https://playground.tensorflow.org/ where you wouldn't have to rebuild the entire model when the shape of a layer changes or the number of layers changes.

The thought stemmed from the [React](https://reactjs.org) ideology of applying only the differences to the tree.

Is it just as efficient to rebuild the graph?

**Comment by nsthorat** [comment]
Unfortunately you can't swap them out on an existing model, but what you can do is create an array of layers, and a model that is initialized with those layers.

When one of your layer params changes, you simply remove that layer, create a new layer with the new hyperparams, and create a new model from those layers.

Does this make sense?

**Comment by nsthorat** [comment]
Closing this out.
