### ISSUE TITLE
DimRoundingMode doesn't work in tf.avgPool

### ISSUE THREAD

**Issue by GreyZzzzzzXh** [tensorflow/tfjs#1055]
#### TensorFlow.js version
tfjs-core: 0.13.3

#### Describe the problem or feature request
DimRoundingMode doesn't work in tf.avgPool. 

#### Code to reproduce the bug / link to feature request
```
x = tf.ones([1, 2, 2, 3]);
y = x.avgPool(1, 2, 1, 'floor');
```

> tfjs@0.13.3:2 Uncaught Error: The output # of rows (2.5) must be an integer. Change the stride and/or zero pad parameters
    at assert (tfjs@0.13.3:2)
    at computeOutputShape3D (tfjs@0.13.3:2)
    at getPadAndOutInfo (tfjs@0.13.3:2)
    at computeConv2DInfo (tfjs@0.13.3:2)
    at computePool2DInfo (tfjs@0.13.3:2)
    at avgPoolImpl_ (tfjs@0.13.3:2)
    at avgPool_ (tfjs@0.13.3:2)
    at Object.avgPool (tfjs@0.13.3:2)
    at e.avgPool (tfjs@0.13.3:2)
    at <anonymous>:1:7

**Comment by GreyZzzzzzXh** [comment]
root cause:
https://github.com/tensorflow/tfjs-core/blob/bb0a830b3bda1461327f083ceb3f889117209db2/src/ops/pool.ts#L184

should be
```
const convInfo = conv_util.computePool2DInfo(
      x4D.shape, filterSize, strides, dilations, pad, dimRoundingMode);
```

**Comment by bileschi** [comment]
Thanks for the clear bug report @GreyZzzzzzXh !  Is this something you would be interested in preparing a pull request for?

**Comment by GreyZzzzzzXh** [comment]
> Is this something you would be interested in preparing a pull request for?

Sounds great. 

PR: tensorflow/tfjs-core#1474.
