### ISSUE TITLE
QR-decomposition fails on a specific matrix.

### ISSUE THREAD

**Issue by jarno-r** [tensorflow/tfjs#1058]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.14.1

#### Browser version
Node.js v8.12.0 without tfjs-node. 

#### Describe the problem or feature request
QR decomposition returns NaNs for the invertible matrix [[0,2,2],[1,1,1],[0,1,2]], but works for some other matrices. 

#### Code to reproduce the bug
```javascript
"use strict";
exports.__esModule = true;
var tf = require("@tensorflow/tfjs");
var a = tf.tensor2d([[0, 2, 2], [1, 1, 1], [0, 1, 2]]);
var b = tf.tensor2d([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);
{
    var _a = tf.linalg.qr(a), q = _a[0], r = _a[1];
    q.print();
    r.print();
}
{
    var _b = tf.linalg.qr(b), q = _b[0], r = _b[1];
    q.print();
    r.print();
}
```

**Comment by jarno-r** [comment]
The bug is in linalg_ops.ts:214: `const s = rjj.sign().neg() as Tensor2D;`
The `sign()` function returns 0 for a zero value. 
It could be fixed like this:

    const sPre = rjj.sign().neg() as Tensor2D;
    const s = sPre.where(sPre.notEqual(tensor2d([[0]])), tensor2d([[1]]));

**Comment by caisq** [comment]
@jarno-r Do you want to send us a PR (to https://github.com/tensorflow/tfjs-core) to fix the issue?

**Comment by jarno-r** [comment]
PR: https://github.com/tensorflow/tfjs-core/pull/1472

**Comment by jarno-r** [comment]
PR: https://github.com/tensorflow/tfjs-core/pull/1473

**Comment by dsmilkov** [comment]
Fixed in https://github.com/tensorflow/tfjs-core/pull/1473
