### ISSUE TITLE
Multiple file:// handlers when using GPU

### ISSUE THREAD

**Issue by tomitheninja** [tensorflow/tfjs#1059]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.2.1
#### Browser version
node v10.15.0
node v11.5.0
#### Describe the problem or feature request
Loading both **tfjs-node** and **tfjs-node-gpu** makes model saving fail

> (node:14204) UnhandledPromiseRejectionWarning: Error: Found more than one (2) save handlers for URL 'file:///PROJECTDIR'

It works fine when I don't include tfjs-node-gpu
I'm using NodeJS's builtin require()
No preprocessor

### My system
Linux Mint 19.1 Cinnamon
Kernel 4.18.0-13-generic
CPU: i5-4460
GPU: NVIDIA gtx 1060 6GB

### Dependencies
    "@tensorflow/tfjs": "^0.14.1",
    "debug": "^4.1.1",
    "lodash": "^4.17.11",
    "mnist-data": "^1.2.6"
    "cross-env": "^5.2.0"
    "@tensorflow/tfjs-node": "^0.2.1",
    "@tensorflow/tfjs-node-gpu": "^0.2.1",
    "@types/debug": "^0.0.31"

yarn v1.12.3
#### Code to reproduce the bug / link to feature request
https://gist.github.com/tomitheninja/7272fd3baf7bfd26ea8292872e2ab0d5

**Comment by caisq** [comment]
@tomitheninja Can you show the code you use to import the libraries?

**Comment by caisq** [comment]
@tomitheninja Thanks. From these lines (https://gist.github.com/tomitheninja/7272fd3baf7bfd26ea8292872e2ab0d5#file-index-js-L10), it seems to me that it's possible that you've imported both @tensorflow/tfjs-node and @tensorflow/tfjs-node-gpu. This may have caused the file:// save handler to be registered twice. Can you make sure that only one of the two said libraries is imported?

**Comment by tomitheninja** [comment]
@caisq Thanks i thought i need to include both of them, because when i tried to use only gpu, it took ~30 secs to train a 10 element array, so i taught it stopped working so i killed it. 30 sec is probably because i have a huge model.

Thank you for the help
