### ISSUE TITLE
Fix Keras deserialization when using TF eager mode

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1060]
When enabling eager mode in the benchmark page (https://github.com/tensorflow/tfjs-layers/pull/396), some params of the mobilenet model get serialized as `{"type": "ndarray", "value": 6.0}` which tf.js deserialization doesn't understand.

To reproduce, run the benchmarks in layers after https://github.com/tensorflow/tfjs-layers/pull/396 gets in, and open browser console to see the error.

**Comment by caisq** [comment]
Fixed by https://github.com/tensorflow/tfjs-layers/pull/436
