### ISSUE TITLE
Scaling images results in values being clipped to zero

### ISSUE THREAD

**Issue by MikeHeald** [tensorflow/tfjs#1062]
Update:
I tried this on another windows machine and it worked without issues. So, this might be an issue specific to my machine if no one else can replicate.

#### TensorFlow.js version
0.14.1
It looks like this bug was introduced from 0.13.1 -> 0.13.2.

#### Browser version
Chrome and Firefox for Windows 10 (Other operating systems seem to work as expected)

#### Describe the problem or feature request
Scaling an image of any size to a size of about 128,128 will clip some values to zero. This happens using tf.image.resizeNearestNeighbor as well as with a model which has any step using tf.layers.upSampling2d or tf.layers.maxPooling2d. 

![image](https://user-images.githubusercontent.com/835870/50617913-27bbcf80-0eb5-11e9-8931-7559826ba8bf.png)

scaled up to [128,128] becomes:

![image](https://user-images.githubusercontent.com/835870/50617923-34402800-0eb5-11e9-84fb-fffab9310314.png)

#### Code to reproduce the bug / link to feature request
Scaling up using resizeNearestNeighbor :

	<canvas id="input" height=200 width=64></canvas>
	<canvas id="output" height=120 width=120></canvas>
	
	<script>
		input_canv = document.getElementById('input');
		
		randPix = tf.randomUniform([200,64,3],0,255, 'int32');
		
		tf.toPixels(randPix,input_canv)
							
		output_canv = document.getElementById('output')
		
		tf.toPixels(randPix.resizeNearestNeighbor([120,120]),output_canv);
	</script>

Scaling down using maxPooling2d :

	<canvas id="input" height=256 width=256></canvas>
	<canvas id="output" height=128 width=128></canvas>
	
	<script>
		input_canv = document.getElementById('input');
		
		randPix = tf.randomUniform([256,256,3],0,255, 'int32');
		
		tf.toPixels(randPix,input_canv)

		encoder_model = tf.sequential();
		
		encoder_model.add(tf.layers.maxPooling2d({
			inputShape: [256,256,3],
			size: [2,2]
		}));
	
		scaled = encoder_model.predict(randPix.expandDims(0));
							
		output_canv = document.getElementById('output')
		
		tf.toPixels(scaled.squeeze().asType('int32'),output_canv);
		
	</script>

**Comment by MikeHeald** [comment]
I tried this on some other devices and was unable to replicate the issue. I think it's safe to say this is an issue specific to my working laptop, caused by something outside of tfjs. I'll go ahead and close this issue, sorry for any inconvenience.

**Comment by LucaChen** [comment]
Have you used four generations of Intel CPUs?
