### ISSUE TITLE
Request to implement correlation layer

### ISSUE THREAD

**Issue by zboldyga** [tensorflow/tfjs#1063]
#### Describe the problem or feature request
A novel correlation layer is introduced in the FlowNet paper: https://arxiv.org/abs/1504.06852. This layer has been implemented in a pull request and it sounds like this will be added to Tensorflow/addons soon:

https://github.com/tensorflow/tensorflow/issues/11956
https://github.com/tensorflow/tensorflow/pull/21392

I am familiar with the mechanics of the correlation layer and recently did work on 3d convolutions in tfjs, I'd be happy to implement the correlation layer in tfjs :)

**Comment by gaikwadrahul8** [comment]
Hi, @zboldyga 

Apologize for the delayed response and I see this feature request hasn't implemented till now if I'm not wrong so still are you looking to implement this feature in TFJS ? Thank you!

**Comment by zboldyga** [comment]
@gaikwadrahul8 good timing, I was just about to prowl around for some project & use case to make a contribution. It's been a couple of years since I touched this code, but happy to scope it out, determine the value of this.

Do you know offhand the magnitude of requests for this type of feature, the relevant use cases? If not I can scan the mailing list & issues and revisit the proposed logic to figure out the impact and what implementation would look like
