### ISSUE TITLE
tf.data.csv("BAD_URL").forEach iterates over the lines of index.html

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#1067]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs: "0.14.0"
tfjs-converter: "0.7.0"
tfjs-core: "0.14.0"
tfjs-data: "0.1.4"
tfjs-layers: "0.9.0"

#### Browser version
72.0.3626.28 (Official Build) beta (64-bit)

#### Describe the problem or feature request
Iterating over a tfjs-data built from a faulty URL instead iterates over the lines of the HTML file which contains it.

#### Code to reproduce the bug / link to feature request
```
const myData = tf.data.csv("NOT_A_URL");
await myData.forEach((line) => console.log('line'));
```

**Comment by bileschi** [comment]
Example branch exhibiting behavior here:
https://github.com/tensorflow/tfjs-examples/tree/data-csv

**Comment by bileschi** [comment]
sorry, meant cc @davidsoergel @kangyizhang , not assign.

**Comment by ericdnielsen** [comment]
I'm running into this too.  Do we have thoughts on when/how it will be fixed?

**Comment by kangyizhang** [comment]
This should have been covered by the validation of row's item count in tf.data.
