### ISSUE TITLE
Should tf.oneHot be available as a chainable op?

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#1070]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs: "0.14.1"
tfjs-converter: "0.7.1"
tfjs-core: "0.14.2"
tfjs-data: "0.1.4"
tfjs-layers: "0.9.1"

#### Browser version
irrelevant

#### Describe the problem or feature request

Converting to onehot works like this:
oneHotRep = tf.oneHot(indexRep, 10);

But would it be more convenient if it could also be chained, like many of our other unary ops?

oneHotRep = indexRep.oneHot(10);

**Comment by bileschi** [comment]
cc @dsmilkov thoughts?

**Comment by dsmilkov** [comment]
+1. Want to take this on? Or we can label it as "contribution welcome".

**Comment by bileschi** [comment]
I can not prioritize this in the near future.  Labeled "contribution welcome" for now.
