### ISSUE TITLE
New Ops: Cholesky decomposition

### ISSUE THREAD

**Issue by ethanluoyc** [tensorflow/tfjs#1078]
Hi!

I am trying to write an operator for computing Cholesky decomposition (and gradients).
It will roughly be based on the approach in TensorFlow (which is based on https://homepages.inf.ed.ac.uk/imurray2/pub/16choldiff/choldiff.pdf). I am half way through and
have created a PR https://github.com/tensorflow/tfjs-core/pull/1492 but I think I need some help with a few details for implementing it. In particular
I would like to know 

1. What's the best way to copy the values of a tensor? I have tried tensor.clone() but apparently it does not do deep copying (https://github.com/tensorflow/tfjs/issues/1032).
2. I would like to know how I can do in-place update to the content of the result tensor. The original code (in Numpy) does in place updates with `a[:] = b` but I don't know if there is a simple way to do this in tfjs. Right now I am just creating loops to iterate through the indices to do updates but is there a better way?

Thanks!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
