### ISSUE TITLE
why i can't load tensorflow model use tf.loadFrozenModel in tensorflowjs

### ISSUE THREAD

**Issue by yiifanLu** [tensorflow/tfjs#1079]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.14
#### Browser version
Google Chrome ： 69.0.3497.100
#### Describe the problem or feature request
I first train the model in tensorflow，and I saved the model use tf.saved_model.simple_save.I was succeed converting to the tensorflowjs，but I cant load use tf.loadFrozenModel in tensorflowjs
#### Code to reproduce the bug / link to feature request
const MODEL_URL = 'web_model/tensorflowjs_model.pb'
const WEIGHTS_URL = 'web_model/weights_manifest.json'
async function fun(){
	console.log("111");
	console.time('Loading of model');
    const model = await tf.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
    console.log("222");
    console.time('Loading of model');
}
fun()

it always wait

**Comment by yiifanLu** [comment]
Whether the parameters will cause the load to fail, because I found that I can load when I only use a few parameters.

**Comment by pyu10055** [comment]
There is a SO thread on this, https://stackoverflow.com/questions/54143715/why-cant-i-load-tensorflow-model-using-tf-loadfrozenmodel-in-tensorflowjs
