### ISSUE TITLE
Local dev setups of tfjs-node should auto-clean deps

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1085]
When working on `@tensorflow/tfjs-node` a dependency library is symlinked to the build folder of node-gyp. This works fine until there is an update we ship to libtensorflow. Ideally, we'll keep a hash and check if the deps should be updated when running `yarn`.

**Comment by ManishAradwad** [comment]
Hello, I'd like to work on this issue! Can someone plz give me some pointers about how should I begin?

**Comment by jayeshmann** [comment]
@kangyizhang How can I begin to work on this?

**Comment by puranjayyadav** [comment]
Hey, I'd like to solve this problem, can someone please tell me where to start from, it'll be of great help.

**Comment by puranjayyadav** [comment]
@pyu10055 Can I please get this issue to solve?

**Comment by jayeshmann** [comment]
> @kangyizhang How can I begin to work on this?

@pyu10055

**Comment by rthadur** [comment]
This is not required as we have bundled all the dependencies under tfjs and there will be bazel which will take care of this from future releases.
