### ISSUE TITLE
Feature request: EarlyStopping callback for Model.fit() and Model.fitDataset()

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1087]
#### TensorFlow.js version
0.14.2

**Comment by chenqing** [comment]
+1

**Comment by caisq** [comment]
I plan to start working on EarlyStopping soon, assuming @davidsoergel / nobody else has started on this.

**Comment by davidsoergel** [comment]
Haven't started-- go for it!

**Comment by chenqing** [comment]
cool
