### ISSUE TITLE
Tensor flow js model upload to Google Cloud Storage

### ISSUE THREAD

**Issue by Comestibles** [tensorflow/tfjs#1089]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
Latest version
#### Browser version
Chrome
#### Describe the problem or feature request
Can't upload my saved model to Google cloud storage keep getting error 408 bad request while using upload type multipart

**Comment by tafsiri** [comment]
@Comestibles this is probably a better question for [StackOverflow](https://stackoverflow.com/). We are directing people there for support questions and this one may be more related to GCS than tensorflow.js.
