### ISSUE TITLE
Allow multiple instances of tf

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#109]
_From @HalfdanJ on January 18, 2018 18:17_

If there are two instances of deeplearnjs present (eg. in two different modules node_modules) they can easily both be loaded, and they both try to register backend. Currently that fails with `Uncaught Error: cpu backend was already registered`, could it instead just re-use the already registered backend?

_Copied from original issue: tensorflow/tfjs-core#562_

**Comment by amellnik** [comment]
This also occurs if the user imports `tf` more than once in a webpack project (for example, in multiple components using angular-cli).
