### ISSUE TITLE
fail to use loadfrozenmodel

### ISSUE THREAD

**Issue by JWSunny** [tensorflow/tfjs#1090]
when i use loadfrozenmodel function load my pb and json file about ssd demo, i have the the problem: RangeError: byte length of Float32Array should be a multiple of 4, the statue is 200 and i use the parceljs as the http server. 
I also have the mistake; and when i download the demo https://github.com/tensorflow/tfjs-converter/tree/master/demo/ssd ,and download the pb and json file, upload them from locally, i also have the same problem: RangeError: byte length of Float32Array should be a multiple of 4, can tell why? 
thanks
![image](https://user-images.githubusercontent.com/29625315/51102998-1f03bb80-181c-11e9-94aa-4d03fe278c81.png)

**Comment by pyu10055** [comment]
this looks like error related to file serving or cors, and related tfjs issues should have been fixed previously. Closing this issue due to lack of activities.
