### ISSUE TITLE
ReLU and LeakyReLU activations cannot be saved/loaded from model.json

### ISSUE THREAD

**Issue by rix0rrr** [tensorflow/tfjs#1093]
#### TensorFlow.js version

```
    "@tensorflow/tfjs-node": "^0.2.1",
@tensorflow/tfjs-layers:   "version": "0.9.1"
@tensorflow/tfjs-core:   "version": "0.14.2"
```

#### Browser version

N/A

#### Describe the problem or feature request

I've tried building a model with leaky relu activation functions. I *must* spell this as:

```
                    tf.layers.dense({
                        units: 100,
                        activation: 'LeakyReLU',
                    }),
```

Otherwise it will not be picked up. When I save the model (using `model.save()`) the activation function gets serialized to model.json as `"leaky_re_lu"`.

When I try to read the model again, I get an error that this activation function is not supported,but it's shown with a different case, showing `"leakyReLu"`:

```
Unknown activation: leakyReLu. This may be due to one of the following reasons:
1. The activation is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom activation is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
Creating new model.
```

Same happens if I specify `"ReLU"` as my activation function (but not if I specify `"relu"`).

### Expectation

I would expect that if my model successfully creates, I can save and load it as well.

**Comment by bileschi** [comment]
@rix0rrr  Looks like we have a serialization_utils problem.  Thanks for filing!  

Looks like leakyReLU might need to be special cased.

https://github.com/tensorflow/tfjs-layers/blob/11565ae1ff556bad97332fe11a64101303e5ebfd/src/utils/serialization_utils.ts#L44

https://github.com/tensorflow/tfjs-layers/blob/3d7d0d5ccf74b88960fcac461b7f885e2ba660fd/src/utils/generic_utils.ts#L122

**Comment by caisq** [comment]
@rix0rrr Thanks for reporting this issue. As we investigate and fix this issue, you can use the following workaround to make a model with a LeakyReLU activation that can be saved and loaded:

```
    const model1 = tf.sequential();
    model1.add(tf.layers.dense({
      units: 100,
      inputShape: [200]
    }));
    model1.add(tf.layers.leakyReLU());  // Use the leakyReLU function under `tf.layers`.
```

**Comment by obenjiro** [comment]
@caisq Any progress so far?

**Comment by obenjiro** [comment]
@lina128 can you help here? Or will you accept pull request for this particular issue?

**Comment by lina128** [comment]
Hi @obenjiro, I see discussion in https://github.com/tensorflow/tfjs/issues/918, reference @caisq reply: "I'm pretty sure that 'leakyrelu' is not supported as a string activation even in Python Keras. It's accessible via tf.layers.* though." In this case, I think the workaround that @caisq suggested is the solution for now, unless keras change this behavior in the future. We are trying to have feature parity with keras. Does this solution solve your problem?

**Comment by obenjiro** [comment]
@lina128 Thank you didn't know about feature parity with Keras. I think we can close this issue then.
