### ISSUE TITLE
Feature Request: Add the ability to control how many shards are produced with tfjs-converter

### ISSUE THREAD

**Issue by raj-sivakumar** [tensorflow/tfjs#1095]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
"@tensorflow/tfjs-converter": "0.7.2",
"@tensorflow/tfjs-core": "0.14.5",
"@tensorflow/tfjs-data": "0.1.7",
"@tensorflow/tfjs-layers": "0.9.2"
python tensorflowjs==0.14.2
#### Browser version
Chrome 71.0.3578.98

#### Describe the problem or feature request
It would be nice instead of generating a pre-determined number of shards for the binary weights, to allow the user to specify either:
1. the number of shards or
2. the size of each shards or a limit to the size.

Depending on which is specified, it would be nice to automatically adjust the other parameter allowing users to have either fewer shards of larger size or more shards of smaller size, depending on their needs.

**Comment by tommy3266** [comment]
for now ,can i use tfjs convert my keras model to tfjs_model and control the shards files?

**Comment by pyu10055** [comment]
the feature is available in the converter now.
