### ISSUE TITLE
tfjs-node support

### ISSUE THREAD

**Issue by ShadabFaiz** [tensorflow/tfjs#1104]
"@tensorflow/tfjs-node": "^0.2.3"

Scenario: FaceAPIJS is a library that make use / suggest to used tfjs-node to increase performance for image analysis. There tfjs-node works perfectly. No error or warning anything.

So i want to start learning about Tenserflow using @tenserflow/tfjs-node. Created a project. Installed @tenserflow/tfjs-node.  But here, when i try to load it, i'm getting warning:
```nodejs
 import '@tensorflow/tfjs-node'; // this is all i'm doing right now.

 // Error on console.
import '@tensorflow/tfjs-node';
2019-01-18 15:49:34.249257: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```
Any reason why i works with when i used with FaceApiJS but it gives this warning / error when i'm using it on a newly crated project?

**Comment by rthadur** [comment]
Thanks @ShadabFaiz  please refer here for similar issue raised in Stack-overflow https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by ShadabFaiz** [comment]
Thanks for the link. However the discussion on the link provided was related to tenserflow and not with this specific @tenserflow/tfjs-node library. Also i dont have tenserflow install globally in my system, so i dont that can be the problem.

**Comment by ShadabFaiz** [comment]
Something interesting happened jsut now. FaceApiJs suggested that i use tfjs-node like this:
```typescript
import "@tensorflow/tfjs-node"
```
and i did just that and it worked there. however, in my new project, i was trying to use it just like that only. but when i changed the import syntax to:
```typescript
import * as tf from '@tensorflow/tfjs-node';
```
i'm not getting any error. Wierd but it worked.

**Comment by hartatovich** [comment]
it is possible to use custom binary with tfjs-node ?
I created a custom build on my mac-os (should be optimized) but I cannot make tfjs-node work with that binary I compiled
(I'm also trying to install it into pip but still cannot make tfjs-node work with it)

I think tfjs/node is working with a local binary inside node_modules but I'm not really sure.

I would also consider tfjs-node-gpu on windows 10 but also there I cannot replace the binary
any thoughts ??
cc
@rthadur @ShadabFaiz

**Comment by kangyizhang** [comment]
hi @hartatovich it is not supported right now. We have a tracking issue and we will prioritize this request. Meanwhile if you would like to try with your local tfjs-node package, you can modify this file https://github.com/tensorflow/tfjs-node/blob/master/scripts/install.js#L106 to bind with your own binary.

hi @ShadabFaiz your issue is duplicate as https://github.com/tensorflow/tfjs/issues/894. face-api.js is mostly using tfjs-core, which is not using tensorflow c library.

**Comment by hartatovich** [comment]
@kangyizhang Thank you for your response.
but I'm not sure I'm following...

where can I track the see the prioritize of the request (I'm trying to understand if I should try it before my self or not)

looks like the function in line 106 is only handling windows?
I'm actually trying to replace the binary for both macos and windows.. (macos is higher priory at me end

**Comment by kangyizhang** [comment]
@hartatovich ah sorry I missed the link of the tracking issue: https://github.com/tensorflow/tfjs/issues/571

The current workflow is that:
1. this line https://github.com/tensorflow/tfjs-node/blob/master/scripts/install.js#L111 will download and unpack the raw binary based on your os (windows/linux/mac, cpu or gpu). If you want to use your own binary you will need to change this part to that it doesn't do anything.
2. node-gyp will bind the downloaded binary based on config is https://github.com/tensorflow/tfjs-node/blob/master/binding.gyp, to use your own binary you will need to config node-gyp to bind with your own binary.

Please feel free to let me know if you have any question. This tracking issue fits the topic better: https://github.com/tensorflow/tfjs/issues/571

We might switch to deliver pre-built binary which changes the workflow, so I would love to know more about your production use-case.  Real-world server side uses cases will help us prioritize features on Node.js :-)

**Comment by mattalec** [comment]
HI, I am following a course on udemy that involves running the 'npm install' into my directory of choice. Unfortunately I have tried swapping to python 2 (from 3 as it seemed to cause an error), running the windows building code and most other 'fixes' I could find online. Unfortunately nothing has let me download the libraries without a 'not ok' error at the end. I am new to coding (and github) and would really appreciate any help/ directions into fixing this issue. Here is the latest cmd prompt message I got back:
Many thanks to anyone that will take a look.


C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf>npm install

> @tensorflow/tfjs-node@0.1.17 install C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

* Downloading libtensorflow
[==============================] 3672796/bps 100% 0.0s
* Building TensorFlow Node.js bindings
C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf\node_modules\@tensorflow\tfjs-node\scripts\install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at cp.exec (C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf\node_modules\@tensorflow\tfjs-node\scripts\install.js:154:13)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm WARN knn-tf@1.0.0 No description
npm WARN knn-tf@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.1.17 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.1.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alec\AppData\Roaming\npm-cache\_logs\2019-07-22T08_14_41_825Z-debug.log

C:\Users\alec\Desktop\MLKits-master\MLKits-master\knn-tf>

**Comment by kangyizhang** [comment]
@mattalec 

Can you try the latest version of tfjs-node@1.2.4? The new version does not require local compiling on your machine and should not have the error you described.

**Comment by kangyizhang** [comment]
The latest tfjs-node does not require client side compiling anymore.

**Comment by josephrocca** [comment]
@kangyizhang tfjs-node works fine for me, but I thought I'd mention that I do still get these messages warning me that my CPU isn't being fully utilised:

```
node-pre-gyp info This Node instance does not support builds for N-API version 5
node-pre-gyp info This Node instance does not support builds for N-API version 5
2020-01-19 02:09:42.223966: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-19 02:09:42.255597: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300075000 Hz
2020-01-19 02:09:42.256468: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3efa230 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-19 02:09:42.256949: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
```

Apparently one can get significant speed-ups with these extra instructions, so I wonder if it's possible to ship extra binaries that utilize them?

Here's a demo of those warning messages: https://glitch.com/edit/#!/tfjs-node-avx2-fma Just click `tools > logs` in the bottom-right to see the logs.

Let me know if I should post as a separate issue, or the binaries that use AVX2 and FMA will always need to be manually compiled by the user. Thanks!
