### ISSUE TITLE
WebGL development status: Prospective Contributer

### ISSUE THREAD

**Issue by karanchahal** [tensorflow/tfjs#1105]
#### TensorFlow.js version
N/A
#### Browser version
N/A
#### Describe the problem or feature request

Hello, I am a GPU developer and I'm interesting in speeding up the WebGL backend of Tfjs. At what stage is the development happening currently and can someone link me in the right direction to get me started on an issue ?

#### Code to reproduce the bug / link to feature request
N/A

**Comment by tafsiri** [comment]
Hi @karanchahal, I think any of the issues [tagged performance](https://github.com/tensorflow/tfjs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Atype%3Aperformance) might be a good place to look. Not sure how to answer your question about development stage, but the WebGL backend has been around for a while and is one our main focus areas for browser execution.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
