### ISSUE TITLE
TypeScript compile errors with 'strict'

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#111]
_From @ofrobots on January 21, 2018 17:23_

I was trying to use this library from a TypeScript project and getting some very hard to digest TypeScript compile errors in deeplearn types. It turns out that the code here is not usable from a project that uses the TypeScript [strict compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Adding the strict flag to `tsconfig.json` in this repo and building gives the same errors. Gory details included.

<details>
yarn run v1.3.2
$ tsc

src/data/checkpoint_loader.ts(124,21): error TS2345: Argument of type 'Array4D<"float32"> | Array1D<"float32"> | Array3D<"float32"> | Array2D<"float32"> | Scalar<"float...' is not assignable to parameter of type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">'.
  Type 'Array4D<"float32">' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">'.

124             resolve(ndarray);
                        ~~~~~~~


src/data/dataset.ts(151,11): error TS2345: Argument of type 'Scalar<"float32"> | Array1D<"float32"> | Array2D<"float32"> | Array3D<"float32"> | Array4D<"float...' is not assignable to parameter of type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">'.
  Type 'Scalar<"float32">' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">'.
    Types of property 'flatten' are incompatible.
      Type '() => Array1D<"float32">' is not assignable to type '() => Array1D<"float32" | "int32" | "bool">'.
        Type 'Array1D<"float32">' is not assignable to type 'Array1D<"float32" | "int32" | "bool">'.

151           NDArray.make(example.shape, {values: normalizedValues}, 'float32'));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/data/dataset.ts(206,7): error TS2322: Type 'number | undefined' is not assignable to type 'number | Float32Array'.
  Type 'undefined' is not assignable to type 'number | Float32Array'.

206       curLowerBounds = this.normalizationInfo[dataIndex].lowerBound;
          ~~~~~~~~~~~~~~


src/data/dataset.ts(207,7): error TS2322: Type 'number | undefined' is not assignable to type 'number | Float32Array'.
  Type 'undefined' is not assignable to type 'number | Float32Array'.

207       curUpperBounds = this.normalizationInfo[dataIndex].upperBound;
          ~~~~~~~~~~~~~~

src/data/dataset.ts(236,34): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number | Float32Array'.
  Type 'undefined' is not assignable to type 'number | Float32Array'.

236         this.dataset[dataIndex], this.normalizationInfo[dataIndex].lowerBound,
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/data/dataset.ts(249,19): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number | Float32Array'.
  Type 'undefined' is not assignable to type 'number | Float32Array'.

249         examples, this.normalizationInfo[dataIndex].lowerBound,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/data/dataset_test.ts(48,37): error TS2345: Argument of type '(Array2D<"float32">[] | Array1D<"float32" | "int32">[])[]' is not assignable to parameter of type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">[][]'.
  Type 'Array2D<"float32">[] | Array1D<"float32" | "int32">[]' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">[]'.
    Type 'Array2D<"float32">[]' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">[]'.
      Type 'Array2D<"float32">' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">'.
        Types of property 'flatten' are incompatible.
          Type '() => Array1D<"float32">' is not assignable to type '() => Array1D<"float32" | "int32" | "bool">'.
            Type 'Array1D<"float32">' is not assignable to type 'Array1D<"float32" | "int32" | "bool">'.

48     const dataset = new StubDataset(data);
                                       ~~~~


src/data/input_provider_test.ts(41,53): error TS2345: Argument of type 'Scalar<"float32">[][]' is not assignable to parameter of type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">[][]'.
  Type 'Scalar<"float32">[]' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "higher" | "0" | "1" | "2" | "3" | "4">[]'.
...
...
...
</details>


To make deeplearn usable as broadly as possible, it would be good to start using the `strict` compile option in this repo. Looking at `tsconfig.json`, it seems like the intent is to be strict, but the config might have been written before `strict` was a thing. It is a bit more strict than the flags in use at the moment. Many of the existing flags are subsumed by `strict`.

<sub>Tangential: I would encourage to take a look at the module [gts](https://www.npmjs.com/package/gts). It provides the Google TS Style Guide configuration and utilities to apply them on a code-base.</sub>

_Copied from original issue: tensorflow/tfjs-core#576_

**Comment by nsthorat** [comment]
_From @dsmilkov on January 21, 2018 17:38_

Good point. Unfortunately, we find strict mode to be strangely prohibitive. For example (omitted quotes for readability):
`Array4D<float32>` should be assignable to `NDArray<float32|int32|bool, higher|0|1|2|3|4>` because:
- `Array4D<float32>` actually extends `NDArray<float32, 4>`, thus
- `Array4D` should be assignable to `NDArray`
- `float32` should be assignable to `float32|int32|bool`
- `4` should be assignable to `0|1|2|3|4|higher`.

but strict mode won't allow that. To fix that, we'll have to make major changes to our library (remove classes that extend NDArray) and break users.

Open to suggestions. Would be great to fix this!

**Comment by nsthorat** [comment]
_From @ofrobots on January 21, 2018 20:20_

I think the problem is due to the following definition of `NDArray`:

```ts
export class NDArray<D extends DataType = DataType, R extends Rank = Rank> { .. }
```
The default type parameters allow one to omit the type parameters when referring to `NDArray`. Strict mode enables [contravariant types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html) for function parameters, and a function accepting an `NDArray<DataType, Rank>` parameter is not type compatible with a function accepting `NDArray<D extends DataType, R extends Rank>` as D may actually be a type different from 'float32', 'int32', 'bool'.

Example:

```ts
// in NDArray constructor
ENV.math.register(this); // <-- type error in strict mode. 
```

`math.register` is defined as: `register(a: NDArray): void { ... }`  (omitting `| Variable` for brevity). The call to `math.register` from the `NDArray` constructor is unsound because `this` (an `NDArray` instance) may have been instantiated with a datatype different from the default value of DataType. This can be fixed by changing the definition of `register` to: ` register<D extends DataType, R extends Rank>(a: NDArray<D,R>): void {`.

More generally, I think we should omit the default template parameters from the `NDArray` definition, as it is leading to many instances of such type unsoundness.

With the `strict` flag I see lots of real type errors in the library that we are not currently catching.

**Comment by evmar** [comment]
Idea: you could enable most of strict mode, and just disable the `--strictFunctionTypes` flag, to get the other benefits of strict mode (such a null checking, which is also needed to generate the proper Closure externs from this library).

**Comment by dsmilkov** [comment]
That's good to know, thanks!

I think fundamentally the problem comes down to:

Why does a third-party typescript project care about the typescript settings of an external dependency?

I think that is fundamentally a typescript problem, and not a problem of the library. I'm happy to reopen this issue if we see a decent number of users that are affected by this limitation.
