### ISSUE TITLE
tf.fromPixels(img) is using width, I was expecting naturalWidth

### ISSUE THREAD

**Issue by steren** [tensorflow/tfjs#1111]
It seems that `tf.fromPixels(img)` is creating a Tensor of the size of the image's `width` and `height` properties, I would expect it to use the size defined by `naturalWidth` and `naturalHeight`.

Indeed, the `width` and `height` attribute of an image depend on how it is rendered on screen (potentially via CSS rules), I expect loading the pixels of an image to be independent from how it is rendered.

#### TensorFlow.js version:
0.13.3

#### Browser version:
73.0.3669.0

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
Let's keep this open possibly for TensorFlow.js 2.0.

**Comment by gaikwadrahul8** [comment]
Hi, @steren 

Apologize for the delayed response and I see we have updated our official documentation w.r.t `fromPixels` API [here](https://js.tensorflow.org/api/4.4.0/#:~:text=tf.setBackend-,BROWSER,tf.browser.toPixels,-METRICS) that's what you were looking or have I missed something here please ?

If we did not implement this feature till now so are you looking to implement this feature request ? Thank you!
