### ISSUE TITLE
Add generic dot product as a method.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#112]
_From @nsthorat on January 28, 2018 17:49_

Right now we only have "matMul" which forces you to have 2 Array2Ds, so a vector * matrix becomes:

`v.as2D(-1, m.shape[0]).matMul(m)`

We should simply have to do `v.dot(m)`.

_Copied from original issue: tensorflow/tfjs-core#610_

**Comment by nsthorat** [comment]
We also currently have a `dotProduct`, and `matrixTimesVector`-type methods, which we should consolidate under tensordot with the fix for this issue.

**Comment by nsthorat** [comment]
_From @tafsiri on February 23, 2018 15:34_

@dsmilkov can this be closed since it is a dup of #664 which is closed?

**Comment by nsthorat** [comment]
_From @dsmilkov on February 23, 2018 15:54_

we already marked #664 as dup of this one, so let's keep this open

**Comment by dsmilkov** [comment]
Fixed in https://github.com/tensorflow/tfjs-core/pull/1066

**Comment by sinoforever** [comment]
Could you expand the implementation of dot to mirror that of tf.tensordot or even implement tf.einsum from tensorflow? Currently dot only support 1d and 2d tensors. There was tensorflow/tfjs-layers#305, but it is for the layers API and follows Theano convention, which is not as easy to use as tensorflow's. Many thanks.
