### ISSUE TITLE
Remove Tensor1D/2D/3D/4D types?

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1125]
We have static rank inference in tfjs, however due to the flexibility of ops (e.g. reduction), we often can't infer the rank, which makes the user explicitly retype the tensor, e.g. 
```ts
const a = tf.tensor2d(...);
const axis = 0;
b.sum(axis) as tf.Tensor1D
c.sum() as tf.Scalar
```

Opening the discussion to understand if our Typescript users had much benefit from the explicit `TensorxD` types. Otherwise we should remove them in 1.0 in order to simplify the coding experience of our Typescript users.

**Comment by dsmilkov** [comment]
We've decided not to make this change for 1.0.

**Comment by thekevinscott** [comment]
Hello! I realize this is 3 years old, but it's the only one on this topic.

I'm maintaining a library where having explicit `TensorxD` rank types is very useful. They're still in TFJS so I presume you've elected to keep them, but I'd just like to log a vote in their favor.

>  however due to the flexibility of ops (e.g. reduction), we often can't infer the rank

This is a particular bugbear in my library, where I'm explicitly casting to specific ranks after TFJS operations. The three ops in particular I see this are:

- `.squeeze()`
- `.expandDims()`
- `model.predict()`

I understand that for the last operation it is probably difficult to infer any sort of rank for the tensor, but for the first two operations, is it possible for TFJS to infer the resulting rank based on the incoming tensor to avoid the explicit cast?
