### ISSUE TITLE
tf.data.generator should take a generator/iterator

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1139]
#### TensorFlow.js version
tfjs-data 0.1.7

#### Describe the problem or feature request

This function https://github.com/tensorflow/tfjs-data/blob/2f0b3a73e22ece7aed89570928d0dd22806f6bee/src/readers.ts#L127 takes something that is close to a generator/iterator but isn't as far as I can tell an actual JavaScript generator or iterator (note that all JS generators are iterators).

The example in the js doc passes in a function that returns `{value: any, done: boolean}` but doesn't have a `next()` method which generators and iterators should have.

Generators docs - [Link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)
Iterators docs - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

#### Code to reproduce the bug / link to feature request

Here is the kind of code that I think should work (adapted from the code on the MDN links above).

```js
// Make the generator function
function* dataGenerator() {
  const numElements = 1000;
  let index = 0;
  while (index < numElements) {
    const x = index;
    const y = index * 2;
    yield [x, y]
  }    
}

// Note we do not have to make generator, e.g. const generateData = dataGenerator();

// Make the dataset
const dataset = tf.data.generator(dataGenerator);

// Do some data processing with dataset methods
// ...

// Train on the data
model.fitDataset(dataset, ...[etc]...);
```

In this case the generator function is a factory that creates generators that yield data.

The same thing can be done without `function*` using an iterator, e.g. the `makeRangeIterator` on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators.

I think ideally this method should match taking something that satisfies the iterator protocol. Currently it doesn't work with either `dataGenerator` or the `generateData` that could be created from that.

If we want to keep the current form I think it should be named something else.

Let me know if I am missing anything.

---

Relatedly I think it would also be nice if there were some tests in the repo that used model.fitDataset. tfjs can be a dev dependency so that are more end-to-end tests that exercise the various dataset constructors to actually train a small model.

**Comment by dsmilkov** [comment]
+1. Thanks Yannick for filing this. The tl;dr is that the current `tf.data.generator()` is not aligned with the JS spec of generators and we should align it fully to avoid confusion. Thanks for sharing a code snippet!

**Comment by kangyizhang** [comment]
Current `tf.data.generator()` takes a function which returns what `iterator.next()` will return, in the format of `{value:[0, 0], done:false}`. 

We have a function called `datasetFromIteratorFn` which generates a dataset from `LazyIterator` object.  JavaScript generator or iterator has the same return value of `.next()` as our own class `LazyIterator`, but it's missing other methods, such as `.forEach()`, `.map()`, `.filter()`. 

We can use `iteratorFromFunction` to create `LazyIterator` from JavaScript generator or iterator, and then generate `Dataset` from `LazyIterator` here is an example:

  ```
  function* dataGenerator() {
      const numElements = 1000;
      let index = 0;
      while (index < numElements) {
        const x = index;
        const y = index * 2;
        index++;
        yield [x, y];
      }
    }

    const lazyIterator = iteratorFromFunction(dataGenerator().next);
    lazyIterator.take(10).forEach(e => console.log(JSON.stringify(e)));

    const ds = datasetFromIteratorFn(
        async () => iteratorFromFunction(dataGenerator().next));
    ds.take(10).forEach(e => console.log(JSON.stringify(e)));
```

I'll rename current API to something like `tf.data.fromFunction()` and add `tf.data.generator()` API to take JavaScript generator/iterator.

**Comment by Sir-hennihau** [comment]
is it possible to use async generators? f.e. when you need to stream data from your database that needs to be loaded asynchronously. didn't find a working example for that yet.
