### ISSUE TITLE
tfjs-core@master breaks layers

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1140]
Doing the version bump and we have some breakages:

https://github.com/tensorflow/tfjs-core/pull/1508
https://travis-ci.org/tensorflow/tfjs-core/jobs/484069285

**Comment by annxingyuan** [comment]
cc @pyu10055

**Comment by pyu10055** [comment]
https://github.com/tensorflow/tfjs-layers/blob/master/src/models_test.ts
all instances of spyOn(window, 'fetch').and.callFake() should return Promise
