### ISSUE TITLE
Guide: Differences from Python tf.keras

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1150]
- Models

**Comment by tafsiri** [comment]
FYI @caisq I assigned this to you for porting over to the new site. This mainly involves reviewing this tutorial to see if there is anything you want to update or change.

**Comment by caisq** [comment]
Will do.

**Comment by tafsiri** [comment]
Link to doc: https://github.com/tensorflow/tfjs-website/blob/devsite/docs/guides/tfjs-layers-for-keras-users.md
