### ISSUE TITLE
Tutorial: Saving and Loading Models

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1158]
- Training Models

**Comment by tafsiri** [comment]
Depends on https://github.com/tensorflow/tfjs/issues/1175 and https://github.com/tensorflow/tfjs/issues/1207

PR submitted. https://github.com/tensorflow/tfjs-website/pull/240

**Comment by tafsiri** [comment]
Link to doc https://github.com/tensorflow/tfjs-website/blob/devsite/docs/guides/saving-loading.md

**Comment by apoorv-1310** [comment]
so we cant the trained model ???

**Comment by tafsiri** [comment]
@apoorv-1310 Please take a look at https://www.tensorflow.org/js/guide and https://www.tensorflow.org/js/tutorials for more information.

**Comment by nsthorat** [comment]
Closing this out since this is done.
