### ISSUE TITLE
FrozenModel does not contain control flow or dynamic shape ops when using executeAsync()

### ISSUE THREAD

**Issue by Pravez** [tensorflow/tfjs#1169]
First of all, thank you for your wonderful library !

#### TensorFlow.js version

0.14.2

#### Browser version

chrome latest

#### Describe the problem

When using the `executeAsync` method from a model loaded with `loadFrozenModel`, I end up with the following exception :

```
Error: The model does not contain control flow or dynamic shape ops, please use execute method for better performance.
    at e.<anonymous> (tf-converter.esm.js:6743)
    at tf-converter.esm.js:133
    at Object.next (tf-converter.esm.js:146)
    at tf-converter.esm.js:53
    at new Promise (<anonymous>)
    at __awaiter (tf-converter.esm.js:30)
    at e.executeAsync (tf-converter.esm.js:6738)
    at Model._callee2$ (Model.ts:5)
   ....
```
This thing is, it works when using predict() or execute() methods.

My code is as follows :

```Typescript
public async runAsync(
    inputImage: HTMLImageElement,
    outputCanvas: HTMLCanvasElement
  ): Promise<tf.Tensor3D> {
    return this._execAsync(
      tf.tidy(() =>
        tf
          .fromPixels(inputImage)
          .toFloat()
          .expandDims()
      )
    ).then(
      value => {
        this.lastResult = tf.tidy(
          () =>
            (value as tf.Tensor4D)
              .squeeze()
              .toInt()
              .clipByValue(0, 255) as tf.Tensor3D
        );

        tf.toPixels(this.lastResult, outputCanvas);
        return this.lastResult;
      }, rejected => rejected
    ).catch(err => console.log(err));
  }

  private async _execAsync(
    input: tf.Tensor
  ): Promise<tf.Tensor<Rank> | tf.Tensor<Rank>[]> {
    if (this.model != undefined) {
      return this.model.executeAsync({ Placeholder: input });
    }

    throw Error("Model is undefined");
  }
```

I found [this issue](https://github.com/tensorflow/tfjs-converter/pull/195) which was about the same method generating the same exception but not in the same context. Can't say if it has anything to do with it ... The last update was in august, nothing new since then.

Thank you :)

**Comment by nsthorat** [comment]
The error message is just saying use `model.execute` instead of `model.executeAsync` since there are no asynchronous operations. `execute` and `executeAsync` do fundamentally the same thing, and you should use `execute` for models that can be executed synchronously.

cc @pyu10055 maybe the error could be clearer.

**Comment by Pravez** [comment]
Thank you for your answer.
What are exactly asynchronous operations ? I must admit I am not sure exactly what is the difference with synchronous operations, and just thought this was a way to execute the model "in background".
My final goal was to make the execute() asynchronous in order to show a loader and update my webpage, since running in synchronous mode is provoking a nice ~1 second lag.

**Comment by pyu10055** [comment]
@Pravez The reason for having executeAsync method is not performance specific, it is due to some of op's output shapes cannot be pre-determined during the compilation time.

It is interesting that you are experience 1 sec improvement on the your model when using executeAsync. The execute method for most part is actually async in term of javascript, since it pushes all the calculation to GPU, and only downloads the data, when you calls the output.dataSync(). And in the GPU all ops are serialized, so it not very likely that there will be such a large improvement when using executeAsync.

Maybe you can share some more details about your model, like how big is size, and what is the topologylike? (are there any preprocessing/postprocessing blocks)

**Comment by Pravez** [comment]
It is not really an improvement, actually it is a big lag causing my webpage to freeze for ~1 second (because it is a "blocking" call, not asynchronous).

My model is a loaded TFJS model from a converted TensorFlow model made from the paper "perceptual losses for real-time style transfer and super-resolution", so the style transfer. It contains a lightweight convolutional network and a VGG-16. Except concerning image pre-processing/post-processing with tasks like /255, type to float etc. there are no pre/post-processing blocks.

thank you for your interest ... :)

**Comment by nsthorat** [comment]
The `model.execute()` itself, which is synchronous, should be very quick to execute (actually calling `execute()` only enqueues GPU programs, it doesn't wait for them to finish).

Only when you call `dataSync()` on the resulting tensor do you actually block the UI and wait for the GPU to finish. If you call `data()` on the result of `model.execute()` you shouldn't block the UI thread for a second.

**Comment by XdyGoGo** [comment]
I use executeAsync method to handle my model and It takes one mistake - Error: Error in concat1D: rank of tensors[3] must be the same as the rank of the rest (1)

**Comment by chauhansaurabhb** [comment]
@nsthorat : I am getting the following output after running a object detection in tensorflow.js but I am not getting the output. Could you please help me to interpret the output?

`(4) [t, t, t, t]
0: t
dataId: {}
dtype: "float32"
id: 1480
isDisposed: (...)
isDisposedInternal: false
kept: false
rank: (...)
rankType: "3"
scopeId: 2240
shape: (3) [1, 100, 4]
size: 400
strides: (2) [400, 4]
__proto__: Object
1: t
dataId: {}
dtype: "float32"
id: 1481
isDisposed: (...)
isDisposedInternal: false
kept: false
rank: (...)
rankType: "2"
scopeId: 2242
shape: (2) [1, 100]
size: 100
strides: [100]
__proto__: Object
2: t
dataId: {}
dtype: "float32"
id: 1479
isDisposed: (...)
isDisposedInternal: false
kept: false
rank: (...)
rankType: "2"
scopeId: 2238
shape: (2) [1, 100]
size: 100
strides: [100]
__proto__: Object
3: t
dataId: {}
dtype: "float32"
id: 1477
isDisposed: (...)
isDisposedInternal: false
kept: false
rank: (...)
rankType: "1"
scopeId: 2234
shape: [1]
size: 1
strides: []
__proto__: Object
length: 4
__proto__: Array(0)`

Here is the code of _index.js_ file:
`let model;
const webcam = new Webcam(document.getElementById('wc'));
let isPredicting = false;


async function init(){
        try {
            await webcam.setup();
            model = await tf.loadGraphModel('http://127.0.0.1:8887/model/model.json');
        } catch (err) {
            console.log(err);
        }
}

async function predict() {
        const img = webcam.capture();
        console.log("executing model");
        output = await model.executeAsync(img);
        console.log(output);
    }

init()

function startPredicting(){
	isPredicting = true;
	predict();
}

function stopPredicting(){
	isPredicting = false;
	predict();
}`

> index.js

Code of _inference.html_ file:
`<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"> </script>
<script src="webcam.js"></script>
</head>
<body>
	<div>
		<div>
			<video autoplay playsinline muted id="wc" width="224" height="224"></video>
		</div>
	</div>
	<button type="button" id="startPredicting" onclick="startPredicting()" >Start Predicting</button>
	<button type="button" id="stopPredicting" onclick="stopPredicting()" >Stop Predicting</button>
	<div id="prediction"></div>
</body>

<script src="index.js"></script>
</html>
`

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
