### ISSUE TITLE
tensorflow.js:  how to multiply a layer by a scalar?

### ISSUE THREAD

**Issue by lhdoeo** [tensorflow/tfjs#1177]
I am using the tf.layers module to build an inception-resnet-v2 network, in terms of the paper, I need to multiply a scalar by the output in inception-resnet module to stabilize the training, when I used tf.layers.multiply().apply([tf.tensor(0.1),layer]), there threw an error that Arguments to apply() must be all SymbolicTensors or all Tensors, how can I achieve this requirement? A deep learning green hand from china QAQ

**Comment by caisq** [comment]
@lhdoeo 

The error message is appropriate in this case. What is the value you want to multiply the output of the inception-resnet module with? Is it constant or may change? If constant, you can define a custom layer to do that. If it can change, you can use an input layer and define the whole model using the "functional API". Let me know and I'll be happy to guide you further.

Also, for the future, questions like this are more suited to StackOverflow.

**Comment by lhdoeo** [comment]
```
with(tf.layers){
  let layer1_0 = conv2d(Config('conv',[1,32])).apply(_input)  
  let layer1_1 = conv2d(Config('conv',[1,32])).apply(_input)  
  let layer1_2 = conv2d(Config('conv',[1,32])).apply(_input)  
  let layer2_0 = conv2d(Config('conv',[3,48])).apply(layer1_0)  
  let layer2_1 = conv2d(Config('conv',[3,32])).apply(layer1_1)  
  let layer3_0 = conv2d(Config('conv',[3,64])).apply(layer2_0)  
  let concat1 = concatenate().apply([layer3_0,layer2_1,layer1_2])  
  let layer4 = conv2d(Config('conv',[1,_input.shape[3]],{activation:'linear'})).apply(concat1)  
// I need multiply a constant scalar --> scalar*layer4
// how to custom a layer? I only find tf.registerClass is related with custom layer, but no more details there are
  let add1 = add().apply([_input,layer4])  
  let bn = batchNormalization().apply(add1)  
  let output = elu().apply(bn)  
  return output  
}
```
![tim 20190201191428](https://user-images.githubusercontent.com/43592706/52122286-6fbd4600-265d-11e9-971e-1285315546b2.png)

**Comment by lhdoeo** [comment]
I am sorry for my stupidity, this problem have been solved by just using 1x1 conv layer with constant kernelinitializer ... -_-||
