### ISSUE TITLE
feat(docs): add doc comments

### ISSUE THREAD

**Issue by ngfelixl** [tensorflow/tfjs#1180]
## Feature Request

This is a feature request for doc-comments to get detailed information for functions and classes inline while programming when hovering them.

Currently using the tensorflow js package looks like this (this is just example code) when hovering functions and other parts. Here I am hovering the **mul** memberfunction.

![currently](https://user-images.githubusercontent.com/24190530/52076200-716c0880-258e-11e9-9e06-f2ef255aab69.png)

But it would be nice to have detailed information on how to use the functions. For example the **mul** doc comment could contain the type of multiplication (element wise, matrix etc) and best practice examples, e.g. run math in `tidy`.

Here is an example using Angular. The Angular doc-comments are pretty awesome, I think. It contains almost everything in here, so that it's not necessary to google for it or look in the API docs most of the time.

![wouldbenice](https://user-images.githubusercontent.com/24190530/52076202-7466f900-258e-11e9-8b40-494c934f7d8b.png)

Cheers, Felix :)

**Comment by ngfelixl** [comment]
Oh, then this might be related to `@tensorflow/tfjs-node` only, since I'm using it in NodeJS and recently have read that one should not use

```
import { scalar } from '@tensorflow/tfjs';
import '@tensorflow/tfjs-node';
```

anymore but instead import everything directly from `@tensorflow/tfjs-node`.

**Comment by tafsiri** [comment]
If you post a small repo demonstrating what you are seeing we can take a look locally and see what combinations might cause issues.

**Comment by ngfelixl** [comment]
Sure. Have created a demo-repo, containing the setup and a single source file (*src/index.ts*) importing items from **@tensorflow/tfjs-node**.

https://github.com/ngfelixl/tfjs-no-docs-demo

**Comment by tafsiri** [comment]
@ngfelixl perfect. I can reproduce this and will look into it.

**Comment by tafsiri** [comment]
Note: A few PRs need to land a new release would need to be made to actually close the issue, but github will auto close this issue when each PR gets merged so i'll update it after they are all in.
