### ISSUE TITLE
Update jsdoc to explain what type of data is available in Dataset

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1187]
Current element type in `Dataset` is `DataElement`, which actually is `TensorContainer`. In tfjs-core jsdoc, `TensorContainer` has a jsalias(
https://github.com/tensorflow/tfjs-core/blob/a878dc2ef793b176dceece26b65ed51be6864383/src/tensor_types.ts#L31) to explain the type detail:
```
/**
 * @docalias void|number|string|Tensor|Tensor[]|{[key:
 * string]:Tensor|number|string}
 */
export type TensorContainer = void|Tensor|string|number|boolean|
    TensorContainerObject|TensorContainerArray;
```
In tfjs-data we should also explain what is `DataElement`, so user would be able to know what they are expecting from `Dataset`, as well as what type of data they can generate from `tf.data.generator`.

**Comment by davidsoergel** [comment]
Now that TensorContainer is exported, we can just use it directly, I think.  The DataElement stuff is a holdover from when we had to duplicate the interfaces.

**Comment by kangyizhang** [comment]
cc: @tafsiri
