### ISSUE TITLE
Performance in Node.JS

### ISSUE THREAD

**Issue by nxz91** [tensorflow/tfjs#1196]
Hello,

just seen the paper on HN – first of all – this is GREAT news! Thank you.

From my understanding, in Node Tensorflow.js binds to the TensorFlow C implementation. I only see a performance comparison for the browser – could you release a performance comparison with Python as well?

Thank you!!
Leonard

**Comment by inf3rno** [comment]
This one uses webGL for the computations, I think the node-tensorflow uses the C implementation: https://github.com/nikhilk/node-tensorflow It would be nice to compare them to each other and maybe to the python version on a few benchmarks. Afaik the webGl one is very slow, but so far I saw only browser measurements not nodejs ones.
