### ISSUE TITLE
Type '"int32"' is not assignable to type 'DType'.

### ISSUE THREAD

**Issue by mysticatea** [tensorflow/tfjs#120]
#### TypeScript version

- 2.8.1

#### TensorFlow.js version

- 0.7.0

#### Browser version

- N/A

#### Describe the problem or feature request

```ts
import * as tf from "@tensorflow/tfjs"

tf.input({ dtype: "int32" }) // error TS2345
```

```
error TS2345: Argument of type '{ dtype: "int32"; }' is not assignable to parameter of type 'InputConfig'.
  Types of property 'dtype' are incompatible.
    Type '"int32"' is not assignable to type 'DType'.
```

However, that `DType` enum is not exposed. It's defined at [tfjs-layers/src/types.ts#L23](https://github.com/tensorflow/tfjs-layers/blob/ea0796c0f07be7d4eb2712e5d11e169a9822bef1/src/types.ts#L23) then [tfjs-layers/src/index.ts#L21](https://github.com/tensorflow/tfjs-layers/blob/ea0796c0f07be7d4eb2712e5d11e169a9822bef1/src/index.ts#L21) does not expose it.

On the other hand, `tf.tensor` uses `DataType` rather than `DType`, so we can write `tf.tensor1d([1, 2, 3], "int32")`: https://github.com/tensorflow/tfjs-core/blob/643477e8198fc594731ce3b5aaadec60a4071d50/src/ops/array_ops.ts#L61

So I think there are two problems here:

1. Two incompatible types exist to represent the type of `dtype`: `DType` and `DataType`.
2. Some types aren't exposed but APIs are using, e.g., `DType`, `Layer`, `History`, etc.

#### Code to reproduce the bug / link to feature request

```ts
import * as tf from "@tensorflow/tfjs"
tf.input({ dtype: "int32" }) // error TS2345
```

**Comment by dsmilkov** [comment]
Thanks @mysticatea. We will consolidate and have `tfjs-layers` accept `DataType` (which is just a string union), just like `tfjs-core` does.

Thanks!

**Comment by dsmilkov** [comment]
Closing since this is fixed at head.
