### ISSUE TITLE
Add integration tests for data + layers

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1200]
Add integration tests for data and layers that exercise end-to-end ML use cases (e.g. reading from csv and training a simple model).

This enables us to dogfood the Data API and understand the UX of using data.

The integration tests can live in the `tfjs-data` repo, depend on layers@master and data@master and run on Travis nightly.

**Comment by dsmilkov** [comment]
cc @tafsiri

**Comment by nsthorat** [comment]
If we expect to have more of these, would it make sense to put it in the union package? Otherwise we're going to have to remember where all the integration tests live (layers has its own integration tests).

**Comment by dsmilkov** [comment]
It makes sense for these to live in the data repo since these tests should be written by the owners of tfjs-data and should detect when data introduced breaking changes. Likewise for other repos.
