### ISSUE TITLE
[tfjs-vis] tfvis.render.heatmap() collapses rows or columns when there are duplicate labels

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1201]
#### TensorFlow.js version
tfjs-vis 0.5.0

If there are duplciate items in xLabels and/or yLabels, the rows or columns will be collapsed, causing confusing displays.

The displaying of the matrix should be done regardless of whether there are duplicate labels.

**Comment by tafsiri** [comment]
This fix is now available in https://www.npmjs.com/package/@tensorflow/tfjs-vis/v/1.2.0
