### ISSUE TITLE
How to build docs?

### ISSUE THREAD

**Issue by generic-github-user** [tensorflow/tfjs#1202]
I would like to build the TensorFlow.js docs from their source. I could not find any relevant information in the [documentation section](https://www.tensorflow.org/community/documentation) of the community pages. I was able to locate [this script](https://github.com/tensorflow/tfjs-website/blob/docs/build-scripts/build-api), which appears to be for building the docs. However, I was unable to figure out what command line parameters should be provided and in what format. The relevant section of the code seems to be [lines 32 to 40](https://github.com/tensorflow/tfjs-website/blob/docs/build-scripts/build-api.js#L32-L40).

```js
commander.option('--in [path]', 'main source entry')
    .option('--package [path]', 'Package.json path')
    .option('--src [path]', 'Path to src folder of repo')
    .option('--repo [path]', 'Path to repo')
    .option('--bundle  [path]', 'JS Bundle Path')
    .option('--github [url]', 'Github repository URL')
    .option('--out [path]', 'Output Path')
    .option('--branch [branch name]', 'branch to build from')
    .parse(process.argv);
```

I would appreciate any and all help that is provided. Thanks in advance!

**Comment by generic-github-user** [comment]
I have found instructions [here](https://github.com/generic-github-user/tfjs-website/blob/master/README.md) on how to use Yarn to build the docs, but I am now receiving this error:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tensorflow/tfjs-converter' into submodule path 'C:/Path/tfjs-website/libs/tfjs-converter' failed
Failed to clone 'libs/tfjs-converter' a second time, aborting
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I have attempted to fork the repository and make a fresh clone and this has not resolved the issue. I also could not find any relevant issues existing within this repository.

**Comment by generic-github-user** [comment]
I've also tried creating a new SSH key and adding it to my GitHub account and adding GitHub to `.ssh/known_hosts`.

**Comment by generic-github-user** [comment]
I resolved the above error using [this solution](https://stackoverflow.com/a/23634016/10940584). I now receive this error:
```
fatal: Needed a single revision
Unable to find current revision in submodule path 'libs/tfjs-core'
error Command failed with exit code 1.
```
I will work on this more tomorrow and update accordingly.

**Comment by tafsiri** [comment]
Is `yarn prep` working for you? If not you can try running the individual git commands (separated by `&&` specified in https://github.com/tensorflow/tfjs-website/blob/master/package.json#L12. It may be easier to see if there are any git configuration issues that way.

**Comment by generic-github-user** [comment]
`yarn prep` was giving an access rights error. I fixed that by changing `git@github.com:tensorflow/tfjs-layers.git` to `github.com/tensorflow/tfjs-layers.git` for all the repositories listed in `.gitmodules` and `config`.

**Comment by generic-github-user** [comment]
I was able to locate the fully built [JSON documentation tree](https://github.com/tensorflow/tfjs-website/blob/master/source/_data/api/0.14.2/docs.json) in the tfjs-website repository after some more searching. I no longer need to build the documentation for myself, but someone else may find this thread useful. Feel free to close the issue.
