### ISSUE TITLE
Add docs for tf.IOHandler to guide

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1207]
It is referenced in https://js.tensorflow.org/api/latest/#tf.Model.save but i don't think its docs are exported.

**Comment by anikulk** [comment]
Hi @tafsiri, I am a new comer to tfjs.  Can I work on this issue?

**Comment by tafsiri** [comment]
Hi @anikulk, thanks for being willing to jump in. I don't think this would be a good issue to start with as we are in the midst of changing some of how doc generation works to support this particular use case and are be changing the underlying functions and interfaces for our next release. I'll give some thought as to whether there are any good areas to jump in.

**Comment by tafsiri** [comment]
@caisq @nsthorat 

Updates from various convos about the doc generator and what it looks like we need for the 1.0.

- [ ] We need a symbol for `tf.io.browserHTTPRequests` to be in the generated docs
- [ ] We need a symbol for `tf.io.browserFiles` to be in the generated docs
- [ ] We need symbols for any other exported functions from `tf.io` that a user can use.
- [ ] We need to document tf.IOHandler in the [tutorial/guide](https://github.com/tensorflow/tfjs-website/pull/240) and ideally in the API docs.

In order to achieve 4. @nsthorat suggests that we make IOHandler a class. This way we can add it to the docs and link it as a symbol for the return type of the provided io handlers. It also provides a place to put a bunch of docs about implementing IO handlers.

@caisq would you be able to work on this? Feel free to ping us on chat or in person.

**Comment by tafsiri** [comment]
Update, i just realized that some of these are done (1 and 2 above). 3 may also be done (not sure if there are any more). So its mainly the change from interface to class to help with making IOHandler linkable. Gonna update the title of this as well.

**Comment by tafsiri** [comment]
I'm also working on a guide version of how to make a custom IOHandler.

**Comment by anikulk** [comment]
Thanks @tafsiri Please let me know of any suitable tasks.

**Comment by tafsiri** [comment]
@anikulk any particular areas/types of task of interest? (e.g. documentation, examples, ml stuff, browser/web stuff...). I'll try and triage the issues for good starter ones.

**Comment by anikulk** [comment]
@tafsiri I am open to any suggestions and have experience and interest in ML but I think as a starting point documentation or examples would be better. appreciate your help.

**Comment by tafsiri** [comment]
@anikulk I tagged some issues with the [good first issues](https://github.com/tensorflow/tfjs/labels/good%20first%20issue) tag. Take a look at that and see if anything catches your eye (some are docs related others are core library functionality). If you find something that you are interested in feel free to make a comment in that issue that you want to work on it (feel free to tag me).

**Comment by tafsiri** [comment]
The custom IOHandler section of [this guide](https://www.tensorflow.org/js/guide/save_load) might be the easiest place to resolve this.

**Comment by rthadur** [comment]
Looks like this has been fixed [here](https://github.com/tensorflow/tfjs-website/pull/240) , so closing this issue.Thank you
