### ISSUE TITLE
calling js file into html problem (not getting any output)

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#121]
i have written a js code following:

import * as tf from '@tensorflow/tfjs';
function addition()
{
var a = parseInt(form.input1.value);
var b = parseInt(form.input2.value);
c = tf.constant(a,name="a")
d = tf.constant(b,name="b")
e = tf.add(c,d,name="e")
sess = tf.Session()
output = sess.run(e)
document.write(output);
sess.close()
document.write(output);
}
and i am calling this js like below below --
<script type="text/javascript" src="script2.js"></script> with addition function

input type="button" value="ADD" onclick="addition()"

I am not getting any output, please tell me how to fix this issue

**Comment by George35mk** [comment]
### Try this

`const output = this.model.predict(img) as any;`

`this.predictions = Array.from(output.dataSync());`

**Comment by tafsiri** [comment]
@kallols depending on how you set up your environment it may not be able to understand the 'import' statement (you probably want to use the script tag approach of loading the library). We just added a new example that I could point you to to use as a base https://github.com/tensorflow/tfjs-examples/tree/master/getting_started 

Try using the index.html and index.js as a guide (or just copy that project and put your code in) and it should work.

**Comment by George35mk** [comment]
@tafsiri can I ask you what version of tensorflow can I use this example because in typescript I get an error 

on VScode editor that 

```
[ts]
Argument of type '{ loss: string; optimizer: string; useBias: string; }' is not assignable
to parameter of type 'ModelCompileConfig'.
Object literal may only specify known properties, and 'useBias' does not exist in type
'ModelCompileConfig'.
```

**Comment by George35mk** [comment]
```
async function myFirstTfjs() {
  // Create a simple model.
  const model = tf.sequential();
  model.add(tf.layers.dense({units: 1, inputShape: [1]}));
  // Prepare the model for training: Specify the loss and the optimizer.
  model.compile({loss: 'meanSquaredError',
                 optimizer: 'sgd',
                 useBias: 'true'});     <====================== here
  // Generate some synthetic data for training. (y = 2x - 1)
  const xs = tf.tensor2d([-1, 0, 1, 2, 3, 4], [6, 1]);
  const ys = tf.tensor2d([-3, -1, 1, 3, 5, 7], [6, 1]);
  // Train the model using the data.
  await model.fit(xs, ys, {epochs: 250});
  // Use the model to do inference on a data point the model hasn't seen.
  // Perform within a tf.tidy block to perform cleanup on intermediate tensors.
  tf.tidy(() => {
    // Should print approximately 39.
    document.getElementById('micro_out_div').innerText += model.predict(
        tf.tensor2d([20], [1, 1]));
  });
  // Manually clean up the memory for these variables.
  xs.dispose();
  ys.dispose();
}
```

**Comment by tafsiri** [comment]
@George35mk that example loads a pre-built bundle, currently 0.7.0 see index.html `<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.7.0"> </script>` It is primarily geared towards javascript users. if you are using typescript I'd guess you would want to use it via npm to get the type definitions?

**Comment by George35mk** [comment]
@tafsiri Thank you, Yes i have installed the latest tensorflow.js via NPM
`"@tensorflow/tfjs@^0.8.0"` 
and again the `useBias` is missing from the `node_modules/@tensorflow/tfjs-layers/dist/engine/training.d.ts`

```typescript
export interface ModelCompileConfig {
    optimizer: string | Optimizer;
    loss: string | string[] | {
        [outputName: string]: string;
    };
    metrics?: string[] | {
        [outputName: string]: string;
    };
    useBias?: any; // added this line. to fix the missing useBias property.   <=====
}
```

**Comment by tafsiri** [comment]
@George35mk it might be best to file another issue to track this. Would you like to do that or I can copy your message to a new issue so that the right people can take a look.

**Comment by George35mk** [comment]
Yes @tafsiri if you can please copy the messafe is gonna be greate that. or i can do this tomorow.

**Comment by kallols** [comment]
Hi,
When I am calling this tiny javascript code below in my html code:
function go(){
    var array = new Array();
    document.write("hello");
}
its giving correct ans, but when I am including tensorflow its not giving any output like below:

**import * as tf from '@tensorflow/tfjs';**
function go(){
    var array = new Array();
    document.write("hello");
}

please tell me why am I not getting any output and how to solve the issue.

**Comment by kallols** [comment]
@nsthorat I have a very simple javascript file like this:
function go(){
a=tf.constant(7)
b=tf.constant(10)
c = tf.add(a,b)

simple_session = tf.Session()
value_of_c = simple_session.run(c)
simple_session.close()
document.write(value_of_c);
}

and I am including this particular js file into my html to display a simple addition output with the buttion click and my html script is 

```
`<html>
    <head>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.7.0"> </script>
    </head>
    <body>
        <input type="button" onclick="go()" value="Display JS Array"/>       
    </body>
     <script type="text/javascript" src="index.js"></script>
</html>`
```

But I am not getting the output, nothing is displaying the output should be 17 with the button click.
Please let me know where am I doing the mistake. Thanks.

**Comment by ManrajGrover** [comment]
@kallols Please check your console for errors and share them here. [Reference](https://developers.google.com/web/tools/chrome-devtools/console/)
