### ISSUE TITLE
Add deprecation warnings for methods that will be renamed or deleted in 1.0 on the 0.15.x branch.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1210]
Deprecated methods in Core:

- `Tensor.get` will now be `Tensor.array` with normal array indexing.
- `Tensor.buffer` will now be `Tensor.bufferSync`. `Tensor.buffer` will become async.
- `tf.fromPixels` => `tf.browser.fromPixels`
- `tf.toPixels` => `tf.browser.toPixels`

Deprecated methods in Layers:
- `tf.loadModel` => `tf.loadLayersModel`

Deprecated methods in Converter:
- `tf.loadFrozenModel` => `tf.loadWebSavedModel`

**Comment by dsmilkov** [comment]
All deprecating messages should be in place, but let me know otherwise.
