### ISSUE TITLE
[Feature] [Documentation] Add example on how to train a model with audio data using getUserMedia()

### ISSUE THREAD

**Issue by theunreal** [tensorflow/tfjs#122]
#### TensorFlow.js version
any
#### Browser version
any browser supports the [MediaStream API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API)

#### Describe the problem or feature request
It can be awesome to have a tutorial similar to the webcam-transfer-learning, just with audio coming using the browser MediaStream() API.

#### Code to reproduce the bug / link to feature request

```
navigator.mediaDevices.getUserMedia({audio: true})
      .then((stream) => {
        this.mediaRecorder = new MediaRecorder(stream);
        this.mediaRecorder.start();
        this.mediaRecorder.ondataavailable = function(e) {
           console.log(e.data); // I'd love to learn from a tutorial about how to use this data to feed and train TensorFlow Model to recognize audio
        };
      });
```

**Comment by nsthorat** [comment]
+1 this is a great idea.

The problem right now is that the spectrogram in the browser is ever so slightly different than the spectogram we get from TensorFlow.

The op that tensorflow uses is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/spectrogram.cc

Which comes from "fft2d". If somebody ports this to a GLSL shader or compiles it with WASM, the whole world of audio opens up to us.

**Comment by nsthorat** [comment]
This is fixed! See this example in models: https://github.com/tensorflow/tfjs-models/tree/master/speech-commands
