### ISSUE TITLE
.shape doesn't exist in the typescript d.ts for result of flatten()

### ISSUE THREAD

**Issue by quantuminformation** [tensorflow/tfjs#1225]
If I take the example from https://js.tensorflow.org/api/0.14.2/#layers.flatten

#### TensorFlow.js version
15.1
#### Browser version
Latest chrome
#### Describe the problem or feature request

We get this error:

<img width="834" alt="screen shot 2019-02-12 at 12 34 22" src="https://user-images.githubusercontent.com/216566/52635724-929ff380-2ec2-11e9-97b7-41668062a5f1.png">

**Comment by QuantumInformation** [comment]
I also found another d.ts one for the outputs prop:

<img width="1030" alt="screenshot 2019-02-15 at 09 36 59" src="https://user-images.githubusercontent.com/216566/52847879-50b2bf80-3105-11e9-8b65-ae29c0cbb6a7.png">

The d.ts files are autogenerated? If you want I can test the tf-core repo to see what it going on?

**Comment by QuantumInformation** [comment]
The error goes away if I import like this:
`var tf = require('@tensorflow/tfjs')`

vs `import * as tf from '@tensorflow/tfjs'`

Any reason why the `import as` syntax doesn't work?

<img width="437" alt="Screenshot 2019-06-14 at 17 16 43" src="https://user-images.githubusercontent.com/216566/59519477-37a9f780-8ec8-11e9-8dc7-13344b98c2a2.png">
