### ISSUE TITLE
Can't predict using loaded FrozenModel

### ISSUE THREAD

**Issue by leemengtaiwan** [tensorflow/tfjs#1235]
I encountered this error when trying to use my own FrozenModel to predict a dummy input.

#### TensorFlow.js version

I think it's `0.14.2` because I just simply run the setup command `yarn` indicated at [tfjs-examples/mobilenet/](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet) and check the content of newly created `node_modules/@tensorflow/tfjs/package.json`:

```json
{
  "name": "@tensorflow/tfjs",
  "version": "0.14.2",
```
#### Browser version

Google Chrome, version `71.0.3578.98`

#### Describe the problem or feature request

I used the [mobilenet](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet) example shown in [tfjs-examples](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet) repo and started the server by `yarn watch`.

Secondly, I loaded my own FrozenModel successfully.

But when I use the `predict` method of the loaded model with a input of correct shape, it shown the error below:

![image](https://user-images.githubusercontent.com/3454980/52726328-5968a000-2ff6-11e9-9107-489f76cccd44.png)

```text
ERROR: 0:163: 'updates' :  left of '[' is not of type array, matrix, or vecto
```

![image](https://user-images.githubusercontent.com/3454980/52726730-1a871a00-2ff7-11e9-91b8-792db9026778.png)

#### Code to reproduce the bug / link to feature request

I just slightly modified the original `index.js` in the [mobilenet example](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet) and the script look like this:

```javascript
import * as tf from '@tensorflow/tfjs';

const MODEL_URL = 'path_to_tensorflowjs_model.pb';
const WEIGHTS_URL = 'path_to_weights_manifest.json';

let gan;
const ganDemo = async () => {
  status('Loading model...');

  gan = await tf.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
  gan.predict(tf.zeros([1, 3, 450, 300])).dispose(); # error here

  ...
```

I had made sure the model was loaded successfully, and the shape of the input is correct (I intentionally tried other shape, and if the shape is not correct, it will throw another error)

Please help me solve the problem, really want to make my first tfjs project work.

**Comment by leemengtaiwan** [comment]
Updated: using the latest version of tfjs still produced the exact same error. 

No idea for debugging this.

**Comment by leemengtaiwan** [comment]
Hi there, what information can I provide to get any comments or suggestions? Really want to solve this issue and get the model to work.

**Comment by tafsiri** [comment]
@leemengtaiwan could you try this using version `0.14.1` of tensorflowjs and let us know if it works? There is a regression that we discovered between 0.14.1 and 0.14.2 that affects model loading/execution.

**Comment by dsmilkov** [comment]
Hi @leemengtaiwan ,

Can you share your model with us? Even though you've slightly modified the example, it looks like you are loading your own custom model (GAN architecture).

**Comment by leemengtaiwan** [comment]
@tafsiri thanks for the suggestion, I just tried `0.14.1` and got same error message. And actually I had also post this issue to [StackOverflow](https://stackoverflow.com/questions/54675163/cant-predict-using-loaded-frozenmodel) and @pyu10055 was suggesting me using other versions of tfjs like `latest`, `v0.15.1` and `v1.0.0-alpha2` but all of them produced the same error.

@dsmilkov yes of course. The model is quite big (600MB) and in order to save the bandwidth and easier debugging, I had made a Python HTTP server that can reproduce the error, you can check the repo below:

https://github.com/leemengtaiwan/tfjs-debug

Actually this tfjs FrozenModel was converted from a TensorFlow FrozenGraph, and which was converted from a ONNX model. If you need more information for solving the issue other than the tfjs model itself, please let me know.

**Comment by leemengtaiwan** [comment]
I understand that this is a tricky issue and you guys are busy, but just wondering how do you think about this issue? Can this be solved?

Also when will this issue be handled, for example, like after TensorFlow.js 1.0 release?

Thanks for all your time.

**Comment by pyu10055** [comment]
is this related to https://github.com/tensorflow/tfjs/issues/1355?
I have a fix addressing the strided_slice op, which on my machine the predict method completes in 1sec.

**Comment by leemengtaiwan** [comment]
@pyu10055
> I have a fix addressing the strided_slice op, which on my machine the predict method completes in 1sec.

Cool! how can I use the fixed code to solve #1355? or maybe we should discuss there?

And I think this is not related to #1355 because th model referenced there (built natively from tf graph) is not the same as the model specified here (converted from an ONNX model).

**Comment by dsmilkov** [comment]
Thanks for your patiance @leemengtaiwan and the invaluable feedback. I'm going to clone https://github.com/leemengtaiwan/tfjs-debug and investigate today.

In the meantime, what issues are you running when installing the 1.0 converter ?

**Comment by dsmilkov** [comment]
I got your example working. I just sent https://github.com/tensorflow/tfjs-core/pull/1632 to fix the shader compiler error.

Note that this fix is going into the 1.x (master) branch.

The best for you is to migrate your model to 1.x (which uses the JSON format). If you can't do that yet, you'll have to manually merge the changes in https://github.com/tensorflow/tfjs-core/pull/1632 (2 lines of code) and follow instructions in https://github.com/tensorflow/tfjs/issues/1355#issuecomment-473980497 for producing a custom build of tf.js.

**Comment by leemengtaiwan** [comment]
@dsmilkov thanks for your work!

Sorry for commenting on closed issue, one last thing to confirm.

I had successfully converted the pb model to json model using `pb2json_converter.js`:

```commandline
yarn ts-node tools/pb2json_converter.ts \
	.../tfjs-debug/web_model \
	.../tfjs-debug/json_model
```

And changed to 1.x compatible api call in `index.html` (using the latest tfjs version as before):
```javascript
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script>

...

const MODEL_URL = 'http://localhost:2345/json_model/model.json';
const model = await tf.loadGraphModel(MODEL_URL);
```

The error persist but I guess this will be solved as new patch released (which include #1632) just as you said? 

Just want to make sure I'm doing it correctly, thanks!

**Comment by dsmilkov** [comment]
No worries. Glad you were able to convert.  I'm uploading a custom tf.(min).js with the fix included, so you don't have to wait for the next release. Let me know if you run into other issues.

[tfjs-custom.zip](https://github.com/tensorflow/tfjs/files/2980961/tfjs-custom.zip)

**Comment by leemengtaiwan** [comment]
Thanks guy, you are the best!
