### ISSUE TITLE
Rename dataset.forEach() to dataset.each() to avoid confusion with Array.forEach()

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1236]
Rename `dataset.forEach()` to `dataset.forEachAsync()` to avoid confusion with `Array.forEach()` and confusing sync vs async iteration.

So we will have:
```js
await dataset.forEachAsync(elem => {
  console.log(elem);
});
```

Later when the async iteration proposal gets finalized: https://tc39.github.io/proposal-async-iteration/, we will support also:

```js
for await (const elem of dataset) {
  console.log(elem);
}
````

**Comment by dsmilkov** [comment]
cc @caisq @bileschi @nsthorat

**Comment by bileschi** [comment]
@davidsoergel

**Comment by bileschi** [comment]
@kangyizhang

**Comment by dsmilkov** [comment]
FYI, Once we release tfjs alpha 3, I'll update the boston-housing example and test it.

**Comment by dsmilkov** [comment]
We've decided on `forEachAsync()`.
