### ISSUE TITLE
Examples repository should have some integration tests

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1237]
With the growth in the number of examples, we should start to implement some unit tests. This is going to require some discussion for implementing a solution for Node.js and browser examples.

**Comment by caisq** [comment]
We've already started adding unit tests to some TF.js examples, e.g.,
https://github.com/tensorflow/tfjs-examples/blob/master/date-conversion-attention/model_test.js
https://github.com/tensorflow/tfjs-examples/blob/master/date-conversion-attention/date_format_test.js

These tests are currently run manually. But running them automatically with Travis or other testing infra and adding more tests will be valuable.

**Comment by gaikwadrahul8** [comment]
Hi, @nkreeger 

Apologize for the delayed response and I see in most of the tfjs-examples we have added unit tests for your reference I have added some references below and also we have updated our official documentation w.r.t tfjs-examples [here] (https://github.com/tensorflow/tfjs-examples), if have missed something here please let me know ? and if we already taken care of this issue could you please close this issue ? Thank you!

1. https://github.com/tensorflow/tfjs-examples/tree/master/abalone-node
2. https://github.com/tensorflow/tfjs-examples/tree/master/date-conversion-attention
3. https://github.com/tensorflow/tfjs-examples/tree/master/fashion-mnist-vae
4. https://github.com/tensorflow/tfjs-examples/tree/master/jena-weather
5. https://github.com/tensorflow/tfjs-examples/tree/master/lstm-text-generation
6. https://github.com/tensorflow/tfjs-examples/tree/master/mnist-acgan
7. https://github.com/tensorflow/tfjs-examples/tree/master/sentiment
8. https://github.com/tensorflow/tfjs-examples/tree/master/snake-dqn
