### ISSUE TITLE
Add tests for error detection in fitDataset() / standardizeDataIteratorOutput()

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1238]
fitDataset() expects a Dataset that produces elements of a certain shape, with matching batch sizes etc., and throws errors (from standardizeDataIteratorOutput()) when the conditions are not met.  These errors should be tested.

**Comment by hpandeycodeit** [comment]
@davidsoergel is this open to work on?

**Comment by davidsoergel** [comment]
@hpandeycodeit Yep, go for it!

**Comment by caisq** [comment]
cc @kangyizhang, who is working on some integration tests for `fitDataset()`. @hpandeycodeit and @kangyizhang might want to coordinate.

**Comment by ManishAradwad** [comment]
I'd love working on this issue. I'll need some help:
1. Which files should I edit / Where should I add test files?
2. Is there some reference test file to see how it's done?
Thanks!

**Comment by Sanket-Ghosh** [comment]
Hi. I would like to work on the issue and it would be my first open source contribution. I would like to know if I could start working.

**Comment by Sreejan100** [comment]
@caisq  I have created a pull request please look into it

**Comment by sourabh-choudhary0** [comment]
@caisq @Sreejan100 @davidsoergel Can I try working on this too? This will be my first open-source project So, I might need your guidance.

**Comment by sourabh-choudhary0** [comment]
@caisq @Sreejan100 @davidsoergel I have made the changes. Should I make a PR? It is failing on 51-32 test cases sometimes but other times it passing all of them.

**Comment by Sreejan100** [comment]
@caisq  please go over the pull request #5549

**Comment by Sreejan100** [comment]
@caisq  please review the pull request #5549

**Comment by Sreejan100** [comment]
@caisq  please go over the pull request #5549  and give comments if any changes are required

**Comment by pree-T** [comment]
I wanna work on this ..can someone help me?

**Comment by rubiagatra** [comment]
I think I want take a look @gaikwadrahul8, thank you for you PR referer
