### ISSUE TITLE
Add unit tests for tensor naming

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#124]
common.ts includes functionality for managing tensor names, such as `getUniqueTensorName(prefix)`;

This functionality should have unit tests.

**Comment by NahomAgidew** [comment]
@bileschi Is this issue still pending?

**Comment by bileschi** [comment]
Looks like `getUniqueTensorName` is covered, but `isValidTensorName` is not

**Comment by valishah** [comment]
Hi @bileschi : I see the test cases available for both `getUniqueTensorName` and `isValidTensorName`. Hope we can close this issue.

**Comment by bileschi** [comment]
You are right!  Closing.
