### ISSUE TITLE
Augment Dataset.size with Dataset.maxSize and Dataset.minSize

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1244]
If I have a dataset `ds` of unknown size, then `ds.take(100)` currently produces another dataset of unknown size-- but we could usefully track that the size is now *at most* 100 (and similarly throughout the size-propagation code).

**Comment by gaikwadrahul8** [comment]
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!
