### ISSUE TITLE
Stepping into source takes me to minified TensorFlow code

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs#1248]
I'm not having luck with sourcemaps here

https://github.com/QuantumInformation/tensorflowjs-playground/blob/master/api-examples/src/index.ts#L4

if I try to step into that line in the browser it takes me to minified code.

<img alt="screenshot 2019-02-14 at 08 55 05" width="1013" src="https://user-images.githubusercontent.com/216566/52774888-41b10c00-3036-11e9-8ea9-e8565cc7b68b.png">

However the sourcemaps files are present in the browser

Source maps should work with this webpack build

```var path = require('path')
var webpack = require('webpack')
var WebpackBuildNotifierPlugin = require('webpack-build-notifier')

const PATHS = {
  src: path.join(__dirname, './src'),
  dist: path.join(__dirname, './dist')
}

module.exports = {
  mode: 'development',
  entry: {
    app: PATHS.src + '/index.ts'
  },
  output: {
    path: PATHS.dist,
    filename: '[name].js'
  },
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript-loader'
      }
    ]
  },
  resolve: {
    // you can now require('file') instead of require('file.js')
    extensions: ['.ts', '.js']
  },
  plugins: [
    new WebpackBuildNotifierPlugin({
      title: 'My Project Webpack Build'
    }),
    new webpack.IgnorePlugin(/test\.ts$/)
  ]
}
```

**Comment by QuantumInformation** [comment]
any update?

**Comment by dsmilkov** [comment]
I think https://github.com/webpack-contrib/source-map-loader might help you here. According to their docs:

`"This loader is especially useful when using 3rd-party libraries having their own source maps."`

**Comment by dsmilkov** [comment]
Let me know if that helped

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by QuantumInformation** [comment]
If you use devTool : inline in webpacks its worked with every other project I've used. 

But thanks for that I'll try it out when I get back to it.
