### ISSUE TITLE
Documentation for tf.memory is missing numBytesInGPU

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1262]
https://js.tensorflow.org/api/latest/#memory

doesn't mention numBytesInGPU

**Comment by DCtheTall** [comment]
Hey all, is this issue still open? Are you accepting contributions for this?

**Comment by rthadur** [comment]
@DCtheTall i believe it is still open, feel free to send PR. Thank you

**Comment by DCtheTall** [comment]
Sg, I can open one in the next day or so. Just confirming my understanding from the code, `numBytesInGPU` represents how much memory TF.js is currently using in the GPU, not how much is still available?

**Comment by annxingyuan** [comment]
Hi @DCtheTall - yes `numBytesInGPU` represents memory usage on the GPU only, whereas `numBytes` represents memory usage across backends.
