### ISSUE TITLE
Remove texture dimensions from shader cache key - upload as uniforms instead

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1264]
This will enable shader program reuse and cut down on compilation time. This will especially benefit our text models e.g. https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

Apologize for the delayed response and I see we have updated TFJS API official documentation w.r.t memory management [here](https://js.tensorflow.org/api/latest/#Performance-Memory) and there is workaround to clear texture's, please refer this [comment](https://github.com/tensorflow/tfjs/issues/7589#issuecomment-1511744847) and If have I missed something here please let me know ? Thank you!
