### ISSUE TITLE
Add more CPU forwarding

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1265]
Add logic to more WebGL backend ops to forward to the CPU. Start with those ops involved with https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

Apologize for the delayed response and I see this PR [#1586](https://github.com/tensorflow/tfjs-core/pull/1586) got merged and as mentioned in the PR it will address partially this issue so May I know whether have we addressed this issue completely or not or still in progress ? Thank you!
