### ISSUE TITLE
Camera object tracking with tfjs

### ISSUE THREAD

**Issue by gearsmotion789** [tensorflow/tfjs#1268]
Hi,
I wanted to ask if there is a sample that uses node.js to do object tracking from a live camera with tfjs. I see there is an example that can do tracking for a single image from https://github.com/tensorflow/tfjs-examples/tree/master/simple-object-detection, but what's the code to do live camera tracking?

**Comment by tafsiri** [comment]
@gearsmotion789 there isn't a specific example we have for this (and I also assume you want to do this in the browser and not in node). And it would depend on the object you want to track. If you are looking for something that demonstrates using the webcam and passing the images through a model then https://github.com/tensorflow/tfjs-examples/tree/master/webcam-transfer-learning might be worth looking at, though no objects are 'tracked' by that model (look at webcam.js in that example). 

If you want to train something custom then https://github.com/tensorflow/tfjs-examples/tree/master/simple-object-detection might be a good place to start.

This is also a good question to ask on StackOverflow as you might get more responses from other people who might be attempting the same thing (e.g. there are face tracking libraries built on top of tensorflow.js). 

Hope this helps.
