### ISSUE TITLE
Incorrect results from conv2d with kernel size 1 

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1270]
#### TensorFlow.js version
0.15.2 (latest)

When the kernelSize for conv2d has a dimension of 1 (e.g., [1, 1] or [1, 2]), the result differs between Python TensorFlow and TensorFlow.js in the browser. 

Code to reproduce error:

```typescript
  // Reference Python code:
  // ```py
  // import numpy as np
  // import tensorflow as tf
  //
  // tf.enable_eager_execution()
  //
  // xs = np.array([
  //     10, 30, 50, 70, 20, 40, 60, 80, -10, -30, -50, -70,
  //     -20, -40, -60, -80], np.float32).reshape([1, 4, 4, 1])
  // kernel = np.array([1, 0.5, 1], np.float32).reshape([1, 1, 1, 3])
  //
  // strides = [2, 2]
  // ys = tf.nn.conv2d(xs, kernel, strides, 'SAME', data_format='NHWC')
  // print(ys)
  // ```
  fit('1x1 kernel', () => {
    const x4by4Data = [
        10, 30, 50, 70, 20, 40, 60, 80, -10, -30, -50, -70, -20, -40, -60, -80];    
    const x = tfc.tensor4d(x4by4Data, [1, 4, 4, 1]);
    const kernel1by1Data = [1, 0.5, 1];
    const kernel = tfc.tensor4d(kernel1by1Data, [1, 1, 1, 3]);
    // TODO(cais): Remove "control case" below.
    // const kernel1by1Data = [1, 0.5, 1, -1, 1, 0.5, 1, 0.5, 1, -1, 1, 0.5];
    // const kernel = tfc.tensor4d(kernel1by1Data, [2, 2, 1, 3]);
    const strides = [2, 2];
    const y = conv2d(x, kernel, strides, 'same', 'channelsLast');
    y.print();
  });
```

The result from the browser is:
[[[[40 , 20 , 40 ],
       [80 , 40 , 80 ]],

      [[-40, -20, -40],
       [-80, -40, -80]]]]'

while the result from TensorFlow (Python) is:
[[[[ 10.   5.  10.]
   [ 50.  25.  50.]]

  [[-10.  -5. -10.]
   [-50. -25. -50.]]]]

The results are the same if the dimensions of the kernel size are all greater than 1.

**Comment by caisq** [comment]
You may pull the code from my PR https://github.com/tensorflow/tfjs-layers/pull/471 to reproduce this issue.

**Comment by annxingyuan** [comment]
@dsmilkov @caisq just a note that this occurs on every tfjs backend and is not packing related.
