### ISSUE TITLE
Problems with deprecation warnings

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1276]
These warnings are good but there are two problems:

1. Chrome rarely combines them (see below where occasionally it indicates there were 2 instances)
2. The latest version of tfjs.js triggers the warning

Here's a sample:

![image](https://user-images.githubusercontent.com/2138696/53284380-7dfb0f80-378e-11e9-9fb2-6886bd7a28cb.png)

**Comment by dsmilkov** [comment]
Are you calling tf.fromPixels() directly in your code? Can you share a snippet of code that triggers that warning? Thanks!

Also, you can disable them by calling `tf.disableDeprecatingWarnings()`.

**Comment by ToonTalk** [comment]
In Chrome Dev Tools I did a search for tf.fromPixels and changed them all. But I just discovered I was using an older version of mobilenet (https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet) that had this line

e instanceof a.Tensor || (e = a.fromPixels(e));

so I missed this call.

So ignore my point #2 but why didn't Chrome combine all the warnings and just display the warning count? This is its usual behaviour and from my screenshot you can see it occasionally combined two warnings into one.

**Comment by dsmilkov** [comment]
Thanks for the investigatino! We will release new versions of our models (including mobilenet) in a couple days and that warning will go away when you switch to the latest mobilenet.

Regarding the combining of messages, just a wild guess, Chrome might decide not to combine if:
- they come from a different stack trace
- they come in another animation frame...
