### ISSUE TITLE
Update model.json when exporting models from Layers

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1285]
Add the following fields to model.json when exporting models in Layers:
- `format: string`. Currently, can be `layers-model` or `graph-model`.
- `generatedBy: string`. Will be used for debugging purposes when the (de)serialization fails.

Analogous issue for converter: https://github.com/tensorflow/tfjs/issues/1286

**Comment by caisq** [comment]
I'm going to add an additional field called convertedBy
