### ISSUE TITLE
Coco-SSD tensorflowjs_model.pb contains large embedded constants

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1289]
The Coco-SSD graph `tensorflowjs_model.pb` contains large embedded constants which makes the pb be `10 MB` (excluding the external weights).

When I converted the model to JSON, I manually removed all embedded float constants, and the model is still working (and is only 200KB in JSON size), which means that those constants are not used for inference.

We should investigate why those constants were not removed by grappler or the converter.

**Comment by nsthorat** [comment]
I would like to up the priority on the investigation of this issue. There are two issues:

1) Why do these unused weights show up in the model at all?
2) Why do we have any weights embedding in the model.json and not in the weights manifest / binary files.

Thanks @pyu10055!!

**Comment by pyu10055** [comment]
This model is converted with older pip, which has a bug that includes small constants in the pb file. Since I will reconvert this model with the 0.15.x again.

**Comment by nsthorat** [comment]
Can we convert this with 1.0? Let's stop developing against 0.15.x.

**Comment by dsmilkov** [comment]
Closing since this was been addressed in 1.x since we are pruning the graph
