### ISSUE TITLE
Simplify Python testing in tfjs-converter tool

### ISSUE THREAD

**Issue by manrajgrover** [tensorflow/tfjs#129]
If you would like to get help from the community, our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) might be a better fit.

#### TensorFlow.js version
0.8.0

#### Browser version
Chrome Version 65.0.3325.181 

#### Describe the problem or feature request
I feel following changes can be incorporated to improve Python testing:

1. Caching dependencies in travis can improve build times
2. Move linting to separate entry in travis matrix
3. Integrate Appveyor for testing the tool on Windows
4. Currently, we're making use of shell scripts which I feel can be replaced with [tox](https://tox.readthedocs.io/en/latest/) for easy testing

Opening an issue before working on it to discuss them. I can take this one up once finalized.

#### Code to reproduce the bug / link to feature request
None

**Comment by nsthorat** [comment]
I think you finished this, no? Please reopen if I am wrong.
