### ISSUE TITLE
Add WebGL for onesLike

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1293]
#### TensorFlow.js version
1.0.0-alpha3

**Comment by Lewuathe** [comment]
Do we need to do something more?
Since `onesLike` already uses `fill` kernel internally, it already uses the WebGL specific implementation. Is it necessary to add another kernel `onesLike`?

**Comment by nsthorat** [comment]
I don't think we need to do anything more, the fill kernel is fine as is.
