### ISSUE TITLE
Information on PoseNet accuracy across subgroups

### ISSUE THREAD

**Issue by kevinrobinson** [tensorflow/tfjs#1297]
Thanks for sharing this awesome work!  :)  TensorFlow.js opens up so many incredible applications of ML, and the API has and examples have been awesome for prototyping different uses within education, so thanks for all that it takes to do this work in the open. ❤️ 👍 

I'm looking at using PoseNet within a K12 educational setting, and wanted to first check that accuracy on different subgroups (eg, ages, skin colors, gender identity, wearing glasses).  I'm hoping to do this in the same kind of spirit as awesome Google work like [AI principles](https://ai.google/principles), [Responsible AI Practices](https://ai.google/education/responsible-ai-practices) and [Inclusive ML](https://cloud.google.com/inclusive-ml/), and to avoid creating an experience for K12 students similar to what's described in https://www.ajlunited.org/gender-shades.

I looked in a few places to try to learn more:
- readme: [https://github.com/tensorflow/tfjs-models/tree/master/posenet](https://github.com/tensorflow/tfjs-models/tree/master/posenet)
- blog post: [Real-time Human Pose Estimation in the Browser with TensorFlow.js](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5)
- [Towards Accurate Multi-person Pose Estimation in the Wild](https://arxiv.org/abs/1701.01779)
- [PersonLab: Person Pose Estimation and Instance Segmentation with a Bottom-Up, Part-Based, Geometric Embedding Model](https://arxiv.org/abs/1803.08225)
- [Microsoft COCO: Common Objects in Context](https://arxiv.org/pdf/1405.0312.pdf)

I also looked through the [code](https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/single_pose/decode_single_pose.ts) which is awesomely clear and well-described, and skimmed through a few pull requests too (eg, https://github.com/tensorflow/tfjs-models/pull/63).   These didn't quite help me answer what I was trying to figure out, but I'm not an expert in the evaluation of image recognition or pose estimation models, so I might just be missing this or not looking for the right language.  

From reading the blog post and code, it also seemed like this implementation is different enough that it'd be best to evaluate this end-to-end.  As I understand it, the overall accuracy will probably not be particularly high (since it's the mean of each keypoint's), and that parameters like MobileNet size or output stride or would impact this as well.  One way to get started looking at this might be by picking the default config and looking at the single-pose estimation on the nose only.  This could be useful both in answering my original question, but also as something that could help young people explore these kinds of questions themselves in educational settings, perhaps visually and experientially rather than quantitatively.  For example, a demo might show a photogrid like in https://www.ajlunited.org/gender-shades using PoseNet to overlay snapchat-style filters for glasses, wigs, etc. so it's visible if the filters don't fit different subgroups as well (skin color and gender in that case).  This would let young people ask questions about subgroup accuracy, or explore how this changes when different model sizes are used, etc.  If there are other datasets that would be better that you can point me to, especially ones that might be appropriate for testing how this model behaves on different age subgroups, that would be super helpful too.

Or if folks have looked at this in more sophisticated ways (eg, a public variant of the [what-if tool](https://pair-code.github.io/what-if-tool/) for this PoseNet), that would be amazing to learn more about too.  Thanks again for sharing this awesome work! 👍 

EDIT: more general questions about accuracy in: https://github.com/tensorflow/tfjs/issues/842, https://github.com/tensorflow/tfjs/issues/1137 and https://github.com/tensorflow/tfjs/issues/534

**Comment by kevinrobinson** [comment]
Hello @oveddan and @tylerzhu-github!  It seems like you have done the work here, based on the issue and commit history, so thanks for sharing this!  Perhaps you could share more about past work on these kinds of evaluation and accuracy questions?

To get started on this myself, I made something for young people or non-ML people to get an intuitive feel for this, and ask these kinds of questions themselves.  The code and a link to a demo is here if it's useful for anyone else: https://github.com/kevinrobinson/posenet-subgroups

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
