### ISSUE TITLE
Support exporting model weights from browser

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#13]

**Comment by zixia** [comment]
+1

**Comment by QuantumInformation** [comment]
No +1's please

**Comment by venkatesh-sakthivel** [comment]
+1

**Comment by kriptontr** [comment]
it'would be great if its allow distributed/collaborated learning somehow. isn't it?  or is it a completely different story

**Comment by thibo73800** [comment]
+1

**Comment by travisstaloch** [comment]
Will this also include exporting without the browser? I would like to be able to export a trained model to a file from node (after running model.fit(...)).

**Comment by nsthorat** [comment]
This issue specifically doesn't talk about it, but we will plan on supporting checkpointing to TensorFlow SavedModels in node.js.

**Comment by DakshMiglani** [comment]
any updates on this?

**Comment by broggi** [comment]
Looks like some progress in the last few days... You guys rock, looking forward to this! Is there an ETA? :)

**Comment by caisq** [comment]
@broggi, thanks for checking in

For basic features such as saving `tf.Model`s (Keras-style Models) to browser local storage or as downloaded files, we are looking at next couple of weeks as the ETA. For more advanced features, such as sending models to HTTP servers, the ETA will be longer. The support for saving non Keras-style models, e.g., `FrozenModel`s loaded from converted TensorFlow SavedModels, the ETA will be even longer.

**Comment by PheoOneWhoMade** [comment]
@caisq  so erm... how is the progress going?

**Comment by caisq** [comment]
@PheoOneWhoMade Apart from the comments in this issues, you can also look at the linked pull requests to see the progress as it happens.

**Comment by rajsite** [comment]
@caisq The formdata based browserHTTPRequest is interesting. It should be an efficient way of handling the browser weights as binary data.

Is having a JSON serialization format also being considered?

For example:
```javascript
{
    "model": MODEL_DATA_HERE,
    "model.weights.bin.base64": MODEL_WEIGHTS_AS_BASE64_ENCODED_STRING
} 
```

I think it's generally a lot easier to push around JSON (despite the inefficiencies of base64 encoding) and then migrate to a more performant approach when needing to optimize.

**Comment by atanasster** [comment]
@caisq thanks for considering adding more export/save options. 
in my use-case, the models are created from custom structures, however I would need to save the weights per layer when training, then later load the weights when creating each layer manually for predictions.
Is there some API for serializing/deserializing the weights or do I need to just do it manually?

**Comment by rajsite** [comment]
@caisq local storage before the user persists on the server over HTTP handles one use case.

The HTTP implementation in your fork would almost do it, but I would need to tweak some CORS configuration for the fetch. It might more flexible to take a Fetch Configuration object as a parameter and replace the body (then you also don't need to manually take a method).

Alternatively, for my specific use case, exposing the credentials property would probably be sufficient.

**Comment by caisq** [comment]
@rajsite I can make it possible to configure additional fields of the `RequestInit` used with the `fetch`, including `cache`, `credentials`, `headers` and `mode`. How does that sound?

**Comment by rajsite** [comment]
@caisq those should handle my current usage 👍
Also, being able to make my own IOHandler sounds like a good backup.

**Comment by traboukos** [comment]
@caisq I am trying to load a Keras model through node.js on the backend. I see that an IOHandler interface is present and it is used by the loadModel function. Is it currently possible to implement such an interface for use with node.js ? Should I give this a try or are other parts missing for this to work ? Is this functionality maybe going to be implemented on the tfjs-node repo ?

**Comment by nsthorat** [comment]
We're going to implement IOHandlers for writing to disk for tfjs-node very soon!

**Comment by caisq** [comment]
Update:
The model importing and exporting feature for the browser environment are launched with @tensorflow/tfjs release 0.11.1. Please see tutorial at:
https://js.tensorflow.org/tutorials/model-save-load.html

Please use the new API and let us know what you think. If you find bugs or have enhancement requests, please file GitHub issues.

I will leave this issue open for now because we plan to modify a few examples in https://github.com/tensorflow/tfjs-examples so they can save/load trained or fine-tuned models locally. 

The saving/loading support for TensorFlow.js in Node.js will be released later.

**Comment by caisq** [comment]
You can play with the runnable code snippets on our website to get a feeling of the new API:
https://js.tensorflow.org/api/latest/#loadModel

**Comment by caisq** [comment]
Now that a concrete example has been added to [the Iris example in tfjs-example](https://github.com/tensorflow/tfjs-examples/tree/master/iris), I will close this issue. I filed a separate issue to track the support of model saving and loading in Node.js:
https://github.com/tensorflow/tfjs/issues/343
