### ISSUE TITLE
Add constraints to tf.variable.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#130]
_From @nsthorat on February 22, 2018 14:26_

To mimic TensorFlow: 

https://www.tensorflow.org/api_docs/python/tf/Variable#constraint

_Copied from original issue: tensorflow/tfjs-core#768_

**Comment by nsthorat** [comment]
Since there is no pressing need for this I'm going to close it out.

**Comment by zaleslaw** [comment]
@nsthorat Does it mean, that constraints are loaded from Keras, but not applied to weights? I could not find the place in the tfjs code where constraints are used after variable updates
