### ISSUE TITLE
Doc: Add tfjs-node-specific functions to website

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1301]
#### TensorFlow.js version
tfjs-node 0.3.1

Node-specific functions are:
- `tf.node.summaryFileWriter()`
- `tf.node.tensorBoard()`

**Comment by tafsiri** [comment]
@caisq the new functions need @doc annotations to be rendered into the site. Going to assign this to you for now to add those docs and then you can reassign this back to me. Since these are new, you can choose the sections/subsections that you want!

**Comment by caisq** [comment]
This is fixed by https://github.com/tensorflow/tfjs-node/pull/214

**Comment by tafsiri** [comment]
FYI @caisq this can be done whenever a new node package is released that has the annotations.
