### ISSUE TITLE
Document the pb2json converter script.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1309]
There is no documentation for the pb2json converter script, it would be good to add this to the README of the tfjs-converter repository.

**Comment by nsthorat** [comment]
Also, we'll make sure to talk about this in the 1.0 release notes.

**Comment by leemengtaiwan** [comment]
After failing to install tfjs 1.0, I would like use this script to convert my pb file to json file (but have no idea how to use it)

It will be very helpful to include some guideline for non-NPM (e.g, Python) users to use the script :)

**Comment by nsthorat** [comment]
+1 -- @pyu10055 can you please prioritize this when you get some cycles?
