### ISSUE TITLE
Add examples to documentation of methods of tf.GraphModel

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1322]
tf.GraphModel methods are documented but have no runnable snippets.

Let's add some snippets.

**Comment by gaikwadrahul8** [comment]
Hi, @nsthorat 

Apologize for the delayed response and It seems like we have updated our official documentation for [tf.GraphModel](https://js.tensorflow.org/api/latest/#class:GraphModel) with runnable snippets and [implementation](https://github.com/tensorflow/tfjs/blob/tfjs-v4.2.0/tfjs-converter/src/executor/graph_model.ts#L42-L567), If have I missed something here please let me know ? Thank you!
