### ISSUE TITLE
Tensorflow.js error: unknown layer: GaussianNoise

### ISSUE THREAD

**Issue by josemafuen** [tensorflow/tfjs#1326]
I converted a pretrained keras model to use it with Tensorflow.js following the steps in [this guide](https://js.tensorflow.org/tutorials/import-keras.html)
Now, when I try to import it to javascript using
`const model = tf.loadModel("{% static "keras/model.json" %}");`
The following error shows up:
```
Uncaught (in promise) Error: Unknown layer: GaussianNoise. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with 
tf.serialization.registerClass().
    at new t (errors.ts:48)
    at deserializeKerasObject (generic_utils.ts:239)
    at deserialize (serialization.ts:31)
    at t.fromConfig (models.ts:940)
    at deserializeKerasObject (generic_utils.ts:274)
    at deserialize (serialization.ts:31)
    at models.ts:302
    at common.ts:14
    at Object.next (common.ts:14)
    at i (common.ts:14)
```
I'm using 0.15.3 version of Tensorflow.js, imported this way:
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.15.3/dist/tf.min.js"></script>`
I trained my neural network with Tensorflow 1.12.0 and Keras 2.2.4

**Comment by davidsoergel** [comment]
Indeed, looks like we don't have any of the noise layers yet (https://keras.io/layers/noise/).

**Comment by jofuelo** [comment]
Any clue about when will it be implemented?

**Comment by caisq** [comment]
This looks like an easy-enough layer that it'll be great if an open-source contributor can do it.

**Comment by arp95** [comment]
@caisq interested in this. Can you tell the starting point where I can start working on it?

**Comment by caisq** [comment]
@arp95 Thanks for offering to help. Please go for it :)

To get started, take a look at the Keras documentation of the GaussianNoise layer:
https://keras.io/layers/noise/

Also look at the Python implementation:
https://github.com/keras-team/keras/blob/master/keras/layers/noise.py#L14

To write the implementation in TypeScript (this tfjs-layers repo), create a file at src/layers/noise.ts. Follow the convention in files such as https://github.com/tensorflow/tfjs-layers/blob/master/src/layers/core.ts#L525

For this new layer, you need to define these methods at lease:
- constructor 
- `computeOutputShape()`, which will return the same as the input shape
- `call()`
- `getConfig()`
- also, don't forget to define `className` and call `serialization.registerClass()`

Thanks!

**Comment by WenheLI** [comment]
Is anyone still working on it? If no, I think I can help out. I have done some similar customized layer class before. It won't take long I believe

**Comment by caisq** [comment]
@arp95 are you still planning to work on this?

**Comment by WenheLI** [comment]
Hi, @caisq I have done a quick implementation for the GaussianNoise layer.  If it looks okay, I will implement the rest of the noise layer in the Keras and open a PR.

Thanks

```typescript
import {Layer, LayerArgs, SymbolicTensor} from '../engine/topology';
import {serialization, Tensor, tidy, util} from '@tensorflow/tfjs-core';
import {Kwargs} from '../types';
import {Shape} from '../keras_format/common';
import * as K from '../backend/tfjs_backend';

export class GaussianNoise extends Layer {

  static className = 'GaussianNoise';
  readonly stddev: number;

  constructor(stddev: number, args?: LayerArgs) {
    super(args || {});
    this.supportsMasking = true;
    this.stddev = stddev;
  }

  computeOutputShape(inputShape: Shape | Shape[]): Shape | Shape[] {
    return inputShape;
  }

  getConfig() {
    const baseConfig = super.getConfig();
    const config = {stddev: this.stddev};
    Object.assign(config, baseConfig);
    return config;
  }

  call(inputs: Tensor | Tensor[], kwargs: Kwargs): Tensor | Tensor[] {
    const noised = () => (inputs + K.randomNormal(inputs.shape, 0., this.stddev));
    return K.inTrainPhase(noised, inputs, kwargs.training || false);
  }
}
serialization.registerClass(GaussianNoise);

```

**Comment by WenheLI** [comment]
Hi, I have done an implementation about GaussianNoise and GaussianDropout here is my implementation https://github.com/WenheLI/tfjs-layers/commit/caeb9826cb713092c064ac82ec1e79ab9b1d53da.
If it looks fine, I think I can also take over the rest of the noise layer!

**Comment by caisq** [comment]
@arp95 didn't reply in 2 days. @WenheLI please feel free to take over. I saw your PR and will review it soon.

**Comment by rthadur** [comment]
referenced PR has been merged , so closing this issue, thank you all.
