### ISSUE TITLE
Using Body-pix as standalone es5 bundle is not working.

### ISSUE THREAD

**Issue by Akhiladdh** [tensorflow/tfjs#1329]
Link to JSbin.
https://jsbin.com/dokikopeko/edit?html,js,console,output

**Comment by davidsoergel** [comment]
There are at least two issues here:

 1. The [usage examples](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) mentions `body-pix@0.0.4`, but that version does not exist in npm.  The solution is to remove the version numbers for both tfjs and body-pix, or replace them both with `1.0.0` if you want to pin it.

 2. The image data in your example is subject to CORS restrictions.  Hosting the image file yourself, or grabbing an image from the webcam instead etc., should fix that.

**Comment by Akhiladdh** [comment]
Thanks @davidsoergel this fixed my issue.
