### ISSUE TITLE
Syntax Error on First Step of Tutorial

### ISSUE THREAD

**Issue by justingolden21** [tensorflow/tfjs#1333]
Hi, I was trying to follow the tutorial [here](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#1) however in step 1 I get:

```Uncaught SyntaxError: Unexpected token *``` in ```data.js:18```

Continuing the tutorial in [step 2](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#2), I get:

```Uncaught SyntaxError: Unexpected token {``` in ```scripts.js:1```

This is probably because the import/export syntax isn't available on my end, however I've followed the instructions completly. I can presume that this would also turn off anybody else trying to follow the tutorial when none of the code works because of invalid import/export syntax. 

I've got the newest versions of Chrome and Firefox, and in Firefox I get:

```SyntaxError: import declarations may only appear at top level of a module``` instead for both files.

I've looked at the [syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and the [support](https://stackoverflow.com/questions/33516906/which-browsers-support-import-and-export-syntax-for-ecmascript-6) for this and don't see why this code would cause any problems.

Thank you for looking into this issue.

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by justingolden21** [comment]
StackOverflow won't allow me to ask questions, and typically when I could ask questions I am downvoted into losing more "privileges" and provided with only incorrect or completely inapplicable answers. I asked on GitHub because I was hoping to have a different result from this community. Although it is not quite a bug, it is a problem with something made by TensorFlow that should be fixed, for the health of the TensorFlow community.

**Comment by davidsoergel** [comment]
No worries-- this is a real bug.  It has to do with the fact that the provided data.js is an ES6 Module, not a plain JS script.

Here's a quick workaround while we figure out the best way to address this:

 * In your data.ts, delete or comment out the `import * as tf...` line.
 * Also delete the word `export` on line 40, so it just reads `class MnistData {`
 * Similarly, remove the import line in script.js in step 3.

**Comment by tafsiri** [comment]
Hi @justingolden21 thanks for reporting this! It is a bug. I have updated the tutorial with the fix. There was a missing `type=module` attribute on the script tags, and I updated the link to a data file that doesn't have the import statement. It should work now in recent Chrome and Firefox versions. Let me know if you have any trouble with this.

**Comment by davidsoergel** [comment]
@tafsiri I had tried that but it also didn't work, because CORS kicks in and prevents loading the module from a `file://` URL (which it is if you follow the tutorial instructions and load these files from a local directory).  Apparently `type=module` makes the rules more strict.

**Comment by tafsiri** [comment]
@davidsoergel I also updated the tutorial with some instructions to work around the CORS issues (depends on the browser though)

**Comment by davidsoergel** [comment]
+1 cool, thanks!

**Comment by justingolden21** [comment]
Great, thank you guys for working on this issue and being so responsive.

I've followed the instructions and got the hello world after step 2 in the console (Firefox only, Chrome doesn't allow it due to CORS policy).

However, once I finished step three, I got <code>TypeError: tf.browser is undefined</code> at <code> script.js:25:5</code>:

![image](https://user-images.githubusercontent.com/30274440/54064370-7e50cd00-41c8-11e9-84f3-ff00a0de340d.png)

Thank you again for your hard work on this issue.

**Comment by tafsiri** [comment]
@justingolden21 thanks for the update. I think a few things got mixed up with the releases of the new versions. I'm going to take a look at the whole thing.

**Comment by tafsiri** [comment]
@justingolden21 I've updated the tutorials, they were indeed not pointing to the latest release. Sorry for all the trouble, i've gone through them step by step so they should be working. Let me know if you have more trouble. Thanks again for letting us know.

**Comment by justingolden21** [comment]
Works beautifully in firefox now, thank you for your hard work.

**Comment by tafsiri** [comment]
Thanks @justingolden21 for your patience!
