### ISSUE TITLE
tensorflowjs pip package

### ISSUE THREAD

**Issue by startupgurukul** [tensorflow/tfjs#1338]
Hi folks congrats on 1.0 release, definitely an exciting moment in ML history :)

The converter package seems to point to 0.8.0. If the latest version can be published to pip, that would be great. 

PS: tensorflowjs_converter generated from python code in the repo works fine (after running yarn/npm run gen-json

**Comment by Johannes0Horn** [comment]
I am also looking for the 1.0 pip package. Which is the straight forward way to build it from source? Should one use the 'build-pip-package.sh' inside '.../tfjs-converter-master/python'?

**Comment by startupgurukul** [comment]
Clone the latest  tfjs-converter
Do yarn/npm run gen-json
cd python
python setup.py install

**Comment by Johannes0Horn** [comment]
Thank you for saving me some time@startupgurukul! It worked for me.

**Comment by apkuhar** [comment]
use the v1.0.0 tag if you want to do the manual install. the current latest is using TF 2.0 allready.

**Comment by pyu10055** [comment]
tensorflowjs-converter pip v1.0.1 is published.
