### ISSUE TITLE
tf_frozen_model to tfjs_layers_model

### ISSUE THREAD

**Issue by Scooling** [tensorflow/tfjs#1343]
Dear developer, my current --input_format is tf_frozen_model, and I want --output_format to be tfjs_layers_model. What do I need to do to achieve this goal?

**Comment by caisq** [comment]
@Scooling Converting model from tf_frozen_model to tfjs_layers_model is not currently supported. To get a tfjs_layes_model, you can either convert it from keras or tf.keras or (`--input_format keras`) or save a model from TensorFlow.js directly (`tf.LayersModel.save()`)

**Comment by caisq** [comment]
cc @pyu10055
