### ISSUE TITLE
.yalc directory published to npm

### ISSUE THREAD

**Issue by mhart** [tensorflow/tfjs#1344]
The `.yalc` directory has been published to npm and it takes up 60% of the `tfjs` module disk space.

I believe I've seen this with `tfjs-core` in the past too – I suspect it should be added to `.npmignore` in all tfjs projects.

#### TensorFlow.js version

1.0.0

#### Code to reproduce the bug / link to feature request

```console
$ npm install @tensorflow/tfjs@1.0.0
$ du -k node_modules | sort -n | tail -10
9176	node_modules/@tensorflow/tfjs/dist
16772	node_modules/@tensorflow/tfjs/.yalc/@tensorflow/tfjs-core/dist
16792	node_modules/@tensorflow/tfjs-core/dist
16796	node_modules/@tensorflow/tfjs/.yalc
16796	node_modules/@tensorflow/tfjs/.yalc/@tensorflow
16796	node_modules/@tensorflow/tfjs/.yalc/@tensorflow/tfjs-core
16812	node_modules/@tensorflow/tfjs-core
26000	node_modules/@tensorflow/tfjs
55332	node_modules/@tensorflow
56732	node_modules
```

**Comment by nsthorat** [comment]
Agreed -- I will fix this.

**Comment by dsmilkov** [comment]
An idea: we publish a tiny package tfjs-repo-check that makes sure the `tslint.json`, `.npmignore`, `.gitignore` etc are consistent across our repos. All repos depend on that package as a dev dependency, and run it on every presubmit.

**Comment by nsthorat** [comment]
+1 this is a great idea. I think we can put the script in tfjs-core since all the repos depend on it rather than making a separate repo.
