### ISSUE TITLE
No backend found in registry in react native

### ISSUE THREAD

**Issue by WenheLI** [tensorflow/tfjs#1346]
#### TensorFlow.js version
1.0.0
#### Browser version
React: 16.5.0
React native: sdk-32.0.0
expo: 32.0.0
#### Describe the problem or feature request
I was trying to import tfjs into React Native, when I want to call tf methods, it goes with an error `Error: No backend found in registry.`. I also tried it under production mode it is the same.
#### Code to reproduce the bug / link to feature request
```javascript

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as tf from '@tensorflow/tfjs';


export default class App extends React.Component {
  render() {
    console.log(tf);
    let t = tf.tensor([1, 2, 3, 4]).shape;
    return (
      <View style={styles.container}>
      <Text>{t}</Text>
      </View> 
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by WenheLI** [comment]
Just an update about this issue. I was trying to find out what makes the registration process failed. And found out a set of warning showing in the console:
<img width="424" alt="warning" src="https://user-images.githubusercontent.com/23213772/54658875-67da2980-4a84-11e9-88ab-df507a98e23f.png">
As it suggests that the react native environment does not have any ``webgl`` support to start the GPU backend and does not have the`` document`` to support the cpu. It seems to be a problem with the unique environment of react native.

While given this warning, I am thinking of is it possible to directly call tfjs method? Since what react native is doing is to translate the js code to native code and operate the native components. That means these JS/browser like methods are not really happened in the browser environment. Will the tfjs work in this environment? 

From my perspective, to let the tfjs work with react native we should use Tensorflow Lite and build a wrapper for tfjs to translate the tfjs methods to Tensorflow Lite methods.

**Comment by nkreeger** [comment]
We don't fully support React Native - it is something we have on our roadmap but we haven't had a chance to figure out how to do this correctly.

**Comment by Ivikassingh** [comment]
This is all due to WebGL not present in your testing device
