### ISSUE TITLE
tf.sequential is not a function

### ISSUE THREAD

**Issue by JimTheMan** [tensorflow/tfjs#1351]
I am trying to follow the tensorFlow.js guide here: https://www.tensorflow.org/js/guide/models_and_layers

I installed TensorFlowjs, and my node dependencies in package.json looks like this:

```
"dependencies": {
    "@babel/preset-es2017": "^7.0.0-beta.53",
    "@tensorflow/tfjs": "^0.15.3",
    "@tensorflow/tfjs-node": "^0.3.1",
    "asyncawait": "^1.0.8",
    "babel-preset-env": "^7.0.0-beta.3",
    "install": "^0.12.2",
    "tnpm": "^1.0.6"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.3.4",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2017": "^6.24.1",
    "webpack": "^3.12.0"
  }
```

In my code I have these two lines:

```
import * as tf from '@tensorflow/tfjs';
const model = tf.sequential();
```

I run then run it like this:
```
node --experimental-modules ./src/basic-tf.mjs
```

But I get the error:
```
TypeError: tf.sequential is not a function
```

node v10.15.1
nom v6.4.1

What am I doing wrong here? Thanks!

**Comment by caisq** [comment]
@JimTheMan 

The ECMAScript import syntax in your JavaScript code snippet probably won't work with vanilla node. You should try either ts-node (https://www.npmjs.com/package/ts-node) or using the `require()` syntax:

```js
const tf = require('@tensorflow/tfjs-node');
```

**Comment by JimTheMan** [comment]
Thanks @caisq, it works when I switch from using `import` to `require`. I guess it kind of should have been obvious for me to try the require syntax, but it doesn't mention that anywhere in that docs (that I know of). It would be nice to have clearer docs for all favors of javascript. :)

**Comment by caisq** [comment]
@JimTheMan You are right, we currently have essentially no code example for tfjs-node on our website (js.tensorflow.org). However, we do have some examples in our tfjs-examples repo, e.g.,
- https://github.com/tensorflow/tfjs-examples/blob/master/mnist-node/main.js#L18
- https://github.com/tensorflow/tfjs-examples/blob/master/simple-object-detection/train.js#L23
- https://github.com/tensorflow/tfjs-examples/blob/master/mnist-acgan/gan.js
