### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [tensorflow/tfjs#1354]
I'd like to talk about WebGPU in tfjs.
Currently, Tensorflow.JS is only based on WebGL. 
I am curious whether Tensorflow.JS([node-gpu)](https://github.com/tensorflow/tfjs-node) has a plan to support WebGPU in the future. 
According to Webgpu proposal with new shading language thanks to WebAssembly and directly accessing API, they will outperform WebGL which is indirect api causing less performance than direct one like Native stuff. 
So, Why would not take advantage of this new advanced technology in the near future ?

**[W3C WebGPU proposal](https://gpuweb.github.io/admin/cg-charter.html)**

**Comment by nsthorat** [comment]
We will be certainly be writing a WebGPU backend as soon as it's available -- we are in close contact with the Chrome folks who are implementing it.

Closing this out since we will track this elsewhere.
