### ISSUE TITLE
website link 404

### ISSUE THREAD

**Issue by chenqing** [tensorflow/tfjs#1358]
https://www.tensorflow.org/js/tutorials/transfer/what-is-transfer-learning   in https://www.tensorflow.org/js/, it's broken.
this is the right one :
https://www.tensorflow.org/js/tutorials/transfer/what_is_transfer_learning

![image](https://user-images.githubusercontent.com/3064613/54170917-8b650900-44b3-11e9-943c-70cf17e3612f.png)

**Comment by chenqing** [comment]
![image](https://user-images.githubusercontent.com/3064613/54170906-79836600-44b3-11e9-95fb-8ff03f0900e6.png)

**Comment by bileschi** [comment]
Thanks for the bug report!  I am able to reproduce the 404

**Comment by tafsiri** [comment]
I believe this has been fixed. Thanks for reporting!
