### ISSUE TITLE
Support stft and inverse stft ops.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1362]
See:

https://www.tensorflow.org/api_docs/python/tf/signal/stft
https://www.tensorflow.org/api_docs/python/tf/signal/inverse_stft

**Comment by Lewuathe** [comment]
I tried to implement this and found we first need to implement window functions like hann or hamming. I'll work on them first.

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/signal/hann_window
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/signal/hamming_window

**Comment by Gurpreetsingh9465** [comment]
@Lewuathe can we work together in this module and add support to more ops as mentioned in [tf.signals](https://www.tensorflow.org/api_docs/python/tf/signal) similar PR did to tensorflow/tensorflow#27075

**Comment by Lewuathe** [comment]
Thanks! I think you can add necessary ops in tf.signal. Some other ops like fft are still in `spectral_ops.ts`, though.

**Comment by Gurpreetsingh9465** [comment]
thanks!
I would like to implement.
1. fftfreq
2. rfftfreq
3. fftshift(required tf.roll)
4. ifftshift(required tf.roll)

reference [np.fft](https://docs.scipy.org/doc/numpy/reference/routines.fft.html#helper-routines)

**Comment by nsthorat** [comment]
@Gurpreetsingh9465 since those don't exist in TensorFlow we probably won't implement them in TensorFlow.js for now.

**Comment by Gurpreetsingh9465** [comment]
@nsthorat can i work on [dct](https://www.tensorflow.org/api_docs/python/tf/signal/dct) and [idct](https://www.tensorflow.org/api_docs/python/tf/signal/idct)

**Comment by nsthorat** [comment]
Great! Just curious if you have a concrete use case for those ops?

**Comment by Gurpreetsingh9465** [comment]
I am not sure about that but i think discrete cosine transform converts one function into sum of cosine functions of different amplitude which can be used to compress mp3 or image files.

**Comment by nsthorat** [comment]
For now let's try to keep it to the ops we have a concrete use case (one that someone wants to build), otherwise we bloat the bundle size without a real need for the op :)

**Comment by Gurpreetsingh9465** [comment]
Ok @nsthorat :smiley:

**Comment by ClaraJacintho** [comment]
Hey, any updates on the inverse FFT? Is anyone working on it? I am working on a project that needs it, and I would be willing to help implement it if necessary!

**Comment by rthadur** [comment]
@ClaraJacintho no one is working on it at this point , feel free to submit a PR. Thank you
cc @dsmilkov

**Comment by gaikwadrahul8** [comment]
Hi, @ClaraJacintho 

Apologize for the delayed response and I see we have implemented [tf.signal.stft](https://js.tensorflow.org/api/4.4.0/#signal.stft) and it seems like we haven't implemented `tf.signal.inverse_stft` so still you're looking to implement `tf.signal.inverse_stft`  feature please ? Thank you!

**Comment by StiliyanKushev** [comment]
Bump. People are still looking for an official implementation of `tf.signal.inverse_stft`.

**Comment by matbee-eth** [comment]
Would be nice, I've tried to do it myself but it doesnt quite work :)
