### ISSUE TITLE
Mobilenet: different results when WEBGL_PACK is true or false

### ISSUE THREAD

**Issue by GreyZzzzzzXh** [tensorflow/tfjs#1363]
#### TensorFlow.js version
tfjs: "1.0.0"

#### Browser version
Chrome 70.0.3538.77 64-bit

#### Describe the problem or feature request
WEBGL_PACK is true:
https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html
![image](https://user-images.githubusercontent.com/35633199/54212212-8f2d7580-451d-11e9-89ce-cd4bd1aa517a.png)

WEBGL_PACK is false:
https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html?tfjsflags=WEBGL_PACK:false
![image](https://user-images.githubusercontent.com/35633199/54212297-acfada80-451d-11e9-868f-276f0a2f8012.png)

**Comment by nsthorat** [comment]
This should be fixed & will go out in the 1.0.1 patch release.

**Comment by bileschi** [comment]
This appears to be resolved, given that both have the same results now.  Curious that the new result is different from both previous results.  @nsthorat is this expected?

**Comment by nsthorat** [comment]
This fixed the issue: https://github.com/tensorflow/tfjs-core/pull/1610

We should update the example to 1.0.1 and this should go away.

**Comment by juliiami** [comment]
Is it correct that this example is not updated to a new version of tfjs? Because the results are still different for these two links.
