### ISSUE TITLE
tensorflow custom model : “Giving wrong prediction with bulk data”

### ISSUE THREAD

**Issue by a4ankit** [tensorflow/tfjs#1365]
We are facing an issue here, while training with the bulk dataset and use that custom model for prediction it giving the wrong prediction. Most of the time it gives the second index value.

Setting Label:

    let label = [];
    for(var k = 0; k< 21; k++){
        label.push('Store Shelf');
    }
    for(var l = 0; l< 21; l++){
        label.push('Rejected');
    }
    console.log('label:::'+label);
    const setLabel = Array.from(new Set(label));
    console.log('model1',model);
    let prediction =  await model.predict(tensor);
    console.log('prediction:::'+ prediction);
    pred = prediction.argMax(1).dataSync(); 
    const labelsPred = Array.from(pred).map(e => setLabel[e]);
    console.log('labelsPred:::'+ labelsPred);
    let top5 = Array.from(prediction)
    .map(function(p,i){
        return {
            probability: p,
            className: prediction[i]
        };
    }).sort(function(a,b){
        return b.probability-a.probability;
    }).slice(0,1);

    $("#prediction-list").empty();
    //top5.forEach(function(p){
    $("#prediction-list").append(labelsPred);
    //});
Here we have two labels 'Store Shelf' and 'Reject' but it gives us 'Rejected' for all kind of images that we pass with bulk data(trained with 40 images).

Please guide what I'm doing wrong here, or how can I achieve correct prediction with bulk dataset after loading saved model.

**Comment by nsthorat** [comment]
This seems like an issue with your model setup rather than an issue with the library. You will probably get more luck solving this kind of issue on stackoverflow.com with the "tensorflow.js" tag.
