### ISSUE TITLE
Ship Raspberry Pi (arm7) TensorFlow 1.13 builds

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1370]
I don't want to block a 1.0.x version of @tensorflow/tfjs-node on some Docker/Bazel issues with getting an official RPi build out for 1.13. This issue will track this work for a followup point release.

**Comment by sirShakir** [comment]
Any update on how to install tfjs on raspberry pi?

**Comment by TechnoDezi** [comment]
Hi

I managed to get tfjs-node running on a raspberry pi 4. You can check out my blog post: [https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs](https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs)

It's running a little slow, but at least it's running. It all comes down to getting the build from source correct. If you still battling I am willing to assist.

**Comment by EddieOne** [comment]
@TechnoDezi What was the secret to make it work?

I see there is mention of this command. ` npm rebuild @tensorflow/tfjs-node --build-from-source`

but I get ` UnhandledPromiseRejectionWarning: Error: Unsupported system: cpu-linux-arm`

Maybe because I'm using a raspbery pi 3

**Comment by bonkzero404** [comment]
> @TechnoDezi What was the secret to make it work?
> 
> I see there is mention of this command. ` npm rebuild @tensorflow/tfjs-node --build-from-source`
> 
> but I get ` UnhandledPromiseRejectionWarning: Error: Unsupported system: cpu-linux-arm`
> 
> Maybe because I'm using a raspbery pi 3

No, i'm using RPI4 but it still has an error

**Comment by memolipd** [comment]
I still cannot install the node bindings on my RPI3

`root@raspberrypi:/home/pi/otto-os# npm rebuild @tensorflow/tfjs-node --build-from-source
npm ERR! code 1
npm ERR! path /home/pi/otto-os/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.6.1.tar.gz
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@15.14.0 | linux | arm
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info build requesting source compile
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | linux | arm
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | linux | arm
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3`

**Comment by shkr** [comment]
Commenting here, to increase priority

**Comment by shkr** [comment]
The doc instructions don't work, unable to build tfjs using bazel on ubuntu 20.04 that is running on my raspberry pi 4.

**Comment by rthadur** [comment]
Support for Rasberry Pi has been implemented here https://github.com/tensorflow/tfjs/pull/6564 , please check out next release for changes.
