### ISSUE TITLE
loadLayersModel is blocking the UI?

### ISSUE THREAD

**Issue by emer7** [tensorflow/tfjs#1373]
#### TensorFlow.js version
0.15.3

#### Browser version
Chrome 72.0.3626.121

#### Describe the problem or feature request
UI is blocked (cannot click on anything) while loadLayersModel is executing despite wrapper in await

#### Code to reproduce the bug / link to feature request
nsfwjs.com

**Comment by caisq** [comment]
@emer7 Thanks for filing the issue. Can you tell us about the model you are loading, like what its size is, how many layers it consists of.

**Comment by GantMan** [comment]
@emer7, it's an Inception v3  + a few more layers after flattening.  Quantized at 24meg model.

**Comment by GantMan** [comment]
The full source of the model is available here: https://github.com/GantMan/nsfw_model

**Comment by danieldaeschle** [comment]
Any update?
