### ISSUE TITLE
Add tf.strided_slice op

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#138]
_From @pyu10055 on March 13, 2018 22:43_

I have noticed many estimators are generating this op.
https://www.tensorflow.org/versions/master/api_docs/python/tf/strided_slice

_Copied from original issue: tensorflow/tfjs-core#851_

**Comment by nsthorat** [comment]
This is the most common missing op I've seen, let's prioritize this.

**Comment by pyu10055** [comment]
the op has been added https://github.com/tensorflow/tfjs-converter/pull/135
