### ISSUE TITLE
Doc generator not expanding ts types in param lists

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1383]
#### TensorFlow.js version
tfjs-vis 1.0.2

#### Describe the problem or feature request
Not sure where we left this off, but should the doc generator expand `type`s? See HistogramOpts in screenshot below. 

<img width="803" alt="Screen Shot 2019-03-14 at 11 47 51 AM" src="https://user-images.githubusercontent.com/26408/54371201-61484e00-464f-11e9-86bd-704fc220a670.png">

#### Code to reproduce the bug / link to feature request
See https://js.tensorflow.org/api_vis/latest/#render.histogram, the type is defined https://github.com/tensorflow/tfjs-vis/blob/v1.0.2/src/types.ts#L127 

Is the fix to change this to an interface?

**Comment by nsthorat** [comment]
Currently we don't automatically unpack types. You can use one of the following right now if you want to fix this:

Just take the type and put the string value in the docs:
```
@docinline
type blah = TypedArray|Array;
```

Alias the type as something else:
```
@docalias Array
type blah = TypedArray|Array;
```

**Comment by tafsiri** [comment]
closed via https://github.com/tensorflow/tfjs-website/pull/291
