### ISSUE TITLE
84.5% Unused bytes with pre-trained model

### ISSUE THREAD

**Issue by robertmarshii** [tensorflow/tfjs#1386]
Is there a TFJS library that I can use for pre-trained model use only?

Trying to reduce the overheads on the client side.

**Comment by bileschi** [comment]
Is this about the bundle size of TFJS itself?

**Comment by robertmarshii** [comment]
That is correct. I have attempted to remove the training/etc code, but once minified the size is only slightly smaller than the official bundle.

**Comment by bileschi** [comment]
Sounds like this is related to the request for tree-shaking.  Is that the case?
https://github.com/tensorflow/tfjs/issues/353

**Comment by robertmarshii** [comment]
That correct Bileschi. However, I am not restricted by any third-party size, this is purely motivated by improving loading speeds for clients in the browser. Does a tf-lite version exist for javascript?

**Comment by bileschi** [comment]
Unfortunately we do not have a deployable bundle with reduced functionality, unless you are able to use just tfjs-core, as you mentioned in #353.  Still, there is likely to be much in core that you are not using.  Ideally we would like to be able to prune the bundle to just the functionality used by the application.  At this point we do not have a general solution pattern to this problem.  Your comments and "me too" applied to the other bug will help us to justify resourcing this problem over and above other priorities.

**Comment by davidsoergel** [comment]
Closing as dup of #353.
