### ISSUE TITLE
Remove usage of `import xxx from '@tensorflow/tfjs-core/dist/xxx';` in tfjs-data

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1391]
Currently some un-exported data types are being used in tfjs-data through `import xxx from '@tensorflow/tfjs-core/dist/xxx';`. Such as https://github.com/tensorflow/tfjs-data/blob/70541295906315d0e74ff7de0d07d87991fc9f6c/src/util/deep_map.ts#L20

This kind of import should be replaced by regular export in `tfjs-cored` and using `import xxx from '@tensorflow/tfjs-core'` in tfjs-data.

**Comment by kangyizhang** [comment]
cc @pyu10055 @davidsoergel @dsmilkov

**Comment by dsmilkov** [comment]
Thanks for taking this on! If some of the types are not exported by core, feel free to send a PR on core.
