### ISSUE TITLE
coco-ssd: using a custom base

### ISSUE THREAD

**Issue by m4nuC** [tensorflow/tfjs#1394]
Coco-ssd API allow to select a base for the classification model. https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd

Is there support plan for using custom classifier ?

If not, would it make sense to work on this ? I am happy to contribute.

Thanks

**Comment by pyu10055** [comment]
No plan for supporting custom classifier at this moment. 
Since the model has some post processing done in javascript, the custom classifier would need to have similar model topology. 
Do you have any custom classifiers you are planning to use?

**Comment by m4nuC** [comment]
I am planing on using a pre-trained mobile net but retrained with a different set of classes. 

What type of preprocessing would be needed ? For my use case it's OK to use javascript to do the pre processing.

**Comment by m4nuC** [comment]
@pyu10055 Does my answer helps ? It seems it would be a common use case. I am happy to work on this if needed.

**Comment by pyu10055** [comment]
@m4nuC reviving the thread, thank you for the interest for supporting custom classifier. I think it is a great idea, I noticed a lot of interests in ssd model, and people are struggling with how to get the model converted and create the optimized solution similar to our coco-ssd repo. 
It would be very useful to setup a easier process (a script or similar) to help people get the model converted properly and use the coco-ssd model repo for inference.
If you are interested in contributing, we can discuss more. thanks.

**Comment by m4nuC** [comment]
Hi @pyu10055,  yes I am interested in helping out. Let's discuss the details anytime

**Comment by pyu10055** [comment]
@m4nuC current coco-ssd has a model config object
```
export interface ModelConfig {
  base?: ObjectDetectionBaseModel;
  modelUrl?: string;
}

cocoSsd.load(config: ModelConfig = {});
```

We should probably add a custom model type to the base enum, and use the modelUrl to load the model. 
We will also need the user to provide the classes following this interface:
```
export interface ObjectDetectionClass {
  name: string;
  id: number;
  displayName: string;
}
```

If you are interested, you can send a PR and I am happy to review it. thanks.
