### ISSUE TITLE
How to make localhost:1234 running on my own computer work on my colleague's machine

### ISSUE THREAD

**Issue by Scooling** [tensorflow/tfjs#1397]
Dear developer:
Now i can run postnet  code in my own computer ,but when i give the http://ip:1234 to my colleague,they can access the web,but show "this browser does not support video capture,or this device does not have a camera" .what should i do?

**Comment by alex77t** [comment]
the easiest way probably would be to run ngrok on your machine - it would give you temporary HTTPS URL your colleague would need to be able to access webcam on mobile device

**Comment by davidsoergel** [comment]
Yep, Chrome won't allow access to the webcam for pages served via HTTP (https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).  So @alex77t is right that serving over HTTPS should resolve that.

Another option is to try Safari or Firefox-- I *think* those don't currently impose that restriction.

**Comment by Scooling** [comment]
Thanks a lot! When i use nginx make http to be https ,it works!
