### ISSUE TITLE
Write a TSLint rule to disallow importing from '@tensorflow/tfjs-core/dist'

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1402]
This is bad practice since moving files around in core should not break the external API. If you need something, either export it from core, or redefine it in the dependent package.

Related to https://github.com/tensorflow/tfjs/issues/1391

**Comment by WenheLI** [comment]
I am interested in this issue. But I didn't see there is a folder for custom rules. Do I need to create a folder under tfjs only or I need such folders for every tfjs sub-repo like the layers, data and so on?

**Comment by nsthorat** [comment]
For now we can make a folder in each repository called something like .tslint, let's iterate a single repository first. Separately we can figure out how we'll share code between multiple repos.

**Comment by gaikwadrahul8** [comment]
Hi, @nsthorat 

Apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs/pull/1477 got merged to take care of this issue if I'm not wrong so if this issue got resolved please feel free to close this issue now ? Thank you!
