### ISSUE TITLE
Migrate builds / CI to travis-ci.com

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1403]
travis-ci.com provides better support than travis-ci.org. This may improve our build and queue time.

**Comment by dsmilkov** [comment]
Update: travis-ci.com requires **full write access** to all our repos which is a blocker. Will contact the Travis team. If they can't remove that, we have to look for alternatives (Cloud Build, CircleCI etc)

**Comment by dsmilkov** [comment]
we migrated to Cloud so closing this
