### ISSUE TITLE
Some TF Hub modules are not converted.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1408]
We should either convert them all, or throw a better error message if the request fails when that bit is set.

Here is some code that fails:
```
async function go() {
  console.log('loading');
  const model = await tf.loadGraphModel('https://tfhub.dev/google/elmo/2', {fromTFHub: true});
  console.log('loaded');
}
go();
```

**Comment by nsthorat** [comment]
We should do both, but short term let's get a better error message in when fromTfHub: true is set.

Here is the original PR that improved error messaging: https://github.com/tensorflow/tfjs-core/pull/1599

**Comment by rthadur** [comment]
Related PR has been merged here https://github.com/tensorflow/tfjs-core/pull/1599 , closing this issue.
