### ISSUE TITLE
Improve error messaging for input_format=tf_session_bundle

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1409]
We don't support input_format=tf_session_bundle in the converter. However, it shows up in one of the arguments of the tool as a supported input, and when you specify it it will only say "invalid input / output pair format tf_session_bundle - None".

We should provide a better error message.

Ideally, we fix this all [with a CLI interface](https://github.com/tensorflow/tfjs/issues/1407), but if that takes too much time we can improve messaging here.

**Comment by tafsiri** [comment]
@pyu10055 Could you also update https://www.tensorflow.org/js/tutorials/conversion/import_saved_model to not mention session_bundle (file is here https://github.com/tensorflow/tfjs-website/blob/master/docs/tutorials/conversion/import_saved_model.md) and also on the README at https://github.com/tensorflow/tfjs-converter
