### ISSUE TITLE
Gesture Classification Web App (many bugs on JS code)

### ISSUE THREAD

**Issue by gbobeff** [tensorflow/tfjs#1412]
- index.js : function loadModel does not exist
line **32** `const mobilenet = await tf.loadModel(
`
i replaced it for `loadLayersModel` as the only function with a similar name
`const mobilenet = await tf.loadLayersModel(`

- ui.js : two missing carry return
line **151** `} ui.donePredicting =`
replaced by 
`}`
`ui.donePredicting =`
line **181** `} let mouseDown = false;`
replaced by 
`}`
`let mouseDown = false;`

- webcam.js
line 39 ` const webcamImage = tf.fromPixels(this.webcamElement);`

i replaced it for `browser.fromPixels`, i found it inspecting tfjs.js code
` const webcamImage = tf.browser.fromPixels(this.webcamElement);`

after those changes application worked correctly ...

or perhaps local js code (index.js, ui.js and wbecam.js) was coded with respect to a previous version of `tfjs.js` (i mean not for the latest at least)
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"> </script>`

**Comment by tafsiri** [comment]
Hi @gbobeff could you give us the link to where you saw this code? We've updated our examples recently but maybe we missed some.

**Comment by gbobeff** [comment]
Hi @tafsiri ,
here you are the links to concerned source code 
* [index.js](https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/web/index.js)
* [ui.js](https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/web/ui.js)
* [webcam.js](https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/web/webcam.js)

. Gustavo

**Comment by tafsiri** [comment]
Thanks @gbobeff, it looks like there is a pending fix for it here https://github.com/tensorflow/examples/pull/30/files it should be reviewed and merged soon.

**Comment by tafsiri** [comment]
Closed in https://github.com/tensorflow/examples/pull/30/files
