### ISSUE TITLE
Can't use tfjs-vis in a React app due to Preact typings collision

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1415]
Depending on tfjs-vis from our React app causes trouble.  We use @types/react, but tfjs-vis uses preact, which provides colliding global JSX definitions.

The problem started with tfjs-vis 0.5.1 (and persists in 1.0.x).  I don't understand why things worked with tfjs-vis 0.5.0; still trying to pin down any relevant difference.

Some background on the issue:
https://github.com/developit/preact/issues/1036
https://github.com/Microsoft/TypeScript/issues/18588 (maybe?)

**Comment by tafsiri** [comment]
Updating issue after convo with David. Workaround is to delete preact.d.ts in node_modules/preact/dist and node_modules/preact/src

I suspect the preact 8.* typings are just incompatible with react 16s latest typings. But can dig deeper when I get a chance. Either way preact typings should not be relevant for consumers of tfjs-vis.

**Comment by davidsoergel** [comment]
Yep, thanks.  An effective workaround is to add this to package.json:

    "scripts": {
        "postinstall": "rimraf node_modules/preact/*/preact.d.ts"
    }

That way the irrelevant preact types are automatically deleted after every ```yarn```, and everything works fine.  I think this is sufficient to close the bug?

**Comment by tafsiri** [comment]
Thanks David! I might keep it open for a bit just to remind me to investigate typings drift between the projects (though I do think your solution is the right one, react users would always want to use react types). So I might close it soon (maybe i'll remove the bug tag since it has a solution).
