### ISSUE TITLE
Coral edge tpu bindings for tf.js 

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1422]
I'm not sure if this is possible, but:

[the current starter code](http://storage.googleapis.com/cloud-iot-edge-pretrained-models/edgetpu_api.tar.gz) for the Coral edge board on Raspberry Pi contains python bindings for the c++ edge tpu engine.  Would it be possible to create tf.js node bindings as well?  It would be awesome to be able to use javascript for this, especially because of its non-blocking nature, and types provided by typescript.

**Comment by ericpelland** [comment]
I would love to see this as well!! Please and thank you!

**Comment by chenqing** [comment]
+1

**Comment by larsgk** [comment]
Another option could be to make e.g. the accelerator work directly with a web application (e.g. using WebUSB)

**Comment by dsmilkov** [comment]
Thanks for filling this. Unfortunately, we don't have the bandwidth to do this. Also, I think this would be best as an external project and the TF.js team can help provide guidance and feedback.

**Comment by EddieOne** [comment]
Using the Coral TPU is shocking fast. Would be amazing to get the Coral team to make a tfjs module. For me at least, I want to do scheduling in Node as it works with the pi camera and motor controllers. We are not too far off from having a computer that can plug itself in.

**Comment by EddieOne** [comment]
Just to update everyone

>We have already received this feature request and our engineering team is analysing this. However, We don't have this on our roadmap as of now.

**Comment by bhack** [comment]
This could be interesting in the roadmap to run out of the browser:
https://github.com/tensorflow/mlir/issues/140

**Comment by larsgk** [comment]
I am wondering - is there a reason for the .so files to only be closed source? If Coral were to open it, others could add support

**Comment by EddieOne** [comment]
Yeah I am disappointed with the Google Coral implementation. Maybe a better setup in my case is to use something like the Nvidia Jetson. Can someone confirm [TFJS works with GPUs](https://www.tensorflow.org/js/tutorials/setup)?

**Comment by moeiscool** [comment]
@EddieOne apparently tfjs works with CUDA GPUs https://github.com/tensorflow/tfjs/tree/master/tfjs-node. im not sure about the browser version

**Comment by EddieOne** [comment]
For evaluation, it's like having a big GPU. Easily 30 frames per second. Yet, it only takes a tiny amount of power. Can run off batteries for hours with no motors running. In that way it is amazing. A lot of work if you need to do things in NodeJs + Python

**Comment by EddieOne** [comment]
Hello everyone, people are starting to notice the power of TFJS. If you want Coral support, please do this 5 min survey! https://t.co/RdQ9YreToH?amp=1

**Comment by akosb** [comment]
Please see latest [WebCoral demo](https://github.com/google-coral/webcoral)

**Comment by pyu10055** [comment]
To follow up, we are working with Google Coral team to provide coral-usb support on the web, stay tuned.

**Comment by larsgk** [comment]
This is awesome! - especially interesting if it works from an Android phone too :)

**Comment by ned-kelly** [comment]
Does anyone know if plans to integrate with tfjs and coral will happen any time soon?

Based on @akosb's link to the Web Demo I'm hopeful it won't be too hard to get coral support in tfjs? - Even if it's just node.js server side to begin - This is where i'm really hoping to use the library.

Cheers,

**Comment by pereibex** [comment]
+1

coral in the tfjs-node and coral in tensorflow-serving please!

**Comment by bartbutenaers** [comment]
Hi @pyu10055, @jinjingforever,
Would be nice if you could share some information about the status of this feature.
We are using Tensorflow.js extensively for video surveillance in our open-source commity, in the Node-RED ***NodeJs*** IOT application.  If a Javascript-only solution for Coral tpu's would become available, we could offer free professional video surveillance for less technically skilled users.
Thanks !!!
Bart

**Comment by jasonmayes** [comment]
Hello all. I see a lot of people still interested in this and am curious to gather more information. For those of you that see this would you be able to provide more details for:

1) The target platforms you want to use this on? Is it RaspberryPi or a mobile phone or something else?

2) Is a Node.js solution just as useful or do you need browser usage explicitly? My reasoning here is that right now only Chrome (and related Chromium browsers) support this  WebUSB standard but with Node.js it may be easier to interface with USB directly (just thinking out the box here). Not to mention there are issues on MacOS / Windows with the emerging WebUSB interface as detailed on this repo: https://github.com/google-coral/webcoral

Thank you!

**Comment by bartbutenaers** [comment]
Hi @pyu10055,
I was wondering if there is any update available about this feature?
Seems to be pretty difficult to order a coral tpu usb stick, because they are worldwide sold out.  However last night I managed to order one.  So I am going to try to get it running somehow from NodeJs on my Raspberry Pi 4.
But it would be nice if this would work out-of-the-box via npm dependencies in the future, without too much of manual setup steps.
Thanks and hope you have a nice summer!!
Bart

**Comment by pyu10055** [comment]
@bartbutenaers We have release the coral support for node in our tfjs-sig repo, and you can follow the colab [here](https://github.com/tensorflow/sig-tfjs/tree/main/tfjs-tflite-node-codelab/coral_inference_working) cc @mattsoulanille

**Comment by bartbutenaers** [comment]
@pyu10055,
Thanks for the pointers, and all the hard work you people are doing!!!
