### ISSUE TITLE
Broken iteration in TensorFlow.js for Node

### ISSUE THREAD

**Issue by rkinabhi** [tensorflow/tfjs#1428]
The following issue is w.r.t [op_utils.ts](https://github.com/tensorflow/tfjs-node/blob/master/src/ops/op_utils.ts) in the [TensorFlow.js for Node project](https://github.com/tensorflow/tfjs-node)

The function [`getTFDTypeForInputs(...)`](https://github.com/tensorflow/tfjs-node/blob/master/src/ops/op_utils.ts#L91) _@ line 91_ seems to have broken logic as the _[iteration](https://github.com/tensorflow/tfjs-node/blob/master/src/ops/op_utils.ts#L96)_ _@ line 96_ executes only once for any number on tensors provided as input to the function. 

Is there any specific reason for an iteration to be used instead of a simple 
`return getTFDType(tensors[0].dtype)`  ? 😕

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
