### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined

### ISSUE THREAD

**Issue by Swocky** [tensorflow/tfjs#1432]
Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined
    at e.<anonymous> (tfjs-converter:17)
    at tfjs-converter:17
    at Object.next (tfjs-converter:17)
    at o (tfjs-converter:17)

My model is from Keras.
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
<script>
  const MODEL_URL = './web_model/model.json';
  async function predict(){
    const model = await tf.loadGraphModel(MODEL_URL);
    const input_x = tf.tensor([[2714,    0,    0,   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0]],shape=[1,50],dtype='int32');

    const output = model.execute({input_x:input_x});
    console.log(output);
  }
  predict();
</script>
Maybe because the version？ 
I'll appreciate it if you could give me some help. Thanks.

**Comment by pyu10055** [comment]
@Swocky can you share the model.json file?
If your model is from Keras, it is likely you need to use tf.loadLayersModel API instead of tf.laodGraphModel API.
In the model.json file, there should be a field 'format' that indicates whether it is a graph or layers model.

**Comment by Swocky** [comment]
> @Swocky can you share the model.json file?
> If your model is from Keras, it is likely you need to use tf.loadLayersModel API instead of tf.laodGraphModel API.
> In the model.json file, there should be a field 'format' that indicates whether it is a graph or layers model.
You are right, I'm so casreless, as I used tf model before. But a new issue appears, I use a Lambda layer in my model， the result is 
Uncaught (in promise) Error: Unknown layer: Lambda. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at new e (tfjs:2)
    at Dp (tfjs:2)
    at pd (tfjs:2)
    at u (tfjs:2)
    at e.fromConfig (tfjs:2)
    at Dp (tfjs:2)
    at pd (tfjs:2)
    at tfjs:2
    at tfjs:2
    at Object.next (tfjs:2)

**Comment by Swocky** [comment]
It seems that Lambda layer is not supported in tfjs. So I wonder if I have any alternative to expand my dim?

**Comment by Swocky** [comment]
I solved it by myself. Just use reshape.
```
from keras.backend import int_shape
        ......
        embedded_sequences = Reshape((int_shape(embedding_layer)[1], int_shape(embedding_layer)[2], 1))(embedding_layer)
        ......
```
You could expand dim without using expand_dims and Lambda layer.

**Comment by lijialiang** [comment]
I also encountered the same problem but could not find a solution :(
