### ISSUE TITLE
Add tf.util.fetch()

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1439]
Add `tf.util.fetch()` as a cross-platform utility which mimics browser's `fetch`.

The weights loader should use this util instead of the global fetch (see weights_loader.ts) if the user hasn't provided a custom `fetchFunc`.

`tf.util.fetch()` should first check for the existence of a global fetch using `tf.ENV.global.fetch`. Then fallback for platform-specific solutions. The current platform-specific solution should be to use `node-fetch` when the environment is node.

Platforms such as wechat can override their global fetch `fetch = customFetch`, which will then be used by all fetching inside the TF.js eco-system (model loading, weights loading, etc)

**Comment by Kriyszig** [comment]
I would love to work on this if  annxingyuan hasn't started working on it  yet

**Comment by annxingyuan** [comment]
hey @Kriyszig - sorry I didn't notice your comment until today! I'm finishing this up now :) Thank you for the offer though!

**Comment by Kriyszig** [comment]
I'll try my hand at something else. Thanks @annxingyuan (^_^)
