### ISSUE TITLE
`dataset.batch()` is not working properly when `element.done===true`

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1443]
When creating a dataset from iterator: 
```
function getIterator() {
  let i = 0;
  return {
    next: () => {
      const x = [i, i, i, i]
      const y = [i];
      i++;
      return {value: {xs: x, ys: y}, done: i === 10};
    }
  }
}
```

The dataset will not return `result.done===true` properly
```
async function main() {
  // This terminates properly, as expected.
  // const ds = tf.data.generator(getIterator);
  
  // This doesn't seem to terminate properly.
  const ds = tf.data.generator(getIterator).batch(2);

  const ITER_MAX = 100;  // Added this so that it won't run into a dead loop.
  const iter = await ds.iterator()
  for (let i = 0; i < ITER_MAX; ++i) {
    const item = await iter.next();
    console.log(item.done);
    if (item.done) {
      break;
    }
  }
}
main();
```

**Comment by WenheLI** [comment]
@kangyizhang Hey, I am interested in this issue. Could you please tell me where the start point is?

**Comment by kangyizhang** [comment]
hi @caisq , after some investigation and discussion, there are two point about this issue:

1) the iterator generated from `function getIterator()` would produce result `{value:9, done:true}`. Currently the data API would treat this result the same as `{value:null, done:true}`. This is intended and the data API will keep doing in this way.

2) after the generated iterator returns `{value:9, done:true}`, it will keep returning `{value:10, done:false}, {value:11, done:false}, ...`. This is why the test method runs infinitely. I think it is a misuse of iterator. The correct way is  `return {value: {xs: x, ys: y}, done: i >= 10}`.

Please let me know if you have any thoughts.

cc: @davidsoergel

**Comment by kangyizhang** [comment]
hi @WenheLI 

Thank you for your interest. We have investigated this issue. It should be a misuse of provided param and no need to update the library code. 

We also have other issues marked with `good first issue`, please feel free to take one if any of them interests you.

**Comment by davidsoergel** [comment]
+1 to @kangyizhang's explanation!
