### ISSUE TITLE
Possible typo in tf.layers.reshape API documentation

### ISSUE THREAD

**Issue by adwellj** [tensorflow/tfjs#1448]
In https://js.tensorflow.org/api/0.15.3/#layers.reshape, it currently states "Use the ReshapeLayerConfig field input_shape when using this layer as the first layer in a model."

I'm trying 'input_shape', but that's not working. However, 'inputShape' does work.

I believe that input_shape should actually be inputShape. This also seems to align with the LayerArgs interface, which ReshapeLayerArgs extends from.
https://github.com/tensorflow/tfjs-layers/blob/v0.10.3/src/engine/topology.ts#L346-353

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
