### ISSUE TITLE
Code snippet for tf.data.mapAsync seems incorrect

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1451]
The code snippet for https://js.tensorflow.org/api/latest/#tf.data.Dataset.mapAsync doesn't use the mapAsync function.

**Comment by chenqing** [comment]
https://js.tensorflow.org/api/latest/#data.generator 
tfd => tf.data .

**Comment by kangyizhang** [comment]
@chenqing thanks for catching the typo. It has been fixed in https://github.com/tensorflow/tfjs-data/pull/159 and will be included in our next release.
