### ISSUE TITLE
How can I get my model not to be taken by the user through the model link?

### ISSUE THREAD

**Issue by izshuang** [tensorflow/tfjs#1452]
**Dear developer,**
  I want to develop a project with TensorFlowjs now, but I don't want my model files to be visible to the user. In the current demo, I found that the model files are all accessible through the browser and directly accessing the link. I especially want to know how to secure my own model on the browser side. I really hope to get your help. Thank you very much!

**Comment by nsthorat** [comment]
Unfortunately there is no way to do this because of the nature of browsers. Think of model assets as image assets, there's no way to hide an image that you show to the user from them.

**Comment by izshuang** [comment]
> Unfortunately there is no way to do this because of the nature of browsers. Think of model assets as image assets, there's no way to hide an image that you show to the user from them.

Thanks for the reply, I especially want to know that you will provide some encryption to protect my own model. If I can't protect the model, I find it difficult to use it to do commercial things.

**Comment by izshuang** [comment]
> Unfortunately there is no way to do this because of the nature of browsers. Think of model assets as image assets, there's no way to hide an image that you show to the user from them.

Thanks for the reply, I especially want to know if you will provide some encryption to protect my own model? If I can't protect the model, I find it difficult to use it to do commercial things.
