### ISSUE TITLE
TFJS-converter | Cannot convert saved_model to tfjs_graph_model

### ISSUE THREAD

**Issue by vpanichkin** [tensorflow/tfjs#1456]
#### Python version
3.6
#### tensorflowjs version
1.0.1
#### OS version
MacOS Mojave 10.4.3

## Error
While I am trying to convert faster_rcnn_inception_v2_coco saved model to Javascript format, I received an issue:

`KeyError: <tf.Tensor 'SecondStagePostprocessor/BatchMultiClassNonMaxSuppresion/map/while/Switch_1:0' shape=<unkknown> dtype=float32>`

#### Code to reproduce the bug / link to feature request

1. Download [faster_rcnn_inception_v2_coco](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz) tar and extract it
2. Try to convert with
`
 tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model <pathToExtractedTar>/saved_model ./output_folder
`

Would you be so kind to provide some help according this issue?
Thank you!

**Comment by bileschi** [comment]
I am able to replicate this issue on my own workstation. I suspect that there is some property of the input model that is not handled by the converter, and that the error message does not accurately reflect the actual problem.

**Comment by vpanichkin** [comment]
Hi, Google Team!

Thank you for such quick response.
Today I succeed in converting this model by using 0.8.x version and passing a frozen model with 

> output_node_names=detection_boxes,detection_scores,detection_classes,num_detections

I suppose, that, while I am providing output_node_names, I stay focused on a particular part of the graph and this part converts without any issue. 

Is it possible to add ` output_node_names` parameter  to future releases?

**Comment by bileschi** [comment]
Hi @vpanichkin !

I'm trying to understand exactly what you did as a work around.  It sounds like you loaded faster_rcnn_inception_v2_coco (presumably in python TF), annotated the output nodes, and then re-saved it.  You then loaded the modified artifact using tfjs_converter 0.8.x.  Is that correct?

Is the request to add `output_node_names` as a flag to the converter? If so, how would you go about determining the names of the nodes you wish to select?

Thanks!  These user stories are very helpful to understanding how TF is used 'in the wild'

**Comment by vpanichkin** [comment]
Hello @bileschi !

Yeap, You are totally right. I loaded faster_rcnn_inception_v2_coco and additionally retrained it. Afterwards, I used `summarize_graph` to get output_node_names. Than, I exported this model using tfjs_converter 0.8.x.

If I got docs correctly, `output_node_names` let us to take particular part of the graph that is needed for prediction. If so, it would be nice to come back to contact that we had in tfjs_converter 0.8.x, i.e, `output_node_names=node_1,node_2,node_n`

**Comment by pyu10055** [comment]
@vpanichkin with 1.x converter, we cannot arbitrarily set the output node names any more, they have to be a signature def in the saved model. One way to achieve this, you need to create a signature def in your saved model and set the signature_name param with the signature def key for the converter.

**Comment by vpanichkin** [comment]
Hi, @pyu10055!

Solved an issue with older converter. Thanks for cooperating!

**Comment by ccx01** [comment]
> Hi, @pyu10055!
> 
> Solved an issue with older converter. Thanks for cooperating!

Hi, @vpanichkin 

Could I ask which converter version work for you?

Hi,@pyu10055 

I got the error "NotImplementedError: numpy() is only available when eager execution is enabled.", when i try to convert the tf_save_model to tf_graph_nodel.

I'm new to python and tensorflow, could you be kind to provide some help me to convert tf_save_model to the web format?

the model I use from this tutorial:  https://www.tensorflow.org/tutorials/images/hub_with_keras

my pip package:
________________________________
absl-py                          0.7.1
astor                            0.8.0
backports.weakref                1.0rc1
bleach                           1.5.0
gast                             0.2.2
google-pasta                     0.1.7
grpcio                           1.21.1
h5py                             2.8.0
html5lib                         0.9999999
Keras                            2.2.4
Keras-Applications               1.0.8
Keras-Preprocessing              1.1.0
Markdown                         3.1.1
mock                             3.0.5
numpy                            1.16.4
pip                              19.1.1
protobuf                         3.8.0
PyYAML                           5.1
scipy                            1.3.0
setuptools                       41.0.1
six                              1.11.0
tb-nightly                       1.14.0a20190605
tensorboard                      1.14.0
tensorflow                       1.14.0
tensorflow-estimator             1.14.0rc1
tensorflow-estimator-2.0-preview 1.14.0.dev2019060600
tensorflow-gpu                   1.14.0
tensorflow-hub                   0.3.0
tensorflowjs                     1.1.2
termcolor                        1.1.0
tf-nightly-2.0-preview           2.0.0.dev20190605
Werkzeug                         0.15.4
wheel                            0.33.4
wrapt                            1.11.1
__________________________

and the command 'tensorflowjs_converter --input_format=tf_hub --quantization_bytes=1 https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/classification/1 /mobilenet/web_model', it works

Thank you!
