### ISSUE TITLE
Feature Request: Model encryption

### ISSUE THREAD

**Issue by Vandmoon** [tensorflow/tfjs#1461]
Does tfjs supply any tools to encrypt the model file? Such that the model will not be "readable" by the user. Anyway, we developers should further encapsulate the code that decrypts the model file and runs the inference, so the decrypted file won't expose to the user at runtime. Thanks.

**Comment by bileschi** [comment]
This sounds like Feature Request #239 : Model access control solution.

Right now you will need to use some external solution for keeping the model secret.  One possible solution is to host the model code elsewhere, and send requests to the model hosting system.
