### ISSUE TITLE
Failed to link vertex and fragment shaders.

### ISSUE THREAD

**Issue by 993352359** [tensorflow/tfjs#1466]
`const posenet = require('@tensorflow-models/posenet');

const ScaleFactor = 0.50;
const flipHorizontal = false;
const outputStride = 16;

// const imageElement = document.getElementById('cat');

const imageElement = document.createElement("img");
imageElement.src = "../../img/timg.jpg";
imageElement.width = "767";
imageElement.height = "1024";

//加载模型

const start = async function(){
    const net = await posenet.load();
    const pose = await net.estimateSinglePose(imageElement,ScaleFactor,flipHorizontal,outputStride);
    console.log(pose);
}

start();`

C:\fakepath(77,32-58): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(78,32-80): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): warning X3556: integer divides may be much slower, try using uints if possible.

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(77,32-58): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(78,32-80): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): warning X3556: integer divides may be much slower, try using uints if possible.

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(77,32-58): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(78,32-80): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): error X4010: Unsigned integer divide by zero
C:\fakepath(116,33-81): warning X3556: integer divides may be much slower, try using uints if possible.

Warning: D3D shader compilation failed with skip optimization flags. (ps_5_0)

Failed to create D3D Shaders

**Comment by nsthorat** [comment]
This fix for this will go out in the next release! This was fixed in: https://github.com/tensorflow/tfjs-core/pull/1646

**Comment by WaseemAhmadNaeem** [comment]
I'm using / trying Tensorflow example for JS. This issue is persistent

**Comment by rthadur** [comment]
@WaseemAhmadNaeem can you please share more details ?
@993352359 is this issue resolved for you ?

**Comment by tafsiri** [comment]
Just to add some context, the new release hasn't gone out yet. @nsthorat was just indicating that we have a fix merged into master.

**Comment by WaseemAhmadNaeem** [comment]
@rthadur I was trying the TensorFlow JS tutorial given at Official Page. I copy pasted the code and Got this error at first step.

**Comment by tafsiri** [comment]
@WaseemAhmadNaeem could you provide a link to the tutorial you are following? The image recognition tutorials shouldn't be using posenet.

**Comment by WaseemAhmadNaeem** [comment]
https://www.tensorflow.org/js/tutorials/transfer/image_classification I'm
talking about this bad boy

**Comment by CoderFF** [comment]
This one is also crashes with the same error: 
https://storage.googleapis.com/tfjs-examples/tsne-mnist-canvas/dist/index.html

**Comment by rthadur** [comment]
> This one is also crashes with the same error:
> https://storage.googleapis.com/tfjs-examples/tsne-mnist-canvas/dist/index.html

Thank you @CoderFF , tsne issues are better asked in this [repo](https://github.com/tensorflow/tfjs-tsne) , can you please open an issue there.

**Comment by lewisf** [comment]
Is this fixed? Looks like this was merged into newer versions?

**Comment by rthadur** [comment]
this is fixed and code is there in the new releases, thank you all.
