### ISSUE TITLE
Error when saving model to localstorage

### ISSUE THREAD

**Issue by tehZevo** [tensorflow/tfjs#1470]
#### TensorFlow.js version
1.0.2

#### Browser version
Chrome 73.0.3683.86

#### Describe the problem or feature request
Attempting to save model causes `RangeError: Maximum call stack size exceeded.`
This error is getting caught and re-thrown as an error related to LocalStorage saving (eg: `Error: Failed to save model 'vae' to local storage: size quota being exceeded is a possible cause of this failure: modelTopologyBytes=6234, weightSpecsBytes=1122, weightDataBytes=289692.`).
The size of the model I'm trying to save is well below the LocalStorage limit, and I've checked that LocalStorage otherwise works fine on the same page.

I believe the original exception is caused by https://github.com/tensorflow/tfjs-core/blob/0e0f11e9b42a540c9681c057babe5720606c1c73/src/io/io_utils.ts#L215 where `String.fromCharCode` is being fed *far* too many arguments after expanding the Uint8Array.

**Comment by caisq** [comment]
@tehZevo Can you try running the code example in "Example 2" at https://js.tensorflow.org/api/latest/#loadLayersModel? It saves a very simple model to localStorage, loads it back, and calls predict() on the loaded model.

**Comment by tehZevo** [comment]
@caisq Looks like Example 2 works fine. Tested in Chrome 73.0.3683.86 tfjs versions 1.0.2-1.0.4.
