### ISSUE TITLE
posenet failing for simple images and too slow

### ISSUE THREAD

**Issue by parthi2929** [tensorflow/tfjs#1472]
#### TensorFlow.js version
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs
https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet

#### Browser version
Chrome 73.0.3683.86 (Official Build) (64-bit)

#### Describe the problem or feature request
Posenet is badly estimating poses for many simple images. This make me wonder if there is any guideline we should follow to facilitate better posenet. Also it takes about 20 to 30 seconds per image be it in CPU or webgl mode. Here are the failed images (RHS image should have posenet estimation drawn)

**Settings:**
outputStride = 16, imageScaleFactor = 1, 
minPartConfidence = 0.2, minPoseConfidence=0.2 (pose obtained has around 0.36 only so increasing simply does not get me any pose drawn at all)

**Example 1:**
![image](https://user-images.githubusercontent.com/11896263/55287095-45200d00-53c2-11e9-8d9b-e2235f6021f5.png)

**Example 2:** 
![image](https://user-images.githubusercontent.com/11896263/55287148-e9a24f00-53c2-11e9-8c6b-ecad6f97d956.png)

**Example 3:**
![image](https://user-images.githubusercontent.com/11896263/55287170-21a99200-53c3-11e9-9c4b-c752a82f0802.png)

Obviously it then performed worse for video related to above images. 

#### Code to reproduce the bug / link to feature request
Simply try singlePoseDetection on above images. The images are available below for testing.
1. [yoga 1](https://i.postimg.cc/pXJ7NCF9/0284.jpg)
2. [yoga 2](https://i.postimg.cc/yY1jRHDd/0002.jpg)
3. [yoga 3](https://i.postimg.cc/8PcWDPFh/0134.jpg)

I have tried multiple tuning, and I also do not see much issue with images as well. The image is clear, pose is clear, and even in 2 of test images, the bg is almost grey. 

We have a demo release coming week. Kindly help.

**Comment by tafsiri** [comment]
@parthi2929 A good resource to look at would be https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5 which describes a lot of the different parameters to PoseNet and how they may be used.

About to the execution time could you give us a bit more information about what kind of device you are running on? (OS, any information on the graphics card). Could you also let us know what version of tensorflow.js you are using. 

Also when you go to this link https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html what FPS are you getting (graph in the top left corner)?

**Comment by parthi2929** [comment]
Hi

I have tried all those parameters (pose confidence score, part confidence score, scale factor, output stride). With best setting, I already get bad results, so with faster setting it only gets worse as I explained. 

Regarding execution time, here are the details. 

OS: Windows 10 Home version 1803
GPU: Nvidia GT 740M
Chrome: 73.0.3683.86 (Official Build) (64-bit) 

Tfjs as I already mentioned, I use below link as suggested in posenet, I do not know which version it pulls from. 
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs
https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet

I am getting 0 FPS on your last [link](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html)

**Comment by tafsiri** [comment]
cc @dsmilkov a potential windows-related bug.

**Comment by dsmilkov** [comment]
Hi @parthi2929 

My best guess currently is that there is something wrong with the WebGL/GPU drivers on your machine.

Can you send us a screenshot of
- http://webglreport.com/?v=2
- http://js.tensorflow.org/debug

That would be very helpful to us. Thank you!

**Comment by parthi2929** [comment]
Hi

Please find them below. Kindly note the results are same (both bad pose results and execution time), be it cpu or webgl. 

**webgl report:**  

![image](https://user-images.githubusercontent.com/11896263/55421593-3474c000-5597-11e9-9e2d-281a49fb640f.png)

**tensorflow debug:**  

![image](https://user-images.githubusercontent.com/11896263/55421783-b1a03500-5597-11e9-95ce-6ff9f7c19db3.png)

**Comment by parthi2929** [comment]
Also, how the suspected driver problem results in poor pose estimations? Kindly note there are two  problems

1. Very wrong pose net estimation (should be tfjs issue likely?)
2. Too slow ( be it cpu or webgl same issue )

**Comment by parthi2929** [comment]
@dsmilkov can you kindly let me know if any update on this? this is one blocking point, unable to make any app out of pose net, production ready.

**Comment by parthi2929** [comment]
@nsthorat can you also kindly check?

**Comment by nsthorat** [comment]
Do you still see this issue on TensorFlow.js 1.0.4?

**Comment by dsmilkov** [comment]
@parthi2929 Can you also share your graphics card model (e.g. `Intel Graphics 4600`) and the CPU chip (e.g. `Broadwell`, `Haswell`, `Coffeelake`, etc). Thanks!

**Comment by parthi2929** [comment]
@nsthorat  I used this as advised in posenet. where to check tf version if we use this? Should this not be using latest version? 
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs
https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet

@dsmilkov  
GPU : GeForce GT 740M
CPU: i7-4702MQ

**Comment by dsmilkov** [comment]
@parthi2929 I didn't catch an important detail from the webglreport screenshot you sent earlier. Note from your report two things:
- Unmasked renderer: Google SwiftShader
- Major performance caveat: Yes

This means that your GPU drivers are in a bad state and Chrome is reverting to the CPU-emulation of WebGL (SwiftShader), which explains the performance. Try reinstalling Chrome and your GPU drivers. Also make sure that the [threejs](https://threejs.org/) animations work smoothly.

Once you fix it, you should see something like this:

![issue](https://user-images.githubusercontent.com/2294279/56072033-efa01480-5d60-11e9-945f-e23e6dafdccd.png)

**Comment by parthi2929** [comment]
@dsmilkov Ok I will check that and revert.   

But why in CPU mode also, the pose estimations are bad (if you could check my examples 1,2,3). you could check that in mean time?

**Comment by dsmilkov** [comment]
Closing this issue for now. @parthi2929 let me know if you managed to resolve the drivers issue and if it started working again for you.
