### ISSUE TITLE
Are these ops going to be supported soon? SpaceToBatchND, FloorMod, BatchToSpaceND, ResizeBilinear, ResizeNearestNeighbor, StridedSlice

### ISSUE THREAD

**Issue by samwyi** [tensorflow/tfjs#148]
I have a model that needs the following ops to be supported:
SpaceToBatchND, FloorMod, BatchToSpaceND, ResizeBilinear, ResizeNearestNeighbor, StridedSlice

Any schedule on supporting the above ops? Thank you.

**Comment by rodrigob** [comment]
See #159 and #161.

ResizeBilinear is now available in the tfjs-core.

**Comment by nsthorat** [comment]
These should all be supported now. Let me know if you have any further issues.
