### ISSUE TITLE
Import Error:  Numpy.Core.Multiarray with tensorflowjs_converter

### ISSUE THREAD

**Issue by ctmckee** [tensorflow/tfjs#1484]
#### Description of problem = I've installed tensorflow.js and tried to use tensorflowjs_converter on a keras model.  I keep getting the following error:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

I've tried deleting and reinstalling all versions of python and numpy on my computer without success.

**Comment by llxxee** [comment]
A simple workaround is
```
pip install --upgrade numpy
```
It results in a warning:

> tensorflowjs has requirement numpy==1.15.1, but you'll have numpy 1.16.2 which is incompatible.

but after all it makes tensorflowjs_converter work properly.

**Comment by msektrier** [comment]
I can confirm ctmckee's description. I had the same setup in windows and the same error. 
after forcing the upgrade of numpy to 1.16.3 (not 1.16.2) I received a warning:


> ERROR: tensorflowjs 1.0.1 has requirement numpy==1.15.1, but you'll have numpy 1.16.3 which is incompatible.

Afterwards I tried to execute "tensorflowjs_converter --help" and "tensorflowjs_converter" and received this output:

> Traceback (most recent call last):
>   File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python36\Scripts\tensorflowjs_converter.exe\__main__.py", line 5, in <module>
>   File "c:\python36\lib\site-packages\tensorflowjs\__init__.py", line 21, in <module>
>     from tensorflowjs import converters
>   File "c:\python36\lib\site-packages\tensorflowjs\converters\__init__.py", line 22, in <module>
>     from tensorflowjs.converters.keras_tfjs_loader import deserialize_keras_model
>   File "c:\python36\lib\site-packages\tensorflowjs\converters\keras_tfjs_loader.py", line 26, in <module>
>     import tensorflow as tf
>   File "c:\python36\lib\site-packages\tensorflow\__init__.py", line 42, in <module>
>     from tensorflow._api.v2 import compat
>   File "c:\python36\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 21, in <module>
>     from tensorflow._api.v2.compat import v1
>   File "c:\python36\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 643, in <module>
>     'tensorflow_estimator.python.estimator.api._v1.estimator'))
>   File "c:\python36\lib\site-packages\tensorflow\python\tools\component_api_helper.py", line 56, in package_hook
>     child_pkg = importlib.import_module(child_package_str)
>   File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "c:\python36\lib\site-packages\tensorflow_estimator\python\estimator\api\_v1\estimator\__init__.py", line 8, in <module>
>     from tensorflow_estimator.python.estimator.api._v1.estimator import experimental
>   File "c:\python36\lib\site-packages\tensorflow_estimator\python\estimator\api\_v1\estimator\experimental\__init__.py", line 29, in <module>
>     _sys.modules[__name__], "estimator.experimental")
> TypeError: __init__() missing 1 required positional argument: 'deprecated_to_canonical'

**Comment by pyu10055** [comment]
@llxxee @ctmckee can you try to create an empty virtualenv and install tensorflowjs in that. thanks.

**Comment by ctmckee** [comment]
Seems like time was the answer.  I have today (4-30-19) re-installed and now the converter is working.  

Thanks @llxxee and @pyu10055 for the suggestions
