### ISSUE TITLE
How to make localhost:1234 running on my own computer work on my iphone 

### ISSUE THREAD

**Issue by tuna0808** [tensorflow/tfjs#1493]
Dear developer:
Now i can run postnet demo code in my own computer(cd body-pix/demos -> yarn -> yarn watch) ,but when I try to connect the localhost(http://localhost:1234 ) by my iphone,  I can access the web, but show only "Loading the model..." and nothing happen(iphone camera doesn't work). 
what should i do to work my iphone camera?

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Adeema-Amir** [comment]
go on this link https://github.com/Adeema-Amir here is soloution
