### ISSUE TITLE
the speed of prediction get much slower after its deployment on the server

### ISSUE THREAD

**Issue by Swocky** [tensorflow/tfjs#1494]
My model is converted from Keras.
The speed is normal, less than 1s when I test it on localhost.
But after I deployed it on my remote Ubuntu server using tomcat(https), the speed of prediction is much slower than localhost, nearly 10s.
```JavaScript
    const tensor = tf.tensor(data,[1,93],"int32");
    let value = sentiment_predict(tensor);

    async function sentiment_predict(tensor){
        const model = await tf.loadLayersModel(MODEL_URL);
        let result = model.predict(tensor).toString();
        let num = result.split('[')[2].split(',');
        let neg = parseFloat(num[0]);
        let pos = parseFloat(num[1]);
        return pos - neg;
    }
```
Maybe because the size of  model (6.3M) ?
Maybe because I load the model every time I want to predict?
So why that and  what should I do to?
I'll appreciate it if you could help me.

**Comment by Swocky** [comment]
```JavaScript
    const model = tf.loadLayersModel(MODEL_URL);

    async function sentiment_predict(tensor){
        let result = model.predict(tensor).toString();
        let num = result.split('[')[2].split(',');
        let neg = parseFloat(num[0]);
        let pos = parseFloat(num[1]);
        return pos - neg;
    }
```
If I put 'load' outside the function, the error is "Uncaught (in promise) TypeError: model.predict is not a function"

**Comment by adwellj** [comment]
@Swocky, I believe that `model` is going to be the promise for `loadLayersModel()` instead of the actual model. It likely works in your first example because of the `await` statement.

**Comment by Swocky** [comment]
> @Swocky, I believe that `model` is going to be the promise for `loadLayersModel()` instead of the actual model. It likely works in your first example because of the `await` statement.

Yeah, you are right. And I try  this way, the problem has basically been solved. Thanks.
```JavaScript
var model;
    loadModel();
    async function loadModel() {
        model = await tf.loadLayersModel(MODEL_URL);
    }

    async function sentiment_predict(tensor){
        let result = model.predict(tensor).toString();
        let num = result.split('[')[2].split(',');
        let neg = parseFloat(num[0]);
        let pos = parseFloat(num[1]);
        return pos - neg;
    }
```

**Comment by Swocky** [comment]
But there still be a problem.

The first time I try to pedict, I get the error. But it gets normal after the first time.
And I refresh the webpage, it happen again.

Uncaught (in promise) TypeError: Cannot read property 'predict' of undefined
    at sentiment_predict (meeting?met_id=3410441485:2176)
    at Object.success (meeting?met_id=3410441485:2153)
    at fire (jquery-3.3.1.js:3268)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.js:3398)
    at done (jquery-3.3.1.js:9305)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.js:9548)

**Comment by adwellj** [comment]
Sounds like you might be trying to make a prediction before the model has finished loading.

**Comment by Swocky** [comment]
> Sounds like you might be trying to make a prediction before the model has finished loading.

You are right again. If I wait for several seconds, it won't happen. Thanks.
