### ISSUE TITLE
Heatmaps for tfjs-models/posenet

### ISSUE THREAD

**Issue by ldenoue** [tensorflow/tfjs#1501]
Are heatmaps accessible for posenet?
Specifically, I’d like to implement 3D head pose estimation using only activation maps for nose, eyes and ears from this paper:
https://arxiv.org/abs/1812.00739

**Comment by tafsiri** [comment]
@ldenoue Take a look at the [predictForSinglePose](https://github.com/tensorflow/tfjs-models/blob/707c3603972f9b08ce330ade5cabee1777d9f454/posenet/src/posenet_model.ts#L50) and [predictForMultiPose](https://github.com/tensorflow/tfjs-models/blob/707c3603972f9b08ce330ade5cabee1777d9f454/posenet/src/posenet_model.ts#L78) methods, it returns the lower level results from the model including heatmaps.
