### ISSUE TITLE
Microphone is opening too soon on tutorial and exception being thrown on recognizer.listen()

### ISSUE THREAD

**Issue by rstor1** [tensorflow/tfjs#1505]
#### TensorFlow.js version
0.15.3

#### Browser version
Chrome 73.0.3683.103

#### Describe the problem or feature request
On step 7 of the audio recognition tutorial, when I click on the Left button to gather examples the microphone opens and an exception is thrown. See attachment:
![Screen Shot 2019-04-09 at 8 33 35 AM](https://user-images.githubusercontent.com/43070937/55801684-999f4880-5aa4-11e9-90b9-7300154f3ccc.png)

#### Code to reproduce the bug / link to feature request
The code is exactly like the tutorial. I tried this once before and it worked, now a couple of days later it is not. Any changes introduced to the repo since then perhaps that broke something?

**Comment by caisq** [comment]
@nsthorat @dsmilkov Does this look like a problem in the CodeLab or the speech-commands library?

**Comment by rstor1** [comment]
Sorry, false alarm. I failed to load the html file via the localhost:8000 port. Rookie mistake:p
