### ISSUE TITLE
Vega error from tfjs-vis linechart: Unrecognized transform type: "filter"

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1509]
We're getting this when trying to render a line chart:

```
error.js:2 Uncaught (in promise) Error: Unrecognized transform type: "filter"
    at _default (error.js:2)
    at _default (transform.js:12)
    at data.js:12
    at Array.forEach (<anonymous>)
    at parseData (data.js:11)
    at spec.js:29
    at Array.forEach (<anonymous>)
    at _default (spec.js:28)
    at parseView (view.js:56)
    at Object._default (parse.js:8)

  | _default | @ | error.js:2
-- | -- | -- | --
  | _default | @ | transform.js:12
  | (anonymous) | @ | data.js:12
  | parseData | @ | data.js:11
  | (anonymous) | @ | spec.js:29
  | _default | @ | spec.js:28
  | parseView | @ | view.js:56
  | _default | @ | parse.js:8
  | (anonymous) | @ | embed.ts:258
  | (anonymous) | @ | tslib.es6.js:71
  | __awaiter | @ | tslib.es6.js:67
  | embed | @ | embed.ts:175
  | (anonymous) | @ | linechart.ts:245
  | (anonymous) | @ | histogram.ts:239
  | __awaiter | @ | histogram.ts:239
  | linechart | @ | linechart.ts:85
  | TFVisPlotComponent.drawChart | @ | tfvis_plot.tsx:82
```

I'm guessing this has to do with https://github.com/tensorflow/tfjs-vis/blob/master/src/render/linechart.ts#L145 and 211 and 233.

I'm further *guessing* there is some transitive dependency issue where the vega-embed that tfjs-vis depends on doesn't actually pull in everything it needs, or the deps are loaded in the wrong order, or some such.

Any ideas?  Thanks!

**Comment by tafsiri** [comment]
@davidsoergel could you post a sample of arguments you are calling it with so that I can try and reproduce (including what you are using for opts.yAxisDomain)?

Also could you let me know What versions of tfjs and tfjs-vis you are using.

**Comment by davidsoergel** [comment]
Never mind, sorry for the false alarm!  It turned out that a dependency on vega 5 had snuck in to our project.  Since tfjs-vis depends on vega 4, things naturally broke.  Removing our spurious dependency fixes it.
