### ISSUE TITLE
Found typo on documentation website.

### ISSUE THREAD

**Issue by George35mk** [tensorflow/tfjs#151]
If you would like to get help from the community, our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) might be a better fit.

#### Describe the problem or feature request

I am not sure but i thing I found a small typo in documentation website

> https://js.tensorflow.org/api/0.6.1/#Models

![55](https://user-images.githubusercontent.com/20750445/38468696-6f7964c2-3b52-11e8-8b42-156092409652.PNG)

**Comment by George35mk** [comment]
@caisq I want to contribute but I can't find any HTML file of the documentation in this repo can you show me where I can find the website repo?

all files are **.md** from this https://github.com/tensorflow/tfjs-website

**Comment by tafsiri** [comment]
Thanks for reporting this! Looks like somebody found it ad made a PR https://github.com/tensorflow/tfjs-website/pull/122
