### ISSUE TITLE
Support execution of AutoML Vision Edge model

### ISSUE THREAD

**Issue by sthongprasert** [tensorflow/tfjs#1513]
I'm trying to perform a conversion from savedmodel to tensorflowjs, but I am getting an unsupported ops error. The savedmodel was created using AutoML Edge TPU feature.

**Error**: Unsupported Ops in the model before optimization
DecodeJpeg

**Tensorflowjs version**: 1.0.1

Is it possible to get DecodeJpeg ops added?

**Comment by aronsuarez** [comment]
I have the same problem, but i used the the CPU feature of automl

**Comment by aronsuarez** [comment]
is there any time frame when this feature will be integrated?

**Comment by rosman21** [comment]
Found this online somewhere but maybe try adding this to the end of your convert command. I was able to get past that error but I ended up getting another one. Again I am not saying this is the solution just saying give it a try and see what happens.

```
--skip_op_check=SKIP_OP_CHECK
```

**Comment by sthongprasert** [comment]
@rosman21 Added skip_op_check did get me through the decode error, but now I am getting

ValueError: Error dumping weight Const_1, dtype object not supported.

Not sure if that is the same error that you are receiving as well.

**Comment by rosman21** [comment]
@sthongprasert yup except I am getting a different error dumping weight error. 

I read in another thread someone downgraded their python version and tensorflowjs version and it worked for them so maybe that might be the next thing to try unless we get some support and guidance.

**Comment by sthongprasert** [comment]
@rosman21 Tried every version of tensorflowjs with Python 2.7, got the same error with every version. Hopefully someone finds a solution that works. Would be amazing if tensorflowjs can start converting AutoML edge models.

**Comment by rosman21** [comment]
@sthongprasert did you try python 3.6? and tensorflowjs 0.8.0?

**Comment by sthongprasert** [comment]
@rosman21 Tried Python 3.6 and Python 3.5 with tfjs0.8.0, neither worked. For some reason, the saved_model input requires '.pb.frozen' file. And I could not get frozen file from AutoML. Did you run into the same issue?

**Comment by sthongprasert** [comment]
@dsmilkov I tried running converter pip in virtualenv with Python 3.6.4 and tensorflowjs 0.8.0 which got me pass the previous error, but now running into a new error below 

ValueError: You need to supply the name of a node to --output_node_names.

I couldn't figure out the output node names that get created by Google AutoML Edge TPU. I tried to load pb file in tensorboard and also generated pbtxt to load into tensorboard, but it is not displaying anything, except import layer. When I tried 'Identity' as the output node name, I get the following error:

TypeError: Expected config_proto to be a ConfigProto, saw type <class 'tensorflow.core.protobuf.rewriter_config_pb2.RewriterConfig'>

Do you have any suggestions on what should be the output node names? 

Appreciate the help.

**Comment by rosman21** [comment]
@sthongprasert I think double clicking on the import layer in TensorBoard will give you the output node names. I think in my models it is called final_result. I was able to get past this output node names error after finding that out but I still hit a road block.

**Comment by sthongprasert** [comment]
@rosman21 Thanks that got me pass the node names issue. Now I'm getting the following error, not sure if this is this same one that you're experiencing as well.

TypeError: Expected config_proto to be a ConfigProto, saw type <class 'tensorflow.core.protobuf.rewriter_config_pb2.RewriterConfig'>

**Comment by davidbrewer** [comment]
Hey, just wanted to chime in to say I am also trying to get exactly the same thing working, although I downloaded my model from AutoML Vision Edge using the "Tensorflow (recommended for GPU-based devices)" format.

With Tensorflowjs version 1.0.1 and Python 3.6.6, I get the same error as mentioned in the original issue:
```
Error: Unsupported Ops in the model before optimization
DecodeJpeg
```

Adding `--skip_op_check=SKIP_OP_CHECK` got me to this different error:
```
ValueError: Error dumping weight Const_1, dtype object not supported.
```

By backing down to Tensorflowjs version 0.8.5, I got the same error about `dtype object not supported` when using this variant of the command:

```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tensorflowjs \
  --output_node_names='Identity,Tile,scores' --skip_op_check=SKIP_OP_CHECK \
  --strip_debug_ops STRIP_DEBUG_OPS \
  --saved_model_tags=serve \
  tf-saved-model tfjs-output-dir
```

But, by removing the "Tile" node name it did output a converted model.  

```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tensorflowjs \
  --output_node_names='Identity,scores' --skip_op_check=SKIP_OP_CHECK \
  --strip_debug_ops STRIP_DEBUG_OPS \
  --saved_model_tags=serve \
  tf-saved-model tfjs-output-dir
```

I haven't had a chance to actually *try out* this model that it output, but I'm pretty confident that it won't work. I'm thinking that the DecodeJpeg op is probably pretty important to this image recognition model.  

Would also love to hear if there is a plan to integrate this op anytime in the near future. Now that it's so easy to make photo recognition models with AutoML Vision Edge, the ability to easily get those models into javascript would be amazing.

**Comment by aronsuarez** [comment]
any update on this feature?

**Comment by dsmilkov** [comment]
Hi all! I’ll take a look at this today! If anyone can share their saved model and the name of the input/output nodes, that would be very helpful! Thanks!

**Comment by csaroff** [comment]
I can't share my model right now, but I did run the saved_model_cli on both the [pretrained coco ssd model](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) and a model of my own which was trained with the tensorflow object detection api.

Here's the signature for the pretrained model.
```bash
saved_model_cli show --dir models/model/ssd_v1_fpn_640x640_coco/saved_model/ --tag_set serve --signature_def serving_default
The given SavedModel SignatureDef contains the following input(s):
  inputs['inputs'] tensor_info:
      dtype: DT_UINT8
      shape: (-1, -1, -1, 3)
      name: image_tensor:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100, 4)
      name: detection_boxes:0
  outputs['detection_classes'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100)
      name: detection_classes:0
  outputs['detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100)
      name: detection_scores:0
  outputs['num_detections'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1)
      name: num_detections:0
Method name is: tensorflow/serving/predict
```

But for my model, the input signature is different

```
saved_model_cli show --dir models/model/export/Servo/1558228042/ --tag_set serve --signature_def serving_default
The given SavedModel SignatureDef contains the following input(s):
  inputs['serialized_example'] tensor_info:
      dtype: DT_STRING
      shape: ()
      name: tf_example:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100, 4)
      name: detection_boxes:0
  outputs['detection_classes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: detection_classes:0
  outputs['detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: detection_scores:0
  outputs['num_detections'] tensor_info:
      dtype: DT_FLOAT
      shape: (1)
      name: num_detections:0
  outputs['raw_detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 51150, 4)
      name: raw_detection_boxes:0
  outputs['raw_detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 51150, 6)
      name: raw_detection_scores:0
Method name is: tensorflow/serving/predict
```

tensorflowjs_converter 1.1.2 worked fine on the pretrained model, but failed on my retrained model.  I'm going to dig into the tensorflow object detection api code a little to try to track down the disparity, but any insight here would be super helpful.  I've spent more hours than I'd like to admit just convert this model to tfjs :tongue

**Comment by csaroff** [comment]
Okay, so after debugging for the entire day it turned out that I just needed to [explicitly export](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md) my tensorflow object detection api model from the checkpoint files, setting the input type to image_tensor.

```
python /home/csaroff/work/models/research/object_detection/export_inference_graph.py \
  --input_type=image_tensor \
  --pipeline_config_path=models/model/pipeline.config \
  --trained_checkpoint_prefix=models/model/model.ckpt-50000 \
  --output_directory=exported_tf_model
```

Luckily, I stumbled upon the saved_model_cli tool which gave me a clue, but I almost gave up on this entirely.  It might be worthwhile for others to try using it as a debugging tool to compare against a working model.  More explicit error reporting in tensorflowjs_converter could be really helpful though. 😄

**Comment by aronsuarez** [comment]
Any workaround or Timeline?

**Comment by aronsuarez** [comment]
@dsmilkov I saw you make a pull request, that solve this problem, is this in the current version 1.1.2?
Can you give a example how i can convert a automl saved_model to tfjs? 

Thanks for help

**Comment by sthongprasert** [comment]
Not sure if this has been resolved. Today I tried with latest version 1.2.1 and got a different error

Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 556, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 287, in convert_tf_saved_model
    optimize_graph(frozen_func, output_graph, model.tensorflow_version,
AttributeError: 'AutoTrackable' object has no attribute 'tensorflow_version'

**Comment by davidbrewer** [comment]
Hi, I wanted to report in that I was able to convert that same AutoML Vision model using the 1.2.1 version of the converter! But, I'm having some problems actually loading the resulting model in the browser.

To sum up the model:
* AutoML Vision Edge model, exported using the "Tensorflow (recommended for GPU-based devices)" format.
* I converted it using the following command: 
`tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --skip_op_check --signature_name=serving_default --saved_model_tags=serve path_to_saved_model path_to_converted_model`

I'm trying to load the model as follows:

```
return await tf.loadGraphModel(this.modelPath).then(
    (ourModel: tf.GraphModel) => {
        /* do stuff with the model */
    }
);
```

I can see that all the shards of the weights got loaded by Chrome, but I get the following error and the model is undefined:
```
site.min.js:5 Uncaught (in promise) TypeError: Cannot read property 'T' of undefined
    at e.getDtypeParam (site.min.js:5)
    at site.min.js:5
    at Array.reduce (<anonymous>)
    at e.mapNode (site.min.js:5)
    at site.min.js:5
    at Array.reduce (<anonymous>)
    at e.transformGraph (site.min.js:5)
    at e.<anonymous> (site.min.js:2)
    at n (site.min.js:2)
    at Object.next (site.min.js:2)
```

Out of curiosity I also tried making a separate converted model using `--quantization_bytes=1`, and if I try to use that model I get a different error (whether it's occurring earlier or later than the error above, I'm unsure!)

```
site.min.js:7 Uncaught (in promise) Error: Unsupported dtype in weight 'map/while/eval_image/central_crop/mul/y': float64
    at a (site.min.js:7)
    at Object.a [as decodeWeights] (site.min.js:7)
    at e.<anonymous> (site.min.js:2)
    at n (site.min.js:2)
    at Object.next (site.min.js:2)
    at i (site.min.js:2)
```

Any insights into this would be much appreciated! I'm also happy to share the `model.json` or other parts of the model files somewhere if that would be useful...

**Comment by dsmilkov** [comment]
Hi all, we are in the process of adding support of AutoML.
We have a few more in process PRs that we plan to submit in the next week or two. After that, we will release a new version of TF.js and we will write a tutorial/codelab demonstrating how to use it.

In the meantime, all of these errors are very useful to know.

@davidbrewer, @sthongprasert is it possible to share the saved model files with us to help us debug? Thanks!

**Comment by dsmilkov** [comment]
An update: The `TypeError: Cannot read property 'T' of undefined` turns out was because of an older version of TF.js. I'll look into the `quantization_bytes` today.

**Comment by hansamann** [comment]
I somehow got the model from AutoML vision converted and loaded in a web page.

```
const MODEL_URL = '/web_model/model.json';

async function go() {
    const model = await tf.loadGraphModel(MODEL_URL); 
    const cubalibre = document.getElementById('cubalibre');
    model.predict(tf.browser.fromPixels(cubalibre));
}

go();
```


But when I load the web page the js throws this error:
```
graph_model.ts:179 Uncaught (in promise) Error: Input tensor count mismatch,the graph model has 11 placeholders, while there are 1 input tensors.
    at t.normalizeInputs (graph_model.ts:179)
    at t.execute (graph_model.ts:212)
    at t.predict (graph_model.ts:168)
    at go (mytfjs.js:6)
```
It seems I need to convert the img dom element to the suitable input tensors of my AutoML Vision model that I converted.  BTW I converted using these settings:

```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --skip_op_check --signature_name=serving_default --saved_model_tags=serve 2019-07-10_12-13-40-642_tf-saved-model web_model
```

**Comment by dsmilkov** [comment]
Hi all,

- I renamed this issue to be about AutoML Vision Edge models since that's the underlying intention.
- We did bunch of work over the last month to improve support. The benefits will be available in the next release of TF.js (which should be in 1-2 weeks).
- Our work is far from done, but when we release a new version I'll post alpha instructions on this issue on how to convert and deploy an AutoML Vision Model for enthusiastic alpha users to try.

Stay tuned.

**Comment by camoconnell** [comment]
@hansamann - did you find a solution? ... i'm snagged on the exact same issue. 
@dsmilkov - were aforementioned updates rolled out? 
 
Thanks!

**Comment by dsmilkov** [comment]
Hi everyone,

Thanks so much for your patience. I'm really excited to announce that our integration with AutoML is now public. See the [blog post](https://medium.com/tensorflow/build-and-deploy-tensorflow-js-models-with-the-power-of-automl-1985b8985083) which has pointers on how to train and export your model to TensorFlow.js.

Few things to note:
- With this integration, you don't need to export a SavedModel and run the converter yourself (that conversion might fail). Instead you export directly to TensorFlow.js from the Cloud UI.
- If you already have a AutoML model that you trained more than 2 weeks ago, you might have to re-train it in order for the TF.js conversion to work. 

Hope this helps and I'd love your feedback if you run into any issues.
