### ISSUE TITLE
tf.image.cropAndResize return zero values on large crop size

### ISSUE THREAD

**Issue by vlesu** [tensorflow/tfjs#1524]
#### TensorFlow.js version
tfjs@1.0.0

#### Browser version
Google Chrome 73.0.3683.103

#### Describe the problem or feature request
When i use cropSize more than 90x90, tf.image.cropAndResize produce zeroes at the end of array instead of correct pixel values.

#### Code to reproduce the bug / link to feature request
```
<!DOCTYPE html>
<html lang="en">
  <head>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js"></script>
	<script>
		const image = tf.ones([1, 1920, 1920, 3]);
		const boxes  = [[0, 0, 0.1, 0.1]];
		const boxInd  = [0];
		const cropSize = [100,100];
		const cropped = tf.image.cropAndResize (image, boxes, boxInd, cropSize);
		const r = cropped.dataSync();
		console.log(r[r.length-1]); // should be "1", but "0" printed	
	</script>
  </head>
<body>
</body>
</html>
	
```

**Comment by Udolf15** [comment]
Tried the code on my google chrome -v (73.0.3683.103), the code is printing 1.

**Comment by vlesu** [comment]
Problem resolved by re-installing of video drivers and configure Chrome to use NVidia graphics card.

Issue can be closed, thank you
