### ISSUE TITLE
Convert old performance benchmark data to new format and save it in Cloud Firestore

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1525]
Follow the type/schema system at
https://github.com/tensorflow/tfjs/blob/master/integration_tests/benchmarks/types.ts

For example code on how to write data to Cloud Firestore, see:
https://github.com/tensorflow/tfjs/blob/master/integration_tests/benchmarks/firestore.ts

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Apologize for the delayed response and We have updated official documentation w.r.t [Benchmark on multiple devices](https://github.com/haoyunfeix/tfjs/tree/webgpu_integration_test/e2e/benchmarks/browserstack-benchmark) and if I'm not wrong we have converted old performance benchmark data to new format saved it in cloud Firestore and I'm referring this [file](https://github.com/tensorflow/tfjs/blob/master/e2e/benchmarks/browserstack-benchmark/firestore.js), If have I missed something here please let me know ? Thank you!
