### ISSUE TITLE
How can I convert to any model format?

### ISSUE THREAD

**Issue by Lursun** [tensorflow/tfjs#1531]
I want to convert model format between .pb .h5 tfjs(json/bin?) and pkl(option),It is too complicated.
tenserflowjs(tfjs-converter) is insufficient.
I need a more powerful tool.
I think tfjs model and .h5 convert to .pb is required.
Keras and Javascript are easier for some people, But sometimes you need to convert to .pb (Golang application)

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by escanor-98** [comment]
i developed model in pkl format now i want to deploy it in an app so need is pkl should get converted to tflite. how to do that???
