### ISSUE TITLE
how to save model or weights when use tfjs-core api?

### ISSUE THREAD

**Issue by chenqing** [tensorflow/tfjs#1532]
When using tfjs-core API train some model, I can't see any method like tf.Model.saveXX .
how can I save the last trained weights and used in another place?

**Comment by tafsiri** [comment]
When using the core api you would need to implement your own serialization (you can get the values of the tensor using the `.data()` method. Note that there is no model object for us to save as you can write arbitrary code using the core api. In built serialization is one of the major benefits of the layers api.
