### ISSUE TITLE
Can't replace layers.dense with layers.lstm

### ISSUE THREAD

**Issue by dan-ryan** [tensorflow/tfjs#1533]
I've just started learning Tensorflow.js 1.0 and I was playing around with the CSV example code. I wanted to use `tf.layers.lstm` instead of `tf.layers.dense`. In other neural network libraries, it's an easy swap. But instead, I get an error.

I was going to list this on StackOverflow, but unsure if this is a bug or an improvement that needs to happen. Reading the API docs, for me, it's not clear what the differences are and why a direct swap can't happen. Maybe I missed something? 

I've written up a workable sample here, with the lstm code commented out. https://codepen.io/dan-ryan/pen/MRXGMp

I was hoping it was a direct swap, but instead, I get this error:

> (node:23344) UnhandledPromiseRejectionWarning: Error: Input 0 is incompatible with layer lstm_LSTM1: expected ndim=3, found ndim=2

The error is unclear for new users too. I've tried various things people have suggested on StackOverflow without luck.

**Comment by tafsiri** [comment]
@dan-ryan I think this is because the input shape in your example is 1d whereas it needs to be 2d i.e. `[timesteps/sequence_length, numFeatures]`, (there will be one more dimension, the batch size, that will automatically be added to the input shape). 

@caisq Is there any opportunity here to improve the error message?

**Comment by dan-ryan** [comment]
The API doesn't make that clear if that is the case. 

Can you show an example, how to fix my sample code?

**Comment by caisq** [comment]
@dan-ryan 

This API follows keras standard. IMHO, the error message is relatively clear in this case. An LSTM layer (or any RNN layers) expects its input to be 3D. The 3 dimensions are example (batch), time step and features, respectively. If you give it a 2D input (as I think is what happened in your case), it'll throw the error.

LSTM (RNN) layers typically don't follow dense layers. Instead, it is more common for dense layers to follow LSTM layers. The inputs to LSTM layers are usually one of the three:
1. Original input of the model, which is 3D (see the jena-weather and lstm-text-generation examples below)
2. Output from an embedding layer (see the sentiment example below)
3. Input from anther LSTM layer, with the `returnSequences` property set to `true`.

We have some examples of using LSTMs in our tfjs-examples repo. For example:
https://github.com/tensorflow/tfjs-examples/blob/master/jena-weather/models.js#L149
https://github.com/tensorflow/tfjs-examples/blob/master/lstm-text-generation/model.js#L40
https://github.com/tensorflow/tfjs-examples/blob/master/sentiment/train.js#L75
