### ISSUE TITLE
tfjs-visor API 1.0.2 examples not running

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#1539]
tfjs-visor API examples (all versions) do not run for me on Windows, Android Chrome or Ubuntu Chrome. 

Using this link to version 1.0.2 tfjs-visor API:  https://js.tensorflow.org/api_vis/1.0.2/#visor

When clicking the "run" button the error I get is:

> codeSnippets.js:74 Uncaught (in promise) TypeError: Cannot read property 'startScope' of undefined
>     at executeCodeSnippet (codeSnippets.js:74)
>     at HTMLButtonElement.<anonymous> (codeSnippets.js:145)

Any ideas @tafsiri ?

The examples work fine away from the API.

**Comment by tafsiri** [comment]
@hpssjellis Thanks for reporting! We found the fix (a change in a recent release) and i've made a PR to update the snippet runner. Should be deployed fairly soon.

**Comment by hpssjellis** [comment]
Everything works now. Thanks.

Quick observation @tafsiri after I hide the visor, the visor command does not work (because the visor is hidden). Probably best each time tfvis.visor(); is called, to force the visor to be visible.

Perhaps "force visor visible"  could be an option passed to tfvis.visor();
