### ISSUE TITLE
Heatmap columns/rows swapped in API docs example code

### ISSUE THREAD

**Issue by Polarisation** [tensorflow/tfjs#1543]
#### TensorFlow.js version

tfjsvis 1.02

#### Browser version
Chrome 73

#### Describe the problem or feature request

The rows and columns in the Heatmap example on the API docs page are swapped. The example code states there should be 50 rows and 20 columns, but running the code shows 50 columns and 20 rows. I am not clear if this represents a bug in the example code or in tfjsvis itself.

In any case it would be helpful if the `data.values` parameter could be clarified in the API docs. I found the arrangement of values confusing. In the second example code block we have the following for `data.values`:
```
[
  [4, 2, 8, 20],
  [1, 7, 2, 10],
  [3, 3, 20, 13]
]
```

But when running the second example the heatmap is displayed as:
```
[4] [1] [3]
[2] [7] [3]
[8] [2] [20]
[20] [10] [13]
```
So the inner arrays are columns with the order from top to bottom. I found it confusing the way the rows and columns seem to be swapped, and it seems whomever wrote the first example did too.

A more natural order would be to have the inner arrays as rows, and then display the rows either top to bottom (matching the nested array structure) or bottom to top (matching Cartesian co-ordinates). Changing this would break existing code, but perhaps an option can be introduced to change the order?

#### Code to reproduce the bug / link to feature request

Run first Heatmap example here:
https://js.tensorflow.org/api_vis/latest/#render.heatmap

**Comment by tafsiri** [comment]
Thanks for the report @Polarisation! That is indeed a bug in the documentation. We are updating the examples and docs to make it clearer. I've also merged a PR that adds an option for your feature request, which i think is quite reasonable. 

The new feature and docs should be going out in a release that should be out by the end of this week.

**Comment by tafsiri** [comment]
@Polarisation, 1.1.0 is released. Updated docs are here https://js.tensorflow.org/api_vis/1.1.0/#render.heatmap, let us know if that makes things clearer. Thanks!

**Comment by Polarisation** [comment]
Looks clearer to me now, and the option will come in handy next time, thank you!
