### ISSUE TITLE
Recommend running converter pip in virtualenv

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1546]
Motivation for this issue: https://github.com/tensorflow/tfjs/issues/1484, https://github.com/tensorflow/tfjs/issues/1513, #1534

Update the README in tfjs-converter to clarify that users should run it in a docker or virtual env.

Also update the converter script to error if we detect that the user already has TF <2.0 installed, and asking the user to run it in a virtual env, or explicitly install tf 2.0 herself.

**Comment by sdll** [comment]
@dsmilkov, would it be enough to raise, say, ImportError in [setup.py](https://github.com/tensorflow/tfjs-converter/blob/cb2796a8182857e2b272d59178c570a117b5e52e/python/setup.py#L24) if tf < 2 is installed?

**Comment by dsmilkov** [comment]
The type of error doesn't matter much as long as we give a useful actionable error message so the user.

**Comment by dsmilkov** [comment]
Reopened until the 2nd part of the issue is addressed regarding protecting the user if they already have TF installed.

**Comment by dsmilkov** [comment]
Now that we depend on TF 1.4 instead of 2.0, this is a lower priority

**Comment by ldenoue** [comment]
when I do `pip install tensorflow-gpu`, I got tensorflow 2 and everything runs fine with the GPU.
but after I do `pip install tensorflowjs`, it somehow messes up my current packages and makes my python scripts fail.
Is tensorflowjs not compatible with tensorflow 2?

**Comment by TechnikEmpire** [comment]
@ldenoue I'm not sure why no one ever responded to you but no, if you watch the deps, tfjs from pip explicitly tries to install tensorflow-cpu and it quite often mangles your installations. I often have to `-U --force-reinstall` my original GPU packages after having a go with tfjs.

**Comment by gaikwadrahul8** [comment]
Hi, @dsmilkov 

Apologize for the delayed response and As far I know currently we do not support `Tensorflow 1.x `anymore and now by default Tensorflow latest stable version is getting installed which is `TF2.11` and it seems like we have updated our official [documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#:~:text=0.%20Please%20make,for%20your%20platform.) 

@ldenoue, If you''re using `Node.js setup` then you can `Install TensorFlow.js for GPU` with this command `npm install @tensorflow/tfjs-node-gpu` and please make sure that you've `cudatoolkit=11.2` and `cudnn=8.1.0` and you can refer our official [documentation](https://www.tensorflow.org/js/tutorials/setup#option_2_install_tensorflowjs_for_gpu). Thank you!
