### ISSUE TITLE
TypeError: load() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sahilb** [tensorflow/tfjs#1550]
#### TensorFlow.js convertor : 1.0.1 
`(python -c "import tensorflowjs as tfjs; print(tfjs.__version__)")`

I am getting the following error when trying to convert a tensor flow python saved model

(myenv) 258: ~/workspace/pen3/pensieve/sim $` tensorflowjs_converter --input_format=tf_saved_model  --output_format=tfjs_graph_model  ./saved_1 ./exported_model`

Traceback (most recent call last):
  File "/Users/a/workspace/pen3/myenv/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/Users/a/workspace/pen3/myenv/lib/python3.5/site-packages/tensorflowjs/converters/converter.py", line 358, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/Users/a/workspace/pen3//myenv/lib/python3.5/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 268, in convert_tf_saved_model
    model = load(saved_model_dir, saved_model_tags)
TypeError: load() takes 1 positional argument but 2 were given

these are the contents of saved_1 directory
 
- saved_model.pb
- variables
       - variables.data-00000-of-00001
       - variables.index

I have the virtual env setup with python 3.5.5

**Comment by caisq** [comment]
@pyu10055 Can you take a look?

**Comment by sahilb** [comment]
this is the output from  saved_model_cli --all 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['myInput'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 6, 8)
        name: myInput:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['myOutput'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 6)
        name: myOutput:0
  Method name is: tensorflow/serving/predict

**Comment by pyu10055** [comment]
I believe this is resolved through the mail list, the cause of this issue is user having two versions of Tensorflow pip installed.
