### ISSUE TITLE
multi_gpu_model support

### ISSUE THREAD

**Issue by chenqing** [tensorflow/tfjs#1551]
As tf.keras.utils.multi_gpu_model , does tfjs-node-gpu support this?

the same issue linked https://github.com/tensorflow/tfjs/issues/1277

**Comment by chenqing** [comment]
Now, use `CUDA_VISIBLE_DEVICES=0 node train.js` can specify the first GPU, And so on.

**Comment by Luxcium** [comment]
What is the status of this issue? 


What is the support for using one (or the other) of 2 _GPUs_ or what is the support (documentation) for using both _GPUs_ in **TFJS** (I am using **NodeJS** but maybe 🤔 others would be interested in using it in the _browser_)...

**Comment by rthadur** [comment]
Did you get chance to check this documentation https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md and tfjs-node-gpu uses libtenorflow-gpu under the hood, which in turn recognizes the CUDA_VISIBLE_DEVICES system environment variable. You can use the env var to specify which GPU is to be used by tfjs-node-gpu, e.g., export CUDA_VISIBLE_DEVICES=2 selects the 3rd GPU on a machine with >=3 CUDA GPUs.
