### ISSUE TITLE
Packed broadcast gives different result than unpacked broadcast

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1555]
Relevant PR that introduced this bug: https://github.com/tensorflow/tfjs-core/pull/1706

To reproduce, yalc link core@master and run the tfjs-layers test. 1 test fails.

**Comment by annxingyuan** [comment]
Keeping the issue open so we remember to try to figure out how to create a test case (note this error only occurs on Linux and has to do with how unused channels are handled).

**Comment by dsmilkov** [comment]
Fixed in https://github.com/tensorflow/tfjs-core/pull/1721. Closing since there is a test in layers that catches this issue.
