### ISSUE TITLE
tensorflowjs: How to use numpy arrays in tfjs?

### ISSUE THREAD

**Issue by ctmckee** [tensorflow/tfjs#1558]
Is there a way to convert a numpy array to a usable tensor in tfjs?  

My image pre-processing files are numpy arrays.  To get predictions from a model I need to process input images with these files and I'm not sure how to accomplish this is tfjs.

**Comment by kangyizhang** [comment]
For future reference, this sort of questions are more suited to StackOverflow with tag 'tensorflow.js'.

You can try to convert and save the numpy array in other format such as json, then load and parse it as javascript array.

Numeric and array operation with numpy is not supported in tfjs. Please see https://www.tensorflow.org/js/guide/layers_for_keras_users#no_numpy_for_tensorflowjs
