### ISSUE TITLE
when build a graph, when run the graph in js, what's eager mode in js?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1559]
It might be a very stupid question.
I am quite confused.

When I have a model, it has 
call, apply, compile, fit 
4 methods.

I assume compile will build a graph, and then fit will run the graph.
Now are call/apply methods executed in compile phase or fit phase.
In python, it has an eager mode to control it. What is it in tfjs?

George Wu

**Comment by bileschi** [comment]
Perhaps this codelab will help you?
https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#0
