### ISSUE TITLE
how to call python function in javascript

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#156]
I have a function in python that takes the text input and convert them into arrays using gensim word2vec features. 

I want to call that function to my javascript that function will take the input from browser and convert them into arrays.

please tell me how to do this with an example.

**Comment by caisq** [comment]
There is no simple way to call python directly from JavaScript. Options are:
1. If the python function isn't prohibitively complex and all the dependencies have equivalents in JavaScript, rewrite the function in JavaScript. This is what we did for some of the tfjs-examples, e.g., https://github.com/tensorflow/tfjs-examples/blob/master/addition-rnn/index.js#L28
2. Wrap your python function as a webserver endpoint that the browser can query.

**Comment by kallols** [comment]
@caisq I guess the example doesn't use gensim kind of package. my function is written using gensim package. How to get use of that here.
