### ISSUE TITLE
webgl or node gpu? which is better?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1560]
I understand gpu is much faster than cpu mode.

There are two choices:
1) use webgl, which is supported in all browsers. even for windows platform.
2) use node gpu on linux with tensorflow backend. it will not work on windows.

My question is which one is better? which one is faster? which one is more stable?

George Wu

**Comment by bileschi** [comment]
Hello, this sort of question is better suited to StackOverflow.  This issues list is for bugs and feature requests.  Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
