### ISSUE TITLE
will javascript be executed in gpu?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1561]
I believe javascript will not be executed in gpu. 
Only the tensor operations are executed in gpu.
So javascript is used to build a graph and submitted the tensor graph to gpu.

I am very confused with the my javascript code.  
I am not sure which part of my code is run in gpu.

George Wu

**Comment by bileschi** [comment]
Hello, this sort of question is better suited to StackOverflow.  This issues list is for bugs and feature requests.  Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
