### ISSUE TITLE
can I do model/submodel composition and reshape with layer api?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1563]
I need to have a model which call a submodule a few times.
Can I do it with layer api? or should I use core api?
e.g. A call B 16 times:
B input and output shape is [10]
A input and output shape is [16*10]
In core api, I should be able to reshape the tensor to [16, 10] and B get a batch parameter of 16.
How can I do it with layer api to reshape it?

George Wu

**Comment by bileschi** [comment]
Hello, this sort of question is better suited to StackOverflow.  This issues list is for bugs and feature requests.  Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
