### ISSUE TITLE
can I do f(x+g(x)) with layer api?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1564]
I want to use layer api to do it.
f(x+g(x))
where x in the input tensor, g,f are two layers.

I believe it is quite straight forward to use core api.
But since the document suggest using layer api and I don't need to maintain 
the learning parameters, I am just wondering if it is possible.

George Wu

**Comment by bileschi** [comment]
Hello, this sort of question is better suited to StackOverflow.  This issues list is for bugs and feature requests.  Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
