### ISSUE TITLE
how to consume complex/zipped dataset with model.fitDataset?

### ISSUE THREAD

**Issue by aihuawu** [tensorflow/tfjs#1565]
It seems the Dataset can be composed and have arbitrary data structure.
Dataset can be zipped. how to consume a zipped Dataset?

If we call model.fitDataset, inside the model, how can we 
consume the dataset and walk through the structure and override which method to
consume it?

I find the model.fit take tensor arguments which looks like simpler.
But I am just wondering if it can do lazy data input. I assume Dataset is designed
to be able to do lazy data input.

George Wu

**Comment by bileschi** [comment]
Hello, this sort of question is better suited to StackOverflow.  This issues list is for bugs and feature requests.  Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
