### ISSUE TITLE
Inverse matrix

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs#157]
Do you guys plan to add Inverse matrix function or should we use an external lib.

I see there is a python eq

https://www.tensorflow.org/api_docs/python/tf/matrix_inverse

Shall I look at doing a PR for it?

**Comment by caisq** [comment]
@QuantumInformation It would be wonderful if you can contribute a matrix inverse implementation to tfjs-core. L-BFGS and some other applications are blocked on it. What algorithm are you considering?

**Comment by QuantumInformation** [comment]
How about this one https://github.com/jcoglan/sylvester/blob/master/src/matrix.js#L364

**Comment by nsthorat** [comment]
If possible, you should try to do this as a combination of other ops. In general we want to keep number of shader programs small.

**Comment by caisq** [comment]
@QuantumInformation Before we let you go ahead and do the coding, I want to ask: what's your use case of matrix inverse? Depending on the use case and whether the matrix at hand is symmetric, there might be more efficient ways to solve the problem that calculating the inverse.

**Comment by caisq** [comment]
@QuantumInformation Another thought: as building blocks for an efficient inv() implementation (if it makes sense to do it), we should implement LU decomposition first.

**Comment by QuantumInformation** [comment]
My use case was for showing how to do various matrice operations in tfjs, not an actual ML problem.

**Comment by rthadur** [comment]
related PR has been, so closing this issue.Thank you

**Comment by nyanye** [comment]
What is the "related PR"?
TensorFlow.js 2.3.0 API still doesn't have equivalent of tf.linalg.inv and only implements linalg.qr and linalg.gramSchmidt
