### ISSUE TITLE
Reinforcement learning / NeuroEvolution

### ISSUE THREAD

**Issue by samfultonschool** [tensorflow/tfjs#1573]
I am just getting started with tf.js and I have been trying to find a way to get reinforcement learning  and neuroevolution to work with the layers api. Are there any cross over / mutate functions, or anything for RL working with the layers api? If not, are there any plans to have this implemented? Thanks!

**Comment by caisq** [comment]
@samfultonschool We have a deep-Q network example to be checked in soon. It uses the layers API and is based on the snake game.
https://github.com/tensorflow/tfjs-examples/pull/270

We don't have a plan to add examples for neural evolution soon. But there are open-source examples of how to do neural evolution in TensorFlow.js, e.g.,
https://github.com/adityathebe/evolutionSimulator
https://github.com/MagicCube/tensorflow-rex-run
