### ISSUE TITLE
Implement tf.resizeNearestNeighbor

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#159]
Following tf.resizeBilinear, we should implement resizeNearestNeighbor as folks have requested this.

For reference of resizeBilinear:
https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/resize_bilinear_gpu.ts

This would be a great community contribution!

**Comment by oeway** [comment]
Is this error expected?
```
Uncaught (in promise) Error: Cannot compute gradient: gradient function not found for resizeNearestNeighbor.
```
I need this to train a `UpSampling2D` which has just been added: https://github.com/tensorflow/tfjs/issues/250
