### ISSUE TITLE
Documentation doesn't mention if there will be any drastic API changes due to transition to tensorflow 2 API

### ISSUE THREAD

**Issue by WillAvudim** [tensorflow/tfjs#1590]
I couldn't find any mentioning of this in the documentation. Is the API subject to drastic changes similar to tensorflow 2? The changes in my tensorflow models caused by the transition to tensorflow 2 are substantial.

I like the already implemented API, can I rely on it staying stable going forward?

**Comment by caisq** [comment]
@WillAvudim Thanks for the question. There won't be any significant API changes in TensorFlow.js (currently at 1.1.2) in relation to TensorFlow (Python) 2. The eager-style execution mode and the keras-centric high-level API in TensorFlow.js is already consistent with TensorFlow 2. In addition, the tensorflowjs_converter already is compatible with models saved by TensorFlow 2.

**Comment by caisq** [comment]
Also, this is consistent with the fact that TensorFlow.js has reached version 1.x, which according to semver, won't make breaking API changes until TensorFlow.js 2.0 (not on the horizon yet).
