### ISSUE TITLE
Can't predict using loaded FrozenModel 

### ISSUE THREAD

**Issue by joyicejin** [tensorflow/tfjs#1593]
#### TensorFlow.js version
1.0.0-alpha2
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0-alpha2/dist/tf.min.js"></script>`

#### Browser version
Google Chrome
Version 70.0.3538.77 (Official Build) (64-bit)

#### Describe the problem or feature request
I want to use the tensorflow forzen model to load in the js browser and make a predict for a shape of [60,3000,1,1] tensor.
First, I'm sure I have loaded my own FrozenModel successfully, and the shape of input is correct.
 it shown the error below:
```
Uncaught (in promise) Error: new axis mask is not yet supported
    at stridedSlice_ (strided_slice.ts:66)
    at stridedSlice (operation.ts:46)
    at executeOp$13 (slice_join_executor.ts:82)
    at executeOp$16 (operation_executor.ts:77)
    at graph_executor.ts:168
    at engine.ts:156
    at e.scopedRun (engine.ts:167)
    at e.tidy (engine.ts:153)
    at e.tidy (environment.ts:186)
    at e.execute (graph_executor.ts:157)
```
Screenshot like this:
![Screenshot from 2019-05-21 11-15-40](https://user-images.githubusercontent.com/32789540/58066397-c7a39c80-7bbb-11e9-8785-de8828c2d720.png)

I also tried the tfjs@1.1.2 and the json_model and use the loadGraphModel to make the predict, but got the same error. I can only load the model correct with correct input shapes, but can't make a predict.
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.1.2/dist/tf.min.js"></script>
const MODEL_URL='./tensorflowjs/json_model/model.json';
const model = await tf.loadGraphModel(MODEL_URL);
var xs = tf.randomUniform([60, 3000, 1, 1]);
model.predict(xs).print();  #got error: Uncaught (in promise) Error: new axis mask is not yet supported
```
#### Code to reproduce the bug / link to feature request
The complete code is here:
https://github.com/joyicejin/tfjs_frozen_bug
Could you give me some suggestions? Thanks!

**Comment by pyu10055** [comment]
@joyicejin The strided_slice op has not support the new axis mask, do you have access the the python code that generates the model? If so, possible work around is the avoid using the new axis mask.

**Comment by joyicejin** [comment]
OK,thanks!
