### ISSUE TITLE
Pacman demo static build

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#16]
@nsthorat How can i build the pacman demo (https://github.com/tensorflow/tfjs-layers/tree/master/demos/pacman) into a static bundle? I tried using watch-demo in that repo but couldn't get it to work. I also don't know if that produces a final bundle or not.

**Comment by AIGyan** [comment]
@nsthorat 
Thank you for your effort in building and supporting tensorflow.js I am new to java script. 
I am trying to run the demo on my laptop and I am getting the following error on the webpage
`No webcam found. 
To use this demo, use a device with a webcam.`
My laptop has a camera, its working file and I am able to execute my opencv object detection model. 
Please let me know what changes I have to make to run this demo.

**Comment by nsthorat** [comment]
Hi @AIGyan what kind of computer are using, and how are you running the demo? It may be yelling at you because you're actually not over SSL for a non-localhost domain (if you use `yarn watch` it should run on localhost and work).
