### ISSUE TITLE
Support tf.resizeBilinear in the TensorFlow SavedModel converter.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#160]
We currently support tf.resizeBilinear in core, but don't support it in the converter.

Let's prioritize this since we've been asked by some folks.

**Comment by pyu10055** [comment]
Added support for resizeBilinear.

**Comment by chenjin3** [comment]
The converter of tensorflowjs-0.1.1 still does not seem to provide support for ResizeBilinear.

**Comment by ManrajGrover** [comment]
@chenjin3 I believe it will be part of next release. You can check out the master branch of [tfjs-converter](https://github.com/tensorflow/tfjs-converter) and install it manually.

**Comment by chenjin3** [comment]
@ManrajGrover  It works! Thank you for your guide.
