### ISSUE TITLE
tensorflowjs_converter fails to run using tensorflowjs==0.8.5

### ISSUE THREAD

**Issue by sdll** [tensorflow/tfjs#1600]
#### pip tensorflowjs version

0.8.5

#### Describe the problem or feature request

`tensorflowjs_converter` fails to run, throwing `ImportError: numpy.core.multiarray failed to import`.

#### Code to reproduce the bug 

Run `tensorflowjs_converter` in a virtualenv.

#### Solution

The problem is resolved by installing the latest numpy (1.16.3).

```bash
pip uninstall numpy
pip install numpy
```

[Here](https://github.com/tensorflow/tfjs-converter/blob/fb5104dbce4b2912a738ab36a0906efb6707e2fd/python/requirements.txt#L3) is the culprit.

**Comment by sdll** [comment]
I can confirm that the DeepLab frozen model converts fine with the latest numpy installed.

**Comment by rthadur** [comment]
Thank you , closing this issue.

**Comment by sdll** [comment]
@rthadur, a fresh install `tensorflowjs_converter -h` still fails to run unless numpy 1.15.1 is replaced with 1.16.3 manually. I will open a PR fixing the issue.
