### ISSUE TITLE
few issues with tensorflowjs_converter

### ISSUE THREAD

**Issue by AllAwake** [tensorflow/tfjs#1603]
TF 2.0 using SavedModel
the converter was failing so i fixed couple dependencies and build the local whl
made it work with a bunch of limitations - not sure if it's by design or bugs

signature name doesn't appear in json - so i defaulted to predict
our function has 3 input arguments - but predict expects 1 so i've arranged them into array
the input arguments order is not preserved in json
thanks! helena

**Comment by AllAwake** [comment]
TF 2.0  using SavedModel
the converter was failing so i fixed couple dependencies and build the local whl
made it work with a bunch of limitations - not sure if it's by design or bugs
1. signature name doesn't appear in json - so i defaulted to predict
2. our function has 3 input arguments -  but predict expects 1 so i've arranged them into array
3. the input arguments order is not preserved in json

thanks! helena

**Comment by msektrier** [comment]
Just a remark towards point 3 - the [RFC](https://tools.ietf.org/html/rfc7159) for json allows pre-defined orders only for arrays. Otherwise, there is no guarantee how any parser implementation should process the elements of a set.

**Comment by pyu10055** [comment]
@AllAwake Good point we should persist the saved model signature into JSON.
For now, you can take a look at the signature by using the saved_model_cli, and find out the node names that are associated with the inputs, and use those names to feed to the predict method.
