### ISSUE TITLE
Tensor name can not start with number

### ISSUE THREAD

**Issue by aspidov** [tensorflow/tfjs#1604]
#### TensorFlow.js version
1.1.2
#### Browser version
This issue is not browser-specific. 
#### Describe the problem or feature request
When I using model, converted via tensorflowjs_converter (model works correctly with python and swift) (in this model using layer with name `5-con/kernel`) i getting this error:
```
Uncaught (in promise) Error: Not a valid tensor name: '5-con/kernel'
    at getUniqueTensorName (tf-layers.esm.js:575)
    at new e (tf-layers.esm.js:1376)
```
#### Code to reproduce the bug / link to feature request
regex described here: https://github.com/tensorflow/tfjs-layers/blob/8ee7bd7aaaca047f64578aefee5b1fe8753429be/src/common.ts#L106

and name : `5-con/kernel`.

for reproduce you can evaluate this line in your dev console:
```javascript
 '5-con/kernel'.match(new RegExp(/^[A-Za-z][-A-Za-z0-9\._\/]*$/)) ? true : false;
```

Is it ok or Can i create pull request for fix it?

**Comment by caisq** [comment]
@aspidov Thanks for reporting the issue. Feel free to send a PR to fix it.

**Comment by aspidov** [comment]
@caisq PR was created, but i don't know, may be will be better if converter will rename these tensors or fail if names are incorrect?

**Comment by caisq** [comment]
The merged PR should have addressed the problem.
