### ISSUE TITLE
op_list missing when running with bazel

### ISSUE THREAD

**Issue by vbardiovskyg** [tensorflow/tfjs#1605]
#### TensorFlow.js version
Running at head

#### Describe the problem or feature request
When running with bazel:
bazel build tensorflowjs/converters:converter
./bazel-bin/tensorflowjs/converters/converter --input_format=tf_saved_model --  --output_format=tfjs_graph_model /tmp/my_saved_model /tmp/converted_model

I get an error:
OSError: [Errno 2] No such file or directory: '~/tfjs-converter/python/bazel-bin/tensorflowjs/converters/converter.runfiles/org_tensorflow_js/tensorflowjs/converters/../op_list/'

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/search?q=tensorflowjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by vbardiovskyg** [comment]
Ok, found a solution. For future reference and for those who are trying to build the package themselves with bazel. To solve the "missing op_list" error, before `bazel build`, run:
```
yarn gen-json
```

**Comment by rthadur** [comment]
Thank you
