### ISSUE TITLE
PoseNet script tag example: net.estimatePoses is not a function

### ISSUE THREAD

**Issue by stuartcrobinson** [tensorflow/tfjs#1608]
#### TensorFlow.js version
using cdn scripts
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs
https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet

#### Browser version
Chrome Version 74.0.3729.131 (Official Build) (64-bit)

#### Describe the problem or feature request
_Example Usage via Script Tag_  not working for me
https://github.com/tensorflow/tfjs-models/tree/master/posenet#via-script-tag

#### Code to reproduce the bug / link to feature request
load the example in an html file and then open it in a browser. (with img src pointing to a local image).

i get this error in the console
```
Uncaught (in promise) TypeError: net.estimatePoses is not a function
    at posenetexamplejs_original.html:19
```

using this code from example: https://github.com/tensorflow/tfjs-models/tree/master/posenet#via-script-tag:
```
<html>
  <head>
    <!-- Load TensorFlow.js -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
    <!-- Load Posenet -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet"></script>
 </head>

  <body>
    <img id='cat' src='/images/cat.jpg '/>
  </body>
  <!-- Place your code in the script tag below. You can also use an external .js file -->
  <script>
    var flipHorizontal = false;

    var imageElement = document.getElementById('cat');

    posenet.load().then(function(net) {
      const poses = net.estimatePoses(imageElement, {
        flipHorizontal: flipHorizontal,
        decodingMethod: 'single-person'
      });
      const pose = poses[0];
      return pose;
    }).then(function(pose){
      console.log(pose);
    })
  </script>
</html>
```

**Comment by tafsiri** [comment]
Hi @stuartcrobinson. The README got out of sync because we are preparing a new release with new API. I've made a PR to update the readme to point to a stable version that matches what is published. Take a look at https://www.npmjs.com/package/@tensorflow-models/posenet for the correct instructions.
