### ISSUE TITLE
Enables the `onProgress` callback of tf.loadGraphModel

### ISSUE THREAD

**Issue by tylerzhu-github** [tensorflow/tfjs#1610]
#### TensorFlow.js version
1.1.0

#### Browser version
Chrome 74.0.3729.169

#### Describe the problem or feature request

The `onProgress` handler passed to [tf.loadGraphModel](https://js.tensorflow.org/api/latest/#loadGraphModel) is not invoked.

#### Code to reproduce the bug / link to feature request

After debugging it using breakpoints, I found that:
Currently the `onProgress` argument is not used ([source code](https://github.com/tensorflow/tfjs-core/blob/c157cc52c784edcb7499929516f3e9662ab0e3d1/src/io/router_registry.ts#L111)).

**Comment by syt123450** [comment]
Hi @tylerzhu-github , I take a look at this issue. It seems that `onProgress` works well with relative path, but breaks when using HTTP url. For example:
```javascript
// onProgress works
const model = await tf.loadGraphModel('./PATH/TO/MODEL/model.json', {
  onProgress: function(fraction) {
    console.log(fraction);
  }
});
```
```javascript
// onProgress breaks
const model = await tf.loadGraphModel('https://URL/TO/MODEL/model.json', {
  onProgress: function(fraction) {
    console.log(fraction);
  }
});
```
As a workaround for tfjs <= 1.2.0, you can use the relative path instead. I have sent a PR to fix it.

**Comment by tylerzhu-github** [comment]
Thanks for looking into this!
