### ISSUE TITLE
Doc inconsistency: Latest docs still mention tfl.loadModel which does not exist in 1.1.2

### ISSUE THREAD

**Issue by vladnicula** [tensorflow/tfjs#1611]
Apologies if this is the wrong place to mention documentation problems.

https://js.tensorflow.org/api/latest/#io.browserFiles shows the following code:

```js
// Note: This code snippet won't run properly without the actual file input
//   elements in the HTML DOM.

// Suppose there are two HTML file input (`<input type="file" ...>`)
// elements.
const uploadJSONInput = document.getElementById('upload-json');
const uploadWeightsInput = document.getElementById('upload-weights');
const model = await tfl.loadModel(tf.io.browserFiles(
    [uploadJSONInput.files[0], uploadWeightsInput.files[0]]));
```

But `loadModel` no longer exists. I think it should be `loadLayersModel`.

I could fix this if someone can point out where I can do it.

**Comment by caisq** [comment]
Sent out fixing PR at https://github.com/tensorflow/tfjs-core/pull/1770

In the latest API version (1.1.2), it should be `tf.loadLayersModel()`
