### ISSUE TITLE
Documentation for universal-sentence-encoder suggests tfjs@1.0.0 while latest version works fine

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1618]
#### TensorFlow.js version
1.0.0

#### Browser version
Version 74.0.3729.169 (Official Build) (64-bit)

#### Describe the problem or feature request

As documented at https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder#usage if 

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0"></script>

is used the following exception occurs and yet

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>

works fine.

universal-sentence-encoder:2 Uncaught (in promise) TypeError: n.util.fetch is not a function
    at universal-sentence-encoder:2
    at universal-sentence-encoder:2
    at Object.next (universal-sentence-encoder:2)
    at universal-sentence-encoder:2
    at new Promise (<anonymous>)
    at t (universal-sentence-encoder:2)
    at f (universal-sentence-encoder:2)
    at e.<anonymous> (universal-sentence-encoder:2)
    at universal-sentence-encoder:2
    at Object.next (universal-sentence-encoder:2)

#### Code to reproduce the bug / link to feature request

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/universal-sentence-encoder"></script>
<script>
// Load the model.
use.load().then(model => {
  // Embed an array of sentences.
  const sentences = [
    'Hello.',
    'How are you?'
  ];
  model.embed(sentences).then(embeddings => {
    // `embeddings` is a 2D tensor consisting of the 512-dimensional embeddings for each sentence.
    // So in this example `embeddings` has the shape [2, 512].
    embeddings.print(true /* verbose */);
  });
});
</script>

**Comment by annxingyuan** [comment]
Thanks @ToonTalk ! Created a PR to address this: https://github.com/tensorflow/tfjs-models/pull/219
