### ISSUE TITLE
Roll forward redundant backend creation test refactor.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#162]
After this commit tests were failing only on linux (so not showing up on travis): https://github.com/tensorflow/tfjs-core/commit/cd0cfe62ca8e005b38dada030b5517300ff8c2ab

I am rolling it back in this PR: https://github.com/tensorflow/tfjs-core/pull/936

I did about 2 hours of investigation and decided to give up. I narrowed it down to a simple test case that fails when not switching / recreating backends between tests:

```
  // These two lines cause the error, even though they are disconnected from the last line.
  const b = tf.tensor4d([5, 1, 2, 3, 4, 23, 5, 35, 12, 3, 4, 3], [1, 2, 3, 2]);
  const result = b.slice([0, 0, 0, 0], [1, 1, 1, 1]);

  // The following line prints [1, 1, 1].  
  tf.tensor1d([1, 2, 3]).square().print();
```

It seems like some state from 4D slices (this only happens for 4D slices) persists and causes problems with other ops.

Things I checked
- Shader cache is not the issue
- Other slice ranks work just fine (1d, 2d, 3d, 4d)
- This works just fine in a standalone build (not a real problem with the library, just a problem with test infra)

Suspicions:
 Somehow state is leaking from: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/slice_gpu.ts#L48

cc @dsmilkov @lewauthe

**Comment by dsmilkov** [comment]
Thanks! I had the same issue when making tests reusable. I narrowed it down to a single unit test, to a several character change in the shader source code, which leads to a WebGL bug. Will chat more in person.

**Comment by nsthorat** [comment]
This is 100% fixed
