### ISSUE TITLE
Support for protobuf `.pb` exports

### ISSUE THREAD

**Issue by BlackstoneEngineering** [tensorflow/tfjs#1624]
#### TensorFlow.js version
latest
#### Browser version
latest
#### Describe the feature request
I would like to be able to export protobuf (.pb) files from tfjs. This is so I can leverage this code together with [uTensor](http://www.utensor.ai) in order to train models in single page web apps and then deploy them to deeply embedded IoT edge devices running on Cortex M series MCU's. 
#### Code to reproduce the bug / link to feature request
Currently protobuf files are not supported

**Comment by bileschi** [comment]
It is unlikely that proto support will be added in the very near future.  Is it possible to write a converter using protobuf.js?

**Comment by BlackstoneEngineering** [comment]
Well darn. 

RE: using protobuf.js - unsure, will need to talk with @neil-tan

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
