### ISSUE TITLE
Experiment with using FMA in matMul.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1641]
Reference: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/fma.xhtml

**Comment by math3d** [comment]
Hi, I tried the mul+add and fma (fma is done by instruction mad in OpenCL Inetl SDK) on OpenCL Intel SDK. The mul+add can be optimized into mad on Intel platform. If you think thi sis necessary, we may try this on compute shader.

Below are my mul+add and fma example.

## mul+add:

```
__kernel void read(global float *src, global float *dst, uint simd_id)
{
 float a = src[0];
 float b = src[1];
 // This is done by mad.
 dst[2] += a*b;
}
```

<pre>
(W)      mov      (8|M0)         r2.0<1>:ud    r0.0<1;1,0>:ud                 
(W)      or       (1|M0)         cr0.0<1>:ud   cr0.0<0;1,0>:ud   0x4C0:uw         {Switch}
(W)      mov      (2|M0)         r126.8<1>:w   0x40:uv                        
(W)      mov      (1|M0)         r5.0<1>:ud    0x8:uw                         
(W)      mov      (8|M0)         r127.0<1>:ud  r2.0<8;8,1>:ud                   {Compacted}
(W)      add      (2|M0)         r126.0<1>:ud  r3.0<0;1,0>:ud    r126.8<2;2,1>:w
(W)      send     (1|M0)         r125:ud       r5:ud             0xA       0x2110801 //  hdc.dc0  wr:1, rd:1, fc: 0x10801
(W)      send     (2|M0)         r4:ud         r126:ud           0xA       0x21108FF //  hdc.dc0  wr:1, rd:1, fc: 0x108ff
(W)      <b>mad</b>      (4|M0)         r6.0<1>:f     r125.0<0;0>:f     r4.0<0;0>:f       r4.1<0>:f      
(W)      sends    (1|M0)         null:ud       r5                r6                0x4A      0x2030801 //  hdc.dc0  wr:1+1, rd:0, fc: 0x30801
(W)      send     (8|M0)         null:ud       r127:ud           0x27      0x2000010 {EOT} //  spawner  wr:1, rd:0, fc: 0x10
</pre>

## fma

```
__kernel void read(global float *src, global float *dst, uint simd_id)
{
 float a = src[0];
 float b = src[1];
 // This is done by mad.
 dst[2] = fma(a,b,dst[2]); 
}
```

<pre>
(W)      mov      (8|M0)         r2.0<1>:ud    r0.0<1;1,0>:ud                 
(W)      or       (1|M0)         cr0.0<1>:ud   cr0.0<0;1,0>:ud   0x4C0:uw         {Switch}
(W)      mov      (2|M0)         r126.8<1>:w   0x40:uv                        
(W)      mov      (1|M0)         r5.0<1>:ud    0x8:uw                         
(W)      mov      (8|M0)         r127.0<1>:ud  r2.0<8;8,1>:ud                   {Compacted}
(W)      add      (2|M0)         r126.0<1>:ud  r3.0<0;1,0>:ud    r126.8<2;2,1>:w
(W)      send     (1|M0)         r125:ud       r5:ud             0xA       0x2110801 //  hdc.dc0  wr:1, rd:1, fc: 0x10801
(W)      send     (2|M0)         r4:ud         r126:ud           0xA       0x21108FF //  hdc.dc0  wr:1, rd:1, fc: 0x108ff
(W)      <b>mad</b>      (4|M0)         r6.0<1>:f     r125.0<0;0>:f     r4.1<0;0>:f       r4.0<0>:f      
(W)      sends    (1|M0)         null:ud       r5                r6                0x4A      0x2030801 //  hdc.dc0  wr:1+1, rd:0, fc: 0x30801
(W)      send     (8|M0)         null:ud       r127:ud           0x27      0x2000010 {EOT} //  spawner  wr:1, rd:0, fc: 0x10
</pre>

**Comment by axinging** [comment]
Hi, I tried the mul+add and fma (fma is done by instruction mad in OpenCL Inetl SDK) on OpenCL Intel SDK. The mul+add can be optimized into mad on Intel platform. If you think this is necessary, we may try this on compute shader.

Below are my mul+add and fma example.

## mul+add:

```
__kernel void read(global float *src, global float *dst, uint simd_id)
{
 float a = src[0];
 float b = src[1];
 // This is done by mad.
 dst[2] += a*b;
}
```

<pre>
(W)      mov      (8|M0)         r2.0<1>:ud    r0.0<1;1,0>:ud                 
(W)      or       (1|M0)         cr0.0<1>:ud   cr0.0<0;1,0>:ud   0x4C0:uw         {Switch}
(W)      mov      (2|M0)         r126.8<1>:w   0x40:uv                        
(W)      mov      (1|M0)         r5.0<1>:ud    0x8:uw                         
(W)      mov      (8|M0)         r127.0<1>:ud  r2.0<8;8,1>:ud                   {Compacted}
(W)      add      (2|M0)         r126.0<1>:ud  r3.0<0;1,0>:ud    r126.8<2;2,1>:w
(W)      send     (1|M0)         r125:ud       r5:ud             0xA       0x2110801 //  hdc.dc0  wr:1, rd:1, fc: 0x10801
(W)      send     (2|M0)         r4:ud         r126:ud           0xA       0x21108FF //  hdc.dc0  wr:1, rd:1, fc: 0x108ff
(W)      <b>mad</b>      (4|M0)         r6.0<1>:f     r125.0<0;0>:f     r4.0<0;0>:f       r4.1<0>:f      
(W)      sends    (1|M0)         null:ud       r5                r6                0x4A      0x2030801 //  hdc.dc0  wr:1+1, rd:0, fc: 0x30801
(W)      send     (8|M0)         null:ud       r127:ud           0x27      0x2000010 {EOT} //  spawner  wr:1, rd:0, fc: 0x10
</pre>

## fma

```
__kernel void read(global float *src, global float *dst, uint simd_id)
{
 float a = src[0];
 float b = src[1];
 // This is done by mad.
 dst[2] = fma(a,b,dst[2]); 
}
```

<pre>
(W)      mov      (8|M0)         r2.0<1>:ud    r0.0<1;1,0>:ud                 
(W)      or       (1|M0)         cr0.0<1>:ud   cr0.0<0;1,0>:ud   0x4C0:uw         {Switch}
(W)      mov      (2|M0)         r126.8<1>:w   0x40:uv                        
(W)      mov      (1|M0)         r5.0<1>:ud    0x8:uw                         
(W)      mov      (8|M0)         r127.0<1>:ud  r2.0<8;8,1>:ud                   {Compacted}
(W)      add      (2|M0)         r126.0<1>:ud  r3.0<0;1,0>:ud    r126.8<2;2,1>:w
(W)      send     (1|M0)         r125:ud       r5:ud             0xA       0x2110801 //  hdc.dc0  wr:1, rd:1, fc: 0x10801
(W)      send     (2|M0)         r4:ud         r126:ud           0xA       0x21108FF //  hdc.dc0  wr:1, rd:1, fc: 0x108ff
(W)      <b>mad</b>      (4|M0)         r6.0<1>:f     r125.0<0;0>:f     r4.1<0;0>:f       r4.0<0>:f      
(W)      sends    (1|M0)         null:ud       r5                r6                0x4A      0x2030801 //  hdc.dc0  wr:1+1, rd:0, fc: 0x30801
(W)      send     (8|M0)         null:ud       r127:ud           0x27      0x2000010 {EOT} //  spawner  wr:1, rd:0, fc: 0x10
</pre>

**Comment by annxingyuan** [comment]
@axinging - are you saying that += a*b and fma compile to the same instructions so it shouldn't make a difference for performance? I would like to know whether using fma improves performance for WebGPU - are you interested in carrying out that investigation?

**Comment by axinging** [comment]
OK, we will try this to see if performance diffs on different platforms.
