### ISSUE TITLE
posenet camera open problem 

### ISSUE THREAD

**Issue by jesh09** [tensorflow/tfjs#1647]
Error: got multiplier type of object when it should be a number in posenet.
utils.ts line 106 compilation error in browser.

**Comment by tafsiri** [comment]
Try the instructions here https://www.npmjs.com/package/@tensorflow-models/posenet see [this note](https://github.com/tensorflow/tfjs-models/tree/master/posenet#documentation-note) for context.

**Comment by rthadur** [comment]
Hope the issue is resolved , closing this issue .
