### ISSUE TITLE
posenet demo folder does not work

### ISSUE THREAD

**Issue by ericmcgregor** [tensorflow/tfjs#1649]
The posenet demo folder does not work locally with the instructions provided.  it will throw the following error in the browser:

Uncaught (in promise) Error: got multiplier type of object when it should be a number.
    at Object.v [as assert] (util.ts:106)
    at Object.<anonymous> (posenet.esm.js:2)
    at posenet.esm.js:2

Does anybody know why this is?

**Comment by tafsiri** [comment]
If you are using the instructions for the readme they are out of sync with the published package as we are preparing a [new release](https://github.com/tensorflow/tfjs-models/tree/master/posenet#documentation-note). I would try the [instructions on npm](https://www.npmjs.com/package/@tensorflow-models/posenet), if you have any trouble with those let us know. Thanks!

**Comment by ericmcgregor** [comment]
I saw that note, so are you saying that the actual demo is out of date and doesn't work with the published packages?  The code you have published right now just doesn't work in github?  It's just very confusing, because you can view a working demo linked to from both sets of instructions.  What is out of sync between the npm and github installation instructions?  they look basically the same.  I'd really love to try this out, but i feel like i'm the only person that doesn't get how to make it work.  Is there a working demo anywhere online?

**Comment by tafsiri** [comment]
@ericmcgregor Could you let me know which instructions in particular you are using so I can double check. You can also just put in a code snippet of what you are calling here in the issue.

My recommendation is to try [these instructions (on NPM)](https://www.npmjs.com/package/@tensorflow-models/posenet) (there is also a working demo linked to from that page). The API for posenet is changing so even if they look similar the code snippets are not the same. If that (the instructions on NPM)  doesn't work, let us know as that would be a bug. 

One noticeable difference between the two is that the `.estimatePoses()` function does not exist in the currently published version.

To further elaborate on why that is, what you seeing on GitHub are instructions for an as yet _unreleased_ version of posenet.

**Comment by phpirate** [comment]
@tafsiri The demo linked inside the NPM instructions page is also not working (Talking about the Camera demo page), do you guys expect to get this fixed anytime soon?

**Comment by ericmcgregor** [comment]
Hey @tafsiri, I was not expecting to have to write my own demo files based on the instructions on NPM.  I assumed that the demo folder would contain demo code that worked, and that the installation and build instructions would be what i would need to follow to build and run the demo locally.  My understanding from the comments you made and on the github page was that maybe the installation instructions were out of date(?), but it seems like that is a misread of the intent.

If you download the github demo folder, and follow the instructions to install and build, the console will throw the error i listed above.  That's all i understand.

I don't know enough about tensorflow or debugging to go through the code in NPM and figure out what the delta is between the two code bases.  I know that makes me an unhelpful member of the dev community here.  I know there are much more important pieces to work on, but getting a local demo and example that works out of the box would be really great for those of us less savy at coding but looking to learn by example.

**Comment by tafsiri** [comment]
Thanks for the updated steps to reproduce the problem. 

Ping @tylerzhu-github, could you take a look at this? If the new package won't be out for a while can we revert the changes to the demo source?

**Comment by tylerzhu-github** [comment]
Hi all, 

The final PR has been approved for the new PoseNet release. 
https://github.com/tensorflow/tfjs-models/pull/227

Sorry for the confusion and I can understand the frustration from your side.
We will be updating the PoseNet version number in the demo in the next week for sure.

**Comment by tylerzhu-github** [comment]
If you want to use the demo in the current github. You can temporarily using the following instructions:

(rm -r node_modules) in posenet folder if thing messed up
--
in the posenet folder: yarn
in the posenet folder: yarn build && yalc push
in the demos folder: yarn && yalc link @tensorflow-models/posenet
in the demos folder: yarn watch

**Comment by SkySway13** [comment]
> Hey @tafsiri, I was not expecting to have to write my own demo files based on the instructions on NPM. I assumed that the demo folder would contain demo code that worked, and that the installation and build instructions would be what i would need to follow to build and run the demo locally. My understanding from the comments you made and on the github page was that maybe the installation instructions were out of date(?), but it seems like that is a misread of the intent.
> 
> If you download the github demo folder, and follow the instructions to install and build, the console will throw the error i listed above. That's all i understand.
> 
> I don't know enough about tensorflow or debugging to go through the code in NPM and figure out what the delta is between the two code bases. I know that makes me an unhelpful member of the dev community here. I know there are much more important pieces to work on, but getting a local demo and example that works out of the box would be really great for those of us less savy at coding but looking to learn by example.

First I wish to thank all teams and their members at Google to create such a great project.
I`m having the same issue here, every time I clicked into camera.html it shows nothing, and if I go to console I can see its giving me the same message. Long story short, it won`t work and everything I can find on the Internet is also out of date. 
Surprisingly through,  I forked this repository roughly a month ago, I found the old version in my forked repo works just fine following current demo setup instructions, so I`m guessing that new versions of demo would require a more accurate setup instruction.
I believe for now the best solution here for us beginners is find a old version of this  and use that instead.
 Hope this helps.

**Comment by tylerzhu-github** [comment]
Hi @SkySway13,

This is Tyler and I am from Google working on PoseNet library. Thanks for reaching out! How are you! I am so excited to see what you are experimenting with PoseNet.

After knowing the issue, we released a new NPM package and updated the PoseNet library’s version yesterday:

https://github.com/tensorflow/tfjs-models/pull/234#issuecomment-500110651

The new version of PoseNet models switch to use the graph execution mode in TensorFlow.js

I am very glad that the camera demo in your previous fork works! If you want to sync to the latest commit and give the latest version a try too, I will be here to help. Feel free to reach out here anytime. If your current repo is synced before yesterday’s last commit, then you can try sync to the latest commit.

**Comment by ericmcgregor** [comment]
@SkySway13 just tried re-downloading the repo and got the demo folder to work!   i'm looking forward to learning more about tfjs and posenet now.  thank you.

**Comment by njss** [comment]
I just tried to run the demos now...it is not working for me.
"\TensorFlowJS\tfjs-models\posenet\demos\node_modules\@tensorflow-models\posenet\dist\posenet.esm.js: ENOENT: no such file or directory, open 'E:\Silva_BKP\iDN\1_Research\0_iDN_Klif\CODE\TensorFlowJS\tfjs-models\posenet\demos\node_modules\@tensorflow-models\posenet\dist\posenet.esm.js'

**Comment by njss** [comment]
I also get this error: Uncaught Error: Request for https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/float/075/model-stride16.json failed due to error: TypeError: Failed to fetch
