### ISSUE TITLE
Document model.fit callbacks in API docs

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#165]
https://js.tensorflow.org/api/0.8.0/#tf.Model.fit

Current we don't show which callbacks you can use in the docs.

**Comment by johnpaulada** [comment]
Which callbacks CAN we use? 😅

**Comment by nsthorat** [comment]
Check these out:
https://github.com/tensorflow/tfjs-layers/blob/master/src/callbacks.ts#L78-L88

An example:
https://github.com/tensorflow/tfjs-examples/blob/master/iris/index.js#L64

**Comment by johnpaulada** [comment]
Awesome! Thanks! 😄 🎉
