### ISSUE TITLE
Uncaught TypeError: model.predict is not a function

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#166]
Hi,

I have imported a pre-trained keras model via json file. Find my javascript below:

```
 var a = (form.input1.value);
    $.post('http://127.0.0.1:5000/',{"text":a},function(response)
    {
        console.log('response: ',response);
        var arr=response;
        const model=tf.loadModel('./json/model.json');
        console.log(model.predict(arr))

    });
```

but I am getting the error that Uncaught TypeError: model.predict is not a function.

Please help this issue.

**Comment by nsthorat** [comment]
loadModel returns a promise so you have to await it. Try this:

```
 var a = (form.input1.value);
    $.post('http://127.0.0.1:5000/',{"text":a}, async function(response)
    {
        console.log('response: ',response);
        var arr=response;
        const model= await tf.loadModel('./json/model.json');
        console.log(model.predict(arr))

    });
```

**Comment by kallols** [comment]
@nsthorat That works fine but got another issue, while executing the json file I got one error:

```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at h (tfjs@latest:1)
    at t.predict (tfjs@latest:1)
    at t.predict (tfjs@latest:1)
    at Object.success (sample.js:19)
h @ tfjs@latest:1
t.predict @ tfjs@latest:1
t.predict @ tfjs@latest:1
(anonymous) @ sample.js:19
async function (async)
(anonymous) @ sample.js:14
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
```

Could you please tell me how to solve this too.

**Comment by dsmilkov** [comment]
Hi @kallols 

Note that model.predict() takes a `Tensor` ([api ref](https://js.tensorflow.org/api/0.8.0/#tf.Model.predict)), whereas I suspect `arr=response` gives you a regular js array? Can you try wrapping that in a Tensor using [tf.tensor](https://js.tensorflow.org/api/0.8.0/#tensor)?

**Comment by kallols** [comment]
@dsmilkov I am passing **array([[0., 0., 0., ..., 0., 0., 0.]])** to my base keras model to get the output. I got the input data from web browser in javascript is **[[0., 0., 0., ..., 0., 0., 0.]]**

could you please give one example code how to put this javascript array into model. Thanks

**Comment by kallols** [comment]
@nsthorat @dsmilkov I have used following code:

console.log(model.predict(tf.ones([1, 30000]), b));       i.e. b is the array of shape [1,30000]  as I want to convert b into tensor. but I am getting following result.

 {isDisposed: false, size: 1, shape: Array(2), dtype: "float32", strides: Array(1), …}

Could you please write the one line of code for this.

**Comment by kallols** [comment]
@nsthorat @dsmilkov A big thanks to all of you. Its working fine as I wanted. I am closing this issue.
