### ISSUE TITLE
Optimization for single pose on posenet

### ISSUE THREAD

**Issue by jrbasso** [tensorflow/tfjs#1664]
#### Posenet version
2.0.0

#### Browser version
Independent

#### Describe the problem or feature request
The implementation of posenet converts some tensors to buffers but it's not used on single pose estimation. These variables are only used for multi pose estimation. It impacts the single pose performance in about 15% from local tests.

#### Code to reproduce the bug / link to feature request
I opened a PR moving the code for multi pose into the multi pose `if` block. See https://github.com/tensorflow/tfjs-models/pull/230

**Comment by tafsiri** [comment]
Thanks @jrbasso, your PR is merged and should go out with the next release.
