### ISSUE TITLE
getting started example, extra param to model.compile 

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#167]
Extracting this from @George35mk comments in https://github.com/tensorflow/tfjs/issues/121 

#### TensorFlow.js version
0.8.0

#### Describe the problem or feature request
Example code at https://github.com/tensorflow/tfjs-examples/blob/master/getting_started/index.js#L31 uses an extra parameter.

It looks model.compile doesn't actually take a useBias param. @bileschi could you take a look?

**Comment by George35mk** [comment]
Ok, thank you.

**Comment by nsthorat** [comment]
This is fixed in the example now.
