### ISSUE TITLE
packed depthwiseConv with large filter size is slow

### ISSUE THREAD

**Issue by GreyZzzzzzXh** [tensorflow/tfjs#1673]
#### TensorFlow.js version
1.1.2

#### Browser version
Version 73.0.3683.103 (Official Build) (64-bit)

#### Describe the problem or feature request
When filter size and channel is large, e.g. [H, W, C] = [9, 9, 960], packedDepthwiseConv (82ms) is much slower than depthwiseConv (27ms). 

Moreover, this case will crash the browser on mobile.

We encountered this case in a segmentation model, and use `tf.ENV.set('WEBGL_PACK_DEPTHWISECONV', false)` temporarily. Is there any other way to improve it?  :)

#### Code to reproduce the bug / link to feature request
```ts
  const times = [];

  const x = tf.randomNormal([1, 28, 28, 960]);
  const w = tf.randomNormal([9, 9, 960, 1]);
  const s = 1;
  const p = 'same';
  let y = tf.depthwiseConv2d(x, w, s, p);
  await y.data();

  for (let i = 0; i < 100; i++) {
    const start = performance.now();
    y = tf.depthwiseConv2d(x, w, s, p);
    await y.data();
    times.push(performance.now() - start);
  }

  console.log(`Average time ms: ${times.reduce((a,b)=>a+b,0)/times.length}`);
```

**Comment by annxingyuan** [comment]
@GreyZzzzzzXh Thank you for identifying this issue! This is very helpful to know. For now I will add a bandaid to route to unpacked depthWiseConv based on the heuristic you proposed. Then I'll try to see whether we can improve the packed shader.

**Comment by annxingyuan** [comment]
Hey @GreyZzzzzzXh - just curious which device you're observing those numbers on?

**Comment by GreyZzzzzzXh** [comment]
Thanks! I tested it on Intel Iris Pro 6200.
