### ISSUE TITLE
TFJS Converter : Error while converting saved_model to tfjs_graph_model

### ISSUE THREAD

**Issue by satbecse** [tensorflow/tfjs#1676]
(base) C:\Users\st3015\Documents\00-SATHISH\06-Full Stack Developer\NodeJs\tensorflow>tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=None --saved_model_tags=myTag /tmp/new/  /tmp/web_model
2019-06-18 18:25:49.392714: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "c:\users\st3015\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\st3015\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\st3015\Anaconda3\envs\python36\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "c:\users\st3015\anaconda3\envs\python36\lib\site-packages\tensorflowjs\converters\converter.py", line 448, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "c:\users\st3015\anaconda3\envs\python36\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 274, in convert_tf_saved_model
    concrete_func = model.signatures[signature_def]
  File "c:\users\st3015\anaconda3\envs\python36\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 196, in __getitem__
    return self._signatures[key]
KeyError: 'None'

This is how saved model is created : 
     tf.logging.info('Saving a saved model')      
      builder = tf.compat.v1.saved_model.Builder("C:\\tmp\\new")
      builder.add_meta_graph_and_variables(sess=sess,tags=["myTag"],signature_def_map=None)  
      builder.add_meta_graph(["my-Tag"],signature_def_map=None)
      builder.save();    

Versions:
(base) C:\Users\st3015\Documents\00-SATHISH\06-Full Stack Developer\NodeJs\tensorflow>tensorflowjs_converter --version

tensorflowjs 1.1.2
Dependency versions:
  keras 2.2.4-tf
  tensorflow 2.0.0-dev20190607

OS : Windows 10

Python version : 3.7.3

**Comment by pyu10055** [comment]
@satbecse the tfjs converter requires the saved model you created to have a correct signature def that specifies the input and output nodes.
In your example the signature def is empty, which is causing the problem.

**Comment by satbecse** [comment]
Can you please let me know how to create a correct signature def that specifies the input and output nodes ?

**Comment by ccx01** [comment]
Hi, I got the same error, and if I use the command

>  "tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=serving_default --saved_model_tags=serve /saved_models /mobilenet/graph" 

it will show 

> "tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable module/MobilenetV2/Conv/weights_6966 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/module/MobilenetV2/Conv/weights_6966/class tensorflow::Var does not exist. [Op:ReadVariableOp]"

and when I just change the signatures_name

>  "tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=sign --saved_model_tags=serve /saved_models /mobilenet/graph" 

it showed

> KeyError: 'test'

the model I created from this tutorial  https://www.tensorflow.org/tutorials/images/hub_with_keras

I saved it with this:
> tf.contrib.saved_model.save_keras_model(model, "./saved_models", 'test')

**Comment by satbecse** [comment]
> @satbecse the tfjs converter requires the saved model you created to have a correct signature def that specifies the input and output nodes.
> In your example the signature def is empty, which is causing the problem.

FYI. I am trying to follow the Simple Audio recognition given in 
https://www.tensorflow.org/tutorials/sequences/audio_recognition 

My intent is to convert the model into web model(Java Script). I tried 2 approaches. 

Approach 1 : Converting the frozen model to Web model  
=====================================
With freeze.py I created a frozen model  by 
(python_new) C:\Users\st3015\Documents\00-SATHISH\06-Full Stack Developer\NodeJs\tensorflow>python tensorflow/examples/speech_commands/freeze.py --start_checkpoint=/tmp/speech_commands_train\conv.ckpt-4 --output_file=/tmp/my_frozen_graph.pb

When I Convert that frozen model to web model like given below , I am getting the following error
(python_new) C:\Users\st3015\Documents\00-SATHISH\06-Full Stack Developer\NodeJs\tensorflow>tensorflowjs_converter --input_format=tf_frozen_model --output_format=tensorflowjs --output_node_names=labels_softmax --skip_op_check=AudioSpectrogram,DecodeWav,Mfcc /tmp/my_frozen_graph.pb  /tmp/web_model
Using TensorFlow backend.
Traceback (most recent call last):
  File "c:\users\st3015\anaconda3\envs\python_new\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\st3015\Anaconda3\envs\python_new\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\converter.py", line 352, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_pb.py", line 331, in convert_tf_frozen_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_pb.py", line 128, in optimize_graph
    graph_def=graph.as_graph_def(), graph=graph)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\training\saver.py", line 1561, in export_meta_graph
    **kwargs)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 1000, in export_scoped_meta_graph
    **kwargs)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 585, in create_meta_graph_def
    stripped_op_list_for_graph(meta_graph_def.graph_def))
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 202, in stripped_op_list_for_graph
    raise ValueError("Op %s is used by the graph, but is not registered" % op)
ValueError: Op AudioSpectrogram is used by the graph, but is not registered


Approach 2 : Saving it as a saved model and converting it to web model. 
When I try to do that I am getting the error as given in this issue # 1676 which I created.

Can you please help me to overcome this ?
With the web model, I want to make it work in the browser to detect my own key word.

**Comment by pyu10055** [comment]
@satbecse unfortuantely those ops are not supported by tensorflow.js yet. 
If your intent is to play with an audio model in the browser, you can try out our [audio model](https://github.com/tensorflow/tfjs-models/tree/master/speech-commands), which is pretty much the same as the model you trying to converter, but uses web audio API for those audio data preprocessing.

**Comment by satbecse** [comment]
@pyu10055  I used the audio_model which has given in https://github.com/tensorflow/tfjs-models/tree/master/speech-commands. 

I downloaded the speech dataset of google which has 'one','two,'three',...... 

I have few questions. 
1. I trained with my custom wake word 'heyapple'  like you how you did it in https://www.youtube.com/watch?v=-1QGEQWhmSI.  But, in the front end it is not detecting when I say heyapple.  
 Is it possible to train a custom key word using audio_model you mentioned ? 

2.  If So, what will be vocabulary of that ? Because default_vocabulary is '18w'.  and then when I try to create a model do I have to pass an argument _background_noise as well ? 
I mean when I try  
create_model 'heyapple' _background_noise_          (do I have to _background_noise' as an argument ?)

I am able to create and save a model.json and weights.bin 

Please help me here.

**Comment by satbecse** [comment]
@rthadur  Can you please help me on this ?

**Comment by pyu10055** [comment]
@satbecse have you checked out this demo https://storage.googleapis.com/tfjs-speech-model-test/2019-01-03a/dist/index.html?
It allow you to train a custom vocabulary, it can saved the trained model too.

**Comment by satbecse** [comment]
@pyu10055  Thank you. 
 https://storage.googleapis.com/tfjs-speech-model-test/2019-01-03a/dist/index.html
 
Here, I am able record and train my word 'Hey Apple' and it detects when I say Hey Atlas. But I am not able to download/save the model. Can you please help me to save/download the model ?

**Comment by satbecse** [comment]
https://storage.googleapis.com/tfjs-speech-model-test/2019-01-03a/dist/index.html 

In Mac's Safari browser ,when using above url, after clicking the 'start' button , it is recognizes when I say 'one' ,'seven' or some other number. 

It gets hung , 
1. If I switch to other application say calculator from the safari and come back to safari.
2. If I minimize and maximize the safari browser. 

Can u please help me on this ?

**Comment by rthadur** [comment]
I was able to reproduce error in my mac safari browser. cc @pyu10055

**Comment by tafsiri** [comment]
I can confirm the issue when minimizing the safari window but not when switchig to another app.

Handing this over to @caisq to take a look, it might be an issue with the model losing the audio context on minimization, but there is no visible error in the console.

**Comment by gaikwadrahul8** [comment]
Hi, @satbecse 

Apologize for the delayed response and I see we have updated our official documentation w.r.t to tfjs-converter [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) and May I know this issue still exists ? I would suggest you to please try with latest version of `tensorflowjs 4.4.0` and also try with other web browser apart from Mac safari and let us know whether this issue still exists or not ? Thank you!
