### ISSUE TITLE
Feature request - JavaScript implementation of image grid

### ISSUE THREAD

**Issue by generic-github-user** [tensorflow/tfjs#1680]
It would be useful to have the image grid contrib function, [as seen here](https://www.tensorflow.org/api_docs/python/tf/contrib/gan/eval/image_grid), implemented in TensorFlow.js. The function allows for simple reorganization of a minibatch of images into one grid and would be useful for visualization purposes for users creating GANs, VAEs, and similar visual projects in TensorFlow.js.

**Comment by rthadur** [comment]
Contrib has been deprecated from tf 2.0 , so closing this request. Thank you
