### ISSUE TITLE
PoseNet performance improvement suggestion - pad and resize to maintain original aspect ratio instead of to a square

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1681]
With the new version of posenet, images are always padded to have equal width and height, and then resized to the inputResolution.  Since posenet does not require a square image, adding these pixels causes extra pixels to be processed that are not needed and result in uneccesary performance overhead.  It would be better if the image was resized to be close to the original aspect, and padding is only added to make sure that the resize for a dimension matches a valid inputResolution.

**Comment by tafsiri** [comment]
cc @tylerzhu-github

**Comment by tylerzhu-github** [comment]
> It would be better if the image was resized to be close to the original aspect, and padding is only added to make sure that the resize for a dimension matches a valid inputResolution.
All images are resized to a square crop for simplicity and we can definitely support specifying height size and width size independently.

**Comment by tylerzhu-github** [comment]
Thanks for adding me and will support specifying height and width resolution

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
