### ISSUE TITLE
"Input tensor count mismatch" when executing converted ssd_mobilenet_v2_oid_v4_2018_12_12 model

### ISSUE THREAD

**Issue by crazybob** [tensorflow/tfjs#1683]
#### TensorFlow.js version

1.2.1

#### Browser version

Version 75.0.3770.100 (Official Build) (64-bit)

#### Describe the problem or feature request

I get an error when I try to execute a converted model: "Unhandled Rejection (Error): Input tensor count mismatch,the graph model has 3132 placeholders, while there are 1 input tensors."

#### Code to reproduce the bug / link to feature request

1. Convert ssd_mobilenetv2_oidv4 model from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

2. Initialize the model using tf.loadGraphModel().

3. Create the input tensor: const tensors = tf.browser.fromPixels(this.state.videoElement).expandDims(0);

4. Execute: const predictions = await this.state.model.execute(tensors);

I get an exception: "Unhandled Rejection (Error): Input tensor count mismatch,the graph model has 3132 placeholders, while there are 1 input tensors."

**Comment by piercus** [comment]
I'm facing similar problem

**Comment by piercus** [comment]
I have fixed it by going by to version 0.8 of the converter and  https://github.com/tensorflow/tfjs/issues/1382#issuecomment-472970078

```shell
pip install pipenv
pip shell
pip install tensorflowjs==0.8
tensorflowjs_converter --input_format=tf_saved_model --output_json=true --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice' --saved_model_tags=serve  source dest
```

**Comment by crazybob** [comment]
Do you still use v1.2.1 of tensorflowjs?

**Comment by piercus** [comment]
On my side, version `1.1.2` (from npm) is loading a model converted using version `0.8` (from pip).

**Comment by crazybob** [comment]
Nice. I ran into this bug next: https://github.com/tensorflow/tfjs/issues/841

Removing the postprocessing blocks got me passed it.

**Comment by mike-hor** [comment]
so do I,exception: "Input tensor count mismatch,the graph model has 59 placeholders, while there are 1 input tensors"
Is there any mistake in my following operation？
step1:
use ssd_mobilenet_v1_coco_2018_01_28 to training my data,this is my config 
![image](https://user-images.githubusercontent.com/17822235/61603840-cf41f900-ac71-11e9-817a-d57f709a0e91.png)
![image](https://user-images.githubusercontent.com/17822235/61603845-d2d58000-ac71-11e9-85f2-3346dfc468d1.png)
![image](https://user-images.githubusercontent.com/17822235/61603849-d832ca80-ac71-11e9-8c96-f3853c4d3cb9.png)
![image](https://user-images.githubusercontent.com/17822235/61603852-de28ab80-ac71-11e9-98ee-1ab3234e29de.png)
![image](https://user-images.githubusercontent.com/17822235/61603858-e41e8c80-ac71-11e9-98f1-305b6c7c16de.png)
step2:
start training
```
python model_main.py --model_dir=training --pipeline_config_path=training/ssd_mobilenet_v1_coco.config --num_train_steps=20000 --num_eval_steps=4000 --alsologtostderr
```
step3:
export
···
python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v1_coco.config --trained_checkpoint_prefix training/model.ckpt-20000 --output_directory seal_graph
···
step4:
transform
```
tensorflowjs_converter --input_format=tf_saved_model --saved_model_tags=serve ./saved_model ./web_model
```
step5:
use in browser
such as
```js
export class ObjectDetection {

    constructor() {
        this.modelPath = BASE_PATH;
    }

    async load() {
        this.model = await tf.loadGraphModel(this.modelPath, {
            weightPathPrefix: "./web_model/"
        });
    }
    async detect(image) {
        const pixels = tf.browser.fromPixels(image);
        const res1 = await this.model.executeAsync(pixels.reshape([1, ...pixels.shape]));
        res1.map(t => t.dataSync());
        const res2 = await this.model.executeAsync(pixels.reshape([1, ...pixels.shape]));
        const count = res2[3].dataSync()[0];
        const boxes = res2[0].dataSync();
        const scores = res2[1].dataSync();
        const classes = res2[2].dataSync();
        console.log('number of detections: ', count);
        for (let i = 0; i < count; i++) {
            const min_y = boxes[i * 4] * 399;
            const min_x = boxes[i * 4 + 1] * 600;
            const max_y = boxes[i * 4 + 2] * 399;
            const max_x = boxes[i * 4 + 3] * 600;
            console.log('find detections:', min_x, min_y, max_x - min_x, max_y - min_y)
        }
    }
}
```
please,tell me what should i do, or my problem.forgive me,i am a newbie in tensorflow
tks！！！！

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
