### ISSUE TITLE
How to use model build on python

### ISSUE THREAD

**Issue by maelfosso** [tensorflow/tfjs#170]
If you would like to get help from the community, our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) might be a better fit.

#### TensorFlow.js version
any
#### Browser version
any
#### Describe the problem or feature request
Hi, please I built a model on python and I would to use it on a Node.js app.
How to do it please ?

**Comment by caisq** [comment]
Closing this issue as it's being discuss in the Google Group: https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/ORQI_yQFwHI
