### ISSUE TITLE
TFJS-VIS version number missing?

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1703]
The documentation page https://js.tensorflow.org/api_vis/latest/ today says 1.1.0 but I couldn't find a way to find out what version I had loaded.

**Comment by tafsiri** [comment]
Thanks for the report. I'll mark this as a feature for a future release.

Note to self: export a version number from the main namespace.

**Comment by tafsiri** [comment]
Just FYI this will go out with the next release.

**Comment by tafsiri** [comment]
This fix is now available in https://www.npmjs.com/package/@tensorflow/tfjs-vis/v/1.2.0
