### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by mgobishop** [tensorflow/tfjs#1707]
Hi. I'm using tfjs-node. I have a video file server-side. How can I detect objects in the video? For a single image I am using node-canvas but what would the equivalent be for video? I see some people are using ffmpeg to generate individual image files from the video but that seems wasteful. Any help would be appreciated :-)

**Comment by erikcartman** [comment]
If understand correctly, posenet processes images only, you can check implementation in tfjs-core, it converts data from HTMLVideoElement element into image

**Comment by tafsiri** [comment]
Hi, @mgobishop We don't have a specific recommendation for node video processing libraries. You would have to find a way to get individual images from the video, either at run time or via pre-processing. If you are unable to find a library that handle this in node then ffmpeg does seem like a reasonable approach. Something like https://github.com/fluent-ffmpeg/node-fluent-ffmpeg might let you stream the raw frame data into a custom function in your program (but I haven't tried it).

This might also be a better question for stack-overflow or the community mailing list to see how others have approached this.
