### ISSUE TITLE
Error with unknown words in Word Embeddings (Error: Invalid TF_Status: 3)

### ISSUE THREAD

**Issue by ClemHlrdt** [tensorflow/tfjs#1709]
I am building a sentiment analysis classifier. I trained it with Python using Keras and converted it to use it with TensorflowJS. I tried it in the browser with a simple implementation and it works just fine. I am now tried to use if with Node and I run in some issues.

It seems like an error appears when a **word in the sentence provided is not found** in the dictionary of my word embedding. 

However, using the same model and same dictionary on tensorflowJS (in the browser), I do not have this problem. 

## The full error:
`
(node:33660) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 3
Message: indices[333] = 38846 is not in [0, 20001)
    at NodeJSKernelBackend.executeSingleOutput (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:196:43)
    at NodeJSKernelBackend.gather (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:1028:21)
    at engine_1.ENGINE.runKernel.$x (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/ops/segment_ops.js:115:27)
    at /Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:405:26
    at Engine.scopedRun (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:359:23)
    at Engine.runKernel (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:403:14)
    at gather_ (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/ops/segment_ops.js:114:29)
    at Object.gather (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:46:29)
    at /Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-layers/dist/backend/tfjs_backend.js:456:20
    at /Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:349:22
    at Engine.scopedRun (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:359:23)
    at Engine.tidy (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:348:21)
    at Object.tidy (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/globals.js:164:28)
    at Object.gather (/Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-layers/dist/backend/tfjs_backend.js:449:24)
    at /Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-layers/dist/layers/embeddings.js:135:28
    at /Users/clement/Desktop/SentimentAnalysisTwitterAPI/node_modules/@tensorflow/tfjs-core/dist/engine.js:349:22
(node:33660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

## What I tried:

- Give the same sentence to the Browser implementation and Node implementation. (No problem in the browser but an error appears in Node if a word is unknown).
- Replacing @tensorflowjs/tfjs-node with @tensorflowjs/tfjs (Works but it is much slower)

#### TensorFlow.js version
tfjs-node: 1.2.3
tfjs: 1.2.2

#### Code for the Browser version & Node version
tfjs code (Works)

`
(async () => {
    console.log('Script loading...');
    const model = await tf.loadLayersModel(
        'http://127.0.0.1:5500/models/model.json'
    );
    emotions = ['disgust', 'sadness', 'shame', 'joy', 'guilt', 'fear', 'anger'];
    document.getElementById('myBtn').addEventListener('click', makePrediction);

    async function makePrediction() {
        // Get sentence from input
        const input = document.getElementById('myInput').value;
        // Return a sequence of 350 integers for word embedding
        const sentence = await preprocess(input);
        // fit sentence to tensor
        const inputData = tf.tensor2d(sentence, [1, 350]);
        // Make a prediction
        const result = model.predict(inputData);
        const results = result.dataSync();
        // Show all predictions with their probabilities
        for (let i = 0; i < emotions.length; i++) {
            console.log(emotions[i], (results[i] * 100).toFixed(2) + '%');
        }
        // Get index of highest result
        let index = results.indexOf(Math.max(...results));
        console.log(
            `Results: ${emotions[index]} with ${(results[index] * 100).toFixed(
                2
            )}%`
        );
        document.getElementById('prediction').innerText = emotions[index];
    }
})();
`

tfjs-node code (doesn't work)
`const tf = require('@tensorflow/tfjs-node');
const st = require('../tools/preprocess.js');
async function fetch(sentence) {
    // Load model
    console.log('Loading model...');
    const model = await tf.loadLayersModel(
        'http://127.0.0.1:3000/models/model.json'
    );

    // Define emotions
    emotions = ['disgust', 'sadness', 'shame', 'joy', 'guilt', 'fear', 'anger'];
    // Tokenize
    const tweet = await st.preprocess(sentence);
    // Create a tensor
    // TODO Fix this block
    const inputData = tf.tensor2d(tweet, [1, 350]);

    // // Predict
    const result = model.predict(inputData).dataSync();
    let index = result.indexOf(Math.max(...result));
    //return emotions[index];

    // Find index of the highest probability

    // Show all predictions with their probabilities
    for (let i = 0; i < emotions.length; i++) {
        console.log(emotions[i], (result[i] * 100).toFixed(2) + '%');
    }
    // Get index of highest result

    console.log(
        `Results: ${emotions[index]} with ${(result[index] * 100).toFixed(2)}%`
    );
}
module.exports = { fetch };
`

**Comment by elizabethsiegle** [comment]
Hi! I am having the same error with words not in the dictionary

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
