### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by AlokTakshak** [tensorflow/tfjs#1710]
before `train` method we are using `async` but we are `not using await`  anywhere in train method

**Comment by tafsiri** [comment]
Could you post a link to the page you are looking at? I am looking at https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#5 and see `await` in `trainModel` (right after `return`).

**Comment by AlokTakshak** [comment]
> Could you post a link to the page you are looking at? I am looking at https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#5 and see `await` in `trainModel` (right after `return`).

https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#5

**Comment by tafsiri** [comment]
In this case we return the promise from model.fit and allow the caller to await the result. The async marker is not needed but is a nice indication that a promise is returned/an async function is called within the body. Thanks for the report though.
