### ISSUE TITLE
Polyfill or workaround browser `performance` API in non-browser envs for WebGL backend

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1711]
When running the WebGL backend outside of the browser, we need to whitelist or polyfill the `performance` API. This causes an issue when running under Node.js (there is no performance).

Might be good to have an interface or a provider for this.

**Comment by dsmilkov** [comment]
We have to replace all instances of `performance.now()` in tfjs-core with `util.now()`, which we added for this purpose and works in both node and browser.

**Comment by tafsiri** [comment]
I think we also need to fallback to `Date.now()` if `performance` is not present in `util.now()`. For things that are neither browser nor node.

**Comment by nsthorat** [comment]
I never did this but we should put now() on Platform and override it, having util.now() call it. But calling util.now() for now should work.

**Comment by gaikwadrahul8** [comment]
Hi, @nkreeger 

Apologize for the delayed response and It seems like this issue has been taken care after this PR [#1825](https://github.com/tensorflow/tfjs-core/pull/1825) got merged and even we have updated our official documentation w.r.t [tf.util.now](https://js.tensorflow.org/api/latest/#util.now) which `Returns the current high-resolution time in milliseconds relative to an arbitrary time in the past. It works across different platforms (node.js, browsers).` If have I missed something here please let me know ? Thank you!

**Comment by pyu10055** [comment]
This issue has been fixed.
