### ISSUE TITLE
Migrate tfjs-node backend to use bytes for strings

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#1713]
With https://github.com/tensorflow/tfjs-core/pull/1816, string tensors are stored encoded as bytes using `Uint8Array[]` in the backend.

We need to migrate the tfjs-node backend to align with this and be compatible with latest tfjs-core.

**Comment by TheNewSound** [comment]
+ add possibility to cast 'string' tensor to 'int' tensor?

Example: I load up a string and want to convert uppercase to lowercase:
```
let t=tf.tensor([["ammmmmmmmmmmmmmmmmmmmmmmmz"], ["AZ"]],[2,1],'string');
t.print();
let b = tf.scalar(97);
let c = t.asType('int32').greaterEqual(b);
let d = c.asType('int32').mul(32);
b.sub(d).print();
```

**Comment by dsmilkov** [comment]
Will close this issue since it was fixed in https://github.com/tensorflow/tfjs-node/pull/279

Regarding the question, can you try using plain JS [`String.toLowerCase`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)? If that doesn't fit you need, feel free to file another issue.
