### ISSUE TITLE
502 on posenet/mobilenet_v1_050/manifest.json

### ISSUE THREAD

**Issue by akeiper** [tensorflow/tfjs#1716]
This morning I started to receive a 502 for the following request:

```
Request URL: https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_050/manifest.json
Request Method: GET
Status Code: 502 
```

I am currently including posenet version 1.0.3:

```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet@1.0.3"></script>
```

**Comment by tafsiri** [comment]
@akeiper are you still getting this error? It seems to be resolving for me, so may have been a networking blip.

**Comment by akeiper** [comment]
@tafsiri seems to be working for me now. thanks for looking into the issue.
