### ISSUE TITLE
fromPixels produces different results in WebGL / CPU if the image element has to be resized.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1719]
WebGL directly uploads the image element to a texture which creates artifacts, while CPU first renders to a canvas. 

We should investigate rendering to a canvas in the WebGL backend, or playing with image rendering CSS rules to remove the artifacts. 

Related: #1488

**Comment by jessetrana** [comment]
Any idea what kind of overhead the extra render might create?
