### ISSUE TITLE
Firefox and Safari mnist example runtime errors.

### ISSUE THREAD

**Issue by merpnderp** [tensorflow/tfjs#172]
#### TensorFlow.js version 
0.8.0

#### Browser version 
Firefox 60.0b11
Safari 11.1

#### Describe the problem or feature request
In the mnist example I get an error on run in both Safari and Firefox.

In Safari I get Unhandled Promise Rejection: TypeError: Type error in runtime:566

In Firefox I get "message: "'mode' member of RequestInit 'arraybuffer' is not a valid value for enumeration RequestMode."" in tfjs-examples-mnist.js line: 27561

#### Code to reproduce the bug / link to feature request
I'm using the latest github clone for tfjs examples built with yarn and node 8.11.1

**Comment by tafsiri** [comment]
Thanks for reporting this @merpnderp. We'll take a look.
