### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by moona3k** [tensorflow/tfjs#1722]
#### Inconsistency in tutorial content

**Link**: https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#5

There is a seeming discrepancy for **batchSize** value. The copy & paste code section and explanation section display different values.

It's something very minor/trivial and does not break the flow of tutorial.
Below are the screenshots with red highlights.

![Screen Shot 2019-07-04 at 4 11 12 PM](https://user-images.githubusercontent.com/32221114/60689863-f5485a80-9e76-11e9-846c-ea8706233172.png)
![Screen Shot 2019-07-04 at 4 13 24 PM](https://user-images.githubusercontent.com/32221114/60689864-f5485a80-9e76-11e9-9ad1-c3653c4f3efa.png)

**Comment by tafsiri** [comment]
Thanks! Fixed.
