### ISSUE TITLE
Support for Mfcc, DecodeWav, AudioSpectrogram

### ISSUE THREAD

**Issue by bayartsogt-ya** [tensorflow/tfjs#1728]
Hey thank you for the great work guys!

#### TensorFlow.js version: 0.5.6
I want to know if I can convert the pb model which was originally created by the [repo here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands) and shared on [official website](https://www.tensorflow.org/tutorials/sequences/audio_recognition)

After I used conversion from frozen graph, the following error has appeared:
```
ValueError: Unsupported Ops in the model before optimization
Mfcc, DecodeWav, AudioSpectrogram
```
Is it possible that I can convert this model into tfjs one?

**Comment by robinhad** [comment]
I tried to convert DeepSpeech model to tfjs, but get the same result:
`
ValueError: Unsupported Ops in the model before 
Mfcc, AudioSpectrogram, BlockLSTM
`

**Comment by rthadur** [comment]
This is still a future request , for now we do not have specific timeline.

**Comment by rlleshi** [comment]
Any plans for this?

**Comment by JRMeyer** [comment]
+1 to adding these Ops

**Comment by gaikwadrahul8** [comment]
Hi, @bayartsogt-ya 

Apologize for the delayed response and Could you please try with latest version of `tensorflowjs 4.4.0` and check whether this issue got resolved or not ? if not are you still looking for this feature ? Thank you!
