### ISSUE TITLE
Mysteriously slow performance using pre-trained VGG16 with WebGL backend

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tfjs#1736]
#### TensorFlow.js version
1.1.0, WebGL backend

#### Browser version
Chrome/Observable, on Ubuntu 16.04 with Nvidia GTX 1060

#### Describe the problem or feature request

I am getting some very mysterious performance using a pre-trained VGG16 model (forward pass only with the dense layers removed). The following timing results are showing that VGG16 is almost 2x *slower* than resnet50 for 256x256 resolution and over 100x slower than resnet50 for 512x512 resolution:

```
vgg_256x256: 109.79ms

vgg_512x512: 18136.97ms

resnet_256x256: 66.15ms

resnet_512x512: 115.42ms
```
None of this is making any sense, since VGG16 with no dense layers should be faster then Resnet50. What is causing the massive performance slow down at 512x512 resolution for VGG16?

#### Code to reproduce the bug / link to feature request

To reproduce, see the following [observable notebook](https://observablehq.com/@evancasey/benchmarking-mobilenet-in-tensorflow-js/2).

**Comment by evancasey** [comment]
Note that these pret-trained models are from `tf.keras.applications`. Here is example code to create the saved models:

```class CustomModule(tf.Module):

    def __init__(self):
        super(CustomModule, self).__init__()
        # self.net = tf.keras.applications.VGG16(include_top=False, weights='imagenet')
        self.net = tf.keras.applications.ResNet50(include_top=False, weights='imagenet')

    @tf.function
    def __call__(self, x):
        return self.net(x)

module = CustomModule()

_call = module.__call__.get_concrete_function(tf.TensorSpec([None, 256, 256, 3], tf.float32))
tf.saved_model.save(module, "../models/saved_models/resnet_256x256", signatures=_call)

_call = module.__call__.get_concrete_function(tf.TensorSpec([None, 512, 512, 3], tf.float32))
tf.saved_model.save(module, "../models/saved_models/resnet_512x512", signatures=_call)```

**Comment by annxingyuan** [comment]
Hi @evancasey - thanks for pointing this out - I'm also surprised by these results. I did some profiling and it turns out that while there are fewer kernels in VGG compared with ResNet, there are a few extremely costly convolutions in VGG that I think explain the slowdown. For example, the slowest op in VGG is a conv with output size 512x512x64, which is 4x larger than the largest conv output in ResNet.

I'm pretty surprised to see that VGG 512 takes 18 seconds for you though... my numbers are similar to yours for the other 3 models, but for VGG 512 I'm getting around 1.8 seconds. I'm testing in Chrome on my 2018 Macbook Pro.

**Comment by evancasey** [comment]
Hi @annxingyuan, thanks for getting back to me. Your analysis of the VGG slowness being related to the 512x512x64 conv op makes sense but I don't think it explains the full picture of what is going on here.

I re-ran this again on my ubuntu machine and got the following numbers:

```
vgg_256x256: 103.39ms

vgg_512x512: 1969.33ms

resnet_256x256: 53.16ms

resnet_512x512: 117.67ms
```

The  `vgg_256x256` is about 2x as slow as `resnet_256x256` -- this makes sense if we take into account your point about the larger conv output. But what about the fact that `vgg_512x512` is 20x as slow as `resnet_512x512`? Seems like there is something -- possibly related to memory or the size of the input image -- that is causing things to go awry here.

Are you seeing the same amount of performance discrepancy between the 256x256 and 512x512 VGG versions?

**Comment by annxingyuan** [comment]
Hi @evancasey 

On my Macbook Pro VGG 512 is about 10x slower than Resnet 512. It looks like the slowest op in VGG is a convolution with the following inputs:

```
x: [1, 256, 256, 128]
w: [3, 3, 128, 128]
stride: 1
pad: 'same'
```

The slowest op in Resnet 512 is a convolution with the following inputs:

```
x: [1, 518, 518, 3]
w: [7, 7, 3, 64]
stride: 2
pad: 'valid'
```

When I profile these ops in isolation I see that the VGG convolution is about 10x slower than the Resnet one.

Do you know about our benchmarking page? https://github.com/tensorflow/tfjs-core/blob/master/benchmarks/index.html

There's a spot in the code for you to swap out your own model - this page will give you a breakdown of which ops are taking up the most time.

**Comment by evancasey** [comment]
@annxingyuan cool, I didn't know about the benchmarking page. Will use that in the future for issues like this.
