### ISSUE TITLE
Some methods are ...Crossentropy and others are ...CrossEntropy

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1743]
In https://js.tensorflow.org/api/latest/

There is for example

https://js.tensorflow.org/api/latest/#metrics.binaryCrossentropy
and
https://js.tensorflow.org/api/latest/#losses.sigmoidCrossEntropy

**Comment by bileschi** [comment]
Thanks for the report!
Based on the relationship to python Keras, the "Crossentropy" (one word) should be correct).  @caisq to verify.
https://github.com/tensorflow/tfjs-layers/pull/564

**Comment by bileschi** [comment]
Proposed fix:
`sigmoidCrossEntropy` gets renamed to `sigmoidCrossentropy`
and a shim `sigmoidCrossEntropy` symbol is added which points to `sigmoidCrossentropy`
We add a TODO to remove `sigmoidCrossEntropy` at the 2.0.0 breaking change.

**Comment by caisq** [comment]
Yes, we've been trying to be consistent: "Crossentropy" should be treated as a single word when doing snake and camel cases in the layers API. This is indeed the case for the string-represented 'sigmoidCrossentropy' in the tf.LayersModel.compile() API.

I think the `tf.losses.sigmoidCrossEntropy` predates the layers API. For consistency, we should deprecate the old one and create `tf.losses.sigmoidCrossentropy`.

**Comment by bileschi** [comment]
The root of the misalignment comes from the difference between Keras and TensorFlow.  Keras spells crossentropy with one word, while TensorFlow spells cross_entropy with two.

See additional discussion in closed PR tensorflow/tfjs-core#1843

**Comment by bileschi** [comment]
Note that the incongruity exists within TensorFlow itself.

See:

    tf.keras.binary_crossentropy
    tf.nn.sigmoid_cross_entropy_with_logits
