### ISSUE TITLE
Behaviour of SSDLite MobileNet V2 on Android (WebGL)

### ISSUE THREAD

**Issue by msektrier** [tensorflow/tfjs#1744]
I hope it is fine that we create a new issue but we are exercising a lot with TF, TFJS and the TFJS converter and maybe somebody finds the results useful. 

In a previous issue it was discovered there are different prediction values on Pixel and Sony Xperia Z1. We illustrated the issue. Left it is running on the Sony Xperia XZ1 in Chrome's remote debug mode and left on my notebook in browser mode. Web host is an nginx running on a notebook.

![compare](https://user-images.githubusercontent.com/49950048/60524586-1da44d80-9ced-11e9-85a6-7744c14ce905.jpg)

What we recognized is that the **MAX_TEXTURE_SIZE** on the mobile device is lower than on the notebook. It was the only difference we could find in **tf.ENV**. Partially, the execution of the model in the mobile Chrome browser also lead to the error message ["Requested texture size 4800*4736 greater than webGL maximum on this browser 4096 * 4096"](https://github.com/tensorflow/tfjs/issues/689) in case the image was even bigger. 

We could **solve the prediction** by reducing the resolution of the input image. Then it worked well on the Sony Xperia. However, we don't know the relationship between the box prediction of the network and the resolution of the input image. 

Moreover, we faced a strange - but positive - behaviour using WebGL (with WEBGL_PACK disabled). As reported and confirmed here(https://github.com/tensorflow/tfjs/issues/1715) we are facing issues with the WebGL warm up phase.

* On i7 notebook ~ 10seconds
* On chrome browser of Sony Xperia Z1 ~ 10seconds
* On cordova APK file on Sony Xperia Z1 ~ <1second

Running the web app inside a Apache Cordova container is the first time we saw normal Load times.

We would be interested in understanding the impact of the image resolution and the prediction results and we are still surprised about the working WebGL warm up phase. 

_Originally posted by @msektrier in https://github.com/tensorflow/tfjs/issues/1586#issuecomment-507726799_

**Comment by msektrier** [comment]
After some more investigation we have to state that the wrong prediction values on the Sony Xperia XZ1 may result from a programmatic error.

We load the image from a HTML canvas before we convert it with `tf.browser.fromPixels()`.

```
let canvas = uploadedCanvas[i];
let base64 = canvas.toDataURL('image/jpeg', 1);
		
let tmpImg = new Image();
tmpImg.src = base64;
tmpImg.width = canvas.width;
tmpImg.height = canvas.height;
```

We were inputting `tmpImg` in 

```
const batched = tf.tidy(() => {
      if (!(img instanceof tf.Tensor)) {
        img = tf.browser.fromPixels(tmpImg);
      }
	  const resized = tf.image.resizeBilinear(img, [1000, 1000]).toInt();
      // Reshape to a single-element batch so we can pass it to executeAsync.
      return resized.expandDims(0);
    });
```

and `batched` was consisting only of zeros but with the right shape. With inputting the canvas it worked. However, we have no clue why it was not working with the created image. We also tried to append the image into the DOM because it should calculate other values like naturalWidth or naturalHeight but the computed tensor consisted only of zeros.

**Comment by rthadur** [comment]
@msektrier thank you , did you check what values you are getting for `tmpImg.width , height` before  inputing ?

**Comment by msektrier** [comment]
@rthadur if the `canvas` was (width 500/ height 500) then the `tmpImg` was also (500/500) and the shape of the created tensor was also 500/500 but filled with zeros only.

**Comment by kangyizhang** [comment]
hi @msektrier , I can successfully load pixel value from HTMLImageElement/HTMLCanvasElement/ImageData. Can you make sure that the dom element is loaded and the canvas is not tainted by cross-origin data?

**Comment by msektrier** [comment]
Mhh strange. I was appending it to the DOM as well and I was waiting until it was finally rendered (visually). I guess CORS should not be a problem here, since I upload the file from my computer. A simple JavaScript upload. 
Basically I can load from an image as well but here the process is: File Upload > Canvas (Base64) > new Image(of Canvas) and it was not working. Since the correct shape was recognized I thought the colors of the pixels should also load.
