### ISSUE TITLE
Missing docs for tf.io.browserHTTPRequest in tfjs 1.1.2

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1746]
#### TensorFlow.js version
1.1.2

#### Describe the problem or feature request

https://js.tensorflow.org/api/latest/#tf.io.browserHTTPRequest is not present in docs for tfjs 1.1.2. But is referenced in other parts of the docs and in the [saving and loading guide](https://www.tensorflow.org/js/guide/save_load#loading_models_with_iohandlers). The code says it has been deprecated in favour of another method, but it should probably still show up in the docs.

**Comment by tafsiri** [comment]
reported in https://github.com/tensorflow/tfjs-website/pull/316

**Comment by bileschi** [comment]
https://github.com/tensorflow/tfjs-layers/pull/564

**Comment by rthadur** [comment]
Thank you all , since the PR is merged i will be closing this issue, feel free to reopen.
