### ISSUE TITLE
how to make index in tfjs like python :  such as : boxes[:, :, 0]

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tfjs#1753]
how to make index in tfjs like python :  such as : boxes[:, :, 0]

**Comment by kangyizhang** [comment]
hi @aohan237  

are you trying to index in tensor or array?

**Comment by aohan237** [comment]
@kangyizhang  yes, it seems that there is no way to do this

**Comment by aohan237** [comment]
and such method as tf.meshgrid does not exist in tfjs, which makes hard to impl some custom layer in tfjs from python model

**Comment by aohan237** [comment]
@kangyizhang  @rthadur  is there any solution about this? thanks in advance

**Comment by WenheLI** [comment]
@aohan237 - For the `index in tensor or array` thing,I think you can use [TensorBuffer](https://js.tensorflow.org/api/0.11.2/#buffer) to achieve. 

Also, one possible workaround regarding with pythonic index would be using babel to overwrite the [] operator. But I did not see any babel plugin serves for that aim. 

Hope that gives you some clue.

**Comment by caisq** [comment]
@aohan237 There is no support for Python-style slicing in TensorFlow.js's Tensor of TensorBuffer at this moment.

However, something like `boxes[:, :, 0]` can be achieved using `tf.gather()`, e.g., `tf.gather(boxes, 0, 2)`, or equivalently `boxes.gather(0, 2)`. In both cases, the argument (`0`) is the index along the last dimension, and the argument (`2`) refers to the 3rd dimension.

**Comment by aohan237** [comment]
@caisq  thanks. i will try.

and there is someting missing in tfjs . meshgrid, for example in tfpy, but not found in tfjs

**Comment by aohan237** [comment]
@caisq  and what if i want a boxes[:, :, 2:4], gather cant do this..

how can i get this?

**Comment by caisq** [comment]
@aohan237 Questions like this might be more suitable for StackOverflow, under the tag "tensorflow.js":
https://stackoverflow.com/questions/tagged/tensorflow.js

For `boxes[:, :, 2:4]`, you can use `tf.slice()`, although it's slightly tedious.

```
tf.slice(boxes, [0, 0, 2], [boxes.shape[0], boxes.shape[1], 4]);
```

Also, feel free to file a feature request issues for meshgrid.

**Comment by aohan237** [comment]
@caisq  Thanks, use tf.slice can make this, although it is not that user-friendly.

and a small suggestion:
if something needs one to find out how to impl an function from your api docment, may be add something example to the doc for people to find out.
such as : add the following to the beginner guides(from python) 

> For boxes[:, :, 2:4], you can use tf.slice().
`tf.slice(boxes, [0, 0, 2], [boxes.shape[0], boxes.shape[1], 4]);`

all new people will know it, rather than try to find out how to use this.
