### ISSUE TITLE
[tfjs-converter] @tensorflow/tfjs 1.2.3 fails to load weights from the official GCP bucket due to CORS issues

### ISSUE THREAD

**Issue by sdll** [tensorflow/tfjs#1755]
#### TensorFlow.js version
1.2.3 & 1.2.2

#### Browser version
Chrome Version 77.0.3854.3 (Official Build) dev (64-bit)
FireFox 69.0b4 (64-bit)

#### Bug report

[Here](https://github.com/sdll/tfjs-converter-cors-issues) is a minimalistic repo showing the bug.

Loading one of the PoseNet weights in the `erroring` demo fails with:

```
Access to fetch at 'https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/quant2/100/group1-shard2of2.bin' from origin 'http://localhost:1234' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Both Chrome and FireFox allow the JSON file, but deny the loading of the model chunks. Using [CORS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) helps in FireFox.

This issue was first spotted in the context of [semantic segmentation](https://github.com/tensorflow/tfjs-models/pull/229) and [text detection](https://github.com/tensorflow/tfjs-models/pull/274) models loading weights from a non-official GCP bucket with the following CORS rules suggested by @nsthorat [here](https://github.com/tensorflow/tfjs/issues/89#issuecomment-378601628):

 ```json
[
  {
    "origin": ["*"],
    "responseHeader": ["Content-Type"],
    "method": ["GET", "HEAD"],
    "maxAgeSeconds": 3600
  }
]
```

I have tried imposing other rules as well, as described [here](https://github.com/tensorflow/tfjs-models/pull/229#pullrequestreview-263032882), but the issue persists.

**Comment by erikcartman** [comment]
I try to use posenet. In my case it works for localhost but fails for test deployment on azure.
I cant download from https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/quant2

**Comment by sdll** [comment]
@erikcartman, could you please post the local copy of your working `yarn.lock` in a gist?

**Comment by sdll** [comment]
@erikcartman, thank you! You are using `@tensorflow/tfjs` v. 1.2.2 locally. You might hack around this bug by [pinning](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json) it to match 1.2.2 exactly in `package.json` (pinning `@tensorflow/tfjs-core` and `@tensorflow/tfjs-converter` as well).

**Comment by erikcartman** [comment]
@sdll actually, yes, thanks

**Comment by kangyizhang** [comment]
hi @sdll @erikcartman 

This is a bug in tfjs@1.2.3 and we will fix it soon.

**Comment by nsthorat** [comment]
Loading from the official buckets should work now. I'm reverting a change that will fix this for any custom server.
