### ISSUE TITLE
Where is "/homepage/assets/support.js" in  demo of tfjs-core?

### ISSUE THREAD

**Issue by wdl000001** [tensorflow/tfjs#176]
In every demo's file "index.html", there's a line of code: 
` <script src="../homepage/assets/support.js"></script>`
But I can't find the path “homepage”

**Comment by tafsiri** [comment]
@wdl000001 The demos in tfjs-core are deprecated and we are in the process of deleting/migrating them which is probably why that file is missing. Our new examples are at https://github.com/tensorflow/tfjs-examples. Sorry for the confusion we will be cleaning that up soon.
