### ISSUE TITLE
Decrease compute capability limit.

### ISSUE THREAD

**Issue by erikcartman** [tensorflow/tfjs#1765]
#### Tensorflow
    "@tensorflow-models/posenet": "^2.1.2"
    "@tensorflow/tfjs-node-gpu": "^1.2.4"

#### OS
Linux (Ubuntu)

#### Describe the problem or feature request
I use posenet from nodejs backend.
In windows 10 960 GTX gpu with 5.2 compute capability not ignored even if its compute capability below 6.0 limit and estimates poses at decent speed. But on linux Tesla M60 with same compute capability  is ignored.
`2019-07-22 08:25:40.278513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1717] Ignoring visible gpu device (device: 0, name: Tesla M60, pci bus id: 2dc0:00:00.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.`
Is it possible to decrease this limit? because there is huge difference for vm pricing for Tesla M60 vs Tesla P100

**Comment by kangyizhang** [comment]
hi @erikcartman 

This is a configuration in [core Tensorflow GPU](https://github.com/tensorflow/tensorflow/blob/a5780f657ff44c00d0182a4ac0ed321202d0a187/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1697) and we can not configure it.
