### ISSUE TITLE
Add dynamic_partition

### ISSUE THREAD

**Issue by Lewuathe** [tensorflow/tfjs#1768]
As TensorFlow core has `dynamic_partition`, TensorFlow.js can have the ops.
This op is necessary to implement a clustering algorithm such as K-means. Without this op, we are enforced to download the index data every iteration to update the centroids.

See: https://www.tensorflow.org/api_docs/python/tf/dynamic_partition

**Comment by gaikwadrahul8** [comment]
Hi, @Lewuathe 

Apologize for the delayed response and It seems like we haven't implemented this feature as of now so if you're looking to contribute for this feature then please refer this [link](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md)

May I know are you looking to implement this feature from our end ? Thank you!
