### ISSUE TITLE
For toxicity (and others too) model, is it possible to train the model with additional word set ?

### ISSUE THREAD

**Issue by ahsan87** [tensorflow/tfjs#1769]
Is it possible to train the models with additional word set ?

https://github.com/tensorflow/tfjs-models/tree/master/toxicity

Thanks.

**Comment by rthadur** [comment]
@ahsan87 yes you can use own data set.

**Comment by ahsan87** [comment]
I am not sure how to do it, any pointers ? @rthadur

**Comment by annxingyuan** [comment]
Hi @ahsan87 - you won't be able to retrain the toxicity model in JS - however here is the Python code that was used to train the model: https://github.com/conversationai/conversationai-models/tree/master/experiments

For more information on how to extend the toxicity model, you might refer to this blogpost: https://medium.com/tensorflow/text-classification-using-tensorflow-js-an-example-of-detecting-offensive-language-in-browser-e2b94e3565ce
