### ISSUE TITLE
[integration_tests] Browser benchmarks fails due to node-pre-gyp and aws-sdk

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1770]
Step to reproduce:
1. Checkout the tfjs (union) repo at head
2. cd integration_tests
3. yarn benchmark --layers

Notice the error message:

23 07 2019 10:54:53.444:ERROR [karma-server]: Error: Unable to resolve module [aws-sdk] from [.../tfjs/tfjs/integration_tests/node_modules/node-pre-gyp/lib/unpublish.js]

**Comment by rthadur** [comment]
closing this as the related PR has been merged. Thank you
