### ISSUE TITLE
Support for MirrorPad

### ISSUE THREAD

**Issue by vbardiovskyg** [tensorflow/tfjs#1775]
We were trying to convert a Magenta -> TF Hub module -> tfjs.

**Comment by rthadur** [comment]
Hi @pyu10055 any plans to support MirrorPad ?

**Comment by qzcsgs** [comment]
Hi @pyu10055 any plans to support MirrorPad ?

**Comment by qzcsgs** [comment]
Hi @pyu10055 any plans to support MirrorPad ?

**Comment by qzcsgs** [comment]
@rthadur How to replace MirrorPad in the generated model with other pad

**Comment by TomLuna** [comment]
Any progress on this issue? We have a model for image processing, MirrorPad handles the borders pretty good so we can't replace it with other pads or work arounds easily as #936.

**Comment by rthadur** [comment]
@pyu10055 gentle ping , 
CC @kangyizhang

**Comment by qzcsgs** [comment]
tensorflowjs MirrorPad
https://github.com/qzcsgs/tfjs-MirrorPad

**Comment by gkcalat** [comment]
@vbardiovskyg if this is still an issues, I successfully converted the Magenta model from tf.hub into tf-js:

**1. Convert the model checkpoint to tfjs:**

`tensorflowjs_converter --control_flow_v2=True --input_format=tf_hub --skip_op_check --strip_debug_ops=True --signature_name serving_default https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2 ./models/magenta_tfjs`

**2. Copy-paste this snippet into your .js or .html (within <script></script>):**
https://github.com/gkcalat/mirrorpad-tfjs/blob/master/mirrorpad.js
