### ISSUE TITLE
tfjs-converter "NonMaxSuppression" unsupported op

### ISSUE THREAD

**Issue by blechatellier** [tensorflow/tfjs#1783]
Trying to convert a [frozen model](https://github.com/yeephycho/tensorflow-face-detection/blob/master/model/frozen_inference_graph_face.pb) using `tfjs-converter 0.8.6` as per the documentation.

Getting an error about an unsupported op:
```
ValueError: Unsupported Ops in the model before optimization
NonMaxSuppression
```
I can see that `NonMaxSuppression` should be supported from the list of [supported ops](https://github.com/tensorflow/tfjs-converter/blob/0.8.x/docs/supported_ops.md).

Is there something obvious I'm missing?

**Comment by rthadur** [comment]
@blechatellier thank you , did you try with latest version of `tfjs-converter ?`

**Comment by pyu10055** [comment]
@blechatellier This an older version of NonMAxSuppresion, are you using a existing saved model, if not what version of TF you are using to generate this saved model?

**Comment by blechatellier** [comment]
@rthadur I haven't tried the latest version as it doesn't support frozen models anymore, this is the command I used on the following model https://github.com/yeephycho/tensorflow-face-detection/blob/master/model/frozen_inference_graph_face.pb

```
tensorflowjs_converter \
    --input_format=tf_frozen_model \
    --output_json=true \
    --output_node_names='detection_boxes,detection_scores,num_detections,detection_classes' \
    --saved_model_tags=serve \
    frozen_model.pb \
    tfjs
```

@pyu10055 that would make sense, this frozen model is already pre-trained but almost 2 years old. Should I retrain and export a new model with the latest version of tensorflow to support those ops?

**Comment by pyu10055** [comment]
@blechatellier yes, if you can retrain the model, and save it as saved model would be much better. Since even if we supported this op, it will be in the new converter, where the frozen model would not be supported.
