### ISSUE TITLE
#1844 is causing test failure in tfjs-layers

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1788]
When tfjs-layers tests are run against HEAD of tfjs-core currently (through yalc linking), about 18 tests fail, e.g., 

"loadLayersModel from URL cpu undefined pathPrefix=. "

The test passes against latest release of tfjs-core (1.2.6), though. I bisected the issue and located the culprit at https://github.com/tensorflow/tfjs-core/pull/1844. 

The cause seems to be changes to `util.fetch`. Let's discuss this @tafsiri .

**Comment by tafsiri** [comment]
@caisq I'll take a look/ping you when back in the office. The API of util.fetch hasn't changed but platform.fetch was changed to take an extra optional parameter.
