### ISSUE TITLE
tfjs-converter: Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by Resin01** [tensorflow/tfjs#1789]
#### TensorFlow.js version
1.2.6

#### Browser version
N/A

#### Describe the problem or feature request
If I install "@tensorflow/tfjs": "^1.2.6", first and then try to install anything else afterwards using npm install xxx, I get an error:
{path}/node_modules/@tensorflow/tfjs-converter: Appears to be a git repo or submodule

#### Code to reproduce the bug / link to feature request
Install tensor flow and then try installing some other package afterwards

**Comment by ababbdev** [comment]
If anyone needs to get it working in the meantime you can remove the .git folder.
`rm -rf ./node_modules/\@tensorflow/tfjs-converter/.git/`

**Comment by MongoExpUser** [comment]
**@ababbdev**,
I ran into the same problem. I think your suggested solution above solves the problem with a minor typo *correction**:

remove the **\** before **@tensorflow**. So the edited solution is:

**rm -rf ./node_modules/@tensorflow/tfjs-converter/.git/**

**Then remove the package(s):**
sudo npm uninstall @tensorflow/tfjs 
sudo npm uninstall @tensorflow/tfjs-node 
sudo npm uninstall@tensorflow/tfjs-node-gpu 

**And re-install:**
sudo npm install @tensorflow/tfjs 
sudo npm install @tensorflow/tfjs-node 
sudo npm install @tensorflow/tfjs-node-gpu

**Comment by ababbdev** [comment]
Ah yeah that would be my terminal I had to escape the @

**Comment by MongoExpUser** [comment]
@ababbdev,
Ok. Thanks..

**Comment by rthadur** [comment]
there will be a fix pushed out soon , thank you everyone

**Comment by rthadur** [comment]
Here is the [fix](https://github.com/tensorflow/tfjs-converter/pull/406)

**Comment by ababbdev** [comment]
Thank you.
