### ISSUE TITLE
Cors Policy issue - tensorflowjs teacheable machine learning algorithm

### ISSUE THREAD

**Issue by reemawits** [tensorflow/tfjs#1790]
Hello, 
We are trying to execute tensor flow Javascript machine learning algorithm wherein we are getting CORS Policy issue.
Below URL referred - 
https://codelabs.developers.google.com/codelabs/tensorflowjs-teachablemachine-codelab/index.html#0

Please note : Few days back it was running successfully but from last two days it is throwing CORS issue.

Refer attachment
![TensorFlowGlitchError](https://user-images.githubusercontent.com/53085488/61536159-99bec500-aa51-11e9-83f4-ba7766aa5f5a.JPG)

Request you to assist

**Comment by dsmilkov** [comment]
This was fixed in https://github.com/tensorflow/tfjs-core/pull/1848 and the fix is available in the latest release. Thus closing this issue. Let me know if you still run into this problem with the latest version (1.2.6).

**Comment by rthadur** [comment]
Thank you @dsmilkov
