### ISSUE TITLE
tensorflow-node-gpu@1.2.5  Cannot find module '@tensorflow/tfjs-core/dist/backends/backend'

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tfjs#1791]
tensorflow-node-gpu@1.2.5  Cannot find module '@tensorflow/tfjs-core/dist/backends/backend'

try to install tensorflow-node-gpu@0.2.2,but it shows cant find libtensorflow, but i have extract the libtensorflow on /usr/local/lib as libtensorflow's instructions, and sudo ldconfig

so ,what is this problems?  thanks in advance

**Comment by kangyizhang** [comment]
@aohan237 we just published tensorflow-node-gpu@1.2.6, you can give it a try.

**Comment by aohan237** [comment]
thanks. i will try.
@kangyizhang  another question.  i use tfjs-converter to transform tfpy model, the output gets lots  of unused_control_flow_input members,which cant be used.  why,what should i do with these models? 

 tfjs-converter or tfjs also has some version problems,i dont know which version of tfjs-converter or tfjs version to use, in corresponding to the python version.

and tfjs-converter has no trouble shooting and no faq.  it really cant be used by others.

**Comment by aohan237** [comment]
1.2.6 still has the problem
Cannot find module '@tensorflow/tfjs-core/dist/backends/backend'

**Comment by kangyizhang** [comment]
hi @aohan237 , can you provide more details?

1. tfjs-node-gpu
I can not reproduce this error. How did you use the package? Are you building your own model or loading a model? Which function cause this error? 
If you clone this package, then run 1) `yarn` 2) `yarn enable-gpu` 3) `yarn test, do you see any failing test?

2. tfjs-converter
tfjs does not support all tf python ops. See [this](https://github.com/tensorflow/tfjs-converter#supported-operations). You can file issues with your use case to request missing ops.

The latest tfjs-converter support both tensorflow 1.0 and 2.0 models. You should create a docker or virtual environment and [tf-nightly-2.0-preview](https://pypi.org/project/tf-nightly-2.0-preview/#files) to convert your model.

If your model is Session bundle or Frozen model formats, which have been deprecated in TensorFlow.js 1.0, you should use the TensorFlow.js 0.15.x backend and tfjs-converter@0.8.6 to convert your model.

You can get more information in tfjs-converter [readme](https://github.com/tensorflow/tfjs-converter#getting-started).

**Comment by aohan237** [comment]
@kangyizhang  thanks for your so detailed information.

1. tfjs-node-gpu.
    i use a lib ,which use tfjs-core@0.14.2 to impl a yolov2 model.  
    i try to train my own model use nodejs. 
    i use tfjs-node@0.2.2 to speed up the training.
    then  i want to use tfjs-node-gpu to gen more speed.  but tfjs-node-gpu@0.2.2 seems that dont work, the training back to pure js ,which is much slower than tfjs-node.  so i install the latest tfjs-node-gpu, then the exception as above.
 

2. tfjs-converter

i follow the instruction: 
 `https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd#technical-details-for-advanced-users` 

it shows that it just use the specific model to tfjs, so i want to reproduce it.

i download the model and installed the tfjs-converter@0.8.* but it does not work as it said.
so i install the latest tfjs-converter, and tranform the model again.
the process runs well, but the result model can not use ,as it gens so much unused_control_flow_input.

maybet i will try tf-nightly-2.0-preview.

**Comment by kangyizhang** [comment]
@aohan237 

1. tfjs-node
Both tfjs-node and tfjs-node-gpu have peer dependency on tfjs-core, so the latest version of tfjs-node/tfjs-node-gpu might have exception with mismatch version of tfjs-core. So you should keep using tfjs-node@0.2.2 or tfjs-node-gpu@0.2.2. 

tfjs-node-gpu requires cuda drivers and cudnn, you can find more information in this [link](https://www.tensorflow.org/install/gpu). Please note for tfjs-node-gpu@0.2.2 it should be CUDA 9.0 and CUDNN 7.1, not the version listed in the link (those are for the latest tensorflow gpu). Feel free to file issue if you met any error.

2. tfjs-converter
The latest tfjs-convert has strict version requirement, make sure you are using the correct one.

**Comment by aohan237** [comment]
@kangyizhang  thanks. i now know the tfjs-converter version requirement.

maybe most of the problem is the version thing.
