### ISSUE TITLE
Error passing tfvis.show.fitCallbacks AND tf.callbacks.earlyStopping as callbacks option to fit 

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1792]
#### TensorFlow.js version
1.2.6
#### Browser version
Version 76.0.3809.87 (Official Build) (64-bit)
#### Describe the problem or feature request
I can pass either tfvis.show.fitCallbacks or tf.callbacks.earlyStopping as callbacks option to fit as an Array (with one element) but when I pass both an error results. Depending upon the order of the callbacks the error is either

Uncaught (in promise) TypeError: this.getMonitorValue is not a function
    at e.<anonymous> (tfjs@latest:2)
    at tfjs@latest:2
    at Object.next (tfjs@latest:2)
    at o (tfjs@latest:2)

or

tfjs@latest:2 Uncaught (in promise) TypeError: n[e].setParams is not a function
    at t.setParams (tfjs@latest:2)
    at Pf (tfjs@latest:2)
    at tfjs@latest:2
    at tfjs@latest:2
    at Object.next (tfjs@latest:2)
    at tfjs@latest:2
    at new Promise (<anonymous>)
    at wp (tfjs@latest:2)
    at tfjs@latest:2
    at tfjs@latest:2
#### Code to reproduce the bug / link to feature request
```
<html><body>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis@latest"></script>
<script>
const model = tf.sequential();
model.add(tf.layers.dense({
  units: 3,
  activation: 'softmax',
  kernelInitializer: 'ones',
  inputShape: [2]
}));
const xs = tf.tensor2d([1, 2, 3, 4], [2, 2]);
const ys = tf.tensor2d([[1, 0, 0], [0, 1, 0]], [2, 3]);
const xsVal = tf.tensor2d([4, 3, 2, 1], [2, 2]);
const ysVal = tf.tensor2d([[0, 0, 1], [0, 1, 0]], [2, 3]);
model.compile(
    {loss: 'categoricalCrossentropy', optimizer: 'sgd', metrics: ['acc']});

const metrics = ['loss', 'val_loss', 'acc', 'val_acc'];
const container = {name: 'Loss and accuracy',
                   tab: 'Training'};
const ftfvis_options = {callbacks: ['onEpochEnd']};

model.fit(xs, ys, {
  epochs: 10,
  validationData: [xsVal, ysVal],
  callbacks: [tfvis.show.fitCallbacks(container, metrics, ftfvis_options), tf.callbacks.earlyStopping({monitor: 'val_acc'}), ]
}).then((history) => {
// Expect to see a length-2 array.
console.log(history.history.val_acc);  
});
</script>
</body></html>
```

**Comment by rthadur** [comment]
@tafsiri was able to reproduce this , any thoughts on this ?

**Comment by tafsiri** [comment]
I'd guess callbacks from the second call are overriding some in the first. It's either a bug in layers or vis. I'll dig deeper.

**Comment by sthalles** [comment]
Hi, any news on this? I am facing a similar problem. When I try to use early stopping and one of the training callbacks, it does not work. Follows a sniped for reproducibility.

```
const model = tf.sequential();
model.add(tf.layers.dense({
  units: 3,
  activation: 'softmax',
  kernelInitializer: 'ones',
  inputShape: [2]
}));
const xs = tf.tensor2d([1, 2, 3, 4], [2, 2]);
const ys = tf.tensor2d([[1, 0, 0], [0, 1, 0]], [2, 3]);
const xsVal = tf.tensor2d([4, 3, 2, 1], [2, 2]);
const ysVal = tf.tensor2d([[0, 0, 1], [0, 1, 0]], [2, 3]);
model.compile(
    {loss: 'categoricalCrossentropy', optimizer: 'sgd', metrics: ['acc']});

const onTrainBegin = function onTrainBegin(logs){
     console.log("onTrainBegin");
}


// Without the EarlyStopping callback, the val_acc value would be:
//   0.5, 0.5, 0.5, 0.5, ...
// With val_acc being monitored, training should stop after the 2nd epoch.
const history = await model.fit(xs, ys, {
  epochs: 10,
  validationData: [xsVal, ysVal],
  callbacks: [onTrainBegin, tf.callbacks.earlyStopping({monitor: 'val_acc'})]
});

// Expect to see a length-2 array.
console.log(history.history.val_acc);
```
It gives the error message:
> An error occured this.getMonitorValue is not a function

**Comment by joaoahmad** [comment]
maybe it can help someone ending up here:
you can use `tf.CustomCallback` to make it work

```
await model.fit(chunkXs, chunkYs, {
  epochs: 1000,
  callbacks: [
    tf.callbacks.earlyStopping({ monitor: 'val_acc' }),
    new tf.CustomCallback({
      onEpochEnd (epoch, logs) {
        // ...
      },
    }),
  ],
})
```

**Comment by spazmodius** [comment]
@joaoahmad Where can I find docs on `tf.CustomCallback`? It seems conspicuously absent from https://js.tensorflow.org/api/latest/

**Comment by ToonTalk** [comment]
Look in https://js.tensorflow.org/api_vis/1.4.3/

**Comment by spazmodius** [comment]
Thanks, @ToonTalk . Can you give me a little more guidance about where in that doc I'm to find information about `tf.CustomCallback`?  Basic searching did not yield anything.

(I'm not using tfvis, nor tf in a browser)

**Comment by ToonTalk** [comment]
You are right that tf.CustomCallback isn't documented. 

The original problem occurs in tfvis using https://js.tensorflow.org/api_vis/1.4.3/#show.fitCallbacks

**Comment by spazmodius** [comment]
I see the problem.  

The `callbacks` argument is passed through [`standardizeCallbacks()`](https://github.com/tensorflow/tfjs/blob/550e2c7ced057309533f44f76e692fe28aa7a802/tfjs-layers/src/base_callbacks.ts#L465), which only handles homogeneous arrays of either `BaseCallback` or `CustomCallbackArgs`. It does not handle an array containing a mix of these.

After all, that is how the `callbacks` argument is typed. Had I been using TypeScript instead of javascript, I suppose I would have gotten a compiler error.

**Comment by ValueInvestorThijs** [comment]
Has there been any progress on this issue? I am currently running the following:
  ```
const visualCallback = tfvis.show.fitCallbacks(
      {name: "Training Performance"},
      ["mape", "val_mape"],
      {callbacks: ["onEpochEnd"]}
);
// Add callback and set training parameters
const params = {
      batchSize:32,
      epochs:200
      callbacks:[visualCallback, tf.callbacks.earlyStopping({monitor: "val_mape", patience: 50})],
      validationData:[XVal, yVal]
};
await model.fit(X, y, params);
```
... and tf js cannot seem to handle it. As there is no documentation of tf.CustomCallback, I am not sure how I could use it to solve the problem.

**Comment by ValueInvestorThijs** [comment]
Thank you. This seems to work. Good luck with the PR.
