### ISSUE TITLE
tf.where on CPU backend is incorrect for inputs with rank 3 or higher.

### ISSUE THREAD

**Issue by ioga** [tensorflow/tfjs#1794]
#### TensorFlow.js version
1.2.6

#### Browser version
Google Chrome 75.0.3770.100 (Mac OS X 10.14.5).
Safari 12.1.1 (14607.2.6.1.1) (Mac OS X 10.14.5).

#### Describe the problem
`tf.where` output on `cpu` backend when `a` and `b` tensors have rank 3 or above is incorrect: all elements except for the very first row are zeros.
Same operation on `webgl` backend works properly.

#### Code to reproduce the bug / link to feature request
Run `tf.where` to select from two non-zero 3d arrays while on CPU backend:
```
tf.setBackend('cpu').then(() => { 
    let res = tf.where(tf.ones([1]).toBool(), tf.ones([1, 3, 3]), tf.ones([1, 3, 3]));
    console.log(res.arraySync().flat().flat());
});
```
Will incorrectly produce zeros except for the first few elements and print `[1, 1, 1, 0, 0, 0, 0, 0, 0]`.

Same code but executed on `webgl` works fine:
 ```
tf.setBackend('webgl').then(() => { 
    let res = tf.where(tf.ones([1]).toBool(), tf.ones([1, 3, 3]), tf.ones([1, 3, 3]));
    console.log(res.arraySync().flat().flat());
});
```
Will print `[1, 1, 1, 1, 1, 1, 1, 1, 1]` as expected.

**Comment by ioga** [comment]
@rthadur thanks for taking a look. 
Looking at the assigned labels, I don't believe this is a performance issue. This is a bug in CPU backend implementation.

**Comment by rthadur** [comment]
@ioga thanks for reporting , i was able to reproduce the issue , @annxingyuan any thoughts on this ?
