### ISSUE TITLE
Object detection inference time nodejs vs python

### ISSUE THREAD

**Issue by blechatellier** [tensorflow/tfjs#1796]
I've benchmarked the ssd_mobilenet_v2_coco from the [official repo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) on cpu using the frozen model in python vs the converted saved model in tfjs (using the latest tfjsconverter).

tensorflow 1.4.0
tfjs-node 1.2.6

```
Python warmup inference 3.0s
Python inference 0.07s
```

```
Nodejs warmup inference 0.8s
Nodejs inference 0.5s
```

Any idea why there is such a big difference? Is the [coco-ssd model](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd) in the tfjs-models repo converted or optimized differently?

**Comment by pyu10055** [comment]
@blechatellier you should try out the coco-ssd model in tfjs-model repo, there are couple optimization done there especially in the post-process step.
My guess for the performance different between node.js and python is related to the post-processing. The post processing of coco-ssd contains many loops which use control flow ops, which will cause performance degrade in node.js due context switching.
You should try the tfjs-models version, it has a simplified post processes, and runs on JS CPU, which will eliminate the context switching for node.js.
