### ISSUE TITLE
tfjs-core: cannot read property 'isContextLost' of null

### ISSUE THREAD

**Issue by yqtianust** [tensorflow/tfjs#1805]
#### TensorFlow.js version
git checkout v1.2.7

#### Browser version
Chrome 75.0.3770 
Ubuntu 16.04 LTS

#### Describe the problem or feature request
When I run 'yarn test --single-run', I got 11 failures. The error message is 
`TypeError: Cannot read property 'isContextLost' of null`

#### Code to reproduce the bug / link to feature request
yarn test --single-run

The full log is:
[1.log](https://github.com/tensorflow/tfjs/files/3488717/1.log)

Thanks.

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by yqtianust** [comment]
OK. I think it is because I didn't enable webGL2 in chrome. Sorry for bothering.
