### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Insiyaa** [tensorflow/tfjs#1806]
https://www.tensorflow.org/js/tutorials/conversion/import_saved_model

Has a code snippet for conversion from tf_frozen_model which is not supported anymore. 
Also, why is it not supported anymore?

**Comment by rthadur** [comment]
Hi Can you please open the issue using [template](https://github.com/tensorflow/tfjs/issues/new) so that we can better assist you  , thank you so much.
