### ISSUE TITLE
Support tfjs_graph_model --> keras_saved_model  conversion 

### ISSUE THREAD

**Issue by chuan92** [tensorflow/tfjs#1808]
There is no method to convert a tfjs_graph_model to tflite.

**Comment by caisq** [comment]
Can you let me know your detailed use case? Why do you need to convert a tfjs_graph_model to keras_saved_model?

**Comment by chuan92** [comment]
@caisq I'm not familiar with javascript programming. The conversion is useful when I get an tfjs_graph_model and use it on tflite.

**Comment by willfu** [comment]
@caisq is there any plan for this feature? thanks.

**Comment by caisq** [comment]
It is not possible to convert a tfjs_graph_model into a keras_saved_model. If you have a tfjs_graph_model, it should have originated from a TensorFlow model, which can be saved as a tf SavedModel. A tf SavedModel has an almost identical format as keras_saved_model.

If this doesn't answer your question, please feel free to comment and/or reopen the issue.
Let me kno

**Comment by willfu** [comment]
@caisq May I know why it is impossible to convert tfjs_graph_model into a keras_saved_model? is it technically impossible? I can not get the original tensorflow model, so ask for help.
