### ISSUE TITLE
output of model.predict() gives array of shape(1,1) but returning undefined elements.

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#181]
I am sending the input to a pre trained keras model imported via json file. the input of the keras model in python is **np.array([[1,1,1,.......,1,1,1]])**
The code for javascript is below:

```
var newoutput=model.predict((tf.ones([1, 30000])));
var g=newoutput[0];
var h=newoutput[1];
console.log(g);
console.log(h);
console.log(newoutput);
```

I am getting output as undefined for g and h. 

For newoutput I am getting following result.

`e {isDisposed: false, size: 1, shape: Array(2), dtype: "float32", strides: Array(1), …}`

The result shoulf be an array of shape (1,1) and will have valid number not undefined.

**Comment by sambitraze** [comment]
how did u resolve the issue
