### ISSUE TITLE
feature request: example code for how to process a video frame by frame in tfjs-node

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1810]
For my use case, I want to read a video file, extract each frame as an image, and run each image through a `tfjs-node` model.  Right now to do this I end up using ffmpeg to convert a video into pngs, and store them on a file system.  Then I load each png one by one into tfjs-node using the nifty `tf.node.decodePng`, and feed that image through the model.

Is there a way to do this by piping the output of ffmpeg into node.js directly and reading each image frame by frame?

**Comment by kangyizhang** [comment]
hi @oveddan 

The ideal case would be for tfjs to provide an API to load local video file and return each frame as a Tensor, similar to tf.data.webcam. But there is no API doing this kind of work yet.

What you are doing right now is the right way to get tesnors from video file. Another way I can think of is to use [tf.data.generator](https://js.tensorflow.org/api/latest/#data.generator) to create a Dataset, and get each frame through iterator.next(). But I'm not sure if you can wrap ffmpeg as a iterator type object and pass it to the tf.data.generator function.

**Comment by UsmanAyyaz** [comment]
Reviving this thread, as I am facing a similar usecase - I need to parse a video in real time and run tfjs/mobilenet model on it to make predictions on the objects present in each video frame. Is there API support for this sort of use case in tfjs? Any pointers on how to approach this problem?

**Comment by solcabz** [comment]
is there a way to scan the video frame by frame to detect a blank screen or color
 tones

**Comment by gaikwadrahul8** [comment]
Hi, @oveddan 

Apologize for the delayed response and May I know are you still looking this feature in TFJs and if someone wants to contribute to this feature then please refer this [link](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md). Thank you!
