### ISSUE TITLE
PoseNet 3d coordinates? z-coordinate?

### ISSUE THREAD

**Issue by supermoos** [tensorflow/tfjs#1811]
#### TensorFlow.js version
PoseNet 2.1.3
#### Browser version
Chrome 76
#### Describe the problem or feature request
Is there a way to get 3D pose-estimation, i.e. adding z coordinate to position output? Or is that outside the scope of PoseNet, or perhaps planned for future versions?

**Comment by rthadur** [comment]
@supermoos thank you , this is out of scope for posenet , no plans to work on this feature.

**Comment by yucolabjames** [comment]
+1 for this feature req

**Comment by JudeOsborn** [comment]
+1 for me as well.

**Comment by rmajasol** [comment]
+1 here too

**Comment by Stylos21** [comment]
+1 for this
