### ISSUE TITLE
Ignoring visible gpu device

### ISSUE THREAD

**Issue by hernanpatronc** [tensorflow/tfjs#1819]
Hi! I am running tfjs in a container from an official image of tensorflow-gpu. It logs to the console the following message:
`Ignoring visible gpu device (device: 0, name: Tesla M60, pci bus id: 0000:00:1e.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.`
The host is an aws vm with a Tesla M60. How can i compile tfjs to run with cuda capability 5.2?
Thanks in advance

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.fjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by kangyizhang** [comment]
@hernanpatronc tensorflow has strict [version requirement](https://github.com/tensorflow/tfjs-node#installing) for GPU. You can try with the latest Docker or install the toolkit by yourself.
