### ISSUE TITLE
Reuse trained model json for prediction in js

### ISSUE THREAD

**Issue by rohban0u** [tensorflow/tfjs#182]
Is it possible to store the json file generated for model post training and reuse it in browser for making predictions for that dataset.

**Comment by tafsiri** [comment]
Not sure which json you are referring to but we have two tutorials for porting models to the browser. 
 - [Importing Keras Models](https://js.tensorflow.org/tutorials/import-keras.html)
 - [Importing TensorFlow SavedModels](https://github.com/tensorflow/tfjs-converter)

**Comment by nsthorat** [comment]
:)
