### ISSUE TITLE
Unable to load model locally - asyncToGenerator.js:20

### ISSUE THREAD

**Issue by Neuroforge** [tensorflow/tfjs#183]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

Install via Yarn.

var version = '0.6.0';

#### Browser version

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

#### Describe the problem or feature request

I am trying to load a model.

In model.js i get an error which is thrown in loadModelInternal()

                case 1:
                    modelConfigRequest = _a.sent();
                    return [4, modelConfigRequest.json()];

> "asyncToGenerator.js:20 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0"

If i put weights_manifest.json into https://jsonlint.com/ i am told that it is VALID.

The url i am loading from is http and not https.... could this be the issue?

#### Code to reproduce the bug / link to feature request

Similar to the example code, however i am trying to load a locally hosted model.

https://github.com/tensorflow/tfjs-examples/tree/master/webcam-transfer-learning

async function createModel()
{
  //console.log("Loading Model");
  const mobilenet = await tf.loadModel('./Models/tensorFlowJsModel/weights_manifest.json');
  // Return a model that outputs an internal activation.
  const layer = mobilenet.getLayer('conv_pw_13_relu');
  return tf.model({inputs: mobilenet.inputs, outputs: layer.output});
}

**Comment by Neuroforge** [comment]
On further testing i have downloaded the model from...

https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json

Loading it locally gives the same error.

**Comment by tafsiri** [comment]
A couple of quick questions/tests to do:

- For converting the model did you follow [this tutorial](https://js.tensorflow.org/tutorials/import-keras.html). Are the model weights being written correctly? (The model.json should be in a folder with other files that represent the sharded weights).

- Are you able to load that json file separately? i.e. does fetch('./Models/tensorFlowJsModel/weights_manifest.json') give you a valid json?

**Comment by Neuroforge** [comment]
This can be achieved using yarn build and then creating a server around those files.

**Comment by tangtai** [comment]
@Neuroforge how did you create a server around those files?

**Comment by xtr33me** [comment]
Regarding the "No 'Access-Control-Allow-Origin' " issue, make sure that on the server you are hosting the files that you add a file with the name .htaccess at the root and that that file contains the entry below.  Hope it helps others as I was dealing with the same issue and it fixed that problem.

Header set Access-Control-Allow-Origin "*"

**Comment by Mohammed-Shoaib** [comment]
I am having the same issue.
Loading the file loads the index.html file instead of the model.json file when the path is specified locally. I am using the React framework at the moment and did not find problems loading the model outside react,
