### ISSUE TITLE
Fix tfjs-models/mobilenet 2.0.3 predictions / norm control

### ISSUE THREAD

**Issue by joe4dev** [tensorflow/tfjs#1830]
#### TensorFlow.js version

`1.2.7` but this issue relates to `@tensorflow-models/mobilenet:2.0.3`

#### Browser version

independent: Google Chrome 76.0.3809.100 (Official Build) (64-bit) or NodeJS v10/v12

#### Describe the problem or feature request

The [MobileNet example](https://github.com/tensorflow/tfjs-models/tree/master/mobilenet#via-script-tag) and any code using `@tensorflow-models/mobilenet:2.0.3` yields totally wrong predictions. Example:
![Screenshot 2019-08-14 at 21 09 17](https://user-images.githubusercontent.com/8161292/63048944-e1613100-bed7-11e9-9d34-f3fe9d317ae8.png)

The [norm control](https://github.com/tensorflow/tfjs-models/pull/252) PR changes input range normalization (see [here](https://github.com/tensorflow/tfjs-models/commit/fc85a75383245df787f37e0dd655791047a8f4f6#diff-6f60c30b63966ef3c53b9abbc8e3adecR197)).
Is multiply and add correct [here](https://github.com/tensorflow/tfjs-models/commit/fc85a75383245df787f37e0dd655791047a8f4f6#diff-6f60c30b63966ef3c53b9abbc8e3adecR199)?
`img.toFloat().mul(this.inputRange).add(this.inputMin) as tf.Tensor3D;`

Normalization bounds are by default `[-1,1]` (c.f., inputMin and inputMax) but in MODEL_INFO initialized to `[0,1]` (is that correct?).

Further, @nsthorat suggested exposing the normalization bounds to the public load method [here](https://reviewable.io/reviews/tensorflow/tfjs-models/252#-LinY6bB1GCIjUZ15sEx-r1-157) but inputRange remains hardcoded for user-provided modelUrls.

That issue is unfortunate as there is no fully working v2 (using tfjs v1) version published because `@tensorflow-models/mobilenet:2.0.2` in the NPM registry lacks its main file `dist/index.js` (improper build when published; manually building works but is annoying).

#### Code to reproduce the bug / link to feature request

[MobileNet example](https://github.com/tensorflow/tfjs-models/tree/master/mobilenet#via-script-tag) => save to HTML and use any image (e.g., [cat.jpg](https://github.com/tensorflow/tfjs-converter/blob/master/demo/mobilenet/cat.jpg) from the plain Tensorflow example without the MobileNet wrapper)

```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@2.0.3"> </script>
```

**Comment by rthadur** [comment]
@joe4dev thanks for reporting the issue , @nsthorat  i was able to reproduce the error , seems like a bug , can you please take a look.
cc @dsmilkov

**Comment by dsmilkov** [comment]
@bileschi, I can take this today, unless you are already working on it. Let me know.
