### ISSUE TITLE
Sentiment analysis breaking with dilationRate error in 0.9.0.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#185]
dilationRate must be a number for 1D convolution, but received [1]

See this notebook:
https://beta.observablehq.com/@jashkenas/sentiment-analysis-with-tensorflow-js

Seems like we should accept array of one number for dilationRate for 1D conv (since that's simply ported from keras).

**Comment by caisq** [comment]
Fixed by PR: https://github.com/tensorflow/tfjs-layers/pull/125
