### ISSUE TITLE
PoseNet models don't accept batch sizes greater than 1.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1864]
I'm writing some custom code that is to feed a batch of images into the PoseNet models for inference; in my case its a series of frames from long videos.  I would eventually  open a PR that supports this functionality.

However, when feeding a batch size of greater than one to both the MobileNet and ResNet models, you get an error:

> Error: The shape of dict['sub_2'] provided in model.execute(dict) must be [1,-1,-1,3], but was [5,537,953,3]

A way to simply reproduce the error source is:

```
  const url =
      'https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/quant1/model-stride16.json'
  const graphModel = await tf.loadGraphModel(url);

  const inputTensor = tf.zeros([5, 100, 100, 3]);

  const result = graphModel.predict(inputTensor);
```

The above code results in an error:

> UnhandledPromiseRejectionWarning: Error: The shape of dict['sub_2'] provided in model.execute(dict) must be [1,-1,-1,3], but was [5,100,100,3]

The same thing occurs for other model urls.

CC @tylerzhu-github

**Comment by rthadur** [comment]
CC @tylerzhu-github gentle ping to check this error.

**Comment by tylerzhu-github** [comment]
Thanks for the reminder!
Yes that will require exporting a model that support batch size > 1.
Will handle that in the next release, timeline would be end of next quarter.

**Comment by oveddan** [comment]
@tylerzhu-github thanks!  Does this require re-training the model or just a modification to how the model is saved?

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
