### ISSUE TITLE
Support op TF.unique

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tfjs#1866]
It would be really great to have support for [tf.unique](https://www.tensorflow.org/api_docs/python/tf/unique).

This has been brought up by a number of [previous](https://github.com/tensorflow/tfjs/issues/958) [issues](https://github.com/tensorflow/tfjs/issues/1693) and in general it is a very common operation that many applications rely on.

**Comment by rthadur** [comment]
@evancasey thank you , may i know your use case ?

**Comment by evancasey** [comment]
Hey @rthadur, I'm using tf.unique right now to do a type of one-hot encoding where I have an input vector with a discrete number of unique values but the values are scattered between [0,N] and N is potentially very large. I can't call tf.one_hot directly on this because I want the depth to be equal to the number of unique values.

**Comment by rthadur** [comment]
@pyu10055 any plans to support TF.unique op ?

**Comment by ClaytonSmith** [comment]
Poking this issue. There aren't any good alternatives to `unique`.
