### ISSUE TITLE
TF.cumsum operation is unreliable for large tensors

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tfjs#1867]
### TensorFlow.js version
1.2.7

#### Browser version
Firefox/chrome

#### Describe the problem or feature request
tf.cumsum will return an incorrect answer and/or take a very long time to return if you pass it a tensor of more than a couple hundred thousand values.

#### Code to reproduce the bug / link to feature request
```python
const x = tf.zeros([1000000]);
x.cumsum().print();
```

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
