### ISSUE TITLE
Cannot read property 'rank' of undefined

### ISSUE THREAD

**Issue by Neuroforge** [tensorflow/tfjs#187]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

Install via Yarn.

var version = '0.6.0';

#### Browser version

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

#### Describe the problem or feature request

I am following this tutorial - https://github.com/tensorflow/tfjs-converter

When running the predict stage in the same way as the example.....

const output1 = mobilenet.execute({input: resized}, OUTPUT_NODE_NAME);

The output of the error shows the files where the exception is thrown. I am unclear where to start with this error. Since i am following the example, it would indicate something wrong with the model and not the code. Is this an issue see else where?

```
ConvOps.conv2d = function (x, filter, strides, pad, dataFormat, dilations, dimRoundingMode) {
        if (dataFormat === void 0) { dataFormat = 'NHWC'; }
        if (dilations === void 0) { dilations = [1, 1]; }
        var x4D = x;
        var reshapedTo4D = false;
        if (x.rank === 3) {  <<< ERROR ON THIS LINE HERE!!!
            reshapedTo4D = true;
            x4D = x.as4D(1, x.shape[0], x.shape[1], x.shape[2]);
        }
```

> e9e6dd3146dafb04690c5987b15aed49.js:5344 Uncaught (in promise) TypeError: Cannot read property 'rank' of undefined
>     at ConvOps.conv2d (e9e6dd3146dafb04690c5987b15aed49.js:5344)
>     at e9e6dd3146dafb04690c5987b15aed49.js:3019
>     at Object.Tracking.tidy (e9e6dd3146dafb04690c5987b15aed49.js:7998)
>     at Object.descriptor.value [as conv2d] (e9e6dd3146dafb04690c5987b15aed49.js:3019)
>     at Object.exports.executeOp (e9e6dd3146dafb04690c5987b15aed49.js:44350)
>     at Object.executeOp (e9e6dd3146dafb04690c5987b15aed49.js:44693)
>     at e9e6dd3146dafb04690c5987b15aed49.js:44794
>     at Array.reduce (<anonymous>)
>     at e9e6dd3146dafb04690c5987b15aed49.js:44793
>     at Object.Tracking.tidy (e9e6dd3146dafb04690c5987b15aed49.js:7998)
> ConvOps.conv2d @ e9e6dd3146dafb04690c5987b15aed49.js:5344
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:3019
> Tracking.tidy @ e9e6dd3146dafb04690c5987b15aed49.js:7998
> descriptor.value @ e9e6dd3146dafb04690c5987b15aed49.js:3019
> exports.executeOp @ e9e6dd3146dafb04690c5987b15aed49.js:44350
> executeOp @ e9e6dd3146dafb04690c5987b15aed49.js:44693
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:44794
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:44793
> Tracking.tidy @ e9e6dd3146dafb04690c5987b15aed49.js:7998
> GraphExecutor.execute @ e9e6dd3146dafb04690c5987b15aed49.js:44792
> FrozenModel.execute @ e9e6dd3146dafb04690c5987b15aed49.js:44974
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:45328
> Tracking.tidy @ e9e6dd3146dafb04690c5987b15aed49.js:7998
> _callee2$ @ e9e6dd3146dafb04690c5987b15aed49.js:45317
> tryCatch @ e9e6dd3146dafb04690c5987b15aed49.js:857
> invoke @ e9e6dd3146dafb04690c5987b15aed49.js:1091
> prototype.(anonymous function) @ e9e6dd3146dafb04690c5987b15aed49.js:909
> step @ e9e6dd3146dafb04690c5987b15aed49.js:2266
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2284
> F @ e9e6dd3146dafb04690c5987b15aed49.js:281
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2263
> predict @ e9e6dd3146dafb04690c5987b15aed49.js:45345
> _callee3$ @ e9e6dd3146dafb04690c5987b15aed49.js:45365
> tryCatch @ e9e6dd3146dafb04690c5987b15aed49.js:857
> invoke @ e9e6dd3146dafb04690c5987b15aed49.js:1091
> prototype.(anonymous function) @ e9e6dd3146dafb04690c5987b15aed49.js:909
> step @ e9e6dd3146dafb04690c5987b15aed49.js:2266
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2277
> Promise.then (async)
> step @ e9e6dd3146dafb04690c5987b15aed49.js:2276
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2277
> Promise.then (async)
> step @ e9e6dd3146dafb04690c5987b15aed49.js:2276
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2277
> Promise.then (async)
> step @ e9e6dd3146dafb04690c5987b15aed49.js:2276
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2284
> F @ e9e6dd3146dafb04690c5987b15aed49.js:281
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:2263
> init @ e9e6dd3146dafb04690c5987b15aed49.js:45376
> require.5.babel-runtime/core-js/array/from @ e9e6dd3146dafb04690c5987b15aed49.js:45400
> newRequire @ e9e6dd3146dafb04690c5987b15aed49.js:42
> require.174 @ e9e6dd3146dafb04690c5987b15aed49.js:69
> (anonymous) @ e9e6dd3146dafb04690c5987b15aed49.js:74

**Comment by tafsiri** [comment]
@pyu10055 would you be able to take a look? 

@Neuroforge would you be able to add what the value of OUTPUT_NODE_NAME is.

**Comment by Neuroforge** [comment]
OUTPUT_NODE_NAME = ModelName/concat_stage7

Which is the same as the one defined when converting the model.

 tensorflowjs_converter --input_format=tf_saved_model --output_node_names='ModelName/concat_stage7:0' ./saved ./saved3

**Comment by Neuroforge** [comment]
Is {input: resized} this always "input".

Or should this be the name of the input tensor image?

**Comment by Neuroforge** [comment]
The issue was with the {input:resized} and so it should be {image:resized} which is the name of the input tensor in the python code.

**Comment by nsthorat** [comment]
@pyu10055 have you released a new version of the converter since your friendlier error messages?
