### ISSUE TITLE
Adanet automl in tfjs

### ISSUE THREAD

**Issue by flesicek** [tensorflow/tfjs#1880]
Hi,

Tensorflow Python have Adanet Automl capability for couple of months https://github.com/tensorflow/adanet

Is there a plan to migrate this Adanet capability into tfjs environment?
That would be fantastic !! 🤗

Note: Keep up fantastic work with tensorflow.

Thanks
Jozef

**Comment by rthadur** [comment]
not in the near future. cc @dsmilkov

**Comment by rthadur** [comment]
Closing this issue as this will not included in near future , but contributions are welcome as a separate library. Thank you
