### ISSUE TITLE
Serialization of Glorot[Normal|Uniform] cannot be read by Python Keras

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#189]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

0.9.1

Any model defined in TensorFlow.js that contain Glorot initializaters contains the class name like GlorotNormal. When one tries to load such models in Python Keras, an error is thrown complaining about improper config fields.

This is because in Python Keras, GlorotNormal and GlorotUniform are not classes, but merely hepler classes for VarianceScaling initializers. Then such initializers are defined and serialized from Python, they show up as VarianceScaling. 

For compatibility, TensorFlow.js should serialize Glorot initializers in the same way.

**Comment by caisq** [comment]
cc @ericdnielsen

**Comment by nsthorat** [comment]
@caisq fixed this.
