### ISSUE TITLE
Node backend doesn't support NCHW data format

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1891]
WebGL and CPU backends now support NCHW data format (https://github.com/tensorflow/tfjs/commit/9f5ec4708487cc166db91bafaa7abab68eddedf4) but TensorFlow does not.

**Comment by rthadur** [comment]
NCHW is supported in conv2d now here is the reference link https://www.tensorflow.org/api_docs/python/tf/nn/conv2d . Closing this feature request.
