### ISSUE TITLE
tfjs-executeAsync exception with tensorflow object detect api-mask-rcnn

### ISSUE THREAD

**Issue by aohan237** [tensorflow/tfjs#1898]
i convert a tensorflow object detect api --mask rcnn model to tfjs.

when i load the model, and run model.

await model.executeAsync([tf.zeros([1, 800, 800, 3])]);

there is an exception:

> (node:6828) UnhandledPromiseRejectionWarning: Error: The implicit shape can't be a fractional number. Got 900 / 1200

location : 
@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/util.js:301:15

what's the problem and how to fix it

**Comment by aohan237** [comment]
i found that the problem maybe the tfjs-converter --quantization_bytes .
when choose 1 the model will be raise these exception
when choose 2 will be good.

**Comment by pyu10055** [comment]
@aohan237 can you share the saved model files or link to the model in order for us to reproduce? thanks!

**Comment by aohan237** [comment]
@pyu10055  
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/instance_segmentation.md

https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/mask_rcnn_resnet50_atrous_coco.config

**Comment by pyu10055** [comment]
@aohan237 sorry for the delay, it would be great if you can provide the saved model for me to reproduce the problem. Thanks

**Comment by aohan237** [comment]
sorry, the model i cant find it.  but the model  generated by following the links i give to you to produce.
