### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by nate1021** [tensorflow/tfjs#1905]
#### Describe the problem or feature request
Link to data file used in tutorial is dead.

https://storage.googleapis.com/tfjs-tutorials/carsData.json

**Comment by rthadur** [comment]
@nate1021 did you try using the code or browser ?

**Comment by nate1021** [comment]
Oh, my bad. It was a "Access-Control-Allow-Origin exception". I just saw a request exception, doubled checked with the browser and saw another exception, so I assumed the link was dead and went to fetch the data off the repo. Thought I should notify you before moving on, sorry.
