### ISSUE TITLE
Tf.js Playground

### ISSUE THREAD

**Issue by reiinakano** [tensorflow/tfjs#194]
Do you have any plans to bring back deeplearn.js Playground as TF.js Playground?

**Comment by tafsiri** [comment]
@reiinakano yes... Its going to be somewhat different though, a PR is about to land here https://github.com/tensorflow/tfjs-website/pull/128

**Comment by tafsiri** [comment]
@reiinakano There is a new "Try it live" button on https://js.tensorflow.org/. Try it out and let us know what you think.

**Comment by tafsiri** [comment]
@ManrajGrover. XOR sounds like it could potentially be a good option. It wouldn't require pulling in external libraries, and would have a fairly short implementation. I think you had a PR for this a while back so I'll take a look!

I'd rule out mnist as it involves pulling too much data on load imo. I think this is something that should load quickly and have a relatively short code snippet. The tutorials are a better format for something that needs a lot of explanation imo.

**Comment by ManrajGrover** [comment]
@tafsiri Agreed. Yeah, sure. Here it is: https://github.com/tensorflow/tfjs-core/pull/804

Let me know if I can be of any help.

**Comment by tafsiri** [comment]
Thanks @ManrajGrover, looking at it now, I think it may be a bit on the long side for this codepen snippet—though using the layers api might make it smaller. It may benefit from a fuller tutorial/blog post if its goal is to explain stuff, I worry that just having the code might be overwhelming for some. As is i like that the whole snippets fits in a single screenful.

As an aside I also think there are some advantages to keeping it to the same code as on the front page (though that need not be the driving factor here). 

Thoughts?

**Comment by ManrajGrover** [comment]
@tafsiri You mean front page of the website or codepen? Yeah, now even I think it would be better as a tutorial or a blog. +1 to that.

**Comment by tafsiri** [comment]
@ManrajGrover yeah the codepen code matches the code shown on the front page right now.

I'll close this issue for now.
