### ISSUE TITLE
How to support Mirrorpad when transforming frozen model of tensorflowjs_converter

### ISSUE THREAD

**Issue by qzcsgs** [tensorflow/tfjs#1941]
command: tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='MobilenetV1/Predictions/Reshape_1' /mobilenet/frozen_model.pb /mobilenet/web_model

result: ValueError: Unsupported Ops in the model before optimization
MirrorPad

**Comment by rthadur** [comment]
this is a feature request and there is already issue opened here to track it , please check [here](https://github.com/tensorflow/tfjs/issues/1775) , will be closing this so that we can track it at one place , thank you
