### ISSUE TITLE
tf.memory() does not return reasons

### ISSUE THREAD

**Issue by Polarisation** [tensorflow/tfjs#1942]
#### TensorFlow.js version
1.2.7

#### Browser version
Firefox 68
#### Describe the problem or feature request
The documentation for tf.memory() states that it will return `reasons` when `unreliable: true`. However it does not do so (at least with the `cpu` backend).

#### Code to reproduce the bug / link to feature request

```
tf.setBackend('cpu')
console.log(tf.memory());
```

The response is: `{ unreliable: true, numTensors: 0, numDataBuffers: 0, numBytes: 0 }`. The `reasons` property is missing.

I can see it is set by the CPU backend:
https://github.com/tensorflow/tfjs-core/blob/v1.2.7/src/backends/cpu/backend_cpu.ts#L242
But it is not output by TensorFlow.js

**Comment by rthadur** [comment]
Hi it is showing reasons here please check below image 
![image](https://user-images.githubusercontent.com/43972606/63950757-706e5d00-ca31-11e9-862c-5099e9c82d72.png)
please try with latest tfjs verion , i will keep this issue open for a day if this issue still persists , please comment here

**Comment by Polarisation** [comment]
Sorry, I did use an older version by mistake here. It's working fine with latest version so closing
