### ISSUE TITLE
 flatten_1_input to have shape [null,7,7,512] but got array with shape [1,224,224,3

### ISSUE THREAD

**Issue by Gautamshahi** [tensorflow/tfjs#1943]
Hello,

I am writing to use the concept and the code mentioned at https://tinyurl.com/y7ehja7h for my data, data is of binary class after loading the image, when I click on the predict, I get the error, Uncaught (in promise) Error: Error when checking: expected tfjs@0.13.5.2 flatten_1_input to have shape [null,7,7,512] but got array with shape [1,224,224,3].

Can you please help me to solve this issue?

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Gautamshahi** [comment]
@rthadur I will already post it at the StackOverflow, there was no response there, then I posted here, I have already seen similar questions here, it will be a kind help if you provide a solution or suggestion for it.
