### ISSUE TITLE
Frozen Model conversion issues

### ISSUE THREAD

**Issue by qzcsgs** [tensorflow/tfjs#1945]
When converting Frozen Model, a pb file and a JSON file and a group1-shard1of1 file will be generated. Is this normal?

The format in the JSON file is like this
```json
[
  {
    "path": [],
    "weights": []
  }
]
```

tensorflowjs 0.8.6

**Comment by tafsiri** [comment]
Yes that is expected given that version of TensorFlow.js you are using. Newer versions do not produce the pb file.

**Comment by qzcsgs** [comment]
> Yes that is expected given that version of TensorFlow.js you are using. Newer versions do not produce the pb file.
So how to use them?

**Comment by qzcsgs** [comment]
@tafsiri So how to use them?

**Comment by pyu10055** [comment]
To converter a frozen model and be compatible with the latest tfjs version,
use the following steps:

7. I have a model formatted as a Session bundle or Frozen model. How do I
convert it to TensorFlow.js?

You can install a previous version of TensorFlow.js in a virtual
environment to convert the model to the JSON format. Here is how you can
achieve this.

   - Set up the virtual environment:

virtualenv --no-site-packages venv. venv/bin/activate
pip install tensorflowjs==0.8.6

venv is the name of the virtual environment.

   - Convert a session bundle model:

tensorflowjs_converter \
    --input_format=tf_session_bundle \
    --output_json=true \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    /mobilenet/session_bundle \
    /mobilenet/web_model


   - Convert a frozen model:

tensorflowjs_converter \
    --input_format=tf_frozen_model \
    --output_json=true \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    --saved_model_tags=serve \
    /mobilenet/frozen_model.pb \
    /mobilenet/web_model

**Comment by haleemik** [comment]
For Converting Frozen_inference_model.pb to tensroflowjs(model.json) : Please Refer this Link : https://github.com/tensorflow/tfjs-models/blob/master/deeplab/scripts/convert_deeplab.sh

**Comment by haleemik** [comment]
> For Converting Frozen_inference_model.pb to tensroflowjs(model.json) : Please Refer this Link : https://github.com/tensorflow/tfjs-models/blob/master/deeplab/scripts/convert_deeplab.sh

tensorflowjs_converter \
    --input_format=tf_frozen_model \
    --output_json=true \
    --saved_model_tags=serve \
    --output_node_names='SemanticPredictions' \
    --quantization_bytes 2 \
    frozen_inference_graph.pb \
    $OUTPUT_DIR
