### ISSUE TITLE
Is there a way to switch between tfjs-node and tfjs-node-gpu?

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1950]
I'm working with a solution that when I develop I want to run on my mac, and use straight up tfjs-node since I don't have cuda installed.  When deploying to production I want to switch to use tfjs-node-gpu as cuda is available on the production machine.

Is there a way to dynamically enable cuda gpu support from within the code?  If so it would be great if example code or documentation exists for how to do this.

I'm thinking something like:

```javascript
import * as tf from '@tensorflow/tfjs-node'

tf.enableGpu()
```

or is there a script we can run that switches the npm installed tfjs-node to use a cuda enabled backend?

**Comment by kangyizhang** [comment]
hi @oveddan tfjs-node and tfjs-node-gpu are using different TensorFlow C library (libtensorflow). During installation, they would download libtensorflow from different source and use different node addon module, so a JS function can not achieve it.

I would recommend you to add some commend into your deploy script if you have one, or add a new script to replace tfjs-node with tfjs-node-gpu in your package.json.dependencies and the line where you import `@tensorflow/tfjs-node`, similar to this https://github.com/tensorflow/tfjs/blob/master/tfjs-node/scripts/build-npm-gpu.sh#L24

**Comment by tafsiri** [comment]
@oveddan one pattern that we use is to have both libraries in package.json and do a dynamic require. e.g. https://github.com/tensorflow/tfjs-examples/blob/b3b28a3d55625e199c3e9ff04fdf5d9ee3e12635/intent-classifier/training/train_tagger.js#L256

**Comment by oveddan** [comment]
Thanks @tafsiri and @kangyizhang 

@tafsiri Is there a way to do your example but with typescript typings?  I think that with require it's not possible.  

@kangyizhang thanks for that suggestion - it's slightly hacky but seems like the easiest way.

**Comment by tafsiri** [comment]
@oveddan not sure what you mean. In our node scripts we often just use requires and I believe we still get typings support in vscode. But I may be misunderstanding your question? Also in these examples you can still `import * as tf from @tensorflow/tfjs` you just also do a dynamic require after that to enable the bindings.
