### ISSUE TITLE
Feature request: being able to specify the GPU to use when loading a model with tfjs-node-gpu

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#1951]
I have a situation where I'm processing thousands of images for inference using tfjs-node-gpu.  It would be great if, lets say I have multiple gpus, I can evenly distribute the images to send to the multiple gpus, by specifying which gpu to use when loading a model.  Is this possible to do currently with tfjs-node-gpu, and if so can there be an example shown somewhere?

**Comment by caisq** [comment]
@oveddan tfjs-node-gpu uses libtenorflow-gpu under the hood, which in turn recognizes the CUDA_VISIBLE_DEVICES system environment variable. You can use the env var to specify which GPU is to be used by tfjs-node-gpu, e.g., `export CUDA_VISIBLE_DEVICES=2` selects the 3rd GPU on a machine with >=3 CUDA GPUs.

**Comment by caisq** [comment]
I'll close the issue now. If my answer above doesn't address your question, please feel free to comment or re-open this issue. @oveddan
