### ISSUE TITLE
Set up bazel build for tfjs-converter Python code on Cloud Build

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1955]
Currently our Cloud Build test infra for the Python code in tfjs-converters doesn't run the tests using the bazel BUILD files. This doesn't guard the BUILD files against breakages by external PRs. 

There should be a new Cloud Build step that 
1. Installs the correct version of bazel
2. Calls: `cd tfjs-converter/python && bazel test tensorflowjs/...`

**Comment by rthadur** [comment]
I believe this is implemented here https://github.com/tensorflow/tfjs/pull/1953/files , thank you
