### ISSUE TITLE
Missing op: Multinomial

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1970]
Reference from TensorFlow: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/multinomial

This op is used by the [Music Transformer model](https://colab.sandbox.google.com/drive/1h2s1xkrVEm2MXPEdISfrhtBZrNZq9iNZ#scrollTo=PBngSJvP_En7&forceEdit=true&offline=true&sandboxMode=true).

**Comment by Lewuathe** [comment]
[`multinomial`](https://js.tensorflow.org/api/latest/#multinomial) op seems to already exist in TensorFlow.js. Is this different from what you are talking about?

**Comment by rthadur** [comment]
this op was included few days back in #1918

**Comment by annxingyuan** [comment]
Oh my bad... I was just copying missing ops from a failed conversion error message - you're right :)
