### ISSUE TITLE
Turning off debug mode (tf.enableProdMode doesn't work) nothing documented for disabling debug mode

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1972]
## TensorFlow.js version
1.2.6

#### Browser version
Version 76.0.3809.132 (Official Build) (64-bit)
#### Describe the problem or feature request
After doing tests with `tf.enableDebugMode() `I tried to turn it off as follows
```
tf.enableProdMode()
undefined
tfjs.js:2 reshape                  	0ms      	2D 1,100         	100	
tfjs.js:2 reshape                  	0ms      	0D               	1	
tfjs.js:2 reshape                  	0ms      	2D 1,100         	100
```	
It continued to spit out trace information.
How can one disable debug mode?

**Comment by kangyizhang** [comment]
hi @ToonTalk , `enableProdMode` does not turn off debug mode. You can import `ENV` from tf and run `ENV.set('DEBUG', false);` to turn off debug mode.

Please let us know if it works for you.

**Comment by ToonTalk** [comment]
Thanks.

I'm loading tfjs as a  script element on a web page. 

`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>`

It is not clear how to load ENV.

**Comment by kangyizhang** [comment]
You should be able to get it through `tf.ENV`.

**Comment by ToonTalk** [comment]
Works fine, thanks. It would be good if this was documented at https://js.tensorflow.org/api/latest/

**Comment by kangyizhang** [comment]
Glad to hear it works. Editing ENV is not encouraged and that's why it's not documented.
