### ISSUE TITLE
Normalization of out of range start/end and negative stride breaks stridedSlice

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1984]
The [normalization of start, end and strides](https://github.com/tensorflow/tfjs/blob/aa92053a8d7c640fe9e685e254655f417480cf0d/tfjs-core/src/ops/strided_slice.ts#L81) make the stridedSlice op return different result in TF C library. Without normalization the result is correct. 

I haven't figure out why the result is different, such as for this [test](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/strided_slice_test.ts#L166), the 1d tensor shape is [4], start and end indexes are [-3], [-5]. After normalization the indexes become [1], [-1]. It's still the same position but the result is different.

I think the solution is to move the normalization logic to wegbl/cpu backend, but needs to be verified.

**Comment by dsmilkov** [comment]
I just pushed to your PR that upgrades node to 1.2.8 and made all tests to pass - you should be good to go. For the diff see commit: https://github.com/tensorflow/tfjs/pull/1983/commits/62903237bd5c86dee3c4ed112393854f6ab7d1c7
