### ISSUE TITLE
Support vec4/ivec4 in shader storage block for webgpu backend

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#1986]
Currently, only float/int is supported in shader storage block which results that only one data in memory can be accessed per time. Maybe we can use vec4 to optimize it since we can load/store 4 data per time.

**Comment by qjia7** [comment]
@annxingyuan FYI

**Comment by OVERSTANDING683** [comment]
Support vec4/ivec4 in shader storage block for web GPU backend #1986

**Comment by rthadur** [comment]
@qjia7 i see you have added this feature request here https://github.com/tensorflow/tfjs/pull/4167 , can we close this issue ?

**Comment by qjia7** [comment]
> @qjia7 i see you have added this feature request here #4167 , can we close this issue ?

Sure. Closing it. Thanks.
