### ISSUE TITLE
Fallback to cpu when the inputs size is small for WebGPU backend

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#1987]

**Comment by qjia7** [comment]
@annxingyuan FYI

**Comment by annxingyuan** [comment]
Thanks @qjia7 ! By the way, if you wouldn't mind adding the 'webgpu' label and 'WebGPU' project board to these issues that would be awesome :)

**Comment by qjia7** [comment]
>By the way, if you wouldn't mind adding the 'webgpu' label and 'WebGPU' project board to these issues that would be awesome

@annxingyuan I don't have the permission to change it. Is it ok to give me those permission?

**Comment by annxingyuan** [comment]
@qjia7 Ah I see... in that case I will apply the labels! Thanks!
