### ISSUE TITLE
Improve error messaging around INVALID_ENUM readpixels.

### ISSUE THREAD

**Issue by Neuroforge** [tensorflow/tfjs#199]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

Hello,

Thank you for you help so far. I have my code working in Firefox and Chrome. When using Safari however i am seeing different behaviour. Some of the detections appear to be different when it does work but the only error output is as follows.

#### TensorFlow.js version

    "@tensorflow/tfjs": "0.6.1",
    "@tensorflow/tfjs-converter": "^0.1.1",

#### Browser version

Safari - Version 11.1 (13605.1.33.1.2)

#### Describe the problem or feature request

[Error] WebGL: INVALID_ENUM: readPixels: invalid type
	readPixels
	isFloatTextureReadPixelsEnabled (e9e6dd3146dafb04690c5987b15aed49.js:8618)
	evaluateFeature (e9e6dd3146dafb04690c5987b15aed49.js:8711)
	get (e9e6dd3146dafb04690c5987b15aed49.js:8668)
	getTextureInternalFormat (e9e6dd3146dafb04690c5987b15aed49.js:11477)
	createAndConfigureTexture (e9e6dd3146dafb04690c5987b15aed49.js:11510)
	acquireTexture (e9e6dd3146dafb04690c5987b15aed49.js:12597)
	uploadToGPU (e9e6dd3146dafb04690c5987b15aed49.js:13545)
	getTexture (e9e6dd3146dafb04690c5987b15aed49.js:13055)
	fromPixels (e9e6dd3146dafb04690c5987b15aed49.js:12899)
	tidy (e9e6dd3146dafb04690c5987b15aed49.js:7998)
	_callee2$ (e9e6dd3146dafb04690c5987b15aed49.js:47210)
	tryCatch (e9e6dd3146dafb04690c5987b15aed49.js:857)
	invoke (e9e6dd3146dafb04690c5987b15aed49.js:1091)
	step (e9e6dd3146dafb04690c5987b15aed49.js:2266)
	initializePromise
	Promise
	F (e9e6dd3146dafb04690c5987b15aed49.js:281)
	(anonymous function) (e9e6dd3146dafb04690c5987b15aed49.js:2263)
	tryCatch (e9e6dd3146dafb04690c5987b15aed49.js:857)
	invoke (e9e6dd3146dafb04690c5987b15aed49.js:1091)
	step (e9e6dd3146dafb04690c5987b15aed49.js:2266)
	(anonymous function) (e9e6dd3146dafb04690c5987b15aed49.js:2277)
	promiseReactionJob

#### Code to reproduce the bug / link to feature request

Same issue is seen in 

https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html

**Comment by dsmilkov** [comment]
That error in the console is expected. We tests some webgl features in the browser, and Safari logs an error, which we they take into account when deciding what webgl features are supported.

Other than that log message, do you see any issues with the game itself?

**Comment by guillochon** [comment]
I have this same error, and when I get this error the prediction I'm getting out of my model is way off from what I get out of Chrome/Firefox. This is using a Macbook Pro 2013 with an embedded GPU.

**Comment by dsmilkov** [comment]
Hi @guillochon,

Are you getting this error on the [webcam-transfer-learning](https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html) demo page, or on your own project. I'm asking since our demos use an old version of tf.js that had numerical problems in Safari, which reminds me we need to refresh our demos. cc @nsthorat since he's done deployment.

**Comment by guillochon** [comment]
This is on my own project, using the latest version of tfjs (0.11.7).

**Comment by guillochon** [comment]
Hi @dsmilkov, can't share a live demo at the moment but I can share the error + the relevant javascript.

Here's the full stack trace from Safari:

```
[Error] WebGL: INVALID_ENUM: readPixels: invalid type
	readPixels
	isDownloadFloatTextureEnabled (tfjs@0.11.7:2:148433)
	get (tfjs@0.11.7:2:149610)
	readSync (tfjs@0.11.7:2:261489)
	(anonymous function) (predict.js:29)
	tidy (tfjs@0.11.7:2:73794)
	predict (predict.js:19)
	success (predict.js:235)
	i (jquery.min.js:2:27457)
	fireWith (jquery.min.js:2:28217)
	y (jquery.min.js:4:22604)
	c (jquery.min.js:4:26752)
```

And javascript:
```
function predict(imageData, propRadius) {

  console.log(tf.memory().numBytes);
  console.log(tf.getBackend());
  return tf.tidy(() => {

    // Convert the canvas pixels to a Tensor of the matching shape
    img = tf.tensor(imageData);
    img = tf.cast(img, 'float32');
    mean = tf.scalar(102.32204);
    std = tf.scalar(50.741535);
    img = img.sub(mean).div(std);
    img = img.reshape([1, 512, 512, 3]);
    img = this.model.predict(img).mul(
      tf.scalar(255.0)).dataSync();

    const output = Uint8ClampedArray.from(img);

    drawImage(output, propRadius);

    return output;
  });
}
```

**Comment by dsmilkov** [comment]
Thanks! Is `imageData` an instance of [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) or a regular array of values?

**Comment by guillochon** [comment]
It’s an array of regular values I believe, originates as the payload of an ajax call:

```
$.ajax({
    url: 'queries/' + path.replace('.png', '.json'),
    dataType: 'json',
    success: function(json) {
      img = predict(json, radius);
      document.getElementById('analyzer').style.display = 'none'
      document.getElementById('imwrap').style.display = 'block'
      document.getElementById('maskswitch').style.display = 'block'
    },
    complete: function() {
      document.getElementById('metrizer').style.display = 'block'
      document.getElementById('btn').disabled = false;
      metrics(img, head);
    }
  });
```

**Comment by dsmilkov** [comment]
Closing the issue since we fixed the spurious error message regarding WebGL: INVALID_ENUM: readPixels: invalid type.
