### ISSUE TITLE
All the documentation points to archived repos with empty README files

### ISSUE THREAD

**Issue by aledalgrande** [tensorflow/tfjs#1999]
#### TensorFlow.js version
1.2.9

#### Browser version
N/A

#### Describe the problem or feature request
As per title, docs like [Model conversion](https://www.tensorflow.org/js/guide/conversion) point to this [repo](https://github.com/tensorflow/tfjs-converter) and the README is completely void of information for someone who wants to learn.

#### Code to reproduce the bug / link to feature request
N/A

**Comment by rthadur** [comment]
this will be resolved by this PR https://github.com/tensorflow/tfjs-website/pull/331, thank you for reporting.
