### ISSUE TITLE
Unknown layer: KerasLayer

### ISSUE THREAD

**Issue by aledalgrande** [tensorflow/tfjs#2000]
#### TensorFlow.js version
1.2.9

#### Browser version
NodeJS 11.3.0

#### Describe the problem or feature request
After converting a model created with a layer from TF Hub (MobileNetV2) with TF 2.0RC, and running `loadLayersModel`, I get:
```
Unknown layer: KerasLayer. This may be due to one of the following reasons:
    1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
    2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
```

#### Code to reproduce the bug / link to feature request
```python
# model created like this during training (Python)
feature_extractor_layer = hub.KerasLayer(feature_extractor_url,
                                         input_shape=(224,224,3))

model = tf.keras.Sequential([
  feature_extractor_layer,
  layers.Dense(image_data.num_classes, activation='softmax')
])
```

```sh
# model then converted like this
$ tensorflowjs_converter --input_format=keras input_file.h5 output_dir
```

```js
// model used like this in Node
const handler = tf.io.fileSystem('output_dir/model.json');
const model = await tf.loadLayersModel(handler);
```

**Comment by aledalgrande** [comment]
Any workaround for this?

**Comment by lucnat** [comment]
Still having this issue...any update?

**Comment by caisq** [comment]
@dsmilkov @pyu10055 Supporting `KerasLayer` will require some design. IIUC, KerasLayer wraps a TF Hub module as a Keras Layer. TF.js should have all the machinery to execute a GraphModel as a part of LayerModel, but this needs to be wired together. How that should be done needs to be thought through. Potential subtleties include:
1) signature-related issues
2) re-serialization 
3) should their be a more generic type than `KerasLayer`, e.g., `GraphModelLayer` that `KerasLayer` can inherit from.

The design should be reviewed by the TF Hub team as well.

**Comment by dsmilkov** [comment]
Hi,

Support for `KerasLayer` will probably not happen in the next 3 months due to the complexity of the solution.

For a workaround, can you try serializing the model to a `SavedModel`, convert saved_model --> tfjs_graph_model using the converter, and use `tf.loadGraphModel()` instead?

**Comment by caisq** [comment]
@aledalgrande Just to add to what @dsmilkov said: You need to save the Python using `tf.keras.experimental.export_saved_model`: https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model

Then use the `--input_format tf_saved_model` option with `tensorflowjs_converter`.

**Comment by aledalgrande** [comment]
Thanks, I ended up switching library because I couldn't wait. Will leave the thread open so it can be tracked for others.

**Comment by lucnat** [comment]
@caisq Thanks, the conversion works but when loading the model in tfjs I get an error  ```Provided weight data has no target variable: bn_Conv1/moving_mean``` 

Any ideas?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by aledalgrande** [comment]
was this implemented?

**Comment by caisq** [comment]
This bug shouldn't be closed. The new layer type hasn't been implemented yet.

**Comment by rasikanavarange** [comment]
Is there any update on when this might be implemented?

**Comment by JJwilkin** [comment]
I'm running into the same issue

**Comment by lucnat** [comment]
@rasikanavarange @JJwilkin This is fixed in more recent versions of tfjs. Consider updating.

**Comment by JJwilkin** [comment]
@lucnat I still get the Unknown Layer: KerasLayer with version 3.1.0  which appears to be the most recent

**Comment by raffizulvian** [comment]
I am facing the same issue while trying to load the model that I trained on python. The model using the [MobileNetV3](https://tfhub.dev/google/imagenet/mobilenet_v3_small_100_224/feature_vector/5) feature vector version from TF Hub.

- TensorFlow.js version = 3.6.0

Have there been any developments?

**Comment by x110** [comment]
i am running into the same issue

**Comment by Fume19** [comment]
i am running into the same issue

**Comment by azeemhassni** [comment]
I'm running into this issue on version `3.8.0` which is the most recent version.

**Comment by thibaut-d** [comment]
I also get "Error: Unknown layer: KerasLayer" when exporting with tfjs.converters.save_keras_model(model, "./test_tfjs"). I will test with other export options.

**Comment by rodrigoGA** [comment]
I have generated a model using tensorflow modelmaker and exported it
```

model = image_classifier.create(
    train_data, 
    validation_data=validation_data,
    shuffle = True, 
    epochs=50
)

model.export(export_dir='./tfjs-model', export_format=ExportFormat.SAVED_MODEL)
```

and then 

`model =  await tf.loadLayersModel("./tfjs-model/model.json");
`
throw the following error

```
Unknown layer: HubKerasLayerV1V2. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at deserializeKerasObject (generic_utils.js:227)
    at deserialize (serialization.js:25)
    at fromConfig (models.js:861)
    at deserializeKerasObject (generic_utils.js:258)
    at deserialize (serialization.js:25)
    at loadLayersModelFromIOHandler (models.js:222)
```

**Comment by khuezy** [comment]
From my understanding, and correct me if I'm wrong (new to tensorflow), the custom layer generated by Keras can't be serialized from python to js, so you have to implement the `KerasLayer` custom layer in JS. I haven't been able to find a port on the web yet.

A workaround is to not use Layers, but use Graph instead. Assuming you're not doing training on the browser and only doing predictions...

1. Save the Keras trained model as a "Saved Model" via: `tf.saved_model.save('model')
2. Convert it using `tensorflowjs_converter`: `tensorflowjs_converter --input_format=tf_saved_model model tfjs_model`
3. Load it in the browser (in web worker to prevent blocking): `const model = tf.loadGraphModel('/model/model.json')`

**Comment by gaikwadrahul8** [comment]
Hi, @aledalgrande 

Apologize for the delayed response and Could you please try with latest version of `@tensorflow/tfjs@4.4.0` and check whether this issue still exists or not ? We have updated official documentation w.r.t `tfjs-converter` [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) ? if issue still persists please let us know with model folder and  tfjs-converter command to replicate the same issue from our end ? Thank you!

**Comment by kalboussiKarim** [comment]
It's 2024 and i am facing this problem, any solution ?
