### ISSUE TITLE
Failed to install @tensorflow-models/deeplab

### ISSUE THREAD

**Issue by hoktin** [tensorflow/tfjs#2008]
I got an error with installing deeplab module. I see empty folder of @tensorflow-models when i check in node_modules folder. 

this is how my dependencies look like:
```
  "dependencies": {
    "@tensorflow-models/deeplab": "link:.yalc/@tensorflow-models/deeplab",
    "@tensorflow/tfjs-converter": "1.2.5",
    "@tensorflow/tfjs-core": "1.2.5",
    "bulma": "^0.7.5"
  },
```

this is the errors:
```
  18 | import 'bulma/css/bulma.css';
  19 | 
> 20 | import {load} from '@tensorflow-models/deeplab';
     |                   ^
  21 | import * as tf from '@tensorflow/tfjs-core';
  22 | 
  23 | import ade20kExampleImage from './examples/ade20k.jpg';
```

thanks,
@manrajgrover

**Comment by rthadur** [comment]
Hi @hoktin this is not an tfjs issue instead you can file a new issue [here](https://github.com/tensorflow/models/issues) in models repo. But I see an issue here as the [deeplab](https://github.com/tensorflow/models/issues) is  nested in research folder you might need to update the path.
