### ISSUE TITLE
pre-trained model getting trained again while tfjs execution

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#201]
I have created a keras model and saving in tfjs format like below:

```
model.fit( train_matrix , train_labels , nb_epoch=1, batch_size=128)
tfjs.converters.save_keras_model(model, "C:/Users/User/Desktop/Training/json")
```

when I am executing this model in tfjs, it is executing the epocs again. in this case 26 epocs are being executed in javascript when I called the json file.

I have already trained with those epocs before converting it to json, then is this  getting executed again ?

What to do if I don't want it to be executed while calling it in javascript file ?

**Comment by tafsiri** [comment]
Could you post your javascript code that loads the model/json?

**Comment by kallols** [comment]
@tafsiri  Please find below js code:

```
const model= await tf.loadModel('./json/model.json');
var newoutput=model.predict((tf.tensor(b)));
```

**Comment by tafsiri** [comment]
And what is the output you are seeing that you do not expect to see? Is there output for the 26 epochs mentioned in your issue?

**Comment by kallols** [comment]
@tafsiri  when the json file is called in browser, following things are executing(Please find the attachment and have a look). I don't want these epocs to be executed again in browser. 
![epoc issue](https://user-images.githubusercontent.com/32521972/38936729-0f50dcac-433f-11e8-94a7-5efb11ca20a1.PNG)

**Comment by tafsiri** [comment]
What you are seeing in the browser network tab is the model being downloaded from your server/disk. The model structure is in the .json file and the group1-*** files are the model weights split up into multiple files. There are no epochs being executed or training occurring.

**Comment by kallols** [comment]
@tafsiri okay. Thanks
