### ISSUE TITLE
support Lgamma and BroadcastTo Ops in order to support probabilistic models  (Poisson distribution)

### ISSUE THREAD

**Issue by lukasheinrich** [tensorflow/tfjs#2011]
When trying to covnert a model that uses `tensorflow_probability.distributions.Poisson` I get the error

```
ValueError: Unsupported Ops in the model before optimization
Lgamma, BroadcastTo
```

In order to support probabilistic models using those libraries itwould be great if those Ops could be added

@kratsg @matthewfeickert

https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/lgamma
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/broadcast-to

**Comment by dsmilkov** [comment]
Hi Lukas,

Can you share a bit about your model/use-case? There are a long tail of ops that TF.js is missing and we are trying to prioritize based on use-case.

**Comment by lukasheinrich** [comment]
hi @dsmilkov,

our specific use case is the computation of probabilistic models for high energy physics models at CERN, but I think being able to compute a Poisson distribution is probably of much broader appeal for any model using tensorflow probability.

**Comment by DirkToewe** [comment]
The rather monstrous [PR#1356](https://github.com/tensorflow/tfjs-core/pull/1356) contained a `broadcastTo` [implementation](https://github.com/tensorflow/tfjs-core/pull/1356/files#diff-b62631f91d28d56ddc898bc41513df9cR106-R156). If You want, I can take it out and submit it as PR to the monorepo.

**Comment by lukasheinrich** [comment]
hi @DirkToewe I think that would be awesome and maybe easier to merge. Do you know anytone working on lgamma?

**Comment by DirkToewe** [comment]
No idea sorry. A `float32/complex64` implementation of lgamma(z) for `Re(z) > 0` can be found in:
```
"Numerical Recipes in C",
2nd edition,
chapter 6, page 213f.
```
It's C code but fairly easy to read and understand. Should be fairly easy to implement using existing TFJS functions as well.

**Comment by kratsg** [comment]
@DirkToewe -- copying here for usefulness

```
#include <math.h>

// Returns the value ln[Γ(xx)] for xx > 0.
float gammln(float xx)
{
//Internal arithmetic will be done in double precision, a nicety that you can omit if five-figure
// accuracy is good enough.
    double x,y,tmp,ser;
    static double cof[6]={76.18009172947146,-86.50532032941677,
                          24.01409824083091,-1.231739572450155,
                          0.1208650973866179e-2,-0.5395239384953e-5};
    int j;
    y=x=xx;
    tmp=x+5.5;
    tmp -= (x+0.5)*log(tmp);
    ser=1.000000000190015;
    for (j=0;j<=5;j++) ser += cof[j]/++y;
    return -tmp+log(2.5066282746310005*ser/x);
}
```

**Comment by annxingyuan** [comment]
Noting that BroadcastTo is also needed for the music transformer model.

**Comment by gaikwadrahul8** [comment]
Hi, @lukasheinrich 

Apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs/pull/2238 got merged for [tf.broadcastTo](https://js.tensorflow.org/api/4.4.0/#broadcastTo) but at the moment It seems like we haven't implemented `Lgamma` Op so just to confirm still are you looking to add this `Lgamma` Op please ? Thank you!

**Comment by kratsg** [comment]
> Apologize for the delayed response and I see this PR #2238 got merged for [tf.broadcastTo](https://js.tensorflow.org/api/4.4.0/#broadcastTo) but at the moment It seems like we haven't implemented `Lgamma` Op so just to confirm still are you looking to add this `Lgamma` Op please ?

We definitely would want the LGamma op if you want to support Poisson distributions fully, no?

**Comment by kratsg** [comment]
@google-ml-butler not stale...

**Comment by matthewfeickert** [comment]
@dsmilkov as the @google-ml-butler isn't taggable on GitHub can you unstale this?
