### ISSUE TITLE
Throw useful error messages when tensor-inputs are not tensors.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#202]
Right now we have cryptic errors if you pass non-tensors to ops. Let's assert inputs are valid with a useful error messages in core.

I will take this on since it's tangentially related to stuff I was going to do about accepting numbers in place of tensors in some situations.

**Comment by dsmilkov** [comment]
We probably won't expect shapes to be specified as tensors, unless you have a concrete use-case that needs shape to be a tensor?

**Comment by dsmilkov** [comment]
Original issue fixed in https://github.com/tensorflow/tfjs-core/pull/967
