### ISSUE TITLE
Tensor shape inference

### ISSUE THREAD

**Issue by Piyush3dB** [tensorflow/tfjs#203]
The following code shows how shape inference can be used to statically query the shape of a tensor before the computation graph has been run:

```
>>> z = tf.zeros((1, 2, 3))
>>> z.get_shape().as_list()
[1, 2, 3]
```

Is there a function similar to `get_shape()` in tfjs?

**Comment by tafsiri** [comment]
In tfjs shape is a property/field of a tensor, so you can call `.shape` on your tensor (`z.shape` in this case)
