### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by mblls** [tensorflow/tfjs#2042]
I'm getting another CORS error when I load the JS file, I believe with the links trying to access the image set.

**Comment by janithwanni** [comment]
Which JS file ? The tensorflow.js file or tfjs vis file? and I have completed that codelab and I dont see anything regarding image sets in that codelab. In what step are you getting the error

**Comment by mblls** [comment]
<img width="546" alt="Screen Shot 2019-09-15 at 8 02 10 PM" src="https://user-images.githubusercontent.com/38448078/64929413-b7ab6a80-d7f3-11e9-8cea-9adb7e919b66.png">

**Comment by rthadur** [comment]
@mblls above files are from your local system and hosted by our team , closing this issue , thank you.
