### ISSUE TITLE
Converting BodyPix to TensorFlow Lite

### ISSUE THREAD

**Issue by JakeWade3** [tensorflow/tfjs#2043]
Hello, I was wondering if its possible to convert the BodyPix model to a TensorFlow Lite model for running on Android and iOS. I found a discussion on this GitHub about this 

https://github.com/tensorflow/tfjs/issues/1280

The issue was closed as it was not possible to convert this model back into a tensorflow saved model, I was wondering if this is now available/possible.

Thanks

**Comment by pyu10055** [comment]
@tylerzhu-github can you answer this question? thanks.

**Comment by tylerzhu-github** [comment]
Thanks for adding me Ping! 
Thanks Jake for interested in using BodyPix for your project!

For PoseNet, we have released the model in .tflite format here:
Android: https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android
Coral TPU: https://github.com/google-coral/project-posenet

Here is a contribution from our community users:
https://medium.com/flutter-community/posenet-for-ios-android-and-flutter-using-tensorflow-lite-836788a110c7

You are right that currently tfjs_convertor doesn't support converting the TensorFlow.js GraphModel back to SavedModel format. We will try to release a BodyPix model in TensorFlow Lite format with demos. 

Quick question for Ping is: can we host non TensorFlow.js model/assets (e.g. TensorFlow Lite file)?

**Comment by pyu10055** [comment]
@tylerzhu-github I think we can host the tflite file on TFHub storage.

**Comment by JakeWade3** [comment]
Thanks for the replies, so reading this there is a TensorFlow Lite model kicking around somewhere but it just needs hosting?

**Comment by gdgggithub** [comment]
I would also like to have this model data for my project if available pls inform thx a lot in advance!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sreed101** [comment]
@tylerzhu-github I would like to use BodyPix in a Python project. Is it possible to get the original TensorFlow model?

**Comment by JakeWade3** [comment]
Why was this issue closed? As I am waiting on one of you guys / tensor-flow guys to respond, or at least point me where I can get the original model for use with TensorFlow Lite

**Comment by darcula1993** [comment]
> @tylerzhu-github I would like to use BodyPix in a Python project. Is it possible to get the original TensorFlow model?

That would be great! Bodypix and Posenet are truly marvelous project. I would like to use them on other platform on which tfjs is not compatible.

**Comment by dallarosa** [comment]
I'd love to use this with TFLite for Android so if it would be great if you could release the original tensorflow model or at least the the tflite version

**Comment by tylerzhu-github** [comment]
Hi @JakeWade3, @gdgggithub, @sreed101, @darcula1993, @dallarosa,  

Sorry for the delayed reply! 
I agree with what @pyu10055 suggested about hosting the models on TFHub.
Currently I am in the middle of making the corresponding model available via TFHub together with TensorFlow and TensorFlow.js teams. This process might take time.

Thx for the patience!!

Best,
Tyler

**Comment by darcula1993** [comment]
@tylerzhu-github thank you very much for your reply.
@dallarosa @JakeWade3 @gdgggithub @sreed101 
If you need a tf-format bodypix or posenet model, you can use 
`https://github.com/patlevin/tfjs-to-tf`
to convert the tfjs-graph model into tf fronzen graph.  You can also extract weights from it if you want to build your own posenet or bodypix.

I convert a mobilenetV1_float_100 posenet tfjs model into a keras h5 model here just in case anyone need it:
[posenet.zip](https://github.com/tensorflow/tfjs/files/3943875/posenet.zip)

**Comment by rthadur** [comment]
@JakeWade3 was your question answered ?

**Comment by JakeWade3** [comment]
@rthadur Not yet, still haven't had any links or information for when the body pix TensorFlow lite model ready.

**Comment by rthadur** [comment]
@tylerzhu-github gentle ping if you have any update ?

**Comment by jernsting** [comment]
@darcula1993 could you please explain how you converted the posenet to an hd5 file? I can only see the function to convert the graph model to a tensorflow graph model (.pb file).

**Comment by darcula1993** [comment]
> @darcula1993 could you please explain how you converted the posenet to an hd5 file? I can only see the function to convert the graph model to a tensorflow graph model (.pb file).

Using https://github.com/patlevin/tfjs-to-tf, you can extract weight from tfjs model. Then I build the model architecture using keras and loading weights layer by layer.Since we have layer name, it is not that hard.

**Comment by dallarosa** [comment]
> @tylerzhu-github thank you very much for your reply.
> @dallarosa @JakeWade3 @gdgggithub @sreed101
> If you need a tf-format bodypix or posenet model, you can use
> `https://github.com/patlevin/tfjs-to-tf`
> to convert the tfjs-graph model into tf fronzen graph. You can also extract weights from it if you want to build your own posenet or bodypix.
> 
> I convert a mobilenetV1_float_100 posenet tfjs model into a keras h5 model here just in case anyone need it:
> [posenet.zip](https://github.com/tensorflow/tfjs/files/3943875/posenet.zip)

Thanks for this! It should probably do the job for me. I'll check it out :)

**Comment by KapoorHitesh** [comment]
Can we have some example usage of the boypix model in python?

**Comment by ajaichemmanam** [comment]
> Can we have some example usage of the boypix model in python?

See https://github.com/ajaichemmanam/simple_bodypix_python

**Comment by JakeWade3** [comment]
Was wondering if there's any updates for this? For BodyPix on Tensorflow Lite?

**Comment by mahendran-narayanan** [comment]
@KapoorHitesh You can refer this ml5js and p5js example code.
https://github.com/ml5js/ml5-examples/tree/release/p5js/BodyPix

**Comment by hegman12** [comment]
For my personal project, i had to use bodypix in android so I ended up re implementing a part of bodypix in python( specifically SegmentMultiPersonParts using mobilenet).
[ You can find the tflite model here ](https://github.com/hegman12/body_pix_tflite/tree/master/converter_example/tflite/converted). 
[A demo app here](https://github.com/hegman12/body_pix_tflite/tree/master/example)  
[How to convert tfjs to tflite here](https://github.com/hegman12/body_pix_tflite/tree/master/converter_example) 
[A flutter plugin for bodypix here](https://github.com/hegman12/body_pix_tflite)

Sample results below

![image](https://user-images.githubusercontent.com/24982961/84034613-dca3c700-a99a-11ea-8811-9ff5f0ee6eb1.png)

Hope this helps!

**Comment by josh-nathanson** [comment]
@tylerzhu-github Hi Tyler,

Has BodyPix model to a TensorFlow Lite model for iOS development been released yet? Would love to use it for mobile application development

Thanks

**Comment by josh-nathanson** [comment]
Does anyone have a solution for this?^

**Comment by mianaliasjad** [comment]
Guys i think instead of asking BodyPix TensorFlow Lite model we can use [Segmentation](https://www.tensorflow.org/lite/models/segmentation/overview) from TensorFlow lite.

**Comment by mishan** [comment]
@mianaliasjad from my (very limited) experience, BodyPix seems to perform more accurately

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
