### ISSUE TITLE
dot product unit test fails with WEBGL_PACK: false

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#2044]
To reproduce:
`yarn test --testEnv webgl2 --flags '{"WEBGL_PACK": false}'`

The test that fails is: https://github.com/tensorflow/tfjs/blob/dd5d9ed60e9cadf0426304d5a470504fd9b6d44a/tfjs-core/src/ops/matmul_test.ts#L1151

**Comment by annxingyuan** [comment]
Caused by https://github.com/tensorflow/tfjs-core/pull/1543
