### ISSUE TITLE
[Layers] Use the public API in unit tests.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#205]
Right now we test against the classes directly, which causes things like this bug:
https://github.com/tensorflow/tfjs/issues/204

We should use the public API to test the functionality of layers (testing all the way through exports).

Specifically, in unit tests, import index and test through that: `import * as tfl from 'index';`

**Comment by bileschi** [comment]
#137 is intended to fix this issue.  External API is now used in most locations where the such API is exposed.
