### ISSUE TITLE
Support uint8 dtype

### ISSUE THREAD

**Issue by ry** [tensorflow/tfjs#206]
Is this a desired feature?

**Comment by dsmilkov** [comment]
Yes, it is on our roadmap for doing quantized math in our shaders, but our shaders right now only work with floats. Curious if you had a different use case in mind?

**Comment by ry** [comment]
Would you be opposed to adding uint8 now before having quantized shader support? Even if it offers no storage size benefit in WebGL, it would be good to be able to future proof code that wanted to handle uint8 tensors. EG a library that returned MNIST images.

**Comment by dsmilkov** [comment]
Since doing math with uint8 is not possible yet, adding uint8 as a type is not the highest priority for now, but we want to eventually add it. Is it an option for you to store those images using native `UInt8Array` for now?

**Comment by dsmilkov** [comment]
Starting with something small would be great. I'll be happy to review and get that in. Thanks!

**Comment by rthadur** [comment]
@nsthorat do you want this issue to be a placeholder or someone else is working on it.

**Comment by alew3** [comment]
Does TFJS support uint8 quantization? I ask because it is one of the options in quantization:

tfjs.converters.save_keras_model(model, "q8",quantization_dtype=np.uint8)

but the results don't work properly. uint16 behaves correctly.

**Comment by TheNewSound** [comment]
I'd like to see (u)int8 tensor support in order to take advantage of enhanced INT8 performance of NVIDIA's Tensor Cores.

Maybe the same goes for FP16 support but that could be a lower priority since I suspect Tensorflow.js already takes advantage of Tensor Cores in FP32 mode.

**Comment by npip99** [comment]
Is there any status on int8 in Tensorflow? It seems like Int8 inference is a crucial 3-4x speedup when doing AlphaZero-style reinforcement learning. With

```
tensorflowjs_converter \
    --input_format=tfjs_layers_model \
    --output_format=tfjs_layers_model \
    --quantize_uint8 '*' \
    ./models/MyModel/model.json ./models/MyInt8Model
```

this makes a model with uint8 quantization, but when actually running the model in `tfjs-backend-wasm` or `tfjs-node-gpu`, inference speeds appear identical.

**Comment by gaikwadrahul8** [comment]
Hi, @ry 

Apologize for the delayed response and I see we have updated our official documentation w.r.t tfjs-converters flag option with `--quantize_uint8` so just to confirm that is what you were looking or Am I missing something here ? 

Please refer this [official documentation ](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter). Thank you!
