### ISSUE TITLE
Advice needed on how to support a custom op from tensorflow/addons

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tfjs#2062]
I would really like to be able to use a custom op from tensorflow/addons with tensorflow.js (both the webgl backend or node.js backend would work).

Here is a link to the op: https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/optical_flow.py

Since it uses a custom C++ op, this would probably be tricky. It sounds like my options are currently:
- WebGL: Implement a WebGL op and add it to the list of supported ops
- Node.js: Add the existing C++ op from tensorflow/addons to the converter, which would only work for Node.js 

Am I missing anything here? Do you have any advice on how to proceed? Both routes sound fairly daunting -- am I better off switching to a client server architecture if I really need this?

**Comment by rthadur** [comment]
@dsmilkov any suggestions for above feature request ?

**Comment by pyu10055** [comment]
@evancasey This looks like an custom TF layer, which is different from the core TF ops.
Have you tried to save you model to saved model format? TF keras layers will be break down into TF ops automatically, you might not need to implement anything new, if it can be broken down into existing TF ops.

**Comment by evancasey** [comment]
There is both a custom TF layer and also a [custom C++ op](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/optical_flow.py#L96-L104) used within the layer. Can that be broken down into TF ops automatically?

**Comment by pyu10055** [comment]
@evancasey oh, if there is a custom TF c op then it would be broken down.
You can either create a new TFJS op, or use the registerOp method defined [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/src/operations/custom_op/register.ts#L47).

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
