### ISSUE TITLE
Add LayersModel.dispose to public api docs

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#2069]
#### TensorFlow.js version
1.2.9

#### Describe the problem or feature request
We should add https://github.com/tensorflow/tfjs/commit/202127da67c3812ee388fd966cee4667814707e6 to the api docs.

**Comment by rthadur** [comment]
This has been updated in api docs here https://js.tensorflow.org/api/latest/#tf.layers.Layer.dispose.Closing this request.
