### ISSUE TITLE
baseball-node client not loading

### ISSUE THREAD

**Issue by PiyushRamuka** [tensorflow/tfjs#2075]
## Describe the problem or feature request
Followed the steps to set-up and run baseball-node example on MacOS Mojave with Node 8.15.0. Server and the client are running but "localhost:8080" does not load.
![image](https://user-images.githubusercontent.com/7099771/65336491-74a31b80-db94-11e9-873f-027645554b90.png)

Will appreciate any help resolving this issue. Thanks!

**Comment by caisq** [comment]
Assigning to @nkreeger, the original author of the example and who's more familiar with it.

**Comment by kangyizhang** [comment]
@PiyushRamuka The client site works on my machine. What did you see when you open localhost:8080?

**Comment by PiyushRamuka** [comment]
@kangyizhang - The client doesn't load and browser gives timeout error. Are there any log files I can upload to help resolve this issue?

**Comment by PiyushRamuka** [comment]
@kangyizhang - please let me know if there is anything I can do on my end to provide more insight into this issue. Thanks in advance.

**Comment by kangyizhang** [comment]
@PiyushRamuka since I can not reproduce this issue, it would be helpful to debug on your end. Looks like it has nothing to do with the tfjs-node library, but with webpack or browser config. Can you remove script src bundle.js in index.html and try `yarn start-client`? It should say "Waiting for server..." with no js code.

**Comment by PiyushRamuka** [comment]
@kangyizhang - thanks for your response. I removed the script src bundle.js from index.html. Interestingly the page shows "Waiting for server..." when loaded for the first time. When refreshed/reloaded, it doesn't load again. I will try to run this again on a windows PC later today. Will keep you posted. Thanks once again!

**Comment by rthadur** [comment]
@PiyushRamuka were you able to run this on windows PC ?

**Comment by PiyushRamuka** [comment]
@kangyizhang & @rthadur - I was able to run the example on a windows machine without issues. It must be a webpack issue on Mojave.
