### ISSUE TITLE
Where did the old deeplearnjs issues go? 

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#209]
I was looking for an issue that @tafsiri solved in Deeplearnjs that would have been useful with Tensorflowjs, but it looks like the old issues have all been cleansed. Is there an easy way to get them back? I often search through closed issues when I am really stuck.  This is the one I was looking for which was cached in my browser, but not live online.

![image](https://user-images.githubusercontent.com/5605614/39029719-225cbd42-4412-11e8-814f-3de67e474b92.png)

**Comment by tafsiri** [comment]
@hpssjellis we closed/disabled github issues on tfjs-core (which was previously tfjs-core) and moved open issues to this repository (so we could track everything in one place). Unfortunately there isn't a way that I am aware of on GitHub to allow access to the old issues while disabling submitting new issues to that repository.
