### ISSUE TITLE
Universal Sentence Encoder in webworkers

### ISSUE THREAD

**Issue by arherzf8er** [tensorflow/tfjs#2091]
### TensorFlow.js version
1.2.9
#### Browser version
Version 77.0.3865.90 (Official Build) (64-bit)
#### Describe the problem or feature request
Can't `embed()` sentences in webworkers (despite the fact I can do it in main thread)
#### Code to reproduce the bug / link to feature request
```
importScripts('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.2.9/dist/tf.min.js');
importScripts('https://cdn.jsdelivr.net/npm/@tensorflow-models/universal-sentence-encoder@1.1.1/dist/universal-sentence-encoder.min.js');
tf.setBackend('cpu');

onmessage = () =>
  use.load().then(model => {
    console.log(Object.keys(model)) // [ 'model', 'tokenizer' ]
  });
```

**Comment by rthadur** [comment]
@arherzf8er i was able to run successfully with the above code , can you please recheck.

**Comment by arherzf8er** [comment]
@rthadur thanks for checking, could you please share your full code for main thread and webworker?
There should be something that I missed somehow (weird that `model` has only 2 properties)

**Comment by arherzf8er** [comment]
`use.load().then(model => console.log(model))`

![image](https://user-images.githubusercontent.com/29209372/65639681-46d53100-dff1-11e9-80b4-1f415cd10a5b.png)
