### ISSUE TITLE
tensor shape issues

### ISSUE THREAD

**Issue by thirukumars** [tensorflow/tfjs#2100]
while workonh with ml5js,i am getting this weird error,,i don't whats wrong

ml5.min.js:818 Uncaught (in promise) Error: Based on the provided shape, [3,3,1024,512], the tensor should have 4718592 values but has 1805028
    at w (ml5.min.js:818)
    at Pn (ml5.min.js:3510)
    at i (ml5.min.js:13910)
    at Object.oc [as decodeWeights] (ml5.min.js:13915)
    at ml5.min.js:20090
    at ml5.min.js:15668
    at Object.next (ml5.min.js:15680)
    at o (ml5.min.js:15569)

**Comment by thirukumars** [comment]
this is my code,please check guys


import React, { Component , Fragment } from 'react';
import ml5 from 'ml5'
import p5 from 'p5'
import "bootstrap/dist/css/bootstrap.min.css";
import "p5/lib/addons/p5.dom";
import './object.css'
var video;
var yolo;
var stop=false
var no_of_times=0;
// export
 let objects = [];


export  default class Detection extends Component {
    // constructor() {
    //     super()
    //     // this.stop = this.stop.bind(this)
    // }


    componentDidMount() {
        // this.call()
        this.sketch = new p5( p => {
            // p.preload = function() {
            //     // if(no_of_times === 0) {
            //         video = p.createCapture(p.VIDEO)
            //         video.parent('videoContainer')
            //         video.hide();
            //     // }           
            // }
            p.setup = function () {
                // stop = false
                // if(no_of_times === 0){
                    p.createCanvas(480,440)
                    //imitialize the webcam stream in a object
                    video = p.createCapture(p.VIDEO)
                    // p.background(100,0,100)
                    video.parent('videoContainer')
                    video.size(480,440) 
                    // no_of_times++;
                    video.hide();
                    
                    yolo = ml5.YOLO(video, startDetecting)
                    console.log("caught")
                // } else {
                //     p.createCanvas(0,0)
                //     //imitialize the webcam stream in a object
                //     video = p.createCapture(p.VIDEO)
                //     video.parent('videoContainer')
                //     video.size(600,440) 
                //     // no_of_times++;
                //     video.hide();
                //     yolo = ml5.YOLO(video, startDetecting)

                // }
            };
            p.draw =  () => {
                // if(no_of_times===0)
                p.image(video,0,0);
                // p.noLoop();
    
                for(let i = 0;i < objects.length;i++){
                    p.noStroke();
                    p.fill(0, 0, 255);
                    p.text(objects[i].label, objects[i].x * p.width, objects[i].y * p.height - 5);
                    p.noFill();
                    p.strokeWeight(4);
                    p.stroke(0, 0, 255);
                    p.rect(objects[i].x * p.width, objects[i].y * p.height, objects[i].w * p.width, objects[i].h * p.height);
                }
            };
            function startDetecting() {
                //status.html('Model loaded!');
                console.log('Model Ready');
                detect();
            };

            function detect() {
                yolo.detect(video,(err, results)=> {
                objects = results;
                console.log(objects)
                    
               
                // if(stop === false)
                detect();
                })
            }   
    })
    }
    
    // call = () =>
    // stop(){
    //     stop = true
    //     no_of_times++
    // }
    
    render(){

        return(

            <Fragment>
                <div id ="videoContainer" className="center" >

                </div>

               
{/* 
                <div style={{position: "absolute", top: "120%", left: "50%"} }>
                    <button
                        ref="startBtn"
                        className="btn btn-success"
                        id="btnStart"
                        onClick={this.call}
                        style = {{
                        color: "white",
                        fontStyle: "bold"
                        }}
                    >
                    Start
                    </button>
                    <button
                        className="btn btn-danger"
                        id="btnStop"
                        onClick={this.stop}
                        style={{
                        marginLeft: "15px",
                        color: "white"
                        }}
                        >
                        Stop
                    </button>
                    </div>*/}
                </Fragment> 

        );
    }
}

**Comment by tafsiri** [comment]
Hi @thirukumars, i noticed that you already [opened an issue](https://github.com/ml5js/ml5-library/issues/586) on the ml5 repo. I think that is the best place for this question since you are using the ML5 wrapper. So I'll close this issue to allow focus on that one. All the best!
