### ISSUE TITLE
feature request: tf.node - support saving to / loading from numpy array

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2101]
It would be great if from `tf.node` you can save tensors in a format that can be loaded in numpy with [numpy.load](https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html), such as in the `.npy` format.  And conversely, it would be great if you can load numpy array files saved as .npy into tensorflow.js with `tf.node`.

**Comment by gaikwadrahul8** [comment]
Hi, @oveddan 

Apologize for the delayed response and It seems like we haven't implemented this feature as of now so May I know are you still looking to add this feature in TFJs please ? Thank you!
