### ISSUE TITLE
Calling tf.Sequential() uppercase, has bad, strange effect

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#211]
#### TensorFlow.js version
0.9.1

#### Browser version
Chrome 66.0

#### Describe the problem or feature request
Calling tf.Sequential() (incorrectly... uppercase... removes 'layers' from the tf object.

#### Code to reproduce the bug / link to feature request

```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.9.1"> </script>
    <script>
      tf.sequential();
      console.log(tf.layers);
      tf.Sequential();
      console.log(tf.layers);
    </script>
  </head>
  <body></body>
</html>
```

**Comment by nsthorat** [comment]
I don't think there's any way to detect this :/
