### ISSUE TITLE
Nightly benchmark fails due to converter's out-of-date import from tensorflow

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#2110]
This started happening today.

Steps to reproduce the problem:

Run the benchmark: 
```sh
cd tfjs/integration_tests
yarn benchmark --layers
```

See the error message that happens when the converter runs:

> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/tfjs/tfjs/tfjs/integration_tests/python/benchmarks.py", line 43, in <module>
>     import tensorflowjs as tfjs
>   File "/tmp/tmp.mDMdkLFlbp_venv/lib/python3.6/site-packages/tensorflowjs/__init__.py", line 21, in <module>
>     from tensorflowjs import converters
>   File "/tmp/tmp.mDMdkLFlbp_venv/lib/python3.6/site-packages/tensorflowjs/converters/__init__.py", line 24, in <module>
>     from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model
>   File "/tmp/tmp.mDMdkLFlbp_venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 41, in <module>
>     from tensorflowjs.converters import fuse_prelu
>   File "/tmp/tmp.mDMdkLFlbp_venv/lib/python3.6/site-packages/tensorflowjs/converters/fuse_prelu.py", line 200, in <module>
>     register_prelu_op()
>   File "/tmp/tmp.mDMdkLFlbp_venv/lib/python3.6/site-packages/tensorflowjs/converters/fuse_prelu.py", line 52, in register_prelu_op
>     op_def_registry.register_op_list(missing_op_list)
> AttributeError: module 'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'
>

**Comment by pyu10055** [comment]
This integration test is using nightly TF, but our pip is based on 1.14, we should align otherwise this type issue will happen more often.

**Comment by caisq** [comment]
@pyu10055 I can make that change. 

But in the larger context, this problem needs to be fixed in order to unblock future releases, right?

**Comment by pyu10055** [comment]
this fixed by PR https://github.com/tensorflow/tfjs/pull/2106
