### ISSUE TITLE
bidirectional wrapper throws assertFeedCompatibility error

### ISSUE THREAD

**Issue by m4nuC** [tensorflow/tfjs#213]
#### TensorFlow.js version
v0.9.0
#### Browser version
Chrome V65
#### Describe the problem or feature request
Using a bidirectional wrapper around an LSTM layer throws the following error:
**Uncaught (in promise) TypeError: Cannot read property 'dtype' of undefined at assertFeedCompatibility**

#### Code to reproduce the bug / link to feature request
```
const X = tf.tensor(this.toOneHot([1, 2, 4, 8, 8, 8, 8], 10)).expandDims(0);
const Y =  tf.tensor(this.toOneHot([2, 4, 8, 8, 8, 8, 1], 10)).expandDims(0);

const model = tf.sequential();
const lstm = tf.layers.lstm({units: 5, returnSequences: true, batchInputShape: [1, 7, 10]})
model.add(
  tf.layers.bidirectional({layer: lstm, inputShape: [7, 10], mergeMode:'add'})
)
model.add(tf.layers.dense({units: 10, activation: 'softmax'}))
model.compile({
  optimizer: tf.train.adam(0.01),
  loss: 'categoricalCrossentropy',
  metrics: ['accuracy']
})

for( let i = 0; i < 5; i ++ ) {
  const history = await model.fit( X, Y, {batchSize: 1, epochs: 1});
  console.log(history.history.loss)
}

const predict = model.predict(X, {verbose: true, batchSize:1})
tf.argMax(predict, 2).print()
```

**Comment by dadadel** [comment]
Hi,

I've got the same issue with version 0.10.0

**Comment by m4nuC** [comment]
Is anyone working on this ? Else if someone can point me in the right direction I am happy to take a stab at it.

**Comment by rthadur** [comment]
@m4nuC Please let us know if this still an issue ?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
