### ISSUE TITLE
Enable strictNullChecks

### ISSUE THREAD

**Issue by evmar** [tensorflow/tfjs#2148]
TypeScript has a 'strictNullChecks' feature that makes the type system more strict around handling of null.

I see there have been multiple bugs filed by users who have been confused about this:
  https://github.com/tensorflow/tfjs/issues?q=is%3Aissue+strictnullchecks+is%3Aclosed
but there appears to be no overarching bug about actually turning it on.

---

I normally think it's totally up to you whether you enable a flag or not.  But importantly in this case, when you don't use this flag, the *API* you provide also is unclear about how null is handled.  For example, if you have some function

```ts
export function getWhatever(): string { return null; }
```

Then if some user code in a project with strict null checks on uses this function, they will think that this function can never return null.  This is especially confusing because in my experience most TypeScript code is null-checks-correct (it is the default setting to have it on), so it means the other APIs they're using from other libraries will clearly document whether the functions can return null or not, so it's a surprise when it silently does the wrong thing here.

(You might suggest: why doesn't TypeScript just add an `|null` to the signature of *every* function in tfjs when producing its API definition?  It turns out that ends up not quite working for subtle reasons related to co/contravariance, which I can go into if you're into type system nerdery but otherwise suffice it to say that TS cannot do so in general.)

**Comment by evmar** [comment]
(This is also blocking Google-internal bug b/114839683, which is why I was inspired to file this.)

**Comment by rthadur** [comment]
@evmar thank you for reporting this , @dsmilkov @nsthorat any thoughts on this request ?

**Comment by evmar** [comment]
I tried turning it on in tfjs-layers just to see how bad it would be.

It pointed out that logic is a bit strange:
https://github.com/tensorflow/tfjs/blob/c8a47c34c25a140452ce731dbf5d6255d00f24d6/tfjs-layers/src/engine/topology.ts#L1603

The nodeIndex param is optional, but if it's provided then we clobber it with something else, and then unconditionally use it as an index into an array a few lines later (where it may still be 'undefined').  Maybe the `if` condition is inverted?

**Comment by dsmilkov** [comment]
Hi Evan,

This will be a massive undertake and not worth the benefit for now. Also most of our users are JS and those that are TS users are not very familiar with the strict null check, in contrast to what we do internally at Google.

I haven't seen many bugs reported that would be fixed by a null check. We also usually rely on extensive unit testings for that instead of static typing.

I'm willing to revisit this in the future when we get more signal.
