### ISSUE TITLE
[Umbrella Entry] BodyPix 2.0 Enhancement PRs

### ISSUE THREAD

**Issue by tylerzhu-github** [tensorflow/tfjs#2153]
BodyPix 2.0 Enhancement Follow up PRs

#### After BodyPix 2.0 main [PR](https://github.com/tensorflow/tfjs-models/pull/280) is merged, the following enhancement PRs should address:
- Shares utility code between BodyPix 2.0 and PoseNet 2.0 [[pr](https://github.com/tylerzhu-github/tfjs-models/pull/1)] (TODO: @oveddan)  
- Updates the BodyPix 2.0 README.md file [[pr](https://github.com/tensorflow/tfjs-models/pull/304)] (TODO: @tylerzhu-github)
- Supports specifying `input_height` and `input_width` separately [[pr](https://github.com/tensorflow/tfjs-models/pull/296)] (TODO: @oveddan)
- Attempts performance (measured by fps) optimization (TODO: @tylerzhu-github)
- In the demo, added an option to pass, in the query string: backend=cpu to test cpu based decoding. In the demo, defaulting to use MobileNet. [[pr](https://github.com/tylerzhu-github/tfjs-models/pull/2)][[reopened pr](https://github.com/tylerzhu-github/tfjs-models/pull/3)] (TODO: @oveddan)
- Refactored the estimate segmentation methods to have separate activation functions, and be more concise/readable [[pr]](https://github.com/tylerzhu-github/tfjs-models/pull/2)[[reopened pr](https://github.com/tylerzhu-github/tfjs-models/pull/3)] (TODO: @oveddan)
- Added some tests around valid resolution [[pr](https://github.com/tylerzhu-github/tfjs-models/pull/2)][[reopened pr](https://github.com/tylerzhu-github/tfjs-models/pull/3)] (TODO: @oveddan)

**Comment by nsthorat** [comment]
Can we separate these into separate issues so each of these can be solved in a separate PR (it greatly reduces the time it takes to review if the PRs are smaller)

**Comment by tylerzhu-github** [comment]
Thx! I have break them in to the following separate issues:
* https://github.com/tensorflow/tfjs/issues/2183
* https://github.com/tensorflow/tfjs/issues/2184
* https://github.com/tensorflow/tfjs/issues/2185
* https://github.com/tensorflow/tfjs/issues/2186
* https://github.com/tensorflow/tfjs/issues/2187
* https://github.com/tensorflow/tfjs/issues/2188
*  https://github.com/tensorflow/tfjs/issues/2189
