### ISSUE TITLE
tfjs-node-gpu for windows.

### ISSUE THREAD

**Issue by conorpo** [tensorflow/tfjs#2154]
Was hoping you guys could add windows support for tfjs-node-gpu. Having it only available for linux is a bit limiting. And I cant use tfjs-node either because I have an AMD cpu.

**Comment by rthadur** [comment]
please refer to this [link](https://github.com/tensorflow/tfjs-node/tree/master/tfjs-node) , this explains steps to installing tfjs-node-gpu on windows.
