### ISSUE TITLE
Bug in tfjs-models/knn-classifier demo and tutorial

### ISSUE THREAD

**Issue by isaac-fisher** [tensorflow/tfjs#2157]
In the `tfjs-models/knn-classifier/demo` as well in its [tutorial](https://codelabs.developers.google.com/codelabs/tensorflowjs-teachablemachine-codelab/index.html#6), there is a bug that causes the classifier to work only if the user clicks on the 'add example' buttons in an ordered way. If you try to classify not in order, like starting with the second button before the first, the result will be wrong (it'll predict the first instead of the second).      
    
**The fix:**    
in tfjs-models/knn-classifier/demo/camera.js:148: `if (res.classIndex == i) {`
should be: `if (res.label == i) {`    
in the tutorial: 
```
      document.getElementById('console').innerText = `
        prediction: ${classes[result.classIndex]}\n
        probability: ${result.confidences[result.classIndex]}
      `;
```
should be
```
      document.getElementById('console').innerText = `
        prediction: ${classes[result.label]}\n
        probability: ${result.confidences[result.label]}
      `;
```

**Comment by rthadur** [comment]
I was able to reproduce this bug on my mac @nsthorat @dsmilkov any comments ?

**Comment by nsthorat** [comment]
Thanks for the issue, I fixed the codelab and sent a PR to fix the demo :)

**Comment by rthadur** [comment]
@nsthorat thank you.

**Comment by isaac-fisher** [comment]
Thanks!
