### ISSUE TITLE
BodyPix default loader fails.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#2182]
With bodyPix 2.0 if you do the following

```
const net = await bodyPix.load();
```

The network request for the model errors out:
`Uncaught (in promise) Error: Request to https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/075/model-stride32.json failed with status code 404. Please verify this URL points to the model JSON of the model to load.`

**Comment by tylerzhu-github** [comment]
Thanks for the bug report and will fix this tomorrow when I am at the office.

**Comment by Abhisheknarsing** [comment]
https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/075/model-stride32.json link doesn't responding on request. can we get that json file link to load loadGraphModel to tensorflow converter locally

**Comment by tylerzhu-github** [comment]
The bug is because: 
- The output stride supported by MobileNet75,50 are 16, 8 
- The output stride supported by MobileNet100 is 32, 16, 8
I will update the README to reflect this or I can set the output stride to 16 if an unsupported stride (e.g., 32) is accidentally specified by the user.

**Comment by Abhisheknarsing** [comment]
I am trying it for RestNet50, will this works?

**Comment by tylerzhu-github** [comment]
Thanks for the feedback and early testing!
The supported output stride for ResNet50 is currently: 32 and 16.

**Comment by nsthorat** [comment]
Fixed by https://github.com/tensorflow/tfjs-models/pull/307

**Comment by davehorner** [comment]
I am getting this error when trying to use the upload_video.  I'm not sure where that url is defined yet but it is not a json file.
```
Uncaught (in promise) Error: Found more than one (2) load handlers for URL 'https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/075/model-stride16.json'
    at GraphModel.findIOHandler (graph_model.ts:128:15)
    at GraphModel.load (graph_model.ts:143:10)
    at Object.loadGraphModel (graph_model.ts:495:15)
    at body_pix_model.ts:997:35
    at step (body_pix_model.ts:17:4)
    at Object.next (body_pix_model.ts:17:4)
    at body_pix_model.ts:17:4
    at new Promise (<anonymous>)
    at __awaiter (body_pix_model.ts:17:4)
    at loadMobileNet (body_pix_model.ts:985:49)
```
I am using the latest 3a8b906 (HEAD -> master)
