### ISSUE TITLE
[BodyPix] Adds backend=cpu

### ISSUE THREAD

**Issue by tylerzhu-github** [tensorflow/tfjs#2187]
In the demo, added an option to pass, in the query string: backend=cpu to test cpu based decoding. In the demo, defaulting to use MobileNet.

**Comment by oveddan** [comment]
@tylerzhu-github can you please rename this to:

[BodyPix] add cpu instance level decoding ops.

**Comment by nsthorat** [comment]
Is the motivation for this to get it to work in Node.js?
