### ISSUE TITLE
[BodyPix] - consider removing single pose decoding from non instance segmentation methods.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2196]
With BodyPix 2.0, `segmentPerson` and `segmentPersonParts` now return segmentation masks that work for all the people in the picture.  With BodyPix 1.0, the masks worked only for a single person.

In 2.0, these methods also decode and return a single pose.  I think it would be best to remove the single pose from this result because:
1. It is confusing that this method returns a mask that applies to all people in the image, but a pose for a single person.   It actually sells how awesome this new model is short, in that returning a single pose implies that this method works just for a single person.
2. The much more common use case is to get the segmentation masks for the entire image. Feeding through the heatmaps, short-range offsets, and decoding the outputs for single pose causes a performance overhead which isn't needed for this common use case.
3. There aren't many use cases where you would only want a single pose, but get the mask for the whole image.
4.  The single pose is not used at all when decoding non-instance level masks; the only way these return types are tied together is that they can both be decoded from the outputs of a single forward pass.

For the edge case that people want to get a single pose along with the mask, we should expose static functions which would let them go the extra step and decode that from the outputs.

**Comment by rthadur** [comment]
Will be closing this issue as `bodypix` is is deprecated , please check out this demo https://github.com/tensorflow/tfjs-models/tree/master/pose-detection here , thank you
