### ISSUE TITLE
BodyPix models don't accept batch sizes greater than 1.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2197]
Similar to #1864 

Even though the [BodyPix base graph model takes 4d tensors as inputs, and returns tensors meant for batch inference](https://github.com/tensorflow/tfjs-models/blob/c93c716cf42b0ef90607e4f447f577e3ec385c7b/body-pix/src/resnet.ts#L57):

```typescript
predict(input: tf.Tensor3D): {[key: string]: tf.Tensor3D} {
    return tf.tidy(() => {
      const asFloat = processInput(toFloatIfInt(input));
      const asBatch = asFloat.expandDims(0);
      const [
          displacementBwd4d,
          displacementFwd4d,
          heatmaps4d,
          longOffsets4d,
          offsets4d,
          partHeatmaps4d,
          segmentation4d,
          partOffsets4d,
      ] = this.model.predict(asBatch) as tf.Tensor[];

      const heatmaps = heatmaps4d.squeeze() as tf.Tensor3D;
      const heatmapScores = heatmaps.sigmoid();
      const offsets = offsets4d.squeeze() as tf.Tensor3D;
      const displacementFwd = displacementFwd4d.squeeze([0]) as tf.Tensor3D;
      const displacementBwd = displacementBwd4d.squeeze([0]) as tf.Tensor3D;
      const segmentation = segmentation4d.squeeze([0]) as tf.Tensor3D;
      const partHeatmaps = partHeatmaps4d.squeeze([0]) as tf.Tensor3D;
      const longOffsets = longOffsets4d.squeeze([0]) as tf.Tensor3D;
      const partOffsets = partOffsets4d.squeeze([0]) as tf.Tensor3D;

      return {
        heatmapScores,
        offsets: offsets as tf.Tensor3D,
        displacementFwd: displacementFwd as tf.Tensor3D,
        displacementBwd: displacementBwd as tf.Tensor3D,
        segmentation: segmentation as tf.Tensor3D,
        partHeatmaps: partHeatmaps as tf.Tensor3D,
        longOffsets: longOffsets as tf.Tensor3D,
        partOffsets: partOffsets as tf.Tensor3D
      };
    });
  }
```

The base model's `predict` function throws an error when you invoke it with a 4d tensor that has a batch size greater than 1.  To replicate:

```typescript
const url = 'https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/model-stride16.json`
const graphModel = await tfconv.loadGraphModel(config.modelUrl || url);
const inputTensor = tf.zeros([5, 100, 100, 3]);

graphModel.predict(inputTensor);
```

This results in an error:

Uncaught (in promise) Error: The shape of dict['sub_2'] provided in model.execute(dict) must be [1,-1,-1,3], but was [5,100,100,3]
    at Object.f [as assert] (util.ts:107)
    at graph_executor.ts:428
    at Array.forEach (<anonymous>)
    at e.checkInputShapeAndType (graph_executor.ts:420)
    at e.execute (graph_executor.ts:141)
    at e.execute (graph_model.ts:235)
    at e.predict (graph_model.ts:189)
    at body_pix_model.ts:932
    at version.ts:4
    at Object.next (version.ts:4)

To fix this, when converting the model to tf.js, the first (batch) dimension should be a hyperparameter instead of being fixed to 1.

**Comment by nsthorat** [comment]
Is there a use case that wants to batch these? If not let's just throw a nice error if the batch size > 1

**Comment by oveddan** [comment]
The use case is mainly for Node.js, for when you have a long video and you want to perform inference on all of the frames of the video. Let's say the video is 1080ps and 24 fps.  It would be great if you could feed a bunch of frames at once to the model instead of having to do it one by one.

This brings me to a higher level question.

Is there any difference, performance wise, if you perform inference on a bunch of 3d tensors in one go vs a batch of 3d tensors rolled up into 4d?

What I mean is, lets say your code looks like:

```javascript
const graphModel = await tfconv.loadGraphModel();
const inputTensors = [
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3])
]

const results = inputTensors.map(input => graphModel.predict(input));

const resultData = await Promise.all(results.map(result => result.data()));
```

Is this slower that something like:

```javascript
const graphModel = await tfconv.loadGraphModel();
const images = [
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3]),
   tf.zeros([100, 100, 3])
]

const batch = tf.concat4d(images.map(x => x.expandDims(0)));

const resultData = await graphModel.predict(batch).data();
```

**Comment by nsthorat** [comment]
Yes, there is a large performance difference. In the browser you don't want draw calls to exceed a certain threshold otherwise the GPU gets hosed.

Can we wait until there is a concrete user asking for that in Node.js before we implement it?

**Comment by oveddan** [comment]
Is there a performance difference when running this type of code in tfjs-node-gpu?

I'm a concrete user :) I reported it because I tried to use it this way in tfjs-node (cpu and gpu).

People at ITP have asked me the best way to run posenet on videos, and I was going to do a workshop showing them how to use it using tfjs-node (or gpu if they have it available).  Being able to feed a batch of images would be great in this case.

On another personal project I did a browser based thing where I had multiple web cams running at the same time, and wasn't able to feed the frames into posenet at the same time as a batch, but had to feed them in one by one.

**Comment by nsthorat** [comment]
Haha okay makes sense, then I think it makes sense to support it if it's straightforward!

And yes, it will be a major perf gain for tfjs-node-gpu.

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
