### ISSUE TITLE
Align tf.resizeNearestNeighbor with TF

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#221]
The [following test](https://github.com/tensorflow/tfjs-core/blob/master/src/ops/resize_nearest_neighbor_test.ts#L24) fails when ran against TensorFlow Python:
```resizeNearestNeighbor simple alignCorners=false```

TF Python gives:   2,2,2,2,2,2,4,4,4.
The current implementation gives: 2,2,2,4,4,4,4,4,4.

**Comment by dsmilkov** [comment]
Here is the python code to reproduce it

```python
import tensorflow as tf

with tf.Session():
  input1 = tf.constant([2, 2, 4, 4], shape=[1, 2, 2, 1])
  output = tf.image.resize_nearest_neighbor(input1, [3, 3], align_corners=False)
  print(output.eval())
  # Gives 2, 2, 2, 2, 2, 2, 4, 4, 4
```

**Comment by dsmilkov** [comment]
The other test that fails is ```matches tensorflow w/ random numbers alignCorners=false```

**Comment by Lewuathe** [comment]
@dsmilkov Thanks for letting me know. I'll take a look.

**Comment by Al-barazanchi** [comment]
When trying to convert TensorFlow autoencoder model with resize_nearest_neighbor I am getting the error below. However it is converting with no issues when using resize_bilinear layer instead

Unsupported Ops in the model
ResizeNearestNeighbor

**Comment by Lewuathe** [comment]
@Al-barazanchi Could you tell me the version of tfjs-converter you are using?
[tfjs-converter supports `ResizeNearestNeighbor` recently](https://github.com/tensorflow/tfjs-converter/commit/91c1234dd2dca12670fcfd6fda9e84ff1521a1ce). The latest one (v0.4.1) should support it.
Can you try the latest tfjs-conveter?

**Comment by Al-barazanchi** [comment]
@Lewuathe  The version I have is 0.2.1. I uninstalled it and got the latest version. However, the latest version by pip is 0.4.0 not 0.4.1. I still have the same issue with 0.4.0 version. Any suggestions?

**Comment by Lewuathe** [comment]
@Al-barazanchi I see. The latest version uploaded in [PyPi](https://pypi.org/project/tensorflowjs/) is still 0.4.0. Unfortunately, I do not have a right to upload the package to PyPi.

@dsmilkov 0.4.1 looks already tagged in the repository. What is the plan for the next release of tfjs-converter?

**Comment by dsmilkov** [comment]
cc @pyu10055 can you release a new PyPi version of tfjs-converter (0.4.1)? Thank you!

**Comment by tafsiri** [comment]
@nsthorat @dsmilkov I'm pretty sure we can close this. The [test](https://github.com/tensorflow/tfjs-core/blob/master/src/ops/resize_nearest_neighbor_test.ts#L24) has updated to match the expected python update.

Lemme know if there is something i'm missing in terms of actions on this bug.
