### ISSUE TITLE
Feature: Conv3DTranspose Layer

### ISSUE THREAD

**Issue by lalberge** [tensorflow/tfjs#2211]
#### Describe the problem or feature request

Hi,
Is there any plan for implementing the conv3Dtranspose layer in JS, I have seen that there already is a conv3dtranspose op but no associated layer? And to make it compatible with tfjs-converter (as well as the Conv3D op) to importer U-Net-like models in the browser? 
Thank you, 
Léo

**Comment by rthadur** [comment]
The related PR has been merged #2641 , will be closing this request.
