### ISSUE TITLE
bodyPix@2.0 not available on npm

### ISSUE THREAD

**Issue by yijunxiao-samsung** [tensorflow/tfjs#2227]
May I ask if bodyPix@2.0 is released on npm? If not, when it is going to be released? Many thanks!

**Comment by rthadur** [comment]
@tylerzhu-github gentle ping, do you when this will be available on cdn and npm ?

**Comment by nsthorat** [comment]
Apologies, we are preparing to release a new version and updated the README but haven't released yet. This PR reverts the README to v1 so you can see the old API (stay tuned for a new version!)

https://github.com/tensorflow/tfjs-models/pull/327
