### ISSUE TITLE
How to run toxicity demo in your local computer

### ISSUE THREAD

**Issue by jt4000** [tensorflow/tfjs#2239]
Hello,

I'm not enable to run the code index.html and index.js in my local computer when I use <script> instead of "import * as tf from '@tensorflow/tfjs';,"   (https://github.com/tensorflow/tfjs/issues/149)
from https://github.com/tensorflow/tfjs-models/tree/master/toxicity/demo  ("https://github.com/tensorflow/tfjs/issues/149")

When I run with "<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script> " i retrieve another error message that is 

"Uncaught (in promise) ReferenceError: toxicity is not defined at predict (index.js:71) at index.js:95"

How do you enabel to run the file index.html and index.js in your local computer in relation to   "<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script> "?

Thank you!

![d1](https://user-images.githubusercontent.com/14993569/67156244-4132e880-f31c-11e9-891f-456c5e5a3c3f.png)
![d2](https://user-images.githubusercontent.com/14993569/67156245-4132e880-f31c-11e9-9700-ab01778d3c3a.png)

**Comment by annxingyuan** [comment]
Hi @jt4000 - it looks like the toxicity model hasn't loaded yet when you call predict. Are you loading index.js after loading both tfjs and the toxicity library?

Something like:

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/toxicity@latest"></script>
<!-- index.js must be after tfjs and toxicity -->
<script src="index.js"></script>
```

**Comment by rthadur** [comment]
@jt4000 were you able to verify this ?
