### ISSUE TITLE
Bodypix@2.0 not available on cdn

### ISSUE THREAD

**Issue by JaeDukSeo** [tensorflow/tfjs#2240]
the javascript file is not found

**Comment by rthadur** [comment]
this is a duplicate of #2227 , closing this , will wait for Tyler reply.

**Comment by nsthorat** [comment]
Apologies, we are preparing to release a new version and updated the README but haven't released yet. This PR reverts the README to v1 so you can see the old API (stay tuned for a new version!)

https://github.com/tensorflow/tfjs-models/pull/327

**Comment by kesar** [comment]
waiting for v2 on cdn too 👍

**Comment by dsmilkov** [comment]
Closing since we released 2.0 on NPM, as well as uploaded a new demo.
