### ISSUE TITLE
Body-pix@2.0 not found on CDN

### ISSUE THREAD

**Issue by abhieshekumar** [tensorflow/tfjs#2241]
TensorFlow.js 1.2

Browser version - Google Chrome Version 77.0.3865.90

I am working on a project and BodyPix@2.0 when requested from CDN returns a 404 status.

#### Code to reproduce the bug
The documentation mentioned for [bodypix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) indicates using a [CDN link](https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix@2.0) to load the model however the link returns a 404 error while requesting for the js file.

**Comment by rthadur** [comment]
this will be fixed soon thanks for reporting.
