### ISSUE TITLE
tf.ones size limit

### ISSUE THREAD

**Issue by antonylawler** [tensorflow/tfjs#225]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version 
tfjs@0.9.0
#### Browser version
Chrome 66.0.3359.117 
#### Describe the problem or feature request
tf.transpose or tf.ones not working.
#### Code to reproduce the bug / link to feature request
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.9.0"> </script>
<script>
const a = tf.ones([1,10000]);
a.transpose().print();
</script>
</head>
<body>
</body>
</html>
# Output in console:
Tensor
    [[1],
     [1],
     [1],
     ...,
     [0],
     [0],
     [0]]
# Fault might be tied to GPU
I get correct output on some workstations. The above fault occurs on a workstation whose dxdiag output is as follows:

------------------
System Information
------------------
      Time of this report: 4/24/2018, 19:36:56
             Machine name: BPL22
               Machine Id: {C1452F44-2C01-408A-B020-AB8A025CBCF5}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
                 Language: English (Regional Setting: English)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: BIOS Date: 04/18/12 13:45:16 Ver: 06.07
                Processor: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 CPUs), ~3.4GHz
                   Memory: 4096MB RAM
      Available OS Memory: 3790MB RAM
                Page File: 4236MB used, 3393MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.15063.0000 64bit Unicode

---------------
Display Devices
---------------
          Card name: Intel(R) HD Graphics 4000
       Manufacturer: Intel Corporation
          Chip type: Intel(R) HD Graphics Family
           DAC type: Internal
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_8086&DEV_0162&SUBSYS_84CA1043&REV_09
      Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
Device Problem Code: No Problem
Driver Problem Code: Unknown
     Display Memory: 1792 MB
   Dedicated Memory: 224 MB
      Shared Memory: 1568 MB
       Current Mode: 1920 x 1080 (32 bit) (32Hz)
        Driver Name: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll
Driver File Version: 10.18.0010.4358 (English)
     Driver Version: 10.18.10.4358
        DDI Version: 11.2
     Feature Levels: 11_0,10_1,10_0,9_3,9_2,9_1
       Driver Model: WDDM 1.3
Graphics Preemption: DMA
 Compute Preemption: Thread group
           Miracast: Not Supported by WiFi driver
Hybrid Graphics GPU: Not Supported
     Power P-states: Not Supported
  Driver Attributes: Final Retail
   Driver Date/Size: 21/12/2015 12:00:00 PM, 11157656 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: Unknown
  Device Identifier: {D7B78E66-4222-11CF-F562-C0A4B4C2C735}
          Vendor ID: 0x8086
          Device ID: 0x0162
          SubSys ID: 0x84CA1043
        Revision ID: 0x0009
 Driver Strong Name: oem0.inf:5f63e53413eb6103:iIVBD_w10:10.18.10.4358:pci\ven_8086&dev_0162
     Rank Of Driver: 00D12001
        Video Accel: Unknown
        DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeVC1_D2010  DXVA2_ModeWMV9_IDCT  DXVA2_ModeVC1_IDCT  DXVA2_ModeH264_VLD_NoFGT  
      Deinterlace Caps: n/a
       D3D9 Overlay: Supported
            DXVA-HD: Supported
       DDraw Status: Not Available
         D3D Status: Enabled
         AGP Status: Not Available
           MPO Caps: Not Supported
        MPO Stretch: Not Supported
    MPO Media Hints: Not Supported
        MPO Formats: Not Supported

**Comment by antonylawler** [comment]
tf.ones([10000])

results in tensor with 8192 records set as 1, and the remainder as 0.

**Comment by antonylawler** [comment]
tf.ones([10000])

only fills 8192 1's, with the remainder as 0.

**Comment by ManrajGrover** [comment]
@antonylawler Hi, I cannot reproduce this error with the latest version. Could you please fill the template in the 1st comment which would help debug this?

**Comment by dsmilkov** [comment]
We got a windows machine and I couldn't reproduce it either. Feel free to reopen if the problem shows up again!
