### ISSUE TITLE
Unable to save model for Tensorflowjs using tfjs.converterjs

### ISSUE THREAD

**Issue by Gautamshahi** [tensorflow/tfjs#2253]
I am using the Tensorflow hub for importing the Imagenet, but after retaining my data, I wanted to save the model for the TensorFlow Js, I am using

tfjs.converters.save_keras_model(model, path1)

I am not able to save the model for my TensorFlow's, I am getting the error

RuntimeError: Unable to create a link (name already exists)

I need to save only in the format supported by TensorFlowJs

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Gautamshahi** [comment]
Hi,

Why do you think that people have not done homework before posting here?

My code works well, but it doesn't work for TensorFlow hub. 

Don't close the issue with an immature reply.

**Comment by rthadur** [comment]
Sorry that was eager closing, please use the template and open a new issue, there are lot of details missing in order for us to categorize this as a bug.

**Comment by Gautamshahi** [comment]
that's something else; I accept that I have not followed the template, don't be in a race of the active collaborator in Github.
