### ISSUE TITLE
Error with converted model, "Input tensor count mismatch"

### ISSUE THREAD

**Issue by ychen0901** [tensorflow/tfjs#2254]
Version:
tensorflowjs         1.2.10.1

I used tfjs-converter to convert the pre-trained saved model, and the conversion was completed successfully. But when I use the model in js, got this error, 
"Input tensor count mismatch,the graph model has 46 placeholders, while there are 1 input tensors"

Link to the pre-trained model,
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz

The command I used to convert,
$tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=serving_default --saved_model_tags=serve saved_model web_model

The js code,
this.model = await tf.loadGraphModel(WEB_MODEL_PATH);
this.model.executeAsync(tf.zeros([1, 300, 300, 3]))

The error happened with the executeAsync method.
I also attached the converted model.json.

**Comment by wingman-jr-addon** [comment]
Sounds quite a bit like [this StackOverflow post with no answer yet](https://stackoverflow.com/questions/55573051/getting-error-of-input-count-mismatch-while-getting-predictions-from-pretrained).

**Comment by mike-hor** [comment]
me too!!!!
i used so many ways,include tfjs-convert 0.8.6(but it can't install)
no way to resolved it.
just give me a error
![image](https://user-images.githubusercontent.com/17822235/67374992-912bdc80-f5b4-11e9-9686-d24d745275ac.png)

**My Version**
tensorlfow 1.14.0
tfjs-convert 1.2.6

**Comment by alien35** [comment]
Same. hoping tensorflowjs==1.2.11 will fix it.

**Comment by wingman-jr-addon** [comment]
Well, I poked at this a bit. There is a related issue #1793 that gets most of the way to the final answer. Basically, we just need to specify the input and output node names and all is well:
```
	let outputs = await model.executeAsync(
		{ 'image_tensor' : tf.zeros([1, 300, 300, 3]) },
		[ 'detection_boxes','detection_scores','detection_classes','num_detections']);
	tf.print(outputs);
```
This produced the following for me with no errors:
```
Tensor
    [[[0, 0, 0, 0],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
      ...,
      [0, 0, 0, 0],
      [0, 0, 0, 0],
      [0, 0, 0, 0]]],Tensor
     [[0, 0, 0, ..., 0, 0, 0],],Tensor
     [[1, 1, 1, ..., 1, 1, 1],],Tensor
    [0]
```
This was with tfjs 1.2.10 and tensorflowjs_converter from tensorflowjs 1.2.10.1.

**Comment by ychen0901** [comment]
@wingman-jr-addon Thank you! This workaround works for me!
Still hope this can be fixed by tfjs team.

**Comment by alien35** [comment]
Thanks, that worked for me too, though now I'm getting this error. Anyone else? https://github.com/tensorflow/tfjs/issues/2265

**Comment by kangyizhang** [comment]
Did you see any error when using `model.predict()`?

**Comment by wingman-jr-addon** [comment]
I do not get that error @alien35 and the op being referenced does not seem to show up in the model.json when converted using the OP's conversion. I'm going to head over to your referenced issue and respond there.

**Comment by wingman-jr-addon** [comment]
@ychen0901 Do you feel this can be closed? I know you had indicated that you'd like to see it fixed, but I'm not 100% sure that inferring the input and output nodes is a bug - was this a regression in behavior from a previous version?

**Comment by ychen0901** [comment]
@wingman-jr-addon Hello, the input and output nodes are not required in earlier versions of the converter. As far as I know, the original code "this.model.executeAsync(tf.zeros([1, 300, 300, 3]))" works well with model converted by tensorflowjs 0.8.0.

**Comment by wingman-jr-addon** [comment]
Thanks @ychen0901 - @pyu10055 I see you've been taking action on #2287. Anything else we need here?

**Comment by ychen0901** [comment]
Great! Thank you @wingman-jr-addon  and @pyu10055 !
