### ISSUE TITLE
"Cannot compute the outputs" for dynamic ops (TensorArrayStack)

### ISSUE THREAD

**Issue by cifkao** [tensorflow/tfjs#2263]
### TensorFlow.js version

1.2.11

#### Browser version

Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

#### Describe the problem or feature request

I have a graph model (built using `tf.contrib.seq2seq`) which uses control flow ops for dynamic RNN decoding. I exported it with TF 1.15 (using `simple_save`) and converted with TF.js 1.2.11 (command: `tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --saved_model_tags=serve`).

When trying to run the model with `executeAsync`, I get the following error:

```
Uncaught (in promise) Error: Cannot compute the outputs [decoder/decode_sample/decoder_1/transpose_1] from the provided inputs [inputs,softmax_temperature]. Consider providing the following inputs: []. Alternatively, to avoid the dynamic ops, use model.execute() and specify the inputs [decoder/decode_sample/decoder_1/TensorArrayStack_1/TensorArrayGatherV3]
    at t.<anonymous> (graph_executor.ts:318)
    at callbacks.ts:253
    at Object.next (callbacks.ts:253)
    at o (callbacks.ts:253)
```

Does this mean TF.js currently cannot handle these ops? Is it the `TensorArrayStack`/`TensorArrayGatherV3` operation or something else?

**Comment by rthadur** [comment]
Hi there is a known bug with `executeAsync` specified here in #1793 , for it to work you may need to specify the output nodes please refer [here](https://github.com/tensorflow/tfjs/issues/2254#issuecomment-545755315).

**Comment by cifkao** [comment]
Hi, thanks for the response. I'd seen that issue before and I'm already specifying the output nodes like this:

```
model.executeAsync({'inputs': tf.zeros([1, 128, 16]), 'softmax_temperature': tf.scalar(0.6)}, ["decoder/decode_sample/decoder_1/transpose_1"])
```

I can, for example, get the encoder outputs by passing "encoder_rnn/rnn/transpose_1", but there seems to be some issue with the decoder... I'm guessing the graph may be broken by the conversion.

Is there some way to get more information from the executor to see what exactly is preventing it from running? The error says `Consider providing the following inputs: []`, which doesn't help much...

**Comment by pyu10055** [comment]
@cifkao Thank you for reporting the issue, this might related to our model analyzer having issue with TensorArray ops. Do you have the converted op that can be shared for us to reproduce?

**Comment by cifkao** [comment]
@pyu10055 Below is the converted `TensorArrayStack` op.

```
[
 {
  "name": "decoder/decode_sample/decoder_1/TensorArrayStack_1/TensorArraySizeV3",
  "op": "TensorArraySizeV3",
  "input": [
   "decoder/decode_sample/decoder_1/TensorArray_1",
   "decoder/decode_sample/decoder_1/while/Exit_3"
  ]
 },
 {
  "name": "decoder/decode_sample/decoder_1/TensorArrayStack_1/range",
  "op": "Range",
  "input": [
   "encoder_rnn/rnn/GRUCellZeroState/ExpandDims/dim",
   "decoder/decode_sample/decoder_1/TensorArrayStack_1/TensorArraySizeV3",
   "encoder_rnn/rnn/TensorArrayUnstack/range/delta"
  ],
  "attr": {
   "Tidx": {
    "type": "DT_INT32"
   }
  }
 },
 {
  "name": "decoder/decode_sample/decoder_1/TensorArrayStack_1/TensorArrayGatherV3",
  "op": "TensorArrayGatherV3",
  "input": [
   "decoder/decode_sample/decoder_1/TensorArray_1",
   "decoder/decode_sample/decoder_1/TensorArrayStack_1/range",
   "decoder/decode_sample/decoder_1/while/Exit_3"
  ],
  "attr": {
   "dtype": {
    "type": "DT_INT32"
   },
   "element_shape": {
    "shape": {
     "dim": [
      {
       "size": "-1"
      }
     ]
    }
   }
  }
 }
]
```

**Comment by cifkao** [comment]
I was able to get a complete example. I'm attaching the [SavedModel protobuffer](https://github.com/tensorflow/tfjs/files/3783528/saved_model.pb.gz) and the [converted model](https://github.com/tensorflow/tfjs/files/3783529/model.json.gz).

**Comment by pyu10055** [comment]
@cifkao can you provide the whole directory of the saved_model, also the weights files for the tfjs converter model? Thanks.

**Comment by cifkao** [comment]
@pyu10055 Sure, here's everything:
* [export.tar.gz](https://github.com/tensorflow/tfjs/files/3785892/export.tar.gz)
* [export_web.tar.gz](https://github.com/tensorflow/tfjs/files/3785894/export_web.tar.gz)

**Comment by pyu10055** [comment]
@cifkao  I was able to run your model with the fix above.
I got following result 
[122, 122, 122, 122, 122, 122, 122, 121, 122, 122, 122, 122, 122, 121, 122, 122, 122, 122, 121, 122, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122, 122, 121, 122, 122]

Please let me know if it matches your python output, thanks.

**Comment by cifkao** [comment]
@pyu10055 Perfect!

I got a different output, but I assume it's because the random generators are different. Can you try the deterministic output `"decoder/decode_sample/decoder/transpose_1"`? That gave me:
[[ 37  37 162  73 162  55  55  55  55  55  55  55  55  55  55  55  55  55
   55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55
   55  55  55  55  55  55  55  55  55  55  55  55  55  55]]

**Comment by cifkao** [comment]
(Updated the comment above, it should be greedy instead of sample.)

**Comment by pyu10055** [comment]
yes, that is the exact result I got
[37, 37, 162, 73, 162, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55]
length: 1
__proto__: Array(0)

**Comment by pyu10055** [comment]
You have some Assert ops in your model, it would be ideal to avoid them, since it will slow down the model. Our converter automatically convert them to no-op by default, which is causing the issue you are having.

**Comment by cifkao** [comment]
@pyu10055 Thanks! Is there an easy way to remove the asserts from the graph? (They're added by `tf.contrib.seq2seq`.)

**Comment by pyu10055** [comment]
@cifkao in that case you can rely on our converter to do that, and the fix I had will fix your issue.
