### ISSUE TITLE
Ubuntu failed to run tfjs demo downloaded from tfjs

### ISSUE THREAD

**Issue by kingsleyljc** [tensorflow/tfjs#2266]
I've downloaded a demo called 'iris' and followed the README.md.
But it failed to run due to some ERROR.
ubuntu --version 18.0.4
yarn --version 1.19.1
nodejs --version 13.0.1
![微信截图_20191024225833](https://user-images.githubusercontent.com/48885821/67498336-d71a9a80-f6b1-11e9-9e92-f31238696317.png)
![微信截图_20191024225913](https://user-images.githubusercontent.com/48885821/67498399-f4e7ff80-f6b1-11e9-8439-d34f138ca402.png)
I have struggled for it for a long time!!!! Why the demo can't work ???!?!?!?! Thanks a lot for helping!!!

**Comment by kingsleyljc** [comment]
I don't what the problem is? Is it due to yarn?

**Comment by kangyizhang** [comment]
Looks like your linux is missing some standard header files and tools. Try to run `sudo apt install build-essential` and then try again.

**Comment by kingsleyljc** [comment]
@kangyizhang Thank you very much!!!!! I can run it now !!!
