### ISSUE TITLE
Can't install tfjs

### ISSUE THREAD

**Issue by logan-lieou** [tensorflow/tfjs#2277]
#### Cannot install tfjs

I'm trying to use node to fun tfjs and it says that I don't have the package after I attempt to install it with npm, where I get an error and I don't know how to get this to work.

#### Code to reproduce

```python

require('@tensorflow/tfjs-node');

```
![image](https://user-images.githubusercontent.com/20232318/67627659-fa665680-f825-11e9-9220-4d8b3cb93440.png)

![image](https://user-images.githubusercontent.com/20232318/67627663-0c47f980-f826-11e9-8339-b0beec8bb271.png)

**Comment by kangyizhang** [comment]
hi @logan-lieou 
Can you paste the full error message? Looks like you installed the package in `c:\Users\eeayo` and tried to load it in `e:\Git Projects\Learning-ML\General\Day_6\program_1.js`

**Comment by logan-lieou** [comment]
![image](https://user-images.githubusercontent.com/20232318/67638487-abb2ce00-f8b2-11e9-938c-54ddb88e9126.png)

**Comment by kangyizhang** [comment]
@logan-lieou did you see the @tensorflow/tfjs-node folder in your node_modules?

**Comment by logan-lieou** [comment]
![image](https://user-images.githubusercontent.com/20232318/68001636-ead67b80-fc32-11e9-9921-2a0fd339a698.png)
No is there supposed to be something in here...

**Comment by kangyizhang** [comment]
Change check the `node_modules` folder in `e:\Git Projects\Learning-ML\General\Day_6`?
Looks like you installed the package in another place (`c:\Users\eeayo`).

**Comment by kangyizhang** [comment]
The problem can not be reproduced and based on the log seems like you installed the library in a different directory.
