### ISSUE TITLE
speech commands no longer working

### ISSUE THREAD

**Issue by ashinzekene** [tensorflow/tfjs#2298]
```js
import * as speechCommands from '@tensorflow-models/speech-commands';

(async() => {
  const recognizer = speechCommands.create("BROWSER_FFT", "directional4w");
  await recognizer.ensureModelLoaded();  
})()
```

Returns error :  
`https://storage.googleapis.com/tfjs-models/tfjs/speech-commands/v0.4/browser_fft/directional4w/metadata.json` NOT FOUND

![image](https://user-images.githubusercontent.com/20991583/67843938-338c1880-fafd-11e9-8ad8-fabde71f517d.png)

`https://storage.googleapis.com/tfjs-models/tfjs/speech-commands/v0.3/browser_fft/directional4w/metadata.json` works however

**Comment by caisq** [comment]
This should be fixed now. Sorry for the breakage.
