### ISSUE TITLE
Support Stateful RNN Layers

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#23]
tf.layers.rnn currently does not support stateful RNN layer subtypes.

**Comment by wangwalton** [comment]
Any update on this item? How about importing a stateful LSTM that's been converted from keras?

**Comment by brannondorsey** [comment]
I too am hoping this is supported soon. Last time I attempted to import an LSTM model that used stateful units from Keras I received not implemented errors. Is there a roadmap to include this feature in tfjs?
