### ISSUE TITLE
Adding AddSign optimizer

### ISSUE THREAD

**Issue by janhuenermann** [tensorflow/tfjs#230]
Hey guys,

I really like what you're doing with Tensorflow-JS and would like to contribute. Would you guys appreciate if I implement the [add-sign optimizer](https://arxiv.org/pdf/1709.07417.pdf) or are you trying to keep the codebase/number of optimizers small? I already got the base implementation, basically only the tests are missing. Let me know what you think.  

Best,
Jan

**Comment by dsmilkov** [comment]
We are trying to be use-case oriented in the early days when the team is smaller so we have less code/bugs to maintain.

Do you have any particular use case where AddSign is needed? Otherwise, we can close this issue and revisit later.

Thanks!

**Comment by ManrajGrover** [comment]
Tensorflow API does not implement AddSign Optimizer, which was one of the reasons we had to close https://github.com/tensorflow/tfjs-core/pull/260 which implemented the same.

**Comment by dsmilkov** [comment]
Good point. I forgot about that.
