### ISSUE TITLE
loadLayersModel method doesn`t work.

### ISSUE THREAD

**Issue by Glunky** [tensorflow/tfjs#2300]
Hi!
 Im trying to load my model which located in my computer like demonstrating [here](https://www.tensorflow.org/js/guide/save_load#native_file_system_nodejs_only_2). My string is `model = await tf.loadLayersModel('file:///home/ilya/Downloads/node-webrtc-examples-master/model.json');` But i get an error: `(node:5208) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported`. When i use `file//home...` i get `TypeError: Only HTTP(S) protocols are supported`. Bin file also there. What am i doing wrong and how can i fix it??

**Comment by Glunky** [comment]
> i guess you are missing async function which is when present can allow you to use await.
> 
> This sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

No, Im not, I used await in async function. Just I pasted only string with my path. Ok, will try find out in StackOverflow audience.

**Comment by Aligertor** [comment]
found the solution on stackoverflow

https://stackoverflow.com/questions/56049893/only-absolute-urls-are-supported-when-loading-keras-model-in-tensorflow-js-wit

in short:
make sure "@tensorflow/tfjs-node" is imported/required when loading a model in node

gl
