### ISSUE TITLE
Distribution Normal from Tensors

### ISSUE THREAD

**Issue by thibo73800** [tensorflow/tfjs#231]
#### TensorFlow.js version

Any

#### Browser version

Any

#### Feature request

The only function who refer to a normal distribution is tf.randomNormal, the two parameters: mean and 
stdDev must be number and not tensor thereby the resulting tensor is not differentiable... Moreover, we can create only a set of values from only one pair of mean and variance instead of using multiple pairs.

It would be great to accept tensor too as parameters...

#### Code from Python tensorflow

Using tensorflow in python it is possible to create a normal distribution from two tensors (mean and stdDev)
Example (with eager execution):

```
nr = tf.distributions.Normal([0.5, 2.0], [0.5, 0.5])
nr._sample_n(1)
#<tf.Tensor: id=300, shape=(1, 2), dtype=float32, numpy=array([[ 0.52700466,  2.44701052]], dtype=float32)>

```

**Comment by thibo73800** [comment]
I would be ok to implement it

**Comment by dsmilkov** [comment]
That would be great. Thank you!

**Comment by thibo73800** [comment]
Hi @dsmilkov  I have a working code! Which branch should I use to make my pull request?

**Comment by ManrajGrover** [comment]
@thibo73800 You should make a PR to master branch.
