### ISSUE TITLE
implement TF cumsum op

### ISSUE THREAD

**Issue by jameswex** [tensorflow/tfjs#232]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10

#### Describe the problem or feature request

implement TF cumsum operation https://www.tensorflow.org/api_docs/python/tf/cumsum

**Comment by dsmilkov** [comment]
Interested in implementing? Happy to review and give guidance. Should be extremely similar to how sum is implemented: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/backend_webgl.ts#L447

**Comment by jameswex** [comment]
sure

**Comment by dsmilkov** [comment]
Fixed in https://github.com/tensorflow/tfjs-core/pull/1032
