### ISSUE TITLE
Unknown op '_FusedConv2D' with tfjs-automl using object-detection demo

### ISSUE THREAD

**Issue by gitunit** [tensorflow/tfjs#2327]
I've exported a model from AutoML and now trying to make it run with Tensorflow.js.
Im using the object_detection demo code and i replaced the link to my local model.
It has been loaded successfully but when it comes to the prediction part, it fails with the error message: 

> Uncaught (in promise) TypeError: Unknown op '_FusedConv2D'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
>     at operation_executor.ts:95
>     at executeOp$16 (operation_executor.ts:52)
>     at c (graph_executor.ts:351)
>     at e.processStack (graph_executor.ts:337)
>     at e.<anonymous> (graph_executor.ts:299)
>     at tensor.ts:397
>     at Object.next (tensor.ts:397)
>     at o (tensor.ts:397)

i saw a [similar issue](https://github.com/tensorflow/tfjs/issues/2054) but this was a different model and i believe running the latest with the demo code from this repo.

edit: it works with [this snippet](https://github.com/tensorflow/tfjs/blob/master/tfjs-automl/code_snippets/object_detection.html) though

**Comment by pyu10055** [comment]
@gitunit The _FusedConv2d op is supported after 1.13, please load the latest tfjs union package. thanks.

**Comment by gitunit** [comment]
> @gitunit The _FusedConv2d op is supported after 1.13, please load the latest tfjs union package. thanks.

isn't the object_detection demo already loading the latest? if not, how would i do that?
furthermore with [this](https://github.com/tensorflow/tfjs/blob/master/tfjs-automl/code_snippets/object_detection.html) it works but it seems very slow. could it be that it uses CPU as backend? how would i set WEBGL as backend? 
i've tried by using tf.setbackend('webgl') but this has no effect. did i miss anything? has this something to do with automl?

**Comment by Wlisfes** [comment]
您好！我已经更新了依赖包还是出现这个错误

`
"@tensorflow/tfjs-core": "^1.3.1",
"@tensorflow/tfjs-automl": "^1.3.1"
`
operation_executor.ts:95 Uncaught (in promise) TypeError: Unknown op '_FusedConv2D'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
    at operation_executor.ts:95
    at executeOp$16 (operation_executor.ts:52)
    at c (graph_executor.ts:351)
    at e.processStack (graph_executor.ts:337)
    at e.<anonymous> (graph_executor.ts:299)
    at add.ts:17
    at Object.next (add.ts:17)
    at o (add.ts:17)
``

**Comment by alexhmyang** [comment]
> 您好！我已经更新了依赖包还是出现这个错误
> 
> `"@tensorflow/tfjs-core": "^1.3.1", "@tensorflow/tfjs-automl": "^1.3.1"` operation_executor.ts:95 Uncaught (in promise) TypeError: Unknown op '_FusedConv2D'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp() at operation_executor.ts:95 at executeOp$16 (operation_executor.ts:52) at c (graph_executor.ts:351) at e.processStack (graph_executor.ts:337) at e. (graph_executor.ts:299) at add.ts:17 at Object.next (add.ts:17) at o (add.ts:17) ``

same problem, anyone solve it? 
npm info @tensorflow/tfjs-converter

@tensorflow/tfjs-converter@4.2.0 | Apache-2.0 | deps: none | versions: 123
