### ISSUE TITLE
Add dilations to tf.layers.separableConv2d

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#233]
The config object of [tf.layers.separableConv2d](https://js.tensorflow.org/api/0.10.0/#layers.separableConv2d) doesn't take `dilation`, but Keras [one does](https://keras.io/layers/convolutional/#separableconv2d).

[tf.separableConv2D](https://js.tensorflow.org/api/0.10.0/#separableConv2d) (core's version) supports dilations so it is just a matter of passing it through.

There is a GAN model that would benefit from this. [See discussion](https://groups.google.com/a/tensorflow.org/d/msgid/tfjs/c858dcfa-9344-4129-b133-e6a8f1ee3c2a%40tensorflow.org?utm_medium=email&utm_source=footer).

**Comment by nsthorat** [comment]
cc @ericdnielsen @bileschi

**Comment by bileschi** [comment]
I think this is supported now:  See this test:
https://github.com/tensorflow/tfjs-layers/blob/master/src/layers/convolutional_test.ts#L662
