### ISSUE TITLE
mobilenet2.0.2 set modelURL:gstaticcnapps.cn，has cors error

### ISSUE THREAD

**Issue by allanguys** [tensorflow/tfjs#2338]
`
mobilenet.load({
version:1.0,
modelUrl:'https://www.gstaticcnapps.cn/tfhub-tfjs-modules/google/imagenet/mobilenet_v1_100_224/classification/1/model.json'
});
`
 **error detail:**
Access to fetch at 'https://www.gstaticcnapps.cn/tfhub-tfjs-modules/google/imagenet/mobilenet_v1_100_224/classification/1/model.json' from origin 'http://127.0.0.1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rthadur** [comment]
@allanguys thanks for reporting , may i know where you got above link ?

**Comment by allanguys** [comment]
> @allanguys thanks for reporting , may i know where you got above link ?
thanks for replay
i got link from https://github.com/tensorflow/tfjs-wechat .just for the special case of China

**Comment by pyu10055** [comment]
@wangtz Hi Tiezhen, can you take a look at the CORS error for TFHub model files, thanks!

**Comment by rthadur** [comment]
@wangtz can you please assist with above request

**Comment by Leslie-Fang** [comment]
Hi, any update of this issue? I have got the same error...

**Comment by Leslie-Fang** [comment]
setting `requestInit:{mode:'no-cors'}`
Could avoid the CORS error, but the fetched model is empty...

**Comment by rthadur** [comment]
cc @hj929

**Comment by wangtz** [comment]
I think this has been fixed. I can open the file with proper content. 
Maybe give it a try again?

**Comment by rthadur** [comment]
@wangtz I will give a try and update the thread.

**Comment by rthadur** [comment]
This is working.Thank you @wangtz
