### ISSUE TITLE
Posenet demo page has left and right confused (only in single pose mode)

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#2350]
https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html

Displays the green dots further to the other side when I move. Works OK in "multi-pose" mode.

![posenet-bug](https://user-images.githubusercontent.com/2138696/68410611-e8b77400-0180-11ea-89be-fb3ff59fca60.png)

While someone is looking into this perhaps the explanatory text could be improved as well. It refers to a "higher image scale" and yet none of the parameters has a matching name. Is it the "multiplier"?

Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by rthadur** [comment]
@ToonTalk would you like to contribute ? If yes please submit a PR

**Comment by tylerzhu-github** [comment]
Thanks for reporting the issue @ToonTalk!
Let me fix this.

**Comment by tylerzhu-github** [comment]
Hi @ToonTalk,

Thanks again for the report. I think we just need to host the latest PoseNet demo online.

Could you try build and run the demo locally from the latest source to see if it fixes the issue.
Here are the instructions: https://github.com/tensorflow/tfjs-models/tree/master/posenet/demos

Best,
Tyler

**Comment by tylerzhu-github** [comment]
A new demo (with the fix) has been released here:
https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html

Let us know if it fixes the reported issue.

**Comment by ToonTalk** [comment]
Working fine now. Thanks.
