### ISSUE TITLE
Drawing Graph

### ISSUE THREAD

**Issue by PveOnly** [tensorflow/tfjs#237]
Hi i would like to know how do you draw a function on a graph on a html page ?Because i tried to do it for the first tutorial :https://js.tensorflow.org/tutorials/mnist.html with plotting the function a*x*x*x+b*x*x+c*x+d (a ,b ,c ,d are the random coeff) but even if there is no error it draw nothing (i tried with real number and it drawed something so i don't think it's my function .
![image](https://user-images.githubusercontent.com/37158659/39312613-49c8b45e-4970-11e8-8068-f693713ce78f.png)

![image](https://user-images.githubusercontent.com/37158659/39312624-5496a6ca-4970-11e8-9570-b21f9b43108d.png)

**Comment by caisq** [comment]
I will close this issue as it is not related to the core functionalities of tensorflow.js. You might want to ask this question on stackoverflow and/or look up tutorials on how to draw shapes in HTML canvases.
