### ISSUE TITLE
shapeInfo.texShape is 'undefined' in shader_compiler::getPackedSampler2D

### ISSUE THREAD

**Issue by ychen0901** [tensorflow/tfjs#2375]
#### TensorFlow.js version
1.3.1
#### Browser version
Chrome Version 78.0.3904.70
#### Describe the problem or feature request
I have an object detection graph model that was trained in Python and converted to web model using tfjs-converter, the model was working well in Python. But with tfjs, I got error "Cannot read property '0' of undefined" during prediction.
A bit investigation shows that exception happens inside of shader_compiler::getPackedSampler2D, inputInfo.shapeInfo.texShape has value "undefined", but the code tries to access it as an array and that caused the exception,
#### Code to reproduce the bug / link to feature request
const model = await tf.loadGraphModel(MODEL_URL);
await model.executeAsync(tf.zeros([1, 300, 300, 3])); // Exception happens in this call.

I can provide link to the model if needed.

**Comment by rthadur** [comment]
@ychen0901 please prove the model if you can and also please specify how the model was trained and in which version of tensorflow ?

**Comment by pyu10055** [comment]
@ychen0901 Please also specify what version of tfjs converter you have used, the latest version (1.3.1.1) has some fixes related to detection models conversion, please try it out if you have not.

**Comment by ychen0901** [comment]
@pyu10055 @rthadur Thank you for your responses!

I just tried with the latest version tensorflowjs 1.3.2, for both of tensorflowjs_converter and my project dependency, and the same problem still occurs.

The model was trained with tensorflow 1.12, based on ssd_mobilenet_v1_coco from [Tensorflow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

I followed these steps to train and export the saved model,
Train: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md
Export:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/exporting_models.md

@rthadur What would be the best way to share the model files with you?

**Comment by rthadur** [comment]
@ychen0901 thank you , you can use github gist.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by rafinskipg** [comment]
It happens to me too, trying to load a model saved with nodejs. It doesn't work
