### ISSUE TITLE
tfjs-node can not install

### ISSUE THREAD

**Issue by WenheLI** [tensorflow/tfjs#2390]
While I was trying to install `tfjs-node` on GCP, I got an error:

```
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/CPU-linux-1.3.2.tar.gz 
```

This seems to be a problem with the server that hosts the TensorFlow-binary. I have also tried it with the GPU version and my laptop. All emit similar errors. 

**Update:** I can install the `tfjs-node` with an older version like `1.3.1` for mac and `1.3.0` for Linux.

**Comment by kangyizhang** [comment]
hi @WenheLI this is a warning when pre-build node addon is not available and it should build the node addon from source (you can tell from the command `node-pre-gyp install --fallback-to-build`). Did you see any log marked with error? Does the package have any issue when import and use it?

**Comment by WenheLI** [comment]
@kangyizhang - Thanks for your response! I think the `napi-v4` module/binary just can not be accessed via the link: `https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/CPU-linux-1.3.2.tar.gz `. And it triggers the warning. 

Also, if I require the package in node, I got the following errors:
```js
> require('@tensorflow/tfjs-node')
Thrown:
Error: Cannot find module '/Users/eric/Desktop/dev/training-node/node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node'
Require stack:
- /Users/eric/Desktop/dev/training-node/node_modules/@tensorflow/tfjs-node/dist/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/eric/Desktop/dev/training-node/node_modules/@tensorflow/tfjs-node/dist/index.js',
    '<repl>'
  ]
}

```

It suggests the napi-v4 is not there.

**Comment by kangyizhang** [comment]
@WenheLI I have just uploaded prebuild addon module for napi-v4, please try again.

**Comment by WenheLI** [comment]
Thanks! It has been fixed!
