### ISSUE TITLE
[ tensorflowjs_converter ] Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined

### ISSUE THREAD

**Issue by seijichishiki** [tensorflow/tfjs#2395]
I performed transfer learning(ssd_mobilenet_v1_coco_2018_01_28) on Google Colab.
Tensorflow=1.15.0.

fine-tuned-model folder
```
-rw------- 1 root root       77 Nov 14 14:32 checkpoint
-rw------- 1 root root 29358826 Nov 14 14:32 frozen_inference_graph.pb
-rw------- 1 root root 27380740 Nov 14 14:32 model.ckpt.data-00000-of-00001
-rw------- 1 root root     8937 Nov 14 14:32 model.ckpt.index
-rw------- 1 root root  3010369 Nov 14 14:32 model.ckpt.meta
-rw------- 1 root root     4127 Nov 14 14:32 pipeline.config
drwx------ 3 root root     4096 Nov 14 14:32 saved_model
drwx------ 2 root root     4096 Nov 13 07:46 web_model
```

saved_model
```
-rw------- 1 root root 7141483 Nov 15 11:36 saved_model.pb
drwx------ 2 root root    4096 Nov 15 11:36 variables
```
variables
```
-rw------- 1 root root 27380740 Nov 15 11:36 variables.data-00000-of-00001
-rw------- 1 root root     8937 Nov 15 11:36 variables.index
```

!pip install tensorflowjs==1.3.1

```
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --skip_op_check \
    --signature_name=serving_default \
    --saved_model_tags=serve \
  ./saved_model \
  ./web_model

```

I got many warning.
"WARNING:tensorflow:Unable to create a python object for variable <tf.Variable ....."
However, model.json was created in the web_model folder.
```
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard1of7.bin
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard2of7.bin
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard3of7.bin
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard4of7.bin
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard5of7.bin
-rw------- 1 root root 4194304 Nov 15 12:11 group1-shard6of7.bin
-rw------- 1 root root 2094848 Nov 15 12:11 group1-shard7of7.bin
-rw------- 1 root root 1098289 Nov 15 12:11 model.json
```

I tried to make it work with a browser, but I got an error.
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.3.1"></script>
var model = await tf.loadGraphModel('http://xxxxxxxxx.com/web_model/model.json');
```
Error

> Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined
>     at t.<anonymous> (graph_model.ts:120)
>     at callbacks.ts:253
>     at Object.next (callbacks.ts:253)
>     at o (callbacks.ts:253)

I searched many websites, but I can't solve it.
Does anyone know how to solve this?

**Comment by pyu10055** [comment]
@seijichishiki Please try again with the latest converter version 1.3.2, this is a fix recently for the issue you have encounter.

**Comment by seijichishiki** [comment]
Thank you very much !
This "producer" error has been resolved. But I got othner error on browser JS console.

> Uncaught (in promise) TypeError: Unknown op 'NonMaxSuppressionV5'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
>     at tfjs@1.3.2:2
>     at hb (tfjs@1.3.2:2)
>     at p (tfjs@1.3.2:2)
>     at t.processStack (tfjs@1.3.2:2)
>     at t.<anonymous> (tfjs@1.3.2:2)
>     at tfjs@1.3.2:2
>     at Object.next (tfjs@1.3.2:2)
>     at o (tfjs@1.3.2:2)

Do you know how to solve this ?

**Comment by seijichishiki** [comment]
I solved it myself.
The input_format of tensorflowjs_converter is 'tf_frozen_model' , not 'tf_saved_model'.

```
!tensorflowjs_converter \
    --input_format=tf_frozen_model \
    --output_format=tfjs_graph_model \
    --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice' \
    --skip_op_check \
    --saved_model_tags=serve \
  ./frozen_inference_graph.pb \
  ./web_model
```
tensorflowjs==1.3.2
```
!tensorflowjs_converter --help
  --output_node_names OUTPUT_NODE_NAMES
              The names of the output nodes, separated by commas.
              E.g., "logits,activations". Applicable only if input
              format is "tf_frozen_model".
```

I spent a lot of time for this.
I hope this helps someone.
