### ISSUE TITLE
Load model from variables

### ISSUE THREAD

**Issue by harishkrishnav** [tensorflow/tfjs#2399]
I'm using tfjs 1.3.1 on Google Chrome v77. 

I have the model topography and weights as blobs and I want to load a model with these. In other words, if `var model ` and  `var weights` have the contents of `model.json` and `weights.bin` respectively, how do I use `tf.loadLayersModel` on them?

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by harishkrishnav** [comment]
Thanks @rthadur  for the reply. [I did ask on StackOverflow](https://stackoverflow.com/questions/58633704/load-tensorflow-js-model-from-object) about 2 weeks ago but didn't get a response.

**Comment by rthadur** [comment]
Can you please provide more details . 
1) model if possible and steps you are trying to generate model and utilize it in tfjs.
2) node version
3) converter version
Thanks

**Comment by harishkrishnav** [comment]
I'll give more context. I recieve from an API a zipped folder containing model.json, weights.bin, and the labels. These seem to have been converted with tfjs-converter v 1.3.1 but I could be wrong. Now, I can unzip the folder and save the individual files to the file system fine. I can also load these without qualms using `tf.loadLayersModel(path\to\model.json)` with weights.bin in the same folder. 
I want to avoid this step of downloading to the file system and load the model directly on the browser. I think it should be possible since I have the contents of model.json and weights.bin already.

**Comment by pyu10055** [comment]
@harishkrishnav You can try to use the browser file io handler similar to following:

```
 const jsonUpload = document.getElementById('json-upload');
 const weightsUpload = document.getElementById('weights-upload');
 
 const model = await tf.loadLayersModel(
      tf.io.browserFiles([jsonUpload.files[0], weightsUpload.files[0]]));
```
 can implement a custom io handler for your files, the interface is defined [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/io/types.ts)

**Comment by harishkrishnav** [comment]
Thanks @pyu10055 for your response. I did use the browser file io method but it's quite inconvenient because there has to be an upload step since loadLayersModel seems to be performing some file reading. I want to completely avoid loading from a file because I already have the file contents. I looked at the link for custom io handlers but it seems that here too we need paths to the files. Can you point me to which specific part of the code I can look at?

**Comment by pyu10055** [comment]
@harishkrishnav 
The LoadHandler interface has no requirement for a path, you can take a look at the [BrowserFile](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/io/browser_files.ts#L122) implementation, you can have the data as part of your own IOHandler class, you can totally ignore what is passed into the IOHandler constructor. The only thing you need to do is to construct the ModelArtifacts as output of the load method.

**Comment by harishkrishnav** [comment]
Many thanks @pyu10055
