### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization NonMaxSuppressionV5

### ISSUE THREAD

**Issue by sushanth-d** [tensorflow/tfjs#2413]
#### TensorFlow.js version 1.3.2

Running the following command : 
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    /content/sample_data/1 \
    /content/sample_data/web

is throwing the error:
ValueError: Unsupported Ops in the model before optimization NonMaxSuppressionV5.

I am trying to convert a trained ssd_mobilenet_v2. I tried the same code with ssd_mobilenet_v1_fpn also. But faced the same issue. In both cases, I took a pre-trained model on the coco dataset and retrained it on my custom dataset. 

Folder sturucture of "1"
1:
    ----variables (empty folder)
    ----saved_model.pb

Any help would be much appreciated.

**Comment by rthadur** [comment]
Thanks for reporting , i see you commented in other related issue here #2323 , did you try this steps mentioned by user https://github.com/tensorflow/tfjs/issues/2323#issuecomment-549801010

**Comment by sushanth-d** [comment]
Yes I tried 

> You can convert the model with an older version of tfjs 

this recommendation and downgraded my tensorflowjs to 0.8.6 and 1.0.1 and tested. In both the cases it threw the same error with the difference that  there were other ops that were not supported in  those versions. But ops not supported error nonetheless.

**Comment by pyu10055** [comment]
@sushanth-d You don't need to downgrade the converter to older version anymore, the latest version (1.3.2) supports frozen model, you can use following command to convert:

```
tensorflowjs_converter --input_format=tf_frozen_model \
                       --output_format=tfjs_graph_model \
                       --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice' \
                       ./frozen_inference_graph.pb \
                       ./web_model
```

The coco-ssd README has been updated with this.

**Comment by sushanth-d** [comment]
@pyu10055  I tried that like mentioned in the #2323. But I am still getting the same error.

```
!tensorflowjs_converter --input_format=tf_frozen_model \
                       --output_format=tfjs_graph_model \
                       --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice' \
                       /content/sample_data/frozen_inference_graph.pb \
                       /content/sample_data/web
```

Error:

Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 638, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 642, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 625, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 382, in convert_tf_frozen_model
    strip_debug_ops=strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 141, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
NonMaxSuppressionV5

**Comment by sushanth-d** [comment]
I trained these models using TensorFlow 1.15.0. Would that be a factor to consider?

If yes, please tell me which TensorFlow version I should use for tensorflowjs 1.3.2. Or any corresponding versions of TensorFlow and tensorflowjs.

**Comment by sushanth-d** [comment]
Downgrading the TensorFlow version from 1.15.0 to 1.14.0 while training my model fixed this issue. Then I was successfully able to convert the model into TensorFlow-js format.
