### ISSUE TITLE
Body-pix 2.0 -- How to show the human skeleton?

### ISSUE THREAD

**Issue by charlesgu6** [tensorflow/tfjs#2415]
Body-pix 2.0 is a wonderful work! I have some trouble in show the human skeleton, please help me.
my code is:
```html
<html>

<head>
  <!-- Load TensorFlow.js -->
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.2"></script>
  <!-- Load BodyPix -->
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix@2.0"></script>
</head>

<body>
  <img id='image' src='person.jpg' crossorigin='anonymous' /><br>
  <canvas id="canvas" width="480" height="270"></canvas>
</body>
<!-- Place your code in the script tag below. You can also use an external .js file -->
<script>
  const img = document.getElementById('image');

  async function loadAndPredict() {
    const net = await bodyPix.load();
    const partSegmentation = await net.segmentMultiPersonParts(img);

    const coloredPartImage = bodyPix.toColoredPartMask(partSegmentation);
    const opacity = 0.7;
    const flipHorizontal = false;
    const maskBlurAmount = 0;
    const canvas = document.getElementById('canvas');

    bodyPix.drawMask(
      canvas, img, coloredPartImage, opacity, maskBlurAmount,
      flipHorizontal);
  }
  loadAndPredict();
</script>

</html>
```
I want to show the human skeleton in image, but I can not find any infomation in your README.md, please help me!!!

p.s. I also have a plan to use body-pix 2.0 detect video stored on my computer, could you please add some tutorial about video in your README.md.

**Comment by tylerzhu-github** [comment]
Hi @charlesgu6 

Thanks for reaching out! And sorry for the delayed response.

The code for visualizing the poses can be found in our BodyPix demo's index.js file.
Here: https://github.com/tensorflow/tfjs-models/blob/master/body-pix/demos/index.js#L572
You can use that as a reference. 

In terms of running BodyPix on videos, I used HTML Video. Here: https://www.w3schools.com/tags/tag_video.asp. 
Yes, I can add an example of how to read local video and run BodyPix on them to the README.md.

Best,
Tyler

**Comment by charlesgu6** [comment]
Thank you !
