### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization CTCBeamSearchDecoder

### ISSUE THREAD

**Issue by porst17** [tensorflow/tfjs#2419]
#### TensorFlow.js version
1.3.2

#### Describe the problem or feature request
I tried to convert a Tensorflow `SavedModel` to a web model via 
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names "w2l/predictions/1" \
    --saved_model_tags=serve \
    ./saved_model/ \
    ./web_model/
```
and it failed due to an unsupported operation:
```
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/tensorflowjs/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/miniconda3/envs/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 638, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/miniconda3/envs/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 642, in main
    convert(argv[0].split(' '))
  File "/usr/local/miniconda3/envs/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 591, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/usr/local/miniconda3/envs/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 443, in convert_tf_saved_model
    strip_debug_ops=strip_debug_ops)
  File "/usr/local/miniconda3/envs/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 141, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
CTCBeamSearchDecoder
```
Any help is appreciated.

**Comment by rthadur** [comment]
@porst17 thank you , can you please more details here 
1) what is the model and how it is trained 
2) please share the model if possible 
3) tfjs-converter and tfjs-node versions 
Thank you

**Comment by porst17** [comment]
1. Unfortunately, I can not upload the `SavedModel` due to license restrictions.
2. I got the `SavedModel` (or rather the python code that generates the `SavedModel`) from a project partner, so I don't now much about it. If you let me know how I can extract some information you need from the `SavedModel` (some python code or command line tool), I am happy to try it and share the results.
3. I am running this on macOS. The tfjs-converter version is:
    ```
    $ tensorflowjs_converter -v

    tensorflowjs 1.3.2

    Dependency versions:
      keras 2.2.4-tf
      tensorflow 1.15.0
    ```
   I am not actively running `tfjs-node` at the moment. My goal is to us a `SavedModel` created via some python code in `tfjs-node`,  but the first step - the conversion - failed, so I didn't start with step two yet. I guess, I will use the most recent version of `tfjs-node` then.

**Comment by porst17** [comment]
I created a log file for importing into TensorBoard via https://github.com/tensorflow/tensorflow/issues/8854#issuecomment-549179468. I think that is save to share.

[events.out.tfevents.1574412923.myhost.log](https://github.com/tensorflow/tfjs/files/3878813/events.out.tfevents.1574412923.myhost.log)

The graph is similar to the `wav2letter` convolutional neural network.

**Comment by dsmilkov** [comment]
Hi,

We won't be prioritizing adding `CTCBeamSearchDecoder` at this time, since the op is only used in an older audio-based architecture, and not actively used in newer models. But contributions are welcomed!

**Comment by gaikwadrahul8** [comment]
Hi, @porst17 

Apologize for the delayed response and please refer this [comment](https://github.com/tensorflow/tfjs/issues/2419#issuecomment-598383080) and it seems like we haven't implemented this `CTCBeamSearchDecoder` Op as of now and May I know still are you looking to add `CTCBeamSearchDecoder` Op in TFJs please ? 

If someone is looking to contribute for `CTCBeamSearchDecoder` Op, you're always welcome and please refer this [link](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md). Thank you!


Thank you!
