### ISSUE TITLE
Implement tf.strided_slice

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#242]
We've seen requests for this in model conversions several times, let's prioritize this.

See: https://www.tensorflow.org/api_docs/python/tf/strided_slice

**Comment by BusbyActual** [comment]
Happy to take this one on. Any guidance would be appreciated I see the link and that looks like a great spec

**Comment by nsthorat** [comment]
Awesome, thanks @BusbyActual. Sure, yeah I think the spec is pretty clear too.

First, I would implement the op on the CPU, before you write the shader. For example: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/backend_cpu.ts#L171

First thing you need to do is compute the output shape given the input parameters. For now, it's fine to keep the parameters as number[] and not Tensors (except for x, of course). Once you compute the output shape, you should iterate through all elements in the output Tensor and then compute which input to sample from to produce that output.

Hopefully thats enough to get you started. Feel free to open up a PR with "WIP" if you want me to look at it and give some feedback.

Cheers!

**Comment by BusbyActual** [comment]
@nsthorat I'm a little confused about the CPU part.  Do you mean to define op in tfjs-core https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/backend_cpu.ts#L145 ?

Also, your other instructions I'm following I think. Also using this as a guideline https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/array_ops.py#L753 . Thanks again for clarification this is my first issue on the project.

**Comment by pyu10055** [comment]
@BusbyActual I just created PR for the support of strided slice. You can use it for reference. There are several mask I did not implement, maybe you can look into those once the PR is merged. Thanks.
