### ISSUE TITLE
Failed to load a pretrained TF model in TFJS: "await is only valid in async function"

### ISSUE THREAD

**Issue by philipp-ghtest** [tensorflow/tfjs#2423]
Hey,

(disclaimer - I'm a JavaScript newbie, but I have to use TFJS to deploy a project, so please excuse me if this is a stupid mistake)

I trained a model with python TF, saved it to hdf5, converted it to a model.json with tensorflowjs_converter, and now I want to use it to make predictions in the browser.

So, this is my index.html:

>  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js"></script>

>  <script>

>  	

>  	const model = tf.loadLayersModel('http://localhost:3000/model.json');

>  	alert(typeof(model));

>  

>  	document.getElementById("summary").innerHTML = model.summary();

>  

>  	const example = tf.tensor3d([   // here comes a hugh tensor I left out for readability

>  	const prediction = model.predict(example);

>  	

>  

>  	document.getElementById("demo").innerHTML = example;

>  

>   

>  </script>

When I'm running this on a local node.js server, I get the error message:

> Uncaught SyntaxError: await is only valid in async function

So, when I remove the await statement, I first get the alert for the typeof which says 'object' as well as the following error messages:

> Uncaught TypeError: model.summary is not a function

> Uncaught (in promise) Error: Input 0 is incompatible with layer flatten: expected min_ndim=3, found ndim=2.

So, I guess, loading the model fails because the typeof alert says 'object' instead of tf.something, which seems to be why I can't call summary() on the model (calling predict() fails as well).

But still the second error seems to be a TF error?!

Loading a different model also fails with the same errors:

> const model = await tf.loadLayersModel('https://storage.googleapis.com/tfjs-models/tfjs/iris_v1/model.json');

So, what am I doing wrong?

**Comment by rthadur** [comment]
@philipp-ghtest thank you , you should wrap your code in a async so that you can use await , that might solve the intial problem there.

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by philipp-ghtest** [comment]
Thank you, I fixed the issue with the await statement like you suggested and it worked, but now a tfjs error pops up.

I'll resubmit it here later in case no-one on stackoverflow knows what to do
