### ISSUE TITLE
[BodyPix] Adds to README.md an example of running BodyPix on a video

### ISSUE THREAD

**Issue by tylerzhu-github** [tensorflow/tfjs#2425]
Adds an example of how to read local videos and run BodyPix on them to the README.md.

**Comment by tylerzhu-github** [comment]
Ref: https://github.com/tensorflow/tfjs/issues/2415

**Comment by passachon** [comment]
I want an example of running bodypix on a video too.

**Comment by passachon** [comment]
<html>
  <head>
    
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.2"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix@2.0"></script>
 </head>

  <body>
    <button onclick="myFunction()" type="button">Get video length</button><br>
 
 <video id="myVideo" width="640" height="480" controls>
  <source src="ep1.mp4" type="video/mp4">
  
  Your browser does not support HTML5 video.
 </video>
 <script>
  var vid = document.getElementById("myVideo");
  
  function myFunction() { 
    alert(vid.duration);
  } 
  </script> 
  </body>
  
  <script>
    const img = document.getElementById('myVideo');
    
    
    async function loadAndPredict() {
      const net = await bodyPix.load(/** optional arguments, see below **/);

      /**
       * One of (see documentation below):
       *   - net.segmentPerson
       *   - net.segmentPersonParts
       *   - net.segmentMultiPerson
       *   - net.segmentMultiPersonParts
       * See documentation below for details on each method.
       */
      

      const segmentation = await net.segmentPersonParts(img);
      console.log(segmentation);
    }
    loadAndPredict();
  </script>
</html>

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
