### ISSUE TITLE
Validate input arguments for MaxPooling1D config

### ISSUE THREAD

**Issue by urbiworx** [tensorflow/tfjs#244]
I did already ask at the google group, I was asked to raise a ticket

#### TensorFlow.js version
0.10.0

#### Browser version
Chrome 66.0.3359.139

#### Describe the problem or feature request
When trying to build a model like below, the error message "RangeError: Invalid typed array length: -272" occurs.
```
	const model = tf.sequential();
	model.add(tf.layers.conv1d({
		  inputShape: [20,1],
		  kernelSize: 5,
		  filters: 8,
		  strides: 1,
		  activation: 'relu',
		  kernelInitializer: 'VarianceScaling',
		  name:'Layer1'
		}));
		model.add(tf.layers.maxPooling1d({
		  poolSize: [2],
		  strides: [2],
		  name:'Layer2'
		}));
		model.add(tf.layers.flatten({name:'flatten'}));
		model.add(tf.layers.dense({
				units: 2,
				kernelInitializer: 'VarianceScaling', 
				activation: 'softmax',
				name:'Layer3'
			})
		);
```

#### Code to reproduce the bug / link to feature request
https://jsfiddle.net/94v3dgm9/

**Comment by caisq** [comment]
I believe you get this error because in your `Layer2`, you should set `poolSize` and `strides` as numbers, instead of Arrays. I.e.,

```js
model.add(tf.layers.maxPooling1d({
		  poolSize: [2],
		  strides: [2],
		  name:'Layer2'
		}));
```

We'll improve the type checking and error messages.

**Comment by caisq** [comment]
Closing this issue, as `maxPooling1d` layer is able to handle `poolSize` or `strides` passed as arrays now.
