### ISSUE TITLE
Bug in deserializing TF2.0 GRU layer's bias vector in tf.loadLayersModel()

### ISSUE THREAD

**Issue by philipp-ghtest** [tensorflow/tfjs#2442]
Dear tfjs-team,

I ran into an issue these days when I tried to import a former Keras .h5 model with GRU layers into tfjs, see https://github.com/tensorflow/tfjs/issues/2437

tldr: this error popped up:
```
 Uncaught (in promise) Error: Shape mismatch: [384] vs. [2,384]
     at variables.ts:135
     at t.write (variables.ts:98)
     at variables.ts:339
     at Array.forEach (<anonymous>)
     at sf (variables.ts:337)
     at e.loadWeights (container.ts:598)
     at models.ts:315
     at common.ts:14
     at Object.next (common.ts:14)
     at a (common.ts:14)
```

On further investigation, I figured out that there's something wrong in `models.ts:300` in the  `deserialize()` function. 

Turns out that the model object returned by `deserialize()` sets faulty shapes for the bias vectors of GRU layers (those should be of shape [2, x] but are set to [x], here [384):

![tfjs_debug3](https://user-images.githubusercontent.com/50402778/69738257-18c9b580-1136-11ea-8a82-1b5c960c742d.png)

On the contrary, the weights loaded in `models.ts:313` by `io.decodeWeights()` are set correctly (here [2, 384]):

![tfjs_debug2](https://user-images.githubusercontent.com/50402778/69738265-1e270000-1136-11ea-9505-b9d434d0f654.png)

So there must be something wrong with `deserialize()` or some nested functions. I really tried to dig further, but I'm basically totally foreign to JS/TS so it's really hard for me to figure it out any further.

This bug should be easy to reproduce, just create some model with GRU layers in Keras, like this:

```
model = keras.models.Sequential([
#    keras.layers.GRU(128, return_sequences=True, batch_input_shape=[batch_size, None, max_id+1]),
    keras.layers.GRU(128, return_sequences=True, input_shape=[ None, max_id+1]),
    keras.layers.GRU(128, return_sequences=True),
    keras.layers.GRU(128),
    keras.layers.Flatten(),
    keras.layers.Dense(output_size, activation="softmax")
])
```

I guess you don't even need to train it, just initializing it should be fine.

Then convert it with the tfjs-converter, and load it with `tf.loadLayersModel`

I'd be really grateful for any fixes or quick workarounds. Thank you in advance!

**Comment by philipp-ghtest** [comment]
Hey, any update on this?

**Comment by caisq** [comment]
@philipp-ghtest Sorry for the delay in getting back to you.

I looked at the Python code that you used to generate the model. Why are you including a ` keras.layers.Flatten()` layer? The output of the 3rd (last) GRU layer already has a flat output shape (None, 128). If you remove that layer, things should work properly in TensorFlow.js.

**Comment by caisq** [comment]
I close this issue for now. If you have any additional questions or concerns, please feel free to keep adding comments and/or re-open this issue. @philipp-ghtest

**Comment by ckhordiasma** [comment]
I am having this exact same issue. I am also using a GRU, in my case my model looks like 
``` python
model = tf.keras.Sequential([
  tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
  tf.keras.layers.GRU(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
  tf.keras.layers.Dense(vocab_size)
])
```

I am importing using keras and the tensorflowjs command line tool from pip, ` tensorflowjs_converter --input_format keras ./model.h5 ./output`

when I try to import my model into tensorflow js using the command:  `const model = tf.loadLayersModel('/output/model.json')` 

I get the error:  `Uncaught (in promise) Error: Shape mismatch: [3072] vs. [2,3072]`

I have tried converting using the python tool instead of the command line tool 

```python
import tensorflowjs as tfjs
import tensorflow as tf
model = tf.keras.models.load_model('../model.h5')
tfjs.converters.save_keras_model(model, './output/')
```

but that has also not worked.

please let me know if there is any more info I can provide.

**Comment by philipp-ghtest** [comment]
> @philipp-ghtest Sorry for the delay in getting back to you.
> 
> I looked at the Python code that you used to generate the model. Why are you including a ` keras.layers.Flatten()` layer? The output of the 3rd (last) GRU layer already has a flat output shape (None, 128). If you remove that layer, things should work properly in TensorFlow.js.

Nope, it doesn't. I've already tried this.

As I extensively described in my first post, this is due to a shape mismatch when setting the bias weights of the GRU layers in tfjs.

I'm still trying to track this issue down, but up to date I'm pretty sure there's something wrong with setting/initializing weights in tfjs' GRU layers.

**Comment by philipp-ghtest** [comment]
@ckhordiasma 

Thanks for your reply. This is indeed the same issue as mine. I'm glad I'm not the only one.

**Comment by philipp-ghtest** [comment]
@ckhordiasma @caisq 

I found a workaround that works for me. 

I figured that in the bias weights that get saved from keras that have the shape `[2, 384]` (the 384 is case specific of course), that in these weights, the [0] column has exactly the same values as the [1] column. So that's more likely a bug in tf's python code?

Anyway, if you manually set up the architecture, and then manipulate the weights by cropping them from `[2, 384]` to `[384]`, it works!!

```js
       //build arch manually first
	const model = tf.sequential();
	model.add(tf.layers.gru({ units: 128 , returnSequences: true, inputShape: [null, 63], name: 'gru'}));
	model.add(tf.layers.gru({ units: 128 , returnSequences: true, name: 'gru_1'}));
    
	model.add(tf.layers.gru({ units: 128 , name: 'gru_2'}));
	//model.add(tf.layers.flatten());
	model.add(tf.layers.dense({ units: 3732, activation: 'sigmoid', name: 'dense'}));
	
	model.summary();

	
       //load weights manually
	const path = 'http://localhost:3000/prototype_catcross_web_Kopie/model.json'
	const handlers = tf.io.getLoadHandlers(path);
    if (handlers.length === 0) {
		handlers.push(tf.io.browserHTTPRequest(path, options));
		}
	handler = handlers[0];
	(async () => {
		const artifacts = await handler.load();
		const weights =
			tf.io.decodeWeights(artifacts.weightData, artifacts.weightSpecs);
		
         // crop weights to correct shape
                bias = weights["gru/bias"].as1D().slice([0],[384]);
		bias_1 = weights["gru_1/bias"].as1D().slice([0],[384]);
		bias_2 = weights["gru_2/bias"].as1D().slice([0],[384]);
		weights["gru/bias"] = bias
		weights["gru_1/bias"] = bias_1;
		weights["gru_2/bias"] = bias_2;
		model.loadWeights(weights, true);
		
		const example = tf.tensor3d(// stupidly long tensor for testing ]]);
		const prediction = model.predict(example);
		
                // correct result is found!!!
                argmax = prediction.squeeze().argMax();
		document.getElementById("demo").innerHTML = argmax;
		document.getElementById("summary").innerHTML = prediction;
}	)();
```

So this workaround is quite ugly, but it clearly shows that it's because of the weights.

Sorry I can't post a more elaborate fix, since I'm really not  good at TS/JS and absolutely not familiar with tfjs code.

**Comment by philipp-ghtest** [comment]
@caisq can you maybe reopen this and label it as a bug and not as support? That would really be great, thanks!

**Comment by caisq** [comment]
@philipp-ghtest and @ckhordiasma I realized I should have asked you for this basic piece of info before: what versions of tensorflow and tensorflowjs (in python) and tensorflow.js (in JavaScript) are you using?

I just did a quick testing of @ckhordiasma 's GRU model with tensorflow 1.15.0, tensorflowjs 1.1.5, and @tensorflow/tfjs-node 1.3.2 and the model saving / conversion and loading seem to be working properly.

**Comment by ckhordiasma** [comment]
Im traveling and don’t have access to my computer for more specifics, but I
know I’m using tensorflow 2.0 and the most recent version of tensorflowjs
on pypi for the import

**Comment by philipp-ghtest** [comment]
@caisq I trained and exported the model with Tensorflow 2.0.0, and converted it with the tensorflowjs_converter from tensorflowjs 1.3.2., both installed via pip

In JS, I tried both tfjs 1.0.0 and 1.3.2, imported by script tag, but neither works

`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.3.2/dist/tf.min.js"></script>
`

**Comment by caisq** [comment]
@philipp-ghtest I can verify that this error exists for models saved by tensorflow 2.0.0. I'll continue investigating this issue.

The workaround for you folks right now is to use tensorflow 1.15 to saved the model (followed by conversion and model loading in JS). Sorry for the inconvenience.

**Comment by caisq** [comment]
Changing priority to P2 as there is a workaround available. 

This seems to be originated from a change in the behavior of the GRU layer (specifically the GRUCell class) between tf 1.5 and 2.0. In the older version, the bias has a shape of (9,), in the latter, it has a shape of (2, 9), which is a stacking of two biases: recurrent_bias (input_bias and recurrent_bias). TensorFlow.js hasn't caught up with this change yet.

cc @fchollet @karmel

**Comment by philipp-ghtest** [comment]
Thank you very much for looking into it and for the workaround.

Unfortunately, the workaround only works if you retrain the model on tf1.1x. I tried loading my saved .h5 model into my python training script, and exporting it again for conversion with tfjs. 

But on `model.load_weights(os.path.join(data_dir, "prototype.h5"))` I get the following error:

 `ValueError: GRU(reset_after=True) is not compatible with GRU(reset_after=False)`

So, I tried again, this time with setting `reset_after=True`:


```py
model = keras.models.Sequential([
#    keras.layers.GRU(128, return_sequences=True, batch_input_shape=[batch_size, None, max_id+1]),
    keras.layers.GRU(128, return_sequences=True, input_shape=[ None, max_id+1], reset_after=True),
    keras.layers.GRU(128, return_sequences=True, reset_after=True),
    keras.layers.GRU(128, reset_after=True),
    keras.layers.Flatten(),
    keras.layers.Dense(output_size, activation="softmax")
])
```

This time, loading my saved weights works fine. But when I export this configuration to TFJS, I get the same error in TFJS:

`Uncaught (in promise) Error: Shape mismatch: [384] vs. [2,384]`

So I'm retraining my model right now, I can tell you if the workaround works if it's done

**Comment by elazarg** [comment]
reset_after=True doesn't work for me:
```python
import tensorflow as tf

USE_BIAS = True  # Fails iff True
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(5, 7),
    tf.keras.layers.GRU(3, use_bias=USE_BIAS, reset_after=True)
])

import tensorflowjs as tfjs
tfjs.converters.save_keras_model(model, 'bad_js/')
```

Version 1.6.0

**Comment by psaikko** [comment]
This seems to still be current. I am seeing this same shape mismatch issue with

TensorFlow.js version
@tensorflow/tfjs@1.7.4/dist/tf.min.js

python packages:
tensorflow 2.1.0
tensorflowjs 1.7.4.post1

I am saving my model with `tfjs.converters.save_keras_model`

```
Uncaught (in promise) Error: Shape mismatch: [192] vs. [2,192]
    at variables.ts:135
    at t.write (variables.ts:98)
    at variables.ts:339
    at Array.forEach (<anonymous>)
    at od (variables.ts:337)
    at e.loadWeights (container.ts:628)
    at models.ts:318
    at common.ts:14
    at Object.next (common.ts:14)
    at o (common.ts:14)
```

If I replace the `GRU` layer with a `SimpleRNN` layer in the model, it loads correctly in tfjs.

**Comment by GUR9000** [comment]
Can someone explain why the GRU would need twice as many biases in TF2.0 compared to all other implementations of GRUs (origninal paper, TF1, other frameworks, etc.? Is this a TF2 bug?

**Comment by jaspervandorp** [comment]
I encountered this issue to, and I have trouble understanding what is happening under the hood. I wrote a small script that basically proofs that tensorflow does *something* with the 'second' vector in the 2xN bias matrix, but to me it is not clear what exactly.

When I try to re-create the output of a GRU layer manually using only one of the two 1xN vectors, I get a different result than the one from model.predict(). When I replace the second 1xN vector in the original model with zeros, I *do* get the same result.

So, the following questions remain:

1. What does tensorflow/Keras do with this second vector? The literature about GRU cells never mentions these biases.
2. Why is the second vector exactly equal to the first one?

Can someone shed a light on this?

**Here is the script:**
```
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import GRU
import numpy as np

print('Tensorflow version: {}'.format(tf.__version__))
print('Numpy version: {}'.format(np.__version__))
print('')

num_features = 3
num_nodes = 4
Ntrain = 100

def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

def split_weights(W, U, b, num_nodes):
    """
    Splits the concatenated weights & biases into individual kernels
    """
    Wz = W[:,:num_nodes]
    Wr = W[:,num_nodes:2*num_nodes]
    Wh = W[:,2*num_nodes:3*num_nodes]
    Uz = U[:,:num_nodes]
    Ur = U[:,num_nodes:2*num_nodes]
    Uh = U[:,2*num_nodes:3*num_nodes]
    bz = b[:num_nodes]
    br = b[num_nodes:2*num_nodes]
    bh = b[2*num_nodes:3*num_nodes]
    return Wz,Wr,Wh,Uz,Ur,Uh,bz,br,bh

def GRU_layer(W, U, b, num_nodes, X):
    """
    Simulates a "v3" GRU layer, where the reset gate is applied
    before matrix multiplication.
    """
    # Get the individual kernels & biases
    Wz,Wr,Wh,Uz,Ur,Uh,bz,br,bh = split_weights(W, U, b, num_nodes)
    # The current state will be all-zeros
    ht = np.zeros((num_nodes,))
    # Calc GRU
    zt = sigmoid(np.matmul(X,Wz)+np.matmul(ht,Uz)+bz)
    rt = sigmoid(np.matmul(X,Wr)+np.matmul(ht,Ur)+br)
    # v3 behavior: reset applied before matrix multiplication
    ht_new = np.tanh(np.matmul(X,Wh)+np.matmul(rt*ht,Uh)+bh)
    Y = zt*ht + (1-zt)*ht_new
    return Y

# Create a 1-layer GRU model
keras_model = Sequential()
keras_model.add(GRU(num_nodes, stateful=True, 
                    batch_input_shape=(1,1,num_features)))
keras_model.compile(loss='binary_crossentropy',
                    optimizer='Adam')

# Reset the model states to all-zeros
keras_model.reset_states()

# Train the model for one epoch on some dummy data
Xtrain = np.random.normal(size=(Ntrain,1,num_features))
Ytrain = np.random.normal(size=(Ntrain,num_nodes))
keras_model.fit(Xtrain,Ytrain)

# Create random input
X = np.random.normal(size=(1,1,num_features))

# Run model
Y0 = keras_model.predict(X)
print('Keras model output: {}'.format(Y0))

# Extract the GRU layer weights
W,U,bb = keras_model.layers[0].get_weights()

# Here's the issue: how to convert the 2xN bias matrix to a 1xN vector?
b = bb[0,:]

# Calculate the GRU layer manually (output will not be the same!)
Y1 = GRU_layer(W, U, b, num_nodes, X)
print('GRU_layer output: {}'.format(Y1))

# Now, re-set the weighs in the original model, but replace the 'second'
# bias vector with zeros
bb_alt = np.vstack((b, b*0))
keras_model.layers[0].set_weights([W, U, bb_alt])

# Re-calculate the output (this will be the same as the GRU_layer result!)
keras_model.reset_states()
Y0_alt = keras_model.predict(X)
print('Keras model output (alt): {}'.format(Y0_alt))
```

**And this is the output:**

```
Tensorflow version: 2.1.0
Numpy version: 1.19.1

Train on 100 samples
100/100 [==============================] - 2s 17ms/sample - loss: 0.5797
Keras model output: [[-0.3623277  -0.28993392 -0.13113655  0.07228291]]
GRU_layer output: [[[-0.45852431  0.16752497 -0.18502576  0.1790349 ]]]
Keras model output (alt): [[-0.45852435  0.16752502 -0.18502575  0.17903492]]
```
