### ISSUE TITLE
Uncaught (in promise) Error: Tensor must have a shape comprised of positive integers but got shape [100,].

### ISSUE THREAD

**Issue by MRchenao** [tensorflow/tfjs#2449]
Uncaught (in promise) Error: Tensor must have a shape comprised of positive integers but got shape [100,].
use ssd_mobilenet_v1_coco 
![image](https://user-images.githubusercontent.com/18750497/69839537-d8cc1500-1292-11ea-82f8-d26c581ad9ce.png)

Any help will be greatly appreciated.

**Comment by rthadur** [comment]
Please specify the steps you used to generate the model ?

**Comment by MRchenao** [comment]
@rthadur 
1、`python3 tf-models/research/object_detection/export_inference_graph.py --input_type=image_tensor --pipeline_config_path=/data/FashionDetector/models/ssd_mobilenet_v1_coco_11_06_2017/pipeline.config --trained_checkpoint_prefix=/data/FashionDetector/models/ssd_mobilenet_v1_coco_11_06_2017/model.ckpt-7904 --output_directory=/data/FashionDetector/ssd_v1_coco`

2、`tensorflowjs_converter --input_format=tf_saved_model --output_node_names="detection_boxes,detection_scores,detection_classes" --saved_model_tags=serve --output_json model.json ./saved_model ./web_model`

3、the model.json url is :  https://wx.ndszgb.com/ssdlite/model.json

**Comment by MRchenao** [comment]
最后我发先是coco-ssd的源码有问题，出现这个错误是说明你的输入不符合标准。最终我是通过修改另一个类似coco-ssd的物体检测的前端sdk来解决这个问题的。具体的解决办法还是需要各位根据自己的模型输出情况来处理。

**Comment by McDo** [comment]
same issue
I found that `scores` should be `result[0]` while `boxes` should be `result[1]` in `index.ts`

**Comment by kezmanh** [comment]
@MRchenao  Could you please share your solution?

**Comment by bchiu** [comment]
I had the same problem on windows (but it builds fine on colab using replicated procedure). There is an issue compiling the object detection modules....

protoc object_detection/protos/*.proto --python_out=.

All the modules compile except for image_resizer which yields the warning:
>> object_detection/protos/input_reader.proto:5:1: warning: Import object_detection/protos/image_resizer.proto is unused.

Solution is to compile image_resizer and run export_inference_graph, tensorflowjs_converter again:
protoc object_detection/protos/image_resizer.proto --python_out=.

**Comment by meiroo** [comment]
> 最后我发现是coco-ssd的源码有问题，出现这个错误是说明你的输入不符合标准。最终我是通过修改另一个类似coco-ssd的物体检测的前端sdk来解决这个问题的。具体的解决办法还是需要各位根据自己的模型输出情况来处理。

能透露一下用的哪一个sdk吗 我目前也遇到这个问题。

**Comment by gildniy** [comment]
What if you use the 127 offset for normalization instead?

```
...
const offset = tf.scalar(127)
const normalized  = resized.sub(offset).div(offset));
...
```
