### ISSUE TITLE
loadModel of a simple LSTM model, with weights on the order of 3MB uses 5GB memory.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#245]
Code to reproduce:

```
const model = await tf.loadModel('https://timotheebernard.github.io/models/model.json');

// This yields:
// { 
//    unreliable: false
//    numTensors: 8991
//    numDataBuffers: 8986
//    numBytes: 5050462344
// }
console.log(tf.memory());

// If you use this code here you can get the total size of the weights of all layers,
//  which gives 766601. With 4 bytes per weight, that's 3066404 bytes ~= 3MB.
const totalWeightsSize =
    tf.util.flatten(model.layers.map(l => l.weights).filter(x => x.length > 0))
    .map(x => x.val)
    .reduce((accumulator, weight) => accumulator += weight.size, 0);
```

Note that the weights files are small, < 3MB:
https://github.com/timotheebernard/timotheebernard.github.io/tree/master/models

Is there something that recurrent cells are doing that cause this much memory blowout? @caisq, @ericdnielsen, @bileschi can you take a look?

**Comment by nsthorat** [comment]
After we fix this, a useful unit test for every layer will be to assert that when a layer is created, only the variables internally are remaining (using `tf.memory().numTensors`).

See what we do here: https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/sgd_optimizer_test.ts#L29-L34

**Comment by caisq** [comment]
My guess is that this has to do with the Orthogonal initializer of the LSTM. When the model JSON is loaded, the Orthogonal initializer calls the QR decomposition under the hood. Owing to the relatively large size of the matrix, this slows things done. Maybe we can optimize the memory usage of the QR decomposition a little. We can also consider adding the logic to skip any initialization if weights are going to be loaded afterwards.

**Comment by bileschi** [comment]
The QR decomposition seems to be the only reasonable culprit.  I verified that memory is reduced by adding tidy().  Did not test on the full model yet.

See 
https://github.com/tensorflow/tfjs-layers/pull/158

**Comment by nsthorat** [comment]
Awesome!! Nice find guys.

Let's make sure to add memory unit tests for backend methods / layer calls going forward.

**Comment by caisq** [comment]
FYI, I plan to speed up orthogonal initiazers by replacing the QR decomposition with the Gram-Schmidt process.

**Comment by Raza25** [comment]
What is the version for tfjs to which you have added these changes @caisq, @nsthorat @bileschi  ?
I get the warning 'orthogonal initializer is being called' this results in slowness and out of memory exception to end with.
What changes should I make to solve this issue?
