### ISSUE TITLE
Loading keras converted model failed.

### ISSUE THREAD

**Issue by csmovva** [tensorflow/tfjs#2455]
Hello TFJS team. We are trying to convert a standard mobilenet keras model but we are having problems.
Below are the sequence of steps followed and the Error message observed.

colab conversion commands used:
------------------------------------------
!tensorflowjs_converter \
    --input_format=keras \
    --output_format=tfjs_layers_model \
    ./mobilenet_2_5_224_tf.h5 \
    ./my_mobilenet 
---------------------------------------------

commands used to load the model in JS.
----------------------------------------------------------------
let mobilenet = await tf.loadLayersModel("test/model.json");
mobilenet.predict(tf.zeros([1, 224, 224, 3])).dispose();
----------------------------------------------------------------

Errors
------------------------------------------------------------------------------------------------------------
tf-layers.esm.js:4959 Uncaught (in promise) TypeError: Cannot read property 'model_config' of null
    at tf-layers.esm.js:4959
    at tf-layers.esm.js:149
    at Object.next (tf-layers.esm.js:161)
    at o (tf-layers.esm.js:50)
------------------------------------------------------------------------------------------------------------

can you help us with this issue.

Thank You.

**Comment by wingman-jr-addon** [comment]
Looks similar to #931 - could it be that you're only saving weights?

**Comment by startupgurukul** [comment]
The model being used is official recommendation from the url and instructions from https://github.com/tensorflow/tfjs-examples/blob/master/mobilenet/README.md
![Screenshot_20191201-045356478](https://user-images.githubusercontent.com/11027129/69907202-ab987780-13f6-11ea-8879-376cb1d38efd.jpg)

**Comment by caisq** [comment]
@csmovva can you let us know the versions of 
1. tensorflowjs_converter (Python)?
2. tensorflow.js (JavaScript)?

**Comment by wingman-jr-addon** [comment]
@startupgurukul It might be worth posting your exact steps, because I think you may have a misunderstanding about the .h5 file.

The [linked .h5 file](https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_2_5_224_tf.h5) on that page is _not_ a full model, but rather weights that are intended to be loaded into a model - see [the verbiage on the download page](https://github.com/fchollet/deep-learning-models/releases/) makes it clear that the weights are supposed to be loaded into the model created using [mobilenet.py](https://github.com/fchollet/deep-learning-models/blob/master/mobilenet.py).

So let's check that out. If I try converting it using tensorflowjs_converter using the command line you listed above, it's quite happy to do so:
```
(venv) developer@developer-VirtualBox:~/Desktop/tfjs-convert$ tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model ./mobilenet_2_5_224_tf.h5 ./my_mobilenet
```

However, what if we actually tried to load it in Python using `load_model` rather than `model.load_weights` with a preconstructed model?

```
(venv) developer@developer-VirtualBox:~/Desktop/tfjs-convert$ python3
Python 3.6.8 (default, Sep 23 2019, 21:02:06) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.keras.models.load_model('mobilenet_2_5_224_tf.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/Desktop/tfjs-convert/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/developer/Desktop/tfjs-convert/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 209, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
```

So, if you are trying to directly use that linked model you will have problems. I believe the currently recommended approach would be to do something more like this using Keras' applications.

```
(venv) developer@developer-VirtualBox:~/Desktop/tfjs-convert$ python3
Python 3.6.8 (default, Sep 23 2019, 21:02:06) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> model = tensorflow.keras.applications.mobilenet_v2.MobileNetV2(input_shape=(224,224,3), weights="imagenet")
WARNING:tensorflow:From /home/developer/Desktop/tfjs-convert/venv/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Downloading data from https://github.com/JonathanCMitchell/mobilenet_v2_keras/releases/download/v1.1/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224.h5
14540800/14536120 [==============================] - 14s 1us/step
2019-12-04 23:39:28.360542: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-12-04 23:39:28.656541: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2903995000 Hz
2019-12-04 23:39:28.657281: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f5d6a14a50 executing computations on platform Host. Devices:
2019-12-04 23:39:28.657389: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-12-04 23:39:29.904295: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.

>>> tensorflow.keras.models.save_model(model, 'arch_and_weights.h5')
>>> quit()
(venv) developer@developer-VirtualBox:~/Desktop/tfjs-convert$ tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model arch_and_weights.h5 ./mymobilenet_fixed
```
Does that work better for you?

**Comment by wingman-jr-addon** [comment]
@startupgurukul Any luck?

**Comment by caisq** [comment]
Yeah, I think what happened here is that some HDF5 files released by Keras are weights-only: I.e., they have only the weights, but not the model topology. They are used for loading by the Python Keras library itself, in its keras.applications module. If you try to convert such HDF5 files directly to TF.js and load them in JavaScript, you'll get this error.

The workaround is to load the file in Python first, then save it as a HDF5 with both the model topology and weights, and then do the conversion to TF.js.

Does that make sense, @csmovva @wingman-jr-addon ?

**Comment by wingman-jr-addon** [comment]
Yes @caisq  we are on the same page. @csmovva  In this specific case, that mobilenet.py is what builds the model topology.

**Comment by hamletbatista** [comment]
@wingman-jr-addon I have a similar problem but with a different model. I'm following this tutorial that uses TF 2 https://github.com/huggingface/transformers is TF 2 supported?

I see two files saved:

config.json  tf_model.h5

I'm able to convert the h5 file, but get TypeError: Cannot read property 'model_config' of null

This is what is included in config.json

{
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 28996
}

I haven't been able to recreate a Keras model from these two files. Am I missing something?

Thanks

**Comment by wingman-jr-addon** [comment]
@startupgurukul  Was your issue solved by what @caisq  and I were discussing earlier?

@hamletbatista 
Looks like they have a wrapper around the model saving with `.save_pretrained` or some such? So it's a little hard to say quite what's going on without digging in deeper there.
What I can say though is that I think you should be getting a model.json with an architecture in it - if you were to open it, you would see JSON that looked like a bunch of tensors or layers.
I'd look for two things:

1. What does that project do when it actually saves the model as an .h5? Is it calling model.save under the hood etc.
2. If it's not too huge and it's not secret, posting an .h5 produced by it can let folks take a look.

Similarly, assuming you know a bit of Python I find it a good check to try doing the appropriate load method based on the save method you found in #1 as that may give more clues.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by lebron8dong** [comment]
@rthadur 


> tensorflow.keras.models.save_model(model, 'arch_and_weights.h5')

error：CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '
