### ISSUE TITLE
tensorflowjs_converter command not found in windows

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tfjs#2464]
Dear Google-Tensorflow guys,

I met problems when I try to convert some model json file to keras model file.

I have installed tensorflow and tensorflow-js.

It is the version number:
```
>>> import tensorflow
2019-12-03 15:28:51.912271: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
>>> print(tensorflow.__version__)
1.15.0
>>> import tensorflowjs
>>> print(tensorflowjs.__version__)
1.3.2
>>>
```

However, it reported "Command not found" when I launch the command "tensorflowjs_converter". It is so wierd. Can you give me some comment?

Thanks & Regards!
Momo1986

**Comment by tafsiri** [comment]
If i had to guess this would be a path issue. @pyu10055 @caisq any tips for what needs to be in PATH on windows?

**Comment by pyu10055** [comment]
@momo1986 Yannick is probably right on this, it depends if you install the tensorflowjs pip globally or locally. On Linux, the local installation will put the executable in ~/.local/bin directory, for windows people suggest this is the location:
%USERPROFILE%\AppData\Roaming\Python\Scripts
Please confirm if you can find the tensorflowjs_converter exeutable in that directory.
If so, you need to add that to your PATH env variable.

**Comment by MaxMady** [comment]
@pyu10055 I tried to install the npm package @tensorflow/tfjs-converter globally with administrative privileges, everything for the package got installed except the executable file in the Scripts folder, which is missing. I've found the package in the global packages node_modules but the executable cmd file for command line is missing.
