### ISSUE TITLE
How to download posenet model files for using offline?

### ISSUE THREAD

**Issue by sachingarg05** [tensorflow/tfjs#2465]
Trying to use https://github.com/tensorflow/tfjs-models/tree/master/posenet in an electron app that needs to be bundled for use in offline environment.

When offline, can't directly use the model files hosted at,
  https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/
  https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/

It seems easy enough to change the code to point to a local relative path instead, but how/where to download all these model files?

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
