### ISSUE TITLE
No webcam found.  To use this demo, use a device with a webcam

### ISSUE THREAD

**Issue by AIGyan** [tensorflow/tfjs#247]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Browser version: chrome Version 66.0.3359.139

Thank you for your effort in building and supporting tensorflow.js I am new to java script. I am testing webcam transfer learning demo
I am trying to run the demo on my laptop and I am getting the following error on the webpage
`No webcam found. 
To use this demo, use a device with a webcam.`
My laptop has a camera, its working file and I am able to execute my opencv object detection model. 
Please let me know what changes I have to make to run this demo.

**Comment by AIGyan** [comment]
@nsthorat could you please guide me to resolve the above issue.

**Comment by nsthorat** [comment]
How exactly are you running the demo? Are there any errors in the console?

**Comment by kovalepskaia** [comment]
I have the same error that shows cause as below:
[Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
setupCamera @ camera.js:53

**Comment by tafsiri** [comment]
@kovalepskaia are you running this from localhost or from a remote server. If you are doing it from a remote server (i.e. not localhost) you need to server the page over https.

**Comment by kovalepskaia** [comment]
I use code as below (in file index.js):
```
var https = require('https');
var fs = require('fs');
var options = {
    key: fs.readFileSync('./info/key.pem'),
    cert: fs.readFileSync('./info/cert.pem')
};
var a = https.createServer(options, function(){
    res.writeHead(200);
    res.end("hello world \n");
}).listen(1234);
```

But, when running the program, it has an error:
Uncaught ReferenceError: Buffer is not defined
    at Object.require.4.https (index.js:4)
    at newRequire (tfjs-models.js:42)
    at require.27 (tfjs-models.js:69)
    at tfjs-models.js:74

**Comment by hossein-b** [comment]
> @kovalepskaia are you running this from localhost or from a remote server. If you are doing it from a remote server (i.e. not localhost) you need to server the page over https.

Hi, how we can serve the page over https? I need to run it over a remote server, not localhost.
