### ISSUE TITLE
TypeError: The JSON content is required to be a `dict`, but found <class 'list'>.

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tfjs#2472]
Hello, when I run "tensorflowjs_converter" .
It reported error:

> TypeError: The JSON content is required to be a `dict`, but found <class 'list'>.

I want to transform the file of json to keras_save_model:

 `tensorflowjs_converter --input_format tfjs_layers_model --output_format keras_saved_model tiny_face_js/tiny_face_detector_model-weights_manifest.json tiny_face_h5`

But it failed, is there any workaround to resolve the problem?

Thanks & Regards!
Jun Yan

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by momo1986** [comment]
Thanks!
I try to post the question:
https://stackoverflow.com/questions/59189181/typeerror-the-json-content-is-required-to-be-a-dict-but-found-class-list
I wish you are all the best.
Maybe the issue can be closed.
Thanks & Regards!
