### ISSUE TITLE
keras mobilenet model predict Nan

### ISSUE THREAD

**Issue by GodsDusk** [tensorflow/tfjs#2478]
#### python version
3.6.8 virtualenv
#### TensorFlow.js version
1.3.2 
#### Browser version
Chrome 78.0.3904.108 x64
and 
Safari 13.0.3 (14608.3.10.10.1)

I use tf.keras mobilenet pre-trained model
```python
import tensorflowjs as tfjs


from tensorflow.keras.applications.mobilenet import MobileNet

model = MobileNet(weights='imagenet')
tfjs.converters.save_keras_model(model, 'model/')
```
image is from skimage.data.chelsea()

```html
<html>

    <img src="image.jpg" id="image" width=224 height=224 style="display: none" />
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.2.8/dist/tf.min.js"> </script>
    <script>

      let model;
      const demo = async() =>{
        model = await tf.loadLayersModel('model/model.json');
        const imageElement = document.getElementById('image');
        pred = predict(imageElement);
       // pred is nan !
        console.log(pred) 
      }
      async function predict(imageElement){

        const logits = tf.tidy(() => {
        const img = tf.browser.fromPixels(imageElement).toFloat();
        const offset = tf.scalar(127.5);
        const normalized = img.sub(offset).div(offset);
        const batched = normalized.reshape([1, 224, 224, 3]);
        return model.predict(batched)
      });
        return logits.data();
      }
      demo();
    </script>

</html>
```

**Comment by tafsiri** [comment]
Could you give a bit more detail about the nan result you are seeing? Are you seeing a typedarray with nan values or something else. Looking at the code snippet the result from predict is not `await`ed so i would expect that value to be a promise. 

You can also check the values of `img` to make sure they are what you expect (i.e. the image has loaded and is being read correctly).

Other than that any reason to not use https://www.npmjs.com/package/@tensorflow-models/mobilenet?

**Comment by GodsDusk** [comment]
> Could you give a bit more detail about the nan result you are seeing? Are you seeing a typedarray with nan values or something else. Looking at the code snippet the result from predict is not `await`ed so i would expect that value to be a promise.
> 
> You can also check the values of `img` to make sure they are what you expect (i.e. the image has loaded and is being read correctly).
> 
> Other than that any reason to not use https://www.npmjs.com/package/@tensorflow-models/mobilenet?

<img width="494" alt="WX20191206-095644@2x" src="https://user-images.githubusercontent.com/13726533/70289263-2efb0400-180f-11ea-9727-a0ae67da0689.png">

here is  the result，and if I replace 
`model = await tf.loadLayersModel('model/model.json');`  to `'https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json'` 
the result is correct

**Comment by caisq** [comment]
@GodsDusk 

To help us diagnose this issue, can you provide the following information:
1. If you feed an all-zero input image to your model (tf.zeros([1, 224, 224, 3])), does the model output NaNs?
2. Can you get the weights of the model (`model.getWeights()`) to see if any of the weights of the model contains NaN or Infinity elements?
3. Can you serialize the content of your input batched.dataSync() and send it to us for inspection?

**Comment by GodsDusk** [comment]
@caisq 
Use `tf.zeros([1, 224, 224, 3])`  aslo output NaNs

then I extract subnetwork from mobilenet to find how it works.
```python
import tensorflowjs as tfjs
from tensorflow.keras.models import Model
from tensorflow.keras.applications.mobilenet import MobileNet

base_model = MobileNet(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('Conv1').output)
tfjs.converters.save_keras_model(model, 'model/')
```


I found this output values become very large and the next output layer 'bn_Conv1' has some 'inf' values.

**Conv1 outputs:**
![WX20191210-102414](https://user-images.githubusercontent.com/13726533/70489954-156ffa00-1b38-11ea-8fd1-d32d548ac81a.png)

**bn_Conv1 outputs:**
![WX20191210-104912](https://user-images.githubusercontent.com/13726533/70490953-c8d9ee00-1b3a-11ea-81aa-8d970d690110.png)

**Comment by caisq** [comment]
@GodsDusk These weight values definitely look problematic. I have no idea how it ends up being so. Can you check your cached model weight files? Perhaps clear it? I believe that are in the 'models' subfolder.

**Comment by GodsDusk** [comment]
@caisq 
do you mean those files named 'group1-shardXofX.bin' ? 
I clean up those files before convert everytime, it's not helpful.

**Comment by caisq** [comment]
@GodsDusk Hmm. This is getting confusing. There seems to be something peculiar about your set up. 

What version of Python TensorFlow are you using? 

Try doing everything from a clean virtualenv and a clean working directory.
Try another computer maybe?

**Comment by caisq** [comment]
Another possibility: There may be something incorrect about the HTTP server, which causes the bytes for the weight files to be garbled somehow.

**Comment by caisq** [comment]
At least we know now the root cause of your problem is the weights having very large and infinity values. The weights should all have reasonably small values (i.e., absolute values <= 5.0 approximately).

**Comment by caisq** [comment]
@GodsDusk Another thing you can check: Before the model conversion, in Python, call the model's `get_weights()` method to see if the weight values are already larger and infinity in Python.

**Comment by GodsDusk** [comment]
@caisq  
I use another computer and it works fine 
😅 
too ridiculous

Anyway, thank you so much
