### ISSUE TITLE
Support loss and sample weighting in Model.fit()

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#25]
Currently, loss and sample weighting are not supported by Model.fit() yet.

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!
