### ISSUE TITLE
Implement UpSampling2D layer

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#250]

**Comment by zaidalyafeai** [comment]
I am going to work on it ...

**Comment by caisq** [comment]
Thanks, @zaidalyafeai . Looking forward to the PR.

**Comment by caisq** [comment]
@zaidalyafeai I believe this PR may have fulfilled this feature request already?
https://github.com/tensorflow/tfjs-layers/pull/204

**Comment by zaidalyafeai** [comment]
@caisq, nice. I think this issue should be closed.

**Comment by caisq** [comment]
@zaidalyafeai OK. Thanks. Regarding the question about tfjs-core dependency, I think tfjs-layers is depending on a version recent enough to include 5D tensors. If not, then something must be amiss.
