### ISSUE TITLE
Is there a way to set per_process_gpu_memory_fraction tensorflow node gpu

### ISSUE THREAD

**Issue by julkar9** [tensorflow/tfjs#2503]
Is there a way to set `per_process_gpu_memory_fraction` tensorflow node gpu ?

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
