### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by AndreMaz** [tensorflow/tfjs#2505]
It would be great if there was a changelog to track the changes. For example, what changed from `v1.3.2` to  `v1.4.0`?

**Comment by rthadur** [comment]
@nsthorat is this doable ?

**Comment by nsthorat** [comment]
Apologies about this! I updated the script to work with the monorepo and now we have a changelog for 1.4.0:

https://github.com/tensorflow/tfjs/releases/tag/tfjs-v1.4.0

**Comment by AndreMaz** [comment]
Hey @nsthorat sorry to bother you again. What's new in `v1.5.1`? There is no changelog

**Comment by nsthorat** [comment]
Apologies, here are the latest release notes: https://github.com/tensorflow/tfjs/releases/tag/tfjs-v1.5.1

**Comment by AndreMaz** [comment]
@nsthorat can you add the changelog for `v1.5.2`?

**Comment by nsthorat** [comment]
Changelog is out!
