### ISSUE TITLE
Improve JavaScript error messages wherewe rely on TypeScript types.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#251]
This issue requires some investigation, but an example includes asserting the runtime inputs of ops are Tensors, which was fixed here: https://github.com/tensorflow/tfjs/issues/202

Another one (we relied on typings to catch this error at compile time) is here: https://github.com/tensorflow/tfjs/issues/241

**Comment by dsmilkov** [comment]
Closing in favor of a specific issues tracking error messages.
