### ISSUE TITLE
Unable to resolve module '@reactNative\\node_modules\\@tensorflow\\tfjs-react-native\\dist\\asyn_storage_io.js

### ISSUE THREAD

**Issue by azidmiracle** [tensorflow/tfjs#2515]
Hello everyone,

I have been trying to figure out and solve this problem I encountered for almost a week.
Try to search online for a solution but unable to solve it.
Here is the error.

![image](https://user-images.githubusercontent.com/45925710/70371074-3c94b480-1909-11ea-954a-1e9037004e60.png)

I am using Windows 7, android emulator

  "dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "@tensorflow/tfjs": "^1.4.0",
    "@tensorflow/tfjs-react-native": "^0.1.0-alpha.2",
    "expo": "^35.0.0",
    "expo-gl": "~7.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-web": "^0.11.7"
  },

After I installed the following dependencies, I got the above error.
   yarn add @tensorflow/tfjs
    yarn add @tensorflow/tfjs-react-native@alpha
    yarn add @react-native-community/async-storage
    # Expo wrapper for yarn install; Downloads expo dependencies that work with current version
    expo install expo-gl

Here is the code I copied 

import React, { Component } from "react";
import { Text, View } from "react-native";
import { AppLoading } from "expo";
import * as tf from "@tensorflow/tfjs";
import "@tensorflow/tfjs-react-native";

export default class App extends Component {
  state = {
    isTfReady: false,
  };
  prepApp = async () => await tf.ready();
  setAppReady = () => this.setState({ isTfReady: true });
  render() {
    if (!this.state.isTfReady) {
      return (
        <AppLoading
          startAsync={this.prepApp}
          onFinish={this.setAppReady}
          onError={console.warn}
        />
      );
    }
    return (
      <View>
        <Text>Placeholder</Text>
      </View>
    );
  }
}

Please help. Thank you in advance.

**Comment by tafsiri** [comment]
Hi. Did you complete the link step for @react-native-community/async-storage? Documented here on their [README](https://github.com/react-native-community/async-storage#link).

Also FYI @tensorflow/tfjs-react-native 0.1.0-alpha.3 is out so you should also update to that in your package.json.

Let me know if you have any problems after that (note that expo and react-native-fs also have linking/configuration steps that should be completed after installing via yarn.).

**Comment by tafsiri** [comment]
Closing due to lack of recent activity.

**Comment by mawrukh** [comment]
same issue
