### ISSUE TITLE
Revive or replace the benchmark tooling at @tensorflow/tfjs-core/integration_tests/benchmarks

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#253]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs-core 0.9.9

#### Describe the problem or feature request
benchmarks tool no longer works:
https://github.com/tensorflow/tfjs-core/blob/fae97fb30d3a86b8c868b7934b135705632442d2/integration_tests/benchmarks/README.md

**Comment by Lewuathe** [comment]
Is there any plan in progress to revive benchmark tools? If not, I would like to try to reuse existing benchmark tools. 
https://github.com/tensorflow/tfjs-core/tree/master/integration_tests/benchmarks
