### ISSUE TITLE
How to install last version of tfjs

### ISSUE THREAD

**Issue by federicolucca** [tensorflow/tfjs#2535]
Hi guys,
I need to work with the last version of tfjs,i have found some issues fixed in the last 14hours by you.
Es. https://github.com/tensorflow/tfjs/pull/2524
how can i do it? there is a solution or i need to compile from master source source

thanks
Federico

**Comment by kangyizhang** [comment]
hi @federicolucca 

To use the head of master version of @tensorflow/tfjs-core (which is not published to npm), you need to
1. clone the @tensorflow/tfjs repo
2. go to folder `tfjs-core`
3. run `yarn publish-local`, or `npm run publish-local` if you do not have yarn
4. go to your repo folder, run `yalc link @tensorflow/tfjs-core`

Please not you will need to install @tensorflow/tfjs separately to use tfjs-layers and tfjs-converter.
