### ISSUE TITLE
[Feature Request] Improve JSDocs

### ISSUE THREAD

**Issue by AndreMaz** [tensorflow/tfjs#2542]
#### TensorFlow.js version
`"@tensorflow/tfjs-node": "^1.4.0"` but it also happens with previous releases.

#### Describe the problem or feature request
Currently the declaration preview (hovering over a method) is not very informative.
For example, hovering over `dot` method I get the following info
![image](https://user-images.githubusercontent.com/9802754/70711924-94049d00-1cda-11ea-8643-25fa7ee82fe8.png)
Same happens with auto complete feature:
![image](https://user-images.githubusercontent.com/9802754/70712968-f3fc4300-1cdc-11ea-8199-4d93452d90e2.png)

Because of this, I constantly have to check the API available at https://js.tensorflow.org/api/latest/
Which is completely fine but having docs directly in my editor would be much better.

I've looked at actual `exports_layers.ts` file and the description of the `dot` method is declared there.
![image](https://user-images.githubusercontent.com/9802754/70712125-fcec1500-1cda-11ea-851c-2916ac5ca636.png)

The problem is that the description is declared in a separate blocks. So vscode ignores the `/** docs */` block and only shows the `/** @doc {} */`
```ts
/** docs */
/** @doc {heading: 'Layers', subheading: 'Merge', namespace: 'layers'} */
export declare function dot(args: DotLayerArgs): Layer;
```

Merging two blocks into one
```ts
/** docs 
  *   @doc {heading: 'Layers', subheading: 'Merge', namespace: 'layers'} */
export declare function dot(args: DotLayerArgs): Layer;
```
creates a much better experience as I have all the info directly in my code editor
![image](https://user-images.githubusercontent.com/9802754/70713654-60c40d00-1cde-11ea-851d-7535ff77b690.png)

Is this something that you can do?

**Comment by kangyizhang** [comment]
The separate jsdoc annotated with `@doc` is used for the API website. @tafsiri is it possible for us to merge the jsdocs?

**Comment by tafsiri** [comment]
@kangyizhang I agree this would be nice. Would need to look into how our parser would need to be changed to work with that change. I probably cant do that right now but will look into it when I get a chance.

**Comment by macstr1k3r** [comment]
In the meantime, an extremely crude but a very effective "solution" to the problem of JSDoc not showing correctly in vscode:

```bash
find node_modules/@tensorflow -iname *.d.ts | xargs sed -i '' 's~\/\*\*.*@doc.*$~~g'
```

PS
I have a feeling [this](https://github.com/microsoft/TypeScript/pull/32181/files) might be related

**Comment by ManishAradwad** [comment]
I'd like to work on this issue. Should I just go ahead and merge the jsdocs or modify the parser as well? If I need to modify the parser as well, could you plz point me in some direction?

**Comment by pyu10055** [comment]
@tafsiri can you provide pointer on the API doc parser code? thanks

**Comment by tafsiri** [comment]
Doc parse code lives here https://github.com/tensorflow/tfjs-website/tree/master/build-scripts/doc-gen. One would probably need to look at how the whole doc generation process works and try it with an example of the merged doc annotation to see if it just works or what the behaviour is.

**Comment by archie-swif** [comment]
Hi everyone!

I have merged all @doc blocks with jsdoc, tried to run doc-gen on updated code, and it works good!

**doc-gen**
I see that parser in doc-gen goes through all the comment blocks for @doc annotation. It does not matter if @doc is in it's own comment block or in jsdoc. I only get errors if @doc is moved to the first line of jsdoc.

**Testing**
jsons made by ```tfjs-website``` look fine, in diff there is a change in githubUrl line numbers, some json objects are shuffled around. Data from jsdoc is in the right places as before.

API Documentation htmls generated from updated code has little change if compared in diff. I see some items changed order in docs and table of contents. Line numbers changed in references to source code.
<img width="394" alt="segment-moved" src="https://user-images.githubusercontent.com/2158707/90060729-04b0ee80-dc9a-11ea-95d0-82cc60f580c0.png">

**How it looks**
<img width="1257" alt="Screen Shot 2020-08-11 at 23 26 53" src="https://user-images.githubusercontent.com/2158707/89989695-28dae400-dc36-11ea-89aa-4fc037721193.png">
**Issues**
In webstorm, @doc visibility is inconsistent in help popups - sometimes it's in body, on parames level, or not displayed. And there are some extra tailing ```s. Looks like an unrelated issue with ide/jsdoc.

**Comment by archie-swif** [comment]
Here's a PR for it: https://github.com/tensorflow/tfjs/pull/3780

**Comment by archie-swif** [comment]
Hey @tafsiri How's it going? 
Would be great to have your feedback on the fix!

**Comment by tafsiri** [comment]
Reviewed it and it looks great! Thanks for taking the time to do this!

**Comment by tafsiri** [comment]
this will be available in the next release.
