### ISSUE TITLE
[docs update] Creating a dictionary of named inputs to make predictions

### ISSUE THREAD

**Issue by set-killer** [tensorflow/tfjs#2545]
Hello guys,

On [this piece of the documentation](https://js.tensorflow.org/api/latest/#tf.LayersModel.summary) there is a nice example of how to create a model with different inputs and sizes. This is really cool. 
I've managed to create a model and train it with a dataset that takes every row and maps it to an object like:

```
const xs = {
  input1: arrayWith10Elements,
  input2: arrayWith20Elements
};
```

The problem is when i want to make a predictions i have to create a dictionary with tensors of different shapes to feed on the model. There is no a single point in the documentation which describes how to do that... I'm lost at this part...

An object like this is not working.
```
const xs = {
  input1: tf.ones([1, 10]),
  input2: tf.ones([1, 20])
};
```
Am i missing something from the documentation? How do i make a dictionary with tensors of different shapes and then feed it into the model to make predictions after that?

**Comment by tafsiri** [comment]
@set-killer If i understand your question correctly you want to pass in multiple inputs to a model that is set up to take multiple input tensors. 

It looks like the documentation for predict is missing the option to take a dictionary like the one you are passing above. However it should work at runtime, what error are you getting with `xs` like you have it above? Note that you would only use the dictionary format if your model has named inputs, and the names in the dictionary would need to match the names in the model definition.

An alternative is to use an array, both [model.fit](https://js.tensorflow.org/api/latest/#tf.LayersModel.fit) and [model.predict]((https://js.tensorflow.org/api/latest/#tf.LayersModel.predict)) take arrays of tensors for multi-input models.

cc @caisq I found two predict functions that might need an update to their docs, one in [models.ts](https://github.com/tensorflow/tfjs/blob/tfjs-layers-v1.3.1/tfjs-layers/src/models.ts#L773-L778) (linked from [here](https://js.tensorflow.org/api/latest/#tf.LayersModel.predict)) and the other in [training.ts](https://github.com/tensorflow/tfjs/blob/tfjs-layers-v1.3.1/tfjs-layers/src/engine/training.ts#L1100-L1115) linked from [here](https://js.tensorflow.org/api/latest/#tf.Sequential.predict). Is that what you would expect needs an update (also are both those links into the source correct?)

**Comment by set-killer** [comment]
Hello @tafsiri , 
Yes, that's correct. I'll try to simplify the example of that what i'm doing. Let's say that I'm having a dataset with 6 columns - 5 as input parameters and the last one is the label (ys - only one label). For the training i'm mapping the values of the dataset like:
```js
    .map(function(row){
      return {
        xs: {
          input1: [row[0], row[1], row[2]],
          input2: [row[3], row[4]],
        }, 
        ys:row[5]
      };
    })
```
And this is pretty cool because after that i'm using the `model.fitDataset` method which automatically converts the inputs (input1 and input2) to tensors and does the math after that. The problem comes after that when i try to make predictions with the trained model. When i try to do this:

```js
// all this wrapped in tf.tidy()
const xs = {
  input1: tf.ones([1, 3]),
  input2: tf.ones([1, 2])
};
const result = model.predict(xs);
```
I'm getting the following error:
`(node:8212) UnhandledPromiseRejectionWarning: Error: Error when checking model : the Array of Tensors that you are passing to your model is not the size the the model expected. Expected to see 2 Tensor(s), but instead got 0 Tensors(s).
`

When i'm defining the input layers i'm not setting the layers names expressly, but i'm making them like in the example of the `summary` method. In this situation the input layers should be named automatically like input1, input2, input3...


> An alternative is to use an array, both model.fit and model.predict take arrays of tensors for multi-input models.

Yes, the documentation also states that:
```
model.predict (x, args?)
 x (tf.Tensor|tf.Tensor[]) The input data, as an Tensor, or an Array of tf.Tensors if the model has multiple inputs. 
```
But Tensorflow does not allow to create a 2d array with different sizes of the rows.  For example if i try to run: `tf.tensor2d([[1, 2, 3], [4, 5]]).print()` there is an error... But you see - input1 and input2 are having different shapes.

**Comment by set-killer** [comment]
Hey guys, does anyone knows how to solve the puzzle? Thank you.

**Comment by set-killer** [comment]
Updated to the newest version and now it works.

`const result = model.predict(Object.values(xs));`
