### ISSUE TITLE
[webgpu] Devise heuristic for running im2col as separate shader.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#2553]
As a follow up to https://github.com/tensorflow/tfjs/pull/2208, let's figure out a heuristic for running im2col as a separate shader and then get rid of the environment flag. 

@qjia7 - maybe you have some initial insights here?

**Comment by pyu10055** [comment]
@qjia7 Can you verify if this issue can be closed? thanks

**Comment by qjia7** [comment]
After we supported the conv2d vec4 version, I think im2col is not that necessary for us now. Let's close it.
