### ISSUE TITLE
Implement op: Unpack

### ISSUE THREAD

**Issue by hmartiro** [tensorflow/tfjs#256]
Wanted to document an operation I'm missing for a 3D computer vision app: Unpack

Other missing ops:
 * StridedSlice (https://github.com/tensorflow/tfjs/issues/242)
 * BatchMatMul (https://github.com/tensorflow/tfjs/issues/255)
 * ClipByValue (very minor)

python package versions:
tensorflowjs==0.2.1, tensorflow==1.7.0

**Comment by dsmilkov** [comment]
Closing since all of these ops landed in the converter and core.
