### ISSUE TITLE
Error  import  tfjs-node-gpu 1.4.0 in window 10

### ISSUE THREAD

**Issue by blackwool** [tensorflow/tfjs#2561]
#### TensorFlow.js version
@tensorflow/tfjs@1.4.0
@tensorflow/tfjs-node@1.4.0
@tensorflow/tfjs-node-gpu@1.4.0

#### Browser version
None
#### Node Version
v13.3.0 (64bit) 
D:\nodejs>node -p "process.arch"
x64
#### OS
WIN10,  Python is not installed,
Geforce 940MX , CUDA 8.0
#### Describe the problem or feature request
D:\nodejs\test>node
Welcome to Node.js v13.3.0.
> const tf=require("@tensorflow/tfjs-node-gpu");

Thrown:
Error: The specified module could not be found.
\\?\D:\nodejs\node_modules\\@tensorflow\tfjs-node-gpu\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1197:18)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)****
-----------------------------------------------------------------------------------------------

#### FYI
 install is ok :
D:\nodejs>npm install @tensorflow/tfjs-node-gpu
D:\nodejs\npx -> D:\nodejs\node_modules\npm\bin\npx-cli.js
D:\nodejs\npm -> D:\nodejs\node_modules\npm\bin\npm-cli.js

> @tensorflow/tfjs-node-gpu@1.4.0 install D:\nodejs\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

GPU-windows-1.4.0.zip
* Downloading libtensorflow
[==============================] 1629503/bps 100% 0.0s
[==============================] 581462/bps 100% 0.0s
* Building TensorFlow Node.js bindings
+ @tensorflow/tfjs-node-gpu@1.4.0
added 519 packages from 906 contributors in 303.88s

**Comment by blackwool** [comment]
Append Information:

I  upgraded  CUDA to CUDA 9.2 and cudnn ->cudnn10 ,change envirment var below and restart computer .

CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
path=%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin
path=%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp
path=%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\extras\CUPTI\libx64
path=%PATH%;D:\cudnn\cudnn_10\bin

but it still throw error .

I find in   tfjs-node-gpu\dist\index.js: ( line 44)

    var bindings = require(bindingPath);

when execute  to this statement , node will throw the same error.
and at this time  ,

     bindingPath="D:\nodejs\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v5\tfjs_binding.node"

This file is exist using dir command :

D:\nodejs>dir D:\nodejs\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v5\tfjs_binding.node
2019/12/06  05:39           632,832 tfjs_binding.node

**Comment by kangyizhang** [comment]
hi @blackwool , 

1. does package @tensorflow/tfjs-node work for you?
2. tensorflow supports CUDA 10.0, you will need to install CUDA version 10.0 and cuDNN version >= 7.4.1 (https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md#installing)

**Comment by blackwool** [comment]
@kangyizhang 
  I Upfate  cuda to v10.0, then no error occurs.
Thank you.
