### ISSUE TITLE
BodyPix2 GPU version is not very faster than CPU

### ISSUE THREAD

**Issue by blackwool** [tensorflow/tfjs#2569]
#### TensorFlow.js version
@tensorflow/tfjs@1.4.0
@tensorflow/tfjs-node@1.4.0
@tensorflow/tfjs-node-gpu@1.4.0
#### Browser version
None
#### Node Version
v13.3.0 (64bit)

####OS
ThinkpadT460P (32G)
Geforce 940MX
WIN10
CUDA 10.0  CUDNN7.6.5

####BodyPix2 GPU version is not verf fast
I use mobilenet {outputStride: 16,    quantBytes: 2,    multiplier: 0.50 }  for test.
cpu mode:                                                      
     require("@tensorflow/tfjs-node")
     segmentMultiPerson:  0.6 fps
     segmentPerson         : 5.9 fps
gpu mode:
     require("@tensorflow/tfjs-node-gpu")
     segmentMultiPerson : 0.7  fps
     segmentPerson          :14.3 fps

mybe on the other muchine ,speed will be fast ,but  GPU mode is no very fast then CPU mode 
Is this right ? 
Or where should I change else ?

**Comment by sarathkrishna1729** [comment]
Please share the documentation for adding this version in html
