### ISSUE TITLE
Unsupported Ops in the model FakeQuantWithMinMaxVars

### ISSUE THREAD

**Issue by chenjin3** [tensorflow/tfjs#258]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs-converter v0.2.1

#### Describe the problem or feature request
Unsupported Ops in the model FakeQuantWithMinMaxVars error message appears when I'm try to convert a model with FakeQuantWithMinMaxVars  operation.

**Comment by pyu10055** [comment]
this is a model with quantization, are you trying to use a model generated by tflite?
can you share your command line, and possibly the model itself. thanks.

**Comment by chenjin3** [comment]
@pyu10055 No, it saved by tf.saved_model.builder. The model with quantization works well on tflite but on web. My command line are as follow:
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='output' \
    --saved_model_tags=test_saved_model \
    /8bit/saved_model \
    /8bit/web_model
```

**Comment by nsthorat** [comment]
This should work now.
