### ISSUE TITLE
tfjs with autoML on local model

### ISSUE THREAD

**Issue by ozican** [tensorflow/tfjs#2581]
Hello, I try to work that code last 2 months and I really big stucked. 
I trained my model on Google Vision and export for TFJS.. It says; you can use it TFSJ AutoML.

Anyway, I downloaded my model in to my local drive. I want to put an image https link then I want to get a predict.

I need to convert image to tensorflow3d but the point is, if I import TFJS-node or tfjs I get an error which is; `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

After my researchs, they say, do not import `tfjs` or `tfjs-node ` because `automl` already has it, but if I don't import it I can not convert to tensor3d.
If you help me for that, I will rep for nodejs example without HTML.. I beleieve this is very important for nodejs and automl because there is no any example for that.
Here is my latest code;

```
const automl = require('@tensorflow/tfjs-automl');
const modelUrl = 'model.json'; // URL to the model.json file.

const fs = require('fs');
const jpeg = require('jpeg-js');

const NUMBER_OF_CHANNELS = 3

const readImage = path => {
  const buf = fs.readFileSync(path)
  const pixels = jpeg.decode(buf, true)
  return pixels
}

const imageByteArray = (image, numChannels) => {
  const pixels = image.data
  const numPixels = image.width * image.height;
  const values = new Int32Array(numPixels * numChannels);

  for (let i = 0; i < numPixels; i++) {
    for (let channel = 0; channel < numChannels; ++channel) {
      values[i * numChannels + channel] = pixels[i * 4 + channel];
    }
  }

  return values
}

const imageToInput = (image, numChannels) => {
  const values = imageByteArray(image, numChannels)
  const outShape = [image.height, image.width, numChannels];
  const input = tf.tensor3d(values, outShape, 'int32');

  return input
}


const classify = async (path) => {
  const image = readImage(path)
  const input = imageToInput(image, NUMBER_OF_CHANNELS)

  const model = await auto.loadImageClassification('./model.json');
  const predictions = await model.classify(img, options);

  console.log('classification results:', predictions)
}

if (process.argv.length !== 3) throw new Error('incorrect arguments: node script.js <MODEL> <IMAGE_FILE>')

classify(process.argv[2])

```

**Comment by PaDuckk** [comment]
The model url that is passed as an argument to loadImageClassification of tfjs-automl only supports http and https protocols.

Using `loadGraphModel` of `tfjs-node` can solve the problem.

In addition, tf.decodeImage is added to tfjs-node so you no longer need `jpeg-js` and `canvas` to convert the image.

```js
const tf = require("@tensorflow/tfjs-node");
const automl = require("@tensorflow/tfjs-automl");
const fs = require("fs");

const loadDictionary = modelUrl => {
  const lastIndexOfSlash = modelUrl.lastIndexOf("/");
  const prefixUrl =
    lastIndexOfSlash >= 0 ? modelUrl.slice(0, lastIndexOfSlash + 1) : "";
  const dictUrl = `${prefixUrl}dict.txt`;
  const text = fs.readFileSync(dictUrl, { encoding: "utf-8" });
  return text.trim().split("\n");
};

const loadImageClassification = async modelUrl => {
  const [model, dict] = await Promise.all([
    tf.loadGraphModel(`file://${modelUrl}`),
    loadDictionary(modelUrl)
  ]);
  return new automl.ImageClassificationModel(model, dict);
};

const decodeImage = imgPath => {
  const imgSrc = fs.readFileSync(imgPath);
  const arrByte = Uint8Array.from(Buffer.from(imgSrc));
  return tf.node.decodeImage(arrByte);
};

const main = async () => {
  const modelURL = "local/model/path/model.json";
  const model = await loadImageClassification(modelURL);
  const decodedImage = decodeImage("local/image/path/example.png");

  return await model.classify(decodedImage);
};

main()
  .then(console.log)
  .catch(console.log);

```

**Comment by kangyizhang** [comment]
to use the model in node, you only need to import `@tensorflow/tfjs-node`, like the code snippet @PaDuckk provided. 

The message `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA` is a warning instead of an error, it will not block you from anything.

**Comment by aayusharora** [comment]
Thanks @PaDuckk 
That worked for me :)

**Comment by arolihas** [comment]
I am trying to use the code above but tf.loadGraphModel is not working on the model.json.

Unhandled Rejection (TypeError): Failed to fetch
HTTPRequest.fetch
src/platforms/platform_browser.ts:28
  25 | encode(text, encoding) {
  26 |     if (encoding !== 'utf-8' && encoding !== 'utf8') {
  27 |         throw new Error(`Browser's encoder only supports utf-8, but got ${encoding}`);
> 28 |     }
     | ^  29 |     if (this.textEncoder == null) {
  30 |         this.textEncoder = new TextEncoder();
  31 |     }
View compiled
HTTPRequest.load
src/io/http.ts:146
  143 | let weightData;
  144 | if (weightsManifest != null) {
  145 |     const results = await this.loadWeights(weightsManifest);
> 146 |     [weightSpecs, weightData] = results;
      | ^  147 | }
  148 | return {
  149 |     modelTopology,
View compiled
GraphModel.load
src/executor/graph_model.ts:117
  114 | /**
  115 |  * Save the configuration and/or weights of the GraphModel.
  116 |  *
> 117 |  * An `IOHandler` is an object that has a `save` method of the proper
      | ^  118 |  * signature defined. The `save` method manages the storing or
  119 |  * transmission of serialized data ("artifacts") that represent the
  120 |  * model's topology and weights onto or via a specific medium, such as
View compiled
Module.loadGraphModel
src/executor/graph_model.ts:381
ImageClassificationDemo.loadImageClassification
src/ImageClassificationDemo.js:9
