### ISSUE TITLE
[tfjs-converter/python] Relax requirements

### ISSUE THREAD

**Issue by gsakkis** [tensorflow/tfjs#2582]
It would be nice if some requirements weren't pinned to exact versions e.g. numpy and h5py, so they can be more easily installed.

**Comment by DLumi** [comment]
@pyu10055 @oanush 
The closest issue I could find. Maybe should've opened a fresh one. But still.

So it's basically impossible to install TFJS >3.19.0, <4.0.0 on a Python 11 Windows 10 machine. (no WSL, no GPU)
When you try, you get a protobuf dependency error. The versions are not that far apart, maybe relax the requirements a bit?
Here's the error message:
```
ERROR: Cannot install tensorflow-intel==2.12.0 and tensorflowjs==3.21.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflowjs 3.21.0 depends on protobuf<3.20 and >=3.9.2
    tensorflow-intel 2.12.0 depends on protobuf!=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.20.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

P.S. cannot install TFJS >=4.0 as it requires tensorflow-decision-forests package which is non-existent for non-WSL machines.
