### ISSUE TITLE
Version instruction conflict( AVX tfjs restrict non-AVX CPU from running)

### ISSUE THREAD

**Issue by JMRwork** [tensorflow/tfjs#2599]
what is the latest  version of tensorflowjs/tfjs-node that able no AVX support CPU's to run without 'Illegal instruction error'.
A version that is not AVX support specific. Seens that these versions are restricting non-AVX support to workout.

**Comment by kangyizhang** [comment]
@JMRwork it would be tfjs-node v1.2.1 and prior. AVX support was introduced by tensorflow C library v1.14.0 and be introduced to tfjs-node at https://github.com/tensorflow/tfjs-node/pull/261. So tfjs-node published before this PR has no AVX support.
