### ISSUE TITLE
tfjs-node-gpu can  not set size of gpu memory to be used 

### ISSUE THREAD

**Issue by blackwool** [tensorflow/tfjs#2611]
TensorFlow.js version

@tensorflow/tfjs@1.4.0
@tensorflow/tfjs-node@1.4.0
@tensorflow/tfjs-node-gpu@1.4.0

Browser version
None

Node Version

v13.3.0 (64bit)

####OS
WIN10
CUDA 10.0 CUDNN7.6.5

####How to set size of gpu memory to be used ?
For example BodyPix2:
When i use tfjs-node-gpu on Geforce 940MX,  it uses about 1.6G gpu memory,
but wehn i use it on 1060 , it uses 5.2G gpu memory.
Where can i set the gpu memory size to be used by tfjs-node-gpu ?
or will you plan to add this api in the future ?
thank you .

**Comment by rthadur** [comment]
I guess it is not possible to set up GPU memory, @kangyizhang any thoughts on implementing this in near future ?

**Comment by kangyizhang** [comment]
It is not possible to set up GPU memory usage fraction not, and no plan to support it in short future. If you have a use case, please feel free to reopen this ticket with more details.

**Comment by danwexler** [comment]
Does setting the  environment variable, as discussed in [Limiting Memory Usage ](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) help? Unfortunately, the [set_logical_device_configuration](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration) does not have a corresponding env var, which would truly allow you to limit the max mem.

**Comment by H-s-O** [comment]
@kangyizhang Without getting into details, I'm working on an an Electron app where we need to run the PoseNet model but also other models as well with OpenCV via a native addon. We are currently limited currently because PoseNet on tfjs-node-gpu eats all available VRAM when starting inference and there's no VRAM left for any other models.
