### ISSUE TITLE
Unknown op ‘FusedDepthwiseConv2dNative’.

### ISSUE THREAD

**Issue by tomerip** [tensorflow/tfjs#2614]
#### TensorFlow.js version
1.3.1 and 1.5.1

#### Browser version
Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

#### Describe the problem or feature request
Converted part of MobilenetV3 from tf-slim using tfjs-converter (1.4.0 and 1.5.1), conversion is successful and shows no warnings or errors, but when I try to run the model in tfjs (1.3.1 and 1.5.1), I get an error "Unknown op ‘FusedDepthwiseConv2dNative’."
I managed to get around the issue by downgrading tfjs-converter to 1.3.2 and then it worked.

#### Code to reproduce the bug / link to feature request
```
def wrap_frozen_graph(graph_def, inputs, outputs):
    def _imports_graph_def():
        tf.compat.v1.import_graph_def(graph_def, name='')
    wrapped_import = tf.compat.v1.wrap_function(_imports_graph_def, [])
    import_graph = wrapped_import.graph
    return wrapped_import.prune(
                      tf.nest.map_structure(import_graph.as_graph_element, inputs),
                      tf.nest.map_structure(import_graph.as_graph_element, outputs)
                )

graph_def = tf.compat.v1.GraphDef()
loaded = graph_def.ParseFromString(open(pb_path, 'rb').read())
# pb_path is the frozen model .pb from tf-slim

bottleneck_model = wrap_frozen_graph(graph_def, inputs='input:0', outputs='MobilenetV3/expanded_conv_10/output:0')
```

**Comment by nsthorat** [comment]
If you upgrade everything to 1.5.1 (python converter and javascript) you shouldn't see this error anymore. Let me know if that helps.

**Comment by tomerip** [comment]
After completely uninstalling tfjs and installing version 1.5.1 now it works.
Thanks!
