### ISSUE TITLE
Unsupported Ops in the model before optimization, MirrorPad, InvertPermutation

### ISSUE THREAD

**Issue by startupgurukul** [tensorflow/tfjs#2615]
Hello Folks, 
Trying to convert a frozen pb file to tf.js format but hit couple of Unsupported Ops.

ValueError: Unsupported Ops in the model before optimization, MirrorPad, InvertPermutation

There seem to be an issue tracking MirrorPad https://github.com/tensorflow/tfjs/issues/1775

Currently attempting to create a customOp, creating this issue for the implementation 

Interestingly across whole of github, no one implemented a customOp when looking for an example https://github.com/search?q=%22tf.registerOp%22&type=Code

**Comment by thesiti92** [comment]
did you ever make a custom operation for it? would be much appreciated!
