### ISSUE TITLE
Version consitency

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tfjs#2622]
Hello, since I used the older tensorflow version of 1.12 and keras version of 2.2.4.

I want to avoid the problem of version consitency.

How can I determine which tensorflowjs version I should use.

Thanks

**Comment by kangyizhang** [comment]
TensorFlow.js should not have version conflict with model trained in older tensorflow or keras, so feel free to use the latest version. If you see any issue, please file another issue with details information.
