### ISSUE TITLE
tf.time() kernelMs returns zero in Firefox

### ISSUE THREAD

**Issue by MatPoliquin** [tensorflow/tfjs#2624]
TensorFlow.js 1.3.1
FireFox 71.0 (64-bit)
Chrome 79.0.3945.88 (64-bit)
Ubuntu 19.10 (64-bit)

Problem:
**tf.time().kernelMs** returns 0 (or sometimes a very low number) on Firefox while always returning the correct timing on Chrome.

The correct value is typicaly between 100-300 ms, depending on which gpu you have.

Code:

> const matSize = 1024;
> const mat1 = tf.ones([matSize, matSize], tf.float32);
> const mat2 = tf.ones([matSize, matSize], tf.float32);
> const time = await tf.time(() => tf.matMul(mat1, mat2));

    
Edit:
I got the same problem with Edge and Android Chrome

**Comment by rthadur** [comment]
@annxingyuan seems to be a bug I was able to reproduce the bug in firefox  , please check 

repro code: `const matSize = 1024;
const mat1 = tf.ones([matSize, matSize], tf.float32);
const mat2 = tf.ones([matSize, matSize], tf.float32);
const time1 = await tf.time(() => tf.matMul(mat1, mat2));
console.log(`kernelMs: ${time1.kernelMs}, wallTimeMs: ${time1.wallMs}`);`

**Comment by annxingyuan** [comment]
I think the reason `kernelMs` is inaccurate in Firefox is that Firefox doesn't support WebGL query timers. In this case we just snapshot `performance.now()` before and after calling the WebGL draw command for that kernel and report `kernelMs` as the difference.

@dsmilkov @nsthorat - do you think it makes sense to omit `kernelMs` from `tf.time` output if query timers are unavailable?

**Comment by dsmilkov** [comment]
Instead of omitting (which is basically silencing the error), how about we throw an error with a user-friendly msg? Specifically the webgl's backend.time() should throw an error if the query timer is not supported, and that error should propagate through tf.time. WDYT?

**Comment by nsthorat** [comment]
@annxingyuan we actually should use a CPU timer if it's not enabled today. I think it makes to disambiguate and have the error propagate through the tf.time() call.

**Comment by annxingyuan** [comment]
@dsmilkov @nsthorat 

We do use a CPU timer if query timers are not enabled - but the CPU timer just reports the time elapsed before and after calling WebGL draw (which will always be close to 0). 

I feel like `tf.time()` shouldn't throw an error if query timers are not enabled because `tf.time()` also returns `wallMs`, which is valuable regardless of whether query timers are enabled. I think it makes sense for `tf.time()` to adapt its return signature depending on the device's capabilities. What do you think?

**Comment by nsthorat** [comment]
Ah okay, I think that makes sense. Something like gpuKernelMs?

**Comment by annxingyuan** [comment]
@nsthorat I think `kernelMs` makes sense for the name because it could be meaningful for the CPU backend. How about just not returning `kernelMs` as part of `tf.time` if the user is on the WebGL backend and the query timer extension is unavailable?

**Comment by dsmilkov** [comment]
Talked to Nikhil. We decided that we shouldn't silently ignore (omit information) b/c that is not helpful to the user. E.g. if I'm using firefox + webgl and call tf.time, I want to understand why I can't measure the kernel time.

Here is the proposal. `kernelMs` maps to:
- if everything works, a number
- if we can't measure:
```ts
{error: 'WebGL query timers are not supported in this environment'}
```

**Comment by annxingyuan** [comment]
OK - sounds good.
