### ISSUE TITLE
tfjs-node: zsh: illegal hardware instruction (core dumped) 

### ISSUE THREAD

**Issue by vvmspace** [tensorflow/tfjs#2631]
```
import '@tensorflow/tfjs-node';
```

I'm getting:
```
illegal hardware instruction (core dumped)
```

Ubuntu 18.10

**Comment by kangyizhang** [comment]
@vvmspace 
1. can you provide details of the cpu/gpu you are using? 
2. which version of tfjs-node are you using?
3. can you provide your node version

**Comment by nd2014-public** [comment]
Same problem.

CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
No GPU (CUDA)

tfjs-node : 1.5.1

Node : 12.14.0

(I had same problem with NodeJS latest (13.x))

**Comment by kangyizhang** [comment]
Can you run `cat /proc/cpuinfo` and paste the result here? most likely it's because your CPU does not support some instructions used by libtensorflow, such as AVX. And you will need to use an old version of the library.

**Comment by nd2014-public** [comment]
`processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 798.934
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: monitor spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 810.327
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: monitor spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 826.151
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: monitor spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 838.419
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: monitor spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
`

**Comment by nd2014-public** [comment]
It seems it comes from AVX-less CPU model ... I tried old versions, but maybe not old-enough ;)

Could you tell me which version is pre-built without AVX instructions ?

**Comment by kangyizhang** [comment]
@nd2014-public your CPU does not support AVX. 

You can either try `@tensorflow/tfjs-node` version 1.2.4 and prior, 

or build the libtensorflow from source on your machine (here is the instruction). Once you have libtensorflow built, replace what's inside `node_modules/@tensorflow/tfjs-node/deps/lib` and run `npm run build-addon-from-source` in side `node_modules/@tensorflow/tfjs-node`

**Comment by nd2014-public** [comment]
I tried to rebuild it from sources, but I had a TypeScript error : 

```
src/index.ts:42:14 - error TS2742: The inferred type of 'io' cannot be named without a reference to '@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader'. This is likely not portable. A type annotation is necessary.

42 export const io = {
                ~~


Found 7 errors.
```

**Comment by nd2014-public** [comment]
Version 1.2.4 does core dumped too

Version 1.2.2 seems to work, but I have to tune my source code ;) 

Thanks @kangyizhang !

**Comment by qwertangel** [comment]
can we have support for avx less cpu ? reverting to old version is not working for me since there are other dependencies which break with old version.

**Comment by SpeedyCraftah** [comment]
Same problem, tried every single version, but at the end i always got "Illegal instruction" and I need those bindings for local model save/load to work

**Comment by SithMasterBDSM** [comment]
+1

**Comment by sngrl** [comment]
The same problem.
I see that it's regular situation on virtual private servers (KVM virtualization) when CPU does not support needable instructions, as like AVX.
How we can use last version of the TensorFlow on this "cutted" CPUs?

**Comment by TricolorHen061** [comment]
> @nd2014-public your CPU does not support AVX.
> 
> You can either try `@tensorflow/tfjs-node` version 1.2.4 and prior,
> 
> or build the libtensorflow from source on your machine (here is the instruction). Once you have libtensorflow built, replace what's inside `node_modules/@tensorflow/tfjs-node/deps/lib` and run `npm run build-addon-from-source` in side `node_modules/@tensorflow/tfjs-node`

Can you please tell us what to replace it with? Replace it with the contents of what folder?

**Comment by zhuyifang** [comment]
+1
