### ISSUE TITLE
Memory Leak in toPixels()

### ISSUE THREAD

**Issue by meiamsome** [tensorflow/tfjs#264]
#### TensorFlow.js version
0.10.0

#### Browser version
Firefox 59.0.2
Chrome 66.0.3359.139

#### Describe the problem or feature request
When using the `toPixels()` function, two extra tensors are created and are not cleaned up

#### Code to reproduce the bug / link to feature request
The following code outputs '0 0 2' to the console of a browser when ran.
```html
<!DOCTYPE html>
<html>
<body>
  <canvas id='test' width='400' height='400' />
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.10.0"></script>
  <script>
  let fn = (async () => {
    let canvas = document.getElementById('test');
    let count1 = tf.memory().numTensors;
    let tensor = tf.fromPixels(canvas);
    tensor.dispose();
    let count2 = tf.memory().numTensors;
    tensor = tf.fromPixels(canvas);
    await tf.toPixels(tensor, canvas);
    tensor.dispose();
    let count3 = tf.memory().numTensors;
    console.log(count1, count2, count3);
  })();
  </script>
</body>
</html>
```

**Comment by nikudyshko** [comment]
Looks like memory leaks occur in tfjs-core/src/ops/array_ops.ts at lines 637-638: 
```
    const min = (await img.min().data())[0];
    const max = (await img.max().data())[0]; 
```

**Comment by leoarc** [comment]
I am still facing  this issue . One extra tensor is being assigned in ``` tf.browser.toPixels() ``` which I am not able to dispose . Is this issue solved ?

**Comment by AbdulRashidReshamwala** [comment]
This issue can be solved by 
```
tf.engine().startScope()
tf.browser.toPixel()
tf.engine().endScope()
```
tested on version 1.7.0

**Comment by ljazzy** [comment]
extra tensor not disposed in tf.browser.toPixels(), v. 4.22.0
