### ISSUE TITLE
Poor numerical precision on Chrome/Android

### ISSUE THREAD

**Issue by pontusbostrom** [tensorflow/tfjs#265]
#### TensorFlow.js version
0.10.0
#### Browser version
Chrome 66.0.3359.126 on Android 8.1.0

tf.ENV.features:
{DEBUG: false, WEBGL_VERSION: 2, WEBGL_GET_BUFFER_SUB_DATA_ASYNC_EXTENSION_ENABLED: false, BACKEND: "webgl", WEBGL_FLOAT_TEXTURE_ENABLED: true}

#### Describe the problem or feature request

The precision of floating-point calculations seems to be really poor in Chrome on Android. Examples:

tf.scalar(3.3).square().print()
Result: 10.8828125
Should be: 10.89 

tf.scalar(2.4).square().print()
Result: 5.75390625
Should be: 5.76

tf.scalar(1.1).square().print()
Result: 1.208984375 
Should: 1.21

Doing the same calculations for the same application on desktop Chrome produces accurate results. In my application this affects e.g. training, the obtained accuracy is much worse on mobile than on desktop.

#### Code to reproduce the bug / link to feature request

Run the commands above in the console when Tensorflow.js has been loaded.

**Comment by nsthorat** [comment]
Now we support float16 so this should at least have a little higher precision.
