### ISSUE TITLE
How to use tflite directly in tfjs? 

### ISSUE THREAD

**Issue by bernardoespinosa** [tensorflow/tfjs#2650]
#### TensorFlow.js version

1.5.0

#### Browser version

All browser

#### Describe the problem or feature request

In Tensorflow examples, they provide smart reply working version for Android and iOS. Here you can download `tflite` model file https://storage.googleapis.com/download.tensorflow.org/models/tflite/smartreply_1.0_2017_11_01.zip.

But i'm trying to implement the concept in web. Let me know the easy implementation process to achieve smart reply in web.

#### Code to reproduce the bug / link to feature request

For more details about smart reply, please refer below links.
- https://www.tensorflow.org/lite/models/smart_reply/overview
- https://github.com/tensorflow/examples/tree/master/lite/examples/smart_reply

**Comment by rthadur** [comment]
Similar issue has been opened and answere [here](https://github.com/tensorflow/tfjs/issues/991) , please check. Right now there is no support for this.

**Comment by bernardoespinosa** [comment]
@rthadur Thank you.
