### ISSUE TITLE
Overriding ReLU gradients using gradient registry

### ISSUE THREAD

**Issue by ludwigschubert** [tensorflow/tfjs#2659]
#### TensorFlow.js version
1.5.0

#### Describe the problem or feature request
I'm attempting to override the gradient computation of certain Ops, say ReLUs, in a loaded `GraphModel`. The [gradient registry](https://github.com/tensorflow/tfjs/pull/2584) seems like the right place, but currently `tf.getKernelsForBackend` doesn't seem to return a ReLU kernel. It seems like [most core Ops currently don't yet use the gradient registry](https://github.com/tensorflow/tfjs/blob/2d9abb3ef1bdc6c767b2ddb8a2160388acc3af2e/tfjs-core/src/ops/relu_ops.ts#L51).

Does my description here seem correct? Is there currently already a different way to override Op gradients of loaded models? If not, could and should I try porting the specific ops I'd like to be able to override to the new kernel and gradient registry system? 

Thank you for all your work on TFJS!

**Comment by rthadur** [comment]
@ludwigschubert thank you , can you please provide your use case.

**Comment by ludwigschubert** [comment]
Hm, my use case? LMK if I misunderstand your question! 

I'm looking to implement various techniques from the explainability and interpretability literature, which often use TF's Graph's `gradient_override_map` ([example 1](https://github.com/cydonia999/Grad-CAM-in-TensorFlow/blob/master/grad-cam-tf.py#L14), [example 2](https://github.com/tensorflow/lucid/blob/master/lucid/optvis/overrides/redirected_relu_grad.py#L40))

**Comment by tafsiri** [comment]
Hi Ludwig, you are correct, not much is currently using the gradient registry (or even kernel registry). We've been doing some of the groundwork for using a registry approach for kernels, gradients etc. We are going to be doing a bunch more work in this direction this quarter (so there will be quite a few changes there soon).

All new ops will use the registry approach and old ones will be ported to use it. So PRs that do that will be welcome, but there will be some more moving parts there. Is it a lot of ops you need?

**Comment by ludwigschubert** [comment]
Exciting to hear! I mainly need `ReLU` and `MaxPool` atm. I'm experimenting on a fork right now to see if I can port those two ops to use the registry. I'm not sure I'll know enough about the inner workings of TFJS to make it PR-ready, but I'll try. If there's a commit/PR/branch that ports an existing op, I'd be glad about any pointers. (But no pressure, I'll explore on my own, too. :D)

Thanks for giving me extra context! :-)

**Comment by rthadur** [comment]
@ludwigschubert can we close this issue ?
