### ISSUE TITLE
tf.loadModel not working in react native

### ISSUE THREAD

**Issue by tangtai** [tensorflow/tfjs#266]
#### TensorFlow.js version
0.10.3
#### Browser version
react-native 0.55.3
#### Problem:
tf.loadModel not working for local folder and remo url in react native, load local model not working for React
#### Feature request:  
tf.loadModel react-native support
#### Code to reproduce the bug / link to feature request
```
const path = 'https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json';
const localPath = './tfjsmodel/model.json';

  async loadmodel(p) {
    const model = await this.loadHostedPretrainedModel(p);
    console.log(model);
  }

  async loadHostedPretrainedModel(p) {
    try {
      const model = await tf.loadModel(p);
      return model;
    } catch (err) {
      console.error(err);
    }
  }

```
this is the demo app i created for running tfjs in react-native, it can train and predict model locally,
if you are interested this is the repo:  [https://github.com/tangtai/tfjsdemo](url)

<img src="https://user-images.githubusercontent.com/29759753/39657143-01f30aa8-4fba-11e8-80fa-143aa2d230d9.PNG" width="250" >

error i get when try to load model from url, i tried the code on react as well it returns the model successfully:
<img src="https://user-images.githubusercontent.com/29759753/39657258-1bbc6b68-4fbb-11e8-89da-13d5110dfa85.PNG" width="250" >

error i get when try to load model from local folder, for React it returns pending Promise : 
<img src="https://user-images.githubusercontent.com/29759753/39657212-bac063be-4fba-11e8-99bd-2b18ee8a870d.PNG" width="250" >

the model i got from tensorflowjs file convertor:
![screen shot 2018-05-04 at 4 59 55 pm](https://user-images.githubusercontent.com/29759753/39657439-b1d1af86-4fbc-11e8-9898-fd8b9a3e8ab0.png)

**Comment by timotheebernard** [comment]
Hi @tangtai, I'm not really familiar with React but I think you need to find a way to serve your model with a http server, moreover, it must allow CORS requests. 

Is there a way to do this within the React ecosystem? Otherwise, I described a solution in a similar issue: #257.

**Comment by tangtai** [comment]
@timotheebernard  thanks for your response, i tried to host the model on AWS s3 bucket and turn on CORS request it worked for React(web app), but didn't work for react native(mobile app), apparently according to https://facebook.github.io/react-native/docs/network.html native apps have not concept of CORS. 

how ever i can only fetch the json file from AWS and it returns the model configuration for me:
<img width="658" alt="screen shot 2018-05-07 at 12 24 40 pm" src="https://user-images.githubusercontent.com/29759753/39720577-ab30b4ba-51f1-11e8-8603-669a52abd685.png">

I'm wondering if we can somehow bypass the CORS issue and turn the model.json file into a tf.Sequential model we can use in our native app that would be great! 

as i was trying to figure out what tf.loadModel does, i think here is what it uses the model.json file to configure the model https://github.com/tensorflow/tfjs-layers/blob/72d82c90619c449548c5e881c64fcc5a299c5cfc/src/models.ts#L200 but im not 100% sure.

and i also tried tfjs examples on chrome on my phone, the model still works offline, once the model is loaded.

**Comment by pyu10055** [comment]
@tangtai does React native support loading file locally? If so, this would be similar to node.js env, we can provide API to load the model and weights from local file system instead of urls.

**Comment by tangtai** [comment]
hi @pyu10055 , react native can definitely load local json files, as for other files that created by the tensorflowjs converter i am not so sure, since they don't have a file format.  I'm wondering how exactly does the loadModel function turns the json file into a tf.Sequential(). Even if the model is loaded from url other than CORS, if tf.Sequential() is a javascript object, i think react native will be able to store the object locally in async Storage, and use the model offline.

**Comment by pyu10055** [comment]
Adding @caisq to this conversation. That could be a better route, we should move to a more generic loading API, sitting on top of the new serialization mechanism, which allows you to create io handler to store and load models for different storages.

**Comment by caisq** [comment]
`tf.loadModel()` works by
1. making a request to the specified `model.json` path. In the JSON response, there is a field called `weightsManifest`, containing a number of relative paths.
2. requesting binary weight values from the relative paths.

So he server that serves `model.json` must be able to work with relative path. This is the case for Google Cloud Storage, as many of our example and demo models are hosted there. Isn't this also the case for AWS S3 buckets work with relative paths too? It has been a while since I last used S3.

**Comment by tangtai** [comment]
@caisq for AWS s3 buckets you can enable CORS sharing, but it is a web thing, react native can't not do it while React can.

**Comment by tangtai** [comment]
@caisq I’m using react-native which is a JavaScript platform for mobile deve

**Comment by caisq** [comment]
@tangtai Actually,  tf.loadModel in version 0.10.3 of tfjs doesn't actually call `FileReader.readAsArrayBuffer` directory. It should call only `fetch`. Is the call from your own code?

**Comment by tangtai** [comment]
the version of tfjs Im using is @ version 0.10.3.

**Comment by Ivikassingh** [comment]
you can try webpack to import the cdn of tensorflowjs in Reactnative

**Comment by pyankoff** [comment]
Managed to make it work by using a custom loader:
```
const loader = {
  load: async () => {
    return {
      modelTopology: topology,
      weightSpecs: specs
      weightData: data,
    };
  }
}

const model = await tf.loadLayersModel(loader)
```

**Comment by prasadkawthekar** [comment]
@tangtai could you please share the code you used to load a tf.loadLayersModel from AWS s3 bucket on React webapp? Thanks!

**Comment by tafsiri** [comment]
We just released a package for this! https://www.npmjs.com/package/@tensorflow/tfjs-react-native try it out and feel free to re-open this issues if you have trouble with it.

**Comment by coucoseth** [comment]
@tafsiri tf.loadModal("url) is still not functioning

**Comment by SobanQureshi** [comment]
> const loader = {
>   load: async () => {
>     return {
>       modelTopology: topology,
>       weightSpecs: specs
>       weightData: data,
>     };
>   }
> }
> 
> const model = await tf.loadLayersModel(loader)

where is json and bin file in this custom loader
