### ISSUE TITLE
[webgpu] Enable test for fusedConv2D

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#2660]
The setup_test for fusedConv2D is incorrect(https://github.com/tensorflow/tfjs/pull/2448/files#diff-b8ad73e5d7aa8806baa3909ff26ab879R185), it should be as follows:
```
  {
    include: 'fused conv2d',
    excludes: [ ]
  },
```
The original feature request is here: https://github.com/tensorflow/tfjs/issues/2362

**Comment by axinging** [comment]
This issue is introduced by my previous PR(https://github.com/tensorflow/tfjs/pull/2448), I will work on this soon.

**Comment by rthadur** [comment]
@axinging thank you for working on this , do you need any help from our team ?

**Comment by axinging** [comment]
@rthadur, thanks, I have a draft fix for this, will submit it soon.
