### ISSUE TITLE
conv2d useBias not actually false by default

### ISSUE THREAD

**Issue by kylemcdonald** [tensorflow/tfjs#267]
The documentation for [tf.layers.conv2d](https://js.tensorflow.org/api/latest/index.html#layers.conv2d) says: "useBias (boolean) Whether the layer uses a bias vector. Defaults to false. Optional".

But testing with code says otherwise:

```js
m = tf.sequential();
m.add(tf.layers.conv2d({inputShape:[28,28,1], filters:16, kernelSize:4}));
console.log(m.layers[0].weights);
```

Prints a list with two elements. Adding `useBias:false` and it prints a list with one element.

The documentation also says "filters (number) The dimensionality of the output space (i.e. the number of filters in the convolution). Optional" but as far as I can tell, the number of filters is not optional:

```js
m = tf.sequential();
m.add(tf.layers.conv2d({inputShape:[28,28,1], kernelSize:4}));
```

Prints:

```
tfjs@0.10.0:1 Uncaught Error: Constructing tensor of shape (NaN) should match the length of values (0)
    at Object.a [as assert] (tfjs@0.10.0:1)
    at new e (tfjs@0.10.0:1)
    at Function.e.make (tfjs@0.10.0:1)
    at e.toTensor (tfjs@0.10.0:1)
    at e.truncatedNormal (tfjs@0.10.0:1)
    at tfjs@0.10.0:1
    at Object.e.tidy (tfjs@0.10.0:1)
    at Object.n.value [as truncatedNormal] (tfjs@0.10.0:1)
    at Object.C [as truncatedNormal] (tfjs@0.10.0:1)
    at t.apply (tfjs@0.10.0:1)
```

**Comment by dsmilkov** [comment]
Thanks Kyle. Cc @caisq @bileschi @ericdnielsen for tf.layers

**Comment by MengShaoying** [comment]
So , file [this.useBias = config.useBias == null ? true : config.useBias;](https://github.com/tensorflow/tfjs-layers/blob/v0.5.0/src/layers/convolutional.ts)
"this.useBias = config.useBias == null ? true : config.useBias;" should be changed to "this.useBias = config.useBias == null ? false : config.useBias;"?????

**Comment by caisq** [comment]
@kylemcdonald Thanks for reporting these issues.
@MengShaoying This is a documentation bug. `useBias` should default to `true` (like in Python Keras).
`filters` is not optional. I'll send a PR to fix these soon.
