### ISSUE TITLE
[Feature Request] Correlation/Stats Module

### ISSUE THREAD

**Issue by robertherber** [tensorflow/tfjs#2671]
#### TensorFlow.js version
1.5.0

#### Describe the problem or feature request
I'd like to be able to use the Stats module (and specifically [Pearson Correlation](https://www.tensorflow.org/probability/api_docs/python/tfp/stats/correlation)) that are available in the Python library.

**Comment by gaikwadrahul8** [comment]
Hi, @robertherber 

Apologize for the delayed response and It seems like we haven't implemented this feature as of now so May I know are you still looking for this feature now in TFJs ? 

If someone wants to contribute to this feature, you're always welcome please feel free to do it and refer this [link](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md). Thank you!
