### ISSUE TITLE
[WASM] `tfjs-backend-wasm` seems to request wasm file from the wrong location

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#2683]
I tried running the simple demo example in the `tfjs-backend-wasm` readme just now:
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm"></script>

<script>
  (async function() {
    await tf.setBackend('wasm');
    ...
  })();
</script>
```
But I get a 404 for the `wasm` file that the script tries to request:

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm.wasm

I think it should instead be:

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tfjs-backend-wasm.wasm

because that returns the wasm file, and this code does work:

```js
...
await tf.wasm.setWasmPath("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tfjs-backend-wasm.wasm");
await tf.setBackend('wasm');
...
```

**Comment by rthadur** [comment]
@josephrocca thanks for reporting. @lina128 I was able to reproduce the error, link needs to be updated .
cc @nsthorat
