### ISSUE TITLE
[Bug] [tfjs-examples] Specifying 1 digit in the addition-rnn example always creates an error.

### ISSUE THREAD

**Issue by Symbitic** [tensorflow/tfjs#2684]
#### TensorFlow.js version

1.5.1

#### Browser version

Google Chrome 79.0.3945.117

#### Describe the problem or feature request

For the addition-rnn example, entering "1" for the size of digits always results in the following JavaScript error, regardless of training size.
`Error in slice3D: begin[0] + size[0] (20) would overflow input.shape[0]`

#### Code to reproduce the bug / link to feature request

Open <https://storage.googleapis.com/tfjs-examples/addition-rnn/dist/index.html>, Enter "1" for "Digits" and "100" for "Training Size", then click "Train Model"

**Comment by rthadur** [comment]
@Symbitic i was able to reproduce the error with Digits: 2 and Training Size: 100 , but training size 100 is too low , ideally it should be high in order for you to render correct results.

**Comment by Symbitic** [comment]
> @Symbitic i was able to reproduce the error with Digits: 2 and Training Size: 100 , but training size 100 is too low , ideally it should be high in order for you to render correct results.

100 is the maximum allowed training size when Digits = 1.
`const trainingSizeLimit = Math.pow(Math.pow(10, digits), 2);`
(10^1)^2 = 100

**Comment by lina128** [comment]
It seems that # of test examples need to be smaller than 10% of the training size. This seems true for any digits. Here's a runnable configuration: digits=1, training size = 50, rnn type = simplernn, rnn layers = 1, rnn hidden layer size = 128, batch size = 1, train iteration = 500, # of test examples = 5. But with the small amount of data, the model is hard to converge.
