### ISSUE TITLE
Add Pipcook to GALLERY.md

### ISSUE THREAD

**Issue by utkobe** [tensorflow/tfjs#2685]
Pipcook is afront-end Node.js algrithm engineer platform based on tfjs-node. For more information, please check:

Repo: https://github.com/alibaba/pipcook
Medium: 
https://medium.com/imgcook/pipcook-an-algorithm-platform-for-the-front-end-7b2c4ae759f6
https://medium.com/imgcook/how-to-build-a-high-level-front-end-machine-learning-platform-based-on-tfjs-node-b14dff9402a9

**Comment by rthadur** [comment]
#2686

**Comment by rthadur** [comment]
related PR has been merged, thank you.
