### ISSUE TITLE
[tfjs-backend-wasm] before loading wasm is preloaded backend webgl not cpu

### ISSUE THREAD

**Issue by lfuszara1** [tensorflow/tfjs#2697]
#### Versions:

```
import * as jpeg from 'jpeg-js';
import { Buffer } from 'buffer';

import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity, Image } from 'react-native';

import * as Permissions from 'expo-permissions';
import * as FileSystem from 'expo-file-system';

import { RNCamera } from 'react-native-camera';

import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';
import * as cocoSsd from '@tensorflow-models/coco-ssd';
import '@tensorflow/tfjs-backend-wasm';

import Tts from 'react-native-tts';
```

#### TensorFlow.js version

1.5.1

#### Describe the problem or feature request

When I switched kernel to wasm and disabled webgl in platform_react_native.ts of tfjs-react-native package, I try to run app, backend webgl preloaded and webgl throw the error.
On pure cpu app is working. 

#### Code to reproduce the bug / link to feature request

Please set backend to cpu when is used custom tf backend like wasm.

**Comment by rthadur** [comment]
Please provide reproduction code and your system configuration.

**Comment by lfuszara1** [comment]
Wasm backend was priority 2 and webgl have priority 2, this was the problem. 
Cpu backend works because have greater priority than webgl. 
I changed priority wasm to 1 and everything is OK.

**Comment by tafsiri** [comment]
- What WebGl error did you get?
- You can use [setBackend](https://js.tensorflow.org/api/latest/#setBackend) to use the backend you want to use, its not clear from your bug report whether you are calling setBackend.

**Comment by gitathrun** [comment]
I try to setBackend('wasm') with tfjs-react-native, but it shows as yellow warning:

![image](https://user-images.githubusercontent.com/22137687/75571822-dcb63180-5a51-11ea-8646-e59d3f0c1613.png)

Then it automatically reset it to rn-webgl.

My code:
```
        await tf.setBackend('wasm');
        await tf.ready();
        console.log("   backend and tfjs is ready    ");
        checkBackend = tf.getBackend();
        console.log("suppose to be backend: "+ BACKEND_TO_USE);
        console.log("real backend is: "+checkBackend);
```
result
![image](https://user-images.githubusercontent.com/22137687/75571923-125b1a80-5a52-11ea-836c-1051d834251d.png)

Does the wasm backend not work with tfjs-react-native?

**Comment by gitathrun** [comment]
@lfuszara1 Did your tf.setBackend('wasm') worked? Without any warning or error? How is the performance?
