### ISSUE TITLE
Error: Unsupported tensor DataType: DT_INT64

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/tfjs#2698]
#### TensorFlow.js version
"@tensorflow/tfjs-node": "^1.5.1"

#### Browser version
NA

#### Describe the problem or feature request
When I load a saved model that is saved by `tf.keras`, `Error: Unsupported tensor DataType: DT_INT64` error is thrown in node v10.15.0.

#### Code to reproduce the bug / link to feature request
https://colab.research.google.com/drive/13GNsRCVtiS3r-VcupZGC2aZo-gSueMEV#revisionId=0BwoZu2uBQcUZTUFQNDBIdURHaUJsR3VMK2c2OWhxZVg4LytzPQ saves the `tf.keras` model using `model.save("saved_model/3_table_model")`

and

```js
const tf = require("@tensorflow/tfjs-node");
async function main() {
    const modelInfo = await tf.node.getMetaGraphsFromSavedModel("./saved_model/3_table_model")    
}
main();
```
tries to load the meta graph.

And here is the stack trace from the run,
```
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 5
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 5
2020-01-24 23:17:13.039164: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-24 23:17:13.069065: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x109651400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-24 23:17:13.069096: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(node:16643) UnhandledPromiseRejectionWarning: Error: Unsupported tensor DataType: DT_INT64
    at mapTFDtypeToJSDtype (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:464:19)
    at Object.<anonymous> (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:162:57)
    at step (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
(node:16643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm running this on a Mac OS 10.15.1 with `Python 2.7.17 :: Anaconda, Inc.`

**Comment by Nithanaroy** [comment]
I changed my dataset to `int32` to make it work. But not sure if this is mentioned already, but I couldn't find in the `loadSavedModel()` of Node.js doc.
Changed my Python input pipeline for this at https://colab.research.google.com/drive/13GNsRCVtiS3r-VcupZGC2aZo-gSueMEV#revisionId=0BwoZu2uBQcUZSEVEdWVwU1c1ZVE4dlpvS0JuNEc2ZlBSa1g4PQ

**Comment by rthadur** [comment]
Submitted a PR #2700 , thanks for reporting.
cc @kangyizhang

**Comment by Nithanaroy** [comment]
I'm working on another more complex model and facing the same issue even after ensuring all my `tf.data` and `tf.feature_columns` operations are on int32 or float32. Is there a way to debug this in my Python code? 
I tried to use saved model CLI to find any instances of int64 in my saved model, but couldn't find any function which can help me here.

**Comment by loretoparisi** [comment]
@kangyizhang I'm getting this error after converting a GraphModel from TFHub to a saved model:

```
(node:39361) UnhandledPromiseRejectionWarning: Error: Unsupported tensor DataType: DT_INT64, try to modify the model in python to convert the datatype
```

The model I have converted, was working in TFJS, since it's a tfjs-models example:

```
tfconv.loadGraphModel(
      'https://tfhub.dev/tensorflow/tfjs-model/toxicity/1/default/1',
      { fromTFHub: true })
```
