### ISSUE TITLE
how to install tensorflowjs converter version 1.5.1

### ISSUE THREAD

**Issue by shnamin** [tensorflow/tfjs#2703]
Hi, 
What is the process of installing the final version of the tensorflowjs (and TensorFlow js converter) locally on Linux 18 or 19? I need to use tensorflowjs 1.5.1 in my conversion of my quantization-aware trained TensorFlow model to tensorflowjs, otherwise, I am getting errors with some layers that are recently added to tensorflowjs 1.5.1 (like nonmaxsuppressionv5).
 
Please guide!

**Comment by rthadur** [comment]
@shnamin please follow these [instructions](https://github.com/tensorflow/tfjs#via-script-tag) here to use latest version.

**Comment by shnamin** [comment]
hi @rthadur  it doesn't show the installation of the latest version of tensorflow converter!?

**Comment by lina128** [comment]
Hi @shnamin, NonMaxSuppressionV5 is not in converter 1.5.1. The cpu and gpu kernels for this op are implemented and are in core 1.5.1. We will release 1.5.2 tomorrow, so that converter will include this op. Stay tuned.

**Comment by lina128** [comment]
> hi @rthadur it doesn't show the installation of the latest version of tensorflow converter!?

Hi @rthadur, NonMaxSuppressionV5 is supported in 1.5.2. See release note: https://github.com/tensorflow/tfjs/releases/tag/tfjs-v1.5.2
