### ISSUE TITLE
[tfjs-converter] ValueError: Unsupported Ops in the model before optimization TensorListReserve, TensorListStack, TensorListSetItem, TensorListGetItem, TensorListFromTensor

### ISSUE THREAD

**Issue by marius-sm** [tensorflow/tfjs#2722]
#### TensorFlow.js version
1.5.2 
#### Browser version
any
#### Describe the problem or feature request
Unsupported ops

Are there any plans to add these ops or any workarounds ?

**Comment by pyu10055** [comment]
@marius-sm Can you share the name of the model you try to convert?

**Comment by marius-sm** [comment]
The model consists of several files with custom layers, so it is complicated to share.. Meanwhile I'm pretty sure that the error is because of tf.map_fn, which I think is not supported, so I left it out of the model (fortunately it was just before the output) and coded what it did in plain JavaScript

**Comment by pyu10055** [comment]
@marius-sm Good to know that you found a solution, yes, many of these pre/post processing logic should be implemented in javascript, since it might provide better performance too.
