### ISSUE TITLE
Incorrect description of 'epochs' in https://js.tensorflow.org/api/latest/#tf.LayersModel.fit

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#2727]
#### TensorFlow.js version
1.5.2

#### Browser version
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

#### Describe the problem or feature request
When initialEpoch is provided then epochs does not describe "The number of times to iterate over the training data arrays." as documented in https://js.tensorflow.org/api/latest/#tf.LayersModel.fit

#### Code to reproduce the bug / link to feature request
```
// this only runs epochs 3 and 4 unlike the documentation
const model = tf.sequential({
    layers: [tf.layers.dense({units: 1, inputShape: [10]})]
});
model.compile({optimizer: 'sgd', loss: 'meanSquaredError'});
console.log(await model.fit(tf.ones([8, 10]), tf.ones([8, 1]),
         {epochs: 5,
          initialEpoch: 3}));
```

**Comment by rthadur** [comment]
@ToonTalk as mentioned in the document `initialEpoch (number) Epoch at which to start training (useful for resuming a previous training run).` when `initialEpoch` is mentioned code considers `Epochs` as end `Epochs`.
cc @dsmilkov

**Comment by ToonTalk** [comment]
Yes but epochs does not mean

"The number of times to iterate over the training data arrays."

but something like

"The epoch number the iterations will stop"

Shouldn't the documentation for "epochs' be clearer?

**Comment by lina128** [comment]
Hi @ToonTalk, thanks for the feedback. TensorFlow keras API describes epoch as: "epochs: Integer. Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided. Note that in conjunction with initial_epoch, epochs is to be understood as "final epoch". The model is not trained for a number of iterations given by epochs, but merely until the epoch of index epochs is reached." -https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

We follow the same design in our code. Does above description read clearer to you? If so, we can change our documentation to be the same. Thanks.

**Comment by ToonTalk** [comment]
Yes, that is clear. Thanks.
