### ISSUE TITLE
[BodyPix] Feature request: Rendering utils for removing background

### ISSUE THREAD

**Issue by leader22** [tensorflow/tfjs#2736]
Hi team.

Now I'm working on implementing "Virtual background" filter for video chat.

And of course, there are several ways to achieve it.

- composite manually w/ `bodyPix.toMask()`
- use `bodyPix.drawBokehEffect()` w/ large `backgroundBlurAmount` value
  - not ideal, but it works...

It would be helpful if there is the API like `removeBackground()`.

How do you think?
If it is appreciated, I'd like to submit PR for that.

<details>

Memo: implementation details will be..

```ts
export function removeBackground(
    canvas: HTMLCanvasElement, image: ImageType,
    multiPersonSegmentation: SemanticPersonSegmentation|PersonSegmentation[],
    edgeBlurAmount = 3, flipHorizontal = false) {
  const [height, width] = getInputSize(image);
  canvas.width = width;
  canvas.height = height;

  const personMask = createPersonMask(multiPersonSegmentation, edgeBlurAmount);

  const ctx = canvas.getContext('2d');
  ctx.save();
  if (flipHorizontal) {
    flipCanvasHorizontal(canvas);
  }
  // draw the original image on the final canvas
  ctx.drawImage(image, 0, 0, width, height);

  // "destination-in" - "The existing canvas content is kept where both the
  // new shape and existing canvas content overlap. Everything else is made
  // transparent."
  // crop what's not the person using the mask from the original image
  drawWithCompositing(ctx, personMask, 'destination-in');

  ctx.restore();
}
```

</details>

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation
