### ISSUE TITLE
Sporadic Error - shapeInfo.texShape is 'undefined' in shader_compiler::getPackedSampler2D

### ISSUE THREAD

**Issue by recovering1004** [tensorflow/tfjs#2737]
**TensorFlow.js version:**  1.5.2

**Browser Version:** Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Describe the problem or feature request:**
Please reference recently closed issue #2375.  I am having a very similar issue with a model trained in Python using the ssd_mobilenet_v2_coco_2018_03_29 model as the base model and converted to a web model using tfjs-converter.  As reported previously, this model woks well in Python, but I get the following error periodically:  “Cannot read property ‘0’ of undefinded” during prediction.  I have confirmed that this exception occurs inside of shader_compiler::getPackedSampler2D, and inputInfo.shapeInfo.texShape has value “undefined”.

To further investigate this error, I used tfjs-converter to convert the original base model from the TensorFlow Object Detection Model Zoo, ssd_mobilenet_v2_coco_2018_03_29, to see if the problem is somehow related to the custom training.  I still get the same error.

**Code to reproduce the bug / link to feature request:**
```
   async function predict(fileName){
        const img = document.getElementById('blah');
        inputTensor = tf.browser.fromPixels(img).toFloat();
        tensor4d = inputTensor.as4D(1,300,300,3);

        // detect objects in the image.
        try{
                let output = await model.executeAsync(
                    {'image_tensor': tensor4d},
                    ['detection_boxes', 'detection_scores', 'detection_classes', 'num_detections']
                );
                out = checkResults(output, fileName);
                console.log(out + ' detection in ' + fileName);
                return 1;
        } catch (err){
            console.log('err 0 in ' + fileName);
            return 0;
        }
    }

    function checkResults(detectionOutput, imageName){
        count = 0;
        numDetections = detectionOutput[3].dataSync()[0];
        detectionProbability = detectionOutput[1].dataSync();
        detectionClass = detectionOutput[2].dataSync();
        for(k=0; k < numDetections; k++){
            console.log(numDetections);
            if(detectionProbability[k] >= 0.50 && detectionClass[k] == 2){
                pictures.push(imageName);
                count++;
                break;
            }
        }
        return count;
    }
```

Different from the error occurrence found in post #2375, I do not get this error for every attempted prediction.  Below are my observations when trying to reproduce this error:

- I do not get the error by utilizing await model.executeAsync(tf.zeros([1,300,300,3])).  
- I do not get the error for every image that is passed.
- Sometimes if I pass the same image twice (pass image -> Error -> pass image again) I will not get an error the second time and will get results. 
- Sometimes if I pass the same image twice (pass image -> Error -> pass image again) I will get the error both times.
- If I pass multiple images in sequence for prediction, the images for which an error is thrown is dependent on the images passed. 

As an example of the last point, if I have three images for which I would like results (1, 2, and 3), and I can select any or all to pass to the model sequentially for predictions, I can confirm that I receive the following results every time assuming if or when the error is thrown I pass the same image again.

- 1->2->3 will result in 2 consecutive errors on 1, one error then completion on 2, and no errors on 3
- 1 individually will result in two consecutive errors
- 2 individually will result in no error
- 3 individually will result in two consecutive errors
- 1->2 will result in 2 consecutive errors on 1 and one error then completion on 2
- 2->3 will result in no errors on either image
- 1->3 will result in 2 consecutive errors for both images

I should point out that I get these exact same results with both the original ssd mobilenet v2 model and my model that was trained with that model as a base.  Can you point out where I might be going wrong?  I have attached the images discussed above.

**Image 1**
![1](https://user-images.githubusercontent.com/60828790/74093024-1965bd00-4a92-11ea-9607-c548ad1ab319.JPG)

**Image 2**
![2](https://user-images.githubusercontent.com/60828790/74093026-19fe5380-4a92-11ea-9d25-102be958c93a.JPG)

**Image 3**
![3](https://user-images.githubusercontent.com/60828790/74093027-1a96ea00-4a92-11ea-8733-99443f0c3f8b.JPG)

**Comment by pyu10055** [comment]
I tried the generic ssd model you mentioned with your images on our latest release 1.5.2, I did not see the errors you mentioned.
There is one thing I changed, instead of 

```
        inputTensor = tf.browser.fromPixels(img).toFloat();
        tensor4d = inputTensor.as4D(1,300,300,3);
```
I have to changed to 

```
        inputTensor = tf.browser.fromPixels(img).toFloat();
        tensor4d = inputTensor.reshape([1, ...inputTensor.shape]);
```

Since your images are not in the size of 300x300.
Please give it a try, and let us know if the problem persists.
Also please let us know what type machine you are running this on. thanks

**Comment by recovering1004** [comment]
I can not explain it, but I can not recreate the error today.  I am running Windows 10.  I had already set the size of my image element to be 300x300, however I do appreciate your feedback.

**Comment by recovering1004** [comment]
I may have encountered a cache issue, which is why my results seemed to be the same regardless of the model I used. I believe I have an issue with my model only and not the ssd mobilenet v2 model I referenced before.  I have attached the model I am having the issue with in tfjs but not in Python tf Python.  I believe if you use this model, in conjunction with the information found in the original post, you will get the error mentioned.  I am resizing the images to 300x300 prior to detection.

[model.zip](https://github.com/tensorflow/tfjs/files/4188782/model.zip)

**Comment by recovering1004** [comment]
@pyu10055 I am following up with you on this curious if you have had a chance to look at it?

**Comment by rafinskipg** [comment]
@recovering1004  i have the same problem and i can not use my model, did you fixed it?

**Comment by recovering1004** [comment]
@rafinskipg I have not been able to fix this error. I am hoping @pyu10055 will offer some guidance.

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
