### ISSUE TITLE
Unexpected `shape` type in `ModelTensorInfo`

### ISSUE THREAD

**Issue by Pierrci** [tensorflow/tfjs#2739]
#### TensorFlow.js version
1.5.2

#### Browser version
Node.js 12.15.0

#### Describe the problem or feature request
I'm trying to access the `shape` of a model input thanks to `tf.node.getMetaGraphsFromSavedModel`. I was expecting a `number[]` as documented in the [TS typings](https://github.com/tensorflow/tfjs/blob/0db0373720151aedf5608b4c4cde3c81c0aa85ad/tfjs-core/src/model_types.ts#L41), but instead I got this:

```js
[
  {
    wrappers_: null,
    messageId_: undefined,
    arrayIndexOffset_: -1,
    array: [ -1 ],
    pivot_: 1.7976931348623157e+308,
    convertedPrimitiveFields_: {}
  },
  {
    wrappers_: null,
    messageId_: undefined,
    arrayIndexOffset_: -1,
    array: [ 384 ],
    pivot_: 1.7976931348623157e+308,
    convertedPrimitiveFields_: {}
  }
]
```

#### Code to reproduce the bug / link to feature request
Using the following model: https://cdn.huggingface.co/distilbert-base-cased-distilled-squad-384-saved_model.tar.gz

```typescript
const graph = await tf.node.getMetaGraphsFromSavedModel("./distilbert-cased");
console.log(graph[0].signatureDefs["serving_default"].inputs["attention_mask"].shape);
```

**Comment by kangyizhang** [comment]
hi @Pierrci , thanks for reporting this.

This is because the model is exported with a new version of tensorflow python. The corresponding parsing code need to be updated in tfjs-node. I have filed https://github.com/tensorflow/tfjs/issues/2959 to track this and we are working on it.
