### ISSUE TITLE
Typo in https://js.tensorflow.org/api/latest/#layers.conv1d

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#2745]
![image](https://user-images.githubusercontent.com/2138696/74314215-0e6f9d00-4db0-11ea-9221-c2c98a480076.png)

I assume it should have been

(batch, channels, ...)

**Comment by ManishAradwad** [comment]
I'll correct it! Where can I find the corresponding files?

**Comment by rthadur** [comment]
Here is the [file](https://js.tensorflow.org/api/latest/#layers.conv1d) , i guess that is formatting issue in Markdown, there are multiple such issues in the same page, thank s for your help.

**Comment by ManishAradwad** [comment]
I tried finding markdown file for this page but couldn't find it. Can you plz help?

**Comment by rthadur** [comment]
Should be the same file , please check

**Comment by tafsiri** [comment]
I think [this is the file](https://github.com/tensorflow/tfjs/blob/5233a361fabd592e8682147c91c04e271982c989/tfjs-layers/src/layers/convolutional.ts#L316). The code formatter is what splits it onto multiple lines. Re-wording this to fit on one line would likely solve it.

**Comment by ManishAradwad** [comment]
Sure, thanks! I'll take a look at it.
