### ISSUE TITLE
tfjs-react-native - Should add 'png' to the metro config?

### ISSUE THREAD

**Issue by jasonhis** [tensorflow/tfjs#2759]
#### TensorFlow.js version
tfjs@1.5.2
tfjs-react-native@0.2.3

#### Describe the problem or feature request

The README.md recommends to modify metro.config.js to the following.  I was having issues with .png assets from react-navigation and react-native-paper after making this change.

Should the assetExts includes 'png'?

Also, can someone explain what does this blacklist code do?

```
// Change 1 (import the blacklist utility)
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  resolver: {
    // Change 2 (add 'bin' to assetExts)
    assetExts: ['bin', 'txt', 'jpg'],
    sourceExts: ['js', 'json', 'ts', 'tsx', 'jsx'],
    // Change 3 (add platform_node to blacklist)
    blacklistRE: blacklist([/platform_node/])
  },
};
```

**Comment by rthadur** [comment]
@jasonhis users can add `png's` if they have and platform_node has some require statements which are incompatible with metro so we need blacklist.

**Comment by tafsiri** [comment]
You should feel free to add any necessary extensions to your assetExts, note the comment above contains the main instruction (adding .bin to the list).
