### ISSUE TITLE
Add checks for memory leaks to layers

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#276]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs-layers 0.5.3

#### Describe the problem or feature request
In the unit testing code tfjs_backend_test.ts there is a test that the backend function `qr` does not leak any tensors.  Ideally we would have memory-leak coverage for all such functions.  Is it possible to create a simple scalable solution that doens't involve adding a custom memory check testing block for every symbol?

**Comment by dsmilkov** [comment]
A simple solution would be to compare `tf.memory().numTensors` in a `beforeEach()` and `afterEach()`. You can add these gradually to more 'describe()` modules.
