### ISSUE TITLE
Unhandled Rejection (Error): The shape of dict['image_tensor'] provided in model.execute(dict) must be [X,X,X,X], but was [X,X,X]

### ISSUE THREAD

**Issue by sinankarakaya** [tensorflow/tfjs#2764]
###TensorFlow.js version
v1.5.2

###Browser version
Chrome 79.0.3945.130 

###Describe the problem or feature request
I trained my own object with the tensorflow 1.15.0 with faster_rcnn_inception_v2_coco_2018_01_28. After that saved model was converted web models with tensorflow converter. tensorflowjs version is 1.5.2. 

This created model using web app error The shape of dict['image_tensor'] provided in model.execute(dict) must be [X,X,X,X], but was [X,X,X]

Create saved model
```
python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-XXXX --output_directory inference_graph
```
Convert saved model 
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    --saved_model_tags=serve \
    /mobilenet/saved_model \
    /mobilenet/web_model
```

tensorflowjs web app

```
const img = document.getElementById('img');
const model = await tf.loadGraphModel('model.json')
model.predict(tf.browser.fromPixels(img)) // or model.predict(img)
```

What is wrong this process ?

**Comment by dozeBoy** [comment]
@sinankarakaya  You need to do .expandDims(0) after tf.browser.fromPixels(img)

**Comment by rthadur** [comment]
@sinankarakaya did you try above solution ?

**Comment by sinankarakaya** [comment]
> @sinankarakaya did you try above solution ?

No but I changed model  and its work.

**Comment by rthadur** [comment]
thank you, closing this issue.

**Comment by ogawafais** [comment]
May i know which model you use that work with that code?

**Comment by parthlathiya42** [comment]
> > @sinankarakaya did you try above solution ?
> 
> No but I changed model and its work.

Which model worked??

**Comment by sinankarakaya** [comment]
> > > @sinankarakaya did you try above solution ?
> > 
> > 
> > No but I changed model and its work.
> 
> Which model worked??


I don't remember exactly but I think I used ssd_mobilenet_v1_coco.config.
