### ISSUE TITLE
Update docstring for tf.setBackend(): it creates a new Engine and disposes the old one.

### ISSUE THREAD

**Issue by MengShaoying** [tensorflow/tfjs#277]
It seens that a variable can't be defined before using "tf.setBackend()", even if the backend is the same.

```
// I create a variable tensor "BARIABLE_TENSOR".
const BARIABLE_TENSOR = tf.variable(tf.fill([1, 2], 0.5));

// It's "webgl".
console.log('Backend: ' + tf.getBackend());

// It was "webgl" before, so tf.setBackend('webgl') probably didn't do anything.
tf.setBackend('webgl');

// I try to do some calculations.
tf.print(BARIABLE_TENSOR.add(tf.ones([1, 2])));

// All right, I continue.
const denseModel = tf.sequential();
denseModel.add(tf.layers.dense({inputShape:[2], units:1}));

const optimizer = tf.train.sgd(0.01);

const loss = () => {
    return denseModel.predict(BARIABLE_TENSOR).asScalar();
};

// Something worng happened:
// Argument 'b' passed to 'add' must be a Tensor, but got undefined.
optimizer.minimize(loss, true, [BARIABLE_TENSOR]);
```

#### Browser version Chrome 66.0.3359.139

**Comment by davidsoergel** [comment]
This is working as intended.  tf.setBackend() always initializes a new execution environment and disposes any preexisting one.

I see we could improve the documentation to clarify that, though.

**Comment by MengShaoying** [comment]
Thanks, I see that
(1) Obviously, tensor `test` still exists after `tf.setBackend()`, but `tf.memory().numTensors` is 0. Actually, after `tf.setBackend()`, `tf.memory().numTensors` is always 0. So, `tf.memory()` can't be use to show how many tensors exists in memory before `tf.setBackend()`, or tensors before `tf.setBackend()` shouldn't exists.

```
tf.setBackend('webgl');
const test = tf.tensor([1,2,3]);
console.log(tf.memory().numTensors); // numTensors = 1

tf.setBackend('webgl');
console.log(tf.memory().numTensors); // numTensors = 0

test.print(); // "test" exists
test.add(tf.tensor([1,1,1])); // It can even be used to calculate
test.print();

tf.setBackend('cpu');    // switch to a different backend
tf.setBackend('webgl');  // switch back

test.print(); // "test" still exists...
```

(2) The tensors created before `tf.setBackend()` can use `add()` or `mul()` method after `tf.setBackend()`, but it can't be used for Optimizers. In fact, I found that the following code can "work":
```
const BARIABLE_TENSOR = tf.variable(tf.fill([1, 2], 0.5), true, 'tensor_train');

console.log('Backend: ' + tf.getBackend());

tf.setBackend('webgl');

console.log('BARIABLE_TENSOR:');
tf.print(BARIABLE_TENSOR);

/*
 * I just create a new variable tensor. And I set The
 * name is same with BARIABLE_TENSOR.
 */
const TEST_TENSOR = tf.variable(tf.fill([1, 2], 0.5), true, 'tensor_train');

const denseModel = tf.sequential();
denseModel.add(tf.layers.dense({inputShape:[2], units:1}));

const optimizer = tf.train.sgd(0.01);

const loss = () => {
    return denseModel.predict(BARIABLE_TENSOR).asScalar();
};

optimizer.minimize(loss, true, [BARIABLE_TENSOR]);

console.log('BARIABLE_TENSOR & TEST_TENSOR:');
tf.print(BARIABLE_TENSOR);
tf.print(TEST_TENSOR);
```
`optimizer.minimize()` want to change BARIABLE_TENSOR, but what is really changed is TEST_TENSOR.

**Generally, it shows that your "tensors manager(or something else, I don't know what you call it)" seems to have some problems. If everything is normal, what puzzles me is that (2) seems to want to say that the tensor previously created will affect the recent tensor in some way.**
