### ISSUE TITLE
tf.transpose of 1D Tensor leads to ugly shader compiler error

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#278]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10.0
#### Browser version
66.0.3359.117 (Official Build) beta (64-bit)

#### Describe the problem or feature request
Bad error message when taking the transpose of a 1D tensor

#### Code to reproduce the bug / link to feature request
const a = tf.tensor1d([1, 2, 3, 4, 5, 6]);
a.transpose();

An error occured
Failed to compile fragment shader.

Full output error here:
https://gist.github.com/bileschi/9d1f0064c1266862c6a0ba49da136c38

**Comment by dsmilkov** [comment]
Thanks! Can you also share the code that does the transpose? I can only see the tensor construction

**Comment by bileschi** [comment]
Hey sorry.
`a.transpose()`

updated the original to include
This is reproduceable in the editable snippets on the site.

**Comment by dsmilkov** [comment]
Thanks and no worries. I was curious if you were passing any special permutation as an argument. Should to be easy to fix this. Assigning to myself.
