### ISSUE TITLE
Doubt in model conversion to tfjs

### ISSUE THREAD

**Issue by Rakeshvcr** [tensorflow/tfjs#2782]
Hi I tried converting  frozen model to model.json and shard files. I need output files to be tfjs_model.pb, shard and weights_manifest.json. This is command that i have tried what changes need to made to get output files mentioned above

`tensorflowjs_converter ./input_path/frozen_inference_graph.pb ./output_path/  --input_format=tf_frozen_model  --output_node_names='num_detections,detection_boxes,detection_scores,detection_classes' --quantization_bytes=1`

**Comment by rthadur** [comment]
@Rakeshvcr please let us know what error you are getting ?

**Comment by Rakeshvcr** [comment]
sorry for the late replay, I'm not getting any error.
In this [github](https://github.com/victordibia/handtrack.js/tree/master/models/web/ssdlitemobilenetv2) they have 3 different files(tensorflowjs_model.pb, weights_manifest.json and shard files), but when I tried converting frozen_inference_graph.pb file I got (model.json and shard files).

**Comment by rthadur** [comment]
`.pb` format in not supported , we only support model.json right now and there is no plan to support this in near future.Thank you

**Comment by rthadur** [comment]
@Rakeshvcr may we know the reason why you `.pb` output format ?
