### ISSUE TITLE
Fix Node.js tests for local browser storage and Blob

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#279]
We black-listed these tests: 'browser', 'LocalStorage', 'arrayBufferToBase64String', 'stringByteLength' for the Node bindings.

**Comment by caisq** [comment]
cc myself

**Comment by dsmilkov** [comment]
There are two more left that should be constrained to run only in the browser: 'arrayBufferToBase64String', 'stringByteLength'

**Comment by nsthorat** [comment]
With the new test change I can constrain these to only run in the browser, however, is that what we want? It seems like those could both work in node.

**Comment by nsthorat** [comment]
I decided not to fix this in my PR. Restricting to browser environments is trivial if we decide turning the tests off is the right move, we simply use `describeWithFlags` and pass `BROWSER_ENVS`, which turn it off for node.
