### ISSUE TITLE
Undocumented expo-camera required peer dependency for tfjs-react-native

### ISSUE THREAD

**Issue by Polarisation** [tensorflow/tfjs#2795]
#### TensorFlow.js version
v1.5.2

#### Browser version
React Native v0.61.5

#### Describe the problem or feature request
The [installation instructions](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#step-4-install-tensorflowjs-and-tfjs-react-native) do not mention that `expo-camera` must be installed/configured (in a non-expo environment).

Without doing this, `import '@tensorflow/tfjs-react-native'` fails due to the missing `expo-camera` dependency.

Installing and configuring `expo-camera` did work, however I question whether this should be a required dependency because the app may not need to use the camera.

#### Code to reproduce the bug / link to feature request
N/A

**Comment by gitathrun** [comment]
Watch out the version compatiable issue for expo-camera and react-native-unimodule, I recently encountered the issue that expo-camera 8.0.0 only works with react-native-unimodule 0.7.0, otherwise it throws error while building the apk.

**Comment by Polarisation** [comment]
Just in case anyone is struggling with this (or wants to save time), I've published a [React Native Template with TensorFlow.js](https://github.com/Polarisation/react-native-template-tfjs) pre-installed and configured. You can also review the git history on the repo if you're looking to follow the steps yourself.
