### ISSUE TITLE
crossover and mutate functions

### ISSUE THREAD

**Issue by lastnod** [tensorflow/tfjs#280]
no problem guy great job by the way.
Just a feature request ! :)

Could you implement a crossover function in order to perform reinforcement learning ? (genetic algorithm for me :) )
and obviously with crossover we need a simple mutate function to tune weight, maybe with possibility to put your own tuning function like gaussian distribution.

i hope it's not already implemented !

**Comment by davidsoergel** [comment]
My feeling is that this is a higher-level feature that doesn't belong in our core libraries.  Of course anyone is free to build an external genetic algorithm library on top of TF.js primitives, no problem!  (Note none of Python TensorFlow, TF Layers, or Keras provide any explicit support for genetic algorithms afaik).

I'll close this as "won't fix" in a day or two if there are no other opinions.

**Comment by shiffman** [comment]
As an FYI we're hoping to tackle this with ml5! See: 
https://github.com/ml5js/ml5-library/issues/113

**Comment by davidsoergel** [comment]
Excellent!  See also #252.
