### ISSUE TITLE
BodyPix - running segmentPerson in node.js throws an error: Unknown input type: [object ImageData].

### ISSUE THREAD

**Issue by cpshaheen** [tensorflow/tfjs#2800]
TensorFlow.js version 1.2

Code that causes error.

```
var bodyPix = require("@tensorflow-models/body-pix");
var tfjs = require("@tensorflow/tfjs")
var inkjet = require('inkjet');
var createCanvas = require('canvas');
var fs = require('fs');

async function loadAndPredict(data) {
    const net = await bodyPix.load({
           architecture: 'MobileNetV1',
           outputStride: 16,
           multiplier: 0.75,
           quantBytes: 2
    });

    imgD = createCanvas.createImageData(new Uint8ClampedArray(data.data), data.width, data.height);
    const segmentation = await net.segmentPerson(imgD, {
    flipHorizontal: false,
    internalResolution: 'medium',
    segmentationThreshold: 0.7
    });
    const maskImage = bodyPix.toMask(segmentation, false);
}

inkjet.decode(fs.readFileSync('./person.jpg'), function(err, data) {
    if (err) throw err;
    console.log('OK: Image');
    loadAndPredict(data)
  });
```

I have been able to run the segmentation and masking when referencing an image within an html file but I need to be able to reference Images and segment server side in the above manner.

In the BodyPix README it states that the segmentPerson function accepts ImageData object images:
"Params in segmentPerson()
image - ImageData|HTMLImageElement|HTMLCanvasElement|HTMLVideoElement The input image to feed through the network."
https://github.com/tensorflow/tfjs-models/tree/master/body-pix

So, I am confused as to what is causing this issue. Thank you for any help.

**Comment by machenmusik** [comment]
I believe that unlike the browser environment, node does not supply a default ImageData implementation, thus the error.

**Comment by Abhisheknarsing** [comment]
const img = new Image()
img.src = 'hi.jpg'  
img.onload = () => ctx.drawImage(img, 0, 0)
img.onerror = err => { throw err }
height = img.height;
width = img.width ;
const canvas = createCanvas(width, height);
const ctx = canvas.getContext('2d');
ctx.drawImage(img, 0, 0, width, height);
tf.browser.fromPixels(canvas).print();
const imgout = ctx.getImageData(0, 0, width, height);

**Comment by Abhisheknarsing** [comment]
`const { createCanvas, loadImage, drawImage,Image } = require('canvas')

const img = new Image()
img.src = 'hi.jpg'  
img.onload = () => ctx.drawImage(img, 0, 0)
img.onerror = err => { throw err }
height = img.height;
width = img.width ;
const canvas = createCanvas(width, height);
const ctx = canvas.getContext('2d');
ctx.drawImage(img, 0, 0, width, height);
tf.browser.fromPixels(canvas).print();
const imageData = ctx.getImageData(0, 0, width, height);`

Hope this works!
it's gives ImageData Type Object

**Comment by Abhisheknarsing** [comment]
Same issue here!

**Comment by cpshaheen** [comment]
here's the fix!

I. require the proper canvas objects
'''
const { createCanvas, loadImage, createImageData, Image } = require('canvas');
'''

II. decode the image
*note I'm using inkjet to decode the image from the filesystem

'''
var srcimagefile = "image.jpg";
var srcimg = fs.readFileSync(srcimagefile);
inkjet.decode(srcimg, function(err, data){
    if(err) throw err;
    console.log("Image loaded.");
    var img = convImg(data); //this function is provided below
    //console.log(img);
    loadAndPredict(img).catch(e => {console.error(e)}) //this function is provided below
});
'''

III. convert the image to the expected object structure

'''
function convImg(data){
  imgD = createImageData(new Uint8ClampedArray(data.data), data.width, data.height);
  const img = new Image();
  img.src = srcimagefile;
  const canvas = createCanvas(data.width,data.height);
  const ctx = canvas.getContext('2d');
  ctx.drawImage(img,0,0,data.width,data.height);
  return tfjs.browser.fromPixels(canvas);
}
'''

IV. now use the converted object to 'loadAndPredict'

'''
async function loadAndPredict(data) {
  console.log(data)
  console.log("loading architecture");
  const net = await bodyPix.load(architecture);
  console.log()
  console.log("segmenting person");
  const segmentation = await net.segmentPersonParts(data);
  // what you do at this point with the segmentation is up to you
}
'''
Hope this helps! (This took me a while to figure out since I had no prior JS experience)

**Comment by machenmusik** [comment]
FYI, the way face-api handles this is much simpler, there is a way to use the node versions of canvas et al. so it "just works" - might be worth investigating.
