### ISSUE TITLE
Cannot read images from Tensorflow.js Tensorcamera on React Native

### ISSUE THREAD

**Issue by sauceishere** [tensorflow/tfjs#2805]
I am trying to use Tensorflow.js posenet on React Native but I can not get 'images'.
Currently Expo-camera works ok, but images is undefined.
Please advise how to iterate getting images from TensorCamera.
Thanks.

```
const TensorCamera = cameraWithTensors(Camera);

export default class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.handleCameraStream = this.handleCameraStream.bind(this);
  }

  async estimatePoseOnImage(imageElement) {
    const net = await posenet.load();
    const pose = await net.estimateSinglePose(imageElement, {
      flipHorizontal: false,
    });
    this.setState({ pose: pose });
    return pose;
  }

  handleCameraStream( images ) {
    const loop = async () => {
      const nextImageTensor = await images.next().value;
      await this.estimatePoseOnImage(nextImageTensor);
      requestAnimationFrame(loop);
    };
    loop();
  }

  render() {
    return (
      <View>
        <TensorCamera
          type={Camera.Constants.Type.front}
          onReady={this.handleCameraStream}
          autorender={true}
        />
      </View>
    );
  }
}
```

**Comment by fergalindez** [comment]
I'm trying to follow https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx, but none of the models load. I'm using expo to make the test.

**Comment by sauceishere** [comment]
@fergalindez Thanks, Yes I am also following cameraWithTensors on  https://js.tensorflow.org/api_react_native/latest/#Media-Camera

**Comment by sauceishere** [comment]
@tafsiri I just changed from `this.setState({ pose: pose });` to `this.setState({ pose });` and run it. This this.setState lead to render block and shows this.

> ReferenceError: Can't find variable: React
 
The 1st loop gets 'images' and const 'nextImageTensor' is defined, 
but const 'nextImageTensor' is undefined and cannot run 'estimatePoseOnImage' after the 2nd loop, and shows the above error. 
And do I also need to like tf.tensor3d to the data from camera before posenet?

**Comment by tafsiri** [comment]
@fergalindez Please make a new issue describing the problems/errors you are running into. 

@sauceishere Could you post a reproduction somewhere on github where I could take a look and try and reproduce. The React reference not found seems like it could be a project setup issue, but it's hard to tell whats going on. If `images` is defined then you can check if the [iterator is done](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) or not (it will be done/completed if the component is unmounted).

**Comment by tafsiri** [comment]
Also could you post what version of Expo you are using.

**Comment by sauceishere** [comment]
@tafsiri  Thanks very much for the feedback. My code is here https://github.com/sauceishere/tensorcamerajs. and expo version is  3.11.7. `images` is defined only for the 1st loop, and will be undefined later.

**Comment by tafsiri** [comment]
@sauceishere Could you try changing your [react import](https://github.com/sauceishere/tensorcamerajs/blob/master/App.js#L1) to `import * as React from 'react';` and having your main component extend React.Component. Newer versions of expo use a different import format that what is used in the integration_test app.

If that doesn't work then from looking at the error stack it seemed to be coming from react-native-svg, so I would first remove all the things from the app other than the model loading and inference and make sure that works before introducing rendering.

**Comment by sauceishere** [comment]
@tafsiri Thanks. I modified the code according to your advise and it works!! 
By the way, I saw your gif on this page https://blog.tensorflow.org/2020/02/tensorflowjs-for-react-native-is-here.html , do you run on Android or iOS? My code does not render smoothly as yours.
Thanks for your help again.

**Comment by tafsiri** [comment]
Great! That GIF was produced on Android on a Pixel 3.
