### ISSUE TITLE
Unable to use tfjs-node in aws lambda environment

### ISSUE THREAD

**Issue by saumilsdk** [tensorflow/tfjs#2809]
TFJS Node Version
"@tensorflow/tfjs-node": "^1.5.2"

**Problem:**
Unable to use tfjs-node while running. 

```
/data/home/skapadia/projects/cloud-telemetry/node_modules/mocha/node_modules/yargs/yargs.js:1163
      else throw err
           ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/skapadia/projects/cloud-telemetry/node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by rthadur** [comment]
@saumilsdk thanks for reporting , i believe the issue is with the operating system please check [stack-overflow](https://stackoverflow.com/questions/16605623/where-can-i-get-a-copy-of-the-file-libstdc-so-6-0-15) for similar issue.

**Comment by saumilsdk** [comment]
hi @rthadur I am able to take care of libc version but now i am not able to deploy as tfjs-node size is large and >250MB limit of aws serverless. Any idea how to run tsjf-node in serverless?
