### ISSUE TITLE
Make optimizer constructor arg defaults consistent among core and layers

### ISSUE THREAD

**Issue by atanasster** [tensorflow/tfjs#281]
Hi @caisq - just a question, not an issue. 
I saw your referencing sgd default learningRate being 0.1 in another thread, but I am a bit confused. Can you please tell us why some optimizers seem to have default learningRate values (ie adam 0.001), while sgd doesnt seem to have a default value. Or if they do have default values somewhere else, can you pls point me in this direction.

**Comment by davidsoergel** [comment]
When referencing optimizers by name in the Layers API, default arguments are provided in https://github.com/tensorflow/tfjs-layers/blob/master/src/optimizers.ts.

However the underlying implementations in the Core API do not provide defaults: https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/optimizer_constructors.ts

Hope this helps!

**Comment by atanasster** [comment]
thanks @davidsoergel , helps a lot - any reason some models have defaults in the Core API while other only have them when referencing by name?

**Comment by atanasster** [comment]
I got confused, because I was checking the code in tfjs-core and didnt expect defaults are split with tfjs-layers. Btw, some optimizers even have defaults in their constructors, seems a bit confusing, no? 

https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/optimizer_constructors.ts
`static adam(learningRate = 0.001, beta1 = 0.9, beta2 = 0.999, epsilon = 1e-8):`

and https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/adam_optimizer.ts
```
constructor(
      protected learningRate: number, protected beta1: number,
      protected beta2: number, protected epsilon = 1e-8)
```

**Comment by atanasster** [comment]
As a side note, some defaults are duplicated in layers and in core and rmsprop have a slightly different value for momentum:
null in layers and 0 in core

**Comment by davidsoergel** [comment]
Oh whoops, you're right, I overlooked the defaults in core.  Sorry for the confusion.  Reopening and renaming re cleaning this up.  Thanks!

**Comment by atanasster** [comment]
thanks, thats great. Any chance you can consolidate the defaults in core, preferably in the constructors?

**Comment by tafsiri** [comment]
I suspect the ones that have defaults are ones that have some corresponding paper that suggested good defaults. For examples adam optimizer references https://arxiv.org/abs/1412.6980 which suggests defaults. There is a chance we are missing references for some. But we should do some cross comparison to align these, or document differences/sources.

**Comment by ManrajGrover** [comment]
@atanasster I believe we took defaults for optimizers from Tensorflow and referenced papers into consideration while implementing them in Core API to keep things aligned.

**Comment by atanasster** [comment]
Thanks @ManrajGrover makes sense for core, not sure about the layers API, the defaults dont seem to match the keras defaults : https://faroit.github.io/keras-docs/0.2.0/optimizers/

**Comment by atanasster** [comment]
Source here - https://github.com/keras-team/keras/blob/master/keras/optimizers.py 
ex SGD (learningRate 0.01):
```
def __init__(self, lr=0.01, momentum=0., decay=0.,
                 nesterov=False, **kwargs):
        super(SGD, self).__init__(**kwargs)
```

**Comment by ManrajGrover** [comment]
@atanasster I see. Keras out of the box implements its own optimizers with defaults which may not align with Tensorflow.

@davidsoergel I'm not sure whether we want to align Keras with Layers API or with Tensorflow. I'll double check if Core API aligns with Tensorflow for now.

**Comment by atanasster** [comment]
I think tensorflow defaults make more sense. The compatibility is very nice, but will be very hard to keep maintaining. Was just pointing out at the differences - maybe in cases where tf does not have specific defaults, the keras ones can be used?

**Comment by atanasster** [comment]
@ManrajGrover - the API does not fully comply with tensorflow, although it most closely resembles to constructors API in core.
 
ex RMSProp:

https://github.com/tensorflow/tfjs-layers/blob/master/src/optimizers.ts  (lr: 0.001, momentum: null, epsilon: 1e-8)
```
'RMSProp': () => train.rmsprop(.001, .9, null, K.epsilon()),
```

https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/rmsprop_optimizer.ts (lr: undefined, momentum 0.001, epsilon: 1e-8)
```
constructor(
      protected learningRate: number, protected decay = 0.9,
      protected momentum = 0.0, protected epsilon = 1e-8, centered = false) {
```

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/rmsprop.py  (lr: undefined, momentum 0.0, epsilon: 1e-10)
```
def __init__(self,
  learning_rate,
  decay=0.9,
  momentum=0.0,
  epsilon=1e-10,
  use_locking=False,
  centered=False,
```

**Comment by ManrajGrover** [comment]
@atanasster I don't see a difference between Core API and RMSProp of Tensorflow other than epsilon value which is a value of choice for numerical stability. And yes I agree that there is a difference between defaults of Keras and Layers API.

**Comment by atanasster** [comment]
yes, the epsilon was the difference. Any idea why it is different on the two platforms?

**Comment by dsmilkov** [comment]
The epsilon is different since 32bit floats in WebGL are not necessarily 32bits (often 16 or 24bits, depending on hardware). We set epsilon in order to be safe and numerically stable across a wide range of GPU devices.
