### ISSUE TITLE
Different Output values on CPU vs GPU (Intel UHD Graphics 600) +Slower

### ISSUE THREAD

**Issue by GiorgosXou** [tensorflow/tfjs#2837]
# 👨🏽‍💻 Introduction
Hi, my name is George and i am kind of newbie to web development compared to many others, so please be kind with me when it comes to things i've made wrong [...]

*  ## Specs:
*  💳 GPU Intel UHD Graphics 600
*  ⚡️ Using Electron
*  🧠 Using `'@tensorflow/tfjs'`

# 🤔 Issue
**(Briefly Explained)** I am trying to train a simple XOR ANN using GPU-acceleration on an Intel GPU *(just as a test)*. Although, when i use GPU, **output values** are way-off/different compared to when i force it to use CPU *`tf.setBackend('cpu')`* , plus seems like it is way more **slower on my GPU** compared to when i use CPU [...] 

### More Infos ℹ️
*  **`GPU`**
* * [ScreenShot GPU](https://imgur.com/XrisCrr)
* * 55 seconds elapsed time 
* * ` Tensor [[0.4667143], [0.5212799], [0.4914339], [0.5211046]]`
*  **`CPU`**
* * [ScreenShot CPU](https://imgur.com/4sZ3F5N)
* * 16 seconds elapsed time 
* * ` Tensor [[0.1147182], [0.8899023], [0.8888579], [0.1081314]]`
### Codes Used ℹ️
* * [XOR ANN](https://github.com/mattcam/tfjs_xor_example/blob/master/app.js)
* * [Measure Time](https://stackoverflow.com/questions/41632942/how-to-measure-time-elapsed-on-javascript)

# 💛 Outro
Seems to me like something wrong with floating point precision calculations on GPU...  Any Idea? 
Thanks in advance,
George.

**Comment by dsmilkov** [comment]
Hi,

I noticed in your code:
```js
model.add(tf.layers.dense({units: 10, activation: 'sigmoid',inputShape: [2]}));
model.add(tf.layers.dense({units: 1, activation: 'sigmoid',inputShape: [10]}));
```

This means that every time you refresh the page, you will get new random set initial weights, which affect the final output. To make it more consistent, provide a fixed initial value for the weights. See the weights argument in 
https://js.tensorflow.org/api/latest/#layers.dense

Regarding speed, WebGL has a fixed overhead, and should only be used for large numerical computation. That is, adding 2 numbers in WebGL is just as fast as adding 100,000 numbers.

**Comment by GiorgosXou** [comment]
> Regarding speed, WebGL has a fixed overhead, and should only be used for large numerical computation. That is, adding 2 numbers in WebGL is just as fast as adding 100,000 numbers.

**You are right**, i feel a little bit dumb not realising how little amount of layers and neurons were there so that they could have made a difference in speed time compared to GPU hahaha. 

(_Although, i thought about it for a moment and i was queit skeptical about it, i forgot to not mention it at the end without skeptisims, but nevermind_, Thanks :D )

.
>This means that every time you refresh the page, you will get new random set initial weights

**Yeah sure, but** all of the times i have tried it, it always returns wrong output values (around ~0.5 on GPU) even when i expand the number of itterations. **Although, you are right, i should had provided a fixed initial value for the wights**

.
>provide a fixed initial value for the weights.

I am not that familiar with tensorflowjs in general,** if it would be easy for you, could you possible provide me with some code or show me how i could initialize the weights?** though i will try to find out how (just for time time saving)

.
And **Thanks** again for your response&help (:

**Comment by GiorgosXou** [comment]
**My fault i am really sorry**, as it seems actually I hadn't done enough tests on GPU , now i see...
```
Loss after Epoch 299 : 0.04598948732018471
    [[0.1814047],
     [0.7810922],
     [0.7966389],
     [0.2432438]]

67 seconds
```
