### ISSUE TITLE
Indices must be of dtype `int32` tf.gather

### ISSUE THREAD

**Issue by cclcalder** [tensorflow/tfjs#284]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10.0

#### Browser version
https://js.tensorflow.org/api/0.10.0/#gather

#### Describe the problem or feature request
When I testing tf.gather on the docs page
Error is thrown: Indices must be of dtype int32

#### Code to reproduce the bug / link to feature request
const x = tf.tensor1d([1, 2, 3, 4]);
const indices = tf.tensor1d([1, 3, 3]);

x.gather(indices).print();

**Comment by davidsoergel** [comment]
Yep, thanks @ManrajGrover for the tip!
