### ISSUE TITLE
Add tutorial for performance debugging / profiling.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#286]
From https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/_IDVt3wQFXA:

What are best practices in timing operations that involve data transfer between CPU/GPU to identify bottlenecks?

**Comment by davidsoergel** [comment]
It might be sufficient to update https://deeplearnjs.org/docs/tutorials/performance.html and move it to the new TF.js site.

**Comment by caisq** [comment]
cc @dsmilkov
