### ISSUE TITLE
'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.

### ISSUE THREAD

**Issue by pamruta** [tensorflow/tfjs#2871]
Running Facemesh in Mozilla / Safari on mp4 video file.. It gives this error:

tfjs-core:17 Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.
    at https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:215636
    at $t (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:56257)
    at ii (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:215608)
    at t.uploadPixelDataToTexture (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:220462)
    at Object.kernelFunc (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:487966)
    at d (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:42635)
    at https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:43329
    at t.scopedRun (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:41248)
    at t.runKernelFunc (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:43141)
    at t.runKernel (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core:17:41685)

My html / Javascript is really simple -

```
<html>
<head>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/facemesh"></script>

        <script>
        async function main()
        {
                const model = await facemesh.load(maxFaces=1);
                const stream = document.querySelector("video");
                const faces = await model.estimateFaces(stream);
                faces.forEach(face => console.log(face.scaledMesh));
        }

        main();
        </script>
</head>

<body>
        <video width=640 height=480 controls autoplay loop>
                <source src="shri420.mp4" type="video/mp4" />
        </video>
</body>

</html>
```

Can you help debug what might be wrong? I tried setting crossOrigin = "anonymoys" as well for video object but still same error..

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Greeeeyyyss** [comment]
Got the same error but it was fixed when I added a ```crossOrigin='anonymous'``` before setting the ```src``` of the image or video.
