### ISSUE TITLE
Need more  tfjs-models PoseNet images of different resolutions on the cloud storage

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#289]
For the Posenet Coco_images demo [code here](https://github.com/tensorflow/tfjs-models/blob/8ff589193388fddf7b51409b02c8ab49c2fca697/posenet/demos/coco.js) It needs more images that have different sizes. (I don't see an active demo for the coco_images yet. )

[Image Example](https://storage.googleapis.com/tfjs-models/assets/posenet/soccer.png)

All the images are 513 x 513, but the demo mentions other resolutions will effect the speed of analysis.

The issue is that setting the outputStride to 8 (default 16) causes a webGL failure on some browsers whereas testing with a smaller image works fine.

Could someone upload these images to replace the soccer.png to https://storage.googleapis.com/tfjs-models/assets/posenet/ . The code coco.js would be easy for me to change and submit a PR.

![soccer-385sq](https://user-images.githubusercontent.com/5605614/39935692-b73a3280-54fe-11e8-9511-dd463bda6c0d.png)
![soccer-513sq](https://user-images.githubusercontent.com/5605614/39935693-b7767308-54fe-11e8-8a34-335c3817ecc4.png)
![soccer-769sq](https://user-images.githubusercontent.com/5605614/39935694-b790b5ba-54fe-11e8-8b68-4e445072f242.png)
![soccer-1026sq](https://user-images.githubusercontent.com/5605614/39935695-b7aa4c28-54fe-11e8-8aea-6b46f920c8d5.png)
![soccer-129sq](https://user-images.githubusercontent.com/5605614/39935696-b7c1216e-54fe-11e8-9ed4-fab8fc7316bd.png)
![soccer-200sq](https://user-images.githubusercontent.com/5605614/39935697-b7d73ada-54fe-11e8-8442-fe23c8964767.png)

Here is all the images zipped in an images folder

[images.zip](https://github.com/tensorflow/tfjs/files/1996660/images.zip)

**Comment by oveddan** [comment]
I see the need to have different sized images - but I think it would be a lot to maintain to have different sized images stores for each image.  That means every time we add an image we would need to add one of all the different scales.

It would be better if we had a dropdown that let you choose the image size.  The image size would have to be one of the acceptable images sizes where  `((InputImageSize - 1) / OutputStride) + 1` would not have a remainder.  This can be hardcoded to the possible values:
161, 193, 257, 289, 321, 353, 385, 417, 449, 481, 513.
Then the coco images demo could have tensorflow.js resize the image before processing it,
as is done [here](https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/posenet.ts#L40)
