### ISSUE TITLE
optimizer.applyGradients missing from API documentation

### ISSUE THREAD

**Issue by freeman-g** [tensorflow/tfjs#2897]
#### TensorFlow.js version
1.7

#### Browser version
Chrome 80

#### Describe the problem or feature request

I'm trying to figure out how to manually apply gradients and adjust weights for a GAN that I am building. I noticed in the cart pole example, there is a call to 'optimizer.applyGradients'.

```
      // Add the scaled gradients to the weights of the policy network. This
      // step makes the policy network more likely to make choices that lead
      // to long-lasting games in the future (i.e., the crux of this RL
      // algorithm.)
      optimizer.applyGradients(
          scaleAndAverageGradients(allGradients, normalizedRewards));
```

Here is a link to the example above: https://github.com/tensorflow/tfjs-examples/blob/master/cart-pole/index.js#L170

This sounds like what I need to do for my GAN, but I cannot find any reference to the applyGradients function in the API documentation. Is there a reason why this is not documented?

I'm looking at the 1.7 docs here: https://js.tensorflow.org/api/1.7.0/

#### Code to reproduce the bug / link to feature request

N/A

**Comment by rthadur** [comment]
cc @dsmilkov @nsthorat

**Comment by dhirensr** [comment]
@nsthorat @dsmilkov @rthadur : won't this be fixed if we add @doc in https://github.com/tensorflow/tfjs/blob/tfjs-core-v1.7.0/tfjs-core/src/optimizers/optimizer.ts#L105
won't it automatically show docs also for computeGradients and applyGradient?

**Comment by nsthorat** [comment]
@dhirensr yes it will. Care to send a PR?

**Comment by dhirensr** [comment]
@nsthorat : working on it! will send it in sometime

**Comment by freeman-g** [comment]
Thanks for working on this!

**Comment by rthadur** [comment]
related PR has been merged , thank you @freeman-g @dhirensr
