### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by cyberprodigy** [tensorflow/tfjs#2911]
#### TensorFlow.js version
Documentation in 
Making Predictions from 2D Data
4. Define the model architecture
Under section : Add layers
#### Browser version
All
#### Describe the problem or feature request
The first sentence says "This adds a hidden layer to our network. " 
That is wrong. It should instead say - "This adds an input layer to our network. "
There are input layers, hidden layers and output layers in neural networks

**Comment by rthadur** [comment]
@cyberprodigy thank you for reporting , send out a fix will be updated soon.

**Comment by rthadur** [comment]
This is [fixed](https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#3) now please verify. Thank you @tafsiri & Jason
