### ISSUE TITLE
loadFrozenModel, Cannot read property 'io' of undefined

### ISSUE THREAD

**Issue by EddieOne** [tensorflow/tfjs#292]
#### TensorFlow.js version
0.10.3

#### Browser version
Chrome 66

#### Describe the problem or feature request
I'm having problems loading a frozen model from mobilenet and tfjs convert. I get an error `TypeError: Cannot read property 'io' of undefined`. 

#### Code to reproduce the bug / link to feature request

```html
<!doctype html>
<html lang="en">
<head>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
</head>
<body>
  <img style="display: none" id="cat" src="high-detail.jpg" width="224" height="224">

  <script>
    const MODEL_URL = 'https://storage-direct.y8.com/eddie/html5/canvas-friends/detail_js/tensorflowjs_model.pb';
    const WEIGHTS_URL = 'https://storage-direct.y8.com/eddie/html5/canvas-friends/detail_js/weights_manifest.json';

    async function loadModal() {
      const model = await tf_converter.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
    }
    loadModal()
    //const cat = document.getElementById('cat');
    //model.execute({input: tf.fromPixels(cat)});
  </script>
</body>
</html>
```

**Comment by ichitaka** [comment]
Having the exact same issue with the Mobilenet demo.

**Comment by davidsoergel** [comment]
I'm pretty sure this is due to a package versioning problem.  The current tfjs-converter release depends on tfjs-core 0.10.0, but the tfjs union package release (0.10.3) provides only tfjs-core 0.8.3.

The tf.io package was introduced in tfjs-core between those two versions, and tfjs-converter requires it (due to https://github.com/tensorflow/tfjs-converter/pull/99).

So I think the solution will be for us to release a new tfjs union package asap.  And in the future, we'll need to make sure we always do that whenever there is a tfjs-converter release that requires it.

**Comment by nsthorat** [comment]
Working on a fix right now, but if you use an older version of the converter you won't have the issue:

`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@0.2.0"></script>`

**Comment by pyu10055** [comment]
or if you are only using converter you can replace the union package with
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"> </script>

**Comment by kylemcdonald** [comment]
I'm also seeing this, but can't use an old version of tfjs-converter because I want to load a model that was converted by the most recent tfjs-converter. If I use the older version I get:

```
tfjs-converter@0.2.0:1 Uncaught (in promise) Error: Tensorflow Op is not supported: StridedSlice
    at e.mapNode (tfjs-converter@0.2.0:1)
    at tfjs-converter@0.2.0:1
    at Array.reduce (<anonymous>)
    at e.transformGraph (tfjs-converter@0.2.0:1)
    at e.<anonymous> (tfjs-converter@0.2.0:1)
    at n (tfjs-converter@0.2.0:1)
    at Object.next (tfjs-converter@0.2.0:1)
    at i (tfjs-converter@0.2.0:1)
```

**Comment by EddieOne** [comment]
Ah, I wish Google groups would show in Google search. 😞  0.2.0 is no good. `Error: Tensor is disposed.`

**Comment by bileschi** [comment]
Yes, sorry for the trouble.  Newer tfjs-converters should not have this problem.  All new problems now ;)

**Comment by EddieOne** [comment]
Should I still wait or what is the solution? :)

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.1"> </script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@0.3.1"></script>
```

No luck with the above code

**Comment by caisq** [comment]
@EddieOne Sorry for closing the issue prematurely. Please wait for some additional changes that need to go into tfjs-converter.

**Comment by EddieOne** [comment]
Ok I thought so. Sorry, I've been waiting since Tensor Fire. I'm pretty sure tfjs will be very important in the near future, so good to see a lot of interest now.

**Comment by nsthorat** [comment]
Apologies for the delay, once we release this will be fixed. I have a fix pending in this PR: https://github.com/tensorflow/tfjs-converter/pull/136

I hosted a temporary version of the tf-converter for you until we release a new version of the converter (which will happen on Monday). This link will *not* be around forever, but if you really want to use it today you can use this:

<script src="https://storage.googleapis.com/dljs-test/rollup/tf-converter.js"></script>

The difference here is there is no more "tf_converter", only "tf". You call "tf.loadFrozenModel" like you would any other tf op.

**Comment by EddieOne** [comment]
It works! Thank you brother. The first time you see TensorFlow in JS for yourself, it's magical.

**Comment by nsthorat** [comment]
Remember, don't rely on this link ;) We'll have a release tomorrow!
