### ISSUE TITLE
tfjs-react-native bundleResourceIO can't load file with whitespace in it

### ISSUE THREAD

**Issue by lukeforehand** [tensorflow/tfjs#2924]
https://github.com/tensorflow/tfjs/blob/68b830c0bf1a0661c213ec0b6d89f7cf95f7a40e/tfjs-react-native/src/bundle_resource_io.ts#L120

```
base64Weights = await RNFS.readFile(weightsAsset.uri.replace(/%20/g, '\ '), 'base64');
```

**Comment by lukeforehand** [comment]
or perhaps
```
base64Weights = await RNFS.readFile(decodeURI(weightsAsset.uri), 'base64');
```

**Comment by rthadur** [comment]
We will not be support this, you need to make sure white spaces are not there in the file name.
