### ISSUE TITLE
Explore possibility of reducing bundle size

### ISSUE THREAD

**Issue by manrajgrover** [tensorflow/tfjs#293]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10

#### Browser version
NA

#### Describe the problem or feature request
Currently, uglify does not remove trailing new lines, whitespaces, and comments in template strings being used in shaders. This is justifiable as uglify does not know whether the template string has code or text and what user intends to do with it. Given that we know template strings in certain files contain shaders, we can look into removing newlines, spaces, and comments and thus reducing size of bundle even further in tensorflow/tfjs-core.

Link to bundle: https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core

#### Code to reproduce the bug / link to feature request
NA

**Comment by dsmilkov** [comment]
Thanks for opening this issue as a place to brainstorm ideas for bundle size reduction.

Regarding the particular proposal about shader code: my sense is that you won't get much savings, especially since the bundle is served as gzipped content - at least not enough savings to justify the additional build/deploy complexity.

**Comment by alippai** [comment]
Added https://github.com/tensorflow/tfjs-core/pull/1401

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
This is something we're still planning on doing.

**Comment by gaikwadrahul8** [comment]
Hi, @manrajgrover 

Apologize for the delayed response and we're revisiting our older issues and checking whether those issues got resolved or not, I see we have updated our official documentation for [Generating size-optimized browser bundles with TensorFlow.js](https://www.tensorflow.org/js/tutorials/deployment/size_optimized_bundles), please refer webpack ([full example here](https://github.com/tensorflow/tfjs/blob/master/e2e/custom_module/dense_model/webpack.config.js)) and rollup ([full example here](https://github.com/tensorflow/tfjs/blob/master/e2e/custom_module/dense_model/rollup.config.js)) which will help you to resolve your issues. Thank you!
