### ISSUE TITLE
Missing changelogs

### ISSUE THREAD

**Issue by Polarisation** [tensorflow/tfjs#2936]
#### TensorFlow.js version
v1.6.0, v1.6.1, v1.7.0

#### Describe the problem or feature request

It would be helpful to have timely release notes for each new release, so users can stay informed of any new features or fixes.

The [releases page](https://github.com/tensorflow/tfjs/releases) does not include any notes since v1.5.2. Release notes are missing for v1.6.0, v1.6.1, v1.7.0.

I suggest making a process improvement here, so that these a changelog must be created as part of the release process.

**Comment by lina128** [comment]
Hi @Polarisation, thank you for letting us know. We added release log for v1.7.2. We will add the missing ones for 1.6.0, 1.6.1, and 1.7.0. For future release, we are going to automate this process, so that it is the changelog is always generated. Thank you for your suggestion!

**Comment by lina128** [comment]
The release logs for 1.6.0, 1.6.1, and 1.7.0 are also available to see now.
