### ISSUE TITLE
tensorflow texture size

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#2940]
I am getting an error on mobile browser swift that my texture is too big (over 4096 x 4096.) II am using mobilenet 1 without quantization. I was wondering how do I do systematically figure out  and reason what texture size is taken up by the model. Do I just make sure I don't have any layers have  bigger then 4096*4096 parameters, or is it dependent on the total number of parameters of the network.  Does quantization help? Any insights here  would be helpful.

**Comment by annxingyuan** [comment]
Hi @rohanmuplara. Unfortunately there's not a great way for users to measure the largest texture size for their models - as that number depends on details of our WebGL backend which may change. 

However there are some heuristics you could use to minimize the risk of coming up against the texture size limit, e.g. reducing the size of individual layers. The total number of parameters in the network doesn't matter. Quantization doesn't make a difference.

You might also want to try out our WebAssembly backend (`tf.setBackend('wasm')`) - in general it's a bit slower than our WebGL backend, but there are no textures to deal with :)

Good luck!
