### ISSUE TITLE
npm install fails when trying to install @tensorflow/tfjs-node@1.7.0

### ISSUE THREAD

**Issue by ghnp5** [tensorflow/tfjs#2941]
Getting this error:

```
> @tensorflow/tfjs-node@1.7.0 install /dock/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.7.0.tar.gz
* Downloading libtensorflow

* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v5/1.7.0/CPU-linux-1.7.0.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@1.7.0 and node@13.11.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
```

This URL doesn't seem to exist:

https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v5/1.7.0/CPU-linux-1.7.0.tar.gz

My package.json:

```
    "@tensorflow/tfjs": "^1.7.0",
    "@tensorflow/tfjs-node": "^1.7.0",
```

What can I do to be able to install tfjs-node?
Using CentOS 7 on a Docker container.

**Comment by rthadur** [comment]
@ghnp5 thank you, You only need to include @tensorflow/tfjs-node in the package.json file, since those packages ship with @tensorflow/tfjs already.

**Comment by ghnp5** [comment]
Thank you @rthadur . I tried that, actually (because I saw what you said, somewhere), but then this stops working:

const tf = require('@tensorflow/tfjs-node');

saying that the "tfjs-node" wasn't found.


I started over and did:

> npm install @tensorflow/tfjs
+ @tensorflow/tfjs@1.7.0
added 5 packages, removed 47 packages and audited 9833 packages in 40.167s


And the only folders in "@tensorflow" are:

tfjs
tfjs-converter
tfjs-core
tfjs-data
tfjs-layers

Unfortunately, tfjs-node isn't there.

**Comment by ghnp5** [comment]
Thank you @rthadur . I'm a bit confused, though:

> You only need to include @tensorflow/tfjs-node in the package.json file

Are you saying that I should only include this?

    "@tensorflow/tfjs-node": "^1.7.0",

Or are you saying I only need to include this?

    "@tensorflow/tfjs": "^1.7.0",


I started over and did:

> npm install @tensorflow/tfjs
+ @tensorflow/tfjs@1.7.0
added 5 packages, removed 47 packages and audited 9833 packages in 40.167s


And the only folders in "@tensorflow" are:

tfjs
tfjs-converter
tfjs-core
tfjs-data
tfjs-layers

Unfortunately, tfjs-node isn't there.

**Comment by rthadur** [comment]
That is other way around , you need to install only @tensorflow/tfjs-node.

**Comment by ghnp5** [comment]
Alright. That seems to have done the job, indeed!
Thank you very much.
