### ISSUE TITLE
Problem with deeplearnjs.org certificates

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#297]
Chrome warns me "Your connection is not private"

And yet when I proceed it is fine and mentions that things have moved to tensorflow.js

**Comment by bileschi** [comment]
Thanks for letting us know!  At some point deeplearnjs.org will redirect to js.tensorflow.org : see https://github.com/tensorflow/tfjs-website/issues/140 

Moving this issue to tfjs-website
https://github.com/tensorflow/tfjs-website/issues/151
