### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by akshaybabhulkar28** [tensorflow/tfjs#2972]
<!Doctype html>
<html>
<head>

    <title>Tensorflow.js linear regression</title>
   <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
   <script src ="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis"></script>
</head>

<body>

<script type="text/javascript">

        async function plot(pointsArray, FeatureName) {
            tfvis.render.scatterplot (
                {name : '${featureName} vs diabetes' },
                {values: [pointArray], series: ["original"] },
                {
                    xLabel: featureName,
                    yLabel: "Glucose",
                })
                }
        async function run ()
     {
        await tf.ready();

        const diabeticDataset = tf.data.csv("http://localhost:52098/diabetes.csv");
        const SampleDataset = diabeticDataset.take(10);
        const dataArray = await SampleDataset.toArray();
        console.log(dataArray);
        const points = diabeticDataset.map(record => ({
            x: record.outcome,
            y: Glucose,
        }));
            plot(await points.toArray(), "outcome")
           
        }
       

        run();
    </script>

</body>
</html>

tf version: {tfjs-core: "1.7.0", tfjs-data: "1.7.0", tfjs-layers: "1.7.0", tfjs-converter: "1.7.0", tfjs: "1.7.0"}
browser: google chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by akshaybabhulkar28** [comment]
error: Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by rthadur** [comment]
@akshaybabhulkar28 can you please provide steps followed if possible an codepen example ?

**Comment by akshaybabhulkar28** [comment]
<!Doctype html>
<html>
<head>
    <title>Tensorflow.js linear regression</title>
   <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
</head>
<body>
 
    <script type="text\javascript">
        async function run () {
        const diabeticDataset = tf.data.csv("http://localhost:52098/diabetes.csv");
        const SampleDataset = diabeticDataset.take(10);
        const dataArray = await SampleDataset.toArray();
        console.log(dataArray);
        }
 
        run();
    </script>
 
</body>
</html>

**Comment by rthadur** [comment]
is it possible to share .csv or any example data ?

**Comment by akshaybabhulkar28** [comment]
Yes,here it is.


On 03-Apr-2020, at 8:46 AM, Rajeshwar Reddy T <notifications@github.com<mailto:notifications@github.com>> wrote:



is it possible to share .csv or any example data ?

**Comment by rthadur** [comment]
@akshaybabhulkar28 i can't see .csv , can you paste contents of csv in a gist please ?
