### ISSUE TITLE
tfjs@latest:2 Uncaught (in promise) Error

### ISSUE THREAD

**Issue by arshadshk** [tensorflow/tfjs#2989]
following error is shown in console - 
tfjs@latest:2 Uncaught (in promise) Error: Provided weight data has no target variable: bidirectional_1/forward_lstm_1/lstm_cell_4/kernel
    at new e (tfjs@latest:2)
    at e.loadWeights (tfjs@latest:2)
    at tfjs@latest:2
    at tfjs@latest:2
    at Object.next (tfjs@latest:2)
    at o (tfjs@latest:2)
e @ tfjs@latest:2
e.loadWeights @ tfjs@latest:2
(anonymous) @ tfjs@latest:2
(anonymous) @ tfjs@latest:2
(anonymous) @ tfjs@latest:2
o @ tfjs@latest:2
async function (async)
run @ l2.html:7
(anonymous) @ l2.html:14

#### TensorFlow.js version
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"> </script>   
using pretrained model using keras, and chrome browser

**Comment by lina128** [comment]
Hi @arshadshk, does it happen on other versions too? You can change this line to: <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.7.0"> </script>

**Comment by arshadshk** [comment]
Hey @lina128  same problem with 1.7.0

**Comment by arshadshk** [comment]
Resolved.
Used tensorflowjs_wizard and selected Keras HDF5 with 2x compression.
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest">

*Earlier used colabs. Now converted on local machine with tensorflow.js 1.6.0.

Thanks
