### ISSUE TITLE
[WASM] Implement of batchToSpaceND

### ISSUE THREAD

**Issue by akineeic** [tensorflow/tfjs#2994]
Hello, I want to do inference with [SRGAN](https://arxiv.org/abs/1609.04802) (a super resolution model) but found there is no implement of batchToSpaceND in tfjs-backend-wasm. So I'd like to know do you have plan to implement this op in tfjs-backend-wasm since it's a commonly used op in super resolution model. 

Looking forward to your reply.

**Comment by annxingyuan** [comment]
Hi @akineeic - yes this is on our medium-term roadmap - batchToSpaceND and spaceToBatchND are required for models in our repo as well (e.g. DeepLab).

**Comment by akineeic** [comment]
Thanks for your quickly reply. By the way, I'm wondering if your goal is to make wasm backend the same as webgl. For example the [maximum](https://github.com/tensorflow/tfjs/blob/8c2e0b241dc14b1847255c88260642674e7b84e5/tfjs-backend-wasm/src/setup_test.ts#L244-L245) in wasm doesn't support broadcasting along inner dims yet, will you still try to implement these missing features.

**Comment by annxingyuan** [comment]
Yes, we would like our backends to be interchangeable with each other as much as possible. We are gradually adding features to our WASM backend. We look to GitHub issues (like this one) for signal on which features should be prioritized :)

**Comment by akineeic** [comment]
Thanks for your information, that is helpful for me.

**Comment by F0REacH** [comment]
spaceToBatchND is the only kernel stopping WASM use in production. Please add this feature.
