### ISSUE TITLE
gramSchmidt-non-tiny unit tests takes > 3.5 seconds on a 1080GTX.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#300]
We should try to keep tests under 250ms as this will slow everyone down.

**Comment by bileschi** [comment]
@caisq Should we:
1. Do nothing
2. Reduce the size of the gramSchmidt matrix to get the test under time cap
3. Remove the test altogether
4. Something else
?

**Comment by caisq** [comment]
Maybe 2. I think the test is running under test time cap and passes. It's just showing up in the "slow tests" warning.

**Comment by nsthorat** [comment]
Yep, it's just a warning. I think 2 makes sense.

**Comment by nsthorat** [comment]
These tests are taking ~16 seconds on my beefy linux machine, which is a considerable chunk of time.

Any chance we can prioritize this?

**Comment by bileschi** [comment]
Attempted reducing the size to see if we can get this under 250ms.  It is not really possible within the spirit of the test.  Reducing down to 8x8 is still 580ms.

How about we reduce this 'gramSchmidt-non-tiny' from 32x512 to 16x128, which reduced the time from 2500ms to 800ms on my machine. 

FYI.  Simply running compiling and running the test suite, without actually doing any matrix work at all costs about 5 seconds worth of overhead:

https://github.com/tensorflow/tfjs-core/pull/1426
