### ISSUE TITLE
I can't run example tfjs-react-native? Any one help me

### ISSUE THREAD

**Issue by duylinhdang1998** [tensorflow/tfjs#3001]
I get error with react-native-unimodules when I run app. 
Help me please

**Comment by rthadur** [comment]
please provide more details using the template so that we can better assist you.

**Comment by duylinhdang1998** [comment]
I got error like this. I don'tt understand lib tfjs-react-native conflict with react-native-unimodules 
If I remove react-native-unimodules  I can't use tfjs-react-native. If i don't import tfjs-react-native my app is worked. I using react-native 0.61.2
![image](https://user-images.githubusercontent.com/40199004/78092251-7c703200-73f9-11ea-96b2-c8ccfb1da2d6.png)
Here my code: 
![image](https://user-images.githubusercontent.com/40199004/78092449-09b38680-73fa-11ea-881d-7ffd266b0963.png)
