### ISSUE TITLE
Unresponsive script error when using tensorflow js in firefox add-on

### ISSUE THREAD

**Issue by kaushiksa** [tensorflow/tfjs#3014]
TensorFlow.js version: 1.7.1

Browser version Firefox v74

For my web application, I use **TensorFlow js with BlazeFace model** to recognize the number of people present in a frame from a live camera feed. Since it used to blocked my UI, I shifted all my code to a extension/add-on which runs with my web-page. The whole setup (including the extension )works like a charm in chrome.But when I do the same on firefox (even when using firefox add-on), the prediction for the first time takes lot of time and apparently **firefox shows an unresponsive script message**. I've also tried using different models for tensorflow-js and I see this issue in all of them. Also, the same message comes up when I open the demo page hosted by blazeface in firefox. I don't see the same issue in chrome. 

![image](https://user-images.githubusercontent.com/31251013/78214125-0f7c9b00-74d2-11ea-8bb3-af9b92bc7e64.png)

![image](https://user-images.githubusercontent.com/31251013/78214592-44d5b880-74d3-11ea-9bdc-e410fd944b6d.png)

Steps to reproduce this issue:
Open the following in firefox:
https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html
Choose webgl backend

**Comment by pyu10055** [comment]
@kaushiksa The first execution is much slower, since it compiles the webgl shaders for the model. You can try to add a warmup prediction with all zero tensors right after the model is loaded in your extension, see if that can help to avoid the error message.

**Comment by kaushiksa** [comment]
@pyu10055 I did try out a warmup prediction by adding the below in the blazeface library, I still get that message. Am I doing something wrong here?
```
async dummyload(){
    this.blazeFaceModel.predict(tf.zeros([1, 128,128, 3]));
  } 
```

**Comment by rthadur** [comment]
@kaushiksa did you get chance to look at similar issue [here](https://github.com/tensorflow/tfjs/issues/2301) ?

**Comment by kaushiksa** [comment]
@rthadur Yes, I did some optimizations based on those suggestions but I am still getting the warning message. Also, it comes up on the demo page of blazeface itself in firefox (on the web application). https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html
I also get this console warning when i run my prediction for this model:
![image](https://user-images.githubusercontent.com/31251013/78753083-dbeab680-7992-11ea-98a8-3c0354b76027.png)
I tried replacing nonMaxSuppression with nonMaxSuppressionAsync in the blazeface library to see if it works, but got this 
![image](https://user-images.githubusercontent.com/31251013/78754015-654eb880-7994-11ea-9af8-6c0b10e0ed42.png)

**Comment by rthadur** [comment]
I did not see error while running now. @pyu10055 can you please suggest on the warning.

**Comment by rthadur** [comment]
cc @annxingyuan can you please suggest on the warning ?

**Comment by wingman-jr-addon** [comment]
@kaushiksa For what it's worth, I use TF.js to load a MobileNetV2-based model in a Firefox plugin. I choose to take the hit by loading it as part of the background scripts rather than a content script. The main load takes 10+ seconds but I do not get that message, presumably because of that. Would it be an option to move the usage of the TF.js to the background? I know that's less than ideal if you are trying to ferry around lots of image data etc. though...
See the repo [here](https://github.com/wingman-jr-addon/wingman_jr) if you are interested.
