### ISSUE TITLE
api docs listing members of tensor class in return type

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#3017]
Somewhere along the way the doc generator/website expanded Tensor types in the return value to list all their properties it does this in multiple places.

#### TensorFlow.js version
visible in 1.7.1

<img width="1180" alt="Screen Shot 2020-04-02 at 3 14 34 PM" src="https://user-images.githubusercontent.com/26408/78292343-defa2880-74f4-11ea-9197-b7158e56fd56.png">

**Comment by rthadur** [comment]
Related PR has been merged and changes are now available. closing this issue.
