### ISSUE TITLE
Wrong typing for MobileNet interface

### ISSUE THREAD

**Issue by MikeMitterer** [tensorflow/tfjs#3022]
#### TensorFlow.js version
1.7.1

#### Browser version
Version 80.0.3987.149

#### Describe the problem or feature request
I'm following this CodeLab:
https://codelabs.developers.google.com/codelabs/tensorflowjs-teachablemachine-codelab/index.html?index=..%2F..index#6

There is a line which shows:
```typescript
      // Get the activation from mobilenet from the webcam.
      const activation = net.infer(img, 'conv_preds');
```
As you can see - the second param is a string.
But here https://github.com/tensorflow/tfjs-models/blob/master/mobilenet/src/index.ts#L150
the second param is an optional boolean...

If I marke the line from above with `// @ts-ignore` everything works...

This leads to:
![Bildschirmfoto 2020-04-03 um 12 22 55](https://user-images.githubusercontent.com/116654/78350801-170d7400-75a6-11ea-907e-8588b68b8448.png)

**Comment by rthadur** [comment]
@MikeMitterer thanks for reporting , we will check and get back to you.

**Comment by rthadur** [comment]
@MikeMitterer codelab will be updated , meanwhile can you use boolean for embedding.

**Comment by rthadur** [comment]
This is fixed now , thank you
