### ISSUE TITLE
Weights Zeroed On Loading Saved Model

### ISSUE THREAD

**Issue by joeedh** [tensorflow/tfjs#3046]
#### TensorFlow.js version
1.7.2
#### Browser version
Chrome  80.0.3987.163

#### Describe the problem or feature request

When I load a model saved to localstorage with model.save(), it doesn't load any weights.  However there is weight data in localStorage, and model.save()'s return value says it is saving weights.  But when I look at the weight data on the loaded model it's all zeroed.

**Comment by rthadur** [comment]
@joeedh can you please share the steps to reproduce the issue ?

**Comment by joeedh** [comment]
Hi.  So I tracked the problem to a bad polyfill buried in my code.  Sorry, my bad.
