### ISSUE TITLE
Posenet 2.0 in TFLite format.

### ISSUE THREAD

**Issue by vpenades** [tensorflow/tfjs#3048]
#### TensorFlow.js version

Emgu.TF 2.1.0.838

#### Describe the problem or feature request

Hi, I've been using `posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite`, and I've realized there's a Posenet 2.0 for a while now... I've been looking at the code at https://github.com/tensorflow/tfjs-models/tree/master/posenet , and I've noticed the posenet 2.0 models are now delivered as js/weights files.

So first of all, I would like to request, if that's possible, the MobileNet1 and ResNet50 models for Posenet 2.0, as TFLite files.

Second question is, given the new TFLite files are available: can I use them with the same code I was using with `posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite`? or do I need to do changes to it?

Additionally, it could be very useful if the examples here: https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android could be updated to use the latest tflite trained models of posenet 2.0.

Thanks in advance!

**Comment by lyuboraykov** [comment]
+1, especially for the ResNet50 variant.

**Comment by rthadur** [comment]
You can use tfjs-tflite to load the models from tflite , please check here for more details 
https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite
