### ISSUE TITLE
tensorflowjs Dockerfile

### ISSUE THREAD

**Issue by kylemcdonald** [tensorflow/tfjs#305]
I would like to request a single Dockerfile that builds the latest tensorflowjs from source. This will help folks who want to test features before they are published. I've done my best to create a Dockerfile based on miniconda3: https://gist.github.com/kylemcdonald/4ee140f527e1c6c9ae3fd12dd8bb6b3b

I tried to combine everything I learned from these documents:

- https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md
- https://github.com/tensorflow/tfjs-core/blob/master/DEVELOPMENT.md
- https://github.com/tensorflow/tfjs-layers/blob/master/DEVELOPMENT.md
- https://github.com/tensorflow/tfjs-converter/blob/master/DEVELOPMENT.md

I've verified that the Dockerfile builds, but need to check that it has actually installed everything correctly and is actually useful :) Update: afaict everything is working correctly. I made one small change since posting to run `yarn && yarn build-npm` for `tfjs-converter`.

**Comment by kylemcdonald** [comment]
Hey! I'm working on something that needs the most up-to-date converter again, and I wanted to check if this is still the best Dockerfile for building everything. If so, I will add it to the gallery under "Tutorials".

**Comment by nsthorat** [comment]
That dockerfile still looks good to me! Thanks Kyle!

**Comment by manrajgrover** [comment]
Great work @kylemcdonald! Just sharing another [quick docker setup](https://gist.github.com/manrajgrover/84f73a295f85e5902a9239fa698b7603) here that I wrote long back for consumption purpose. Let me know if you need any assistance.

**Comment by rthadur** [comment]
@kylemcdonald  checking if the we can close this issue ?
