### ISSUE TITLE
[wasm] Add SquaredDifference kernel.

### ISSUE THREAD

**Issue by santhiya-v** [tensorflow/tfjs#3053]
#### tfjs-node / tfjs-backend-wasm version
1.7.2

#### Problem
I am running my model using tfjs-node code and it works fine(tensorflow backend). When I try to use 'wasm' backend (for performance), I get following error :

`Error: 'squaredDifference' not yet implemented or not found in the registry. Did you forget to import the kernel?`

#### Model : 
I am using the transformer model (depthwise separable convolutions) from https://github.com/reiinakano/arbitrary-image-stylization-tfjs

Is there any way support for this kernel in 'wasm' can be achieved?

Thanks.

**Comment by annxingyuan** [comment]
Hi @santhiya-v - thanks for reporting this - we aim to add kernels to our WASM backend gradually in response to user need, which we assess by looking at issues like this one :)

However you say you want to use the wasm backend for performance - I wonder whether you might get better performance with our default WebGL backend instead.

**Comment by janakg** [comment]
@annxingyuan  thanks for the response. 

We are trying in both node and browser. In a browser with WebGL mode, toPixel() takes a long time in subsequent calls.

So we are trying in node with wasm backend for faster predict() , but we are limited by wasm's kernel support.

Please let us know if we are missing something.

**Comment by alvinsunyixiao** [comment]
@annxingyuan - Hi, I have put up a PR #3784. Could you help review it? Thanks!

**Comment by rthadur** [comment]
Related PR is merged now , closing this issue.Thank you
