### ISSUE TITLE
Build tfjs using Emscripten

### ISSUE THREAD

**Issue by vasanthhr** [tensorflow/tfjs#3057]
Hello,

Would it be possible to build the tf-backend-wasm.js(wasm) ourselves using Emscripten library.

(Note: opencv supports to build their c++ code to opencv.js(wasm) using Emscripten ).

Is there any way we could get configuration files and guidance where we can modify the tfjs files ourselves to build the tf-backend-wasm.js(wasm) ?

**Comment by tafsiri** [comment]
All the build scripts and config are in the repostiry, you can take a look at the [package.json](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/package.json#L22) and the [build-wash.sh](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/scripts/build-wasm.sh) to see how the toolchain gets kicked off. We use bazel to actually run the build (compilation done via emscripten) so you can look at the .bazelrc or toolchain file for more details on that. We can't really give more pointers on a different way to set up the build though i'm sure its possible.
