### ISSUE TITLE
Quantization aware training

### ISSUE THREAD

**Issue by stbnps** [tensorflow/tfjs#3068]
#### TensorFlow.js version
1.7.2

#### Browser version
None

#### Describe the problem or feature request
After training a model with quantization aware training and saving the model to a .h5 file, when trying to convert the quantized model to javascript using tensorflowjs_wizard, it says: `ValueError: Unknown layer: QuantizeWrapper`

#### Code to reproduce the bug / link to feature request
```
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
import tensorflow_model_optimization as tfmot

def apply_quantization(layer):
  if not isinstance(layer, tf.keras.layers.Concatenate):
    return tfmot.quantization.keras.quantize_annotate_layer(layer)
  return layer


model = MobileNetV2(weights=None)

annotated_model = tf.keras.models.clone_model(model, clone_function=apply_quantization)
model = tfmot.quantization.keras.quantize_apply(annotated_model)
model.save('model.h5')
```
Then:
`tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model --quantization_bytes=1 --weight_shard_size_bytes=4194304 model.h5 out`

Thanks!

**Comment by rthadur** [comment]
I believe the api is not yet implemented in tfjs , @pyu10055 do you know if this is in the roadmap ?
