### ISSUE TITLE
Uncaught TypeError: tf.roll is not a function

### ISSUE THREAD

**Issue by leoffx** [tensorflow/tfjs#3083]
#### TensorFlow.js version
1.7.4 from https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest

#### Browser version
Google Chrome Version 81.0.4044.92 (Official Build) (64-bit)

#### Describe the problem or feature request
Function tf.roll isn't working.

#### Code to reproduce the bug / link to feature request
a = tf.randomUniform([4, 4]);
tf.roll(a, 1, 1);
>Uncaught TypeError: tf.roll is not a function

**Comment by rthadur** [comment]
@leoffx tf.roll is not implemented in tfjs, thats the reason you are getting this error.

cc @pyu10055 @dsmilkov
