### ISSUE TITLE
Wasm: implementing cumsum

### ISSUE THREAD

**Issue by davidpham87** [tensorflow/tfjs#3092]
Hello,

I would be interested to have a cumulative sum/prod in WASM. The reason is I want to implement a rolling average.

I wonder if the reductions (see Clojure reductions) would make sense.

Best regards,
David

**Comment by alvinsunyixiao** [comment]
Is there any recent plans for supporting this for the wasm backend?

**Comment by rthadur** [comment]
It is in our todo list , there is no fixed timeline as of now , please let us know if you would like to contribute.

**Comment by alvinsunyixiao** [comment]
@rthadur I would like to give it a try. But I have limited TypeScript experience, is there a starting point or examples of other operators I could follow?

**Comment by annxingyuan** [comment]
Hi @alvinsunyixiao - WASM cumsum would be an awesome contribution! Here is a recent PR adding support for reverse to WASM: https://github.com/tensorflow/tfjs/pull/3526

I think cumsum could follow a similar format. You can use the CPU implementation as a reference for the kernel logic: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-cpu/src/backend_cpu.ts#L619

In case it's helpful, here's a guide to contributing: https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md

Please let us know if you run into any snags!

**Comment by alvinsunyixiao** [comment]
Hi @annxingyuan, thanks for the pointer! I just made time for starting to implement this. I noticed the CPU backend implementation asserted `axis === x.rank - 1`. Do we expect the same behavior for wasm? Or should I try generalize this to all axis?

**Comment by annxingyuan** [comment]
Hi @alvinsunyixiao - I would say maybe try to implement it for the axis === x.rank - 1 case first, then we can generalize it in a follow-up PR!

**Comment by alvinsunyixiao** [comment]
Hi @annxingyuan - Should I replicate [this](https://github.com/tensorflow/tfjs/blob/2bc0cebf68ffe27a57f8a0823a0cc9442a48556b/tfjs-core/src/ops/cumsum.ts#L57) permutation logic with WASM transpose kernel?

**Comment by alvinsunyixiao** [comment]
It seems like `Sum` is also assuming a `float32` input, but I didn't see an assertion anywhere ensuring that dtype. Is that expected?

**Comment by alvinsunyixiao** [comment]
Hi @annxingyuan - I have just created a PR #3782. Thanks for the help!

**Comment by rthadur** [comment]
related PR is merged now , closing this issue.
