### ISSUE TITLE
tfjs + Distributed TensorFlow?

### ISSUE THREAD

**Issue by larrylindsey** [tensorflow/tfjs#310]
Hello, tfjs looks awesome! I'm curious if there is support, or planned support for using tfjs in a distributed way? (I'm thinking in this sense: https://www.tensorflow.org/deploy/distributed)

**Comment by caisq** [comment]
@larrylindsey Thanks for the inquiry. Are you thinking of distributed training with node.js in the backend or with some sort of novel paradigm in the frontend?

**Comment by timblakely** [comment]
TF in the browser is limited to the computation available locally. Model performance will likely be limited on mobile platforms, including laptops, a common platform for web developers. In addition, many laptops don't have discrete graphics cards, so reaching out to remote workers that have significantly larger compute resources (e.g. a cloud instance of TF with one more more V100s) would allow significant performance increases in both training and inference, especially on larger networks.

**Comment by bileschi** [comment]
The plan for distribution of training depends on the use developer's use case.  If your team is using a node stack, the team is investing to make distributed training work there.  If your team is already invested in the python tensorflow stack, it is possible to export a TFJS model into a format that Python Keras can ingest, and use the model_to_estimator workflow to run your model using the distribution strategies available there.

https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator

Does this help?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by vilorel** [comment]
> @larrylindsey Thanks for the inquiry. Are you thinking of distributed training with node.js in the backend or with some sort of novel paradigm in the frontend?

Any news on distributed training with node.js in the backend? @bileschi thanks for the link, I'd rather not port to Python...

**Comment by thankrandomness** [comment]
Hi, I am looking for references/resources to help discover ways to do distributed training in kubernetes with node.js backend. Would be great if anyone can update on the current state and any future possibility. Thanks!
