### ISSUE TITLE
Issue when using tensorflowjs_converter

### ISSUE THREAD

**Issue by carlos-aguayo** [tensorflow/tfjs#3102]
#### TensorFlow.js version
2.1.0

#### Browser version
Chrome 80

#### Describe the problem or feature request
I'm converting a Keras model to be used with Tensorflow.js

I was using '`tensorflowjs_converter`' and when loading the model in the browser using I got an:
`"Uncaught (in promise) Error: Provided weight data has no target variable: bidirectional_19/forward_lstm_19/lstm_cell_58/kernel"`

I found out that if I instead use '`tfjs.converters.save_keras_model`', that works fine!

I noticed the both methods generated the same weights file but different JSON file.

I also noticed that the '`tensorflowjs_converter`' tool seems to be getting a different version of Keras and I don't know why.

#### Code to reproduce the bug / link to feature request
I put together this [Colab notebook](https://colab.research.google.com/drive/154F0TjsixbJYlTqTNnvjfeDwih0VL1hT) that should make it easy to see the problem.

<img width="1233" alt="2020-04-18_1155" src="https://user-images.githubusercontent.com/338917/79642477-a6508500-816b-11ea-8aac-8d73267ecb4e.png">

**Comment by pyu10055** [comment]
@caisq can you take a quick look if anything looks suspicious. thanks

**Comment by rthadur** [comment]
this is fixed [here](https://github.com/tensorflow/tfjs/issues/3314) , thank you
