### ISSUE TITLE
Error: Backend name 'undefined' not found in registry

### ISSUE THREAD

**Issue by sauceishere** [tensorflow/tfjs#3105]
This error shows up at 'console.log('Error tf.setBackend(): ', error);' when I run the below code to run load posenet.  
I used to use 'tf.ready()' and worked completely fine several weeks ago, but now this error shows up.
Please advise how to solve this.
Thank you.

> Error: Backend name 'undefined' not found in registry

Versions are:
expo --version 3.11.7
node --version v12.14.1
npm -version 6.13.4
@ tensorflow/tfjs-react-native@0.2.3
@tensorflow-models/posenet@2.2.1
@tensorflow/tfjs@1.7.2

```
import * as React from 'react';
import * as tf from '@tensorflow/tfjs';
import * as posenet from '@tensorflow-models/posenet';

export default class Notification extends React.Component {
  inputTensorHeight = 200;
  inputTensorWidth = 152;

  async componentDidMount() {

    await tf.setBackend().then( ref => {
      console.log('--------- tf.setBackend');
    }).catch(function(error) {
      console.log('Error tf.setBackend(): ', error);
    });   

    const posenetModel =  await posenet.load({ 
      architecture: 'MobileNetV1',
      outputStride: 16, 
      inputResolution: { width: this.inputTensorWidth, height: this.inputTensorHeight },
      multiplier: 0.75, 
      quantBytes: 2 
    }).then( ref => {
      console.log('--------- posenet loaded.');
    }).catch(function(error) {
      console.log('Error posenet.load: ', error);
    });   
}
```

**Comment by pyu10055** [comment]
@sauceishere 
tf.setBackend method requires the backend name, https://js.tensorflow.org/api/latest/#setBackend

what are you trying to do here? The default backend is 'webgl', it will be enabled by default, you don't need to set it manually.

**Comment by sauceishere** [comment]
@pyu10055 thanks. I just want to run posenet on react native, and it did work well a couple of week ago, but It does not work now. I think I did not change any, that's why I can not figure out what's going on here. Is there any way I can check if 'webgl' works fine? Thank you.

**Comment by tafsiri** [comment]
@sauceishere you should not set the backend manually. But you do need to import the tfjs-react-native adapter (`import '@tensorflow/tfjs-react-native';`). See sample code here https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#step-6-test-that-it-is-working

**Comment by sauceishere** [comment]
@tafsiri Thanks. I run the below code, it showed '--- 4' and suddenly shut down without showing any error code. Do you have any idea what I should change?

```
import { StyleSheet, Text, View } from 'react-native';
import * as React from 'react';
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isTfReady: false,
    };
  }

  async componentDidMount() {
    // Wait for tf to be ready.
    console.log('--- 0');
    await tf.ready();
    // Signal to the app that tensorflow.js can now be used.
    console.log('--- 1');
    this.setState({
      isTfReady: true,
    });
    console.log('--- 2');
  }


  render() {
    console.log('--- 4');
    return(
      <Text> Hello </Text>
    )
  }

}
```

**Comment by sauceishere** [comment]
@rthadur My code is https://github.com/sauceishere/tf-ready-20200426 , and Expo version is 3.18.6. Please advise if you find something. Thanks!

**Comment by tafsiri** [comment]
@sauceishere I think you are going to have to do a bit more digging to get help with debugging this. Without more detailed info about what encironment you are running in and what error is happening we won't be able to effectively look into this.

If you aren't seeing any errors from expo/javascript, try looking into the device logs to see what is output by the mobile device before the app shuts down. The [react native docs](https://reactnative.dev/docs/debugging#accessing-console-logs) have some more details on how to do this. Note you cannot use tfjs-react-native in a simulator.

**Comment by sauceishere** [comment]
It solved upon switch from Developer mode to Production mode on Expo. Thanks.
