### ISSUE TITLE
Layers API: Add stopTraining to tf.Model.fit() callback logic

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#312]
#### TensorFlow.js version
0.11.1

Currently tf.Model.fit() does not support stopping of training by callbacks. The same logic exists in Keras and we should add it to tfjs as well.

**Comment by VeegY** [comment]
Hey there, is it possible to get a quick example in here? I can not get things to work properly right now.
I am using tfjs-layers v0.7.1 and my code looks like the following (bare minimum):
```javascript
await this.model.fit(data,labels, {
  epochs: 2
     callbacks: {
      onBatchEnd: () => {
         this.model.stopTraining = true;
     }
  },
}
```

To be fair, I am pretty new to javascript, so it might be a mistake elsewhere.
Thanks in advance!
