### ISSUE TITLE
tf.fromPixels() function throw an error under 0.11.1

### ISSUE THREAD

**Issue by PengWang0316** [tensorflow/tfjs#313]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.1
#### Browser version
Chrome Version 66.0.3359.181
#### Describe the problem or feature request
After updated the Tensor Flow js to 0.11.1, the tf.fromPixels() function throw an error:
Uncaught (in promise) TypeError: Cannot read property 'drawImage' of null
    at MathBackendWebGL.fromPixels (backend_webgl.js:181)
    at Engine.fromPixels (engine.js:302)
    at ArrayOps.fromPixels (array_ops.js:292)
    at eval (operation.js:12)
    at Tracking.tidy (tracking.js:39)
    at Object.descriptor.value (operation.js:12)
    at eval (Webcam.js:69)
    at Object.Tracking.tidy (tracking.js:39)
    at Webcam.capture (Webcam.js:66)
    at eval (index.js:288)
The code is come from webcam-transfer-learning (Transfer Learning to play Pacman via the Webcam) and run perfectly under the version 0.10.0
#### Code to reproduce the bug / link to feature request
Html has this element:
<video autoplay playsinline muted id="webcam" width="224" height="224"></video>

JS code as below:
tf.fromPixels(document.getElementById('webcam'));

**Comment by PengWang0316** [comment]
Really exciting about this new version which can let me use Tensorflow js to my project with the new saving model feature. 👍

**Comment by furkilic** [comment]
Same as @PengWang0316 and @creativesands, very excited to save my model but unfortunately tf.fromPixel throws an error with the new version

**Comment by yellowmouse90** [comment]
I resolve using ImageData type.
FromPixel throw error from HTMLVideoElement, HTMLImageElement and HTMLCanvasElement but it works with ImageData

**Comment by nsthorat** [comment]
@dsmilkov @caisq can you prioritize this? I am currently out of office.

**Comment by caisq** [comment]
@dsmilkov Any thoughts on possible causes of this bug? I'm not very familiar with `tf.fromPixels()`.

**Comment by dsmilkov** [comment]
I can take a look today. It is possible that something changed in Chrome - will investigate and update this thread.

**Comment by dsmilkov** [comment]
Fix is ready in https://github.com/tensorflow/tfjs-core/pull/1064
