### ISSUE TITLE
Uncaught (in promise) Error: Error in matMul: inputs must have the same rank of at least 2, got ranks 4 and 2.

### ISSUE THREAD

**Issue by Whiax** [tensorflow/tfjs#3136]
#### TensorFlow.js version
TFJS: 1.7.2
TF: 2.1.0
ONNX: V9

#### Browser version
Chrome / 74.0.3729.134

#### Describe the problem or feature request
Converting Pytorch Squeeze-Excitation module. Two methods, one using Linear found [here](https://github.com/jonnedtc/Squeeze-Excitation-PyTorch/blob/master/networks.py ) the other using Conv found [here](https://github.com/lukemelas/EfficientNet-PyTorch/blob/master/efficientnet_pytorch/model.py) . 
The process is Pytorch => Onnx => Tensorflow => TensorflowJS. **Everything works in Tensorflow**.
The first method doesn't work in TFJS, the second one works in TFJS. The error during inference is `"Error: Error in matMul: inputs must have the same rank of at least 2, got ranks 4 and 2."
` which happens after `"Transpose                	0.02ms   	4D 1,1,1,16      	16	x: 4D 1,16,1,1 	: 0.02"`

#### Code to reproduce the bug / link to feature request
The model can be found here:
[web_6e45e_7.zip](https://github.com/tensorflow/tfjs/files/4516073/web_6e45e_7.zip)

**Comment by pyu10055** [comment]
@annxingyuan This following code fails with tfjs but works on python TF.

```
    const a = tf.zeros([1, 1, 1, 16]);
    const b = tf.zeros([16, 4]);
    const c = tf.matMul(a, b);
```

python output a tensor of shape (1,1,1,4), any idea what could be different here. thanks.
