### ISSUE TITLE
Input shapes do not match

### ISSUE THREAD

**Issue by moisesd37** [tensorflow/tfjs#315]
#### TensorFlow.js version
0.11.1
#### Browser version
Google Chrome Version 66.0.3359.181 (64-bit)

#### Describe the problem or feature request
I am trying to train a simple model on a small data set (15 samples with 4 features each) so i can then try to predict a 6 sample data set.
Everything goes well until i try to do the actual prediction, the browser shows the following error:
```javascript
Uncaught (in promise) Error: Error when checking : expected dense_Dense1_input to have shape [null,15,4] but got array with shape [1,6,4].
```
It does not seems logic to me, am i missing something?

#### Code to reproduce the bug / link to feature request
```javascript
$scope.model = tf.sequential();
$scope.model.add(tf.layers.dense({
    units: 1,
    inputShape: [trainingData.length, 4]
}));
$scope.model.compile({
    loss: 'meanSquaredError',
    optimizer: 'sgd'
});
$scope.xs = tf.tensor([trainingData], [1, trainingData.length, 4]);
$scope.ys = tf.tensor([trainingLabels], [1, trainingLabels.length, 1]);
$scope.model.fit($scope.xs, $scope.ys).then(() => {
    console.log("training finished");
    $scope.output = $scope.model.predict(tf.tensor([testingData], [1, testingData.length, 4]));
});
```
Thanks.

**Comment by bileschi** [comment]
Hi @moisesd37 .  What is happening here is that the inputShape anticipates that the first dimension is the batch dimension (the number of training samples per fitting loop).

In order to fix this, you should do something like: 

```
$scope.model = tf.sequential();
$scope.model.add(tf.layers.dense({
    units: 1,
    inputShape: [4]
}));
$scope.model.compile({
    loss: 'meanSquaredError',
    optimizer: 'sgd'
});
$scope.xs = tf.tensor([trainingData], [trainingData.length, 4]);
$scope.ys = tf.tensor([trainingLabels], [trainingLabels.length, 1]);
$scope.model.fit($scope.xs, $scope.ys).then(() => {
    console.log("training finished");
    $scope.output = $scope.model.predict(tf.tensor([testingData], [testingData.length, 4]));
});
```

See this link for more info about inputshape
https://js.tensorflow.org/api/0.11.1/#sequential
