### ISSUE TITLE
Chrome devtools failed to load SourceMaps

### ISSUE THREAD

**Issue by kelvinOfoli** [tensorflow/tfjs#3150]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis"></script>
    <title>Linear Regression</title>
</head>
<body>
    <script src="./app.js"></script>
</body>

</html>

** the Error in Chrome
![Screenshot (13)](https://user-images.githubusercontent.com/48011970/80341294-b1817000-8851-11ea-974a-7040d241b16a.png)

**Comment by rthadur** [comment]
please use latest version of tfjs [npm](    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script> 
) package.

**Comment by kelvinOfoli** [comment]
I still have the same problem..

**Comment by rthadur** [comment]
@kelvinOfoli  can you please share the code for reproduction , the code which you gave is not complete.

**Comment by lina128** [comment]
Hi, this is most likely chromium issue. In my case, I see that load sourceMap failed for all the libraries, not just tfjs. See a similar discussion recently: https://github.com/storybookjs/storybook/issues/10469

We will wait for chrome 82 release and keep monitoring. Thank you for reporting the issue.

**Comment by kelvinOfoli** [comment]
oh ok.. thanks @lina128
