### ISSUE TITLE
TensorCamera onReady not called in Chrome

### ISSUE THREAD

**Issue by Deams51** [tensorflow/tfjs#3155]
#### TensorFlow.js version
@tensorflow/tfjs: 1.7.3
@tensorflow/tfjs-react-native: 0.2.3

#### Browser version
Version 81.0.4044.122 (Official Build) (64-bit)

#### Describe the problem or feature request
The `TensorCamera` from tfjs-react-native is not calling `onReady` when running in Chrome. However, the camera is triggered and it does show up in the browser. 
The same code runs perfectly on a Pixel 4 XL and Iphone 11. 

#### Example
```
<View style={styles.cameraContainer}>
                <TensorCamera
                    // Standard Camera props
                    style={styles.camera}
                    type={this.state.cameraType}
                    zoom={0}
                    // tensor related props
                    cameraTextureHeight={textureDims.height}
                    cameraTextureWidth={textureDims.width}
                    resizeHeight={inputTensorHeight}
                    resizeWidth={inputTensorWidth}
                    resizeDepth={3}
                    onReady={this.handleImageTensorReady}
                    autorender={AUTORENDER}
                />
</View>;
```

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Deams51** [comment]
@rthadur Thank you for your comment. 
It does look like a bug as it is not the intended behavior.
Or do you have more information concerning why you are ruling out the possibility of a bug in the library?

**Comment by tafsiri** [comment]
tfjs-react-native is not designed/intended to run in browsers. You should be able to use regular tfjs in your browser app. Is there a use case where that wouldn't work for you?

**Comment by astriskit** [comment]
This is interesting thread; have been trying to get face-detection working on react-native stack. The asymmetric api could be one significant difference @tafsiri; In the react-native version the [HOC/cameraWithTensors](https://js.tensorflow.org/api_react_native/0.8.0/#Media-Camera) has no equal in`tfjs`, instead could use [tf.data.webcam](https://js.tensorflow.org/api/3.19.0/#data.webcam) to create an equivalent api. Gonna try doing that, next.

**Comment by expolli** [comment]
> tfjs-react-native is not designed/intended to run in browsers. 

I am confused.

In your [documentation ](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native)for **tfjs-react-native** you state:  

"If you use expo and encounter a build failure when running `npm run web`"

and then you direct to follow the steps eg:

- "Run:` expo customize:web`"

If building a native app for ios and android that would also support web, what would be your suggestion as how to proceed?

Thank you for an excellent library nonetheless!
