### ISSUE TITLE
Want to use static files for local development

### ISSUE THREAD

**Issue by YIN-jw** [tensorflow/tfjs#3182]
We can now load the latest version of the mobilenet model through the [https://github.com/tensorflow/tfjs-models/tree/master/mobilenet].Since we used static files before, we want to continue local development. Are there any open source local model files?

**Comment by rthadur** [comment]
You can use [npm](https://github.com/tensorflow/tfjs-models/tree/master/mobilenet#via-npm) to install on your machine.

This sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
