### ISSUE TITLE
FR: Improve error messages for invalid configuration objects

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#319]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
  tfjs: "0.11.1",
  tfjs-core: "0.11.0",
  tfjs-layers: "0.6.1"
#### Browser version
66.0.3359.117
#### Describe the problem or feature request
Unhelpful error message when layers built with an invalid configuration
#### Code to reproduce the bug / link to feature request
```js
const layer = tf.layers.conv2d({filters: 1, 
                                kenrelSize: 2,
                                strides: 1,
                                padding:'valid',
                                dataFormat:'channelsLast',
                                inputShape: [24,24, 1]
                               });
```
yeilds the error
`Uncaught TypeError: Cannot read property 'length' of undefined`

when the actual error is that `kernelSize` is misspelled as `kenrelSize`

**Comment by atanasster** [comment]
@bileschi - I am trying to get used with the tfjs code and picking some starter issues :) 
do you guys think the kerneSize is to be checked as a required parameter, or should the error rather be caught in https://github.com/tensorflow/tfjs-layers/blob/master/src/utils/conv_utils.ts#L29 (value is required), or both?

**Comment by dsmilkov** [comment]
We should prioritize this since it's going to improve significantly the usability of the library. See [this discussion](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/X1mg69fY1TE/bsfoFFC4AgAJ) for context where config validation would have helped and saved everyone's time.

**Comment by bileschi** [comment]
We started a pattern for this:  Looks like the PR got lost?
https://github.com/tensorflow/tfjs-layers/pull/216

**Comment by bileschi** [comment]
Ok, there we go, submitted just now.
https://github.com/tensorflow/tfjs-layers/pull/216#issue-191263092

**Comment by bileschi** [comment]
@atanasster sorry for the delay.  I would expect the `kernelSize` parameter to be verified as soon as possible.  Extending the framework added above, there should be bounds on what kernelSize values are appropriate (i.e., not negative)

**Comment by rthadur** [comment]
Closing the issue as the commit has been pushed here https://github.com/tensorflow/tfjs-layers/pull/216#issue-191263092, please feel free to reopen the issue if this has not been addressed.
