### ISSUE TITLE
model.fit() crashes the entire app [tfjs-react-native]

### ISSUE THREAD

**Issue by AbdulRashidReshamwala** [tensorflow/tfjs#3196]
#### TensorFlow.js version
"@tensorflow/tfjs": "^1.7.4"
"@tensorflow/tfjs-react-native": "^0.2.3"

#### Browser version
"expo": "~37.0.3"

#### Code to reproduce the bug / link to feature request
I was trying to build and train a model 
The app crashes as soon as I try to train a model

model compiles are successful 
was even able to view model summary
I have double checked all the input tensors 
Here is the code i'm trying to run[`Code`](https://github.com/AbdulRashidReshamwala/teachable-smartphone) 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47809786/80823829-e9ded080-8bfa-11ea-892f-049ae812b52d.gif)

**Comment by AbdulRashidReshamwala** [comment]
The current build fails to work on android due to https://github.com/tensorflow/tfjs/issues/3186 and https://github.com/facebook/react-native/issues/26890

**Comment by tafsiri** [comment]
Could you post the output from the device log before the crash? https://reactnative.dev/docs/debugging#accessing-console-logs They can be a bit noisy, but there should be some exception or error related to the app/tfjs-react-native.

**Comment by AbdulRashidReshamwala** [comment]
@tafsiri  If i enable remote debugging i get the following message the app does not crash
``` 
Running "main" with {"rootTag":21,"initialProps":{"exp":{"manifest":{"slug":"multiImageExpo","packagerOpts":{"urlRandomness":"b3-8fm","lanType":"ip","hostType":"lan","dev":true,"https":false,"minify":false},"bundleUrl":"http://192.168.0.109:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false","debuggerHost":"192.168.0.109:19001","icon":"./assets/icon.png","isVerified":false,"name":"multiImageExpo","xde":true,"version":"1.0.0","iconUrl":"http://192.168.0.109:19001/assets/./assets/icon.png","hostUri":"192.168.0.109:19000","id":"@anonymous/multiImageExpo-d06beda0-8d71-462a-841b-a03ee73367d1","updates":{"fallbackToCacheTimeout":0},"orientation":"portrait","sdkVersion":"37.0.0","env":{},"loadedFromCache":false,"logUrl":"http://192.168.0.109:19000/logs","ios":{"supportsTablet":true},"platforms":["ios","android","web"],"assetBundlePatterns":["**/*"],"mainModuleName":"node_modules/expo/AppEntry","developer":{"projectRoot":"/home/abdul/Desktop/code/personal/mobile/multiImageExpo","tool":"expo-cli"},"splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"http://192.168.0.109:19001/assets/./assets/splash.png"}},"appOwnership":"expo","initialUri":"exp://192.168.0.109:19000","shell":0}}}
RemoteConsole.js:80
Initialization of backend rn-webgl failed
RemoteConsole.js:80
Error: ExponentGLObjectManager.createContextAsync: Unexpected error occurred when initializing headless context
    at Object.fn [as callMethod] (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:2702:36)
    at Object.NativeModulesProxy.<computed>.<computed> [as createContextAsync] (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:96572:30)
    at createContextAsync$ (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:210172:75)
    at tryCatch (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29721:19)
    at Generator.invoke [as _invoke] (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29897:24)
    at Generator.prototype.<computed> [as next] (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29764:23)
    at tryCatch (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29721:19)
    at invoke (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29797:22)
    at /home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:29827:13
    at tryCallTwo (/home/abdul/Desktop/code/personal/mobile/multiImageExpo/.vscode/.react/AppEntry.bundle:3765:7)
```
And even training the model works
```
Layer (type)                 Output shape              Param #   
RemoteConsole.js:80
=================================================================
RemoteConsole.js:80
dense_Dense1 (Dense)         [null,224,224,16]         64        
RemoteConsole.js:80
_________________________________________________________________
RemoteConsole.js:80
flatten_Flatten1 (Flatten)   [null,802816]             0         
RemoteConsole.js:80
_________________________________________________________________
RemoteConsole.js:80
dense_Dense2 (Dense)         [null,2]                  1605634   
RemoteConsole.js:80
=================================================================
RemoteConsole.js:80
Total params: 1605698
RemoteConsole.js:80
Trainable params: 1605698
RemoteConsole.js:80
Non-trainable params: 0
RemoteConsole.js:80
_________________________________________________________________
RemoteConsole.js:80
Loss after Epoch 1 : 0.5
RemoteConsole.js:80
Loss after Epoch 2 : 0.5
RemoteConsole.js:80
Loss after Epoch 3 : 0.5
RemoteConsole.js:80
Loss after Epoch 4 : 0.5
```
I think the issue might be in the rn-webgl-backend 
I tried to use tf.setBackend("cpu"); but even that causes the app to crash

**Comment by tafsiri** [comment]
You can't use remote debugging for this as that will try and run everything in your browser. You want to use native debugging https://reactnative.dev/docs/debugging#native-debugging

What devices are you running this on? If the rn-webgl backend fails to initialize it will fallback to cpu but will be quite slow.

**Comment by tafsiri** [comment]
Any updates? Is the crash related to model.fit or the issue with loading local assets via fetch?

**Comment by AbdulRashidReshamwala** [comment]
This crash is definitely related to model.fit() I am able to successfully load images and even convert them into tensors.
I can't do native debugging since I don't have a device running macos will update as soon as possible

**Comment by tafsiri** [comment]
A few suggestions for you to try, mainly related to [this line in your code](https://github.com/AbdulRashidReshamwala/teachable-smartphone/blob/master/App.js#L111).

1. Do not overwrite `imageTensorBatch.current` and `labelTensorBatch.current` with the result of the stack. Doing this loses the reference to the array of tensors which means you can never dispose them.

2. Move the stack calls into your data generation method, and see if you can run that without calling model.fit. This might help rule out running out of memory before calling model.fit (i'd also try making the number of images small while you test). 

Related to [this line](https://github.com/AbdulRashidReshamwala/teachable-smartphone/blob/master/App.js#L113), don't call model fit in a loop, just increase the epochs. If app responsiveness becomes an issue use the `yieldEvery` argument to model.fit to control how often you want to yield back to the JS thread.

What is [this line](https://github.com/AbdulRashidReshamwala/teachable-smartphone/blob/master/App.js#L124) supposed to do? where is `m` defined? It doesn't look local to this method.

**Comment by AbdulRashidReshamwala** [comment]
I updated the code according to your suggestions I moved creation of stack in another method and tf.stack() does not seem to cause the problem i have also removed the loop in model.fit() and decreased the min images to 4.The app still seems to crash on the model.fit() call
@tafsiri
