### ISSUE TITLE
Compile error in RealtimeDemo class

### ISSUE THREAD

**Issue by vladi-hub** [tensorflow/tfjs#3200]
App.js: Unexpected token (58:7)

  56 | export class RealtimeDemo extends React.Component<ScreenProps,ScreenState> {
  57 |
> 58 |   rafID?: number;
     |        ^
  59 |
  60 |   constructor(props: ScreenProps) {
  61 |     super(props);

**Comment by rthadur** [comment]
Please file the issue using [template](https://github.com/tensorflow/tfjs/issues/new).
