### ISSUE TITLE
[Bodypix] How to load model from local disk?

### ISSUE THREAD

**Issue by jacktang** [tensorflow/tfjs#3202]
Hello,

My app can't connect Internet all the time, and how to load trained bodypix from local disk? The nodejs code snippet
```
    const net = await bodyPix.load({
        architecture: 'MobileNetV1',
        outputStride: 16,
        multiplier: 0.75,
        quantBytes: 2,
    });
```
In README.md I found
> * **modelUrl** - An optional string that specifies custom url of the model. This is useful for local development or countries that don't have access to the models hosted on GCP.

Could you please give me an example what the url is of the local model? and what's the content of the dest model (BTW: how can I download the trained model?). Thanks very much!

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

Please refer to this links for how the model can be downloaded form local.
[1) Loads the MobileNet BodyPix model.](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/body_pix_model.ts#L985)
[2) Load model from native file system.](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#native-file-system)

**Comment by jacktang** [comment]
@rthadur Appreciate your help. I have post the question on stackoverflow with `tensorflow.js` tag. See: https://stackoverflow.com/questions/61561601/how-to-load-bodypix-model-from-local-disk. 

As you told, now I can load model(json) file from local disk. Could you please tell me where can I print weights file uri path (the *.bin files) so that I could download them. Thanks!

**Comment by jacktang** [comment]
Well, I got all files now. Thanks

**Comment by emranio** [comment]
> Well, I got all files now. Thanks

where did you get the files? i'm still struggling to get all files together.
