### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by Zeesy** [tensorflow/tfjs#3205]
#### OS
Ubuntu 18.4

#### Tensorflow version
2.1.0

#### Tensorflow_js version
1.7.4

#### Feature request
Modification to documentation at **Importing a Keras model into TensorFlow.js**:
https://www.tensorflow.org/js/tutorials/conversion/import_keras

#### Code to reproduce the bug / link to feature request
https://www.tensorflow.org/js/tutorials/conversion/import_keras#step_1_convert_an_existing_keras_model_to_tfjs_layers_format

The given #bash command 
```
tensorflowjs_converter --input_format keras \
                       path/to/my_model.h5 \
                       path/to/tfjs_target_dir
```

throws this error:
`TensorFlow.js model converters.: error: unrecognized arguments: path/to/tfjs_target_dir`

Providing this as an alternative:
```
tensorflowjs_converter --input_format keras 
                       "path/to/my_model.h5"
                       "path/to/tfjs_target_dir"
```
would be helpful.

**Comment by rthadur** [comment]
I don't think this is an issue above format works as expected. cc @pyu10055
