### ISSUE TITLE
Performance metrics for the PoseNet models on the COCO dataset

### ISSUE THREAD

**Issue by nuzrub** [tensorflow/tfjs#3206]
Dear Posenet team, 
I am evaluating pose estimation models and I really liked how performant posenet is. However, I can't find its AP scores for the COCO dataset. I am aware of the Personlab paper, but it seems a bit out-dated with the repository. For instance, it does not include the MobileNet based model.
Are these results available some where or could you share it?
Thanks

**Comment by lakshminarayanareddybn** [comment]
Dear posenet team, 

My problem is also similar to reported by @nuzrub,  I am trying to inference the posenet with cocodata set  for keypoint detection and verify the precision using coco APIs. the result file saved in the format mentioned in  http://cocodataset.org/#format-results 
[{
"image_id": int, "category_id": int, "keypoints": [x1,y1,v1,...,xk,yk,vk], "score": float,
}]
But when tried to get evaluation results using coco api. that precision comes 0 always.
Even though posenet identifies keypoints correctly (verified by drawing on to image) it never matched with GT (provided by coco dataset 2017).

please can you confirm if we need to use different set of GT for coco dataset for posenet.

Thanks & Regards,
Lakshminarayana reddy

**Comment by tylerzhu-github** [comment]
Thanks for your interests! Cyvasse (@nuzrub) and Lakshminarayana reddy (@lakshminarayanareddybn). I am very glad that PoseNet.js libraries help you in various creative ways and I look forward to seeing what you are building.

COCO is an excellent dataset. At this moment, the dataset doesn't provide a javascript evaluation protocol and it is not trivial to evaluate using PoseNet.js's APIs directly. Although optimizations (like: e.g. weight quantization) do effect accuracy, and qualitatively we find the predictions satisfying.

Best,
Tyler

**Comment by rthadur** [comment]
Posenet will not be supported in future , please refer to [movenet](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/movenet) model in future.
