### ISSUE TITLE
integration_rn59 not working correctly on any platform

### ISSUE THREAD

**Issue by alexstanbury** [tensorflow/tfjs#3207]
I can see there has been a recent commit that has likely affected this. I am trying to debug some other issues I'm having with tfjs-react-native but cannot get the demo project to run at all on iOS emulator or device, I get the following error at build time:

`fatal error: 'React/RCTAssert.h' file not found`

It will run on an Android emulator and device but a warning is shown saying rn-webgl backend failed to initialise. Then if I click the `SHOW DIAGNOSTIC SCREEN` button the app freezes and it confirms that webgl is not initialised.
![Screenshot 2020-05-05 at 16 48 43](https://user-images.githubusercontent.com/809537/81086518-81d90480-8ef0-11ea-9ce8-3556e3fe2130.png)
![Screenshot 2020-05-05 at 16 48 59](https://user-images.githubusercontent.com/809537/81086520-82719b00-8ef0-11ea-90b5-63a5717d68ce.png)

The emulator and device (high-end flagship) are both capable of webgl as confirmed by https://webglreport.com

The rn-webgl issue is the reason I wanted to test with the demo project because I am experiencing an issue with immediate crash on another project (using RN 0.62.2) with Android unless I explicitly `tf.setBackend('cpu')` before calling `tf.ready()`. 

I can see the version of tfjs the demo is using is `2.0.0-rc.2.1` so I'm guessing this may be something to do with these issues.

**Comment by tafsiri** [comment]
Hi. yes we are right in the middle of some biggish unreleased changes, so I would't work straight from master. I'd pick a tag like https://github.com/tensorflow/tfjs/tree/tfjs-v1.7.1 to work from if you want to debug from source.

**Comment by alexstanbury** [comment]
Understood. I'll try that branch instead, thanks.

**Comment by RatebSeirawan** [comment]
even tho I downgraded to tfjs-v1.7.1 it still crashes when I set the backend to rn-webgl and when I set it to cpu it does not crash until I do anything TF like trying the camera demo.
any help would be appreciated I scratch the internet to find a solution but couldn't, and I am using RN62.2

**Comment by alexstanbury** [comment]
I am seeing the same issue using RN 0.62.2, seems this library / expo gl is not compatible yet.

**Comment by tafsiri** [comment]
could you share your package.json, maybe the version of expo-gl is not compatible with RN62.2. Also on-device debug logs (not remote debugging) with the error that leads to a crash would be very helpful. Feel free to open a new issue when posting this info since this one is closed.
