### ISSUE TITLE
float16 quantization

### ISSUE THREAD

**Issue by JesseFarebro** [tensorflow/tfjs#3221]
#### Describe the problem or feature request

It would be useful to support quantizing to float16 over the wire and then dequantizing back to float32 on the client.
I'm working with a model where the 2-byte affine quantization in TFJS performs very poorly but using float16 quantization has a negligible impact on performance.

**Comment by pyu10055** [comment]
Thanks, that is very a good suggestion.

**Comment by JesseFarebro** [comment]
I'll probably end up putting together a PR for this in the next week or so as I'm going to end up needing this.

**Comment by pyu10055** [comment]
@JesseFarebro that would be great, thank you!

**Comment by JesseFarebro** [comment]
I'm just finishing this work up but I'm now debating what's the best way to incorporate quantization in the converter CLI. What I have right now is:
```
tensorflowjs_converter --quantization_dtype float16 ...
tensorflowjs_converter --quantization_dtype int8 ...
tensorflowjs_converter --quantization_dtype int16 ...
```

The problem with this is it doesn't allow for using `float16` for weights with type `float32` and `int8|int16` for weights with type `*int*`. Perhaps making this even more configurable could be advantageous, for example, only quantizing certain layers could provide improved accuracy while still reducing the model size. Perhaps flags like:

```
tensorflowjs_converter --quantize_float32 block1/*=float16
                       --quantize_float32 block2/*=uint16
                       --quantize_int32 output/*=uint8
```
while also allowing for:
```
tensorflowjs_converter --quantize_float32 float16
                       --quantize_int32 uint16
```

We could also maintain backwards compatibility by still allowing for `--quantization_bytes` being the default quantization if none of the `--quantize_*` flags are present. If the `--quantize_*` flags are present it would override the value of `--quantization_bytes` for the specific dtype or layer specified. e.g.,

```
tensorflowjs_converter --quantization_bytes 1
                       --quantize_float32 block1/*=float16
```
would quantize every weight outside of `block1/*` to uint8 and every float32 weight inside `block1/*` to float16.

I'm not happy with how the block specific flags look but I just want to get a discussion going before I start refining this.
