### ISSUE TITLE
tfjs-models/handpose/  doesn't work

### ISSUE THREAD

**Issue by yslion** [tensorflow/tfjs#3227]
GET https://tfhub.dev/mediapipe/tfjs-model/handskeleton/1/default/1/model.json?tfjs-format=file net::ERR_CONNECTION_TIMED_OUT

**Comment by annxingyuan** [comment]
Hi @yslion - I think that may have been a temporary issue - could you try again?

**Comment by yslion** [comment]
> Hi @yslion - I think that may have been a temporary issue - could you try again?

I tried it for many days   ,  is it the reason of Chinese network ?

**Comment by rthadur** [comment]
@yslion i believe above links are not accessible from china.Please check [here](https://github.com/tensorflow/tfjs/issues/1375)

**Comment by Trenki** [comment]
Have you solved the problem? I have the same problem.

**Comment by Trenki** [comment]
I can't solve my problem in [#1375](https://github.com/tensorflow/tfjs/issues/1375) .I've tried.
