### ISSUE TITLE
Knn Demo - TypeError: Nt.runKernelFunc is not a function

### ISSUE THREAD

**Issue by Patrick-David** [tensorflow/tfjs#3229]
#### TensorFlow.js version
"@tensorflow-models/knn-classifier": "1.2.1",
    "@tensorflow-models/mobilenet": "^2.0.2",
    "@tensorflow/tfjs": "^1.2.1",
    "stats.js": "^0.17.0"

#### Browser version
Chrome: Version 81.0.4044.129 (Official Build) (64-bit)
and also Firefox : 75.0 (64-bit)

#### Describe the problem or feature request
When running the KNN demo found here 
[knn demo](https://github.com/tensorflow/tfjs-models/tree/master/knn-classifier/demo)
upon clicking the train button (either train 0 train 1 or train 2), console returns the following error in chrome:

binary_ops.ts:435 Uncaught (in promise) TypeError: Nt.runKernelFunc is not a function
    at div_ (binary_ops.ts:435)
    at Object.div (operation.ts:45)
    at index.ts:270
    at engine.ts:393
    at t.scopedRun (engine.ts:404)
    at t.tidy (engine.ts:391)
    at Object.Ke [as tidy] (globals.ts:182)
    at KNNClassifier.normalizeVectorToUnitLength (index.ts:267)
    at index.ts:62
    at engine.ts:393

Same thing in Firefox:

TypeError: Nt.runKernelFunc is not a function          binary_ops.ts:435:16

This means I can't get to the training part of the demo.

#### Code to reproduce the bug / link to feature request

I ran the demo by following the readme to run on localhost:

Setup

cd into the demos folder:

cd knn-classifier/demos

Install dependencies and prepare the build directory:

yarn

To watch files for changes, and launch a dev server:

yarn watch

**Comment by rthadur** [comment]
@Patrick-David can you try to use latest tfjs version ?

**Comment by Patrick-David** [comment]
Thanks @rthadur 
simply by changing to tfjs 1.7.4  in the package.json, the error goes away.

**Comment by rthadur** [comment]
@Patrick-David thank you.
