### ISSUE TITLE
Title line on js.tensorflow.org needs update given node.js support

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#324]
Currently, it reads: "A WebGL accelerated, browser based JavaScript library for training and deploying ML models." This doesn't cover node.js support obviously. We may need to think of a more general and all-encompassing title.

**Comment by tafsiri** [comment]
How about "A JavaScript library for training and deploying ML models in the browser and on Node.js." cc @dsmilkov @nkreeger

**Comment by dsmilkov** [comment]
Sounds good to me. We should also add a nodejs subsection in the Getting Started section.

**Comment by nkreeger** [comment]
+1 - I can add something in that section today.

**Comment by nkreeger** [comment]
We should update the README on the tfjs repo too. We currently have one button that links to Github on the site (which his tensorflow/tfjs)

**Comment by dsmilkov** [comment]
Is this fixed?

**Comment by bileschi** [comment]
Looks fixed to me!  Please re-open I'm wrong.
