### ISSUE TITLE
Webcam tfjs on safari

### ISSUE THREAD

**Issue by alexionby** [tensorflow/tfjs#3266]
1.7.4
Safari 13
After several tries of running TFJS model (some examples:

1. https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html
2. https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html
3. https://storage.googleapis.com/tfjs-models/demos/facemesh/index.html
4. https://storage.googleapis.com/tfjs-models/demos/handpose/index.html
)
 Safari webcam stream become blocked by TFJS (details in demo)

Basic demo was created by @vabarbosa
 

> 
> hello, i'm also experiencing this problem with Safari browsers. i created a basic demo where i can reproduce the problem: 
> 
>  1. in a Safari browser go to: https://codepen.io/vabarbosa/pen/bGGZXbz 
>  2. click on **Start Webcam** and grant permission to access webcam
>  3. click **Load Model** to load a base model from posenet: https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/float/075/model-stride16.json
>  4. click **Run Prediction** (with **use requestAnimationFrame** unchecked/disabled) to call `model.predict` once on a frame. (video may pause initially for a brief sec but resumes and subsequent calls are quick and return values always changing)
>  5. check/enable **use requestAnimationFrame** then click **Run Prediction**. this will repeatedly call `model.predict` using `requestAnimationFrame()`. (at this point the predictions run but the video freezes so returned values never change. unchecking the **use requestAnimationFrame** stops the prediction calls and video resumes)
> 
> (4) is OK but (5) is not OK.
> 
> the only difference is (5). i see this problem on Safari but not Chrome or Firefox. i also do not notice any errors in the console. i do not have another machine at this moment to try this on but my current environment is:  
> 
> - **user-agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
> - **tfjs-version**: 1.3.2
> 
> any insight is greatly appreciated and if you need me to try something or look into anything let me know.
> 
> thank you.
> 

_Originally posted by @vabarbosa in https://github.com/tensorflow/tfjs/issues/1174#issuecomment-557297379_

This problem still remains in 1.7.4

**Comment by rthadur** [comment]
I was able to reproduce the issue, @alexionby do you have a codepen example to reproduce error ?

**Comment by alexionby** [comment]
I've updated Safari to 13.1 and bug disappeared. 
But! In some cases I still can face the same bug IOS Safari 13.3.1 - 13.4.1 and it's very tricky to reproduce. For now I have some ideas and I will try to create a stable and reproducible example.

**Comment by rthadur** [comment]
Thank you , closing this issue for now.Feel free to reopen.

**Comment by markstrefford** [comment]
I have this problem consistently on iOS14.2. I've tried it on an iPhone 11 Pro Max and an iPhone 11 Pro. It fails for Posenet and FaceMesh demos, but BlazeFace works ok!

For PoseNet, I get the following error in the console:

```
[Error] A MediaStreamTrack ended due to a capture failure
[Error] Unhandled Promise Rejection: Error: The video element has not loaded data yet. Please wait for `loadeddata` event on the <video> element.
	(anonymous function) (camera.cb338cd2.js:42:5928)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

iOS 13.5.1 on iPhone X runs these models OK.

**Comment by markstrefford** [comment]
> I've updated Safari to 13.1 and bug disappeared.
> But! In some cases I still can face the same bug on IOS Safari 13.3.1 - 13.4.1 and it's very tricky to reproduce. For now I have some ideas and I will try to create a stable and reproducible example.

@alexionby  Did you fix this? I'm experiencing the same problem for the models you mention on iOS14.2, yet 13.5 is OK.
Blazeface demo works on both platforms ok.
