### ISSUE TITLE
The docs for `tf.tidy` are technically incorrect

### ISSUE THREAD

**Issue by notwaldorf** [tensorflow/tfjs#327]
The docs for [`tf.tidy`](https://js.tensorflow.org/api/0.11.1/#tidy) say it `executes the provided function f` but none of the arguments are named `f`:
<img width="750" alt="screen shot 2018-05-22 at 10 40 47 am" src="https://user-images.githubusercontent.com/1369170/40379993-9aa99776-5dac-11e8-9ba4-62fc11d9fda6.png">

I think the fix is to update the comment [here](https://github.com/tensorflow/tfjs-core/blob/master/src/tracking.ts#L27) and try to clean it up. Would you be interested in this PR?

**Comment by bileschi** [comment]
yes please!  Thanks for reporting!

**Comment by tafsiri** [comment]
Fixed
