### ISSUE TITLE
tf.argMax accepts an array or a number

### ISSUE THREAD

**Issue by kedevked** [tensorflow/tfjs#3270]
#### TensorFlow.js version
1.7
#### Browser version
chrome 81
#### Describe the problem or feature request
Following this [question](https://stackoverflow.com/questions/61776343/what-does-argmax-do-with-an-array-as-axis/61780454#61780454) on stackoverflow, `tf.argMax` can accept a number or an array. I am not sure if that is a bug, but I wonder if it is intended since the documentation shows that the axis is a number
#### Code to reproduce the bug 
```js
const x = tf.tensor1d([1, 2, 3]);

x.argMax(0).print(); 
x.argMax([0]).print(); 
```
With `x.argMax([0, 0]).print();` the error seems not to be explicit
>Error in transpose: rank of input 1 must match length of perm 0,0.

**Comment by tafsiri** [comment]
Yeah this is a bug in the tutorial. Thanks for letting us know. I've updated [the tutorial](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#6) to make the axis argument a number.

**Comment by kedevked** [comment]
@tafsiri It is not only a bug in the tutorial, if you use the array, it works. The question should be if array are not allowed, then a specific check should be made on the argument and throw an error like "the parameter is not a number".

**Comment by tafsiri** [comment]
We don't generally do that kind of type checking of our arguments at runtime (especially for non tensor arguments). I recommend using typescript if users want to get that level of protection when it comes to types. I wouldn't consider the fact that it works with a length 1 array a bug either (its more like undefined behaviour). Other than incorrect documentation I doubt that users would run into this as an issue.

**Comment by kedevked** [comment]
Without doing a type check, if this [line](https://github.com/tensorflow/tfjs/blob/tfjs-core-v1.7.2/tfjs-core/src/ops/reduction_ops.ts#L481) 

    let axes = util.parseAxisParam(axis, $x.shape);

was replaced by 

    let axes = util.parseAxisParam([axis], $x.shape);

the argMax will throw the error 

    "All values in axis param must be in range [-${rank}, ${rank}) but ` +
          `got axis ${axis}"

With this error the user can understand that a number is expected
