### ISSUE TITLE
fetchFunc doesn't work with fully qualified URLs

### ISSUE THREAD

**Issue by JesseFarebro** [tensorflow/tfjs#3271]
#### TensorFlow.js version

2.0.0-rc.4

#### Describe the problem or feature request

Currently, if you supply `fetchFunc` to a function like `loadGraphModel` it will ignore `fetchFunc` if the URL is a fully qualified URL. For example,

```js
const options = {
  fetchFunc: (...args) => {
    console.log(`Custom fetch`)
    return fetch(...args)
  }
}

let model = await loadGraphModel(`/path/model.json`, options) // Works
model = await loadGraphModel(`https://mydomain.com/path/model.json`, options) // Doesn't work
model = await loadGraphModel(`//mydomain.com/path/model.json`, options) // Works
```

The issue arises as such:

tfjs first tries to resolve a handler for the URL type. This involves iterating over the known routers. It gets to the HTTP router which will resolve if the following `isHTTP` check is true:

https://github.com/tensorflow/tfjs/blob/a60f32fbb3d12801c35e464a1f5fd173d575097a/tfjs-core/src/io/http.ts#L42

https://github.com/tensorflow/tfjs/blob/602111aa0858bb46837c2091f4507371525aa3f6/tfjs-core/src/io/http.ts#L252-L254

If tfjs resolves any router it won't construct a handler with the provided user options:

https://github.com/tensorflow/tfjs/blob/602111aa0858bb46837c2091f4507371525aa3f6/tfjs-converter/src/executor/graph_model.ts#L92-L103

I'm not sure what the reasoning for this is, shouldn't the options be passed through regardless?

**Comment by rthadur** [comment]
@JesseFarebro did you try using `await` while loading model ?

**Comment by JesseFarebro** [comment]
@rthadur yes, are you referring to my example? I wrote that up quickly in Github, didn't really check it over.

**Comment by rthadur** [comment]
yes I was referring to your code , is it possible to provide an codepen example to reproduce the same , thank you.

**Comment by JesseFarebro** [comment]
https://codesandbox.io/s/tfjs-fqurl-repro-x1y2f?file=/src/index.js

**Comment by pyu10055** [comment]
@JesseFarebro The custom fetch is used, even we calls the default IO handler, since the IO handler will call into the custom fetchFunc. In your example code, if you add a console.log to your custom fetch function, it will print properly.

**Comment by JesseFarebro** [comment]
It doesn't. Add ```console.log(`Fetch ${url}`)``` to `fetchFunc` and notice it only prints the URL prefixed with `//` and not the URL prefixed with `https://`. There are two test cases I have there, the desired result is using `fetchFunc` for both URLs. Am I missing something?

**Comment by pyu10055** [comment]
@JesseFarebro for the case where the url does not start with 'http://', tfjs does not know how to load the model. you need to implement your own IOHander and pass it in in replacement of the modelUrl to loadGraphModel API. please take a look at the API doc.

**Comment by JesseFarebro** [comment]
I get that, that's not where my problem stems from. My problem is there is no way to override this behaviour. I'm supplying a fully qualified URL including the protocol and I want to use a custom fetch function. The reason being is I want to track the download progress by using a custom ReadableStream. Also, no I don't want to use the builtin tfjs progress callback as its inadequate for the HTTP handler to track things like true download %, bytes received, etc.

There doesn't seem to be an adequate builtin solution other than implementing the entire model loading scheme myself or changing my URLs to strip the protocol so the default handler doesn't get used.

**Comment by pyu10055** [comment]
@JesseFarebro Now I understand the issue, yes, we will add a fix to update the fetchFunc for the default http loader.

**Comment by JesseFarebro** [comment]
Thanks @pyu10055, sorry for the confusion.
