### ISSUE TITLE
Error: The specified module could not be found

### ISSUE THREAD

**Issue by zedd3v** [tensorflow/tfjs#3274]
#### TensorFlow.js version
@tensorflow-models/mobilenet; 0.2.2
@tensorflow/tfjs: 0.12.0
@tensorflow/tfjs-node: 1.7.4
#### Describe the problem or feature request
internal/modules/cjs/loader.js:1197
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found

**Comment by rthadur** [comment]
@zedd3v please refer to a similar issue [here](https://github.com/tensorflow/tfjs/issues/2619) , which was resolved. Thank you
