### ISSUE TITLE
NCHW Support for conv2d on loaded Frozen Model  while computing bias

### ISSUE THREAD

**Issue by vonlyinno** [tensorflow/tfjs#3282]
#### TensorFlow.js version
"@tensorflow/tfjs": "^1.7.4"
#### Browser version
Chrome 81.0.4044.138
#### Describe the problem or feature request
It is said that tfjs has ability to support NCHW for  conv2d on loaded Frozen Model. Now I load a frozen  model in  NCHW, it throws out an error when i execuate my model:
**Error: Operands could not be broadcast together with shapes 1,32,220,220 and 32.**

![image](https://user-images.githubusercontent.com/9960612/82149825-e188c580-9889-11ea-8612-1fab51593b4f.png)

I debug the code and find that the output shape of conv2d is [1, 32, 220, 220] and the dataformat is indeed NCHW. **The error occurs in node BiasAdd with shape [32].**

![image](https://user-images.githubusercontent.com/9960612/82149750-cfa72280-9889-11ea-8a30-54f03868aaa9.png)
![image](https://user-images.githubusercontent.com/9960612/82149942-07ae6580-988a-11ea-9e5e-d4c6d4033fb1.png)

I run the same code with model in NHWC format and it went well.
**Does the BaisAdd node in conv2d really support NCHW?**

**Comment by pyu10055** [comment]
@vonlyinno Thank you for reporting, unfortunately our biasadd does not support NCHW data format right now. What is the version of Tensorflow.js you are using?
The is a change that your conv2d + biasAdd could be fused into FusedConv2d Op by the latest converter, in which NCHW should be supported.

**Comment by vonlyinno** [comment]
@pyu10055 Thanks for your reply.
However I do use the latest version 1.7.4 of @tensorflow/tfjs.

**Comment by pyu10055** [comment]
@vonlyinno What is the version of converter you used for converting your model? can you also share your conversion command line? thanks

**Comment by vonlyinno** [comment]
@pyu10055 
I use `pip install tensorflowjs` as instruction and the version is `1.7.4r1`.
convert command line:
`tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='output' /xxx/SR_x2_RGB.pb  /xxx/rgb_model`

**Comment by pyu10055** [comment]
does this frozen model targets CPU? Is it possible for you to generate a CPU version of this model? I believe tensorflow CPU does not support NCHW conv2d.
