### ISSUE TITLE
Implement tf.depth_to_space

### ISSUE THREAD

**Issue by oeway** [tensorflow/tfjs#329]
[tf.depth_to_space](https://www.tensorflow.org/api_docs/python/tf/depth_to_space) can be used as [sub-pixel convolution](https://arxiv.org/abs/1609.05158), which is an efficient way to implement image super-resolution. I hope this op can be prioritized, this will be critical for real-time application or mobile device.

**Comment by jgartman** [comment]
I can give this a shot if no one has started up with it yet.

**Comment by nsthorat** [comment]
This is done!
