### ISSUE TITLE
Posenet not lorded

### ISSUE THREAD

**Issue by djashan** [tensorflow/tfjs#3291]
posenet.esm.js'
Error: ENOENT: no such file or directory, open 'C:\Users\Ashan Pro\Desktop\research\arimac tencs\model demo\tfjs-models-master\posenet\demos\node_modules@tensorflow-models\posenet\dist\p
osenet.esm.js'
![Screenshot (211)](https://user-images.githubusercontent.com/41038007/82347274-0a899180-9a15-11ea-9f3e-e917bbeb4f8b.png)

**Comment by tafsiri** [comment]
Did you follow all the instructions? https://github.com/tensorflow/tfjs-models/tree/master/posenet/demos#setup Did you run `yarn` before yarning `yarn watch`?
