### ISSUE TITLE
Issue with getting tensors from TensorCamera for tfjs-reactnative

### ISSUE THREAD

**Issue by harvinder-power** [tensorflow/tfjs#3294]
#### TensorFlow.js version
1.7.4

#### Browser version
React Native + Expo (SDK37)

#### Describe the problem or feature request
When running handleCameraStream, it encounters the error: 
[Unhandled promise rejection: TypeError: images.next is not a function. (In 'images.next()', 'images.next' is undefined)]

Description of images from CameraWithTensors documentation: _images is a (iterator)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators] that yields tensors representing the camera image on demand._

I also noted that `requestAnimation(loop);` in the TF example didn't work for me, `requestAnimationFrame(loop);` worked in my example.

#### Code to reproduce the bug / link to feature request
https://gist.github.com/harvinder-power/1562e1a9fe8ffb0533dd3e937bb24f9e

Code is based on: https://js.tensorflow.org/api_react_native/latest/#cameraWithTensors

**Comment by tafsiri** [comment]
Hi, The [signature of your handler function](https://gist.github.com/harvinder-power/1562e1a9fe8ffb0533dd3e937bb24f9e#file-tfjs-expo-tensorcamera-js-L35) has an extra `model` parameter at the beginning that does not match the [onReady signature](https://js.tensorflow.org/api_react_native/0.2.3/#cameraWithTensors)

**Comment by harvinder-power** [comment]
Great spot! All works now, many thanks 👍
