### ISSUE TITLE
Build version of posenet not working - posenet.load() returns {}

### ISSUE THREAD

**Issue by yonlif** [tensorflow/tfjs#3298]
#### TensorFlow.js version: 
"@tensorflow-models/posenet": "^2.2.1",
"@tensorflow/tfjs-converter": "^1.7.4",
"@tensorflow/tfjs-core": "^1.7.4",

#### Browser version: I am using electron.

I want to be able to build my app that is using posenet. In the dev version everything is working great, the net is loaded using `posenet.load()` and returns a Promise object.

But when I am building my app using electron-builder and than calling `posenet.load()` it returns a `{}`.

I have no idea why and how to fix it, the net is loaded in dev so my config must be fine.

**Comment by yonlif** [comment]
An update: This is still not working, but we found a work around, take the import and put it in a react segment and not an electron segment inside your app. Everything will work as intended.

**Comment by rthadur** [comment]
@yonlif do you wish to contribute ?
