### ISSUE TITLE
Body pix image demo does not work

### ISSUE THREAD

**Issue by mou23** [tensorflow/tfjs#3301]
I tried to run the image example given at https://github.com/tensorflow/tfjs-models/tree/master/body-pix

However, it fails to fetch 
https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/075/model-stride16.json

TensorFlow.js version:  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.2"></script>

Browser version: Google Chrome Version 81.0.4044.138 

Any help is appreciated.

**Comment by rthadur** [comment]
@mou23 what error you are getting when you try to run , can you please let us know the steps to reproduce the error ?

**Comment by mou23** [comment]
I got the following error
Failed to load resource: net::ERR_CONNECTION_CLOSED storage.googleapis.com/tfjs-models/savedmodel/bodypix/mobilenet/float/075/model-stride16.json:1

**Comment by rthadur** [comment]
@mou23 error means your internet is blocking access to above link, I was able to run the example with out error.Please  verify.

**Comment by mou23** [comment]
Unfortunately it is still showing the same error to me :(

**Comment by rthadur** [comment]
It is not a tfjs issue , please check your internet firewall.
