### ISSUE TITLE
How to use tfjs-react-native in react native cli apps

### ISSUE THREAD

**Issue by zhezui928** [tensorflow/tfjs#3306]
I want to use tfjs to train my own custom tflite models. But it says tfjs-react-native is supported for only expo apps. Is there any solution?

**Comment by rthadur** [comment]
Please refer to the [comment](https://github.com/tensorflow/tfjs/issues/2785#issuecomment-592019215) here , we do not support tflite models in tfjs.

**Comment by tafsiri** [comment]
Also check out the tflite docs here https://www.tensorflow.org/lite for more info about how to use tflite.
