### ISSUE TITLE
TypeError: Cannot change the configurable attribute of "name" from false to true.

### ISSUE THREAD

**Issue by leo108** [tensorflow/tfjs#3308]
### TensorFlow.js version
1.7.4

#### Browser version
Chrome 81.0.4044
Mobile Safari 9.0

#### Describe the problem or feature request

This error is not happening every time, I see this error reported by Sentry from users' browser, the souremap indicates the error was triggered by this line:

https://github.com/tensorflow/tfjs/blob/tfjs_1.7.4/tfjs-core/src/ops/operation.ts#L56

**Comment by rthadur** [comment]
@leo108 please provide steps to reproduce the error ?

**Comment by leo108** [comment]
@rthadur I'm not able to reproduce myself, I think it's quite random because I can see hundreds of this error in Sentry every day.

**Comment by leo108** [comment]
The error occurs in various OS/browsers

![image](https://user-images.githubusercontent.com/1551716/82853587-bca2eb00-9f38-11ea-9fe6-d3e45777341b.png)
![image](https://user-images.githubusercontent.com/1551716/82853607-c62c5300-9f38-11ea-9d87-a96a943d7b03.png)
![image](https://user-images.githubusercontent.com/1551716/82853618-ccbaca80-9f38-11ea-95bd-00c96383c1b5.png)

**Comment by rthadur** [comment]
@leo108 thank you , I don't think we can support this issue, please explore stack-overflow more help with tag 'tensorflow.js'.
