### ISSUE TITLE
Unknown padding parameter: explicit

### ISSUE THREAD

**Issue by bangonkali** [tensorflow/tfjs#3311]
#### TensorFlow.js version

Tested with both: `1.7.4` & `2.0.0-rc.4`

#### Browser version

Any.

#### Describe the problem or feature request

The `model.json` converted using `tensorflowjs_converter` `1.7.4r1` contained `explicit_paddings` in the following lines:

```json
...
      {
        "name": "StatefulPartitionedCall/sequential/conv2d/Relu",
        "op": "_FusedConv2D",
        "input": [
          "conv2d_input",
          "Func/StatefulPartitionedCall/input/_2",
          "Func/StatefulPartitionedCall/input/_3"
        ],
        "device": "/device:CPU:0",
        "attr": {
          "dilations": { "list": { "i": ["1", "1", "1", "1"] } },
          "T": { "type": "DT_FLOAT" },
          "strides": { "list": { "i": ["1", "1", "1", "1"] } },
          "data_format": { "s": "TkhXQw==" },
          "use_cudnn_on_gpu": { "b": true },
          "explicit_paddings": {
            "list": { "i": ["0", "0", "0", "0", "0", "0", "0", "0"] }
          },
          "num_args": { "i": "1" },
          "epsilon": { "f": 0.0 },
          "padding": { "s": "RVhQTElDSVQ=" },
          "fused_ops": { "list": { "s": ["Qmlhc0FkZA==", "UmVsdQ=="] } }
        }
      },
...
```

I get this when trying to use the model. (`2.0.0-rc.4`)
```
    Unknown padding parameter: explicit

      at getPadAndOutInfo (node_modules/@tensorflow/tfjs-core/src/ops/conv_util.ts:434:11)
      at conv_util.computeConv2DInfo (node_modules/@tensorflow/tfjs-core/src/ops/conv_util.ts:149:9)
      at fusedConv2d_ (node_modules/@tensorflow/tfjs-core/src/ops/fused_ops.ts:387:20)
      at fusedConv2d (node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:45:24)
      at convolution.executeOp (node_modules/@tensorflow/tfjs-converter/src/operations/executors/convolution_executor.ts:102:15)
      at node_modules/@tensorflow/tfjs-converter/src/operations/operation_executor.ts:64:23
      at node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/src/engine.ts:425:20
      at Engine.scopedRun (node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/src/engine.ts:436:19)
      at Engine.tidy (node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/src/engine.ts:423:17)
      at Object.tidy (node_modules/@tensorflow/tfjs-core/src/globals.ts:182:17)
```

Pseudo-code of what I did. The other models without `explicit_paddings` on the converted json did work without issues.

```ts
  const model = await loadGraphModel(
    'http://localhost:5000/model2a/model.json'
  );
  const dTensor = tensor([...d, ...d]);
  const reshape = dTensor.reshape([2, 18, 4, 1]);
  console.log(reshape.shape);
  const prediction = model.predict(reshape);
```

#### Code to reproduce the bug / link to feature request
Unfortunately, I can't share the code at the moment. But Also I have other models that work without problems using the same pattern of approach. What common for those that worked is that they do not have `explicit_paddings` in their generated `model.json`.

**Comment by bangonkali** [comment]
Additional note: By manually editing the padding from base64 encoded EXPLICIT to SAME, the `predict()` does work. But I'm not sure about the values it outputs anymore. 😂

![image](https://user-images.githubusercontent.com/539946/82733690-214b2380-9d48-11ea-9b2e-f0eb98875551.png)

**Comment by pyu10055** [comment]
@bangonkali Thank you, we will add explicit padding support for all conv ops.

**Comment by pyu10055** [comment]
@annxingyuan I don't think our conv2d ops support explicit padding, they do allow a single number as pad, can it be expanded to support the TF spec? Thanks

https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

**Comment by annxingyuan** [comment]
@pyu10055 Sure I can work on that.

**Comment by annxingyuan** [comment]
@pyu10055 Hey Ping, wanted to confirm, we just need to modify our tfjs-core conv API to accept `'same'|'valid'|number|[[number,number],[number,number],[number,number],[number,number]]` right?

**Comment by pyu10055** [comment]
I think so, the batch and channel padding are zeros anyway.
