### ISSUE TITLE
 Tensoflow React Native : Failed to load Model [Error: Based on the provided shape, [20736,512], the tensor should have 10616832 values but has 1024992]

### ISSUE THREAD

**Issue by ciscoprakp** [tensorflow/tfjs#3318]
#### TensorFlow.js version
2.2.1

#### Describe the problem or feature request
I am trying to load my model in my react native app, i have setup tensorflow environment for  React Native and i could get the tf.ready message successfully, but when i try to load my Keras model it shows below error.
Failed to load Model [Error: Based on the provided shape, [20736,512], the tensor should have 10616832 values but has 1024992]

Tensorflow version: 2.2.1

Keras Version: 
Using TensorFlow backend.
2.3.1

TensorFlow JS Python version 
'1.7.4r1'

tensorflow react native library version
"@tensorflow/tfjs": "^1.7.4",
"@tensorflow/tfjs-react-native": "^0.2.3",

Model Converted using:
# Convert the model
!mkdir model
!tensorflowjs_converter --input_format keras keras.h5 model/

I am a beginner to Tensorflow and Keras.

Any help on this very much appreciated, stuck with this error from past one week :(

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
