### ISSUE TITLE
Prevent users from converting a model that has no topology

### ISSUE THREAD

**Issue by timotheebernard** [tensorflow/tfjs#332]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

Hi everyone and thanks for the great work!

Following this discussion https://groups.google.com/a/tensorflow.org/d/msg/tfjs/QV3n4NBDi70/pg2gCtdhCAAJ I'm creating this issue.

#### Describe the problem or feature request

tensorflowjs_converter does not prevent the user from exporting a keras h5 that only contains the weights (ex: keras save_weights_only=True). 
I've been able to export my "weights only" h5 to the web format, it resulted in a "modelTopology: null" in the model.json and an error when calling loadModel() (missing topology).

According to @caisq, it is a bug as the converter expects both the topology and the weights to be present.

If no one has any objection, I think I will be able to come up with a pull request by the end of this week.

**Comment by timotheebernard** [comment]
Hi again,

I must admit I'm a little bit confused. I started digging into the code and here's what I rapidly found: https://github.com/tensorflow/tfjs-converter/blame/master/python/tensorflowjs/converters/converter.py#L144

According to this code, a weights-only HDF5 file is one of the expected input format which contradicts @caisq message in the google groups: https://groups.google.com/a/tensorflow.org/d/msg/tfjs/QV3n4NBDi70/pg2gCtdhCAAJ

**Comment by caisq** [comment]
@timotheebernard 

Sorry - I gave misleading information before. tfjs-converter supports converting a weights-only HDF5 file, as you read correctly from the source code. In the conversion result, model.json will contain `null` in the `modelTopology` field. I meant to say that the JavaScript library currently doesn't support loading such converted files. The JavaScript library has a number of files and methods in which this check should be done, in https://github.com/tensorflow/tfjs-core/tree/master/src/io But I believe that only one of the (browser_files.ts) is actually doing the check. The check should be added to other files, including local_storage.ts, indexed_db.ts and browser_http.ts). In addition, I think a check needs to be added here as well:
https://github.com/tensorflow/tfjs-layers/blob/master/src/models.ts#L40

**Comment by timotheebernard** [comment]
Hi @caisq, thanks for the precision.
So, if my understanding is correct, one should be able to export a model without topology but tfjs should check the presence of the topology for every IO (which is currently not the case).

Since the issue name is "Prevent users from converting a model that has no topology", do you want me to close it or rename it "Ensure model has topology for every IO"?

**Comment by swirlingsand** [comment]
Using currently available version on pip (0.8), produces a `model.pb` and `weights_manifest.json`, not a `model.json`. 
Assuming the latest version produces a `model.json` as the docs promise, is there an ETA on publishing latest to pip?

**Comment by rthadur** [comment]
@caisq do you have any comments on this or can we close this issue ?
