### ISSUE TITLE
Convert a simple concrete function model to tfjs?

### ISSUE THREAD

**Issue by keajer** [tensorflow/tfjs#3335]
I am using tensorflow to serve some simple rule based model using concrete functions, https://www.tensorflow.org/guide/concrete_function and convert to TFLite to be used on the mobile client side. I try to apply the same model on the web client using the tfjs-converter. However, I am not able to call the function from the model. I wonder if anyone has an example doing this or any other workarounds?

**Comment by pyu10055** [comment]
@keajer you can follow the following code, which save a saved model from a concrete function

```
  def _create_saved_model(self):
    """Test a basic model with functions to make sure functions are inlined."""
    input_data = constant_op.constant(1., shape=[1])
    root = tracking.AutoTrackable()
    root.v1 = variables.Variable(3.)
    root.v2 = variables.Variable(2.)
    root.f = def_function.function(lambda x: root.v1 * root.v2 * x)
    to_save = root.f.get_concrete_function(input_data)

    save_dir = os.path.join(self._tmp_dir, SAVED_MODEL_DIR)
    save(root, save_dir, to_save)
```

This model can be converted to tfjs properly.

**Comment by keajer** [comment]
yes, this converts fine with following json
`{"format": "graph-model", "generatedBy": "2.2.0", "convertedBy": "TensorFlow.js Converter v1.7.4r1", "userDefinedMetadata": {"signature": {"inputs": {"x:0": {"name": "x:0", "dtype": "DT_INT32", "tensorShape": {}}, "y:0": {"name": "y:0", "dtype": "DT_INT32", "tensorShape": {}}, "z:0": {"name": "z:0", "dtype": "DT_INT32", "tensorShape": {}}}, "outputs": {"Identity:0": {"name": "Identity:0", "dtype": "DT_INT32", "tensorShape": {}}}}}, "modelTopology": {"node": [{"name": "x", "op": "Placeholder", "attr": {"dtype": {"type": "DT_INT32"}, "shape": {"shape": {}}}}, {"name": "y", "op": "Placeholder", "attr": {"shape": {"shape": {}}, "dtype": {"type": "DT_INT32"}}}, {"name": "z", "op": "Placeholder", "attr": {"dtype": {"type": "DT_INT32"}, "shape": {"shape": {}}}}, {"name": "PartitionedCall/add", "op": "AddV2", "input": ["x", "y"], "attr": {"T": {"type": "DT_INT32"}}}, {"name": "PartitionedCall/add_1", "op": "AddV2", "input": ["PartitionedCall/add", "z"], "attr": {"T": {"type": "DT_INT32"}}}, {"name": "Identity", "op": "Identity", "input": ["PartitionedCall/add_1"], "attr": {"T": {"type": "DT_INT32"}}}], "versions": {"producer": 175}}, "weightsManifest": [{"paths": [], "weights": []}]}`
I am not sure how to use this on the js side. could you please shed some light?

**Comment by pyu10055** [comment]
on js side you can do something as following:

```
const model = await tf.loadGraphModel(MODEL_URL);
const x = tf.scalar(-10, 'int32');
const y = tf.scalar(1, 'int32');
const z = tf.scalar(1, 'int32');
const result = model.execute({ x, y, z });
const data1 = result.arraySync();
console.log(data1);
```

**Comment by keajer** [comment]
i somehow got following:
```> const result = model.execute({ x, y, z });
Uncaught TypeError: model.execute is not a function```

**Comment by pyu10055** [comment]
@keajer can you share your code? It is hard to tell what was wrong with one line.

**Comment by keajer** [comment]
I ran this in my local node:
```
const tf = require('@tensorflow/tfjs-node');
const MODEL_PATH = 'file://Documents/.../cf_js/model.json';
const model = tf.loadGraphModel(MODEL_PATH);
const x = tf.scalar(-10, 'int32');
const y = tf.scalar(1, 'int32');
const z = tf.scalar(1, 'int32');
const result = model.execute({ x, y, z });
```
Then, I got the error msg above

**Comment by pyu10055** [comment]
```
const model = tf.loadGraphModel(MODEL_PATH);
```
should be
```
const model = await tf.loadGraphModel(MODEL_PATH);
```

**Comment by keajer** [comment]
getting this error
```
> const model = await tf.loadGraphModel(MODEL_PATH);
const model = await tf.loadGraphModel(MODEL_PATH);
              ^^^^^

Uncaught SyntaxError: await is only valid in async function

**Comment by keajer** [comment]
nvm, i figured out. thanks!
