### ISSUE TITLE
hope tensorflow suport  deno

### ISSUE THREAD

**Issue by chenxyzl** [tensorflow/tfjs#3341]
[deno](https://github.com/denoland/deno) is here.

**Comment by rthadur** [comment]
@chenxyzl this will not supported anytime in near future , so closing this request.

**Comment by chenxyzl** [comment]
Thanks for your response

**Comment by crowlKats** [comment]
@rthadur Deno added support for webgpu in 1.8. Would there be any chance that support for it would be provided?

**Comment by rthadur** [comment]
cc @pyu10055 @lina128

**Comment by kt3k** [comment]
I was able to run tfjs-core with CPU backend in Deno with the following import map configuration.

```json
{
  "imports": {
    "crypto": "./empty.js",
    "seedrandom": "https://esm.sh/seedrandom",
    "@tensorflow/tfjs-core": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core/dist/tf-core.fesm.js",
    "@tensorflow/tfjs-backend-cpu": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.fesm.js"
  }
}
```

test.js
```js
import * as tf from "@tensorflow/tfjs-core";
import "@tensorflow/tfjs-backend-cpu";
tf.randomGamma([2, 2], 1).print();
```

empty.js
```js
export default undefined;
```

```shellsession
$ deno run --import-map import_map.json --location https://example.com test.js
Tensor
    [[0.5183429, 4.3179331],
     [0.4852145, 0.1412067]]
```

**Comment by tlightsky** [comment]
> I was able to run tfjs-core with CPU backend in Deno with the following import map configuration.
> 
> import_map.json
> 
> ```json
> {
>   "imports": {
>     "crypto": "./empty.js",
>     "seedrandom": "https://esm.sh/seedrandom",
>     "@tensorflow/tfjs-core": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core/dist/tf-core.fesm.js",
>     "@tensorflow/tfjs-backend-cpu": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.fesm.js"
>   }
> }
> ```
> 
> test.js
> 
> ```js
> import * as tf from "@tensorflow/tfjs-core";
> import "@tensorflow/tfjs-backend-cpu";
> tf.randomGamma([2, 2], 1).print();
> ```
> 
> empty.js
> 
> ```js
> export default undefined;
> ```
> 
> ```
> $ deno run --import-map import_map.json --location https://example.com test.js
> Tensor
>     [[0.5183429, 4.3179331],
>      [0.4852145, 0.1412067]]
> ```

is it possible to switch to WebGPU backend?

**Comment by disjukr** [comment]
@tlightsky It seems work.

`deno.json`
```json
{
  "importMap": "import_map.json"
}
```

`import_map.json`
```json
{
  "imports": {
    "crypto": "./empty.js",
    "seedrandom": "https://esm.sh/seedrandom",
    "@tensorflow/tfjs-core": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core/dist/tf-core.fesm.js",
    "@tensorflow/tfjs-backend-cpu": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.fesm.js",
    "@tensorflow/tfjs-backend-webgpu": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu/dist/tf-backend-webgpu.fesm.js"
  }
}
```

`test.ts`
```typescript
import * as tf from "@tensorflow/tfjs-core";
import "@tensorflow/tfjs-backend-webgpu";

await tf.ready();
tf.randomGamma([2, 2], 1).print();
```

```sh
$ deno --version
deno 1.23.2 (release, x86_64-pc-windows-msvc)
v8 10.4.132.8
typescript 4.7.2

$ deno run -A --unstable test.ts
Tensor
    [[0.9347293, 0.4923133],
     [2.3871257, 0.3427154]]
```

**Comment by tlightsky** [comment]
> @tlightsky It seems work.
> 
> `deno.json`
> 
> ```json
> {
>   "importMap": "import_map.json"
> }
> ```
> 
> `import_map.json`
> 
> ```json
> {
>   "imports": {
>     "@tensorflow/tfjs-core": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.18.0/dist/tf-core.fesm.js",
>     "@tensorflow/tfjs-backend-webgpu": "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu@0.0.1-alpha.11/dist/tf-backend-webgpu.fesm.js"
>   }
> }
> ```
> 
> `test.ts`
> 
> ```ts
> import * as tf from "@tensorflow/tfjs-core";
> import "@tensorflow/tfjs-backend-webgpu";
> 
> await tf.ready();
> tf.randomGamma([2, 2], 1).print();
> ```
> 
> ```shell
> $ deno --version
> deno 1.23.2 (release, x86_64-pc-windows-msvc)
> v8 10.4.132.8
> typescript 4.7.2
> 
> $ deno run -A --unstable test.ts
> Tensor
>     [[0.9347293, 0.4923133],
>      [2.3871257, 0.3427154]]
> ```

yeah, but seems have issue when running more complex model,
currently try to go through the way of tfjs on top of WebGPU/WebGL in Canary Chrome
