### ISSUE TITLE
Output node name not in the graph

### ISSUE THREAD

**Issue by naoufelfrioui** [tensorflow/tfjs#337]
I used  : "tensorflowjs_converter  --input_format=tf_saved_model  --output_node_names="Predictions/Reshape_1"  --saved_model_tags=serve  inference_graph_v2\saved_model   web_model ".

the object detection Model is Faster_rcnn 
I want to convert SavedModel to a web-friendly format . but I have this error

"AssertionError: Predictions/Reshape_1 is not in graph"

could you please help me

**Comment by pyu10055** [comment]
@naoufelfrioui can you verify if the node name Predictions/Reshape_1 is actually in your Faster_rcnn model? The name kinda looks like from our mobilenet example.

**Comment by dsmilkov** [comment]
Hi @naoufelfrioui, did you get a chance to look at the graph and figure out the name of the output node? In TensorFlow Python, if you have a handle to the `tensor`, you can print `tensor.name` to get its name.

**Comment by pyu10055** [comment]
if it is saved model, we can print out all the signatures.

**Comment by dsmilkov** [comment]
@pyu10055 That would be awesome! Great suggestion.

**Comment by nsthorat** [comment]
This should be fixed.
