### ISSUE TITLE
Tfjs-node Error: Unsupported tensor DataType: DT_UINT8

### ISSUE THREAD

**Issue by jacklynlxq** [tensorflow/tfjs#3374]
#### TensorFlow.js version
"@tensorflow/tfjs-node": "^2.0.0"

#### Browser version
N/A

#### Describe the problem or feature request
I'm trying to load a model trained using Tensorflow Object Detection API and it throws an error: 
```
Error: Unsupported tensor DataType: DT_UINT8, try to modify the model in python to convert the datatype
```

I read it from [here](https://github.com/tensorflow/tfjs/pull/2700) that tfjs doesnt certain datatypes but is there a hacky way to convert UINT8 to compatible datatypes without having to retrain my model in Saved Model format?

I dont understand why the model doesnt work here but it works after being coverted to TFjs model.

#### Code to reproduce the bug / link to feature request
```
var express = require('express');
const http = require('http');
var app = express();
const port = 8080;

const tf = require('@tensorflow/tfjs-node');

async function loadModel(){
  const model = await tf.node.loadSavedModel("saved_model", ['serve'], 'serving_default');
  console.log(model);
}

app.listen(port, async () => {
    console.log(`Example app listening at http://localhost:${port}`);
    loadModel();
});
```

**Comment by rthadur** [comment]
@jacklynlxq I believe there is no way to avoid it, you have to retrain the model.
cc @pyu10055

**Comment by jacklynlxq** [comment]
> @jacklynlxq I believe there is no way to avoid it, you have to retrain the model.
> cc @pyu10055

Okay, thanks for clarifying.
