### ISSUE TITLE
Cannot setWeights on Embedding Layer

### ISSUE THREAD

**Issue by yawetse** [tensorflow/tfjs#3389]
https://github.com/tensorflow/tfjs/blob/3688c7321aa186b412a7469993f07f13e8408a9a/tfjs-layers/src/engine/topology.ts#L1223

this.weights.length is always undefined

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
