### ISSUE TITLE
PoseNet MobileNetV1 does not have stride 32. 

### ISSUE THREAD

**Issue by gel11** [tensorflow/tfjs#3394]
#### TensorFlow.js version
@tensorflow/tfjs@2.0.0
@tensorflow/tfjs-node@2.0.0
@tensorflow-models/posenet@2.2.1

#### Browser version
Chrome - Version 80.0.3987.149 (Official Build) (64-bit)

#### Problem 
Seems like `MobileNetV1` can not use `32` as `outputStride` in the Posenet model. Request to ` https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/quant2/050/model-stride32.json` returns 404. Given https://storage.googleapis.com/tfjs-models there seems only to be a `32 outputStride` for the `ResNet50` model. But given the [README](https://github.com/tensorflow/tfjs-models/tree/master/posenet) there should be for both models. 

#### Code to reproduce the bug
Define A `MobileNetV1` model with `32` as `outputStride`:

```  
require('@tensorflow/tfjs-node');

const posenet = require('@tensorflow-models/posenet');

posenet.load({
  architecture: 'MobileNetV1',
  outputStride: 32
});
```

**Comment by hoaquocphan** [comment]
Hi @annxingyuan 
I have same issue with @gel11 
I checked the ticket  https://github.com/tensorflow/tfjs-models/pull/459 and still don't have the answer.
could you give me the answer: are there any tfjs model for stride 32?
Thanks
