### ISSUE TITLE
Missed data normalization in the predictSample

### ISSUE THREAD

**Issue by wirtaw** [tensorflow/tfjs#3401]
#### TensorFlow.js version
 "@tensorflow/tfjs@1.7.4"
"@tensorflow/tfjs-node" : 1.3.2
#### Browser version
-
#### Node version
v12.16.1
####  npm version
 6.14.5
#### Describe the problem or feature request
Then running example by [Codelab](https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab/#4) sources - sample data back  pitch type - `Fastball (4-seam)`
But in example comment and by data in the csv must be - `Curveball`
#### Code to reproduce the bug / link to feature request
Before sample data normalization return 
```bash
accuracyPerClass {
  'Fastball (2-seam)': { training: 0.7185505301601661, validation: 0.6986126235348639 },
  'Fastball (4-seam)': { training: 0.8041197856226936, validation: 0.6679492705687881 },
  'Fastball (sinker)': { training: 0.5543037599927575, validation: 0.40438333789759784 },
  'Fastball (cutter)': { training: 0.7544288540147245, validation: 0.6399490784760564 },
  Slider: { training: 0.7030178446555511, validation: 0.6925535777537152 },
  Changeup: { training: 0.7323414023183287, validation: 0.6433946020342409 },
  Curveball: { training: 0.7786480566757964, validation: 0.6720112682203763 }
}
predictSample [2.668,-114.333,-1.908,4.786,25.707,-45.21,78,0]
result [2.802596928649634e-44,1,0,0,0,0,0] predictedPitch 1 'Fastball (4-seam)'

```
After problem solution - normalize sample data in the [predictSample](https://github.com/wirtaw/baseball-tensorflow-pitch-type/blob/a2401d416d5b8b4e6b103222a02aba38f4636896/src/pitch_type.js#L112) function
```bash
1999ms 28558us/step - acc=0.814 loss=0.498 
accuracyPerClass {
  'Fastball (2-seam)': { training: 0.5205437056370938, validation: 0.5150882147124503 },
  'Fastball (4-seam)': { training: 0.7875944544905796, validation: 0.6238932343688793 },
  'Fastball (sinker)': { training: 0.6789201184713064, validation: 0.4676991201750934 },
  'Fastball (cutter)': { training: 0.7440306098423898, validation: 0.63376548955217 },
  Slider: { training: 0.602961182523286, validation: 0.6999326177127659 },
  Changeup: { training: 0.7483404694814235, validation: 0.6366032464616 },
  Curveball: { training: 0.8942686270378762, validation: 0.7976557667413726 }
}
predictSample [2.668,-114.333,-1.908,4.786,25.707,-45.21,78,0]
[0.5833017591339648,0.5769492653845572,0.533830954048916,0.6717661028237695,0.40997410954427776,0.07895708794832494,0.41850220264317173,0]
result [2.1684355699935765e-10,3.1887741145514292e-12,3.5616327664911296e-8,6.949693442948046e-7,0.022125843912363052,0.00005654788401443511,0.9778168797492981] predictedPitch 6 'Curveball'

```

[`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js)
[`tfjs-node`](https://stackoverflow.com/questions/tagged/tfjs-node)

**Comment by rthadur** [comment]
@wirtaw please let us know if this is still an issue ,if yes can you please provide steps to reproduce the error ?

**Comment by wirtaw** [comment]
@rthadur yes, this issue is actual
steps for reproduce

- Clone and install [baseball-node](https://github.com/tensorflow/tfjs-examples/tree/master/baseball-node) exaple
- In the [server.js](https://github.com/tensorflow/tfjs-examples/blob/master/baseball-node/server.js) after `console.log('training complete');` add line to emit predictSample `io.emit('predictResult', await pitch_type.predictSample([ 2.668, -114.333, -1.908, 4.786, 25.707, -45.21, 78, 0]));`
- Run `npm run start-server`
- After training complete `[console.log(result)](https://github.com/tensorflow/tfjs-examples/blob/046a2a18f00bf5c24d8f5fc766127d2b217a1a45/baseball-node/pitch_type.js#L121)` return `[ [
    1, 0, 0, 0,
    0, 0, 0
  ] ] 
`
this falsy resut
