### ISSUE TITLE
Incorrect documentation of coco-ssd

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#3404]
https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd states:

"The model is capable of detecting 90 classes of objects. "

It links to https://github.com/tensorflow/tfjs-models/blob/master/coco-ssd/src/classes.ts

which despite having 90 ids has only 80 entries. E.g. 29 and 30 are missing.

**Comment by rthadur** [comment]
@ToonTalk do you wish to contribute to this ?

**Comment by ToonTalk** [comment]
I could change "90" to "80" but I'm not sure why there are missing entries. Intentional or a mistake?

**Comment by rthadur** [comment]
cc @pyu10055 any thoughts ?

**Comment by pyu10055** [comment]
@ToonTalk These classes are from coco dataset. Initially there are 90 classes, and they removed some of them and now it ended up with 80. I will update the documentation to reflect that.

**Comment by rthadur** [comment]
I have  made the change [here](https://github.com/tensorflow/tfjs-models/pull/457) , @pyu10055 can you please review.
