### ISSUE TITLE
Unhandled Rejection (Error): No backend found in registry in a React App

### ISSUE THREAD

**Issue by programandoconro** [tensorflow/tfjs#3413]
Hi, 
System Specifications:

Fedora 32
React JS
npm
Tensorflow-mobilenet
Behavior:
This basic React App using mobilenet from @tensorflow-models was working fine a few months ago. Now I am getting Unhandled Rejection error.
```
import * as mobilenet from '@tensorflow-models/mobilenet';
import photo from './assets/file.jpg';
import { loadImage } from 'canvas';
import React, { useState } from 'react';

const App = () => {
	const [res, handleRes] = useState([]);
	const myPhoto = () => {
		return <img src={photo} alt="foto "></img>;
	};
	const myPrediction = async () => {
		const loadModel = await mobilenet.load();
		const pic = await loadImage(photo);
		const pred = await loadModel.classify(pic);
		console.log(pred);
		handleRes(pred);
	};

	return (
		<div className="App">
			{myPhoto()}
			<button onClick={(e) => myPrediction(e)}>Predict</button>
			{res.map((e, k) => (
				<li key={k}>
					<h1>{e.className + ': ' + Math.round(e.probability * 100) + '%'}</h1>
				</li>
			))}
		</div>
	);
};

export default App;

```
![file](https://user-images.githubusercontent.com/50117686/84123354-a49b9300-aa31-11ea-8a2e-c189d120804e.jpg)

This basic example should make a prediction on the uploaded image.

I made a post here https://programandoconro.wordpress.com/2019/12/30/react-app-para-clasificacion-de-imagenes-con-machine-learning/

Full App code is here https://github.com/programandoconro/Image-Classification-ML-App (not working either).
file

Fortunately, deployed App still working https://programandoconro.github.io/Image-Classification-ML-App/

Sample image attached.

Thank you,

**Comment by tafsiri** [comment]
That message suggests you are using [tfjs 2.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v2.0.0) without a backend imported, but the package.json in your linked repository says you are using 1.5.1. If there some discrepancy? You can check what version is loaded on the page by doing `console.log(tf.version)`

**Comment by programandoconro** [comment]
You were right, after switching back to tfjs-core ^1.5.1 version the problem was solved. Thank you very much, now I feel dummy. Is there a way I can make it work with 2.0 version?

**Comment by programandoconro** [comment]
Thank you @tafsiri.

**Comment by tafsiri** [comment]
See the link i posted above for instructions to upgrading to tfjs 2.0. You can also checkout the readme for the specific backend you want. Or you can use the 2.0.0 union package (tfjs) which handles this for you.

**Comment by programandoconro** [comment]
Thank you. :)
