### ISSUE TITLE
Formatting error in BodyPix documentation

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#3421]
https://github.com/tensorflow/tfjs-models/tree/master/body-pix

has the wrong nesting of lists for SegmentPerson()

![image](https://user-images.githubusercontent.com/2138696/84174881-bae93380-aab1-11ea-8aee-af28c157baa9.png)

The other 3 listings of `config `are nested correctly

**Comment by rthadur** [comment]
@ToonTalk do you wish to contribute ?
