### ISSUE TITLE
less flops but slower model, profiler required

### ISSUE THREAD

**Issue by flyingmrwang** [tensorflow/tfjs#3425]
(same question on stackoverflow: https://stackoverflow.com/questions/62295540/less-flops-but-slower-model-profiler-required)
The thing is I have a tiny mobile-unet which has only **~1Mflops**, which is much lighter than mobilenet. But it has only **~3 fps** running on webgl backend. I was suggested to forget about the **~10ms** taken by model.predict() and take **300ms** as prediction time. 
So what I want is to figure out which operator delayed the whole thing. Is there any way to **profile** each operator in tfjs model right now? 

![image](https://user-images.githubusercontent.com/18489060/84224435-1d245180-ab0f-11ea-846b-cea47672138b.png)

It seems https://github.com/tensorflow/tfjs/issues/286 has mentioned before, but any **suggestion** is appreciated.

**Comment by flyingmrwang** [comment]
ref of the prediction time: https://github.com/tensorflow/tfjs/issues/537

**Comment by flyingmrwang** [comment]
> I think [tf.enableDebugMode] will help here (https://js.tensorflow.org/api/latest/#enableDebugMode) it will print out more granular timing information about the execution of individual kernels.

Thanks tafsiri, I will give it a try. By the way, I just find I can also get the layer-wise performance by adding my model to tfjs/e2e/benchmarks/, which is pretty simple and clear.

**Comment by lebron8dong** [comment]
@flyingmrwang  Is there any way to get flops
