### ISSUE TITLE
How to support custom ops in saved models

### ISSUE THREAD

**Issue by aknoerig** [tensorflow/tfjs#3426]
#### TensorFlow.js version
tfjs-node 2.0.0

#### Browser version
Node 12

#### Describe the problem or feature request
Using the recent ability to load models directly with `tfjs-node`, I have been able to load and run predictions on complex models such as StyleGAN directly inside of node.

This approach is now failing with [StyleGAN2](https://github.com/NVlabs/stylegan2), due to its use of [some custom ops](https://github.com/NVlabs/stylegan2/tree/master/dnnlib/tflib/ops) (as also noted in its [requirements](https://github.com/NVlabs/stylegan2#requirements)). Loading a saved model with tfjs-node produces the following error message:

> Error: Failed to load SavedModel: Op type not registered 'FusedBiasAct' in binary running on PC-980. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

Now I'm wondering what is the best approach to enable the use of custom ops (written in C++ and Python for CUDA) such as these. Two approaches I can think of are:

* Translate ops to JS using `tf.registerOp()`
* Compile a custom libtensorflow including these ops

Both seem to be very challenging to achieve. Would you have some advice which way to go, or another alternative approach?

**Comment by pyu10055** [comment]
@aknoerig Thank you for using our node backend, let me provide my thoughts on this topic:

1. If the custom op is easy to be rewritten in js, registerOp could be good option. It also depends on if you are using saved model direct execution, since direction execution does not support registerOp through js.
2. option 2 probably the better if op is complicated or using saved model direct execution. I don't you need to rebuild the whole libtensorflow, you can just compile the custom op, add expose TF API to node.js NAPI to register custom op.

If you figure out the solution for option 2, it would be great if you contribute back to our node.js backend, so other can also seamlessly use custom ops.

Thanks

**Comment by aknoerig** [comment]
Thanks for your advice on this! I am directly executing the signatures of the saved model, so good to know that `registerOp` is not supported for this. Option 2 therefore sounds promising!

However, in the meantime I noticed that in my specific case, the authors have provided an alternative implementation that does not require the custom ops (using `impl = 'ref'`). What's nice about this is that I can still train natively using the custom ops, and only activate the alternative implementation when I export to a saved model. This way, tfjs-node is able to load and excute the model.

**Comment by playground** [comment]
@aknoerig have you been able to get option 2 implemented?  I'm running into a similar issue with tfjs-node 3.0.0-rc.1
 loading saved model in Raspberry Pi 4.  

@pyu10055 can you recommend a solution?

**Comment by pyu10055** [comment]
@playground you might want to try the new upcoming build for raspbarryPI, it is based on TF 2.5.

**Comment by aknoerig** [comment]
@playground Sorry, no, I haven't explored this any further.

**Comment by playground** [comment]
@pyu10055 is that available now?  can you point me to it?

**Comment by playground** [comment]
> @playground you might want to try the new upcoming build for raspbarryPI, it is based on TF 2.5.

@pyu10055 where can I try out the up coming build?
