### ISSUE TITLE
Failed to load @tensorflow-models/speech-commands.min.js.map - Links Broken 404

### ISSUE THREAD

**Issue by lihost** [tensorflow/tfjs#3434]
#### TensorFlow.js 1.7.4

Below link is broken, throwing 404

In code, this is being called as follows
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands"></script>
```
Which gets translated in browser as below url
```
https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands.min.js.map
```

**Comment by el1tehAx0r** [comment]
hey was this ever fixed? I am getting an issue but with the cocossd cdn. It just happened today. How did you fix this issue?

**Comment by lihost** [comment]
> hey was this ever fixed? I am getting an issue but with the cocossd cdn. It just happened today. How did you fix this issue?

@el1tehAx0r - Not yet, still same.

**Comment by rthadur** [comment]
@tafsiri gentle ping if you have any update on this.Thank yo

**Comment by mydigitaltears** [comment]
Why is this closed? Has anyone resolved this issue?
