### ISSUE TITLE
wechat plugin support for tfjs 2.0

### ISSUE THREAD

**Issue by Starsky-Synlitec** [tensorflow/tfjs#3437]
This is not a issue but a feature needed.
When can we use facemesh with tfjs 2.0 ? And also the wechat-plugin with tfjs 2.0 ?
Looking forward to it ~: )

**Comment by tafsiri** [comment]
You should be able to use facemesh with tfjs 2.0 today, just make sure to include a backend if you are using tfjs-core directly. Have you tried it and run into a problem?

**Comment by Starsky-Synlitec** [comment]
@tafsiri 
Thx for the reply. I tried but with wechat plugin. 
I guess it is because of the wechat-plugin:
 https://github.com/tensorflow/tfjs-wechat
which is not updated to fit 2.0 yet.
