### ISSUE TITLE
请问object_detection这个方式能否在nodejs环境下执行！

### ISSUE THREAD

**Issue by Wlisfes** [tensorflow/tfjs#3438]
### 您好！
**object_detection这个例子在浏览器端使用会加载大量的文件，size高达几十mb，因为我是使用训练后savs_model的模型，我想把这一块移到nodejs服务器执行，从web上传图片，nodejs解析后返回web，请问能否以这种方式运行？**

**Comment by rthadur** [comment]
please use template [here](https://github.com/tensorflow/tfjs/issues/new) to reopen a new issue.
