### ISSUE TITLE
Render `toPixels` as webgl texture

### ISSUE THREAD

**Issue by alexionby** [tensorflow/tfjs#3455]
For `webgl` backend,
Why did you decide to convert result from `tensor` to `Uint8ClampedArray` and draw it as `canvas.getContext('2d')`. Seems like it would be much better for performance to render `tensor` as **texture** on `canvas.getContext('webgl')`.

**Comment by rthadur** [comment]
Thanks for reporting please use the [template](https://github.com/tensorflow/tfjs/issues/new) to open a new issue with all the required information for us to help you.

**Comment by strumbelj** [comment]
Same issue here, reading a video, processing the frame and predict it takes a few ms. Putting the tensor to a canvas (with t.data / t.array / drawImage / putImageData / ...) needs 3 seconds for 512x512x1 images and thus is a huge bottleneck in my application.

**Comment by FabioRomagnolo** [comment]
Any news about this implementation?
