### ISSUE TITLE
Render `toPixels` as webgl texture

### ISSUE THREAD

**Issue by alexionby** [tensorflow/tfjs#3457]
#### TensorFlow.js version
tfjs 1.7.4 - 2.0.0

#### Describe the problem or feature request
For webgl backend,
Why did you decide to convert result from `tensor` to `Uint8ClampedArray` and draw it as `canvas.getContext('2d')`. Seems like it would be much better for performance to render `tensor` as **texture** on `canvas.getContext('webgl')`.

**Comment by rthadur** [comment]
Thanks for reporting please use the template to open a new issue with all the required information for us to help you.

**Comment by strumbelj** [comment]
Is there a solution to render tensors as texture, e.g. `gl.texImage2D(gl.TEXTURE_2D, level, internalFormat, srcFormat, srcType, TENSOR);` ? Or are there any equivalent (in terms of speed) rendering possibilites?

**Comment by lina128** [comment]
Link https://github.com/tensorflow/tfjs/issues/3455

**Comment by Linchenn** [comment]
Now we have tf.browser.draw API, which support drawing data directly to GPU data.

**Comment by Apj-infinty** [comment]
> Now we have tf.browser.draw API, which support drawing data directly to GPU data.


Hi @Linchenn , I just used it and its returning an error. I believe it is only the backend issue. Is there any way to set it to the backend I have created which is referenced from here   #6683 
 
Error: Kernel 'Draw' not registered for backend 'custom-webgl2'
    at Engine.runKernel (engine.ts:551:1)
    at Module.draw (browser.ts:431:1)

**Comment by Linchenn** [comment]
> > Now we have tf.browser.draw API, which support drawing data directly to GPU data.
> 
> Hi @Linchenn , I just used it and its returning an error. I believe it is only the backend issue. Is there any way to set it to the backend I have created which is referenced from here #6683
> 
> Error: Kernel 'Draw' not registered for backend 'custom-webgl2' at Engine.runKernel (engine.ts:551:1) at Module.draw (browser.ts:431:1)

Hi @Apj-infinty Yes, Draw API currently does not have implementation for WebGL backend. IIUC, WebGPU backend supports this.

**Comment by Apj-infinty** [comment]
Thanks for the reply! I was able to use Draw API using WebGPU backend , which is 100x faster than tf.browser.toPixels().
