### ISSUE TITLE
Any workarounds for converting a keras graph model with custom layers into tf.js?

### ISSUE THREAD

**Issue by MyJumperBroke23** [tensorflow/tfjs#3466]
#### TensorFlow.js version

Keras: 2.3.1
Tensorflow: 2.20
Tensorflow.js: 1.7.2

#### Describe the problem or feature request

I'm trying to convert a keras HDF5 graph model with custom layers into tensorflow.js. If I don't specify the output format to be a graph model, the command line converter automatically converts it into a layers model, and lets me create the custom layers in javascript. However, this results in errors when trying to input something into the tensor. When I specify the output to be a graph model, it gives me the error:

`ValueError: Unknown layer: Layer-Name`

Are there any workarounds to this?

#### Code to reproduce the bug / link to feature request

Convert to layers model:

`tensorflowjs_converter --input_format=keras  --quantization_bytes=1 --weight_shard_size_bytes=9999999999999 ~/PycharmProjects/TrueSky/models/unet_70.h5 ~/PycharmProjects/TrueSky/models/tfjs_model2`

Convert to graph model:

`tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model --quantization_bytes=1 --weight_shard_size_bytes=9999999999999 ~/PycharmProjects/TrueSky/models/unet_70.h5 ~/PycharmProjects/TrueSky/models/tfjs_model2`

**Comment by pyu10055** [comment]
@MyJumperBroke23 What is the error you getting when you converting the model to tfjs_graph_model output format?

**Comment by MyJumperBroke23** [comment]
@pyu10055 The exact error is 

`ValueError: Unknown layer: FixedDropout`

**Comment by pyu10055** [comment]
@MyJumperBroke23 That looks like error from conversion to tfjs_layers_model ? can you share the command line and its output here.

**Comment by MyJumperBroke23** [comment]
@pyu10055 Checking on the json file, it seems like it is now graph-model, but I am getting a different error now, so I will open a separate issue
