### ISSUE TITLE
node-pre-gyp info This Node instance does not support builds for N-API v6 using Electron and tfjs-node

### ISSUE THREAD

**Issue by delebash** [tensorflow/tfjs#3484]
#### TensorFlow.js version
   @tensorflow/tfjs 2.0.2
   @tensorflow/tfjs-node 2.0.1

Windows 10 x64
Node 12.18.1-x64
Electron 9.0.4

#### Browser version
Chrome Version 83.0.4103.106 (Official Build) (64-bit)
#### Describe the problem or feature request
I have seen a few issues discussing this error with N-API v4 but I am using node version node-v12.18.1-x64 which is the current lts and electron version 9.0.4 and get the above error
#### Code to reproduce the bug / link to feature request
With the above system configuration and this package configuration

  "dependencies": {
    "@tensorflow-models/facemesh": "0.0.3",
    "@tensorflow/tfjs": "^2.0.1",
    "@tensorflow/tfjs-node": "^2.0.1",
    "electron": "^9.0.4",
    "stats.js": "^0.17.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "electron main.js"
  },

run npm install
then npm start
this is assuming you have a render.js file with 

const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node')

My code repository for testing
https://github.com/delebash/facemesh_node

**Comment by G2Jose** [comment]
> node-pre-gyp info This Node instance does not support builds for N-API version 6

Have this exact same issue on `@tensorflow/tfjs-node 2.0.1`

**Comment by ifeLight** [comment]
Also having this issues, is there any solution yet?

**Comment by sprengerst** [comment]
Same here

**Comment by Fatxx** [comment]
Same issue on OSX Catalina

**Comment by HaoLiHaiO** [comment]
Same here with 
Windows 10 x64
Node 12.18.1-x64

**Comment by tafsiri** [comment]
Could this be related to the issue described here https://github.com/tensorflow/tfjs/issues/3651#issuecomment-686701119, seems like there are some electron specific elements to consider in terms of version compatibility. Another electron related issue is this one https://github.com/tensorflow/tfjs/issues/2558

**Comment by frank505** [comment]
having this issue right now
