### ISSUE TITLE
[Contribution] Real-time semantic segmentation in the browser

### ISSUE THREAD

**Issue by hugozanini** [tensorflow/tfjs#3486]
Hello,

I'd like to submit my project of Real-Time Instance Segmentation in the browser using TensorFlow.js as a contribution to the pool of examples.

[https://github.com/hugozanini/realtime-semantic-segmentation](https://github.com/hugozanini/realtime-semantic-segmentation)

Thank you,

**Comment by tafsiri** [comment]
@hugozanini Great! You should make a PR to this file https://github.com/tensorflow/tfjs/blob/master/GALLERY.md adding the link to your project.
