### ISSUE TITLE
Problem with Inferencing with Custom Object Detection Model

### ISSUE THREAD

**Issue by jacklynlxq** [tensorflow/tfjs#3494]
#### TensorFlow.js version
2.0.0

#### Browser version
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

#### Describe the problem or feature request
I tried to train my own custom object detection model using Tensorflow's Object Detection API (using Tensorflow 1.14) and converted the model in Saved Model format into tfjs model. I followed this [tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#) and used SSD Mobilenet v2. 

I was inferencing using executeAsync() for an object detection task. The function works well when I have a detection continuously in my live video. However, if I have no detection in any particular frame, there will be an error while it executes the executeAsync() function.

> TypeError: Cannot read property '0' of undefined

And here's the memory leak that happened when there's no detection. I am thinking the issue lies in the dangling tensors that are created in executeAsync() since if there's a detection I would dispose the tensors, but if there's no detection, I couldn't get a reference of the dangling tensors since the ```test_result``` variable hasn't been created yet due to the aforementioned error.

> {unreliable: false, numBytesInGPU: 422861990, numTensors: 1111, numDataBuffers: 673, numBytes: 320663096}
> {unreliable: false, numBytesInGPU: 490830799, numTensors: 1263, numDataBuffers: 752, numBytes: 371606568}
> {unreliable: false, numBytesInGPU: 558799608, numTensors: 1415, numDataBuffers: 831, numBytes: 422550040}

I tried converting from a pretrained inference graph (in Tensorflow Saved Model format) to a tfjs model and it works fine - if there's no detection executeAsync() would just return an empty array. It is only the problem with custom trained models.

#### Code to reproduce the bug / link to feature request
```
async detect(video){
    console.log("detecting...");

    var example = tf.browser.fromPixels(video);
    var tf4d = example.expandDims(0);

    try{
        // error if there's no detection
        const test_result = await this.model.executeAsync({ image_tensor: tf4d }, ['detection_boxes', 'num_detections', 'detection_classes', 'detection_scores']) as tf.Tensor[];
        
        this.no_detection = false;
        var detection_boxes = test_result[0].dataSync();
        var num_detections = test_result[1].dataSync();
        var detection_classes = test_result[2].dataSync();
        var detection_scores = test_result[3].dataSync();

        // dispose tensors to avoid memory leak
        await Promise.all(test_result.map(t => t.data()));
        test_result.map(t => t.dispose());
        tf.dispose(test_result);

        tf4d.dispose();
        example.dispose();

        console.log(tf.memory());

    }
    catch(error){
        console.log("No detection");
        console.log(error)
        this.no_detection = true;
        // dispose of tensor created from images if theres no detection
        tf4d.dispose();
        example.dispose();
        console.log(tf.memory());
        
    }

}
```

**Comment by pyu10055** [comment]
@jacklynlxq can you share the full error stack? so we can see where the error is originated, thanks.

**Comment by jacklynlxq** [comment]
> @jacklynlxq can you share the full error stack? so we can see where the error is originated, thanks.

This is the full error stack:
```
TypeError: Cannot read property '0' of undefined
    at tf-core.esm.js:17
    at ei (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at tf-core.esm.js:17
    at Array.map (<anonymous>)
    at Za (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at tf-core.esm.js:17
    at o.getAndSaveBinary (tf-core.esm.js:17)
    at o.runWebGLProgram (tf-core.esm.js:17)
```

Also, after disposing the variables using ```tf.dispose()```, ```tf.disposeVariables()```, ```tf.engine().startScope()``` and ```tf.engine().endScope()``` (I was trying everything I could to clear the tensors haha), I found that only ```numBytesInGPU``` is increasing but the ```numTensors``` stays the same. 

```{unreliable: false, numBytesInGPU: 15067536, numTensors: 199, numDataBuffers: 199, numBytes: 15002264}```
```{unreliable: false, numBytesInGPU: 15068336, numTensors: 199, numDataBuffers: 199, numBytes: 15002264}```
```{unreliable: false, numBytesInGPU: 15069136, numTensors: 199, numDataBuffers: 199, numBytes: 15002264}```
```{unreliable: false, numBytesInGPU: 15069936, numTensors: 199, numDataBuffers: 199, numBytes: 15002264}```

**Comment by pyu10055** [comment]
@jacklynlxq can you try with the latest build? This could be related to this issue https://github.com/tensorflow/tfjs/issues/3739

**Comment by jacklynlxq** [comment]
> @jacklynlxq can you try with the latest build? This could be related to this issue #3739

I got this error instead

```
Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
    at convertToTensor (tensor_util_env.js:84)
    at less_ (less.js:37)
    at Module.less (operation.js:40)
    at Module.executeOp (logical_executor.js:34)
    at operation_executor.js:63
    at engine.js:307
    at Engine.scopedRun (engine.js:317)
    at Engine.tidy (engine.js:306)
    at Module.tidy (globals.js:166)
    at operation_executor.js:63
```

**Comment by pyu10055** [comment]
@jacklynlxq can you share the model files with us to reproduce this problem? or if you have a codepen would be great.

**Comment by jacklynlxq** [comment]
I just realised that before this I was using Tfjs v1.7.4 for the browser side prediction - works but produced the initial error and I'm using tensorflowjs 2.0.1 for tensorflowjs_converter. When I upgraded it to Tfjs 2.0.1 / 2.3.0 for browser side prediction, it produced the latest error I mentioned. 

[tfjs_model.zip](https://github.com/tensorflow/tfjs/files/5127388/tfjs_model.zip)

Thanks
