### ISSUE TITLE
Result of tf.pow inconsistent on CPU vs. GPU

### ISSUE THREAD

**Issue by jgartman** [tensorflow/tfjs#350]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.2
#### Browser version
Chrome 66.0.3359.139
#### Describe the problem or feature request
The output of the pow function is inconsistent when run on the CPU compared to the GPU.  On CPU trying to take a negative base to a fractional exponent results in `nan` where as on the GPU it's either `-1` times the absolute value of the base to that exponent or the  absolute value of the base to that exponent.  Other libraries like TF or numpy are similar to the CPU implementation and return `nan` in this case.
#### Code to reproduce the bug / link to feature request
```
const a = tf.scalar(-4);
const b = tf.scalar(1.5);
const result = tf.pow(a, b);
```

**Comment by tafsiri** [comment]
@jgartman @nsthorat It looks like this is has been fixed??
