### ISSUE TITLE
tfjs-node, windows 10, duplicate 85mb file

### ISSUE THREAD

**Issue by camhart** [tensorflow/tfjs#3508]
#### TensorFlow.js version
tfjs-node v2.0.1 on windows 10

#### Describe the problem or feature request
@tensorflow/tfjs-node contains a duplicate file at:
`deps/lib/tensorflow.dll`
and
`lib/napi-v5/tensorflow.dll`

The file is 85mb in size.  Could the two files be simplified with one?

**Comment by rthadur** [comment]
cc @kangyizhang can you please help with this ?

**Comment by pyu10055** [comment]
It should, with the latest code, the installer will move the deps/lib/tensorflow.dll to lib/napi-v[x]/tensorflow.dll.
