### ISSUE TITLE
TensorFlow.js crashes on mobile Safari

### ISSUE THREAD

**Issue by andreaferracani** [tensorflow/tfjs#352]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs 0.11.1
tfjs-converter 0.4.0

#### Browser version
Mobile Safari 11

#### Describe the problem or feature request
The browser crashes without any error in console, also loading a simple and small network model converted using tensor flow js converter

**Comment by caisq** [comment]
@andreaferracani Can you provide a little more information about the crash? What model were you converting and using in the browser? At what stage does the crashing happen? When you call `tf.loadFrozenModel` or some other method?

cc @pyu10055

**Comment by andreaferracani** [comment]
1. The model is a simplified version of Yolo v. 1
2. The crash happens when we use dataSync() as it follows
``` 
var result_t = model.execute({"image_input" : input});
var result = result_t.dataSync();
```

Thank you

**Comment by pyu10055** [comment]
@andreaferracani thank you for reporting this bug, in order to properly reproduce the problem, is it possible for you to share the model with us?
And does this issue happens only on mobile Safari? How about desktop and mobile chrome?

Thanks!

**Comment by andreaferracani** [comment]
Hi this is the model which causes the crash and the demo in the zipped folder https://drive.google.com/open?id=1UuWSH3FgIqBoHbPdPJCUA9iGV3fXBu04

**Comment by pyu10055** [comment]
Your process method is calling itself continuously, which causing the browser to freeze.
Increase the timeout or set a limit on how many to run would help.

``` 
 13        function process(model) {
 14             var input = tf.randomNormal([1, 448, 448, 3])
 15             var result = model.execute({"image_input" : input}).dataSync();
 16             console.log("done")
 17             setTimeout(process, 0, model);
 18         }
```

**Comment by andreaferracani** [comment]
Hi
Unfortunately that's not the problem, the bug occurs even without calling the setTimeout function repeatedly. In fact it happens the second time we call the function at line 15. The code is just an example and it works on desktop browsers, in Android but not on mobile Safari

Thanks
