### ISSUE TITLE
Question: What is the standard practice when performing inference on a video to maximise performance (FPS, Memory)?

### ISSUE THREAD

**Issue by sacredvoid** [tensorflow/tfjs#3540]
#### TensorFlow.js version
Using this source for the script : `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js`
#### Describe the question
I am trying to perform inference on a video and feed it back to a canvas. Current pipeline is: <br>`VideoTag -> Hidden Canvas -> OpencvJS(matrix conversions and resizing) -> TFJS Predict -> Post Processing using OpencvJS -> Display Canvas`

Major blockages in the pipeline are `DrawImage function` which draws image to the Hidden Canvas and post processing functions. Any suggestions on how we can improve this pipeline by using any TFJS libraries or any other libraries that are commonly used?

**Comment by pyu10055** [comment]
@sacredvoid there are couple ways to add improvements:
1. Use [canvas filter](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter) to add layer of images onto the video, you can check out our bodypix example.
2. You don't have to use a separate hidden canvas, you can directly use your drawing canvas for tfjs prediction and directly use tfjs output gl texture for your post processing (without downloading the tensor to cpu). @annxingyuan has some example how this can be done.

**Comment by sacredvoid** [comment]
Great inputs, thank you! 
Another question I had was if you know any way to convert `RGB -> YUV -> RBG` other than OpenCV as it takes a lot of time using OpencvJS.

**Comment by annxingyuan** [comment]
Hi @sacredvoid - as Ping mentioned you should be able to achieve faster performance by directly rendering the TFJS output texture for post processing. The key is to initialize a custom WebGL backend with your own WebGL context, like so:

```
tf.registerBackend('webgl', () => {
    return new tf.webgl.MathBackendWebGL(
        new tf.webgl.GPGPUContext(getWebGLRenderingContext(canvasElement)));
  });
await tf.setBackend('webgl');
```

This way, you can access the WebGL context that TFJS uses for computation and chain a rendering shader to the end of the inference pipeline. Within the rendering shader you could perform RGB -> YUV conversion, as described in this post: https://stackoverflow.com/questions/7901519/how-to-use-opengl-fragment-shader-to-convert-rgb-to-yuv420

**Comment by sacredvoid** [comment]
Thank you @annxingyuan and @pyu10055 😄

**Comment by AbdallaGomaa** [comment]
Hi @sacredvoid. I am trying to develop a very similar application to the one you’re making. Did you get it working by setting up the same context for the canvas and TFjs? Any chance you have some sample code to help out? Would be much appreciated!!
