### ISSUE TITLE
FaceMesh detects face even when there's no face

### ISSUE THREAD

**Issue by paq85** [tensorflow/tfjs#3541]
#### TensorFlow.js version
The latest (?)

#### Browser version
Chrome 83

#### Describe the problem or feature request
FaceMesh model detects face even when there's no face.

#### Code to reproduce the bug / link to feature request
Run FaceMesh demo at https://storage.googleapis.com/tfjs-models/demos/facemesh/index.html
And do something like you see in the attached image.
You will get face detected on your hand or sometimes even on the wall etc.
![facemesh 2020-07-01 120611](https://user-images.githubusercontent.com/913555/86231757-52164800-bb93-11ea-94fa-8994209f9a2c.png)

**Comment by munrocket** [comment]
You can find Threshold parameter.

**Comment by paq85** [comment]
@munrocket are you referring to the `detectionConfidence` parameter?

```
facemesh.load(
    {
        maxFaces: 1,
        detectionConfidence: 0.9 // default 0.9
    }
)
```

I've been testing it with a range from 0.1 to 0.999 and it does not seem to change anything.

I get a face detected on a cartoon animal =D

**Comment by rthadur** [comment]
Facemesh has been [depreciated](https://github.com/tensorflow/tfjs-models/pull/853) and no longer supported , closing this request.
