### ISSUE TITLE
Unable to specify custom binary

### ISSUE THREAD

**Issue by adityapatadia** [tensorflow/tfjs#3542]
Code in this line https://github.com/tensorflow/tfjs/blob/69dfce1f988d516b148f7e961490cc6acf0880ba/tfjs-node/scripts/deps-constants.js#L98 actually will only check for `custom-binary.json` inside the tfjs-node folder and not inside project folder. It becomes very hard to put that file in node_modules folder in CI envirnments.

**Comment by rthadur** [comment]
@adityapatadia according this original commit [comment](https://github.com/tensorflow/tfjs/pull/2513#issuecomment-565651906) it looks at same directory.Can you please verify again.

**Comment by adityapatadia** [comment]
According to nodejs docs `__dirname` gives path of current  module. https://nodejs.org/docs/latest/api/modules.html#modules_dirname

This is the reason, when we put `custom-binary.json` file in project folder, it's never read by install script.

**Comment by pyu10055** [comment]
@yhwang Yihong, can you take a look at this issue related to custom binary? thanks!

**Comment by yhwang** [comment]
@pyu10055 sure!

The original purpose of custom-binary.json is used for packaging a new node module that retrieving custom binaries, if I remember correctly.

If you have a CI that needs tfjs-node with custom shared libs, you can build a dedicated NPM package, like `tfjs-node-special-arch`, which contains a custom-binary.json pointing to your special binaries.

**Comment by adityapatadia** [comment]
Ideally it would help to be able to define custom binary during runtime. We can use custom compiled binaries with say AVX512 support.
