### ISSUE TITLE
Can’t find ESM versions for tfjs-core and tfjs-converter

### ISSUE THREAD

**Issue by munrocket** [tensorflow/tfjs#3554]
I tried to use dynamic imports with ES modules:
```
if(cameraExist) {
  Promise.all([
    import('@tensorflow/tfjs-core'),
    import('@tensorflow/tfjs-converter'),
    import('@tensorflow/tfjs-wasm-backend'),
    import('@tensorflow-models/blazeface')
  ]).then(()=>{
    console.log('some prediction');
  });
}
```
But can’t find tfjs-core and tfjs-converter in ESM format in jsdelivr/unpkg CDNs. But other packages have it, for example `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.0.1/dist/tf-backend-wasm.esm.js`.

**Comment by tafsiri** [comment]
As mentioned in my [response on the mailing list](https://groups.google.com/a/tensorflow.org/g/tfjs/c/TjRKUIB7Ab8/m/zkdo6uMQCgAJ) the files [are](https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@2.0.1/dist/index.js) [there](https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@2.0.1/dist/index.js), and the path is described in our package.json so you should be able to determine the correct url you are using. 

If using a npm package name is supported by your loader then it is up to that implementation to figure out how to resolve it. I don't think this is a tensorflow.js bug so i'm going to close this issue. If there is a specific action you think we should take let us know and we can consider it (though we will likely shy away from doing something that supported spec proposals not yet standardized).

**Comment by munrocket** [comment]
Thank you for reply on github. I should connect my primary email with google, because I could discuss this issue there.

Dynamic imports with ESM supported by [89% of browsers](https://caniuse.com/#search=dynamic%20import). I think we should consider one big ESM file because in this case browsers makes less requests. I will make PR in this weekend if you ok with that.

**Comment by munrocket** [comment]
IMHO index.js not fit for browser usage. Do we have some reason why tfjs doesn’t build ESM version in one file?

>If there is a specific action you think we should take let us know and we can consider it

Yes, I think we need something like that #3169 and don’t need ES2017 in build. Can’t see any reason why tfjs prefer ES2017 in UMD bundle instead of ES2015 in ESM.
