### ISSUE TITLE
 TensorFlow.js - Audio recognition using transfer learning tutorial :- 404 Errors Links for tfs and speech-commands

### ISSUE THREAD

**Issue by PaulCreaserML** [tensorflow/tfjs#3559]
# TensorFlow.js - Audio recognition using transfer learning

**Tutorial**

https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab/index.html#2

The links in the above tutorial produce 404 errors.

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands"></script>
```

## Error Message

**Chrome Console**

DevTools failed to load SourceMap: Could not load content for 

https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for 

https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

## Browser version

Windows 10
Google Chrome は最新版です
バージョン: 83.0.4103.116（Official Build） （64 ビット）

### Comments

I can get around the tfjs link problem by including a version.

`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.4.0/dist/tf.min.js"></script>`

Not sure about the speech model.

**Comment by rthadur** [comment]
@PaulCreaserML there is already issue opened to track it , please refer [here](https://github.com/tensorflow/tfjs/issues/3434)
