### ISSUE TITLE
Add option to build tfjs-node for CPUs without AVX

### ISSUE THREAD

**Issue by whatda** [tensorflow/tfjs#3562]
#### TensorFlow.js version

tfjs-node, latest version.

#### Describe the problem or feature request

Since my (not too old) CPU has no AVX, I get the error `Illegal instruction (core dumped)` when using the latest tfjs-node I installed via `npm`.

Proposal: There should be a fast and easy way to build tfjs-node, if your CPU does not support AVX.
If thats not possible, at least a documentation on how to build it.

I already tried `npm rebuild @tensorflow/tfjs-node --build-from-source`, which has no effect.

Thank you!

**Comment by pyu10055** [comment]
@whatda you can check out these instruction to compile TF from source on your own machine.
https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source
