### ISSUE TITLE
React Native Bug? - tf.Tensor changes values

### ISSUE THREAD

**Issue by Zurdge** [tensorflow/tfjs#3563]
### using 
"@tensorflow/tfjs": "^2.0.1",
"@tensorflow/tfjs-react-native": "^0.3.0",

tf.tensor seems to be changing the values slightly which results in faulty predictions.

I'm building a react native app and have followed the instructions by building it with expo etc. 
Tensorflow itself is running correctly however I'm not getting any predictions.
After looking into the tensor's values I noticed they have changed (slightly, but enough to not work)

### Example
Its easy to reproduce on my end. 
Simply test this code.
```
var dataArray = [0.05,0.05,0.15,0.13,0.15]
var dataset = await tf.tensor(dataArray);

console.log(dataArray)  <----- 1
console.log(dataset.arraySync()) <--- 2


```
##### Output
```
#1 - [0.05, 0.05, 0.15, 0.13, 0.15]
#2 - [0.05000000074505806, 0.05000000074505806, 0.15000000596046448, 0.12999999523162842, 0.15000000596046448]<< These have changed from the original values

```

I trained my model on values which were fixed to only 2 decimal places. My model works in python and browser Javascript. however in React Native my model doesn't predict correctly. I think the reason my model isn't generating the correct predictions is because the values are changing from ```0.05``` to ```0.05000000074505806``` etc

Has anyone else experienced this?

**Comment by tafsiri** [comment]
Hi, this is a general issue with precision in floating point numbers, and varying precision in different implementations of webgl on various devices. The solution is to make your code robust to small variance in float values (similar to how you would do this when comparing the output of floating point operations).

The sample above isn't really that useful in seeing if there is a problem that would cause an issue with prediction in a model as the differences in values are incredibly small. (0.05 - 0.05000000074505806). 

Could you post something that shows the difference in behaviour in your model in browser vs react native? I.e. for the same input tensor what are the final values you get from the model in browser and in react native.

**Comment by Zurdge** [comment]
### Hands on demo
https://github.com/Zurdge/tensorflow-react-native-example

See the above link.
#### Setup 
- Clone repo
- ```npm install```

#### Python example ✔️ 
- ```npm run examplePYTHON```
- outputs the predicted value of ```[[30.701174]]``` 😸 

#### Browser example ✔️ 
- ```npm run exampleWEB```
- [Go to Localhost](http://localhost:3000/)
outputs the predicted value of ```30.72240...``` 😸 

#### React Native (Expo) example ❌  
- ```npm run exampleREACTNATIVE```
- open android studio
- run on emulator
outputs a wrong predicted value of ```[0]``` 😿  

-----------------------------

Giving this some thought it's likely not an issue with Tensorflow, its probably doing exactly what it thinks is correct. 
The result of ```0```  in the React Native example makes me think its getting a ```null || undefined``` value from somewhere...
I'm a bit of a jack of all trade and master of none guy so my knowledge of Tensorflow is good but not depthy. 

@tafsiri Thank you for the quick reply, hope the above link helps demonstrate the issue.

**Comment by christoz** [comment]
Probably off topic, can a saved model along with the weights.bin generated in node with **tfjs-node** as tf package can be used in react native side?

I'm trying to make this work but only the predictions are wrong it seems though  the knowledge is not transferred from saved model. 
getting `[0.1999678909778595, 0.19998815655708313, 0.20000174641609192, 0.1999642550945282, 0.20007798075675964]`for every attempt to predict  the probabilities are equal ~ 20%

Example here
https://gist.github.com/christoz/28a2727e9f2b35422b293bb12dd4175f

**Comment by tafsiri** [comment]
@Zurdge thanks for posting the info. I see that you are using the simulator and that may be a factor (or do you get the same behaviour on device?). Depending on your config webgl may not be available in the simulator. 

I would do the following to test this out. First set the backend to ['cpu'](https://js.tensorflow.org/api/latest/#setBackend) and try it out on the simulator. You should be able to get similar results to web, if you are still getting zeros then there is an issue somewhere else (possibly in loading etc). If that works successfully I would test the original code on a physical device and see if you get the same results. If so then it is an issue in your simulator setup and you would need to find out how to enable webgl or if your version of android studio supports that.

**Comment by tafsiri** [comment]
@christoz yes you can use one saved in tfjs-node in react-native. Are you getting different results in node from what you get in react native (for the same input)?

**Comment by christoz** [comment]
@tafsiri Your response is hugely appreciated, thank you.

Yes exactly, in node side  for validation image  works and predicts as expected.
`/src/domain/classification/data/food/validation/Gado-gado/5491061_683737fc-ab29-4409-83cd-8fb1974036cd.jpg
`
prediction.dataSync() Float32Array(5) [
  0.000003024539637408452,
  0.000017217989807249978,
  0.9999618530273438, 
  3.07971845359134e-7,
  0.000017574551748111844
]
`
On the other hand we have the react native app that uses the same model.json and weights.bin that the node side had produced. Also I'm setting tensorflow backend to cpu.

For the same validation image logs 
`
Float32Array(5) [0.1999787539243698, 0.1999756395816803, 0.1999974250793457, 0.19998429715633392, 0.20006392896175385]
`
It seems that the knowledge is not inherited from the saved model, the probabilities are equal ~ 20% which I don't know if react native is compatible with models and weights produced in node


React native code - https://gist.github.com/christoz/28a2727e9f2b35422b293bb12dd4175f
Node app code - https://github.com/christoz/ml-tensorflow-node.git (please check at src/domain/classification/)

**Comment by Zurdge** [comment]
@tafsiri 

Following your advice, 
### ```tf.setBackend('cpu');``` ✔️ 
Setting the backend to CPU allowed my model to return the correct results!
The original issue does seem to stem from the GPU/WebGL section.
I have another project running concurrently to this which makes use of Expo's ```expo-gl``` and I noticed that WebGL on the emulator "clears" to "White" whereas on my real device the WebGL clears to "black" which might be a cause. (The black color could also be the alpha being set to 0). I think for the needs of the project setting the backend to 'cpu' will be fine.

### Running on device / Build Error ❌ 
In order to get the app to build from Android Studio I followed all the steps listed [here](https://www.npmjs.com/package/@tensorflow/tfjs-react-native). 
If I follow all the steps listed then I get 
```
The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.
```
If I remove ```import @tensorflow/tfjs-react-native```  then the build runs fine.
I'm aware that the build error code is more tailored to Expo however it only gets triggered when using ```@tensorflow/tfjs-react-native``` and it is required for ```bundleResourceIO```  to load the model.

Thanks again for your input, ```tf.setBackend('cpu');``` guided me to a solution very quickly 😸

**Comment by rthadur** [comment]
@Zurdge can we close this issue ?

**Comment by Zurdge** [comment]
@rthadur 
Tensorflow remains not useable for the project since importing ```@tensorflow/tfjs-react-native```  causes the build to fail with the error code
```
The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.
```
Is this something you folks have seen pop up before? Theres no results in the Github issues regarding it.

**Comment by rthadur** [comment]
@Zurdge I believe this has been cased by `expo` please check here for similar [issue](https://github.com/expo/expo/issues/8294), if not we will wait for @tafsiri to comment on this, thank you

**Comment by Zurdge** [comment]
## Summary of issue
Using ```import "@tensorflow/tfjs-react-native"``` was causing some issues.
There were two issues which stem out from this.

1 - One was ```WebGL``` in the Android emulator was causing Tensorflow results to default to ```[0]```.

2 - The second was that something inside ```import "@tensorflow/tfjs-react-native"``` was causing expo to not build correctly throwing the error ```The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.``` inside Android Studio. 


## Temp solution
Below is a solution I worked on which solves the hurdles I came across. Maybe it will help others too 🤞 
#### Imports 🎣
```
import '@tensorflow/tfjs-react-native/dist/platform_react_native';
import { util } from '@tensorflow/tfjs-core';
import { Buffer } from 'buffer';
```
```
// IF RUNNING IN EMULATOR
// UNCOMMENT THIS LINE
//tf.setBackend('cpu');
```

#### Loader Class 🐟
The code below is a simple loader which can be used in a ```tf.loadLayersModel``` function
```
class CustomLoader{
  constructor(...props){
    this.modelJSON = props[0];
    this.modelWeights = props[1];
  }

  load = async()=>{
    const modelJson = await this.loadJSON()
    const weightData = await this.loadWeights()
    let modelArtifacts = modelJson;
    modelArtifacts.weightSpecs = modelJson.weightsManifest[0].weights;
    modelArtifacts.weightData = weightData;
    return(modelArtifacts)
  }
  loadWeights = async()=>{
    const RNFS = require('react-native-fs');
    var base64Weights = await RNFS.readFileAssets(this.modelWeights, 'base64');
    const weightData = util.encodeString(base64Weights, 'base64').buffer;
    return weightData;
  }
  loadJSON = async()=>{
    const RNFS = require('react-native-fs');
    var baseJSON = await RNFS.readFileAssets(this.modelJSON, 'ascii');
    const result = JSON.parse(baseJSON)
    return result;
  }
}
```

#### Load the model 🍣

##### Android
- In Android Studio, right click root folder > New > Folder > Assets Folder.
- Add your model files into the assets folder.

##### iOS
- Not done this yet

```
const Loader = new CustomLoader("model/model.json", "model/group1-shard1of1.bin");
const model = await tf.loadLayersModel(Loader);
model.summary()
```


## Full Gist

https://gist.github.com/Zurdge/cc44b68c17180bef25a4aa8d49d2083c

@tafsiri @rthadur 
Thank you for your help. The above isn't a perfect solution but I will close this issue as I am able to progress with the project using TensorflowJS in React Native now.

If you folks develop a solution which allows the backend to be set to GPU whilst running in the emulator and also more information about that expo build error I would be interested to hear about it.

All the best 😸
