### ISSUE TITLE
How to improve tensor.dataSync().

### ISSUE THREAD

**Issue by HrBbCi** [tensorflow/tfjs#3567]
#### problem:
The result of model.predict is a tensor. So I want to draw image, I converted tensor to array with tensor.dataSync(). So dataSync() is too slow. I used await tensor.data(),  tensor.buffer() and tf.browser.toPixel() but everything is no change. Time convert tensor to array approximately 200ms

**Comment by rthadur** [comment]
Please share reproduction code or codepen example

**Comment by HrBbCi** [comment]
> Please share reproduction code or codepen example

This is my code:
1. function predict(img){
 const predictions = model.predict(img);
       var start= performance.now();
        const result_array = predictions.dataSync();
        var end = performance.now();
}
or
2. async function predict(img){
       const predictions = (await) model.predict(img);
        var start= performance.now();
        const result_array = await predictions.data();
        var end = performance.now();
}

So time approximately 200ms

**Comment by tafsiri** [comment]
Because of how tensor operations/dataSync works, you are likely timing more than just how long dataSync takes to get values from the GPU. You are probably timing the whole predict function. You can use tf.profile to get a better sense of what is taking up time in your model execution.

**Comment by HrBbCi** [comment]
> Because of how tensor operations/dataSync works, you are likely timing more than just how long dataSync takes to get values from the GPU. You are probably timing the whole predict function. You can use tf.profile to get a better sense of what is taking up time in your model execution.

Thanks you so much

**Comment by HrBbCi** [comment]
> Because of how tensor operations/dataSync works, you are likely timing more than just how long dataSync takes to get values from the GPU. You are probably timing the whole predict function. You can use tf.profile to get a better sense of what is taking up time in your model execution.

How I can  probably timing the whole predict function ? I used tf.profile , it don't shows bytesAdded or totalBytesSnapshot  dataSync(). Others function have bytesAdded very small

**Comment by pyu10055** [comment]
@HrBbCi your approach 1 is the right way to measure the overall prediction time, which includes
1. JS model execution time predict(...)
2. GPU kernel execution time (all the WebGL op kernels queued by the predict() call)
3. When whole model is executed, the output texture download time (dataSync)

In you approach 2, you are only measuring the JS model execution time.

**Comment by HrBbCi** [comment]
> @HrBbCi your approach 1 is the right way to measure the overall prediction time, which includes
> 
>     1. JS model execution time predict(...)
> 
>     2. GPU kernel execution time (all the WebGL op kernels queued by the predict() call)
> 
>     3. When whole model is executed, the output texture download time (dataSync)
> 
> 
> In you approach 2, you are only measuring the JS model execution time.

Time predict model is very fast but when call method dataSync() is slow. I think it has to wait queued so it is slowed down.I still can't improve it

**Comment by kirill-konshin** [comment]
@pyu10055 @tafsiri 

I don't quite see a resolution here, unfortunately, please consider removing stale mark. We're facing the same issue, `toPixels` function takes a considerable amount of time.

Can someone please explain the difference between

```js
var start= performance.now();
const result_array = process_result.dataSync();
var end = performance.now();

// and

var start= performance.now();
const result_array = await process_result.data();
var end = performance.now();
```

Superficially there has to be no difference, and the overall time taken should be the same (given that there are no other concurrent operations).

I've read @nsthorat comment in another thread https://github.com/tensorflow/tfjs/issues/351#issuecomment-434709493 saying "dataSync blocks the UI thread until all of the work is done and the download is complete" and "If you time a model.predict() the only thing you are actually measuring is the time it takes to schedule the operations on the GPU (...). The synchronization between CPU and GPU happens with a dataSync or a data call -- to time a predict properly (meaning, time all of the operations from start to finish on the GPU) you must introduce a sync between the CPU and GPU.".

What accurate method can we use to precisely measure the inference time and `toPixels` separately?

Side question would be if we already have an image in a `canvas` that will be used for prediction, and then we put result back to `canvas`, does it make sense to somehow avoid GPU->CPU->GPU transfer? Maybe by using bitmaps instead? By looking at `fromPixels` and `toPixels` it seems that it indeed does this kind of transfers to produce and consume `Tensor3d`.

**Comment by mmmahdiii** [comment]
@HrBbCi 
Hi, I faced the same, could you get rid of this problem?

It doesn't matter I use  tensor.data(), tensor.dataSync(), tensor.buffer(),.. even tensor.print(), It'll take about 1.5 second for a 480x320 to get done.

**Comment by ygf8** [comment]
@HrBbCi @tafsiri 
Hi👋 all
I have the same problem. I measured around 170ms to draw a tensor (256,256,3) with [tf.browser.toPixels](https://js.tensorflow.org/api/latest/#browser.toPixels) (webgl)
maybe the conversion (function toPixels) can be optimized ?

Is there any workaround to improve performance?

**Comment by qjia7** [comment]
> @HrBbCi @tafsiri Hi👋 all I have the same problem. I measured around 170ms to draw a tensor (256,256,3) with [tf.browser.toPixels](https://js.tensorflow.org/api/latest/#browser.toPixels) (webgl) maybe the conversion (function toPixels) can be optimized ?
> 
> Is there any workaround to improve performance?

Please look at issue #6683. Currently, you can use `dataToGPU` to customize your own toPixels's functionality.

**Comment by ygf8** [comment]
@qjia7 Thank you 😊

**Comment by FabioRomagnolo** [comment]
> @qjia7 Thank you 😊

Hi! Did you actually manage to implement a faster toPixel() function combined with ```dataToGPU```?

**Comment by qjia7** [comment]
> Hi! Did you actually manage to implement a faster toPixel() function combined with `dataToGPU`?

Please see the `dataToGPU` example https://github.com/tensorflow/tfjs-examples/tree/master/gpu-pipeline and for the webgpu one, you can see the PR here https://github.com/tensorflow/tfjs-examples/pull/867.
