### ISSUE TITLE
Sunset deeplearnjs.org

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#357]
_From @tafsiri on May 7, 2018 18:34_

A tracking issue for the eventual sunset of deeplearnjs.org. The sunsetting will likely be done by redirecting it to js.tensorflow.org however there are a few things hosted at deeplearnjs.org that don't have an equivalent in the new site and may need new homes/custom redirects.

_Copied from original issue: tensorflow/tfjs-website#140_

**Comment by tafsiri** [comment]
- https://distill.pub/2017/aia/ [2] links to https://deeplearnjs.org/demos/latent-space-explorer/

**Comment by tafsiri** [comment]
deeplearnjs.org now redirects to js.tensorflow.org. Only thing remaining is cleanup of some of the internal resources we used to host the old site.

**Comment by nsthorat** [comment]
deeplearn.js is dead. Long live TensorFlow.js!
