### ISSUE TITLE
[Tutorials] Add a tutorial that uses `tf.model`.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#359]
_From @nsthorat on March 28, 2018 2:50_

We currently only have tutorials that use `tf.sequential`, it would be good to have a tutorial that includes `apply` and `SymbolicTensor`s.

_Copied from original issue: tensorflow/tfjs-website#84_

**Comment by nsthorat** [comment]
This guide talks about using a functional model: https://www.tensorflow.org/js/guide/models_and_layers
