### ISSUE TITLE
Add node support for image rotation.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#3595]
Currently tf.image.rotateWithOffset only supports CPU, WebGL, and WASM backends. It should be possible to implement support in Node via [ImageProjectiveTransformV2](https://cs.opensource.google/tensorflow/addons/+/master:tensorflow_addons/image/transform_ops.py;l=108?q=rotate&ss=tensorflow%2Faddons) (interface defined in [ops.pbtxt](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/core/ops/ops.pbtxt)).

This kernel is used in the facemesh and handtrack models.

This is how `tfa.image.rotate` is implemented: https://www.tensorflow.org/addons/api_docs/python/tfa/image/rotate

**Comment by hadidon** [comment]
Hello, 
do you have a planned release date?

**Comment by rthadur** [comment]
The related PR has been merged here , please check here https://github.com/tensorflow/tfjs/pull/3560/files
