### ISSUE TITLE
Enable easy doc symbol linking from markdown files

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#360]
_From @tafsiri on March 22, 2018 21:36_

_Copied from original issue: tensorflow/tfjs-website#56_

**Comment by tafsiri** [comment]
_From @nsthorat on March 22, 2018 21:38_

Just curious, what are you thinking beyond copy pasting links from docs? Some utility function?

**Comment by tafsiri** [comment]
something like {{apiLlink "symbolName"}} have to figure out the markdown way to enable that. The utility function would then always generate links to the latest version.

**Comment by tafsiri** [comment]
I think the first pass at this will just use the new /latest path in #77

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
