### ISSUE TITLE
Null is not an object evaluating (TfliteReactNative.loadModel) 

### ISSUE THREAD

**Issue by XamarinPOC** [tensorflow/tfjs#3603]
dependencies": { "react": "16.13.1", "react-native": "0.63.0", "react-native-image-picker": "^2.3.2", "tflite-react-native": "0.0.5"
target 'TFDemo' do
pod 'TensorFlowLite', '1.12.0'
config = use_native_modules!

/**
<img width="341" alt="Screenshot 2020-07-13 at 12 03 51 PM" src="https://user-images.githubusercontent.com/34939819/87396549-9d3b4c80-c5d0-11ea-9d10-5674e01a8f9a.png">

Metro configuration for React Native
https://github.com/facebook/react-native
@Format
*/
module.exports = {
resolver: {
assetExts: ['tflite', 'txt']
}
}
Hey Folks ,
I'm facing this issue . Is this a bug or i'm missing any things

**Comment by tafsiri** [comment]
Hi I think you've posted this to the wrong repository, the repository for tflite-react-native is here https://github.com/shaqian/tflite-react-native (it is not our project).
