### ISSUE TITLE
Retrain BodyPix TensorflowJS Model 

### ISSUE THREAD

**Issue by HrBbCi** [tensorflow/tfjs#3607]
I am segmenting person for merging background and person.
From skimming BodyPix introductory blog post, it seems like they are mixing the training data with real and simulated images with annotations.  How I retrain the bodypix model? You can guilde me. I'm not sure where to even start.

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
