### ISSUE TITLE
Issue with Posenet using tfjs-reactnative

### ISSUE THREAD

**Issue by harshav-acco** [tensorflow/tfjs#3609]
#### TensorFlow.js version
@tensorflow/tfjs - 2.0.1
@tensorflow-models/posenet -  ^2.2.1
@tensorflow/tfjs-react-native - "^0.3.0"

#### Browser version
React Native + Expo (SDK37)

#### Describe the problem or feature request
When trying to run the expo camera along with posenet model, App is crashing. I believe it has something to do with the way i am trying to use the Posenet.

#### Code to reproduce the bug / link to feature request
Please take a look at the component i wrote 
[https://github.com/harshav-acco/training/blob/master/tensorflow](https://github.com/harshav-acco/training/blob/master/tensorflow)

Code is based on: https://js.tensorflow.org/api_react_native/latest/#cameraWithTensors & https://github.com/tensorflow/tfjs-models/tree/master/posenet

**Comment by rthadur** [comment]
@harshav-acco please provide steps to reproduce the issue and also device information.

**Comment by rameshvishnoi90904** [comment]
@harshav-acco Install fresh project using this command and then add tensorflow/tfjs-react-native
`npx create-react-native-app
`
