### ISSUE TITLE
[Doc generator] Change symbol references in documentation to require "tf." prefix.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#361]
_From @nsthorat on March 22, 2018 21:12_

Sometimes we refer to `ones` as one of the string arguments, sometimes it refers to the function `tf.ones`. To disambiguate, we should force you to use `tf.` when referring to symbols on `tf.`.

I don't want to do this before the launch because it will require a major change to the deeplearn.js docs which we can't do in public yet.

_Copied from original issue: tensorflow/tfjs-website#53_

**Comment by nsthorat** [comment]
This is fixed.
