### ISSUE TITLE
encoding parameter to json.loads was deprecated and removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [tensorflow/tfjs#3611]
Ref : https://github.com/python/cpython/pull/18075

https://github.com/tensorflow/tfjs/blob/e063e103cfcb9bcec53dc326827367dc051eedf0/tfjs-converter/python/tensorflowjs/converters/keras_h5_conversion_test.py#L172

**Comment by rthadur** [comment]
Tensorflow core supports until 3.8 , I believe this will be included once it is upgraded to 3.9 , 
cc @pyu10055

**Comment by tirkarthi** [comment]
Note: The library supports Python 2 and 3. So it should have the parameter in Python 2 and remove it in 3

```python
if six.PY3:
    config_json = json.loads(model.to_json())
else:
    config_json = json.loads(model.to_json(), encoding='utf8')
```

**Comment by pyu10055** [comment]
@tirkarthi thank you for discovering this, you are welcome to submit PR for your solution.

**Comment by tirkarthi** [comment]
Sure, I will add a PR.
