### ISSUE TITLE
I'm having issue when trying to convert keras model to json

### ISSUE THREAD

**Issue by lexms** [tensorflow/tfjs#3618]
I found an error where it could not find my keras model (input path) and the output path, I think it's because of the space character between "My Drive", since I was using google drive to load and save the model. And I think you can't change the name "My Drive".
So Instead of using google drive, I was using the local google colab's drive. So then I uploaded the keras model and convert it and save it in the google colab's drive and downloaded it.

So If it's a bug, I hope in the future it will be fixed. Thank you.

Environment

Google Colab
System information

TensorFlow 2.2
tensorflowjs ver2.0.1.post1
Code
from google.colab import drive
drive.mount('/content/gdrive')

!tensorflowjs_converter --input_format=keras '/content/gdrive/My Drive/model/model.h5' '/content/gdrive/My Drive/json'

Error
usage: TensorFlow.js model converters. [-h]
[--input_format {keras,tf_frozen_model,keras_saved_model,tf_hub,tfjs_layers_model,tf_saved_model}]
[--output_format {keras_saved_model,tfjs_graph_model,tfjs_layers_model,keras}]
[--signature_name SIGNATURE_NAME]
[--saved_model_tags SAVED_MODEL_TAGS]
[--quantize_float16 [QUANTIZE_FLOAT16]]
[--quantize_uint8 [QUANTIZE_UINT8]]
[--quantize_uint16 [QUANTIZE_UINT16]]
[--quantization_bytes {1,2}]
[--split_weights_by_layer] [--version]
[--skip_op_check]
[--strip_debug_ops STRIP_DEBUG_OPS]
[--weight_shard_size_bytes WEIGHT_SHARD_SIZE_BYTES]
[--output_node_names OUTPUT_NODE_NAMES]
[--control_flow_v2 CONTROL_FLOW_V2]
[input_path] [output_path]
TensorFlow.js model converters.: error: unrecognized arguments: /content/gdrive/My Drive/json

**Comment by rthadur** [comment]
@lexms that is expected , try to add backslash before space or addd quoted surrounding the whole path , then you will be able to execute the command

**Comment by lexms** [comment]
As you can see in the example above I've quoted the whole path, but it still gave an error.
And also I've tried adding a backslash before space and it doesn't work out.
or perhaps I've mistaken, could you give me an example? Thanks

**Comment by rthadur** [comment]
please try forward slash or try to run as below 

!tensorflowjs_converter --input_format=keras '/content/gdrive/My Drive/model/model.h5' "/content/gdrive/My Drive/json"
or 
!tensorflowjs_converter --input_format=keras '/content/gdrive/My Drive/model/model.h5' '/content/gdrive/My\ Drive/json'

**Comment by lexms** [comment]
It still gave the same error
TensorFlow.js model converters.: error: unrecognized arguments: /content/gdrive/My\ Drive/json

**Comment by rthadur** [comment]
sorry , can you try this `!tensorflowjs_converter --input_format=keras '/content/gdrive/My\ Drive/model/model.h5' '/content/gdrive/My\ Drive/json'` 

i guess there needs one more slash

**Comment by lexms** [comment]
Still the same error
TensorFlow.js model converters.: error: unrecognized arguments: /content/gdrive/My\ Drive/json

**Comment by pyu10055** [comment]
@lexms can you move the model file to a directory without spaces as part of the name, and output to the same directory?

**Comment by lexms** [comment]
> @lexms can you move the model file to a directory without spaces as part of the name, and output to the same directory?

Yes, actually that's how I resolve the problem, as I explained it in the description above. 
But just, I find it weird that I couldn't use the google drive

**Comment by pyu10055** [comment]
@lexms So the basic problem is how to represent directory with space as a single param to the command line, you can use double quotes "/content/gdrive/My\ Drive/model/model.h5" instead of single quote. You might not need the backslash.
Based on some [quick googling](https://stackoverflow.com/questions/18639663/how-to-pass-command-line-parameters-with-space-in-batch-file).

**Comment by lexms** [comment]
@pyu10055 Well yes you're right, but it seems it doesn't work in Colab, It doesn't recognize the argument even with double quotes or with a backslash, 
but thank you for the sources.

**error:**
TensorFlow.js model converters.: error: unrecognized arguments: /content/gdrive/My\ Drive/json

**Comment by btmanm** [comment]
same issue, dobule quotes and backslash do not work

**Comment by kabyanil** [comment]
issue still exists.

**Comment by vemulaharshith** [comment]
Issue still exists

**Comment by galipmedia** [comment]
This is happening to me on Windows without any space in the name. Did anyone find an answer to this ?

**Comment by kabyanil** [comment]
I can confirm that the issue still exits. Coming back to this thread after 3 years, I was surprised to see my own comment mentioning the issue.
