### ISSUE TITLE
[Doc generator] Add unit tests.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#362]
_From @nsthorat on March 22, 2018 20:44_

The script is now pretty huge, we should add some unit tests.

We could do this by having a test folder and have typescript examples alongside expected JSON output.

_Copied from original issue: tensorflow/tfjs-website#51_

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
