### ISSUE TITLE
BodyPix2 demo doesn't work in Safari (OS X, iOS) 

### ISSUE THREAD

**Issue by ofZach** [tensorflow/tfjs#3624]
**TensorFlow.js version**

sorry I'm not sure ? -- it's this online demo
https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html

**Browser version**

Safari 13.0.3

**Describe the problem or feature request**

The demo doesn't run in safari (OS X, iOS)

[Error] Unhandled Promise Rejection: Error: No color could be found for part id 12.000000953674316
oe (demos.1e01c4c9.js:25:33629)
(anonymous function) (demos.1e01c4c9.js:38:9846)
asyncFunctionResume
(anonymous function)
promiseReactionJob

**Code to reproduce the bug / link to feature request**

Run the demo in Safari (13.0.3), it doesn't launch because of that Unhandled Promise Rejection.

(ps: I posted and closed this issue under a different account by accident, apologies!)

**Comment by rthadur** [comment]
This is working as expected after upgrading to latest version. please check here https://github.com/tensorflow/tfjs-models/blob/master/body-pix/demo/package.json
