### ISSUE TITLE
[Tutorials] Make a tutorial for fully connected training which is simpler than the convolutional tutorial.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#363]
_From @nsthorat on March 22, 2018 18:51_

_Copied from original issue: tensorflow/tfjs-website#49_

**Comment by tafsiri** [comment]
I think we could do fully connected for a different example than MNIST.

**Comment by tafsiri** [comment]
_From @nsthorat on March 22, 2018 19:8_

SG, updated the title

**Comment by nsthorat** [comment]
Done: https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#0
