### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data - Spelling mistake

### ISSUE THREAD

**Issue by benjaminfiliatrault** [tensorflow/tfjs#3655]
Spelling mistake on the tutorial **TensorFlow.js — Making Predictions from 2D Data**

https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#6

We generate 100 new ‘examples' to feed to the model. Model.predict is how we feed those examples into the model. Note that they need to **be** have a similar shape ([num_examples, num_features_per_example]) as when we did training.

**Comment by rthadur** [comment]
@benjaminfiliatrault thanks for reporting.
This is noted and corrected , will be available whenever next push happens.
