### ISSUE TITLE
Modify fromPixel in webgpu backend to async function

### ISSUE THREAD

**Issue by shaoboyan** [tensorflow/tfjs#3661]
We want to do this modification to enhance CPU/GPU parallel execution.

**Comment by shaoboyan** [comment]
@qjia7

**Comment by axinging** [comment]
Thanks @rthadur, we are still working on this, will update this soon.

**Comment by rthadur** [comment]
related PR https://github.com/tensorflow/tfjs/pull/4375 has been merged , closing this request.Thank you
