### ISSUE TITLE
Unsupported Ops: DenseBincount

### ISSUE THREAD

**Issue by jclaessens97** [tensorflow/tfjs#3686]
I encountered following error for an unsupported operation while converting a python model to a tfjs model.

![Screenshot from 2020-07-29 23-18-58](https://user-images.githubusercontent.com/10177148/88855340-fe7b3680-d1f2-11ea-8aea-33cde34ec0c5.png)

**Comment by gaikwadrahul8** [comment]
Hi, @jclaessens97 

Apologize for the delayed response and if I'm not wrong we have updated our official documentation w.r.t [tf.denseBincount](https://js.tensorflow.org/api/4.4.0/#denseBincount), Just to confirm, have we implemented this  `tf.denseBincount` Op in TFJs ? Thank you!
