### ISSUE TITLE
Peer dependency pegged to build version instead of major or minor

### ISSUE THREAD

**Issue by nihonjinrxs** [tensorflow/tfjs#369]
#### TensorFlow.js version

0.11.2

#### Browser version

Non-browser, using in Node.js v10.2.1 with npm v6.1.0

#### Describe the problem or feature request

Peer dependencies are pegged to specific build versions of `tfjs-core`, so when you `npm i @tensorflow/tfjs`, you get the following npm warning:

```
$ npm i @tensorflow/tfjs
npm WARN @tensorflow/tfjs-converter@0.4.0 requires a peer of @tensorflow/tfjs-core@0.11.0 but none is installed. You must install peer dependencies yourself.

+ @tensorflow/tfjs@0.11.2
updated 1 package and audited 25 packages in 1.805s
found 0 vulnerabilities
```

Ideally, these should be pegged to the major versions (or minor if really needed) only, so that we don't have these peer dependency conflicts.

#### Code to reproduce the bug / link to feature request

```
npm i @tensorflow/tfjs
```

**Comment by dsmilkov** [comment]
Thanks. We were just talking about relaxing this version yesterday. Other than the warning message, did you run into run-time issues (I'm hoping not) due to this conflict?

**Comment by nihonjinrxs** [comment]
Not that I saw, but I'm new to the library, so I'm not necessarily using it to its fullest capabilities.
