### ISSUE TITLE
CameraWithTensors Rendering even when autorender is off

### ISSUE THREAD

**Issue by MyJumperBroke23** [tensorflow/tfjs#3709]
#### TensorFlow.js version

"@tensorflow/tfjs": "^1.7.4",
"@tensorflow/tfjs-react-native": "^0.2.3",
"expo": "~37.0.3",

#### Describe the problem or feature request

The Camera still renders when Using CameraWithTensors even when autorender is turned off. 

#### Code to reproduce the bug / link to feature request

```
import React, { Component } from 'react';
import { Camera } from 'expo-camera';
import { cameraWithTensors, fetch, decodeJpeg, bundleResourceIO, renderToGLView } from '@tensorflow/tfjs-react-native';
import { View, Text, StyleSheet, Platform } from 'react-native'
import { CameraStyle } from './styles'
import * as tf from '@tensorflow/tfjs';

const TensorCamera = cameraWithTensors(Camera);

class CameraTester2 extends Component {

  constructor(props) {
    super(props)
  }

  async componentDidMount() {
    await tf.ready()
    console.log("TF Ready")
  }

  handleCameraStream(images, updatePreview, gl) {
    const loop = async () => {
        requestAnimationFrame(loop);
    }
    loop();
  }

  render() {

    let textureDims;
    if (Platform.OS === 'ios') {
      textureDims = {
        height: 1920,
        width: 1080,
      };
    } else {
      textureDims = {
        height: 1200,
        width: 1600,
      };
    }

    return <View>
      <TensorCamera
        // Standard Camera props
        style={CameraStyle.preview}
        type={Camera.Constants.Type.front}
        // Tensor related props
        cameraTextureHeight={textureDims.height}
        cameraTextureWidth={textureDims.width}
        resizeHeight={320}
        resizeWidth={320}
        resizeDepth={3}
        onReady={this.handleCameraStream}
        autorender={false}
      >
      </TensorCamera>
    </View>
    

  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});

export default CameraTester2;
```

**Comment by rthadur** [comment]
```
if autorender is false you need the following two lines.
      // updatePreview();
      // gl.endFrameEXP();
```
for more info please refer [link](https://js.tensorflow.org/api_react_native/0.2.1/)

**Comment by tafsiri** [comment]
Also what are you overall trying to do? In this case you might be seeing the underlying camera component since no tensors are pulled. Do you still get this behaviour if you pull a tensor from `images`?

**Comment by MyJumperBroke23** [comment]
@tafsiri I was trying not to render the cameraWithTensors Camera. 

I can't figure out how to get it working with shaders from gl-react, so I was thinking of rendering the native expo camera, and then adding shaders following [this tutorial ](https://medium.com/react-native-development/react-native-camera-app-with-live-preview-saturation-and-brightness-filters-d34535cc6d14)

I ended up working around the issue by changing my render to 

```
render() {

    let textureDims;
    if (Platform.OS === 'ios') {
      textureDims = {
        height: 1920,
        width: 1080,
      };
    } else {
      textureDims = {
        height: 1200,
        width: 1600,
      };
    }

    
    
    return <TensorCamera
    // Standard Camera props
    style={CameraStyle.preview}
    type={Camera.Constants.Type.front}
    // Tensor related props
    cameraTextureHeight={textureDims.height}
    cameraTextureWidth={textureDims.width}
    resizeHeight={320}
    resizeWidth={320}
    resizeDepth={3}
    onReady={this.handleCameraStream}
    autorender={false}
  >
  </TensorCamera>
    
    <Surface style={{ height:800,width:400 }}>
    <HelloBlue>
      {{ uri: 'https://images.unsplash.com/photo-1562337589-136d8a7dd9dd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMDk0fQ&auto=format&fit=crop&w=1400&q=80' }}
    </HelloBlue>
    </Surface>
  }
```

so I'll close the issue. But if you have any suggestions for the best way to go about this I would very much appreciate any insight you could give.

**Comment by tafsiri** [comment]
If you don't need the tensors for images from the camera stream, then you could just use the regular Camera component from expo? Am i missing something about your use case?

**Comment by MyJumperBroke23** [comment]
@tafsiri I need to apply a shader to the camera, but I also need the image tensor for a seperate task.

**Comment by tafsiri** [comment]
@MyJumperBroke23 I'd suggest looking at the source code for CameraWithTensors (camera_stream.tsx) and look to making a custom component that yields the tensors (what CameraWithTensors does now) but allows you to run your custom shaders. Inside that file you will see a few utility functions that run shaders.
