### ISSUE TITLE
BodyPix example - add accuracy metric

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#3715]
In the BodyPix example readme you say:
> A smaller value results in a smaller model and faster prediction time but lower accuracy.

Could you please share any accuracy metric for the different models on any dataset? 
For some reason, I'm often seeing better performance by the mobilenet model compared to resnet, so I'd like to test it against some numbers.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
