### ISSUE TITLE
Xcode is required for tfjs-node on Mac

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#372]
On a Macbook 13inch without Xcode, I get the following error when I run `yarn` in `tfjs-examples/mnist-node` and `tfjs-examples/baseball-node`:

dyld: Library not loaded: @rpath/DVTFoundation.framework/Versions/A/DVTFoundation
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
  Reason: image not found

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/smilkov/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command \"/Users/smilkov/.nvm/versions/node/v8.9.4/bin/node\" \"/Users/smilkov/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/smilkov/code/tfjs-examples/baseball-node/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2

I think it means that XCode is required on Mac. If so, would be great to mention that in the docs, or try to detect it in a "preinstall" script and provide a nice user-friendly message.

**Comment by nkreeger** [comment]
If you hit this issue - you can just run 

```sh
$ xcode-select --install
```

**Comment by rthadur** [comment]
Closing the issue as the commit has been pushed here https://github.com/tensorflow/tfjs-node/pull/101, please feel free to reopen the issue if this has not been addressed.
