### ISSUE TITLE
Error: Unknown layer: Rescaling.

### ISSUE THREAD

**Issue by co2nut** [tensorflow/tfjs#3728]
Getting the error when trying to load custom converted model :
Error: Unknown layer: Rescaling. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().

**Comment by rthadur** [comment]
@co2nut this is a feature request , would you be willing to contribute ?

**Comment by roca77** [comment]
Have you guys found a solution to this? I am getting the same error...

**Comment by chihuahua** [comment]
Same, I am seeing this when loading a Keras model, ie

```
  tf.loadLayersModel('./model_export/model.json').then(
      (m: tf.GraphModel) => {
        this.model = m;
        console.log(m);
      });
```

**Comment by chihuahua** [comment]
My guess is that you all are using the `tf.keras.layers.experimental.preprocessing.Rescaling` layer, which has not yet been ported to TensorFlow JS.

**Comment by roca77** [comment]
> My guess is that you all are using the `tf.keras.layers.experimental.preprocessing.Rescaling` layer, which has not yet been ported to TensorFlow JS.

Yes, Rescaling is causing the issue; I removed it and now it's working

**Comment by rthadur** [comment]
Thank you , closing this issue for now

**Comment by asterisk37n** [comment]
I know this issue is closed, but for visitors who uses tf.keras.applications.EfficientNetB?, it cannot be converted to tfjs because it uses Rescaling in it.
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/applications/efficientnet.py#L316

**Comment by cardstdani** [comment]
I fixed it by adding this parameter at the conversion command: --output_format=tfjs_graph_model

After that, I loaded the model as Graph in the JavaScript code of the website. I hope it's useful
