### ISSUE TITLE
Bodypix - Smooth between video frames?

### ISSUE THREAD

**Issue by alana314** [tensorflow/tfjs#3733]
TensorFlow.js version: tfjs-node 2.0.1  
body-pix-node v2.0.4  
Hi,  
I'm using bodypix to process frames from video, and it works but it's jittery compared to virtual backgrounds like Zoom. I'm wondering if A) there's a way to "hint" to the model to look in the coordinates of the previous segmentation when it finds the next one before looking through the full frame, or B) if there's a way to smooth the shape between two segmentations. Thanks!

**Comment by rthadur** [comment]
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation

**Comment by alana314** [comment]
Thanks, is it the selfie segmentation? Any other options I should try or just run it on consecutive frames?
