### ISSUE TITLE
Load a model from url of a .zip / .gz file

### ISSUE THREAD

**Issue by alokwhitewolf** [tensorflow/tfjs#3735]
#### Describe the problem or feature request

After pruning/quantization and subsequent conversion to tf js model, it is ideal to host the model files as .zip / .gz fomat in order to make use of the pruned weights. This often leads results in serving smaller files. Is there any feature that loads a model directly from a path or url of the compressed file?  Do you intend to plan on supporting such a feature in the future?

How would one go about this way of serving the models currently ?
TIA

**Comment by pyu10055** [comment]
@alokwhitewolf That is a good idea, I believe you are right if you quantize the weights into 8bit/16bit integer, the weight can probably further compressed using zip format. 
To host all files as a single .gz would be non-trivial, since the model loader has logic that loads the model.json and bin files in order. But you can zip the individual bin file, and create a custom ioHandler to support decompressing.
Contributions are welcome, I think this addition would benefit many tfjs users. thanks!

**Comment by alokwhitewolf** [comment]
@pyu10055 Thanks for response

I ended up using a version of your second approach to make it work for now. 

* Changed the `paths` in `weightsManifest` of model.json to ensure that they end with ".bin.gz" rather than ".bin"
* I gzippped all the .bin files

Since I was using Google Cloud for hosting the weights, I looked at the [transcoding docs](https://cloud.google.com/storage/docs/transcoding) and did the followiing -

* set `content-type` to 'application/json' for the gzipped json file and 'application/octet-stream' for the weights. 
* set `content-encoding` to "gzip"
* Set the `Cache-Control` metadata field for the object to `no-transform`, then the object is served as a compressed object in all subsequent requests, regardless of any `Accept-Encoding` request headers.

This makes it work for now.
But yeah, it would be good to have this as a feature. I will try to contribute a ioHandler for this.

**Comment by pyu10055** [comment]
@alokwhitewolf Cool, basically you are letting browser to handle the decompression. That is very nice. Can you share what level of compression you are getting for the bin files with this approach?

**Comment by alokwhitewolf** [comment]
Roughly around ~3.6x. I suppose this would also be affected by the pruning factor one opts for during optimization

![Capture](https://user-images.githubusercontent.com/24509942/89610647-b3b78980-d898-11ea-97c2-3dcab5792a75.PNG)

**Comment by pyu10055** [comment]
nice, is this model using int8 or int16 quantization?

**Comment by alokwhitewolf** [comment]
Had done 8bit quantization

**Comment by onuryuruten** [comment]
Hey there, are there any updates on this? It would be super cool to have this feature 💯

**Comment by gaikwadrahul8** [comment]
Hi, @alokwhitewolf

Apologize for the delayed response and Just to confirm, as you mentioned in your previous comment, you'll do contribution for this feature request so May I know are you working on this feature request or not ? It seems like this feature haven't added as of now if I'm not wrong so if someone wants to contribute for this feature request please refer this [link](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md) ? Thank you!
