### ISSUE TITLE
TypeError: "e.wasm is undefined" on Firefox

### ISSUE THREAD

**Issue by Jonarod** [tensorflow/tfjs#3753]
#### TensorFlow.js version
2.0.1

#### Browser version
Firefox 65.0

#### Describe the problem or feature request
When loading `tf-backend-wasm` on Firefox, an error occurs:

```bash
TypeError: "e.wasm is undefined":
      node_modules tf-backend-wasm.esm.js:26
```

#### Code to reproduce the bug / link to feature request

```js
import * as tf from '@tensorflow/tfjs-core';
import * as tfconv from '@tensorflow/tfjs-converter';
import * as tfwasm from '@tensorflow/tfjs-backend-wasm';

tfwasm.setWasmPath('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@latest/dist/tfjs-backend-wasm.wasm');

tf.setBackend('wasm').then( () => main() )
```
then an error appears in the console and wasm backend is not usable:

```bash
TypeError: "e.wasm is undefined":
      node_modules tf-backend-wasm.esm.js:26
```

My Firefox version may be too old, but if I am correct, Firefox should be ready for Wasm since version 59.0, so there should be something else going on with TfjsWasm specifically.

**Comment by rthadur** [comment]
@Jonarod please provide executable code to reproduce the error or an code pen example , thank you
