### ISSUE TITLE
Stop Models and clear the video when toggle on and off

### ISSUE THREAD

**Issue by Aditya-Ace** [tensorflow/tfjs#3759]
I am on Angular and using models, 

Posenet

COCO SSD

BodyPix B&W Pixels

BodyPix RGB Pixels

Face API Image Recognition

Face API Emotion and Age Detection

Hand Tracking

in my project, as you can see in the picture.
I load all the models when the page loads in ngAfterViewInit().
I have provided the toggle option and getting true when turned on and false when turned off.
My Models work when turning it on, I start the method that does the job but the problem is I have no idea how to toggle them off or turn it off when toggled.
I wanna add this functionality to my project, I added a method to just refresh the component to get rid of the problem for now but in the production, I want toggle to work turning on or off. Please help. Thanks in advance.
![example](https://user-images.githubusercontent.com/25694814/89737853-060fca80-da92-11ea-961c-acefa026c907.png)

![toggle](https://user-images.githubusercontent.com/25694814/89737760-4de22200-da91-11ea-952b-327e5c91f6f9.png)

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Aditya-Ace** [comment]
> Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

https://stackoverflow.com/q/63345529/12459278

Please help me there
