### ISSUE TITLE
Failing tests in core regarding local storage

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#377]
See this [log](https://api.travis-ci.org/v3/job/387154917/log.txt) (search for `Failed`) for the test that's failing. The relevant snippet is:
```
Firefox 60.0.0 (Mac OS X 10.12.0) ModelManagement {"BACKEND":"test-cpu"} List models: 1 result FAILED[39m
	Expected 2 to equal 1.
	<Jasmine>
	@src/io/model_management_test.ts:110:16 <- src/io/model_management_test.js:149:29
```

It consistently fails on Travis on Firefox on Mac OS X 10.12.0 as of couple days ago.

**Comment by dsmilkov** [comment]
Here is [another log](https://travis-ci.org/tensorflow/tfjs-core/jobs/386952306#L4134) from another run. Which exact test fails is flaky since the failure depends on the order of execution.

**Comment by dsmilkov** [comment]
See this [PR's](https://github.com/tensorflow/tfjs-core/pull/1075) description for context. tl;dr when we switched from karma 2.x to 3.x, by default tests run in random order and localstorage tests were not isolated properly. Switching back to non-random order will fix this issue, but nevertheless, it would be good to fix those tests.

**Comment by caisq** [comment]
@dsmilkov That's good info. However, I don't see how random order by itself may affects the test results. The tests are written in a way that doesn't depend on the order in which the individual `it`s are executed. Is it possible that the tests are executing *concurrently*? That would explain some of the random failures we have been seeing regarding local storage.

**Comment by dsmilkov** [comment]
Chatted offline. I'm fairly certain that tests run sequentially, so I think it's related to not properly cleaning up the local database.

**Comment by nsthorat** [comment]
Pretty sure we don't have tests failing at head now, closing this out.
