### ISSUE TITLE
BytesInGpu keep increasing whereas the numBytes is constant.

### ISSUE THREAD

**Issue by shiv-u** [tensorflow/tfjs#3770]
Opening this new issue as earlier https://github.com/tensorflow/tfjs/issues/3592 didn't get response.
#### TensorFlow.js version
Using this source for the script : https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js
#### Describe the problem or feature request
The BytesInGpu keep increasing whereas the numBytes, numTensors,numDataBuffers are constant. I'm using tf.tidy and even disposing the tensors after using tf.browser.toPixels. Is there any way I can resolve this ?
![bug](https://user-images.githubusercontent.com/29162160/89875388-cf919700-dbda-11ea-9a78-19e2e697778d.png)

#### Code to reproduce the bug / link to feature request
```
console.log("*****start*****",tf.memory());
this.pixels =  tf.browser.fromPixels(this.video);
await tf.browser.toPixels(this.pixels,this.c2)
console.log("*****end*****",tf.memory());
```

**Comment by rthadur** [comment]
@shiv-u thanks for your patience will track this in original issue.
