### ISSUE TITLE
Error loading exported Keras MobileNetV2

### ISSUE THREAD

**Issue by kylemcdonald** [tensorflow/tfjs#3772]
#### TensorFlow.js version

Tested on 2.0.0 and 2.1.0

#### Browser version

Chrome 84.0.4147.105

#### Describe the problem or feature request

I am trying to export a fine-tuned model from Keras, but I see the error "Unknown layer: Functional". I tried using MobileNetV2 without any modifications and I still get the error.

I followed the instructions from [Importing a Keras model into TensorFlow.js](https://www.tensorflow.org/js/tutorials/conversion/import_keras)

#### Code to reproduce the bug

Create these two files:

`convert.py`

```python
import tensorflow as tf
import tensorflowjs as tfjs
model = tf.keras.applications.MobileNetV2(include_top=False)
tfjs.converters.save_keras_model(model, 'mobilenetv2-tfjs')
```

`index.html`

```html
<html>
<head><script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.1.0/dist/tf.min.js"></script></head>
<body><script>tf.loadLayersModel('mobilenetv2-tfjs/model.json')</script></body>
</html>
```

Then after installing Anaconda, run:

```
conda create -n tfjs python=3.7
pip install tensorflowjs==2.1.0
python convert.py
python -m http.server
```

Then open `http://localhost:8000` in your browser. The console should display:

```
Uncaught (in promise) Error: Unknown layer: Functional. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
```

I also tested a simple model, just to make sure it isn't a broad bug:

```python
model = tf.keras.models.Sequential([tf.keras.layers.Dense(8)])
model.build(input_shape=(1,8,))
```

And this model loads without any trouble. So I can only assume that there is an unsupported layer inside `MobileNetV2`. But when I print out all the layer types, I do not see anything called "Functional", or anything out of the ordinary:

```python
import tensorflow as tf
model = tf.keras.applications.MobileNetV2(include_top=False)
print(set([layer.__class__.__name__ for layer in model.layers]))
```

```
{'Conv2D', 'BatchNormalization', 'InputLayer', 'DepthwiseConv2D', 'ZeroPadding2D', 'ReLU', 'Add'}
```

I also tested the SavedModel converter, exporting the same network with the SavedModel format taking notes from the tutorial [Using the SavedModel format](https://www.tensorflow.org/guide/saved_model):

```python
import tensorflow as tf
model = tf.keras.applications.MobileNetV2(include_top=False)
tf.saved_model.save(model, 'mobilenetv2-savedmodel')
```

Then running the converter:

```
tensorflowjs_converter --input_format tf_saved_model mobilenetv2-savedmodel mobilenetv2-tfjs
```

But this gives a different error (for both 2.0.0 and 2.1.0), which I've pasted here slightly abridged:

```
Uncaught (in promise) Error: layer: Improper config format: {"node":[{"name":"StatefulPartitionedCall/mobilenetv2_1.00_224/Conv1_pad/Pad/paddings","op":"Const","attr":{"value":{"tensor":{"dtype":"DTINT32","tensorShape":{"dim":[{"size":"4"},{"size":"2"}]}}},"dtype":{"type":"DTINT32"}}}, [...] {"name":"StatefulPartitionedCall/mobilenetv2_1.00_224/block_2_expand/Conv2D_weights","op":"Const","attr":{"value":{"tensor":{"dtype":"DTFLOAT","tensorShape":{"dim":[{"size":"1"},{"size":"generic_utils.js:227)
    at CT (serialization.js:31)
    at models.js:295
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at Wm (runtime.js:728)
    at o (runtime.js:728)
```

**Comment by kylemcdonald** [comment]
Solved... I think.

It looks like `tfjs.converters.save_keras_model()` does not support functional models. Despite what the error message says, it's not really about a specific layer in the original Keras model.

The process for saving functional models should look like this:

```python
import tensorflow as tf
import tensorflowjs as tfjs
model = tf.keras.applications.MobileNetV2(include_top=False)
model.save('mobilenetv2.h5')
```

Followed by conversion:

```
tensorflowjs_converter --input_format keras --output_format tfjs_graph_model mobilenetv2.h5 mobilenetv2-tfjs
```

And using `loadGraphModel()` instead of `loadLayersModel()`:

```
<html>
<head><script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.1.0/dist/tf.min.js"></script></head>
<body><script>tf.loadGraphModel('mobilenetv2-tfjs/model.json')</script></body>
</html>
```

I figured this out while looking at the options for `tensorflowjs_converter` and found `tfjs_graph_model`. After Googling that, I found [Importing a TensorFlow GraphDef based Models into TensorFlow.js
](https://www.tensorflow.org/js/tutorials/conversion/import_saved_model) which lead me to `loadGraphModel()`.

If you see `Improper config format` it might mean that your model was successfully exported, but you need to use `loadGraphModel()`. For the other error `Unknown layer: Functional`, this seems like the kind of error that could have been caught earlier when calling `tfjs.converters.save_keras_model()`.

**Comment by kylemcdonald** [comment]
One more aside, it looks like with tfjs 2 the loadGraphModel method has moved:

```javascript
import * as tfconverter from '@tensorflow/tfjs-converter';
let model;
const setupPage = async () => {
    model = await tfconverter.loadGraphModel('mobilenetv2-tfjs/model.json');
}
setupPage();
```

I couldn't find this in the documentation... maybe this is obvious to folks who are more experienced with modern JavaScript :) I found a hint in the tests [here](https://github.com/tensorflow/tfjs/blob/master/e2e/integration_tests/load_predict_test.ts).

**Comment by kylemcdonald** [comment]
One more note, the help for `tensorflowjs_converter` says `--output_format tfjs_graph_model` is the default, but I don't think this is actually true.

If you don't specify `tfjs_graph_model` manually, and then try to `loadGraphModel` you will get an error `Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined`.

**Comment by pyu10055** [comment]
@kylemcdonald thank you for try it out, if the input type is keras, the default output is tfjs_layers_model.
The functional layers has been supported with this PR https://github.com/tensorflow/tfjs/pull/3863
