### ISSUE TITLE
Add "repeat" op & gradients / tf.image.resizeBilinear gradients

### ISSUE THREAD

**Issue by tehZevo** [tensorflow/tfjs#38]
### TensorFlow.js version
0.6.1

### Browser version
Chrome 56.0.2924.87 (Electron 1.6.11)

### Feature request
I'm interested in building convolutional generative networks / autoencoders, and am looking for a way to upsample tensors. However, tf.image.resizeBilinear doesn't seem to have its gradient implemented yet, and I couldn't find an element-wise "repeat" op to use in its place.

Having these ops would be very helpful, thanks!  Great work on tfjs, awesome library.

**Comment by tehZevo** [comment]
Awesome to hear about resizeBilinear gradient! As for repeat, I was looking for an op that would perform an element-wise repeat (https://github.com/tensorflow/tensorflow/issues/8246), eg: repeating
```
[[1, 2],
 [3, 4]]
```
with `[2, 2]` would yield:
```
[[1, 1, 2, 2],
 [1, 1, 2, 2],
 [3, 3, 4, 4],
 [3, 3, 4, 4]]
```
I was going to use that as an upsampling op to match the `tf.maxPool()`s on the other side of my autoencoder.

Slightly related: I attempted implementing the solution (tile & reshape) posted in the above TensorFlow issue, but hit an exception when attempting to call `tf.tile()` on rank 5 tensors.

**Comment by nsthorat** [comment]
Are you trying to repeat on a 4D tensor? Just curious, what is the use-case?

We actually haven't done any work with rank-5 Tensors, but we can add support if there's a driving use case here.

**Comment by tehZevo** [comment]
The only reason I would have needed rank 5 tensors would be to implement the makeshift "repeat" solution posted here: https://github.com/tensorflow/tensorflow/issues/8246 , which I only needed in absence of tf.resizeBilinear gradients.  I was trying to achieve the same thing: "upsample" a [batchSize, height, width, numChannels] tensor to [batchSize, height * 2, width * 2, numChannels].  Sorry for the confusion.

**Comment by dsmilkov** [comment]
Hi @tehZevo , gradient for resizeBilinear was added in https://github.com/tensorflow/tfjs-core/pull/996 . Make sure to use the latest tfjs. I'm going to close this issue, as per its title, we've fixed it, but feel free to reopen if you run into any issues with resizeBilinear or its gradient.
