### ISSUE TITLE
SOFT_ONE in tfjs-examples/mnist-acgan/gan.js should be scalar tensor instead of number.

### ISSUE THREAD

**Issue by DrewJay** [tensorflow/tfjs#3821]
#### TensorFlow.js version
v2.0+
#### Browser version
Google chrome v84.0.4147.125
#### Describe the problem or feature request
Problem is located in [gan.js](https://github.com/tensorflow/tfjs-examples/blob/master/mnist-acgan/gan.js) file in tfjs example project demonstrating usage of GANNs. Variable **SOFT_ONE** is declared and defined as `const SOFT_ONE = 0.95`.

This variable is used incorrectly in given circumstances. For example: `tf.ones([batchSize, 1]).mul(SOFT_ONE)`.

This assumption is based on [following documentation](https://js.tensorflow.org/api/latest/#mul) which states that parameter of 'mul' method is tensor - not a number.

Incorrect usage also throws following exception: _**Argument 'b' passed to 'mul' must be a Tensor, but got number.**_

#### Code to reproduce the bug / link to feature request
`const SOFT_ONE = 0.95;
tf.ones([2, 2]).mul(SOFT_ONE);`.

I have also proposed a solution to this issue in following[ pull request](https://github.com/tensorflow/tfjs-examples/pull/351).

**Comment by rthadur** [comment]
@DrewJay can you please provide a codepen example to reproduce the error ?
