### ISSUE TITLE
error 'backend' undefined on a single model with tfjs@2.3.0

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#3823]
anyone tried using openimages_v4/ssd/mobilenet_v2 <https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1> model from tfhub and tfjs 2.0+ ?
i've converted it using:

```shell
tensorflowjs_converter --input_format tf_hub --output_format tfjs_graph_model --skip_op_check --strip_debug_ops=True --weight_shard_size_bytes 4194304 https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1 .
```

and it works perfectly with tfjs@1.7.4.  
but with tfjs@2.3.0, it processes one image just fine and then it fails on the second image with

```log
TypeError: Cannot read property 'backend' of undefined
```

I've tried ~10 other models, some native tfjs and some converted from tfhub and none have this issue.

**Comment by pyu10055** [comment]
@vladmandic I tried this model, but I am having trouble getting it run properly. do you mind sharing a codepen example of this model? Thanks.

**Comment by vladmandic** [comment]
> @vladmandic I tried this model, but I am having trouble getting it run properly. do you mind sharing a codepen example of this model? Thanks.

It's a bit long for codepen, but you can see entire source of my project at <https://github.com/vladmandic/pigallery>
Key code is in function `client/modelDetect.js:detectSSD()`
model is executed using:
`// outputs are: scores, classes, boxes
const result = await model.executeAsync({ images: batched }, ['module_apply_default/hub_input/strided_slice_1', 'module_apply_default/hub_input/strided_slice_2', 'module_apply_default/hub_input/strided_slice']); `

where batched is an image buffer cast to float32 and afterwards it's just logic to decode classes and detection boxes.
classes are in `assets/OpenImage-Labels.json`

**Comment by vladmandic** [comment]
touch more info on the error:  

stack trace:
```log
Uncaught (in promise) TypeError: Cannot read property 'backend' of undefined
    at Engine.moveData (engine.js:270)
    at DataStorage.get (backend.js:29)
    at MathBackendWebGL.reshape (backend_webgl.js:1729)
    at forward (reshape.js:55)
    at engine.js:465
    at engine.js:308
    at Engine.scopedRun (engine.js:318)
    at Engine.tidy (engine.js:307)
    at kernelFunc (engine.js:465)
    at engine.js:477
```
problematic code:
```js
moveData(backend, dataId) {
  const info = this.state.tensorInfo.get(dataId); // this works fine on first execute, but returns undefined second time execute is called
  const srcBackend = info.backend;
  const values = this.readSync(dataId);
```
- dataId is always empty object, so that doesn't change
- during first execute, moveData is called 183 times without issues
- during second execute, moveData is called 22 times before info becomes undefined
- but this.state.tensorInfo looks like a WeakMap with fixed 2890 entries

i've added this debug code after get function:
```js
if (!info) {           
  console.log('dataId', dataId);
  console.log('state', this.state);
  console.log('tensorInfo', this.state.tensorInfo);
  console.log('info', this.state.tensorInfo.get({}))
}
```
and you can see the output:
```log
dataId {}
state EngineState {registeredVariables: {…}, nextTapeNodeId: 0, numBytes: 88874728, numTensors: 1479, numStringTensors: 1, …}
tensorInfo WeakMap {{…} => {…}, {…} => {…}, {…} => {…}, {…} => {…}, {…} => {…}, …}
info undefined
```
and just to confirm, tf.backend() and tf.getBackend() are valid before and after error (using webgl).

i don't think there is anything wrong with moveData per say, as same this.state.tensorInfo.get(dataId) gets used all over the code  
but it does seem that tensor map gets corrupt so getter fails to find value and by it's design it returns undefined

**Comment by pyu10055** [comment]
@vladmandic Thank you for setting up the demo, I have found the issue, and submit a PR for the fix.

**Comment by vladmandic** [comment]
@pyu10055 Nice & Thank you!

I went to get the diff, but it's already been reviewed and checked into master - impressive.
I've done a checkout and clean build and can confirm that it works perfectly!
I'm closing this issue.
