### ISSUE TITLE
tfjs-node: is there a way to install and build from source always

### ISSUE THREAD

**Issue by yorkie** [tensorflow/tfjs#3826]
#### TensorFlow.js version

Latest

#### Browser version

Node.js

#### Describe the problem or feature request

Sometimes we need to build from source for addon because of the different Glibc version between pre-builtin machine and target.

**Comment by rthadur** [comment]
please check this link https://www.npmjs.com/package/@tensorflow/tfjs-node#mnist-demo-for-nodejs for building from source.

**Comment by yorkie** [comment]
@rthadur This looks a little bit complicated and not matched, and what this issue request is just like node-pre-gyp `--build-from-source` option which disables downloading the pre-compiled addon, which the idea is not the same as the demo.

**Comment by rthadur** [comment]
@yorkie what demo you are referring ?

**Comment by yorkie** [comment]
It's https://www.npmjs.com/package/@tensorflow/tfjs-node#mnist-demo-for-nodejs :)

**Comment by tafsiri** [comment]
Have you tried cloning this repository and running that script? You can checkout specific versions of tfjs via tags https://github.com/tensorflow/tfjs/tags

**Comment by yorkie** [comment]
@tafsiri The tag doesn't work for me, because it can't run the script in `npm-script`.

**Comment by tafsiri** [comment]
@yorkie. I don't understand what you mean by "it can't run the script". What output do you get when you run `npm run build-addon-from-source` (within the tfjs-node subfolder of this repository)?

**Comment by yorkie** [comment]
What I mean is run `npm run build-addon-from-from-source` when running `npm install`.

**Comment by tafsiri** [comment]
I'm not sure what you mean, there isn't enough detail in the issue. Could you provide a repository that we can clone with steps to reproduce the problem and what output you are getting vs what you would expect/want to see?
