### ISSUE TITLE
Facemesh "rotated faces" update returns inaccurate .mesh data

### ISSUE THREAD

**Issue by ButzYung** [tensorflow/tfjs#3827]
**TensorFlow.js version**

v2.1.0+ (WASM backend running on a webworker)

**Browser version**

Google chrome v84+

**Describe the problem or feature request**

The latest Facemesh "rotated faces" update (v0.0.4) returns inaccurate .mesh data on detected faces, resulting in inaccurate 3D mesh rotation when mapped using these data. I have recorded a video to demonstrate the problem.

https://youtu.be/R1ReExt20Ho

The face on the upper right is mapped using .scaledMesh, which is accurate as usual. However, when I map .mesh data to the 3D avatar in the middle, the head rotation is obviously inaccurate in certain situations. When I rotated my head along the z-axis at the beginning of the video, the 3D avatar's head stayed pretty still. The top-most number on the uppper left shows the y difference between the Facemesh keypoints 234 and 454, which are roughly the positions of the ears. As you can see, the y difference of these points stays flat even when I rotate the head along the z-axis by a large degree (the app uses this figure to calculate the z-axis rotation, which explains why the avatar head stays still).

This problem never existed in previous versions of Facemesh running on the same app.

**Code to reproduce the bug / link to feature request**

Don't have minimized codes to reproduce the problem, but you can try the app demo and see the problem by yourself.

https://sao.animetheme.com/?cmd_line=/TEMP/DEMO/miku00&use_latest_facemesh=1

Double-click the "Selfie AR" icon to activate the selfie camera, and then double-click "Facemesh AI" to turn on Facemesh.

You may also try the demo using the previous version of Facemesh (v0.0.3), which doesn't have the problem.

https://sao.animetheme.com/?cmd_line=/TEMP/DEMO/miku00

**Comment by ButzYung** [comment]
@annxingyuan I have updated my app to use the new Face-landmarks-detction module (v0.0.1). The problem is partially fixed, but the "roll" rotation (z-axis) is still null for .mesh data. Just like the beginning of the last video demo, if I "roll" my head, the avatar which reacts with the .mesh data doesn't roll her head accordingly.

PS:. scaledMesh data is correct as usual.

**Comment by rthadur** [comment]
@ButzYung sorry for delay , please update the issue with latest information if it still persists. Thank you

**Comment by rthadur** [comment]
Facemesh is deprecated , please try our latest face-detection model which has support included for "rotated faces". Thank you
