### ISSUE TITLE
TFJS-models Speech Commands Readme incomplete

### ISSUE THREAD

**Issue by Arpitrf** [tensorflow/tfjs#3828]
The 3rd point in the readme of [tfjs-models/speech-commands/training/browser-fft/](https://github.com/tensorflow/tfjs-models/tree/master/speech-commands/training/browser-fft) does not explain how to Run WebAudio FFT on the .dat files generated in step 2 in the browser.

Please help.

**Comment by pyu10055** [comment]
please check out the notebook for training a custom model with browser_fft
https://github.com/tensorflow/tfjs-models/blob/master/speech-commands/training/browser-fft/training_custom_audio_model_in_python.ipynb
