### ISSUE TITLE
The path of dict.txt and .bin are not related to model.json.

### ISSUE THREAD

**Issue by SanyapongYoukachen** [tensorflow/tfjs#3833]
#### TensorFlow.js version
"@tensorflow/tfjs-automl": "^1.0.0",
#### Browser version
Google Chrome | 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Linux
JavaScript | V8 8.3.110.13
Flash | 32.0.0.414 /home/force/.config/google-chrome/PepperFlash/32.0.0.414/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

#### Describe the problem or feature request
I tried to load model from firebase cloud storage with tfjs-automl package but the error occur due to **wrong path of dict.txt and .bin** . i noticed that the request path for dict.txt and *.bin are *not related* to the model.json, but directly request at the root level of storage as pictures below. May i ask, how can i define the path for dict.txt and .bin?

#### Code to reproduce the bug / link to feature request
```
const modelRef = await storage
      .ref(props.tfjsModelRef + "/model.json")
      .getDownloadURL();
    const model = await automl.loadObjectDetection(modelRef);
```
![Screenshot from 2020-08-11 15-42-17](https://user-images.githubusercontent.com/39583962/90729690-eaae8600-e301-11ea-839f-e151cd5ed1f1.png)

![Screenshot from 2020-08-11 15-38-49](https://user-images.githubusercontent.com/39583962/90729646-dd919700-e301-11ea-8d35-13c629423b05.png)

Thank you for your hard work.
Best.

**Comment by rthadur** [comment]
@SanyapongYoukachen can you please provide codepen example or execuatable code to reproduce error ? did you try the steps provided [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-automl#loading-the-model-1) ?

**Comment by SanyapongYoukachen** [comment]
To answer your question, yes i followed the instruction from [package!](https://www.npmjs.com/package/@tensorflow/tfjs-automl).

Now, i tried to reproduce error with codepen, but I don't know how to use tfjs-automl in cdn (normally i used React and use syntax as package suggestion). Anyway here is the link to reproduce the error [link to codepen!](https://codepen.io/sanyapongyoukachen/pen/LYNbbZq). Noted that there is still buggy as automl is not defined which i don't know how to solve :(. Hope this pen give you more information about my situation.

For further information, here is download url generated from firebase.
"https://firebasestorage.googleapis.com/v0/b/tidy-fort-206200.appspot.com/o/newFolder%2Fsome%2Fnested%2Fmodel.json?alt=media&token=78bd4dfc-2412-471d-a049-c48648723a10"

Sorry for your not convenient, and thank you in advance for your attention.
Best.

**Comment by SanyapongYoukachen** [comment]
I have followed your instruction, but i still get the error. I have tested my function with string name of .bin file and the result was correct. However the path from error response is different from my test result. Not sure what did i do wrong, any further suggestion for me?. 

Here is some path of custom loadObjectDetection code as your mentioned and also log result for your information. 
```
import * as tf from "@tensorflow/tfjs";

const loadDictionary = async (dictUrl) => {
    try {
      const dict = await window.fetch(dictUrl);
      return dict.text();
    } catch (err) {
      console.log(err);
    }
  };

const convertFunc = async (binFile) => {
    const url = await storage
      .ref(props.tfjsModelRef + "/" + binFile)
      .getDownloadURL();
    return url;
  };

const loadObjectDetection = async () => {
    const modelUrl = await storage
      .ref(props.tfjsModelRef + "/model.json")
      .getDownloadURL();
    const dictUrl = await storage
      .ref(props.tfjsModelRef + "/dict.txt")
      .getDownloadURL();
    // test
    const ref = await convertFunc("group1-shard1of3.bin");
        console.log(ref);
    // download model
    const [model, dict] = await Promise.all([
          tf.loadGraphModel(modelUrl, {
            weightUrlConverter: convertFunc,
          }),
          loadDictionary(dictUrl),
        ]);
```
**url result from test function**: https://firebasestorage.googleapis.com/v0/b/cravi-application.appspot.com/o/HvWne4sucCODst1XuMVjfGlXXVF3%2Fdataset1_model1%2Ftfjs%2Fmodel-export%2Fiod%2Ftf_js-HvWne4sucCODst1XuMVjfGlXXVF3_11-2020-06-23T02%3A25%3A51.333Z%2Fgroup1-shard1of3.bin?alt=media&token=347ee656-636b-4ace-9094-ee9a51e9504b
    
**url result from error**: https://firebasestorage.googleapis.com/v0/b/cravi-application.appspot.com/o/group1-shard3of3.bin?alt=media&token=3bb27eb8-3bc7-41d0-b64c-ec7811d693f5

![Screenshot from 2020-08-24 08-31-18](https://user-images.githubusercontent.com/39583962/90991460-37d17700-e5e4-11ea-895e-05924572d8c0.png)

Sorry for your not convenient,
Best.

**Comment by pyu10055** [comment]
@SanyapongYoukachen This weightUrlConverter feature has not been released, you would need to compile the tfjs-core manually.

**Comment by SanyapongYoukachen** [comment]
@pyu10055 Ohh, got it, I will try to compile tfjs-core from source. I think my asking has been successfully clarified and this issue should be closed now. 

Very appreciate you all calm down to me. Also thank you all very much for this incredible package.

Hope the best for you all.
Regards.
