### ISSUE TITLE
tensorflowjs_converter : size of a converted model is 60% bigger with tfjs 2 compare to tfjs 1

### ISSUE THREAD

**Issue by gabides** [tensorflow/tfjs#3837]
#### TensorFlow.js version
2.3.0
#### Browser version
N/A
#### Describe the problem or feature request

I upgraded to pip tensorflowjs 2.3.0 from 1.3.2 and now the models converted by tensorflowjs_converter are significantly heavier (around 60% more, regardless of quantization).

##### previously with `pip install tensorflowjs==1.3.2` :
```
tensorflowjs_converter --input_format=tf_saved_model \
        --output_format=tfjs_graph_model \
        --signature_name=serving_default \
        --saved_model_tags=serve \
        --strip_debug_ops=False\
       /path_to_saved_model/saved_model converted_model
```
=> size 3.3 MB

```
tensorflowjs_converter --input_format=tf_saved_model \
        --output_format=tfjs_graph_model \
        --signature_name=serving_default \
        --saved_model_tags=serve \
        --strip_debug_ops=False \
        --quantization_bytes 1 \
       /path_to_saved_model/saved_model converted_model_quantized_1_byte
```
=> size 1 MB

##### now with `pip install tensorflowjs==2.3.0` with the `tensorflowjs_wizard` generated command :

```
tensorflowjs_converter --control_flow_v2=True \
        --input_format=tf_saved_model \
        --saved_model_tags=serve \
        --signature_name=serving_default \
        --strip_debug_ops=False \
        --weight_shard_size_bytes=4194304 \
       /path_to_saved_model/saved_model converted_model
```

=> size 5.3 MB

```
tensorflowjs_converter --control_flow_v2=True \
        --input_format=tf_saved_model \
        --quantize_uint8=* \
        --saved_model_tags=serve \
        --signature_name=serving_default \
        --strip_debug_ops=False \
        --weight_shard_size_bytes=4194304 \
        /path_to_saved_model/saved_model converted_model_quantized_1_byte
```

=> size 1.6 MB

both converted models size have increased by 60% compared to tensorflowjs 1.3.2. is this expected behaviour or a bug, or maybe there is an option I missed?

Thanks

**Comment by gabides** [comment]
@pyu10055 i did every test in clean separate virtualenvs for the conversion (each with only tensorflowjs installed with the specific version to test).
Also i did a few more tests to answer your questions:
- setting --control_flow_v2 to True or False doesn't change the output size
- converter with version 2.0.0 gives the same output in terms of size as 2.3.0

 I'll try to find a public model for reproducibility and post it here.
Also maybe related: the models I am trying to convert are coded and exported to saved_model format from tf.keras (tensorflow==1.14)

**Comment by pyu10055** [comment]
@gabides can you try to export your model with TF 2, since tfjs 2.x are using at lease 2.1 TF.
