### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by hiranya911** [tensorflow/tfjs#384]
## Issue 1

Documentation for [`fromPixels()`](https://js.tensorflow.org/api/0.6.1/#fromPixels) method states:

> numChannels (number) The number of channels of the output tensor. The supported image types are all 4-channel by default, a numChannels value less than 4 allows you to ignore channels. Optional

But the default seems to be 3:

```
Tensor
     [ [[100, 150, 200],]]
```

## Issue 2

Documentation for [`tidy()`](https://js.tensorflow.org/api/0.6.1/#tidy) method states:

> Executes the provided function f and after it is executed, cleans up all intermediate tensors allocated by f except those returned by f

But there's no argument called `f` declared in this method.

## Issue 3

Documentation for [`tidy()`](https://js.tensorflow.org/api/0.6.1/#tidy) method states:

> gradMode (boolean) If true, starts a tape and doesn't dispose tensors. Optional

It is not clear what "a tape" means. More details required.

## Issue 4

The config to the [`fit()`](https://js.tensorflow.org/api/0.6.1/#tf.Model.fit) method accepts a verbosity parameter:

> verbose (ModelLoggingVerbosity) Optional

Type of this parameter is not declared (int? string?). Also it seems this parameter is currently not supported (based on the errors we get), and should probably be left out. Or at least document that it is not yet implemented.

## Issue 5

The [getting started](https://js.tensorflow.org/#getting-started) example produces meaningless results, unless the epoch is set to a higher count.

**Comment by tafsiri** [comment]
Thanks for reporting these @hiranya911. I have PRs out for most now. I think the consensus for issue 4  is the message from the error is preferred and wont fall out of sync with the implementation (which the docs could if we just edited that).
