### ISSUE TITLE
How to convert image into tensor3d

### ISSUE THREAD

**Issue by LMJayasundara** [tensorflow/tfjs#3840]
How I convert image into tensor3d in TensorFlow Js using node js.

If I have an RGB image [3, 3, 3] how I convert it into tensor3d like this output

[ [255, 0, 0], [255, 0, 0], [255, 0, 255],
  [255, 0, 0], [255, 255, 0], [255, 0, 0],
  [255, 0, 0], [255, 0, 0], [255, 0, 255] ]

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
