### ISSUE TITLE
Mismatch in sampling rate for speech-commands

### ISSUE THREAD

**Issue by Arpitrf** [tensorflow/tfjs#3845]
I am getting the following in my browser console: 
"WebGL is not supported on this device".

I cannot enable it as well because my institution has disabled "Use Hardware acceleration when possible". So, tensorflow.js is using "cpu" as the backend:
`
console.log(tf.getBackend());
output: cpu
` 

However, now I am getting wrong predictions because of the following error: 
**"Mismatch in sampling rate: Expected: 44100; Actual: 48000"**

Please help.

**Comment by Arpitrf** [comment]
**UPDATE**: I realised that the mismatch error is not due to changing backend to "cpu" because in one chrome browser it working fine, but in a different chrome browser it is not. 

How to ensure that the browser uses 44100 as the sampling rate? Do I need to make any change in recognizer.listen() method?

**Comment by rthadur** [comment]
@Arpitrf what is chrome version for both ? can you please provide minimalistic code to reproduce the error or code pen example ?

**Comment by Arpitrf** [comment]
Chrome version (where code is working fine) - Version 84.0.4147.105 (Official Build) (64-bit)
Chrome version (where mismatch error) - Version 84.0.4147.89 (Official Build) (32 Bit)

JS Code
```
let customSpeechRecognizer;

async function listen() {
    await customSpeechRecognizer.listen(result => {
        // `result.scores` contains the scores for the new words, not the original
        // words.
        scores = Array.from(result.scores).map((s, i) => ({score: s, word: words[i]}));
        
        // Find the most probable word.
        scores.sort((s1, s2) => s2.score - s1.score);
        console.log("PREDICTION: ", scores[0].word)
    }, {probabilityThreshold: 0.75});

}

async function app() {
    customSpeechRecognizer = speechCommands.create('BROWSER_FFT', null, 'http://localhost:8000/best_weights/transferModel.json', 'http://localhost:8000/metadata.json'); 
    await customSpeechRecognizer.ensureModelLoaded();
    console.log(customSpeechRecognizer)
 }

app()
```

HTML Code: 
```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands"></script>
  </head>
  <body>
    <script src="index4.js"></script>
    <button id="listen" onclick="listen()">Listen</button>
  </body>
</html>
```

Although, to reproduce the error, you will need the transerModel.json, transferModel.weights.bin. and metadata.json files. Would you be needing them to analyse this bug?

**Comment by Arpitrf** [comment]
Request your assistance with this!

**Comment by Arpitrf** [comment]
Hi I am very interested to make this work for my project. Request your help!

**Comment by Arpitrf** [comment]
Hello! Any updates on this?

**Comment by Arpitrf** [comment]
Hi request your help on this sooner!

**Comment by Arpitrf** [comment]
I think I have found a solution to this. 
In browser_fft_extractor.js (line 185) changing:
`this.audioContext = new this.audioContextConstructor() as AudioContext;`
to
`this.audioContext = new this.audioContextConstructor({sampleRate:44100}) as AudioContext;`
Worked for me.

Let me know if this seems correct to you and if it does, I can make a pull request.

**Comment by AlanFernandoS** [comment]
The solution is changing the lines of the speech-commands, to:
                            case 1:
                                //This needs to b changed to our System
                                // this.sampleRateHz = 48000;
                                // this.audioContext = new AudioContext({ sampleRate: this.sampleRateHz });

                                this.audioContext = new AudioContext();
                                this.sampleRateHz = this.audioContext;
                                // console.log("Valor de RateHz");
                                // console.log(this.sampleRateHz);
                                // console.log(this.audioContext);
                                // console.log(a.sent());
                                return (
                                    (t.stream = a.sent()),
                                    (this.audioContext),
                                    this.audioContext.sampleRate !== this.sampleRateHz && console.warn("Mismatch in sampling rate: Expected: " + this.sampleRateHz + "; Actual: " + this.audioContext.sampleRate),
                                    (r = this.audioContext.createMediaStreamSource(this.stream)),
                                    (this.analyser = this.audioContext.createAnalyser()),
                                    (this.analyser.fftSize = 2 * this.fftSize),
                                    (this.analyser.smoothingTimeConstant = 0),
                                    r.connect(this.analyser),
                                    (this.freqDataQueue = []),
                                    (this.freqData = new Float32Array(this.fftSize)),
                                    this.includeRawAudio && ((this.timeDataQueue = []), (this.timeData = new Float32Array(this.fftSize))),
                                    (n = Math.max(1, Math.round(this.numFrames * (1 - this.overlapFactor)))),
                                    (this.tracker = new m(n, Math.round(this.suppressionTimeMillis / this.frameDurationMillis))),
                                    (this.frameIntervalTask = setInterval(this.onAudioFrame.bind(this), (this.fftSize / this.sampleRateHz) * 1e3)), [2]
                                );
                        }
