### ISSUE TITLE
Saving FaceMesh to LocalStorage or IndexDB

### ISSUE THREAD

**Issue by dikatok** [tensorflow/tfjs#3846]
Is there any existing roadmap about supporting cache/save feature for `FaceMesh` or `tfjs-models` in general?

I think it could be useful for environments such as chrome extension where you need to download the model every startup.

**Comment by rthadur** [comment]
Facemesh has been [depreciated](https://github.com/tensorflow/tfjs-models/pull/853) and no longer supported , closing this request.
