### ISSUE TITLE
Migrate knn-image-classifier from tfjs-core to tfjs-models

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#385]
The KNN classifier [lives in](https://github.com/tensorflow/tfjs-core/tree/master/models/knn_image_classifier) [tfjs-core](https://github.com/tensorflow/tfjs-core/) and is outdated.

We need to make it generic (have it work with any embedding, not just squeezenet) and move it to [tfjs-models](https://github.com/tensorflow/tfjs-models). Then show a demo that uses MobileNet embeddings + KNN.

**Comment by HalfdanJ** [comment]
Has been added to tfjs-models now, so can be removed from tfjs-core
