### ISSUE TITLE
[WASM] Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by akineeic** [tensorflow/tfjs#3852]
#### TensorFlow.js version
  "tfjs-core": "2.3.0"
"tfjs-backend-wasm": "2.3.0",

#### Browser version
84.0.4147.105 (Official Build) (64-bit)

#### Describe the problem or feature request
I want to  try the newest version of tfjs-backend-wasm. But the error as follows occured when import the module. Is this caused by the missing of package or need some configuration to run tfjs-backend-wasm 2.3.0
```
Uncaught Error: Cannot find module 'worker_threads'
```

#### Code to reproduce the bug
Just using the [example](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm/starter/webpack) of webpack in this repo and modify the version of tfjs-backend-wasm to 2.3.0 in [`package.json`](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/starter/webpack/package.json#L11-L12)

**Comment by orporan** [comment]
+1

**Comment by annxingyuan** [comment]
Hey @akineeic - thank you for reporting this. I believe this should be fixed by: https://github.com/tensorflow/tfjs/pull/3829 - this will be available in our next release.

In the meantime, you could modify the package.json of your project: in the `browser` field, add `worker_threads: false` and `perf_hooks: false`

**Comment by willmorgan** [comment]
@annxingyuan Thanks for looking at this, do you have an ETA for the next release?

This doesn't seem to work with my fairly standard webpack config:

> In the meantime, you could modify the package.json of your project: in the browser field, add worker_threads: false and perf_hooks: false
