### ISSUE TITLE
Feature Request: How to directly read a saved binary weights file

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#386]
How can I directly read a saved binary weights file? What format is the data in the binary file? Is it just a list of float32 numbers or is the format defined by the json file.

I have a saved a very simple json file [here](https://github.com/hpssjellis/beginner-tensorflowjs-examples-in-javascript/blob/e6817ae3dcf6280cfb8efe6093acbb07db05b25a/saved-models/batches-20000-done.json) and a binary saved weights file [here](https://github.com/hpssjellis/beginner-tensorflowjs-examples-in-javascript/blob/e6817ae3dcf6280cfb8efe6093acbb07db05b25a/saved-models/batches-20000-done.weights.bin) all done from my example of saving tensorflowjs models  webpage [here](http://rocksetta.com/tensorflowjs/beginner-examples/tfjs11-load-weights.html) 

Is there a Javascript method to test the validity of the binary file, without having to load it into a model and wait for the model to crash? The above weights file should have 13 'float32' 

I want users to be able to train and upload the weights to an online server. It would be nice to be able to test that the binary file is actually a weights file and not a virus of some sort.

**Comment by tafsiri** [comment]
You can use `tf.io.loadWeights` to read the files. Here is a link to a snippet of code to read just weights files. https://github.com/tensorflow/tfjs-converter#loading-the-weights-only. The JSON file describes what kind of data (floats, ints etc) is in the binary file so both are needed to load the files.

I don't think we have a method to test the validity of a weights file. Its effectively just a stream of bytes that we decode based on the manifest AFAIK.

**Comment by hpssjellis** [comment]
Thanks @tafsiri 

Any idea what the "this" is in the code snippet. I assumed it was the original or newly loaded model but that does not seem to work


```
import * as tf from '@tensorflow/tfjs';

const weightManifestUrl = "https://example.org/model/weights_manifest.json";

const manifest = await fetch(weightManifestUrl);
this.weightManifest = await manifest.json();
const weightMap = await tf.io.loadWeights(
        this.weightManifest, "https://example.org/model");
```

**Comment by nsthorat** [comment]
You don't need "this" here, just call it "weightManifest" and remove all
instances of "this".

**Comment by hpssjellis** [comment]
All this code has working demos at 



[x3.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x3.html) weights tensors

[x2.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x2.html) weightManifest 

[x4.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x4.html) model JSON file

Using this bit of code [x3.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x3.html) weights tensors:
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.4"> </script> 
<script>                                                                                                                                                       
  let myInline = (async function myGo6() {							    								    
     const loadedModel6 = await	 tf.loadModel("https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/batches-20000-done.json")
     document.getElementById('myWeights').value = loadedModel6.getWeights()    
     })()
 </script>
<textarea id="myWeights" rows=10 cols="100%"></textarea><br>
```


 I know that my weights are:

```
Tensor
    [[-6.490416, -7.7665491, -3.3854311],
     [5.834147 , -6.0184202, -6.8177199]],Tensor
    [-4.0337663, 3.154465, 7.0981731],Tensor
    [[6.5765972  ],
     [-10.2805595],
     [9.9978762  ]],Tensor
    [-5.1192789]
```




but that output is not in JSON format and not very usable. 

The [example code](https://github.com/tensorflow/tfjs-converter#loading-the-weights-only) did not work for me but a minor change (I changed weightManifest to weightManifest.weightsManifest notice the added "s") did sort of work. [x2.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x2.html) weightManifest 


```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.4"> </script> 
<script>
  let myInline = (async function() {								    
      const manifest = await fetch("https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/batches-20000-done.json");
      var weightManifest = await manifest.json();								    										    			
      const weightMap = await tf.io.loadWeights(weightManifest.weightsManifest, "https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models" );									    									    
      document.getElementById('myLayers2').value =  JSON.stringify(weightMap, null, 4)												                    
  } )()
</script>
<textarea id="myLayers2" rows=50 cols="100%"></textarea><br><br>
```

unfortunately it gives all the layer information EXCEPT the weights. Note: this output looks similar to the models json output but you can compare it [here x4.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x4.html) 

```
{
    "hiddenLayer/kernel": {
        "isDisposed": false,
        "size": 6,
        "shape": [
            2,
            3
        ],
        "dtype": "float32",
        "strides": [
            3
        ],
        "dataId": {},
        "id": 0,
        "rankType": "2"
    },
    "hiddenLayer/bias": {
        "isDisposed": false,
        "size": 3,
        "shape": [
            3
        ],
        "dtype": "float32",
        "strides": [],
        "dataId": {},
        "id": 1,
        "rankType": "1"
    },
    "outputLayer/kernel": {
        "isDisposed": false,
        "size": 3,
        "shape": [
            3,
            1
        ],
        "dtype": "float32",
        "strides": [
            1
        ],
        "dataId": {},
        "id": 2,
        "rankType": "2"
    },
    "outputLayer/bias": {
        "isDisposed": false,
        "size": 1,
        "shape": [
            1
        ],
        "dtype": "float32",
        "strides": [],
        "dataId": {},
        "id": 3,
        "rankType": "1"
    }
}


```

Any suggestions how to get the weights in a usable format. Hopefully in JSON format?

**Comment by tafsiri** [comment]
We don't have a method that turns weights into JSON (as they would take a lot of space in that format), however if you have a tensor with your weights you could do the following:

```
const weights = tf.tensor2d([1, 2, 3, 4], [4, 1]) // just an example
const weightsData = weights.dataSync();
const weightsDataJson = JSON.stringify(Array.from(data)); // convert the data to a regular array and then turn it to JSON
console.log(weightsDataJson)
```

**Comment by hpssjellis** [comment]
Solved it! This code converts a float32 binary file into JSON format of all the weights.

Live demo [x6.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x6.html)

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.4"> </script> 
Extract weights for consistent float32 Tensorflowjs saved model binary url <br>
<input id="myBinaryFile" type="text" size="130" value="https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/batches-20000-done.weights.bin"><br><br>


<input id="myButton4950" type="button" value="Extract Weights in JSON format" onclick="{                                                                                                                                                       
  let myInline = (async function () {							    								    
     const myBinaryFile = await	fetch(document.getElementById('myBinaryFile').value)    
     const myBuffer =await  myBinaryFile.arrayBuffer() 
     
     const dv = new DataView(myBuffer);
     var f32 = new Float32Array(myBuffer.byteLength / 4);
     const littleEndian = true;
	  
     for (let i = 0; i < f32.length; i++) {
        f32[i] = dv.getFloat32(i*4, littleEndian);
     }   

     const myWeightsJSON = JSON.stringify(f32,null,4)  	  
     document.getElementById('myWeights').value =  myWeightsJSON 
     })()
}"><br>
<textarea id="myWeights" rows=15 cols="50"></textarea><br>
```



The output is 


```
{
    "0": -6.490416049957275,
    "1": -7.766549110412598,
    "2": -3.3854310512542725,
    "3": 5.834146976470947,
    "4": -6.018420219421387,
    "5": -6.81771993637085,
    "6": -4.033766269683838,
    "7": 3.1544649600982666,
    "8": 7.098173141479492,
    "9": 6.576597213745117,
    "10": -10.280559539794922,
    "11": 9.997876167297363,
    "12": -5.119278907775879
}
```


Live demo [x6.html](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/saved-models/x6.html)

**Comment by baloodevil** [comment]
@hpssjellis Thank you for providing your code to pull actual weights (not the definition of them) from the model!

@tafsiri I understand retrieving all weights of a model can be a massive dataset, however it would still be useful to be able to call in some scenarios.  For example, a visualization tool for simple models for educational purposes.

**Comment by baloodevil** [comment]
FYI, you can get weight values from a trained model (which could be sourced from the model.json and model.weights.bin files).

For the first layer...

// kernel (a.k.a. weights):
model.layers[0].getWeights()[0].print()

// bias:
model.layers[0].getWeights()[1].print()
