### ISSUE TITLE
Feature request:  would you mind to add a Reasonml binding for react native tensorflow

### ISSUE THREAD

**Issue by EhsanSarshar** [tensorflow/tfjs#3865]

**Comment by rthadur** [comment]
cc @tafsiri

**Comment by tafsiri** [comment]
Hi. This isn't something our team is going to be able to do/maintain. You are probably in a better position to do it than we are! Our `d.ts` files (typescript typings), might be helpful if you want to go down the route of generating bindings. Good luck!
