### ISSUE TITLE
Memory leak issues in tensor.max()

### ISSUE THREAD

**Issue by kashikarparth** [tensorflow/tfjs#3869]
#### Browser version: Google Chrome 74

```javascript
async function predicttest() {
while (true) {
    console.log('Executing');
    tf.engine().startScope();  
        const img = tf.ones([300,300])
        const fbmx = tf.tidy(() => img.max()); //giving memory leak, but min doesnt.
        img.dispose();
        fbmx.dispose();
    tf.engine().endScope();
    await tf.nextFrame(); 
  }
}
```
GPU memory allocated continues to rise while executing this while loop (made after isolating the leak). No issues if tensor.min() is used instead.
I have tried to use tf.setBackend('webgl') and tf.disposeVariables(), but to no avail.

Is there a way to eliminate the memory leak? The issue is solely from the max() operation.

**Comment by tafsiri** [comment]
Confirmed with minimal [codepen reproduction](https://codepen.io/tafsiri/pen/dyMzrMm?editable=true&editors=0012%3Dhttps%3A%2F%2Fjs.tensorflow.org%2Fapi%2Flatest%2F), @annxingyuan would you be able to take a look.
