### ISSUE TITLE
tfjs-react-native: Unable to run the webcam demo 

### ISSUE THREAD

**Issue by littleV** [tensorflow/tfjs#3874]
#### TensorFlow.js version
"@tensorflow/tfjs": "^2.3.0"
#### Browser version
React Native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
#### Describe the problem or feature request
Hi,

I'm trying to learn to build react native tfjs apps. This is my app: https://github.com/OneArt-Inc/ArtTools/tree/art_stylizer/ArtStylizer, and I used code from Webcam demo. I tried to use the webcam demo directly but I was not able to build due to a signing issue.

So the issue is, I'm able to load the model and predict, however, the resulting image turns out to be black all the time.

Can somebody take a look at my code and see where I did wrong?

**Comment by tafsiri** [comment]
Hi this question as is is a bit too open ended for github issues. You would need to pinpoint further in your code to determine where they may be an issue. For example are you able to run other models or do other computations with tf.js or is everything resulting in zeros. I also noticed this folder https://github.com/OneArt-Inc/ArtTools/blob/art_stylizer/ArtStylizer/js/model/style.json has no `.bin` files which would prevent your model from loading properly.

**Comment by littleV** [comment]
Hi @tafsiri ,

Thanks for your response, I'll try with a different model to see if it's also resulting in zeros.

That style.json is not what I'm actually using for my project, I just downloaded from the link from the tfjs webcam demo to take a look. For what I learned, I don't need a .bin file as long as the weightsManifests are in the .json file, according to a blog post. But I'm new to tfjs I could be wrong.

**Comment by littleV** [comment]
Btw, another interesting find. I loaded the tfjs example in a react native webview, the model is also predicting all zeros. However, I put the exact same code on a browser on a laptop, it works.

**Comment by tafsiri** [comment]
You always need a .bin file (or multiple if it is sharded). The manifest describes how to decode the values in the bin files. I would check for errors in the logs before the prediction is done.

tfjs-react-native is not designed to work in browsers/web mode. But you should be able to use regular tfjs if you want to do that. For your second find, do RN webviews allow access to WebGL? You can see if it works on the cpu backend by adding `tf.setBackend('cpu')` to the top of your program.

**Comment by littleV** [comment]
Hi @tafsiri,

Setting `tf.setBackend('cpu')` didn't help with the webview version either. I'll close this issue for now since I'm not making any progress. Will reopen if I have more info.
