### ISSUE TITLE
Facing trouble on applying merge operation after conv2d operation on version 0.11.2

### ISSUE THREAD

**Issue by co2meal** [tensorflow/tfjs#388]
#### TensorFlow.js version
v0.11.2

#### Browser version
Reproducible in any browser.

#### Describe the problem or feature request
> WebGL backend: No data found for this tensor. Did you change your backend in the middle of the program? New backends can't use Tensors created with previous backends

After running the below code, the above exception arises.

Expected result is printing a tensor with shape of [1, 222, 222, 112].

#### Code to reproduce the bug / link to feature request
```js
const input1 = tf.layers.input({shape:[224, 224, 3]})
const x1 = tf.layers.conv2d({filters: 112, kernelSize: [3, 3]}).apply(input1)
const x2 = tf.layers.conv2d({filters: 112, kernelSize: [3, 3]}).apply(input1)
const added = tf.layers.add().apply([x1, x2])

const model = tf.model({inputs: [input1], outputs: added})
model.predict([tf.ones([1, 224, 224, 3])]).shape
```

* It seems it does not happen on the previous version v0.10.0.
* It does not happen with conv1d, not conv2d 
* Replacing add operation with other merge operations like concatenate, we got same result.

**Comment by caisq** [comment]
@dsmilkov @nsthorat 

I tried the code @co2meal provided on tfjs 0.11.4 and was able to see the error message reported:
WebGL backend: No data found for this tensor. Did you change your backend in the middle of the program? New backends can't use Tensors created with previous backends

The same code works properly on 0.10.0. This looks like something related to the core. Any thoughts?

**Comment by caisq** [comment]
Update: after some debugging, it looks like that this may have to do with the memory optimization that went into 0.11. Still investigating the details.
cc @bileschi @ericdnielsen

**Comment by caisq** [comment]
@nsthorat  and I did some pair-debugging. The conclusion is that this is a manifestation of https://github.com/tensorflow/tfjs/issues/69, which we plan to fix soon.

**Comment by caisq** [comment]
Thanks to @nsthorat for sending out the PR to fix the root cause:
https://github.com/tensorflow/tfjs-core/pull/1080
