### ISSUE TITLE
 peer dependency seedrandom is not provided as dependency by tfjs

### ISSUE THREAD

**Issue by juuyan** [tensorflow/tfjs#3881]
#### TensorFlow.js version
2.3.0

#### Browser version
Chrome 85.0.4183.83

#### Describe the problem or feature request
seedrandom is peer dependency of tfjs-data, yet it is not provide by tfjs as dependency, which leads to error on compile...
`Module not found: @tensorflow/tfjs-data tried to access seedrandom (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`

**Comment by rthadur** [comment]
@juuyan can you please check a related issue [here](https://github.com/tensorflow/tfjs/issues/3875)

**Comment by juuyan** [comment]
@rthadur I have checked that issue but it seems to be different.
The bug here I think is because "seedrandom" is not added as dependency in tfjs. https://github.com/tensorflow/tfjs/blob/master/tfjs/package.json
I can fix it manually by adding it locally.

**Comment by rthadur** [comment]
cc @tafsiri

**Comment by tafsiri** [comment]
Seedrandom is a [dependency of tfjs-core](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/package.json#L88) which is a dependency of tfjs.

Could you provide a repository that we can clone that replicates the problem?

**Comment by juuyan** [comment]
srr I think the problem is on the Yarn berry pnp..

**Comment by tsuckow** [comment]
@tensorflow-butler 

Yarn 2 has a strict dependency resolution system
Because @tensorflow/tfjs-data has a peer dependency on seedrandom, so must @tensorflow/tfjs or it must have an explicit dependency.

This can be worked around by adding the following to `.yarnrc.yml`:
```yaml
packageExtensions:
  "@tensorflow/tfjs@*":
    peerDependencies:
      seedrandom: "~2.4.3"
```

**Comment by PabloRN** [comment]
In case that I'm not using Yarn and I have the same issue? Thank you
