### ISSUE TITLE
tfjs-react-native: Error ‘func is not a function’

### ISSUE THREAD

**Issue by piecemakerz** [tensorflow/tfjs#3885]
#### TensorFlow.js version
"@tensorflow/tfjs": "^2.3.0"
"@tensorflow/tfjs-react-native": "^0.3.0"

#### Describe the problem or feature request
Hi. I'm trying to run tfjs-react-native project [realtime_demo](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx) with my android smartphone, but I'm stuck with TensorCamera.

My project directory is [here](https://github.com/piecemakerz/tfjs-example), and if you need more files to inspect error just ask. The error I’m getting is this.

![error2](https://user-images.githubusercontent.com/22445243/92317932-f65bb580-f040-11ea-9448-c5874a1296ec.PNG)

When I debugged my project, I found out that when **TensorCamera** triggers onReady and calls **handleImageTensorReady**, the first argument of handleImageTensorReady - which is **images** - are not passed properly thus undefined. That's why my code gets stuck when `const imageTensor = images.next().value;` is called.

I'm using bare workflow with react-native-unimodules attached manually, but just to check I also tried using [expo-managed-example](https://github.com/tafsiri/tfjs-expo-managed-example). It throws the same `func is not a function` error.

What is causing this problem? Is it because the testing device I'm using too old to run tensorflow modules? Plz help.

#### ps1.

I'm sure this error is not related to loading tensorflow models (blazeface, posenet) because when I comment out all model-related codes from the demo project, I still get same `func is not a function` error. 

I'm sure TensorCamera is the problem because when I changed TensorCamera to ordinary Camera module from "expo-camera", no error occurred.

#### ps2.

I've borrowed Galazy S20 from one of my friends and test the project, and I got the some error. The problem was not with smartphone itself.

**Comment by piecemakerz** [comment]
After days of research, I found out it was problem with version. In my project where error occurred, I just installed packages using yarn, so I used "@tensorflow/tfjs": "^2.3.0" and     "@tensorflow/tfjs-react-native": "^0.3.0". 

When I changed my module dependencies (in package.json) as listed in [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/package.json), finally everything started to work correctly.

I'm kind of beginner to react-native, so I don't know which modules resulted crush exactly. Hope Amazing contributers of this repo finds out error soon and fit it.

**Comment by juliankleine** [comment]
Same problem over here - how to fix this?

**Comment by CPLTOM** [comment]
Same for me, Component does not render properly.

**Comment by yudhiesh1997** [comment]
I had the same issue then I upgraded web-gl and it worked.

**Comment by tafsiri** [comment]
I think we have a bug in 2.3.0, so I would suggest downgrading to an earlier version until our next release is out (should be this week).

**Comment by juliankleine** [comment]
@tafsiri thanks for the quick info, we are working around this issue for now, looking forward to the bugfix release

**Comment by rohail0** [comment]
@tafsiri were you referring to the recent 2.4.0 release? Unfortunately just updating tfjs from 2.3.0 to 2.4.0 did not fix this for me.

**Comment by Snupas** [comment]
Having the same issue. Interestingly, upgrading to tfjs 2.4.0 and to the newest expo-camera, expo-gl and expo-gl-cpp packages solved the issue for a while, but then I had the laptop shutdown while the react native server was running, restarted the laptop, built the app again and the issue returned.

It's a far fetch correlation and I've tried deleting node modules folder and cleaning up android builds thinking something got corrupted, but to no avail.

**Comment by tafsiri** [comment]
@Snupas, @rohail0  or anyone else still seeing this, would you be able to post a link to a minimal reproduction of this as a github repo (using 2.4.0)?

**Comment by rohail0** [comment]
@tafsiri sorry for the delay, forked the repo to try to expose this on the test integration_rn59 app. All I did was update most of the libraries to newer versions. https://github.com/rohail0/tfjs/tree/bug-func-is-not-function

**Comment by tafsiri** [comment]
This should be fixed in the just released 0.4.0. Thanks for reporting and please let us know if this doesn't resolve the issue for you.
