### ISSUE TITLE
Unknown GlorotUniform initializer while loading MobileNet Model on a localhost webapp 

### ISSUE THREAD

**Issue by Mo-Zakria** [tensorflow/tfjs#3887]
#### Describe the problem or feature request
I am currently trying to load mobilenet model into a web app(currently on localhost). 
I have converted the model using tensorflow converter

when i use the following line specifying the path to model.json 

```
 model = await tf.loadLayersModel("http://127.0.0.1:81/tfjs-models/MobileNet/model.json");}
```
i get the following error(i.e. also described in issue #798). Though this problem is not similar to 798 as i am loading the model into a web app using the above code in a java script file. 

```
Error: Unknown initializer: glorotUniform. This may be due to one of the following reasons:
1. The initializer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom initializer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at wE (generic_utils.js:242)
    at WI (initializers.js:610)
    at UI (initializers.js:650)
    at e [as constructor] (convolutional.js:529)
    at new e (convolutional.js:653)
    at t.fromConfig (serialization.js:96)
    at wE (generic_utils.js:277)
    at kA (serialization.js:31)
    at u (container.js:1207)
    at e.fromConfig (container.js:1235)
```

**Comment by rthadur** [comment]
@Mo-Zakria is it possible to share reproductions code with the model you are using ?

**Comment by Mo-Zakria** [comment]
> @Mo-Zakria is it possible to share reproductions code with the model you are using ?

Thank your for your reply and sorry for late reply from my side.
Can you explain it more that what code you want me to share. 
Plus i am using Mobilenet and to convert it into tfjs i've used both:

1. Tensorflow converter command
```
tensorflowjs_converter --input_format keras mobilenet.h5 TensorFlowJs/static/tfjs-models/MobileNet/

```
2. using tfjs.converters.save command
```
tfjs.converters.save_keras_model(mobilebet,'../TensorFlowJs/static/tfjs-models/MobileNet/')
```

**Comment by Mo-Zakria** [comment]
??

**Comment by pyu10055** [comment]
@Mo-Zakria can you share the mobilenet.h5 file, so we can reproduce?
