### ISSUE TITLE
Sandbox Fails on version 2.2.0 and 2.3.0

### ISSUE THREAD

**Issue by GantMan** [tensorflow/tfjs#3889]
#### TensorFlow.js version

`>= 2.2.0`

#### Browser version

Chrome Version 85.0.4183.83 (Official Build) (64-bit)

#### Describe the problem or feature request

Upgrade from TFJS from 2.1.0 to 2.3.0 or 2.2.0 keeps getting "Cannot evaluate flag 'DEBUG': no evaluation function found." when tested on codesandbox.com

#### Code to reproduce the bug / link to feature request

**This is a minimal demo:**

Take a look at this simple sandbox:  https://codesandbox.io/s/angry-upgrade-4l9pu

Now on the left side, update the version to 2.2.0 
![image](https://user-images.githubusercontent.com/997157/92436506-729de800-f16a-11ea-8c37-22da8a77f501.png)

When you refresh the editor, TFJS errors.

![image](https://user-images.githubusercontent.com/997157/92436592-a8db6780-f16a-11ea-86dd-83aea935e383.png)

I'm not finding anything when googling this issue

**Comment by tafsiri** [comment]
Thanks for the report @GantMan, i think this is probably related to a bug that should be fixed with [this pr](https://github.com/tensorflow/tfjs/pull/3848). We'll get a 
new release out as soon as we can.

**Comment by GantMan** [comment]
It's great to see you again Yannick!   Glad this was already on your radar.

**Comment by tafsiri** [comment]
Hey @GantMan! is this resolved with 2.4.0?

**Comment by GantMan** [comment]
Heya @tafsiri - I just tested and 2.4.0 has the same bug 👎 

![bug](https://user-images.githubusercontent.com/997157/94607467-93d19000-0261-11eb-9d82-372f7a685100.gif)

**Comment by tafsiri** [comment]
@GantMan are you able to reproduce this outside of codesandbox? I tried to reproduce this here https://github.com/tafsiri/tfjs-parcel-test but didn't get any error (on either 2.3.0 or 2.4.0).

I'm assuming codesanbox is running npm run start (or something similar)?

**Comment by GantMan** [comment]
I can confirm, this ONLY happens when the code is online through codesandbox. 

I'm not sure why ONLY 2.2, 2.3, and 2.4 cause this conflict.  That's why I filed it here, rather than with the Codesandbox team.  

It might not be a bug with TFJS.  I'm quite unsure what changed between 2.1 and 2.2

**Comment by tafsiri** [comment]
How can we determine/trace what codesandbox does to generate the page that produces that error? The error suggests that the flags.js file in tjfs-core has not been loaded. If there is a bundling step that does tree shaking and it doesn't respect the side_effects property in the package.json of tfjs_core that might cause this error. But we'd need greater insight into the bundling/loading process to see if it's a bug on our end.

**Comment by GantMan** [comment]
I've reached out to codesandbox - I'll see if I can get us some further info.

**Comment by CompuIves** [comment]
Hey all! Yep, this is definitely an issue with CodeSandbox, it seems like our transpiler has made the imports out of order, which causes `/core` to be loaded after the others. I'll look into a fix now.

**Comment by CompuIves** [comment]
Just merged it, it should be live within 30 min!

**Comment by GantMan** [comment]
This works with 2.4 and even the latest 2.5!   Great work!  Thanks so much @CompuIves for helping.  Codesandbox is my preferred tool for sharing, demonstrating, and updating TFJS codebases.

I'll close this ticket, as it seems it's 100% working!  🥳
