### ISSUE TITLE
TFJS converter mismanages EfficientDet models

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#3903]
None of the new EfficientDet saved models on TFHub can be used in TFJS.

Actual convert completes ok and creates `tfjs_graph_model`:  

`tensorflowjs_converter --input_format=tf_hub --output_format=tfjs_graph_model --signature_name="serving_default" https://tfhub.dev/tensorflow/efficientdet/d0/1 .`  

But when loading model with `tf.loadGraphModel`, it fails with  

`Cannot read property 'children' of undefined`  

Traced to function below where nodes[nodeName] ends up as undefined.

```js
class OperationMapper {
  ...
  mapFunction(functionDef) {
    ..
    const allNodes = Object.keys(nodes);
    allNodes.forEach(key => {
      const node = nodes[key];
      node.inputNames.forEach(name => {
        const [nodeName,] = getNodeNameAndIndex(name);
        node.inputs.push(nodes[nodeName]);
        nodes[nodeName].children.push(node);
      });
    });

```

Tried adding a null check for `node[nodeName]` there and then it loads model without errors,  
but it just fails later as it cannot recognize input on call to `executeAsync`  

`Cannot compute the outputs [Preprocessor/ResizeToRange/cond/resize/Squeeze] from the provided inputs [preprocessor_resizetorange_cond_resize_expanddims_preprocessor_unstack]. Consider providing the following inputs: [].`

Reproduction: Convert model from saved model using `tensorflowjs_converter` and try to load it using `tf.loadGraphModel`.

Environment: Ubuntu 20.04, Node 14.9.0, TFJS 2.3.0, Browser Chrome 85

**Comment by rthadur** [comment]
what model are you using ?

**Comment by vladmandic** [comment]
I don't understand - it's in the tensorflowjs_converter command line I've posted.  

But it's the same with all EfficientDet models on TFHub.

**Comment by rthadur** [comment]
Apologies , I see now , @pyu10055 @tafsiri do you guys know if we support `EfficientDet` models in TFJS ?

**Comment by vladmandic** [comment]
Btw, there's something weird with **EfficientDet** `saved_models` from <https://tfhub.dev/tensorflow/efficientdet/d0/1> since when I go to the source at <https://github.com/google/automl/tree/master/efficientdet>, download checkpoints and convert them to `saved_model`, I can then convert `saved_model` to `tf_graph_model` and load it in TFJS without issues.

Also, `saved_model` files created this way can be read without issues using `saved_model_cli` and `summarize_graph` while using same commands fails on `saved_models` from TFHub.

```text
# download checkpoint from <https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco2/efficientdet-d0.tar.gz>

# convert checkpoint to saved_model and frozen_model

python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=d0/ckpt --saved_model_dir=d0/saved --tensorrt=FP16

saved_model_cli show --dir=d0/saved
  The given SavedModel contains the following tag-sets: 'serve'

summarize_graph --in_graph="./d0/saved/efficientdet-d0_frozen.pb"
  Found 1 possible inputs: (name=image_files, type=string(7), shape=[?])
  Found 1 possible outputs: (name=detections, op=Pack)

# option#1: convert from saved_model to tfjs_graph_model

tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --strip_debug_ops=* --control_flow_v2=True d0/saved d0/graph
  Writing weight file d0/graph/model.json...

# option#2: convert from frozen_model to tfjs_graph_model

tensorflowjs_converter --input_format=tf_frozen_model --output_format=tfjs_graph_model --strip_debug_ops=* --control_flow_v2=True --output_node_names=detections d0/saved/efficientdet-d0_frozen.pb d0/graph-frozen
  Writing weight file d0/graph-frozen/model.json...
```

I still can't use the model since I'm now running into 

```
Error: the input tensors shape does not match
```
coming from `Pack` operation.
Which doesn't make much sense since I'm providing input in the shape of `[1, width, height, 3]` (as specified in model docs) and model expects input `[-1, -1, -1, -1]`.

**Comment by pyu10055** [comment]
@vladmandic Thank you for report the issue. We have identified the bug related to the model execution for TFHub conversion.
https://github.com/tensorflow/tfjs/pull/3917

For frozen model failure, your code show the model input is string, which is different from your image data input for the prediction.

**Comment by vladmandic** [comment]
Thanks!

I'll test it as soon as it's in master.

Btw, I've created a standalone Gist which tests 8 different variations/sources of the same `EfficientDet-D0` model using both `tfnode.node.loadSavedModel` to load `saved_model` and `tf.loadGraphModel` to load converted `tfjs_graph_model`:  
<https://gist.github.com/vladmandic/a7cf75109b7b48f8914a5b18da5c498f>

This fix should help with scenarios (4) and (5), but there seems to be an issue with 'int32' vs 'uint8' which cases failure on execution of a `saved_model`.

I've found your earlier fix at <https://github.com/tensorflow/tfjs/pull/2981/> which patches `tf-converter` by mapping `uint8` to `int32`, but:  
- Same is also needed in tfjs-node/saved_model:mapTFDtypeToJSDtype() (and possibly in other places)  
- During model execution, mode expects to receive `uint8`, but receives `int32` and fails with:  
  `error: Session fail to run with error: Expects arg[0] to be uint8 but int32 is provided`  
  So I'm not sure that simply mapping `uint8` to `int32` is a fix?

Also, on a separate note, why does `tensorflowjs_convert` mangle model signature?
This is not only for EfficientDet-D0 model, but pretty much all of converted models.

For example, output of `tfnode.node.getMetaGraphsFromSavedModel` for loaded `saved_model` is descriptive:

    inputs: { input_tensor: { dtype: 'uint8', name: 'serving_default_input_tensor:0', shape: [Array] } },
    outputs: {
      detection_anchor_indices: { dtype: 'float32', name: 'StatefulPartitionedCall:0', shape: [Array] },
      detection_boxes: { dtype: 'float32', name: 'StatefulPartitionedCall:1', shape: [Array] },
      detection_classes: { dtype: 'float32', name: 'StatefulPartitionedCall:2', shape: [Array] },
      detection_multiclass_scores: { dtype: 'float32', name: 'StatefulPartitionedCall:3', shape: [Array] },
      detection_scores: { dtype: 'float32', name: 'StatefulPartitionedCall:4', shape: [Array] },
      num_detections: { dtype: 'float32', name: 'StatefulPartitionedCall:5', shape: [Array] },
      raw_detection_boxes: { dtype: 'float32', name: 'StatefulPartitionedCall:6', shape: [Array] },
      raw_detection_scores: { dtype: 'float32', name: 'StatefulPartitionedCall:7', shape: [Array] }
    }

While output of `model.executor._signature` or `model.outputs` for loaded `tfjs_graph_model` is cryptic:

  inputs: { 'input_tensor:0': { name: 'input_tensor:0', dtype: 'DT_UINT8', tensorShape: { dim: [ { size: '1' }, { size: '-1' }, { size: '-1' }, { size: '3' }, [length]: 4 ] } } },
  outputs: {
    'Identity_4:0': { name: 'Identity_4:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '100' }, [length]: 2 ] } },
    'Identity_6:0': { name: 'Identity_6:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '49104' }, { size: '4' }, [length]: 3 ] } },
    'Identity_2:0': { name: 'Identity_2:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '100' }, [length]: 2 ] } },
    'Identity_7:0': { name: 'Identity_7:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '49104' }, { size: '90' }, [length]: 3 ] } },
    'Identity:0': { name: 'Identity:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '100' }, [length]: 2 ] } },
    'Identity_3:0': { name: 'Identity_3:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '100' }, { size: '90' }, [length]: 3 ] } },
    'Identity_1:0': { name: 'Identity_1:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, { size: '100' }, { size: '4' }, [length]: 3 ] } },
    'Identity_5:0': { name: 'Identity_5:0', dtype: 'DT_FLOAT', tensorShape: { dim: [ { size: '1' }, [length]: 1 ] } }
  }

I understand both `uint8` mapping and model signature names are separate issues from current one, do you want me to open separate issues for those?

**Comment by pyu10055** [comment]
yes, please open another issue, the int8 support is for node direct saved model execution. thanks.

**Comment by vladmandic** [comment]
I've created separate issues <https://github.com/tensorflow/tfjs/issues/3942> and <https://github.com/tensorflow/tfjs/issues/3930>.

As you've noted, work for core issue here is done under (still in progress) <https://github.com/tensorflow/tfjs/pull/3917>

**Comment by vladmandic** [comment]
possible code fix under <https://github.com/tensorflow/tfjs/pull/3917> is pending for a month - any updates?

**Comment by rthadur** [comment]
#3917 is merged , closing this issue.Thank you

**Comment by vladmandic** [comment]
@rthadur Please don't close the issue before it's confirmed as resolved.
in this case, #3917 has been superseeded by #4100 which will be merged into master soon.
and then it's not certain it fixes this issue - it needs to be verified.

**Comment by vladmandic** [comment]
now that <https://github.com/tensorflow/tfjs/pull/4100> is committed, i've tried it out and no luck  

fresh build from [master](https://github.com/tensorflow/tfjs/commit/cbaa09e5558f1eae6610704c2889222f9db4ea7b)  
tested with **node** (`tfjs-node`) and **browser** (`tfjs-backend-webgl`) environments - both **fail** exactly the same as in the original report   

```
TypeError: Cannot read property 'children' of undefined
    at operation_mapper.js:299
    at Array.forEach (<anonymous>)
    at operation_mapper.js:296
    at Array.forEach (<anonymous>)
    at OperationMapper.mapFunction (operation_mapper.js:294)
    at operation_mapper.js:129
    at Array.reduce (<anonymous>)
    at OperationMapper.transformGraph (operation_mapper.js:128)
    at GraphModel.loadSync (graph_model.js:123)
    at GraphModel.load (graph_model.js:105)
```

**Comment by vladmandic** [comment]
I've updated `tensorflowjs` pip packages and re-converted EfficientDet models using `tensorflowjs_convert --input_format tf_hub ...` and it seems that EfficientDet converted `saved_models` are now working.

There is another issue with CenterNet models, but I'll open a new issue for that.

I'm closing this issue.

**Comment by playground** [comment]
I'm running @tensorflow/tfjs-node v 3.7.0 and I'm still getting this error "**Cannot read property 'outputs' of undefined**" when tried to load model json that was converted from  saved model using tensorflowjs_converter.  
When I changed to @tensorflow/tfjs-node@next, it would throw "**Cannot read property 'children' of undefined**" 

```model = await tf.loadGraphModel(modelPath);```

node-pre-gyp info This Node instance does not support builds for Node-API version 8
node-pre-gyp info This Node instance does not support builds for Node-API version 8
2021-07-10 13:26:00.618147: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

TypeError: Cannot read property 'outputs' of undefined
    at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3851:31
    at Array.forEach (<anonymous>)
    at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3848:29
    at Array.forEach (<anonymous>)
    at OperationMapper.mapFunction (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3846:18)
    at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3679:56
    at Array.reduce (<anonymous>)
    at OperationMapper.transformGraph (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3678:48)
    at GraphModel.loadSync (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7763:68)
    at GraphModel.<anonymous> (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7737:52)
