### ISSUE TITLE
cannot load tfjs-backend-wasm on jsdelivr properly via importScripts.

### ISSUE THREAD

**Issue by y-ich** [tensorflow/tfjs#3908]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

Hi.
I tried loading tfjs-backend-wasm on jsdelivr via importScripts but failed.
tfjs-backend-wasm seems to load tfjs-backend-wasm-threaded-simd.wasm/tfjs-backend-wasm.wasm from a site's base address, not from jsdelivr.

I think that the below is a related issue.
https://github.com/emscripten-core/emscripten/issues/5104

Copying wasm files as the site resources solves this issue, but apparently it is not a good solution.
Are there any workarounds?

Thanks.

**Comment by rthadur** [comment]
@y-ich you need to specify the version from NPM

**Comment by annxingyuan** [comment]
Hi @y-ich - thanks for trying out the WASM backend. The tf-backend-wasm.js file will by default assume that the WASM binaries are located in the same directory. To override this behavior (e.g. if you're using the WASM backend with a bundler), please see this section of the README: https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm#using-bundlers

I think you should be able to resolve your issue by using `tf.wasm.setWasmPaths`.

**Comment by y-ich** [comment]
@rthadur san, @annxingyuan san, thank you for your advices!

    importScripts(
        "//cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.3.0/dist/tf.min.js",
        "//cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js"
    );
    tf.wasm.setWasmPaths("//cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/");

solved my issue.
(The last "/" of the path was very important^^)
