### ISSUE TITLE
when i use tensorflow-gpu 2.0.0, which tensorflowjs version should i use?

### ISSUE THREAD

**Issue by pedro-abundio-wang** [tensorflow/tfjs#3909]
I was used conda install tensorflow-gpu environment, and i saw the document of tensorflowjs, i use pip install tensorflowjs, but it's dependency package version not compatible the environment. 

And I try serveral version like pip install tensorfowjs==X.X.X, some version based on tensorflow 1.15.0 or tensorflow-cpu 2.3.0; no one match with tensorflow-gpu 2.0.0.

**Comment by rthadur** [comment]
please use the [template](https://github.com/tensorflow/tfjs/issues/new?labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md) to fill the steps and error you are getting .
