### ISSUE TITLE
Extend API DocGen to support exposing default values

### ISSUE THREAD

**Issue by ericdnielsen** [tensorflow/tfjs#391]
The existing DocGen scripts are unable to surface default values for most of the fields inside config object for TFJS-Layers.  

The DocGen script explodes the config object to list the possible arguments, and corrects marks the optional ones as optional.  However it has no way of exposing what the default value is for an optional field.

We don't think there's a simple refactoring to how we handle bags of parameters, so the solution is likely to be the extension of the documentation script to support a new feature that allows us to tag the default constant in the config-interface consuming class with what fields its a default for.

Ie. in tfjs-layers/src/layers/convolutional.ts
 @doc(defaultFor='config.kernalInitializer') // Add this line and add support for processing it to the scripts
 readonly DEFAULT_KERNEL_INITIALIZER: InitializerIdentifier = 'glorotNormal';

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
