### ISSUE TITLE
toxicity model always returns the same values in React Native

### ISSUE THREAD

**Issue by wtrevena** [tensorflow/tfjs#3911]
#### TensorFlow.js version
![image](https://user-images.githubusercontent.com/55459400/92987830-22899300-f494-11ea-8ac9-4f51eb3037da.png)

#### Describe the problem or feature request
Regardless of the string I input into the toxicity model, I receive the same probabilities for each result (identity_attack, obscene, etc.) as shown in the screenshot below. I am calling this using the code below. 

One thing to note: I am running this on an expo-managed app, but one of the dependencies of tfjs-react-native is react-native-fs which would normally be replaced by expo-file-system in my implementation. To satisfy the dependency requirement I installed react-native-fs anyways, but I am not sure if should matter as I am not trying to import any custom models from memory using tfjs-react-native.

#### Code to reproduce the bug / link to feature request
```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';
var toxicity = require('@tensorflow-models/toxicity');
```
And I am calling the code in this way
```
async componentDidMount () { 
  await tf.setBackend('rn-webgl')
  await tf.ready();
  console.log("tf is ready!!!")
  // Load the model. Users optionally pass in a threshold and an array of
  // labels to include.
  await toxicity.load(0.9)
    .then(async(model) => {
      await model.classify(['you suck','I love you'])
        .then(async(predictions) => {

            await console.log(predictions);

            // `predictions` is an array of objects, one for each prediction head,
            // that contains the raw probabilities for each input along with the
            // final prediction in `match` (either `true` or `false`).
            // If neither prediction exceeds the threshold, `match` is `null`.
        
        });
  });
}
```

Printing in predictions:

![image](https://user-images.githubusercontent.com/55459400/92987947-3c77a580-f495-11ea-99ef-d36e693d24ad.png)
![image](https://user-images.githubusercontent.com/55459400/92987938-29fd6c00-f495-11ea-8a4c-9551dc2e2e1d.png)
![image](https://user-images.githubusercontent.com/55459400/92987927-1b16b980-f495-11ea-9fb8-069fc15b9f4f.png)

As seen in the output above, the toxicity model is returning the same probabilities regardless of the strings inputted. I also tried this with a variety of other very kind and very toxic strings which all resulted in the same output.

Any help addressing this issue would be greatly appreciated.

**Comment by dhooper21** [comment]
I am having the same issue as well - regardless of the strings inputted, the model continues to return the same probabilities

**Comment by tafsiri** [comment]
Hi, I wasn't able to reproduce this, could you provide more device information. Another thing to try for debugging this is tf.setBackend('cpu').

I tried to [reproduce this here](https://github.com/tafsiri/tfjs-expo-managed-example/tree/toxicity-model), feel free to download that repo and try it out yourself (make sure to switch to the 'toxicity-model' branch.

This is the output I got for `model.classify(['you suck','I love you'])`
```
model output len 7
Label identity_attack
Results Array [
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9659663438796997,
      0.03403365984559059,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.999956488609314,
      0.000043553249270189553,
    ],
  },
]
Label insult
Results Array [
  Object {
    "match": true,
    "probabilities": Float32Array [
      0.08124707639217377,
      0.918752908706665,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9995761513710022,
      0.00042380779632367194,
    ],
  },
]
Label obscene
Results Array [
  Object {
    "match": null,
    "probabilities": Float32Array [
      0.39931538701057434,
      0.6006845831871033,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9999582767486572,
      0.000041756517020985484,
    ],
  },
]
Label severe_toxicity
Results Array [
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9970395565032959,
      0.002960433252155781,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      1,
      4.12830054585811e-8,
    ],
  },
]
Label sexual_explicit
Results Array [
  Object {
    "match": null,
    "probabilities": Float32Array [
      0.7053250670433044,
      0.29467496275901794,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9999380111694336,
      0.0000619467900833115,
    ],
  },
]
Label threat
Results Array [
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9106739163398743,
      0.08932609856128693,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9998704195022583,
      0.00012954739213455468,
    ],
  },
]
Label toxicity
Results Array [
  Object {
    "match": true,
    "probabilities": Float32Array [
      0.031176727265119553,
      0.9688233137130737,
    ],
  },
  Object {
    "match": false,
    "probabilities": Float32Array [
      0.9989683628082275,
      0.00103162438608706,
    ],
  },
]
```
