### ISSUE TITLE
Crop detected faces from Blaze face model based on facial landmarks. 

### ISSUE THREAD

**Issue by yudhiesh1997** [tensorflow/tfjs#3914]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Currently there isn't any builtin method to crop an image based on specific coordinates such as when usin ng Blaze Face Model and cropping the detected faces to be passed to another model. 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone who needs to detect certain elements in an input then pass them over to another model 

**Any Other info.**

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by annxingyuan** [comment]
Hi @yudhiesh1997 - if I'm understanding your issue correctly, I think you could achieve this with `tf.image.cropAndResize`, using the bounding box returned by blazeface.

**Comment by yudhiesh1997** [comment]
> Hi @yudhiesh1997 - if I'm understanding your issue correctly, I think you could achieve this with `tf.image.cropAndResize`, using the bounding box returned by blazeface.

Hi apologies I forgot to update the thread. I managed to do it myself with the method you suggested. 
```
            faces.map((face, i) => {
                const { topLeft, bottomRight } = face;
                // Boxes in cropAndResize require to be normalized
                const normTopLeft = topLeft.div(tensor.shape.slice(-3, -2));
                const normBottomRight = bottomRight.div(
                    tensor.shape.slice(-3, -2)
                );
                const width = Math.floor(
                    bottomRight.dataSync()[0] -
                        topLeft.dataSync()[0] * scale.width
                );
                const height = Math.floor(
                    bottomRight.dataSync()[1] -
                        topLeft.dataSync()[1] * scale.height
                );
                const boxes = tf
                    .concat([
                        normTopLeft.dataSync(),
                        normBottomRight.dataSync()
                    ])
                    .reshape([-1, 4]);
                const crop = tf.image.cropAndResize(
                    tensor.reshape([1, 224, 224, 3]),
                    boxes,
                    [0],
                    [height, width]
                );
```

**Comment by fernandonjardim** [comment]
Hi there !

This is my first post on stackoverflow, so I hope I am doing everything right :D

I got a similar issue, when I tried to adapt the code above and use it, I got the message: 

**"Uncaught (in promise) TypeError: topLeft.div is not a function"**

By any chance,  do you know why?


```
const detectFaces = async () => {
  const prediction = await model.estimateFaces(video, false);

  console.log(prediction);

  ctx.drawImage(video, 0, 0, 600, 400);

  prediction.forEach((pred) => {
    
    ctx.beginPath();
    ctx.lineWidth = "4";
    ctx.strokeStyle = "blue";

    ctx.rect(
      pred.topLeft[0],
      pred.topLeft[1],
      pred.bottomRight[0] - pred.topLeft[0],
      pred.bottomRight[1] - pred.topLeft[1]
    );
    ctx.stroke();
       
    });

    prediction.map((face, i) => {
      const tensor = tf.browser.fromPixels(video)

      const { topLeft, bottomRight } = face;
      // Boxes in cropAndResize require to be normalized
      console.log("topLeft", topLeft)
      console.log("tensor", tensor)
      const normTopLeft = topLeft.div(tensor.shape.slice(-3, -2));
      const normBottomRight = bottomRight.div(
          tensor.shape.slice(-3, -2)
      );
      const width = Math.floor(
          bottomRight.dataSync()[0] -
              topLeft.dataSync()[0] * scale.width
      );
      const height = Math.floor(
          bottomRight.dataSync()[1] -
              topLeft.dataSync()[1] * scale.height
      );
      const boxes = tf
          .concat([
              normTopLeft.dataSync(),
              normBottomRight.dataSync()
          ])
          .reshape([-1, 4]);
      const crop = tf.image.cropAndResize(
          tensor.reshape([1, 224, 224, 3]),
          boxes,
          [0],
          [height, width],
      );
    });
};
```
