### ISSUE TITLE
Runing posenet camera feed demo on Windows is not getting images from camera

### ISSUE THREAD

**Issue by rafalfirlejczyk** [tensorflow/tfjs#392]
#### I tried to run the demo on Windows7/64. First I adopted the package.json to Windows (changes seen as bold):
"scripts": {
    "watch": "**SET** NODE_ENV=development **&** parcel --no-hmr --open index.html ",
    "build": "**SET** NODE_ENV=production **&** parcel build index.html  --no-minify --public-url ./",
    "build-camera": "**SET** NODE_ENV=production **&** parcel build camera.html  --no-minify --public-url ./",
    "lint": "eslint ."
  },

I was able to run the command _yarn watch_ and _yarn build_ or _yarn build-camera_

When I start the the browser it asks to allow using the camera.
However no image from the camera is displayed in the browser

![image](https://user-images.githubusercontent.com/2536392/40995123-7fd9b48c-68fe-11e8-94f9-1af029c32a4a.png)

**Comment by stefanosky** [comment]
wow you arrived till here!
Hi, have you faced with this issue?
![image](https://user-images.githubusercontent.com/22086710/41003380-e913c25e-6916-11e8-9818-3f762f090f70.png)
https://github.com/llSourcell/pose_estimation/issues/1

**Comment by stefanosky** [comment]
Ok I arrived at your point.
open log console, in mine i read -->   Uncaught (in promise) TypeError: Cannot read property 'drawImage' of null

**Comment by rafalfirlejczyk** [comment]
thank you Stefano. In my case the browser gets the error:
_**Uncaught (in promise) TypeError: Cannot read property 'drawImage' of null**_

![image](https://user-images.githubusercontent.com/2536392/41016505-04ae0cde-6950-11e8-8854-8904ec3682f0.png)

The same issue was seen in #349 and it was fixed by upgrading to tfjs 0.11.4. I will try to upgrade and check if it works for Windows

**Comment by rafalfirlejczyk** [comment]
It works on Windows7/64 in Chrome Browser with the tfjs 0.11.4.
In the file **_demos/package.json_** I changed the version of tfjs to 0.11.4
_**"@tensorflow/tfjs": "0.11.4",**_
Then from demos directory I ran
**_yarn_**
and
**_yarn watch_**
