### ISSUE TITLE
localStorage and indexeddb saves do not work

### ISSUE THREAD

**Issue by kentonpowell** [tensorflow/tfjs#3924]
**System information**
- 2.3.0, Chrome 85 and Safari 13, 10.15

**Describe the current behavior**
- Unable to save models with localStorage or indexeddb. Throws error **Cannot find any save handlers for URL.** File-based downloads — **model.save('downloads://model')** — do work.

**Describe the expected behavior**
- A successful save

**Standalone code to reproduce the issue**
- https://js.tensorflow.org/api/latest/#tf.LayersModel.save

**Comment by rthadur** [comment]
@tafsiri I was able to reproduce the error

**Comment by tafsiri** [comment]
Hi, we just released tfjs 2.4.0 could you try it with that version? Thanks.

**Comment by rthadur** [comment]
@tafsiri latest version in https://js.tensorflow.org/api/2.3.0/ is still 2.3.0 , do you know if we need to update this ?

**Comment by tafsiri** [comment]
yep i'm in the process of doing that.

**Comment by kentonpowell** [comment]
Works in 2.4.0. Thank you!
