### ISSUE TITLE
Possible Bug Tensorflowjs_converter Quantization Command Line Example

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#3925]
Can someone check this bug it might be specific to my models. I am using TFJS version 2.3 with a fresh install of ```          pip install tensorflowjs ```

 I used The Quantization example at https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#converting-tfjs_layers_model-to-tfjs_layers_model-with-weight-sharding-and-quantization  

```
tensorflowjs_converter \
   --input_format tfjs_layers_model \
   --output_format tfjs_layers_model \
   --quantize_uint16 \
   original_model/model.json
   quantized_model/
```

It does not seem to work unless ```--output_node_names``` is included with a comma separated list, for example:

```
tensorflowjs_converter  \
--input_format tfjs_layers_model \
--output_format tfjs_layers_model \
--quantize_uint16  \
--output_node_names logits,Bias \
./model.json \
./quantized_model

```

Can someone test if this is a bug?

**Comment by rthadur** [comment]
@hpssjellis is it possible to share your model ?

**Comment by hpssjellis** [comment]
> @hpssjellis is it possible to share your model ?

[tfjs-models](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/m09-Tensoflow/tfjs-modelsl) I can put more but try this one first. Thanks for looking at this @rthadur I can put more models there if needed.

**Comment by rthadur** [comment]
@hpssjellis can not access the path ?

**Comment by hpssjellis** [comment]
I updated above or use this. Not sure what happened @rthadur  

[https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/m09-Tensoflow/tfjs-models](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/m09-Tensoflow/tfjs-models)

**Comment by hpssjellis** [comment]
@pyu10055 Hi Ping. Do you want some clarification of the problem?

**Comment by pyu10055** [comment]
@hpssjellis This looks like argparser issue, if you use following command it should work:

```bash
tensorflowjs_converter \
   --quantize_uint16 \
   --input_format tfjs_layers_model \
   --output_format tfjs_layers_model \
   original_model/model.json
   quantized_model/
```

basically, when the quantize_uint16 params is defined with nargs='?', means it can have an empty value, somehow when it is placed at the end, the argsparser thinks the input_path is its param.
you can also do:
```bash
tensorflowjs_converter \
   --input_format tfjs_layers_model \
   --output_format tfjs_layers_model \
   --quantize_uint16=* \
   original_model/model.json
   quantized_model/
```

**Comment by hpssjellis** [comment]
Thanks @pyu10055 that works fine, so it basically was my bad luck that let me find that bug. One minor issue is your code would not compile for me without the backslash on the second to last line.

```
tensorflowjs_converter \
   --input_format tfjs_layers_model \
   --output_format tfjs_layers_model \
   --quantize_uint16=* \
   original_model/model.json \
   quantized_model/

```

We can close this issue, I can send a PR if you want to [the tfjs-converter README.md file ](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#converting-tfjs_layers_model-to-tfjs_layers_model-with-weight-sharding-and-quantization). I would just move --quantize_uint16=* to the second row.
