### ISSUE TITLE
Handpose with react native

### ISSUE THREAD

**Issue by Laksh05** [tensorflow/tfjs#3928]
Hi @tafsiri
Hope you are doing good. 
I am stuck with similar issue. I am trying this in react native. 
let predictions = await model.estimateHands(nextImageTensor)
It gets stuck in this line.

currently using "@tensorflow-models/handpose": "0.0.6" but tried with "@tensorflow-models/handpose": "0.0.4" also. getting same issue.

_Originally posted by @Laksh05 in https://github.com/tensorflow/tfjs/issues/2906#issuecomment-692252955_

**Comment by tafsiri** [comment]
@Laksh05 could you fill out the issue template to provide more information.

**Comment by Laksh05** [comment]
@tafsiri Issue template? Can you please share link.

**Comment by rthadur** [comment]
here is the link https://github.com/tensorflow/tfjs/issues/new/choose , thank you

**Comment by jayanthsaikiran** [comment]
@Laksh05 Hi, Can you please help me use handpose in react native? I couldn't link it with expo-camera.
