### ISSUE TITLE
Handpose model not detecting landmarks when using the 'wasm' backend

### ISSUE THREAD

**Issue by sanchit-gupta-cn** [tensorflow/tfjs#3929]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**
- TensorFlow.js installed from (npm or script link): **yarn**
- TensorFlow.js version (use command below): **2.3.0**
- Browser version: **NA**
- Node version: **14.9.0**
- Tensorflow.js Converter Version: **2.3.0**

**Describe the current behavior**

I am trying to run the tfjs handpose example described in this README https://github.com/tensorflow/tfjs-models/tree/master/handpose#usage. The only difference being, I'm executing the code using **node v14.9.0** and not in a browser. 

The code runs as expected for a sample image when using a `@tensorflow/tfjs-backend-cpu` backend. Unfortunately,  `@tensorflow/tfjs-backend-wasm` returns no predictions. And since `wasm` backend has better performance than the `cpu` one, I would like to use it if possible.

This is [the image](https://drive.google.com/file/d/1I6VwMqMhjEsjI0abz533HGJLFd3HkMfm/view?usp=sharing) that I'm trying to get predictions on.

**Describe the expected behavior**

The `@tensorflow/tfjs-backend-wasm` backend should return similar predictions as returned by the `@tensorflow/tfjs-backend-cpu`.

**Standalone code to reproduce the issue**
```javascript
const handpose = require('@tensorflow-models/handpose'),
    tf = require('@tensorflow/tfjs-core'),
    pixels = require('image-pixels');

require("@tensorflow/tfjs-backend-cpu");
require("@tensorflow/tfjs-backend-wasm");

async function main() {
    
    await tf.setBackend('wasm');
    const img = await pixels('image.png');
    const model = await handpose.load();
  
    const predictions = await model.estimateHands(img);
    console.log(predictions);
}

main();
```
`image.png` on line 11 refers to [this image](https://drive.google.com/file/d/1I6VwMqMhjEsjI0abz533HGJLFd3HkMfm/view?usp=sharing).

**Other info / logs** 

This issue happens only for certain images and not all. For example, in the case of [this image](https://drive.google.com/file/d/1VwcAKT7L6aaFXxieW7GP4UnUChWh99fX/view?usp=sharing), the `wasm` backend returns the correct predictions.

**Comment by rthadur** [comment]
@sanchit-gupta-cn can you please check this comment [here](https://github.com/tensorflow/tfjs/issues/3883#issuecomment-692669400)
