### ISSUE TITLE
Creating a rollup.config.js that does not treat tfjs as an external results in some errors

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#393]
I'm working on converting [ml5.js](https://github.com/ml5js/ml5-library) to use rollup.  As it is a library aimed at beginners, we wan't someone to just be able to drop the ml5.js script on the page and it will include @tensorflow/tfjs in the bundle.  As ml5 is not built in typescript and uses es7 features, it uses babel.

When trying to build with rollup in this way, a bunch of errors occur.  As these build systems seem to change often, I get a bit lost with how to properly set it up.  Maybe @mbostock can help.

Here is the rollup.config.js:

```javascript
import node from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'src/index.js',
  plugins: [
    babel({
      plugins: ["external-helpers"]
    }),
    node(),
    commonjs()
  ],
  output: {
    file: 'dist/ml5.js',
    format: 'umd',
    name: 'ml5' 
  }
};
```

The .babelrc
```json
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

When building with rollup, a few errors occur:

> preferring built-in module 'url' over local alternative at '/Users/danoved/Source/opensource/ml5-library/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

> (!) Missing shims for Node.js built-ins
> Creating a browser bundle that depends on 'url'. You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins

> (!) Unresolved dependencies
> https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
> url (imported by node_modules/@tensorflow/tfjs-converter/dist-es6/executor/frozen_model.js)

> (!) Missing exports
> https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
> node_modules/@tensorflow/tfjs-core/dist-es6/kernels/backend_cpu.js
> alea is not exported by node_modules/seedrandom/index.js
> 1611:                 cdf[event_1] = cdf[event_1 - 1] + probVals[offset + event_1];
> 1612:             }
> 1613:             var random = seedrandom.alea(seed.toString());
>                                           ^
> 1614:             var outOffset = b * numSamples;
> 1615:             for (var sampleId = 0; sampleId < numSamples; ++sampleId) {

And then there are a bunch of circular dependency warnings (just pasting the first few):

> (!) Circular dependency: node_modules/@tensorflow/tfjs-core/dist-es6/environment.js -> node_modules/@tensorflow/tfjs-core/dist-es6/engine.js -> node_modules/@tensorflow/tfjs-core/dist-es6/environment.js
> (!) Circular dependency: node_modules/@tensorflow/tfjs-core/dist-es6/environment.js -> node_modules/@tensorflow/tfjs-core/dist-es6/engine.js -> node_modules/@tensorflow/tfjs-core/dist-es6/globals.js -> node_modules/@tensorflow/tfjs-core/dist-es6/gradients.js -> node_modules/@tensorflow/tfjs-core/dist-es6/environment.js
> (!) Circular dependency: node_modules/@tensorflow/tfjs-core/dist-es6/globals.js -> node_modules/@tensorflow/tfjs-core/dist-es6/gradients.js -> node_modules/@tensorflow/tfjs-core/dist-es6/globals.js

If I switch rollup to treat tfjs as an external, the errors go away.

Any suggestion for how to properly setup the rollup.config ?

**Comment by oveddan** [comment]
Another thought I had was to fist build the ml5.js as a standalone, then have some post-build step that creates a bundle of tfjs and ml5.js concattenated into a single file.

**Comment by nsthorat** [comment]
@oveddan did you get this resolved?
