### ISSUE TITLE
tf-core depends on a node-fetch with vulnerabilities

### ISSUE THREAD

**Issue by hfiguiere** [tensorflow/tfjs#3931]
`tf-core` depends on a `node-fetch` packages with vulnerabilities: `~2.1.2`

Details in https://www.npmjs.com/advisories/1556

Because it is a `~` dependency, `npm update` doesn't update `node-fetch` to `2.6.1` which is the version that fix the vulnerability described in the advisory.

This matters as `npm audit` complains about it for projects that uses `tf-core`

**Comment by rthadur** [comment]
Related PR has been merged , Thank you

**Comment by Den-dp** [comment]
Any plans to release it?

**Comment by adriangodong** [comment]
For reference, this was released in [2.5.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v2.5.0).
