### ISSUE TITLE
TensorCamera does not automatically handle camera input

### ISSUE THREAD

**Issue by yudhiesh1997** [tensorflow/tfjs#3933]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
    "@tensorflow/tfjs": "^2.0.0",
    "@tensorflow/tfjs-backend-webgl": "2.0.0",
    "@tensorflow/tfjs-converter": "^1.5.2",
    "@tensorflow/tfjs-core": "2.0.0",
    "@tensorflow/tfjs-react-native": "^0.3.0",
    "expo": "~38.0.8",
    "expo-camera": "~8.3.1",

**Describe the current behavior**
TensorCamera does not make predictions on tensors that are passed in unless I resave my code even when both models are loaded

**Describe the expected behavior**
TensorCamera should be making predictions once the model is loaded

**Standalone code to reproduce the issue**
```
  useEffect(() => {
    (async () => {
      try {
        const { status } = await Camera.requestPermissionsAsync().catch(e =>
          console.log(e)
        );
        if (Platform.OS == "ios") {
          setTextureDims({ height: 1920, width: 1080 });
        } else {
          setTextureDims({ height: 1200, width: 1600 });
        }
        setHasPermission(status === "granted");
        await tf.ready().catch(e => console.log(e));
        setTFReady(true);
        setModelLoaded(await loadModel());
        setBlazeFaceModel(
          await loadBlazeFaceModel().catch(e => console.log(e))
        );
      } catch (e) {
        console.log("Error in 1st useEffect()");
      }
    })();
  }, []);

  const handleCameraStream = imageAsTensors => {
    const verbose = true;
    //console.log("Tensor input 1");
    if (!imageAsTensors) {
      console.log("Image not found!");
      return;
    }
    const loop = async () => {
      if (loadedModel !== null && blazeFaceModel !== null) {
        if (frameCount % makePredictionsEveryNFrames === 0) {
          const imageTensor = imageAsTensors.next().value;
          await getPrediction(imageTensor).catch(e => console.log(e));
          tf.dispose(imageAsTensors);
        }
      }

      frameCount += 1;
      frameCount = frameCount % makePredictionsEveryNFrames;
      requestAnimationFrameId = requestAnimationFrame(loop);
    };
    //loop infinitely to constantly make predictions
    loop();
  };

      <TensorCamera
        style={styles.camera}
        type={type}
        zoom={0}
        cameraTextureHeight={textureDimsState.height}
        cameraTextureWidth={textureDimsState.width}
        resizeHeight={tensorDims.height}
        resizeWidth={tensorDims.width}
        resizeDepth={tensorDims.depth}
        onReady={images => handleCameraStream(images)}
        autorender={AUTORENDER}
      />

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tafsiri** [comment]
So what actually gets output before the refresh? Are there any error messages? Also this isn't really stand-alone code, I can't just paste somewhere have it to work (e.g. what is setTFReady). Could you make a repo that I can download and try

**Comment by yudhiesh1997** [comment]
There aren't any error messages. Apologies for that here is a link to the [repository](https://github.com/yudhiesh1997/Driver-Drowsiness-App/blob/master/screens/CameraView.js). My handleCameraInput() only works when I resave the code.

**Comment by tafsiri** [comment]
I took a look at your code and there wasn't anything that immediately stood out to me as being incorrect. I'm guessing this is probably related to how you set up state and do initialization. This is probably more related to react lifecycle and your dev environment so I don't think I can help unless you can point more specifically to a bug with the tensorflow part of things (the fact that it works on re-save suggests its not really a tensorflow.js bug).

I'd suggest you trace what is going on on initial load and figure out which promises aren't resolving to allow the rest of your program to continue.
