### ISSUE TITLE
[Question] How to best time-profile a TFJS workflow?

### ISSUE THREAD

**Issue by sacredvoid** [tensorflow/tfjs#3941]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

### Question Description

Hey, I have a TFJS webapp that takes in frames from a Video, does some pre-processing, passes it into a TFJS Model (converted from a TF Frozen Model), post-processes output and renders that back to a canvas using custom code written in WebGL. <br> I am unable to get proper timing splits between Preprocessing (which includes fromPixels), Model Inference Time and Post Processing. 
Here are the things that I tried to time the application:
- console.time
- performance.now
- tf.Profile (which gives kernelTimeMs)

None of the above methods gave representative numbers. One thing I noticed is that the Datasync (downloading/uploading of buffers to and from GPU, correct me if I am wrong) call is taking about 90% of the time as compared to the Kernel Operations. I've read in some of the issues that the execute function just assembles/prepares the Kernel according to the TF graph along with the weights and doesn't actually execute them until a Datasync operation is called? Does this lead to the timing discrepancy that I'm noticing? 

Kindly help me clarify, thank you!

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by sacredvoid** [comment]
Hey, I noticed a lot of timing discrepancy in the [TFJS Benchmarking Tool](https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html) while testing my custom models as well as the ones provided in the list.

The aggregate kernel-wise timings don't add up. They always exceeded in the case of 'USE - Batch Size 30' (but still relatively close to the Average Inference Time over 50 runs) and they are always very low compared to the Average for the 'USE - Batch Size 1' model. I thought it was to do with the batch size, so tested all the listed models which had batch size 1, and indeed they all had timing discrepancies => Aggregate Kernel-wise timings didn't add up to the average inference time. 

Can you tell me what could be happening? When I used to test using the same tool (about 2 months back) the timings always added up (or very close to the average) which is not happening now.

**Comment by sacredvoid** [comment]
Hey, any leads as to why this is happening?

**Comment by lina128** [comment]
Hi @sacredvoid, the numbers in the kernel-wise timings don't add up because they run in debugMode, which is much slower. But the ratio between these kernel-wise timings hold. So if you use the model inference time multiply by the ratio, you will get the actual time spent for the kernel. Regarding GPU downloading and uploading time, when kernel code finishes, it doesn't know whether computation is done on GPU. When trying to downloading data from GPU, it will wait till data is ready and download it. So when you benchmark, record the time after data sync, which will reflect the actual time taken to compute.

**Comment by sacredvoid** [comment]
> So if you use the model inference time multiply by the ratio, you will get the actual time spent for the kernel

Attaching a PDF to Facedetector Kernel Timings (which don't add up). Can you tell me with the help of the benchmark below of what you meant by multiplying with ratio?
[issue_benchmark.pdf](https://github.com/tensorflow/tfjs/files/5284356/issue_benchmark.pdf)

> when kernel code finishes

This means when it's done compiling the webgl kernel for that operation? So it doesn't actually do the computation till after a datasync is called?

**Comment by lina128** [comment]
So you add up all the time in the kernel time(ms) column. Then for each row, you take the kernel time and divided by the total time. That is the ratio, then multiply by the inference time, for example the 19ms average time, then you get the actual time the kernel takes to run.

For the kernel code finishes, yes I mean it's done executing the kernel. It starts the computation, but doesn't guarantee the computation finishes. datasync guarantees it.

**Comment by sacredvoid** [comment]
Thanks a lot for the clarification! 👍
