### ISSUE TITLE
tfjs handpose not as accurate as mediapipe handpose web demo

### ISSUE THREAD

**Issue by no-1ne** [tensorflow/tfjs#3943]
Hello Folks, 
When trying out handpose, it seems the tfjs version isnt performing as good as mediapipe web version. Can you kindly take a look.
https://viz.mediapipe.dev/demo/hand_tracking
https://storage.googleapis.com/tfjs-models/demos/handpose/index.html
![Screenshot from 2020-09-18 07-54-24](https://user-images.githubusercontent.com/11027129/93548228-73155a80-f984-11ea-80f8-c9cbdb63f859.png)
![Screenshot from 2020-09-18 07-54-10](https://user-images.githubusercontent.com/11027129/93548233-74df1e00-f984-11ea-9f19-a7cefa39ece5.png)

**Comment by rthadur** [comment]
@startupgurukul i don't see any difference in hand pose, what exactly you are referring to ?

**Comment by startupgurukul** [comment]
If you open the two links in two tabs, show the  hand & switch tabs you will see significant changes in performance as shared in the screenshots above espl with fingertips and thumb

**Comment by rthadur** [comment]
![image](https://user-images.githubusercontent.com/43972606/93831067-b7c02080-fc26-11ea-9587-79d931d202c0.png)

I got above results cc @annxingyuan

**Comment by startupgurukul** [comment]
![ezgif-3-24660204391c](https://user-images.githubusercontent.com/11027129/93835124-d90f2400-fc9b-11ea-95d9-61dd5707a555.gif)


Pls notice the finger tips,

**Comment by MiroslavPetrik** [comment]
@no-1ne there [is a newer model from 2021 ](https://blog.tensorflow.org/2021/11/3D-handpose.html)

The old (imprecise) npm package is `@tensorflow-models/handpose`

the new (more precise) npm package is `@tensorflow-models/hand-pose-detection`

**Comment by rthadur** [comment]
@MiroslavPetrik you were right . old npm package is deprecated and please use latest hand-pose-detection model here 
https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection
