### ISSUE TITLE
WASM backend should support matMul for non-float32 tensors.  

### ISSUE THREAD

**Issue by dennis508** [tensorflow/tfjs#3947]
Using WASM with BodyPix:
Error: BatchMatMul for non non-float32 tensors not yet supported.

**System information**
Kubuntu 18.04
npm install @tensorflow/tfjs-core@latest
npm install @tensorflow/tfjs-converter@latest
npm install @tensorflow-models/body-pix@latest
npm install @tensorflow/tfjs-backend-wasm@latest

@tensorflow-models/body-pix@2.0.5
@tensorflow/tfjs-backend-wasm@2.4.0
electron@10.1.2
npm -v 6.14.8
node -v v14.11.0

UNMET PEER DEPENDENCY @tensorflow/tfjs-converter@2.4.0
UNMET PEER DEPENDENCY @tensorflow/tfjs-core@2.4.0
npm ERR! peer dep missing: @tensorflow/tfjs-converter@^1.3.1, required by @tensorflow-models/body-pix@2.0.5
npm ERR! peer dep missing: @tensorflow/tfjs-core@^1.3.1, required by @tensorflow-models/body-pix@2.0.5

**Describe the current behavior**

WebGL works but WASM fails with above error.

**Standalone code to reproduce the issue** (excerpts)
const tf = require('@tensorflow/tfjs-core');
require('@tensorflow/tfjs-backend-wasm');
const bodyPix = require('@tensorflow-models/body-pix');

const architecture = 'MobileNetV1';
const outputStride = 16;
const multiplier = 0.5;
const quantBytes = 4;

tf.setBackend('wasm');
myNet = await bodyPix.load({ architecture, multiplier, outputStride, quantBytes });

await this.loadImage(filePath);
await performSegmentation(myImage);

**Comment by dennis508** [comment]
Can anyone explain what is happening here?

If this is truly missing code, is there a schedule for implementation?

Elsewhere on the site, I see benchmarks for BodyPix and WASM.
Is there a way to command BodyPix to use Float32?
Am I missing a library?

 If this is my error, what might I be doing wrong? Thank you. Thank you. Thank you.

**Comment by rthadur** [comment]
@dennis508 WASM is not supported for bodypix as it is not light weighted , please check this comment [here](https://github.com/tensorflow/tfjs/issues/2723#issuecomment-593538641)

**Comment by dennis508** [comment]
Hello Rajeshwar,

Thank you for this information. In particular, "WASM will likely not help here, since the WASM backend is 3-4X slower than the WebGL backend for "medium-sized" models like BodyPix, PoseNet and MobileNet."

However, shouldn't it be supported? The documentation implies that backends are interchangeable. 

https://www.tensorflow.org/js/guide/platform_environment says "TensorFlow.js provides a WebAssembly backend (wasm), which offers CPU acceleration and can be used as an alternative to the vanilla JavaScript CPU (cpu) and WebGL accelerated (webgl) backends." and "These results will vary depending on your device. The best way to determine whether WASM is right for your application is to test it on our different backends."

So, yes, WASM may be 3-4x slower than webgl but it's also 15x faster than the cpu backend. And https://www.w3.org/2020/06/machine-learning-workshop/talks/fast_client_side_ml_with_tensorflow_js.html says "But WebAssembly is steadily closing the performance gap with WebGL for larger models as well."

I was looking at WASM for more reliability than webgl and more speed than cpu. In particular the texture size error from webgl is driving me crazy and there doesn't seem to be a fix. See https://github.com/tensorflow/tfjs/issues/2940. That one and other errors keep popping up. Again from the workshop talk, "Despite these measures, memory management remains a source of error in our WebGL backend."

So, I appeal to you to support WASM with BodyPix and let application developers decide what's best. Thank you.

**Comment by rthadur** [comment]
cc @annxingyuan @dsmilkov

**Comment by annxingyuan** [comment]
Hi @dennis508 - you're right it looks like there is a [postprocessing step](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/decode_part_map.ts#L103) in the bodyPix model that multiplies two int tensors together. We had collected benchmarks for the model inference alone, which is why we claimed WASM support. 

I've updated the name of the ticket to reflect the underlying issue. Thanks so much for reporting this - I've added this to our backlog and we will try to address it soon!

**Comment by dennis508** [comment]
Thank you, Ann.

**Comment by rthadur** [comment]
We will not be updating body-pix , there is a new body segmentation model here https://blog.tensorflow.org/2022/01/body-segmentation.html , did you get chance to check this out? Thank you

**Comment by dennis508** [comment]
Thanks for the info.

    On Thursday, April 28, 2022, 12:21:49 PM EDT, Rajeshwar Reddy T ***@***.***> wrote:  
 
 


We will not be updating body-pix , there is a new body segmentation model here https://blog.tensorflow.org/2022/01/body-segmentation.html , did you get chance to check this out? Thank you
