### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by liquidx** [tensorflow/tfjs#3948]
In section 7, in the Show Confusion Matrix section:
https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#6

It uses:
tfvis.render.confusionMatrix(
      container, {values: confusionMatrix}, classNames);

But the API seems to have changed to
tfvis.render.confusionMatrix(container, {values: confusionMatrix, tickLabels: classNames})

**Comment by tafsiri** [comment]
Thanks for reporting this @liquidx! Codelab has been updated with the fix.
