### ISSUE TITLE
using tfjs in node js cause error. 

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tfjs#3949]
hello I'm doing tensorflow js following 
https://www.youtube.com/watch?v=EoYfa6mYOG4&t=2221s

but 

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.7"></script>

with above, 
it cause below error in 
`model = await tf.loadModel("images/VGG16/model.json");`
```

Uncaught (in promise) Error: Unknown layer: Functional
    at new t (tfjs@0.11.7:2)
    at deserializeKerasObject (tfjs@0.11.7:2)
    at deserialize (tfjs@0.11.7:2)
    at tfjs@0.11.7:2
    at tfjs@0.11.7:2
    at Object.next (tfjs@0.11.7:2)
    at o (tfjs@0.11.7:2)
```
and I changed it to 2.0 
 <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.0.0/dist/tf.min.js"></script> 

and then it cause in
`model = await tf.loadLayersModel("images/VGG16/model.json");`

```
Uncaught (in promise) Error: Unknown layer: Functional. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at jN (generic_utils.js:242)
    at GI (serialization.js:31)
    at models.js:295
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at Wm (runtime.js:728)
    at o (runtime.js:728)
```

how can I solve this problem?

I made h5 file through colab
```

import keras
!pip install -q tensorflowjs
from google.colab import drive

from google.colab import files
drive.mount('/gdrive')
import tensorflowjs as tfjs
vgg16 = keras.applications.vgg16.VGG16()
a=tfjs.converters.save_keras_model(vgg16,'tfjs/tfjs-models/VGG16')
```

with converted model.json and bin files, it cause above error both for 1.x and 2.0 version.

**Comment by yudhiesh1997** [comment]
In your model.json Functional should be under model_config.class_name change it to "Model"

**Comment by rthadur** [comment]
This issue has been fixed [here](https://github.com/tensorflow/tfjs/pull/3863) , please use latest version to convert and load model and let us know ?
