### ISSUE TITLE
[Documentation ]tf.concat API doc says it accepts Tensors, but you can also pass in arrays

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs#395]
You can use it to concat an array here:

https://github.com/tensorflow/tfjs-examples/blob/master/iris/data.js#L168

but the doc says it needs tensors:

https://js.tensorflow.org/api/0.11.2/#concat

**Comment by tafsiri** [comment]
The doc says it takes a list of tensors. Which seems to be what is happening in that iris example, note the call to `convertToTensors` here https://github.com/tensorflow/tfjs-examples/blob/master/iris/data.js#L159

**Comment by QuantumInformation** [comment]
Thanks for clarifying!
