### ISSUE TITLE
Converter python package installs tensorflow-cpu package on top of already installed tensorflow package

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tfjs#3953]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow.js version: 2.4.0

**Describe the problem**

Converter python package installs tensorflow-cpu package on top of already installed tensorflow package

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ docker run tensorflow/tensorflow:2.3.0 pip3 install tensorflowjs
...
Collecting tensorflow-cpu<3,>=2.1.0
  Downloading tensorflow_cpu-2.3.0-cp36-cp36m-manylinux2010_x86_64.whl (137.3 MB)
```

The official Tensorflow documentation does not seem to mention the `tensorflow-cpu` package. It mentions the `tensorflow` package instead. Maybe tensorlfowjs can depend on it instead.

**Comment by rthadur** [comment]
@Ark-kun tensorflow-cpu and tensorflow are both same, I believe the output has been printed in that way. cc @pyu10055 can you please correct me if i am wrong ? Thank you

**Comment by pyu10055** [comment]
@Ark-kun we recommend installing tensorflowjs pip in a new virtualenv, please refer the converter readme file for details.

**Comment by Ark-kun** [comment]
>@Ark-kun tensorflow-cpu and tensorflow are both same, I believe the output has been printed in that way.

Yes, they seem to be the same. My problem is that in my case TFJS installation downloads and installs a big dependency which is unnecessary since it's already installed. It can be a bit of a problem for us since we dynamically install TFJS every time and want to minimize the amount of dynamically installed packages.
I'd understand if it was the tensorflow vs tensorflow-gpu which is a problem with TF, not TFJS. But tensorflow-cpu vs. tensorflow seems to me more TFJS converter setup related.

> @Ark-kun we recommend installing tensorflowjs pip in a new virtualenv, please refer the converter readme file for details.

I'm running TensorflowJS inside the official Tensorflow Docker [containers](https://hub.docker.com/r/tensorflow/tensorflow).

I do not want to take time from the actual TFJS development. Just thought that maybe there is some explanation for the choice.
