### ISSUE TITLE
bodyPix not working even a little bit correct

### ISSUE THREAD

**Issue by HemantKumar01** [tensorflow/tfjs#3961]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 7 ultimate i7 36000 intel hd built in graphics
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):npm install @tensorflow/tfjs
- TensorFlow.js version (use command below):
- Browser version:chrome 85.0
- Tensorflow.js Converter Version: ^2

**Describe the current behavior**
I am using bodypix in node.js using electron-framework. I am using simple example given on github with this backend.
It is not detecting any human on any simple video I have tried. If I reduce the segmentation threshold  then also it is detecting completely wrong(walls in the video). However once through script tag(only once in 10 tries) it has detected humans exactly right with a console message of "hello seems that you are trying node. Try installing...."
**Describe the expected behavior**
It should simply detect humans as in the demo site using webcam
**Standalone code to reproduce the issue**
You can reproduce the problem by loading a video, drawing it to a canvas on video play per second and then using bodypix on the canvas to output mask data to another canvas
**Other info / logs** If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Sometimes give vertex and shader not linked(something else like this) error. Once it worked with the same settings giving a console message starting with hello, looks like you are using node.... other times no error

**Comment by rthadur** [comment]
@HemantKumarProgrammer we do not have Windows machine to reproduce the error , I tried on my Mac and could not reproduce, It is working as expected.

**Comment by HemantKumarProgrammer** [comment]
> @HemantKumarProgrammer we do not have Windows machine to reproduce the error , I tried on my Mac and could not reproduce, It is working as expected.
I dont know but even using script tag, it is not working. Once it worked exactly the right way. Maybe it is a server problem. Or I don't have a gpu, just inbuilt native Intel hd graphics, is it a problem.
I have @tensorflow/tfjs , @tensorflow/tfjs-node,
@tensorflow/tfjs-convertor,@tensorflow/tfjs -core installed along with bodypix. However while installing tfjs-node it is trying to install some other build tools which were not installed due to an error,saying latest visual studio needed.

**Comment by HemantKumarProgrammer** [comment]
Is a GPU must for using tensorflow bodypix? Then it may be the reason for this issue because I dont have a gpu, just inbuilt intel hd graphics , which is not very good

**Comment by HemantKumar01** [comment]
Just writing this to avoid being stalled.
***Progress:*** thinking to try again, maybe after 10-15 days

**Comment by HemantKumar01** [comment]
It worked after setting ` tf.setBackend("cpu")`
