### ISSUE TITLE
Can TensorFlow React Native works with local models ?

### ISSUE THREAD

**Issue by AnthonyLabaere** [tensorflow/tfjs#3962]
I meet some problems with tfjs-react-native (https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native).

Is the app created using expo? If so is it a managed or bare app?
**Yes, bare app.**

Which version of react native and the dependencies in the install instructions above are you using? 
[dependencies.txt](https://github.com/tensorflow/tfjs/files/5269603/dependencies.txt)

What device(s) are you running on? Note that not all simulators support webgl and thus may not work with tfjs-react-native.
**On my ASUS ROG Phone 2**

What error messages are you seeing? Are there any relevant messages in the device logs?
**My app crash, but see the text below for more informations.**

How could this bug be reproduced? Is there an example repo we can use to replicate the issue?
**I don't have an example repo, please see my explanation below.**

**First of all**, I followed the tutorials https://heartbeat.fritz.ai/image-classification-on-react-native-with-tensorflow-js-and-mobilenet-48a39185717c and https://medium.com/swlh/object-detection-with-android-phone-using-tensor-flow-lite-9463a1522ffd and it works perfectly fine on my app. The only main diff is the source of images. I use expo-camera takePictureAsync function : https://docs.expo.io/versions/latest/sdk/camera/#takepictureasync.

However, I looked for a functional example of tfjs-react-native use with a local model, and so a call of https://js.tensorflow.org/api_react_native/latest/#bundleResourceIO like in https://blog.tensorflow.org/2020/02/tensorflowjs-for-react-native-is-here.html (with burger_not_burger.json and burger_not_burger_weights.bin) but I didn't find anything (except theses burgers but without the model files so... I can't test it).
I tried to do the same with https://tfhub.dev/tensorflow/tfjs-model/ssd_mobilenet_v2/1/default/1 : 
- Downloaded the file and extract it
- Got the js_model/model.json file
- Used the command "cat" to concatenate group1-shard1of17 to group1-shard17of17 into a 65 765ko model_weights.bin
- Tried to load the model by using tf.loadGraphModel(bundleResourceIO(modelJson, modelWeightsId)) or tf.loadLayersModel(bundleResourceIO(modelJson, modelWeightsId)) but my app crash trying to load it and without showing anything into the catch block.

**Is the file too big for react-native ?** If true how you can handle a local model ? The model.json / model_weights.bin is always big and we can't use any other format such as SavedModel, frozenModel or tflite. I false do you any idea what could go wrong here ?

On the other hand I tried to use a local classification model too : https://tfhub.dev/google/tfjs-model/imagenet/mobilenet_v2_035_224/classification/3/default/1
I did the same : 
- Downloaded the file and extract it
- Got the model.json file
- Used the command "cat" to concatenate group1-shard1of2 to group1-shard2of2 into a 6 529ko model_weights.bin
And into my app :
- Loaded my model with tf.loadGraphModel(bundleResourceIO(modelJson, modelWeightsId)) **It works**
- Trying to classify the image returned by expo-camera with this code : 
`        const imageAssetPath = Image.resolveAssetSource({ uri })
        const imgB64 = await FileSystem.readAsStringAsync(imageAssetPath.uri, {
            encoding: FileSystem.EncodingType.Base64,
        })
        const imgBuffer = tf.util.encodeString(imgB64, 'base64').buffer;
        const raw = new Uint8Array(imgBuffer)
        const imageTensor = decodeJpeg(raw)
        const predictions = model.classify(imageTensor)`
And got the following error :
_Error: The shape of dict['images'] provided in model.execute(dict) must be [-1,224,224,3], but was [300,300,3]_
It seems pretty classic, I've seen this error on numerous posts and I did try a lot of things : to reshape or resize my tensor but I never successed to make it work... **Could you tell me how to make it work ?**

**Am I doing something wrong ?** 
I start to think only pre-trained models (https://github.com/tensorflow/tfjs-models ) work with tfjs react-native ^^'
That's pretty sad because I wanted to train my own models and use it into my app.

I also saw this post but there was not really an answer : https://github.com/tensorflow/tfjs/issues/3070

Thank you in advance for your answer, and have a good day.

**Comment by tafsiri** [comment]
Hi thanks for the details in your issue, I'll split my response into two parts:

### Error loading model / app crash

Having more debug information here would be helpful, if the app crashes before the javascript catch block gets to run, I would suggest looking at the device logs between the app starting and the attempt to load a model/crash. More info on device logs are [available here](https://reactnative.dev/docs/debugging#native-debugging) on the react native docs (in particular see the accessing console logs section). There should be some error message given in those logs for the crash.

### Shape error on classification

This part demonstrates that you can indeed load local models (which is great!). However when you try and run a prediction you get an error. Let me try and explain `shape of dict['images'] provided in model.execute(dict)[-1,224,224,3], but was [300,300,3]`.

- Your image dimensions are 300 px * 300 px * 3 channels.
- The model expects images of are 224 px * 224 px * 3 channels. So you need to [resize your image](https://js.tensorflow.org/api/latest/#image.resizeBilinear).
- Further more the model expects inputs to be 'batched'. The -1 means it can take an arbitrary number of 224x224x3 images (constrained by on-device memory). So once you have an imageTensor of the correct size you can turn into into a 'batch of 1' by calling [tf.expandDims](https://js.tensorflow.org/api/latest/#expandDims) on the imageTensor. This will give you a shape of [1,224,224,3] which you should be able to pass to the model.

---

Btw interesting approach to unsharding model weights by using `cat`, hadn't thought of that before. But I wouldn't expect that to work without editing the model.json since the model.json references the different shards. I'm surprised that the second example loads (and is certainly something I will look into if I get some time). We do [plan on adding support](https://github.com/tensorflow/tfjs/issues/3197#issuecomment-631137219) to the tfjs-converter to unshard tfjs graph models using that tool. A workaround I can offer at the moment is to use download the [SavedModel](https://tfhub.dev/google/imagenet/mobilenet_v2_035_224/classification/4) and convert it using the tjfs-converter but set `--weight_shard_size_bytes` to a high number so that you get one shard. This might be a solution to the first issue as well.

**Comment by tafsiri** [comment]
A quick experiment to try to complement your approach of using `cat`. In the model.json there is a `weightsManifest` key, underneath which there is a `paths` key that lists all the shards, if you replace this list with the name of your newly concatenated .bin file, that might work.

**Comment by AnthonyLabaere** [comment]
Hello tafsiri and thank you for yours answers.

I only tried on coco-ssd for now (https://tfhub.dev/tensorflow/tfjs-model/ssd_mobilenet_v2/1/default/1)

Both solutions work for model loading... on android emulator only :
- Using --weight_shard_size_byte on the SavedModel conversion to only have one file
- Changing the path array of weightsManifest in order to reference my concatened .bin file

But as I said only on emulator. On my device my app crashes trying to do "await tf.loadGraphModel(resource)" of this function : 

`export const loadLocalGraphModel = async (modelName: string, modelJson: io.ModelJSON, modelWeightsId: number) => {
    if (__DEV__) {
        console.debug("Chargement du modèle local " + modelName + " en cours...")
    }
    await tf.ready().catch(e => {
        console.debug("Error during TensorFlow initialization", e)
    })

    const resource = tfjsRN.bundleResourceIO(modelJson, modelWeightsId)
    console.log("resource", resource)
    const model = await tf.loadGraphModel(resource)
        .catch(e => {
            console.debug("Error during model loading", e)
        }) as GraphModel
    if (__DEV__) {
        if (model !== undefined) {
            console.debug("Le model local " + modelName + " a bien été chargé")
        } else {
            console.debug("Le model local " + modelName + " n'a pas été chargé")
        }
    }
    return model
}`

with :
- modelJson = require('/assets/models/model.json')
- modelWeightsId = require('/assets/models/group1-shard1of1.bin')

I read "Having more debug information here would be helpful" and I could not agree more. So I tried "adb logcat *:S ReactNative:V ReactNativeJS:V'" but I don't know if there is more information on that : 
[log.txt](https://github.com/tensorflow/tfjs/files/5319134/log.txt)

And I don't know why I have these "Require cycles are allowed". It only appears when I try to load a local model.

I didn't try a prediction for now because my android emulator doesn't take picture :-D And my main issue is to load the model for now.

**Comment by AnthonyLabaere** [comment]
Don't you have a demo app on a repo that I can install on my device, to see if it works ? And if it works, then compare your code with my app code ? Or compare my dependencies ? With that I could debug I think.

**Comment by joaorenatojr87** [comment]
> A quick experiment to try to complement your approach of using `cat`. In the model.json there is a `weightsManifest` key, underneath which there is a `paths` key that lists all the shards, if you replace this list with the name of your newly concatenated .bin file, that might work.
Hi. I use Windows 10, my device conected via USB is Xiaomi 9 with Android 10.
dependencies are
```
"dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@tensorflow-models/mobilenet": "^2.0.4",
    "@tensorflow/tfjs": "^2.6.0",
    "@tensorflow/tfjs-automl": "^1.0.0",
    "@tensorflow/tfjs-react-native": "^0.4.0",
    "async-storage": "^0.1.0",
    "expo-camera": "^9.0.0",
    "expo-gl": "^9.1.1",
    "expo-gl-cpp": "^9.1.2",
    "expo-image-picker": "^9.1.1",
    "expo-permissions": "^9.3.0",
    "jpeg-js": "^0.4.2",
    "react": "16.13.1",
    "react-native": "^0.63.3",
    "react-native-elements": "^2.3.2",
    "react-native-fs": "^2.16.6",
    "react-native-unimodules": "^0.11.0",
    "react-native-vector-icons": "^7.1.0",
    "unimodules": "^1.0.0"
  },
```
I've tried to do it in my project too, whose models I've got from this tutorial [https://cloud.google.com/vision/automl/docs/tensorflow-js-tutorial](url). However I'm using powershell and did it according to [https://stackoverflow.com/questions/1783554/fast-and-simple-binary-concatenate-files-in-powershell](url) . The resulting weights.bin file size sum is correct though, as shown in the picture below:

![image](https://user-images.githubusercontent.com/40832510/96819872-af5c3080-13f2-11eb-8888-4a5fdb70a06b.png)

I've also changed the model.json in the assets directory by changing this: 
`..."weightsManifest": [{"paths": ["group1-shard1of3.bin","group1-shard2of3.bin", "group1-shard3of3.bin" ], "weights":...`
for this:
`..."weightsManifest": [{"paths": ["weights.bin"], "weights":...`

The sequence of the model loading in App.js is inside async componentDidMount(), as the code shows:

```
async componentDidMount() {
    this.cameraRollAccess()
    this.cameraAccess()
    try{
    await tf.ready()
    }catch(err){
      throw(err)
    }
    this.setState({
      isTfReady: true
    });

  try{      
   //const MODEL_PATH ='./assets/model/model.json';
    const modelJson =require('./assets/model/model.json');
    console.log('modelJson = '+modelJson);
    const modelWeights = require('./assets/model/weights.bin');
    console.log('modelWeights = '+modelWeights);
   //this.model = await tf.loadGraphModel(MODEL_PATH);   

    this.model = await tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights));
    
    }catch(err){
      throw (err)
    }
    this.setState({isModelReady: true})
  }
```

As you can see, I've tried with several ways (see commented lines), but with no success either. 
After running 'yarn react-native run-android', I've got the following error:
```
[Wed Oct 21 2020 22:56:39.460]  LOG      modelJson = [object Object]

[Wed Oct 21 2020 22:56:39.461]  LOG      modelWeights = 7

[Wed Oct 21 2020 22:56:40.668]  WARN     Possible Unhandled Promise Rejection (id: 0):

TypeError: undefined is not an object (evaluating 'tfNodes.reduce')
transformGraph@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:195213:26
loadSync@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:199488:66
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:199467:39
step@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:190743:25
fulfilled@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:190625:30
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26991:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27092:27
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30531:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30570:17
callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30787:33
__callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2736:35
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2522:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2719:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2521:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
```

I did some Google on this issue "TypeError: undefined is not an object (evaluating 'tfNodes.reduce')" but never got anything related to this. Assuming that modelJson and modelWeights are never empty or undefined, Is there anything wrong that I haven't seen yet?
Thanks for any help in advance!

**Comment by tafsiri** [comment]
@AnthonyLabaere sorry for the delayed response, in terms of demo apps. There is:
 - [The app](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native/integration_rn59) we use to run integration tests (this will probably be on an older version of expo)
 - I have a couple of repos that I use to test expo related issues as well ([Bare App](https://github.com/tafsiri/tfjs-expo-bare-example), [Managed App](https://github.com/tafsiri/tfjs-expo-managed-example)). We don't support loading local models in managed apps though (so the second link here won't be that relevant).

**Comment by tafsiri** [comment]
@joaorenatojr87 The cat approach isn't really supported so there could be a number of things causing issues that could be the cause of what you are seeing.

An overall takeaway from this thread and [another related one](https://github.com/tensorflow/tfjs/issues/3197) is to add support for sharded local models to react native. I'll look into that post an ETA on that here soon. Until then will you be able to load your model from a web server?

Another comment related to your particular use case with regard to local models is that if you follow that tutorial directly the `tf.automl.loadImageClassification('model.json')` function will expect a url available over http. So you would need to use the [constructor directly](https://github.com/tensorflow/tfjs/blob/b9e2764ff7ea4f538bf9e0a81a95bbe1adc8a905/tfjs-automl/src/img_classification.ts#L38) after the model has loaded. I'll look into updating the docs to reflect that.

**Comment by tafsiri** [comment]
Just to update this thread, I've made a PR to enable loading locally bundled sharded models in with tfjs-react-native, so there would be no need to convert or concatenate the weights. I'll post back here once a new release is out with the feature, I estimate that would happen sometime next week.

**Comment by tafsiri** [comment]
Support for loading sharded models has been added in [0.5.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-react-native-v0.5.0), please try it out and let me know if you run into issues. This should eliminate the need to manually manipulate the weights and weights manifest, which has the potential to introduce errors.

[bundleResourceIO](https://js.tensorflow.org/api_react_native/0.5.0/#bundleResourceIO) can now take an array of ids for weight shards.

**Comment by joaorenatojr87** [comment]
Thanks for the response @tafsiri!
> An overall takeaway from this thread and another related one is to add support for sharded local models to react native. I'll look into that post an ETA on that here soon. Until then will you be able to load your model from a web server?

I've tried to, but got the same error instead:
![modelLoadErrorServer8000](https://user-images.githubusercontent.com/40832510/97587627-f7bab600-19d1-11eb-9758-d1322e593198.png)

In this case I executed node http-server localy on port 8000 as the [tutorial ](https://cloud.google.com/vision/automl/docs/tensorflow-js-tutorial) says.

> Support for loading sharded models has been added in [0.5.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-react-native-v0.5.0), please try it out and let me know if you run into issues. This should eliminate the need to manually manipulate the weights and weights manifest, which has the potential to introduce errors.
> 
> [bundleResourceIO](https://js.tensorflow.org/api_react_native/0.5.0/#bundleResourceIO) can now take an array of ids for weight shards.

I've upgraded to 0.5.0 and the code is like:

```
...
const modelJson =require('./assets/model/model.json');
    const modelWeight1 = require('./assets/model/group1-shard1of3.bin');
    const modelWeight2 = require('./assets/model/group1-shard2of3.bin');
    const modelWeight3 = require('./assets/model/group1-shard3of3.bin');
    this.model = await tf.loadGraphModel(bundleResourceIO(modelJson, [
      modelWeight1, modelWeight2, modelWeight3]));
...
```
And I've downloaded once again the files from my bucket on Cloud Platform to make sure they weren't corrupted, but still, same error (on local http server and on React-Native):
![modelLoadErrorNodeRN](https://user-images.githubusercontent.com/40832510/97587938-5a13b680-19d2-11eb-9174-b23db23243f5.png)

I've got success doing generic image classification with Firebase ML-Vision and with Mobilenet on React-Native, and tested the custom model on Google Platform successfully, but locally with custom model I always get the same issue trying to load the model...

I guess this error is not related to the @tensorflow/tfjs-react-native@0.5.0 , maybe? Is it something related to my custom model that only classifies 2 types of plants? For each plant I've uploaded about 30 pictures of them and it took 1 hour to process the model.
What can it be?

**Comment by tafsiri** [comment]
@joaorenatojr87 that does look like it may be an issue unrelated to the sharding. to make this easier for us to track/resolve, could you make a new issue with everything your last comment __as well as__ your model.json file.
