### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by jameshfisher** [tensorflow/tfjs#3967]
In the code

```
  const carsDataReq = await fetch('https://storage.googleapis.com/tfjs-tutorials/carsData.json');  
  const carsData = await carsDataReq.json();  
```

The variable `carsDataReq` should be called `carsDataResp`.

The code works, but it's conceptually confused - `fetch` returns a promise of a `Response`, not a `Request`.

**Comment by jasonmayes** [comment]
I shall look into this.

**Comment by jasonmayes** [comment]
This is now fixed.
