### ISSUE TITLE
Video support for React Native

### ISSUE THREAD

**Issue by JamesSWilliams** [tensorflow/tfjs#3968]
**System information**
- TensorFlow.js version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes (if someone can point out what needs to be done)

**Describe the feature and the current behavior/state.**

Currently the React Native API only supports running networks on the camera and not on prerecorded videos.

**Will this change the current api? How?**

Probably allow additionally expo video element as input.

**Who will benefit with this feature?**

Everybody who wants to run tf.js on hardware which is not capable of running in realtime.

**Any Other info.**

**Comment by tafsiri** [comment]
Hi @JamesSWilliams, I think this could be interesting to add. At a high level I think it would involve creating something that took a 'video element'/'video source' as input and returned a generator that yielded tensors. 

If this could be done as a utility function similar to [decodeJpeg](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/decode_image.ts) that would probably be most straightforward (it could be decodeExpoVideo or something similar). The other approach would be to do it as a component similar to [camera_stream.tsx](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/camera/camera_stream.tsx), however if going down that route you would need to consider if the user needs to do something else with the video as well at the same time (e.g. displaying it).

Do you have a particular use case in mind that might help shape the design of something like this?

**Comment by JamesSWilliams** [comment]
For a project I'm working on, we need to extract the key points of a person with Posenet over a period of about 20 seconds.
We also want to replay the video. Since we need a video anyway und most phones have problems, using posenet at realtime (at least older or budget phones), we want to postprocess it.

**Comment by tafsiri** [comment]
Cool. I suspect a function approach that yields tensors would probably be best as you'd be able to separate processing the frames from any display of the video that may be happening. But glad to hear you have a use case that would drive prototyping. Is the info I provided above enough to get started? Let me know if you have any questions that I could help with.

**Comment by expolli** [comment]
@tafsiri 
> Cool. I suspect a function approach that yields tensors would probably be best as you'd be able to separate processing the frames from any display of the video that may be happening. But glad to hear you have a use case that would drive prototyping. Is the info I provided above enough to get started? Let me know if you have any questions that I could help with.

Would also be interested in decodeJpeg kind of functionality for video-files. Has there been any activities to provide this from framework side or should be start working on our own function implementation?
