### ISSUE TITLE
tensorflowjs_converter can't make input and output path work

### ISSUE THREAD

**Issue by MarkTension** [tensorflow/tfjs#3972]
**System information**
- Mac OSX
- Version: tensorflowjs 2.4.0

```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='agent/policy/draw_distribution/action_values/linear/bias,agent/policy/move_distribution/action_values/linear/bias' \
    --saved_model_tags='serve' \
    './SavedModel_agent_epsiode5800/'\ './web_model'

```

I get the following error:
`TensorFlow.js model converters.: error: unrecognized arguments:             ./SavedModel_agent_epsiode5800/ ./web_model`

Been trying different things, but I can't get it to run

**Comment by rthadur** [comment]
Issue is with the line ` './SavedModel_agent_epsiode5800/'\ './web_model'` , try to add backslash and quotes appropriately to overcome the format issue.

**Comment by MarkTension** [comment]
Thanks. I've tried a number of combinations already, but had no success with it. Do you have any suggestions to modify that line?

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by Pringmore** [comment]
Hey @MarkTension 
I just get also a similar error this morning similar to the one you get. But now the command line is working for me :))

Avoid using quotes to specify the **input_file_path** or the **output_folder_path**.

Note:
If it doesn't work maybe you should check that the given **path** is correct regarding from where you are running your command. In the case that it doesn't work then check if there is a missing argument you should specify in your command like **--output_node_name**
