### ISSUE TITLE
Tensorflowjs expects 3 Dimensions, even though I trained it with 2 in Python

### ISSUE THREAD

**Issue by mhaas2-tgm** [tensorflow/tfjs#3985]
I am trying to test a Model which I trained using XOR-Operator values in Python:
```
x_train = [[1,0],[0,1],[0,0],[1,1]]
x_label = [1,1,0,0]

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(2,1)),
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(2, activation="softmax")
])

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.fit(x_train, x_label, epochs=15)

prediction = model.predict([[5,5]])
print("Prediction: ", np.argmax(prediction[0]))
```

It works great in Python, but when I transform it into a Tensorflow JS file (model.json), it doesn't work anymore:
```
tfjs.converters.save_keras_model(model, "test_model")
```

As you can see above, I trained it with `input_shape=(2,1)`. But when I try it in Nodejs, I get the Error: 
```
ValueError: Error when checking : expected flatten_input to have 3 dimension(s), but got array with shape [2,1]
```
My JS Code:
```
tf.loadLayersModel(model_url).then((model)=>{
        const input = tf.tensor([1,1],[2,1], "int32");
        const prediciton = model.predict(input)
        console.log(prediciton);
        response.send(prediciton);
        return null;
    }).catch((e)=>{
        console.log(e);
    });
```
Thank you!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Firebase Function
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.4.0

**Comment by tafsiri** [comment]
You aren't passing an input with a similar shape in your JS version to the one in your python version

Compare 

`prediction = model.predict([[5,5]])` with 

```
const input = tf.tensor([1,1],[2,1], "int32");
const prediciton = model.predict(input)
```

Your input shapes are different between python and javascript. Try

```
const input = tf.tensor([[5,5]], "int32");
```

To make sure its working. And then try

```
const input = tf.tensor([[1,1],[2,1]], "int32");
```

Note the extra square brackets around your input arrays.

**Comment by mhaas2-tgm** [comment]
@tafsiri 

When I try `const input = tf.tensor([[5,5]], "int32");` it stops because the second parameter should be the Shape,

When I try `const input = tf.tensor([[1,1],[2,1]], "int32");`, it gives me the same error:
`ValueError: Error when checking : expected flatten_input to have 3 dimension(s), but got array with shape [1,2]`

**Comment by tafsiri** [comment]
Ah yes I think misread one part of your original snippet, yes you need to create a tensor of the appropriate shape (2,1) and then expand it into a batch (i think this is the step that is missing).

You can call [tf.expandDims](https://js.tensorflow.org/api/latest/#expandDims) on your input tensor to convert it to a batch of one. So something like 

```
const input = tf.expandDims(tf.tensor([1,1],[2,1], "int32"));
```

Or in this case since you are giving the shape directly you can add a batch dimension

```
const input = tf.expandDims(tf.tensor([1,1],[1,2,1], "int32"));
```

**Comment by mhaas2-tgm** [comment]
@tafsiri Thank you! It works great!
Just one question: 
From the output `const prediction`, how can I actually get the Prediction of Tensorflow?

**Comment by tafsiri** [comment]
I don't know what you mean. You have the prediction and are even doing console.log(prediction) in your code snippet.

**Comment by mhaas2-tgm** [comment]
Nvm, figured it out!
Thank you!
