### ISSUE TITLE
Predictions are returning strange values

### ISSUE THREAD

**Issue by ojsj18** [tensorflow/tfjs#3989]
**Values exceed 100%**

` const loadMobileNetModel = async () => {
    const modelJson = require('./model.json');
    const modelWeights= require('./weights.bin');
    const model = await tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights));
    setModelFound(true);
    return model;
  }
 
  const getPrediction = async(tensor) => {

     //const prediction = await mobilenetModel.predict(tensor);
     var  results = mobilenetModel.predict(tensor).dataSync()[0];
     
     //const boxes = prediction.dataSync()[0];
     console.log(results);
  }

  const handleCameraStream = (imageAsTensors) => {
    const loop = async () => {

      if(modelFound){
        const verbose = true;
        const nextImageTensor = await imageAsTensors.next().value;
        //tf.print(nextImageTensor, verbose);
        const normalized  = (resized.sub(offset).div(offset));
        const floatImageTensor = tf.cast(nextImageTensor, 'float32');
        const ReshapeImageTensor = floatImageTensor.reshape([1, 416, 416, 3]);
        //tf.print(ReshapeImageTensor, verbose);
        await getPrediction(ReshapeImageTensor);
      }

      requestAnimationFrameId = requestAnimationFrame(loop);
    };
    if(!predictionFound) loop();
  }
`

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
