### ISSUE TITLE
Add a Gaussian Filter

### ISSUE THREAD

**Issue by Ely-S** [tensorflow/tfjs#3990]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Add a Gaussian blur function similar to [OpenCV Gaussian Blur](https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html?highlight=gaussianblur#gaussianblur) or  [Pillow Gaussian Blur](https://pillow.readthedocs.io/en/5.1.x/reference/ImageFilter.html#PIL.ImageFilter.GaussianBlur). This is a pretty common image processing filter. It would be generally useful. 

**Will this change the current api? How?**
It could be a new function, perhaps`tf.image.gaussianBlur(image, params...)`?

It could also be done as a layer. A layer would be more efficient for repeated invocations, because a layer could build its internal kernel just once, when `.build` is called.

```
const gaussianFilter = tf.layers.gaussianFilter(params)
gaussianFilter.apply(image)
```

I have a 2-dimensional implementation in mind for images, but it could be useful in n-dimensions for general signal processing.

**Who will benefit with this feature?**
This would benefit myself, and other developers who work on vision and image processing systems in the browser.

**Any Other info.**
I already solved this for use in my own work, and am volunteering to contribute my code to the greater community. I can make the API conform to whatever the maintainers think best, and would like a consensus on the API before getting started on that. If this feature is undesirable to this project, feel free to close this feature request and I'll publish it as an independent package on NPM. Thanks!

**Comment by tafsiri** [comment]
@Ely-S could you tell us more about your implementation? Is it completely composed of calls to other tf ops or does it implement custom kernels?

If its the latter we may want to start with this as a tfjs-example of how to implement custom op, or see if it makes sense to start an addon library with extra image ops or something else. Having a sense of the complexity of the implementation would be helpful.

**Comment by Ely-S** [comment]
It's a pure tf.js implementation and pretty small for now. Here's a gist:

https://gist.github.com/Ely-S/b0a258d650dceda236ce76e51a9d2e39

**Comment by Ely-S** [comment]
I released my code as a small npm package since this wasn't picked up https://www.npmjs.com/package/tf-gaussian-blur
