### ISSUE TITLE
USE QnA Model Examples doesn't work

### ISSUE THREAD

**Issue by fawazahmed0** [tensorflow/tfjs#3996]
**Describe the current behavior**
The examples for Universal Sentence Encoder for question answering (USE-QA) model, doesn't seem to work.
I tried examples at [tfhub](https://tfhub.dev/google/tfjs-model/universal-sentence-encoder-qa-ondevice/1) , [npmjs](https://www.npmjs.com/package/@tensorflow-models/universal-sentence-encoder) and [Github](https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder), none of them works and two of them fails with a different error in console

**Standalone code to reproduce the issue**
[CodePen](https://codepen.io/fawazahmed0/pen/ZEWdYpV)

**Comment by tafsiri** [comment]
I think the docs are out of date. I tried it and it looks like model.embed does not return a promise (it synchronously returns the embeddings).

Here is a version of your [codepen with the fix](https://codepen.io/tafsiri/pen/vYGqEbJ).

@pyu10055 could you review and update the api docs/examples for useQnA mentioned above.

**Comment by rthadur** [comment]
This is fixed

**Comment by fawazahmed0** [comment]
Only Github example seems to be updated though
