### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by joemullenix-ks** [tensorflow/tfjs#3997]
(latest Chrome 2020 09 30; Windows 10)

When I used the html as shown, the tutorial failed. The viz lib couldn't find the container in the DOM.

Moving the script.js include from head to body solved the issue for me, like this:

`<!DOCTYPE html>
<html>
<head>
  <title>TensorFlow.js Tutorial</title>

  
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis@1.0.2/dist/tfjs-vis.umd.min.js"></script>

</head>

<body>
  
  <script src="script.js"></script>
</body>
</html>`

**Comment by rthadur** [comment]
please check this note in the codelab 

![image](https://user-images.githubusercontent.com/43972606/94872613-eba6fd00-0401-11eb-9e00-34b6fdc23f39.png)
you will not be able to run the file on browser you should use Codepen or glitch .

**Comment by joemullenix-ks** [comment]
I am able to run the entire tutorial after the change I made; no CORS error; no local server needed. It appears to a simple issue with the load sequence.

Thanks for the response.

**Comment by rthadur** [comment]
cc @tafsiri
