### ISSUE TITLE
Allow Config objects expansion to cross package boundaries for DocGen

### ISSUE THREAD

**Issue by ericdnielsen** [tensorflow/tfjs#400]
After ModelPredictConfig moved from -Layers to -Core to support re-use by -Converter, we discussed an issue in our DocGen process.  Specifically, when we're building the API we expand the config object into its nested parameters to inline those parameters in the documentation of the method.  However now when -Layers/predict tries to expand the ModelPredictConfig parameter it fails because that crosses a package boundary in a way that our parser/linker-esque DocGen scripts can't support.

For a short term fix, I'm going to duplicate the ModelPredictConfig code both places.  I think we expect the number of Configs that span packages to be low.

**Comment by caisq** [comment]
cc myself

**Comment by tafsiri** [comment]
This also affects functions like model.save which now uses a config object whose type is defined in core. https://js.tensorflow.org/api/0.11.7/#tf.Model.save

**Comment by nsthorat** [comment]
This was done in https://github.com/tensorflow/tfjs-website/pull/254
