### ISSUE TITLE
More descriptive error when *isTypedArray* fails on certain typed arrays

### ISSUE THREAD

**Issue by nathan-chappell** [tensorflow/tfjs#4009]
**System information**
- TensorFlow.js version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When trying to create a Tensor with `tf.tensor`, and you pass in a `Uint32Array`, and error is thrown which states:
> Error: values passed to tensor(values) must be a number/boolean/string or an array of numbers/booleans/strings, or a TypedArray

This error message is somewhat contradictory to the source code, which includes:

    // @tensorflow/tfjs-core/dist/tf-core.js

    function isTypedArray(a) {
        return a instanceof Float32Array || a instanceof Int32Array ||
            a instanceof Uint8Array;
    }
    /* ... */
    function makeTensor(values, shape, inferredShape, dtype) {
    /* ... */
        if (!isTypedArray(values) && !Array.isArray(values) &&
            typeof values !== 'number' && typeof values !== 'boolean' &&
            typeof values !== 'string') {
            throw new Error('values passed to tensor(values) must be a number/boolean/string or ' +
                'an array of numbers/booleans/strings, or a TypedArray');
        }
    /* ... */

I was passing in a `Uint32Array` and all of the sudden this helpful error message was very annoying.  It would have saved just a little bit of heartache if the error message indicated that, of the typed arrays, only `Float32Array`, `Int32Array`, and `Uint8Array` are accepted.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

I don't know, I guess only me since no one has mentioned it yet 🥴.  But seriously, I think helpful error messages benefit anyone who ever has to read them, and can document expected behavior of code.

**Comment by rthadur** [comment]
@nathan-chappell please submit a PR

**Comment by nathan-chappell** [comment]
@rthadur Roger that.

**Comment by gaikwadrahul8** [comment]
Hi, @nathan-chappell 

Apologize for the delayed response and I was able to replicate the issue from my end it seems like still we're getting same error message and for your reference I have added screenshot below, so just to confirm, May I know have you submitted PR for that issue please ? if not please feel free to submit PR to take care of this issue. Thank you!

![image](https://user-images.githubusercontent.com/115997457/235895699-7823870c-74a1-42f6-8f29-dd1fcb784ae4.png)
