### ISSUE TITLE
layers API limited number of optimizers by name

### ISSUE THREAD

**Issue by atanasster** [tensorflow/tfjs#401]
It seems the layers API does not have all the optimizers by name: 
https://github.com/tensorflow/tfjs-layers/blob/6b5de926d4dfda4c7c32781653e2a9a035272e93/src/optimizers.ts#L28

are defined only `adam`, `sgd`, `adagrad` and `rmsprop`

while the core API also supports 
`adadelta`, `adamax`, `momentum`

**Comment by caisq** [comment]
This looks like a good starter bug to fix for external contributors :)

**Comment by atanasster** [comment]
Cool, I can give it a shot - what are the camelcase names for those?
`Adadelta`, `Adamax`, `Momentum` ?

**Comment by caisq** [comment]
Thanks!

Please see: https://github.com/tensorflow/tfjs-layers/blob/master/src/optimizers.ts#L29
We create aliases for the optimizers. For example, for 'adam', we have an alias 'Adam'

How about the following aliases:
- 'adadelta', 'Adadelta'
- 'adamax', 'Adamax'
- 'momentum', 'Momentum'

This seems to be consistent with what we have.

**Comment by ManrajGrover** [comment]
Keras doesn't have momentum as a separate optimizer. It looks like it is combined with [SGD](https://keras.io/optimizers/#sgd). Should we add it to Layers API?

Also, I just checked that SGD optimizer in Core API is called GradientDescentOptimizer in Tensorflow Python. Maybe it would be difficult to fix that now.

**Comment by caisq** [comment]
There is no `GradientDescentOptimizer` in Keras or tensorflow.js. It is a Python TensorFlow thing. I think it's fine to leave it out for now.

**Comment by atanasster** [comment]
https://github.com/tensorflow/tfjs-layers/pull/229 , I couldn't reference this issue from the layers repo

**Comment by ManrajGrover** [comment]
This can be closed now

**Comment by bileschi** [comment]
Thanks @ManrajGrover , closing.
