### ISSUE TITLE
TensorFlow - Posenet not working properly with React-Native

### ISSUE THREAD

**Issue by mscomazzon** [tensorflow/tfjs#4022]
**System information**
- Mobile device: iPhone 11 Pro
- TensorFlow.js installed from: https://www.npmjs.com/package/@tensorflow/tfjs
                                                    https://www.npmjs.com/package/@tensorflow/tfjs-react-native
- TensorFlow.js version: 
    "@tensorflow/tfjs": "^1.7.1",
    "@tensorflow/tfjs-react-native": "^0.2.3"
    "react": "16.9.0",
    "react-native": "0.61.5"

**Describe the current behavior**
When using tensorflow and posenet realtime with react-native it does not work correctly. Why? Well, upper body parts are not associating as it should. I tried changing the environmental light and it persists. But ... with lower body parts works perfect. 
Something really odd is that we tried out the native option for iOS, and it works wonders, fast and it just grabs the key points, body parts, perfect  
[Images attached]
Configuration can be found here: PoseCorrector.txt

**Describe the expected behavior**
It should recognize the key points on my arms. When is extended, it should show the elbow where the elbow really is, same as wrist, etc. 

**Files**
![IMG_6594](https://user-images.githubusercontent.com/19638233/95128913-85d3b180-0730-11eb-95ac-372ec186bdff.PNG)
![IMG_6597](https://user-images.githubusercontent.com/19638233/95128926-8c622900-0730-11eb-8143-5fc0b73a9a8e.PNG)
![IMG_6595](https://user-images.githubusercontent.com/19638233/95128935-8ff5b000-0730-11eb-8754-7a141965ea50.PNG)
[PoseCorrector.txt](https://github.com/tensorflow/tfjs/files/5330003/PoseCorrector.txt)

**Comment by tafsiri** [comment]
It's possible that the input image you are feeding in is too small and that is causing accuracy issues. Try increasing the tensor size you pass to the model to see if that improves accuracy.

**Comment by mscomazzon** [comment]
Yes ! I redefined width and height and it really improved ! 
const inputTensorWidth = 228;
const inputTensorHeight = 300;

**Thank you !**

**Comment by tafsiri** [comment]
Np! All the best.

**Comment by shahanija** [comment]
Hi, I am using,

`const inputTensorWidth = 228;
const inputTensorHeight = 300;`
and 

`const model = await posenet.load({
      architecture: 'MobileNetV1',
      outputStride: 16,
      inputResolution: { width: inputTensorWidth, height: inputTensorHeight },
      multiplier:0.75,
      quantBytes: 1
    });`

But I am having the same problem  as @mscomazzon specified. Any solution?

Itried using different resolutions and changed `outputStride`. But the only difference i could notice was in the loading time. It takes more than 35 seconds when I increase the resultion and with the  value that you specified it takes about 10-15 seconds.

Please let  me know its solution.

The reference:
[https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx)
