### ISSUE TITLE
Correct the output shape computing for the UpSampling2D layer

### ISSUE THREAD

**Issue by oeway** [tensorflow/tfjs#403]
I think I encountered a bug with the output shape calculation for the newly added UpSampling2D layer (https://github.com/tensorflow/tfjs-layers/pull/204).

It doesn't support a unknown width and height, which I found useful for fully-convolutional networks. With the Conv2DTranspose layer, I could just pass null as width and height.

Maybe we need to add an if statement to check if the spatial dimension is null:
https://github.com/seranus/tfjs-layers/blob/56a0c8b57869b53546a4850a4a6d17da55f1704c/src/layers/convolutional.ts#L1150

Just like the convolution layer do:
https://github.com/seranus/tfjs-layers/blob/56a0c8b57869b53546a4850a4a6d17da55f1704c/src/utils/conv_utils.ts#L59

Thanks.

**Comment by caisq** [comment]
@seranus Do you want to take a look at this issue?

**Comment by seranus** [comment]
@caisq Sure, I'll check it out

**Comment by oeway** [comment]
@seranus I think so. Any news about this issue?

**Comment by seranus** [comment]
@oeway if it's only that I'm going to try to submit a pull request tomorrow or the day after

**Comment by seranus** [comment]
@oeway updated my branched and added a null check, I'd appreciate if you could check it out before I make tests and a pull request. I don't have models to test this scenario.

https://github.com/seranus/tfjs-layers/commit/dce1e7438d4c9f215b3027c43e1f861600ac6d7c

**Comment by oeway** [comment]
@seranus I think the way you did is not correct. We won’t get a single null from the shape array, but the individual dimension can be null, you should check only the ‘height’ and ‘width’ is null, but keep the other two dimension shape.

To make a test is easy you can just build a network with upsampling and define the input shape to something like [null, null, null, 3] for channel last mode and [null, 3, null, null]. Currently this will work if you have convolutional layers, but not with upsampling. If I do that it will fail, because the width and height are null and they can’t be multiplied by 2.

**Comment by seranus** [comment]
@caisq I just can't find any free time to work on this issue at least in the next 2-3 weeks, someone else will have to handle it.

**Comment by oeway** [comment]
@caisq or others, I would appreciate if someone could help with this issue, the fix can be very quick. I hope I can get this in the next release. Thanks in advance.

**Comment by caisq** [comment]
@oeway  Thanks for pinging me. This is on my TODO list now. 

cc @seranus Thank you for your previous try all the same.
