### ISSUE TITLE
.vscode/settings.json missing setting

### ISSUE THREAD

**Issue by atanasster** [tensorflow/tfjs#404]
When submitting fresh PRs, the default settings.json file is missing the setting 
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,

(you guys probably have it set by default in your vscode editor, but on a brand new fork, it formats the code differently from the project defaults)

**Comment by valishah** [comment]
Hi @bileschi : Would like to take this up. Do you mind helping me to put things together w.r.t requirement. What do you mean by `small-project` ?

**Comment by nsthorat** [comment]
We use the google style, I think this is because you haven't installed "clang-format" and "tslint" extensions in vscode.

**Comment by atanasster** [comment]
@nsthorat adding the above setting to .vscode/settings.json , a new user can submit right away, without having to change his own vscode settings. Without the above setting, VSCode will insert spaces around the brackets ie `import { xxx } from yyy;` when saving the file.

**Comment by bileschi** [comment]
Hi @valishah I suspect this problem will be small in that solving it likely requires changes to a single file (`.vscode/settings.json`), or possibly clarifications to the `DEVELOPMENT.md` file to help future users get their settings to match the current style.

Thanks for your interest!

**Comment by atanasster** [comment]
@bileschi - how is the process working on your end ? Will you let us know first if the proposed change is accepted (or change to docs is preferred), or should external contributors submit the PR first to get the conversation going?

**Comment by bileschi** [comment]
Can you please link the PR here?

**Comment by atanasster** [comment]
@bileschi I am having trouble submitting a separate PR while my older PR is still not accepted. Any chance you can take a look at https://github.com/tensorflow/tfjs-layers/pull/229 and let me know if I should remove `momentum` or change the defaults?

**Comment by atanasster** [comment]
@bileschi https://github.com/tensorflow/tfjs-layers/pull/232/files

**Comment by tafsiri** [comment]
looks like this is closed by tensorflow/tfjs-layers/pull/232/files
