### ISSUE TITLE
Random Function signature mismatch errors with WASM Backend

### ISSUE THREAD

**Issue by damienlaine** [tensorflow/tfjs#4047]
Greetings,

**System information**

- I Have I written custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not tested, seems a browser related issue
- TensorFlow.js installed from (npm or script link): CDNDeliver https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js
- TensorFlow.js version (use command below): 2.3.0
- Browser version: Google Chrome, Official build Version 86.0.4240.75 (64 bits)

**Describe the current behavior**

I Use tensorflow JS wasm backend in a Web Worker loaded from a blob. Since i upgraded my Linux box's Chrome to latest version i have unpredictable errors as related in the browser's console output below :

Uncaught (in promise) RuntimeError: function signature mismatch
    at blob:http://dev.linto.local:1234/b8567dbc-0982-4b67-9707-0dcab15d3290:wasm-function[349]:0x218fb
    at blob:http://dev.linto.local:1234/b8567dbc-0982-4b67-9707-0dcab15d3290:wasm-function[199]:0x149bd
    at blob:http://dev.linto.local:1234/b8567dbc-0982-4b67-9707-0dcab15d3290:wasm-function[18]:0x13a0
    at blob:http://dev.linto.local:1234/b8567dbc-0982-4b67-9707-0dcab15d3290:wasm-function[31]:0x2055
    at Add (blob:http://dev.linto.local:1234/b8567dbc-0982-4b67-9707-0dcab15d3290:wasm-function[338]:0x20cbf)
    at A (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js:17:80849)
    at https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js:17:81080
    at g (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js:17:3024)
    at Object.kernelFunc (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.3.0/dist/tf-backend-wasm.min.js:17:3111)
    at h (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.3.0/dist/tf.min.js:17:141788)

Sometime this error has no impact and inferences continues to work as expected (with perfect results). Sometimes the error changes shapes and crashes the browser tab entierely.

The crash might occur at any given time while the wasm backend is loaded. It happens very often, between 10s and 3 hours after loading the wasm backend. Seems totaly random and regardless to any local entropy or user actions on the web page. Might be related on "entropy" on the DevTools console... but not sure...

Finaly, the error occurs even if no inference is running or called (model.predict is called from messages sent to the webworker that uses tfjs).

**Describe the expected behavior**

This weird issue appeared immediately after upgrading my Chrome browser.

**Standalone code to reproduce the issue**

Well...

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

None.

**Comment by rthadur** [comment]
@damienlaine can you please try with latest version 2.6 ?

**Comment by damienlaine** [comment]
Just updated my code.

`96e387d7-1a72-4109-bdbc-1d7c47312ada:1 Uncaught (in promise) RuntimeError: function signature mismatch
    at blob:http://dev.linto.local:1234/96e387d7-1a72-4109-bdbc-1d7c47312ada:wasm-function[349]:0x218fb
    at blob:http://dev.linto.local:1234/96e387d7-1a72-4109-bdbc-1d7c47312ada:wasm-function[199]:0x149bd
    at blob:http://dev.linto.local:1234/96e387d7-1a72-4109-bdbc-1d7c47312ada:wasm-function[18]:0x13a0
    at blob:http://dev.linto.local:1234/96e387d7-1a72-4109-bdbc-1d7c47312ada:wasm-function[31]:0x2055
    at Multiply (blob:http://dev.linto.local:1234/96e387d7-1a72-4109-bdbc-1d7c47312ada:wasm-function[131]:0xf1b2)
    at A (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.6.0/dist/tf-backend-wasm.min.js:17:85322)
    at https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.6.0/dist/tf-backend-wasm.min.js:17:85553
    at g (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.6.0/dist/tf-backend-wasm.min.js:17:3024)
    at Object.kernelFunc (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@2.6.0/dist/tf-backend-wasm.min.js:17:3111)
    at p (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.6.0/dist/tf.min.js:17:150945)
(anonymous) @ VM7 96e387d7-1a72-4109-bdbc-1d7c47312ada:1
(anonymous) @ VM7 96e387d7-1a72-4109-bdbc-1d7c47312ada:1
(anonymous) @ VM7 96e387d7-1a72-4109-bdbc-1d7c47312ada:1
(anonymous) @ VM7 96e387d7-1a72-4109-bdbc-1d7c47312ada:1
Multiply @ VM7 96e387d7-1a72-4109-bdbc-1d7c47312ada:1
A @ VM6 tf-backend-wasm.min.js:17
(anonymous) @ VM6 tf-backend-wasm.min.js:17
g @ VM6 tf-backend-wasm.min.js:17
kernelFunc @ VM6 tf-backend-wasm.min.js:17
p @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.runKernelFunc @ VM4 tf.min.js:17
mul_ @ VM4 tf.min.js:17
mul__op @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
n.call @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
g @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
y_ @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
n.call @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
t.call @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
CE @ VM4 tf.min.js:17
n.apply @ VM4 tf.min.js:17
n.apply @ VM4 tf.min.js:17
OT @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
s @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
(anonymous) @ VM4 tf.min.js:17
t.scopedRun @ VM4 tf.min.js:17
t.tidy @ VM4 tf.min.js:17
sx @ VM4 tf.min.js:17
n.predictLoop @ VM4 tf.min.js:17
n.predict @ VM4 tf.min.js:17
n.predict @ VM4 tf.min.js:17
infer @ VM3 29d9c23b-a4cb-4362-a5e3-8d7329aad108:39
onmessage @ VM3 29d9c23b-a4cb-4362-a5e3-8d7329aad108:11
async function (async)
onmessage @ VM3 29d9c23b-a4cb-4362-a5e3-8d7329aad108:10
Show 37 more frames
blob:http://dev.lint…5e3-8d7329aad108:28 Uncaught (in promise) Ae {name: "ExitStatus", message: "Program terminated with exit(1)", status: 1}
onmessage @ VM3 29d9c23b-a4cb-4362-a5e3-8d7329aad108:28
async function (async)
onmessage @ VM3 29d9c23b-a4cb-4362-a5e3-8d7329aad108:10`

Tested thoroughly on chromium (default debian build) --> No error  
Tested thoroughly on firefox (78) --> No error.

**Comment by damienlaine** [comment]
Hello again,

Just tried the same app (with tfjs 2.3.0) on a Windows 10 Chrome with the same version (Google Chrome, Official build Version 86.0.4240.75 (64 bits).

I have no big crashes so far but appeared a new Warning that was not there before updating chrome from 85.x

The warning in the dev tools console (see below) points out some coincidences with the un-deterministic error that occurs (and might crash the browser tab) in my Linux Debian box. The warning message also appears totaly randomly.

```
tfjs-backend-wasm.js:9 XNN status for xnn_setup_*_nd_f32 is not successful. Got status 4. Use -c dbg to see XNN logs.
printChar @ tfjs-backend-wasm.js:9
_e @ tfjs-backend-wasm.js:9
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0x142e8
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0x14793
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0x6f6c
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0x1e590
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0xf9c
(anonymous) @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0x2270
Multiply @ a9fdf586-6f0b-4400-8f97-41bc11d51813:0xfb31
A @ tfjs-backend-wasm.js:9
(anonymous) @ tfjs-backend-wasm.js:9
g @ binary_kernel.ts:64
kernelFunc @ binary_kernel.ts:70
h @ engine.js:576
(anonymous) @ engine.js:634
e.scopedRun @ engine.js:439
e.runKernelFunc @ engine.js:631
mul_ @ mul.js:64
mul @ operation.js:45
(anonymous) @ recurrent.js:1513
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
n.call @ recurrent.js:1453
(anonymous) @ recurrent.js:736
(anonymous) @ recurrent.js:206
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
g @ recurrent.js:206
(anonymous) @ recurrent.js:204
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
N_ @ recurrent.js:145
(anonymous) @ recurrent.js:744
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
n.call @ recurrent.js:702
(anonymous) @ recurrent.js:1603
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
n.call @ recurrent.js:1590
(anonymous) @ topology.js:1017
YE @ common.js:43
n.apply @ topology.js:976
n.apply @ recurrent.js:693
eT @ executor.js:331
(anonymous) @ training.js:1063
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
s @ training.js:1046
(anonymous) @ training.js:1045
(anonymous) @ engine.js:428
e.scopedRun @ engine.js:439
e.tidy @ engine.js:426
Fy @ globals.js:183
n.predictLoop @ training.js:1029
n.predict @ training.js:1111
n.predict @ models.js:777
infer @ 42125d8a-8d40-4a0f-9107-7bd0a050ff95:37
onmessage @ 42125d8a-8d40-4a0f-9107-7bd0a050ff95:10
async function (async)
onmessage @ 42125d8a-8d40-4a0f-9107-7bd0a050ff95:9
Show 41 more frames
```

If you want to test this out, i deployed app with tfjs 2.3.0 here : https://webvoicesdk.netlify.app/

This is mainly an offline "wake word spotting" tool that needs access to your microphone. You can start the tool with "Start Hotword Pipeline". For english speakers you might afterwards click on "Use LinTO-Snips-Firefox model".
Inference with tfjs starts when there's vocal activity nearby the microphone. You might say "Firefox" or "Hey snips" to trigger one of thoses wake-up words. The main wakeword, alone in the base "LinTO model"  is "LinTO" pronounced in a french speaker fashion (something like "lean toh")

Hope you can help, as the webgl backend do not fit my inference frequency needs.

**Comment by damienlaine** [comment]
Some news from the front.

The problem revolves arround simd / threaded support for Wasm.

I switched from setWasmPath to setWasmPaths and added the three backends to my code.

In the worker i now have :

```
            await tf.wasm.setWasmPaths({
                'tfjs-backend-wasm.wasm': msg.data.wasmPaths.tfWasm,
                'tfjs-backend-wasm-simd.wasm': msg.data.wasmPaths.tfWasmSimd,
                'tfjs-backend-wasm-threaded-simd.wasm': msg.data.wasmPaths.tfWasmThreadedSimd,
                });
```
Now, i can see that Chrome might load the tfjs-backend-wasm-threaded-simd.wasm. 

The browser tab keeps on crashing, but i usualy don't have console message. Just plain tab crash.

I also realize that, with default chrome://flags my browser do not support "SIMD", which fails back to tfjs-backend-wasm.wasm.

The crash is much more prominent when the SIMD flag is enabled and when i use a single setWasmPath with tfjs-backend-wasm.wasm.

Anyway any combination seems unstable with non-predictable results.
