### ISSUE TITLE
How to turn on joins and limb lines for BodyPix v2 with segmentPersonParts()?

### ISSUE THREAD

**Issue by contractorwolf** [tensorflow/tfjs#4054]
I am just getting started using BodyPix from the example code here:
https://github.com/tensorflow/tfjs-models/tree/master/body-pix

I am using the segmentPersonParts with my sample image but it does not appear to show limb lines or join points, how do I turn on this feature? I see it in the demo but the code samples dont appear to show how to do it.  

Here is my basic code and what I see:
![image](https://user-images.githubusercontent.com/4690960/95645530-fca0df80-0a8d-11eb-8ca0-abce7fcafa82.png)

any and all advice would certainly be appreciated!

**Comment by rthadur** [comment]
Demo code is here https://github.com/tensorflow/tfjs-models/tree/master/body-pix/demos , you can leverage same code to in your use case.
