### ISSUE TITLE
https://github.com/tensorflow/tfjs-examples - table of examples - more columns and/or enhancements needed

### ISSUE THREAD

**Issue by sohrabsaran** [tensorflow/tfjs#4056]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):Latest
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
To the table at https://github.com/tensorflow/tfjs-examples#overview-of-examples
Please add columns for:
- Number of inputs (single or multiple) and their datatypes 
(one of the datatypes should be 'boolean' or 'one-hot' as distinguishable logically from analog numeric inputs/outputs)
- Number of outputs (single or multiple) and their datatypes
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
People who want to adapt the most appropriate tf.js example to their real-world problem
**Any Other info.**
Documentation enhancement only

**Comment by rthadur** [comment]
cc @tafsiri

**Comment by tafsiri** [comment]
I not sure that this is practical to maintain outside of the code (and outside of what is documented in the book for examples that are in the book). But cc @jasonmayes and @caisq for their take. The input data types (not a tf dtype) is in the table already though).

@sohrabsaran To help us better understand this request, What were you trying to find that you could not? There could be other ways to solve this documentation issue if we have a better sense of what you overall goal was.

**Comment by sohrabsaran** [comment]
Hi,
Actually I wanted an example of multiple integer inputs and multiple
integer outputs, where some of the inputs and outputs are one-hot encoded.
For now I have deprioritized one-hot encoding and made use of the iris
example.

Thanks,
Sohrab

**Comment by tafsiri** [comment]
@jasonmayes, @caisq to summarize the convo we had with some of the other team members. This seems like something a bit to granular/specific to track in the README (num inputs, dtypes and encodings like one-hot-encoding) and might be hard to maintain if the code changes so is likely not something we would have cycles to do. 

My personal suggestion here is that comments in the source code should be made so that they are sufficient to find these via github search (and thus stay very close to the code they describe—this may already be the case). But we did want to bring this to your attention in case you feel otherwise.

**Comment by jasonmayes** [comment]
I think this is a very nice to have but as @tafsiri pointed out maintaining this and backtracking to get data for existing ones may prove to be a larger task than it seems unless we know the data for those?

As mentioned there is already an inputs column for high level understanding of input type, I think having an outputs column makes a lot of sense if that is easy to add for the existing content so they all have values.

On a related note, I am in the process of converting this table to be available on the TF JS website (tensorflow.org/js) under the demos page there, to make the table filterable etc so you can define to show demos that take only numerical inputs for example and filter out the rest. This will be more important as the table grows here on Github.

Personally I think having high level input and output cols which are unlikely to ever change makes a lot of sense to help people find things that match the pipeline they are trying to use it with. So not quite as granular as the proposition but still helps to filter down things.

**Comment by rthadur** [comment]
@jasonmayes could you please let us know if you have any update on this ?

**Comment by jasonmayes** [comment]
So the data from this table was also added to the website here (https://www.tensorflow.org/js/demos) but there is no extra detail than what is shown here however it is easier to read and filter.

In other news for new demos/examples by the community that are not maintained /created by the TensorFlow.js team we now have a new website for this purpose: https://devlibrary.withgoogle.com/products/ml as it provides a much better interface that is searchable, taggable, and more.

Please submit new demos / examples / and even blog post write ups / tutorials to this DevLibrary site under the Web Machine Learning category for TensorFlow.js work.
