### ISSUE TITLE
Arrow function in tfjs-converter causing syntax error in Internet Explorer 11

### ISSUE THREAD

**Issue by kardeiz** [tensorflow/tfjs#406]
#### TensorFlow.js version

0.11.2 (and tfjs-converter 0.4.0)

#### Browser version

Internet Explorer 11

#### Describe the problem or feature request

tfjs 0.11.2 introduced a dependency on tfjs-converter. tfjs-converter contains an arrow function (in src/data/es6/compiled_api.js) that causes a "Syntax error" in Internet Explorer 11. tfjs 0.11.1 works fine in Internet Explorer 11.

I believe this is a bug because it looks like this arrow function is intended to be compiled away: https://github.com/tensorflow/tfjs-converter/blob/d6abbb538676d5d10e50fe9d436acae4cddad76e/rollup.config.js#L38.

However, if this is not a bug, I would appreciate any workarounds or configuration suggestions.

#### Code to reproduce the bug / link to feature request

    npm install @tensorflow/tfjs@0.11.2

*In index.js:*

    import * as tf from '@tensorflow/tfjs';

Then open your `index.html` that loads `bundle.js` in IE11.

**Comment by tafsiri** [comment]
Could you tell us a bit more about the build setup you are using that produces your bundle.js? Also just to confirm it hasn't already been resolved could you try with @tensorflow/tfjs@0.11.6

**Comment by kardeiz** [comment]
@tafsiri thanks for the assistance!

Upgrading to 0.11.6 does not fix it.

I'm using `webpack` by way of `create-react-app`. Here is a complete reproduction:

```
create-react-app app
cd app
npm i --save @tensorflow/tfjs@0.11.6
sed -i '1s|^|import * as tf from "@tensorflow/tfjs";\r\n|' src/index.js # prepend tf import
npm start
```

**Comment by tafsiri** [comment]
Confirmed. It looks like the file you mention may not be passed through babel. cc @pyu10055 could you take a look.

@kardeiz In the meantime i might have a temporary workaround if you are completely blocked by this. In your app, you could open `node_modules/@tensorflow/tfjs/package.json` and edit it to remove the `module` and `jsnext:main` entries (these are the ones that mention `dist-es6`). That *might* force webpack to pick up the es5 bundle.
