### ISSUE TITLE
Error when executing most of the models with TFJS 1.X and 2.X

### ISSUE THREAD

**Issue by rfourdinier** [tensorflow/tfjs#4062]
Hi, i have an error i cannot get rid of with TFJS.

First of all, I am getting these errors since the first time i have been trying to use TFJS, except in a few cases that I will explain:

The errors always happen when I am executing the model with these lines:

    this.breakerModel = await tf.loadFrozenModel('./assets/converted/eee/model.json');
    //or tf.loadGraphModel depending on tfjs version

    async detectVideo(video, model){
      
      const image_tensor = tf.expandDims(tf.browser.fromPixels(video), 0);
      image_tensor.print();

      await model.executeAsync({ image_tensor }).then(result => { 
     //or model.executeAsync({ input_tensor }) depending on model used

        console.log(result);
      });
    }

The function raising all the following errors is 'model.executeAsync(input)'.

'video' in this code snippet refers to HTMLVideoElement from webcam or hard-coded video file.

The errors are the following:

=== With TFJS 1.X and models trained with Python TF Object Detection API (TF 1.15.X) ===

- with 'ssd_mobilenet_v1_coco_11_06_2017' ---> no error, working perfectly
- with 'ssd_mobilenet_v1_fpn_2018_07_03', 'faster_rcnn_inception_v2_coco_2018_01_28', 'ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03' ---> 

`core.js:6241 ERROR Error: Uncaught (in promise): TypeError: Cannot read property '0' of undefined
 TypeError: Cannot read property '0' of undefined
 at tf-core.esm.js:17
 at ei (tf-core.esm.js:17)
 at tf-core.esm.js:17
 at tf-core.esm.js:17
 at Array.map (<anonymous>)
 at Za (tf-core.esm.js:17)
 at tf-core.esm.js:17
 at tf-core.esm.js:17
 at o.getAndSaveBinary (tf-core.esm.js:17)
 at o.runWebGLProgram (tf-core.esm.js:17)
 at resolvePromise (zone-evergreen.js:798)
 at zone-evergreen.js:705
 at rejected (tslib.es6.js:72)
 at ZoneDelegate.invoke (zone-evergreen.js:364)
 at Object.onInvoke (core.js:41667)
 at ZoneDelegate.invoke (zone-evergreen.js:363)
 at Zone.run (zone-evergreen.js:123)
 at zone-evergreen.js:857
 at ZoneDelegate.invokeTask (zone-evergreen.js:399)
 at Object.onInvokeTask (core.js:41645)`

When i switch from default backend 'webgl' to 'cpu' with  'await tf.setBackend('cpu')', the models are executing without error but it takes of course too much time.

When i execute the model on an hard-coded image source HTMLImageElement, the model is working perfectly, but if I execute the model from an HTMLImageElement which is extracted from the video canvas i get from my Webcam, it is not working and displays the same error as above.

=== With TFJS 1.X and models trained with Python TF Object Detection API (TF 2.3.1) ===

- with 'efficientdet_d1_coco17_tpu-32' --->

`Error in matMul: inputs must have the same rank of at least 2, got ranks 5 and 2.`

When i switch from default backend 'webgl' to 'cpu' with  'await tf.setBackend('cpu')', error persists.

=== With TFJS 2.X and model trained with Python TF Object Detection API (TF 2.3.1) ===

- with 'efficientdet_d1_coco17_tpu-32' --->

`ERROR Error: Uncaught (in promise): Error: Argument 'x' passed to 'expandDims' must be a Tensor or TensorLike, but got 'Promise'`

When i switch from default backend 'webgl' to 'cpu' with  'await tf.setBackend('cpu')', error persists.

=== With TFJS 2.X and models trained with Python TF Object Detection API (TF 1.15.X) ===

- with 'ssd_mobilenet_v1_coco_11_06_2017', 'ssd_mobilenet_v1_fpn_2018_07_03', 'faster_rcnn_inception_v2_coco_2018_01_28', 'ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03' ---> 

`   ERROR Error: Uncaught (in promise): Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
    Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
    at convertToTensor (tensor_util_env.js:84)
    at less_ (less.js:37)
    at Module.less (operation.js:40)
    at Module.executeOp (logical_executor.js:34)
    at operation_executor.js:63
    at engine.js:425
    at t.e.scopedRun (engine.js:436)
    at t.e.tidy (engine.js:423)
    at Module.tidy (globals.js:166)
    at operation_executor.js:63
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41654)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    defaultErrorLogger @ core.js:6228`

When i switch from default backend 'webgl' to 'cpu' with  'await tf.setBackend('cpu')', error persists.

I tried with a few versions of @tensorflow-models/coco-ssd, because of issue #3485 which error is similar.

I have tried loading the model with tfjs-converter library instead of basic tfjs library but the errors in all the above cases are the same.

I am using ionic and node.js, but I cannot use tfjs-node because of a few not related errors . It should nevertheless work with classic tfjs (not node) version, right ?

This is very strange because it works perfectly for only one specific model and TF/TFJS version, but any others cases raises error.
I have been trying to resolve this problem for almost one month, any suggestion would be great.

Thanks.

**Comment by lina128** [comment]
Hi @rfourdinier, thank you the detailed description. Is it possible to share the models you mentioned, it will help us debug. One immediate thing I noticed is that you pass image_tensor as namedTensorMap in this line `model.executeAsync({ image_tensor })`, is the expected input name image_tensor? Is there a input signature for this model? If there is a signature and the expected input name is different, then the image_tensor will be ignored. Also, you mentioned using node.js, webgl backend only works in Browser.

**Comment by rfourdinier** [comment]
Hi, thanks for the reply

I am not sure about the signature but all the models come from TF1/TF2 detection zoo and I am pretty sure I have not added one myself.

with TF1 I convert to frozen_model with this command:

`!python3 export_inference_graph.py --input_type=image_tensor --pipeline_config_path=training/pipeline.config --trained_checkpoint_prefix=training/model.ckpt-5331 --output_directory=frozen_graph #ne pas toucher`

and then converting to TFJS format with this command:

`!tensorflowjs_converter --input_format=tf_frozen_model --quantization_bytes 1 --saved_model_tags=serve --output_node_names='detection_boxes,detection_classes,detection_scores,num_detections' ./frozen_graph/frozen_inference_graph.pb ./converted_and_quantized11/`

-----

with TF2 I convert to saved_model with this command:

`!python3 exporter_main_v2.py --input_type=image_tensor --trained_checkpoint_dir='training/' --output_directory='inference_graph3/' --pipeline_config_path='training/efficientdet_d1_coco17_tpu-32.config'`

and then converting fo TFJS format with this command:

`!tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_scores,num_detections' --saved_model_tags=serve --output_format=tfjs_graph_model ./efficientdet_d1_coco17_tpu-32/saved_model ./converted6/`

-----

Webgl backend only works in Browser, this is kind of strange because with in TF1 I think i succeeded executing the first model I tried as explained above with webgl backend (I have printed it to be sure and set backend to webgl my self again, but maybe it used nevertheless a different backend, it was very fast though) 


-----

With the TF2 versions model, for example EfficientDet, I cannot use `model.executeAsync({ image_tensor })` but I need to use `model.executeAsync({ input_tensor })` instead in order to execute the line (then raising the other error), I don't know if it can help.

I uploaded three models:

- The first one 'ssd_mobilenet_v1_coco_11_06_2017', trained with TF 1.x, which raises no error using TFJS 1.x but raises error using TFJS 2.x

- The second one 'ssd_mobilenet_v1_fpn_2018_07_03', trained with TF 1.x, which raises error using TFJS 1.x and TFJS 2.x

- The third one 'efficientdet_d1_coco17_tpu-32' trained with TF 2.x, which raises error using TFJS 1.x and TFJS 2.x:

You can download the models from here: https://gofile.io/d/OTXUKV

Thanks

**Comment by lina128** [comment]
Hi @rfourdinier, if you are in a Node.js env, webgl backend doesn't work, because it relies on browser native api to run on gpu. If it works in Node.js env, it is only because the input size is small, so the computation is forwarded to cpu to execute. There is no guarantee the forward happens for every kernel. Here's my investigation results:

- ssd_mobilenet_v1_fpn_2018_07_03, can run with TFJS 2.x using cpu backend. Using webgl backend has issue, I've created a separate bug tracking particular for that error. Please track the issue there.

- efficient_d1_coco17_cpu-32, cannot unpack the rar file. Can you pack the file as .zip and upload again?

- ssd_mobilenet_v1_coco_11_06_2017. You said cpu has no error with TFJS 2.x, right?

In terms of how to use the model to predict, look for the signature field in model.json. You need to provide the input as [NamedTensorMap](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/tensor_types.ts#L21). The name has to be exact same as in the signature field except anything other colon. So if the signature name is input1:0, your named tensor should be input1.

**Comment by rfourdinier** [comment]
Hi @lina128 ,

Thank you for all these explanations, it makes sense!

However, I still cannot execute any of the models I have provided with TFJS 2.X ; My models are executing with TFJS 1.X and 'cpu' backend but with TFJS 2.X an error is raised even with 'cpu' backend, and for all the models. 

For example, with "ssd_mobilenet_v1_fpn_2018_07_03" I get the following error:

`core.js:6241 ERROR Error: Uncaught (in promise): Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
    at convertToTensor (tensor_util_env.js:84)
    at less_ (less.js:38)
    at Module.less__op (operation.js:43)
    at Module.executeOp (logical_executor.js:35)
    at operation_executor.js:63
    at engine.js:314
    at Engine.scopedRun (engine.js:324)
    at Engine.tidy (engine.js:313)
    at Module.tidy (globals.js:173)
    at operation_executor.js:63
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41667)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)`

`Uncaught (in promise) Error: Argument 'x' passed to 'clone' must be a Tensor or TensorLike, but got 'Promise'
    at convertToTensor (tensor_util_env.js:84)
    at clone_ (clone.js:36)
    at clone__op (operation.js:43)
    at cloneTensor (utils.js:120)
    at Module.executeOp (control_executor.js:97)
    at operation_executor.js:49
    at executeOp (operation_executor.js:89)
    at GraphExecutor.processStack (graph_executor.js:371)
    at GraphExecutor.executeWithControlFlow (graph_executor.js:332)
    at GraphExecutor._executeAsync (graph_executor.js:278)`

I installed tfjs@2.6.0 and then imported with:

`const tf = require('@tensorflow/tfjs');
require("@tensorflow/tfjs-backend-cpu");
await tf.setBackend('cpu');
console.log(tf.getBackend());
tf.ready().then( () => { this.detectVideo(this.video, this.breakerModel); } );`

then in this.detectVideo:

`    const image_tensor = tf.expandDims(tf.browser.fromPixels(video), 0);
    image_tensor.print();
    await model.executeAsync( image_tensor ).then( result => {
      console.log("execution done");
      console.log(result);  } );
`
Can you tell me if I use it the right way ? 

#3485 is about the same issue, but I did not understand how it was solved, I have latest version of coco-ssd and still the same error.

Also, you can find the .zip 'efficient_d1_coco17_cpu-32' model here: https://gofile.io/d/Twrm7j

Thank you very much for your help.

**Comment by lina128** [comment]
Hi @rfourdinier, how do you get the video as HTMLVideoElement in node.js env?

**Comment by lina128** [comment]
Another observation is that if you are going to use the union package, you don't need to import cpu backend additionally. This may cause some problems.

**Comment by rfourdinier** [comment]
Hi @lina128 ,

I have tried not importing cpu backend using union package unfortunately it does not resolve the error.

I am getting the video as HTMLVideoElement with this snippet:

From my webcam:


    webcam_init() {
    this.logTime("Initializing webcam...");

    if(navigator.getUserMedia){

      console.log('Android');

      const videoCam = <HTMLVideoElement> document.createElement('video');
      videoCam.setAttribute('id', 'vid');
      videoCam.hidden = true;
      videoCam.height = window.innerHeight * 0.8;
      videoCam.width = window.innerWidth;

      navigator.getUserMedia({
        audio: false, 
        video: { facingMode: "environment" ,
            width: {min: 1280, ideal: 1360, max: 4096},
            height: {min: 675, ideal: 720, max: 2160}
        } 
      },
      function(stream) {
        videoCam.srcObject = stream;
        videoCam.onloadedmetadata = () => {
          videoCam.play();
         };

      },
      function(err) {
         console.log("The following error occurred: " + err.name);
      }
      );
      videoCam.style.marginTop = '60px';
      document.body.appendChild(videoCam);
      this.video = videoCam;
    } 

-----

If I want to use a hard-coded video file I just add these lines:

In HTML:

`     <video id = "myVideo" muted> <source src='../../assets/test/videotest.mp4'> </video> `
In JS:

` this.video =<HTMLVideoElement>document.getElementById('myVideo'); `


Thanks.

**Comment by lina128** [comment]
Hi @rfourdinier, we found the root cause for errors that complaining tensor is a Promise. Here is the [fix PR](https://github.com/tensorflow/tfjs/pull/4122), we are going to release the fix in 2.7.0 next Monday. I see that your stack trace has zone.js, which causes issue for async code. zone.js monkey patch all the async calls, and in our code, we check promise using `obj instanceOf Promise`, where the `Promise` could be the one before patching. The fix uses a different way to assert promise, we have tested it with an Angular application. Please try it again after 2.7.0 release.

**Comment by rfourdinier** [comment]
Hi @lina128 ,

Updating to TFJS 2.7.0 seems to have resolved my problems!

Now i am able to execute models without raising any error.

Of course I still cannot execute them really fast but it is normal behavior because I am not using tfjs-node.

Your assistance was greatly appreciated, thank you very much !

**Comment by lina128** [comment]
That's great to hear, @rfourdinier :)
