### ISSUE TITLE
tfjs-node does not implement kernel FlipLeftRight

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4066]
Both [BlazeFace](https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1) and [HandDetector](https://tfhub.dev/mediapipe/tfjs-model/handdetector/1/default/1) models work just fine in NodeJS using tensorflow backend  

The issue is in how post-processing is done in JS code which uses `FlipLeftRight` kernel func to reorient input for better second-pass detection.

So if you use tfjs examples, you'll run into this issue

> Error: Kernel 'FlipLeftRight' not registered for backend 'tensorflow'

Unfortunately, those models are internally used by several others as well such as `FaceMesh` and `HandSkeleton` which makes list of affected models quite long.

Request is to implement `FlipLeftRight` in tfjs-node - expectation is to have feature parity between main backends. 

Also, is there a matrix of implemented features per backend?

Environment: TFJS 3.6.0 on Ubuntu 20.04

**Comment by rthadur** [comment]
@vladmandic can you please check for a similar issue [here](https://github.com/tensorflow/tfjs/issues/2329)

**Comment by vladmandic** [comment]
There is no version conflict and I'm running latest TFJS 2.6.0. Just to confirm, I created a simple test that only has `tfjs-node` listed in `package.json`, zero other libraries so there is nothing to have conflict with.

And I did note the issue <https://github.com/tensorflow/tfjs/issues/3883> that clearly lists that forwardFunc is not implemented in `tensorflow` kernel (and it's .

And it's easy to check:
```shell
nm -D node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow.so | grep forwardFunc
```
function is not present in tensorflow.so shared library which is the backend for `tfjs-node` (unless it's supposed to use a fallback defined in `@tensorflow/tfjs-core/dist/engine.ts`).

**Comment by vladmandic** [comment]
i understand the need for better error message, but will this feature request to actually implement kernel function stay open and eventually be completed?

**Comment by vladmandic** [comment]
any update on this? issue is sitting unassigned for several weeks.

**Comment by tafsiri** [comment]
I'll try and get an update on this.

**Comment by vladmandic** [comment]
@tafsiri any luck getting update?

**Comment by Nuzzlet** [comment]
I get
`(node:15556) UnhandledPromiseRejectionWarning: Error: Backend name 'webgl' not found in registry`

with node-gpu on Windows 10

**Comment by vladmandic** [comment]
@rthadur @tafsiri and plans for implementing this? the issue is open and not even assigned.

**Comment by vladmandic** [comment]
i've tested with tfjs 3.0.0 and error message is improved:
```
Error: Kernel 'FlipLeftRight' not registered for backend 'tensorflow'
```

now the remaining part is to actually implement function `FlipLeftRight` for NodeJS (backend: tensorflow).

**Comment by rthadur** [comment]
Usually feature request are prioritized by the team and are assigned later , hopefully it will get picked up soon. I am tagging this for contributions welcome if any one interested. 

cc @pyu10055 @lina128 @mattsoulanille @jinjingforever

**Comment by vladmandic** [comment]
Just a quick update: both BlazeFace and HandDetect models work just fine in NodeJS using `tensorflow` backend  
The issue is in how post-processing is done in JS code (it uses `FlipLeftRight` kernel func to reorient webcam input)  

So if you use tfjs examples, you'll run into this issue

**Comment by DCtheTall** [comment]
@rthadur I am interested in implementing this if you're still accepting external contributors.

**Comment by rthadur** [comment]
@DCtheTall please go-ahead , thanks for your interest.

**Comment by DCtheTall** [comment]
@rhadur you're welcome! I was wondering if there is a place in tfjs-node which would be a good example of how you typically implement new kernel functions for Node.JS. Just an example of what to go off of should be enough for me to hack something together for a PR

**Comment by jinjingforever** [comment]
Thank you @DCtheTall! This [PR](https://github.com/tensorflow/tfjs/pull/4348) might be a good example of adding missing ops to node JS, and this [doc](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) might also be helpful. Really appreciate it!

**Comment by DCtheTall** [comment]
@jinjingforever thank you for the links. This should be all I need to get started!

**Comment by DCtheTall** [comment]
@rthadur @jinjingforever I have opened a [#5261](https://github.com/tensorflow/tfjs/pull/5261) which implements this function for Node.JS. Lmk if anything else needs to be done.

**Comment by jinjingforever** [comment]
Thank you @DCtheTall for the PR!

**Comment by rthadur** [comment]
This change will be available in next release , thank you so much @DCtheTall for your contribution.

**Comment by jinjingforever** [comment]
Sorry, thanks to @mattsoulanille, looks like the underlying TF C API (1.15) doesn't support this op. It is not supported in the latest version (2.5) either.

What is the right approach to support this kind of ops? (@pyu10055 @lina128 @mattsoulanille). Thanks!

**Comment by lina128** [comment]
Hi @jinjingforever, I see that there's a ScaleAndTranslate in the c API: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/scale-and-translate

Can we use that for FlipLeftAndRight?

**Comment by lina128** [comment]
If ImageProjectiveTransformV3 is available in the c API, it's even better, it's easier to express flip with an Affine transformation matrix: https://www.tensorflow.org/api_docs/python/tf/raw_ops/ImageProjectiveTransformV3

**Comment by jinjingforever** [comment]
Thank you @lina128! I checked the code and looks like the scale factors have to be [greater than 0](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/scale_and_translate_op.cc#L319-L320). So it probably cannot be used to flip an image. And looks like ImageProjectiveTransformV3 is not available in the C API. 

Maybe we could use "reverse" to do the flip, i.e. reverse on the 'H' dimension: `tf.reverse(image, [2])`?

Also, there might be a bug in the current tfjs flipLeftRight implementations that might need to be fixed first. Will discuss with @lina128 offline.

**Comment by lina128** [comment]
reverse sounds good to me.

**Comment by DCtheTall** [comment]
@lina128 thanks for the reply. I'd be happy to assist if I can with any other work needed to reland my original PR

**Comment by jinjingforever** [comment]
Thanks @DCtheTall! I am working on a fix for the existing implementations in other backends and related tests. After that is merged, it would be great if you could help refactor your PR to use "reverse" to implement flipLeftRight in node. 

Really appreciate it!

**Comment by DCtheTall** [comment]
@jinjingforever SGTM. Let me know when your change has merged and I can refactor my PR accordingly

**Comment by jinjingforever** [comment]
Hi @DCtheTall, I've merged my PR. Now you can try implementing flipLeftRight using [reverse](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/kernels/Reverse.ts). The PR also updated the [tests](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/image/flip_left_right_test.ts). You can test your changes locally by running `yarn test` in the `tfjs-node` directory. 

Thank you! Really appreciate your help!

**Comment by DCtheTall** [comment]
@jinjingforever @lina128 I just uploaded a PR that implements the kernel using reverse. Let me know if this is what you had in mind 😄
