### ISSUE TITLE
tfjs convert model

### ISSUE THREAD

**Issue by wbqtac** [tensorflow/tfjs#4068]
Hello there,

Anyone successfully convert the "universal sentence encoder multilingual" model, from tf_saved_model to tfjs_graph_model?
The multilingual use model will needs support tensorflow_text to process on the text. 
In tensorflowjs_converter, I modified the code and import tensorflow_text package. But eventually, still met with the following error:

ValueError: Unsupported Ops in the model before optimization
SegmentSum, DynamicPartition, SentencepieceTokenizeOp, RaggedTensorToSparse, ParallelDynamicStitch, SentencepieceOp

The error comes from tensorflowjs/converters/tf_saved_model_conversion_v2.py, about line 146. 

It looks that this error happens when validating the operation. 
And I checked that for v3 use-multilingual model, it uses tensorflow_text. Before that for v1, it uses sentencepiece and tf_sentencepiece. Is this problem linked to that?

Best

Thank you for your attention.

**Comment by rthadur** [comment]
Have you tried this tfjs model  https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder ?

**Comment by wbqtac** [comment]
Hi Rajeshwar,

Yes, I have tried the js version use before posing the issue.
The js version uses a Lite model, only for English. And I want to load other models. 

Best

**Comment by rthadur** [comment]
@wbqtac can you please share following 

1. model
2. tfjs converter command
3.TFJS version

Thanks

**Comment by wbqtac** [comment]
thank you for your reply. 
More or less, wish to see anyone ever successfully load other models, generally speaking. Not for a very specific model.

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by lukemovement** [comment]
Is there an update planned to fix the issues with the univeral sentence encoder? It still isn't possible to conver the model
