### ISSUE TITLE
Uncaught (in promise) Error: Unknown layer: FixedDropout.

### ISSUE THREAD

**Issue by prakashr85** [tensorflow/tfjs#4069]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution Windows Chrome version 86
- TensorFlow.js version (use command below): 2.6.0
- Tensorflow.js Converter Version: 2.6.0

Converted efficientnet B0 using tfjs convertor and getting this error while loading the model using tf.loadLayersModel

`
Uncaught (in promise) Error: Unknown layer: FixedDropout. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at QR (generic_utils.js:243)
    at $A (serialization.js:31)
    at u (container.js:1206)
    at t.fromConfig (container.js:1234)
    at QR (generic_utils.js:278)
    at $A (serialization.js:31)
    at u (container.js:1206)
    at t.fromConfig (container.js:1234)
    at QR (generic_utils.js:278)
    at $A (serialization.js:31)
Jm @ runtime.js:728
r @ runtime.js:728
t @ errors.js:47
QR @ generic_utils.js:243
$A @ serialization.js:31
u @ container.js:1206
t.fromConfig @ container.js:1234
QR @ generic_utils.js:278
$A @ serialization.js:31
u @ container.js:1206
t.fromConfig @ container.js:1234
QR @ generic_utils.js:278
$A @ serialization.js:31
(anonymous) @ models.js:295
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
Um @ runtime.js:728
o @ runtime.js:728
async function (async)
lemurnetDemo @ index.js:113
(anonymous) @ index.js:287

`

**Comment by prakashr85** [comment]
I getting conversion error with output type tfjs_graph_model with efficientnet


![error](https://user-images.githubusercontent.com/6893395/95983852-f325c780-0e3f-11eb-980c-89ff4f8ff70c.png)

**Comment by rthadur** [comment]
@prakashr85 Can you try to save the model to saved model first and then convert the saved model to tfjs_graph_model?

**Comment by prakashr85** [comment]
yes it worked
