### ISSUE TITLE
Unpack/unstack is implemented, but not usable in tjfs-converter

### ISSUE THREAD

**Issue by dillontiner** [tensorflow/tfjs#407]
#### TensorFlow.js version
tensorflowjs 0.4.0

#### Problem
I am trying to convert the [squeezeDet](https://github.com/BichenWuUCB/squeezeDet) model for use in the browser. Unpack (a.k.a. [unstack](https://github.com/tensorflow/tensorflow/issues/8143)) is the only unsupported op in the graph, but I am aware that an [unstack implementation](https://github.com/tensorflow/tfjs-core/pull/1018) exists for tfjs. In the [supported ops](https://github.com/tensorflow/tfjs-converter/blob/dc51287d6b5bbc6c4778d30b36f2aa1ff47688d4/docs/supported_ops.md) documentation, pack is mapped to stack in tfjs, but nothing yet maps to unstack. Are there plans or obstacles for completing this mapping? Are there any past PRs someone can recommend to use as reference?

#### Similar Issues
#188 asks for unpack and many others to support ssd_mobilenet_v2
#256 asks for unpack and three other ops

#### Code to reproduce the bug / link to feature request
Get the model checkpoints per the squeezeDet README
```
mkdir squeezeDet && cd squeezeDet
wget https://www.dropbox.com/s/a6t3er8f03gdl4z/model_checkpoints.tgz
tar -xzvf model_checkpoints.tgz
rm model_checkpoints.tgz 
cd model_checkpoints/squeezeDet
```

Create and run this python script in to produce a model.pb file
```
# ckpt_to_pb.py
import tensorflow as tf
saver = tf.train.import_meta_graph('./model.ckpt-87000.meta', clear_devices=True)
graph = tf.get_default_graph()
input_graph_def = graph.as_graph_def()
sess = tf.Session()
saver.restore(sess, "./model.ckpt-87000")

graph = tf.get_default_graph()
for op in graph.get_operations(): 
  print (op.name)

from tensorflow.python.platform import gfile
from tensorflow.python.framework import graph_util

output_node_names="bbox/trimming/bbox,probability/class_idx,probability/score"
output_graph_def = graph_util.convert_variables_to_constants(
        sess, # The session
        input_graph_def, # input_graph_def is useful for retrieving the nodes 
        output_node_names.split(",")  )    

output_fld ='./'
output_model_file = 'model.pb'
from tensorflow.python.framework import graph_io
graph_io.write_graph(output_graph_def, output_fld, output_model_file, as_text=False)
```

Run the tensorflowjs_converter on the model.pb file
```
mkdir web_model
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names="bbox/trimming/bbox,probability/class_idx,probability/score" --saved_model_tags=serve $PWD/model.pb $PWD/web_model
```

**Comment by dsmilkov** [comment]
cc @pyu10055 Hey can you add the mapping from "unpack" to "unstack" in the converter?
