### ISSUE TITLE
Getting error when loading wasm backend

### ISSUE THREAD

**Issue by ska-kaushiksa** [tensorflow/tfjs#4070]
**System information**
- OS : Windows 7 - 32 bit
- Hardware : PC : Pentium Dual Core CPU E5400 @ 2.70 GHz 2.69 GHz , RAM : 1 GB (also seen in a machine with RAM of 4GB)
- TensorFlow.js installed from (npm or script link): Script
- TensorFlow.js version : 2.3 
- Browser version: Chrome Version 85

The functionality(loading of backend 'wasm') works fine for most of the machines I am using, but there are few machines where I have noticed that the wasm backend fails to load. 
The error says : 
Error: Backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
![image](https://user-images.githubusercontent.com/11594897/95998439-7a7c3680-0e52-11eb-8011-90ac8a713615.png)

Although I am pretty sure that I am not executing any other method before promise is resolved as shown in below code. 

```
try {
        BlazeFaceModel = await blazeface.load();
        tf.setBackend('wasm').then(() => callNext());

    } catch (error) {
        console.error(error);
    }
```

I have seen this issue mostly in machines with low end hardware and when webgl is not available.

Also it will be helpful if you can clarify some of the below:
1. If we request tf to set a certain backend and if it is not available, will there be fallback to other backends?
2. When I have put the command, tf.setBackend('wasm'). Why is webgl loading? Is webgl loaded first and then the change in backend happens?
3. I have used a promise based approach (similar to await as mentioned in the console error) to execute next command only after the backend is set. Why does the error ask me to await again? Should I use both await tf.ready() with await tf.setBackend()  ?

**Comment by kauavsr12** [comment]
Hi @rthadur , Thanks for the reply.

It says x86 as supported architecture. Pls correct me if I am wrong.
![image](https://user-images.githubusercontent.com/11594897/96146042-7c61fa80-0f23-11eb-8e48-6dfd3387df72.png)

Why won't the fallback happen to other backends? Should I set backend separately if tf.setBackend() fails?
Is the priority list fixed? (Most of the time, the fallback happens from webgl to cpu backend in my case)
Can I set the priority order?

**Comment by rthadur** [comment]
you are right it is supported ,let wait for @annxingyuan response. Thank you

**Comment by nsthorat** [comment]
Can you try loading the model after waiting for the backend to be ready?

**Comment by annxingyuan** [comment]
Hi @kauavsr12, sorry for the delayed response - in answer to your questions:

1. If you request a certain backend but it is not available, TF.js will throw an error.
2. When the WebGL backend is included in the page, it will perform certain initialization activities such as registering its kernels. To avoid this, do not use the TF.js union package, rather require tfjs-core, and then the backend that you want to use (e.g. wasm).
3. As nsthorat suggested above, this error might be resolved by fir calling `await tf.setBackend('wasm')`, and then `await blazeface.load()`.
