### ISSUE TITLE
Bodypix masking for background removal using WebGL instead of software canvas 2D

### ISSUE THREAD

**Issue by danrossi** [tensorflow/tfjs#4076]
I am still going through this api. My requirement is to make the background around bodypix data in a webcam video transparent. I noticed most the helper methods are using software rendering. In a multi user call on the subscribe side, this is possibly no good for performance. 

If bodypix is using webgl internally. Surely there is a way to use that same webgl context to pass the segment data to a shader and make the background manipulations via webgl not canvas 2D. 

I'll play with software rendering for now.

**Comment by danrossi** [comment]
For video, the bodypix util demos dont really work. I just see a mask over the top of the original video. The background needs to be removed and probably better in a shader.

**Comment by danrossi** [comment]
I've tested this out and this shader works. An official api method drawing mask, and adding transparency around the data would be nice.  I think the software rendering to canvas is silly and it crashed chrome a few times. A second texture can be used for rendering a background. 

I've got to test it out still now, but in a webrtc situation a MediaStream can be obtained from a canvas and used for publishing a stream instead of the video. So the rendering is done on the publisher side not subscriber side which may help for a room conference.  

https://jameshfisher.com/2020/09/24/using-bodypix-segmentation-in-a-webgl-shader/

**Comment by danrossi** [comment]
I tried to compare software rendering to webgl. The software method shows the outline in the middle of the canvas, but the video picture is off canvas. The WebGL version is off canvas I have to walk to the right. Resizing the canvas to the video width helps a little. Still rendering to the right. Not sure why yet. 

webgl version. I guess the original webgl context obtaining the data cannot be reutilised. 

```
function drawBody(segmentation, now, metadata) {
	gl.activeTexture(gl.TEXTURE1);
      gl.texImage2D(
        gl.TEXTURE_2D,        // target 
        0,                    // level
        gl.ALPHA,             // internalformat
        segmentation.width,   // width
        segmentation.height,  // height
        0,                    // border, "Must be 0"
        gl.ALPHA,             // format, "must be the same as internalformat"
        gl.UNSIGNED_BYTE,     // type of data below
        segmentation.data     // pixels
      );


       gl.viewport(0, 0, metadata.width, metadata.height);
      gl.activeTexture(gl.TEXTURE0);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, localVideo);
      gl.uniform1i(frameTexLoc, 0);
      gl.uniform1i(maskTexLoc, 1);
      gl.uniform1f(texWidthLoc, metadata.width);
      gl.uniform1f(texHeightLoc, metadata.height);
      gl.drawArrays(gl.TRIANGLE_FAN, 0, 4);

      localVideo.requestVideoFrameCallback(detectBody);
      //requestAnimationFrame(detectBody);

}
```

software version, extra is required to remove the coloured background. 
```
function drawBody2(segmentation, now, metadata) {


const maskBackground = true;
// Convert the segmentation into a mask to darken the background.
//const foregroundColor = {r: 0, g: 0, b: 0, a: 255};
//const backgroundColor = {r: 0, g: 0, b: 0, a: 0};
const foregroundColor = {r: 0, g: 0, b: 0, a: 0};      // foreground
const backgroundColor =   {r: 255, g: 0, b: 255, a: 255};

const backgroundDarkeningMask = bodyPix.toMask(
    segmentation, foregroundColor, backgroundColor);

const opacity = 1;
const maskBlurAmount = 0;
const flipHorizontal = false;

// Draw the mask onto the image on a canvas.  With opacity set to 0.7 and
// maskBlurAmount set to 3, this will darken the background and blur the
// darkened background's edge.
bodyPix.drawMask(
    canvas, localVideo, backgroundDarkeningMask, opacity, maskBlurAmount, flipHorizontal);


let imageData = context.getImageData(0, 0, metadata.width, metadata.height);
    for (let i = 0; i < imageData.data.length; i += 4) {
      if (imageData.data[i] === 255 && imageData.data[i + 1] === 0 && imageData.data[i + 2] === 255) {
        imageData.data[i + 3] = 0
      }
    }
   	context.putImageData(imageData, 0, 0);

//requestAnimationFrame(detectBody);
localVideo.requestVideoFrameCallback(detectBody);
}
```

**Comment by tafsiri** [comment]
potentially related to https://github.com/tensorflow/tfjs/issues/4076

**Comment by danrossi** [comment]
Possibly it meantioned XR as in webXR. I'm not sure if the same webgl reference can be reutilised to remove the background from the texture but this is a start to actually see what its doing to the canvas

```
 const mygl = document.createElement('canvas').getContext('webgl2');
  const gpgpu = new tf.webgl.GPGPUContext(mygl);
  tf.ENV.registerBackend('custom-webgl', () => {
    return new tf.webgl.MathBackendWebGL(gpgpu);
  });
  tf.setBackend('custom-webgl');
```

**Comment by danrossi** [comment]
Working implementation of that shader code above. Would like to try and apply the texture in one process instead of reapplying downloaded data. I think there is a memory leak I need to figure out now also. I have to apply an image texture next or video from screen capture etc. The rendered canvas is publishable to webrtc. 

https://dev.electroteque.org/webrtc/html/virtual-background/publish.html

**Comment by amit1072** [comment]
> I tried to compare software rendering to webgl. The software method shows the outline in the middle of the canvas, but the video picture is off canvas. The WebGL version is off canvas I have to walk to the right. Resizing the canvas to the video width helps a little. Still rendering to the right. Not sure why yet.
> 
> webgl version. I guess the original webgl context obtaining the data cannot be reutilised.
> 
> ```
> function drawBody(segmentation, now, metadata) {
> 	gl.activeTexture(gl.TEXTURE1);
>       gl.texImage2D(
>         gl.TEXTURE_2D,        // target 
>         0,                    // level
>         gl.ALPHA,             // internalformat
>         segmentation.width,   // width
>         segmentation.height,  // height
>         0,                    // border, "Must be 0"
>         gl.ALPHA,             // format, "must be the same as internalformat"
>         gl.UNSIGNED_BYTE,     // type of data below
>         segmentation.data     // pixels
>       );
> 
> 
>        gl.viewport(0, 0, metadata.width, metadata.height);
>       gl.activeTexture(gl.TEXTURE0);
>       gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, localVideo);
>       gl.uniform1i(frameTexLoc, 0);
>       gl.uniform1i(maskTexLoc, 1);
>       gl.uniform1f(texWidthLoc, metadata.width);
>       gl.uniform1f(texHeightLoc, metadata.height);
>       gl.drawArrays(gl.TRIANGLE_FAN, 0, 4);
> 
>       localVideo.requestVideoFrameCallback(detectBody);
>       //requestAnimationFrame(detectBody);
> 
> }
> ```
> 
> software version, extra is required to remove the coloured background.
> 
> ```
> function drawBody2(segmentation, now, metadata) {
> 
> 
> const maskBackground = true;
> // Convert the segmentation into a mask to darken the background.
> //const foregroundColor = {r: 0, g: 0, b: 0, a: 255};
> //const backgroundColor = {r: 0, g: 0, b: 0, a: 0};
> const foregroundColor = {r: 0, g: 0, b: 0, a: 0};      // foreground
> const backgroundColor =   {r: 255, g: 0, b: 255, a: 255};
> 
> const backgroundDarkeningMask = bodyPix.toMask(
>     segmentation, foregroundColor, backgroundColor);
> 
> const opacity = 1;
> const maskBlurAmount = 0;
> const flipHorizontal = false;
> 
> // Draw the mask onto the image on a canvas.  With opacity set to 0.7 and
> // maskBlurAmount set to 3, this will darken the background and blur the
> // darkened background's edge.
> bodyPix.drawMask(
>     canvas, localVideo, backgroundDarkeningMask, opacity, maskBlurAmount, flipHorizontal);
> 
> 
> let imageData = context.getImageData(0, 0, metadata.width, metadata.height);
>     for (let i = 0; i < imageData.data.length; i += 4) {
>       if (imageData.data[i] === 255 && imageData.data[i + 1] === 0 && imageData.data[i + 2] === 255) {
>         imageData.data[i + 3] = 0
>       }
>     }
>    	context.putImageData(imageData, 0, 0);
> 
> //requestAnimationFrame(detectBody);
> localVideo.requestVideoFrameCallback(detectBody);
> }
> ```

Could you share the code for shaders as well?

**Comment by danrossi** [comment]
Here is a method I came up with. 

```

export default class BodyPixRenderer {
    static init(buffer) {
        const config = {
            premultipliedAlpha: false
        };

        gl = buffer.getContext('webgl2', config) || buffer.getContext("webgl", config) || buffer.getContext("experimental-webgl", config);


        const vs = gl.createShader(gl.VERTEX_SHADER);
        gl.shaderSource(vs, 'attribute vec2 c; void main(void) { gl_Position=vec4(c, 0.0, 1.0); }');
        gl.compileShader(vs);
        const fs = gl.createShader(gl.FRAGMENT_SHADER);
        gl.shaderSource(fs, this.fragmentShader);
        gl.compileShader(fs);
        if (!gl.getShaderParameter(fs, gl.COMPILE_STATUS)) {
            console.error(gl.getShaderInfoLog(fs));
        }
        const prog = gl.createProgram();
        gl.attachShader(prog, vs);
        gl.attachShader(prog, fs);
        gl.linkProgram(prog);
        gl.useProgram(prog);
        const vb = gl.createBuffer();
        gl.bindBuffer(gl.ARRAY_BUFFER, vb);
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, 1, -1, -1, 1, -1, 1, 1]), gl.STATIC_DRAW);
        const coordLoc = gl.getAttribLocation(prog, 'c');
        gl.vertexAttribPointer(coordLoc, 2, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(coordLoc);
        gl.activeTexture(gl.TEXTURE0);
        const frame = gl.createTexture();
        gl.bindTexture(gl.TEXTURE_2D, frame);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
        gl.activeTexture(gl.TEXTURE1);
        const background = gl.createTexture();
        gl.bindTexture(gl.TEXTURE_2D, background);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
        frameTexLoc = gl.getUniformLocation(prog, "frame");
        maskTexLoc = gl.getUniformLocation(prog, "mask");
        texWidthLoc = gl.getUniformLocation(prog, "texWidth");
        texHeightLoc = gl.getUniformLocation(prog, "texHeight");
    }
    
    static render(segmentation, metadata, localVideo) {

  

        gl.activeTexture(gl.TEXTURE1);
        gl.texImage2D(gl.TEXTURE_2D, // target 
            0, // level
            gl.ALPHA, // internalformat
            segmentation.width, // width
            segmentation.height, // height
            0, // border, "Must be 0"
            gl.ALPHA, // format, "must be the same as internalformat"
            gl.UNSIGNED_BYTE, // type of data below
            segmentation.data // pixels
        );
        gl.viewport(0, 0, metadata.width, metadata.height);
        gl.activeTexture(gl.TEXTURE0);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, localVideo);
        gl.uniform1i(frameTexLoc, 0);
        gl.uniform1i(maskTexLoc, 1);
        gl.uniform1f(texWidthLoc, metadata.width);
        gl.uniform1f(texHeightLoc, metadata.height);
        gl.drawArrays(gl.TRIANGLE_FAN, 0, 4);
    }
    static get fragmentShader() {
        return `precision mediump float;
  
  uniform sampler2D frame;
  uniform sampler2D mask;

  uniform float texWidth;
  uniform float texHeight;

  void main(void) {
    vec2 texCoord = vec2(gl_FragCoord.x/texWidth, 1.0 - (gl_FragCoord.y/texHeight));
    gl_FragColor = vec4(texture2D(frame, texCoord).rgb, texture2D(mask, texCoord).a * 255.);
  }`;
    }
}
```

**Comment by amit1072** [comment]
Great. Thanks for sharing. I was able to simplify it a bit, like so:-

```
in vec2 textureCoords;
out vec4 color;
uniform sampler2D frame,mask;

void main(){
	vec4 tex1=texture(frame,textureCoords);
	vec4 tex2=texture(mask,textureCoords);
	color = vec4(tex1.rgb, tex2.a * 255.);
}
```

Also were you able to get to the bottom of the memory leak that you were facing? I was wondering where exactly was your code leaking memory from?

**Comment by cvmlddev** [comment]
@danrossi Could you explain why canvas2d is not good for performance in a multi user call?

**Comment by danrossi** [comment]
I have it setup so that the WebRTC publisher is broadcasting the mediastream of the canvas being rendered. So its on the broadcaster side not subscribe side. After the bodypix rendering, be it via webgl or asm not sure what is used, makes no sense to come back into software. I need to add more code to render a background image texture into the canvas behind the bodypix rendering. 

Somehow processing it directly to remove background from the original texture bodypix is using without having data returned and doing it separately would be even more efficient ?

My WebRTC feature is built for multiple servers, but I will put up a working example for now broadcasting and subscribing via millicast. My next task is to combine screen sharing and camera in one.

**Comment by danrossi** [comment]
Here is a basic raw demo. I haven't done any resource testing, but even doing this. https://dev.electroteque.org/bodypix/

**Comment by amit1072** [comment]
@danrossi  - thank you. This works, I was able to test. Now as a separate discussion, I do notice that my CPU is keeps pretty high in terms of usage and the fans keep on of my mac I9. I was hoping that it would go easy on the CPU, but seems like send even the segmentation data back and forth between the software and GPU takes a lot of processing, especially when we're trying to achieve greater than 15-20 FPS.

Is it possible to go one step further and not even exchange segmentation data between GPU and software? that would be the ultimate solution, where u're only sending video frames from camera and segmentation data stays in GPU and is applied on the video frame and result is rendered on a canvas.

What do you think?

**Comment by danrossi** [comment]
@amit1072 I'm not a shader expert I am afraid. I can just apply them like the test. It was obtained from the original blog. This processing within bodypix to apply the mask would be ideal. Do it in one process hence this issue. The canvas software processing is not ideal.

**Comment by danrossi** [comment]
I'm using this project also for standard green screen options. It might be a similar shader required to be integrated. 

https://github.com/bhj/gl-chromakey

**Comment by amit1072** [comment]
@danrossi -- thanks again. I think writing the shader is just one part of it and I think I can do that without much hassle, in fact I will share the code when its done. The main hurdle for me is how to grab the segmentation data inside the GPU, as of now the bodypix javascript API returns it as a one dimensional array which we are sending to the GPU again, but if we want to remove that back and forth, I need  to know how to grab it from the result of tensorflow call for bodypix.

**Comment by danrossi** [comment]
This is the segmentation data gatherer. I don't understand where it processes the input to webgl in tensorflow from here. I notice alot of bloated properties not needed, only the segmentation data is useful. Its also doing dimension stuff which could easily be cached as dimensions on a video texture won't change ? 

https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/body_pix_model.ts#L442

**Comment by danrossi** [comment]
Well it looks like using video as a source it's software rendering to a canvas that is the first resource hit. But if webgl rendering video to canvas and offering that as a source, not sure how it handles it. 

https://github.com/tensorflow/tfjs/blob/964debd9232b0733d035b7b8d899b7254dc12b6f/tfjs-backend-webgl/src/kernels/FromPixels.ts

**Comment by danrossi** [comment]
This is where the canvas is then used as a texture for the internal gl context, all of that up to there could be avoided possibly using the video as a texture to that gl context

https://github.com/tensorflow/tfjs/blob/964debd9232b0733d035b7b8d899b7254dc12b6f/tfjs-backend-webgl/src/gpgpu_context.ts#L158

binding that software rendered canvas to texture here. unnecessary I think. 

https://github.com/tensorflow/tfjs/blob/964debd9232b0733d035b7b8d899b7254dc12b6f/tfjs-backend-webgl/src/gpgpu_util.ts#L200

if you do this and render the video to this externally created gl context, it can use this rendered texture for processing. the methods have to be overridden somehow.to do stuff after


```
const mygl = canvas.getContext('webgl2');

 tf.registerBackend('webgl2', () => {
    return new tf.webgl.MathBackendWebGL(
        new tf.webgl.GPGPUContext(mygl));
  });
 tf.setBackend('webgl2');
 ```

**Comment by danrossi** [comment]
Stale ? My tests have proven the first software composition of the video to canvas is part of the resource and frame dropping issue. I'll try and pull apart the lines I picked out and see if it can be improved.

**Comment by danrossi** [comment]
I'm working at digging into tensorflow to NOT use canvas software rendering to capture a texture. I believe this is causing the performance issues and even browser freezing and crashing. It's in the code above as you can see. That is a good start. I'm not sure how that passed as ok. Canvas software rendering is bad and causes dropped frames.  I can't send out a feature into production because of this.

**Comment by danrossi** [comment]
I've come up with two solutions. If I give bodypix a video element, it will do a software render and then upload that to the gl texture.  I've modified the shader to mix a background image texture with the frame texture and the alpha bodypix texture. It works fine although the image isn't smooth and shows the background through the camera image because of bodypix detection. 

https://electroteque.org/bodypix/virtual5.html


Another working example is rendering the video to a texture of a seperate gl context. And giving that buffer canvas to bodypix. 

https://electroteque.org/bodypix/virtual6.html

It is however internally reuploading to a texture in the internal context. It is doubling the texture render when it should take a video element and do it directly ? Due to the double texture rendering it freezes the frame in chrome. 

It should just take the video element and render like this ? 

```
pixelGl.activeTexture(pixelGl.TEXTURE0);
  pixelGl.texImage2D(pixelGl.TEXTURE_2D, 0, pixelGl.RGB, pixelGl.RGB, pixelGl.UNSIGNED_BYTE, localVideo);
  pixelGl.drawArrays(pixelGl.TRIANGLE_FAN, 0, 4);
  ```
  
  I've got to build the source and debug it further.

**Comment by danrossi** [comment]
Confirming a runaway memory leak in Firefox. Will make a new ticket. Here is an experiment scaling the video / bodypix mask over a background image texture. Can be full scale. In real world test screencapture is switched as background texture. 

https://jsfiddle.net/danrossi303/82tpoy94/3/

**Comment by danrossi** [comment]
I have a new experiment with the lowest possible cpu and gpu right now using video texture. cpu becomes higher in my integration for some reason I have to check why.  

Although once I turn on slow mode gpu usage is 80%. Bodypix doesn't accept an OffscreenCanvas as a source to check if that helps. I hope giving it a buffer canvas with the video printed as a gl texture it doesnt try and do cpu draw internally. I have to build the project from source to check. There should be a way to draw the video to the bodypix shader directly, capture the mask data , then calculate it in the fragment like the code in the example page at once. Without a second step

https://electroteque.org/bodypix/virtual-screen5.html

**Comment by danrossi** [comment]
Here is another experiment using OffScreenCanvas and setting fromPixels externally. bodypix 2.2.0 accepts OffScreenCanvas too but sending input uses lower cpu for some reason.  Seems to be better on the cpu and gpu. Some of the stuff inside segmentPerson is not relevant, so calling the segment code externally.  Tried gl readPixels but the alpha data wasn't correct on the output.

```
var bufferEl = document.createElement("canvas");
var buffer =  ('OffscreenCanvas' in window) ? bufferEl.transferControlToOffscreen() : bufferEl;
```

```
   let input = tf.browser.fromPixels(buffer);
   const { segmentation } = net.segmentPersonActivation(input, 'medium', 0.7);
   const [height, width] = segmentation.shape;
   const result = await segmentation.data();
   segmentation.dispose();
``
https://electroteque.org/bodypix/virtual-screen6.html

**Comment by rthadur** [comment]
Will be closing this issue as we will be using latest body segmentation model for same purpose.
Please check latest body segmentation model for latest bodypix model demo https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation. We will not support existing  bodypix.
