### ISSUE TITLE
VRAM hosting of convolution output

### ISSUE THREAD

**Issue by markmckenna** [tensorflow/tfjs#4080]
**System information**
- TensorFlow.js version (you are using): Experimental only
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Current behaviour, as I understand it, is that TF treats each of its back end components as a selection of bulk operator implementations running on different substrates. The substrate I'm interested in particular is the GPU, more specifically GLSL math bindings.

For certain computer vision related applications, it is desirable to have the operation (e.g. 2d or 3d convolution) collect data from one or more VRAM buffers, and retain the output in VRAM buffers also. This facilitates bridging operators against large pools of data without having to round-trip that data across the bus, and also facilitates building non-AI output processing whose goal is to use the output as vertex, texture, colours, etc. in a render pipeline.

Caveat: I am not an expert at TensorFlow, and although I've read the code and partially understand it, I don't have a full and deep understanding of what it's capable of.

**Will this change the current api? How?**

This would extend the current API. I am not specific in exactly how. I think it would suffice to be able to pass a GL buffer reference as an input, and receive one as an output; and then skip whatever parts of the CPU-GPU bandwidth utilization doing so makes redundant. I would leave the responsibility for getting data into and out of the GPU in the appropriate format outside of Tensorflow as a preprocessing step, since there are potentially lots of different ways to do that.

**Who will benefit with this feature?**

Anyone whose goal is to synthesize or augment still or video images using AI. Video encode/decode/edit/transcode pipelines. Advanced upsampling, modification or XR features implemented in the client. Probably other people too.

**Any Other info.**

My personal goal is to make it possible to deliver higher resolution video without increasing bandwidth and hosting costs, or else to deliver the same quality video for less bandwidth, by taking advantage of idle client GPU.

**Comment by rthadur** [comment]
cc @pyu10055 @lina128

**Comment by annxingyuan** [comment]
Hi @markmckenna - thank you for bringing this up. We have an issue that may be related: https://github.com/tensorflow/tfjs/issues/3937

Would you mind taking a look at that to see whether it covers the same territory?

Also I noticed in your issue description you indicate that you'd be willing to contribute :) We would definitely welcome this contribution, and I'm happy to work with you to help you understand the codebase / help scope this work. Just let me know!

**Comment by markmckenna** [comment]
@annxingyuan thanks for pointing that out, I didn't see that! That's very much the same issue. This issue is a little more general (GPU buffers rather than just textures), and it includes the idea of a GPU-allocated input, as well as pass-through and output. But basically it's the same idea.

I am totally willing to contribute! My only constraint is time. I may also have access to dev resources that can be brought on line to get things to happen, but that'll be an internal negotiation.

I will allocate some time over the next few days to investigating the code a bit more deeply, to see if it's clear how and where my suggestion would fit in. Support from your side is very welcome :)

Thanks so much!
