### ISSUE TITLE
tidy won't work when call multiple hierarchy function

### ISSUE THREAD

**Issue by naah69** [tensorflow/tfjs#4081]
**System information**
- Have I written custom code : use wasm as backend
- OS Platform and Distribution : macOS 10.14
- TensorFlow.js installed from : npm
- TensorFlow.js version : 2.9.0
- Browser version: Chrome 58

**Describe the current behavior**

when i call function that calculate data in `tidy`，the tensors did'n be cleaned up 

example:
```
function a(){
var pointList = tf.tensor2d([[1,2,3],[1,2,3]])
...
}

tf.tidy(()=>{
a();
});
```
![image](https://user-images.githubusercontent.com/25682169/96283392-b9ef8200-100e-11eb-9437-b1e28cf3a463.png)
![image](https://user-images.githubusercontent.com/25682169/96283454-d12e6f80-100e-11eb-8898-bc4d56a2a1eb.png)

**Describe the expected behavior**
tensor in code that is like the above will be clean up,even multiple hierarchy function call

**Comment by rthadur** [comment]
@naah69 can you please provide a codepen example to reproduce the same ? thank you

**Comment by naah69** [comment]
oh,my bad,there is not `dity` in other codes,the tidy work。
