### ISSUE TITLE
Fill op in backend-wasm

### ISSUE THREAD

**Issue by pabloegpf1** [tensorflow/tfjs#4083]
**System information**
- TensorFlow.js version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.**
I am developing a face recognition system inside a web app using face-api.js. 
The library works great for webgl backend. However when I switch to wasm backend  this error will show up:
`Uncaught (in promise) Error: 'fill' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen`
I would like to contribute to tfjs by adding this functionality. I already followed the instructions in the [guide](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md). The problem is that I see the Fill op should be already implemented:

- shows as supported in the [supported_ops](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md)
- already present in `tfjs-core/ops`
- already present in `tfjs-backend-wasm/src/kernels`
- already registered in `tfjs-backend-wasm/src/register_all_kernels.ts`

Am I missing something here? I would really want to contribute this op. Thanks!

**Will this change the current api? How?**

It won't change the api.

**Who will benefit with this feature?**

Anyone that wants to use the wasm-backend.

**Any Other info.**

My repo: https://github.com/pabloegpf1/Face-App
My web app (running on webgl): https://www.pabloescriva.com/Face-App/
face-api.js: https://github.com/justadudewhohacks/face-api.js

**Comment by lina128** [comment]
Hi @pabloegpf1 , I see that face-api depends on tfjs-core 1.7.1, Fill is available in WASM @2.0.1 and up.

**Comment by pabloegpf1** [comment]
Hi @lina128 , you are right, I thought I could use a custom version of tfjs in Face-Api. I ended up using @vladmandic 's fork:

https://github.com/vladmandic/face-api

Thanks!
