### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by kennysong** [tensorflow/tfjs#4085]
Minor typo. A few tfvis containers are probably missing a `tab: "Model"`? 

In "6. Train the Model":

```
tfvis.show.modelSummary({name: 'Model Architecture'}, model);
```

```
const container = {
  name: 'Model Training', styles: { height: '1000px' }
};
```

**Comment by jasonmayes** [comment]
@kennysong I can not locate the code snippet you are referring to in this codelab? Or are you proposing adding these 2 lines of code somewhere in the lab?

**Comment by kennysong** [comment]
It's in the [TensorFlow.js — Handwritten digit recognition with CNNs](https://codelabs.developers.google.com/codelabs/tfjs-training-classfication/index.html#5) CodeLab, page 6.

Here's a screenshot of one of the snippets:

<img width="823" alt="Screen Shot 2020-10-29 at 10 00 05 AM" src="https://user-images.githubusercontent.com/2199875/97512703-8547d700-19cd-11eb-853c-4e12c7fbcbdc.png">

**Comment by jasonmayes** [comment]
Updated on staging server. Should be live soon.
