### ISSUE TITLE
Handling non-batch image rotation

### ISSUE THREAD

**Issue by GantMan** [tensorflow/tfjs#4088]
**System information**
- Are you willing to contribute it (Yes/No):  Yes

**Describe the feature and the current behavior/state.**
I noticed `rotateWithOffset` doesn't work on Int32 and it doesn't work with 3D tensors.  I was thinking of adding code to automatically `expandDims` and convert as needed so `rotateWithOffset` could work on a single image.

**Will this change the current api? How?**
It would allow a variety of input.

**Who will benefit with this feature?**
Anyone looking to rotate an image without a batch.

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by GantMan** [comment]
I'm very interested in bulletproofing, or at the very least, creating commonality with `tf.image`.  Some methods require batches, and some don't.  Some return a tensor of the same dType as the input tensor, and some don't.

**Comment by tafsiri** [comment]
I'll leave Ann to comment more, but I don't think we'd have any objection to rotateWithOffset also supporting 3d tensors or other dtypes (seems like a clear win to me). 

Ditto to inconsistencies with other ops on tf.image, maybe listing out the ones you have found would be a good start, if they would require breaking changes now is a good time for us to consider them.

**Comment by annxingyuan** [comment]
@GantMan Definitely no objections here :) Thank you so much for offering to take this on!

**Comment by gaikwadrahul8** [comment]
Hi, @GantMan 

Apologize for the delayed response and we are re-visiting our older feature request issues and checking whether those feature requests implemented or not as of now so I see your previous comment and you mentioned you would do contribution for this feature request so May I know have you contributed for this feature request or not ? if yes please feel free to close this issue ? 

If this feature haven't implemented as of now then May I know are you still looking for this feature in TFJs ?	If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @GantMan 

Just to confirm, May I know are you working on this feature request and would like to submit PR to take care of this feature request ? Thank you!

**Comment by GantMan** [comment]
I'm unable to do this right now.  Please feel free to re-assign.  I'm in the throws of TFLite work and I dont' have any extra time.

**Comment by gaikwadrahul8** [comment]
Hi, @GantMan 

Thank you for confirming. I am closing this issue now. If you feel that this feature request is still relevant, please let us know and we will reopen the issue. Otherwise, please feel free to create a new issue.

Thank you for your support and understanding.
