### ISSUE TITLE
Initialization of backend rn-webgl failed

### ISSUE THREAD

**Issue by huurray** [tensorflow/tfjs#4098]
![image](https://user-images.githubusercontent.com/41982439/96568295-befc4c00-1302-11eb-90ac-9593e1adbcf4.png)

```js
const BACKEND_TO_USE = 'rn-webgl';
  async function init() {
      await tf.setBackend(BACKEND_TO_USE);
      await tf.ready();
}
```
when i excute this, i've got that error in pic.
but if i turn off react native debug mode, it is find.
and that is in case of ios
when it comes to android, it just crashed app.

please help me!!!

my version is here!

"@tensorflow-models/blazeface": "0.0.5",
"@tensorflow-models/posenet": "^2.2.1",
"@tensorflow/tfjs": "^2.6.0",
"@tensorflow/tfjs-react-native": "^0.4.0",
"expo-camera": "^9.0.0",
"expo-gl": "^9.1.1",
"expo-gl-cpp": "^9.1.2",

**Comment by tafsiri** [comment]
Hi, so to clarify, if you turn off remote debugging the app works fine (on both platforms)?

If you need to use remote debugging you can use the cpu backend by calling `tf.setBackend('cpu')`. The rn-webgl backend does not support using remote debugging.

**Comment by huurray** [comment]
i see. i didn't know it doesn' t support using remote debugging. thanks!

**Comment by AKACC** [comment]
For my case, I have the same error even if I turn off remote debugger. `tf.setBackend('cpu')` would never work in any cases.

**Comment by AKACC** [comment]
Interesting found after a few days workaround.

I manually install @tensorflow/tfjs-backend-wasm and run `pod install`. The problem fixed by itself.

**After a few successful build, the error show up again**. I uninstall @tensorflow/tfjs-backend-wasm and run `pod install`. The problem fixed again.

Could you guys give me some insight on this? @tafsiri @huurray

**Comment by kevinchristianto** [comment]
I'm facing this problem too, while developing I'm just using the cpu backend, but when I changed to rn-webgl and buildRelease the app, it then crashed everytime it's executing `await tf.image.resizeBilinear(imageTensor, [224, 224])`
