### ISSUE TITLE
mobilenet model throw error with webgl but can run with cpu

### ISSUE THREAD

**Issue by lina128** [tensorflow/tfjs#4101]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No, run with tfjs benchmark tool.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): latest
- TensorFlow.js version (use command below): latest
- Browser version: Chrome latest
- Tensorflow.js Converter Version: latest

**Describe the current behavior**
This is part of the problem reported in https://github.com/tensorflow/tfjs/issues/4062
The problem reported here is webgl specific.

When benchmarking the ssd_mobilenet_v1_fpn_2018_07_03 model (can download from [here](https://gofile.io/d/OTXUKV)), cpu backend can run, but webgl backend throws error. 
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at getPackedSampler2D (shader_compiler.ts:721)
    at getPackedSamplerFromInInfo (shader_compiler.ts:118)
    at getInputSamplingSnippet (shader_compiler.ts:131)
    at shader_compiler.ts:56
    at Array.map (<anonymous>)
    at makeShader (shader_compiler.ts:56)
    at compileProgram (gpgpu_math.ts:90)
    at backend_webgl.ts:2574
    at MathBackendWebGL.getAndSaveBinary (backend_webgl.ts:2618)
    at MathBackendWebGL.runWebGLProgram (backend_webgl.ts:2573)
```
**Describe the expected behavior**
Can run.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

Serve the model in local (in the model folder, run npx http-server --cors). Open the tfjs benchmark tool index.html file in browser. In the custom model field, use http://localhost:8080/model.json. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by annxingyuan** [comment]
It would be worth seeing whether this issue goes away with `WEBGL_PACK` set to `false`. Although the packed path in the shader compiler gets hit no matter what because we *always* pack matrix multiplication (regardless of the value of `WEBGL_PACK`).

**Comment by xfffrank** [comment]
I trained a custom ssd-mobilenet-v2 with TF2 from [here](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz) and encountered the same issue when deploying the JS model. It works fine with CPU backend and reported an issue of `TypeError: Cannot read property '0' of undefined` with webgl.

Is this a bug or how can we avoid this problem ? @annxingyuan @lina128

**Comment by xfffrank** [comment]
> It would be worth seeing whether this issue goes away with `WEBGL_PACK` set to `false`. Although the packed path in the shader compiler gets hit no matter what because we _always_ pack matrix multiplication (regardless of the value of `WEBGL_PACK`).

Adding `tf.ENV.set('WEBGL_PACK', false)` solved the problem! Thank you! Using the `webgl` backend is a lot faster than the `cpu`.

**Comment by gaikwadrahul8** [comment]
Hi, @lina128 

Apologize for the delayed response and we're revisiting our older issues and checking whether those issues got resolved or not so as I see previous comment from @annxingyuan after setting `tf.ENV.set('WEBGL_PACK', false)` problem is solving and also user confirmed in previous comment so May I know still do you want to keep this issue open or could you please close this issue if it is resolved ?

If have I missed something here please let me know ? Thank you!
