### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by ghafran** [tensorflow/tfjs#4105]
When creating a model using AutoML with Multi Classification.

Getting this error from tensorflowjs when running 
``` const model = await tf.automl.loadImageClassification('/model/model.json');```
```
tfjs:17 Uncaught (in promise) TypeError: Cannot read property 'reduce' of undefined
    at e.t.transformGraph (tfjs:17)
    at e.t.loadSync (tfjs:17)
    at e.<anonymous> (tfjs:17)
    at u (tfjs:17)
    at Generator._invoke (tfjs:17)
    at Generator.forEach.e.<computed> [as next] (tfjs:17)
    at Um (tfjs:17)
    at o (tfjs:17)
```

html code:
```
<script src="https://unpkg.com/@tensorflow/tfjs"></script>
<script src="https://unpkg.com/@tensorflow/tfjs-automl"></script>
<img id="daisy" src="test2.jpg">
<script>
    async function run() {
        const model = await tf.automl.loadImageClassification('/model/model.json');
        const image = document.getElementById('daisy');
        const predictions = await model.classify(image);
        console.log(predictions);
        // Show the resulting object on the page.
        const pre = document.createElement('pre');
        pre.textContent = JSON.stringify(predictions, null, 2);
        document.body.append(pre);
    }
    run();
</script>
```

Model Multi-Classification, Edge, Exported for Tensorflowjs

Nothing crazy here just a simple export and run from browser. The model works fine when deployed in GCP with "Test&Use".

**Comment by ghafran** [comment]
@pyu10055 Not sure if this falls in your court :)

**Comment by ghafran** [comment]
Just tried this on models that were working previously. Looks like something changed during the model export or creation process on AutoML that is causing this issue.

**Comment by ghafran** [comment]
This seems to be fixed today. I retrained the models this morning and exported. Worked as expected. I love voodoo magic self healing :)

**Comment by ghafran** [comment]
This issue popped up again :(

**Comment by rthadur** [comment]
cc @pyu10055 @tafsiri

**Comment by pyu10055** [comment]
@ghafran can you share your model file? thanks

**Comment by ghafran** [comment]
Attached.
[model.zip](https://github.com/tensorflow/tfjs/files/5586533/model.zip)
Directly from the AutoML multi-classification tensorflowjs export. Edge.
@pyu10055

**Comment by ghafran** [comment]
[model.zip](https://github.com/tensorflow/tfjs/files/5586566/model.zip)
Attached. Just exported it from from AutoML Multi-classification using edge, faster performance.
Getting same error.

**Comment by ghafran** [comment]
@pyu10055 thanks for posting the fix. Your a life saver!

**Comment by ghafran** [comment]
@pyu10055 I see the fix has been completed. Can I regenerate the model now or do we need to wait for a production push?
Thanks.

**Comment by ghafran** [comment]
@pyu10055 This issues still seems to be happening. Do we know when the fix will be deployed?

**Comment by Vivek1907** [comment]
Even I am also facing the same issue :(
The model I exported about 3 weeks ago is working perfectly fine but the model I exported yesterday is not working and showing the error "cannot read property reduce of undefined" :(

**Comment by ghafran** [comment]
Our customers are getting agitated. Do have an estimate of when this will be pushed?

**Comment by pyu10055** [comment]
@ghafran The fix will be available in the next release, but meanwhile you can lock your tfjs version to 2.6.0, that should solve your problem.

**Comment by Vivek1907** [comment]
I think I found a solution

In your model.json file just remove this line:-
`"modelInitializer": {"versions": {}},`.

@ghafran  so here is the modified model.json

[model_json.zip](https://github.com/tensorflow/tfjs/files/5631115/model_json.zip)

Replace your model.json with the above file

So, this should work even with the latest tfjs version

**Comment by ghafran** [comment]
@Vivek1907 that work around fixes it! Thank you!

**Comment by zholmes1** [comment]
@Vivek1907 Worked for me too. Thanks!

**Comment by ghafran** [comment]
Just trained, exported, and ran the models with latest versions. All is good now.

**Comment by jml1996jsonhost** [comment]
Does anyone here have any insight about the problem described here: https://stackoverflow.com/questions/65402617/tensorflow-automl-model-in-react
