### ISSUE TITLE
[wasm] worker.js onmessage() captured an uncaught exception:Uncaught ReferenceError: t is not defined

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#4107]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.4 LTS
- TensorFlow.js installed from (npm or script link):
    "@tensorflow/tfjs-backend-wasm": "2.6.0",
    "@tensorflow/tfjs-core": "2.6.0"

- Browser version: Linux stable 85.0.4183.102

**Describe the current behavior**
Following [Using bundlers guide](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm#using-bundlers) to update [the minimal starter project code with latest @tensorflow/tfjs-backend-wasm (version 2.6.0)](https://github.com/BruceDai/tfjs/commit/143eef51e12261ba709762d881ede0e73862ee46), an error "worker.js onmessage() captured an uncaught exception:Uncaught ReferenceError: t is not defined" happened. 

**Describe the expected behavior**
The minimal starter project works well, none error happens.

**Standalone code to reproduce the issue**
Enabled two flags `WebAssembly SIMD support.` and `WebAssembly threads support` on chrome://flags tab, then execute following commands.

```shell
git clone https://github.com/BruceDai/tfjs
cd tfjs
git checkout webpack-wasm
cd tfjs-backend-wasm/starter/webpack/
npm install
npm run build
npm run watch
```

@annxingyuan Would you please help to look at this issue, thanks.

**Comment by annxingyuan** [comment]
Thanks @BruceDai for pointing this out. I believe I have a fix here: https://github.com/tensorflow/tfjs/pull/4121

**Comment by BruceDai** [comment]
@annxingyuan I could still reproduce the reported error "worker.js onmessage() captured an uncaught exception:Uncaught ReferenceError: t is not defined", any suggestion, thanks.

**Comment by annxingyuan** [comment]
@BruceDai did you test this on master?

**Comment by BruceDai** [comment]
@annxingyuan Yes, I tested on master branch with the commit id: [920794d](https://github.com/tensorflow/tfjs/commit/920794d97c0898cd44fa64e0273e97d901bfb873) which already included your [fixed patch](https://github.com/tensorflow/tfjs/commit/83f5004d55a94a9095d462bcbc4cefa2f1b09dbc), thanks.

**Comment by BruceDai** [comment]
@annxingyuan Any update? Thanks.

**Comment by BruceDai** [comment]
@annxingyuan Did this issue reproduce on your side? Thanks.

**Comment by BruceDai** [comment]
@annxingyuan I try latest tfjs-backend-wasm of 2.7.0, it works, suggest you upgrade package.json for starter/webpack project :) .
