### ISSUE TITLE
Low speed of Facemesh model on Mobile Web

### ISSUE THREAD

**Issue by yoshi-89** [tensorflow/tfjs#4108]
Hi, 
I am working with the facemesh model and have tried it on a few mobile devices, 
It gives a speed of 3-5Fps on [samsung a30](https://www.devicespecifications.com/en/model/cbf74f5d), 3-5 fps on [realme pro2](https://www.devicespecifications.com/en/model/8d2f4cea) and 9-10 Fps on [Pixel 4A](https://www.devicespecifications.com/en/model/c624541a)

So far I have tried using wasm web-workers for speed boost and was able to get it to 5-7fps on samsung a30 but I wanted to achieve a speed of 12-15fps on average devices I listed above

Can someone please help me on this

**Comment by ButzYung** [comment]
@yoshi-89 Which version of Facemesh are you using? You may want to stick with version 0.0.3 for speed, if you don't mind some minor accuracy issues on "roll" rotation (z-axis), or losing the latest iris detection feature in Face-landmarks-detection model (which is roughly 3 times slower than 0.0.3).

PS: On version 0.0.3, I can get about 15fps on a Snapdragon 845 phone (WASM backend).

**Comment by yoshi-89** [comment]
@ButzYung I tested on same devices using version 0.0.3 with webgl and wasm backend webworkers, but was not able get any significant improvements :(

**Comment by ButzYung** [comment]
@yoshi-89 You may need to enable WASM SIMD support to see significant performance boost, which is still a behind-the-flag feature on Chrome.

**Comment by annxingyuan** [comment]
Apologies for the delay - wanted to also mention that it's possible to disable iris detection in the faceLandmarksDetection model like so: 

```
const model = await faceLandmarksDetection.load(
    faceLandmarksDetection.SupportedPackages.mediapipeFacemesh);
const faces = await model.estimateFaces({ input, predictIrises: false });
```
