### ISSUE TITLE
WebGL backend for tensorflowjs loads the model (blazeface) very late

### ISSUE THREAD

**Issue by osmancakir** [tensorflow/tfjs#4117]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No.
- OS Platform and Distribution : Windows 10 Pro
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs
- TensorFlow.js version: 2.6.0
- Browser version: Firefox 81.0.2 (64-bit)
- Model: Blazeface: 0.0.5

I am trying to add blazeface model to my application. I have just figured out that when I use WebGL backend, the first call of estimateFaces() is taking too much time.

```javascript
console.log("estimate started") 
        const predictions = await model.estimateFaces(
          this.refVideo.current,
          returnTensors,
          flipHorizontal,
          annotateBoxes
        );
 console.log("estimate finished") // first time it is very slow with WebGL 15 seconds at least. 

```
When it is set to CPU or WASM backends, you don't see this slow down when loading the model for the first time. You can replicate/see this difference on the [blazeface demo](https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html) as well. Set the backend to WebGL from the upper right menu and open your cam. First mask of the face detection loads way way later than with WASM or CPU backends. 

**Describe the expected behavior**

I would expect similar loading time.

**Comment by rthadur** [comment]
@osmancakir i have not noticed any significance difference on blazeface demo, but for your code, the first detection is slow since the backend are caching the shader programs, the prediction after the first one should much faster and stable.You can add a warm up step after the model loads.
