### ISSUE TITLE
tensorflowjs_converter malforms the tensor values during conversion

### ISSUE THREAD

**Issue by joshSennep** [tensorflow/tfjs#4120]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: MacOS 10.15.6
- TensorFlow.js installed from: npm
- TensorFlow.js version: 2.3.0
- Browser version: Chrome 86.0.4240.80
- Tensorflow.js Converter Version: latest ~ 2.6.0

**Describe the current behavior**
I have created a custom model based on the Keras API in python:
```
keras.applications.Xception(
  weights='imagenet',  # Load weights pre-trained on ImageNet.
  input_shape=(range(*input_shape)),
  include_top=False
)
```

I add my own classification layers on top and train the model using AWS Sagemaker. I then convert my python model to a JS model: 
```
  tensorflowjs_converter --input_format=tf_saved_model ./scripts/tmp ./assets/model
```

And attempt to load that model into the FE but consistently get errors relating to the provided shape vs the inferred shape.
```
Error: Based on the provided shape, [3,3,728,1], the tensor should have 6552 values but has 5415
```

**Describe the expected behaviour**
I **assume** this is a problem with the conversion because I'm not passing any tensors to the JS model and the model correctly trains and evaluates using test data with my data files in the python environment. So I, therefore, expect not to see an error.

**Standalone code to reproduce the issue**
Here's a Repo link, you can see the model created if python, it's then saved, you can see the conversion script using tensorflowjs_converter & finally see how the react FE loads the model – https://github.com/joshSennep/tensorflow-converter-example

**Comment by pyu10055** [comment]
@joshSennep can you share the original saved model to we can try to reproduce the conversion step?

**Comment by joshSennep** [comment]
@pyu10055 it's in the repo under /scripts/tmp sorry I should have written that! This is what I get when exporting the in AWS sagemaker using the command `model.save(args.model_dir)`.

**Comment by pyu10055** [comment]
Hi @joshSennep, I have tried your model and it is converted correctly and I was able to run it in the browser without problem.
Your error might be related to the model file serving, please check your network tab in the chrome developer console, to see if there are any network errors for all the model files.

**Comment by joshSennep** [comment]
Thanks for looking @pyu10055 I can imagine how silly I might look! If you have an example you can show about how you've got it running in the browser that would be great. I'll also do my own work too. 

Thanks again.
