### ISSUE TITLE
`tensorflowjs_convert` fails to convert `saved_models` when there are no explict `tags` set in model

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4125]
`tensorflowjs_convert` fails to convert `saved_models` when there are no explicit `tags` set in model  

such models are working fine when loaded with `loadSavedModel()`, so it's not a model issue, but a converter issue  
and unfortunately, this is a common behavior for many models  

below is the output of `tf.node.getMetaGraphsFromSavedModel()` for one such model

```js
{
  tags: [ [length]: 0 ],
  signatureDefs: {
    default: {
      inputs: { images: { dtype: 'float32', tfDtype: 'DT_FLOAT', name: 'hub_input/image_tensor:0', shape: [ [Object], [Object], [Object], [Object], [length]: 4 ] } },
      outputs: {
        detection_boxes: { dtype: 'float32', tfDtype: 'DT_FLOAT', name: 'hub_input/strided_slice:0', shape: [ [Object], [Object], [length]: 2 ] },
        detection_class_entities: { dtype: 'string', tfDtype: 'DT_STRING', name: 'hub_input/index_to_string_Lookup:0', shape: [ [Object], [Object], [length]: 2 ] },
        detection_class_labels: { dtype: 'int32', tfDtype: 'DT_INT64', name: 'hub_input/strided_slice_2:0', shape: [ [Object], [Object], [length]: 2 ] },
        detection_class_names: { dtype: 'string', tfDtype: 'DT_STRING', name: 'hub_input/index_to_string_1_Lookup:0', shape: [ [Object], [Object], [length]: 2 ] },
        detection_scores: { dtype: 'float32', tfDtype: 'DT_FLOAT', name: 'hub_input/strided_slice_1:0', shape: [ [Object], [Object], [length]: 2 ] }
      }
    }
  }
}
```

there are more than few affected models are on `tfhub`:  
- <https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1>
- <https://tfhub.dev/google/on_device_vision/classifier/popular_wine_V1/1>
- <https://tfhub.dev/google/on_device_vision/classifier/popular_us_products_V1/1>
- <https://tfhub.dev/metmuseum/vision/classifier/imet_attributes_V1/1>

**Edit**: converting model *directly* from `tfhub.dev` using `tensorflowjs_converter --input_format tf_hub ...` works!  
but when same model is downloaded locally, it cannot be converted due to missing tags  

environment: tfjs 2.6.0 on ubuntu 20.10

**Comment by pyu10055** [comment]
@vladmandic unfortunately TensorFlow python [tf.saved_model.load](https://www.tensorflow.org/api_docs/python/tf/saved_model/load?hl=pl) does not support loading models without tags.
It will throw errors for these TFHub models. What is the tags/signatures you are seeing with node.js?

**Comment by vladmandic** [comment]
you can see the tags/signature in the example i've posted above - tags are empty and signature is `default`  

but what's strange is that:
- `tensorflowjs_convert --input_format tf_hub ...` works
- `tensorflowjs_convert --input_format tf_saved_model ...` fails for the same model downloaded from tfhub  

and quite a few models on `tfhub` are like that (efficientdet, centernet, imet, us products, etc.)

**Comment by pyu10055** [comment]
@vladmandic I have a fix for this now, please set the saved_model_tags to empty string `saved_model_tags=''` when the saved model contains no tags, thanks.

**Comment by vladmandic** [comment]
perfect!

i see the fix is currently blocked from merge, but it should be resolved soon so i'm closing this issue.
