### ISSUE TITLE
implement support for saved_models in browser environment

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4126]
tensorflow/js introduced new model type compared to tensorflow/python - `graph_model`  

unfortunately, very few of new models are published in `graph_model` format and require a conversion from `saved_mode` to `graph_model` (just check <tfhub.dev> - less than a third of models are available in `graph_model` format - and none of the models published in the last half a year)  

however, this leads to many issues as `tensorflowjs_converter` is really not up to par - and big divergence from tensorflow itself  
(as an example of issues, see #4125, #3903, #3942, #3930, etc...)  

`tfjs-node` introduced direct loading of `saved_model` using `tf.node.loadSavedModel`  

this allows many more models to be fully functional than relying on just `graph_model` support  

however, that feature is `tfjs-node` specific and cannot be used in browser  

there are valid use-cases to run tfjs in browser even for non-trivial items (and availability of webgl-acceleration on desktop is much easier than getting cuda-acceleration to run)

i also understand the reasoning for `graph_model` on small and/or mobile platforms (especially chunking which allows for parallel loading) - but when working on high speed local network, those reasons are not critical  

environment: tfjs 2.6.0 on ubuntu 20.10

**Comment by pyu10055** [comment]
@vladmandic direct saved model execution would be unlikely due the difference of tfjs and tensorflow. We are in the process to reconvert all the tfhub models with the latest converter, I will expect there could have quite some of the models can be converted now. 
We are working very hard to solve the divergence problem between python and TFJS, but unfortunately, it will still be expected due to WebGL API and device limitations.

**Comment by vladmandic** [comment]
it makes sense, but i'd thought to ask - i love tfjs, but there is quite a lot of frustration with converter experience so far.
i'm closing this issue.

**Comment by vladmandic** [comment]
@pyu10055 silly idea, but did anyone try running tensorflow.dll (software version, not cuda) through emscripten to get a full wasm backend?

Of course it's not as simple as that, but emscripten has gone a long way in the last year.
And being able to control build process of tensorflow can make it compatible.
