### ISSUE TITLE
facelandmarks-detection wrong when image dimensions change

### ISSUE THREAD

**Issue by dosomder** [tensorflow/tfjs#4131]
I am using @tensorflow-models/face-landmarks-detection: 0.0.2 with wasm backend. I am drawing an image onto a canvas and then using the canvas the classify the landmarks.

The first image is classified fine. But when I classify a second image with different dimensions, the classification is wrong. Example:
![grafik](https://user-images.githubusercontent.com/3040570/97169181-ea12ef80-1789-11eb-8cd7-332ca767b45a.png)

When I reload the facedetection model after classifying the first image, the prediction on the second image is correct. So I am not sure if the model is caching something

**Comment by yann86** [comment]
You have to remove previous calculated regionsOfInterest between classification of two differents images to prevent this issue:

`model.pipeline.regionsOfInterest  = []`

**Comment by dosomder** [comment]
@yann86 Thanks for the response. So is this expected behavior and not a bug? Is this documented somewhere?
