### ISSUE TITLE
extract face feature vector from face-landmarks-detection model

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4132]
it would be very useful to be able to extract face feature vector from  
[face landmarks detection model](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection)  
so it can be used to compare similarity between multiple processed faces

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by annxingyuan** [comment]
Hi @vladmandic - can you say a bit more about what you mean by 'face feature vector'? The model does not provide a face embedding, but did you have a certain vector in mind?

**Comment by vladmandic** [comment]
@annxingyuan 

that's exactly what i meant, just terminology is not really standardized.  

i understand the model as-is doesn't produce face embedding output, but i was thinking it could be calculated from an interim node?  

i could do the calculation, but reverse-engineering nodes to figure out what is what is too much.

**Comment by annxingyuan** [comment]
Hi @vladmandic - I've discussed with the model authors and it seems there's nothing really in the model architecture that's well suited for this. Your best bet might be to build a similarity detector based on the keypoints.

**Comment by vladmandic** [comment]
@annxingyuan thanks for checking
