### ISSUE TITLE
Cannot import Posenet into Observable.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#414]
I'm trying to create an observable notebook that imports Posenet.

The Observable [is here.](https://beta.observablehq.com/@oveddan/importing-posenet)

When trying to import PoseNet, it errors with 'Error: unable to load module'

Upon opening the chrome dev tools, the following error shows up:

> GET https://unpkg.com/crypto@1.0.1/index.js 404 
> Refused to execute script from 'https://unpkg.com/crypto@1.0.1/index.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

In the `Network` tab in chrome, it shows a '404' for `https://unpkg.com/crypto@1.0.1/index.js`

**Comment by oveddan** [comment]
@mbostock any ideas?

**Comment by mbostock** [comment]
tensorflow-models/posenet depends on tensorflow/tfjs at exactly 0.11.2, and this version isn’t usable in an AMD environment. This was fixed in tensorflow/tfjs#355 and tensorflow/tfjs-core#1092. I’ll send a PR to relax the specificity of posenet’s dependency.
