### ISSUE TITLE
"topk" kernel for the WASM backend 

### ISSUE THREAD

**Issue by trekhleb** [tensorflow/tfjs#4146]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): `v2.7.0`
- Are you willing to contribute it (Yes/No): `No`

**Describe the feature and the current behavior/state.**

_Feature_

Add support of `topk` kernel for the WASM backend.

This will allow the WASM based usage of object detection models (i.e. `ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8` model from [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md), converted to the GraphModel via TensorFlow.js Converter)

_Current Behavior_
Currently WASM backend is failing with the error `Error: 'topk' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen`.

**Will this change the current api? How?**

Current API should not be changed

**Who will benefit with this feature?**

Consumers of converted object detection models from [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) will be able to run them in browser on top of a WASM backend. According to [this official TF blogpost](https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.html) it may speed up the detection for up to two times. 

**Any Other info.**

**Comment by lcycoding** [comment]
+1 for this feature

**Comment by rthadur** [comment]
cc @annxingyuan
