### ISSUE TITLE
Slice.ts:72 Uncaught (in promise) TypeError: Cannot perform  Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by pallavikhtri25** [tensorflow/tfjs#4150]
Trying to use https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm using direct script tags tried the demo code for mobilenet...working fine but trying tf.setBackend('wasm') for coco-ssd throws error [][1]

Slice.ts:72 Uncaught (in promise) TypeError: Cannot perform 
Construct on a detached ArrayBuffer
at Float32Array.subarray (<anonymous>)
at slice (Slice.ts:72)
at Object.unpack [as kernelFunc] (ZerosLike.ts:23)
at p (engine.js:581)
at engine.js:639
at e.t.scopedRun (engine.js:444)
at e.t.runKernelFunc (engine.js:636)
at unstack_ (unstack.js:57)
at unstack__op (operation.js:51)
at e.t.scatter (tensor_array.js:265)

below are the script tags included

<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd"> </script>

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
<script>

**Comment by pallavikhtri25** [comment]
@pyu10055 @annxingyuan  any workaround for this ?

**Comment by hr0109** [comment]
Same problem here. My workaround is to download data from the Tensor and slice using js native functions.

**Comment by kylejmcintyre** [comment]
In case it's helpful, I encountered the same exception through use of the cloneTensor op:

```
backend_wasm.ts:201 Uncaught (in promise) TypeError: Cannot perform Construct on a detached ArrayBuffer
    at new Float32Array (<anonymous>)
    at BackendWasm.typedArrayFromHeap (backend_wasm.ts:201)
    at Object.identity [as kernelFunc] (Identity.ts:27)
    at kernelFunc (engine.ts:636)
    at engine.ts:703
    at Engine.scopedRun (engine.ts:478)
    at Engine.runKernelFunc (engine.ts:699)
    at Engine.runKernel (engine.ts:543)
    at clone_ (clone.ts:47)
    at clone__op (operation.ts:51)
    at cloneTensor (utils.ts:166)
    at Module.executeOp (graph_executor.ts:45)
```

**Comment by shmishra99** [comment]
Hi @pallavikhtri25 ,

Apology for the late response. I've replicated this issue with latest version of `@tensorflow/tfjs@4.4.0`. It seems like it is working as expected. For your reference I have added the code snippet below. 
```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd"></script>
</head>
<body>
<script>
 async function nan_test() {
    
   await tf.setBackend('wasm')
   let model = await cocoSsd.load()
   console.log("Model loaded successfully ",model )  
}
    nan_test();
</script>
</body>
</html>
```
Result : 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/124146945/235453756-0138d80a-5e80-4965-8826-186f9cf92c21.png">

Let me know if have I missed something ? Thank You!
