### ISSUE TITLE
tf.grad() gives the wrong result for vector valued functions

### ISSUE THREAD

**Issue by kennysong** [tensorflow/tfjs#4151]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.7.0
- TensorFlow.js version (use command below): 2.7.0
- Browser version: Chrome 86.0.4240.111
- Tensorflow.js Converter Version: None

**Describe the current behavior**

Here's a simple example:

```
const f = x => x.mul(tf.tensor([2,3]));
const g = tf.grad(f);

const x = tf.tensor([1]);
g(x).print();
```

This outputs:

```
Tensor
    [5]
```

**Describe the expected behavior**

This is the wrong shape. I believe `g` should return the tensor `[2,3]` (i.e. `∂f/∂x` should be a Jacobian vector?).

**Comment by rthadur** [comment]
@pyu10055 I was able to reproduce the same , can you please take a look ?

**Comment by pyu10055** [comment]
@rthadur are you getting [5] as the print out?

Here is my execution:

```
const f = x => x.mul(tf.tensor([2.3]));
undefined
g = tf.grad(f)
ƒ (t,n){var r=$g(t,"x","tf.grad",null),a=null!=n?$g(n,"dy","tf.grad"):null;return Hg.tidy((function(){var t=Hg.gradients((function(){return e(r)}),[r],a),n=t.value,i=t.grads;return null!=a&&cv(n.shape,…
const x = tf.tensor([1])
undefined
g(x).print()
tfjs:17 Tensor
    [2.3]
```

**Comment by pyu10055** [comment]
I believe the output is correct, I verified with python:

```python
>>> x = tf.Variable(1.0)
>>> with tf.GradientTape() as tape:
...   y = x * [2, 3]

>>> dy_dx = tape.gradient(y, x)
>>> dy_dx.numpy()
5.0
```

**Comment by kennysong** [comment]
@pyu10055 Oh true. It looks like this is [a point of confusion](https://github.com/tensorflow/tensorflow/issues/29064) in Python as well. 

It may be a good idea to add a sentence in the documentation (or a console warning) of `tf.grad` that `f` must be scalar valued, otherwise the function will silently add a `.sum()` to `f`.

FWIW, it looks like the right way to do this in Python is with [`tf.jacobian`](https://www.tensorflow.org/guide/advanced_autodiff#jacobians), which is not available in TF.js.
