### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took <N>ms tfjs hand model demo 

### ISSUE THREAD

**Issue by delebash** [tensorflow/tfjs#4153]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
Windows 10 x64
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
tfjs version used in online demo at https://storage.googleapis.com/tfjs-models/demos/handpose/index.html

**Describe the current behavior**
1) In Chrome open https://storage.googleapis.com/tfjs-models/demos/handpose/index.html
2) Open DevTools
3) After the detection is running refresh the page

4) Error [Violation] 'requestAnimationFrame' handler took ms is thrown after refresh

**Describe the expected behavior**
No error after refresh

**Comment by rthadur** [comment]
I was not able to reproduce the same in MAC OS , may be this is specific to windows cc @pyu10055

**Comment by delebash** [comment]
ok, it does not seem to be interfering with performance.  Thanks
