### ISSUE TITLE
need corresponding relationship between the version numbers of keras tensorflowjs tfjs

### ISSUE THREAD

**Issue by zhubinsheng** [tensorflow/tfjs#4155]
The incompatibility between versions leads to many problems. I think it is necessary to give the corresponding relationship between the version numbers of keras tensorflowjs tfjs

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by pyu10055** [comment]
In general TFJS provides a subset of layers that is available on keras, as wells as tf.keras.
@zhubinsheng can you provide more details on what type of errors you are seeing?

**Comment by zhubinsheng** [comment]
> In general TFJS provides a subset of layers that is available on keras, as wells as tf.keras.
> @zhubinsheng can you provide more details on what type of errors you are seeing?

I'm just a beginner. I use keras to convert the model of Darknet into H5 file, and then tensorflowjs_ Covert is transformed into a model that tsjs can use, a new version of tensorflowjs_ Covert will be converted into bin files and cannot be used in tsjs, but the old ones will not

**Comment by rthadur** [comment]
@zhubinsheng please provide error details which you are seeing ?
