### ISSUE TITLE
Making separable Convolutions more efficient

### ISSUE THREAD

**Issue by susmeet-jain** [tensorflow/tfjs#4168]
Currently the time efficiency for depthwise separable convolutions in tfjs is only as good as regular convolutions.

Depthwise separable convolutions need a lot less multiplication operations then regular convolutions. And this makes them much faster on other platforms including tensorflow.

Requesting support to utilize the efficient architecture optimisations of the depthwise convolution to make it more time effiecient.

**Comment by pyu10055** [comment]
@susmeet-jain I want to make sure which model type you are using, are you using the Keras layers with TFJS layers model or converted the saved model to TFJS graph model?

**Comment by susmeet-jain** [comment]
Thanks @pyu10055, that is an important detail to add. I am currently converting a saved model to a tfjs graph model. Not writing a TFJS layers model.

**Comment by pyu10055** [comment]
thanks you for the clarification, are you referring to [this keras layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv2D)?
It would be really helpful if you can provide an examples that demonstrate the performance in a meaningful way, so we can track down the performance bottleneck. Thanks!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
