### ISSUE TITLE
tf.tidy with bidi rnn layer is not working since v0.11.6

### ISSUE THREAD

**Issue by rodrigopivi** [tensorflow/tfjs#418]
#### TensorFlow.js version
0.11.6 (the code works on v0.11.5)
#### Browser version
Chrome 66.0.3359.181 (Build oficial) (64 bits)
#### Describe the problem or feature request
The code provided works from v0.11.2 to v0.11.5 but fails on v0.11.6 with this error:
```
Unhandled promise rejection Error: Layer lstm_cell_LSTMCell1 is not connected, no input to return.
    at new AttributeError (errors.js:21)
    at LSTMCell.get [as input] (topology.js:193)
    at walkTensorContainer (util.js:403)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
    at walkTensorContainer (util.js:406)
```

#### Code to reproduce the bug / link to feature request
```
const concated = tf.layers.concatenate().apply([someLayer, otherLayer, etc]);
const biLstm = tf.layers.bidirectional({
    layer: tf.layers.lstm({ units: 10, returnSequences: true }),
    mergeMode: 'concat',
}).apply(concated);
```

**Comment by caisq** [comment]
@rodrigopivi I am having trouble reproducing your error. See the added unit test in https://github.com/tensorflow/tfjs-layers/pull/236, which closely replicates your reproduction code. I don't get an error in that unit test.

**Comment by caisq** [comment]
I also tried the code in CodePen and it seems to work there as well:
https://codepen.io/caisq/pen/zadPZM

**Comment by caisq** [comment]
@rodrigopivi Any thoughts? I want to make sure I didn't miss anything important.

**Comment by rodrigopivi** [comment]
@caisq thanks for your help, sorry for the late reply, i was afk, currently still traveling (world cup fan here), but this is the model that was failing for me when upgrading tfjs https://github.com/rodrigopivi/BotanicalDimensions/blob/master/typescript/src/models/ner.ts

If its not good enough example for now, i hope to take some time very soon to work from your codepen, thanks again

**Comment by rodrigopivi** [comment]
ok this is the error i was getting reproduced on codepen https://codepen.io/rodrigopivi/pen/jKQKeE

The problem actually seems to be the tf.tidy function, used to work that way, otherwise not sure how to pass a custom optimizer and wrap with tf.tidy. thanks for your help!
