### ISSUE TITLE
executeAsync `cannot read property 'getItem' of undefined`

### ISSUE THREAD

**Issue by adriang133** [tensorflow/tfjs#4183]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **macOS 10.15.6**
- TensorFlow.js installed from (npm or script link): **npm**
- TensorFlow.js version (use command below): **2.7.0**
- Browser version: **Chrome 86.0.4240.183**
- Tensorflow.js Converter Version: **2.7.0**

**Describe the current behavior**
I have a model ensemble, roughly generated like this:

```python
inputs = trained_models[0].inputs # trained_models is a list of keras.Model instances

y_pred = [model(inputs) for model in trained_models]

y_avg = keras.layers.average(y_pred)

model_ensemble = keras.Model(inputs=inputs, outputs=y_avg, name='ensemble')

model_ensemble.save('...')
```

I then export it via 
```bash
tensorflowjs_converter --input_format=tf_saved_model model/path target/path
```

It loads fine in Javascript land but when I try to predict something, i.e.
```javascript
const model = await loadGraphModel('...');
await model.executeAsync(...)
```

I get this error

```
Uncaught (in promise) TypeError: Cannot read property 'getItem' of undefined
    at executors_control_executor_executeOp (webpack-internal:///483:48432)
    at eval (webpack-internal:///483:49466)
    at operations_operation_executor_executeOp (webpack-internal:///483:49506)
    at executor_graph_executor_GraphExecutor.processStack (webpack-internal:///483:50136)
    at executor_graph_executor_GraphExecutor.executeWithControlFlow (webpack-internal:///483:50097)
    at async executor_graph_executor_GraphExecutor._executeAsync (webpack-internal:///483:50043)
    at async executor_graph_model_GraphModel.executeAsync (webpack-internal:///483:50542)
```
**Describe the expected behavior**
It should work.

**Standalone code to reproduce the issue**
I don't have a minimal example, but my exported model is at https://www.dropbox.com/s/bak5vikeu86rzz8/ensemble.zip?dl=0. 

To reproduce
```
import { loadGraphModel } from '@tensorflow/tfjs-converter';
const model = await loadGraphModel('path/to/model');

const randomInput = {
    'ts_input': tf.ones([1, 101, 3]),
    'shop_category': tf.ones([1, 1]),
    'bucketized_qoh': tf.ones([1, 101]),
}

const pred = await model.executeAsync(randomInput);
```

Note: Everything works if I export just one of the ensembled models, so it might be related to that.

**Comment by pyu10055** [comment]
@adriang133 Thank you for reporting the issue, it would be really helpful if you can share the exact model that we can reproduce this error. thanks!

**Comment by adriang133** [comment]
@pyu10055 There's a link to the model generated by tensorflowjs_converter above. 

Do you mean the code for generating the python model ?

**Comment by pyu10055** [comment]
@adriang133 yes if you can provide the python model would be great.

**Comment by pyu10055** [comment]
@adriang133 I tried your converted TFJS model, I works with the code you provided.
I am confused in what circumstances this would fail?

**Comment by adriang133** [comment]
Tried it in a fresh project and it worked. Must've been something else in my project that caused it to fail. 

Sorry about that!
