### ISSUE TITLE
fromPixels() must be an HTMLVideoElement but was HTMLVideoElement

### ISSUE THREAD

**Issue by Fantantonio** [tensorflow/tfjs#4189]
> Uncaught (in promise) Error: pixels passed to tf.browser.fromPixels() must be either an HTMLVideoElement, HTMLImageElement, HTMLCanvasElement, ImageData in browser, or OffscreenCanvas, ImageData in webworker or {data: Uint32Array, width: number, height: number}, but was HTMLVideoElement

This error is showing up in the console.log of a node.js + nw.js project.

It is triggered by this js code:
```
const tf = require('@tensorflow/tfjs');
const webcam = document.getElementById("webcam");

let new_tensor = tf.browser.fromPixels(webcam);
```

webcam refers to this HTML element:
```
<video id="webcam" autoplay muted></video>
```

The js code is executed after the video element is loaded and it's working if I print a video screenshot into a canvas and then I use that as input for the `fromPixels` method:
```
const tf = require('@tensorflow/tfjs');
const canvas = document.getElementById("canvas");

let ctx = canvas.getContext('2d');
ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
let new_tensor = tf.browser.fromPixels(canvas);
```

canvas refers to this HTML element:
```
<canvas id="canvas"></canvas>
```

- Node.js: 14.6.0
- nwVersion: 0.48.3
- nwjs-builder-phoenix: 1.15.0
- Windows 10 Home: 20H2
- TensorFlow.js installed from: npm
- TensorFlow.js version: 2.7.0

**Comment by tafsiri** [comment]
Could you provide a minimal reproduction that we could run to see the error? Something like https://codepen.io/tafsiri/pen/qBNyMxP?editors=1111 but in the environment that you are experiencing the issue in.

Also could you post the result of the following in your app.

```js
const webcam = document.getElementById("webcam");

console.log('webcam', webcam)
console.log('webcam instanceof HTMLVideoElement', webcam instanceof HTMLVideoElement)
```

**Comment by Fantantonio** [comment]
The code you provided generate this output in console:


> webcam <video id=​"webcam" autoplay muted>​</video>​
> webcam instanceof HTMLVideoElement true


I also tryied to run `tf.browser.fromPixels(webcam);` inside a if statement like so:
```
if (video instanceof HTMLVideoElement) {
        const input_tensor = tf.browser.fromPixels(video);
} else {
        console.log("not an HTMLVideoElement");
}
```

And the if condition is satisfied so the error occur

The problem comes from a node.js + nwjs project so I don't know if there's an online platform that allows to reproduce this issue so easily.
For the moment I uploaded a repo with all the testing code and the steps to reproduce it at this [link](https://github.com/Fantantonio/tfjs_issue_4189_test); if someone knows a better way just let me know.

**Comment by tafsiri** [comment]
After digging around a bit, it looks like your project is running in [separate context mode](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#separate-context-mode) and there are two JS contexts in which code is run. Your code is being run in the browser context and the tfjs library code is being run in the node context. In the node context `video instanceof HTMLVideoElement` returns false. The nw.js docs suggest that browser api's aren't usable in the node context so there may be incompatibility there. 

Their docs suggest you can switch to [mixed context mode](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#mixed-context-mode), I tried that by adding the following entry to the package.json and then it worked.
```
"chromium-args": "--mixed-context",
```

If you want to stay in separate context mode (and I don't know enough about nw.js to know the advantages and disadvantages of each) you would need to not use any of the browser specific apis of tfjs.

**Comment by Fantantonio** [comment]
Thanks for your time and for linking the documentation!
That's the way to get it to work
