### ISSUE TITLE
Image Processing using a pre trained keras model in tensorflow.js

### ISSUE THREAD

**Issue by Subhambh** [tensorflow/tfjs#419]
i have a pre trained keras model consisting of u-net architecture i have converted them to json file
while running the code in browser i am getting the following error

Uncaught (in promise) Error: Unknown layer: Lambda
    at new t (tfjs@0.11.6:1)
    at deserializeKerasObject (tfjs@0.11.6:1)
    at deserialize (tfjs@0.11.6:1)
    at p (tfjs@0.11.6:1)
    at t.fromConfig (tfjs@0.11.6:1)
    at deserializeKerasObject (tfjs@0.11.6:1)
    at deserialize (tfjs@0.11.6:1)
    at tfjs@0.11.6:1
    at n (tfjs@0.11.6:1)
    at Object.next (tfjs@0.11.6:1)

code in js
<html>
	<title> TensorFlow </title>
	<head>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
	<script>
		const model12 = tf.loadModel ("{{ url_for('static', filename='model.json') }}");
		
    </script>
	</head>
	<body>
	</body>
</html>

**Comment by caisq** [comment]
@Subhambh Lambda layers are not supported currently. In fact, it is unlikely we'll support it in the future, because Lambda layers from Python consists of Python code serialized as strings. It is hard to execute Python code in JavaScript.

**Comment by Subhambh** [comment]
I was able to upload my keras model but to start prediction i was unable to upload image from my static folder 
please help
code in js:
<html>
	<title> TensorFlow </title>
	<head>
	
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
	
	<script>
	
		const model12 = tf.loadModel ("{{ url_for('static', filename='model.json') }}");
		
		const example = tf.fromPixels("{{ url_for('static', filename='myfig.PNG') }}");
	   
	   
	   
	   
    </script>
	</head>
	<body>
	</body>
</html>



error:
tfjs@0.11.6:1 Uncaught TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': No function was found that matched the signature provided.
    at tfjs@0.11.6:1
    at callAndCheck (tfjs@0.11.6:1)
    at uploadPixelDataToTexture (tfjs@0.11.6:1)
    at e.uploadPixelDataToTexture (tfjs@0.11.6:1)
    at e.fromPixels (tfjs@0.11.6:1)
    at e.fromPixels (tfjs@0.11.6:1)
    at e.fromPixels (tfjs@0.11.6:1)
    at tfjs@0.11.6:1
    at e.tidy (tfjs@0.11.6:1)
    at Object.r.value [as fromPixels] (tfjs@0.11.6:1)

**Comment by TheHidden1** [comment]
wrap the image in a [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement)

**Comment by Subhambh** [comment]
I have wrapped the image in html but while prediction got the following error

expected dense_Dense1_input to have 2 dimension(s), but got array with shape [597,800,3]

code in js
<html>
	<title> TensorFlow </title>
	<head>
	
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
	<img id='Cells' src='../static/fig.PNG' alt='BVI Cells'>

	<script>
		
		
		const model12 = tf.loadModel ("{{ url_for('static', filename='model.json') }}");
		var cells = document.getElementById('Cells');
		console.log(cells.alt);
		document.write(cells);
		const img = tf.fromPixels(cells);
	 
		const prediction = model.predict(img);

		
	   
	   
	   
    </script>
	</head>
	<body>
	</body>
</html>

**Comment by Subhambh** [comment]
I have wrapped the image but unable to get prediction
error : 
(index):16 Uncaught TypeError: model.predict is not a function
    at (index):16


code in js :
<html>
	<title> TensorFlow </title>
	<head>
	
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
	<img id='Cells' src='../static/fig.PNG' alt='BVI Cells'>

	<script>
		
		const model = tf.loadModel ("{{ url_for('static', filename='model.json') }}");
		var cells = document.getElementById('Cells');
		console.log(cells.alt);
		document.write(cells);
		const img = tf.fromPixels(cells);
	        const prediction = model.predict(img);
		
    </script>
	</head>
	<body>
	</body>
</html>

**Comment by Subhambh** [comment]
tried loading the model using async / await still the error is same

CODE IN JS:

html>
	<title> TensorFlow </title>
	<head>
	
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
	<img id='Cells' src='../static/fig.PNG' alt='BVI Cells'>

	<script>

	   
		async function loadModel(){
			console.log("inside load model");
			const mod = await tf.loadModel("{{ url_for('static', filename='model.json') }}");
			return(mod)
		}
		model = loadModel();
		console.log(model);
		var cells = document.getElementById('Cells');
		console.log(cells.alt);
		
		const example = tf.fromPixels(cells);
	    model.predict(example);
		
	   
	   
	   
    </script>
	</head>
	<body>
	</body>
</html>

**Comment by Subhambh** [comment]
@TheHidden1  and @caisq  help would be appreciated

**Comment by TheHidden1** [comment]
try ```<script async>``` &``` const model = await  tf.loadModel();```

it should be somting like this 
```HTML
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.6"> </script>
<img id='Cells' src='../static/fig.PNG' alt='BVI Cells'>

<script async>
    const model =  await tf.loadModel("{{ url_for('static', filename='model.json') }}");
    console.log(model);
    var cells = document.getElementById('Cells');
    console.log(cells.alt);

    const example = tf.fromPixels(cells);
    const data = model.predict(example);

    example.dispose()
    data.dispose()



</script>
</head>
<body>
</body>
```

**Comment by jamessmith123456** [comment]
i meet the same problem...any friends has solutions worked?waiting...

**Comment by ceylanb** [comment]
Same problem...
