### ISSUE TITLE
Error: The Node.js native addon module (tfjs_binding.node) can not be found at path

### ISSUE THREAD

**Issue by Someguy1834** [tensorflow/tfjs#4191]
**System information**
- Ubuntu 20.04.1 LTS
- npm i @tensorflow/tfjs-node
- 2.7.0

**Describe the problem**
No matter what version I use, trying to use `const tf = require('@tensorflow/tfjs-node')` will just give back this error:
The Node.js native addon module (tfjs_binding.node) can not be found at path: /home/sopur/JavaScript/tensorflowtest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I typed `npm init -y` and `npm i @tensorflow/tfjs-node` in the terminal, and then made a file called "index.js" and typed `const tf = require('@tensorflow/tfjs-node')` into it.

**Comment by toilavic** [comment]
same, looking for the solution

**Comment by hayriyigit** [comment]
Can you show me the output of `npm i @tensorflow/tfjs-node` ?

**Comment by hayriyigit** [comment]
Can you run this and try to reinstall tfjs?
`apt-get install build-essential`

**Comment by toilavic** [comment]
@hayriyigit  hello, i fixed succesfully, my node_modules is old-version (or missing something), so that i deleted it and reinstall again, and this is working.

**Comment by Someguy1834** [comment]
@hayriyigit Tensorflow is installed normally. This is what it logged in the console:
`
added 129 packages, and audited 129 packages in 26s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
`

**Comment by pyu10055** [comment]
looks like the issue is resolved. closing this.
