### ISSUE TITLE
"Source" links at js.tensorflow.org take you to a shallow factory function, which may be confusing.

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#420]
#### TensorFlow.js version
0.11.6
#### Browser version
doesn't matter
#### Describe the problem or feature request
clicking the source link takes the user to the "exports.ts", which then requires them to navigate to the top to determine the actual location of the definition of the symbol

#### Code to reproduce the bug / link to feature request
Click the "source" link at js.tensorflow.org/API/0.11.6/#layers.dense

![image](https://user-images.githubusercontent.com/547150/41296851-d2efa53c-6e2b-11e8-8c68-8db232118762.png)

**Comment by nsthorat** [comment]
I'm not sure there's really much we can do for this unfortunately, I don't think we want to generically walk the AST to find out what it's calling. From there, at least the user can dig in, so I'm going to close this out.
