### ISSUE TITLE
Official Handpose Demo not working

### ISSUE THREAD

**Issue by djthegr8** [tensorflow/tfjs#4206]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): bundle, I believe
- TensorFlow.js version (use command below): N/A
- Browser version: Chrome
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
When the Handpose demo is opened at [this site](https://storage.googleapis.com/tfjs-models/demos/handpose/index.html) then it errors with the console showing the below Error.
![image](https://user-images.githubusercontent.com/44142719/98674628-18462100-237f-11eb-8dba-e9674ee987a3.png)

**Describe the expected behavior**
Works as required
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
N/A
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
N/A

**Comment by rthadur** [comment]
@djthegr8 I tried on windows 10 and it is working as expected , I don't have a Win7 machine to reproduce the same.

**Comment by djthegr8** [comment]
@rthadur I opened in a Windows 10 laptop, please check using the WASM backend. My console output is below 
![image](https://user-images.githubusercontent.com/44142719/98942879-af90ad00-2514-11eb-8bed-457216d8e311.png)

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by djthegr8** [comment]
Have added a PR to update the demo, https://github.com/tensorflow/tfjs-models/pull/539 while also adding proper WASM SIMD support, as the model ops don't fit on the standard WASM backend.

**Comment by djthegr8** [comment]
> @djthegr8 It was running fine on my machine , can you please provide your system specs, Thank you.
> 
> cc @annxingyuan

Did you attempt WASM? My PC is Win10-x64, i7-10th gen, and 8GB RAM

**Comment by djthegr8** [comment]
Have attempted to resolve in [#539 in tfjs-models](https://github.com/tensorflow/tfjs-models/pull/539), kindly review...

**Comment by djthegr8** [comment]
PR merged, will await push to demo
