### ISSUE TITLE
Setting trainable of a tf.layers.Layer and/or a tf.Model should set the trainable bit of the underlying tf.Variable

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#421]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.6

**Comment by caisq** [comment]
Thanks, @bileschi, for the questions.

Let's consider the more general case: A trainable layer has N trainable variables M non-trainable variables initiailly. 

When the user sets layer.trainable to false, all the N + M variables will be set to non-trainable.
Later, when the user sets layer.trainable to true, the state of the N trainable variables and M non-trainable variables will be all restored.

This means that a layer must keep track of the initial state of all its variables, namely which are trainable and which are not. I believe the Layer class is already doing that so it should be relatively easy to do that.

A layer that is non-trainable to begin with will always have 0 trainable variables no matter how its trainable attribute is set.

There is also the question of what happens when a Model's trainable attribute is set. The answer is that it's going to recursively set the trainable attribute of all the layers and (sub)Models it contains. This logic is orthogonal with the logic of setting a layer's weight variables as described above.

**Comment by nsthorat** [comment]
Is this fixed, @caisq?

**Comment by caisq** [comment]
@nsthorat It is now :) Sorry for the delay.
