### ISSUE TITLE
Tensorflow and Tensorflowjs giving different predictions

### ISSUE THREAD

**Issue by purviljain** [tensorflow/tfjs#4214]
I have trained a model in Tensorflow and converting the model to Tensorflow.js.

After conversion, my model is predicting different from the Python TF model even with the same data.

### Code for prediction in tfjs-node: [Codesandbox](https://codesandbox.io/s/tensorflow-bug-uplara-y6n1i)

Are these value differences in the output tensors between python and javascript expected? If yes, why? 

I have a series of 5 models, will these differences have a huge impact on my model accuracy? Will these inaccuracies accumulate? 
I am getting different outputs at the end of my pipeline of models-
![image](https://user-images.githubusercontent.com/32229345/98741537-d777f780-23d2-11eb-9e7e-a6657cd0af05.png)
Left- python (desired)
Right- Javascript

Converted my model using- #4212

**Comment by rthadur** [comment]
@purviljain this question has been answered in #4212 , i assume we can close this and track at one place . Thank you
