### ISSUE TITLE
browser packaging for `tfjs-backend-wasm` module is broken

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4217]
browser packaging for `tfjs-backend-wasm` modules is broken  
it can be loaded as a script tag, but not as a modul bundle

tried 3 different imports:
```js
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm';
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js';
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js';
```

and it tries to load `perf_hooks` and fails  
also, **browser** module should not require **nodejs** specific requires such as `path` and `fs`  

compare generated output of `tfjs-backend-webgl` and `tfjs-backend-wasm` modules headers:

`@tensorflow/tfjs-backend-webgl/dist/tf-backend-webgl.es2017.js`:
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@tensorflow/tfjs-core')) :
  typeof define === 'function' && define.amd ? define(['exports', '@tensorflow/tfjs-core'], factory) :
  (global = global || self, factory(global.tf = global.tf || {}, global.tf));
}(this, (function (exports, tf) { 'use strict';
```

`@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js`:
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@tensorflow/tfjs-core'), require('path'), require('fs'), require('worker_threads'), require('perf_hooks')) :
  typeof define === 'function' && define.amd ? define(['exports', '@tensorflow/tfjs-core', 'path', 'fs', 'worker_threads', 'perf_hooks'], factory) :
  (global = global || self, factory((global.tf = global.tf || {}, global.tf.wasm = global.tf.wasm || {}), global.tf, global.path, global.fs, global.worker_threads, global.perf_hooks));
}(this, (function (exports, tfjsCore, path, fs, worker_threads, perf_hooks) { 'use strict';
```

workaround is to import to compiled sources entry point instead and not use bundles at all - this works!:
```js
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';
```

also, module rebuild should not require full recompilation of binary wasm files by default  
for example, rebuild of `tfjs-node` downloads latest tensorflow binary and compiles typescript to module with bindings to downloaded binary  
but rebuild of `tfjs-backend-wasm` attempts to rebuild .wasm files using `bazel` each time - this is not inline with the rest of tfjs  

environment: tfjs 2.7.0 with chrome 86

**Comment by tafsiri** [comment]
Can you tell us more about what environment you are seeing this in. Are you importing the module in a browser or running this through a bundler/build tools?

**Comment by vladmandic** [comment]
i've tried both - running in browser directly and running through the bundler.

header of `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js` is clearly wrong - that is supposed to be a browser bundle and yet it includes requires for `fs, `path`, `perf_hooks`. no other esm bundle (tfjs-core, tfjs-backend-webgl, tfjs-backend-cpu, etc.) has that.

**Comment by tafsiri** [comment]
For the bundler options, the first import `import {setWasmPaths} from '@tensorflow/tfjs-backend-wasm';` is similar to what [we have here in our webpack example](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm/starter/webpack) and I updated that to 2.7.0 and could build and serve the page without an error. Would you be able to share a small repo with a reproduction of the error you are seeing?

For the browser case neither, `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js` nor `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js` provide ESM modules. So they generally won't work with `import` (without something that can do pre-processing). We are planning on providing pre-bundled esm module builds in upcoming releases. This will probably be the suggested path for using esm modules directly in browser (but isn't something we explicitly support at the moment).

As you may have seen `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';` does provide an es module, though i'm surprised it worked directly in your browser since it doesn't include the file extensions when importing. Note this is the file that a bundler that handle esm modules should resolve the package to (it is the path used in our "module" entry in our package.json).

cc @annxingyuan

**Comment by vladmandic** [comment]
Sorry, when I said it works with no bundler, that's one level removed - my library uses tf and it creates bundle.  
Then I can use it inside html+js and that doesn't need to be bundled anymore. Ignore all notes on 'no bundler'.  

Now, when it comes to bundlers, different bundlers generate different code - and some just strip unresolved extra requires.
In my case, I use `esbuild` which does as little processing as possible and is about 10x faster than webpack/.

1. `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm';`
Loads correctly, but fails on first usage.  
Error: `'cast' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen`  
It just happens that `cast` is the first tfjs function called - basically, `tfjs-backend-wasm` loaded this way does not register kernel functions on its own.  

2. import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js';
Does not load because of erroneous requires in header.  
Error `ReferenceError: require is not defined at empty:perf_hooks:1`  

3. import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js';
Does not load because of erroneous requires in header.  
Error `ReferenceError: require is not defined at empty:perf_hooks:1`  

4. `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';`
Works end-to-end.  

Now, some bundlers may "survive" mistakes, but I don't see how this can be valid for a Browser usage:
`require('path'), require('fs'), require('worker_threads'), require('perf_hooks')`

And that is in the header of generated `tf-backend-wasm.js` and `tf-backend-wasm.es2017.js` while no other part of TFJS intended for browser usage has that.

**Comment by vladmandic** [comment]
UPDATE:

I just noticed that even when I'm importing:
`import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';`
and everything works fine, there is a ghost request towards web server:
`GET/2.0 404 /dist/empty:perf_hooks`

This is because `dist/index.js` still uses a bundled `dist/miniprogram/index.js` which has the silly header with excessive requires!

I think it all comes down to errors in `package.json`.
(which i cannot verify right now because `tfjs-backend-wasm` cannot be rebuild without binary rebuild using `bazel`)

both `tfjs-backend-webgl/package.json` and `tjfs-backend-cpu/package.json` contain:
```json
  "browser": {
    "util": false,
    "crypto": false
  },
```

while `tfjs-backend-wasm/package.json` contains:
```json
  "browser": {
    "fs": false,
    "path": false,
    "worker_threads": false,
    "perf_hooks": false
  },
```

**Comment by vladmandic** [comment]
UPDATE: there is a related pending pull request: <https://github.com/tensorflow/tfjs/pull/3816/commits/f5fe8e89aa316d3d49dd0beb5df8061249f60274>

**Comment by tafsiri** [comment]
I think this basically boils down to how the bundler you are using handles different kinds of modules. 

> import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';
Works end-to-end.

- If your bundler isn't following the module entry, but you do want to consume es modules as part of your build, `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';` is a fine way to go (that is what the module entry points to). Though you may want to file a bug with your bundler on 'module' entry support.

> import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm';
Loads correctly, but fails on first usage.
Error: 'cast' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen

- This makes me think that your bundler is following the module entry correctly. If you are seeing errors with kernels not being registered it means the bundler is also pretty aggressively tree shaking the import and thus kernels are not being registered. This should be fixable by adding an side-effect oriented import `import '@tensorflow/tfjs-backend-wasm/dist/index.js';`


```
"browser": {
	"fs": false,
    "path": false,
    "worker_threads": false,
    "perf_hooks": false
},
```

- These entries tell your bundler to ignore these imports. The spec being used is even linked to from [the esbuild docs](https://esbuild.github.io/getting-started/#bundling-for-the-browser) (see the [browser field ](https://github.com/defunctzombie/package-browser-field-spec)link in the last paragragh). Its possible there is a bug in the bundler causing those 404 requests.

> This is because dist/index.js still uses a bundled dist/miniprogram/index.js which has the silly header with excessive requires!

I'm not entirely sure what this means but I don't think its accurate. [This is the content of `dist/index.js`](https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/index.js) and there isn't a path from that to loading the contents of `dist/miniprogram/index.js`.

I really think this is an issue with your bundler or how you are configuring it/your build.

**Comment by vladmandic** [comment]
yes, `miniprogram` is a a red herring, sorry about that, it's just a copy of minified cpu backend that is internally used by everyone.
`build-npm.sh:cp dist/tf-backend-cpu.min.js dist/miniprogram/index.js`

and lets assume `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm';` fails because bundler is too aggresive with tree shaking. i'll handled that on the bundler side.

so there are no issues with `import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm/dist/index.js';`

but what is the purpose of: `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js` and `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js`?
every other part of tfjs can be imported from such bundles, but `wasm` must be imported from `dist/index.js`?

also, why is `wasm` rebuild process trying to rebuild `*.wasm` binaries using `bazel` every time? no other part of tfjs does that!
e.g., `tfjs-node` *downloads* binary tensorflow during build, it does not try to rebuild it each time.

**Comment by tafsiri** [comment]
`@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js` and `@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.es2017.js` are UMD bundles that provide unminified code using ES5 and ES2017 syntax (note: just the syntax changes, not the module format) this allows people to opt into browser bundles that use modern es6+ code (e.g. async await) even if they do not yet have support for es6 modules. We do this for all our packages. 

> also, why is wasm rebuild process trying to rebuild *.wasm binaries using bazel every time? no other part of tfjs does that!

No other part of tfjs has a bunch of c++ code that needs to be compiled. You can use `yarn build-fast` to skip the wasm bundle compilation if you have already compiled them once (or if you want to try something that doesn't actually require the wasm binaries to exist).

**Comment by vladmandic** [comment]
No other part of tfjs has a bunch of c++ code that needs to be compiled.

`tfjs-node` is based on `tensorflow.so` which is downloaded istead of being compiled, so that doesn't really hold.

    You can use yarn build-fast to skip the wasm bundle compilation

`build-fast` doesn't work unless full build has been completed first as it requires `tfjs-backend-wasm-*.worker.js` which are dynamically generated. yes, i can run a `bazel` build, but it should not be necessary - it's about 50x slower than the rest of tfjs build altogether (when i was building a toolchain just to get `summarize_graph` it took hours).

but we're getting sidetracked here. i don't like how `tfjs-backend-wasm` is handled very differently than the rest of `tfjs` from dependency point of view (fs, path, perf_hooks should not be there at all since this is **not** a nodejs module, it shouldn't be up to bundler to figure it out).

please consider removing unnecessary dependencies from browser packages.

**Comment by vladmandic** [comment]
closing this issue due to changes in packaging of tfjs 3.0.0
