### ISSUE TITLE
Implement native tf.browser.fromPixels() for WASM backend

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4218]
Currently `tf.browser.fromPixels()` has native implementation for WebGL backend while WASM falls back to default `canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;`

This means it will:
a) Fail if input already has a different context  
   e.g., canvas with `webgl` context because user performed some image pre-processing
b) It is really slow

On FullHD input, WebGL native implementation executes in near 0ms while `getImageData()` takes ~20ms  

This significantly impacts overall performance of WASM backend in general.

Example, if model execution takes 33ms in both WebGL and WASM, frame rate in WebGL will be 30 FPS, but in WASM it will be 1000/(20+33) = 18 FPS - that is 36% performance difference just because of lack of native implementation to get image data.

**Comment by vladmandic** [comment]
UPDATE: as an alternative, would it be possible to use WebGL implementation of `tf.browser.fromPixels()` and then continuing with WASM model. I don't mind mixing backends like this, but actually changing active backend on the fly is a no-go.

**Comment by vladmandic** [comment]
Closer look, it's even worse - `browser.js`fromPixels_()` will create extra canvas if it cannot get `2d` context.

So not only there is a missing native implementation, but fallback one is really bad.
```js
    if (fromPixels2DContext == null) {
      fromPixels2DContext = document.createElement('canvas').getContext('2d');
    }
```

Plus it uses DOM (`document.createElement`), so it cannot be executed in Web Worker (if you *have to* create additional canvas, should try `OffsreenCanvas` first and use DOM as fallback).

If you can't use your accelerated webgl implemenation, why not test for canvas `webgl` context first and then rely on GL context `ctx.readPixels()` which is >2x faster than `ctx.getImagedata()`.

**Comment by AmitMY** [comment]
When having a canvas with `2d` context, despite using `webgl` as the `tfjs` backend, the `fromPixels` method still takes 25ms+.
I could not find a way to perhaps copy my canvas with existing context to a new canvas in order to have a `webgl` context.

**Comment by vladmandic** [comment]
@AmitMY in my tests, only first call to `fromPixels` takes ~25ms when using `WebGL` backend as GLSL needs to be initialized  
if doing 1000 calls using `HTMLVideoElement` as input (webcam in full-hd), it takes <2ms per each frame  

btw, I've tried mixing GL and CPU or WASM backends (it can be done in a weird way), but the issue is that with GL `fromPixels` all ops and data happen on GPU and tensor is actually not available for usage outside of GL - I can read canvas really fast, but can't actually use it later in WASM backend, so that doesn't work   

I'm looking at <https://github.com/as2d/as2d> for next steps

**Comment by vladmandic** [comment]
after tons of experiments and reading internal browser documentation, there seems to be no faster way without gl context. closing the issue.

**Comment by rdutta1999** [comment]
Was wondering if there's been any update regarding this?

I have been deploying an object-detection app and using the 'wasm' backend with threaded-simd, I was able to greatly reduce the inference time and post-processing time. However, the time across the call to `tf.browser.fromPixels` increased significantly, from around 0.2ms in WebGL backend to ~15ms in wasm-threaded-simd at 720p resolution. And the jump is even higher for higher resolutions like 2K.

**Comment by axinging** [comment]
Hi, @rdutta1999 @vladmandic 
Could you please try this PR(https://github.com/tensorflow/tfjs/pull/6445):
During my test, set CANVAS2D_WILL_READ_FREQUENTLY to true will greatly improve getImageDta perf. You can do it before run your wasm case:

tf.env().set('CANVAS2D_WILL_READ_FREQUENTLY', true)

**Comment by vladmandic** [comment]
@axinging i'm already using that flag, but it doesn't make too much of a difference as it gets automatically set by latest chrome on frequent canvas access anyhow, so it only accelerates first read. it does make a big difference if you're recreating canvas on each frame as its not set on initial read, but not if you're reusing same canvas element.

**Comment by axinging** [comment]
@vladmandic ,  so do you agree that we turn flag CANVAS2D_WILL_READ_FREQUENTLY to true by default?

BTW, I did more investigation on wasm fromPixels. There are two fromPixels bottlenecks on wasm: getImageData and data copy (from 4 channels to three channels). A typical measured times for these bottlenecks(720p image) are: getImageData: 2.52 ms, data copy: 8.80 ms

It seems when image gets larger, more efforts are spent on data copy. And I think data copy may possibly be improved by wasm.

I wrote a simple case to prove this:
https://github.com/axinging/asyncawaitdemo/blob/main/webgl/index_canvas_bug2.html
