### ISSUE TITLE
The shape of dict['image_tensor'] provided in model.execute(dict) must be [-1,-1,-1,3], but was [224,224,3]

### ISSUE THREAD

**Issue by bcarthic** [tensorflow/tfjs#4221]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **No**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Android Emulator API level 30**
- TensorFlow.js installed from (npm or script link): 
- TensorFlow.js version (use command below):
 ```
    "@tensorflow/tfjs": "2.7.0"
    "@tensorflow/tfjs-react-native": "^0.5.0"
    "react-native": "0.63.2"
```

**Describe the current behavior**
I am trying to run the cocossd model in my react native application. Everything works fine if the model is loaded from the server using import statement. But when I tried local model loading using `bundleResourceIO` like below and predict I get 
`The shape of dict['image_tensor'] provided in model.execute(dict) must be [-1,-1,-1,3], but was [224,224,3]`.

I downloaded the model from https://tfhub.dev/tensorflow/tfjs-model/ssd_mobilenet_v1/1/default/1

```
const modelJson = require("../../assets/model/model.json");
const modelWeights1 = require("../../assets/model/group1-shard1of5.bin");
const modelWeights2 = require("../../assets/model/group1-shard2of5.bin");
const modelWeights3 = require("../../assets/model/group1-shard3of5.bin");
const modelWeights4 = require("../../assets/model/group1-shard4of5.bin");
const modelWeights5 = require("../../assets/model/group1-shard5of5.bin");

const model = await tf.loadGraphModel(
        bundleResourceIO(modelJson, [modelWeights1, modelWeights2, modelWeights3, modelWeights4, modelWeights5])
      );
model.predict(tensor); // Error happens at this step
```
To get the tensor3D from the image, I use
```
const base64String = await RNFS.readFile(resizedImage.uri, "base64");
const rawImageData = tf.util.encodeString(base64String, "base64").buffer;
const raw = new Uint8Array(rawImageData);
const imageTensor = decodeJpeg(raw);
```
The model is loading successfully but when model.predict is executed, the error is thrown.

Any help would be great.

**Comment by pyu10055** [comment]
@bcarthic The API requires rank 4 tensor, while you are providing a rank 3 tensor. you can do following to reshape:

```
tensor = tensor.reshape([1, 224, 224, 3]);
```

**Comment by bcarthic** [comment]
@pyu10055  Great thanks. It worked. I also tried the below, which seems to work too.
```
tensor.expandDims(0)
```
Is that correct? 

Also how do I interpret the output, it seems to be different compared to when I load using web server and use 
`model.detect(tensor)` gives a prediction object.

I am not sure how to post process the output. Is there any documentation or samples to proceed further?

**Comment by bcarthic** [comment]
@pyu10055 I found the solution to interpret the output and got the desired result. Thanks very much for helping. This can be closed
