### ISSUE TITLE
Use another input than microphone for speech commands

### ISSUE THREAD

**Issue by mydigitaltears** [tensorflow/tfjs#4225]
Hi!

I was wondering if it was possible to use another audio input instead of the microphone for the speech commands

I would like to analyze mp3 radio streams and classify a music class + a talking class in real-time.

Thank you so much!

**Comment by rthadur** [comment]
cc @tafsiri

**Comment by tafsiri** [comment]
This isn't currently directly possible with the speech-commands model, so it would require significant modification. The crux of it would likely involve extending [BrowserFFTExtractor](https://github.com/tensorflow/tfjs-models/blob/4a538cb9f6f333e09d96532464c0fe4042ea9d28/speech-commands/src/browser_fft_extractor.ts#L88) to support the kind of input you want to feed in. Even with that I'm not sure if the model would be optimal for your use case.

cc @jasonmayes in case you know of anyone in the community exploring this path. cc @caisq in case this is easier than I thought (or maybe even harder than I am suggesting).

**Comment by jasonmayes** [comment]
Thanks for looping me in - I have not seen folk request this yet, the vast majority of folk use the mic as the input device here. The easiest way to do this using a mic right now would be to create a virtual cable on your computer so chrome picks up your speaker output as a mic input which you can then select and use for this purpose if you just need this to work on your machine. That could be a good way to test for now until any extra formats are added.

**Comment by mydigitaltears** [comment]
I understand, I will try the virtual cable for testing purpose. Thank you all for the information!
