### ISSUE TITLE
Uncaught Error: The dict provided in model.execute(dict) has keys that are not part of graph

### ISSUE THREAD

**Issue by prakashr85** [tensorflow/tfjs#4239]
model used: custom training ultralytics yolo v5 converted to tensorflow saved model then to tensorflow js (quantized to uint8) when using model.predict getting this error, 

- OS Platform: Windows 10 Desktop Chrome
- TensorFlow.js installed from (npm or script link): 2.7.0
- Browser version: Version 86.0.4240.183 (Official Build) (64-bit)
- Tensorflow.js Converter Version: 2.7.0 

`Uncaught Error: The dict provided in model.execute(dict) has keys: [alt,src,srcset,sizes,crossOrigin,useMap,isMap,width,height,naturalWidth,naturalHeight,complete,currentSrc,referrerPolicy,decoding,name,lowsrc,align,hspace,vspace,longDesc,border,x,y,decode,loading,title,lang,translate,dir,hidden,accessKey,draggable,spellcheck,autocapitalize,contentEditable,isContentEditable,inputMode,offsetParent,offsetTop,offsetLeft,offsetWidth,offsetHeight,style,innerText,outerText,onabort,onblur,oncancel,oncanplay,oncanplaythrough,onchange,onclick,onclose,oncontextmenu,oncuechange,ondblclick,ondrag,ondragend,ondragenter,ondragleave,ondragover,ondragstart,ondrop,ondurationchange,onemptied,onended,onerror,onfocus,onformdata,oninput,oninvalid,onkeydown,onkeypress,onkeyup,onload,onloadeddata,onloadedmetadata,onloadstart,onmousedown,onmouseenter,onmouseleave,onmousemove,onmouseout,onmouseover,onmouseup,onmousewheel,onpause,onplay,onplaying,onprogress,onratechange,onreset,onresize,onscroll,onseeked,onseeking,onselect,onstalled,onsubmit,onsuspend,ontimeupdate,ontoggle,onvolumechange,onwaiting,onwebkitanimationend,onwebkitanimationiteration,onwebkitanimationstart,onwebkittransitionend,onwheel,onauxclick,ongotpointercapture,onlostpointercapture,onpointerdown,onpointermove,onpointerup,onpointercancel,onpointerover,onpointerout,onpointerenter,onpointerleave,onselectstart,onselectionchange,onanimationend,onanimationiteration,onanimationstart,ontransitionend,oncopy,oncut,onpaste,dataset,nonce,autofocus,tabIndex,attachInternals,blur,click,focus,onpointerrawupdate,enterKeyHint,namespaceURI,prefix,localName,tagName,id,className,classList,slot,attributes,shadowRoot,part,assignedSlot,innerHTML,outerHTML,scrollTop,scrollLeft,scrollWidth,scrollHeight,clientTop,clientLeft,clientWidth,clientHeight,attributeStyleMap,onbeforecopy,onbeforecut,onbeforepaste,onsearch,elementTiming,onfullscreenchange,onfullscreenerror,onwebkitfullscreenchange,onwebkitfullscreenerror,onbeforexrselect,children,firstElementChild,lastElementChild,childElementCount,previousElementSibling,nextElementSibling,after,animate,append,attachShadow,before,closest,computedStyleMap,getAttribute,getAttributeNS,getAttributeNames,getAttributeNode,getAttributeNodeNS,getBoundingClientRect,getClientRects,getElementsByClassName,getElementsByTagName,getElementsByTagNameNS,hasAttribute,hasAttributeNS,hasAttributes,hasPointerCapture,insertAdjacentElement,insertAdjacentHTML,insertAdjacentText,matches,prepend,querySelector,querySelectorAll,releasePointerCapture,remove,removeAttribute,removeAttributeNS,removeAttributeNode,replaceWith,requestFullscreen,requestPointerLock,scroll,scrollBy,scrollIntoView,scrollIntoViewIfNeeded,scrollTo,setAttribute,setAttributeNS,setAttributeNode,setAttributeNodeNS,setPointerCapture,toggleAttribute,webkitMatchesSelector,webkitRequestFullScreen,webkitRequestFullscreen,ariaDescription,ariaAtomic,ariaAutoComplete,ariaBusy,ariaChecked,ariaColCount,ariaColIndex,ariaColSpan,ariaCurrent,ariaDisabled,ariaExpanded,ariaHasPopup,ariaHidden,ariaKeyShortcuts,ariaLabel,ariaLevel,ariaLive,ariaModal,ariaMultiLine,ariaMultiSelectable,ariaOrientation,ariaPlaceholder,ariaPosInSet,ariaPressed,ariaReadOnly,ariaRelevant,ariaRequired,ariaRoleDescription,ariaRowCount,ariaRowIndex,ariaRowSpan,ariaSelected,ariaSetSize,ariaSort,ariaValueMax,ariaValueMin,ariaValueNow,ariaValueText,getAnimations,replaceChildren,nodeType,nodeName,baseURI,isConnected,ownerDocument,parentNode,parentElement,childNodes,firstChild,lastChild,previousSibling,nextSibling,nodeValue,textContent,ELEMENT_NODE,ATTRIBUTE_NODE,TEXT_NODE,CDATA_SECTION_NODE,ENTITY_REFERENCE_NODE,ENTITY_NODE,PROCESSING_INSTRUCTION_NODE,COMMENT_NODE,DOCUMENT_NODE,DOCUMENT_TYPE_NODE,DOCUMENT_FRAGMENT_NODE,NOTATION_NODE,DOCUMENT_POSITION_DISCONNECTED,DOCUMENT_POSITION_PRECEDING,DOCUMENT_POSITION_FOLLOWING,DOCUMENT_POSITION_CONTAINS,DOCUMENT_POSITION_CONTAINED_BY,DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC,appendChild,cloneNode,compareDocumentPosition,contains,getRootNode,hasChildNodes,insertBefore,isDefaultNamespace,isEqualNode,isSameNode,lookupNamespaceURI,lookupPrefix,normalize,removeChild,replaceChild,addEventListener,dispatchEvent,removeEventListener] that are not part of graph
    at e.t.checkInputs (graph_executor.js:607)
    at e.t.execute (graph_executor.js:193)
    at e.t.execute (graph_model.js:323)
    at e.t.predict (graph_model.js:276)
    at HTMLImageElement.handleClick (index.js:100)
t.checkInputs @ graph_executor.js:607
t.execute @ graph_executor.js:193
t.execute @ graph_model.js:323
t.predict @ graph_model.js:276
handleClick @ index.js:100`

**Comment by rthadur** [comment]
@prakashr85 please provide minimal reproduction code in codepen if possible

**Comment by prakashr85** [comment]
@rthadur  its just a modification of jason's template from codepen,  here it is (i use flask to run) https://codepen.io/prakashr85/pen/PozgabG  Tried with TF object detection model converted to tfjs as well same error.

**Comment by rthadur** [comment]
I guess there is a mismatch in the input provided in model , you need to see how the model was trained and then provide inputs accordingly. 
cc @jasonmayes @pyu10055

**Comment by prakashr85** [comment]
the tensorflow object detection model was taking 540p images and tried with the same and getting same error. the yolo model taking 416p image and getting same error. Is there any way to load tfjs model in python and check inference? if there are any examples it will be great like tflite @rthadur

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by patlevin** [comment]
@prakashr85 You are passing the wrong data into the model. The model expects a tensor but you pass it a DOM element.

The demo works, because it uses custom model class that abstracts the input and accepts tensors as well as DOM elements:

The demo code (line 67):

>  **model.detect**(event.target).then(function (predictions) {
> ...

Your code (line 63)

> **model.predict**(event.target).then(function (predictions) {
> ...

The difference might be subtle, but the TFJS model doesn't have a `detect`-method - that's a method implemented in the [custom code](https://github.com/tensorflow/tfjs-models/blob/7c2b3e406a490fcb7910229cf354fbe61d0ea39f/coco-ssd/src/index.ts#L223) for the model.

You can use the following code snipped to get the correct input for ``model.predict`:

```js
const input = tf.tidy(() => {
  const img = tf.browser.fromPixels(event.target)
  return img.expandDims(0)
})

model.predict(input).then(function(results) { ...
```

I doubt that would be all of the necessary changes, though, since the model will return an array of tensors that you will need to process according to the model's architecture. Judging from the ultralytics yolo v5 source code, you will have to translate the relevant parts of yolo.py and test.py to JavaScript (or TypeScript) in order to use it in the browser.
