### ISSUE TITLE
what to use insted of StatefulPartitionedCall/Postprocessor/Slice in EfficientDet0 model?

### ISSUE THREAD

**Issue by batrlatom** [tensorflow/tfjs#4246]
I converted efficientdet0 model and successfully made a inference calls. When I want to make a boxes from inference results, I am stuck at what nodes to use. 

You use ['StatefulPartitionedCall/Postprocessor/ExpandDims_1', 'StatefulPartitionedCall/Postprocessor/Slice'] as output tensors in your tfjs_models demo. 

StatefulPartitionedCall/Postprocessor/ExpandDims_1 is present in the efficientdet0 graph, but not StatefulPartitionedCall/Postprocessor/Slice.

Is there any node which I can use as a 1:1 replacement? I would like to reuse your code from https://www.npmjs.com/package/@tensorflow-models/coco-ssd

The model converted from tfhub could be found at : https://recall-models.s3.eu-central-1.amazonaws.com/efdet_99/model.json
Thanks for the help

**Comment by vladmandic** [comment]
@batrlatom 
Take a look at #3942 and the last note I wrote - that's how you can map output node names.

**Comment by batrlatom** [comment]
@vladmandic I will take look. Thanks for a quick response!

**Comment by batrlatom** [comment]
@vladmandic I was able to track the right node with netron. Thank you for hints. 

The node which I was lookinf for is named 'StatefulPartitionedCall/Postprocessor/convert_scores' here.
