### ISSUE TITLE
Non-linearity not plotting correctly in tfvis tutorial

### ISSUE THREAD

**Issue by coryroyce** [tensorflow/tfjs#4251]
While following the [Making Predictions from 2D Data](https://codelabs.developers.google.com/codelabs/tfjs-training-regression?hl=en#0) tutorial, I was having a hard time getting the non-linearity of the model to show up in the tfvis graph ([my full code](https://github.com/coryroyce/Machine_Learning_Duration_Estimator/tree/main/src)).

Here is the non-linear model as suggested in the [extra steps](https://codelabs.developers.google.com/codelabs/tfjs-training-regression?hl=en#8) part of the tutorial.

```
function createModel() {
  // Create a sequential model
  const model = tf.sequential(); 
  
  // Add a single input layer
  model.add(tf.layers.dense({inputShape: [1], units: 1, useBias: true}));

  // Add hidden layer to introduce non-linearity
  model.add(tf.layers.dense({units: 50, activation: 'sigmoid'}));
  
  // Add an output layer
  model.add(tf.layers.dense({units: 1, useBias: true}));

  return model;
}
```

Here is the graph from this model when I run it:
<img width="531" alt="Tfvis_Plot_Non_Linearity_Graph" src="https://user-images.githubusercontent.com/15311592/99420045-9d669400-28b1-11eb-886c-a395c62a94a9.png">

Expected the orange predicted to be similar to [extra steps](https://codelabs.developers.google.com/codelabs/tfjs-training-regression?hl=en#8).

Is there a mistake in the way the hidden layer was added or how tfvis calls the prediction? (the rest of the code is straight from the tutorial). If someone know the github link to the code source of the tutorial, that would be helpful for me to reference and trouble shoot further.

**Comment by tafsiri** [comment]
Nope you are on the right track! There is a hint in bullet 3 of that part of the code lab (the solution is not directly written out on the page). 

Try adding more hidden layers (and experimenting with the number of units in them). You can also experiment with the other activation function (relu) mentioned on the [page we link out to](https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks/anatomy).
