### ISSUE TITLE
Unit tests for browserHTTPRequest fail on Safari due to usage of FormData

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#426]
FormData, used in some of our unit tests, is not supported in Safari:
https://developer.mozilla.org/en-US/docs/Web/API/FormData

I'm about to enable Safari unit tests in https://github.com/tensorflow/tfjs-core/pull/978, but I disabled `browserHTTPRequest-save` tests until we fix this. When ready, switch `CHROME_CPU_ENVS` to `CPU_ENVS` (and we can remove CHROME_CPU_ENVS and IS_CHROME)

It seems like we only use this in tests, so should be straightforward to remove.

**Comment by dsmilkov** [comment]
We enabled tests on Safari, so this is outdated.
