### ISSUE TITLE
ModelManagement with LocalStorage fails in Safari, tests are disabled for non-Chrome browsers.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#427]
Looks like something is strange with window.localStorage. I turned off the tests for non-Chrome browsers.

```
Safari 11.0.3 (Mac OS X 10.13.3) ModelManagement {"BACKEND":"test-cpu"} List models: 0 result FAILED
	Expected object not to have properties
	    localstorage://repeat/QuxModel: Object({ dateSaved: '2018-06-13T17:35:39.116Z', modelTopologyType: 'JSON', modelTopologyBytes: 555, weightSpecsBytes: 109, weightDataBytes: 16 })
	<Jasmine>
	src/io/model_management_test.ts:96:30 <- src/io/model_management_test.js:126:44
	<Jasmine>
```

**Comment by caisq** [comment]
I tried running these code snippets in desktop Safari (Version 11.1.1 (12605.2.8)) and they all seem to work.
https://js.tensorflow.org/api/0.11.6/#io.copyModel
https://js.tensorflow.org/api/0.11.6/#io.listModels
https://js.tensorflow.org/api/0.11.6/#io.removeModel
https://js.tensorflow.org/api/0.11.6/#io.moveModel

There are two possible issues here:
1. The unit tests still have some order dependency and/or incomplete clean-up, leading to the errors @nsthorat showed above.
2. Safari seems to be more strict with regard to the security of IndexedDB. E.g., see:
https://github.com/dfahlander/Dexie.js/issues/565
Some work may need to be done to address that security feature of Safari.

**Comment by nsthorat** [comment]
I think what's happening is for some reason the "remove" isn't working. One test runs, adds something to local storage, beforeEach fires and clears everything, but then another test which asserts nothing is in local storage fails.

**Comment by rthadur** [comment]
This is resolved in latest versions , closing this issue.
