### ISSUE TITLE
Unable to resolve "@react-native-community/async-storage" from "node_modules\@tensorflow\tfjs-react-native\dist\async_storage_io.js"

### ISSUE THREAD

**Issue by lakshmikanth-reddy-au2** [tensorflow/tfjs#4270]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device : Honor7x
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 2.7.0

Description:

Importing fetch from @tensorflow/tfjs-react-native resulting in above issue.

I am getting this issue when I import only. I did follow the exact steps as in docs.

Please see the screenshot below:
![WhatsApp Image 2020-11-19 at 2 57 16 PM](https://user-images.githubusercontent.com/49977739/99647365-af922f00-2a77-11eb-9683-8cebf1c2b4cd.jpeg)

Package  Dependencies : 

```javascript
 "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@tensorflow-models/mobilenet": "^2.0.4",
    "@tensorflow/tfjs": "^2.7.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "expo": "~39.0.2",
    "expo-camera": "^9.0.0",
    "expo-constants": "^9.2.0",
    "expo-gl": "^9.1.1",
    "expo-gl-cpp": "^9.1.2",
    "expo-image-picker": "^9.1.1",
    "expo-permissions": "^9.3.0",
    "expo-status-bar": "~1.0.2",
    "jpeg-js": "^0.4.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-fs": "^2.16.6",
    "react-native-web": "~0.13.12"
  },
``` 

Please help me how to resolve this issue.

**Comment by tafsiri** [comment]
Your dependencies have "@react-native-async-storage/async-storage": "^1.13.2". But you need to have "@react-native-community/async-storage" installed. 

It looks like the async-storage packaged moved to a new org recently so we would need to update our dependency in a future release, but at the moment you should be able to load it with the older package name. Let me know if you run into problems with that.

I'll leave this open to track updating the dependency on our end.

**Comment by raul-marques** [comment]
I'm sorry ... but I need the current package(https://github.com/react-native-async-storage/async-storage), and installing both creates conflict. Can it be updated for the package considered indicated?

**Comment by linkian209** [comment]
Is there any update regarding this? It is difficult to start a new project because of how far back in versioning for several libraries you have to go back to support this particular piece.

**Comment by aruneko** [comment]
Since Expo SDK 41 dropped the support of old package name, we cannot upgrade to SDK 41 as long as we use tfjs on an expo project.

**Comment by AliButtar** [comment]
@tafsiri This issue has been open for over 6 months. Would love it if you can make this your priority. Can't use BundleResourceIO and load models at all because this dependency hasn't been updated yet

**Comment by julianklumpers** [comment]
Same issue here, app doesn't even build.

**Comment by AliButtar** [comment]
> Same issue here, app doesn't even build.

If you want to build the app. Go to the file the error takes you and replace the dependency manually to the `"@react-native-async-storage/async-storage"`. I'm not sure if the async storage functionalities still work though. I worked around them.

**Comment by julianklumpers** [comment]
> > Same issue here, app doesn't even build.
> 
> If you want to build the app. Go to the file the error takes you and replace the dependency manually to the `"@react-native-async-storage/async-storage"`. I'm not sure if the async storage functionalities still work though. I worked around them.

Yes that works, but this issue is already open for 6+ months. I think monkey patching is not the solution.
