### ISSUE TITLE
[tfjs-core] Error: The output # of rows (11.4) must be an integer when running pool test

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#4271]
**System information**
- TensorFlow.js version (use command below):
"@tensorflow-core": "^2.7.0" 

**Describe the current behavior**
When running [this pool test](https://brucedai.github.io/report-bug/unset_roundingMode_param.html), error happened 

**Describe the expected behavior**
None error, and the output # of rows is an integer (11) computed with below Python code of [AVERAGE_POOL_2D test](https://android.googlesource.com/platform/frameworks/ml/+/refs/tags/android-cts-11.0_r1/nn/runtime/test/specs/V1_0/avg_pool_float_2.mod.py) from NNAPI  CTS.

```python
row = 52
std = 5
flt = 100
pad = 50
output_row = (row + 2 * pad - flt + std) // std #L35
```

**Standalone code to reproduce the issue**
Here's a [test case](https://brucedai.github.io/report-bug/unset_roundingMode_param.html).

**Other info / logs** Include any logs or source code that would be helpful to
When calling function `conditionalRound`, none value (undefined) was passed to the second **roundingMode** paramter, so as the first **value** paramter being not an integer (11.4), the value wasn't rounded. 
```ts
/**
 * Rounds a value depending on the rounding mode
 * @param value
 * @param roundingMode
 */
function conditionalRound(
    value: number, roundingMode?: 'floor'|'round'|'ceil') {
  if (!roundingMode) {
    return value;
  }
  switch (roundingMode) {
    case 'round':
      // used for Caffe Conv
      return Math.round(value);
    case 'ceil':
      // used for Caffe Pool
      return Math.ceil(value);
    case 'floor':
      return Math.floor(value);
    default:
      throw new Error(`Unknown roundingMode ${roundingMode}`);
  }
}
```
Traced that when calling function **conv_util.computePool2DInfo** of [tfjs-core/src/ops/pool.ts#L85](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/pool.ts#L85), none value (undefined) was passed to the sixth **roundingMode** parameter .
```ts
  const convInfo = conv_util.computePool2DInfo(
      x4D.shape, windowShape, strides, dilations, pad);
```
According to [**computePool2DInfo** definitions](https://github.com/tensorflow/tfjs/blob/4d81b29a13cb67a0fae67833890cac326ca4d720/tfjs-core/src/ops/conv_util.ts#L119):
```ts
export function computePool2DInfo(
    inShape: [number, number, number, number],
    filterSize: [number, number]|number, strides: number|[number, number],
    dilations: number|[number, number], pad: 'same'|'valid'|number,
    roundingMode?: 'floor'|'round'|'ceil',
    dataFormat: 'channelsFirst'|'channelsLast' = 'channelsLast')
```

**Comment by rthadur** [comment]
might be related issue [here](https://github.com/tensorflow/tfjs/issues/1055)

**Comment by lina128** [comment]
Hi @BruceDai, thank you for the bug report! Do you want to contribute a fix PR?

**Comment by BruceDai** [comment]
@lina128 OK, I'll submit a PR for it.

**Comment by BruceDai** [comment]
@lina128 Please take a look this PR #4282, thanks.
