### ISSUE TITLE
.predict & .execute optional arguments type error

### ISSUE THREAD

**Issue by joshuaellis** [tensorflow/tfjs#4276]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX Big Sur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow.js installed from (npm or script link): 2.7.0
- TensorFlow.js version (use command below): 2.7.0
- Browser version: n/a
- Tensorflow.js Converter Version: n/a

**Describe the current behavior**
Using Typescript, `model.predict` & `model.execute` require 2 arguments, however in the docs these arguments are shown to be optional – https://js.tensorflow.org/api/latest/#tf.GraphModel.execute – This therefore throws an error. I'm hesitant to throw an empty object into `model.predict` because I can't see how the optional keys inside the object are set, and it's I can't find any documentation passing the default option for `model.execute` from my model so I can't bypass the typechecking.

**Describe the expected behavior**
For both `model.predict` & `model.execute` I should be able to pass one argument – the tensor inputs and it pass type check,.

**Standalone code to reproduce the issue**
https://codesandbox.io/s/admiring-river-u3jgf?file=/src/index.ts

**Other info / logs** Include any logs or source code that would be helpful to

<img width="476" alt="image" src="https://user-images.githubusercontent.com/37798644/99721131-9fde0f00-2aa6-11eb-86a8-5d56d1d7c0db.png">

**Comment by joshuaellis** [comment]
I want to add, I'd do a PR but I want to be sure which is incorrect the type or the docs.

**Comment by pyu10055** [comment]
looks like there is some inconsistency on the predict/execute method between InferenceModel interface and GraphModel.
Can you check if you type the model as tf.GraphModel instead, will the type check pass?

**Comment by joshuaellis** [comment]
I've changed it to `tf.GraphModel` but `model.execute` still fails with `tf.LayersModel`.

in `training.d.ts` line 296 execute is written as –
```js
execute(inputs: Tensor | Tensor[] | NamedTensorMap, outputs: string | string[]): Tensor | Tensor[];
```

so outputs is still required.

**Comment by pyu10055** [comment]
@joshuaellis you can use predict() method with tf.layersModel, the output strings are not required there.

**Comment by joshuaellis** [comment]
That would mean the docs are wrong then? as it says execute has an optional argument `outputs`

**Comment by pyu10055** [comment]
@joshuaellis The doc for GraphModel and LayersModel are different, only execute on GraphModel says output is optional, LayersModel is consistent with InferenceModel interface, the outputs are required argument.
