### ISSUE TITLE
model.save(url) | ValueError: Cannot find any save handlers for URL

### ISSUE THREAD

**Issue by ColinPeppler** [tensorflow/tfjs#4280]
**System information**
- OS Platform: Mac OSX 10.14.6
- tfjs: 2.7
- tfjs-node: 2.7

**Standalone code to reproduce the issue**
```
const serverAddr = "http://localhost:5001"
model = await tf.loadLayersModel(serverAddr + '/get-model')
model.compile({
    optimizer: tf.train.adam(),
    loss: 'categoricalCrossentropy',
    metrics: ['accuracy']
  });
model.train(...)
await model.save(serverAddr + '/upload-model')    // ValueError occurs
```

A flask server is setup with endpoints /get-model and /upload-model. The /get-model endpoint provides an appropriate json, and so the model compile and trains properly. However, when trying to save the model to my Flask server, I receive the following error.
`ValueError: Cannot find any save handlers for URL 'http://localhost:5001/upload-model' at new ValueError (/Users/colinpeppler/tfplayground/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:186:28)`. 

Running the code on the browser works good when saving to the url. I also tried saving to the filesystem and that worked fine, but the HTTP request method doesn't work with node.

**Comment by rthadur** [comment]
cc @pyu10055 @tafsiri there is a similar issue for saving in file system that got resolved [here](https://github.com/tensorflow/tfjs/issues/723). seems to be bug in tfjs-layers

**Comment by tafsiri** [comment]
A workaround in the meantime is to use https://js.tensorflow.org/api/latest/#io.http directly and pass that to tf.loadLayersModel.

**Comment by ColinPeppler** [comment]
I ended up just saving the model to the file directory and creating a request with multipart/form-data encoding. See [this](https://www.tensorflow.org/js/guide/save_load#https_request)for how tfjs constructs the request's body.

**Comment by timekarma** [comment]
This is a very common issues, most of the tfjs-examples models cannot e saved, ex jena-weather, boston-housing
