### ISSUE TITLE
Customed Object Detection Model Crash When there is no target in video

### ISSUE THREAD

**Issue by luoyuxuan0528** [tensorflow/tfjs#4295]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow.js installed from (npm or script link): npm 
- TensorFlow.js version (use command below): 2.7.0
- Browser version: Chrome 87.0.4280.67
- Tensorflow.js Converter Version: 2.7.0

**Describe the current behavior**
works well when there is target object in video but crash when there is nothing.

**Describe the expected behavior**
works well for video with/without target.

**Standalone code to reproduce the issue**
first I trainned my model and convert it to tfjs format. 
[model.json.zip](https://github.com/tensorflow/tfjs/files/5581107/model.json.zip)

Then I integrated it to tfjs-models demo code using tfconv.loadGraphModel and executeAsync with webGL backend.
```
// pseudo code to reproduce the problem
boundingBoxDetector = tfconv.loadGraphModel(HANDGDETECTIONV2_MODEL_PATH);
const detResult = await boundingBoxDetector.executeAsync(image) as tf.Tensor[];
````

I noticed the PR https://github.com/tensorflow/tfjs/pull/4122 but it does not fix my issue.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Error Stack.
shader_compiler.ts:721 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at getPackedSampler2D (shader_compiler.ts:721)
    at getPackedSamplerFromInInfo (shader_compiler.ts:118)
    at getInputSamplingSnippet (shader_compiler.ts:131)
    at shader_compiler.ts:56
    at Array.map (<anonymous>)
    at Object.makeShader (shader_compiler.ts:56)
    at Object.compileProgram (gpgpu_math.ts:90)
    at backend_webgl.ts:2384
    at MathBackendWebGL.getAndSaveBinary (backend_webgl.ts:2428)
    at MathBackendWebGL.runWebGLProgram (backend_webgl.ts:2383)

Following is the gpu code I found that actually cause crash.
"PadPackedProgram_0,4_undefined_false100,4_100,4_false_
      const ivec2 start = ivec2(0,0);
      const ivec2 end = ivec2(0,4);

      void main() {
        ivec2 outputLoc = getOutputCoords();
        vec4 result = vec4(0.);
        
        ivec2 rc = outputLoc;
        if (any(lessThan(rc, start)) || any(greaterThanEqual(rc, end))) {
          result[0] = float(0);
        } else {
          ivec2 source = rc - start;
          result[0] = getChannel(getX(source.x,source.y), vec2(source.x,source.y));
        }
      
        rc.y += 1;
       if(rc.y < 4) {
      
        if (any(lessThan(rc, start)) || any(greaterThanEqual(rc, end))) {
          result[1] = float(0);
        } else {
          ivec2 source = rc - start;
          result[1] = getChannel(getX(source.x,source.y), vec2(source.x,source.y));
        }
      
        }
       rc = outputLoc;
       rc.x += 1;
       if(rc.x < 100) {
        if (any(lessThan(rc, start)) || any(greaterThanEqual(rc, end))) {
          result[2] = float(0);
        } else {
          ivec2 source = rc - start;
          result[2] = getChannel(getX(source.x,source.y), vec2(source.x,source.y));
        }
      
          rc.y += 1;
         if(rc.y < 4) {
        if (any(lessThan(rc, start)) || any(greaterThanEqual(rc, end))) {
          result[3] = float(0);
        } else {
          ivec2 source = rc - start;
          result[3] = getChannel(getX(source.x,source.y), vec2(source.x,source.y));
        }
      }}
        setOutput(result);
      }
    "

**Comment by lina128** [comment]
Hi @luoyuxuan0528 , does the model run with cpu backend or wasm backend? Also, can you share the model with us?

**Comment by luoyuxuan0528** [comment]
> Hi @luoyuxuan0528 , does the model run with cpu backend or wasm backend? Also, can you share the model with us?

Hi, Lina:
   I did not test the model on cpu/wasm backend because that is not our target. The model is attached and input of that model should be a 224x224x3 Int Tensor. 
   Looking forward to your replay ^_^.

[224x224_det_graph_ssd_small_v5.zip](https://github.com/tensorflow/tfjs/files/5626277/224x224_det_graph_ssd_small_v5.zip)

**Comment by gaikwadrahul8** [comment]
Hi, @luoyuxuan0528 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
