### ISSUE TITLE
Facemesh/Face-Landmarks-Detection model crashes on WebGL Backend

### ISSUE THREAD

**Issue by yeemachine** [tensorflow/tfjs#4309]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
iOS 14.2.1

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
iPhone 12 Pro Max, iPhone 11 Pro Max

- TensorFlow.js installed from (npm or script link):
https://unpkg.com/@tensorflow/tfjs-core@2.7.0/dist/tf-core.js
https://unpkg.com/@tensorflow/tfjs-converter@2.7.0/dist/tf-converter.js
https://unpkg.com/@tensorflow/tfjs-backend-webgl@2.7.0/dist/tf-backend-webgl.js
https://unpkg.com/@tensorflow-models/face-landmarks-detection@0.0.2/dist/face-landmarks-detection.js

- TensorFlow.js version (use command below):
- Browser version: Safari 14.0
- Tensorflow.js Converter Version: 2.7.0

**Describe the current behavior**
Page refreshes after approx 15-18min of usage or 18,000 requestAnimationFrames. Perhaps this is a memory leak within the Face-landmarks-detection library?

**Describe the expected behavior**
Page does not crash when using WASM backend with Face-landmarks-detection.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
https://glitch.com/edit/#!/facemesh-bug

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by yeemachine** [comment]
Any update on this issue? I have since updated to version 2.8.4 with the same results. Is #4405 still relevant to this issue? 
Or perhaps #4407 ?

**Comment by Keramblock** [comment]
@rthadur could you please look again on that issue?

**Comment by Keramblock** [comment]
@pyu10055 It will be great if you could check it too =)

**Comment by rthadur** [comment]
Please check the latest face-landmark-detection with mediapipe here https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/ , the above model was deprecated.
