### ISSUE TITLE
big difference in inference results between webgl and wasm backends

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4311]
there is a **big** difference in inference results between `webgl` and `wasm` backends.
and this makes `wasm` model completely unsuitable for usage with some models.

i've noticed this with several models, but biggest difference is with MediaPipe HandPose model: <https://github.com/tensorflow/tfjs-models/tree/master/handpose>

to be specific, in <https://github.com/tensorflow/tfjs-models/blob/master/handpose/src/hand.ts>:

```js
batchedPrediction = this.model.predict(normalizedInput) as tf.Tensor3D;
...
const prediction: tf.Tensor2D = batchedPrediction.squeeze();
...
const scores: tf.Tensor1D = tf.tidy(() => tf.sigmoid(tf.slice(prediction, [0, 0], [-1, 1])).squeeze());
```

for high (>0.99) and low scores (<0.1), both `webgl` and `wasm` values are simmilar.
but for medium scores values, `webgl` has a gradient - you can get scores of any value while `wasm` behaves almost like a binary function - it's either very high or very low confidence and nothing inbetween.

*it's almost like a wrong cast in a `wasm` backend so details are lost.*

for performance reasons, i'm using `tfjs-backend-wasm-threaded-simd.wasm` after enabling `WebAssembly SIMD support` in <chrome://flags>

environment: tfjs 2.7.0 on chrome 87

**Comment by vladmandic** [comment]
any update on this one? this issue plus #4326 are making `wasm` usage a no-go - i'd even consider it a blocker.

**Comment by vladmandic** [comment]
@rthadur @annxingyuan is wasm backend getting any updates? this makes it very unreliable and there are no updates at all.

**Comment by vladmandic** [comment]
@rthadur @annxingyuan @pyu10055 lina128 sorry for the spam,  

but i have 3 issues filled (#4525, #4326, #4311) for `wasm` backend (with full reproduction code)  
that make `wasm` pretty much unusable.  
and all likely have the same root cause, just symptoms are different.

but none received any updates since they were filed (oldest was 2.5 months ago).

**Comment by rthadur** [comment]
thanks for your patience , cc more folks for better visibility @mattsoulanille @jinjingforever
