### ISSUE TITLE
Use tfjs-react-native with posenet and bundleResourceIO

### ISSUE THREAD

**Issue by dabass51** [tensorflow/tfjs#4312]
I want to build an react native app with the use of posenet. A requirement is, that it works offline.

so the examples work fine. when i do:

```
import * as posenet from '@tensorflow-models/posenet'
this.model = await posenet.load();
``` 

so what i did next is converting the model to one weigth file and load the model locally with:

```
const modelJson = require('./assets/model/original/model-stride32.json');
const modelWeights = require('./assets/model/original/weigth.bin');
    
this.model = await tf.loadGraphModel(
   bundleResourceIO(modelJson, modelWeights)
);
```

so what i want to do next is to run something like this:
```
const predictions = await this.model.estimateSinglePose(imageTensor)
```

but of course this doesn't work because the model doesn't know the function. 

i know i can instanciate the model by using something like this:

```
const checkpointLoader = new posenet.CheckpointLoader(checkpoint.url);
const variables = await checkpointLoader.getAllVariables();
const model =  new posenet.MobileNet(variables, checkpoint.architecture);
```

but the checkpoint loader needs an url. i want to use the local files.

does anyone has a hint for me how to use posenet without rewriting the whole node-module?

thx in advance

**Comment by tafsiri** [comment]
Try using the modelUrl param of posenet but passing the IO handler rather than a string, it would look something like this

```
const net = await posenet.load({
  modelUrl: bundleResourceIO(modelJson, modelWeights)
});
```

**Comment by dabass51** [comment]
Hey @tafsiri,

thx alot, it is working now. You saved my day and my project.

**Comment by jc65536** [comment]
@dabass51 could you tell me where you got the modelJson and modelWeights files? Thanks :)

**Comment by yudhiesh** [comment]
> @dabass51 could you tell me where you got the modelJson and modelWeights files? Thanks :)

You can check on Tensorflow Hub, this [link](https://tfhub.dev/s?deployment-format=tfjs&q=posenet) has all the available models which you can download.

**Comment by distroinfinity** [comment]
@dabass51 I want to achieve pose estimation in my React Native app can you provide me with link to some docs or instructions on how to add tfjs and poseet into a React Native app for android. I was able to set up tfjs by installing necessary dependencies inside my React Native project. Can you provide something to move forward? 
Thanks

**Comment by omaraga12** [comment]
Could anyone say me how can I use the model bodypix in react native?

**Comment by francisco-baptista** [comment]
This fix might be relevant to this conversation https://github.com/tensorflow/tfjs-models/pull/911
