### ISSUE TITLE
tf.tensor([ 17378479 ]).print(); returns 17378480

### ISSUE THREAD

**Issue by ystskm** [tensorflow/tfjs#4313]
Thanks for all tensorflow jobs!
I'm trying to modify image with using tensorflow.js.
and i found that some integer will change via tensorflow object.
But I know that it is not critical for machine learning.
So, I want to know ...
Is it a important bug or inevitable spec for tensorflow.js?

**System information**
- Have I written custom code
  
  e.g.) 
  tf.tensor([ 17378479 ]).print(); // => 17378480
  tf.tensor1d([ 17378479 ], 'int32').print() // => 17378479
  tf.tensor1d([ 17378479 ], 'float32').print() // => 17378480
  tf.tensor1d([ 17378479 ], 'int32').slice([0], [1]).print() // => 17378479 (In some case, changes to 17378480)

- OS Platform and Distribution:
  macOS 11.0.1 (20B29)

- Mobile device:
  MacBookAir9,1

- TensorFlow.js version:
  v2.6.0 / v2.7.0

- Browser version:
  Chrome 87.0.4280.67（Official Build）beta （x86_64）
  MSEdge 87.0.664.47 (Official Build) (x86_64)
  Or another

**Comment by tafsiri** [comment]
By default tensors will be created at float32 tensors, which will have some degree of numerical imprecision, so i'm not particularly surprised with your first three lines, however could you say more about the last line.

`tf.tensor1d([ 17378479 ], 'int32').slice([0], [1]).print() // => 17378479 (In some case, changes to 17378480)`

In particular you say in some cases it changes, Could you elaborate on when that happens? Does that happen when repeatedly running the same line over and over again in the same environment?

**Comment by ystskm** [comment]
@tafsiri Thanks for your reply.
No for a repeatedly running. Run the code below. You can see the value change via .slice( ) method.
```js
let x = 127;
tf.tensor1d(new Array(x).fill(0).concat(17378479), 'int32').slice(0, x + 1).dataSync()[x]; // => 17378480
```

And the case below, the matter is not occured.
```js
let x = 127;
tf.tensor1d(new Array(x).fill(0).concat(17378479), 'int32').dataSync()[x]; // => 17378479
```

```js
let x = 126;
tf.tensor1d(new Array(x).fill(0).concat(17378479), 'int32').slice(0, x + 1).dataSync()[x]; // => 17378479
```

**Comment by gaikwadrahul8** [comment]
Hi, @ystskm 

Apologize for the delayed response and I tried to replicate the same issue with latest version of `@tensorflow/tfjs@4.5.0 ` and I haven't observed same behaviour, For your reference I have added screenshot below so could you please give it try with latest version @tensorflow/tfjs and check whether your issue is resolving or not ? 

If issue still persists please let us know with error log and code snippet ? Thank you!

Here is screenshot for your reference:

![image](https://github.com/tensorflow/tfjs/assets/115997457/bf40627d-4f28-45d8-bb4d-b35069369ac2)

**Comment by ystskm** [comment]
@gaikwadrahul8 Thank you so much for your announcement!
I confirmed and I have updated my knowledge for tfjs.
