### ISSUE TITLE
Unknown op TensorListReserve 

### ISSUE THREAD

**Issue by sahas-** [tensorflow/tfjs#4316]
Hello,

I created a LSTM model, converted it using the CLI and serving the same using node http-server.
Below is the code that attempts to run prediction from within html code and below error was shown on the console. Can you pls provide guidance?

PS: Earlier, I tried model.predict and it recommended using executeAsync.

<img width="1074" alt="Screen Shot 2020-11-27 at 8 53 52 PM" src="https://user-images.githubusercontent.com/10361685/100492532-adbd1100-30f2-11eb-80c1-ab6f0f9fe670.png">

<img width="989" alt="Screen Shot 2020-11-27 at 8 49 40 PM" src="https://user-images.githubusercontent.com/10361685/100492535-b7467900-30f2-11eb-9503-03cc7ff3fbd7.png">

**Comment by pyu10055** [comment]
@sahas- Looks like you are using an old version of TFJS (tfjs@2.0.0), TensorListReserve op should have been supported, can you upgrade to the latest version of the TFJS (2.7.0)? thanks

**Comment by sahas-** [comment]
It works with 2.7.0. Thanks.
