### ISSUE TITLE
Support tensorflow version 2

### ISSUE THREAD

**Issue by woodcockjosh** [tensorflow/tfjs#4317]
**System information**
- TensorFlow.js version (you are using): 2.7.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
 support tensorflow version 2.x

**Will this change the current api? How?**
Yes

**Who will benefit with this feature?**
Everyone that wants to use tensorflow version 2

**Any Other info.**

**Comment by woodcockjosh** [comment]
Docs are also confusing. I assumed that tensorflow version 2 would be supported and ran into this issue: https://github.com/tensorflow/tensorflow/issues/45245. Perhaps these docs should be updated: https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source

**Comment by dcsan** [comment]
I thought TF2 was supported after watching some videos, are you sure?

**Comment by woodcockjosh** [comment]
Quite sure: https://github.com/tensorflow/tfjs/blob/fb53c7d28a58de71bb9e813acdc281574ec56453/tfjs-node/scripts/deps-constants.js#L25

The libarary is currently hard coded to work with version 1.15.0

**Comment by dcsan** [comment]
https://www.npmjs.com/package/@tensorflow/tfjs

since tfjs is doing about 25k downloads a month, i wonder if google considers that a success?
since there is no pytorchJS, it seems like the best option for now.

**Comment by rthadur** [comment]
cc @pyu10055 @tafsiri

**Comment by pyu10055** [comment]
@woodcockjosh you are right that our tfjs-node deps on TF version 1.15. TF c++ 2.0 library was not significantly different from 1.15 in terms of core op and saved model execution, are there any features that you need is missing from tfjs-node?

**Comment by woodcockjosh** [comment]
I don't want to use a 1 year old version of tensorflow. 1.15 is not as performance optimized as 2.0 is just to start. I did try to use tfjs with a 2.0 libtensorflow and I got errors. 

When 2.0 was released they mentioned that javascript was supported but they failed to mention that javascript does not support the version they were talking about https://blog.tensorflow.org/2019/09/tensorflow-20-is-now-available.html. I think it's about time that we update the library to work with 2.x don't you think? I would like to have access to all the new 2.0 features that the python community has been enjoying for the last year.

**Comment by dcsan** [comment]
@pyu10055 

> are there any features that you need is missing from tfjs-node?

can TFJS work with all the recent models? For example there are newer versions of the universal sentence encoder.

![image](https://user-images.githubusercontent.com/514002/100870336-518c2100-3453-11eb-8921-d738b47e2629.png)

**Comment by sbrl** [comment]
Just want to chime in here. If keeping the dependency up-to-date isn't a concern, then maybe making the build process easier is? A few issues spring to mind:

 - libtensorflow 1.15 depends on CUDA 10.0, which is increasingly old and outdated - and unlikely to be installed on people's machines
 - The build instructions are outdated and misleading, as the reader is likely to assume that htye should build the latest version of libtensorflow - the docs don't mention that a specific version is required (figuring this out cost me at *least* a week on my PhD)
 - libtensorflow 1.15 requires a very old version of `bazel` indeed to build, which is a huge pain in the behind to install

I'd suggest that either 1 of the following 2 actions is taken:

1. Update the version of libtensorflow Tensorflow.js depends on
2. Update the docs to clarify the build process

Regardless of any actions taken, I suggest that:

 - The specific versions of libtensorflow, CUDA, and CuDNN required are clearly specified in the README.

With respect to the last one, I believe it's libtensorflow 1.15, CUDA 10.0, and CuDNN 7.

**Comment by woodcockjosh** [comment]
@sbrl yes I also spent a week figuring out you need those exact versions. I think at a minimum, a stop gap solution is to update the docs.

**Comment by dcsan** [comment]
is this on linux? for me on the mac it was pretty smooth to install. if those versions are right, is it worth sending a PR? seems there's nearly 2000 PRs that have been merged for this repo

**Comment by woodcockjosh** [comment]
I'll open a PR if one of the project owners agrees to merge it before I spend the time. This still wouldn't address this issue which is to support libtensorflow 2.0. So I think a new issue to update the docs should be opened.

**Comment by sbrl** [comment]
@dcsan: Yep, I'm on Linux. Install is fine, but if you want AVX2 for example, you have to compile from source.

@woodcockjosh: If someone could chime in here that'd be awesome. /cc @pyu10055, @tafsiri

**Comment by tafsiri** [comment]
We'd be happy to take an update to the readme that clarifies the requirements or build steps, and I agree that it is a good intermediate step. In addition to listing the version of libtensorflow used, would tightening the version constraint for CuDNN mentioned here https://github.com/tensorflow/tfjs/tree/master/tfjs-node#installing to say `>=7.4.1 and < 8.0.0` help?

I think we would also need to update the link to the TensorFlow installation instructions to point to a 1.15 related page.

Wrt libtensorflow 2 support, I believe there are going to some efforts in the new year with the [tfjs SIG ](https://github.com/tensorflow/community/blob/master/sigs/tf.js/CHARTER.md)around tfjs-node builds and integrations. So it's possible that this would roll up nicely into that work.

cc @pyu10055 @sandeepngupta for visibility on bringing this up in the next SIG meeting.

**Comment by sbrl** [comment]
@tafsiri sorry for not getting back to you, I was on my Christmas break :-)

Yeah, clarifying the CuDNN version would help too.

That would be a great step to take as well. Though I suggest updating the build instructions to do something like e.g. `git switch v1.15.4` (untested) for example before executing any build commands. Perhaps a recommendation to install and use [`bazelisk`](https://github.com/bazelbuild/bazelisk) wouldn't go amiss either, as it's very useful for managing `bazel` versions (I've found Tensorfllow can be *hugely* picky about the `bazel` version it requires).

Ah, sounds good! That (and improved documentation in the meantime) should go a long way to alleviating the frustrations of users who attempt to build `libtensorflow` from source.

**Comment by tafsiri** [comment]
@sbrl since you have been through that process recently, would you be interested in making a PR to the README with your suggestions?

**Comment by jumrz** [comment]
Hello,

I'm a user of tf-node-gpu on Win10 since long time ago and I was playing with a NVIDIA 980TI.
I really enjoyed it, so thank you very much for making it possible !

I recently sold my card to get a more powerful RTX 3070 (only for that) and today, I realize that I can't get tensorflow nodejs+cuda working anymore, cause it requires cuda11... while tfjs-node stayed stuck with cuda 10.0.

(I never paid attention before, as my previous config was working pretty well)

I'm not a strong developer as you can be and I totally don't know the amount of work that it could require to update tfjs-node to use the last versions of tensorflow + cuda.

But seriously guys... cuda 10.0 still in 2021 ?! If I'm not wrong, all recent cards RTX30xx are requiring cuda11 with ampere.
How should we do ? I can't believe that you let the main project evolve and you didn't follow it.

Please developers, tell me that I won't need to give up tfjs-node to switch back on the main tensorflow with Python ??

I sincerely hope that I am doing something wrong in my setup and that you'll have a solution for recent cards.
Thanks for your reply.

**Comment by vladmandic** [comment]
@pyu10055 @tafsiri @rthadur 

is there any plan for this?  

as it is, usage of `tfjs-node` is limited as some ops are missing and usage of `tfjs-node-gpu` is basically non-existent due to it's dependency on obsolete version of `CUDA`

**Comment by pyu10055** [comment]
@vladmandic Yes, we are working on supporting TF 2.4 c library, here is the issue related to that
https://github.com/tensorflow/tfjs/issues/4193

**Comment by sbrl** [comment]
> @sbrl since you have been through that process recently, would you be interested in making a PR to the README with your suggestions?

Unfortunately, I don't currently have a good record of what I did, so I'd have to go through the process all over again in order to write some documentation. As I am doing a PhD at the moment, I don't really have the time to do that right now.

**Comment by jumrz** [comment]
Hello,
I've followed the dev of the support 2.4 (https://github.com/tensorflow/tfjs/issues/4193) and I thank you a lot for it.

Is there any other dev needed to be able to use CUDA11 now ? (with tf-node-gpu on Win10)
Thanks for your return.

**Comment by rthadur** [comment]
if tf core supports CUDA 11 , tfjs-node-gpu will automatically support. closing this issue as this request is fulfilled here https://github.com/tensorflow/tfjs/issues/4193 , thank you

**Comment by sbrl** [comment]
Does this mean that I can now install the latest version of Tensorflow.js and use CUDA 11? Or is there still work that needs to be done in that area?
