### ISSUE TITLE
Is This Memory Leak on iOS / Android ?

### ISSUE THREAD

**Issue by gravestar** [tensorflow/tfjs#4318]
![image](https://user-images.githubusercontent.com/47879146/100567239-9a7c9200-32fa-11eb-9160-11e2dd90e670.png)

so everytime i trained a model, numTensors is increasing, im just wondering if this is bad or not ?
and when i close the apps, and start load the model and trained new model, it keeps increasing 
is it bad when i got so many model ? and how to fix this ?

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.
