### ISSUE TITLE
RangeError: Source is too large in saving/loading models

### ISSUE THREAD

**Issue by kumarde** [tensorflow/tfjs#432]
#### TensorFlow.js version
0.11.6

#### Browser version
Chrome 67

#### Describe the problem or feature request
I get the following error when trying to store a model to either localstorage or IndexedDB:

```
tfjs@0.11.6:1 Uncaught (in promise) RangeError: Source is too large
    at Uint8Array.set (<anonymous>)
    at tfjs@0.11.6:1
    at Array.forEach (<anonymous>)
    at concatenateTypedArrays (tfjs@0.11.6:1)
    at tfjs@0.11.6:1
    at n (tfjs@0.11.6:1)
    at Object.next (tfjs@0.11.6:1)
    at i (tfjs@0.11.6:1)
```

After a little digging, I found the bug to be in this function, specifically on this line: https://github.com/tensorflow/tfjs-core/blob/b400eed1cb234e951c287090e1c13513deb822aa/src/io/io_utils.ts#L137

This is because `y` is set to `totalByteLength` which is computed by iterating over the individual representations of each TypedArray. However, when copying over the contents, it's instead filled with `<typed_array>.buffer`, which can be larger than the `totalByteLength` calculation as this stores the individual byte representation of each byte in each type.

I think a reasonable fix would be to change L125 and L128 to instead use`e.buffer.byteLength`, which resolves the error, at least. However, I don't know if this will have any impact to functions upstream. I'm also not sure what it is specifically about my model that makes this bug appear, but it's appeared in every model I've tried to store/load.

If the fix I outline will solve the problem, I'm happy to submit a PR. 

Thanks!

**Comment by caisq** [comment]
@kumarde thanks for reporting this. Do you have an estimate of the total size of your model's weights? From what you described, I think it's possible that it's too large to fit in the browser's IndexedDB anyway.

**Comment by kumarde** [comment]
The size ilor the weights are around ~1.2MB, and there's 300K or so
parameters to the model overall.

Not sure about max size for indexedDB, but I'm pretty sure you can go up to
5MB without it complaining usually. Maybe there's some kind of increase in
storing the model that I'm not understanding, though.

**Comment by caisq** [comment]
OK. Then it's definitely small enough to fit into IndexedDB. 

Do you want to send a pull request  to fix this?
