### ISSUE TITLE
Inconsistent creation of tensor6d with nested Uint8Arrays

### ISSUE THREAD

**Issue by joemullenix-ks** [tensorflow/tfjs#4324]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10, Version 1909 (OS Build 18363.1198)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a
- TensorFlow.js installed from (npm or script link):
npm
- TensorFlow.js version:
2.7.0
- Browser version:
n/a
- Tensorflow.js Converter Version:
unknown

**Describe the current behavior**
TLDR: It appears the type definitions for tensor1-5d and tensor6d have inconsistent nested Uint8Array bracket counts. Please see the source at the bottom of this bug.

Full Story:
When creating tensors from nested Uint8Arrays, the results are not consistent across every supported rank (1-6). Specifically, rank 6 does not act like ranks 1-5.
_Regarding depth, I will consider Uint8Array[] as one-dimensional in this write-up, as I would with boolean[] or number[]. It's confusing with typed arrays._

- If you pass a 6d array of Uint8Array into tensor6d(), an error is thrown.
- If you pass the same 6d array into the generic tensor(), a rank 7 tensor is returned.
- If you pass a 5d array into tensor6d(), a rank 6 tensor is returned.

These cases may be perfectly valid (although they seem inconsistent). However, the behavior of the third case changes when applied to lower ranks.

- If you attempt to pass a 4d array into tensor5d(), a TypeScript error is produced, showing that 'Uint8Array[][][][] not assignable to TensorLike5D'.

It appears that one of these problems exists:
- The type for 6d Uint8Array is missing a pair of brackets.
OR
- The types for 1-5d Uint8Array each have an extra pair of brackets.

_NOTE: I'd be happy to fix this one, but I'm not certain which behavior is preferred. Should tensor5() accept 4d or 5d arrays of Uint8Array? Should the generic tensor() ever produce a rank 7, or should that throw?_

**Describe the expected behavior**
The generic call tensor() and the specific calls tensor<1-6>d() should return properly ranked tensors given identical Uint8Array input, and there should be no TypeScript errors.

**Standalone code to reproduce the issue**
```
import * as TF from '@tensorflow/tfjs-node';

const UI8_4: Uint8Array[][][][]     = [[[[new Uint8Array(3)]]]];
const UI8_5: Uint8Array[][][][][]   = [[[[[new Uint8Array(3)]]]]];
const UI8_6: Uint8Array[][][][][][] = [[[[[[new Uint8Array(3)]]]]]];

try {
	// using the generic tensor() call
	const TENSOR_6_MADE_FROM_6D_AUTO = TF.tensor(UI8_6); // rank 7, shape [1, 1, 1, 1, 1, 1, 3]
	const TENSOR_6_MADE_FROM_5D_AUTO = TF.tensor(UI8_5); // rank 6, shape [1, 1, 1, 1, 1, 3]

	// sending n-1 dimensions to the tensor<n>d() calls
	const TENSOR_6_MADE_FROM_5D = TF.tensor6d(UI8_5); // rank 6, shape: [1, 1, 1, 1, 1, 3]
	const TENSOR_5_MADE_FROM_4D = TF.tensor5d(UI8_4); // rank 5, shape: [1, 1, 1, 1, 3]; TypeScript: "Argument of type 'Uint8Array[][][][]' is not assignable to parameter of type 'TensorLike5D'. ts(2345)"

	// sending n dimensions to the tensor<n>d() calls
	const TENSOR_6_MADE_FROM_6D = TF.tensor6d(UI8_6); // crash: "Error: tensor6d() requires values to be number[][][][][][] or flat/TypedArray"
	const TENSOR_5_MADE_FROM_5D = TF.tensor5d(UI8_5); // crash: "Error: tensor5d() requires values to be number[][][][][] or flat/TypedArray"
}
catch (e) {
	console.log(e);
}
```

**Other info / logs**

This is the source in question (*.\tfjs-core\src\types.ts, lines 136-159*):
```
/** @docalias TypedArray|Array */
export type TensorLike =
    TypedArray|number|boolean|string|RecursiveArray<number|number[]|TypedArray>|
    RecursiveArray<boolean>|RecursiveArray<string>|Uint8Array[];
export type ScalarLike = number|boolean|string|Uint8Array;
/** @docalias TypedArray|Array */
export type TensorLike1D = TypedArray|number[]|boolean[]|string[]|Uint8Array[];
/** @docalias TypedArray|Array */
export type TensorLike2D = TypedArray|number[]|number[][]|boolean[]|boolean[][]|
    string[]|string[][]|Uint8Array[]|Uint8Array[][];
/** @docalias TypedArray|Array */
export type TensorLike3D = TypedArray|number[]|number[][][]|boolean[]|
    boolean[][][]|string[]|string[][][]|Uint8Array[]|Uint8Array[][][];
/** @docalias TypedArray|Array */
export type TensorLike4D = TypedArray|number[]|number[][][][]|boolean[]|
    boolean[][][][]|string[]|string[][][][]|Uint8Array[]|Uint8Array[][][][];
/** @docalias TypedArray|Array */
export type TensorLike5D =
    TypedArray|number[]|number[][][][][]|boolean[]|boolean[][][][][]|string[]|
    string[][][][][]|Uint8Array[]|Uint8Array[][][][][];
/** @docalias TypedArray|Array */
export type TensorLike6D =
    TypedArray|number[]|number[][][][][][]|boolean[]|boolean[][][][][][]|
    string[]|string[][][][][][]|Uint8Array[]|Uint8Array[][][][][];
```

**Comment by joemullenix-ks** [comment]
I'm not sure whether arrays belong in ScalarLike, but I don't believe that affects this issue. It's purely the implementation of 1-5 and 6 being done differently, regardless of type.

To me, it's pretty clearly a typo. Somebody just left out the last set of brackets on rank 6.


________________________________

**Comment by gaikwadrahul8** [comment]
Hi, @joemullenix-ks 

Apologize for the delayed response and I tried to replicate the same issue from my end with latest version of `@@tensorflow/tfjs-node@4.5.0` and I was getting below error message with your above code snippet mentioned in the issue template so for your reference I have added screenshot below so Are you also getting the same error message or difference error message please ? 

May I know are you still looking for solution or your issue got resolved please ? Thank you!

```
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ node tfjs.js
Platform node has already been set. Overwriting the platform with node.
Error: tensor6d() requires values to be number[][][][][][] or flat/TypedArray
    at Object.tensor6d (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:19044:15)
    at Object.<anonymous> (/Users/gaikwadrahul/Desktop/TFJS/tfjs.js:15:36)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ 
```
