### ISSUE TITLE
wasm backend is unusable for model training

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4326]
simple `tf.sequential` model with float32 input data normalized to 0..1 produces expected loss during training using `fit()` with `cpu` and `webgl` backends.

```log
onEpochEnd 0 {val_loss: 0.8914764523506165, loss: 0.5688045620918274}
...
onEpochEnd 19 {val_loss: 0.00248712464235723, loss: 0.004089016932994127}
```

but with `wasm` backend and same input data, loss values are all over the place and resulting trained model is unusable:

```log
onEpochEnd 0 {val_loss: 1.294883131980896, loss: 16261.525390625}
...
onEpochEnd 19 {val_loss: 222.3777618408203, loss: 188.08377075195312}
```

without digging into internals, it seems that `wasm` backend is doing some internal renormalization and casting to avoid using `float32`, but then forgets to do the opposite before returning values?

for reference, model is at <https://github.com/vladmandic/lstm/blob/main/src/model.js>

environment: tfjs 2.7.0 on chrome 87

**Comment by vladmandic** [comment]
any update on this one? this issue plus #4311 are making `wasm` usage a no-go - i'd even consider it a blocker.

**Comment by vladmandic** [comment]
@rthadur @annxingyuan is wasm backend getting any updates? this makes it very unreliable (and pretty much useless for training) and there are no updates at all.

**Comment by vladmandic** [comment]
@rthadur @annxingyuan @pyu10055 lina128 sorry for the spam,  

but i have 3 issues filled (#4525, #4326, #4311) for `wasm` backend (with full reproduction code)  
that make `wasm` pretty much unusable.  
and all likely have the same root cause, just symptoms are different.

but none received any updates since they were filed (oldest was 2.5 months ago).

**Comment by vladmandic** [comment]
likely fixed via #4730, awaiting confirmation

**Comment by lina128** [comment]
We are doing the release tomorrow morning, stay tuned.

**Comment by vladmandic** [comment]
upgraded to tfjs 3.2.0 and confirmed as resolved - `wasm` backend now returns same results as `webgl` backend when used for model training.
