### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by JonNieves** [tensorflow/tfjs#4327]
Found inconsistency

https://www.tensorflow.org/js/tutorials/setup - script uses tfjs@2.0.0

https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#1 - script uses tfjs@1.0.0

Also, I see "55 mins remaining" on top. Can I not be rushed? :(

**Comment by rthadur** [comment]
It is fixed now, thanks for reporting.
