### ISSUE TITLE
Uncaught (in promise) Error: This execution contains the node 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow/Where'

### ISSUE THREAD

**Issue by parthlathiya42** [tensorflow/tfjs#4333]
I am running inference in browser by using a tensorflow graph model converted from saved model generated by training mobilenet v1 from official tensorflow models zoo using tensorflow v2.x.

The model's inference runs fine when using model.executeAsync(...) but it blocks the UI thread of the browser.

When I use model.execute(...) instead, it shows up the error:

```
Uncaught (in promise) Error: This execution contains the node 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow/Where', which has the dynamic op 'Where'. Please use model.executeAsync() instead. Alternatively, to avoid the dynamic ops, specify the inputs [StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow/Reshape]
    at e.t.compile (tf.min.js:17)
```

As per the error, I do not wish to continue with the Async but want to specify the inputs that they say. How to do this?

**Comment by rthadur** [comment]
Can you please elaborate why you want to use execute here?

**Comment by sickopickle** [comment]
I have this same issue. Also, I want to use predictAsync, not executeAsync, but it doens't work. It says that predictAsync is not a funciton
