### ISSUE TITLE
[Question] Performance Gap in using SavedModels in TFJS

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/tfjs#4335]
To try out a basic version of a use-case I am working on. I use a Mobilenet based model with TFJS and observe a huge performance gap than the original SavedModel. I make use of [this model](https://tfhub.dev/google/aiy/vision/classifier/food_V1/1) to test out a basic version of the use-case.

I converted the SavedModel to TFJS without any compression techniques and use the TFJS Converter to do so. I use these few lines of code to test out the model-

```js
async function run() {
  const MODEL_URL = 'no-comp/model.json';
  const model = await tf.loadGraphModel(MODEL_URL);
  const img = document.getElementById('img');
  let inp = tf.browser.fromPixels(img, 3)
    .resizeNearestNeighbor([192, 192])
    .expandDims()
    .toFloat();

  const result = model.predict(inp).data();

  console.log(result)

}
```

This, as expected, gives me an array of shape `[1,2024]` and I would ideally be picking up the label with the highest confidence but this gives me a lot of mispredictions whereas running the original `SavedModel` gives a lot better performance. This also seems odd to me since I have used TFJS multiple times and not faced these kinds of issues.

**Comment by pyu10055** [comment]
@Rishit-dagli can you share what version of TFJS you are using and on what type of devices you are seeing this degrade of accuracy? Also, if you can share the models (both TF saved model and tfjs) with us to reproduce this problem would be great.

**Comment by Rishit-dagli** [comment]
@pyu10055 I am using the latest version of TFJS, as of now I tried running the model on multiple desktops and am facing the same problem with all the devices I run on. Here is the [SavedModel](https://storage.googleapis.com/rishit-dagli/tfjs%234335/saved-model/saved_model.pb) and the [TFJS model](https://storage.googleapis.com/rishit-dagli/tfjs%234335/tfjs/tfjs.zip) which I use as a `zip`.

**Comment by pyu10055** [comment]
@Rishit-dagli your model is quite straightforward, can you share your python code on how to execute the model?
For mobilenet model, it is common that the input needs to be normalized, your js code is not doing that, can you verify that?

**Comment by Rishit-dagli** [comment]
To try out a basic version of a use-case I am working on I make use of [this model](https://tfhub.dev/google/aiy/vision/classifier/food_V1/1) since this on TF Hub itself I make use of the embed on the model website to test the `SavedModel`.

Thank you for pointing that out, I was using this as an example code so I used a readily available Mobilenet inference script with TFJS and simply changed the pixel values since the normalizing steps were built-in. Thank you for pointing out that I missed the normalization steps, a small mistake from my end. I use-

```js
.sub(offset).div(offset)
```

to normalize the input image and that solves it.
