### ISSUE TITLE
[Question] Performance issue with the body-pix model

### ISSUE THREAD

**Issue by LoSunny** [tensorflow/tfjs#4342]
https://stackoverflow.com/questions/65101541/performance-issue-with-the-body-pix-model

I'm having issue with the node performance, while someone suggested that https://www.tensorflow.org/js/guide/nodejs#production_considerations 
But I don't know how to implement a worker

**Comment by rthadur** [comment]
Can you please refer to this links  https://medium.com/@wl1508/webworker-in-tensorflowjs-49a306ed60aa
https://medium.com/@wl1508/webworker-in-tensorflowjs-49a306ed60aa as how to implement web worker. Currently we do not have working example. Thank you

**Comment by LoYungSum** [comment]
But how do I send the data to the worker for it to process the information? Also, do I initialise the tf modal in the worker? Or pass it with the data?

**Comment by vladmandic** [comment]
@LoYungSum 
if you want, take a look at example <https://github.com/vladmandic/human/blob/main/demo/browser.js> that has both standard and webworker workflows.

**Comment by LoYungSum** [comment]
I'll take a look at it, thanks for the suggestion

**Comment by vladmandic** [comment]
also, a thread on web worker performance issues: <https://github.com/vladmandic/human/issues/2>
