### ISSUE TITLE
frequent getaddrinfo ENOTFOUND tfhub.dev on models

### ISSUE THREAD

**Issue by dcsan** [tensorflow/tfjs#4343]
**System information**
this is just to do with loading models, basic TF js code.

**Describe the current behavior**
frequently when loading models, I'll get an error like the below:

```
Uncaught Promise Rejection FetchError: request to https://tfhub.dev/tensorflow/tfjs-model/universal-sentence-encoder-lite/1/default/1/group1-shard1of7?tfjs-format=file failed, reason: getaddrinfo ENOTFOUND tfhub.dev
    at ClientRequest.<anonymous> (/Users/dc/dev/nlp/TfClassifier/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

**Describe the expected behavior**
Ideal would be a way to download the models locally for both speed and reliability.
otherwise, less network fails!

**Standalone code to reproduce the issue**

```
import * as sentenceEncoder from "@tensorflow-models/universal-sentence-encoder";
await sentenceEncoder.load()
```

but this is hard to repro as it seems to be a networking issues

**Other info / logs** Include any logs or source code that would be helpful to
see above

**Comment by rthadur** [comment]
@dcsan can you please share code snippet and model which you are trying to load ?

**Comment by dcsan** [comment]
@rthadur there is a code snippet above

```
import * as sentenceEncoder from "@tensorflow-models/universal-sentence-encoder";
await sentenceEncoder.load()
```

around here is where it times out.

is there any way to grab/cache the models locally rather than a network import every runtime?

**Comment by dcsan** [comment]
Not stale bot

**Comment by rthadur** [comment]
you can save the model using model.save("localstorage://model") locally.

**Comment by dcsan** [comment]
Actually I was asking about the encoder not my own models, as from the example above.

```
import * as sentenceEncoder from "@tensorflow-models/universal-sentence-encoder";
await sentenceEncoder.load()
```

I don't think `sentenceEncoder.save()` will work in the same way as for a model. I do of course use that already for saving and caching models.

**Comment by dcsan** [comment]
not stale :D

**Comment by rthadur** [comment]
May i know from which location you are trying to load tfhub models ?

**Comment by dcsan** [comment]
import * as sentenceEncoder from "@tensorflow-models/universal-sentence-encoder";

like written in the issue above

**Comment by rthadur** [comment]
some links does not work in china , I would like to know if you are accessing from china and one more thing we will not be supporting custom save function in universal-sentence-encoder in near future.

**Comment by dcsan** [comment]
No I'm not accessing from China.

So there is no way to pull the model down locally, it has to be re-downloaded for every run?
meaning this function:

`await sentenceEncoder.load()`

pulls a large model over the network every time I run my process?

**Comment by kucukkanat** [comment]
I am super disappointed I have been searching to figure this issue out myself for hours now only to end up in here 🤦 . 
I tried hacking the library, intercepting the network even to figure where it downloads the damn file. Even if I figure, idk if I will be able to load it from the file I downloaded. 
Going back to huggingface sentence transformers, thanks for the disappointment.

**Comment by martindale** [comment]
This is happening when importing `@langchain/community/embeddings/tensorflow` with no Internet connection:

```js
const { TensorFlowEmbeddings } = require('@langchain/community/embeddings/tensorflow');
```

Error:
```
node:internal/deps/undici/undici:11731
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11731:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: getaddrinfo ENOTFOUND tfhub.dev
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'tfhub.dev'
  }
}
```
