### ISSUE TITLE
WebGL backend should include an environment variable to toggle failIfMajorPerformanceCaveat value.

### ISSUE THREAD

**Issue by wingman-jr-addon** [tensorflow/tfjs#4347]
I've run into an interesting situation.

Recently, when Firefox upgraded from 82 to 83, performance on [my addon](https://github.com/wingman-jr-addon/wingman_jr) dropped sharply for myself and some other users as well. I traced the issue to the WebGL backend failing to load due to `failIfMajorPerformanceCaveat` exhibiting a change in behavior between the two versions. As this was negatively affecting my users, I quickly added in the WASM backend as an option. However, while this was [faster for some users](https://github.com/wingman-jr-addon/wingman_jr/issues/75#issuecomment-734822117) - thank you TF.js team for your awesome work! - for others like myself it seems to still be a blocking issue.

When I [did a bisection and filed a bug with Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1679671), their initial response is that it is likely that `failIfMajorPerformanceCaveat` had a bug in FF 82 but that has now been fixed, and that the context creation *should* be failing by the spec.

So this puts me in an interesting spot. With the evidence I have so far, I believe there are a significant number of users that would still benefit from the WebGL backend - even with "major performance caveats" - over the WASM backend. Unfortunately, it appears that the `failIfMajorPerformanceCaveat` is [hardcoded](https://github.com/tensorflow/tfjs/blob/c537c813ba8234a909d1e0849abfd95998a8fb5b/tfjs-backend-webgl/src/canvas_util.ts#L27) rather than relying on say an environment variable or something I can tweak to allow for a different user experience.

So, I have a couple followup questions:

1. Is the use of `failIfMajorPerformanceCaveat` solely about performance for the end user, or is there a correctness concern as well?
2. If it is solely about performance, would the TF.js team consider making this controllable via, say, an environment variable?

Maybe I'm missing something about the overall situation, but I've been battling this for about a week and a half now and I'm curious your perspective on the matter.

Thanks!

**Comment by pyu10055** [comment]
@wingman-jr-addon I believe you can create your own webgl backend using your own gl context.
similar to how we register webgl backend for wechat mini program ([link](https://github.com/tensorflow/tfjs-wechat/blob/master/src/plugin/utils/wechat_platform.ts#L127))

**Comment by wingman-jr-addon** [comment]
@pyu10055 Thanks for the tip - as per my first question, do you know if there are any correctness concerns if I do that?

**Comment by annxingyuan** [comment]
Hi @wingman-jr-addon - I don't believe there would be correctness concerns with creating your own WebGL backend. Per the [Khronos documentation](http://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2) of this attribute, it should only be relevant to performance.

I think it would be reasonable to add a WebGL environment variable to toggle this value - thanks for the suggestion! I've renamed this issue to reflect.

**Comment by wingman-jr-addon** [comment]
Thanks @annxingyuan - and that was also a good link to the spec; I learned a few things about some of the additional flags, too!

**Comment by wingman-jr-addon** [comment]
@annxingyuan and @pyu10055 I think you may be interested to see the direction Firefox has taken now regarding this flag in the linked bugs [1684475](https://bugzilla.mozilla.org/show_bug.cgi?id=1684475) and [1678652](https://bugzilla.mozilla.org/show_bug.cgi?id=1678652).

**Comment by gaikwadrahul8** [comment]
Hi, @wingman-jr-addon 

Apologize for the delayed response and I found similar issue https://github.com/tensorflow/tfjs/issues/6606 and also please refer above comments from @pyu10055 and @annxingyuan which answered your questions.

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
