### ISSUE TITLE
Return type of tf.oneHot depends on backend

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#435]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.8

#### Browser version
irrelevant

#### Describe the problem or feature request
tf.oneHot returns a tensor of dtype 'float32' with some backends, and with dtype 'int32' in other backends.

#### Code to reproduce the bug / link to feature request

```
describeWithFlags('oneHotType', ALL_ENVS, () => {
  expectedType = 'int32'
  fit('Output type is what', () => {
    const indices = tf.tensor1d([0, 1], 'int32');
    const res = tf.oneHot(indices, 2);
    console.log("XXXXXXXXXXXXXXXX");
    console.log(res.dtype);
    expect(res.dtype).toEqual(expectedType);
  });
});
```
outputs
```
LOG: 'XXXXXXXXXXXXXXXX'
LOG: 'int32'
LOG: 'XXXXXXXXXXXXXXXX'
LOG: 'int32'
LOG: 'XXXXXXXXXXXXXXXX'
LOG: 'float32'
Chrome 67.0.3396 (Linux 0.0.0) oneHot {"BACKEND":"test-cpu"} Output type is int32 FAILED
	Expected 'float32' to equal 'int32'.
	    at <Jasmine>
	    at UserContext.<anonymous> (src/ops/array_ops_test.ts:2171:22 <- src/ops/array_ops_test.js:7084:39)
	    at <Jasmine>

```

**Comment by ManrajGrover** [comment]
@bileschi Looks like CPU backend was using default `float32` as `dtype`. Providing `int32` as `dtype` to output fixes it.
