### ISSUE TITLE
Cannot compute the outputs [Identity_1,Identity] from the provided inputs [input_1:0,input_2:0]. Consider providing the following inputs: []. Alternatively, to avoid the dynamic ops, use model.execute() and specify the inputs [StatefulPartitionedCall/encoder/gru/StatefulPartitionedCall/while/LoopExecuted/_63]

### ISSUE THREAD

**Issue by venkat-ravilla** [tensorflow/tfjs#4350]
**System information**
- TensorFlow.js installed from (npm or script link):npm
- TensorFlow.js version (use command below):2.7.0

**Current behavior**
I have a graph model built using tensorflow(python) which is an encoder model with tf version 2.3.0. I have converted it using tensorflow_converter (command **tensorflowjs_converter --input_format=tf_saved_model encoder/ encoderjs**).
When I try to run the model using **executeAsyc**, I get the below error:
```
Error: Cannot compute the outputs [Identity_1,Identity] from the provided inputs [input_1:0,input_2:0]. Consider providing the following inputs: []. Alternatively, to avoid the dynamic ops, use model.execute() and specify the inputs [StatefulPartitionedCall/encoder/gru/StatefulPartitionedCall/while/LoopExecuted/_63]
    at GraphExecutor.<anonymous> (/space/users/rvenkatar/savedmodel/v2/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6918:35)
    at step (/space/users/rvenkatar/savedmodel/v2/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:77:23)
    at Object.next (/space/users/rvenkatar/savedmodel/v2/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:58:53)
    at fulfilled (/space/users/rvenkatar/savedmodel/v2/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:48:58)
```
Not able to figure out what the issue is from above error.

**Expected behavior**
It should return array of two outputs(encoded output, hidden state) 
**Standalone code to reproduce the issue**
```
const tfn = require('@tensorflow/tfjs-node');
const tf = require('@tensorflow/tfjs');
const input = [1, 28, 47, 26, 137, 14, 3, 96, 17, 76, 133, 65, 2, 0, 0, 0];
const hidden = tf.zeros([1,1024]);
async function predictSample(sample) {
  const inputTensor = tf.tensor(input, [1,input.length],'int32');
  const handler = tfn.io.fileSystem("./encoderjs/model.json");
  const model = await  tf.loadGraphModel(handler);
  let results = {};
  try{
    const values = model.executeAsync({"input_1:0":inputTensor,"input_2:0":hidden},["Identity_1:0","Identity:0"]);
  }catch(error){
    console.log(error);
    return "error prediction"
  }
  //console.log(values);
  return values;
}
predictSample().then((x)=>{console.log("success")}).catch((e)=>{console.log(e)})
```
Does tensorflow.js support above operations?

**Comment by rthadur** [comment]
@venkat-ravilla can you please check a related issue [here](https://github.com/tensorflow/tfjs/issues/2254)

**Comment by venkat-ravilla** [comment]
I tried adding inputs and outputs as mentioned in the link, but still the same issue

**Comment by venkat-ravilla** [comment]
Any update on the issue?

**Comment by venkat-ravilla** [comment]
I am still waiting for the resolution.

**Comment by pyu10055** [comment]
@venkat-ravilla can you provide a codepen example for reproducing this error? thanks

**Comment by HarshalRohit** [comment]
I facing similar issue.
Converted a keras .h5 model to tfjs_graph_model, and it doesn't show any issues on loading but using prediction/executeAsync/execute throws similar error. 

The same .h5 model converted to tfjs_layers_model works correctly.
My use-case involves performing predictions in react-native application.

I will be happy to share more details, if required.

**Comment by HarshalRohit** [comment]
@rthadur Should I raise a new Issue?

**Comment by rthadur** [comment]
@HarshalRohit yes, please use the template https://github.com/tensorflow/tfjs/issues/new/choose , thank you

**Comment by venkat-ravilla** [comment]
@pyu10055 I am trying to use https://www.tensorflow.org/tutorials/text/nmt_with_attention.
I am using the same NN architecture as above, saved the encoder model, converted it using tfjs and facing the issue while running it in nodejs.

**Comment by tempdeltavalue** [comment]
graph_executor.js:599 Uncaught (in promise) Error: Cannot compute the outputs [Identity] from the provided inputs [inputs:0]. Consider providing the following inputs: []. Alternatively, to avoid the dynamic ops, use model.execute() and specify the inputs [Identity]
    at h (tf.min.js:17:2100)
    at Generator.<anonymous> (tf.min.js:17:3441)
    at Generator.next (tf.min.js:17:2463)
    at u (tf.min.js:17:8324)
    at o (tf.min.js:17:8527)

        const res = model.executeAsync({"inputs:0":x}).then(predictions => {
            console.log(predictions)
        }); 
        
  issue still lives
