### ISSUE TITLE
The posenet detection speed is too slow

### ISSUE THREAD

**Issue by carterinchina** [tensorflow/tfjs#4351]
The posenet detection speed is too slow, it takes about 300 milliseconds

I use tfjs-react-native's posetnet to detect pose, but the detection speed is very slow. EstimateSinglePose takes 300 milliseconds to return the result. How can it be faster

tf.setBackend（“rn-webgl”）

model:
  const model = await posenet.load({
          
            architecture: 'MobileNetV1',
            outputStride: 16,
            multiplier: 1,
            inputResolution: 257,
        });

phone:pixel  android 10

**Comment by tafsiri** [comment]
See the documentation on the [config options for posenet](https://github.com/tensorflow/tfjs-models/tree/master/posenet#config-params-in-posenetload) for ideas on different settings you can try that have an effect on performance. The multiplier and outputStride parameters may be of particular interest to you.
