### ISSUE TITLE
The Node.js native addon module (tfjs_binding.node) can not be found at path

### ISSUE THREAD

**Issue by JLizardo019** [tensorflow/tfjs#4359]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Big Sur
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs-node
- TensorFlow.js version: 2.7.0
- Node version: v14.15.1

**Describe the problem**
Every time I try to start my Node server, I run into an error that says tfjs_binding.node cannot be found.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`npm init`
`npm install @tensorflow-models/toxicity`
`npm install @tensorflow/tfjs-node`
`npm start`

**Any other info / logs**
Here is the main error log:

> Platform node has already been set. Overwriting the platform with [object Object].
> /Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/dist/index.js:49
>     throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
>     ^
> 
> Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node. 
> Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module. 
> If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
>     at Object.<anonymous> (/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/server.js:4:17)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

This is the log when I run the suggested command `npm rebuild @tensorflow/tfjs-node build-addon-from-source`:

> * Building TensorFlow Node.js bindings
> node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
> node-pre-gyp WARN Using needle for node-pre-gyp https download 
> node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.7.0/CPU-darwin-2.7.0.tar.gz 
> node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.7.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
> action_after_build.target.mk:6: *** missing separator.  Stop.
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Darwin 20.1.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/lib/napi-v6" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
> gyp ERR! cwd /Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node
> gyp ERR! node -v v14.15.1
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> node-pre-gyp ERR! System Darwin 20.1.0
> node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /Users/julieliz/Desktop/ITP Classes/Machine Learning/Assignment #9/toxicity/node_modules/@tensorflow/tfjs-node
> node-pre-gyp ERR! node -v v14.15.1
> node-pre-gyp ERR! node-pre-gyp -v v0.14.0
> node-pre-gyp ERR! not ok 

I have tried upgrading/downgrading node, rebuilding node modules, and manually updating node-pre-gyp with no luck. Please advise. I would appreciate the help.

**Comment by pyu10055** [comment]
your problem might be solved with the upcoming node release, which support napi 7.

**Comment by Floffah** [comment]
i fixed this by moving to an older node version via nvm
