### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by JungangLUO** [tensorflow/tfjs#4360]
![image](https://user-images.githubusercontent.com/71870800/101284798-c88f3400-381c-11eb-980b-c1ad84f03f7f.png)

So I strictly followed a tutorial of this Node-RED project: https://github.com/IBM/node-red-tensorflowjs/blob/master/README.md#start-node-red.

First I used Node.js v14 LTS, got this error, then I came here and tried a solution which suggested using Node.js v12, but still I got this error. I can find no answer. 

**Why would I have this error and how can I fix it?** Would appreciate any help please I'm very new to both node red and tensorflow.

**Comment by rthadur** [comment]
please post the question on same [repo](https://github.com/IBM/node-red-tensorflowjs/blob/master/README.md#start-node-red) as we do not maintain it. thank you

**Comment by pvaneck** [comment]
@JungangLUO Similar issues are here: https://github.com/tensorflow/tfjs/issues/4116 . I'm not sure if this is specifically your issue, but try checking `deps/lib` in your tfjs-node install directory and see if there is a tensorflow.dll in there that can be copied over to `lib/napi-*`. There seem to be some issues installing tfjs-node on Windows depending on versions of Node used.

Also, were there any install errors when you did the `npm install` to install all the dependencies? Maybe worth trying to install the latest tfjs-node as that project uses 2.0.1 based on the package-lock.json.
