### ISSUE TITLE
The tfjs-node-gpu occupies almost all GPU memory after loading model

### ISSUE THREAD

**Issue by lionkunonly** [tensorflow/tfjs#4363]
I run the `tfjs-node-gpu` on Linux.  The NVIDIA 1080Ti is equipped in my computer and it has 11175MB memory. However, when I run a model where its size of weights is only 87 MB, the `nvidia-smi` shows that the 99947 MB is occupied by the node.js server. I think the reason is that I run the model with `tfjs-node-gpu` on the node.js and provide service for users. 

The real problem is that when the `tfjs-node-gpu` occupies so much memory that the OOM problem happens when users send lots of requirements to the server for AI service. Do you know how to solve this problem?

System: Ubuntu 18.04
GPU: NVIDIA 1080Ti
CUDA version: 10.1
tfjs-node-gpu version: 2.5.0

**Comment by pyu10055** [comment]
@lionkunonly Is this model converted from TF saved model?
If so, you can try to using [tfjs-node direct saved model execution](https://blog.tensorflow.org/2020/01/run-tensorflow-savedmodel-in-nodejs-directly-without-conversion.html).

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
