### ISSUE TITLE
Resize Bilinear behaves differently 

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#4364]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

The problem is the tensorflow python code and the tensorflowjs code use different methods for bilinear interpolation. The tensorflow code uses the half-pixel method while the tfjs code uses two different methods depending on align corners and neither one is similar. 

python version - https://colab.research.google.com/drive/1ID3yDkG8vyODerZbaAOeK5QS_06v8A8v?usp=sharing
javascript version - https://codepen.io/rohan-uplara/pen/mdrEeMw; look at console
different approaches -  (https://jricheimer.github.io/tensorflow/2019/02/11/resize-confusion/ )  What would you suggest for us to do? 

Specific Question 
I just looked and it seems  resizing is supported in master? https://js.tensorflow.org/api/latest/#image.resizeBilinear is not there but in the master https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/image/resize_bilinear.ts#L47 it is. Is it possible somehow to use the master and if so how do build it? Second, if we are able to get this custom layer to work, how do we make sure when we do the tensorflow to tfjs conversion to make sure it calls resizeBilinear in the right way. Additionally, right now by default tensorflow python has half-pixels enabled on (you actually can't turn it off from my understanding) tensorflowjs has it false.  

Any help would be appreciated. 

**System information**
- mac os
 -script link
- TensorFlow.js version (2.7):
chrome-Version 86.0.4240.198

**Comment by Shawn-Chahal** [comment]
See similar issue: https://github.com/tensorflow/tfjs/issues/4340

**Comment by pyu10055** [comment]
@rohanmuplara [half-pixel support](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/image/resize_bilinear.ts#L41) has just been added, if it is still not available in the latest release, it should be available in upcoming release 2.8.0, which will be cut this week.

**Comment by rohanmuplara** [comment]
Thanks so much @pyu10055

**Comment by rthadur** [comment]
related PR has been merged , so closing the issue.Thank you
