### ISSUE TITLE
Add Support for BilinearUpSampling2D Layer for Keras model

### ISSUE THREAD

**Issue by jmlb** [tensorflow/tfjs#437]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.6
#### Browser version
Version 67.0.3396.62 (Official Build) (64-bit)
#### Describe the problem or feature request
When I import my model in tfjs, I get the error: 
`Error: Unknown layer: BilinearUpSampling2D`

**Comment by caisq** [comment]
@jmlb Do you know whether `BilinearUpSampling2D` is an official layer in Keras. It doesn't seem to be in the documentation at https://keras.io/ or in the source code in https://github.com/tensorflow/tensorflow

Is it possible that your Keras model artifacts are saved from Python code using Keras and a customly defined layer (`BilinearUpSampling2D`)?

**Comment by kylemcdonald** [comment]
BilinearUpSampling2D is not an official layer in Keras.

Here's are two implementations I found:

- https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/layers/BilinearUpSampling.py#L45-L110
- https://github.com/penny4860/FCN/blob/master/keras_fcn/layers.py#L8-L41

Interestingly, neither of them set `align_corners=True`. From my read of issues like https://github.com/tensorflow/tensorflow/issues/6720 it's an open question whether the default behavior is desired or not going forward. Another description of this "bug" is provided here https://hackernoon.com/how-tensorflows-tf-image-resize-stole-60-days-of-my-life-aba5eb093f35

**Comment by jmlb** [comment]
Thanks for the reply. I am using the same implementation as in https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/layers/BilinearUpSampling.py#L45-L110 (@kylemcdonald ). 
Great suggestion: I will convert the model to TF.
BTW, thank you for the discussion and links about `align_corners`...something I was not aware of. Very interesting reading.

**Comment by bileschi** [comment]
@jmlb You may be able to get this working sooner by using a custom layer in tfjs.  See here for an example custom layer https://github.com/tensorflow/tfjs-examples/tree/master/custom-layer

**Comment by bhack** [comment]
There is no upstream bandwidth to review https://github.com/keras-team/keras/pull/9303.
I think that it is "a general status" of keras.

**Comment by caisq** [comment]
Closing the issue as the layer is still not a standard layer in Keras. Users can implement the custom layer.
