### ISSUE TITLE
Tensorflow.js with wasm backend is trying to use unsupported function 'resizeNearestNeighbor', even though I used bilinear interpolation in all the places

### ISSUE THREAD

**Issue by martun** [tensorflow/tfjs#4386]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): pip install tensorflowjs
- TensorFlow.js version (use command below): 2.7.0
- Browser version: Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Tensorflow.js Converter Version: v2.4.0

**Describe the current behavior**
Tensorflow.js with wasm backend is trying to use unsupported function 'resizeNearestNeighbor', even though I used bilinear interpolation in all the places. I get the following error when trying to run inference in the browser "Error: 'resizeNearestNeighbor' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen".
Code runs smoothly but slowly when switching to "cpu" backend.

**Describe the expected behavior**
I would like the inference to run without errors and use Bilinear interpolation which is supported on all the backends.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

I can not share the trained weights, but the rest of inference code is here. You can see the model.json file, which does not contain any nearest neighbor interpolation. 
https://github.com/martun/tensorflow_js_issue

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tafsiri** [comment]
Related to https://github.com/tensorflow/tfjs/issues/4340 and https://github.com/tensorflow/tfjs/issues/4212

The underlying issue is the UpSampling2D layer (used in your model0 directly calls `resizeNearestNeighbor` and doesn't seem handle the bilinear interpolation option. @pyu10055 @caisq, should this be an enhancement to the UpSampling2D layer?

**Comment by caisq** [comment]
@tafsiri I agree this should be considered as an enhancement. It is currently unimplemented is most likely lack of support by tfjs-core. So it's possible that the nearest-neighbor resampling support is still unavailable from tfjs-core and that'll need to be addressed first.

**Comment by tafsiri** [comment]
@caisq tfjs-core has both resizeNearestNeighbour (currently called) and resizeBilinear, so we should be able to switch on that unless resizeBilinear does not support something required by upsampling2d.

**Comment by tafsiri** [comment]
@caisq Actually looks like its been added!

**Comment by martun** [comment]
Thanks guys, it started to work after I updated to tfjs version: 2.8.0
