### ISSUE TITLE
tfjs-models/face-landmarks-detection/demo/ TypeError: Fail to fetch

### ISSUE THREAD

**Issue by Sunyingbin** [tensorflow/tfjs#4394]
Hi , I run this demo in my macbook, I don't have VPN, How to synchronize the model and store it myself. thank you!

**Comment by rthadur** [comment]
@Sunyingbin please check here for various ways to download model fileshttps://www.tensorflow.org/js/guide/save_load#file_downloads_browser_only , please let us know why you are using VPN ?

**Comment by Sunyingbin** [comment]
In China， I can't fetch the model

**Comment by rthadur** [comment]
@Sunyingbin the model links are not accessible from china , please check here for related previous issue https://github.com/tensorflow/tfjs/issues/1375
cc @pyu10055 cc @jasonmayes

**Comment by rthadur** [comment]
Can you please try here https://gstaticcnapps.cn/tfjs-models/ , these URL is specific to users in China. Thank you

**Comment by Sunyingbin** [comment]
> https://gstaticcnapps.cn/tfjs-models/

Sorry, I am not a professional front-end developer, do you mean to modify the address pointed to by the model?
https://tfhub.dev/mediapipe/tfjs-model/iris/1/default/2 -- 》https://gstaticcnapps.cn/tfjs-models/iris/1/default/2
yes？ but i try，it's not working

**Comment by Sunyingbin** [comment]
tfjs-models/face-landmarks-detection/ in this case，How should I download the model locally and point it to it

**Comment by rthadur** [comment]
This should be fixed soon , will update the thread with updated urls, thank you

**Comment by wangtz** [comment]
Hi Sunyingbin,

TFHub models have been mirrored. You should be able to download the model from https://hub.tensorflow.google.cn/mediapipe/tfjs-model/iris/1/default/2

Let me know if it works.
Thanks,
Tiezhen
