### ISSUE TITLE
Chrome with Mac Silicon(M1): WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

### ISSUE THREAD

**Issue by huan** [tensorflow/tfjs#4396]
I'm running https://github.com/lmoroney/dlaicourse/blob/master/TensorFlow%20Deployment/Course%201%20-%20TensorFlow-JS/Week%202/Examples/mnist.html and get this error.

The same HTML works without any problem on my Intel MacBookPro Chrome browser.

M1 Silicon Versions:

1. `@tensorflow/tfjs@2.7.0`
1. Chrome Version 87.0.4280.88 (Official Build) (arm64)
1. macOS 11.0.1 (20B29)

```
tfjs@latest:17 Uncaught (in promise) Error: Failed to compile fragment shader.
    at mP (tfjs@latest:17)
    at e.t.createProgram (tfjs@latest:17)
    at tfjs@latest:17
    at tfjs@latest:17
    at t.n.getAndSaveBinary (tfjs@latest:17)
    at t.n.runWebGLProgram (tfjs@latest:17)
    at Object.kernelFunc (tfjs@latest:17)
    at p (tfjs@latest:17)
    at tfjs@latest:17
    at e.t.scopedRun (tfjs@latest:17)
```

**Comment by alkamin** [comment]
What OS are you running on each machine?

**Comment by rthadur** [comment]
Looks like an issue with latest M1, pleas check here for a similar issue [here](https://github.com/tensorflow/tfjs/issues/4166), thank you

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by vladmandic** [comment]
just a thought - GPU on M1 platform is not a discrete GPU, it is an integrated one so memory is shared.  
TFJS memory usage when using `WebGL` backend is high, so it's likely OSX that denies Chrome's request for memory allocation.   
You didn't mention which GPU is in your Intel-based Mac.
