### ISSUE TITLE
JS Error in demo 

### ISSUE THREAD

**Issue by deepnov** [tensorflow/tfjs#4397]
**System information**

Demo URL mentioned in the link (https://github.com/tensorflow/tfjs-models/tree/master/qna)
https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html is not working!

**Describe the expected behavior**
I didn't get answers to any question. Attaching the error here.
![demoerror](https://user-images.githubusercontent.com/2010921/102015121-af880500-3d7f-11eb-9f09-eef093a6cbaa.JPG)

**Comment by rthadur** [comment]
There is a similar issue [here](https://github.com/tensorflow/tfjs/issues/3861) for tracking , will close this and track it at one place.
