### ISSUE TITLE
node-gyp configure --verbose "gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp"

### ISSUE THREAD

**Issue by mdjfs** [tensorflow/tfjs#4401]
I'm seeing the doc about windows troubleshooting because i have a unexpected error while i'm trying to use @tensorflow/tfjs-node module. That are my versions:

Python: 2.7.18
Node: 10.17.0
NPM: 7.1.2

When i call require("@tensorflow/tfjs-node") in any program, i got this error:

`Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\Marco\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.`
 
I trying to rebuild the package and it's all right:

`npm rebuild @tensorflow/tfjs-node build-addon-from-source`
`rebuilt dependencies successfully`

Then, I looked the doc and i go to node_modules/@tensorflow/tfjs-node and i run the command

 `node-gyp configure --verbose`

but I see the error:

`gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp`

What can I do in that case?

**Comment by rthadur** [comment]
can you try with V node > 12  ?

**Comment by mdjfs** [comment]
> 
> 
> can you try with V node > 12 ?

Recently i try with that and i get the same error, here the full error:

`gyp info spawn C:\Users\Marco\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Marco\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Marco\\OneDrive\\Documentos\\Tesis\\Test2\\node_modules\\@tensorflow\\tfjs-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Marco\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Marco\\AppData\\Local\\node-gyp\\Cache\\12.20.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Marco\\AppData\\Local\\node-gyp\\Cache\\12.20.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Marco\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Marco\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.20.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Marco\\OneDrive\\Documentos\\Tesis\\Test2\\node_modules\\@tensorflow\\tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Marco\\OneDrive\\Documentos\\Tesis\\Test2\\node_modules\\@tensorflow\\tfjs-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Marco\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Marco\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd C:\Users\Marco\OneDrive\Documentos\Tesis\Test2\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok`

I exec the command node-gyp configure --verbose in node_modules/@tensorflow/tfjs-node

Thanks, but nothing happens btw

**Comment by rthadur** [comment]
can you please try with latest version 2.8.1 ?

**Comment by mdjfs** [comment]
> 
> 
> can you please try with latest version 2.8.1 ?

Same error when I exec the command node-gyp configure --verbose in node_modules/@tensorflow/tfjs-node

I install the version 2.8.1 of @tensorflow/tfjs-node 

![image](https://user-images.githubusercontent.com/56895143/102952766-4a7e8e80-44a6-11eb-8587-8fb866dabcd3.png)

![image](https://user-images.githubusercontent.com/56895143/102952794-58341400-44a6-11eb-8b70-029142961a13.png)

**Comment by mdjfs** [comment]
Hey! But I see something new:

![image](https://user-images.githubusercontent.com/56895143/102953027-cd074e00-44a6-11eb-97ee-9ee2a3ac37b7.png)


I hear about the package works better with python 2.7, but i have python 2.7, look:

![image](https://user-images.githubusercontent.com/56895143/102953073-e01a1e00-44a6-11eb-96a9-43b2c48aa228.png)

**Comment by mdjfs** [comment]
The issue only happens in Windows. Works in linux with WSL btw

**Comment by sbrl** [comment]
@mdjfs Not true. I can reliably reproduce this in a Docker container on Linux. The Docker container's name is `nvcr.io/nvidia/tensorflow:19.02-py3`. Logs: https://pastebin.com/4AEyc2cP

**Comment by djbreen7** [comment]
Same problem here:
tfjs-node: 3.7.0
node.js: 14.16.0
npm: 6.14.11
electron: 12.0.14

No luck in WSL.

Also worth noting: It works fine when I'm serving the app in development mode. I only have issues when I package the application and install it.

I can't upgrade to a higher version of node/npm because it will break electron. LTS (13.1.6) electron still uses node.js 14.6.0. Furthermore, node.js 14.6.0 uses Node-API v7.

I've done a lot of digging today. This binding.gyp error is the latest find. I read of other packages with a similar issue being resolved when developers downgraded from npm 7.x to 6.x. I tried both 6.x and 7.x here with no luck.
