### ISSUE TITLE
Tips for blazeface performance on Chromebooks?

### ISSUE THREAD

**Issue by ericrosenbaum** [tensorflow/tfjs#4410]
I've been testing blazeface on a lower end Chromebook (a Samsung Chromebook 3). Curious if anyone has ideas for performance improvements. Here are my observations so far:

- The demo runs at about 12fps
- While also using Google Meet for video chat, with camera on, the demo drops to 2fps
- Running blazeface inside our web app, we are seeing about 6fps
- This Chromebook is able to use the webgl backend, and it is faster than using wasm
- We are sending webcam image-data to blazeface at 480x360
- Looks like inputWidth and inputHeight cannot be set below the default 128

Would setting `maxFaces` to 1 (which is fine for me application) be expected improve performance?

Is there anything else we can do to improve frame rates?

**Comment by tafsiri** [comment]
👋  A few random thoughts:
- With the WASM backend you could [try enabling SIMD](https://v8.dev/features/simd#enabling-experimental-simd-support-in-chrome). This might also help the scenario where you are simultaneously using meet as when the two are running I believe they are both competing for GPU access.
- Smaller input images should generally be faster (at the risk of loss of accuracy) but I would experiment with that.
- I'm curious about the diff in fps between the demo and your webapp, I can't guess where the discrepancy may be coming from, but isolating what is causing the difference (maybe your app is doing something intensive that can be interleaved with blazeface). Comparing with the options [used in the demo](https://github.com/tensorflow/tfjs-models/blob/master/blazeface/demo/index.js#L58) might help?

cc @annxingyuan in case she has any other ideas.

**Comment by willmorgan** [comment]
How are you getting imagery into the model?

Have you tried performance profiling your app?

One cause of the holdup could be `getImageData`. Using canvas as an input method (due to running off main thread), I find that `getImageData` takes a significant amount of time  - 78ms on a 2017 Macbook Pro. That's using a small canvas - 320x180.
