### ISSUE TITLE
examples: tfjs-examples/firebase-object-detection-node fails to run

### ISSUE THREAD

**Issue by ahmetb** [tensorflow/tfjs#4415]
Sample code in https://github.com/tensorflow/tfjs-examples/tree/master/firebase-object-detection-node not working with Node v15.4.0, `/predict` endpoint fails with error:

```
(node:13194) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/ahmetb/workspace/junk/tfjs-examples/firebase-object-detection-node/functions/index.js:59
    const buf = req.files.file[0].buffer;
                                  ^

TypeError: Cannot read property 'buffer' of undefined
    at Busboy.<anonymous> (/Users/ahmetb/workspace/junk/tfjs-examples/firebase-object-detection-node/functions/index.js:59:35)
    at Busboy.emit (node:events:388:22)
    at Busboy.emit (/Users/ahmetb/workspace/junk/tfjs-examples/firebase-object-detection-node/functions/node_modules/busboy/lib/main.js:37:33)
    at /Users/ahmetb/workspace/junk/tfjs-examples/firebase-object-detection-node/functions/node_modules/busboy/lib/types/multipart.js:304:17
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**Comment by rthadur** [comment]
@ahmetb can you try with latest 2.8.1 v ? thank you

**Comment by ahmetb** [comment]
Doesn't work. I had to refactor the code and remove some statements like busboy.end for this to work. 

Highly recommend reproing it yourself. Overall code quality also isn't great.

**Comment by ahmetb** [comment]
If you're interested in seeing the patch that made it work for me on Node 15.x, take a look at here (I removed Firebase Functions boilerplate, as I was converting it to a container image for Cloud Run).

https://www.diffchecker.com/AZUp1iPX I know no Node.js at all, but I figured the choices around storing values and flowing data between closures were quite odd. So I took a stab at that, too.

**Comment by gaikwadrahul8** [comment]
Hi, @ahmetb 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not so May I know your issue got resolved or still you're looking for solution ? 

I see you had proposed some workaround  with `Node v15.4.0` but it seems like we haven't updated `tfjs-examples/firebase-object-detection-node` with your workaround so now could you please try with latest version of `Node` and check whether `tfjs-examples/firebase-object-detection-node` fails to run or not ? 

If issue still persists after with latest version please let us know ? Thank you!
