### ISSUE TITLE
tfjs 2.8.0 is broken and introduces regressions in tf.image.cropAndResize

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4418]
As subject line says, TFJS 2.8.0 unfortunately seems like a broken version.

First, default parameter in `cropAndResize` was unintentionally removed (and apparently just re-added via #4407) which causes quite a lot of errors in existing apps

Second, even when specifying resize method as `bilinear`, `cropAndResize` FAILS on `WebGL` baclend:

```
Uncaught (in promise) Error: Failed to compile fragment shader.
    at createFragmentShader (webgl_util.ts:103)
    at GPGPUContext.createProgram (gpgpu_context.ts:280)
    at compileProgram (gpgpu_math.ts:93)
    at backend_webgl.ts:858
    at MathBackendWebGL.getAndSaveBinary (backend_webgl.ts:902)
    at MathBackendWebGL.runWebGLProgram (backend_webgl.ts:857)
    at Object.cropAndResize3 [as kernelFunc] (CropAndResize.ts:35)
    at kernelFunc3 (engine.ts:590)
    at engine.ts:660
    at Engine.scopedRun (engine.ts:453)
```

With WebGL code dump highlighting error in
```
204 setOutput(float(undefined));
```

IMO, this is is blocking bug - once fixed, TFJS packages should be republished!
(and I'm not sure how this passed any level of testing?)

Btw, same code confirmed working after downgrade to tfjs 2.7.0.

**Comment by vladmandic** [comment]
cc @annxingyuan @lina128 for visibility - sorry for spam, but this is bad

**Comment by lina128** [comment]
cc @tafsiri

**Comment by annxingyuan** [comment]
Hi @vladmandic - thanks for reporting this issue - just wanted to let you know that you can avoid the fragment shader compile error by passing both `method` and `extrapolationValue` into `cropAndResize`, e.g.: `tf.image.cropAndResize(image, boxes, boxInd, [5,5], 'bilinear', 0 /* extrapolation value */) // note the last argument`

**Comment by vladmandic** [comment]
@annxingyuan thanks for that - but I have `cropAndResize` all over my code, I'll just wait until this is fixed and tfjs is republished - in the meantime i'm sticking with tfjs 2.7.0.

**Comment by lina128** [comment]
Hi @vladmandic, we are going to release the fix in 2.8.1 very soon.

**Comment by mgol** [comment]
Since `2.8.0` is tagged as `latest`, the whole package looks deprecated now, see:
https://www.npmjs.com/package/@tensorflow/tfjs
I'd recommend to tag `2.7.0` as `latest` until you have a fixed version to remove the warning from the package npm page:
```
npm dist-tag add @tensorflow/tfjs@2.7.0 latest
```

**Comment by mattsoulanille** [comment]
Thanks for the tip @mgol! We've tagged 2.7.0 as the latest npm version for all packages that were in the 2.8.0 release.

**Comment by lina128** [comment]
2.8.1 is released. It should fix the bug.

**Comment by vladmandic** [comment]
another issue in #4429
