### ISSUE TITLE
NPM says "This package has been deprecated" 

### ISSUE THREAD

**Issue by a-y-u-s-h** [tensorflow/tfjs#4421]
As of right now (Thursday, 17 December 2020), npm package search says `@tensorflow/tfjs` has been deprecated. Release notes say that Tensorflow 2 is up on npm. Version `2.8.0` is also written under deprectaed so I'm confused whether I've downloaded the correct one. 

![screenshot_20201217_092430](https://user-images.githubusercontent.com/19586719/102442296-1d675180-404a-11eb-9ba9-abff6330760f.png)

**Comment by vladmandic** [comment]
version 2.8.0 has a regression and that's why devs marked it as deprecated.  
either use 2.7.0 or wait until 2.8.1 comes out.

**Comment by rthadur** [comment]
Yes 2.8.0 has been depreciated .

**Comment by rthadur** [comment]
2.8.1 is released please try latest.
