### ISSUE TITLE
[TypeError: img.toFloat is not a function] When passing an image from decodeJpeg (tfjs-react-native) into model.classify (tfjs-auto-ml)

### ISSUE THREAD

**Issue by zholmes1** [tensorflow/tfjs#4424]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All mobile devices
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.7.0
- tfjs-react-native 0.5.0
- tfjs-automl: 1.0.0

**Describe the current behavior**
I can get the image from the react native file system (using expo-file-system), convert it from base64 to array buffer, decode it (with tfjs-react-native), but once I pass it to my `ImageClassificationModel` from tfjs-automl, it gives me the error. It seems like the object returned from decodeJpeg (tfjs-rn) doesn't have a method `toFloat` that `ImageClassificationModel.classify` expects it to have for preprocessing.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```
  const base64 = await ExpoFileSystem.readAsStringAsync(imageUri, {
    encoding: 'base64'
  })

  const raw = Uint8Array.from(toByteArray(base64)) // toByteArray is from npm package 'base64-js'

  const imageTensor = decodeJpeg(raw) // decodeJpeg is from tfjs-rn
  const predictions = await model.classify(imageTensor) // ImageClassificationModel from tfjs-automl
```

Here's how I create my `ImageClassificationModel`, if it's relevant. I'm using expo to grab the asset txt as a string, then I pass it along with my asset ids for my model.json and my model_weights.bin. I'm using metro bundler properly to make sure that the extensions .txt. and .bin are bundled.
```
async function loadModel(dictId: number, modelJsonId: any, weightsId: number) {
  const [dictAsset] = await Asset.loadAsync(dictId)
  const dictRaw = await ExpoFileSystem.readAsStringAsync(dictAsset.localUri)
  const dict = dictRaw.trim().split('\n')
  const model = await loadGraphModel(bundleResourceIO(modelJsonId, weightsId))
  return new ImageClassificationModel(model, dict)
}
```

Here's what I get when I log the `imageTensor` object. This is supposed to be of type `Tensor`.
`{"dataId": {}, "dtype": "int32", "id": 324, "isDisposedInternal": false, "kept": false, "rankType": "3", "shape": [224, 126, 3], "size": 84672, "strides": [378, 3]}`

I can definitely see why this is crashing. `ImageClassificationModel` from automl wants to call `toFloat()` on this `Tensor` as part of preprocessing before classification.

**Comment by tafsiri** [comment]
Hi. Just to confirm something, do you get the same error if you manually call .toFloat() on the tensor after this line

```
const imageTensor = decodeJpeg(raw) // decodeJpeg is from tfjs-rn
// add 
const asFloat = imageTensor.toFloat();
```

**Comment by zholmes1** [comment]
Same error.

**Comment by tafsiri** [comment]
Thanks I'm going to try and reproduce this (if you have a link to a github repo that reproduces the error that would be helpful), a potential temporary workaround to try. Could you add:

`import '@tensorflow/tfjs-core/dist/public/chained_ops/to_float';`

To the imports list for that file and give it a try?

**Comment by zholmes1** [comment]
@tafsiri 

You're the man! It was a little deeper than just `to_float`, but I was able to follow the trail and get everything imported.

```
import '@tensorflow/tfjs-core/dist/public/chained_ops/to_float'
import '@tensorflow/tfjs-core/dist/public/chained_ops/expand_dims'
import '@tensorflow/tfjs-core/dist/public/chained_ops/div'
import '@tensorflow/tfjs-core/dist/public/chained_ops/sub'
import '@tensorflow/tfjs-core/dist/public/chained_ops/squeeze'
import '@tensorflow/tfjs-core/dist/public/chained_ops/reshape'
import '@tensorflow/tfjs-core/dist/public/chained_ops/as2d'
```

I know the way that I'm doing things may be a bit abnormal, so many I'm skipping some step where all those files would be imported.

My general flow is:

1. Load models (json/weights/dict) from RN bundle
2. Create graph models with loadGraphModel
3. Pass the graphModel and my parsed dictionary.txt over to `new ImageClassificationModel`

**Comment by tafsiri** [comment]
Oh actually your response gives me an idea, can you post all your other tfjs related imports? Do you have an `import * as tfjs from '@tensorflow/tfjs'` or `import '@tensorflow/tfjs'`, `import '@tensorflow/tfjs-core'` in there somewhere?

**Comment by tafsiri** [comment]
I haven't been able to reproduce this so if you have a minimal repro in a github repo i wouldn't mind taking a look. You shouldn't _need_ to import those files manually (assuming you have one of the imports in my prev message above), unless something funky is going on with the build/bundling/js optimization step.

Glad the workaround unblocks you, you can shorten the imports by replacing those individual op imports with.

`import '@tensorflow/tfjs-core/dist/public/chained_ops/register_all_chained_ops'`

**Comment by zholmes1** [comment]
Thanks for the help. I just got off a flight. I'll mess around with it a
bit tomorrow and I'll see if I can isolate exactly why it's happening. It's
possible that I had a * import that got replaced with a named import.

**Comment by zholmes1** [comment]
Switching from `import { loadGraphModel } from '@tensorflow/tfjs'` to `import * as tf from '@tensorflow/tfjs'`/`tf.loadGraphModel` allowed me to remove the all chained ops script.
