### ISSUE TITLE
How can I use wasm backend in react native?

### ISSUE THREAD

**Issue by devops35** [tensorflow/tfjs#4431]
cpu backend is very slow. On the other hand, rn-webgl is both very slow and I get the error "Requested texture size [5069x5069] greater than WebGL maximum on this browser / GPU [4096x4096]". So I want to try wasm backend.
I'm importing "@tensorflow / tfjs-backend-wasm" and running "await tf.setBackend('wasm')". But I get the error "Initialization of backend wasm failed". How can I use wasm backend in react native?

**Comment by rthadur** [comment]
@devops35 can you please provide your device specifictions ?
Note:  tfjs-wasm is build on top of [XNNPACK library](https://github.com/google/XNNPACK) , please check [here](https://github.com/google/XNNPACK#supported-architectures) for more info

**Comment by devops35** [comment]
I want to run it with react native 0.63. Style transfer works very slowly in React native. on the iPhone 6 phone, RAM is not enough. It works in the simulator, but it also takes about 20-30 minutes.

**Comment by tafsiri** [comment]
Hi. I don't think react native supports WASM so you won't be able to use that backend there unfortunately.
