### ISSUE TITLE
QuantizationAware Training Conversion

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#4432]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**Describe the feature and the current behavior/state.**

Tensorflow has added 
https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization/keras/quantize_model which has added QuantizeWrapper to nodes.  Converters like tflite support this but tfjs has trouble converting these nodes. 
- Are you willing to contribute it (Yes/No): Yes but will need significant guidance. 

**Will this change the current api? How?** No
 
**Who will benefit with this feature?**
Anyone who wants to deploy stuff in production. Quantization is super important in reducing memory footprint by 4x and improving inference speed. These are really important gains. However, without quantization aware training there is significant drop in  performance. TF-Lite converter is able to handle this.  We just the tfjs converter to convert 
these quantized models

**Any Other info.**

**Comment by rthadur** [comment]
cc @pyu10055 @tafsiri

**Comment by rthadur** [comment]
Please use https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite to run the tflit models without converting. Thank you
