### ISSUE TITLE
[wasm] Add Round kernel. Unblocks efficientdet models.

### ISSUE THREAD

**Issue by rafallukasik123** [tensorflow/tfjs#4434]
**System information**
- TensorFlow.js version (you are using): 2.7.0

**Describe the feature and the current behavior/state.**
There are plans to add an implementation for efficientdet models in the wasm backend ? 
It is related to the issue https://github.com/tensorflow/tfjs/issues/4408.
When i use webgl backend i  have a problem with precision (my device doesn't support float32) 
I took the advice from this issue. I tried to use the wasm backend but i have exception 
"Error: 'round' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen"

**Comment by rthadur** [comment]
cc @annxingyuan

**Comment by annxingyuan** [comment]
XNNPACK implementation: https://github.com/google/XNNPACK/tree/master/src/f32-vrnd
