### ISSUE TITLE
sort and argsort

### ISSUE THREAD

**Issue by naah69** [tensorflow/tfjs#4438]
**System information**
- TensorFlow.js version (you are using): 2.8.1 
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

`tf.sort` and `tf.argsort`

**Will this change the current api? How?**

add two interface to api

**Who will benefit with this feature?**

developers

**Any Other info.**

**Comment by rthadur** [comment]
cc @pyu10055 @tafsiri

**Comment by rthadur** [comment]
@naah69 can you please explain your use case ?

**Comment by naah69** [comment]
matrix index sort,but now i make it be vector index sort，if it has argsort,i can make it be matrix index sort
![image](https://user-images.githubusercontent.com/25682169/106223626-c6de5d00-621c-11eb-8f17-20fd2508583f.png)

**Comment by mahnehsilla** [comment]
Wouldn't this be useful, in the same way than it is in tensorflow.py and pytorch ? I am also trying to sort a tensor, cant do it

**Comment by asilvas** [comment]
Possible to reopen?
