### ISSUE TITLE
Memory leak with Model predict?

### ISSUE THREAD

**Issue by sampsongao** [tensorflow/tfjs#4457]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.40, 2.70
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
```
// also tried requiring @tensorflow/tfjs-node
const tf = require('@tensorflow/tfjs-node-gpu');

const model = tf.sequential();
model.add(tf.layers.flatten({
  inputShape: [9, 9, 3]
}));
for (let i = 0; i < 40; i ++) {
  model.add(tf.layers.dense({
    units: 128, activation: 'relu'
  }));
}
model.add(tf.layers.dense({
  units: 10, activation: 'relu'
}));

const inputs = tf.randomNormal([20, 9, 9, 3]);
let i = 20000;
while (i --) {
  tf.tidy(() => {
    const outputs = model.predict(inputs);
    return outputs.arraySync();
  });
}
```
Running the above script in node 10.23.0 results in growing memory consumption of around 800 MB to 1GB. Does this indicate memory leaks or a bug in my program?

**Describe the expected behavior**
I guess this code snippet is not saving any of the output variables and the model predict is wrapped with tf.tidy. So I would expect it to take constant memory consumption over the loop.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
See above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
I tried your example with node cpu, I did not see memory spike (both tf.memory() and system monitor), how have you measured the memory?
