### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by PawelWesolowski** [tensorflow/tfjs#4458]
In the Extra Credit section... Given the info from the codelab I am not able to "bend" the test prediction graph as it is on the codelab's example picture. I have tried different combinations of adding more units and layers e.g.:
```javascript
function createModel() {
    // Create a sequential model
    const model = tf.sequential();

    // Add a single input layer
    model.add(tf.layers.dense({ inputShape: [1], units: 1000, useBias: true }));
    model.add(tf.layers.dense({ units: 50, activation: 'sigmoid' }));
    model.add(tf.layers.dense({ units: 50, activation: 'sigmoid' }));
    model.add(tf.layers.dense({ units: 50, activation: 'sigmoid' }));
    model.add(tf.layers.dense({ units: 50, activation: 'sigmoid' }));

    // Add an output layer
    model.add(tf.layers.dense({ units: 1, useBias: true }));

    return model;
}
```
but all I got was:
![flat](https://user-images.githubusercontent.com/17248853/103318010-4e258e80-4a2d-11eb-8334-d15ca7d1c6a9.png)

Could you please explain how to achieve this? AFAIK adding more layers should do the job but I obviously am missing sth...

**Comment by tafsiri** [comment]
Increase the number of epochs you are training for. For example set it to 150 epochs and see what happens. However you results look like a horizontal line so I don't know if there is another bug in your code. Here is a link to a version with a solution that produces a more curved result. https://glitch.com/edit/#!/tfjs-training-one?path=script.js%3A89%3A17

**Comment by PawelWesolowski** [comment]
Thanks. Works now. The only difference was the number of epochs - it MUST be over 100.
Fyi. your glitch example uses only 50 epochs and if you retry it couple of times, you may see a result similar to mine. This is from your glitch:
<img width="516" alt="Screenshot 2021-01-08 at 21 52 36" src="https://user-images.githubusercontent.com/17248853/104066611-f98acc00-5201-11eb-986c-fc2a60102f4c.png">
Cheers!
