### ISSUE TITLE
 How to train my own postnet model?

### ISSUE THREAD

**Issue by lijing271** [tensorflow/tfjs#446]
https://github.com/tensorflow/tfjs-models/tree/master/posenet

How to train my own postnet model?

**Comment by caisq** [comment]
@oveddan Any thoughts?

**Comment by tafsiri** [comment]
@lijing271 take a look at https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5, it has some links to a couple of papers describing PoseNet and its setup. I believe the model in that repository was converted from one that those researchers had trained.

**Comment by lijing271** [comment]
@tafsiri ohh，thanks very much.

**Comment by lijing271** [comment]
@tafsiri hi, where can i find the pbtxt file(caffe's prototxt ) for the model?

**Comment by tonyguo1987** [comment]
@lijing271 Have you found out how to train the model?

**Comment by lijing271** [comment]
@tonyguo1987 
Not yet, but I found that the single pose model is the same as openpose

**Comment by oveddan** [comment]
So the current models that PoseNet uses are all multi-pose models.  Both single pose and multi-pose estimation use the same models, they just have different algorithms to decode the outputs.  

It's not the same as the OpenPose model.

All of the models that were released with PoseNet were trained based on research in the paper:

[PersonLab: Person Pose Estimation and Instance Segmentation with a Bottom-Up, Part-Based, Geometric Embedding Model](https://arxiv.org/abs/1803.08225)

In particular, section 3.1 explains how pose estimation is trained.
