### ISSUE TITLE
Node js - Warning: Missing input files + empty napi-v7

### ISSUE THREAD

**Issue by borodadada** [tensorflow/tfjs#4467]
Node js.
Hello. After latest update, i have warning

IMAGES:
npm install
https://ibb.co/zQwrkpw
empty file result
https://ibb.co/gZhQTCJ

**Comment by rthadur** [comment]
Here is a similar issue https://github.com/tensorflow/tfjs/issues/1121 which was raised earlier , looks like a bug.
cc @pyu10055

**Comment by pyu10055** [comment]
I cannot reproduce this with tfjs-node 2.8.3 on a windows 10 machine that runs 15.2.1 node.
@borodadada what is the tfjs-node version you using?

**Comment by borodadada** [comment]
after last update all work fine!

**Comment by borodadada** [comment]
now all work fine. tested. thanks

**Comment by rthadur** [comment]
Thank you  for confirming , closing this issue.
