### ISSUE TITLE
Scores of Listen and Recognize are different in speech-commands

### ISSUE THREAD

**Issue by adotnusiyan** [tensorflow/tfjs#4474]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.8.2
- Browser version: Google Chrome. Version 87.0.4280.88 (Official Build) (x86_64)

**Describe the current behavior**
I have a `recognizer` and used its `listen` function to get the Float32Array array from [SpeechCommandRecognizerResult.spectrogram.data](https://github.com/tensorflow/tfjs-models/blob/master/speech-commands/src/types.ts#L367), then concatenated the array using [concatenateFloat32Arrays](https://github.com/tensorflow/tfjs-models/blob/2d269c257bf59a3c878d823d3e3973d7954500bc/speech-commands/src/generic_utils.ts#L45) util function

When using `listen` function the scores were fine as expected, but when I use `recognize` function and provide the concatenated Float32Array as an input, the scores are different and not as expected

**Describe the expected behavior**
Expected to have the same or at least similar scores when using `recognize` function with input parameter that I got from `listen` function

**Standalone code to reproduce the issue**

[Example in Codesandbox](https://codesandbox.io/s/tfjs-listen-recognize-scores-iyrjd)

**Other info / logs** Include any logs or source code that would be helpful to

When I use the Float32Array that I got from `listen` function and use it as a parameter [input](https://github.com/tensorflow/tfjs-models/blob/master/speech-commands/src/types.ts#L85) in `recognize` function, the score is different and the score of the second label is almost always zero

**Comment by adotnusiyan** [comment]
@tafsiri 
Will [this update](https://github.com/tensorflow/tfjs/issues/4554) fix the issue?

**Comment by pyu10055** [comment]
@adotnusiyan 
I think you need to normalize the spectrogram before passing to the recognizer:
take a look at [this line](https://github.com/tensorflow/tfjs-models/blob/2d269c257bf59a3c878d823d3e3973d7954500bc/speech-commands/src/browser_fft_recognizer.ts#L787) 
```

```

**Comment by adotnusiyan** [comment]
@pyu10055  
It works. After using the normalization method, the scores are still not the same, but they're similar now.

Thank you so much

**Comment by pyu10055** [comment]
@adotnusiyan btw, the normalization method is exposed in the latest speech-commands v0.5.1
