### ISSUE TITLE
Fit gets slower and slower after each call

### ISSUE THREAD

**Issue by MicheleLambertucci** [tensorflow/tfjs#448]
I'm not sure if this is intended (like sgd gets computationally heavier over time or something), but since I wasn't able to find any information about this behaviour I decided to post it here.

#### TensorFlow.js version
"@tensorflow/tfjs@0.11.6":
version: "0.11.6"

#### Browser version
Version 67.0.3396.87 (official build) (64 bit)

#### Problem
Each time model.fit is called, the computational time required for it to end increases.

#### Code to reproduce the bug
Code to reproduce:
```
async function execute(){
	const model = tf.sequential();
	model.add(tf.layers.dense({
		units: 1,
		inputShape: [1]
	}));
	model.compile({
		loss: 'meanSquaredError',
		optimizer: 'sgd'
	});
	const xs = tf.tensor2d([1, 2, 3, 4], [4, 1]);
	const ys = tf.tensor2d([1, 3, 5, 7], [4, 1]);

	for(let i = 0; i < 10000; i++){
                var t0 = performance.now();
		const h = await model.fit(xs, ys);
		var t1 = performance.now();
                console.log(t1-t0);
	}	
}
execute();
```

I also repeated this test with a slightly difference: I collected each deltaTime and pushed it in an array. Then I plotted the gathered values:
![chrome_2018-06-19_15-57-27](https://user-images.githubusercontent.com/15233143/41601757-82a3b772-73d9-11e8-98fb-094fa0ccf1ea.png)

I don't really know if it's related, but I have an AMD RX480 as GPU.

**Comment by caisq** [comment]
cc @nsthorat This is similar to the slowing down in RNNs in 0.11.5 that we have seen. Interestingly, this example doesn't involve any RNN (it's just a dense layer). May be worth looking at whether https://github.com/tensorflow/tfjs-core/pull/1080 is related here. 

@MicheleLambertucci Can you try this on tfjs version 0.11.4 and see if the same thing happens?

**Comment by MicheleLambertucci** [comment]
@caisq Tried with 0.11.4.
The function duration seems to be **constant over time** in 0.11.4:
![image](https://user-images.githubusercontent.com/15233143/41606057-1bc703ce-73e3-11e8-9908-c61068d5738e.png)

**Comment by nsthorat** [comment]
I'll take a look.
