### ISSUE TITLE
Error running LinSpace

### ISSUE THREAD

**Issue by epicure** [tensorflow/tfjs#4480]
When I run **[tf.linspace](https://js.tensorflow.org/api/2.8.2/#linspace)** in the 2.8.2  API documentation.
I got this "An error occured on line: 1 Error running LinSpace: Neither modular kernel nor forward func passed".

![image](https://user-images.githubusercontent.com/422362/103514521-23658b00-4eb0-11eb-9284-8197ab47d166.png)

The 2.7.0 vsersion of tf.linspace works but 2.8.0, 2.8.1, 2.8.2  are not working for now.

**System information**

- TensorFlow.js version: 2.8.0, 2.8.1, 2.8.2

- OS Platform and Distribution (MacOS 10.15, Windows 10):

**Comment by tafsiri** [comment]
Re-opening as this will need a new release to publish the fix.

For context this will only happen if linspace is the first op called. As a workaround you call 
`tf.ready()` or `await tf.ready()` before calling any ops.

**Comment by rafallukasik123** [comment]
@tafsiri  your workground doesn't work for me. 
When i call tf.ready() before calling any ops i have error in one of kernel func. 
More specifically in fromPixels.js and the error content is "backend.makeTensorInfo is not a function"

**Comment by tafsiri** [comment]
@rafallukasik123 could you post a reprodcution (maybe in codepen form) so that we can take a look.

**Comment by rafallukasik123** [comment]
Unfortunately I can't share all the code. Here is a small snipe of code https://codepen.io/rafallukasik123/pen/LYRBpVj 
When i remove tf.ready() from the beginning i have error similar to you "Error running Round: Neither modular kernel nor forward func passed".
If my code contain tf.ready() i have mentioned error "backend.makeTensorInfo is not a function" in @tensorflow/tfjs-backend-webgl/dist/kernels/FromPixels.js

**Comment by rafallukasik123** [comment]
in the latest version 2.8.3 I have error `Error running Reciprocal: Neither modular kernel nor forward func passed`. 
should I create a new issue?

**Comment by tafsiri** [comment]
@rafallukasik123 Yes I think a new issue would be best. In terms of reproduction, you don't have to post your whole code, ideally it would be the smallest snippet of code that shows the error. It can even just load the library and directly call tf.reciprocal or tf.browser.fromPixels. In the codepen you posted I get a syntax error so the code doesn't run.

**Comment by tafsiri** [comment]
Fixed in 2.8.3 https://js.tensorflow.org/api/2.8.3/#linspace

**Comment by jxmorris12** [comment]
In the latest version (3.5.0) I've seen:

```
Error: Kernel 'LinSpace' not registered for backend 'wasm'
```

Is this a related issue?
