### ISSUE TITLE
Use tfjs 2.8.2 executeAsync show 'length' undefined error

### ISSUE THREAD

**Issue by zhuyingyan** [tensorflow/tfjs#4481]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): 2.8.2
- Browser version: Google Chrome. Version 87.0.4280.88

**Describe the current behavior**
I use a train model by myself. When I use Tensorflow.js 2.7.0, it was ok. But, when I use the latest Version Tensorflow.js 2.8.2(script link: https://cdn.jsdelivr.net/npm/@tensorflow/tfjs), use code **model.executeAsync**, it show an error:
 **Uncaught (in promise) TypeError: Cannot read property 'length' of undefined**

**Describe the expected behavior**
I just want to use as Tensorflow.js 2.7.0 as well

**Standalone code to reproduce the issue**
Here is the code:
```
const MODEL_URL = "./niu_web_model/model.json";
const model = await tf.loadGraphModel(MODEL_URL);
const cat = document.getElementById("cat");
model
   .executeAsync(tf.browser.fromPixels(cat).expandDims(0))   // error when execute to here
   .then((modelres) => {                       
      console.log(modelres[6].dataSync(),modelres[7].dataSync())
    });
```
error show:
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at Vz (tfjs:17)
    at Object.kernelFunc (tfjs:17)
    at p (tfjs:17)
    at tfjs:17
    at e.t.scopedRun (tfjs:17)
    at e.t.runKernelFunc (tfjs:17)
    at e.t.runKernel (tfjs:17)
    at topk_ (tfjs:17)
    at topk__op (tfjs:17)
    at tfjs:17
```
It 's ok when use in Tensorflow.js 2.7.0.

**Comment by MiksVasiljevs** [comment]
I got a similar error, but when running tf.topk() on my prediction results instead.

What seemed to fix it was running .print() on the inference output tensor.

This works:
```
const prediction = model.predict(x);
prediction.print();
const topPreds = tf.topk(prediction, 3, true);`
```

But this throws an error
```
const prediction = model.predict(x);
const topPreds = tf.topk(prediction, 3, true);

Unhandled Promise rejection: Cannot read property 'length' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'length' of undefined
    at topKImpl (TopK_impl.js:22)
    at Object.topK [as kernelFunc] (TopK.js:24)
    at kernelFunc (engine.js:440)
    at engine.js:504
    at Engine.scopedRun (engine.js:333)
    at Engine.runKernelFunc (engine.js:502)
    at Engine.runKernel (engine.js:391)
    at topk_ (topk.js:57)
    at Module.topk__op (operation.js:44)
```

No clue why the error is being thrown without the print though.

**Comment by pyu10055** [comment]
@zhuyingyan @MiksVasiljevs can either of you provide a codepen example for this failure?

**Comment by MiksVasiljevs** [comment]
> @zhuyingyan @MiksVasiljevs can either of you provide a codepen example for this failure?

See here:
https://codepen.io/miksvasiljevs/pen/VwKxpGK

Let me know if there are any issues with the pen or anything.
