### ISSUE TITLE
tfjs-react-native: Any way to make models load faster? (outside of Metro)

### ISSUE THREAD

**Issue by zholmes1** [tensorflow/tfjs#4483]
I load three graph models when my app boots. On my new Galaxy S20+, this takes ~3 seconds with Metro (served over HTTP right?) and ~9 seconds with a release bundle (loaded with react-native-fs I believe). These numbers are fine (although I'd be interested to know why it takes 3x as long when the file is already on-device _edit: I realize now this is because over HTTP we use fetch as binary, whereas with fs we cycle between bytes/base64 multiple times_ ), but now that my app is getting ready for release, I'm seeing load times of 30 seconds or more on some older devices. This is really pushing the limit of what I'm comfortable with.

Is there any recourse here? Each of my models is a tfjs model with 6 or 7 weights shards, 4mb each. ~75mb total on file.

**Comment by zholmes1** [comment]
I think I know what's going on here.

I found this in react-native-fs:
```
      InputStream inputStream = getInputStream(filepath);
      byte[] inputData = getInputStreamBytes(inputStream);
      String base64Content = Base64.encodeToString(inputData, Base64.NO_WRAP);

      promise.resolve(base64Content);
```

And this in BundleResourceHandler:
```
base64Weights = await RNFS.readFileRes(fileName)
...
const weightData = util.encodeString(base64Weights, 'base64').buffer
```

So the flow is:

RNFS reads bytes > RNFS converts to base64 > TFJS receives base64 > TFJS converts to bytes

**Comment by zholmes1** [comment]
@tafsiri 

Check this out! I think I'm on to something here. I know this code is pretty raw (mixing Expo FS and RNFS...) but it actually works! And I can use this exact same code to load buffers in Metro or in release.

I was able to reduce my shards load time from 9-12 seconds to 3-3.5 seconds!

Flow:

1. Get asset uris from expo-asset
2. Copy files from cache into document directory
3. use react-native-static-server to serve doc directory over HTTP
4. use axios to grab the .bin files from the server

I also think it's definitely possible to skip the cache>docDir copies, but it's late and I will try tomorrow...

```
async function loadAllShards() {
  const t1 = Date.now()
  const [family, genus, species] = await Asset.loadAsync([
    require('../../assets/family_shards.bin'),
    require('../../assets/genus_shards.bin'),
    require('../../assets/species_shards.bin')
  ])
  console.log('loaded assets in', Date.now() - t1, 'ms')

  if (!family.localUri || !genus.localUri || !species.localUri) {
    throw new Error('shards file is missing a localUri')
  }

  await FileSystem.copyAsync({
    from: family.localUri,
    to: FileSystem.documentDirectory + 'family_shards.bin'
  })
  await FileSystem.copyAsync({
    from: genus.localUri,
    to: FileSystem.documentDirectory + 'genus_shards.bin'
  })
  await FileSystem.copyAsync({
    from: species.localUri,
    to: FileSystem.documentDirectory + 'species_shards.bin'
  })

  console.log('starting server', RNFS.DocumentDirectoryPath, Date.now() - t1)

  const server = new StaticServer(0, RNFS.DocumentDirectoryPath)
  const baseURL = await server.start()

  console.log('serving at', baseURL, Date.now() - t1)

  const axios = Axios.create({
    baseURL
  })

  const buffers = await Promise.all(
    ['family_shards.bin', 'genus_shards.bin', 'species_shards.bin'].map(
      async file => {
        const response = await axios.get<ArrayBuffer>(file, {
          responseType: 'arraybuffer'
        })
        return response.data
      }
    )
  )

  console.log('got all buffers in', Date.now() - t1, 'ms')
}
```

**Comment by Caundy** [comment]
Ran into the same issue when loading a single model with four weight shards, totalling to ~13MB. The tf.loadGraphModel method resolves reasonably quickly on iOS (iPhone7: 3s when developing locally, 9s when installed from testflight) but the load times on Android devices running built release apk are **much slower** leaving the app UI completely unresponsive in the meantime 😕 
loadGraphModel taking: 24s on Redmi 7, 60s on nexus 5x, 78s on samsung a10 😖 

@zholmes1  Could you elaborate on how you ended up using the _buffers_ array? I don’t see them used in any wayin the posted code and wanted to attempt try your version of the code. Running it I’m also running into an issue where axios returns undefined for response.data if "arraybuffer" responseType is specified.
