### ISSUE TITLE
Update tfjs-models/body-pix dependencies to @tensorflow/tfjs 2.x

### ISSUE THREAD

**Issue by adriangodong** [tensorflow/tfjs#4484]
**System information**
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 1.5.2
- Tensorflow.js Converter Version: 1.5.2

**Describe the current behavior**

The latest release of @tensorflow-models/body-pix depends on @tensorflow/tfjs-core 1.x, ref: https://github.com/tensorflow/tfjs-models/blob/c08dae1739f8cc42502c1770ce4f314052ece2e8/body-pix/package.json#L17

@tensorflow/tfjs-core before 2.5.0 depends on a vulnerable version of node-fetch. This vulnerability was fixed via https://github.com/tensorflow/tfjs/issues/3931.

**Describe the expected behavior**

There should be a version of @tensorflow-models/body-pix that does not depend on vulnerable node-fetch version.

**Standalone code to reproduce the issue**

Run:
```
npm install @tensorflow-models/body-pix
npm audit
```

There should be no vulnerability listed.

**Comment by rthadur** [comment]
@tafsiri can we update tfjs-core version to latest ?

**Comment by tafsiri** [comment]
Yeah no reason why we shouldn't be able to. I think we have PRs for blazeface and face-landmarks-detection.

**Comment by rthadur** [comment]
@tafsiri submitted a PR , please review

**Comment by rthadur** [comment]
Package.json is updated with latest version , this should be fixed now.Thank you
