### ISSUE TITLE
Error loading TF 2.3 model in tfjs-node

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/tfjs#4493]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux & Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow.js installed from (npm or script link): 2.8.2
- TensorFlow.js version (use command below): 2.8.2
- Browser version: NA
- Tensorflow.js Converter Version: NA

**Describe the current behavior**
tfjs-node throws the below error when loading a TF >= 2.3 estimator saved model

```
Error: Failed to load SavedModel: Input 2 of node dnn/input_from_feature_columns/input_layer/feature1_embedding_1/feature1_embedding_weights/embedding_lookup_sparse was passed int64 from dnn/input_from_feature_columns/input_layer/feature1_embedding_1/feature1_embedding_weights/embedding_lookup_sparse/strided_slice:0 incompatible with expected int32.
    at NodeJSKernelBackend.loadSavedModelMetaGraph (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:401:29)
    at Object.<anonymous> (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:446:45)
    at step (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
```

**Describe the expected behavior**
Should ideally load the model like it does today with TF <= 2.2

**Standalone code to reproduce the issue**
- Click the `Run` button in https://repl.it/@NitinPasumarthy/estimator-in-tfjs-node#index.js which loads the TF Python model in tfjs-node 2.8.2
- https://colab.research.google.com/drive/1XhBsoTUCsGLVTb3z8gAIb_xbN9qvYCce?usp=sharing has the necessary code to generate the TF saved model for different versions of TF

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
@pyu10055 is already looking into the issue. Created this only for tracking purposes.

**Comment by pyu10055** [comment]
@Nithanaroy This issue seems to have been fixed with our latest upgarade of TFJS-node to TF 2.4.
Please verify, thanks!

**Comment by Nithanaroy** [comment]
I was able to test it on the toy model in https://repl.it/@NitinPasumarthy/estimator-in-tfjs-node#index.js with v3.5. It works perfectly. Thank you Ping :)

**Comment by yearsss** [comment]
i use tensorflow estimator 2.5 export model, and i ecounter the same problem when i use tfserving 1.15.0 load the model
