### ISSUE TITLE
No Backend registry

### ISSUE THREAD

**Issue by SkellyM386** [tensorflow/tfjs#4497]
it says no backend registry heres the code, the error log and i even put the package.json in as well

<h3>What I was doing</h3>
I was trying to use the qna model but i keep getting the same error message and i've got no clue what im doing wrong.

<br /> I also am using the wikipedia article found here https://en.wikipedia.org/wiki/Google about google <br />and then in the second argument I have a question about the article.<br>there are only 2 inputs on it.

<hr />

![image](https://user-images.githubusercontent.com/74203498/103705893-b1994a00-4f60-11eb-9700-e9854fea7157.png)

![image](https://user-images.githubusercontent.com/74203498/103706022-f1f8c800-4f60-11eb-9966-96c4c6f923cd.png)

**Comment by tafsiri** [comment]
If you are using qna model with tfjs 2.x you need to import a backend at the top of your program. In your case I would add the following to the top of the program `import '@tensorflow/tfjs-node';`

**Comment by SkellyM386** [comment]
> If you are using qna model with tfjs 2.x you need to import a backend at the top of your program. In your case I would add the following to the top of the program `import '@tensorflow/tfjs-node';`

Thank you!
