### ISSUE TITLE
Unhandled Rejecting Error ~ Implicit Shape Can't Be a Fractional Number 

### ISSUE THREAD

**Issue by riccrdo5** [tensorflow/tfjs#4498]
Hello everyone, sos

I am following an online tutorial on how to run gesture recognition using react and tensor flow. However, I am always seeing this error whenever I play around with the webcam in chrome.

Here is my github for what I am working on btw. And here is the tutorial video I'm watching. I got stuck right around minute 10

https://github.com/riccrdo5/help

https://youtu.be/f7uBsb-0sGQ

Ty and happy holidays

![image](https://user-images.githubusercontent.com/67179440/103816496-eae1c080-5019-11eb-8e4e-f05b5622c2cd.png)
![image](https://user-images.githubusercontent.com/67179440/103816511-f03f0b00-5019-11eb-96f3-d690d5164eba.png)

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.
