### ISSUE TITLE
Implement step op in WASM backend (needed for training ReLU networks)

### ISSUE THREAD

**Issue by janhuenermann** [tensorflow/tfjs#4500]
**System information**
- TensorFlow.js version (you are using): 2.8.2
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.** 

Hi,

I am currently using `tfjs-backend-wasm` to implement some RL algorithms. For that I am trying to train a perceptron with ReLU activations in a web worker. Unfortunately not all ops required for this are implemented. I understand that your priorities are on inference.

However, it seems that the only thing missing to make ReLU training work, is the gradient function of the ReLU activation (training works fine with sigmoid whose gradient only needs sub/mul ops). More specifically, the gradient fails due to the absence of the `step` op.

Are you guys planning on implementing the `step` op in the WebAssembly backend soon? 

**Will this change the current api? How?**
No. New op.

**Who will benefit with this feature?**
Anyone who trains using ReLU activation and WebAssembly backend.

**Any Other info.**
If you are not planning on implementing this, I would love to help! Let me know.

**Comment by rthadur** [comment]
cc @annxingyuan
