### ISSUE TITLE
Support Reciprocal in wasm backend

### ISSUE THREAD

**Issue by rafallukasik123** [tensorflow/tfjs#4508]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow.js installed from (npm or script link):  2.8.3
- TensorFlow.js version (use command below): 2.8.3
- Browser version:  Chrome 87
- Tensorflow.js Converter Version: 2.7

**Describe the current behavior**
When i run my efficientdet model in the WASM backend i have error `Error running Reciprocal: Neither modular kernel nor forward func passed`. Possibly related to https://github.com/tensorflow/tfjs/issues/4480

i initialize model as follows

```
const init = async () => {
  await tf.setBackend('wasm');
  await tf.ready();
  prepareEfficentDetModel();
};
init();
```

**Comment by tafsiri** [comment]
@rafallukasik123 thanks for adding the extra info about the backend you are using. The WASM backend does not yet implement Reciprocal. You could try this with the webgl backend and see if it works.

I'm going to update this bug to be a feature request for adding reciprocal to the wasm backend.

**Comment by yutou15** [comment]
Is there a plan for this feature in wasm backend? It still does not work in 3.12.0.

**Comment by yutou15** [comment]
@tafsiri hello nihao.
Is there a plan for this feature in wasm backend? It still does not work in 3.12.0.

**Comment by Didi3333** [comment]
Hi,
Still doesn't work in 3.13.0

**Comment by Didi3333** [comment]
Still doesn't work in 3.15.0

**Comment by rthadur** [comment]
We will track this request in this issue https://github.com/tensorflow/tfjs/issues/5932 , will close the issue. Thank you
