### ISSUE TITLE
My intention is to reduce the size of the model when im converting to json using quantization

### ISSUE THREAD

**Issue by Leejo-011** [tensorflow/tfjs#4509]
I need to convert my keras model to json file but to the large size of my model i need to reduce the size of my converting model so i made use of quantization using tensorflow version of 2.4.0 and tensoflowjs version of 2.8.3 i came across two issues while persuing my work.

   1. The https://stackoverflow.com/questions/63949766/how-can-i-quantize-a-keras-model-while-converting-it-to-a-tensorflowjs-layers-mo page for this conversion recommends two path but in practice it asks for three paths where the first path is not being considered.
   2.  While conversion it pops an error of AttributeError: 'NoneType' object has no attribute 'read'. I'm in need of your help to resolve these issues.
   
tensorflowjs_converter \
   --input_format keras \
   --output_format tfjs_layers_model \
   --quantize_uint16 \
   original_model/model.json
   quantized_model/

![error](https://user-images.githubusercontent.com/77158365/104043665-26d77a00-5202-11eb-96cc-2cd89b587826.png)

**Comment by pyu10055** [comment]
@Leejo-011 can you check you command, the `input_format` should be `keras` instead of `tfjs_layers_model`

**Comment by Leejo-011** [comment]
> @Leejo-011 can you check you command, the `input_format` should be `keras` instead of `tfjs_layers_model`



> @Leejo-011 can you check you command, the `input_format` should be `keras` instead of `tfjs_layers_model`

@pyu10055 Thank you🙂... But i gave it a try it doesnt achieve my requirement of reducing the size it simply converts keras to json format
