### ISSUE TITLE
[Converter] When an output node is invalid, list all the output nodes.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#451]
We should provide a way to show the output node names from the converter script as people may be porting pretrained models.

**Comment by pyu10055** [comment]
I could be wrong, but It is not easy to know the output node directly for session bundles if it also contains the training graph.

**Comment by nsthorat** [comment]
You cant list all the nodes?

**Comment by pyu10055** [comment]
It could be overwhelming if there are more than a hundred nodes, it is quite typical for TF models, since there are lots constant nodes, I guess we can eliminate the constants from the output.

**Comment by nsthorat** [comment]
I think it's still fine if there are a lot of nodes, it's better than now where folks can't find what they're looking for at all.

**Comment by nsthorat** [comment]
@pyu10055 is this fixed?

**Comment by pyu10055** [comment]
the is deprecated since converter uses saved model signatures now.
