### ISSUE TITLE
The minimum required Cuda capability is 6.0 for the binary C-API releases 1.14.0 and 1.15.0 (reopened)

### ISSUE THREAD

**Issue by MitskiP** [tensorflow/tfjs#4510]
**System information**
- OS Platform and Distribution: Arch Linux
- TensorFlow installed from: binary
- TensorFlow version: 1.15.0
- Installed using: npm (tensorflow/tfjs-node-gpu)
- GPU model and memory: GeForce 960M, compute capability: 5.0
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P0    N/A /  N/A |      0MiB /  2004MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Describe the problem**
Cuda capability requirement is set to 6.0.
Error:
```
Ignoring visible gpu device (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 6.0.
```
This reopens the issue [#36853](https://github.com/tensorflow/tensorflow/issues/36853) which is related to [#25329](https://github.com/tensorflow/tensorflow/issues/25329).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Create `package.json` containing
```{"dependencies": {"@tensorflow/tfjs-node-gpu": "^1.7.3"}}```
2. run `npm install`
3. run some javascript using node
```const tf = require('@tensorflow/tfjs-node-gpu');```

**Comment by rthadur** [comment]
cc @pyu10055 @lina128 should we rerelease the package to make it compatible ?

**Comment by rthadur** [comment]
There is already issue opened here https://github.com/tensorflow/tfjs/issues/4193 for the same request, will close this and track at one place , thank you
