### ISSUE TITLE
Incompatible with Ubuntu 20.04?

### ISSUE THREAD

**Issue by jj12345654321** [tensorflow/tfjs#4511]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow.js installed from (npm or script link): 2.8.0
- TensorFlow.js version: 2.8.0
- CUDA/cuDNN version: No cuda being used.

**Describe the problem**

After installing through NPM, on node.js 14.8.0, it receives the bindings in tfjs-node for NAPI-4. Then when tfjs is called in the program, an error message displays stating that it is looking for NAPI-6. I have tried to rebuild from addon and source with no success. It simply reinstalls the NAPI-4 bindings again. NPM version is 6.14.7.

Thanks for looking this over.

**Any other info / logs**
```

# ./nodejs/node app.js 3333
node-pre-gyp info This Node instance does not support builds for N-API version 7
node-pre-gyp info This Node instance does not support builds for N-API version 7
/service/node_modules/@tensorflow/tfjs-node/dist/index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /service/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/service/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/service/services/serving.js:52:25)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
#
```

**Comment by pyu10055** [comment]
@jj12345654321 have you tried to delete the node_modules directory and reinstall the latest (2.8.3) tfjs-node?
I have tried node 14.8.0 on a linux machine (debian) without problem.

**Comment by jj12345654321** [comment]
@pyu10055 I have attempted to delete node_modles and reinstall 2.8.3. I am getting the same error message. However, this time, when I tried to build addon from source, I got a different output instead of the usual one:

`# npm rebuild @tensorflow/tfjs build-addon-from-source
@tensorflow/tfjs@2.8.3 /service/node_modules/@tensorflow/tfjs
@tensorflow/tfjs@2.8.2 /service/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs`

**Comment by pyu10055** [comment]
@jj12345654321 what is the new message you got for compiling from source? I think it is cut off in you last message.
