### ISSUE TITLE
Efficientdet and mobilenet models don't work correctly on ipads

### ISSUE THREAD

**Issue by rafallukasik123** [tensorflow/tfjs#4517]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: ipad mini 5, ipad air 3
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below):  2.8.3
- Browser version: Chrome 87
- Tensorflow.js Converter Version: 2.8.3

**Describe the current behavior**
When i run models on iPads, they work incorrectly. This is due to device doesn't support flaot32. 
I described problem in detail in https://github.com/tensorflow/tfjs/issues/4408. 
We are currently unable to run any models on iapd well.
I tried to train a model with float16 weights but this  solution didn't help.
I also tried used wasm backend but currently wasm doesn't support efficientdet models.
It is important that everything works fine in the cpu backend. But there we have terrible times.
Is it possible to add support for ipads devices?

**Comment by pyu10055** [comment]
@rafallukasik123 what are the ops missing  on WASM for efficientnet?
I believe Mobilenet should have all ops supported on WASM.

**Comment by rafallukasik123** [comment]
As for wasm now i'm waiting to solve the issue https://github.com/tensorflow/tfjs/issues/4508.
Yes, mobilenet works well on the WASM and CPU backend.  Problem  occurs for both architectures only on webgl. I think when efficientdet successfully run on the wasm backend issue with precision will be resolved.
