### ISSUE TITLE
npm i @tensorflow/tfjs-node fails to install

### ISSUE THREAD

**Issue by 404jimnotfound** [tensorflow/tfjs#4522]
- System version: Ubuntu MATE 20.04.1 LTS 64-bit
- Installation source:  NPM (npm i @tensorflow/tfjs-node)
- TensorFlow.js version: 2.8.3-node
- CUDA/cuDNN version: none

npm i @tensorflow/tfjs-node fails to install tfjs-node. It looks like that it cannot download  CPU-linux-2.8.3.tar.gz because it no longer exists on that directory. 

Terminal log:
`> @tensorflow/tfjs-node@2.8.3 install /opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-2.8.3.tar.gz
* Downloading libtensorflow
[==============================] 2340108/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/2.8.3/CPU-linux-2.8.3.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.8.3 and node@14.15.4 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES current user ("jim") does not have permission to access the dev dir "/root/.cache/node-gyp/14.15.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node/.node-gyp"
make: *** No rule to make target '../.node-gyp/14.15.4/include/node/common.gypi', needed by 'Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-60-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node/lib/napi-v7" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=7" "--node_napi_label=napi-v7"
gyp ERR! cwd /opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node --module_name=tfjs_binding --module_path=/opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node/lib/napi-v7 --napi_version=7 --node_abi_napi=napi --napi_build_version=7 --node_napi_label=napi-v7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/lampp/htdocs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-60-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/lampp/htdocs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/lampp/htdocs/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok`

**Comment by rthadur** [comment]
@404jimnotfound can you please provide npm version ?

**Comment by iHildy** [comment]
I run into this exact same error with a different package, quick.db. I have tried installing with and without sudo.

**Comment by iHildy** [comment]
I fixed it by doing `sudo npm install quick.db --unsafe-perm`
So try `sudo npm install @tensorflow/tfjs-node --unsafe-perm`

[From this issue](https://npm.community/t/eacces-permission-denied-access-root-npm/5667/5)

**Comment by 404jimnotfound** [comment]
> I fixed it by doing `sudo npm install quick.db --unsafe-perm`
> So try `sudo npm install @tensorflow/tfjs-node --unsafe-perm`
> 
> [From this issue](https://npm.community/t/eacces-permission-denied-access-root-npm/5667/5)

Thank you, that fixed my issue. I will now close this thread.

**Comment by jonit-dev** [comment]
try  sudo chown yourlinuxuserhere -R . 

and then 

yarn install

**Comment by AiDriveOne** [comment]
having issues installing npm @tensorflow/tfjs-node, i need help please

**Comment by AiDriveOne** [comment]
well i tried it and it didn't work for me :


mac@Macs-MacBook-Air aiGPT % npm i @tensorflow/tfjs-node
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /Users/mac/node_modules/ansi-regex
npm ERR! dest /Users/mac/node_modules/.ansi-regex-lqjDShi4
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/Users/mac/node_modules/ansi-regex' -> '/Users/mac/node_modules/.ansi-regex-lqjDShi4'
npm ERR!  [Error: EACCES: permission denied, rename '/Users/mac/node_modules/ansi-regex' -> '/Users/mac/node_modules/.ansi-regex-lqjDShi4'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/Users/mac/node_modules/ansi-regex',
npm ERR!   dest: '/Users/mac/node_modules/.ansi-regex-lqjDShi4'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/mac/.npm/_logs/2023-04-02T22_11_22_578Z-debug-0.log
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % 
mac@Macs-MacBook-Air aiGPT % sudo npm install quick.db --unsafe-perm
Password:
npm ERR! code EISDIR
npm ERR! syscall open
npm ERR! path /Users/mac/package.json
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, open '/Users/mac/package.json'

npm ERR! A complete log of this run can be found in: /Users/mac/.npm/_logs/2023-04-02T22_16_28_000Z-debug-0.log
mac@Macs-MacBook-Air aiGPT % sudo npm install @tensorflow/tfjs-node --unsafe-perm
npm ERR! code EISDIR
npm ERR! syscall open
npm ERR! path /Users/mac/package.json
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, open '/Users/mac/package.json'

npm ERR! A complete log of this run can be found in: /Users/mac/.npm/_logs/2023-04-02T22_16_55_503Z-debug-0.log
mac@Macs-MacBook-Air aiGPT %
