### ISSUE TITLE
wasm backend returns incorrect values as result

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4525]
I have a very simple float32 model (link provided in the code below) that takes image with values in range of 0..255 as input and returns a single float32 value.  
Works perfectly with `webgl` backend, but values explode using `wasm` backend.  
E.g., instead of returning value in range of 1-99, it returns values like 700+.  

This is just one more case that looks like incorrect cast inside `wasm` backend, likely related to #4326 and #4311 that I've reported earlier.  

simple reproduction code:
```js
const resizeT = tf.image.resizeBilinear(image, [64, 64], false); // image is any picture of a face
const normalizeT = tf.mul(resizeT, [255.0]);
resizeT.dispose();
const model = await tf.loadGraphModel('https://vladmandic.github.io/human/models/age-ssrnet-imdb.json');
const ageT = await model.predict(normalizeT);
normalizeT.dispose();
const age = ageT.dataSync();
ageT.dispose();
console.log(age);
```

Environment: TFJS 2.8.3 on Chrome 87 / Windows 10

**Comment by vladmandic** [comment]
@rthadur @annxingyuan @pyu10055 lina128 sorry for the spam,  

but i have 3 issues filled (#4525, #4326, #4311) for `wasm` backend (with full reproduction code)  
that make `wasm` pretty much unusable.  
and all likely have the same root cause, just symptoms are different.

but none received any updates since they were filed (oldest was 2.5 months ago).

**Comment by jinjingforever** [comment]
Hi, Vladimir

Thank you for your patience!

I took a look at this and found that: if I disable simd, the result from WASM backend matches the webgl result. If simd is enabled (with or without multi-threading support), the result is wrong, like you mentioned. 

Our code uses different flags/options to build WASM module for different combinations of simd+multi-threading support. At this point it looks like that there are some potential bugs in xnnpack/simd. I will follow up with my colleagues and will update here if more comes up.

Thanks!

**Comment by vladmandic** [comment]
@jinjingforever thanks for the update

**Comment by jinjingforever** [comment]
BTW we further noticed that the wrong results come from some of the "div" nodes. With SIMD enabled, those nodes produce the results with the numerator and the denominator swapped.. I am asking folks from the xnnpack project to investigate further. Thanks!

**Comment by vladmandic** [comment]
@jinjingforever any update from xnnpack team?
i've chedked xnnpack git repository and there is nothing simmilar mentioned there.

**Comment by jinjingforever** [comment]
(sorry, I was on vacation last week)

Today we figured out that the error was caused by out-of-date xnnpack+emscripten. I am in the process of updating our toolchain to the latest xnnpack and emscripten. Hopefully it can be done this week. Thanks!
