### ISSUE TITLE
tfjs-node-gpu fails because missing binary version napi-v4  >2.7.0 for windows 

### ISSUE THREAD

**Issue by eunminlee** [tensorflow/tfjs#4529]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): yarn
- TensorFlow.js version: 2.8.3
- CUDA/cuDNN version: v10.0 v7.6.5

**Describe the problem**
yarn installation fails on windows I think there isn't binary version available for napi-v4.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./lib/napi-v4 fails

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@eunminlee can you please check similar issue here https://github.com/tensorflow/tfjs/issues/2046
