### ISSUE TITLE
@tensorflow/tfjs-node package.json file missing license value

### ISSUE THREAD

**Issue by DPain** [tensorflow/tfjs#4534]
Hi, I'm trying to get tfjs-node added into our corporate repository, but our process requires the package.json file to have the license header included.

@tensorflow/tfjs can be added easily, because it has the value "Apache-2.0" in the license header, but tfjs-node doesn't.

Is it intended that tfjs-node would not have the license header within its package.json file?

Thanks in advance!

**Comment by rthadur** [comment]
Added license filed in tfjs-node package.json
