### ISSUE TITLE
Add support for "string" type tensors

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#454]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.6

#### Browser version
irrelevant

#### Describe the problem or feature request
Support Tensors of dType 'string' and ops associated with that dtype, such as those here:
https://www.tensorflow.org/api_guides/python/string_ops
e.g.,
tf.string_to_hash_bucket
tf.string_split
tf.string_to_number

#### Code to reproduce the bug / link to feature request
t = tf.tensor1d(['hi'])

**Comment by dsmilkov** [comment]
String tensor and basic functionality added in https://github.com/tensorflow/tfjs-core/pull/1408, thus closing this issue. We can open separate issues per op.
