### ISSUE TITLE
Update face-landmarks-detection source to build against 3.0.0-rc.1

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#4548]

**Comment by arpu** [comment]
looks like 3.0.0 tsfs stable was released on npm would be nice to have face-landmarks-detection compatible to npm

**Comment by arpu** [comment]
@lina128 would be nice to have  3.2.0 builds on npm

**Comment by rthadur** [comment]
This has been updated to use latest 3.12.0 . Thank you
