### ISSUE TITLE
NodeGL Status

### ISSUE THREAD

**Issue by ecc521** [tensorflow/tfjs#4565]
The NodeGL page still states that it's under active development, however the demos have been broken since commit 74b93f074cd5d5d12cd303cc648b441664497c15, and the last code change was in early 2019. Additionally, the [Node-Gles](https://github.com/google/node-gles) dependency is showing no changes since April 2020. 

Has the NodeGL backend been suspended indefinitely? Is it being held up by ANGLE? Reading through issues, it looked like a release was anticipated in late 2019, and it's 2021 by now. 

I was anticipating that NodeGL would be a very solid and relatively config-free way to run Tensorflow on non-CUDA devices (especially Macs, given how NVIDIA isn't even officially supported), but it doesn't seem like anything is happening with it. Is electron the only option at this point, or are there plans for a production-ready NodeGL in the reasonable future?

Similar to #1906, this is probably a question for @nkreeger.

**Comment by pyu10055** [comment]
@ecc521 WE have suspended the Node-gles development due to lack of resources and interests. We will need external helps to move this project further, it could be a great project for TensorFlow.js SIG.
