### ISSUE TITLE
Query: Convert Tensorflow NMT with attention model to tfjs

### ISSUE THREAD

**Issue by kabyanil** [tensorflow/tfjs#4566]
I'm following the TensorFlow NMT with attention ([link](https://www.tensorflow.org/tutorials/text/nmt_with_attention)) guide to build a character level transliteration model. I'm able to train the model and make inference calls in an .ipynb notebook. I'm able to save training checkpoints and load them later. However, my front end application is built on electron js. Therefore, I need to convert the encoder-decoder model to tfjs. Would anybody provide some guidance to convert my model to tfjs? I'd be happy to provide source code if needed.

**Comment by rthadur** [comment]
@kabyanil did you check this old discussion on google groups https://groups.google.com/a/tensorflow.org/g/tfjs/c/OOz4JMu4kOg/m/z7Oig2ytAgAJ ?

**Comment by kabyanil** [comment]
@rthadur thanks for replying. going through the group discussion, i ended up on the tensorflow/ tfjs repository. it contains a note saying -

_Note: Session bundle format have been deprecated in TensorFlow.js 1.0. Please use the TensorFlow.js 0.15.x backend to convert session bundle, available in tfjs-converter 0.8.6._

i don't seem to understand it this means. how do i install tensorflow.js 0.15.x?

**Comment by rthadur** [comment]
please check step 7 as how to install lower version in VM here https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md. Thank you

**Comment by kabyanil** [comment]
i followed step 7 as mentioned...

i created a venv and tried installing tensorflowjs 0.8.6.

i got the following error -

```
Collecting tensorflowjs==0.8.6
  Using cached tensorflowjs-0.8.6-py3-none-any.whl (39 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from tensorflowjs)
ERROR: No matching distribution found for tensorflow==1.13.1
```
how do i install tensorflowjs 0.8.6 and convert my session bundle to tfjs?

**Comment by rthadur** [comment]
tensorflow has stopped supporting 1.13.1 so we do not support session bundle anymore as there is underlying dependency.
Updated README here https://github.com/tensorflow/tfjs/pull/4583

**Comment by kabyanil** [comment]
Thanks for the information. You may as well remove the 7th point in the README file.

**Comment by rthadur** [comment]
Sure , opened a new PR to remove , thank you
