### ISSUE TITLE
how to load a model from local path?

### ISSUE THREAD

**Issue by Kevin-1993-35** [tensorflow/tfjs#4568]
I have converted a tensorflow savedmodel to tensorflow json format and saved it locally in my computer.i I am trying to load that json model in a javascript code using the below command ,but i find it only works for loading model from a url,is there any way to load a model from local path?
     
       `import * as tf from '@tensorflow/tfjs';
       import {loadGraphModel} from '@tensorflow/tfjs-converter';
       const MODEL_URL = './model.json';
      const  model = await loadGraphModel(MODEL_URL);

**Comment by DPain** [comment]
Depending on what tfjs you're using, you'd probably want to use `localstorage://modelName` (for browser) or `file://modelName` (for node.js). This works for saving models, so I bet it'd work for your case too.

**Comment by rthadur** [comment]
try moving the model.json and weight files in to model folder and load using below code 
`    model = await tf.loadGraphModel('model/model.json');
`

**Comment by Kevin-1993-35** [comment]
@rthadur I did as you said but got the same error as before，It doesn't seem to work for me
    `Failed to load resource: the server responded with a status of 404 (Not Found)
    http.ts:161 Uncaught (in promise) Error: Request to model/model.json failed with status code 404. Please verify this URL points 
     to the model JSON of the model to load.
    at HTTPRequest.load (http.ts:161)
    at async GraphModel.load (graph_model.ts:132)
    at async loadGraphModel (graph_model.ts:440)`

**Comment by Kevin-1993-35** [comment]
@DPain   What do you mean by modelname? is it the path to model.json?

**Comment by DPain** [comment]
> @DPain What do you mean by modelname? is it the path to model.json?

Oh yeah, the directory to your `model.json`. Check this example out if you're working with node.js.
https://github.com/tensorflow/tfjs-examples/tree/master/abalone-node

**Comment by Kevin-1993-35** [comment]
> > @DPain What do you mean by modelname? is it the path to model.json?
> 
> Oh yeah, the path to your `model.json`. Check this example out if you're working with node.js.
> https://github.com/tensorflow/tfjs-examples/tree/master/abalone-node
> 
> I don't have much experience using tfjs on the front end, but tfjs's documentation in the code has some great examples as well.

**Comment by Kevin-1993-35** [comment]
@DPain  well,I am working with browser.so i replaced my code with below,but got error `Error: In local storage, there is no model with name 'D:/tfjs-models-master/blazeface/demo/model/model.json'`,i tried both  absolute path and relative path but got same error.
   ` const MODEL_URL = 'localstorage://D:/tfjs-models-master/blazeface/demo/model/model.json';`

**Comment by DPain** [comment]
> @DPain  well,I am working with browser.so i replaced my code with below,but got error `Error: In local storage, there is no model with name 'D:/tfjs-models-master/blazeface/demo/model/model.json'`,i tried both  absolute path and relative path but got same error.
>    `const MODEL_URL = 'localstorage://D:/tfjs-models-master/blazeface/demo/model/model.json';
>      const  model = await loadGraphModel(MODEL_URL);`

Oh if you're working with the browser, the localstorage doesn't actually mean your project folder. It means the browser's localstorage. https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by andypotato** [comment]
In case anyone comes here from a Google search, here is how you do it:

```
const tfn = require('@tensorflow/tfjs-node');

const modelPath = '/path/to/your/model.json';
const handler = tfn.io.fileSystem(modelPath);

const model = await tf.loadLayersModel(handler);
```
