### ISSUE TITLE
Memory leak in model.fit with callbacks

### ISSUE THREAD

**Issue by devspaceship** [tensorflow/tfjs#457]
*TensorFlow.js version 0.11.6*

It seems like there is still a **memory leak** in the fit method but only when using **callbacks**

![image](https://user-images.githubusercontent.com/15971801/41696609-2f082548-7515-11e8-8ae1-50efa659490c.png)

**Comment by caisq** [comment]
@devspacehlp Thanks for reporting this issue. Can you show us the callback you are using?

**Comment by devspaceship** [comment]
At the origin I was using the callback onBatchEnd to modifiy a status <p> element and indicate the logs.loss but there's still the issue with a blank function as shown in the picture in my first post
