### ISSUE TITLE
`layers.lstm` returns type `Layers` instead of `RNN`

### ISSUE THREAD

**Issue by kiancross** [tensorflow/tfjs#4578]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**
- TensorFlow.js installed from (npm or script link): **From npm**
- TensorFlow.js version (use command below): **2.8.4**

**Describe the current behavior**

`layers.lstm` returns type `Layer`:

https://github.com/tensorflow/tfjs/blob/2ec85af6c8d4b869989d8c4a6211868e99a0997f/tfjs-layers/src/exports_layers.ts#L1242

However, the `LSTM` class is of type `RNN`:

https://github.com/tensorflow/tfjs/blob/2ec85af6c8d4b869989d8c4a6211868e99a0997f/tfjs-layers/src/layers/recurrent.ts#L1847

**Describe the expected behavior**

`layers.lstm` should return type `RNN`, so that it can be used with `layers.bidirectional`.

**Comment by rthadur** [comment]
We will export RNNCell as tf.layers.RNNCell and export RNN as tf.layers.RNN.

**Comment by kiancross** [comment]
> We will export RNNCell as tf.layers.RNNCell and export RNN as tf.layers.RNN.

@rthadur And also change the return type of `lstm` from `Layer` to `RNN`?

**Comment by rthadur** [comment]
cc @pyu10055 @lina128 @mattsoulanille

**Comment by kiancross** [comment]
@rthadur Can we keep this open?

**Comment by rthadur** [comment]
Sure , gentle ping for @pyu10055 @jinjingforever

**Comment by pyu10055** [comment]
@kiancross We export all layers as Layer type, it is the parent class for all layers.
If you are trying to avoid typescript error, you can cast the object to RNN, in order to use for bidirectional method.
```
    const lstm = tfl.layers.lstm({
      units: 1,
      kernelInitializer: 'ones',
      recurrentInitializer: 'ones',
      biasInitializer: 'ones',
      goBackwards: true
    }) as RNN;
    const bidi = tfl.layers.bidirectional(
        {layer: lstm, inputShape: [2, 2], mergeMode: 'ave'});
```

**Comment by kiancross** [comment]
@pyu10055 Ok, I guess that works.

It's a bit strange to export it as a `Layer` rather than `RNN` though - why not leave it as `RNN`?
