### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from tensorflowjs)

### ISSUE THREAD

**Issue by kabyanil** [tensorflow/tfjs#4580]
I am following the NMT with attention tutorial from tensorflow docs. My requirement is to port the same model to tfjs. the tensorflow/tfjs repository readme.md file has a note saying -

_Note: Session bundle format have been deprecated in TensorFlow.js 1.0. Please use the TensorFlow.js 0.15.x backend to convert session bundle, available in tfjs-converter 0.8.6._
.
.
.
as well as
.
.
.
_7. I have a model formatted as a Session bundle. How do I convert it to TensorFlow.js?_
.....
`pip install tensorflowjs==0.8.6`

following the readme.md, i created a venv and tried installing tensorflowjs 0.8.6.

i got the following error -

```
Collecting tensorflowjs==0.8.6
  Using cached tensorflowjs-0.8.6-py3-none-any.whl (39 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from tensorflowjs)
ERROR: No matching distribution found for tensorflow==1.13.1
```

how do i install tensorflowjs 0.8.6 and convert my session bundle to tfjs?

**Comment by rthadur** [comment]
Lets track this issue at one place here https://github.com/tensorflow/tfjs/issues/4566 , thank you
