### ISSUE TITLE
tfjs-examples tSNE example sometimes fails with lost WebGL context

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#459]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.6 and 0.11.7 (latest as of now)

#### Browser version
Version 67.0.3396.87 (Official Build) (64-bit) on Linux

#### Describe the problem or feature request
Run the tSNE example (https://github.com/tensorflow/tfjs-examples/tree/master/tsne-mnist-canvas) with the default settings (data size: 10,000 examples). On my machine, the browser tab freezes for a few seconds, and then an error appears in the console:

```none
environment.js:249 Registration of backend webgl failed
Environment.registerBackend @ environment.js:249
require.33.../environment @ backend_webgl.js:953
newRequire @ noevent.js:5
localRequire @ noevent.js:5
require.8../kernels/backend_webgl @ index.js:1
newRequire @ noevent.js:5
localRequire @ noevent.js:5
require.2.@tensorflow/tfjs-core @ index.js:18
newRequire @ noevent.js:5
require.111 @ noevent.js:5
(anonymous) @ noevent.js:5
environment.js:250 Error: WebGL is not supported on this device
    at new MathBackendWebGL (backend_webgl.js:100)
    at backend_webgl.js:953
    at Environment.registerBackend (environment.js:244)
    at Object.require.33.../environment (backend_webgl.js:953)
    at newRequire (noevent.js:5)
    at localRequire (noevent.js:5)
    at Object.require.8../kernels/backend_webgl (index.js:1)
    at newRequire (noevent.js:5)
    at localRequire (noevent.js:5)
    at Object.require.2.@tensorflow/tfjs-core (index.js:18)
Environment.registerBackend @ environment.js:250
require.33.../environment @ backend_webgl.js:953
newRequire @ noevent.js:5
localRequire @ noevent.js:5
require.8../kernels/backend_webgl @ index.js:1
newRequire @ noevent.js:5
localRequire @ noevent.js:5
require.2.@tensorflow/tfjs-core @ index.js:18
newRequire @ noevent.js:5
require.111 @ noevent.js:5
(anonymous) @ noevent.js:5
tensor_to_data_texture.js:48 Uncaught (in promise) Error: WebGL backend is not available
    at tensor_to_data_texture.js:48
    at step (tensor_to_data_texture.js:31)
    at Object.next (tensor_to_data_texture.js:12)
    at tensor_to_data_texture.js:6
    at new Promise (<anonymous>)
    at __awaiter (tensor_to_data_texture.js:2)
    at tensorToDataTexture (tensor_to_data_texture.js:39)
    at TSNE.<anonymous> (tsne.js:97)
    at step (tsne.js:31)
    at Object.next (tsne.js:12)
```

**Comment by caisq** [comment]
cc @nicola17

**Comment by nsthorat** [comment]
@dsmilkov I think you may be fixing this soon.

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Apologize for the delayed response and I was trying to replicate the same issue from my end and I was getting below error message after following the instructions in the official documentation from [here](https://github.com/tensorflow/tfjs-examples/tree/master/tsne-mnist-canvas) and also tried [See this example live!](https://storage.googleapis.com/tfjs-examples/tsne-mnist-canvas/dist/index.html) for that also I'm getting error message so we'll dig more into this issue and will update you soon.

Thank you for bringing this issue to our attention. Thank you!

Below error screenshot after trying on `Mac M1 Machine`

![image](https://github.com/tensorflow/tfjs/assets/115997457/22a59953-fb45-489f-b039-ad13868b307b)


Below error screenshot from `See this example` :

![image](https://github.com/tensorflow/tfjs/assets/115997457/20a6170d-cef6-4b63-9863-728f2037f247)

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

As we discussed in the internal meeting and this `tfjs-tsne example: MNIST` tfjs-example is depreciated and it's using the very old version of `tfjs` and `tSNE for TensorFlow.js` repository has been archived by the owner on Sep 14, 2021. It is now read-only. please refer this [link](https://github.com/tensorflow/tfjs-tsne) so if I'm not wrong we can close this issue.

Thank you!
