### ISSUE TITLE
Minor typo (I believe)

### ISSUE THREAD

**Issue by EFHIII** [tensorflow/tfjs#4592]
```
Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: [path]\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v7\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
```
> Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source'

should be
> Please run command 'npm rebuild @tensorflow/tfjs-node-gpu --build-addon-from-source'

if I'm not mistaken...

I'd make a Pull Request myself if I knew which file to change.

**Comment by rthadur** [comment]
Here is the file https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/index.ts#L43 , where you can submit a PR. Thank you

**Comment by EFHIII** [comment]
Oh, is that file used for both the GPU and non-GPU versions? 

Would the best solution be to add a conditional like

```js
// error message
`'npm rebuild @tensorflow/tfjs-node`+
(String(bindingPath).indexOf('@tensorflow\tfjs-node-gpu\') > 0 ? `-gpu` : ``) +
` --build-addon-from-source' to ` +
// error message
```
?

**Comment by rthadur** [comment]
@pyu10055 @lina128

**Comment by pyu10055** [comment]
@EFHIII looks good, I will suggest to just check for string `tfjs-node-gpu` instead to avoid dealing with file separators.
