### ISSUE TITLE
[tfjs-react-native] [iOS only] Initialization of backend rn-webgl failed [native code]

### ISSUE THREAD

**Issue by zholmes1** [tensorflow/tfjs#4593]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 14.3 Simulator / Device
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 11
```
yarn list v1.22.10
├─ @tensorflow/tfjs-automl@1.0.0
├─ @tensorflow/tfjs-backend-cpu@2.7.0
├─ @tensorflow/tfjs-backend-webgl@2.7.0
├─ @tensorflow/tfjs-converter@2.7.0
├─ @tensorflow/tfjs-core@2.7.0
├─ @tensorflow/tfjs-data@2.7.0
├─ @tensorflow/tfjs-layers@2.7.0
├─ @tensorflow/tfjs-react-native@0.5.0
└─ @tensorflow/tfjs@2.7.0
```

**Describe the current behavior**
On launch, when I tf.ready(), I get the warning Initialization of backend rn-webgl failed

**Describe the expected behavior**
rn-webgl platform loads

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```
// index.js
import '@tensorflow/tfjs-react-native'
```

```
// App.tsx
import * as tf from '@tensorflow/tfjs'

...

const [tfReady, setTfReady] = useState(false)

useEffect(() => {
  tf.ready()  // <-- this is when the warning happens
    .then(() => setTfReady(true))
}, [])

if (!tfReady) {
  return null
}

// render app
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
yarn list v1.22.10
├─ expo-asset@8.2.1
├─ expo-camera@9.0.0
├─ expo-constants@9.2.0
├─ expo-file-system@9.2.0
├─ expo-font@8.3.0
├─ expo-gl-cpp@9.1.2
├─ expo-gl@9.1.1
├─ expo-image-loader@1.2.0
├─ expo-linking@2.0.0
│  └─ expo-constants@9.3.5
├─ expo-location@9.0.1
├─ expo-media-library@9.2.1
├─ expo-network@2.4.0
├─ expo-permissions@9.3.0
├─ expo-splash-screen@0.8.1
└─ expo-store-review@2.3.0
```

All of these dependencies are configured and working on their own. WebGL initializes and works properly on Android emulator and device. This is an issue I'm encountering only for iOS, both on simulator and device.

**Comment by zholmes1** [comment]
Standing up a new project with `npx create-react-native-app` and doing the minimum dependency installations allowed me to get the rn-webgl backend loading. Closing the issue for now until I can figure out why it's not working in my app.

**Comment by Cannonball2134** [comment]
Did you ever figure out what caused it?

**Comment by zholmes1** [comment]
@Cannonball2134 

> Did you ever figure out what caused it?

No idea, but creating a new RN project and copying over all my code fixed it

**Comment by AKACC** [comment]
Hi @zholmes1, I face the same error like you did. From your case, I kinda found out a trick which can be a temporary solution for this problem.

I manually install @tensorflow/tfjs-backend-wasm and run `pod install`. The problem fixed by itself.

After a few successful build, the error show up again. I uninstall @tensorflow/tfjs-backend-wasm and run `pod install`. The problem fixed again.

 @Cannonball2134 hopefully this is still helpful for you
