### ISSUE TITLE
tf.unique failing on Node only with `Error running Unique: Neither modular kernel nor forward func passed`

### ISSUE THREAD

**Issue by GantMan** [tensorflow/tfjs#4595]
The code 
```ts
const tf = require('@tensorflow/tfjs-node')

const a = tf.tensor1d([1, 1, 2, 4, 4, 4, 7, 8, 8]);
const {values, indices} = tf.unique(a);
```

Fails on **windows** and **mac** for Node.js

If you switch backend to CPU it works.

Here it is failing on node
<img width="1456" alt="Screen Shot 2021-01-24 at 8 31 28 PM" src="https://user-images.githubusercontent.com/997157/105654244-35b96000-5e83-11eb-8d30-90c5ba88379d.png">

But when using CPU backend it works.

See https://github.com/GantMan/unique_fail_poc for failure and success reproductions with latest release of TFJS Node.  

Let me know if I can help with anything.   Tested on two machines, and it fails on quite a few versions of TFJS, btw.  Lots of stuff works just fine, it's just tf.unique that seems angry.

**Comment by rthadur** [comment]
@GantMan thank you for detailed report , tf.unique is only supported in 'cpu' and 'webgl' for now , this would be a feature request to add it to Node.

**Comment by rthadur** [comment]
cc @jinjingforever

**Comment by GantMan** [comment]
I think it would be wise to add some kind of notation or caveat to the docs where functions are unsupported.  A small note on (the docs)[https://js.tensorflow.org/api/latest/#unique] would identify this is not a bug.

Secondly, as another feature, better error messages would be a good feature as well.  It took me a while to find out what the issue was.  

I'll make a note of this and try to contribute back if this issue is still outstanding when I get some cycles.

**Comment by bibs2091** [comment]
Hello, any news relating to this feature? I think getting the unique values in a tensor in a core method and should be also implemented for node

**Comment by ClaytonSmith** [comment]
What's the status on this? Its been Three years, any updates? Definitely a needed feature.

**Comment by ClaytonSmith** [comment]
Second comment: Why was this issue closed in response to https://github.com/tensorflow/tfjs/pull/5956? That PR did not address the issue being reported. 

From https://js.tensorflow.org/api/latest/#unique 
`Kernel 'Unique' not registered for backend 'webgpu'`
