### ISSUE TITLE
How to read modelWeights.bin from file system 

### ISSUE THREAD

**Issue by kscgl** [tensorflow/tfjs#4596]
As it is raised before, I am not able to load model as below. It gives `TypeError: Network request failed `error.  

`const model = await tf.loadLayersModel('file://path/to/my-model/model.json');`

I need to read model.json and model_weights.bin manually and bundle them together. I am able to read model.json without any issues but I am having troubles to get right type for bin file. 

```
const rootPath = Platform.OS === 'ios' ? RNFS.MainBundlePath : RNFS.DocumentDirectoryPath;
const modelWeights = await RNFS.readFile(`${rootPath}/model_weights.bin`, 'base64');
```

I am not sure how to convert modelWeights (string) into number to use `bundleResourceIO(modelJson: io.ModelJSON, modelWeightsId: number)`

I saw suggestions to convert base64 string into Uint8Array but I couldn't find a way to convert it into 'number' type.

```
const buffer = tf.util.encodeString(modelWeights, 'base64').buffer;
const arr = new Uint8Array(buffer);
```

Any suggestions how to bundle them together or any other ways loading model from native file system? 

PS: Statically bundle works without any issues. 

```
import modelJson from './assets/model.json';
import modelWeights from './assets/model_weights.bin';

const model = await tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights));
```

**Standalone code to reproduce the issue**

```
import React from 'react';
import {Button, View} from 'react-native';
import * as tf from '@tensorflow/tfjs';
import {bundleResourceIO} from '@tensorflow/tfjs-react-native';
import modelJson from './assets/model/model.json';
import modelGroup from './assets/model/group1-shard1of1.bin';
import RNFS from 'react-native-fs';

class Home extends React.Component {
  triggerModel = async () => {
    await tf.ready();

    //Successful
    const model = await tf.loadGraphModel(
      bundleResourceIO(modelJson, modelGroup),
    );

    //model.json and group1-shard1of1.bin exists in file system
    //returns model.json file successfully
    const modelJson1 = await RNFS.readFile(
      `${RNFS.DocumentDirectoryPath}/model/model.json`,
    );

    //Throws TypeError: Network request failed
    const model1 = await tf.loadGraphModel(modelJson1, {
      weightUrlConverter: async (weightFileName) => {
        return `file://${RNFS.DocumentDirectoryPath}/model/group1-shard1of1.bin`;
      },
    });

    //Throws TypeError: Network request failed
    const model2 = await tf.loadGraphModel(
      `${RNFS.DocumentDirectoryPath}/model/model.json`,
    );
  };

  render() {
    return (
      <View>
        <Button onPress={() => this.triggerModel()}>Trigger Model</Button>
      </View>
    );
  }
}

export default Home;

```

**Comment by HarshalRohit** [comment]
@kscgl Please update if you get any solution on this.

I am working on something similar.

**Comment by nischal-sanil** [comment]
Also, I have a similar questions. That is how to load a model with two different links to json and weights file. If anybody here knows how to do it, do let me know.

Thanks.

**Comment by nischal-sanil** [comment]
There is an optional argument in the loadGraphModel called `weightUrlConverter` which can be used to modified the weights path. It worked for me. 

Hope this helps.

**Comment by kscgl** [comment]
Thank you @nischal-sanil for suggestion. I tried as below but I got `TypeError: Network request failed`

```
const modelLoad = await tf.loadGraphModel(modelJson, {
            weightUrlConverter:
              'file://' +
              RNFS.DocumentDirectoryPath +
              '/model/group1-shard1of1.bin',
          });
```

**Comment by nischal-sanil** [comment]
@kscgl You should pass an async function to the `weightUrlConverter`. This function will receive a `weightFileName: string` as input and should return path to the weights. If you path is correct something like this should work.

```
const modelLoad = await tf.loadGraphModel(modelJson, {
            weightUrlConverter: async function (weightFileName) => {
              return 'file://' +
              RNFS.DocumentDirectoryPath +
              '/model/group1-shard1of1.bin',
          }});
```

**Comment by kscgl** [comment]
@nischal-sanil I am getting the same network request failed error. 

```
  const modelLoad = await tf.loadGraphModel(modelJson, {
            weightUrlConverter: this.getWeightFile(
              'model/group1-shard1of1.bin',
            ),
          });


  getWeightFile = async (weightFileName) => {
    return `file://${RNFS.DocumentDirectoryPath}/${weightFileName}`;
  };
```

**Comment by nischal-sanil** [comment]
Do not call the function. By calling it you are again passing a string as an input. 

Try something like this.

```
  const modelLoad = await tf.loadGraphModel(modelJson, {
            weightUrlConverter : async (weightFileName) => {
                  return `file://${RNFS.DocumentDirectoryPath}/${weightFileName}`;
          }});
```

**Comment by kscgl** [comment]
@nischal-sanil I see. I tried that one but same error. 

```
const modelLoad = await tf.loadGraphModel(modelJson, {
            weightUrlConverter: async (weightFileName) => {
              return `file://${RNFS.DocumentDirectoryPath}/model/group1-shard1of1.bin`;
            },
          });
```

**Comment by nischal-sanil** [comment]
hmmm, Not sure why this is the case then. If the path is right it should have worked. May be you can try another optional argument called `weightPathPrefix` instead of `weightUrlConverter`. Check out the [docs](https://js.tensorflow.org/api/latest/#loadGraphModel)

**Comment by kscgl** [comment]
@nischal-sanil That won't work either because it always give `TypeError: Network request failed` wherever I provide a location from file system.

**Comment by nischal-sanil** [comment]
Aren't you using a local server?

**Comment by kscgl** [comment]
@nischal-sanil For what purpose? I provide the path of phone file system itself.

**Comment by rthadur** [comment]
@kscgl can you please share minimal code for reproduction ? if you are loading local file system , you should not see above error, are you trying to load using script tags ?

**Comment by kscgl** [comment]
@rthadur I updated the initial post to add standalone code. Please let me know if you need more details.

**Comment by kscgl** [comment]
@HarshalRohit I decided to go with [asyncStorageIO handler](https://js.tensorflow.org/api_react_native/0.2.1/#asyncStorageIO) until I figure this out. 

```
...
const modelName = 'customModelName';
await model.save(asyncStorageIO(modelName));
//Save modelName somewhere. I use local database
...

//Fetch your model name then call your model
const modelName = fetchModelName();
const model = await tf.loadGraphModel(asyncStorageIO(modelName));
...
```

**Comment by HarshalRohit** [comment]
@kscgl Thanks!!

**Comment by HarshalRohit** [comment]
I am getting **Error** `Row too big to fit into CursorWindow requiredPos=0, totalRows=1` on calling `tf.LoadLayersModel`.

@kscgl How much is your model size (as returned by  `model.save(asyncStorageIO(modelName))` ? Mine is 6 MB.

@jinjingforever I understand this is due sqlite limits, but is there any workaround for this??

**Comment by kscgl** [comment]
@HarshalRohit Mine is around 1 MB. It's probably due to Android AsyncStorage limit which is 6 MB. You can look into how to incresae AsyncStorage size and try if that works.

**Comment by HarshalRohit** [comment]
@kscgl Increasing the AsyncStorage size doesn't work.
I tried increasing the size and 
`model.save` works fine but
`model.load` throws the error `Row too big to fit into CursorWindow requiredPos=0, totalRows=1`.

I guess I will have to write custom IO handler.

**Comment by rthadur** [comment]
This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
