### ISSUE TITLE
Slicing the last layer's output before put it into the model

### ISSUE THREAD

**Issue by jacobchen1** [tensorflow/tfjs#4600]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):3.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
I am working with time series data with TCN model, there is no function that supports slicing the last layers'. output.
**Will this change the current api? How?**

**Who will benefit with this feature?**
All the researcher who is working with the state of art architecture for time series data
**Any Other info.**

**Comment by pyu10055** [comment]
@jacobchen1 Do you mind providing a simple example to demonstrate your use case? Do you need to output before the last layer?
You can create a new tf.Model instances using the same input as the original model and output of the layer before the last one. 

Something like
```
const index = oldModel.layers.length - 2;
const newModel = tf.model({inputs: oldModel.inputs, outputs: oldModel.layers[index].output); 
const layerActivation = newModel.predict(inputValue);
```
