### ISSUE TITLE
API Version 3.0.0 is not working with script link

### ISSUE THREAD

**Issue by jacobchen1** [tensorflow/tfjs#4603]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**
I use this <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.0.0/dist/tf.min.js"></script>
to implement CNN. There is  a error poped up. When the version downgrades to 2.8.5, the error has been disappeared. Are there any solutions for this issue?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Node Version v12

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
@jacobchen1 Thanks for reporting, Can you share a codepen for reproducing this error?
