### ISSUE TITLE
Contribute a TFJS example

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/tfjs#4617]
I am looking to contribute a and example to the [tfjs-examples](https://github.com/tensorflow/tfjs-examples) repository which asks to first reach out via a GitHub issue.

I am planning on contributing the [MIRNet-TFJS](https://github.com/Rishit-dagli/MIRNet-TFJS/tree/prod) example by me. This is a minimalistic example that aims to enhance low-light images up to a great extent on the web. As an example some of the results are as follows:

![image](https://user-images.githubusercontent.com/39672672/106258131-74646700-6243-11eb-9ec2-f735df416539.png)

You are requested to kindly help me if this example would be a good fit to contribute and if so what my next steps would be.

**Comment by pyu10055** [comment]
@Rishit-dagli This is very cool! Since you already have a separate github repo, it will be easier to add to our gallery page without duplicating the effort. Thanks!

**Comment by jasonmayes** [comment]
This one: https://github.com/tensorflow/tfjs/blob/master/GALLERY.md

**Comment by Rishit-dagli** [comment]
@pyu10055 Sure that makes sense, I will make a PR adding this project to the gallery page. Thanks, @jasonmayes for sharing the gallery page.
