### ISSUE TITLE
Feature request for `tf.io.encode_jpeg` in tfjs-react-native.

### ISSUE THREAD

**Issue by ahtrahdis7** [tensorflow/tfjs#4620]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 2.8.5
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The Js version of  `tf.io.encode_jpeg` <a href="https://www.tensorflow.org/api_docs/python/tf/io/encode_jpeg"> Link </a>

**Will this change the current api? How?**
Nope

**Who will benefit with this feature?**
Everyone implementing image based models into their projects.

**Any Other info.**
Nope

**Comment by rthadur** [comment]
Here is the node version of encode jpeg https://js.tensorflow.org/api_node/3.0.0/#node.encodeJpeg , please let me know if this helps ?

**Comment by ahtrahdis7** [comment]
I need the react-native version of the same.

**Comment by rthadur** [comment]
cc @mattsoulanille do we support this in react-native ?

**Comment by ahtrahdis7** [comment]
@rthadur  I don't think so. I have checked the repository thoroughly and the documentation too.

**Comment by gaikwadrahul8** [comment]
Hi, @ahtrahdis7 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and If I'm not wrong this `encodeJpeg` is not implemented as of now and I see we have [decodeJpeg](https://js.tensorflow.org/api_react_native/0.8.0/#decodeJpeg) in `tfjs-react-native` May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
