### ISSUE TITLE
Tensorflow.js implimentation error on Blazor Server Application

### ISSUE THREAD

**Issue by felixkjoseph** [tensorflow/tfjs#4622]
Hi, Need one help, am trying to implement tensorflow.js into my Blazor Server application.  But in the java script  
Promise.all([
        faceapi.nets.tinyFaceDetector.loadFromUri('models'),
        faceapi.nets.faceLandmark68Net.loadFromUri('models'),
        faceapi.nets.faceExpressionNet.loadFromUri('models')
    ]).then(beginVideo);
getting an error 
face-api.min.js:1 Uncaught (in promise) Error: Based on the provided shape, [3,3,32,1], the tensor should have 288 values but has 281

https://github.com/felixkjoseph/BlazorTensorflowJS.git
Thanks in advance

**Comment by pyu10055** [comment]
@felixkjoseph Not familiar with Blazor, purely based on your description, this could be an network issue, (i.e. CORS etc) You should check network tab (if this runs in browser) to see if the model files are downloaded correctly.

**Comment by JMHeartley** [comment]
Hello, the original poster didn't respond, however I'm trying to implement face-api.js (which runs on top of tensorflow) in a Blazor server application and I'm getting the same error. The model.json files are loading correctly however when the shard files are loaded they're much smaller than expected. The thing is I can run the same code and models in Visual Studio Code using live server just fine but when I run it in VS 2019 using IIS Express I get this error. Is this an issue with the way the files are being hosted?
