### ISSUE TITLE
Unknown op: BroadcastArgs

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tfjs#4624]
**System information**
- TensorFlow.js version (you are using): 3.0.0
- Are you willing to contribute it (Yes/No): No, but can if told what to change and where

**Describe the feature and the current behavior/state.**
BroadcastArgs are not supported. [tf.linspace](https://www.tensorflow.org/api_docs/python/tf/linspace) changed implementations between TF versions 2.2.0 and 2.3.0 to use BroadcatsArgs and now models using linspace cannot be converted to TFJS.

An example model:
```
import tensorflow as tf
tf.keras.Sequential([tf.keras.Input(shape=(4,)), tf.keras.layers.Lambda(lambda x: tf.linspace(0, 1024, 1))])
```
If a model like this is run through the tfjs converter the following error is returned:
```
Unsupported Ops in the model before optimization
BroadcastArgs
```

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
People who use functions that use BroadcastArgs such as linspace

**Any Other info.**

**Comment by david942j** [comment]
Facing the same issue when converting polices trained by tf agents to tensorflowjs models.

**Comment by rthadur** [comment]
cc @pyu10055 @mattsoulanille

**Comment by rthadur** [comment]
related PR has been merged and changes are now available. closing this issue. Thank you
