### ISSUE TITLE
Convert Output Tensor to Image/Canvas

### ISSUE THREAD

**Issue by Kevin-1993-35** [tensorflow/tfjs#4627]
I've a js model which predicts depth-image as a tensor.
I tried to I covert the tensor to image by using tf.node.encodePng ,but got the error  _TypeError: Cannot read property 'encodePng' of undefined_
Any suggestions on how I can convert the tensor to an image/canvas ?

**Comment by rthadur** [comment]
please check for a similar issue here https://github.com/tensorflow/tfjs/issues/3140 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.
