### ISSUE TITLE
Build Custom non-trainable Layers using `tf.layers.fn`

### ISSUE THREAD

**Issue by piercus** [tensorflow/tfjs#4629]
**System information**
- TensorFlow.js version (you are using):
- I'm willing to contribute, just want to make sure this makes sense for someone else, and/or maybe there is already some work in progress related to this

**Describe the feature and the current behavior/state.**

## Actual

On my current understanding, building a simple custom layer (like a sum layer) is made by creating a CustomLayer Class

```js
const tf = require('../tf');

class SumLayer extends tf.layers.Layer {
	constructor(config) {
		super(config);
		this.axis = config.axis;
		this.keepDims = config.keepDims;
	}
	/**
	* Call() contains the actual numerical computation of the layer.
	*
	* It is "tensor-in-tensor-out". I.e., it receives one or more
	* tensors as the input and should produce one or more tensors as
	* the return value.
	*
	* Be sure to use tidy() to avoid WebGL memory leak.
	*/
	call(input) {
		return tf.tidy(() => {
			return tf.sum(input, this.axis, this.keepDims);
		});
	}

	/**
	* GetConfig() generates the JSON object that is used
	* when saving and loading the custom layer object.
	*/
	getConfig() {
		const config = super.getConfig();
		Object.assign(config, {axis: this.axis});
		return config;
	}

	/**
	* The static className getter is required by the
	* registration step (see below).
	*/
	static get className() {
		return 'SumLayer';
	}
}
/**
 * Regsiter the custom layer, so TensorFlow.js knows what class constructor
 * to call when deserializing an saved instance of the custom layer.
 */
tf.serialization.registerClass(SumLayer);
```

## Expected

Maybe we could directly create a custom layer like : 
```js
const axis = 2;
const keepDims = false;
const layer = tf.layers.fn((a) => tf.sum(a, axis, keepDims))
```

**Will this change the current api? How?**

I do not feel it will change anything to current api

**Who will benefit with this feature?**

Faster prototyping, less code.

**Comment by rthadur** [comment]
@pyu10055 @lina128 @caisq

**Comment by pyu10055** [comment]
@piercus Thank you for thinking about this, I want to make sure I understand your idea, are you suggesting to create a helper method
fn() which takes a function and returns a registered custom layer class instance? This sounds like a great idea, looking forward to your contirbution.

**Comment by caisq** [comment]
@piercus How do you plan to support serialization / deserialization of such a function layer?

Serialization is an important consideration for saving a model and loading it elsewhere.

**Comment by piercus** [comment]
Thanks for tour feedbacks !

@pyu10055 yes exactly, i was thinking of https://keras.io/api/layers/core_layers/lambda/ for js

@caisq i feel serialization will be a concern yes. When checking at your example on https://gist.github.com/caisq/33ed021e0c7b9d0e728cb1dce399527d , my first guess is
* I was thinking to generate a custom registered class with `cls.className = 'Custom<hash>'` with `hash=sha1(fn.toString())`. 
* I'm not sure if sha1 or any other 'hash' function is available in tfjs, i need to dig into this

This is really a prototyping-focused feature on my mind, so no trainable weights or config

What do you think ?

**Comment by gaikwadrahul8** [comment]
Hi, @piercus 

Apologize for the delayed response and we are re-visiting our older feature request issues and checking whether those feature requests implemented or not as of now so May I know are you working on this feature request or not please ?  May I know are you still looking for this feature in TFJs ?	

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
