### ISSUE TITLE
Problem occuring, while following the example for pitch types 

### ISSUE THREAD

**Issue by NiklasRosar** [tensorflow/tfjs#4633]
Hello, 

I have used tensorflow.js with script-tag and this have worked very good for me for a long time. 
Now, I want to use the node.js setup for improving the performance by using cpu. 
(gpu support doesn't work for me, because I have no access to NVIDIA gpu)
This is the first time I work with node.js
To get a feeling, how this approach works, I try to follow the example for classifying pitch types:
[https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab/#0](url)
The first issue occurs in step 3 by executing "npm install". I get this message: 

> @tensorflow/tfjs-node@1.7.4 install C:\***\baseball\node_modules\@tensorflow\tfjs-node
> node scripts/install.js
>CPU-windows-1.7.4.zip
>* Downloading libtensorflow
>[==============================] 3866376/bps 100% 0.0s
>* Building TensorFlow Node.js bindings
> core-js@3.8.3 postinstall C:\***\baseball\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"
>Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
>The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock
>Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
>npm WARN tfjs-examples-baseball-node@0.2.0 No repository field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>added 737 packages from 508 contributors and audited 742 packages in 27.984s
>24 packages are looking for funding
>run `npm fund` for details
>found 4 low severity vulnerabilities
>run `npm audit fix` to fix them, or `npm audit` for details

When I run "npm audit fix" I get this message:

>npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
>npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>npm WARN @tensorflow/tfjs-backend-cpu@3.0.0 requires a peer of @tensorflow/tfjs-core@3.0.0 but none is installed. You must install peer dependencies yourself.
>npm WARN @tensorflow/tfjs-backend-webgl@3.0.0 requires a peer of @tensorflow/tfjs-core@3.0.0 but none is installed. You must install peer dependencies yourself.
>npm WARN @tensorflow/tfjs-converter@3.0.0 requires a peer of @tensorflow/tfjs-core@3.0.0 but none is installed. You must install peer dependencies yourself.
>npm WARN @tensorflow/tfjs-data@3.0.0 requires a peer of @tensorflow/tfjs-core@3.0.0 but none is installed. You must install peer dependencies yourself.
>npm WARN @tensorflow/tfjs-layers@3.0.0 requires a peer of @tensorflow/tfjs-core@3.0.0 but none is installed. You must install peer dependencies yourself.
>npm WARN tfjs-examples-baseball-node@0.2.0 No repository field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>+ webpack-dev-server@3.11.2
>added 4 packages from 3 contributors, removed 22 packages and updated 5 packages in 6.861s
>13 packages are looking for funding
> run `npm fund` for details
>fixed 1 of 4 vulnerabilities in 742 scanned packages
> 1 package update for 3 vulnerabilities involved breaking changes
>  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually) 

In step 6 of the baseball example I get with the command "npm run start-server" the message:

>internal/modules/cjs/loader.js:1122
>  return process.dlopen(module, path.toNamespacedPath(filename));
>                 ^
>
>Error: Das angegebene Modul wurde nicht gefunden.
>\\?\C:\***\baseball\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
>    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>    at Module.require (internal/modules/cjs/loader.js:952:19)
>    at require (internal/modules/cjs/helpers.js:88:18)
>    at Object.<anonymous> (C:\***\baseball\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
>    at Module._compile (internal/modules/cjs/loader.js:1063:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! tfjs-examples-baseball-node@0.2.0 start-server: `node server.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the tfjs-examples-baseball-node@0.2.0 start-server script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2021-02-03T08_34_40_401Z-debug.log`

I've tried to solve this issue by:

- replacing python 3.* with python 2.7 
- starting the command line as administrator
- using rebuild commmand 
etc. 

But I always get the same error. 

I'm using node v14.15.4, npm 6.14.10 on Windows 10.

It would be very nice, if somebody could tell me, what I've did wrong and maybe how to fix it, because I can't identify the problem.

**Comment by rthadur** [comment]
@NiklasRosar can you try `npm rebuild @tensorflow/tfjs-node build-addon-from-source` ?

**Comment by NiklasRosar** [comment]
Thank you very much for your answer. 
Unfortunately, the approach doesn't work for me. 
Again I get error, when I try to use the command >npm run start-server

> tfjs-examples-baseball-node@0.2.0 start-server C:\***\baseball
> node server.js
>
>internal/modules/cjs/loader.js:1122
  >return process.dlopen(module, path.toNamespacedPath(filename));
>                 ^
>
>Error: Das angegebene Modul wurde nicht gefunden. [Module not found]
>\\?\C:\***\baseball\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
>    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>    at Module.require (internal/modules/cjs/loader.js:952:19)
>    at require (internal/modules/cjs/helpers.js:88:18)
>    at Object.<anonymous> (C:\***\baseball\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
>    at Module._compile (internal/modules/cjs/loader.js:1063:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! tfjs-examples-baseball-node@0.2.0 start-server: `node server.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the tfjs-examples-baseball-node@0.2.0 start-server script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2021-02-04T09_14_57_633Z-debug.log

I want to share the complete log of this run: 

>0 info it worked if it ends with ok
>1 verbose cli [
>1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
>1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
>1 verbose cli   'run',
>1 verbose cli   'start-server'
>1 verbose cli ]
>2 info using npm@6.14.10
>3 info using node@v14.15.4
>4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
>5 info lifecycle tfjs-examples-baseball-node@0.2.0~prestart-server: tfjs-examples-baseball-node@0.2.0
>6 info lifecycle tfjs-examples-baseball-node@0.2.0~start-server: tfjs-examples-baseball-node@0.2.0
>7 verbose lifecycle tfjs-examples-baseball-node@0.2.0~start-server: unsafe-perm in lifecycle true
>8 verbose lifecycle tfjs-examples-baseball-node@0.2.0~start-server: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\***\baseball\node_modules\.bin;C:\Users\***\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python27;C:\Program Files\nodejs\;C:\texlive\2019\bin\win32\;C:\Users\***\AppData\Local\Microsoft\WindowsApps;C:\Users\***\AppData\Local\GitHubDesktop\bin;C:\Users\***\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\***\AppData\Local\Programs\Git\cmd;C:\Users\***\AppData\Roaming\npm
>9 verbose lifecycle tfjs-examples-baseball-node@0.2.0~start-server: CWD: C:\Users\***\baseball
>10 silly lifecycle tfjs-examples-baseball-node@0.2.0~start-server: Args: [ '/d /s /c', 'node server.js' ]
>11 silly lifecycle tfjs-examples-baseball-node@0.2.0~start-server: Returned: code: 1  signal: null
>12 info lifecycle tfjs-examples-baseball-node@0.2.0~start-server: Failed to exec start-server script
>13 verbose stack Error: tfjs-examples-baseball-node@0.2.0 start-server: `node server.js`
>13 verbose stack Exit status 1
>13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
>13 verbose stack     at EventEmitter.emit (events.js:315:20)
>13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
>13 verbose stack     at ChildProcess.emit (events.js:315:20)
>13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
>13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
>14 verbose pkgid tfjs-examples-baseball-node@0.2.0
>15 verbose cwd C:\Users\***\baseball
>16 verbose Windows_NT 10.0.17763
>17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-server"
>18 verbose node v14.15.4
>19 verbose npm  v6.14.10
>20 error code ELIFECYCLE
>21 error errno 1
>22 error tfjs-examples-baseball-node@0.2.0 start-server: `node server.js`
>22 error Exit status 1
>23 error Failed at the tfjs-examples-baseball-node@0.2.0 start-server script.
>23 error This is probably not a problem with npm. There is likely additional logging output above.
>24 verbose exit [ 1, true ]

May another approach will solve this problem?
