### ISSUE TITLE
Unhandled Rejection (TypeError): Unknown op 'TensorListFromTensor'

### ISSUE THREAD

**Issue by NSTiwari** [tensorflow/tfjs#4638]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes, I referred the following GitHub repo: https://github.com/hugozanini/TFJS-object-detection/blob/master/src/index.js
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): !pip install tensorflowjs[wizard]
- TensorFlow.js version (use command below): 3.0.0
- Browser version: Chrome 88.0.4
- Tensorflow.js Converter Version: 3.0.0

**Describe the current behavior**
The web app crashes when the webcam turns ON.

**Describe the expected behavior**
The browser should be able to detect cartoon shown from the web cam.

**Standalone code to reproduce the issue**
https://github.com/NSTiwari/TFJS-Custom-Object-Detection/blob/main/src/index.js

![tfjs](https://user-images.githubusercontent.com/37960279/106920534-324e9000-6731-11eb-90f0-0d5c8325375f.png)

**Comment by rthadur** [comment]
In the package.json it still uses 1.74 version of tfjs , can you try updating to latest version ? Thank you

**Comment by rthadur** [comment]
Also the above mentioned op is added in latest versions , please refer the PR here https://github.com/tensorflow/tfjs/pull/3432

**Comment by nimishdesai1989** [comment]
Hello All. I have ensured I am using the latest version of the tfjs and tfsj-converter. I still get the same error.

below are my dependencies added

"dependencies": {
    "@tensorflow/tfjs": "^3.8.0",
    "@tensorflow/tfjs-converter": "^3.8.0",
    "@tensorflow/tfjs-core": "^3.8.0",
    "@tensorflow/tfjs-node": "^1.7.4",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-magic-dropzone": "1.0.1",
    "react-scripts": "2.0.3"
  },

Is there any way I can solve this ? I have followed the tutorial from tensorflow blog https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html

Any help is appreciated as I dont know what to do next.

**Comment by Amonsalvek** [comment]
Were you able to solve this?
I have the same exact problema, tried TensorFlow 2.4.0 as per Hugo Zanini's model.json shows but still the same error.
TensorListFromTensor is obsolete and will be removed, yet it should still be working to date....

**Comment by Amonsalvek** [comment]
Brief update, tried using TF converter 2.8.0, same exact error (2.8.0 is the one used in the tutorial).
Then updated to 3.18.0 (this time through Colab) and the error now change to

Unknown op 'TensorListReserve'

Same exact behaviour as NSTiwari, the web app crashes when the webcam turns ON, and the error occurs when the function _model.executeAsync_ is called.


Please any help on this issue?

**Comment by mtrucc** [comment]
> Brief update, tried using TF converter 2.8.0, same exact error (2.8.0 is the one used in the tutorial). Then updated to 3.18.0 (this time through Colab) and the error now change to
> 
> Unknown op 'TensorListReserve'
> 
> Same exact behaviour as NSTiwari, the web app crashes when the webcam turns ON, and the error occurs when the function _model.executeAsync_ is called.
> 
> Please any help on this issue?

I had the same problem, but I found that with other model files (before Jan 2021) it worked fine.
