### ISSUE TITLE
Facing issue when run PoseNet on my local

### ISSUE THREAD

**Issue by AdnanLatif** [tensorflow/tfjs#464]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Describe the problem or feature request
I cloned tfjs-models from git. When I run on my local it throws an error. I also added
<script src="https://unpkg.com/@tensorflow/tfjs"></script>
<script src="https://unpkg.com/@tensorflow-models/posenet"></script>
into camera.html but when I run it throws an error into console

Uncaught SyntaxError: Unexpected token *

cause of error is take me to the line

`import * as posenet from '@tensorflow-models/posenet';`

When I run from https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html I go to view source and I copied code from js which is located at bottom and change code into camera.js than its working but this is more than 2000 lines of code and its not a good approach. Seeking help regarding this issue.
I am using windows 10 64 bit.

**Comment by nsthorat** [comment]
@AdnanLatif, what's happening is you need a bundler to run the code inside the PoseNet example, you can't just run the code directly in the browser. Have you tried running "yarn" and "yarn build" inside the PoseNet example to build it?

You can also use PoseNet directly via unpkg using a bundle (without yarn)
```
<script src="https://unpkg.com/@tensorflow/tfjs"></script>
<script src="https://unpkg.com/@tensorflow-models/posenet"></script>
```

And then you can write your own application that uses the PoseNet API.

Hope this helps.

**Comment by yucolabjames** [comment]
Am running into the same problem, am wondering if OP managed to solve it eventually. I did a `yarn` and `yarn build` in the posenet folder and it created a dist folder but the HTML is still complaining about:

```
camera.html:1 Uncaught TypeError: Failed to resolve module specifier "@tensorflow-models/posenet". Relative references must start with either "/", "./", or "../".
```
