### ISSUE TITLE
Memory leak in MomentumOptimizer

### ISSUE THREAD

**Issue by jo-fra** [tensorflow/tfjs#4647]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): React Native (Expo)
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs-core
- TensorFlow.js version (use command below): 3.0.0

**Describe the current behavior**
Calling dispose() on MomentumOptimizer does not free memory.
**Describe the expected behavior**
Calling dispose() should free all memory.
**Standalone code to reproduce the issue**
```
const optimizer = new tfc.MomentumOptimizer(0.001, 0.9);
optimizer.dispose();
console.log(tfc.memory());
```
Reports that there is still one tensor in memory:
```
Object {
  "numBytes": 4,
  "numBytesInGPU": 0,
  "numBytesInGPUAllocated": 0,
  "numBytesInGPUFree": 0,
  "numDataBuffers": 1,
  "numTensors": 1,
  "unreliable": false,
}
```

**Other info / logs**
When I use another optimizer e.g. SGD and call dispose() all memory is freed. 
```
const optimizer = new tfc.SGDOptimizer(0.001);
optimizer.dispose();
console.log(tfc.memory());
```
```
Object {
  "numBytes": 0,
  "numBytesInGPU": 0,
  "numBytesInGPUAllocated": 0,
  "numBytesInGPUFree": 0,
  "numDataBuffers": 0,
  "numTensors": 0,
  "unreliable": false,
}
```

**Comment by rthadur** [comment]
https://github.com/tensorflow/tfjs-core has been archived, please use this repo https://github.com/tensorflow/tfjs and let us know if the issue still persists. Thank you.
