### ISSUE TITLE
Support complex64 input in tf.transpose

### ISSUE THREAD

**Issue by JPery** [tensorflow/tfjs#4649]
**System information**
- TensorFlow.js version (you are using): 3.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Support complex64 input in tf.transpose

**Will this change the current api? How?**

It will support the tf.transpose operation instead of throwing the error "GPGPUProgram does not support complex64 input", as seen at #4507

**Who will benefit with this feature?**

Everyone that needs to work with tf.transpose and complex64, f.e. trasposing the output of a STFT operation.

**Any Other info.**

Creating this issue as @pyu10055 asked me to in #4507. Also, this feature will close that issue.

**Comment by DCtheTall** [comment]
I'd be interested in writing a PR for this if the owners are open to it.

**Comment by rthadur** [comment]
@JPery you are welcome to contribute, please submit a PR. Thank you

**Comment by DCtheTall** [comment]
I think you tagged the issue author instead of me, so unless you say otherwise I can get started 😄

**Comment by rthadur** [comment]
ahh sorry, @DCtheTall please submit a PR. Thank you so much

**Comment by DCtheTall** [comment]
@rthadur since we are dealing with complex numbers, does `tf.transpose` simply transpose complex matrices without changing any values, or do we take the conjugate transpose?

**Comment by rthadur** [comment]
@ahmedsabie could you please help with above comments . Thank you

**Comment by JPery** [comment]
In the (official docs)[https://www.tensorflow.org/api_docs/python/tf/transpose] there is an optional parameter "conjugate" that tells the function if the values of the tensor are conjugated and transposed.

**Comment by DCtheTall** [comment]
Thanks @JPery I'll be sure to add support for both options in the PR.

**Comment by DCtheTall** [comment]
@rthadur I implemented it using higher level ops instead of at the backend level. @JPery let me know if this is what you had in mind.

**Comment by DCtheTall** [comment]
Refer to the 2nd PR, due to a git fail I borked the first PR

**Comment by JPery** [comment]
I think your PR should be compatible with 'complex128' dtype just changing line 76 to:

`if ($x.dtype === 'complex64' || $x.dtype === 'complex128' ) {`

Do you agree, @DCtheTall ?

**Comment by DCtheTall** [comment]
@JPery looks like complex128 is not actually supported by TensorFlow.js: https://github.com/tensorflow/tfjs/blob/38f8462fe642011ff1b7bcbb52e018f3451be58b/tfjs-core/src/types.ts#L40

**Comment by DCtheTall** [comment]
@rthadur now that #6410 has landed, I think we can close this? @JPery I don't think complex128 is in scope for this issue since that would involve adding support for a whole new dtype to TFJS.

**Comment by rthadur** [comment]
Thank you so much @DCtheTall for contributing , changes will available in next release meanwhile you can get changes from tfjs repo.
