### ISSUE TITLE
PoseNetJS (intermediate value)(intermediate value).resizeBilinear is not a function

### ISSUE THREAD

**Issue by hentschelpatrick** [tensorflow/tfjs#4653]
We've been using PoseNetJS in our angular project since November 2020, everything worked fine until thursday last week, where suddenly our pose estimation stopped working everytime the call on 
```posenet.estimateSinglePosition(videoElement)``` was made. 

Running through the debugger every element is defined and we are running on the latest version ```^2.2.1```

```JavaScript
async poseDetectionFrame(
		video: HTMLVideoElement,
		canvas: HTMLCanvasElement,
		net: PoseNet,
		ctx: CanvasRenderingContext2D,
		width: number,
		height: number
	) {
		const pose: Pose = await net.estimateSinglePose(video);
		this.poses.push(pose);
                 .
                 .
                 .
}
````

The error shown in the console shows the following:
```JavaScript
ERROR Error: Uncaught (in promise): TypeError: (intermediate value)(intermediate value).resizeBilinear is not a function
TypeError: (intermediate value)(intermediate value).resizeBilinear is not a function
    at posenet.esm.js:17
    at tfjs-core:17
    at e.scopedRun (tfjs-core:17)
    at e.tidy (tfjs-core:17)
    at tidy (globals.js:175)
    at padAndResizeTo (posenet.esm.js:17)
    at e.<anonymous> (posenet.esm.js:17)
    at posenet.esm.js:17
    at Object.next (posenet.esm.js:17)
    at posenet.esm.js:17
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27504)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27492)
```

Does anyone have an idea what is going wrong?

**Comment by rthadur** [comment]
@hentschelpatrick i tried the latest posenet model from https://github.com/tensorflow/tfjs-models/tree/master/posenet which uses 3.0.0-rc.1 it was working fine , can you try updating to latest version explicitly in package.json ?

**Comment by joshuatz** [comment]
@rthadur I'm running into the same issue as OP, and wanted to try your suggestion, but... am I missing something, or did the posenet package update not get pushed to the NPM registry?

Looking at the last update to the posenet model, the semver was never bumped, and NPM still has the old code. (I don't think this is the only model that has been updated for v3 and not pushed to the registry either - [see similar comment](https://github.com/tensorflow/tfjs/issues/4656)).

Also, this issue goes away if I downgrade `tfjs` and `tfjs-backend-webgl` to the pre-v3 release (`2.8.5` for both), so I'm guessing this is indeed an incompatibility issue for `2.2.1` against v3.

**Comment by frankl1** [comment]
Hello,
I am facing the same issue. Downgrading tfjs and tfjs-backend-webgl does not fix the problem.
@rthadur  I upgraded tfjs to 3.0.0-rc.1, but I don't know where to find  posenet@3.0.0-rc.1. How did you manage to get that version of posenet ?

**Comment by denys-havryliv** [comment]
Hello, 

Have the same issue. PoseNetJS (intermediate value)(intermediate value).resizeBilinear is not a function. Can you please investigate the problem? I have used the latest packages and I think the problem is in the package posenet(which was not updated on npm(.2.1 • Public • Published a year ago). Built project from demo works fine, but if you install via npm without yarn yalc, the code does not run.

@tensorflow/tfjs-backend-webgl": ^3.0.0-rc.1
@tensorflow/tfjs-converter": ^3.0.0-rc.1
@tensorflow/tfjs-core": ^3.0.0-rc.1

**Comment by frankl1** [comment]
After many searches and tries of different versions, it is working for me now with the latest version on npm. I cannot explain what happened.

Here are my dependencies:
@tensorflow-models/posenet": "^2.2.1",
@tensorflow/tfjs-backend-webgl": "^2.8.6",
@tensorflow/tfjs-node": "^2.8.6",

**Comment by RobinDeBaets** [comment]
Having the same problem over here.

**Comment by hentschelpatrick** [comment]
same problem with 


"@tensorflow-models/posenet": "^2.2.1",
"@tensorflow/tfjs-backend-webgl": "^3.2.0",
"@tensorflow/tfjs-converter": "^3.2.0",
"@tensorflow/tfjs-core": "^3.2.0",

**Comment by scriptify** [comment]
Same problem here with the following package version combination:

```bash
"@tensorflow-models/posenet": "^2.2.1",
"@tensorflow/tfjs-backend-webgl": "^3.3.0",
"@tensorflow/tfjs-converter": "^3.3.0",
"@tensorflow/tfjs-core": "^3.3.0",
```

**Comment by jinjingforever** [comment]
I pushed a new version (2.2.2) that should work with tfjs 3.x. Please give it a try. Thanks!

**Comment by sigurdbuchberger** [comment]
> I pushed a new version (2.2.2) that should work with tfjs 3.x. Please give it a try. Thanks!

Thank you!! resolved it for me :)
