### ISSUE TITLE
GitHub Policy link in issue template points to a deleted file.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [tensorflow/tfjs#4658]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

The policy link above points to a deleted file. The templates in the [tensorflow repo](https://github.com/tensorflow/tensorflow/search?q=issues.md) also have this problem. I'd fix it, but I can't see the commit that deleted the file without cloning tensorflow.

**Comment by pyu10055** [comment]
@rthadur Can you help to fix the broken links. thanks!

**Comment by rthadur** [comment]
Sure @pyu10055

**Comment by rthadur** [comment]
@phoenix-meadowlark do you have correct link for the Github policy.

**Comment by phoenix-meadowlark** [comment]
I had tensorflow sitting in a submodule, so:

```shell
git log  -1 -- ISSUES.md
# da0884c7d4e7322f9c8dd9affa816dfce8759488
```

This PR should have updated all references: https://github.com/tensorflow/tensorflow/commit/da0884c7d4e7322f9c8dd9affa816dfce8759488. The new path is:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/opensource_only/ISSUES.md

**Comment by rthadur** [comment]
got it , thank you will update in tfjs , do you want me to update in tensorflow core as well ?

**Comment by phoenix-meadowlark** [comment]
I looked at the internal change and `tensorflow/opensource_only` isn't actually supposed to exist in open source.... How fun. You were already doing the right thing. I'll go fix it.

**Comment by rthadur** [comment]
sure , thank you

**Comment by phoenix-meadowlark** [comment]
fixed in https://github.com/tensorflow/tensorflow/commit/556ab089ea32328845cee36c1745aa931d1e88ac
