### ISSUE TITLE
[Feature] Auto check for version compatibility when individual package is loaded

### ISSUE THREAD

**Issue by phoenix-meadowlark** [tensorflow/tfjs#4659]
**System information**
Browser: Chrome `88.0.4324.96`
OS: macOS `10.15.7`

Copying and pasting the [Via a script tag](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md#via-a-script-tag) section of the WASM readme throws the following errors:

```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.4.0/dist/tf.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
<script>tf.setBackend('wasm').then(() => {});</script>
```

```
kernel_registry.ts:111 Uncaught Error: The kernel 'undefined' for backend 'wasm' is already registered
    at Object.c [as registerKernel] (kernel_registry.ts:111)
    at register_all_kernels.ts:200
    at tf-backend-wasm.js:20
    at tf-backend-wasm.js:21
```

```
engine.ts:235 Uncaught (in promise) Error: Backend name 'wasm' not found in registry
    at t.<anonymous> (engine.ts:235)
    at tf.min.js:2
    at Object.next (tf.min.js:2)
    at tf.min.js:2
    at new Promise (<anonymous>)
    at r (tf.min.js:2)
    at t.setBackend (engine.ts:233)
    at Object.t.setBackend (globals.ts:276)
    at index.html:3
```

**Comment by vladmandic** [comment]
you're force-loading `tfjs` 1.4.0 while `wasm` is loaded without version string, so defaults to latest 3.0.0 - no chance those two can work together.

**Comment by phoenix-meadowlark** [comment]
Ah, that makes sense, thanks! Is there a way to catch that incompatible versions of `tfjs*` are being used and surface an error that reflects that?

**Comment by pyu10055** [comment]
@phoenix-meadowlark That is a great idea, we will look into that.

**Comment by gaikwadrahul8** [comment]
Hi, @phoenix-meadowlark 

Apologize for the delayed response and we are re-visiting our older feature request issues and checking whether those feature requests implemented or not as of now and I was able to replicate the same issue and still I'm getting same error and in previous comment @vladmandic explained the reason for that error and for feature Auto check for version compatibility when individual package is loaded It seems like we haven't implemented as of now if I'm not wrong, If this feature haven't implemented as of now then May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

[[Feature] ](https://github.com/tensorflow/tfjs/issues/4659#top)




![image](https://user-images.githubusercontent.com/115997457/236122287-afc1eec7-e620-4df6-9244-87747fe7979d.png)
