### ISSUE TITLE
Broken tensor on specific GPU

### ISSUE THREAD

**Issue by chirva-ivan** [tensorflow/tfjs#4660]
**System information**
- Have I written custom code: https://codesandbox.io/s/tfjs-unstack-issue-loz5r?file=/src/index.js
- OS Platform and Distribution: 
Windows 10
GPU:
![GL_vendor_GL_renderer](https://user-images.githubusercontent.com/18259976/107361735-e6149e80-6ae8-11eb-9577-59014b600410.PNG)
WebGL:
![gpu](https://user-images.githubusercontent.com/18259976/107361777-f3ca2400-6ae8-11eb-84d8-b6cca5c19b48.PNG)

- TensorFlow.js version: 3.0.0
- Browser version: Chrome 88.0.4324.146

**Describe the current behavior**
With WebGL backend this code returns broken tensor:
```
  const frameSourceRaw = tf.tensor3d(
    new Int32Array(Array(128 * 224 * 4).fill(225)),
    [128, 224, 4],
    "int32"
  );
  const unstacked = tf.unstack(frameSourceRaw, -1);
  unstacked.forEach((a) => a.print());
```
 is printed:
```
    [[225, 225, 225, ..., 225, 225, 225],
     [225, 225, 225, ..., 225, 225, 225],
     [225, 225, 225, ..., 225, 225, 225],
     ...,
     [0  , 0  , 0  , ..., 0  , 0  , 0  ],
     [0  , 0  , 0  , ..., 0  , 0  , 0  ],
     [0  , 0  , 0  , ..., 0  , 0  , 0  ]]
```
while frameSourceRaw is correct.
This behavior does not appear only after `unstacked` operation, but also after other (`slice`, `div`).
More examples: https://codesandbox.io/s/tfjs-unstack-issue-loz5r?file=/src/index.js

![01](https://user-images.githubusercontent.com/18259976/107363699-8cfa3a00-6aeb-11eb-8857-209c27465c01.png)
![tenserflow](https://user-images.githubusercontent.com/18259976/107363735-9d121980-6aeb-11eb-91e7-44df312375f0.PNG)

Zeros appear after 65536 (2^16) element.
With CPU backend or with other GPU or with other array dimensions (eg. 144 * 256) output tensor is correct.

**Comment by pyu10055** [comment]
@chirva-ivan can you try [this page](https://js.tensorflow.org/debug/), and share screenshot of the output? thanks

**Comment by chirva-ivan** [comment]
@pyu10055 

![tenserflow](https://user-images.githubusercontent.com/18259976/107614289-12e8c300-6c5b-11eb-9071-0a5d23a85382.png)

**Comment by pyu10055** [comment]
Looks like the tensor texture might be exceeding the max texture limit 16384, which translate to 16384 * 4 = 65536, since we are packing the tensor into 4 channels of the texture. Can you try to disable the packing and see if the 0 values appears at 1/4 of the size.

```
tf.env().set('WEBGL_PACK', false)
```

**Comment by chirva-ivan** [comment]
@pyu10055 

`tf.env().set('WEBGL_PACK', false)`

That helped, thanks a lot!

![001](https://user-images.githubusercontent.com/18259976/107949821-e4dee800-6fa6-11eb-9fac-86040abbd273.png)

Does this option affect performance in any way?

**Comment by pyu10055** [comment]
@chirva-ivan This is interesting, actually I did not expect this would help. @annxingyuan Seems packing is causing the 0 values in a tensor, any quick thoughts on what could be the reason? thanks.
