### ISSUE TITLE
Unable to resolve module `crypto` from `node_modules/@tensorflow/tfjs/dist/tf.node.js`: crypto could not be found within the project

### ISSUE THREAD

**Issue by gaurav8809** [tensorflow/tfjs#4661]
Can anyone please help me with this.

I have react native cli project and not expo.

I installed all required packages 

- react-native-unimodules
- expo-gl-cpp and expo-gl
- expo-camera
- async-storage
- react-native-fs

![Simulator Screen Shot - iPhone 11 - 2021-02-09 at 18 59 36](https://user-images.githubusercontent.com/59197887/107370419-f63c7600-6b08-11eb-980a-936967ef2d55.png)

**Comment by rthadur** [comment]
@gaurav8809 can you please check a similar issue here related to nodejs https://github.com/tensorflow/tfjs/issues/3354

**Comment by gaurav8809** [comment]
> @gaurav8809 can you please check a similar issue here related to nodejs #3354

I just checked 
But I can not find any solution related this issue

**Comment by rthadur** [comment]
did you try deleting node modules ? can you please share code to reproduce in a git repo , thank you

**Comment by CristiakaWar** [comment]
same issue here, just followed the setup info from "https://www.npmjs.com/package/@tensorflow/tfjs-react-native", I'm running expo SDK 40 and the latest versions of the dependent packages

**Comment by gaurav8809** [comment]
> did you try deleting node modules ? can you please share code to reproduce in a git repo , thank you

I resolved my issue anyhow
Build getting successful for iOS but in android getting issue with this @react-native-community/cameraroll

![Screenshot 2021-02-11 at 3 55 31 PM](https://user-images.githubusercontent.com/59197887/107624944-95847900-6c81-11eb-888f-fcecc611de07.png)

Please help me out with it
