### ISSUE TITLE
incorrect values when creating a tensor.

### ISSUE THREAD

**Issue by ELI7VH** [tensorflow/tfjs#4662]
using tfjs-node to put together some tensors, and I get incorrect data in my sets. 

here is my code:
```
const x_vals = this.stats.frames.map((f) => f.t).slice(0, 4)
const y_vals = this.stats.frames.map((f) => f.p).slice(0, 4)

const x = tf.tensor(x_vals)
const y = tf.tensor(y_vals)

const nx = x.sub(x.min()).div(x.max().sub(x.min()))
const ny = y.sub(y.min()).div(y.max().sub(y.min()))

return [
  x_vals,
  x.arraySync(),
  nx.arraySync(),
  y_vals,
  y.arraySync(),
  ny.arraySync(),
]
```
here is the response:
```
[
    [
        1612892067115,
        1612892067089,
        1612892066967,
        1612892066783
    ],
    [
        1612892078080,
        1612892078080,
        1612892078080,
        1612892078080
    ],
    [
        null,
        null,
        null,
        null
    ],
    [
        0.0706483,
        0.0706052,
        0.0706,
        0.0706589
    ],
    [
        0.07064829766750336,
        0.07060520350933075,
        0.0706000030040741,
        0.07065889984369278
    ],
    [
        0.8199873566627502,
        0.08829854428768158,
        0,
        1
    ]
]
```

as you can see the derivatives if the x_vals is wrong. 

the numbers in the tensor itself seem to be totally incorrect, and then when trying to normalize these numbers, it's just returns null..

hope somebody can point out what I am doing wrong

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ELI7VH** [comment]
@rthadur it's not a bug? But the numbers it creates are completely incorrect. Would you mind clarifying?

**Comment by ELI7VH** [comment]
@rthadur here is another test case.

### Inputs
```
    [
        56754.515,
        56754.498,
        56754.466,
        56754.399,
        56754.325,
        56754.307
    ],
 ```
 
### Output Tensor Values
 ```
    [
        56754.515625,
        56754.49609375,
        56754.46484375,
        56754.3984375,
        56754.32421875,
        56754.30859375
    ],
 ```
 
 Is this still not a bug?

**Comment by pyu10055** [comment]
@ELI7VH Looks like there are some precision loss in the tensor, but it is expected for WebGL backend, we would need more information to analyze this bug. Can you provide a simple tfjs-node code example to reproduce the problem. thanks.
