### ISSUE TITLE
speech-command Unable to load the model using ensureModelLoaded

### ISSUE THREAD

**Issue by adotnusiyan** [tensorflow/tfjs#4667]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.0.0
- Browser version: Version 88.0.4324.150 (Official Build) (x86_64)

**Describe the current behavior**
Error when trying to load the model using `ensureModelLoaded` method:
`Uncaught (in promise) Error: No backend found in registry.`

**Describe the expected behavior**
Expected to load the model.

**Standalone code to reproduce the issue**
[Example in Codesandbox](https://codesandbox.io/s/tfjs-listen-recognize-scores-iyrjd)

**Other info / logs**
It was working fine in `speech-command` **0.4.2**, but faced this issue after using the latest version **0.5.1**

Full error:
```
Uncaught (in promise) Error: No backend found in registry.
    at ut.getSortedBackends (speech-commands.esm.js:17)
    at ut.initializeBackendsAndReturnBest (speech-commands.esm.js:17)
    at ut.get backend [as backend] (speech-commands.esm.js:17)
    at ut.makeTensor (speech-commands.esm.js:17)
    at Ss (speech-commands.esm.js:17)
    at Po.apply (speech-commands.esm.js:17)
    at Sh.addWeight (speech-commands.esm.js:17)
    at Sh.build (speech-commands.esm.js:17)
    at speech-commands.esm.js:17
    at ho (speech-commands.esm.js:17)
    at Sh.apply (speech-commands.esm.js:17)
    at $u.add (speech-commands.esm.js:17)
    at fromConfig (speech-commands.esm.js:17)
    at _a (speech-commands.esm.js:17)
    at Ml (speech-commands.esm.js:17)
    at speech-commands.esm.js:17
```

**Comment by rthadur** [comment]
@adotnusiyan can you please check a similar issue here https://github.com/tensorflow/tfjs/issues/3811 , thank you

**Comment by adotnusiyan** [comment]
@rthadur 

The issue you linked is not resolved 

And I already did what @pyu10055 suggested in that issue and still getting the error 


You can check the example I provided. If you downgrade speech-command to version 0.4.2 it works, but if you use version 0.5.1 it doesn't

**Comment by pyu10055** [comment]
@adotnusiyan please add this line to your app.tsx file, this would ensure backends are loaded.

```
import * as tf from '@tensorflow/tfjs';
```

**Comment by adotnusiyan** [comment]
@pyu10055 
Still getting the same error.

Did you try adding the line in the example and worked?

**Comment by pyu10055** [comment]
Look like it might have been treeshaked, here what I did:

```
import React from "react";
import * as tf from "@tensorflow/tfjs";
import * as speechCommands from "@tensorflow-models/speech-commands";
import { useState } from "react";

console.log(tf.engine().backend);
```

**Comment by adotnusiyan** [comment]
@pyu10055 

Thank you. It worked after adding this line
`console.log(tf.engine().backend);`

Could you please explain what does it do?

Is this a temporary fix? Or do I have to always use it before loading the model for version 0.5.1?

**Comment by rthadur** [comment]
Here is the link which explains why we need add https://github.com/tensorflow/tfjs/releases/tag/tfjs-v2.0.0 

thank you
