### ISSUE TITLE
face-landmarks-detection model caching bounding boxes from previous predictions

### ISSUE THREAD

**Issue by lmiguelmh** [tensorflow/tfjs#4668]
First I want to thank you for the wonderful work you do.

I am using the [face-landmarks-detection model](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection). The model is fast and accurate and it works well when using it on a page via a webcam.

The problem I am experiencing is because I am not using a webcam but single images with different sizes that are feeded to the model. From what I've seen my issue is similar to this issue: [facelandmarks-detection wrong when image dimensions change](https://github.com/tensorflow/tfjs/issues/4131). As it is stated by @yann86 on the referenced issue a solution will be to:

```
model.pipeline.regionsOfInterest = []
```

But that can't be done because `pipeline` is marked as private on `FaceMesh` class (same with `regionsOfInterest` on `Pipeline` class).

https://github.com/tensorflow/tfjs-models/blob/a206fe1fdc1465000a5579db8960e85c7bb032ef/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L250-L251
```
class FaceMesh implements MediaPipeFaceMesh {
  private pipeline: Pipeline;
```

So after a bit of researching I think a better solution will be to set the configuration parameter `maxContinuousChecks` to `0` at the moment of loading the model. 

https://github.com/tensorflow/tfjs-models/blob/a206fe1fdc1465000a5579db8960e85c7bb032ef/face-landmarks-detection/src/index.ts#L34-L55
```
/**
 * Load face-landmarks-detection.
 ...
 * @param config - a configuration object with the following properties:
 *  - `maxContinuousChecks` How many frames to go without running the bounding
 * box detector. Only relevant if maxFaces > 1. Defaults to 5.
 ...
 */
export async function load(
``` 

As it is stated on the comment this parameter set the number of "frames to go without running the bounding box detector", after reviewing the code that updates these ROIs it should work.

https://github.com/tensorflow/tfjs-models/blob/a206fe1fdc1465000a5579db8960e85c7bb032ef/facemesh/src/pipeline.ts#L266-L276
```
  shouldUpdateRegionsOfInterest(): boolean {
    const roisCount = this.regionsOfInterest.length;
    ...
    return roisCount !== this.maxFaces &&
        this.runsWithoutFaceDetector >= this.maxContinuousChecks;
  }
```

But the issue is still there and I think that is because in the function `updateRegionsOfInterest` the new bounding boxes aren't updated because old ones are overlapped (IOU rate is less than 0.25). So I think a possible solution will be to add a parameter for this IOU rate (`UPDATE_REGION_OF_INTEREST_IOU_THRESHOLD`) or a flag to force the bounding boxes to invalidate.

https://github.com/tensorflow/tfjs-models/blob/a206fe1fdc1465000a5579db8960e85c7bb032ef/facemesh/src/pipeline.ts#L223-L255
```
  // Updates regions of interest if the intersection over union between
  // the incoming and previous regions falls below a threshold.
  updateRegionsOfInterest(boxes: Box[]) {
    for (let i = 0; i < boxes.length; i++) {
      const box = boxes[i];
      const previousBox = this.regionsOfInterest[i];
      let iou = 0;
      ...
      if (iou < UPDATE_REGION_OF_INTEREST_IOU_THRESHOLD) {
        this.regionsOfInterest[i] = box;
      }
    }
    ...
  }
```

A workaround is to feed the model with an EMPTY image before every call to estimateFaces to force an invalidation of the cache of bounding boxes.

```
    model = await faceLandmarksDetection.load(
      faceLandmarksDetection.SupportedPackages.mediapipeFacemesh,
      {
        maxContinuousChecks: 0,
      }
    );
    ...
    const EMPTY: tf.Tensor3D = tf.zeros([128, 128, 3]);
    await model.estimateFaces({input: EMPTY});  // force invalidation of cache of bounding boxes
    let predictions = await model.estimateFaces({
        input: imageAsTensor3D
      }
    );
```

**Comment by mattsoulanille** [comment]
Hi @lmiguelmh. Thanks for the detailed report!

It looks like you've put a good amount of research into this problem, and your idea of adding a parameter to adjust the region of interest iou threshold looks like a good solution. Would you like to make a PR implementing that change?

**Comment by lmiguelmh** [comment]
Oh, thank you. 
I'll do it and keep you guys updated.

**Comment by lmiguelmh** [comment]
Ok, I've commit the PR: [Adding a parameter to control the update behaviour of face bounding boxes from previous predictions on face-landmarks-detection](https://github.com/tensorflow/tfjs-models/pull/584). The local tests were successful as can be seen on these images:

```
    model = await faceLandmarksDetection.load(
      faceLandmarksDetection.SupportedPackages.mediapipeFacemesh,
      {
        maxContinuousChecks: 0,
        boundingBoxUpdateRoiIouThreshold: 1.0,  // update *all* face bounding boxes
      }
    );
    ...
    let predictions = await model.estimateFaces({
        input: imageAsTensor3D
      }
    );
    // draw landmarks and immediately predict another image of different size
    ...
    let predictions2 = await model.estimateFaces({
        input: image2AsTensor3D
      }
    );
    // draw landmarks
```

![image](https://user-images.githubusercontent.com/3931964/107864351-66107080-6e29-11eb-8a1e-e6e5914a0791.png)

And this will be the result if using the default value of `0.25` for `boundingBoxUpdateRoiIouThreshold`:

![image](https://user-images.githubusercontent.com/3931964/107864454-36ae3380-6e2a-11eb-9c69-ed66da890417.png)

**Comment by mattsoulanille** [comment]
Bumping to keep this open. There appears to be a discrepancy between tfjs's implementation of face landmarks and the official model. [PR 584](https://github.com/tensorflow/tfjs/pull/4769/commits/e9530cf79b0c6df79d80b4c5896ac79a74e5d711) fixes the originally posted issue, but it's possible / likely that making sure the tfjs model matches the official model will also fix it. I'll take a look as soon as I'm able to.

**Comment by lmiguelmh** [comment]
Ok, I hope the problem is fixed by using the "official model".

**Comment by Narendra186** [comment]
> Ok, I hope the problem is fixed by using the official model.

What happened to this issue? Why isn't your PR `https://github.com/tensorflow/tfjs-models/pull/584` merged?

**Comment by Narendra186** [comment]
@lmiguelmh What happened to this issue? Why isn't your PR `https://github.com/tensorflow/tfjs-models/pull/584` merged?
