### ISSUE TITLE
tensorflow-model/posenet is not loading on expo SDK 40

### ISSUE THREAD

**Issue by gihanrangana** [tensorflow/tfjs#4669]
**System information**
- iOS, Android
- "@tensorflow-models/posenet": "^2.2.1", "@tensorflow/tfjs": "^3.0.0",

**Describe the problem**
when i try to load posenet model it's getting `[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'env().platform.fetch')]` 

 ```
let model: any = null
useEffect(() => {
    onRead();
}, []);

const onRead = useCallback(async () => {
    await tf.ready();
    setIsTFReady(true);

    model = await posenet.load();
    setIsPosnetReady(true);

}, []);
```

![image](https://user-images.githubusercontent.com/24897554/107612226-c5288680-6c6b-11eb-80be-d744495efc1c.png)

**Comment by rthadur** [comment]
@SL-CodeBlaster can you try running this test repo https://github.com/mattsoulanille/tfjs-rn-webgl-test ?

**Comment by SL-CodeBlaster** [comment]
> @SL-CodeBlaster can you try running this test repo https://github.com/mattsoulanille/tfjs-rn-webgl-test ?

tfjs is loading successfully. but when i try load posenet model getting above warning

**Comment by rthadur** [comment]
Can you please share your code in a GitHub repo , so that we can try on our end. Also please share your system configuration.

**Comment by SL-CodeBlaster** [comment]
> Can you please share your code in a GitHub repo , so that we can try on our end. Also please share your system configuration.

it's created with my company framework, i can can share package.json

`{
	"name": "lila-app",
	"version": "1.0.001",
	"scripts": {
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"metro": "react-native start",
		"web": "expo start --web --config ./app/app.json",
		"start": "expo start --config ./app/app.json",
		"publish": "expo publish --config ./app/app.json",
		"test": "jest"
	},
	"dependencies": {
		"@dex/bubl-app": "^1.0.289",
		"@tensorflow-models/mobilenet": "^2.0.4",
		"@tensorflow-models/posenet": "^2.2.1",
		"@tensorflow/tfjs": "^3.0.0",
		"@tensorflow/tfjs-react-native": "^0.5.0",
		"expo-camera": "^10.0.0",
		"expo-constants": "^10.0.1",
		"expo-gl": "^10.1.0",
		"expo-permissions": "^11.0.0",
		"jpeg-js": "^0.4.3",
		"react-native-fs": "^2.16.6"
	},
	"devDependencies": {
		"@babel/core": "~7.9.0",
		"@dex/bubl-fetch": "1.6.114",
		"@dex/bubl-helpers": "1.6.112",
		"@dex/bubl-ui": "1.0.383",
		"@react-native-community/async-storage": "^1.12.1",
		"@react-native-community/masked-view": "0.1.10",
		"@react-navigation/bottom-tabs": "^5.11.2",
		"@react-navigation/drawer": "^5.11.4",
		"@react-navigation/native": "5.8.10",
		"@react-navigation/stack": "5.12.8",
		"@types/react": "~16.9.35",
		"@types/react-css-modules": "^4.6.2",
		"@types/react-dom": "~16.9.8",
		"@types/react-native": "~0.63.2",
		"babel-plugin-react-native-classname-to-dynamic-style": "github:dex-labs/babel-plugin-react-native-classname-to-dynamic-style",
		"babel-plugin-react-native-classname-to-style": "1.2.2",
		"babel-plugin-react-native-platform-specific-extensions": "1.1.1",
		"babel-preset-expo": "~8.3.0",
		"expo": "~40.0.0",
		"expo-av": "^8.7.0",
		"expo-image-picker": "^10.0.0",
		"expo-linear-gradient": "^8.4.0",
		"expo-network": "^2.4.0",
		"expo-react-native-shadow": "^1.0.3",
		"expo-splash-screen": "^0.8.1",
		"expo-updates": "^0.4.1",
		"expo-video-player": "^1.6.1",
		"expo-web-browser": "^8.6.0",
		"jest-expo": "~40.0.0",
		"node-sass": "^5.0.0",
		"react": "16.13.1",
		"react-dom": "16.13.1",
		"react-native": "~0.63.4",
		"react-native-animation-hooks": "^1.0.1",
		"react-native-dynamic-style-processor": "^0.21.0",
		"react-native-fast-image": "8.3.4",
		"react-native-gesture-handler": "~1.8.0",
		"react-native-indicators": "0.17.0",
		"react-native-keyboard-spacer": "^0.4.1",
		"react-native-raw-bottom-sheet": "^2.2.0",
		"react-native-reanimated": "1.13.0",
		"react-native-redash": "16.0.3",
		"react-native-render-html": "^5.0.1",
		"react-native-root-toast": "3.2.1",
		"react-native-safe-area-context": "3.1.9",
		"react-native-sass-transformer": "^1.4.0",
		"react-native-screens": "~2.15.0",
		"react-native-shadow": "^1.2.2",
		"react-native-svg": "^12.1.0",
		"react-native-unimodules": "~0.12.0",
		"react-native-web": "~0.13.12",
		"react-native-webview": "^11.0.2",
		"recyclerlistview": "~3.0.0",
		"typescript": "~4.0.0"
	},
	"jest": {
		"preset": "react-native"
	}
}
`

**Comment by SL-CodeBlaster** [comment]
i have fixed that
but i have new issue now when i access to `model.estimateSinglePose` it's getting undefined

**Comment by SL-CodeBlaster** [comment]
i have passed image element like this
```
 let poses: any;
  const imageScaleFactor = 0.50;
  const flipHorizontal = false;
  const outputStride = 16;
let imageRef = useRef(null);

  poses = await model.estimateSinglePose(imageRef.current, imageScaleFactor, flipHorizontal, outputStride);
````

**Comment by phamquyhai** [comment]
> i have fixed that
> but i have new issue now when i access to `model.estimateSinglePose` it's getting undefined
hi @SL-CodeBlaster 
I have same issue. how to fix it?

**Comment by Shahanija-Inovatrik** [comment]
> i have fixed that
> but i have new issue now when i access to `model.estimateSinglePose` it's getting undefined

How did you fix it?

**Comment by shahanija** [comment]
> i have fixed that
> but i have new issue now when i access to `model.estimateSinglePose` it's getting undefined

How did you fix it?
