### ISSUE TITLE
Feature Request: tf.linalg.solve

### ISSUE THREAD

**Issue by antoniotorres** [tensorflow/tfjs#467]
Are there plans to include tf.linalg.solve as part of tensflow.js core?
Also known as: tf.matrix_solve

TF Docs: https://www.tensorflow.org/api_docs/python/tf/matrix_solve

**Comment by nsthorat** [comment]
No plans right now, but happy to take contributions!

**Comment by caisq** [comment]
@antoniotorres Just curious, what is your use case for this function?

**Comment by antoniotorres** [comment]
@caisq I'm implementing an RBF interpolation.

**Comment by kedevked** [comment]
I have just implemented a method to get the determinant of a matrix using the Jordan-Gauss method [here](https://stackoverflow.com/questions/51805389/how-do-i-invert-a-matrix-in-tensorflow-js). It can be used to solve a linear problem of A * X = B. This method here that needs to be implemented will take an array of [A, ...] matrix, [B, ...] and then will compute the array [S, ...] where each A * S = B. I will work on it

**Comment by antoniotorres** [comment]
Hey @kedevked I haven't worked on it.

**Comment by kedevked** [comment]
Thanks @antoniotorres for letting me know.  @nsthorat and @dsmilkov , could you please let us know if you have already worked on this issue ?

**Comment by nsthorat** [comment]
We have not, @kedevked! The only thing I would say is it would be good to try to mimic with TensorFlow python does in terms of API and functionality.

**Comment by kedevked** [comment]
@nsthorat thanks for your reply. I have started to implement the [Jordan Gauss method](https://en.wikipedia.org/wiki/Gaussian_elimination). As you suggested, we need to be compliant with the python version. There is an `adjoint` parameter in the signature of the method. I only need to implement that. Everything is [here](https://github.com/kedevked/tfjs-core). I will greatly appreciate your feedback as I am implementing this feature. Thanks!

**Comment by Gurpreetsingh9465** [comment]
can i work on this issue 😃

**Comment by bileschi** [comment]
Please, feel welcome to contribute!

**Comment by nsthorat** [comment]
I think we should hold off on this issue -- we're going to thinking about what a linear algebra package in JS would look like holistically.

**Comment by Gurpreetsingh9465** [comment]
@nsthorat sir, i am trying to implement linalgebra module in typescript.

these are some of the functions i decided to put in this module. sir, can you suggest some additional functions or these are enough.
1. linalg.cholesky(a)
2. linalg.svd(a[,full_matrices,compute_uv])
3. linalg.eig(a)
4. linalg.eigvals(a)
5. linalg.norm(x[,ord,axis,keepdims])
6. linalg.cond(x[,p])
7. linalg.det(a)
8. linalg.matrix_rank(M[,tol,hermitian])
9. linalg.slogdet(a)
10. trace(a[,offset,axis1,axis2,dtype,out])
11. linalg.pca(a,n_components)
12. linalg.solve(a,b)
13. linalg.tensorsolve(a,b[,axes])
14. linalg,lstsq(a,b[,rcond])
15. linalg.inv(a)
16. linalg.pinv(a[,rcond])

out of these i had implemented
1. solve
2. pca
3. inv
4. eigvals
5. det
6. slog det
7. trace
8. det

should i do a PR regarding this.  😄
