### ISSUE TITLE
tfjs_binding.node can not be found at path "...\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node"

### ISSUE THREAD

**Issue by fuzzlogdev** [tensorflow/tfjs#4676]
**System information**
Code: Baseball example at **https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab**
OS: **Windows 10 Pro 64 bit**
Tensorflow.js version: **"^1.3.2"** (as provided by code sample)
Tensorflow.js: Converter Version:  **NO IDEA** (all initial versions are derived from the sample project)
Node.js version: **12.*** (initially)
Python Version: **2.7.18**
Browser: **FireFox 85.0.2**

**Describe the current behavior**
Following the instructions in the tutorial above, Step 6 asks you to run the following line:

`npm run start-server`

This results in the following error being displayed:

`tfjs_binding.node can not be found at path "...\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node"`

I've tried the following:

- Replacing Node.Js with different version.
  -- This only changes the "napi-v" section of the error with 4,5,6 or 7 depending on the version of node (11, 12, 13, 14...)

- npm rebuild @tensorflow/tfjs-node build-addon-from-source
  -- Same result because the expected file (tfjs_binding.node) is never in the expected "napi" folder.

- Reinstalling Tensorflow.js via `npm install @tensolflow/tfjs `
  -- Still same error message

- Rebuilding tfjs-node via `npm rebuild @tensorflow/tfjs-node build-addon-from-source`
  -- Still same error message

Not sure what else can be done.  It seems obvious to me that there are internal issues with the framework, but without specific instructions how to overcome them, at this point I'm just stuck.

Please advise.

Thanks,

**Comment by pyu10055** [comment]
@fuzzlogdev I suspect you don't have python in the system, can you post the output from the following command:
```
npm install @tensolflow/tfjs
```

**Comment by fuzzlogdev** [comment]
I do have python installed in the system.  The version is 2.7.18 (as
specified when running "> python --version").

The output of npm install @tensorflow/tfjs at the specified folder is:

F:\Projects\Dev\TensorFlow\NodeJs\baseball>npm install @tensorflow/tfjs






*up to date, audited 739 packages in 1s24 packages are looking for funding
run `npm fund` for detailsfound 0 vulnerabilities*

Thanks,

fuzzlog

**Comment by pyu10055** [comment]
@fuzzlogdev We have updated tensorflow version to 2.4.1 for tfjs-node, please try again with the latest version (3.6.0). thanks
