### ISSUE TITLE
`@tensorflow/tfjs` is missing dependency on `seedrandom`

### ISSUE THREAD

**Issue by kiancross** [tensorflow/tfjs#4679]
**System information**
- TensorFlow.js installed from (npm or script link): `3.0.0`

**Describe the current behavior**

`@tensorflow/tfjs-data` has a peer dependency on `seedrandom`:
https://github.com/tensorflow/tfjs/blob/1612c9a316dd4edeea9c9ef9cd6ab029f43741b5/tfjs-data/package.json#L71

`@tensorflow/tfjs` depends on `@tensorflow/tfjs-data`, but does not provide the `seedrandom` peer dependency:

https://github.com/tensorflow/tfjs/blob/1612c9a316dd4edeea9c9ef9cd6ab029f43741b5/tfjs/package.json#L92

**Describe the expected behavior**

`@tensorflow/tfjs` should provide the `seedrandom` peer dependency for `@tensorflow/tfjs-data`.

**Comment by rthadur** [comment]
This is a duplicate , here is the similar issue opened to track the same https://github.com/tensorflow/tfjs/issues/3875 , Thank you

**Comment by kiancross** [comment]
@rthadur Are you sure this is the same issue? This is a dependency issue - not a bundling issue.

**Comment by PabloRN** [comment]
Any solution for this issue? Thx

**Comment by kiancross** [comment]
> Any solution for this issue? Thx

What package manager are you using?
