### ISSUE TITLE
Unknown op 'SparseTensorDenseMatMul' and 'SparseMatMul'

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tfjs#4681]
**System information**
- TensorFlow.js version (you are using): 3.0.0
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
I am trying to convert a TF2 saved model using [sparse_dense_matmul](https://www.tensorflow.org/api_docs/python/tf/sparse/sparse_dense_matmul) (or alternatively [matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) with `b_is_sparse=True`, but can't as tfjs does not support that yet.

**Will this change the current api? How?** The only change will be a new transformation for people to use.

**Who will benefit with this feature?**

I am using this function in my TF model to multiply a tensor from my training batch against a transformation matrix (not dissimilar from a [DFT matrix](https://en.wikipedia.org/wiki/DFT_matrix)). My transformation matrix happens to be very sparse (full of 0s in my case) and is suitable to be converted to a sparse tensor. However, I would not get the speed boost (I would get the memory boost) that comes with a sparse tensor unless I use a function like sparse_dense_matmul or sparse matmul.

Functionality like this is very useful in signal processing, particularly audio processing (my use case) where transformation matrices like this exist.

**Any Other info.**

**Comment by rthadur** [comment]
cc @ping @mattsoulanille

**Comment by gaikwadrahul8** [comment]
Hi, @drubinstein 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I seems like we haven't implemented this feature as of now so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
