### ISSUE TITLE
Error: TensorList shape mismatch: Shapes -1 and 3 must match - CONTINUE

### ISSUE THREAD

**Issue by umitkacar** [tensorflow/tfjs#4684]
I've been working for a week. This error appears to be from open source applications that were not in previous versions. I even tried from old models. They are working. But the one I just created doesn't work. 

This error continues. How do we fix this?

```
tfjs-core: ^3.0.0
tfjs-converter: ^3.0.0
TF 2.4.1
Python 3.6.9
```

_Originally posted by @umitkacar in https://github.com/tensorflow/tfjs/issues/4641#issuecomment-779332368_

**Comment by AlexAndrascu** [comment]
I am getting the same: 
```
Uncaught (in promise) Error: TensorList shape mismatch:  Shapes -1 and 3 must match
    at Module.assert (:3000/static/js/0.chunk.js:102327)
    at assertShapesMatchAllowUndefinedSize (:3000/static/js/0.chunk.js:40206)
    at TensorList.setItem (:3000/static/js/0.chunk.js:39991)
    at _callee2$ (:3000/static/js/0.chunk.js:41111)
    at tryCatch (:3000/static/js/0.chunk.js:141550)
    at Generator.invoke [as _invoke] (:3000/static/js/0.chunk.js:141769)
    at Generator.prototype.<computed> [as next] (:3000/static/js/0.chunk.js:141603)
    at asyncGeneratorStep (:3000/static/js/0.chunk.js:140798)
    at _next (:3000/static/js/0.chunk.js:140820)
    at :3000/static/js/0.chunk.js:140827
    at new Promise (<anonymous>)
    at Module.<anonymous> (:3000/static/js/0.chunk.js:140816)
    at Module.executeOp (:3000/static/js/0.chunk.js:41213)
    at :3000/static/js/0.chunk.js:47719
    at executeOp (:3000/static/js/0.chunk.js:47799)
    at _loop (:3000/static/js/0.chunk.js:38002)
    at GraphExecutor.processStack (:3000/static/js/0.chunk.js:38038)
    at GraphExecutor._callee4$ (:3000/static/js/0.chunk.js:37928)
    at tryCatch (:3000/static/js/0.chunk.js:141550)
    at Generator.invoke [as _invoke] (:3000/static/js/0.chunk.js:141769)
    at Generator.prototype.<computed> [as next] (:3000/static/js/0.chunk.js:141603)
    at asyncGeneratorStep (:3000/static/js/0.chunk.js:140798)
    at _next (:3000/static/js/0.chunk.js:140820)
```

**Comment by nirchetrit** [comment]
Same here.
If anyone knows how to fix it, please share

**Comment by luke-iqt** [comment]
The current package on NPM doesn't included this change yet. If you are using NPM or the <script> tag to pull in the package it won't have the change yet. I am not sure how to build and run the packages directly from Github, but if you figure that out, you should be able to try out the fix that has been merged in.

**Comment by umitkacar** [comment]
However, older models are working.  This is really interesting.  Where are we doing wrong?

**Comment by umitkacar** [comment]
The models we just created do not work.  I think a new update generated such an error while creating the model.

**Comment by nirchetrit** [comment]
> However, older models are working. This is really interesting. Where are we doing wrong?

Any chance you can post a link to an SSD MobileNet V2 FPNLite 320x320  model that is working?

**Comment by AlexAndrascu** [comment]
> > However, older models are working. This is really interesting. Where are we doing wrong?
> 
> Any chance you can post a link to an SSD MobileNet V2 FPNLite 320x320 model that is working?

I was going to ask the same. Also TF / TFJS versions used when training / exporting the mode would be really useful. 
I am now doing a sanity check with a ssd_mobilenet_v2_coco_2018_03_29 on TF1.

**Comment by umitkacar** [comment]
It is working. This is old model.,

https://github.com/hugozanini/TFJS-object-detection/tree/master/models/kangaroo-detector

**Comment by umitkacar** [comment]
I shared demo codes.
```javascript
const model_url = 'http://127.0.0.1:5502/web_ws/model.json';
console.log(model_url)

var model = undefined;
var vidHeight = 320;
var vidWidth = 320;

async function app() {

    const model = await tf.loadGraphModel(model_url);
    console.log('Model loaded');

    const img = document.getElementById('img');
    const tfImg = await tf.browser.fromPixels(img);

    const smallImg = await tf.image.resizeBilinear(tfImg, [vidHeight, vidWidth]);
    const resized = await tf.cast(smallImg, 'int32');
    var tf4d_ = await tf.tensor4d(Array.from(resized.dataSync()), [1, vidHeight, vidWidth, 3]);
    const tf4d = await tf.cast(tf4d_, 'int32');
    console.log('Preprocess completed');
    const predictions = await model.executeAsync(tf4d);

    console.log(predictions[0].dataSync())
    console.log(predictions[1].dataSync())
    console.log(predictions[2].dataSync())
    console.log(predictions[3].dataSync())
}

app();
```

**Comment by umitkacar** [comment]
Other model is running:

https://github.com/KostaMalsev/ObjectDetection/tree/master/model/mobile_netv2/web_model2

`"format": "graph-model", "generatedBy": "2.3.0", "convertedBy": "TensorFlow.js Converter v2.6.0",`

**Comment by umitkacar** [comment]
If you find an improvement, I will be glad if you share.

**Comment by AlexAndrascu** [comment]
This is really helpful. Thank you @umitkacar !

Like you, I was also looking at Hugo's repository. Here's another useful repo:  
https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model

**Comment by luke-iqt** [comment]
I have a docker container and notebooks for building an objection detection model using TF 2.0 here: https://github.com/IQTLabs/SkyScan/tree/main/ml-model

I have some additional notebooks for converting it to TensorJS.

**Comment by rthadur** [comment]
Latest version has been posted to npm https://www.npmjs.com/package/@tensorflow/tfjs , please check

**Comment by umitkacar** [comment]
I tried it. It is working. Thank you everyone.

Perfect!

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js

**Comment by nirchetrit** [comment]
I've trained SSD MobileNet V2 FPNLite 320x320 model from the Tensorflow object detection zoo using the [object detection API](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html).
Then converted it to tfjs, and after updating to tfjs 3.1.0 I now have a problem saying:
Cannot read property 'backend' of undefined

Here is both the saved_model after training on two classes and the web_model that was converted:
https://drive.google.com/drive/folders/1YtT2OHY0Ni6QgimQAWKgvWI6v2v2liZ_?usp=sharing

the code for loading the model to the browser and making the inference:
loadGraphModel("http://172.18.109.97:8080/model.json").then(model => {
            setModel(model);
});
const runModel = async () => {
        const image = document.getElementById('image');
        model.executeAsync(tf.browser.fromPixels(image).expandDims()).then(pred=>{
            console.log(pred);
        })
}


Does anyone know how to fix it?

**Comment by AlexAndrascu** [comment]
> I've trained SSD MobileNet V2 FPNLite 320x320 model from the Tensorflow object detection zoo using the [object detection API](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html).
> Then converted it to tfjs, and after updating to tfjs 3.1.0 I now have a problem saying:
> Cannot read property 'backend' of undefined
> 
> Here is both the saved_model after training on two classes and the web_model that was converted:
> https://drive.google.com/drive/folders/1YtT2OHY0Ni6QgimQAWKgvWI6v2v2liZ_?usp=sharing
> 
> the code for loading the model to the browser and making the inference:
> loadGraphModel("[http://172.18.109.97:8080/model.json").then(model](http://172.18.109.97:8080/model.json%22).then(model) => {
> setModel(model);
> });
> const runModel = async () => {
> const image = document.getElementById('image');
> model.executeAsync(tf.browser.fromPixels(image).expandDims()).then(pred=>{
> console.log(pred);
> })
> }
> 
> Does anyone know how to fix it?

Same problem here

**Comment by umitkacar** [comment]
I examine for you. My model is running.

I converted from your saved model to tfjs-3.1.0. This model is below.

Please try it. If it runs, I will share details. Maybe, there is a convert problem.

https://drive.google.com/file/d/149HMeTsgF0cHHwOOQhNwAsXGSFk-gljg/view?usp=sharing

**Comment by AlexAndrascu** [comment]
@umitkacar thanks for getting back. Do you have a repo for the demo app you are testing with ?

**Comment by umitkacar** [comment]
```bash
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    saved_model \
    web_model
```

**Comment by AlexAndrascu** [comment]
> Can you try it? Please, give me feedback. This is bash code. If there is any problem, you can try `tensorflowjs_wizard`
> 
> I shared the test code above.
> 
> ```shell
> tensorflowjs_converter \
>     --input_format=tf_saved_model \
>     --output_format=tfjs_graph_model \
>     --signature_name=serving_default \
>     --saved_model_tags=serve \
>     saved_model \
>     web_model
> ```

It is possible this might be down to React. Here's a related issue: #4237 

I will try with your test code later and get back.

**Comment by nirchetrit** [comment]
Thank you all guys for the help!
I will test it later today and share the results.

**Comment by umitkacar** [comment]
#4237 is related to LSTM. Tensorflow Object Detection API doesn't include LSTM layer.

**Comment by mihaelagrigore** [comment]
> 
> 
> I tried it. It is working. Thank you everyone.
> 
> Perfect!
> 
> https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js

How did you manage to make it work ? 
In my case, the 3.1.0 version introduces a new problem 👎🏼 

Here's my story. I am following Hugo's tutorial got get a tfjs object detection model starting from a SSD pre-trained (https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html).

All goes well until the conversion to tfjs. For the conversion to tfjs, I followed the same steps mentioned by Hugo and detailed here (https://github.com/tensorflow/tfjs/tree/master/tfjs-converter)
The environment where I run the convertion is an Anaconda env with:
Python 3.6.8 (as instructed in the tfjs-converter github readme)
tensorflow 2.4.1 
tensorflowjs 3.1.0 
The last two were installed by default with these versions when I ran 
`pip install tensorflowjs[wizard]`
In this env I ran the tfjs-converter and got my web model.

Then I use Hugo's tfjs object detection browser app (https://github.com/hugozanini/TFJS-object-detection). 
I am running a local webserver to serve the model (for now).
I changed Hugo's package,json dependencies like this:
```
  "dependencies": {
    "@tensorflow/tfjs": "^3.1.0",
    "@tensorflow/tfjs-converter": "^3.1.0",
    "@tensorflow/tfjs-core": "^3.1.0",
    "@tensorflow/tfjs-node": "^3.1.0"
```
.......
The rest stays the same. 
npm install goes fine.
But then npm start fails to compile:

```
Failed to compile

./node_modules/@tensorflow/tfjs-core/dist/io/http.js
Error: C:\Stuff\Work\Personal Projects - Portfolio\tf2_object_detection\TFJS-object-detection\node_modules\@tensorflow\tfjs-core\dist\io\http.js: Expected type "Expression" with option undefined, but instead got "SpreadElement".
    at Array.map (<anonymous>)
    at Array.forEach (<anonymous>)

This error occurred during the build time and cannot be dismissed.
```

**Comment by umitkacar** [comment]
Please give me sometime. I'll try this example and get back to you. Everyone is in trouble with this new version. Actually I'm thinking of a video conference to discuss.

**Comment by luke-iqt** [comment]
I tested everything out, and it is working for me. I am using an SSD based Object Detection Model. I used the TF Obj Detect API 2.0 to retrain a MobileNet model. My web app is here:
https://luke-iqt.github.io/SkyScan-Web-App/index.html
And the source code is here:
https://github.com/luke-iqt/SkyScan-Web-App

**Comment by AlexAndrascu** [comment]
> I tested everything out, and it is working for me. I am using an SSD based Object Detection Model. I used the TF Obj Detect API 2.0 to retrain a MobileNet model. My web app is here:
> https://luke-iqt.github.io/SkyScan-Web-App/index.html
> And the source code is here:
> https://github.com/luke-iqt/SkyScan-Web-App

I've managed to get the model imported fine with your app. However no detections / detection boxes are rendered :)

**Comment by mihaelagrigore** [comment]
> 
> 
> > I tested everything out, and it is working for me. I am using an SSD based Object Detection Model. I used the TF Obj Detect API 2.0 to retrain a MobileNet model. My web app is here:
> > https://luke-iqt.github.io/SkyScan-Web-App/index.html
> > And the source code is here:
> > https://github.com/luke-iqt/SkyScan-Web-App
> 
> I've managed to get my web model imported fine with your app. Nicely done. No moaning about any missing 'backend' now so probably that was just React playing? I must admit I'm not very skilled when it comes to React & debugging javascript .
> I was already investigating these 2 imports:
> 
> ```
> import '@tensorflow/tfjs-backend-cpu';
> import '@tensorflow/tfjs-backend-webgl';
> ```
> 
> However no detections / detection boxes are rendered with my model as of yet :)
> Everything looks fine in Tensorboard's eval though.

@AlexAndrascu Is my understanding correct that the same tfjs model was not being deployed correctly with Hugo's React app but it works with Luke's app ? Same model, different front end deployment method and it works ?

**Comment by AlexAndrascu** [comment]
> > > I tested everything out, and it is working for me. I am using an SSD based Object Detection Model. I used the TF Obj Detect API 2.0 to retrain a MobileNet model. My web app is here:
> > > https://luke-iqt.github.io/SkyScan-Web-App/index.html
> > > And the source code is here:
> > > https://github.com/luke-iqt/SkyScan-Web-App
> > 
> > 
> > I've managed to get my web model imported fine with your app. Nicely done. No moaning about any missing 'backend' now so probably that was just React playing? I must admit I'm not very skilled when it comes to React & debugging javascript .
> > I was already investigating these 2 imports:
> > ```
> > import '@tensorflow/tfjs-backend-cpu';
> > import '@tensorflow/tfjs-backend-webgl';
> > ```
> > 
> > 
> > However no detections / detection boxes are rendered with my model as of yet :)
> > Everything looks fine in Tensorboard's eval though.
> 
> @AlexAndrascu Is my understanding correct that the same tfjs model was not being deployed correctly with Hugo's React app but it works with Luke's app ? Same model, different front end deployment method and it works ?

Indeed that's how it looks like.

**Comment by luke-iqt** [comment]
I pulled in some of Hugo's code. I think the only major difference is that he was looking at different Output Tensor Arrays:
I found the Classes, Scores and Boxes in these arrays:
https://github.com/luke-iqt/SkyScan-Web-App/blob/main/src/App.js#L110
I think he was using 4,5,6 in the output array.

My model only had one class. You may need to adjust things. Probably best to put a Breakpoint and examine the output from the inference in the Chrome Web Developer panel. Your model could be outputing things differently.

**Comment by umitkacar** [comment]
I trained Kangaroo dataset again. I used this code below to convert javascript. This model is running my demo code not react. As a results, the model is OK. I think that react is problem. I didn't use react before. 
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    saved_model \
    web_model
```

**Comment by AlexAndrascu** [comment]
> I pulled in some of Hugo's code. I think the only major difference is that he was looking at different Output Tensor Arrays:
> I found the Classes, Scores and Boxes in these arrays:
> https://github.com/luke-iqt/SkyScan-Web-App/blob/main/src/App.js#L110
> I think he was using 4,5,6 in the output array.
> 
> My model only had one class. You may need to adjust things. Probably best to put a Breakpoint and examine the output from the inference in the Chrome Web Developer panel. Your model could be outputing things differently.

@luke-iqt this is how my model looks like:

`saved_model_cli show --dir medistats_inference_graph/saved_model/ --all`:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_tensor'] tensor_info:
        dtype: DT_UINT8
        shape: (1, -1, -1, 3)
        name: serving_default_input_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detection_anchor_indices'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100)
        name: StatefulPartitionedCall:0
    outputs['detection_boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100, 4)
        name: StatefulPartitionedCall:1
    outputs['detection_classes'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100)
        name: StatefulPartitionedCall:2
    outputs['detection_multiclass_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100, 6)
        name: StatefulPartitionedCall:3
    outputs['detection_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 100)
        name: StatefulPartitionedCall:4
    outputs['num_detections'] tensor_info:
        dtype: DT_FLOAT
        shape: (1)
        name: StatefulPartitionedCall:5
    outputs['raw_detection_boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 110484, 4)
        name: StatefulPartitionedCall:6
    outputs['raw_detection_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 110484, 6)
        name: StatefulPartitionedCall:7
  Method name is: tensorflow/serving/predict
```

What I changed on your app:
`classList` to reflect my multiple classes and

```
    const  classes = predictions[2].arraySync()
    const scores = predictions[4].arraySync()
    const boxes = predictions[1].arraySync()
    const detections = buildDetectedObjects(scores, threshold,
      boxes, classes, classList);
```

**Comment by mihaelagrigore** [comment]
> 
> 
> I trained Kangaroo dataset again. I used this code below to convert javascript. This model is running my demo code not React. As a results, the model is OK. I think that React is problem. I didn't use React before.
> 
> ```
> tensorflowjs_converter \
>     --input_format=tf_saved_model \
>     --output_format=tfjs_graph_model \
>     --signature_name=serving_default \
>     --saved_model_tags=serve \
>     saved_model \
>     web_model
> ```

Thank you @umitkacar. I think it's safe to say all goes well with tfjs in 3.1.0 for us now. 
We just can't figure out the right way to deploy it in the broswer, I guess -.-

**Comment by umitkacar** [comment]
I think the `tfjs-3.1.0` version works fine. However, I have not printed the model outputs on the screen yet. I can share when finished.

**Comment by luke-iqt** [comment]
Sorry about that!!
I just pushed some changes to fix the bounding boxes. I think it is better now. 
The Web App ran a little older version of the code, so it didn't have that problem.

Try removing the `homepage` line from the package.json
https://github.com/luke-iqt/SkyScan-Web-App/blob/main/package.json#L5
that will let you use the URL localhost:3000/

**Comment by JoaoSisanoski** [comment]
I was having the same issue and I got it working after I decided to not use the tensorflowjs_wizard and run the `tensorflowjs_converter` straight away and it did work fine after that.  I noticed that tensorflowjs_wizard adds an extra argument to the conversion. `--control_flow_v2=True` and for some reason, it was causing the issues for me

> I trained Kangaroo dataset again. I used this code below to convert javascript. This model is running my demo code not React. As a results, the model is OK. I think that React is problem. I didn't use React before.
> 
> ```
> tensorflowjs_converter \
>     --input_format=tf_saved_model \
>     --output_format=tfjs_graph_model \
>     --signature_name=serving_default \
>     --saved_model_tags=serve \
>     saved_model \
>     web_model
> ```

**Comment by lina128** [comment]
Hi @JoaoSisanoski , can you try converting with the wizard and use 3.1.0 to run the model? If control_flow_v2=true, then it will use TensorList, which is the issue reported here. It is fixed in version 3.1.0.

**Comment by JoaoSisanoski** [comment]
> Hi @JoaoSisanoski , can you try converting with the wizard and use 3.1.0 to run the model? If control_flow_v2=true, then it will use TensorList, which is the issue reported here. It is fixed in version 3.1.0.

I did that. When I was using the control_flow_v2=true I was getting: `Cannot read property 'backend' of undefined`. 

It doesn't matter if running via tag script, react, npm...

I will try later tonight the imports suggested up here and I will let you know if it fixes the issue I was having. 

```
import '@tensorflow/tfjs-backend-cpu';
import '@tensorflow/tfjs-backend-webgl';
```

**Comment by umitkacar** [comment]
I also checked `control_flow_v2=true` using `tensorflowjs_wizard`. There is an error:

`Uncaught (in promise) TypeError: Cannot read property 'backend' of undefined` (tfjs-3.1.0)

**Comment by lina128** [comment]
Hi @JoaoSisanoski and @umitkacar , do you mind sharing your code and model?

**Comment by JoaoSisanoski** [comment]
Hi @lina128 I will be providing one dummy one shortly as I can't publish the one I am working on at the moment.
Another thing that I noticed is that the `Uncaught (in promise) TypeError: Cannot read property 'backend' of undefined` error only comes up if I wrap my function around a `tf.startScope` and `tf.endScope`
eg:
```python
tf.engine().startScope()
var img = this.preprocess(input, options);
var resp = await this.graphModel.executeAsync(img);
console.log(resp)
tf.engine().endScope()
``` 
an exception is thrown.


```python
//tf.engine().startScope()
var img = this.preprocess(input, options);
var resp = await this.graphModel.executeAsync(img);
console.log(resp)
//tf.engine().endScope()
``` 

No exception, but I would need to manage the tensors by myself using the tidy/dispose functions

**Comment by lina128** [comment]
Hi @JoaoSisanoski , that makes sense. If you use executeAsync, tidy/startScope,endScope doesn't work, which only work for synchronous code. For async execution, you need to manage the tensors yourself.

**Comment by xfffrank** [comment]
> It is working. This is old model.
> 
> https://github.com/hugozanini/TFJS-object-detection/tree/master/models/kangaroo-detector
> 
> I checked `model.json` . I noticed:
> 
> `format": "graph-model", "generatedBy": "2.4.0", "convertedBy": "TensorFlow.js Converter v2.8.0"`



> Other model is running:
> 
> https://github.com/KostaMalsev/ObjectDetection/tree/master/model/mobile_netv2/web_model2
> 
> `"format": "graph-model", "generatedBy": "2.3.0", "convertedBy": "TensorFlow.js Converter v2.6.0",`

Hi, @umitkacar 
I'm training a `ssd_mobilenet_v2_320x320_coco17_tpu-8` model like the one in the [kangaroo detector](https://github.com/hugozanini/TFJS-object-detection/tree/master/models/kangaroo-detector) except that I changed the input resolution to `192x192` and `depth_multiplier` to 0.25. And I'm deploying the JS model with the [TensorflowJS WeChat](https://github.com/tensorflow/tfjs-wechat) plug-in which was said to only supports tfjs 2.0.x.

I've tried different combinations of Tensorflow and TensorflowJS versions as shown below.
```
"format": "graph-model", "generatedBy": "2.4.0", "convertedBy": "TensorFlow.js Converter v2.8.0"

"format": "graph-model", "generatedBy": "2.3.0", "convertedBy": "TensorFlow.js Converter v2.6.0"

"format": "graph-model", "generatedBy": "2.4.1", "convertedBy": "TensorFlow.js Converter v3.4.0"

"format": "graph-model", "generatedBy": "2.4.0", "convertedBy": "TensorFlow.js Converter v3.4.0"

```
But the error `Error: TensorList shape mismatch: Shapes -1 and 3 must match` persists. 

Surprisingly, I tried the kangaroo model which corresponds to `"format": "graph-model", "generatedBy": "2.4.0", "convertedBy": "TensorFlow.js Converter v2.8.0"` and it worked. But I've tried many times and cannot figured out how the error disappeared with the kangaroo model.

Can you help as I cannot upgrade the tfjs version in WeChat to 3.1.0 or other higher versions ? For now, I'm using tfjs 2.1.0 in WeChat.

**Comment by xfffrank** [comment]
It seems that the plug-in has been updated. [#92](https://github.com/tensorflow/tfjs-wechat/issues/92)

**Comment by avinashnair02** [comment]
Versions used :tfjs@2.8.6, tfjs-node@2.7.0

Error TensorList shape mismatch: Shapes -1 and 3 must match"

Screen shoot the model json and the link has been attached****


Model url :[Model url :https://appptest12.herokuapp.com/model.json](url)

**Comment by lina128** [comment]
@avinashnair02 Can you try with the latest version? 3.13.0. You may want to convert the model with the latest tfjs-converter too.

**Comment by avinashnair02** [comment]
This issue im currently getting

model json: [https://appptest12.herokuapp.com/model.json](url)


 F tensorflow/core/framework/tensor_shape.cc:332] Check failed: 0 <= new_num_elements (0 vs. -1)

**Comment by waqardongre** [comment]
> I tried it. It is working. Thank you everyone.
> 
> Perfect!
> 
> https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js

I think the tensorflowJS version included in web app must be the same as the converter we used to convert the model from tensorflow saved model. For me adding this"<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.18.0/dist/tf.min.js"></script>" this in index.html in [https://github.com/KostaMalsev/ObjectDetection](url) in this template worked for me, because I converted using 3.18.0 tensorflowJS version. to check your tensorflowJS version in linux/ubuntu run this in terminal "pip show tensorflowjs"

Thanks.
