### ISSUE TITLE
Documentation missing for tf.engine().startScope() and tf.engine().endScope()

### ISSUE THREAD

**Issue by jameshfisher** [tensorflow/tfjs#4685]
I was looking for an equivalent of [`tf.tidy`](https://js.tensorflow.org/api/latest/#tidy) that would work for async code. I eventually stumbled across [`startScope` and `endScope`](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/engine.ts#L1031-L1074). For my use-case, these methods seem to work, but they have no documentation or guidance.

What is the recommended way to manage tensors in `async` code? Should I be using `startScope`/`endScope`, or some other pattern, or just manually `.dispose()` everywhere?

**Comment by jameshfisher** [comment]
I should note, the functions have a comment saying

> Use this ... to achieve the same functionality as `scope()` without the need for a function closure.

However, I don't know what this method `scope()` is, either. What is it referring to?

**Comment by lina128** [comment]
Hi @jameshfisher For async code, you need to manually dispose the tensors.

**Comment by jameshfisher** [comment]
@lina128 thanks, that makes sense. I'm not sure how tfjs could provide automatic GC for async code anyway.

**Comment by rohanmuplara** [comment]
@lina128 what is the problem with using tf.engine.start_scope and tf.engine_clear_scope. Is it that the callers now have to guarantee no interleaving? Any other disadvantages?

**Comment by lina128** [comment]
Hi @rohanmuplara, you mean startScope and endScope? It handles memory management, any intermediate tensors will be disposed properly. The disadvantage is it doesn't work with async code.

**Comment by lina128** [comment]
Hi @rohanmuplara, I look at your question again, and now I understand better, yeah, I think the interleaving issue is the disadvantage.

**Comment by rohanmuplara** [comment]
ok thanks
