### ISSUE TITLE
Property 'toFloat' does not exist on type 'Tensor3D'

### ISSUE THREAD

**Issue by nxtexe** [tensorflow/tfjs#4686]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Windows Home
- TensorFlow.js installed from (npm or script link):
- Yes
- TensorFlow.js version (use command below):
- 3.0.0
- Browser version:
- Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
Typescript throws ```Property 'toFloat' does not exist on type 'Tensor3D'``` error.
**Describe the expected behavior**
Cast the array to type float32
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
```
const video = document.createElement('video');
tf.browser.fromPixels(video).toFloat()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
----------------------------------------------
I'm new to tensorflowjs and I was following along the code example in [this](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection) npm package and [this](https://github.com/tensorflow/tfjs-models) github repo. I traced the problem to [this](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/mediapipe-facemesh/index.ts) file at line 315 to be the cause of my problems. When I pass in the video as input to model.estimateFaces I get a JS error that says toFloat doesn't exist on input. I'm pretty sure this is a bug.

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.
