### ISSUE TITLE
Slow Speed of Converted TFJS Model

### ISSUE THREAD

**Issue by NaeemKhan333** [tensorflow/tfjs#4688]
I have a question related to tensorflow-Js inferences speed. I have trained a custom u2net model and run the inferences on the video input to trained model.It is giving me 7-10 Fps on cpu device. I have converted this model into tensorflow-Js model, the model is running on the browser but it is giving me 0.5 to 1 Fps on the browser . My converted model have size of 600 kb . It is running fine while I run the web on the browser having gpu device but on the cpu device it is slow .  Can anybody suggest me how I can speed up the model to get 7-10 fps on the browser using the cpu device.Please suggest me some method which improve my speed on the web browser using cpu Device. Thanks

**Comment by NaeemKhan333** [comment]
Here is my model architecture

https://drive.google.com/drive/folders/1DU0cFue1v6QVb87DM77PfAYI2etqGZAr?usp=sharing

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.
