### ISSUE TITLE
Property 'print' does not exist on type 'Tensor<Rank>[]'.

### ISSUE THREAD

**Issue by George35mk** [tensorflow/tfjs#47]
If you would like to get help from the community, our [Google
group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) might be a
better fit.

#### TensorFlow.js version
0.6.1

#### Describe the problem or feature request
I use Typescript environment (Angular 5)

I trying to run this code from the`https://js.tensorflow.org/#getting-started`

```
 import * as tf from '@tensorflow/tfjs';

  // Define a model for linear regression.
  const model = tf.sequential();
  model.add(tf.layers.dense({units: 1, inputShape: [1]}));

  // Prepare the model for training: Specify the loss and the optimizer.
  model.compile({loss: 'meanSquaredError', optimizer: 'sgd'});

  // Generate some synthetic data for training.
  const xs = tf.tensor2d([1, 2, 3, 4], [4, 1]);
  const ys = tf.tensor2d([1, 3, 5, 7], [4, 1]);

  // Train the model using the data.
  model.fit(xs, ys).then(() => {
    // Use the model to do inference on a data point the model hasn't seen before:
    model.predict(tf.tensor2d([5], [1, 1])).print();
  });
```

![3](https://user-images.githubusercontent.com/20750445/38177163-0a6a6f42-3605-11e8-8e34-c0ef7784ba56.PNG)

```
ERROR in src/app/app.component.ts(29,47): error TS2339: Property 'print' does not exist on type 'Tensor<Rank> | Tensor<Rank>[]'.
  Property 'print' does not exist on type 'Tensor<Rank>[]'.
```

**Comment by dsmilkov** [comment]
Hi @George35mk 

We wrote that example for es6 javascript. For typescript, since predict() can return either a `Tensor`, or `Tensor[]`, depending on how many outputs your model has, you have to notify the compiler which one it is:
```typescript
(model.predict(...) as tf.Tensor).print()
```

Hope this helps!

**Comment by George35mk** [comment]
Thank you @dsmilkov for your fast response. and for the beautiful javascript library you created with your team.

**Comment by sullyfischer** [comment]
> either a Tensor, or Tensor[]

@dsmilkov Could you please provide examples for both? Sorry if my question is too basic.

**Comment by George35mk** [comment]
@dsmilkov  I am using Angular 6 to work with machine learning so what I have found is because angular 6 is using typescript and is strong typing I get a lot of type errors when I compile the apps with tensorflow, a lot of errors are exist today just try to use a simple typescript 2.9 project and you gonna find a lot of warnings with tensorflow.js.

create a test dir and add a file with name `main.ts`

Inside `test` dir run this commands:

### Step 1 
`npm init`

### Step 2 
`git init`

### Step 3
`npm install -g typescript`

### Step 4
`npm install @tensorflow/tfjs`

and finaly import the  tensorflow.js lib in your main.ts and start to code, in the end you gonna find that some of the .print() or some other methods are causing an error while you are compiling the main.ts

### Step 5 compile
`tsc main.ts`

**Comment by grinsteindavid** [comment]
const result = model.predict(tf.tensor2d(input, [1, 1])) as tf.Tensor; // this is a tensor

const data = await result.data(); // will return a promise with the Y value ( result )
