### ISSUE TITLE
Latest version of speech-commands library won't load in browser 

### ISSUE THREAD

**Issue by dalelane** [tensorflow/tfjs#4709]
For a simple recreate:
```
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js"></script>
<script src="https://unpkg.com/@tensorflow-models/speech-commands@0.5.1"></script>
</head>
<body></body>
</html>
```

The browser console shows the error:
```
speech-commands@0.5.1:17 Uncaught TypeError: Cannot read property 'Buffer' of undefined
    at speech-commands@0.5.1:17
    at Ms (speech-commands@0.5.1:17)
    at speech-commands@0.5.1:17
    at speech-commands@0.5.1:17
    at speech-commands@0.5.1:17
```

This used to work, and if you pin the speech-commands version you can see earlier versions don't have this problem.

For example, this works correctly
```
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js"></script>
<script src="https://unpkg.com/@tensorflow-models/speech-commands@0.4.2"></script>
</head>
<body></body>
</html>
```

For real examples of this in the wild, see pages like these:
- https://glitch.com/~abrasive-ixora (cf. https://yashints.dev/blog/2019/12/16/tfjs-transfer-learning )
- https://livecodestream.dev/post/speech-recognition-with-tensorflowjs/ 
- https://bensonruan.com/speech-recognition-with-tensorflow-js/
- https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab#2

(which, at the time of writing, are currently broken because they're using https://unpkg.com/@tensorflow-models/speech-commands to just grab the latest released version)

I haven't tried this on every browser, but it's broken on the current versions of Firefox and Chrome on MacOS.

**Comment by pyu10055** [comment]
@dalelane Thank you for reporting this bug, new build 0.5.2 has been release, I have checked some of the website, they seems to be working as expected.

**Comment by dalelane** [comment]
@pyu10055 Fantastic - thanks for fixing it so quickly!
