### ISSUE TITLE
speech-commands demo failing with large training sets - with "TypeError: n.array is not a function"

### ISSUE THREAD

**Issue by dalelane** [tensorflow/tfjs#4719]
I'm loading speech-commands from npm, using version 0.5.2. 

If I revert to 0.4.2, I don't see the error shown below, so this looks like a recent regression. (Could it be a build problem, similar to the one fixed in https://github.com/tensorflow/tfjs/issues/4709 ?) 

### When do I get the error?

When I call `transferRecognizer.train` 

You can see an example of what I'm doing at https://github.com/tensorflow/tfjs-models/blob/62f4f9c20db0eef4cae1ee82d000b9cd69696a58/speech-commands/demo/index.js#L456-L466 

Calling `train()` results in an uncaught exception

### What error am I getting?

```
Uncaught (in promise) TypeError: n.array is not a function
    at speech-commands.min.js:17
    at engine.js:467
    at e.t.scopedRun (engine.js:478)
    at e.t.tidy (engine.js:465)
    at Object.vx [as tidy] (globals.js:192)
    at e.getData (speech-commands.min.js:17)
    at r.collectTransferDataAsTfDataset (speech-commands.min.js:17)
    at r.<anonymous> (speech-commands.min.js:17)
    at speech-commands.min.js:17
    at Object.next (speech-commands.min.js:17)
```

### How to recreate 

I _think_ this is only happening with training data that is large enough to trigger this:

```
Detected large dataset: total duration = 98900 ms > 60000 ms. Training transfer model using fitDataset() instead of fit()
```

When I use training data small enough to not see that message, I don't see the error.

### More info about the exception

I tried rebuilding the app with speech-commands.js (instead of the minified version) to get a more useful stack trace:

```
Uncaught (in promise) TypeError: tfd.array is not a function
    at speech-commands.js:1067
    at engine.js:467
    at e.t.scopedRun (engine.js:478)
    at e.t.tidy (engine.js:465)
    at Object.vx [as tidy] (globals.js:192)
    at Dataset.getData (speech-commands.js:966)
    at TransferBrowserFftSpeechCommandRecognizer.collectTransferDataAsTfDataset (speech-commands.js:2536)
    at TransferBrowserFftSpeechCommandRecognizer.<anonymous> (speech-commands.js:2616)
    at step (speech-commands.js:95)
    at Object.next (speech-commands.js:76)
```

Catching the error in a debugger, I can see it's caused by this line:
![image](https://user-images.githubusercontent.com/1444788/108553596-d2d4b080-72ea-11eb-9380-967e4cc841c4.png)

`tfd` isn't null/undefined, and looks like it's the right sort of shape, but sure enough, it doesn't have an `array` function.

![image](https://user-images.githubusercontent.com/1444788/108553702-fbf54100-72ea-11eb-8b62-3a66a6ca28c8.png)

And if I let it try to step past that line, I get the stack trace copied above

![image](https://user-images.githubusercontent.com/1444788/108553762-0ca5b700-72eb-11eb-8173-e0cdfb7c9bbe.png)

**Comment by pyu10055** [comment]
@dalelane Thank you for the detail debugging session, I think it is the build error where the tfjs-data package is not indexed properly.

**Comment by pyu10055** [comment]
@dalelane Thank you for the detailed debugging session, this seems to be kinda weird, the tfd (tfjs-data) object seems to become tfjs-core. Is it possible for you to create a codepen example of this? thanks!

**Comment by dalelane** [comment]
Not easily, sorry. 

But essentially I'm just doing this:

```js
var baseRecognizer = speechCommands.create('BROWSER_FFT');
baseRecognizer.ensureModelLoaded()
    .then(function () {
         var transferRecognizer = baseRecognizer.createTransfer('uniqueid');
         
         // collect at least 60 seconds worth of examples
         // e.g.  many times calling    
         //  transferRecognizer.collectExample('label');     
                 
         return transferRecognizer.train();
    });
```

**Comment by pyu10055** [comment]
@dalelane Please verify with the new release 0.5.3, thanks.

**Comment by dalelane** [comment]
@pyu10055 That seems to have done the trick - thanks!
