### ISSUE TITLE
the speed is too slow

### ISSUE THREAD

**Issue by Kevin-1993-35** [tensorflow/tfjs#4720]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):npm
- TensorFlow.js version (use command below):2.8.0
- Browser version:Chrome 88.0.4324.150
- Tensorflow.js Converter Version:
- PC:lenovo y7000,
- cpu: i7 6700HQ
- backend:wasm

**Describe the current behavior**
I tested the blazeface demo on my own PC,but the inference was 35ms,it was much slower than the official announcement，can you help me to solve it？
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@Kevin-1993-35 can you try with latest version 3.0.0-rc.1 ? and please let us know which announcement you are referring to ?
