### ISSUE TITLE
Built in image decoder for note js.

### ISSUE THREAD

**Issue by bebensiganteng** [tensorflow/tfjs#4724]
**System information**
- Operating system: macOS
- TensorFlow.js version (you are using): 2.8.6
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behaviour/state.**
A built-in image decoder for node js. At the moment image needs to be decoded through node-canvas, which is extremely slow for real-time detection.
```
  if(data && data.body) {
    const img = new Image()
    img.src = data.body;
    const canvas = createCanvas(320, 180);
    const ctx = canvas.getContext('2d');
    const input = tf.browser.fromPixels(canvas);

    try {
      predictions = await model.estimateSinglePose(input, {
        flipHorizontal: false
      });
    } catch(e) {
      console.log(e);
    }

  }
```

**Will this change the current api? How?**
Yes, it'll add another method to decode the image.

**Who will benefit with this feature?**
Anybody who to use Posenet without sacrificing the client frame rate.

**Any Other info.**

**Comment by rthadur** [comment]
Decode image for Node is already implemented here https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/image.ts#L155 , please verify

**Comment by rthadur** [comment]
you do not need to explicitly convert to Unit8Array , here is the sample code from one of the [SO questions ](https://stackoverflow.com/questions/65429456/cant-open-jpg-or-png-after-saving-it-using-node-js-fs-and-http)

`saveImageToDisk(imageurl,filepath)

            const img_buffer = fs.readFileSync(filepath)
            const img = tf.node.decodeImage(img_buffer)

            coco.load().then(model => {
                // detect objects in the image.
                model.detect(img).then(predictions => {
                    console.log('Predictions: ', predictions);
                });
              });`

**Comment by bebensiganteng** [comment]
@rthadur thanks, but I have a different use case. The reason I need the Unit8Array is that I need to pass the webcam image to the server.

**Comment by pyu10055** [comment]
@bebensiganteng when you use the getImageData() call, it returns the pixel values of the image, which means it is decoded, you can use it directly to create the tensors for model execution.

**Comment by bebensiganteng** [comment]
@pyu10055 could you elaborate, please? And did you actually tried it? because it threw me this error.

```
Error: Tensor must have a shape comprised of positive integers but got shape [,,3].
   at assert (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:335:15)
   at /Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:813:9
   at Array.forEach (<anonymous>)
   at assertNonNegativeIntegerDimensions (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:812:11)
   at makeTensor (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4081:9)
   at tensor3d (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:7445:12)
   at fromPixels_ (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:7588:12)
   at Object.fromPixels__op [as fromPixels] (/Users/xxx/app/server/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3986:29)
   at toInputTensor (/Users/xxx/app/server/node_modules/@tensorflow-models/posenet/dist/util.js:211:60)
   at /Users/xxx/app/server/node_modules/@tensorflow-models/posenet/dist/util.js:247:27
```

**Comment by pyu10055** [comment]
you need to create a tensor from the data, with something as following:
height = 180, width=320, channels=4 
```
    const temp = tf.tensor(new Uint8Array(data), [height, width, channels]);
    const image = tf.slice(temp, [0, 0, 0], [-1, -1, 3]);
    temp.dispose();
```

**Comment by bebensiganteng** [comment]
It worked! thank you! 

`CLIENT`
```
          const imageData = refCam.current.ctx.getImageData(0, 0, 320, 180);
          const buffer = imageData.data.buffer;
          // console.log(typeof buffer);
          socket.emit("signal", buffer);
```
`BACKEND`
```
    let pose = []

    if(model) {

      const buffer = new Uint8Array(data);

      const temp = tf.tensor(buffer, [HEIGHT, WIDTH, CHANNELS]);
      const image = tf.slice(temp, [0, 0, 0], [-1, -1, 3]);
      temp.dispose();
      pose = await model.estimateSinglePose(image, {
        flipHorizontal: false
      });

    }

    socket.emit("messageAll", pose);
```
@pyu10055 If you don't mind could explain what `tf.slice `means?
