### ISSUE TITLE
tensorflowjs_converter: Add Support for Operations used by BigQuery ML models

### ISSUE THREAD

**Issue by fneubaum-sulvo** [tensorflow/tfjs#4725]
**System information**
- TensorFlow.js version (you are using): 3.1.0 (version 2.4.1 of tensorflow)
- Are you willing to contribute it (Yes/No): I'm not familiar enought with this or tensorflow's codebase so I don't think I could write the code to fix this issue. But I think I can contribute in anything else you need, like testing, reviewing the code or giving more context. 

**Describe the feature and the current behavior/state.**
The company I work for is building a Deep Neural Network Regressor (DNN_REGRESSOR) using BigQuery ML and we plan on deploying in a Node.js environment. The initial tests worked fine but recently when we tried to convert the Saved Model to Tensorflowjs it failed with the following error:
```sh
ValueError: Unsupported Ops in the model before optimization
SparseSegmentMean, LookupTableSizeV2, StringToHashBucketFast, SparseReshape, SparseFillEmptyRows
```
I'm converting the model in this way: 
```sh
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=predict --weight_shard_size_bytes=25000000 --saved_model_tags=serve source target
```
As a result we can't convert model nor deploy it, rendering it unusable for us. I'm using tabular data with high cardinality categorical features and these ones seem to be at the root of the problem.

BigQuery ML doesn't give any options in which operations to include or not, so we depend on you giving support for these operations or maybe offering a workaround that I don't know of.

**Will this change the current api? How?**
Definitely, because it will require adding those Operations as supported, but that shouldn't break any working code.

**Who will benefit with this feature?**
Every user that is producing *BigQuery ML* models and then using them with Tensorflowjs can benefit from this. We're using tabular data in a pretty straightforward way so I don't think this is an edge case that you won't encounter anymore and it would probably be a nice synergy to have ML models created in BigQuery that work smoothly in Tensorflowjs.

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by fneubaum-sulvo** [comment]
@rthadur @pyu10055 
I have been familiarizing myself with the library. I'll try adding at least LookupTableSizeV2 and StringToHashBucketFast myself. 

I'll start with LookupTableSizeV2. I think this only requires returning the size of the Hash Table and should be pretty similar to other operations like LookupTableFind. Do you think this approach is OK? Do you agree on adding those operations?

I read the contributing guidelines but would appreciate any help or guidance you can offer. Thanks in advance!

**Comment by fneubaum-sulvo** [comment]
@rthadur @pyu10055 
[This PR](https://github.com/tensorflow/tfjs/pull/4755) adds one of the operations I mentioned previously. I haven't signed the CLA on behalf of my employer yet but will do it soon. I'd appreciate your review. Thanks in advance!

**Comment by pyu10055** [comment]
@fneubaum-sulvo Thank you, will review the PR.
