### ISSUE TITLE
cameraWithTensor Component does not allow Expo Camera Methods

### ISSUE THREAD

**Issue by JJwilkin** [tensorflow/tfjs#4726]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Os Catalina 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: any device
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.0.1
- Browser version: N/A
- Tensorflow.js Converter Version: Not used

**Describe the current behavior**
Using the cameraWtihTensor component as described [here](https://js.tensorflow.org/api_react_native/0.5.0/#cameraWithTensors)
which extends the [Expo Camera](https://docs.expo.io/versions/latest/sdk/camera/#takepictureasync), I'm not able to call any basic Expo Camera methods, like takePictureAsync()

**Describe the expected behavior**
All props and methods of Expo.Camera should be available. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

Download repo and use expo to run [here](https://github.com/JJwilkin/Pictionary-modification/tree/takePicture)

```
import {cameraWithTensors} from '@tensorflow/tfjs-react-native';
import { Camera } from 'expo-camera';
const TensorCamera = cameraWithTensors(Camera);

<TensorCamera
...
  ref={ref => {
    this.camera = ref;
  }}
/>;
// ...
snap = async () => {
  if (this.camera) {
    let photo = await this.camera.takePictureAsync();
  }
};
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/44853346/108750437-0001a880-750f-11eb-8151-6be2132bdce7.png)

Code can be tested using this [repo](https://github.com/JJwilkin/Pictionary-modification/tree/takePicture)

**Comment by mati-a** [comment]
Maybe this help. I was having the same issue trying to call `getAvailablePictureSizesAsync` method of Expo Camera. I find that the ref of `TensorCamera` has an attribute called `camera`. So in my case i have:
```
            <TensorCamera
              ref={(ref) => {
                this.cameraRef = ref;
              }}
              onCameraReady={this.setTextureDims}
```

Then
```
  constructor(props) {
    this.setTextureDims = this.setTextureDims.bind(this);
  }

  async setTextureDims() {
    const pictureSizes = await this.cameraRef.camera.getAvailablePictureSizesAsync(
      '4:3',
    );

```

**Comment by jinjingforever** [comment]
Thanks Mati for the answer!

**Comment by JJwilkin** [comment]
@mati-a This didn't seem to solve the issue, I tried in a functional and class component. But it says the cameraRef.camera doesn't have that method available

**Comment by jinjingforever** [comment]
Hi Joshua,

Here is a sample code that works for me. I tested on iOS. Please check. Thanks!

```typescript
import React, {useState, useEffect, useRef} from 'react';
import {Text, View, Button} from 'react-native';
import {Camera} from 'expo-camera';
import * as Permissions from 'expo-permissions';
import {cameraWithTensors} from '@tensorflow/tfjs-react-native';
import * as MediaLibrary from 'expo-media-library';

const TensorCamera = cameraWithTensors(Camera);

export default function App() {
  const cameraRef = useRef();
  const [hasPermission, setHasPermission] = useState(false);

  useEffect(() => {
    (async () => {
      const {status} = await Permissions.askAsync(Permissions.CAMERA, Permissions.MEDIA_LIBRARY);
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  const takePicture = async () => {
    cameraRef.current.camera.takePictureAsync().then(result => {
      MediaLibrary.saveToLibraryAsync(result.uri);
    });
  };

  return (
    <View>
      <TensorCamera
        ref={cameraRef}
        style={{
          width: 600,
          height: 600,
        }}
        autorender={true}
        type={Camera.Constants.Type.back}
      />
      <View style={{marginTop: 50}}>
        <Button onPress={() => takePicture()} title="Take Picture">
        </Button>
      </View>
    </View>
  );
}
```

**Comment by JJwilkin** [comment]
@jinjingforever Thanks that worked!  I believe the issue was I wasn't using useRef so it was accessing the camera properly. This was very helpful!

**Comment by jinjingforever** [comment]
You are welcome! Glad it works!
