### ISSUE TITLE
How look easy program for predict using TensorFlow.js

### ISSUE THREAD

**Issue by tyt34** [tensorflow/tfjs#473]
I want to creat easy program for predict.
Example: I have array [1,2,3].  It's not difficult to guess what next number must be 4. 
For this task I was advised this library TensorFlow.js.
I look all examples on this site https://js.tensorflow.org/api/0.11.7/ but not find that I search.

Please humans, can you show easy program for that 
or
show example from other link?

**Comment by tafsiri** [comment]
Hi @tyt34, it may not be so easy for a program to guess that the next number is 4. You would need to think about how you would go about teaching a machine to guess the next number. What examples would you use? How would you tell it it is doing a good job. I suggest reading through the tutorials we have (https://js.tensorflow.org/tutorials/) and possibly exploring something like https://developers.google.com/machine-learning/crash-course/ml-intro to get a sense of what you may be able to do with machine learning.

**Comment by tyt34** [comment]
Hello @tafsiri. 
After your post, I figured it out.

I have event. It consists of 2 parts. It happens _0_ or _1_. It turns out _[0,0],[0,1],[1,0],[1,1]_.
I think it depends on the last 2-4 (may be more) such events, which too happens _0_ or _1_.
Therefore, I think, for example, to do this:
Input _[[0,0],[0,0],[0,0]]_ , output _[0,0]_.

Suppose I have information about already past events that look like this:
_1,1,0,1,0,0,1,0,1,1,1,0,0,0._
Input _[[1,1],[0,1],[0,0]]_ , output _[1,0]_
Input _[[0,1],[0,0],[1,0]]_ , output _[1,1]_
Input _[[0,0],[1,0],[1,1]]_ , output _[1,0]_
Input _[[1,0],[1,1],[1,0]]_ , output _[0,0]_
Input _[[1,1],[1,0],[0,0]]_ , output _[?? , ??]_ (Here I get my prediction)

Do you think that I'm thinking the right way?

**Comment by tafsiri** [comment]
@tyt34 Yes i'd say you are on the right path, if you have the training data, you should be able to try it and see how it performs.
