### ISSUE TITLE
speech-command playRawAudio plays blank audio

### ISSUE THREAD

**Issue by adotnusiyan** [tensorflow/tfjs#4736]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution: Windows10
- TensorFlow.js installed from: npm
- TensorFlow.js version: 3.2.0
- speech-command version: 0.5.2
- Browser version: Version 88.0.4324.192 (Official Build) (x86_64)

**Describe the current behavior**
I'm trying to use [playRawAudio](https://github.com/tensorflow/tfjs-models/blob/59c6ecb1d6bddfe287d4a6559ae1a70f5b423a8d/speech-commands/src/index.ts#L84) method by providing `RawAudioData` object. `Float32Array` as [data](https://github.com/tensorflow/tfjs-models/blob/59c6ecb1d6bddfe287d4a6559ae1a70f5b423a8d/speech-commands/src/types.ts#L727) and `sampleRateHz:44100`. 

There's an audio playing with the same duration of `data`, but the audio is blank (no audio)

I provided `Float32Array` array from `SpeechCommandRecognizerResult.spectrogram.data` in `listen` function, then concatenated the array using `concatenateFloat32Arrays` util function

**Describe the expected behavior**
Expected to play the correct audio, not a blank audio.

**Standalone code to reproduce the issue**
[Example in Codesandbox](https://codesandbox.io/s/tfjs-listen-recognize-scores-iyrjd)

**Comment by zipweight** [comment]
@adotnusiyan 
did you find a solution? 
i also need this and got same issue

**Comment by adotnusiyan** [comment]
Not yet.
Hopefully waiting @lina128

**Comment by lina128** [comment]
Hi @adotnusiyan and @zipweight , I'm investigating this, I'm seeing a sampleRate mismatch error in my browser, not sure if it is related, just fyi: https://github.com/tensorflow/tfjs-models/pull/612

**Comment by lina128** [comment]
Hi @adotnusiyan, I looked at the code you provided, it seems you provide the spectrum data to the playRawAudio function. You need to provide raw audio sound, not the spectrum data.

**Comment by adotnusiyan** [comment]
@lina128 

How to play the spectrum data as audio?

Or how can I get raw audio data from listen function?

Thanks

**Comment by lina128** [comment]
If you have a transferRecognizer with collectExample({includeRawAudio = true}). And then get the rawAudio from tranferRecognizer.getExamples()[0].example.rawAudio.

If you just want a generic solution, you need to implement your own.

**Comment by adotnusiyan** [comment]
@lina128 I tried your suggestion with basic code from [the example in README](https://github.com/tensorflow/tfjs-models/tree/b5d49c0f5ba2057cc29b40317126c5f182495f96/speech-commands#transfer-learning) and the audio doesn't sound right. You can hear some distortion/glitching in the audio

[You can try it yourself in this example](https://codesandbox.io/s/tfjs-play-raw-audio-v0y12)
