### ISSUE TITLE
Add jsdoc strings for Layers tf.metrics.*

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#474]
We should add docs to these functions:

https://js.tensorflow.org/api/0.11.7/#metrics.binaryAccuracy

**Comment by caisq** [comment]
This should have been fixed by https://github.com/tensorflow/tfjs-layers/pull/267

**Comment by caisq** [comment]
The fix will be reflected on the website after the next release of @tensorflow/tfjs and website push.
