### ISSUE TITLE
arraySync gets tripped up by complex numbers

### ISSUE THREAD

**Issue by joonoro** [tensorflow/tfjs#4759]
**System information**
Using Tensorflow JS 3.2.0 in NodeJS v15.5.0, MacOS 10.15.7 (19H512)

**Describe the current behavior**

Running the below code produces the error:

```
Error: [32,1025] does not match the input size 65600.
```

**Describe the expected behavior**

The code should return a 2-dimensional array of size 32800.

**Standalone code to reproduce the issue**
```javascript
let tf = require('@tensorflow/tfjs')

let samples = new Float32Array(18048);

let res = tf.signal.stft(tf.tensor(samples), 2048, 512, 2048);

console.log(res.arraySync());
```

**Other info / logs**

Tensor info after running stft:

```
Tensor {
  kept: false,
  isDisposedInternal: false,
  shape: [ 32, 1025 ],
  dtype: 'complex64',
  size: 32800,
  strides: [ 1025 ],
  dataId: { id: 3014054 },
  id: 453,
  rankType: '2',
  scopeId: 0
}
```

**Comment by joonoro** [comment]
Ok I think I see what's going on, it's having trouble with the real and imaginary parts of the complex number right?

**Comment by joonoro** [comment]
Well, in my case I can solve this because I need to run `abs()` on my Tensor anyways which gets rid of the imaginary part.

**Comment by joonoro** [comment]
Ok so, after reading a bit more I'll summarize:

When complex64 was added (https://github.com/tensorflow/tfjs/issues/565), it was decided that dataSync should return both parts of the complex number. That's why the array returned by dataSync is twice as big. 

However, when arraySync was added this wasn't taken into account, which is why it prints an error. It's trying to fit the bigger array into the same shape.

So dataSync is working correctly, but arraySync is not. A potential fix for arraySync would be to change it's shape to return an array where each element is a pair of real/imaginary parts of the complex number, to mirror the behavior of dataSync.

I assume the above also applies to the non-sync'd version of arraySync.

**Comment by jinjingforever** [comment]
Thanks for the report Joonatan!
