### ISSUE TITLE
Detecting texture dimensions while using Expo Camera ( it is not supported currently )

### ISSUE THREAD

**Issue by ahtrahdis7** [tensorflow/tfjs#4760]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by rthadur** [comment]
cc @mattsoulanille

**Comment by carrycooldude** [comment]
@ahtrahdis7 If possible can you share the source code for which you are using the expo camera component
