### ISSUE TITLE
Existing trained models not classifying cases of severe toxicity. (Toxicity classifier)

### ISSUE THREAD

**Issue by proton9** [tensorflow/tfjs#4762]
The sample text in question which did not get flagged as severe toxic 
![3333](https://user-images.githubusercontent.com/24552372/109404229-f30b0c00-7989-11eb-98c1-20d1c3099dd7.PNG)

https://twitter.com/Twictator/status/3315018819

I'm making a simple app that feeds a list of tweets to the classifier to help with my learning.
I only just started with machine learning and haven't yet reached the training models part of my learning so far yet,
What I want to know is the definition 'severe_toxic'

**Comment by rthadur** [comment]
please refer to this document https://github.com/conversationai/conversationai.github.io/blob/master/crowdsourcing_annotation_schemes/toxicity_with_subattributes.md which explains about different classification. Thank you
