### ISSUE TITLE
Backend WASM does not implement kernel ResizeNearestNeighbor

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4766]
attempting to run nudenet model using `wasm` backend  
converted from tf saved to tfjs graph using tensorflowjs_convert:

```log
engine.js:391 Uncaught (in promise) Error: Kernel 'ResizeNearestNeighbor' not registered for backend 'wasm'
    at Engine2.runKernel (engine.js:391)
    at resizeNearestNeighbor_ (resize_nearest_neighbor.js:60)
    at Object.resizeNearestNeighbor__op [as resizeNearestNeighbor] (operation.js:44)
    at executeOp$9 (image_executor.js:34)
    at operation_executor.js:62
    at engine.js:327
    at Engine2.scopedRun (engine.js:337)
    at Engine2.tidy (engine.js:326)
    at tidy (globals.js:175)
    at operation_executor.js:62
```

same model works fine using `weblgl` backend  

as per #4386 it has been implemented, but it seems it was implemented for `cpu` backend only although title specifies `wasm`?

environment: tfjs 3.2.0 on chrome 88 on ubuntu 20.10

**Comment by rthadur** [comment]
cc @lina128 @pyu10055 @mattsoulanille

**Comment by davidstrahm** [comment]
@jinjingforever @rthadur I second this, asking for update. Have made a benchmark with yolov5n model converted to tfjs. Inference takes up to 100ms on cpu / webgl backend on my laptop, which means on a phone this would unfortunately be too slow for real-time application.

**Comment by rthadur** [comment]
@all will share the request with team and let you know. Thank you

**Comment by mattsoulanille** [comment]
Fixed by https://github.com/tensorflow/tfjs/pull/6524
