### ISSUE TITLE
No easy way to change the input shapes for a built model for transfer learning

### ISSUE THREAD

**Issue by aman-tiwari** [tensorflow/tfjs#477]
#### TensorFlow.js version
0.11.7

#### Browser version
N/A

#### Describe the problem or feature request
If I load a pretrained TFJS model, there is no easy way to change the input shapes it takes in.
For instance, if I load [`Mobilenet`](https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet), and I want to perform transfer learning on it, I have no easy way to get the model to take different shapes (even if the model is fully convolutional).

#### Code to reproduce the bug / link to feature request
```js
  const model = await tf.loadModel('https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json')
  
  const test = tf.zeros([1, 512, 512, 3])
  const preds = model.predict(test) 
```

#### Expected output:
`preds` is a tensor of the output of the model

#### Actual output:
 ```js
Error: Error when checking : expected input_1 to have shape [null,224,224,3] but got array with shape [1,512,512,3].
```

This is especially needed when you need to transfer some layers of a loaded model into another:
```js
const someLayers = tf.sequential({layers: model.layers.slice(0, 5)})
someLayers.predict(test)
```

It would be good if there was some way to `unbuild` a layer, or if there was some easy way to clone a layer (keeping everything but the shapes & topology), potentially like:

```js
const convLayers = model.layers.slice(0, 5).map(l => l.unbuilt()) // or l.clone(), l.clone({withoutShape: true}), etc

const someLayers = tf.sequential({layers: convLayers})
```

WDYT? I would be happy to author a PR for it unless someone else is working on something similar.

**Comment by nsthorat** [comment]
cc @caisq

**Comment by caisq** [comment]
@aman-tiwari I'm not sure how the "unbuilding" works. The shapes of the weights and output tensors of layers are determined by the input image shape. In other words, if you change the size of the input image, everything changes in the model. 

It seems to me more straightforward to use one of the two following approaches:

1) Before you feed your new image to the model, resample it to the required shape. This can probably be done with some sort of HTML5 canvas tricks.

2) Add a "image resampling" layer type to tensorflow.js and/or Keras, and create a new sequential model with the resampling layer as the first layer and the original model as the second layer (note that sequential models can be nested.) Keras doesn't have such a layer AFAIK. The closest is UpSampling2D, which allows you to change the size of the image only by positive integer factors.

**Comment by aman-tiwari** [comment]
Essentially what I'm looking for is a way to get a copy of the layer that has the same weights but no input/output shape information (i.e, before the layer was put into a model), as it was before it was built, such that I could use the layer in an other model.

**Comment by caisq** [comment]
@aman-tiwari I still don't quite understand your proposal. The shape of the weights are tied to the input image shape.

**Comment by nsthorat** [comment]
@caisq, many fully convolutional models are not actually explicitly coupled to the input shape. If you were able to reflow the shapes from a 32x32x3 input instead of a 227x227x3 input, you would find that the prediction is still a 1000D tensor. Doing an upsample or downsample will not have the same effect because the filters will be operating on a up/downsampled input.

Aman could do this by simply reconstituting a new model with all the same weights, but we wanted to understand if you knew of an easier way.

**Comment by aman-tiwari** [comment]
This works for now:
```ts
type ShapeMap = { [name: string]: [number, number, number, number] };

function mapInputShapes<T extends tf.Model>(model: T, newShapeMap: ShapeMap) {
  const cfg = {...model.getConfig()};
  cfg.layers = (cfg.layers as any[]).map(l => {
    if(l.name in newShapeMap) {
      return {...l, config: {
        ...l.config,
        batchInputShape: newShapeMap[l.name]
      }};
    } else {
      return l;
    }
  });
  //tslint:disable-next-line
  const [cls, fromConfig] = tf.serialization.SerializationMap.getMap().classNameMap[model.getClassName()]

  return fromConfig(cls, cfg) as T;
}
```

But not sure if `tf.serialization.SerializationMap.getMap().classNameMap` is public or whether this will break for certain kinds of models.

**Comment by jtoy** [comment]
I have run into the same issue.

**Comment by faceshape** [comment]
I'm also running into this issue, I have a fully convolutional network for segmentation and would like to avoid resizing and cropping images.

Just wondering if there's any updates? Is this going to be implemented soon ? If not, do you have any pointers on where I can look to implement it myself ?

Thanks!

**Comment by BenjaminWegener** [comment]
solved it for me by changing the model.json directly to
`(...)"layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, null, null, 3],(...)`

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by schematical** [comment]
I used @aman-tiwari's solution above but now getting this:
```
Input 0 is incompatible with layer dense_Dense1: expected axis -1 of input shape to have value 25088 but got shape 51,38400.
``` 
Any ideas?

**Comment by gaikwadrahul8** [comment]
Hi, @aman-tiwari 

Apologize for the delayed response and Do you still need help on this issue ? if not could you please close this issue now ? Thank you!

@schematical, Did you try above workaround and referred above comments please, Is it resolving your issue or not ? if not I would request you to please submit new issue with your code and error log by following issue template [here](https://github.com/tensorflow/tfjs/issues/new/choose).
