### ISSUE TITLE
Tfjs error with macOS 11 on m1 chip

### ISSUE THREAD

**Issue by MeiyappanKannappa** [tensorflow/tfjs#4775]
Trying to run basic get started example with tfjs in max m1 chip and getting illegal argument : 4 error. Is there anything specific need to be done for Mac m1 chip .

**Comment by rthadur** [comment]
There is already issue opened here for M1 Chip , currently tfjs does not work well with M1 , please check back here https://github.com/tensorflow/tfjs/issues/4775
