### ISSUE TITLE
Error: Cannot find name 'EmscriptenModule'. when using wasm as a backend in Angular

### ISSUE THREAD

**Issue by sivarajakani** [tensorflow/tfjs#4793]
### Error: node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts:18:44 - error TS2304: Cannot find name 'EmscriptenModule'.

I got this error while executing this line in Angular.
`import '@tensorflow/tfjs-backend-wasm';`

Also, I installed and activated Emscripten SDK (version 2.0.14), EMSDK path also declared.
`./emsdk activate 2.0.14
&& source ./emsdk_env.sh
&& echo $EMSDK`
>   '/home/emsdk'

**Comment by rthadur** [comment]
@sivarajakani i see you already commented in a related issue https://github.com/tensorflow/tfjs/issues/3866#issuecomment-793419787 , will wait for @jinjingforever response. Thank you for your patience.
