### ISSUE TITLE
Threaded SIMD tests for the wasm backend crash the browser

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#4796]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): 3.2
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian rodete
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version: Chrome ~88
- Tensorflow.js Converter Version:

**Describe the current behavior**
Threaded SIMD tests for the wasm backend create a new webworker for each test, crashing the page with hundreds of webworkers.

**Describe the expected behavior**
Each test does not have its own webworker, or webworkers are cleaned up after the test is finished.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mattsoulanille** [comment]
Bundling all tests (with e.g. esbuild) does not fix this. While test files are no longer individually requested from Karma, each test still re-initializes the wasm backend (requesting the `.wasm` file each time) and creates a new webworker.

**Comment by carrycooldude** [comment]
Hey @mattsoulanille, Actually for test and fixed-width SIMD maybe there is some issues with Web Assembly , Can you help me out in this
![image](https://user-images.githubusercontent.com/41143496/110775224-ade9b280-8284-11eb-8ec7-f0e95abb9f78.png)
