### ISSUE TITLE
Expose `LayerVariable` in module exports

### ISSUE THREAD

**Issue by asross** [tensorflow/tfjs#480]
#### TensorFlow.js version

0.11.7

#### Describe the problem or feature request

When developing TypeScript code that interfaces with the Layers API, it would be convenient to be able to import `LayerVariable` from `@tensorflow/tfjs-layers` (without having to go through `@tensorflow/tfjs-layers/dist/variables`, which is problematic).

**Comment by tafsiri** [comment]
Looks like this was fixed in https://github.com/tensorflow/tfjs-layers/pull/255
