### ISSUE TITLE
After setting TensorflowJS model's backend as WASM is too slow

### ISSUE THREAD

**Issue by sivarajakani** [tensorflow/tfjs#4800]
It's an **LSTM model.** The model total size is **23.2 MB**(model.json, group1.bin, ...).

### Before setting a backend as wasm, the prediction runtime is <1500ms, after setting wasm >5000ms.
I use this set of code to change the backend as wasm.
```
setWasmPaths({
	'tfjs-backend-wasm.wasm': 'assets/wasm/tfjs-backend-wasm.wasm',
	'tfjs-backend-wasm-simd.wasm': 'assets/wasm/tfjs-backend-wasm-simd.wasm',
	'tfjs-backend-wasm-threaded-simd.wasm': 'assets/wasm/tfjs-backend-wasm-threaded-simd.wasm'
});

setBackend('wasm').then(() => {...}
```
**Is it possible to fix this issue?**

TensorflowJS - 3.2.0
Angular - 11.2.3

Brave - 1.21.73 
Chromium - 89.0.4389.72

OS - ubuntu 20.04.2

**Comment by sivarajakani** [comment]
### I used this code snippet for wasm.
```
import { loadLayersModel, LayersModel, Tensor, squeeze, setBackend } from '@tensorflow/tfjs';
import { setWasmPaths } from "@tensorflow/tfjs-backend-wasm";

private model: LayersModel;
private topValues: number = 5;
private minPredictionValue = 0.7;

constructor() {
    setWasmPaths({
        'tfjs-backend-wasm.wasm': 'assets/wasm/tfjs-backend-wasm.wasm',
        'tfjs-backend-wasm-simd.wasm': 'assets/wasm/tfjs-backend-wasm-simd.wasm',
        'tfjs-backend-wasm-threaded-simd.wasm': 'assets/wasm/tfjs-backend-wasm-threaded-simd.wasm'
    });
    
    setBackend('wasm').then(() => {
        this.loadModel();
    }
}

private loadModel(): void {
    const modelURL = "assets/model/model.json";
    
    loadLayersModel(modelURL).then(
        model => {
            this.model = model;
        },
        error => alert(error)
    );
}

private predict(input: string): number[] {
    const predictedValue = this.model.predict(input);
    const predictedIndex = this.decodePrediction(predictedValue);

    return predictedIndex;
}

private decodePrediction(predictedValue: Tensor): number[] {
    const {values, indices} = squeeze(predictedValue, [0]).topk(this.topValues);
    
    const valueArray = values.dataSync();
    const indexArray = indices.dataSync();
    
    let output: number[] = [];
    
    for(let i = 0; i < this.topValues; i++) {
    
        if(valueArray[i] > this.minPredictionValue) {
            output[i] = indexArray[i];
        } else {
            break;
        }
    }
    
    return output; 
}
```

### Before using wasm, I used this code snippet.
```
...
constructor() {
    this.loadModel();
}
...
```

**Comment by rthadur** [comment]
is it possible to share the model ? or similar model which we can use for reproduction ?

**Comment by sivarajakani** [comment]
[I modified the model from this](https://keras.io/examples/generative/lstm_character_level_text_generation/), other processes are the same as this. [JS model is here](https://drive.google.com/drive/folders/1kvcKukV6fEjgB-J_HsOCwnXI8N-YXHIW?usp=sharing)

**Comment by sivarajakani** [comment]
Any updates? @rthadur

**Comment by sivarajakani** [comment]
Any updates? @rthadur

**Comment by wingman-jr-addon** [comment]
@sivarajakani Quick question: is the default backend (before you set it) WebGL? If so, you are probably just seeing the difference in performance between the two backends on your machine. As an example: on my machine, WASM is often about 10x slower than WebGL for a MobileNetV2 prediction, but for someone who uses my project, WASM performs faster than WebGL. So it can vary a lot based on the setup.

**Comment by sivarajakani** [comment]
**is the default backend (before you set it) WebGL?**

I think CPU is the default backend in TensorFlowJS, but I'm not sure about that. So I tried CPU and WebGL. WebGL runtime same as the default runtime, and the CPU runtime is greater than the default runtime. From these results, I confirmed WebGL is the default backend in my project.

Thank you, @wingman-jr-addon.
