### ISSUE TITLE
Crash installing tfjs-node-gpu: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by sbrl** [tensorflow/tfjs#4802]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.10, Ubuntu 18.04, CentOS 7.2.1511
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow.js installed from (npm or script link): `"@tensorflow/tfjs-node-gpu": "^3.0.0"` in package.json
- TensorFlow.js version: `"@tensorflow/tfjs-node-gpu": "^3.0.0"` in package.json
- CUDA/cuDNN version: CUDA 10.0, CuDNN 7

**Describe the problem**

Crash when attempting to install `@tensorflow/tfjs-node-gpu`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Use `git clone` to clone down a pre-existing project that depends on `@tensorflow/tfjs-node-gpu`
2. `cd` into the directory
3. Run `npm install`

**Any other info / logs**

Installation logs: [tfjs-node-gpu-install-log.txt](https://github.com/tensorflow/tfjs/files/6117941/tfjs-node-gpu-install-log.txt)

Note that I only have admin rights over the Ubuntu 20.10 machine.

Note also that I reliably get the same issue inside the `nvcr.io/nvidia/tensorflow:19.02-py3` Docker container.

**Comment by rthadur** [comment]
@pyu10055 here is the related issue which was occurring on windows https://github.com/tensorflow/tfjs/issues/4401#issuecomment-795773373 , I tried on Mac and o see no issues.

**Comment by pyu10055** [comment]
@sbrl Sorry I was not able to reproduce this error, I tried the same docker file nvcr.io/nvidia/tensorflow:19.02-py3 and installed node both (v14.16.0, v15.11.0) and npm v7.6.0, tfjs-node-gpu v3.3.0 was install successfully. 

can you upgrade node to 15.11.0 and try again?

**Comment by sbrl** [comment]
Huh, that's really odd. I've tried on all 3 of those machines again now and I can't reproduce it either - even with Node.js v15.5.0. Perhaps it was a transitory issue that was fixed by someone. Though why it would mysteriously affect all these different machines all at the same time I don't know.

I'll close this for now, but if I experience the issue again I'll reopen.

Thanks for the help, @pyu10055!
