### ISSUE TITLE
BodyPix - drawBokehEffect stretched background on Safari Browsers (MacOS - iOS)

### ISSUE THREAD

**Issue by guillaume250** [tensorflow/tfjs#4808]
**System information**
- Wrote custom code and tried stock examples.
- macOS Big Sur 11.1
- Safari iOS browser
- TensorFlow.js installed from (npm and script link): 1.2 for script link & tfjs-core 3.1.0 npm version
- Browser version: Safari Version 14.0.2 (16610.3.7.1.9)
- Tensorflow.js Converter Version: 3.1.0

**Describe the current behavior**
On Safari browsers when blurring the background of video tracks coming from a `navigator.mediaDevices.getUserMedia` stream, the blurred background seems stretched. 

Assuming this is a Safari only issue, I think an aspect ratio fix on the [cpuBlur](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/blur.ts) function should do it. 😉

**Describe the expected behavior**
drawBokehEffect expected behavior 

**Standalone code to reproduce the issue**
Opening the codepen below in Safari should immediately reproduce the bug.
https://codepen.io/guillaume250/pen/ZEBVPaG

- Cheers

**Comment by mattsoulanille** [comment]
Hi @guillaume250. Thanks for the codepen reproduction! `drawBokehEffect` [bases its output dimensions on the video element's `width` and `height` properties](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/output_rendering_util.ts#L503-L504) (although perhaps it shouldn't). If you set the video element's width and height to match the camera's aspect ratio, the output should have the correct aspect ratio. See [my fork of your codepen](https://codepen.io/mattsoulanille/pen/eYBxvqM?editors=1111) as an example. 

Feel free to re-open if this doesn't solve the issue.

**Comment by guillaume250** [comment]
Hi @mattsoulanille, thanks for the quick response, and the fork.
I just opened your fork in a safari browser and still see the same issue.



<img width="913" alt="Screen Shot 2021-03-15 at 1 36 47 PM" src="https://user-images.githubusercontent.com/26730301/111196976-4a1cfd80-8594-11eb-9bab-1e707f1d37ad.png">
 
<img width="912" alt="Screen Shot 2021-03-15 at 1 37 31 PM" src="https://user-images.githubusercontent.com/26730301/111197107-73d62480-8594-11eb-9774-2f8a433b56f7.png">

**Comment by mattsoulanille** [comment]
I initially thought your report was about the incorrect aspect ratio of the output image, but I've been able to reproduce the issue you're seeing on Safari. I'll take a look. Thanks!

**Comment by alexopoulos7** [comment]
Any updates on this issue? @mattsoulanille how have you overcome issue?

**Comment by rthadur** [comment]
can you please check with latest body segmentation model and let us know if this is resolved ?

**Comment by guillaume250** [comment]
Just checked with `body-pix@2.2.0` CDN version. Issue still there

**Comment by rthadur** [comment]
@guillaume250 we will not be updating body-pix , there is a new body segmentation  model here https://blog.tensorflow.org/2022/01/body-segmentation.html , did you get chance to check this out? Thank you
