### ISSUE TITLE
TypeError: Cannot read property 'length' of null (dilations is null in depthwiseConv2dNativeBackpropInput_)

### ISSUE THREAD

**Issue by opiepj** [tensorflow/tfjs#4811]
**System information**
- From the [simple-object-detection](https://github.com/tensorflow/tfjs-examples/tree/master/simple-object-detection) example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): tried both on Mac OS and Windows  and Windows WSL
- TensorFlow.js installed from (npm or script link): npm library
- TensorFlow.js version (use command below): tested on ^2.6.0 and ^3.3.0

**Describe the current behavior**
Playing with the [simple-object-detection](https://github.com/tensorflow/tfjs-examples/tree/master/simple-object-detection) example. Ran `npm run train` and the following happens

Step 1: (Phase 1 of 2: initial transfer learning) - this runs without any problems
```javascript
  const tBegin = tf.util.now();
  console.log(`Generating ${args.numExamples} training data...`);
  const { images, targets } = await trainingData();
  const { model, fineTuningLayers } = await buildObjectDetectionModel();
  model.compile({ loss: customLossFunction, optimizer: tf.train.rmsprop(5e-3) });
  model.summary();

  // Initial phase of transfer learning.
  // console.log('Images Shape:', images.shape);
  // console.log('Targets Shape', targets.shape);
  console.log('Phase 1 of 2: initial transfer learning');
  await model.fit(images, targets, {
    epochs: args.initialTransferEpochs,
    batchSize: args.batchSize,
    validationSplit: args.validationSplit,
    callbacks: args.logDir == null ? null : tfn.node.tensorBoard(args.logDir, {
      updateFreq: args.logUpdateFreq
    })
  });
```

Step 2: (Phase 2 of 2: fine-tuning phase) - this is where it breaks
```javascript
  // Fine-tuning phase of transfer learning.
  // Unfreeze layers for fine-tuning.
  for (const layer of fineTuningLayers) {
    console.log(fineTuningLayers);
    layer.trainable = true;
  }
  model.compile({ loss: customLossFunction, optimizer: tf.train.rmsprop(2e-3) });
  model.summary();

  // Do fine-tuning.
  // The batch size is reduced to avoid CPU/GPU OOM. This has
  // to do with the unfreezing of the fine-tuning layers above,
  // which leads to higher memory consumption during backpropagation.
  console.log('Phase 2 of 2: fine-tuning phase. Top Layer Name:', topLayerName, 'Group Names:', topLayerGroupNames);
  await model.fit(images, targets, {
    epochs: args.fineTuningEpochs,
    batchSize: Math.round(args.batchSize / 2),
    validationSplit: args.validationSplit,
    callbacks: args.logDir == null ? null : tfn.node.tensorBoard(args.logDir, {
      updateFreq: args.logUpdateFreq
    })
  });
```

I get this error after `model.fit(images, targets, {...` is executed:

![image](https://user-images.githubusercontent.com/7416676/111085676-9bb28300-84d5-11eb-9cdf-af32be17e081.png)

I debugged down a bit further - turns out that somewhere at the kernel input (I think??), it's giving a dilation value of `null` (should be `number` or `number[]`).

![image](https://user-images.githubusercontent.com/7416676/111085448-ab7d9780-84d4-11eb-8226-fe246256050d.png)

![image](https://user-images.githubusercontent.com/7416676/111085562-13cc7900-84d5-11eb-82f8-31eed68c301c.png)

Please advise, I'm going off the tfjs-examples repo simple-object-dectection
https://github.com/tensorflow/tfjs-examples/blob/master/simple-object-detection/package.json

...then just running `npm install` and `npm run train`

**Comment by opiepj** [comment]
Still broken, but found a workaround (though probably the model is not even transfer learning)

1. train.js import `@tensorflow/tfjs-node` rather than `@tensorflow/tfjs`
2. replaced `const topLayerGroupNames = ['conv_pw_9', 'conv_pw_10', 'conv_pw_11'];` to `const topLayerGroupNames = [ 'conv_pw_11'];

Both of those had to happen for it to work, doing one without the other had the same problem... not sure why.

**Comment by schematical** [comment]
@opiepj #2 did it for me. You are my hero!

**Comment by rthadur** [comment]
@opiepj can we close this issue ?

**Comment by opiepj** [comment]
No

**Comment by opiepj** [comment]
> @opiepj #2 did it for me. You are my hero!

Sick... but you still have frozen layers

**Comment by KaivnD** [comment]
+1

**Comment by KaivnD** [comment]
After three month, anything new?

**Comment by rthadur** [comment]
Related PR has been merged , the change will be available in next release. Thank you
