### ISSUE TITLE
Detecting more than 1 hand with HandPose

### ISSUE THREAD

**Issue by jaygit123** [tensorflow/tfjs#4820]
Hello Team,
Great work with hand pose detection. 
Wish to know when the feature of detecting more than one hand will be made available. Also, is there a workaround/tweak now to enable detection of both hands of a person?

Regards,
Jay

**Comment by jaygit123** [comment]
Hi @pyu10055 , @lina128 ,
Any update on this issue please? 

Regards
Jay

**Comment by masoudcharkhabi** [comment]
Thank you for feature request @jaygit123! @lina128 and team are actually working on a multi-hand extension to HandPose. Stay tuned!

**Comment by rthadur** [comment]
Please check out latest handpose with multiple poses here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection , thank you
