### ISSUE TITLE
Tensorflow not tree shaken when embedded in library but not used

### ISSUE THREAD

**Issue by CyrilGC** [tensorflow/tfjs#4828]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Only tried on Windows 10, Chrome 89.0.4389.82
- TensorFlow.js installed from (npm or script link): from npm
- TensorFlow.js version: 3.3.0

I'm creating a library where some parts are using TensorFlow, and some aren't. I use Rollup to create my lib, and also to test it. The problem is that when I use classes from my lib that do not use TensorFlow, I still see the code from TensorFlow included in the bundle. The rest of my lib that I don't use is correctly tree shaken from the final bundle, but not tensorflow.

Below is the rollup config for generating my lib. Note that I'm generating an esm and umd version. I use the esm version in the test app where I'm expecting TensorFlow to be tree shaken.

```
import typescript from '@rollup/plugin-typescript';
import commonjs from '@rollup/plugin-commonjs';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { terser } from "rollup-plugin-terser";
import nodePolyfills from 'rollup-plugin-node-polyfills';
import alias from 'rollup-plugin-alias';
import copy from 'rollup-plugin-copy';
import visualizer from 'rollup-plugin-visualizer';

const path = require('path');

const dev = (process.env.NODE_ENV !== 'production');
console.log(`running in ${dev ? 'development' : 'production'} mode`);

const sourcemap = dev ? 'inline' : false;


export default [
    {
        input: 'src/sdk/index.ts',
        output: [
            {
                file: 'dist/library/mylib.esm.js',
                format: 'esm',
                name: 'mylib',
            },
            {
                file: 'dist/library/mylib.js',
                format: 'umd',
                name: 'mylib',
            }
        ],
        watch: {
            include: './src/sdk/**',
            clearScreen: false,
        },
        plugins: [
            alias({
                entries: [
                    {
                        find: /@tensorflow\/tfjs$/,
                        replacement: path.resolve(__dirname, './custom_tfjs/custom_tfjs.js'),
                    },
                    {
                        find: /@tensorflow\/tfjs-core$/,
                        replacement: path.resolve(__dirname, './custom_tfjs/custom_tfjs_core.js'),
                    },
                    {
                        find: 'tensorflow/tfjs-core/dist/ops/ops_for_converter',
                        replacement: path.resolve(__dirname, './custom_tfjs/custom_ops_for_converter.js'),
                    },
                ],
            }),
            nodePolyfills(),
            nodeResolve({
                browser: true,
                preferBuiltins: false,
            }),
            commonjs(),
            typescript(),
            !dev && terser(),
        ]
    },
];
```

When I inspect the lib output, I see some Object.defineProperty like this one for instance:
```
Object.defineProperty(Tensor, Symbol.hasInstance, {
    value: (instance) => {
        // Implementation note: we should use properties of the object that will be
        // defined before the constructor body has finished executing (methods).
        // This is because when this code is transpiled by babel, babel will call
        // classCallCheck before the constructor body is run.
        // See https://github.com/tensorflow/tfjs/issues/3384 for backstory.
        return !!instance && instance.data != null && instance.dataSync != null &&
            instance.throwIfDisposed != null;
    }
});
```
which from what I understand create side effects. 

I tried to play with the treeshake option of the nodeResolve plugin but that didn't help.

I'm not super familiar with Rollup so maybe I'm missing something.

Any help would be appreciated.

**Comment by gaikwadrahul8** [comment]
Hi, @CyrilGC 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
