### ISSUE TITLE
Error dumping weights, duplicate weight name block1_conv1/kernel

### ISSUE THREAD

**Issue by jackfrost1411** [tensorflow/tfjs#4830]
```
import tensorflowjs as tfjs
tfjs.converters.save_keras_model(Xception_unet, 'connt')
#!tensorflowjs_converter --input_format=keras /content/a.h5 /content/
```
Tried both the ways to convert my keras model into tfjs model. but ended up with the error:
**_Error dumping weights, duplicate weight name block1_conv1/kernel_**

![Capture](https://user-images.githubusercontent.com/48760936/111568047-08739900-87c6-11eb-9f95-461f1b38f20e.PNG)

ANY IDEA HOW TO RESOLVE THIS ISSUE!!?

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jackfrost1411** [comment]
I resolved this issue by changing the names of the layers.
