### ISSUE TITLE
How does tfjs handle memory when GC occurs

### ISSUE THREAD

**Issue by WenheLI** [tensorflow/tfjs#4832]
From the official document, we find that tfjs can automatically handle tensor memory management when GC occurs. However, this does not happen in our practice.
Below is a snippet of code to reproduce it:

```js
const tf = require('@tensorflow/tfjs');

const wait = () => new Promise((resolve) => {
  setTimeout(resolve, 1000);
});
const main = async () => {
  const makeFeature = () => tf.ones([100]);
  const makeLabel = () => 1;

  for (let i = 0; i < 1; i++) {
    for (let j = 0; j < 2; j++) {
      let xs = tf.stack([makeFeature(), makeFeature(), makeFeature()]);
      let ys = tf.stack([tf.oneHot(makeLabel(), 2), tf.oneHot(makeLabel(), 2), tf.oneHot(makeLabel(), 2)]);
      // this will not delete the tensor from memory automatically.
      //xs = null
      xs.dispose()
      await wait()      
    }
    console.log(tf.memory())
  }
}

main();

```

**Comment by pyu10055** [comment]
@WenheLI I believe if you are using WebGL backend, which is the default backend if you using the union package, the tensor dispose needs to be manually initiated or using the `tf.tidy()` block.
Can you link to the document where we stated differently? thanks
