### ISSUE TITLE
Cannot raise UnsupportedOps during a TFJS conversion

### ISSUE THREAD

**Issue by coco-moiny** [tensorflow/tfjs#4833]
**System information**

- OS Platform and Distribution: macOs Big Sur 11.2.1
- Mobile device: N/A
- TensorFlow.js installed from: npm
- TensorFlow.js version: 3.2.0
- Browser version: Chrome 89.0.4389.82
- Tensorflow.js Converter Version: 3.2.0 (tfjs converter wizard w/ Python)

I have built a MNIST estimator for testing purposes as:

```
def neural_net(features):
    """
    Build Neural net
    """
    unsup_layer = UnSupLayer( units=256, name="hd0").apply(features)
    layer_1 = tf.compat.v1.layers.dense(inputs=unsup_layer, units=256, name="hd1")
    layer_2 = tf.compat.v1.layers.dense(inputs=layer_1, units=256, name="hd2")
    out_layer = tf.compat.v1.layers.dense(inputs=unsup_layer, units=10, name="out")
    
    return out_layer
```

UnSupLayer is meant to add unsupported ops to the model that will be converted later during the pipeline. Class is built over a Dense layer as:

```
import tensorflow as tf
import numpy as np

class UnSupLayer(tf.compat.v1.layers.Dense):
    def __init__(self, units, name):
        super(UnSupLayer, self).__init__(units=units, name=name)

    def call(self, inputs):
        print("============================")
        print("======   Unsup Ops   =======")
        print("============================")
        print("Input shape: {}".format(inputs.get_shape()))
        print("Input tensor: {}".format(inputs))
        print("Input tensor type: {}".format(type(inputs)))

        inputs = self.unsuportedOps(inputs)

        return super().call(inputs)

    @tf.function
    def unsuportedOps(self, inputs):

        tf.raw_ops.IsNan(x=tf.constant([5.0, np.nan, 6.8, np.nan, np.inf]))
        tf.raw_ops.RandomStandardNormal(shape=tf.constant([1,2,3], dtype=tf.int64), dtype=tf.float64)
        tf.strings.to_hash_bucket_fast(["Hash", "Bucket", "Fast"], 3)
        return inputs
```

**Describe the current behavior**

These Ops are ignored during conversion. Even with the flags off, as:

`tensorflowjs_converter --control_flow_v2=False --input_format=tf_saved_model --metadata= --saved_model_tags=serve --signature_name=serving_default --strip_debug_ops=False --weight_shard_size_bytes=4194304 ./src/model/estimators/mnist_ops/last ./src/model/tfjs/mnist_ops; \`

The conversion is successful

**Describe the expected behavior**

Call been made in **unsuportedOps** function meant to add theses Ops during model training and so they should appear in the JSON model.

**Conversion should fail because skip unsupported Op flag is off.**

**Comment by pyu10055** [comment]
@coco-moiny I believe you are creating a tf.function named as unsuportedOps, but when the model is saved as saved model, it will only persist ops defined within the function (IsNan, RandomStandardNormal, etc).

It might be better to convert your model to tfjs-layers format and [implement custom layers](https://gist.github.com/caisq/33ed021e0c7b9d0e728cb1dce399527d) with tfjs-layers.

**Comment by coco-moiny** [comment]
I really need to use TF Estimators has a source model. 

I found out that Tensors hold their Ops history and are probably used as a base to convert. I did use isNan on the predicted class in the model function and successfully managed to have an Unsupported Ops raised.

**Comment by pyu10055** [comment]
@coco-moiny Got it, those op that does not act on the input tensor will be pruned away during the conversion. Is that you want to inject an op that can be registered in TFJS?
I think it is not that easy to do it in python, you might have to create your own TF custom op. 
But if you edit the TFJS model.json file directly, you can add node to the graph with a custom op name, then you can register the op with the custom op name in TFJS.

**Comment by coco-moiny** [comment]
Thank you
