### ISSUE TITLE
Fields kernelInitializer, kernelRegularizer and kernelConstraint are invalid for SeparableConv2D. 

### ISSUE THREAD

**Issue by jackfrost1411** [tensorflow/tfjs#4839]
When using Xception in TensorflowJS, SeparableConv2D gives this error! If it's invalid then how am I supposed to use Xception architecture that I have already trained from Keras.applications.
Any idea how to fix this issue!?

![Capture](https://user-images.githubusercontent.com/48760936/111815396-9ef8a500-8901-11eb-9cd5-ad8b3bd13d06.PNG)

**Comment by gaikwadrahul8** [comment]
Hi, @jackfrost1411 

Apologize for the delayed response and May I know are you still facing the same issue ? I see in the official documentation w.r.t [tf.layers.separableConv2d](https://js.tensorflow.org/api/latest/#layers.separableConv2d), we can pass  `kernelInitializer`, `kernelRegularizer`, `kernelConstraint` as `args` so just to confirm, are you facing this issue with `Xception` model only ?

Could you please try with latest version of `@tensorflow/tfjs@4.4.0` and check still you're facing the same issue or not ? If yes please help us with your model to replicate this issue from our end ? if have I missed something here please let me know ? Thank you!
