### ISSUE TITLE
[rn-tfjs] TensorCamera memory leak on iOS

### ISSUE THREAD

**Issue by valentinchelle** [tensorflow/tfjs#4846]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I used the code from the camera demo to extract the pose : https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx
- 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iOS
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.7.0

**Describe the current behavior**
When I compile my app with expo, and display the performance monitor, I observe that every-time the app is fast refreshed, the RAM increases of 20MB.  So I start around 300 MB and after several fast refresh I reach +600 MB

The memory leak comes from the TensorCamera, since I don't observe any RAM increase when I comment it out. RAM increases steadily even when TensorCamera doesn't receive any prop.

**Describe the expected behavior**
No increase of the RAM between two fast refresh. 

**Standalone code to reproduce the issue**

https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx

then
```
expo start
```
and then fast refresh by saving several times the same file.

**Comment by JJwilkin** [comment]
I've noticed this behaviour as well, I'm using the TensorCamera for live image classification and if i just have the camera preview open, sitting on my desk after about 4-5 minutes the app will crash from a memory issue.

**Comment by basicvisual** [comment]
@valentinchelle  I was just curious if you had faced any issue on running the realtime_demo.tsx file. I have some error executing it 
https://github.com/tensorflow/tfjs/issues/5304

**Comment by dee1ag** [comment]
still happening :(

**Comment by gaikwadrahul8** [comment]
Hi, @valentinchelle 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
