### ISSUE TITLE
Unknown op 'TensorListFromTensor'.

### ISSUE THREAD

**Issue by dusskapark** [tensorflow/tfjs#4847]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Codesandbox 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 1.7.4
- CUDA/cuDNN version:

**Describe the problem**

I found a problem that my models worked in Python, but I did not work in TFJS. My steps were below:

Step 1) Create model
I created the object detection model with my custom dataset and `efficientdet-d0`. 
You can see more details from my Colab belew:

https://colab.research.google.com/drive/1fjnVbDnHnGnILuvDTv7zAwUwIMntrC7p?usp=sharing 

Step 2) convert saved_model to web_model

```bash
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    saved_model \
    web_model
```

Step 3) import it on my Code sandbox but it didn't work

https://codesandbox.io/s/object-detection-with-tensorflow-js-forked-6r45k?file=/src/index.js

| Python | JS |
|----|----|
|<img src="https://user-images.githubusercontent.com/4177529/111897340-bdc27d00-8a62-11eb-97bb-d4992da89134.png"> | <img src="https://user-images.githubusercontent.com/4177529/111897414-37f30180-8a63-11eb-875a-781058dfbd53.png"> |

**Any other info / logs**

When I replaced my model with Kangaroo-detector from [this blog post](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)...And it worked?! I have no idea what makes this kinda difference.

<img width="1243" alt="스크린샷 2021-03-21 오후 4 39 04" src="https://user-images.githubusercontent.com/4177529/111897590-1ba39480-8a64-11eb-8f51-97e19b6b9989.png">

**Comment by rthadur** [comment]
I see you are using older version , please use latest version(3.X) as this op was added here https://github.com/tensorflow/tfjs/pull/3432. Thank you
