### ISSUE TITLE
 Unknown op 'IsNan'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()

### ISSUE THREAD

**Issue by sandhyacs** [tensorflow/tfjs#4852]
tfjs.js:41127 Uncaught TypeError: Unknown op 'IsNan'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
    at tfjs.js:41127
    at eM (tfjs.js:41129)
    at tfjs.js:41436
    at tfjs.js:9567
    at e.t.scopedRun (tfjs.js:9576)
    at e.t.tidy (tfjs.js:9560)
    at dx (tfjs.js:13205)
    at e.t.execute (tfjs.js:41422)
    at e.t.execute (tfjs.js:42063)
    at e.t.predict (tfjs.js:42040)

Model: centernet_mobilenetv2_fpn_kpts
tf version: 2.2.0
tfjs version: 2.1.0

my code:

function abc(){
		if(model !=''){
			img = tf.browser.fromPixels(video);
			const smalImg = tf.image.resizeNearestNeighbor(img, [512, 512]);
			const resized = tf.cast(smalImg, 'float32');
			t4d = tf.tensor4d(Array.from(resized.dataSync()),[1,512,512,3])
			var predictions=  model.predict(t4d).data();
			console.log("prediction:", predictions)
			let x = predictions[0]
	        let y = predictions[1]
	        let width = predictions[2]
	        let height = predictions[3]
	        drawRectangle(boxcanvas, x, y ,width, height);	
		}
			

		requestAnimationFrame(abc);
	}

**Comment by rthadur** [comment]
Related PR has been merged and will be available in next stable release, thank you.
