### ISSUE TITLE
Feature Request: add KMeans and KMeansClustering

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tfjs#486]
#### TensorFlow.js version
0.11.7
#### Browser version
-
#### Describe the problem or feature request
Please add `tf.contrib.factorization.KMeans` - https://www.tensorflow.org/api_docs/python/tf/contrib/factorization/KMeans
and `tf.contrib.factorization.KMeansClustering`
https://www.tensorflow.org/api_docs/python/tf/contrib/factorization/KMeansClustering

#### Code to reproduce the bug / link to feature request
-

**Comment by nsthorat** [comment]
Until this is out of contrib we probably won't implement this in core.

**Comment by rthadur** [comment]
There is a similar issue opened with this feature request , we will close this and track the other one.
#574
