### ISSUE TITLE
Automatically disposing tensors using a `FinalizationRegistry`

### ISSUE THREAD

**Issue by MaximeKjaer** [tensorflow/tfjs#4864]
**System information**
- TensorFlow.js version (you are using): 3.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, it's important to call `tf.tidy` and `tf.dispose` in TensorFlow.js code to avoid memory leaks.

I'm opening this issue to ask about whether the somewhat new [JavaScript `FinalizationRegistry` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) could help in that regard. This API is already [available in most major browsers and in Node.js 14.6+](https://caniuse.com/mdn-javascript_builtins_finalizationregistry). Though I'm opening this as a "feature request issue", I'm not really *requesting* the feature, I'm just interested in asking about whether this would be possible!

The idea is that a `tf.Tensor` could register a callback that automatically calls `dispose` when the `tf.Tensor` is GC'ed, which would remove the need to call `tf.tidy` or `tf.dispose` in most situations.

Here's a sketch of the idea; you can run this in node with `node --expose-gc`.

```js
function dispose(data) {
  console.log("called: dispose(", data, ")");
}
const registry = new FinalizationRegistry((data) => dispose(data));

class Tensor {
  constructor(size) {
    this.data = { dataId: 123, size, dtype: "string" }; // placeholder values
    registry.register(this, this.data); // when `this` is GC'ed, pass `this.data` to the callback
  }

  add(that) { // placeholder implementation, just here for the demo
    return new Tensor(this.data.size + that.data.size);
  }
}

function test() {
  const a = new Tensor(1);
  const b = new Tensor(2);
  console.log("add result:", a.add(b));
}

test();
global.gc();
// OUTPUT:
// add result: Tensor { data: { dataId: 123, size: 3, dtype: 'string' } }
// called: dispose( { dataId: 123, size: 3, dtype: 'string' } )
// called: dispose( { dataId: 123, size: 2, dtype: 'string' } )
// called: dispose( { dataId: 123, size: 1, dtype: 'string' } )
```

**Will this change the current api? How?**

This could be done without being a breaking change; it should be safe to release the memory backing a `tf.Tensor` once it's garbage collected (assuming that two `tf.Tensor`s can't be backed by the same data — is that a correct assumption?).

One question would be whether it should still remain possible to call `dispose` or `tidy` in order to dispose of a tensor before it's  GC'ed. I think it *should* remain an option, as it's possible that some applications would prefer to `dispose` earlier for performance reasons.

Another question is how much refactoring would be necessary to achieve this: are there any places in the current implementation that keep references to a `tf.Tensor`, and if so, could those be rewritten to only hold a `WeakRef`?

**Who will benefit with this feature?**

Everyone who has (or should have!) at least one call to `tf.tidy` or `tf.dispose` in their codebase. Codebases with a lot of `async` code could also benefit from this.

**Any Other info.**

Related discussions: #4832, #962

**Comment by rthadur** [comment]
cc @pyu10055 @lina128

**Comment by pyu10055** [comment]
@MaximeKjaer Thank you for bring up this suggestion, I think this will be definitely be a good enhancement. 
I have a couple concerns after reading through the spec:
1. We need to manage the non-JS resources allocated by the tensor (i.e. GPU texture, WASM heap), those are not visible to the JS GC. It is likely that javascript side does not need GC but GPU is OOM.
2. Looks Safari has not supported the spec yet, which would be a problem to use it as a generic solution. Users need to inspect on the browser type to determine which approach.

**Comment by MaximeKjaer** [comment]
> We need to manage the non-JS resources allocated by the tensor (i.e. GPU texture, WASM heap), those are not visible to the JS GC. It is likely that javascript side does not need GC but GPU is OOM.

This is also something I am concerned about: I'm not sure the GC pressure is high enough on the JS side to force GC before we're OOM on the external resources. A solution could be to somehow force a JS GC when the external device / process is close to OOM, but in general, GC isn't exposed like that in JS, so that's not really a possibility.

So in light of that, and having given this a bit more thought, I don't think that automatic GC of TensorFlow.js resources is currently possible. The new `FinalizationRegistry` API gets us some of the way, but is not quite enough for this. As far as I understand, browser vendors are somewhat reluctant to expose GC too much (somewhat understandably), so I don't know if this will be possible at some point in the future.

I'm therefore closing the issue for now. Thank you for the response!
