### ISSUE TITLE
tensorflow-models: Face-Landmarks-Detection does not work on Video

### ISSUE THREAD

**Issue by Alpheron** [tensorflow/tfjs#4867]
Hello,

I was trying to recently implement a sort of facial-landmark-detector in a website that I was making. However, when I try to input an `HTMLVideoElement`, it seems that it breaks only offers the points for the first frame, despite being a 30-second video with a face at all times. I'm confused as to why this may be happening because I did use the sample code that was given on the `README.md` file so it should be working ideally but as of now, I have no clue. Attached below is the code that I am running.

```
import React from "react";
import * as tf from "@tensorflow/tfjs";

export default function RunMesh() {
  tf.ready();
  const faceLandmarksDetection = require("@tensorflow-models/face-landmarks-detection");

  async function main() {
    const model = await faceLandmarksDetection.load(
      faceLandmarksDetection.SupportedPackages.mediapipeFacemesh
    );
    const predictions = await model.estimateFaces({
      input: document.querySelector("video"),
    });
    console.log(document.querySelector("video"));
    console.log(predictions.length);
    if (predictions.length > 0) {
      for (let i = 0; i < predictions.length; i++) {
        const keypoints = predictions[i].scaledMesh;

        // Log facial keypoints.
        for (let i = 0; i < keypoints.length; i++) {
          const [x, y, z] = keypoints[i];

          console.log(`Keypoint ${i}: [${x}, ${y}, ${z}]`);
        }
      }
    }
  }
  main();

  return (
    <main>
      <video
        controls
        style={{
          position: "relative",
          marginLeft: "auto",
          marginRight: "auto",
          left: 0,
          right: 0,
          textAlign: "center",
          zindex: 9,
          width: "auto",
          height: "auto",
        }}
      >
        <source src={JSON.parse(localStorage.getItem("calibration"))}></source>
      </video>
    </main>
  );
}
```
Please let me know what might be going wrong.
Thanks,
Aditya

**Comment by lina128** [comment]
Hi @Alpheron , it's hard to see what's going on with this code, can you share something we can reproduce? For example, a codepen demo or your codebase with instruction on how to setup the demo in local. Thanks.

**Comment by Alpheron** [comment]
After some quick digging, I had realized that the development framework I was using, Next.js, did not properly call the code. When running on an individual codepen, it seemed that the model was fully functional.
