### ISSUE TITLE
Dump and load KNN Classifier

### ISSUE THREAD

**Issue by rakesh4real** [tensorflow/tfjs#4868]
Hey! Is there any way to dump and load [knn classifier](https://github.com/tensorflow/tfjs-models/tree/master/knn-classifier) so that we don't have to add examples everytime using `classifier.addExample` except for the first time (while training)

Ps. Asking the question here because the repo does not have issues tab.
 
> Thanks,
> Rakesh

**Comment by rthadur** [comment]
did you get a chance to look at this discussion regarding load and save KNN classifier. https://github.com/tensorflow/tfjs/issues/633 ?

**Comment by rakesh4real** [comment]
[THIS](https://github.com/tensorflow/tfjs/issues/633#issuecomment-576218643) worked like charm! Thank you @rthadur
