### ISSUE TITLE
Allow Tensor Camera to accept RNCamera as well

### ISSUE THREAD

**Issue by JJwilkin** [tensorflow/tfjs#4873]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Currently the Tensorflow HOC available for React Native accepts an Expo Camera as a foundation for the component, the RNCamera and Expo camera share many similarities however.

**Will this change the current api? How?**
Yes, but as RNCamera is heavily based on Expo camera, the fundamental behaviour should be the same
 
**Who will benefit with this feature?**
This will allow many features for RNCamera to be used in conjuctio with tensorflow live image classification , including OCR, face recognition which is built into RNCamera
**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @JJwilkin 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and it seems like this feature haven't implemented as of now if I'm not wrong so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
