### ISSUE TITLE
Feature request: Ability to wrap a SymbolicTensor with tf.input()

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#490]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.0

... so that one can take a non-first layer of a sequential model and use it as the first layer of another model.

**Comment by caisq** [comment]
cc @nsthorat 

The motivating example is a case in which one wants to throw away the first few layers of a sequential model and use the remaining ones by feeding data directly to it (the opposite of "decapitate", whatever that is called ;) )

**Comment by nsthorat** [comment]
The example is I have an embedding lookup layer as an input and then I want to use the model but provide the embedding (for interpolation).
