### ISSUE TITLE
Memory Leak in TensorCamera when remounting repeatedly

### ISSUE THREAD

**Issue by JJwilkin** [tensorflow/tfjs#4902]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): React Native 0.63.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 8 Plus
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.0.0
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
I have the [TensorCamera](https://js.tensorflow.org/api_react_native/0.5.0/#cameraWithTensors) for React Native mounted on a tab in my [Tab Navigator](https://reactnavigation.org/docs/bottom-tab-navigator/). Switching between tabs causes the total memory usage to increase every time TensorCamera is remounted. I've narrowed the memory leak down to the Tensorcamera as replacing it with Expo Camera caused no memory leaks when switching between tabs. I've also commented out the onReady function so it shouldn't be related to undisposed tensors.

**Describe the expected behavior**
Re-mouting the TensorCamera shouldn't cause memory leaks

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
```
const TensorCamera = cameraWithTensors(Camera);
```
...
```
               <TensorCamera
                  ref={cameraRef}
                  style={styles.camera}
                  type={Camera.Constants.Type.back}
                  zoom={0}
                  cameraTextureHeight={textureDims.height}
                  cameraTextureWidth={textureDims.width}
                  resizeHeight={tensorDims.height}
                  resizeWidth={tensorDims.width}
                  resizeDepth={3}
                  onReady={handleCameraStream}
                  autorender={true}
                />
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![IMG_2767](https://user-images.githubusercontent.com/44853346/113497214-e40b0280-94cf-11eb-8042-7723f8b6c887.PNG)
![IMG_2770](https://user-images.githubusercontent.com/44853346/113497220-e79e8980-94cf-11eb-85bb-5e5af8ef86c0.PNG)

**Comment by valentinchelle** [comment]
I face the same issue, i opened a ticket here : https://github.com/tensorflow/tfjs/issues/4846

I then tracked down the leak to expo-gl's method createCameraTextureAsync() ( used in TensorCamera ). I wrote a ticket there too : https://github.com/expo/expo/issues/12468

**Comment by dee1ag** [comment]
still happening :(

**Comment by mattsoulanille** [comment]
Not stale
