### ISSUE TITLE
QUESTION: Live OCR using Tensor Camera

### ISSUE THREAD

**Issue by rajwanialiya** [tensorflow/tfjs#4904]
Hi! I'm creating an Android application that performs image classification and OCR on the same image. My original plan was to use two separate cameras in the app; RNCamera to perform live OCR, and Tensor Camera to form image classification. I chose this approach because I haven't had success using Tensor Camera for live OCR, and RNCamera doesn't allow users to easily access the camera stream, making live image classification challenging. 

Upon implementing this idea, I ran into a dependency issue with expo-camera and RNCamera. Is there a way to run both in the same app? If not does Tensor Camera include support for live text recognition?

**Comment by rthadur** [comment]
cc @pyu10055 @mattsoulanille

**Comment by gaikwadrahul8** [comment]
Hi, @rajwanialiya 

Apologize for the delayed response and I'm not sure which `react-native` and `expo version` are you using at the moment so could you please try to use package dependancies mentioned in this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and check whether are you able to use both Tensor camera and react native in the same app ? 

If not please let us know with error log for further investigation ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```
