### ISSUE TITLE
After tf.Tensor creation, its value can be changed by input TypedArray (not immutable)

### ISSUE THREAD

**Issue by huningxin** [tensorflow/tfjs#4905]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.2.0"> </script>
- TensorFlow.js version (use command below): 3.2.0
- Browser version: Google Chrome | 89.0.4389.114
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
```js
const array = new Float32Array([1, 2, 3, 4]);
const tensor = tf.tensor(array, [2, 2]);
tensor.print();
// Tensor
//    [[1, 2],
//     [3, 4]]
array[0] = 2;
tensor.print();
// Tensor
//    [[2, 2],
//     [3, 4]]
```

**Describe the expected behavior**
As the [doc](https://js.tensorflow.org/api/latest/#class:Tensor) says, `tf.Tensor` should be immutable. So change `array` should not change the value of `tensor`. It is expected that:
```js
const array = new Float32Array([1, 2, 3, 4]);
const tensor = tf.tensor(array, [2, 2]);
tensor.print();
// Tensor
//    [[1, 2],
//     [3, 4]]
array[0] = 2;
tensor.print();
// Tensor
//    [[1, 2],
//     [3, 4]]
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@huningxin  Tensor's are immutable and Variable is a fairly thin wrapper around that to allow reassignment.Tensor are results of computation so you are able to change the value of tensor output.

**Comment by huningxin** [comment]
> Tensor are results of computation so you are able to change the value of tensor output.

In the test code above, the tensor output is changed without any computations. Is that the expected behavior?

**Comment by rthadur** [comment]
but the the variable `array` is mutable , so the value is changed

**Comment by vladmandic** [comment]
tensor data is just a reference *until* it's first used - then it becomes internal to tensor and immutable.
for example, if you perform *any* operation on a tensor (even a no-op such as `tensor = tensor.add(0);`), the result of that op becomes internal to tensor and no longer associated to original variable.

**Comment by huningxin** [comment]
> but the the variable `array` is mutable , so the value is changed

According to the doc, "A tf.Tensor object represents an immutable, multidimensional array of numbers that has a shape and a data type.", I suppose it should be immutable after creation. The change of `array` should not impact `tf.Tensor`. 

> tensor = tensor.add(0);

`tensor.add` just returns another tensor. My issue is about the user created tensor, it should be immutable after creation.

**Comment by vladmandic** [comment]
In theory, completely agree  
In practice, it would just cause another data copy

If you really need it, trigger that copy manually using tf.clone or by using spread operator on the array when creating tensor

**Comment by huningxin** [comment]
If the `array` is a JS array, there is no issue. So I suppose it is an optimization for typed array. My point it would be helpful if this typed array optimization could be documented.

Does that make sense?

**Comment by vladmandic** [comment]
It does

**Comment by pyu10055** [comment]
@huningxin Thank you for raising this issue. I agree, we should document this limitation properly.
