### ISSUE TITLE
Using WASM with NodeJS but LoadGraphModel does not accept local file as input

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4927]
`WASM` backend is supported in `NodeJS` environments as per  
<https://blog.tensorflow.org/2020/03/introducing-webassembly-backend-for-tensorflow-js.html>

> In Node.js, the WASM backend is a great solution for devices that don’t support the TensorFlow binary or you don’t want to build it from source.

And yes, loading `tfjs` and `tfjs-backend-wasm` and setting backend to `wasm` works fine - but then how to use it?

```js
tf.loadGraphModel('file://models/model.json');
```

```error
RuntimeError: abort(TypeError: Only HTTP(S) protocols are supported).
```

So I've started a dev web server just to load models using *http://...* - and it works - but that really goes against idea of running NodeJS with WASM.

I understand the scope of this issue is more of an enhancement, but since `WASM` is supported in `NodeJS`, expectation is that it should work natively.

Also, note that missing local file I/O handler is just for model loader as loading *.wasm files from local filesystem works just fine.

Just as a test, I've tried loading `tfjs-node` with `tfjs-backend-wasm` as `tfjs-node` provides local file I/O handler, but that causes hard conflict.

Environment: TFJS 3.3.0 on Ubuntu 20.10 with NodeJS 15.14.0

**Comment by marcelklehr** [comment]
Just ran into the same problem!

**Comment by zavalyshyn** [comment]
I confirm the OP issues. I have similar issues when trying to decode local image files using `tf.node.decodeImage(buf)` function. tf.node is not defined in tf object when importing it as `import * as tf from '@tensorflow/tfjs';`
When I try to import tfjs-node package separately it causes a conflict when setting a 'wasm' backend.

Seems like for now wasm backend is primarily for browsers or I'm missing something. 
I attack my code just for a reference:
```js
import * as fs from 'fs';
// Import @tensorflow/tfjs or @tensorflow/tfjs-core
import * as tf from '@tensorflow/tfjs';
// import tfjs-node to read local image file
import tfnode from '@tensorflow/tfjs-node';
// Adds the WASM backend to the global backend registry.
import '@tensorflow/tfjs-backend-wasm';
// Set the backend to WASM and wait for the module to be ready.
tf.setBackend('wasm').then(() => main());

async function main() {
  var path = 'dog.jpeg';
  const buf = fs.readFileSync(path);
  let img = tfnode.node.decodeImage(buf);
  //let img = tf.browser.fromPixels(document.getElementById('img'))
      //.resizeBilinear([224, 224])
      //.expandDims(0)
      //.toFloat();
  //console.log("This is img: ", img)
  let model = await tf.loadGraphModel(
    'https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/2',
    {fromTFHub: true});
  const y = model.predict(img);

  y.print();
}

main();
```

**Comment by vladmandic** [comment]
that is a separate thing (and i don't consider it an issue at all, its just how its designed) - `tf.node.*` is defined by tfjs-node as it depends on specific nodejs libraries. and equally tf.browser.*` is only defined in browser environments as it depends on browser-specific implementation.  

in your case, you can use something like `node-canvas` to decode jpeg and then continue using `tfjs-backend-wasm` as normal.

**Comment by vladmandic** [comment]
closing as this is going backwards - at least until `nodejs` platform fetch supports `file://` namespace.
