### ISSUE TITLE
tfjs 3.4.0 has been released on cdnjs, but it's not on github releases page and there are no release notes

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4930]
`tfjs` **3.4.0** has been released on <https://www.npmjs.com/package/@tensorflow/tfjs>,  
but it's not on <https://github.com/tensorflow/tfjs/releases> releases page and there are no release notes  

environment: tfjs 3.4.0 on ubuntu 20.10

**Comment by rthadur** [comment]
@vladmandic release notes has been updated and i see it here https://github.com/tensorflow/tfjs/releases, thanks for noticing this.
cc @lina128

**Comment by vladmandic** [comment]
yup, it's online now, closing the issue.
