### ISSUE TITLE
tfjs 3.4.0 regression: wasm causes browser hang

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4932]
tfjs 3.4.0 was just released and unfortunately wasm module is somewhat broken  

to be precise, `tfjs-backend-wasm.wasm` and `tfjs-backend-wasm-simd.wasm` seem to work (although haven't tested in depth)  
what's definitely broken is `tfjs-backend-wasm-threaded-simd.wasm`

and symptoms are simple - complete browser hang,  
up to a point where browser window is nonresponsive to close requests and requires a hard kill

to reproduce: 
- enable `WebAssembly SIMD support` in <chrome://flags>
- enable `WebAssembly threads support` in <chrome://flags>
- set backend to `wasm`
- run any model inference

this used to work in all recent versions of tfjs

environment: tfjs 3.4.0 on windows 10 with chrome 89 or edge 89

**Comment by rthadur** [comment]
https://github.com/tensorflow/tfjs/issues/4796 this might be related , will try to test in my local as well and update , thank you 

cc @mattsoulanille

**Comment by lina128** [comment]
I test in my local, the problem is gone after turning off the SIMD flag in chrome. We are working on a fix. Thank you for reporting the bug!

**Comment by pyu10055** [comment]
@mattsoulanille This maybe related to the recent changes to bazel wasm build, https://github.com/tensorflow/tfjs/pull/4769

**Comment by vladmandic** [comment]
any updates on this one? as much as i'd love to use tfjs 3.4.0 due to support of tf2, this is a blocker for me.

**Comment by mattsoulanille** [comment]
No updates yet, but I've been able to reproduce it. I agree with Ping that this is likely related to changes made in #4769, and I'm taking a look.

**Comment by vladmandic** [comment]
@mattsoulanille - thanks - *'taking a look'* is an update, just wanted to know what's going on as it's a blocker for me.

**Comment by vladmandic** [comment]
@mattsoulanille thanks!

given it's a regression that causes hangs, does this warrant spinning up a tfjs service build (e.g., 3.4.1)?
(cc @pyu10055)

**Comment by lina128** [comment]
Hi @vladmandic , we are releasing 3.5.0 with this fix today.
