### ISSUE TITLE
Add Training BERT with TFJS to Gallery

### ISSUE THREAD

**Issue by alexander-fischer** [tensorflow/tfjs#4933]
I created a tutorial for training a classifier on top of BERT within the browser and with TensorflowJS. I would like to contribute it to the gallery, if it fits your requirements. If I need to change sth, feel free to contact me.

Here are the links:

[Blog article](https://alexfi.dev/blog/tensorflowjs-bert-train)

[Github Repo](https://github.com/alexander-fischer/browser-bert)

[Demo](https://browser-bert.vercel.app/)

**Comment by rthadur** [comment]
cc @pyu10055 @jasonmayes

**Comment by rthadur** [comment]
here is the gallery where you can add https://github.com/tensorflow/tfjs/blob/master/GALLERY.md , once it is approved by team.

**Comment by jasonmayes** [comment]
This could live under the tutorials section of GALLERY.md so if you add a new line item there with the relevant links to the above in that new line item and create a pull request then the team can merge that.

**Comment by alexander-fischer** [comment]
merged
