### ISSUE TITLE
Unable to load TensorFlow Lite models from memory

### ISSUE THREAD

**Issue by Michael-F-Bryan** [tensorflow/tfjs#4935]
**System information**
- `@tensorflow/tfjs-tflite ^0.0.1-alpha.1`

**Describe the feature and the current behavior/state.**

The `@tensorflow/tfjs-tflite` package currently only provides a `loadTFLiteModel()` function which accepts a URL to load a TensorFlow Lite model from. We already have the model in memory (as an `ArrayBuffer`) and were hoping to avoid the need for a round trip to the server.

**Will this change the current api? How?**

We noticed a `TFLiteWebModelRunner.CreateFromBufferAndOptions()` constructor and were hoping it could be exposed to the end user in some form. 

The overall signature may look something like this:

```ts
export function loadTFLiteModelFromBuffer(model: ArrayBuffer, options?: TFLiteWebModelRunnerOptions): Promise<TFLiteModel>;
```

This would be a purely additive change and just re-exporting functionality that is already used inside `loadTFLiteModel()`.

**Who will benefit with this feature?**

Any user who wants to use `@tensorflow/tfjs-tflite` in their apps without needing to fetch the model from a remote location. This provides benefits for:

- Privacy and Intellectual Property (keeping the model on the end user's device means it is less likely to be accessed without authorization)
- Latency/Performance - no need to do a round trip to a server to download the model if you've already got a version locally
- Convenience - you can use `@tensorflow/tfjs-tflite` without needing to provision, maintain, and pay for a server
- Dependency injection/Purity - What if I want to retrieve the model via something other than HTTP?

**Comment by gbaned** [comment]
cc @pyu10055

**Comment by jinjingforever** [comment]
Hi, 

Please try version `0.0.1-alpha.2` which supports passing arraybuffer to `loadTFLiteModel`:

https://github.com/tensorflow/tfjs/blob/master/tfjs-tflite/src/tflite_model.ts#L279

Thank you! (and sorry for the delay)
