### ISSUE TITLE
tfjs-converter

### ISSUE THREAD

**Issue by Master-of-moyu** [tensorflow/tfjs#4943]
**System information**
- macOS 10.13.6

**Describe the problem**
I download a TensorFlow SavedModel from 'https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/4' , and i use
`tensorflowjs_converter --input_format=tf_saved_model  ./imagenet_mobilenet_v2_100_224_classification_4/ ./mymodel`
to convert it to a tfjs model, but i. get the following result:
`ValueError: Signature 'serving_default' does not exist. The following signatures are available: KeysView(_SignatureMap({}))`

if i run 
`saved_model_cli show --dir ./imagenet_mobilenet_v2_100_224_classification_4  --tag_set serve`
i get
`The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "__saved_model_init_op"`
so, what should i do?

**Comment by rthadur** [comment]
did you specify `--signature_name` in the following example ?
`tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    /mobilenet/saved_model \
    /mobilenet/web_model`

**Comment by Master-of-moyu** [comment]
> did you specify `--signature_name` in the following example ?
> `tensorflowjs_converter \ --input_format=tf_saved_model \ --output_format=tfjs_graph_model \ --signature_name=serving_default \ --saved_model_tags=serve \ /mobilenet/saved_model \ /mobilenet/web_model`

Hi, i tried 
`tensorflowjs_converter \ --input_format=tf_saved_model \ --output_format=tfjs_graph_model \ --signature_name=serving_default \ --saved_model_tags=serve \ /imagenet_mobilenet_v2_100_224_classification_4  \ /mymodel`
or 
`tensorflowjs_converter \ --input_format=tf_saved_model \ --output_format=tfjs_graph_model \ --signature_name=serving_default \ --saved_model_tags=serve \ /imagenet_mobilenet_v2_100_224_classification_4  \ ./mymodel`
it always gives me 
> TensorFlow.js model converters.: error: unrecognized arguments:     /imagenet_mobilenet_v2_100_224_classification_4  /mymodel  

or 
> TensorFlow.js model converters.: error: unrecognized arguments:     /imagenet_mobilenet_v2_100_224_classification_4  ./mymodel  

seems like there is something wrong with the last two arguments.

**Comment by rthadur** [comment]
please check the related issue here https://github.com/tensorflow/tfjs/issues/3618 and let us know ?

**Comment by pyu10055** [comment]
you can try to convert the tfhub model directly without download
```
tensorflowjs_converter \
    --input_format=tf_hub \
    'https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/4' \
    /mobilenet/web_model```
