### ISSUE TITLE
load a trained model very slowly

### ISSUE THREAD

**Issue by Beliefuture** [tensorflow/tfjs#4949]
**System**
Browser: Edge/Chrome; 
tfjs version: 2.7.0;

**Description**
Load a trained MobileNet V2 model with tensorflow.js in a specific page take **10+ seconds** one time.
Not only for the first time, but takes **the same 10+ seconds** every time I open the page. 
When the loading phase is completed, the prediction phase is fast.

But I want to know how to **speed up the loading phase**, because it appears a not very good performance like this.

**Comment by Beliefuture** [comment]
Code below

```
async function loadModel(model_path) {
    model = await tf.loadLayersModel(
        model_path
    );
}
```

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rthadur** [comment]
Also inference time for the first time is slow that is expected and in the subsequent runs it is faster , please check the benchmark tool here https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html which you can run on MobilenetV2
