### ISSUE TITLE
Save\load model and weights to\from DB

### ISSUE THREAD

**Issue by Aluman** [tensorflow/tfjs#495]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Describe the problem or feature request
How can I save\load model and weights to\from DB? 
Model has method toJSON and I can store json in DB. But in method tf.loadModel I can't use use JSON. How can I create model from JSON?
For weights model has methods getWeights, setWeights. But this methods return/use Tensor[]. How can I convert Tensor[] to/from JSON?

**Comment by nkreeger** [comment]
We are starting to look at implementing this feature in layers. We need the ability to pass a JSON object directly into tf.loadModel() instead of loading it over some resource protocol.

**Comment by caisq** [comment]
@Aluman Can you clarify what you mean by "convert Tensor[] to/from JSON"? Tensors are binary (mostly float) data. Representing the float numbers in JSON is very inefficient, which is why the saving and loading of the weights involve non-JSON types such as ArrayBuffers.

**Comment by caisq** [comment]
Also, by "DB", what do you mean? IndexedDB of the browser?

**Comment by Aluman** [comment]
> Also, by "DB", what do you mean? IndexedDB of the browser?

I mean SQL/NoSQL DB like MySQL, mongodb etc.

> Can you clarify what you mean by "convert Tensor[] to/from JSON"? Tensors are binary (mostly float) data. Representing the float numbers in JSON is very inefficient, which is why the saving and loading of the weights involve non-JSON types such as ArrayBuffers.

I mentioned JSON because it's widely used format in js development, usually array\object can be converted to JSON and model already can be saved as json. JSON can easily stored to db/file or transfer by network it is very handy format. But if JSON is very inefficient any others formats can be used as well.
I just looking for way to store model/weights to well known formats(JSON, string, array, buffer etc). And way to load model from it.

**Comment by davidsoergel** [comment]
I just prepared tensorflow/tfjs-core#1148, providing "passthrough" IOHandlers that load and save models to a simple in-memory format (a combination of JS objects and ArrayBuffers).  That approach may be enough for simple use cases.

For more complex use cases, you can write your own implementation of IOHandler (https://github.com/tensorflow/tfjs-core/blob/master/src/io/types.ts#L207).  Then you could write things like `tf.loadModel(new MySqlIOHandler(credentials, model_key))` and `model.save(new MySqlIOHandler(...))`.

Note that IOHandlers (including the "passthrough" ones proposed in the PR) operate in terms of ModelArtifacts (https://github.com/tensorflow/tfjs-core/blob/master/src/io/types.ts#L165), where the weights are packed into a single ArrayBuffer.  You could convert that to JSON for storage, but that would be very inefficient; you'd be much better off just storing the binary data as a blob.  If for some reason you do need to shard the weight data or extract individual weight variables, the weightSpecs entry provides the information you need to do that.

Hope this helps!

**Comment by davidsoergel** [comment]
Closing: tensorflow/tfjs-core#1148 is now submitted.  I think either that or the custom IOHandler approach should resolve this need.

**Comment by toddpi314** [comment]
@davidsoergel Any docs on usage of the pass-through handler?
