### ISSUE TITLE
Publish @tensorflow-models/coco-ssd with tfjs 3

### ISSUE THREAD

**Issue by Dimitris-Toulis** [tensorflow/tfjs#4952]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 3.3.0
- Are you willing to contribute it (Yes/No): N/A

**Describe the feature and the current behavior/state.**

The latest version of @tensorflow-models/coco-ssd is using tfjs 2. Please publish the new version to npm in order to use it with tfjs 3 

**Will this change the current api? How?**

The new version will require tfjs 3

**Who will benefit with this feature?**

Everyone who wants to use @tensorflow-models/coco-ssd with tfjs 3

**Any Other info.**

This change is already commited but not published

**Comment by gbaned** [comment]
cc @pyu10055

**Comment by rthadur** [comment]
New version will be published soon. Thank you @lina128
