### ISSUE TITLE
Supporting more NLP-centric ops

### ISSUE THREAD

**Issue by JEF1056** [tensorflow/tfjs#4953]
**System information**
- TensorFlow.js version 2.6.0:
- Are you willing to contribute it No

**Describe the feature and the current behavior/state.**
ReadVariableOp, DatasetToSingleElement, BatchDatasetV2, ParallelMapDatasetV2, SentencepieceOp, TensorSliceDataset, VarHandleOp, SentencepieceDetokenizeOp
Are all currently not supported by tensorflow.js, but some of them have similar operations that already exist in tensorflow.js
**Will this change the current api? How?**
Yes, It would add new operations to tensorflow.js
**Who will benefit with this feature?**
Many people working in the NLP space would be able to use these two operations to bundle tokenizers into their models on tensorflow.js with these operations
**Any Other info.**
I have not been able to sucessfully test the functionality of SentencePieceOp (it may already work) but TensorSliceDataset definitely does not exist, the closest existing function in tfjs being tf.data.CSVDataset.

**Comment by gbaned** [comment]
cc @pyu10055

**Comment by rthadur** [comment]
will you be interested in contributing?

**Comment by josephrocca** [comment]
More support for NLP ops would be great! I just got:

> tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'SentencepieceTokenizeOp', 'SentencepieceOp', 'SentencepieceDetokenizeOp'}) are also absent from the c++ registry.

while trying to run:

```bash
tensorflowjs_converter --input_format tf_hub https://tfhub.dev/google/bertseq2seq/roberta24_cnndm/1 ./roberta24_cnndm
```

@rthadur JEF1056 answered that in their original post:

> Are you willing to contribute it No

It would be useful to know what specifically needs to be done to contribute these ops. I think a lot of people posting feature requests in this repo are end-users of tfjs who only have (or mostly have) experience with JS, and don't really know much about the internals (including writing webgl and compiling c/c++ wasm, let alone the internals of `tensorflowjs_converter`). A guide on how to add ops might help people to contribute?

**Comment by rthadur** [comment]
@josephrocca here is the guide https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md , please check. Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @JEF1056 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and if I'm not wrong it seems like we haven't implemented above mentioned NLP Ops so May I know are you still looking add above mentioned NLP Ops in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
