### ISSUE TITLE
Way of connecting different Layer model

### ISSUE THREAD

**Issue by WenheLI** [tensorflow/tfjs#4959]
I am wondering if there is a way to connect different layer models together.
For instance, I have layer models `A` and `B`. And I want to put `B` after `A' and construct a new model `C` and train it.

Is there any way of achieving it?

**Comment by pyu10055** [comment]
@caisq any suggestions on this question? thanks

**Comment by caisq** [comment]
Yes, that should be doable, as long as model A's output shape fits with model B's input shape. 

An example would be:

```js
  const model_a = tf.sequential();
  model_a.add(tf.layers.dense({inputShape: [4], units: 3}));

  const model_b = tf.sequential();
  model_b.add(tf.layers.dense({inputShape: [3], units: 1}));

  const model_c = tf.sequential();
  model_c.add(model_a);
  model_c.add(model_b);

  model_c.summary();
  console.log(model_c.outputShape);
```

**Comment by WenheLI** [comment]
@caisq - Thanks! But it does not work if the sub-model has multiple output nodes. Is there a way to deal in that case?
