### ISSUE TITLE
Getting error while using bodyPix.drawBokehEffect in IE11

### ISSUE THREAD

**Issue by EzhumalaiPrakash** [tensorflow/tfjs#4961]
When i use bodyPix.drawBokehEffect in IE11 getting error message, but same code working in chrome browser. Please find attached error message and suggest something to resolve this issue.
![Capture](https://user-images.githubusercontent.com/82143523/115408314-6143b080-a20e-11eb-9be3-0d892436ffda.PNG)

Does IE11 support tfjs@1.2 & body-pix@2.0 ?

**Code we used**
`function loadAndBlur() {
	 const img = document.getElementById('refimg');
	  const canvas = $('#reflay').get(0)
      const backgroundBlurAmount = 9;
      const edgeBlurAmount = 3;
      const flipHorizontal = false;
	  return bodyPix.load().then(function net(response) {
		return response.segmentPerson(img, {
							  flipHorizontal: false,
							  internalResolution: 'low',
							  segmentationThreshold: 0.6
							}).then(function processResult(segmentation) {
									return bodyPix.drawBokehEffect(canvas, img, segmentation, backgroundBlurAmount, edgeBlurAmount, flipHorizontal);
								})
		})  
    }`

**Comment by rthadur** [comment]
1.2 is very old version and we will not able to support this.Please use latest version(3.x) and let us know. Thank you

**Comment by EzhumalaiPrakash** [comment]
even changing version 3.4.0 we got WebGL warning and promise rejection error in IE11. and bodyPix.drawBokehEffect does not bind on screen.
![Capture_1](https://user-images.githubusercontent.com/82143523/115501975-cf7d8700-a291-11eb-96cb-ec4d1c4e2d67.PNG)

**Comment by EzhumalaiPrakash** [comment]
Issue still persists, please help us where I did mistake?

**Comment by rthadur** [comment]
Sorry, we will not be able to support IE11.
