### ISSUE TITLE
Mismatch between documentation and the actual behavior of column's dtype

### ISSUE THREAD

**Issue by spleshakov** [tensorflow/tfjs#4962]
According to https://js.tensorflow.org/api/latest/#data.csv `csvConfig.columnConfigs[columnHeader].dtype` can be any value of `int32, float32, bool, or string`

However, this switch clause https://github.com/tensorflow/tfjs/blob/623da7ecbada115425888c62bd65df685e2bdd75/tfjs-data/src/datasets/csv_dataset.ts#L253 has all specified values but `string`. Default - `parsedValue = valueAsNum;`

This also doesn't work in practice, when I use danfojs like so:

service_areas.csv
```
SERVICE_AREA_ID|ZIPCODE|STATE_CODE|COUNTY_CODE|COUNTY_NAME|SERVICE_AREA_NAME|PLAN_YEAR
"North"|56762|"MN"|"24440"|"Marshall"|"North"|2021
"PR North"|56762|"MN"|"24440"|"Marshall"|"PR North"|2021
```
javascript
```
service_areas_data = await danfojs.read_csv(
		"zpr_service_areas.txt",
		{
			delimiter: "|",
			columnConfigs: {
				"ZIPCODE": {
					dtype: "string"
				}
			}
		}
	)
service_areas_data.ctypes.print()
```
results in output
```
╔═══════════════════╤══════════════════════╗
║                   │ 0                    ║
╟───────────────────┼──────────────────────╢
║ SERVICE_AREA_ID   │ string               ║
╟───────────────────┼──────────────────────╢
║ ZIPCODE           │ int32                ║
╟───────────────────┼──────────────────────╢
║ STATE_CODE        │ string               ║
╟───────────────────┼──────────────────────╢
║ COUNTY_CODE       │ int32                ║
╟───────────────────┼──────────────────────╢
║ COUNTY_NAME       │ string               ║
╟───────────────────┼──────────────────────╢
║ SERVICE_AREA_NAME │ string               ║
╟───────────────────┼──────────────────────╢
║ PLAN_YEAR         │ int32                ║
╚═══════════════════╧══════════════════════╝

```

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by spleshakov** [comment]
@rthadur it's in the description. Do you need anything else apart from that?

**Comment by rthadur** [comment]
I see you are using danfojs, I don't see a reference where you are using tfjs , could you please provide a codepen example or GitHub test repo where we can reproduce the behavior ? Thank you
