### ISSUE TITLE
React Native: Crash on tf.ready() when running on Android's JS Engine

### ISSUE THREAD

**Issue by khalidbashirmyant** [tensorflow/tfjs#4965]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Big Sur 11.2.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Any Android device. I have tested on OnePlus 5 and Samsung Galaxy S10
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs-react-native 
- TensorFlow.js version (use command below): 3.4.0
- Browser version: The problem happens when JS is run on the phone
- Tensorflow.js Converter Version: The problem happens on initialization of tensor flow

**Describe the current behavior**
We have integrated TFJS into a react native app. It works fine with remote debugging as the JS is running on the computer in chrome. However, when we try to run on the phone itself it crashes the app as soon as tf.ready() is called. Following is the log from logcat

A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xfe8aa0003f3 in tid 25679 (mqt_js)

The above only happens for Android. We have also tried with another JS engine https://www.npmjs.com/package/react-native-v8 but that also fails with a crash

It works fine on iPhone both in remote debugging and running on the phone itself.

**Describe the expected behavior**
TensorflowJS should initialize

**Standalone code to reproduce the issue**
Add tensorflowjs imports to App.js in a react native app and call await tf.ready()

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xfe8aa0003f3 in tid 25679 (mqt_js)

**Comment by jinjingforever** [comment]
Sorry Matt, re-assigning this for you now since I don't have an Android device:) Thanks!

**Comment by khalidbashirmyant** [comment]
Here is the package.json. This may provide an insight of the environment tfjs is running in
[package.json.zip](https://github.com/tensorflow/tfjs/files/6368794/package.json.zip)

**Comment by kevinchristianto** [comment]
I'm also having this issue right now, any solution?

I'm using tfjs 3.7.0 and react native 0.62.3

**Comment by wvanooijen92** [comment]
I am also facing the same issue

```
    "@react-native-async-storage/async-storage": "^1.15.8",
    "@tensorflow/tfjs": "^3.9.0",
    "@tensorflow/tfjs-react-native": "^0.7.0",
    "expo-camera": "^11.2.2",
    "expo-gl": "^10.4.2",
    "expo-gl-cpp": "^10.4.1",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-ble-manager": "^7.6.1",
    "react-native-fs": "^2.18.0",
    "react-native-svg": "^12.1.1",
    "react-native-unimodules": "^0.14.9",
    "react-native-vector-icons": "^8.1.0",

 ```

A screenshot of my device logs

![Screenshot 2021-09-26 at 14 51 19](https://user-images.githubusercontent.com/2452503/134808787-ca121a0f-fa1a-4ded-991a-6014258b2ae8.png)

**Comment by jinjingforever** [comment]
Hi @wvanooijen92 @AhmedRazaVerge, I recently checked in some tfjs react native example apps [here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native). Please take a look. One thing to note is that react native 0.65.1 does not work well with expo-gl 10.4.2 (would crash Android as you guys mentioned). Please use react native 0.63.2. Thank you!

**Comment by wvanooijen92** [comment]
@jinjingforever thanks for the update, I was just about to leave you message, that is exactly what I did today, I was able to get it running. Fyi I am on 0.63.4 now and it seems to be working. Thank you!
