### ISSUE TITLE
Feature request: Activate initialEpoch in model.fit

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#497]
Please activate initialEpoch in model.fit

In the API it is listed as

> initialEpoch (number) Epoch at which to start training (useful for resuming a previous training run). Optional

But when I try to activate it, it does not work, see [codepen](https://codepen.io/rocksetta/pen/gKNVre?editors=0011)

The [code](https://github.com/tensorflow/tfjs-layers/blob/v0.7.0/src/engine/training.ts#L1605-L1802) seems to have it partially in place, however line 1801 says

>   // TODO(cais): Add initialEpoch.

I will look into sending a PR, but typescript is a bit out of my comfort zone.

**Comment by hpssjellis** [comment]
Seemed to get it working with a few changes to [training.ts](https://github.com/tensorflow/tfjs-layers/blob/1a9ac50bdb8e7ff7f82c91e94119a96bf724f104/src/engine/training.ts)

See working [demo](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/keras/initialEpoch/graceful-exit04.html)

**Comment by caisq** [comment]
@hpssjellis has sent out PR https://github.com/tensorflow/tfjs-layers/pull/261 to fix this. It is under review. Thanks!
