### ISSUE TITLE
Build fails when upgrading @tensorflow/tfjs-react-native from 0.2.1 to 0.5.0

### ISSUE THREAD

**Issue by farhan2056** [tensorflow/tfjs#4975]
<em>This is a build/installation issue. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.2.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy M10
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version:  1.5.1
- CUDA/cuDNN version:

**Steps executed before running into the problem**
Installed @tensorflow/tfjs-react-native in my project according to the [docs](https://www.npmjs.com/package/@tensorflow/tfjs-react-native) provided.
The project did run successfully.

After that, I tried to update the version of @tensorflow/tfjs-react-native from 0.2.1 to 0.5.0 when these errors occurred.

![1](https://user-images.githubusercontent.com/8373729/115825224-bbb75980-a426-11eb-88bd-26e5ae276cda.png)

module "expo-camera" not found. I installed it.

![2](https://user-images.githubusercontent.com/8373729/115825300-d38edd80-a426-11eb-91b3-2f98d4b5af2b.png)
 module @tensorflow/tfjs-backend-webgl not found. I installed it.

Then the build failed with this error message.

![3](https://user-images.githubusercontent.com/8373729/115825398-00db8b80-a427-11eb-9189-8e2caadde1ed.jpeg)

Please help me in solving this issue.

Thank you.

**Comment by pyu10055** [comment]
@farhan2056 You are using an older version of TFJS (TensorFlow.js version: 1.5.1), try to upgrade the TFJS version to the latest (3.5.0)
