### ISSUE TITLE
knn classifier fails with npm

### ISSUE THREAD

**Issue by nerkn** [tensorflow/tfjs#4976]
**System information**
- OS : Linux n-Lenovo-ideapad-320-15ISK 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- TensorFlow.js installed from (npm or script link): `npm install '@tensorflow/tfjs'`
- TensorFlow.js version:         
        "@tensorflow-models/coco-ssd": "^2.2.2",
        "@tensorflow-models/mobilenet": "^2.1.0",
        "@tensorflow/tfjs": "^3.4.0",
        "@tensorflow/tfjs-node": "^3.4.0",
- CUDA/cuDNN version: NA

**Describe the problem**
npm installation fails 

**Exact sequence of steps  executed before running into the problem**
Have coco-ssd and mobilenet already installed and working smoothly also want to add knn classifier 
`npm i @tensorflow-models/knn-classifier`

**Any other info / logs**
 npm i @tensorflow-models/knn-classifier
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @tensorflow/tfjs-core@3.4.0
npm ERR! node_modules/@tensorflow/tfjs-core
npm ERR!   peer @tensorflow/tfjs-core@"^3.3.0" from @tensorflow-models/coco-ssd@2.2.2
npm ERR!   node_modules/@tensorflow-models/coco-ssd
npm ERR!     @tensorflow-models/coco-ssd@"^2.2.2" from the root project
npm ERR!   peer @tensorflow/tfjs-core@"^3.1.0" from @tensorflow-models/mobilenet@2.1.0
npm ERR!   node_modules/@tensorflow-models/mobilenet
npm ERR!     @tensorflow-models/mobilenet@"^2.1.0" from the root project
npm ERR!   6 more (@tensorflow/tfjs, @tensorflow/tfjs-backend-cpu, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @tensorflow-models/knn-classifier@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @tensorflow/tfjs-core@1.7.4
npm ERR! node_modules/@tensorflow/tfjs-core
npm ERR!   peer @tensorflow/tfjs-core@"^1.2.1" from @tensorflow-models/knn-classifier@1.2.2
npm ERR!   node_modules/@tensorflow-models/knn-classifier
npm ERR!     @tensorflow-models/knn-classifier@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/n/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by rthadur** [comment]
I guess there are duplicate dependencies in the package.json , which needs to be resolved , please check. 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.
