### ISSUE TITLE
Is real time object detection possible using TensorCamera and Cocossd ?

### ISSUE THREAD

**Issue by AdarshJais** [tensorflow/tfjs#4988]
When I use Tensor Camera 

1. It is very much laggy 
2. I guess it keeps capturing each frame and thus we just get one item in prediction using the mobilenet model 
3. In case we use cocossd for multiple image detection it throw error ""tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead""

So How is it possible to make a real-time multiple image detection, I can see an example in flutter so is that the same possible in React Native anyway? 

Flutter example that I need in React Native : - https://heartbeat.fritz.ai/turning-the-mobile-camera-into-a-real-time-object-detector-with-flutter-and-tensorflow-lite-f412962b1805

**Comment by RohitGamare** [comment]
You can refer tensorflow js face landmark detection from the tensorflow website itself it might help you ,for capturing the images u can use openCV

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by uffoltzl** [comment]
> 
> 
> When I use Tensor Camera
> 
>     1. It is very much laggy
> 
>     2. I guess it keeps capturing each frame and thus we just get one item in prediction using the mobilenet model
> 
>     3. In case we use cocossd for multiple image detection it throw error ""tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead""
> 
> 
> So How is it possible to make a real-time multiple image detection, I can see an example in flutter so is that the same possible in React Native anyway?
> 
> Flutter example that I need in React Native : - https://heartbeat.fritz.ai/turning-the-mobile-camera-into-a-real-time-object-detector-with-flutter-and-tensorflow-lite-f412962b1805

I was wondering if you found a solution?

**Comment by AdarshJais** [comment]
> > When I use Tensor Camera
> > ```
> > 1. It is very much laggy
> > 
> > 2. I guess it keeps capturing each frame and thus we just get one item in prediction using the mobilenet model
> > 
> > 3. In case we use cocossd for multiple image detection it throw error ""tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So How is it possible to make a real-time multiple image detection, I can see an example in flutter so is that the same possible in React Native anyway?
> > Flutter example that I need in React Native : - https://heartbeat.fritz.ai/turning-the-mobile-camera-into-a-real-time-object-detector-with-flutter-and-tensorflow-lite-f412962b1805
> 
> Did you find a solution?

No bro, no solution yet.

**Comment by robbiewebhub** [comment]
> 

any solution ?

**Comment by arpitKohli112** [comment]
> > > When I use Tensor Camera
> > > ```
> > > 1. It is very much laggy
> > > 
> > > 2. I guess it keeps capturing each frame and thus we just get one item in prediction using the mobilenet model
> > > 
> > > 3. In case we use cocossd for multiple image detection it throw error ""tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead""
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So How is it possible to make a real-time multiple image detection, I can see an example in flutter so is that the same possible in React Native anyway?
> > > Flutter example that I need in React Native : - https://heartbeat.fritz.ai/turning-the-mobile-camera-into-a-real-time-object-detector-with-flutter-and-tensorflow-lite-f412962b1805
> > 
> > 
> > Did you find a solution?
> 
> No bro, no solution yet.

any solution bro ? my camera is lagging too when I get predictions from model.predict()

**Comment by arpitKohli112** [comment]
> Hi. I'm facing the same issue. It's very laggy on Android. Any helps please? Thanks a lot

Brother did you find any solution to this im also facing same problem im using a model that I created using teachable machine and its very laggy ?

**Comment by arpitKohli112** [comment]
> > When I use Tensor Camera
> > ```
> > 1. It is very much laggy
> > 
> > 2. I guess it keeps capturing each frame and thus we just get one item in prediction using the mobilenet model
> > 
> > 3. In case we use cocossd for multiple image detection it throw error ""tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So How is it possible to make a real-time multiple image detection, I can see an example in flutter so is that the same possible in React Native anyway?
> > Flutter example that I need in React Native : - https://heartbeat.fritz.ai/turning-the-mobile-camera-into-a-real-time-object-detector-with-flutter-and-tensorflow-lite-f412962b1805
> 
> Did you find a solution?

Brother did you find any solution to this im also facing same problem im using a model that I created using teachable machine and its very laggy ?

**Comment by uffoltzl** [comment]
Hi. My solution is still a little bit laggy on android, but you can find an article I wrote about two years ago (https://www.bam.tech/article/how-to-recognize-real-time-object-in-reactnative-for-dummies) it has not been updated since so it may be an outdated solution. Hope it can help
