### ISSUE TITLE
Keras model accepts internal layers with incorrect 'inputShape' without warning.

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#499]
#### TensorFlow.js version
0.12.1

#### Browser version
irrelevant

#### Describe the problem or feature request
It would be nice to at least warn the user that the provided 'inputShape' for intermediate layers is ignored.

#### Code to reproduce the bug / link to feature request
```
const model = tf.sequential();
// First layer must have an input shape defined.
model.add(tf.layers.dense({units: 32, inputShape: [50]}));
// Shape is ignored on subsequent layers.
model.add(tf.layers.dense({units: 32, inputShape: [10]}));
model.add(tf.layers.dense({units: 123, inputShape: 'XX ignored XX'}));
// Inspect the inferred shape of the model's output, which equals
// `[null, 123]`. The 1st dimension is the undetermined batch dimension; the
// 2nd is the output size of the model's last layer.
console.log(JSON.stringify(model.outputs[0].shape));
```

outputs:
```
[null,123]
```

**Comment by caisq** [comment]
FWIW, if you do the equivalent thing in Keras in Python, you also get no warning. So it may make sense for us to fix in JS and Python at the same time.

**Comment by caisq** [comment]
cc @fchollet
