### ISSUE TITLE
IRIS online Demo not loading resource

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#50]
Is anyone else having issues with the IRIS online demo?
Demo at

https://storage.googleapis.com/tfjs-examples/iris/dist/index.html

Github at 
https://github.com/tensorflow/tfjs-examples/tree/master/iris

The error I get is 

Failed to load resource: the server responded with a status of 404

**Comment by nsthorat** [comment]
Thanks for filing this. It should be fixed on GCS now, I sent a PR to fix it:

https://github.com/tensorflow/tfjs-examples/pull/48

**Comment by hpssjellis** [comment]
Looks good. Thanks.
