### ISSUE TITLE
Setting a Proxy for bodyPix internal requests

### ISSUE THREAD

**Issue by perahlberg** [tensorflow/tfjs#5002]
Hi, 
BodyPix is today doing two request to  storage.googleapis.com to access external files.
Many (Swedish) companies, specially government organizations always must use a proxy to mask the client’s IP-address. 

It should be great to have the option to set a proxy-server for these requests.
Thanks for your great work!

**Comment by vladmandic** [comment]
`tf.loadGraphModel` at the end is just a generic `fetch` request in browser

so in your app, you can register a service worker (`navigator.serviceWorker.register`) and then inside service worker listen to fetch requests and modify them on the fly any way you want (`self.addEventListener('fetch', (evt) => { ... }`)

**Comment by perahlberg** [comment]
Thank you for the super-fast replay!
I will try this! 
If you do not feel interesting haven this feature request still here, you can close it.
