### ISSUE TITLE
tensorflow/tfjs import error in react js

### ISSUE THREAD

**Issue by RohitGamare** [tensorflow/tfjs#5004]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10
- TensorFlow.js installed from npm 
- TensorFlow.js version: 3.5.0
- CUDA/cuDNN version: NO

**Describe the problem**
As I try to import  import tensorflow into my component i get the error as such : 

./node_modules/@tensorflow/tfjs-core/dist/io/http.js
Error: C:\Users\sony\Desktop\rohit\decentragram-master\node_modules\@tensorflow\tfjs-core\dist\io\http.js: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at Array.map (<anonymous>)
    at Array.forEach (<anonymous>)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
const tf = require('@tensorflow/tfjs-node');

**Any other info / logs**
I have installed @tensorflow/tfjs-node in my project but the dependency is not visible in the package.json file

**Comment by rthadur** [comment]
@RohitGamare please provide the steps you are following to install and sample code if possible. Thank you

**Comment by RohitGamare** [comment]
> @RohitGamare please provide the steps you are following to install and sample code if possible. Thank you

npm install @tensorflow/tfjs
npm install @tensorflow/tfjs-core
npm install @tensorflow/tfjs-node
npm install @tensorflow/tfjs-node --unsafe-perm=true --allow-root

above been the commands i tried

**Comment by rthadur** [comment]
npm install @tensorflow/tfjs-node will install all the dependencies for tfjs and tfjs core ,also check windows trouble shooting guide here https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md

**Comment by RohitGamare** [comment]
> npm install @tensorflow/tfjs-node will install all the dependencies for tfjs and tfjs core ,also check windows trouble shooting guide here https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md

Thank you for the response
