### ISSUE TITLE
TFJS converter mismanages EfficientDet models 2

### ISSUE THREAD

**Issue by partus** [tensorflow/tfjs#5013]
Efficientdet  can't be used , it relates to #3903, but seems to be a completely different one
For this  [model](https://tfhub.dev/tensorflow/efficientdet/d0/1)

## Converted the following way
```
tensorflowjs_converter \
    --input_format=tf_hub  \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    ./efficientdet_d0_1 ./web_model_tfhub
```

## Loaded and executed as follows in a browser
```
const model = await tf.loadGraphModel("web_model_tfhub/model.json");
t = tf.browser.fromPixels(img).expandDims(0)
let output = await model.executeAsync(t)
```

## Results in
```
Uncaught Error: FusedConv2d and DepthwiseConv2d with BiasAdd must have one extra argument: bias.
    at UO (tfjs@2.7.0:17)
    at tfjs@2.7.0:17
    at tfjs@2.7.0:17
    at tfjs@2.7.0:17
    at e.t.scopedRun (tfjs@2.7.0:17)
    at e.t.tidy (tfjs@2.7.0:17)
    at lx (tfjs@2.7.0:17)
    at tfjs@2.7.0:17
    at KO (tfjs@2.7.0:17)
    at p (tfjs@2.7.0:17)
```

Same when the model is taken from the official repo.

Tried both tfjs version 2.7.0 , which was released just after #3903 was resolved , and 3.6.0, the result is the same

**Comment by partus** [comment]
What versions of other packages are relevant? : I am running it on Arch linux, hence the most recent tensorflow + python as well, e.g. tensorflow with python 3.9... is not officially supported. Which are the important dependencies so that I will I will put it into a cantainer, Hopefully  veryify that it’s fine. Then with the next step we might verify the issue in a container with upgraded versions

**Comment by Linh0704** [comment]
@partus Have you resolved this issue, I've countered the same one. Change tfjs version and tensorflowjs won't work
```Uncaught Error: FusedConv2d and DepthwiseConv2d with BiasAdd must have one extra argument: bias.```

**Comment by partus** [comment]
@Linh0704 , @pyu10055  I was able to convert and run the tfhub version with python 3.8 instead of 3.9, and tfjs 3.6.0 , but I was unable to run the model from the official repo. Did not dive into it further as decided to run the model on a server.

**Comment by rthadur** [comment]
Closing the issue , please mention@ if you need further help to reopen. Thank you

**Comment by npip99** [comment]
@rthadur I get the same issue right now, on npm `tensorflowjs@3.13.1`, with pip version of tensorflow==2.7, tensorflowjs==3.13.1

```
tensorflowjs_converter --input_format=tfjs_layers_model --output_format=tfjs_graph_model
    ./models/MyModel/model.json ./models/MyGraphModel
```

```
let graphModel = await tf.loadGraphModel('file://' + path.resolve('models', 'MyGraphModel', 'model.json'));
graphModel.predict(...);
```
