### ISSUE TITLE
bodyPix drawBokehEffect does not accept OffscreenCanvas

### ISSUE THREAD

**Issue by jpodwys** [tensorflow/tfjs#5019]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: macOS 10.15.4
- TensorFlow.js installed from: script link
- TensorFlow.js version: 3.6.0
- BodyPix version: 2.1.0
- Browser version: Chrome 90.0.4430.93
- Tensorflow.js Converter Version: ?

**Describe the current behavior**
When I call `bodyPix.drawBokehEffect` and provide an `HTMLCanvasElement` as the second argument, everything works fine. However, when I provide an `OffscreenCanvas` instance, I get an error.

**Describe the expected behavior**
[This PR](https://github.com/tensorflow/tfjs-models/pull/610) appears to fix the issue, but it's not available in the latest releases of tfjs (3.6.0) or bodypix (2.1.0).

I'd like to request a release that includes this change. If this change is already published, please let me know which version contains it as I believe I'm using the latest version of both libraries.

Thank you!

**Comment by rthadur** [comment]
@jpodwys thank you soon new version will be published to npm

**Comment by jpodwys** [comment]
That's great news, thank you!

**Comment by rthadur** [comment]
New Version is published in npm https://www.npmjs.com/package/@tensorflow-models/body-pix , thank you @lina128

**Comment by jpodwys** [comment]
Thank you, it's working great!
