### ISSUE TITLE
Are the check of EXT_color_buffer_float in the gpgpu_context need to be forced?

### ISSUE THREAD

**Issue by lygstate** [tensorflow/tfjs#502]
https://github.com/tensorflow/tfjs-core/blob/5d0b2997e2f56f126d146dbe282fe1fd08a6ff53/src/kernels/webgl/gpgpu_context.ts#L69

I have GPU that do not support for EXT_color_buffer_float  but support OpenGL ES 3.1(Mali T720).
I want to running tfjs on that GPU:)

**Comment by nsthorat** [comment]
Yes unfortunately we need that extension to render floats. What browser are you using?

**Comment by lygstate** [comment]
I am using Chrome 68

**Comment by lygstate** [comment]
How about using https://skytiger.wordpress.com/2010/12/01/packing-depth-into-color/ to polyfill when EXT_color_buffer_float not available

**Comment by lygstate** [comment]
How about DEPTH_COMPONENT32F for gray image?

**Comment by nsthorat** [comment]
Closing this out in favor of https://github.com/tensorflow/tfjs/issues/551
