### ISSUE TITLE
Getting Error for export { ImageClassificationModel, loadImageClassification } from './img_classification when trying to do object detection with AutoML model in NodeJS

### ISSUE THREAD

**Issue by ayandebbarman** [tensorflow/tfjs#5023]
I am trying to make Object detection in Node (Not Html) with custom model that was trained. 

**System information**
- OS Platform - Mac OS Catalina
- TensorFlow.js installed using NPM
- TensorFlow.js version
          "dependencies": {
            "@tensorflow/tfjs-automl": "^1.1.0",
            "@tensorflow/tfjs-node": "^3.6.1"
          }

**Describe the current behavior**
Trying to make object detection predict working in Node js. Below is the code

`const tf = require("@tensorflow/tfjs-node");
const automl = require("@tensorflow/tfjs-automl");
const fs = require("fs");

const model_url = "/model.json";
const image_path = process.argv.slice(2)[0];

if (!image_path) {
  throw new Error("/MegaFortuneWheel.png");
}

const image = fs.readFileSync("/MegaFortuneWheel.png");
const decoded_image = tf.node.decodeJpeg(image);

async function run() {
  const model = await automl.loadObjectDetection(model_url);
  const predictions = await model.detect(decoded_image);

  console.log(predictions);
}

run().catch(console.error);`

**Standalone code to reproduce the issue**
Below is full code with the model files
https://github.com/ayandebbarman/TensorFlowObjectDetection

**Other info / logs** Include any logs or source code that would be helpful to
 This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/ayan.barman/Documents/Node/TF_git/node_modules/@tensorflow/tfjs-automl/dist/index.js:18
export { ImageClassificationModel, loadImageClassification } from './img_classification';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/ayan.barman/Documents/Node/TF_git/tf.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)

**Comment by aravindvnair99** [comment]
Duplicate of https://github.com/tensorflow/tfjs/issues/5017
