### ISSUE TITLE
TypeError: e.forEach is not a function

### ISSUE THREAD

**Issue by fatorius** [tensorflow/tfjs#5027]
I'm new to tensorflow.js, I've used the Python version before and now I'm converting my previously trained models to web.
I followed a CodeLabs tutorial, where I got this code:
```javascript
const MODEL_URL = "../model/model.json"

async function run() {
    // Load the model from the CDN.
    const model = await tf.loadLayersModel(MODEL_URL, strict=false);

    // Print out the architecture of the loaded model.
    // This is useful to see that it matches what we built in Python.
    console.log(model.summary());
```

But I keep getting this error:
```
Uncaught (in promise) TypeError: e.forEach is not a function
    at bg (util_base.js:681)
    at Mw (tensor_ops_util.js:44)
    at Lw (tensor.js:56)
    at Ww (io_utils.js:225)
    at RM (models.js:334)
    at models.js:316
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at bv (runtime.js:747)
```

Can you tell me what's wrong here? Is it a problem with my converted model or could it be some bug?

**Comment by rthadur** [comment]
@fatorius can you please provide code to reproduce and full log trace. Also please provide the colab you are referring to . Thank you.

**Comment by fatorius** [comment]
> @fatorius can you please provide code to reproduce and full log trace. Also please provide the colab you are referring to . Thank you.

The codelab where I got the code was https://codelabs.developers.google.com/codelabs/tensorflowjs-convert-python-savedmodel#5

The code is pretty simple, I have the index.html:

```html
<!DOCTYPE html>

<html>

    <head>
        <title>Testing the JS Model</title>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.6.0/dist/tf.min.js"></script>
        <script src="scripttest.js"></script>
    </head>

    <body>

    </body>

</html>
```

In the scripttest.js I have:
```javascript
const MODEL_URL = "../model/model.json"

async function run() {
    // Load the model from the CDN.
    const model = await tf.loadLayersModel(MODEL_URL, strict=false);
    
    // Print out the architecture of the loaded model.
    // This is useful to see that it matches what we built in Python.
    console.log(model.summary());

    // Create a 1 dimensional tensor with our test value.
    const input = tf.tensor1d([TEST_VALUE]);

    // Actually make the prediction.
    const result = model.predict(input);
}

run();
```

The full log trace is in my first post, but if you want to see it running by yourself I've put it into my website: http://hugosouza.com/test_tfjs/

Since it doesnt't outputs anything in the ```console.log(model.summary())``` I'm suspecting it's caused by the ```await tf.loadLayersModel(MODEL_URL, strict=false);``` line

**Comment by fatorius** [comment]
I realised that in my code there wasn't declared the value for INPUT_VALUE, so I changed it and I am still getting the same error

```
const MODEL_URL = "../model/model.json"

async function run() {
    // Load the model from the CDN.
    const model = await tf.loadLayersModel(MODEL_URL, strict=false);

    const TEST_VALUE = 950.0
    
    // Print out the architecture of the loaded model.
    // This is useful to see that it matches what we built in Python.
    console.log(model.summary());

    // Create a 1 dimensional tensor with our test value.
    const input = tf.tensor1d([TEST_VALUE]);

    // Actually make the prediction.
    const result = model.predict(input);
}

run();
```

```
Uncaught (in promise) TypeError: e.forEach is not a function
    at bg (util_base.js:681)
    at Mw (tensor_ops_util.js:44)
    at Lw (tensor.js:56)
    at Ww (io_utils.js:225)
    at RM (models.js:334)
    at models.js:316
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at bv (runtime.js:747)
```

But in none of these script files there is any e.forEach function, so I don't get what is not working here

**Comment by rthadur** [comment]
I was able to run the codelab with out any issues , here is the glitch example https://glitch.com/edit/#!/funny-polar-dirt?path=script.js%3A31%3A32 , please check

**Comment by fatorius** [comment]
> I was able to run the codelab with out any issues , here is the glitch example https://glitch.com/edit/#!/funny-polar-dirt?path=script.js%3A31%3A32 , please check

I see, can you try with my model? The code is pretty the same in my site and in the codelab, which makes me think that there must be something wrong in my model. Can you tell me if tensorflow.js handles Bidirectional layers or LSTM layers? Maybe this is causing the error because it's not supported.

Anyway, I'm sending my model for you to take a look:
https://we.tl/t-fJXQs70vZH
