### ISSUE TITLE
Serialize to Memory

### ISSUE THREAD

**Issue by Jaliborc** [tensorflow/tfjs#503]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.0

#### Describe the problem or feature request
Allow us to serialize models into memory (let serialization = model.save ) instead of being restricted to files, local storage, etc. It's terrible having to save models to file and loading the result just so we can work with the serialization.

The serialization can be a buffer, a bytearray, a .json compatible object structure. Doesn't matter, just give us something lower level instead of hiding it behind the .save function.

**Comment by caisq** [comment]
@davidsoergel  has recently added `tf.io.withSaveHandler()` that I believe will address your need. See a code example at:

https://github.com/tensorflow/tfjs-core/blob/master/src/io/passthrough.ts#L86

@Jaliborc can you let me know whether this will work for you? Note that it's not available in the latest release (0.12.0) yet, but will be in the next release.

**Comment by Jaliborc** [comment]
I'll try it out and let you know.

**Comment by davidsoergel** [comment]
Yep, this is now in place as @caisq showed.
