### ISSUE TITLE
Contribute a project to TFJS Gallery

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/tfjs#5031]
I am looking to contribute an example to the [TFJS Gallery](https://github.com/tensorflow/tfjs/blob/master/GALLERY.md).

I plan on contributing [this project](https://github.com/Rishit-dagli/Greenathon-Plant-AI) by me. This is a web application that could help easily diagnose diseases in plants using Machine Learning all on the web. The underlying model can classify among 38 healthy and unhealthy plant categories by species and disease. This model was trained on the plant_village (Hughes et al.) dataset [1].

A hosted version of this is also available to try out at https://www.plant-ai.tech/, coupled with [this set](https://drive.google.com/drive/folders/13gjzw--osiXXZdIrhtyzB6WvCtHY36Wj?usp=sharing) of images from the text set (to ensure the model hasn't seen those) for testing purposes.

I request you to kindly review if this would be a good fit for the TFJS Gallery.

### References

[1] Hughes, David P., and Marcel Salathe. “An Open Access Repository of Images on Plant Health to Enable the Development of Mobile Disease Diagnostics.” ArXiv:1511.08060 [Cs], Apr. 2016. arXiv.org, http://arxiv.org/abs/1511.08060.

**Comment by rthadur** [comment]
@Rishit-dagli excellent job , @jasonmayes @lina128 can this be added to TFJS Gallery ?

**Comment by jasonmayes** [comment]
Thanks Rishit - just to confirm, the version you plan to add to the TFJS Gallery uses TensorFlow.js right? The one linked seems to be using Python or will you convert the resulting savedmodel to TFJS format to run in browser for this TensorFlow.js demo?

**Comment by Rishit-dagli** [comment]
Hi @jasonmayes ,
The code in the project [GitHub repo](https://github.com/Rishit-dagli/Greenathon-Plant-AI) and the [hosted web app](https://www.plant-ai.tech/), both run the TFJS model on the browser.

**Comment by jasonmayes** [comment]
Ah yes I see it. In that case I am happy on my side for us to link this. Seems like a good use case to link to.

**Comment by Rishit-dagli** [comment]
> Ah yes I see it. In that case I am happy on my side for us to link this. Seems like a good use case to link to.
> @rthadur

Thank You, I will make a PR adding this project.
