### ISSUE TITLE
"info.backend.decComplexRef is not a function" when using tfjs-models

### ISSUE THREAD

**Issue by rubenlg** [tensorflow/tfjs#5042]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- TensorFlow.js installed from (npm or script link): @tensorflow/tfjs-node-gpu
- TensorFlow.js version (use command below): 3.6.1
- Browser version: N/A (Nodejs 14)
- Tensorflow.js Converter Version: ???

**Describe the current behavior**
`(node:2070191) UnhandledPromiseRejectionWarning: TypeError: info.backend.decComplexRef is not a function`

**Describe the expected behavior**
No errors

**Standalone code to reproduce the issue**

Minimal repro program (`test.ts`):
```typescript
import * as use from '@tensorflow-models/universal-sentence-encoder';
import * as tf from '@tensorflow/tfjs-node-gpu';

async function main() {
  // Dropping this line makes the error go away, although the error is in .add below.
  const sentenceModel = await use.load();
  const model = tf.sequential();
  model.add(tf.layers.dense({
    units: 16,
    activation: 'sigmoid',
    inputShape: [3],
  }));
}
main();
```

package.json is generated by running these commands:
```bash
npm init
npm install --save-dev @tensorflow-models/universal-sentence-encoder @tensorflow/tfjs-node-gpu ts-node typescript
```
I run the main script like so:
```bash
node_modules/.bin/ts-node test.ts
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
(node:2070982) UnhandledPromiseRejectionWarning: TypeError: info.backend.decComplexRef is not a function
    at Engine.disposeTensor (/tmp/kk/node_modules/@tensorflow/tfjs-core/src/engine.ts:874:20)
    at Tensor.dispose (/tmp/kk/node_modules/@tensorflow/tfjs-core/src/tensor.ts:388:17)
    at Dense.Layer.addWeight (/tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/engine/topology.ts:1298:15)
    at Dense.build (/tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/layers/core.ts:244:26)
    at /tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/engine/topology.ts:993:14
    at nameScope (/tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/common.ts:48:20)
    at Dense.Layer.apply (/tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/engine/topology.ts:979:12)
    at Sequential.add (/tmp/kk/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-layers/src/models.ts:478:15)
    at /tmp/kk/test.ts:8:9
    at step (/tmp/kk/test.ts:33:23)
```

**Note**: If I drop the line initializing the universal sentence encoder, the error disappears.

**Comment by rubenlg** [comment]
FTR: I get the same results if I install `@tensorflow/tfjs` instead of the node-gpu version.

**Comment by rthadur** [comment]
please check if this is issue is related in your case https://github.com/tensorflow/tfjs/issues/4609 ? thank you

**Comment by rubenlg** [comment]
I saw that other issue. The only relationship is the stack trace, everything else seems unrelated. I'm not using the wasm backend, and as I mentioned in my last comment, using `tfjs` **instead** of `tfjs-node-gpu` exhibits the same behavior.

I believe this is a bug in the interaction between tfjs-models and the last version of tfjs. It used to work well in the past, but after the last update of tfjs, it started failing.

**Comment by rubenlg** [comment]
The version I was using before the upgrade was `@tensorflow/tfjs-node-gpu`version `2.8.0`. I followed my steps from the original post in a clean directory forcing that version and it does indeed work.

I suspect it has something to do with running in a `node` environment, because I can't make it fail in codepen. 

I did some poor-man's binary search to identify the version that broke things:

2.8.0: works
2.8.6: works
3.0.0: fails
3.6.1: fails

Looks like this broke with tfjs 3.0, since 2.8.6 was the previous version published on npm.

Are you able to reproduce this by following the commands in my original post?

**Comment by rthadur** [comment]
@rubenlg I could not run the above commands , can you please provide a git repo or steps to reproduce the same . Thank you

**Comment by rubenlg** [comment]
Did the git repo help with reproducing the bug?

**Comment by rthadur** [comment]
I was not able to run on this my machine and reproduce the same.

**Comment by rubenlg** [comment]
I ran the script with `--inspect-brk` to debug it in the chrome devtools and get some insights. Hopefully this helps:
`info.backend` is of type `MathBackendCPU`.

Here is a screenshot of the debugger where you can see that this backend does indeed lack that `decComplexRef` member:
![image](https://user-images.githubusercontent.com/12220495/119271201-d5ec7f00-bc00-11eb-9fd4-69775f9be0a1.png)

While debugging, I noticed that depending on whether I was using `universal-sentence-encoder` or not, I got a slightly different version of the `engine.ts` file. Indeed, when inspecting the node modules, I saw this:

* In `node_modules/@tensorflow/tfjs-core` I got version 2.8.6 (because that's forced by the dependencies of `universal-sentence-encoder`.
* In `node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core` I got version 3.6 (same as tfjs itself).

This might be a weird interaction with NPM (version 7.14.0). It keeps one tfjs-core at the root node_modules, and another copy with a different version inside of `@tensorflow/tfjs`.

It's weird, because this is a snippet of the `package.json` for `@tensorflow-models/universal-sentence-encoder` as I get it when installing with npm even on a fresh directory:

```json
{
  "name": "@tensorflow-models/universal-sentence-encoder",
  "version": "1.3.2",
  [...]
  "peerDependencies": {
    "@tensorflow/tfjs-converter": "^2.0.1",
    "@tensorflow/tfjs-core": "^2.0.1"
  },
  "devDependencies": {
    "@tensorflow/tfjs-backend-cpu": "^2.0.1",
    "@tensorflow/tfjs-converter": "^2.0.1",
    "@tensorflow/tfjs-core": "^2.0.1",
```

However, I see in github that the dependency is not 2.x but 3.x. Is it possible that the package uploaded to NPM is incorrect?

**Comment by rubenlg** [comment]
Checking the blame of `@tensorflow-models/universal-sentence-encoder` sheds quite a bit of light into this issue:

https://github.com/tensorflow/tfjs-models/blame/master/universal-sentence-encoder/package.json

The dependencies were updated but the version of the package remained the same, so there is a discrepancy between the dependencies in npm and in github.

Can you please release a new version of `universal-sentence-encoder` with the updated dependencies? That should fix this issue.

**Comment by outermeasure** [comment]
I could also reproduce this bug when using node v14, npm v7.14 and the following deps in package.json:

```
"devDependencies": {
    "@tensorflow-models/universal-sentence-encoder": "^1.3.2",
    "@tensorflow/tfjs": "3.6.0",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  }
```
It wasn't reproducible with npm v6.

**Comment by rthadur** [comment]
@rubenlg @outermeasure Thank you confirming. We will be releasing new version of npm.

**Comment by rubenlg** [comment]
Ping

**Comment by rthadur** [comment]
Dependencies are updated in npm https://npm.runkit.com/@tensorflow-models/universal-sentence-encoder/package.json?t=1622731783058 , please verify. Thank you @lina128

**Comment by rubenlg** [comment]
I can confirm this resolved the issue. Thanks everyone!
