### ISSUE TITLE
face-landmarks-detection blocks UI thread

### ISSUE THREAD

**Issue by mathieuUbble** [tensorflow/tfjs#5045]
Hi there,

I have been using the library [FaceMesh](https://github.com/tensorflow/tfjs-models/tree/master/facemesh) for the last weeks, but, as it is suggested on the repo (_This repository has been archived in favor of tfjs-models/face-landmarks-detection and will no longer be updated._), I had to move to [FaceLandmarksDetection](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection)

However, it appears to me that the performance of the new package are less great than the performance of the first package: with [FaceMesh](https://github.com/tensorflow/tfjs-models/tree/master/facemesh), the UI thread isn't blocked. Although with [FaceLandmarksDetection](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection), the UI threat is blocked during the first inference (the first inference is the longest one since the tensors have to be uploaded from the CPU to the GPU)

To illustrate my point, I made these sand box code:
- a sandbox using facemesh model: https://codesandbox.io/s/facemeshtest-0oe3n 
In this sandbox, you can see that during the first inference, the UI thread is still fluid.

- a sandbox using face-landmarks-detection model: https://codesandbox.io/s/facelandamarkdetection-fsj2k
In this sandbox, you can see that during the first inference, the UI thread is blocked for a few seconds (first inference).

My questions are the following:
- Do you confirm that the performance are less great with the face-landmarks-detection model ?
- If yes, do you have an explanation, and a workaround to unblock the UI thread during the first inference ? I tried to use webworker, but if I want to use webgl backend with webworker, I require an Offscreencanvas which is only supported by chrome...

Thank you very much for your help 🙏

**Comment by vladmandic** [comment]
@mathieuUbble just my $0.02 - as long as model is using `webgl`, there will be significant warmup time - and that time increases with model complexity. but that is not the same as model *performance*, let's not overload that term.  

also, there is no way to totally free up main thread no matter how much async operations are used - it's the nature of javascript.
that, is - unless you use web workers. and if you do, you don't need `offscreenCanvas` - regardless of support, it's an inefficient way of transferring data to worker since it has to be copied instead of passed by reference.

try `imageData` buffer instead - it's supported on safari/firefox/chrome:

in main thread:
```js
const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
worker.postMessage({ image: imgData.data.buffer, width: imgData.width, height: imgData.height }, [imgData.data.buffer]);
```

and then in worker, either reconstruct ImageData (`new ImageData(new Uint8ClampedArray(msg.data.image), msg.data.width, msg.data.height)`) or even faster - create an input tensor and pass that to model for inference.

**Comment by mathieuUbble** [comment]
@vladmandic Thank you very much for your very comprehensive response ! It is very helpful ! 
I still have one question: do you know whether it is possible to use webgl backend with a webworker ? I read in some articles that the only way to use webworker with webgl backend was to use `offscreenCanvas`. Perhaps you can confirm or not this claim ? If it is possible, do you know how I could handle it ?
Once again, thank you for your help !

**Comment by vladmandic** [comment]
@mathieuUbble nope, `webgl` doesn't work within a thread as it needs either `Canvas` or `offscreenCanvas` (either will do).  
so if a browser doesn't support offscreenCanvas, it will use Canvas.  
but workers don't support DOM objects, so there is no Canvas inside a worker.  

at the end, you get an error:  

> `Error when getting WebGL context:  Error: Cannot create a canvas in this context`

which comes from initialization of `webgl` backend in `getWebGLRenderingContext()`  

its unfortunate as **tfjs** only needs a canvas context handle so it's able to communicate with gpu using gles, it doesn't actually use any of the canvas functions.

it *may* be possible (just maybe) to do a custom tfjs backend registration that uses a hacked polyfill for canvas so it can be used inside a worker (something like <https://github.com/ai/offscreen-canvas>), i might give that a try.

btw, it's not just **chrome** (and all chromium-based browsers) that supports `offscreenCanvas`, **firefox** has it for a while now, but you need to enable it in `about:config`: `gfx.offscreencanvas.enabled` (why is firefox leaving it disabled by default for such a long time is beyond me).  
but that still leaves **safari** as *unsupported*.

**Comment by vladmandic** [comment]
@mathieuUbble if you're going down the custom backend rathole, this might help as a starting point: <https://github.com/vladmandic/human/blob/main/src/tfjs/backend.ts>
