### ISSUE TITLE
Model conversion does not fully work

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#5060]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Mac, Colab, CentOS**
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:  **v3.6.0**

**Describe the current behavior**

I try to convert a model:
```bash
tensorflowjs_converter --input_format=keras model.h5 web_model
```

But then I need to fix the following:
```python
import json
model_info = json.load(open("web_model/model.json", "r"))

# Fix class name from "Functional" to "Model"
model_info["modelTopology"]["model_config"]["class_name"] = "Model"

# Fix input shape
model_info["modelTopology"]["model_config"]["config"]["layers"][0]["config"]["batch_input_shape"] = [1,1,468*3]

# Make all recurrent layers stateful
for layer in model_info["modelTopology"]["model_config"]["config"]["layers"]:
  if "stateful" in layer["config"]:
    layer["config"]["stateful"] = True


json.dump(model_info, open("web_model/model.json", "w"))
```

**Describe the expected behavior**
No need to fiddle with the `model.json`

**Standalone code to reproduce the issue**
Exists above. h5 file attached
[model.h5.zip](https://github.com/tensorflow/tfjs/files/6458397/model.h5.zip)

**Comment by AmitMY** [comment]
I'm using `tensorflow==2.4.1` and:
```
"@tensorflow/tfjs": "^2.3.0",
"@tensorflow/tfjs-backend-webgl": "^2.3.0",
"@tensorflow/tfjs-converter": "^2.3.0",
"@tensorflow/tfjs-core": "^2.3.0",
"@tensorflow/tfjs-layers": "^2.3.0",
```

I'm loading using `tfjs`, it says `Functional` is not a know layer.
Without the additional fixes, for the input shape and `stateful`, the model doesn't work as expected.

**Comment by rthadur** [comment]
@AmitMY can you try with latest version of tfjs 3.6.0 ?

**Comment by AmitMY** [comment]
> @AmitMY can you try with latest version of tfjs 3.6.0 ?

works for the `Functional` part, still, the conversion does not convert the `stateful` parameter

**Comment by rthadur** [comment]
@AmitMY thank you , I guess you already opened a issue for this a while ago here https://github.com/tensorflow/tfjs/issues/3553#issuecomment-657757071 and you were manually changing the stateful parameter. @pyu10055 @lina128 any thoughts on how to fix this ? Thank you so much.

**Comment by pyu10055** [comment]
@AmitMY I took a look at your H5 file, the stateful config on both SimpleRNN layers are set to false, can you verify that? thanks

**Comment by AmitMY** [comment]
yep, that is correct, I did not use the right model file.
so this is a s none-issue.
Thanks!
