### ISSUE TITLE
React Native with TypeScript tfjs-models/universal-sentence-encoder error on model load

### ISSUE THREAD

**Issue by willcray** [tensorflow/tfjs#5063]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS 14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 12
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs
- TensorFlow.js version (use command below): 3.6.0
- Browser version: n/a
- Tensorflow.js Converter Version: @tensorflow/tfjs-react-native@0.5.0

**Describe the current behavior**
I'm trying to use tfjs-models/universal-sentence-encoder within a React Native app by following these instructions. However, I get the following error when I try to load the model:

`TypeError: undefined is not an object (evaluating '_universalSentenceEncoder.default.load'`

**Describe the expected behavior**
It should load the use model, compute embeddings, and print them to the console.

**Standalone code to reproduce the issue**
```
import React, { useEffect, useState } from 'react';
require('@tensorflow/tfjs');
const use = require('@tensorflow-models/universal-sentence-encoder');

export default function App() {

  useEffect(() => {
    console.log("App is starting...")
    
    const init = async () => {
      // initialize state variables 
      // console.log("App is initializing services...")
      
      // Load the model.
      try {
        use.load().then((model: any) => {
          // Embed an array of sentences.
          const sentences = [
            'Hello.',
            'How are you?'
          ];
          model.embed(sentences).then((embeddings: any) => {
            // `embeddings` is a 2D tensor consisting of the 512-dimensional embeddings for each sentence.
            // So in this example `embeddings` has the shape [2, 512].
            embeddings.print(true /* verbose */);
          });
        });
      }
      catch (err) {
        console.log(err);
      }
    };
  }, []);`

```

**Comment by willcray** [comment]
This was fixed via some code changes and downgrading @tensorflow/tfjs to 3.0.0 (see [this post](https://stackoverflow.com/questions/67507110/react-native-with-typescript-tfjs-models-universal-sentence-encoder-error-on-mod/67514193#67514193). 

Code changed to the following:

`import React, { useEffect, useState } from 'react';
import "@tensorflow/tfjs-react-native";
import * as tf from '@tensorflow/tfjs';
import * as use from '@tensorflow-models/universal-sentence-encoder';

export default function App() {

  useEffect(() => {
    console.log("App is starting...")
    
    const init = async () => {
      // initialize state variables 
      // console.log("App is initializing services...")
      
      await tf.ready();
      
      // Load the model.
      try {
        use.load().then((model: any) => {
          // Embed an array of sentences.
          const sentences = [
            'Hello.',
            'How are you?'
          ];
          model.embed(sentences).then((embeddings: any) => {
            // `embeddings` is a 2D tensor consisting of the 512-dimensional embeddings for each sentence.
            // So in this example `embeddings` has the shape [2, 512].
            embeddings.print(true /* verbose */);
          });
        });
      }
      catch (err) {
        console.log(`ERROR: ${err}`);
      }
    };
  }, []);`

I am, however, still only able to produce valid embeddings when running the code on an emulator. Running on physical iOS device produces an embeddings vector full of NaNs:

`[javascript] Tensor
    [[NaN, NaN, NaN, ..., NaN, NaN, NaN],
     [NaN, NaN, NaN, ..., NaN, NaN, NaN]]`

On an iOS emulator, the vector is full of valid floating point values.

**Comment by gaikwadrahul8** [comment]
Hi, @willcray 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by ndekross** [comment]
I'm experiencing a similar issue. The model runs on Android and iOS simulator fine, however returns

```
Tensor
  dtype: float32
  rank: 2
  shape: [1,512]
  values:
     [[NaN, NaN, NaN, ..., NaN, NaN, NaN],]
```
When tested on a physical iPhone
