### ISSUE TITLE
Mention of ml5.js

### ISSUE THREAD

**Issue by Aspie96** [tensorflow/tfjs#5064]
Tensorflow is a well known as an Open Source framework for machine learning.
I believe it being Open Source is one of the main features of Tensorflow.

In: https://www.tensorflow.org/js/tutorials
Tensorflow refers users to ml5.js.

ml5.js used to be an Open Source library as well, but recently decided to use a proprietary license (https://medium.com/ml5js/ml5-js-code-of-conduct-4eb8fcae1ef7).

Since Tensorflow is an important part of the Open Source community, I suggest that it should prefer avoiding to refer users to ml5.js.

If ml5.js is necessary to use Tensorflow.js easily, that's a problem, because it can no longer be done trough Open Source software (which is part of why one should use Tensorflow). In that case, it's hopeful an Open Source replacement for ml5.js will exist in the future, or that Tensorflow.js becomes easier to use, or some mixture of both.
I believe, howerver, that ml5.js can no longer be considered part of the Tensorflow ecosystem.

**Comment by rthadur** [comment]
cc @pyu10055 @mattsoulanille

**Comment by 6r1d** [comment]
If some license restricts the userbase in any way, this is simply wrong.

To be clear, what restrictions will `ml5.js` impose on the userbase from now on?

What also needs clarification is how much this influences TensorFlow itself.

* Will the use of `ml5.js` require license changes from TensorFlow?
* Will it require users to agree with something and / or act in a certain way?
* Will it limit access to the library to some groups?

**Comment by jasonmayes** [comment]
So a few things:

1) I would say TensorFlow.js is pretty easy to use - you can take any of our pre-made models and use them in just a few lines of JS without any background in ML at all.  I would say they are both easy to use for a regular JS developer but may target slightly different audiences - I think ML5 is highly targeting creative coders so may have some extra models and functions for that sort of thing which is beyond the scope of the core TFJS library itself.

2) Your questions should be posed to ML5.js as we can not answer on their behalf. To the best of my knowledge they are open source when I last spoke to them. My guess the extra clause added around ethical use is to help prevent machine learning being used for malicious use cases. Again what they mean by that you would have to ask them for clarification.

3) You are of course welcome to make your own library as you stated - if you do I would love to check it out so let me know if that ever exists!

Jason

**Comment by Aspie96** [comment]
For future readers: another user, after my post, added a list of questions, unrelated to Tensorflow and about ml5. @jasonmayes's answer followed. Then the questisons were deleted.

Hi, @jasonmayes.

> Your questions should be posed to ML5.js as we can not answer on their behalf.

I believe this refers to the now deleted off topic questions from another user, but the rest of your point is relevant.

> To the best of my knowledge they are open source when I last spoke to them. My guess the extra clause added around ethical use is to help prevent machine learning being used for malicious use cases.

What makes Tensorflow (or any other software) Open Source is not merely source availability, but also, and importantly, Open Source licensing. Licenses that try to restrict users or prevent certain use cases do not, by definition, qualify as Open Source.

ML5 used to be Open Source until very recently. Now, the license is different and is meant to prevent certain use cases, making ML5 effectively proprietary.

Tensorflow being Open Source is one of Tensorflow's greatest benefits. This makes it useful for research (programs are a way to gather and publish information) and government-funded works (since laws already restrict behaviour which the State considers harmful). There are many other reasons to prefer (truly) Open Source software, expecially as a dependency outside of these cases. The principles of Open Source mean that Open Source comes with as few strings attached as possible, this is quite unifying for the community (and provides certainty and simplicity for companies).

Now, ML5 not being Open Source is not a problem, in principle. They don't claim it is, either, so it's a legitimate choice. I am however, saying that using Tensorflow.js trough ML5 means no longer having one of the greatest advantages about Tensorflow.js, which is it being Open Source.

This is not Tensorflow's fault, of course. I am aware Tensorflow and ML5 are in no way affiliated and have separate governance. However, because of the current state of ML5, I am suggesting that Tensorflow.js should no longer suggest users to use it, because it means suggesting them to renounce taking advantage of the Open Source state of Tensorflow.js and driving them towards a proprietary dependency (and away from Tensorflow's great Open Source ecosystem and community).

>  I think ML5 is highly targeting creative coders so may have some extra models and functions for that sort of thing which is beyond the scope of the core TFJS library itself.
> You are of course welcome to make your own library as you stated - if you do I would love to check it out so let me know if that ever exists!

The thing is, ML5 is no longer Tensorflow.js provided to a different audience because it differs from Tensorflow.js not only in terms of API, but in terms of licensing as well, making it a much less preferrable solution.

I'd argue that currently there isn't a suitable library which provides such functionalities targeted at creative coders, which can effectively be considered as having the advantages of Tensorflow.js.

**Comment by Aspie96** [comment]
@jasonmayes I fully recognize this is a very low priority "issue" as it only (mildly) affects documentation.
May I ask whether there has been any internal conversation about this?

**Comment by Aspie96** [comment]
I'd like to provide some additional information.

First, ML5 confirms that their license does not comply with the Open Source Definition:
https://medium.com/ml5js/a-new-code-of-conduct-and-license-for-ml5-js-6b0e4c109b76
> We understand that incorporating ethical concerns into open source licenses violates the terms of the Open Source Definition maintained by the Open Source Initiative.

They also state:
> That may mean that some people will no longer view ml5.js as open source software.

This is a huge understatement as that "some people" include, at minimum, OSI, all its affiliates (including Debian), the FSF and GNU project (which recognize the meaning of "open source", while not supporting the phrase) and many others. The definition is also widely recognized by the community in which it was firt popularized, by contracts and possibly even governments. I'd argue it's one of the best recognized definitions:
- https://opensource.org/affiliates
- https://opensource.org/authority
- https://commonsclause.com/ (as an example, the Commons Clause correctly claims not to be open source).

One thing which strongly conflicts with the OSD, besides being an ethical license, is the fact that it can change, effectively revoking some terms.

According to Kyle E. Mitchell, who is a lawyer who is happy about this license:
https://writing.kemitchell.com/2021/01/12/ml5js-Takes-a-Stand.html
> I would read this to require staying up to date on changes to the code of conduct, for example. If you download the software on January 1, the code of conduct changes in February, and you use the software in violation of the new February code in March, I could see you getting notice of a violation.

**Comment by jasonmayes** [comment]
@Aspie96 On a somewhat related but also different note you may be interested in a project we just announced from Google that may be useful to you in the future:
https://ai.googleblog.com/2023/04/visual-blocks-for-ml-accelerating.html?m=1
