### ISSUE TITLE
Audio is glitching/distortion using playRawAudio

### ISSUE THREAD

**Issue by adotnusiyan** [tensorflow/tfjs#5071]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.6.0
- speech-command version: 0.5.4
- Browser version: Version 90.0.4430.212 (Official Build) (x86_64)

**Describe the current behavior**
I'm using basic code from [the example in README](https://github.com/tensorflow/tfjs-models/tree/b5d49c0f5ba2057cc29b40317126c5f182495f96/speech-commands#transfer-learning) and the audio doesn't sound right. You can hear glitching/distortion in the audio

**Describe the expected behavior**
Expected to have audio without glitching/distortion

**Standalone code to reproduce the issue**
[Example in Codesandbox](https://codesandbox.io/s/tfjs-play-raw-audio-v0y12?file=/src/App.tsx:1100-1112)

**Comment by adotnusiyan** [comment]
@lina128 
I tried [this solution](https://stackoverflow.com/a/38555027/9340882), but it didn't work..

**Comment by Timothycobain87** [comment]
I would sat stop but its to late now Sent from Mail for Windows 10 From: adotnusiyanSent: Thursday, May 20, 2021 11:54 PMTo: tensorflow/tfjsCc: SubscribedSubject: Re: [tensorflow/tfjs] Audio is glitching/distortion using playRawAudio ***@***.***I tried this solution, but it didn't work..—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by adotnusiyan** [comment]
@lina128 
Is there any updates on this issue? Thanks

**Comment by lina128** [comment]
Hi, I took a look at this, not sure why audio glitches. This is not a typical use of the API and our model seems run well.

**Comment by adotnusiyan** [comment]
@lina128 
What's the typical use?

I did not do any custom code. It's what you suggested [here](https://github.com/tensorflow/tfjs/issues/4736#issuecomment-802300190). And just like what's written in [README](https://github.com/tensorflow/tfjs-models/tree/b5d49c0f5ba2057cc29b40317126c5f182495f96/speech-commands#transfer-learning)

**Comment by lina128** [comment]
I mean playing back the raw audio is not the main purpose of this API. As long as the model is working well, there's nothing to fix.

**Comment by adotnusiyan** [comment]
@lina128 
If it's not the "main" purpose, it doesn't mean there's "nothing" to fix. Maybe it should have a low priority, but not "closed"!
