### ISSUE TITLE
Button styling on Firefox for Linux.  Buttons overlap

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#508]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.0

#### Browser version
Firefox Linux  	52.8.1

#### Describe the problem or feature request
The 'Edit' button overlaps the 'Run' button

![image](https://user-images.githubusercontent.com/547150/42637483-4d09dee2-85b9-11e8-8792-232ff60a8956.png)

**Comment by nsthorat** [comment]
This doesn't seem to be an issue anymore.
