### ISSUE TITLE
tfjs-backend-wasm - How to enable symbols for wasm function names

### ISSUE THREAD

**Issue by rahulchaphalkar** [tensorflow/tfjs#5091]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., WSL2 Ubuntu 20):
- Mobile device (e.g. Surface Laptop i7-1065G7) if the issue happens on mobile device:
- TensorFlow.js installed from (script link):
- TensorFlow.js version: 3.6.0
- CUDA/cuDNN version: N/A

**Describe the problem**
Is there a good way to enable symbols for showing function names for the wasm backend? I have tried adding `--copt="-g" --strip=never` to `tfjs-backend-wasm\scripts\build-wasm.sh` before building, but it doesn't seem to achieving the desired result.
I have also tried `-c dbg` instead of the existing `-c opt` but that didn't work either.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Comment by jinjingforever** [comment]
Hi Rahul,

Looks like you need to do both of the following to make it work:

- Add `--copt="-g"` to [build-wasm.sh](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/scripts/build-wasm.sh#L27)
- Add `"-g"` to `linkopts` in the [BUILD](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/src/cc/BUILD#L34) file.

I tried it and here is the end result when I step into the WASM instructions (`tf.add` in this case):

![Screen Shot 2021-05-19 at 5 39 01 PM](https://user-images.githubusercontent.com/8752427/118902193-07e0a700-b8ca-11eb-8972-fdb801456ed1.png)

Thanks!
