### ISSUE TITLE
why is @tensorflow/tfjs-backend-wasm still in alpha？

### ISSUE THREAD

**Issue by seminelee** [tensorflow/tfjs#5093]
why is @tensorflow/tfjs-backend-wasm still in alpha？what problems is facing？
Can @tensorflow/tfjs-backend-wasm be used in project online？
Thank you

**Comment by jinjingforever** [comment]
Thank you for the report! Looks like the README file is outdated. It is no longer in alpha and it is definitely can be used in online projects. I will update it.

The only thing to note is that not all our pre-trained models support the WASM backend. I will update the list in the README file too. Thanks!
