### ISSUE TITLE
Extract TFLite Metadata with TFJS TFLite API

### ISSUE THREAD

**Issue by Rishit-dagli** [tensorflow/tfjs#5099]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): TFJS TFLite API 0.0.1-alpha.4
- Are you willing to contribute it (Yes/No): I could, but I am yet to explore the TFJS TFLite API completely

**Describe the feature and the current behavior/state.**
As of now, the TFJS TFLite API does not allow extracting metadata from TFLite models, which I think would be pretty useful.

**Will this change the current api? How?**
I believe this should not change the working of the current API, maybe we could have a new method in the [tflite.TFLiteModel](https://js.tensorflow.org/api_tflite/0.0.1-alpha.4/#class:TFLiteModel) class to extract the metadata.

**Who will benefit with this feature?**
I believe this would be quite useful for all users, especially for folks to use random TFLite models they find on the web with TFJS. This will also help convey the best practice when using the model. I am not sure if this is on the TFJS Roadmap (should I create a separate feature request for this?) but if a tool similar to Android Studio ML Model Binding Plugin or the TFLite Android Code Generator was to be made for TFJS, it would imply adding support to extract model metadata.

**Any Other info.**
Thanks, @pyu10055 for suggesting to send this over as a feature request at TensorFlow.js Q&A at Google IO

**Comment by gaikwadrahul8** [comment]
Hi, @Rishit-dagli 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and if I'm not wrong this feature hasn't implemented yet so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by Rishit-dagli** [comment]
@gaikwadrahul8 I think this would still be helpful for me (motivations described in the issue).
