### ISSUE TITLE
Different shape values and performance issue depending on browser

### ISSUE THREAD

**Issue by wojciechtryba** [tensorflow/tfjs#5100]
**System information**
- OS Platform and Distribution: macOs Catalina
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.6.0
- Browser version: Google Chrome 90.0.4430.212, Mozilla Firefox 88.0.1, Safari 13.0.5

**Describe the current behavior**

The code is executed in Angular 10 web worker.

1. Using ```tf.real()``` or ```tf.imag()``` after ```tf.rfft()``` results in getting different ```shape``` value depending on browser used. For example:
```
const samples = [1, 2, 3, 4, 5, 6];
const x = tf.tensor1d(samples).rfft();
const xRe = tf.real(x);
const xIm = tf.imag(x);
```
On Firefox and Safari values ```xRe.shape``` and ```xIm.shape``` are equal to ```[4]```, but on Chrome both are ```[1, 4]```. The extra dimension is added.

2. Using ```tf.complex(xRe, xIm).irfft()``` where ```xRe``` and ```xIm``` are large number of data (e. g. about 300 000 samples) causes very long time of executing for Firefox and Safari. Is there a way to increase the performance? On Chrome the performance is ok.

**Describe the expected behavior**
1. The result value of ```shape``` should be consistent in different browsers.
2. Faster performance

**Comment by pyu10055** [comment]
@wojciechtryba I have tried your example code on both firefox(88.0.1) and safari (14.1). The xRe and xIm all have the same shape as chrome [1, 4], please confirm that are you using webworker in both cases?

**Comment by rosek86** [comment]
Hi @pyu10055,

We investigated this further, and we get different shape for webgl and cpu backends. Is it expected? For some reason Tensorflow switches to the cpu backend, and then we get different shape and very slow computation.

We've been trying to implement upsampling using FFT method but we'll move computation to the backend for a time being.

**Comment by pyu10055** [comment]
If you are using webworker, currently only chrome/edge support offscreen canvas, safari and firefox do not, it will revert back to cpu.
But if you can afford to run the model with the main js thread, webgl result should be consistent across browsers.
