### ISSUE TITLE
[Codelab]: TensorFlowJS Comment Spam Detection

### ISSUE THREAD

**Issue by iathul** [tensorflow/tfjs#5111]
[Found a typo in Section 8 Serve the machine learning model](https://codelabs.developers.google.com/codelabs/tensorflowjs-comment-spam-detection?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fget-started-text-classification-web%3Fhl%3Den%23codelab-https%3A%2F%2Fcodelabs.developers.google.com%2Fcodelabs%2Ftensorflowjs-comment-spam-detection#7)

The current sentence is like this. **First, if you have not done so already, unzip the files you downloaded for the model downloaded at the start of this codelab.** The word downloaded is repeating and it bit confusing. 
It will be better if we remove the second occurrence of word downloaded so the sentence will be more understandable like this.

**First, if you have not done so already, unzip the files you downloaded for the model  at the start of this codelab**

**Comment by jasonmayes** [comment]
Thanks for the feedback on this one. I shall update that and push it out shortly.

**Comment by jasonmayes** [comment]
Changes made they should be pushed live shortly (next day or two).
