### ISSUE TITLE
use posenet.js with flutter mobile

### ISSUE THREAD

**Issue by R-abodyak** [tensorflow/tfjs#5112]
I realy want to use  
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet"></script> 
in flutter web , so I put scripts  and this test code in index.html :

    posenet.load().then(function(net) {
      const pose = net.estimateSinglePose(imageElement, {
        flipHorizontal: true
      });
      return pose;
    }).then(function(pose){
      console.log(pose);
    })

but how to call it in dart?

**Comment by lina128** [comment]
Hi @R-abodyak, to call it in dart, you can use dart:js library (https://api.dart.dev/stable/2.12.2/dart-js/dart-js-library.html) to wrap essential TF.js methods. We can also provide such dart wrapper if needed, please let us know if you want to request this feature.
