### ISSUE TITLE
React Native : Huge Memory Leak when using face-landmark-detection in estimateFaces() function

### ISSUE THREAD

**Issue by OckyKristanto-TomTom** [tensorflow/tfjs#5115]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Tablet S6
- TensorFlow.js installed from (npm or script link): yarn add @tensorflow/tfjs
- TensorFlow.js version (use command below): 3.6.0
- Browser version: -
- Tensorflow.js Converter Version: -

**Describe the current behavior**
Huge Memory Leak happening when calling estimateFaces() inside TensorCamera Loop
(**Memory usage reach 3.5 GB in less than 1 Minute !!!!**)

**Describe the expected behavior**
No Memory Leak 

**Standalone code to reproduce the issue**
```
"dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@tensorflow-models/face-landmarks-detection": "^0.0.3",
    "@tensorflow/tfjs": "^3.6.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "expo": "~41.0.1",
    "expo-camera": "~11.0.2",
    "expo-gl": "~10.2.0",
    "expo-gl-cpp": "~10.1.0",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-screens": "~3.0.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12"
  },
```
```
import { StatusBar } from 'expo-status-bar';
import React, {useState, useEffect} from 'react';
import { StyleSheet, Text, View } from 'react-native';
import {Camera} from 'expo-camera';
import * as tf from '@tensorflow/tfjs';
import {cameraWithTensors, bundleResourceIO} from '@tensorflow/tfjs-react-native';
import * as FaceModel from '@tensorflow-models/face-landmarks-detection';

const modelJson = require('./assets/model.json');
const modelWeights = require('./assets/group1-shard1of1.bin');

export default function App() {
  const [tensorReady, setTensorReady] = useState(false);
  const [modelReady, setModelReady] = useState(null);
  const TensorCamera = cameraWithTensors(Camera);

  useEffect(()=>{
    (async () => {
      await tf.ready();
      await tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights));
      setTensorReady(true);
      setModelReady(await FaceModel.load(FaceModel.SupportedPackages.mediapipeFacemesh, {maxFaces: 1, shouldLoadIrisModel: true}));
      console.log(tf.getBackend());
      console.log("READY!!!");
    })();
  }, [])

  const handleImage = (images, updatePreview, gl) => {
              const loop = async () => {
                let nextImageTensor = images.next().value;
                const result = await modelReady.estimateFaces({input: nextImageTensor});
                console.log(result);
                // if autorender is false you need the following two lines.
                // updatePreview(); gl.endFrameEXP();

                requestAnimationFrame(loop);
              };
              loop();
            };

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      {(modelReady && 
          <TensorCamera
            style={[styles.camera, {height: 200, width: 200}]}
            type={Camera.Constants.Type.front}
            onReady={handleImage}
            cameraTextureHeight={1080}
            cameraTextureWidth={1920}
            resizeHeight={200}
            resizeWidth={152}
            resizeDepth={3}
            autorender={true}
          />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Other info / logs** 
TensorFlow was loaded properly (with 'rn-webgl' backend engine)
The Model is also loaded properly (Attached)
Setup steps are following: https://www.npmjs.com/package/@tensorflow/tfjs-react-native

[facemesh_1_default_1.tar.gz](https://github.com/tensorflow/tfjs/files/6535008/facemesh_1_default_1.tar.gz)

**Comment by pyu10055** [comment]
@OckyKristanto-TomTom Please dispose the image tensors from TensorCamera.
Please take a look at the example [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx#L101)

**Comment by OckyKristanto-TomTom** [comment]
@pyu10055 . Indeed that dispose line solves the Memory Leak. 
Thanks a lot for the swift reaction and help

Suggestion: maybe its worth it to add the dispose line on the documentation: https://js.tensorflow.org/api_react_native/0.5.0/#cameraWithTensors

**Comment by OckyKristanto-TomTom** [comment]
Hi @pyu10055, I tried the same code in iOS iPhone7, but 
```const result = await modelReady.estimateFaces({input: nextImageTensor}); ``` always return null

Do I miss something?
