### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by sharathgg5** [tensorflow/tfjs#5123]
The section [Define the model architecture](https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#3) is not able to complete due to code error.

In the HTML code example `<script src="script.js"></script>` appears before `<body>`. Since the JavaScript code is executed before the HTML body tag has loaded, document.body is null.

A possible solution is to move the script at the end of the body tag, once it’s been loaded:

```
<body>
<script src="script.js"></script>
</body>
```

**Comment by rthadur** [comment]
This is fixed , please verify.
