### ISSUE TITLE
Introduce yarn workspaces

### ISSUE THREAD

**Issue by gyagp** [tensorflow/tfjs#5126]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): Any version
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
tfjs is a monorepo, which means it contains multiple packages. We use yarn for package management, but currently it has below problems:
* Different packages may be dependent on same node module, but we need to download it again and again in all sub folders.
* When we hope to do a change in yarn.lock, like bumping the version, we have to change all the yarn.lock files.

Yarn workspaces (https://classic.yarnpkg.com/blog/2017/08/02/introducing-workspaces/) is the way to rescue. Can we introduce it?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
tfjs developers

**Any Other info.**

**Comment by pyu10055** [comment]
@gyagp Thank you for the suggestion. @mattsoulanille will our move the bazel solve this issues? or we may still benefit from using yarn workspace?

**Comment by mattsoulanille** [comment]
Thanks for the suggestion @gyagp! This has been a long-standing issue with our monorepo that deserves to be fixed as it's a significant source of development friction. 

The move to [Bazel](https://bazel.build/) (and [rules_nodejs](https://github.com/bazelbuild/rules_nodejs)), which Angular uses as their build system, will solve this by using a single root package.json file for yarn dependencies. Packages will still have their own `package.json` files, but those `package.json`s will be used only for publishing to npm, and won't actually be used in development, which solves the issue of downloading the same yarn package multiple times

This doesn't immediately solve the issue of bumping versions, but eventually, we're planning on using Bazel to generate each package's package.json file as part of the release step, meaning we'll only have the single root package.json file to update.

**Comment by gyagp** [comment]
Thanks for the details and look forward to further integration with Bazel. Let me close this request.
