### ISSUE TITLE
Body-Pix Dataset with the latest TFJS

### ISSUE THREAD

**Issue by ideerge** [tensorflow/tfjs#5128]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 2
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The pix-body dataset can't be loaded with the latest .tsjs, the dataset sample currently uses v1.2

TypeError: t.equal is not a function
    at body-pix@2.0:formatted:384
    at tfjs:formatted:9338
    at e.t.scopedRun (tfjs:formatted:9347)
    at e.t.tidy (tfjs:formatted:9331)
    at Object.JN [as tidy] (tfjs:formatted:13060)
    at body-pix@2.0:formatted:383
    at body-pix@2.0:formatted:386
    at Array.map (<anonymous>)
    at body-pix@2.0:formatted:381
    at tfjs:formatted:9338

**Will this change the current api? How?**

**Who will benefit with this feature?**
Those using the latest tsjs

**Any Other info.**

**Comment by rthadur** [comment]
Thank you for reporting,I was also not able to run using latest version. @pyu10055 @lina128 looks like latest changes are causing the errors , can you please check ?

**Comment by lina128** [comment]
Hi, I'm able to run the body-pix demo with tfjs 3.6.0 and 3.7.0. Can you share a reproducible code?
