### ISSUE TITLE
tf.image.greyscale_to_rgb

### ISSUE THREAD

**Issue by lina128** [tensorflow/tfjs#5134]
Useful for converting greyscale image back to rgb so that the output can be rendered on canvas with toPixels.

tf api: https://www.tensorflow.org/api_docs/python/tf/image/grayscale_to_rgb

**Comment by himanshu007-creator** [comment]
Hi ! i would like to work on this issue

**Comment by lina128** [comment]
That’s great! Looking forward to your PR @himanshu007-creator

**Comment by himanshu007-creator** [comment]
import tensorflow as tf

def process_image(image):
    image = tf.convert_to_tensor(image, dtype=tf.uint8)
    image_rgb =  tf.cond(tf.rank(image) < 4,
                         lambda: tf.image.grayscale_to_rgb(tf.expand_dims(image, -1)),
                         lambda: tf.identity(image))
    # Add shape information
    s = image.shape
    image_rgb.set_shape(s)
    if s.ndims is not None and s.ndims < 4:
        image_rgb.set_shape(s.concatenate(3))
    return image_rgb


please have a look @lina128

**Comment by lina128** [comment]
Hi @himanshu007-creator , can you make a PR?

**Comment by himanshu007-creator** [comment]
> Hi @himanshu007-creator , can you make a PR?

Yes, can you point the file where i need to push this code and what name should i give to it?!

**Comment by lina128** [comment]
https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md

**Comment by raffizulvian** [comment]
Hi everyone! Is anyone working on this issue? If not can I try to work on this issue? @lina128

**Comment by himanshu007-creator** [comment]
> Hi everyone! Is anyone working on this issue? If not can I try to work on this issue? @lina128

Thanks, but at present I am working on it, incase I am unable to do so, it's all yours!

**Comment by raffizulvian** [comment]
Alright @himanshu007-creator , thanks for the info!

**Comment by raffizulvian** [comment]
Any update? @himanshu007-creator
