### ISSUE TITLE
Checkpoint Manager or something to at least store optimizer state

### ISSUE THREAD

**Issue by StoneT2000** [tensorflow/tfjs#5138]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 3.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently one can save models to anywhere but there is no documentation or code on saving optimizer states.

**Will this change the current api? How?**

Optimizers should have a function to get state information to then write somewhere or a helpful save function that will use the same api the model saving functions use to save optimizer states.

**Who will benefit with this feature?**

People looking to use training checkpoints with optimizers like adam and rmsprop or use a checkpoint manager akin to the python api! This greatly helps us with reproducibility without having to start training from scratch again.

**Any Other info.**

**Comment by rthadur** [comment]
@StoneT2000 will you be interested in contributing for the above ?

**Comment by StoneT2000** [comment]
I'd be happy to help out if possible, although not too sure where to start just yet

**Comment by gaikwadrahul8** [comment]
Hi, @StoneT2000 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and If  I'm not wrong this feature hasn't implemented in TFJs yet so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
