### ISSUE TITLE
Error when trying to use tfjs-node

### ISSUE THREAD

**Issue by CoolingJam** [tensorflow/tfjs#5150]
**System information**
- OS Platform Windows 10 1909
- TensorFlow.js (@tensorflow/tfjs-node) installed from npm
- TensorFlow.js (@tensorflow/tfjs-node) version: 3.6.1
- Node.js version: v14.17.0 (x86)

**My code**
`require('@tensorflow/tfjs-node')`

**Error**
```
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\Programmer.exe\Desktop\Stuff\Cafe-Manager\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (C:\Users\Programmer.exe\Desktop\Stuff\Cafe-Manager\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)

```

**What I already tried**
- Deleting node_modules and reinstalling the module
- Upgrading to latest node.js
- Adding python 2 to path

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Also, I tried `npm rebuild @tensorflow/tfjs-node --build-addon-from-source`. The error is attached below.
[2021-05-31T18_35_31_293Z-debug.log](https://github.com/tensorflow/tfjs/files/6571816/2021-05-31T18_35_31_293Z-debug.log)

**Comment by rthadur** [comment]
You need to copy files from  deps/libs to lib/napi-v8, please check for similar issues raised [here](https://github.com/tensorflow/tfjs/issues?q=is%3Aissue+The+Node.js+native+addon+module+%28tfjs_binding.node%29+can+not+be+found+at+path+is%3Aclosed)  , Thank you.

**Comment by CoolingJam** [comment]
I copiled tensorflow.dll and tensorflow.dll frm deps/lib to lib/napi-v8

**Comment by rthadur** [comment]
did you get chance to check related issues ?

**Comment by CoolingJam** [comment]
yeah, none of them worked

**Comment by CoolingJam** [comment]
For some reason, after I reinstalled tfjs-node, deps/lib and lib/napi-v8 vanished

**Comment by rthadur** [comment]
Thank you , closing the issue , feel free to mention@ so that we can reopen if you see any further issues.

**Comment by CoolingJam** [comment]
@rthadur Still getting the same error, could you please reopen.

**Comment by CoolingJam** [comment]
I'm not sure how to fix this, I looked up all the solutions I could.

**Comment by rthadur** [comment]
Can you please list down the steps you were following to install ?

**Comment by CoolingJam** [comment]
- npm install @tensorflow/tfjs-node 
- npm install @tensorflow-models/toxicity

**Comment by pyu10055** [comment]
@CoolingJam after you installed @tensorflow/tfjs-node and cd into `node_modules/@tensorflow/tfjs-node`,
can you share the log from running `yarn build-addon-from-source`?

**Comment by CoolingJam** [comment]
I dont have yarn, but I attached an log of `npm rebuild @tensorflow/tfjs-node --build-addon-from-source`.

**Comment by VladislavDDP** [comment]
I am getting the same issue and no workarounds are helpful
