### ISSUE TITLE
TensorflowJS Issue : Looking for previous version of cusolver64_10

### ISSUE THREAD

**Issue by fireholster** [tensorflow/tfjs#5151]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
TensorFlowJS version: 3.6.1
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: 11.3
GPU model and memory: RTX 2060 MAXQ
Describe the problem
GPU build is looking for cusolver64_10 instead of latest cusolver64_11 version

**Comment by rthadur** [comment]
@fireholster I guess this needs to be fixed in TF Core firstly , see here for similar issue here https://github.com/tensorflow/tensorflow/issues/44291 .
cc @pyu10055 @lina128

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
