### ISSUE TITLE
VueJS App - Model.fit causes TypeError: Cannot read property 'backend' of undefined

### ISSUE THREAD

**Issue by xinterface** [tensorflow/tfjs#5154]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): NPM
- TensorFlow.js version (use command below): 3.6.0
- Browser version: Chrome Version 91.0.4472.77 :

**Describe the current behavior**

I have created custom model in using tfjs and it works with just regular javascript (mixed with Jquery) but when I tried to create VueJS app using @vue3/cli and migrate all of my code to the vue app, I started getting error when I try to fit the model. 

**Describe the expected behavior**

 **Other info / logs**  
 
```
Uncaught (in promise) TypeError: Cannot read property 'backend' of undefined
    at Engine.moveData (engine.js?6ae2:288)
    at DataStorage.get (backend.js?8b87:29)
    at eval (backend_webgl.js?5edb:497)
    at Array.every (<anonymous>)
    at MathBackendWebGL.shouldExecuteOnCPU (backend_webgl.js?5edb:497)
    at concatImpl (Concat_impl.js?2cbf:39)
    at Object.concat [as kernelFunc] (Concat.js?b4c2:35)
    at kernelFunc (engine.js?6ae2:463)
    at eval (engine.js?6ae2:524)
    at Engine.scopedRun (engine.js?6ae2:337)
moveData @ engine.js?6ae2:288
get @ backend.js?8b87:29
eval @ backend_webgl.js?5edb:497
shouldExecuteOnCPU @ backend_webgl.js?5edb:497
concatImpl @ Concat_impl.js?2cbf:39
concat @ Concat.js?b4c2:35
kernelFunc @ engine.js?6ae2:463
eval @ engine.js?6ae2:524
scopedRun @ engine.js?6ae2:337
runKernelFunc @ engine.js?6ae2:520
runKernel @ engine.js?6ae2:393
concat_ @ concat.js?649e:79
concat__op @ operation.js?54ef:44
eval @ EyeModel.js?4fc1:72
eval @ engine.js?6ae2:327
scopedRun @ engine.js?6ae2:337
tidy @ engine.js?6ae2:326
tidy @ globals.js?c04e:175
_callee$ @ EyeModel.js?4fc1:71
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
trainModel @ EyeModel.js?4fc1:70
trainModel @ Models.vue?2820:106
Object.onClick._cache.<computed>._cache.<computed> @ Models.vue?2820:17
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:163
invoker @ runtime-dom.esm-bundler.js?830f:333
Promise.then (async)
trainModel @ Models.vue?2820:106
Object.onClick._cache.<computed>._cache.<computed> @ Models.vue?2820:17
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:154
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:163
invoker @ runtime-dom.esm-bundler.js?830f:333
Show 2 more frames

```

**Comment by rthadur** [comment]
I haven't used VueJS before ,By seeing the error WebGL is not supported , it is either the dependencies are missing in the package.json or related to Vue js support for webgl ? Apologies if i am wrong. 

 cc  @mattsoulanille if you have any thoughts on this ? Thank you

**Comment by ChainYo** [comment]
I had a similar problem some weeks ago. 
You can read in your error that « in promise » means there is an async problem.
You declare the model in a function that can’t be accessed by others.
