### ISSUE TITLE
How to get a spectrogram offline with the right shape as an input to recognize() in node .js?

### ISSUE THREAD

**Issue by Leiga** [tensorflow/tfjs#5156]
I am trying to perform offline recognition with this doc: https://github.com/tensorflow/tfjs-models/tree/master/speech-commands

I had the same issue as https://github.com/tensorflow/tfjs/issues/3820 described, and I had tried all solutions suggested from there, including the colab support https://colab.research.google.com/github/tensorflow/tfjs-models/blob/master/speech-commands/training/browser-fft/training_custom_audio_model_in_python.ipynb#scrollTo=1AjdTru5NnQQ but got an array with all NaN values. Is there a solution to this problem

**Comment by gaikwadrahul8** [comment]
Hi, @Leiga 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now so  May I know are you still looking for this feature in TFJs or your issue got resolved please ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
