### ISSUE TITLE
Do not get model inferences, only thing that comes on the screen is laggy camera screen when using tensorcamera that also crushes after 1-2 minutes

### ISSUE THREAD

**Issue by ladokhasia** [tensorflow/tfjs#5158]
I do not get any warnings or errors - only that async storage has been renamed in new expo, so I have older one installed not to cause an issue (as new one crushed the code)

all code I use is here 

https://stackoverflow.com/questions/67790431/tfjs-react-native-for-real-time-object-detection-expo-managed-workflow

**Comment by rthadur** [comment]
can you please check this issue https://github.com/tensorflow/tfjs/issues/3808 if it is related ? Thank you

**Comment by ladokhasia** [comment]
@rthadur thanks a lot for your answer! I tried that, but the same happens + after one minute expo go gets closed by itself. Now I tried this example code: https://github.com/tafsiri/tfjs-expo-managed-example and again the same happened, even after reinstalling Expo Go on my android device. Otherwise my expo works just fine. Is it possible, that all of this is because I try to run the code on my android 10 ?

**Comment by ladokhasia** [comment]
tried on Android 11, same problem. only difference is that expo does not crush after 1-2 minutes

**Comment by rthadur** [comment]
please check a related issue here https://github.com/tensorflow/tfjs/issues/4902

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
