### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by IamManifold** [tensorflow/tfjs#5166]
[https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab/#4](https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab/#4)
I believe "sparseCategoricalCrossentroy" should be "sparseCategoricalCrossentropy"

This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

**Comment by rthadur** [comment]
This will be fixed and published accordingly. Thank you
