### ISSUE TITLE
Issue converting keras model to JavaScript and subsequent loading 

### ISSUE THREAD

**Issue by josephzonghaozhu** [tensorflow/tfjs#5172]
I am having difficulty loading a model that has been converted using the 'TensorFlow.js converter' . Any help would be appreciated!

**System information**
Google Colab
P5js

Tensorflow 2.5.0
TensorFlow.js Converter v3.7.0

**Describe the current behavior**

- Unable to load a model that has been converted from 'keras_saved_model' into 'tfjs_layers_model' format using 'TensorFlow.js converter'. The following errors appear in console upon attempts to load via the P5.js editor & 'tf.loadLayersModel(MODEL_PATH)':

initializers.js:131 The shape of the input tensor ([null,148,148,256]) does not match the expectation of layer conv2d_1: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,73,73,256]) does not match the expectation of layer conv2d_2: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,69,69,128]) does not match the expectation of layer conv2d_3: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,32,32,128]) does not match the expectation of layer conv2d_4: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,30,30,64]) does not match the expectation of layer conv2d_5: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,14,14,64]) does not match the expectation of layer conv2d_6: [null,150,150,3]
initializers.js:131 The shape of the input tensor ([null,5,5,32]) does not match the expectation of layer conv2d_7: [null,150,150,3]

util_base.js:154 Uncaught (in promise) Error: Based on the provided shape, [256], the tensor should have 256 values but has 0
    at Wv (util_base.js:154)
    at Mw (engine.js:1086)
    at Lw (tape.js:54)
    at Ww (engine.js:1190)
    at RM (container.js:211)
    at container.js:196
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at bv (runtime.js:747)

- Saving the model as 'keras' format (model.h5) and converting into 'tfjs_layers_model' format does not resolve the issue
- Manually editting the model.json file resolves the "initializers.js:131..." errors but not the "util_base.js:154..." error

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1EhMHvteiQqPGvZKti6cvjGuDspDXzDXP?usp=sharing

**Other info / logs**
[model.zip](https://github.com/tensorflow/tfjs/files/6598599/model.zip)
[modelConverted.zip](https://github.com/tensorflow/tfjs/files/6598601/modelConverted.zip)
[modelDescription.zip](https://github.com/tensorflow/tfjs/files/6598625/modelDescription.zip)

**Comment by rthadur** [comment]
@josephzonghaozhu sorry for the delay , were you able to run the model before converting ?

**Comment by josephzonghaozhu** [comment]
Thanks for taking a look! 

I was able to run the model with no issues before converting, I added an example at the bottom of the colab

**Comment by rthadur** [comment]
Sorry for the delay , can you provide example in P5js editor so that we can reproduce the error ?
