### ISSUE TITLE
Error: Cannot evaluate flag 'DEBUG': no evaluation function found.

### ISSUE THREAD

**Issue by kevinchristianto** [tensorflow/tfjs#5179]
**System information**
- OS Platform and Distribution: **Windows 10**
- Mobile device: **Mi 8 Lite running on Android 10**
- TensorFlow.js installed from (npm or script link): **npm**
- TensorFlow.js version: **3.7.0**

Every time I tried to run the apps and import @tensorflow/tfjs, I got an error message like this in Metro.
![image](https://user-images.githubusercontent.com/19814559/120883919-3d93c880-c60a-11eb-9ee8-f7fa3b9873ad.png)

These are the dependencies I used (this is literally a fresh new React Native project created by react-native cli.
![image](https://user-images.githubusercontent.com/19814559/120883943-6fa52a80-c60a-11eb-9165-c25a3e9cbb33.png)

I ran into this problem every time I tried to run the apps, I thought by creating a new project and install tfjs first without installing any other library/dependencies will solve this, but it still the same.

Any solution?

**Comment by Kipko** [comment]
I am getting this error too on `3.7.0`. 

<img width="1048" alt="Screen Shot 2021-06-06 at 6 26 36 PM" src="https://user-images.githubusercontent.com/11457183/120934125-f7fffa00-c6f4-11eb-8b95-4cfed2765eb3.png">

<img width="423" alt="Screen Shot 2021-06-06 at 6 30 06 PM" src="https://user-images.githubusercontent.com/11457183/120934201-457c6700-c6f5-11eb-9476-041fc2088bc3.png">

-

**Comment by roihanmufli** [comment]
is this solved ? I have same issue

**Comment by roihanmufli** [comment]
I just have solved this issue, before you import tensorflowjs on react native . you MUST follow this configuration first https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native

**Comment by kevinchristianto** [comment]
> I just have solved this issue, before you import tensorflowjs on react native . you MUST follow this configuration first https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native

I can make sure that I have followed those steps, and what steps did you do or you missed before?

**Comment by roihanmufli** [comment]
I think I missed on react-native-fs configuration, but I forgot precisely. For the ease, I suggest you try to create new project and then follow those step first before you code your program and import tensorflow.js. It really worked for me. 

By the way, I use React Native CLI

**Comment by kevinchristianto** [comment]
I've tried that, even before you tell me. I'm using React Native CLI too.
May I see your metro.config.js?

**Comment by roihanmufli** [comment]
> I've tried that, even before you tell me. I'm using React Native CLI too.
> May I see your metro.config.js?

This is my **metro.config.js**:

 const { getDefaultConfig } = require('metro-config');
 module.exports = (async () => {
   const defaultConfig = await getDefaultConfig();
   const { assetExts } = defaultConfig.resolver;
   return {
     resolver: {
       // Add bin to assetExts
       assetExts: [...assetExts, 'bin'],
     }
   };
 })();


And just in case, if you want to see my **package.json** :

{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@tensorflow/tfjs": "^3.7.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "expo-camera": "^11.0.3",
    "expo-file-system": "^11.0.2",
    "expo-gl": "^10.3.0",
    "expo-gl-cpp": "^10.3.0",
    "jpeg-js": "^0.4.3",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-fs": "^2.18.0",
    "react-native-image-picker": "^4.0.3",
    "react-native-unimodules": "^0.13.3",
    "whatwg-fetch": "^3.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by kevinchristianto** [comment]
Okay so I found the problem.
I tried to merge the metro.config.js from tfjs installation instruction with the existing one, so it become like this
```
const { getDefaultConfig } = require('metro-config');
module.exports = (async () => {
  const defaultConfig = await getDefaultConfig();
  const { assetExts } = defaultConfig.resolver;
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      // Add bin to assetExts
      assetExts: [...assetExts, 'bin'],
    },
  };
})();
```

And it gives me the errors above
But when I change it into
```
const { getDefaultConfig } = require('metro-config');
module.exports = (async () => {
  const defaultConfig = await getDefaultConfig();
  const { assetExts } = defaultConfig.resolver;
  return {
    resolver: {
      // Add bin to assetExts
      assetExts: [...assetExts, 'bin'],
    },
  };
})();
```

It worked, no error shown.

**Comment by FawadMahmood** [comment]
I am having same issue.

**Comment by kevinchristianto** [comment]
> I am having same issue.

Have you tried this one? https://github.com/tensorflow/tfjs/issues/5179#issuecomment-864395043

**Comment by FawadMahmood** [comment]
> > I am having same issue.
> 
> Have you tried this one? [#5179 (comment)](https://github.com/tensorflow/tfjs/issues/5179#issuecomment-864395043)

Hi, Yes I have tried, I am using react-native-navigation and typescript where I am having this issue.

**Comment by andrekovac** [comment]
I can confirm it: Issue present exactly as described by [here](https://github.com/tensorflow/tfjs/issues/5630#issuecomment-924147365) for the following versions:

```
"@tensorflow/tfjs": "^3.13.0",
"@tensorflow/tfjs-react-native": "^0.8.0",
```

**Comment by Th0mYT** [comment]
@grapefruitlips have you found any solution for that?

**Comment by grapefruitlips** [comment]
yes, although it took me a long time to figure everything out

versions of installed packages (package.json):
```
    "@tensorflow/tfjs": "2.8.2",
    "@tensorflow/tfjs-react-native": "0.6.0",
    "@unimodules/core": "7.1.2",
    "@unimodules/react-native-adapter": "6.3.9",
    "expo-asset": "8.3.3",
    "expo-camera": "11.2.2",
    "expo-constants": "11.0.2",
    "expo-file-system": "11.1.3",
    "expo-gl": "7.0.0",
    "expo-gl-cpp": "7.0.0",
    "expo-image-loader": "2.2.0",
    "expo-module-scripts": "2.0.0",
    "expo-modules-core": "0.2.0",
    "react-native-fs": "^2.18.0",
    "react-native-unimodules": "^0.14.10"
    "unimodules-app-loader": "2.2.0",
    "unimodules-camera-interface": "^6.1.0",
    "unimodules-task-manager-interface": "6.2.0"

    "react": "17.0.2",
    "react-native": "0.67.2"
```

first, you need to comment this line 
in `getNativeModulesFromModuleRegistry` in file `node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java`:
```
//nativeModulesList.add(new ModuleRegistryReadyNotifier(moduleRegistry));
```



then add to `public class NativeModulesProxy extends ReactContextBaseJavaModule {` in  `node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/NativeModulesProxy.java`

```
@Override    
public boolean canOverrideExistingModule() {        
  return true;    
}
```


second, you need to edit all build.gradle files in these modules:

`node_modules/@unimodules/core/android/build.gradle`
`node_modules/@unimodules/react-native-adapter/android/build.gradle`
`node_modules/expo-camera/android/build.gradle`
`node_modules/expo-constants/android/build.gradle`
`node_modules/expo-file-system/android/build.gradle`
`node_modules/expo-gl/android/build.gradle`
`node_modules/expo-gl-cpp/android/build.gradle`
`node_modules/expo-image-loader/android/build.gradle`
`node_modules/expo-modules-core/android/build.gradle`
`node_modules/unimodules-app-loader/android/build.gradle`
`node_modules/unimodules-task-manager-interface/android/build.gradle`

edit it the same way:

```
// apply plugin: 'maven'
apply plugin: 'maven-publish'

// configurations {
//  deployerJars
// }

task androidSourcesJar(type: Jar) {
  // classifier = 'sources'
  archiveClassifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

// artifacts {
//  archives androidSourcesJar
// }

publishing {
   publications {
     maven(MavenPublication) {
       artifact androidSourcesJar
// uploadArchives {
//   repositories {
//    mavenDeployer {
//      configuration = configurations.deployerJars
//      repository(url: mavenLocal().url)
    }
  }
}
```

it's better to use something like patch-package to save edited modules

edit `myapp/android/settings.gradle `

```
//apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
apply from: new File(["node", "--print", "require.resolve('react-native-unimodules/package.json')"].execute(null, rootDir).text.trim(), "../gradle.groovy"); includeUnimodulesProjects()
apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```

edit `myapp/android/build.gradle`

```
buildscript {
    ...
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
	...
    }
}
allprojects {
    repositories {
	...
        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
	...
    }
}
```

change distributionUrl in `myapp/android/gradle/wrapper/gradle-wrapper.properties`

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
```

edit `myapp/android/app/build.gradle `

```
apply plugin: "com.android.application"
apply from: '../../node_modules/react-native-unimodules/gradle.groovy'

dependencies { 
    ...
    addUnimodulesDependencies()
    ...
}
```

change `myapp/android/app/src/main/java/com/myapp/MainApplication.java`

```
package com.myapp;
import com.myapp.generated.BasePackageList;
import com.rnfs.RNFSPackage;
import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.Arrays;
import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;



public class MainApplication extends Application implements ReactApplication {
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), null);

     ...

    @Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
            new ModuleRegistryAdapter(mModuleRegistryProvider)
          );
      packages.addAll(unimodules);
      return packages;
    }

      ...
```

something like that

**Comment by Th0mYT** [comment]
Oh! Nothing else? 😅😅😅😅😅
