### ISSUE TITLE
tfjs-node native saver/loader may not be fully functional on MS Windows

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#518]
#### TensorFlow.js version
0.12.2

A line such as `await model.save('file://./model')` gives error:

Cannot find any save handlers for URL 'file://model/'

**Comment by caisq** [comment]
Turns out that in the original thread that prompted the creation of this bug, the user was not importing tfjs-node. So we don't really have a reason to believe the file:// URL scheme is not working on MS Windows. Closing this bug.

**Comment by iiredalert** [comment]
Just ran into the same issue on linux.  I guess for some reason the tfjs-node module was not registering the file:// handler.  Got around it by using the NodeFileSystem class directly.

> await model.save(new NodeFileSystem("./modelName"));

**Comment by deanshub** [comment]
Hey @caisq @iiredalert ,
I'm having the same issue, running 
```@tensorflow/tfjs 0.13.1``` and ```@tensorflow/tfjs-node 0.1.17```
I'm getting the same error when running the mnist-node example...

though I am getting an error on initial binding
```Registration of backend tensorflow failed``` but I can't seem to figure the cause, any tips?

**Comment by caisq** [comment]
@deanshub Can you show 1) the package.json and 2) the import / require lines from your .js file?

**Comment by deanshub** [comment]
imports
```
import * as tf from '@tensorflow/tfjs'
import '@tensorflow/tfjs-node'
```
package.json
```
{
  "name": "stockRl",
  "version": "0.0.1",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "nodemon src/index.js",
    "test": "jest"
  },
  "dependencies": {
    "@tensorflow/tfjs": "^0.13.1",
    "@tensorflow/tfjs-node": "^0.1.17",
    "@tensorflow/tfjs-node-gpu": "^0.1.17",
    "config": "^1.30.0",
    "fs-extra": "^7.0.0",
    "moment": "^2.22.1",
    "yahoo-stocks": "^2.0.4"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "eslint": "^4.19.1",
    "nodemon": "^1.17.3"
  }
}
```
I also tried the [mnist-node](https://github.com/tensorflow/tfjs-examples/blob/master/mnist-node/main.js) example

**Comment by caisq** [comment]
Please remove this dependency from your package.json:

"@tensorflow/tfjs": "^0.13.1"

@tensorflow/tfjs-node version 0.1.17+  depends on @tensorflow/tfjs . If you manually specify a version of @tensorflfow/tfjs, you cause two separate versions of tfjs to be imported, which leads to the issue you are experiencing.

**Comment by deanshub** [comment]
Thanks @caisq that did it 🥇
