### ISSUE TITLE
converter drops model output keys

### ISSUE THREAD

**Issue by jimlloyd** [tensorflow/tfjs#5183]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux 1e50325cd6ff 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 GNU/Linux
This is a docker image using the attached Dockerfile

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A

- TensorFlow.js installed from (npm or script link):
pip -- see attached Dockerfile

- TensorFlow.js version (use command below):
3.7.0 -- see attached Dockerfile

- Browser version:
N/A

- Tensorflow.js Converter Version:
3.7.0

**Describe the current behavior**
I have a model with five outputs, built using the functional API of `tf.keras`.   The `saved_model_cli` signature looks like this:

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['main'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 52, 14)
        name: serving_default_main:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['carlMoon'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 52)
        name: StatefulPartitionedCall:0
    outputs['hearts'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 52)
        name: StatefulPartitionedCall:1
    ...
```

Note the keys `'carlMoon'` and `'hearts'` in the two outputs shown.

I ran the `tensorflowjs_converter` to convert this model using this command line (from within the Docker container built with the attached Dockerfile):

```
tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model --signature_name serving_default /data/e1431.4M.model /data/e1431.tfjs.model
```

The resulting `model.json` (pretty-printed with the attached `json-pretty.mjs` script which uses `util.inspect()` -- valid JSON would require quoted strings for the keys) produces this output for the model signature:

```
  signature: {
    inputs: {
      main: {
        name: 'main:0',
        dtype: 'DT_FLOAT',
        tensorShape: { dim: [ { size: '-1' }, { size: '52' }, { size: '14' } ] }
      }
    },
    outputs: {
      'Identity_4:0': {
        name: 'Identity_4:0',
        dtype: 'DT_FLOAT',
        tensorShape: { dim: [ { size: '-1' }, { size: '52' } ] }
      },
      'Identity_1:0': {
        name: 'Identity_1:0',
        dtype: 'DT_FLOAT',
        tensorShape: { dim: [ { size: '-1' }, { size: '52' } ] }
      },
     ....
```

Note that the output keys have become `Identity_4:0` and `Identity_1:0` instead of the original keys `carlMoon` and `hearts`.

**Describe the expected behavior**

The `model.json` signature outputs section should preserve the original keys and look like this:

```
    outputs: {
      carlMoon: {
        name: 'Identity_4:0',
        dtype: 'DT_FLOAT',
        tensorShape: { dim: [ { size: '-1' }, { size: '52' } ] }
      },
      hearts: {
        name: 'Identity_1:0',
        dtype: 'DT_FLOAT',
        tensorShape: { dim: [ { size: '-1' }, { size: '52' } ] }
      },
      ...
```

**Standalone code to reproduce the issue**
N/A

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The Dockerfile and the source model are attached in one tar ball.

[bugfiles.tar.gz](https://github.com/tensorflow/tfjs/files/6604862/bugfiles.tar.gz)

**Comment by pyu10055** [comment]
@jimlloyd Unfortunately, the outputs 'carlMoon' and 'heart' have the same output shape and dtype, the converter cannot differentiate them after inlining the original saved model functions.

As an work around, you can always edit the model.json file after the conversion.

**Comment by jimlloyd** [comment]
@pyu10055 It sounds like you are saying that there is a known problem where the converter drops these values upstream, but the converter works around that problem by trying to infer the information from the output shape and dtype. That may be sufficient for the use cases covered by unit tests now, but I bet that inference code is fairly complex and also unnecessary.

The values are available in the protobuf records in the `tf_saved_model` file format. In addition to this being shown by the `saved_model_cli` output above, I can confirm that I have working C++ code that correctly extracts the signature. In fact, I had this exact same bug in my first (C++) implementation that extracted this information from the `tensorflow::SavedModelBundleLite` bundle. 

It is true that I can work around this problem by editing the model.json file. But I still think there is a bug somewhere in the converter pipeline that should be fixed. The fix should even be easy (it was easy to fix in my C++ implementation), though perhaps there is some intermediate representation  that would have to change, and doing so in a backwards compatible way might not be easy.

**Comment by pyu10055** [comment]
@jimlloyd `tensorflowjs_converter` inlines the functions in the saved model, the mapping between the signature and the node in the graph cannot be retained after that. It would be great if you can share your experience or contribute with a fix. Thanks

**Comment by jimlloyd** [comment]
It may be that I should see if I can debug this, but let me ask one more question. I see that the internal tensor names are converted (in my model) from `StatefulPartitionedCall:0` to `Identity_4:0`. I don't have any problem with that. It should be pretty obvious that I didn't choose the name `StatefulPartitionedCall:0` in the first place. But any application that needs to be able to load different "flavors" (or versions) of a model needs to have some stable/public representation of the inputs and outputs. The input name `main` is preserved just fine by the existing converter -- it is only the outputs that have their stable/public names replaced with the internal/private names.

Perhaps it might be helpful to describe my use case as a concrete example. I have been working for several years now on a Reinforcement Learning implementation of the card game Hearts, inspired by DeepMinds' AlphaGo/Zero. Over time I have made various changes to the model architecture to obtain various improvements, but I have wanted to retain the ability to test new models against the old models. This is not that difficult because Tensorflow can load and execute predictions for an arbitrary model as long as the code driving those predictions can create valid input tensor(s) and interpret the resulting output tensor(s).

In my case, all of the different models I have developed have always had one input tensor and multiple output tensors. The shape of the input tensor can be changed, and when it does, I have to change the name ("main" in the attached example). The output tensors always have the same shape (a vector of 52 floats, one per card in a deck) but any given model might produce a different set of outputs compared to other models. So, each output must have a stable name. In this examples above, the `hearts` vector is a prediction of the expected number of hearts the player will have taken at the end of the round if the given card is played. The oddly named `carlMoon` vector is the prediction of the probability that the current player will "shoot the moon" (take all points) if the given card is played. 

So, all of this is to say that any of my applications that loads a model must be able to inspect the model and dynamically configure how to take a given game state, convert it into the correct input tensor, run the prediction, and then dynamically interpret the output tensors. My C++ code can do this just fine.

The workaround you propose (to edit the model.json file) is certainly workable, since I will have a relatively small number of models (on the order of 10, not 100) that I use (and someday include in releases).

I am a little surprised that no one else has encountered this bug yet, but I suppose multi-output models are still relatively uncommon,  and perhaps I am the first person trying to port such models to Tensorflow JS.

**Comment by pyu10055** [comment]
@jimlloyd models with multiple outputs can have a proper mapped signatures, as you have discovered, only when outputs have different data types or shapes.
TFJS relies on TensorFlow internal code to inline the StatefulPartitionedCall function, which will map nodes for the input/output of the function to different names.
