### ISSUE TITLE
Support loading a frozenModel from disk in Node.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#519]
Currently we can load a layers model from disk but not a frozen model.

https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/-n96cZqXFF8/9bryVgQyBwAJ

This should be quiet easy to implement, given that we've already solved it for layers.

This flow should work, even if we get the SavedModel approach working.

cc @nkreeger

**Comment by nsthorat** [comment]
@piyu10055 can you look into this error?

**Comment by pyu10055** [comment]
@Jylomaki can you share the model that produce this error? thanks.

**Comment by Jylomaki** [comment]
https://drive.google.com/open?id=1W-bxKijG5xhJ7fFkoTDGhZUdpXWIkpfj
It is a regressor based upon mobile_net_096.
Expected input should be of type: `([1,96,96,3],tf.float32)`

**Comment by icysapphire** [comment]
Same problem here.
Correctly converted model (with tfjs-converter) but no way to use it with tfjs.
