### ISSUE TITLE
[webgpu] Provide a fused path for webgpu

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#5198]
Unlike other backends, webgpu is using compute shader to implement each ops. The advantage of compute shader is that we can randomly access any locations in input buffers and write to any position of output buffer. So for webgpu, it's more easier to implement some fused ops, which can help improve the performance greatly.
The problem is how we to provide the fused ops for webgpu and which level it should be happen: Provide a fused model or a normal model and parse it to fused ops and then call to webgpu?

We would like to discuss the details to achieve the target.

**Comment by qjia7** [comment]
@pyu10055 @lina128 @jinjingforever Please share your ideas here and help/guide us to finish it. Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @qjia7 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now so May I know are you still looking for this feature in TFJs ?

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by qjia7** [comment]
Close this since it's kind of duplicated with #5458.
