### ISSUE TITLE
Invalid Array Length error on libtensorflow download

### ISSUE THREAD

**Issue by manishchauhan30** [tensorflow/tfjs#5200]
I am trying to install the @tensorflow/tfjs-node package. Earlier I was getting the Socket exception but resolved it by setting the TFJS_NODE_CDN_STORAGE = /path to npm project repo.
Tried with 2 versions of Node Js 14.16.0 and 10.15.3 but both raised the same error.
Now I am getting a different error Invalid Array Length on the libtensorflow download. Entire logs below with --verbose option.

Node Js version: 14.16.0
npm version: 6.14.11
Windows 10
Python version: 2.7.13

npm info it worked if it ends with ok
npm verb cli [
npm verb cli 'C:\nodejs\node.exe',
npm verb cli 'C:\nodejs\node_modules\npm\bin\npm-cli.js',
npm verb cli 'install',
npm verb cli '@tensorflow/tfjs-node',
npm verb cli '--verbose'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v14.16.0
npm verb npm-session c1c57b93def4a995
npm http fetch GET 304 https://registry.npmjs.org/@tensorflow%2ftfjs-node 154ms (from cache)
npm timing stage:loadCurrentTree Completed in 455ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 141ms
npm http fetch GET 304 https://registry.npmjs.org/adm-zip 137ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 151ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@mapbox%2fnode-pre-gyp 167ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-fetch 116ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nopt 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/debug 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 101ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/agent-base 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/es6-promisify 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/es6-promise 61ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 921ms
npm timing stage:loadIdealTree Completed in 1113ms
npm timing stage:generateActionsToTake Completed in 15ms
npm verb correctMkdir C:\Users\manish.chauhan\AppData\Roaming\npm-cache_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\manish.chauhan\AppData\Roaming\npm-cache_locks\staging-d5c52856532deef9.lock for D:\Avian\MongoDb_Removal\bird-check-node\node_modules.staging
npm timing audit submit Completed in 273ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 274ms
npm timing audit body Completed in 1ms
npm timing action:extract Completed in 387ms
npm timing action:finalize Completed in 67ms
npm timing action:refresh-package-json Completed in 364ms
npm info lifecycle rimraf@3.0.2preinstall: rimraf@3.0.2
npm info lifecycle chownr@2.0.0preinstall: chownr@2.0.0
npm info lifecycle agent-base@4.3.0preinstall: agent-base@4.3.0
npm info lifecycle mkdirp@1.0.4preinstall: mkdirp@1.0.4
npm info lifecycle ms@2.1.2preinstall: ms@2.1.2
npm info lifecycle debug@4.3.1preinstall: debug@4.3.1
npm info lifecycle https-proxy-agent@5.0.0preinstall: https-proxy-agent@5.0.0
npm info lifecycle debug@3.2.7preinstall: debug@3.2.7
npm info lifecycle node-fetch@2.6.1preinstall: node-fetch@2.6.1
npm info lifecycle nopt@5.0.0preinstall: nopt@5.0.0
npm info lifecycle semver@7.3.5preinstall: semver@7.3.5
npm info lifecycle yallist@4.0.0preinstall: yallist@4.0.0
npm info lifecycle minipass@3.1.3preinstall: minipass@3.1.3
npm info lifecycle fs-minipass@2.1.0preinstall: fs-minipass@2.1.0
npm info lifecycle minizlib@2.1.2preinstall: minizlib@2.1.2
npm info lifecycle tar@6.1.0preinstall: tar@6.1.0
npm info lifecycle @mapbox/node-pre-gyp@1.0.4preinstall: @mapbox/node-pre-gyp@1.0.4
npm info lifecycle https-proxy-agent@2.2.4preinstall: https-proxy-agent@2.2.4
npm info lifecycle @tensorflow/tfjs-node@3.7.0preinstall: @tensorflow/tfjs-node@3.7.0
npm timing action:preinstall Completed in 11ms
npm info linkStuff rimraf@3.0.2
npm verb linkBins [
npm verb linkBins { rimraf: 'bin.js' },
npm verb linkBins 'D:\Avian\MongoDb_Removal\bird-check-node\node_modules\@tensorflow\tfjs-node\node_modules\@mapbox\node-pre-gyp\node_modules\.bin',
npm verb linkBins false
npm verb linkBins ]
npm info linkStuff chownr@2.0.0
npm info linkStuff agent-base@4.3.0
npm info linkStuff mkdirp@1.0.4
npm verb linkBins [
npm verb linkBins { mkdirp: 'bin/cmd.js' },
npm verb linkBins 'D:\Avian\MongoDb_Removal\bird-check-node\node_modules\@tensorflow\tfjs-node\node_modules\.bin',
npm verb linkBins false
npm verb linkBins ]
npm info linkStuff ms@2.1.2
npm info linkStuff debug@4.3.1
npm info linkStuff https-proxy-agent@5.0.0
npm info linkStuff debug@3.2.7
npm info linkStuff node-fetch@2.6.1
npm info linkStuff nopt@5.0.0
npm verb linkBins [
npm verb linkBins { nopt: 'bin/nopt.js' },
npm verb linkBins 'D:\Avian\MongoDb_Removal\bird-check-node\node_modules\@tensorflow\tfjs-node\node_modules\.bin',
npm verb linkBins false
npm verb linkBins ]
npm info linkStuff semver@7.3.5
npm verb linkBins [
npm verb linkBins { semver: 'bin/semver.js' },
npm verb linkBins 'D:\Avian\MongoDb_Removal\bird-check-node\node_modules\@tensorflow\tfjs-node\node_modules\.bin',
npm verb linkBins false
npm verb linkBins ]
npm info linkStuff yallist@4.0.0
npm info linkStuff minipass@3.1.3
npm info linkStuff fs-minipass@2.1.0
npm info linkStuff minizlib@2.1.2
npm info linkStuff tar@6.1.0
npm info linkStuff @mapbox/node-pre-gyp@1.0.4
npm verb linkBins [
npm verb linkBins { 'node-pre-gyp': 'bin/node-pre-gyp' },
npm verb linkBins 'D:\Avian\MongoDb_Removal\bird-check-node\node_modules\@tensorflow\tfjs-node\node_modules\.bin',
npm verb linkBins false
npm verb linkBins ]
npm info linkStuff https-proxy-agent@2.2.4
npm info linkStuff @tensorflow/tfjs-node@3.7.0
npm timing action:build Completed in 49ms
npm info lifecycle rimraf@3.0.2install: rimraf@3.0.2
npm info lifecycle chownr@2.0.0install: chownr@2.0.0
npm info lifecycle agent-base@4.3.0install: agent-base@4.3.0
npm info lifecycle mkdirp@1.0.4install: mkdirp@1.0.4
npm info lifecycle ms@2.1.2install: ms@2.1.2
npm info lifecycle debug@4.3.1install: debug@4.3.1
npm info lifecycle https-proxy-agent@5.0.0install: https-proxy-agent@5.0.0
npm info lifecycle debug@3.2.7install: debug@3.2.7
npm info lifecycle node-fetch@2.6.1install: node-fetch@2.6.1
npm info lifecycle nopt@5.0.0install: nopt@5.0.0
npm info lifecycle semver@7.3.5install: semver@7.3.5
npm info lifecycle yallist@4.0.0install: yallist@4.0.0
npm info lifecycle minipass@3.1.3install: minipass@3.1.3
npm info lifecycle fs-minipass@2.1.0install: fs-minipass@2.1.0
npm info lifecycle minizlib@2.1.2install: minizlib@2.1.2
npm info lifecycle tar@6.1.0install: tar@6.1.0
npm info lifecycle @mapbox/node-pre-gyp@1.0.4install: @mapbox/node-pre-gyp@1.0.4
npm info lifecycle https-proxy-agent@2.2.4install: https-proxy-agent@2.2.4
npm info lifecycle @tensorflow/tfjs-node@3.7.0install: @tensorflow/tfjs-node@3.7.0

@tensorflow/tfjs-node@3.7.0 install D:\Avian\MongoDb_Removal\bird-check-node\node_modules@tensorflow\tfjs-node
node scripts/install.js

CPU-windows-3.7.0.zip

Downloading libtensorflow
D:\Avian\MongoDb_Removal\bird-check-node\node_modules\progress\lib\node-progress.js:160
complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
^
RangeError: Invalid array length
at ProgressBar.render (D:\Avian\MongoDb_Removal\bird-check-node\node_modules\progress\lib\node-progress.js:160:14)
at ProgressBar.tick (D:\Avian\MongoDb_Removal\bird-check-node\node_modules\progress\lib\node-progress.js:97:8)
at IncomingMessage. (D:\Avian\MongoDb_Removal\bird-check-node\node_modules@tensorflow\tfjs-node\scripts\resources.js:66:40)
at IncomingMessage.emit (events.js:327:22)
at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
at flow (internal/streams/readable.js:992:34)
at resume_ (internal/streams/readable.js:973:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm verb lifecycle @tensorflow/tfjs-node@3.7.0install: unsafe-perm in lifecycle true
npm verb lifecycle @tensorflow/tfjs-node@3.7.0install: PATH: C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Avian\MongoDb_Removal\bird-check-node\node_modules@tensorflow\tf
js-node\node_modules.bin;D:\Avian\MongoDb_Removal\bird-check-node\node_modules.bin;C:\oracle\BIN;C:\Oracle\product\12.1.0\client_1\bin;C:\Users\manish.chauhan\Downloads\instantclient\instantclien
t_18_5;C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-openj9\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Wi
ndowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;D:\Softwares\python;C:\Users\manish.chauhan\AppData\Roaming\nvm;C:\Program File
s\nodejs;C:\nodejs;C:\oracle\product\12.1.0\client_1\BIN;C:\Users\manish.chauhan\AppData\Local\Microsoft\WindowsApps;C:\Users\manish.chauhan\AppData\Local\Programs\Git\cmd;D:\Softwares\apache-mave
n-3.2.1-bin\apache-maven-3.2.1\bin;C:\Users\manish.chauhan\Downloads\instantclient\instantclient_18_5;C:\Program Files\TortoiseSVN\bin;D:\Softwares\python;C:\Users\manish.chauhan\AppData\Roaming\n
vm;C:\Program Files\nodejs;C:\Users\manish.chauhan\AppData\Roaming\npm
npm verb lifecycle @tensorflow/tfjs-node@3.7.0install: CWD: D:\Avian\MongoDb_Removal\bird-check-node\node_modules@tensorflow\tfjs-node
npm info lifecycle @tensorflow/tfjs-node@3.7.0install: Failed to exec install script
npm timing action:install Completed in 512ms
npm verb unlock done using C:\Users\manish.chauhan\AppData\Roaming\npm-cache_locks\staging-d5c52856532deef9.lock for D:\Avian\MongoDb_Removal\bird-check-node\node_modules.staging
npm timing stage:rollbackFailedOptional Completed in 248ms
npm timing stage:runTopLevelLifecycles Completed in 3286ms
npm verb stack Error: @tensorflow/tfjs-node@3.7.0 install: node scripts/install.js
npm verb stack Exit status 1
npm verb stack at EventEmitter. (C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack at EventEmitter.emit (events.js:315:20)
npm verb stack at ChildProcess. (C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack at ChildProcess.emit (events.js:315:20)
npm verb stack at maybeClose (internal/child_process.js:1048:16)
npm verb stack at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid @tensorflow/tfjs-node@3.7.0
npm verb cwd D:\Avian\MongoDb_Removal\bird-check-node
npm verb Windows_NT 10.0.18363
npm verb argv "C:\nodejs\node.exe" "C:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "@tensorflow/tfjs-node" "--verbose"
npm verb node v14.16.0
npm verb npm v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@3.7.0 install: node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@3.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

**Comment by rthadur** [comment]
did you check this troubleshooting steps https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md also please specify the steps you are following to install.

**Comment by manishchauhan30** [comment]
Yes, I followed this troubleshooting document but no help. 
Steps I followed for installation:
1. Installed Node Js 14.16.0
2. Installed the windows-build-tools with version 4.0.0 through powershell with admin with command **npm install -g --production windows-build-tools@4.0.0** . I was not able to install the latest version of windows-build-tools for some reason. It gets stuck after some time when I try to install the latest version. So I had to install the 4.0.0 version.
3. Python 2.7.13 was already installed and the PATH env variable is also updated to point to Python.
4. Then installed the @tensorflow/tfjs without any issue using command npm install @tensorflow/tfjs.
5. Tried installing the @tensorflow/tfjs-node using command npm install @tensorflow/tfjs-node but got error during the download of libtensorflow. Error mentioned in the error log above.
6. Note: I am installing this on my Client PC which does not allow binary downloads from outside on the web. So I have set the TFJS_NODE_CDN_STORAGE to the path of my project's npm artifactory.
7. Sometimes, I do not see any error in the npm command logs when I try to install the tfjs-node. But then I see that the deps and lib folders are empty. These folders should contain the libtensorflow and tfjs_binding.node files.

**Comment by rthadur** [comment]
Thank you for the details , you do not need to install tfjs separately , when you install tfjs-node all the dependencies will be installed, please try again installing tfjs-node.

**Comment by manishchauhan30** [comment]
I have tried installing tfjs-node only but got the same error. It's the problem with the download of libtensorflow which is present in the deps folder.
Once previously, I was able to install the tfjs-node without any error but I found out that the **libs** folder was missing and **deps** folder was empty. So when I tried to run my classification program using **node <file_name.js>** , it complained of missing **tfjs_binding.node** file which should be present in the **libs** folder. I then also tried to rebuild the addon from source but it could not install the required files.

Should not the repo below contains the deps and libs folder?
https://github.com/tensorflow/tfjs-node/tree/master/tfjs-node

**Comment by rthadur** [comment]
The above repo is archived , please use this https://github.com/tensorflow/tfjs/tree/master/tfjs-node#installing-cpu-tensorflowjs-for-node for installing tfjs-node

**Comment by manishchauhan30** [comment]
@rthadur , As I mentioned before, the problem I have is in the download of custom binaries libtensorflow. I am not using the default URI [https://storage.googleapis.com/] to download libtensorflow but using a mirror to download it. I have also set the TFJS_NODE_CDN_STORAGE to the mirror url. But still not able to download it.

**Is there any way to manually download libtensorflow?**

**Comment by pyu10055** [comment]
@manishchauhan30 I think setting the TFJS_NODE_CDN_STORAGE is the right move, but can you verify if the url generated does match to the file that you serving?
This [line](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/scripts/install.js#L136) should have printed the URL, but it is not shown in your log.

**Comment by manishchauhan30** [comment]
@pyu10055 , yes the url points to the correct npm repo of the project. I cannot share the logs which mentions the project's npm repository for security reason. But I can confirm that the repository selected before doing the npm install was our project's npm repository.
I set the registry using **npm config set registry <url_of_project_repo>**
