### ISSUE TITLE
tfjs-converter: convert js models to keras

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#5201]
**System information**
- TensorFlow.js version (you are using): 3.7.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I have models that were previously converted from keras h5 for tfjs.
Now, I want to use these models in python.
I want the tfjs-converter to be able to support a reverse conversion as well, or at least, given that I have the model architecture in keras, to load the weights from the js model.

**Will this change the current api? How?**
Command line will support 
```
$ tensorflowjs_converter --input_format=tfjs /tmp/tfjs_model  /tmp/model.h5
```

**Who will benefit with this feature?**
Anyone who wants to convert a js model to run using python

**Any Other info.**

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by pyu10055** [comment]
yes, you can convert tfjs-layers model to keras as specified [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#javascript-to-python)

```--input_format= tfjs_layers_model --output_format=keras```

**Comment by AmitMY** [comment]
Thanks, didn't find this doc before!
