### ISSUE TITLE
WebcamIterator Fails w/ Virtual Camera

### ISSUE THREAD

**Issue by nskaiser** [tensorflow/tfjs#5207]
On a PC only, if you initialize the webcam but have a Virtual Camera (e.g. XSplitter, OBS, etc) it will not load. For example, if you load the webcam with this:

  initWebcam = async (webcamElement) => {
    const { selectedDeviceId } = this.props.webcam;
    const webcamConfig = selectedDeviceId.length > 0 ? { deviceId: selectedDeviceId } : { facingMode: 'user' };
    this.tfWebcam = await tfjs.data.webcam(webcamElement, webcamConfig);
    this.props.dispatch(setWebcamInitialized(true));
  }

Follow these steps to reproduce:

1) Make sure you are on a PC.  Close Chrome.
2) Start a Virtual Camera, such as OBS or XSplitter and get the camera going.
3) Start one of the Tensorflow webcam demos here.  The default camera won't work because it's in use from your Virtual Camera (that is fine).  Now switch access to use your Virtual Camera. 

It will crash with  the following:

Uncaught (in promise) TypeError: Cannot set property message of  which has only a getter
    at WebcamIterator._callee$ (webcam_iterator.js:134)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.throw (runtime.js:118)
    at asyncGeneratorStep (webcam_iterator.js:5)
    at _throw (webcam_iterator.js:7)

**Comment by rthadur** [comment]
cc @jasonmayes

**Comment by jasonmayes** [comment]
Hello there. I have not tried XSplitter but I use OBS regularly in  my demos to test models out with a pre-recorded video using the virtual cam built into OBS which works fine for me and I am also on Windows. So long as Chrome can see the virtual camera and your demo support selecting the virtual cam if it is not already the default cam Chrome picks up, and the resolution / FPS are standard eg 640x480, 1080P  720p etc it should work fine (I have tested all 3 of those resolutions at 30 FPS.

Could you try my demo here which I have successfully used and let me know if you still get the issue:

https://tensorflow-js-object-detection.glitch.me/

At the bottom is an enable cam  button - just click that and ensure OBS Virtual Cam is set to default camera in chrome settings.

**Comment by nskaiser** [comment]
Many thanks, Jason.  You are right, your demo worked fine. So I guess it's something with our application.  Interestingly, a lot of the google ones do not work either. Likely it's the same issue because that is where they copied code from?

For example, if you try https://lipsync.withyoutube.com or https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html

If you start  OBS first, then start Chrome, it will fail.  If you start Chrome first, then OBS, it works.

Do you see any issues in that code?

**Comment by jasonmayes** [comment]
What version of TensorFlow are you importing? Do you have a  live CodePen  / Glitch or such I can try and edit etc to see what is causing it?

**Comment by jasonmayes** [comment]
Oh sorry just realised you linked to your HTML page too. Will have a go.

**Comment by jasonmayes** [comment]
I can not seem to replicate this issue on my end. I will try on my desktop when I get back in a couple of weeks to see if I can replicate on that one.

**Comment by jasonmayes** [comment]
Just a bump to keep this open for now until I get back to my other PC to try and replicate

**Comment by jasonmayes** [comment]
I can not replicate this on Windows 10 Pro with latest OBS virtual camera installed. Everything works fine for me.
