### ISSUE TITLE
How to make posenet.estimateSinglePose() load faster?

### ISSUE THREAD

**Issue by shahanija** [tensorflow/tfjs#5213]
I am using tensorflow model called 'posenset' to detect the poses from frames detected by the tensorflow camera component in bare react-native platform. I am loading the model in componentDidMount() and calls estimateSinglePose() when each frame is detected by the component. But it takes too long to get the response from the posenet model. What should I do to make it to return the keypoints faster?

Reference:
[https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx)

Environment:
` "@tensorflow-models/posenet": "^2.2.2",
    "@tensorflow/tfjs": "^3.7.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "assets": "./src/assets",
    "date-fns": "^1.30.1",
    "expo-camera": "^11.0.3",
    "expo-gl": "^8.4.0",
    "expo-gl-cpp": "^8.4.0",
    "react": "16.11.0",
    "react-native": "0.63.0",
    "react-native-unimodules": "^0.11.0",`

Below is my code:

import React, {
  Component
} from 'react';
import PropTypes from 'prop-types';
import {
  connect
} from 'react-redux';
import * as types from '../../constants/actionTypes';

import Svg, {
  Circle,
  Rect,
  G,
  Line
} from 'react-native-svg';
import {
  ActivityIndicator,
  Button,
  Text as TEXT,
  StyleSheet,
  View,
  Platform,
  Dimensions,
  BackHandler
} from 'react-native';
import {
  GLView
} from 'expo-gl';
import {
  Camera
} from 'expo-camera';
import * as Permissions from 'expo-permissions';

import * as tf from '@tensorflow/tfjs';
import * as posenet from '@tensorflow-models/posenet';
import {
  cameraWithTensors
} from '@tensorflow/tfjs-react-native';

import SoundPlayer from 'react-native-sound-player'

const TensorCamera = cameraWithTensors(Camera);
const {
  width,
  height
} = Dimensions.get("window")

const inputTensorWidth = 640;
const inputTensorHeight = 480;

const AUTORENDER = true;

export default class index extends Component {

  static navigationOptions = () => ({
    headerTintColor: '#fff',
    headerTransparent: true,
  });

   

  constructor(props) {
    super(props);
    this.state = {
      isLoading: true,
      cameraType: Camera.Constants.Type.back,
      modelName: 'posenet',
      ejecting: false,
      rect: [{
          "score": 0.9903333783149719,
          "part": "leftShoulder",
          "position": {
            "x": 121.84140179266079,
            "y": 147.07495482485194
          }
        },
        {
          "score": 0.9952194690704346,
          "part": "rightShoulder",
          "position": {
            "x": 148.75751061657158,
            "y": 148.12498782341024
          }
        },
        {
          "score": 0.9976027607917786,
          "part": "leftHip",
          "position": {
            "x": 126.69576329907936,
            "y": 196.11758567448567
          }
        },
        {
          "score": 0.9986424446105957,
          "part": "rightHip",
          "position": {
            "x": 145.25335060214599,
            "y": 195.3146917861596
          }
        }
      ],
      wrist: null
    };
    this.handleImageTensorReady = this.handleImageTensorReady.bind(this);
  }

  loadPosenetModel = async() => {
    const model = await posenet.load({
      architecture: 'MobileNetV1',
      outputStride: 16,
      inputResolution: {
        width: inputTensorWidth,
        height: inputTensorHeight
      },
      multiplier: 0.50,
      quantBytes: 2
    });
    this.setState({
      isModalReady: true
    })

    return model;
  }

  loadBlazefaceModel = async() => {
    const model = await blazeface.load();
    return model;
  }

  handleImageTensorReady = async(images, updatePreview, gl) => {
    const loop = async() => {
      // const { modelName } = this.state;
      if (!AUTORENDER) {
        updatePreview();
      }

      // // if (modelName == 'posenet') {
      if (this.state.posenetModel != null) {
        const imageTensor = images.next().value;
        // alert(imageTensor)
        const flipHorizontal = Platform.OS === 'ios' ? false : true;

        const pose = await this.state.posenetModel.estimateSinglePose(
            imageTensor, {
              flipHorizontal
            })
          .then((value) => {
            console.log("pose" + JSON.stringify(value))
            this.setState({
              pose: value
            });
            tf.dispose(imageTensor);
          })

      }
      // // } else {
      // //   if (this.state.faceDetector != null) {
      // //     const imageTensor = images.next().value;
      // //     const returnTensors = false;
      // //     const faces = await this.state.faceDetector.estimateFaces(
      // //       imageTensor, returnTensors);

      // //     this.setState({ faces });
      // //     tf.dispose(imageTensor);
      // //   }
      // // }

      // if (!AUTORENDER) {
      //   gl.endFrameEXP();
      // }
      this.rafID = requestAnimationFrame(loop);
    };

    loop();
  }

  async componentWillUnmount() {

    console.log("WILLUNMOUNT")

    this.setState({
      rect: []
    })
    await this.ejectEverything()
  }
  ejectEverything = async() => {

    console.log("EJECT")

    this.setState({
      ejecting: true
    }, async() => {
      // if (this.rafID) {
      //   await cancelAnimationFrame(this.rafID);
      // }
      this.setState({
        ejecting: false
      }, () => {
        this.backHandler.remove();

        this.props.navigation.goBack();

      })
    })

    return true
  }

  async componentDidMount() {

    this.backHandler = BackHandler.addEventListener(
      "hardwareBackPress",
      this.ejectEverything
    );

    const {
      status
    } = await Permissions.askAsync(Permissions.CAMERA);

    await tf.setBackend('cpu')

    await tf.ready()
    this.setState({
      isTfReady: true
    })
    this.setState({
      isModalReady: false
    })
    const [posenetModel] =
    await Promise.all([
      // this.loadBlazefaceModel(), 
      this.loadPosenetModel()
    ]);

    this.setState({
      isLoading: false,
      // faceDetector: blazefaceModel,
      posenetModel,
    });

  }

  renderPose = () => {

    const MIN_KEYPOINT_SCORE = 0.2;
    const {
      pose
    } = this.state

    if (pose != null) {
      const keypoints = pose.keypoints
        .filter(k => k.score > MIN_KEYPOINT_SCORE)
        .map((k, i) => {
          return <Circle
          key = {
            `skeletonkp_${i}`
          }
          cx = {
            k.position.x
          }
          cy = {
            k.position.y
          }
          r = '2'
          strokeWidth = '0'
          fill = 'blue' /
            >
          ;
        });

      const adjacentKeypoints =
        posenet.getAdjacentKeyPoints(pose.keypoints, MIN_KEYPOINT_SCORE);

      const skeleton = adjacentKeypoints.map(([from, to], i) => {
        return <Line
        key = {
          `skeletonls_${i}`
        }
        x1 = {
          from.position.x
        }
        y1 = {
          from.position.y
        }
        x2 = {
          to.position.x
        }
        y2 = {
          to.position.y
        }
        stroke = 'magenta'
        strokeWidth = '1' /
          >
        ;
      });

      return <Svg height = '100%'
      width = '100%'
      viewBox = {
          `0 0 ${inputTensorWidth} ${inputTensorHeight}`
        } > {
          skeleton
        } {
          keypoints
        } <
        /Svg>;
    } else {
      return null;
    }
  }

  // renderFaces = () => {
  //   const { faces } = this.state;
  //   if (faces != null) {
  //     const faceBoxes = faces.map((f, fIndex) => {
  //       const topLeft = f.topLeft;
  //       const bottomRight = f.bottomRight;

  //       const landmarks = (f.landmarks).map((l, lIndex) => {
  //         return <Circle
  //           key={`landmark_${fIndex}_${lIndex}`}
  //           cx={l[0]}
  //           cy={l[1]}
  //           r='2'
  //           strokeWidth='0'
  //           fill='blue'
  //         />;
  //       });

  //       return <G key={`facebox_${fIndex}`}>
  //         <Rect
  //           x={topLeft[0]}
  //           y={topLeft[1]}
  //           fill={'red'}
  //           fillOpacity={0.2}
  //           width={(bottomRight[0] - topLeft[0])}
  //           height={(bottomRight[1] - topLeft[1])}
  //         />
  //         {landmarks}
  //       </G>;
  //     });

  //     const flipHorizontal = Platform.OS === 'ios' ? 1 : -1;
  //     return <Svg height='100%' width='100%'
  //       viewBox={`0 0 ${inputTensorWidth} ${inputTensorHeight}`}
  //       scaleX={flipHorizontal}>
  //       {faceBoxes}
  //     </Svg>;
  //   } else {
  //     return null;
  //   }
  // }

  render() {

    const {
      isLoading,
      modelName,
      ejecting
    } = this.state;

    // TODO File issue to be able get this from expo.
    // Caller will still need to account for orientation/phone rotation changes
    let textureDims = {
      width: 0,
      height: 0
    };
    if (Platform.OS === 'ios') {
      textureDims = {
        height: 1920,
        width: 1080,
      };
    } else {
      textureDims = {
        height: 1200,
        width: 1600,
      };
    }

    const camView = !!this.state.isTfReady && !!this.state.isModalReady && < View style = {
        styles.cameraContainer
      } >

      <
      TensorCamera
    // Standard Camera props
    style = {
      styles.camera
    }
    type = {
      this.state.cameraType
    }
    zoom = {
      0
    }
    // tensor related props
    cameraTextureHeight = {
      textureDims.height
    }
    cameraTextureWidth = {
      textureDims.width
    }
    resizeHeight = {
      inputTensorHeight
    }
    resizeWidth = {
      inputTensorWidth
    }
    resizeDepth = {
      3
    }
    onReady = {
      this.handleImageTensorReady
    }
    autorender = {
      true
    }
    /> <
    View style = {
        styles.modelResults
      } > { /* {modelName === 'posenet' ? */ } {
        !!this.state.pose && this.renderPose()
      } { /* : this.renderFaces()} */ } <
      /View> < /
      View > ;

    return ( <
      View style = {
        {
          width: '100%',
          flex: 1
        }
      } >

      {!this.state.isTfReady || !this.state.isModalReady ?
        <
        View style = {
          {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: "white"
          }
        } >
        <
        ActivityIndicator size = 'large'
        color = '#FF0266' / >
        <
        /View> :
        camView
      } {
        !!ejecting && < View style = {
            {
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: "white"
            }
          } >
          <
          ActivityIndicator size = 'large'
        color = '#FF0266' / >

          <
          /View>
      } <
      /View>
    );
  }
}

const styles = StyleSheet.create({
  loadingIndicator: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 200,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  cameraContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
  },
  camera: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 0,
  },
  modelResults: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    zIndex: 20,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 0,
  }
});

Thanks in advance

**Comment by rthadur** [comment]
Hi @shahanija , could you please use the latest example https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection and let us know if this helps ?
