### ISSUE TITLE
Issue with blazepose_tfjs\detector  same Image Tensor works  fine with MoveNet and Posenet  in ReactNative 

### ISSUE THREAD

**Issue by AkshayMethe** [tensorflow/tfjs#5214]
[Unhandled promise rejection: TypeError: undefined is not a function (near '...tf.image.transform...')]
at node_modules\@tensorflow-models\pose-detection\dist\calculators\convert_image_to_tensor.js:18:0 in <global>
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3347:23 in scopedRun$argument_2
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3357:23 in Engine.prototype.scopedRun        
at node_modules\@tensorflow-models\pose-detection\dist\calculators\convert_image_to_tensor.js:15:0 in <global>
at node_modules\@tensorflow-models\pose-detection\dist\blazepose_tfjs\detector.js:194:56 in BlazePoseTfjsDetector.prototype.reset
at node_modules\@tensorflow-models\pose-detection\dist\blazepose_tfjs\detector.js:44:30 in step
at http://127.0.0.1:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:245651:72 in <unknown>
at node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
at node_modules\@tensorflow-models\pose-detection\dist\blazepose_tfjs\detector.js:5:0 in <global>       
at http://127.0.0.1:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:245876:40 in <unknown>
at node_modules\@tensorflow-models\pose-detection\dist\blazepose_tfjs\detector.js:44:30 in step
at http://127.0.0.1:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:245651:72 in <unknown>
at node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
at node_modules\@tensorflow-models\pose-detection\dist\blazepose_tfjs\detector.js:5:0 in <global>       
at src\ModelView.js:132:28 in loop
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:293:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:154:27 in invoke
at node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
at node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
at node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
at node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
at src\ModelView.js:127:19 in loop
at src\ModelView.js:144:10 in React.useCallback$argument_0
at node_modules\@tensorflow\tfjs-react-native\dist\camera\camera_stream.js:193:34 in CameraWithTensorStream#onGLContextCreate
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:293:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:154:27 in invoke
at node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by lina128** [comment]
Hi @AkshayMethe, tf.image.transform op is added recently. We will update tfjs-react-native's tfjs dependency version.

**Comment by AkshayMethe** [comment]
Hi @lina128, any update on the tfjs-react-native dependency version update.

**Comment by lina128** [comment]
Hi @mattsoulanille, please update the issue when tfjs-react-native is updated.

**Comment by lina128** [comment]
@AkshayMethe new tfjs-react-native is released, please check.
