### ISSUE TITLE
`tf.keras.backend.rnn` would raise errors when using some layers in `step_function`

### ISSUE THREAD

**Issue by gdhy9064** [tensorflow/tfjs#5215]
**System information**
- TensorFlow.js installed from (npm or script link): <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.7.0/dist/tf.min.js"></script>
- TensorFlow.js version (use command below): 3.7.0
- Tensorflow.js Converter Version: 3.7.0

**Describe the current behavior**
I'd like to use `tf.keras.backend.rnn` to build a model that can recurrently generate samples. When I use some `tf.keras.layers.Layer` in `step_function`, which is one of parameters of  `tf.keras.backend.rnn`, the model will raise errors in tensorflow.js, but can successfully run in python. 
I have simplified the source to build the model, my actual source uses more `tf.keras.layers.Layer` in `step`. The python code is as below:
```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Layer, Embedding
from tensorflow.keras import Model
import tensorflow.keras.backend as K

class TestLayer(Layer):
    def __init__(self):
        super().__init__()
        self.embedding = Embedding(input_dim=3, output_dim=3)
        
    def step(self, _, params):
        idx = params[0]
        y = self.embedding(idx)
        next_idx = tf.random.categorical(y, 1)[:, 0]
        return next_idx, [next_idx]
    
    def call(self, max_len):
        initial_idx = K.tile(K.constant([0], dtype='int64'), [K.shape(max_len)[0]])
        unused = K.tile(K.constant([[[0]]]), [K.shape(max_len)[0], K.shape(max_len)[1], 1])
        _, sample, _ = K.rnn(self.step, unused, [initial_idx], input_length=K.shape(max_len)[1])
        return sample
    

max_len = Input([None])

test_layer = TestLayer()
sample = test_layer(max_len)
model = Model(inputs=max_len, outputs=sample)
print(model.predict(np.zeros([4, 5])))
model.save('test')
```
And my conversion command is as follow:
```
tensorflowjs_converter --input_format=tf_saved_model test <somewhere>/test
```
The javascript/html code is as below:
```
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.7.0/dist/tf.min.js"></script>

</head>
<script>
    tf.loadGraphModel('http://127.0.0.1:5000/test/model.json').then(
        (model) => {
            model.executeAsync(tf.zeros([4, 5]), ['Identity']).then(x=>x.print());
        }
    );
</script>
</html>
```
I use Flask to run a server to provide the files needed. The loaded model will raise errors like:
`Uncaught (in promise) Error: Cannot compute the outputs [Identity] from the provided inputs [input_3:0]. Consider providing the following inputs: []. Alternatively, to avoid the dynamic ops, use model.execute() and specify the inputs [Identity]`

**Describe the expected behavior**
I wonder if there exist some ways to build this model in python and convert it to tensorflow.js without transplanting the source to javascript.

**Standalone code to reproduce the issue**
The attachment is the related source. The `flask_run.py` should run before opening `test.html`.
[test.zip](https://github.com/tensorflow/tfjs/files/6642492/test.zip)

**Other info / logs** 
I ensure that the `output_node_name` 'Identity' is the final output node of model. And I have tried to use `tf.keras.backend.rnn` without any `tf.keras.layers.Layer` in `step`, the model can successfully return results.

**Comment by gaikwadrahul8** [comment]
Hi, @gdhy9064 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
