### ISSUE TITLE
Safari 15 / iOS 15 Vertex/Shader Errors

### ISSUE THREAD

**Issue by heystoney** [tensorflow/tfjs#5216]
DESCRIPTION
I'm getting a consistent vertex/fragment error across the official TFJS demos using Safari 15 on the new developer release of iOS 15.0. It would seem changes have been introduced into Webkit that are causing this, so hopefully shouldn't require any changes by the tensorflow team, but I did want to raise it here.

ERROR LOG:
Internal error compiling shader with Metal backend.
Please submit this shader, or website as a bug to https://bugs.webkit.org
Error: Failed to link vertex and fragment shaders.

STEPS TO REPRODUCE:
The error can be seen running these demos on Safari 15:
[https://emojiscavengerhunt.withgoogle.com/](https://emojiscavengerhunt.withgoogle.com/)
[https://magenta.tensorflow.org/demos/performance_rnn/index.html](https://magenta.tensorflow.org/demos/performance_rnn/index.html)
[https://storage.googleapis.com/tfjs-examples/addition-rnn/dist/index.html](https://storage.googleapis.com/tfjs-examples/addition-rnn/dist/index.html)

HARDWARE:
I am using an iPhone XS running iOS 15. 
I tested these on a iPhone X running 14.6 and had no errors.

REPORTING:
I filed a bug report with WebKit too, but this may be something a team member may be better positioned to follow up on as it seems to be breaking pretty consistently across my own code and the official TFJS demos:
[https://bugs.webkit.org/show_bug.cgi?id=226953](https://bugs.webkit.org/show_bug.cgi?id=226953)

**Comment by pyu10055** [comment]
@heystoney can you paste the details of this failure? We usually show the shader source code and where the compilation fails.
You might need to use safari remote debug to get the error message. thanks.

**Comment by heystoney** [comment]
For sure. So using [this one](https://storage.googleapis.com/tfjs-examples/addition-rnn/dist/index.html) as example (but the error is the same in each) in Safari 15:

Before erroring it will log:
**Internal error compiling shader with Metal backend. (webgl_util.ts:154)
Please submit this shader, or website as a bug to https://bugs.webkit.org**

The console error that follows is:
**Unhandled Promise Rejection: Error: Failed to link vertex and fragment shaders.**

The error always occurs when tfjs is running its training (or segmentation for bodypix). In this case, the line that triggers the error is:
`await demo.train(trainIterations, batchSize, numTestExamples);`

That's all I get in my logs, so I'm not sure if there is an additional debug mode these could be run in with more information, but hopefully that helps. 

I had also attempted to run this page as well:
https://js.tensorflow.org/debug/
It didn't output any tf.ENV information or navigator.userAgent or run any tf.scalar calculations. No logs either.

**Comment by heystoney** [comment]
Just a small update -- I ran the tests again in the new iOS15 Beta 2 and this error still exists across the official TFJS examples.

A [patch](https://bugs.webkit.org/show_bug.cgi?id=226953) had been created by the Webkit team, but I'm not sure if it was included in the new iOS release. This may need to be followed up on by someone closer to the Webkit team so TFJS can continue working when iOS15 is released.

**Comment by heystoney** [comment]
One more quick update -- heard back from a member of the Webkit team that their patch for this issue did not make it into iOS15 Beta 2, but they are hopeful it will be in the next one. I'll test when Beta 3 is released and update/close the ticket if it's fixed.

**Comment by heystoney** [comment]
This has been fixed in iOS 15 beta 3. Closing it out.
