### ISSUE TITLE
Support for `ReverseSequence` in `tensorflowjs_converter`

### ISSUE THREAD

**Issue by chrisdonahue** [tensorflow/tfjs#522]
The [`tf.nn.bidirectional_dynamic_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn) API uses the [`ReverseSequence`](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/reverse-sequence) operation to reverse variable-length batches of sequences. Can `tensorflowjs_converter` please support this operation?

Cheers!

**Comment by siclait** [comment]
Hi @pyu10055 - is there any update on this / is it being worked on? I have the same use case as above (converting a graph built using `tf.nn.bidirectional_dynamic_rnn`). I'm also up for attempting the change if you haven't started yet.

**Comment by siclait** [comment]
Thanks @pyu10055 - I opted for sticking to the Python API for my use case so I no longer need to implement this op.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
