### ISSUE TITLE
how to assign values to a portion of a large tensor

### ISSUE THREAD

**Issue by JoeyChuuichi** [tensorflow/tfjs#5224]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**Describe the feature and the current behavior/state.**
suppose that we have a 3*3 tensor
```
Tensor
    [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]
```
Is there any way we can change it into 
```
Tensor
    [[1, 1, 0],
     [1, 1, 0],
     [0, 0, 0]]
```
?

The application may be editing some masks of an image

**Comment by pyu10055** [comment]
@JoeyChuuichi If you want to manipulate values of the tensor, you can download them to CPU by using the data() or dataSync() method.
Manipulate the data as you need, and create a new tensor.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
