### ISSUE TITLE
Fail to load converted model in node.js

### ISSUE THREAD

**Issue by leolellisr** [tensorflow/tfjs#5234]
Hi guys! I'm new to TensoFlowjs and I'm struggling to find a solution to this error. I'm trying to train a Blazeface model in Python and convert it to use in node.js.

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow.js installed from npm
- TensorFlow.js version 3.6.0
- Tensorflow.js Converter Version: tensorflowjs 3.7.0; 
- Dependency versions: keras 2.4.0; tensorflow 2.3.1
- Node version: 15.14.0
- NPM version: 7.7.6

**Describe the problem**

I trained a BlazeFace model from code provided by https://github.com/FurkanOM/tf-blazeface and adapted it to get 68 landmarks https://github.com/FurkanOM/tf-blazeface/issues/2.
I saved the trained model with TF 2.3.1 `model.save('modelSaved.h5')`

I converted `modelSaved.h5` with `tensorflowjs_converter --input_format keras --weight_shard_size_bytes 60000000 modelSaved.h5 converted_models/blazeface`.

The first time I tried to load the model in Js, I got the error:

```
import * as tf from '@tensorflow/tfjs'
await tf.setBackend('webgl')
const modelJson = 'https://***/models/blazeface1/model.json';
const modelLoaded = await tf.loadLayersModel(modelJson);
```

**Error: Unknown layer: HeadWrapper. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().**

After some research I build a HeadWrapper class in JavaScript. The original HeadWrapper is here: https://github.com/FurkanOM/tf-blazeface/blob/master/blazeface.py

**custom_layer.js**
 ```
import * as tf from '@tensorflow/tfjs';
 class HeadWrapper extends tf.layers.Layer {
   constructor() {
     super({});
     this.supportsMasking = true;
   }
 computeOutputShape(inputShape) {
     return [inputShape[0], inputShape[1], inputShape[2], 2 * inputShape[3]]
   }
  call(inputs, kwargs) {
     let input = inputs;
     if (Array.isArray(input)) {
       batch_size = input[0].shape[0];
       input = input[0];
     }
     this.invokeCallHook(inputs, kwargs);
     const origShape = input.shape;
     // need something to do here
     outputs= origShape;
     return tf.concat(outputs, 1);
   }
```
 
Then loading again the model in js:
```
import * as tf from '@tensorflow/tfjs'
import {headwrapper} from '../custom-layer/custom_layer';

await tf.setBackend('webgl')
const layer = headwrapper();
const modelJson = 'https://***/models/blazeface1/model.json';
const modelLoaded = await tf.loadLayersModel(modelJson);

```

I got the error:

**TypeError: Cannot read property ‘length’ of undefined load**

Then I got stucked. Can you help?

h5 saved model: https://drive.google.com/file/d/1NXzZnBbPcvMBMCxStChhkfhC9TloR47E/view?usp=sharing
Converted model and weights: https://drive.google.com/drive/folders/1OvQTG9wDLDLjZ17TMDNWY4K1RrDtTuSD?usp=sharing

Thanks in advance!

**Comment by rthadur** [comment]
@leolellisr this might be related issue to the repo https://github.com/FurkanOM/tf-blazeface , This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.
