### ISSUE TITLE
MoveNet Performance with JavaScript ES5

### ISSUE THREAD

**Issue by emsoneal** [tensorflow/tfjs#5235]
I was wondering if there are any suggestions for increasing MoveNet performance in ES5. Here is the one function below that I  make calls to MoveNet in.

~~~
detectPoseInRealTime = function(video) {
    //video is a HTML Video Element
    function poseDetectionFrame() {
        const imageElement = video; 
        const detectorConfig = {modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING};
        poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig).then(function(net) {
                const pose = net.estimatePoses(imageElement);
                return pose;
            }).then(function(pose){
                    //do something with the keypoint positions
                    //we are calling pose[0].keypoints[0] but will eventually want to use more
            }); 
        window.requestAnimationFrame(poseDetectionFrame);
    }
    poseDetectionFrame();
};
~~~

**Comment by lina128** [comment]
Hi @emsoneal , can you share with us the performance difference? If the difference is just then vs async/await, then there's nothing we can help here. async/await is more performant than then (ref: https://mathiasbynens.be/notes/async-stack-traces).

**Comment by emsoneal** [comment]
Sorry for the late response, we drastically improved performance, now averaging 50 fps, by calling createDetector() outside of the poseDetectionFrame() function.
