### ISSUE TITLE
Kernel 'Linspace" not registered for backend 'undefined'

### ISSUE THREAD

**Issue by asilvas** [tensorflow/tfjs#5237]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow.js installed from (npm or script link): 3.7.0
- TensorFlow.js version (use command below): 3.7.0
- Browser version: 3.7.0

**Describe the current behavior**

```
> tf.linspace(0, 9, 10)
Uncaught Error: Kernel 'LinSpace' not registered for backend 'undefined'
```

In browser docs example or locally in node

Might be connected to a recent commit but nothing obvious to me so haven't submitted PR yet: https://github.com/tensorflow/tfjs/commit/293d357e884cb903fc9c8a4ae9c48eb130f05e3b#diff-f085c223aa4f2e310b69b8f405f28107ae81921dbf1468392683f4e83fb9a0d7

**Standalone code to reproduce the issue**

```
tf.linspace(0, 9, 10)
```

**Comment by rthadur** [comment]
@jinjingforever I was able to reproduce the same , please check.

**Comment by jinjingforever** [comment]
Thank you for the report @asilvas! The PR above should fix this issue (it will be in the next release). For now, a workaround is wrapping the code around `tf.ready`:

```js
tf.ready(()=>{
  tf.linspace(0, 9, 10);
  // ...
});
```
