### ISSUE TITLE
README does not recommend installation of the right CUDA version

### ISSUE THREAD

**Issue by sbrl** [tensorflow/tfjs#5241]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 21.10 Hirsute Hippo
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.7.0
- CUDA/cuDNN version: 11.3 (causes crash), 11.0.3

**Describe the problem**
The documentation in the README does not correctly describe the version of CUDA required. Recently, I noticed that the version requirement for CUDA was bumped from 10.0 (thanks so much for that!). Unfortunately, the README has not also been updated (link: <https://github.com/tensorflow/tfjs/tree/master/tfjs-node#installing>), so it is unclear which version of CUDA is required.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

If I use CUDA 11.3 (system default), Tensorflow.js crashes because it can't open the libraries required.

If I switch to CUDA version 11.0.3, then  get lots of this message when compiling a model:

```
2021-06-22 16:23:11.284940: W tensorflow/stream_executor/gpu/asm_compiler.cc:235] Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'
```

I propose that the CUDA support table be expanded to support multiple versions of `@tensorflow/tfjs-node-gpu`. For example:

Tensorflow.js | Nvidia Driver | CUDA | CuDNN
------------------|-------------------|----------|-------------------
D.E.F - present | > EEE.x      | JK.L    | >= T.U.V
X.Y.Z - A.B.C | >410.x           | 10.0    | >= 7.4.1

This will enable people to ensure they have precisely the right version of CUDA installed.

**Any other info / logs**

**Comment by anzbert** [comment]
so CUDA 10 is the only working version right now?

**Comment by sbrl** [comment]
No, that's not necessarily the case with the latest version of Tensorflow.js @anzbert. If you are on an older version of Tensorflow yes, but with the latest version I have observed it attempting to load the CUDA 11 libraries, but as for which ones it is actually after I can't tell because the documentation is incorrect.

**Comment by rthadur** [comment]
This has been here https://github.com/tensorflow/tfjs/tree/master/tfjs-node#installing , can you please verify once now with latest version.

**Comment by sbrl** [comment]
Ah, looks like it has been updated now. Thanks @rthadur! Though I do strongly recommend implementing a table rather than just fiddling with the existing required versions, and adding a new row for every version of Tensorflow.js released.

Still, the core of my issue has been resolved, so I'll close this for now.
