### ISSUE TITLE
`tfjs-automl` image classification memory leak on Node.js

### ISSUE THREAD

**Issue by SukkaW** [tensorflow/tfjs#5242]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Repo link below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin 20.5.0 x64 (macOS Big Sur 11.4)
- TensorFlow.js installed from (npm or script link): npm
- System information:

```js
const os = require('os');
const { node, v8 } = process.versions;
const plat = `OS: ${os.type()} ${os.release()} ${os.arch()}\nNode.js: ${node}\nV8: ${v8}`;
const cpus = os.cpus().map(cpu => cpu.model).reduce((o, model) => {
  o[model] = (o[model] || 0) + 1;
  return o;
}, {});
const cpusInfo = Object.keys(cpus).map((key) => {
  return `${key} x ${cpus[key]}`;
}).join('\n');

console.log(`${plat}\nCPU: ${cpusInfo}\nMemory: ${os.totalmem() / (1024 * 1024)} MiB\n`);

// OS: Darwin 20.5.0 x64
// Node.js: 14.17.0
// V8: 8.4.371.23-node.63
// CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz x 16
// Memory: 32768 MiB
```

**Describe the current behavior**

`Resident Set Size` keeps getting bigger.

**Standalone code to reproduce the issue**

https://github.com/SukkaW/tfjs-memory-leak-example

**Other info / logs** Include any logs or source code that would be helpful to

```sh
git clone https://github.com/SukkaW/tfjs-memory-leak-example && cd tfjs-memory-leak-example
npm i
node index.js
```

```
Platform info:
OS: Darwin 20.5.0 x64
Node.js: 14.17.0
V8: 8.4.371.23-node.63
CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz x 16
Memory: 32768 MiB

daisy 146083840 2035808
daisy 152354816 2035808
daisy 153202688 2035808
daisy 157728768 2035808
daisy 163180544 2035808
daisy 167120896 2035808
daisy 169332736 2035808
daisy 169385984 2035808
daisy 170770432 2035808
daisy 172281856 2035808
daisy 174080000 2035808
daisy 174120960 2035808
daisy 176160768 2035808
.....
```

**Comment by rthadur** [comment]
The above GitHub link does not work , please check, meanwhile can you check this comment https://github.com/tensorflow/tfjs/issues/4015#issuecomment-704335135 if it helps , thank you

**Comment by SukkaW** [comment]
> The above GitHub link does not work , please check, meanwhile can you check this comment [#4015 (comment)](https://github.com/tensorflow/tfjs/issues/4015#issuecomment-704335135) if it helps , thank you

@rthadur The repo should be available now.

I will look into the link you provided, thanks for your reply!

**Comment by SukkaW** [comment]
Why the issue is marked as stale? I don't see the issue is being solved, or if it is a dupe of #3061

**Comment by SukkaW** [comment]
Is the Issue is still being working on?

I already provided a minimum reproduction using the modal provided by TensorFlow.js when I originally open the issue, why no one can find out what is going on?

**Comment by mattsoulanille** [comment]
Hi @SukkaW.

Sorry for not getting to this sooner, and thanks for posting a reproduction. I've isolated the cause of the memory leak to `tfNode.node.decodeJpeg`.

With the following code, memory use never exceeds 250Mb
```js
const tensor = tf.node.decodeJpeg(input);
for (let i = 0; i < 10000; i++) {
  const predictions = await model.classify(tensor);
  console.log(predictions[0].label, process.memoryUsage().rss, tf.memory().numBytes);
}
```

However, with this code, memory use climbs rapidly
```js
for (let i = 0; i < 10000; i++) {
  const tensor = tf.node.decodeJpeg(input);
  //const predictions = await model.classify(tensor);                                     
  tensor.dispose();
  console.log(/*predictions[0].label,*/ process.memoryUsage().rss, tf.memory().numBytes);
}
```
I've tested against TensorFlow 2.8 and 2.6, and this memory leak persists. I think the leak may be in the tfjs-node's node bindings, so that's what I'm checking now.
