### ISSUE TITLE
[tfjs-models] memory access out of bounds error in pose-detection demo

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#5248]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): https://unpkg.com/@tensorflow/tfjs-core@latest/dist/tf-core.js
- TensorFlow.js version (use command below): 3.7.0
- Browser version: 91.0.4472.114 
- Tensorflow.js Converter Version: 

**Describe the current behavior**
Met RuntimeError: memory access out of bounds when use wasm backend in posenet model.

**Describe the expected behavior**
Should not met Error

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
1. Add wasm backend to poseNet model.
```
diff --git a/pose-detection/demos/live_video/src/params.js b/pose-detection/demos/live_video/src/params.js
index 3ddf62e..66cdb98 100644
--- a/pose-detection/demos/live_video/src/params.js
+++ b/pose-detection/demos/live_video/src/params.js
@@ -80,7 +80,7 @@ export const BACKEND_FLAGS_MAP = {
 };

 export const MODEL_BACKEND_MAP = {
-  [posedetection.SupportedModels.PoseNet]: ['tfjs-webgl'],
+  [posedetection.SupportedModels.PoseNet]: ['tfjs-webgl', 'tfjs-wasm'],
   [posedetection.SupportedModels.MoveNet]: ['tfjs-webgl', 'tfjs-wasm'],
   [posedetection.SupportedModels.BlazePose]:
       isiOS() ? ['tfjs-webgl'] : ['mediapipe-gpu', 'tfjs-webgl']
```
2. `yarn watch`
3. Visit http://localhost:1234/?model=posenet
4. select "tfjs-wasm"

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by haoyunfeix** [comment]
Reproduce code is here: https://github.com/tensorflow/tfjs-models/pull/756

**Comment by rthadur** [comment]
Wasm is not supported in posenet , @lina128 can you please confirm if this is supported ?

**Comment by lina128** [comment]
Right, WASM is not supported, it's either too slow to run or throws memory access out of bounds error.
