### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by marcus7777** [tensorflow/tfjs#525]
I trying to find a way to work with my data
it is 2 * 40  with a value 0 to 28 with 26 label. 
I made a CSV the 80 values with the label on the end.
https://pastebin.com/3WyLipTG
any advice would be most welcome.
Thank You !!

**Comment by davidsoergel** [comment]
Please use StackOverflow for general questions like this.  Also, even there, I think you'll need to be much more specific about what you are trying to do and what you have tried so far.
