### ISSUE TITLE
mobilenet infer method's embedding parameter

### ISSUE THREAD

**Issue by volkans80** [tensorflow/tfjs#5250]
Why many example uses 'conv_preds' string for infer method's second parameter?
In type definitions, second parameter is boolean not string.

Thanks,

![image](https://user-images.githubusercontent.com/3122625/123333913-05b5dc00-d54b-11eb-8e4c-300a23b51cd5.png)

**Comment by rthadur** [comment]
This was changed here from string to boolean here https://github.com/tensorflow/tfjs-models/pull/161/files but was not updated in the above [example](https://github.com/tensorflow/tfjs-models/tree/master/knn-classifier) , I have created a PR and made it `true` by default.
