### ISSUE TITLE
Unsigned APK Not Working As Expected

### ISSUE THREAD

**Issue by lowkeyboard** [tensorflow/tfjs#5255]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**Describe the problem**
Before you say this is a react native issue, I want to say that I was always able to get apk files that works as expected until tensorflow.   Apk is not working as it should have been when i build it by commands: 
npx react-native start
npx react-native run-android

**Provide the exact sequence of commands / steps that you executed before running into the problem**

What I did: 
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

cd android && ./gradlew assembleDebug

and as expected I found the apk in this path 
mobile-app/android/app/build/outputs/apk/debug/app-debug.apk

However, this .apk file is not working like it's supposed to like when I run the commands 
npx react-native start
npx react-native run-android

Package.json: 
```
{
  "name": "Myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-picker/picker": "^1.16.1",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@teachablemachine/image": "^0.8.4",
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow/tfjs": "^3.7.0",
    "@tensorflow/tfjs-core": "^3.7.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "axios": "^0.21.1",
    "expo-av": "^9.1.2",
    "expo-camera": "^11.0.3",
    "expo-gl": "^10.3.0",
    "expo-gl-cpp": "^10.3.0",
    "expo-image-manipulator": "^9.1.0",
    "lottie-react-native": "^4.0.2",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^2.2.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-shapes": "^0.1.0",
    "react-native-unimodules": "^0.13.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by rthadur** [comment]
looking at the package.json I see you have both tfjs and tfjs-core , the later will take care of installing all the dependencies of tfjs , also did you check the steps here https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native ?

**Comment by lowkeyboard** [comment]
I deleted "@tensorflow/tfjs-core": "^3.7.0",   apk works but on the camera page (tensorflow's cameraWithSensors) is not providing any camera preview is a black screen and not recording video.

**Comment by lowkeyboard** [comment]
My bad, After setting permissions for camera, unsigned apk has started to work as expected.
