### ISSUE TITLE
Posenet Camera Demo is Broken

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#5257]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 5.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): N/A
- TensorFlow.js version (use command below): N/A
- Browser version: Chrome 91
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
The Posenet live camera demo displays "this browser does not support video capture,or this device does not have a camera" instead of opening the camera. Other models' live camera demos work fine on my machine.
**Describe the expected behavior**
The posenet live camera demo predicts poses from the computer's webcam.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

Click the demo from the [Posenet readme](https://github.com/tensorflow/tfjs-models/tree/master/posenet). Here's a [direct link](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html) to the demo.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Neilblaze** [comment]
@mattsoulanille the demo [link](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html) which you provided is working for me without any issues (on my PC - Windows 10 pro x64 | Chrome 91.0.4472.124). Later, I re-checked whether the issue persists on different systems, & found that my MacBook is also facing the same issue (with Chrome).

**Comment by mattsoulanille** [comment]
This is strange. The demo is now working for me with no issues on the same computer I used in my first test. I don't believe I've made any changes to the setup (haven't restarted Chrome). I also tested on a 2015 macbook pro 10.14.6 chrome 91.0.4472.114 with no issues. I'll keep this issue open since you've been able to reproduce it.

**Comment by Neilblaze** [comment]
@mattsoulanille I would love to add an update to my reply.

I was facing the same issue (on my MacBook Air) which you mentioned, later I figure out that doing a **hard refresh** fixes the issue! I think, I was able to reproduce the issue because of the cache of the ResNet50 model from one of my personal projects, which might be creating an issue when a new model (MobileNetv1) was loading up.

**Comment by mattsoulanille** [comment]
Thanks for the additional info, @Neilblaze. I was running some other demos that use ResNet50 locally, so maybe that caused the same cache problems you had. I thought I had done an **empty cache and hard reload**, but I guess I actually didn't. I'll close this issue, since it seems like that was the problem.
