### ISSUE TITLE
[tfjs-converter] Conversion from `tf_saved_model` to `tfjs_layers_model`

### ISSUE THREAD

**Issue by MaximeKjaer** [tensorflow/tfjs#5269]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 3.7.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, the [Python-to-Javascript conversion table of tfjs-converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#python-to-javascript) features a conversion from `tf_saved_model` to `tfjs_graph_model`, but no conversion from `tf_saved_model` to `tfjs_layers_model`.

The feature this issue requests is to add a conversion from `tf_saved_model` to `tfjs_layers_model`.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Users who want to take a model defined in Python, save it to a file, and load it into TensorFlow.js for training. 

Supposing the Python implementation of the model doesn't use the Keras API, the only option is to save the model as a TensorFlow SavedModel; as far as I know, it isn't possible to save something not defined using the Keras API to `keras` or `keras_saved_model` formats.

My understanding is that it is currently not possible to load such a model to TensorFlow.js for training, as `tf_saved_model` can only be converted to `tfjs_graph_model`, which can only be used for inference / serving, and not for training.

**Any Other info.**

Are there any technical limitations to this conversion?

**Comment by pyu10055** [comment]
@MaximeKjaer The conversion from saved_model to tfjs_layers_model is possible, if the saved_model is created by TF keras API.
The corresponding input format is keras_saved_model

```
