### ISSUE TITLE
About the Bug of executeAsync Asynchronous Function

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tfjs#5291]
@rthadur @lina128
I studied the object detection project of tfjs and found that the code of `tf.loadGraphModel(weights).executeAsync(input)` has some bugs when it is called.
Bug description:
When there is a detected object in the input picture, the program is normal, as shown in the figure.
![ksnip_20210705-103113](https://user-images.githubusercontent.com/41098760/124410046-27e60000-dd7c-11eb-8934-4bc6145d336f.png)
As can be seen from the above figure, the object has been detected normally, and there is no error message in the chrome console.Let's look at a bug, as shown in the figure below:
![ksnip_20210705-103511](https://user-images.githubusercontent.com/41098760/124410277-b6f31800-dd7c-11eb-809d-822f94fc5d5a.png)
When I upload a picture without an object to be detected by the detector, the `executeAsync` function will throw an error message and terminate the program at the same time.
This happened when I used the camera to detect it. When there is no object to be detected in the first frame or other frames in the camera, an error will be reported and the program will be terminated.
##### This is my complete project code:https://drive.google.com/file/d/11uuOqKprEc5Ot30WuWRwwxMbSaDb7Lk-/view?usp=sharing
- There is my code and model in this project
- Have my profile
- Steps for usage:
```shell
# 1. Unzip
# 2. Install dependencies with yarn
yarn
# 3. Run
yarn start
```
I want the program to not display this kind of error message in pictures without detected objects, and the program can run normally.I tried many exception catching methods, such as try catch, ErrorBoundary tag, etc., but nothing worked. I think it’s not Reactjs's problem, but tfjs's problem.
So please experts help me, thank you.

**Comment by vladmandic** [comment]
see #4716 for details (still open)

**Comment by Zengyf-CVer** [comment]
> see #4716 for details (still open)

I have read your question before, but I still want to ask you, is this error because there is no object to be detected by the model in the picture you entered? In other words, is the problem you encountered because executeAsync function cannot handle the returned empty object? Thank you.

**Comment by vladmandic** [comment]
I'm guessing it's about empty return as TFJS is connecting layers, it doesn't necessarily has to be output layer.

**Comment by rthadur** [comment]
Thank you @vladmandic , I will this close this issue and track the same at #4716
