### ISSUE TITLE
[WebGL] Failed to compile fragment shader 

### ISSUE THREAD

**Issue by Honry** [tensorflow/tfjs#5293]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All platforms
- TensorFlow.js version (use command below):  tf.js 3.7.0 webgl backend.
- Browser version: Chrome 93.0.4545.0

**Describe the current behavior**
WebGL backend throws `Failed to compile fragment shader` error while using `depthwiseConv2d` op with specific options. While WebGPU backend doesn't reproduce.

**Describe the expected behavior**
No error.

**Standalone code to reproduce the issue**

CodePen: https://codepen.io/honry/pen/wvdMmva

```
    const input = tf.fill([1, 65, 65, 960], 0);
    const weights = tf.fill([3, 3, 960, 1], 1);
    const result = tf.depthwiseConv2d(input, weights, 1, 'same', 'NHWC', 4);
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Please check error log from https://codepen.io/honry/pen/wvdMmva

**Comment by huningxin** [comment]
Thanks @Honry , how about the cpu backend and wasm backend?

**Comment by Honry** [comment]
@huningxin, this issue only reproduce on webgl backend.

**Comment by ColorfulCakeChen** [comment]
A similiar situation could be occurred by the following codes (i.e. depthwiseCon2d with ( strides == 2 ) ):

```
//await tf.setBackend( "cpu" ); // Error not happend in CPU.
await tf.setBackend( "webgl" ); // Error happend in WebGL.

let a = [
  111, 112, 113, 114, 121, 122, 123, 124, 131, 132, 133, 134,
  141, 142, 143, 144, 151, 152, 153, 154, 211, 212, 213, 214,
  221, 222, 223, 224, 231, 232, 233, 234, 241, 242, 243, 244,
  251, 252, 253, 254, 311, 312, 313, 314, 321, 322, 323, 324,
  331, 332, 333, 334, 341, 342, 343, 344, 351, 352, 353, 354];
let shape = [ 3, 5, 4 ];
let x = tf.tensor( a, shape );

let filters = tf.tensor( [ 11, 22, 33, 44 ], [ 1, 1, 4, 1 ] );

// When ( strides == 1 ), No problem.
let c = tf.depthwiseConv2d( x, filters, 1, "valid" );
c.print();
let d = tf.depthwiseConv2d( x, filters, 1, "same" );
d.print();

// When ( strides == 2 ), error: "Failed to compile fragment shader."
let e = tf.depthwiseConv2d( x, filters, 2, "valid" );
e.print();

// When ( strides == 2 ), error: "Failed to compile fragment shader."
let f = tf.depthwiseConv2d( x, filters, 2, "same" );
f.print();

```

**Comment by Honry** [comment]
@pyu10055, many thanks for fixing this issue! The `compile error` had been fixed, but the computed result looks wrong.

Here's a simple test, I just compared the first value of the output buffer, which is obviously different from result from `wasm` and `cpu` backends.

https://codepen.io/honry/pen/wvdMmva

**Comment by Honry** [comment]
@pyu10055, friendly ping. :) Should I create a separate issue for incorrect computational result?

**Comment by rthadur** [comment]
@Honry please open a new issue. Thank you

**Comment by Honry** [comment]
Thanks @rthadur, I've created a new issue at https://github.com/tensorflow/tfjs/issues/5378.
