### ISSUE TITLE
Tensor image is flipped horizontally when using back camera

### ISSUE THREAD

**Issue by facuacostag** [tensorflow/tfjs#5298]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.2.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iOS/Android
- TensorFlow.js installed from: npm
- TensorFlow.js version: "@tensorflow/tfjs" -> 3.7.0 / "@tensorflow/tfjs-react-native" -> 0.6.0

**Describe the current behavior**
I'm trying to user the back camera `Camera.Constants.Type.back` from the `cameraWithTensors` component. The main issue I'm facing is that the tensor image returned back from the callback is flipped horizontally, so my model cant detect the text properly, since it's not a real text. I tried to flip the tensor with `tf.image.flipLeftRight(tensor);` but nothing is happening. I believe the issue is happening when the tensor is generated from the GL texture but I can't tell where since my knowledge of GL is very limited.

**Describe the expected behavior**
Image tensor to be returned with the proper orientation as seen on the preview. As you can see on the image below, preview is on the right orientation but when converting the tensor to an image to see the result, it's flipped. This doesnt happen with `Camera.Constants.Type.front`

![Screenshot_20210707-111202_Stamp Free Carrier](https://user-images.githubusercontent.com/19332669/124753973-8b5d6280-df21-11eb-9b91-b8592d04f083.jpg)

**Standalone code to reproduce the issue**
```
<TensorCamera
          // Standard Camera props
          style={styles.camera}
          type={Camera.Constants.Type.back}
          zoom={0}
          // tensor related props
          cameraTextureHeight={textureDims.height}
          cameraTextureWidth={textureDims.width}
          resizeHeight={840}
          resizeWidth={400}
          resizeDepth={3}
          onReady={handleImageTensorReady}
          autorender={AUTORENDER}
        />
```

**Comment by rthadur** [comment]
Sorry for the delay , could you please update the issue if it exists in latest versions ?
