### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by djbreen7** [tensorflow/tfjs#5313]
The documentation appears to be outdated.

The main readme states:
> ⚠️ We recently released TensorFlow.js 2.0. If you have been using TensorFlow.js via a script tag without specifying a version and see an error saying no backends are found, then you should read our release notes for instructions on how to upgrade.

npmjs shows that v2.0.0 was one year ago. The current "latest" version is 3.7.0, which was published last month.
- https://www.npmjs.com/package/@tensorflow/tfjs/v/3.7.0
- https://www.npmjs.com/package/@tensorflow/tfjs/v/2.0.0

The concern is that developers are likely using the README for v2 code while using v3.

Additionally, [WINDOWS_TROUBLESHOOTING](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) is outdated.

> Currently, node-gyp requires Python 2.x to work properly. If Python 3.x is installed, you will see build failures. Also double check your python version python --version and update the Windows $PATH as needed.

That statement is inaccurate. See https://github.com/nodejs/node-gyp/issues/1977#issuecomment-567131298
> You do not need Python 2.7 in order to run node-gyp. **_Python 3 has been supported since version 5.0.5_**. If you have verified that your issue is python related, as in that node-gyp is trying to run a script which contains errors according to the python 3 interpreter, then try the following:
...

**Comment by rthadur** [comment]
@djbreen7 thanks for checking this , I have submitted 2 separate PRs to remove above lines
