### ISSUE TITLE
how to transform a model file saved by tfjs to a model file used by python ?

### ISSUE THREAD

**Issue by zju-zry** [tensorflow/tfjs#5318]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

is there have any solutions 

I really want to get,

thanks!

**Comment by rthadur** [comment]
please check this out https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#javascript-to-python , you will be able to find commands how to convert from tfjs to python.

**Comment by zju-zry** [comment]
thanks for your answer, I knew it later.
