### ISSUE TITLE
Trying to use ML5.js with Posenet

### ISSUE THREAD

**Issue by emsoneal** [tensorflow/tfjs#5319]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOs Big Sur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
script link
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**
I am trying to use two different tfjs libraries ml5.js and posenet in a single project. They both work in seperate projects, but I get errors building when they are used together. To run https://unpkg.com/ml5@latest/dist/ml5.min.js I need https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.13.5, but that version of tfjs is incompatible with https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection and https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Right now I am using the following to load a ml model:
https://unpkg.com/ml5@latest/dist/ml5.min.js with https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.13.5
and in a different project the following to do pose detection
https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection and https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core with https://cdn.jsdelivr.net/npm/@tensorflow/tfjs
Each project works separately, but not together.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
When I run the pose detection project with https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.13.5 I get the following error:
<img width="665" alt="Screen Shot 2021-07-12 at 2 32 12 PM" src="https://user-images.githubusercontent.com/20036774/125358652-06f25180-e31e-11eb-975b-d89acafa1f3b.png">

**Comment by rthadur** [comment]
This question is better suited for https://github.com/ml5js/ml5-library/issues , we will not be able to support ML5.js. One thing to mention is you can't use tfjs and tfjs-core together because tfjs is a union package which includes tfjs-core.So please use only one package.
