### ISSUE TITLE
Model.executeAsync() adds another not-disposed Tensor.

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5324]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow.js installed from (npm or script link):  script link
- TensorFlow.js version (use command below):
- Browser version: 3.7.0
- Tensorflow.js Converter Version: 3.7.0

**Describe the current behavior**

After executing this code `prediction=await Model.executeAsync(); `  Expecting `prediction.dispose()` to dispose all children, but `executeAsync` model seems to produce at least a single Tensor which isn't disposed by the Model and can't be disposed manually.

**Describe the expected behavior**
no tensor can't be disposed 

**Standalone code to reproduce the issue**
Before  executing `Model.executeAsync()`, the `tf.memory().numTensors` is 128,  after executing `predictions=Model.executeAsync()`, the `tf.memory().numTensors` is 130,  and then execute `prediction.dispose()`, the expected  `tf.memory().numTensors` is 128,  but it is 129.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>layer_test</title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
</head>
<body>
<script>
console.log('start', tf.memory().numTensors); // start 0
var m;
(async()=>{
m=await tf.loadGraphModel("http://qw7y9u2r4.hb-bkt.clouddn.com/model.json");
console.log('+ model', tf.memory().numTensors); // + model 128
const prediction = await m.executeAsync(tf.tensor2d(new Array(300).fill(34), [1,300],'float32'));
console.log('+ executeAsync', tf.memory().numTensors); // + executeAsync 130
prediction.dispose();
console.log('+ predict', tf.memory().numTensors); // + predict 129
m.dispose(); 
console.log('- model', tf.memory().numTensors); // - model 1
})();
</script>
</body>
</html>
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
@liliquan0118 Your model seems to be layers model not a graph model. The code you shared does not seem to work. Can you create a working example on codepen or other site? thanks

**Comment by liliquan0118** [comment]
> @liliquan0118 Your model seems to be layers model not a graph model. The code you shared does not seem to work. Can you create a working example on codepen or other site? thanks

Thank you for your reply, Sorry there is a problem with the model link in the code, I re-updated the model, now the code can work normally.  
the new code is:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>layer_test</title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
</head>
<body>
<script>
console.log('start', tf.memory().numTensors); // start 0
var m;
(async()=>{
m=await tf.loadGraphModel("http://qw7y9u2r4.hb-bkt.clouddn.com/model.json");
console.log('+ model', tf.memory().numTensors); // + model 128
const prediction = await m.executeAsync(tf.tensor2d(new Array(300).fill(34), [1,300],'float32'));
console.log('+ executeAsync', tf.memory().numTensors); // + executeAsync 130
prediction.dispose();
console.log('+ predict', tf.memory().numTensors); // + predict 129
m.dispose();
console.log('- model', tf.memory().numTensors); // - model 1
})();
</script>

</body>
</html>
```
Or, you can run the following bug-5324.html file directly.
[bug-5324.zip](https://github.com/tensorflow/tfjs/files/6813778/bug-5324.zip)

**Comment by pyu10055** [comment]
@liliquan0118 in your code, you have created a new tensor as input, you need to manually dispose it as shown below:
```
const input = tf.tensor2d(new Array(300).fill(34), [1,300],'float32');
const prediction = await m.executeAsync(input);
...
prediction.dispose();
input.dispose();
```
