### ISSUE TITLE
WASM throws memory access out of bounds in Chrome but not Firefox/Edge

### ISSUE THREAD

**Issue by tauber** [tensorflow/tfjs#5336]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
Yes, at least as pertains to the web part.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10

- TensorFlow.js installed from (npm or script link):
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js");

- Browser version:
Chrome 91.0.4472.164

**Describe the current behavior**
When running the ProGan model on a website in web workers, when using WASM backend, Firefox and Edge will use tfjs-backend-wasm-simd.wasm while Chrome will use tfjs-backend-wasm-threaded-simd.wasm. 
The code will execute fine on Firefox and Edge but fail on Chrome with unclear exceptions. Best guess, multithreaded only works on the main js module and fails through workers.

However, when setting WASM_HAS_MULTITHREAD_SUPPORT to false, Chrome uses the same tfjs-backend-wasm-simd.wasm file and throws a memory access out of bounds exception. Again, this works fine with the other browsers. This is the same with WASM_HAS_SIMD_SUPPORT set to false as well.

**Describe the expected behavior**
Chrome should load the model instead of throwing the error.

NOTE: I'm running wasm in worker threads not only to achieve multithreading on browsers other than Chrome, but primarily to not block the UI thread. This is for benchmarking, not meant to be real-time.

**Standalone code to reproduce the issue**
https://github.com/tauber/progan

You can run the demo from http://objectcoded.com/progan/progan.html
Select any number of threads and WASM for the backend. Approx. ~100MB model.

Exception details:
Uncaught (in promise) RuntimeError: memory access out of bounds
    at tfjs-backend-wasm-simd.wasm:0xa8b
    at Pa (tfjs-backend-wasm-simd.wasm:0x1aaa2)
    at BackendWasm.move (backend_wasm.ts:83)
    at BackendWasm.write (backend_wasm.ts:54)
    at e.t.makeTensor (engine.js:813)
    at Sk (tensor_ops_util.js:75)
    at Tk (tensor.js:56)
    at Ak (io_utils.js:224)
    at e.t.loadSync (graph_model.js:160)
    at e.<anonymous> (graph_model.js:134)
(anonymous) @ tfjs-backend-wasm-simd.wasm:0xa8b
Pa @ tfjs-backend-wasm-simd.wasm:0x1aaa2
BackendWasm.move @ backend_wasm.ts:83
BackendWasm.write @ backend_wasm.ts:54
t.makeTensor @ engine.js:813
Sk @ tensor_ops_util.js:75
Tk @ tensor.js:56
Ak @ io_utils.js:224
t.loadSync @ graph_model.js:160
(anonymous) @ graph_model.js:134
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
bv @ runtime.js:747
o @ runtime.js:747
async function (async)
render_gan_image @ render-gan.js:73

**Comment by jinjingforever** [comment]
Hi @tauber,

Thanks for the report! 

Looks like the problem is version mismatch. The `progan/modules/tfjs-backend-wasm-simd.wasm` file in your [repo](https://github.com/tauber/progan) is from 3.7.0, but the `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js` is loading 3.8.0 (which was released 23 days ago, 2 days before your repo was created). 

I replaced `tfjs-backend-wasm-simd.wasm` with the one from 3.8.0 and your app works without problems (great app btw!). I am not entirely sure why things work on other browsers though.. 

One thing to do to help with this is to call the following in your worker script (maybe after the two `importScripts` calls). This will ask the wasm backend to load the wasm binary files from jsdelivr so you don't need to copy them manually. I tried it and it seems to [work](https://drive.google.com/file/d/1utcV8WEiG6AQlkdYJbV7dCyazt1jCyML/view?usp=sharing).

```js
tf.wasm.setWasmPaths(
    'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/'
);
```

Thanks!

**Comment by rthadur** [comment]
Thank you @tauber , did you mean to say the documentation here https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md#using-bundlers  is not clear ?

**Comment by jinjingforever** [comment]
@rthadur Looks like the doc didn't mention what to do when importing the wasm backend through the script tag. I will update it. Thanks!

**Comment by tauber** [comment]
Now I see the comment: '// or tf.wasm.setWasmPaths when using <script> tags.'
I don't know why I missed this. Making it more obvious would definitely help exhausted developers :)
Thank you again for your help with this issue.

**Comment by tauber** [comment]
Hi Jing Jin,

Thank you so much for handling my case (5336). Great advice on that fix!

With the same program I run into memory out of bound errors on the GPU 
when using webgl. This has to do with issue #4166 as well.

I know you didn't have the time to fix texture size allocations in the 
GPU version of TF (I don't even think that is the real issue, rather 
than no garbage collection), but I did want to add some information 
about the issue, if that helps.

I have the same PROGAN model running on Python and on javascript on the 
GPU. Both take the same amount of memory and overflow over 4gb (which is 
the size of my graphics card). However, the python version completes the 
operation while the web version crashes. Any ideas how TF/CUDA on python 
achieves that and if it can be applicable to webgl? Should this be 
another issue, or just drop it?

This is what python says:

W tensorflow/core/common_runtime/bfc_allocator.cc:271] Allocator 
(GPU_0_bfc) ran out of memory trying to allocate 3.39GiB with 
freed_by_count=0. The caller indicates that this is not a failure, but 
may mean that there could be performance gains if more memory were 
available.



I'm happy to live with slowdowns when the alternative is 
non-functionality, and I think a lot of other people will be too.

Thank you,

- Zohar
