### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by davideduma** [tensorflow/tfjs#5346]
Greetings

The following error is presented in console in step 2 (TensorFlow.js: Handwritten Digit Recognition with CNN)

2127.0.0.1/:1 Uncaught TypeError: Failed to resolve module specifier "@tensorflow/tfjs". Relative references must start with either "/", "./", or "../".

**Comment by rthadur** [comment]
It is working as expected in step 2 , please check the glitch here https://glitch.com/edit/#!/snowy-quilt-cinema?path=data.js%3A142%3A1

**Comment by davideduma** [comment]
Thank you
