### ISSUE TITLE
Is there some way to surpress this warning message?

### ISSUE THREAD

**Issue by TylerLeonhardt** [tensorflow/tfjs#5349]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 3.8.0
- Are you willing to contribute it (Yes/No): maybe but likely no

**Describe the feature and the current behavior/state.**

👋 from the VS Code team

We use tfjs in VS Code and see this warning:
![image](https://user-images.githubusercontent.com/2644648/126220844-e3eb21e8-85d8-4728-a9ec-9413d0ff2896.png)

It would add a lot of extra complexity to include tfjs-node in VS Code so we'd like to not do what it's suggesting and instead would like to suppress this warning.

Is this possible?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
People who don't want to use tfjs-node

**Any Other info.**

**Comment by TylerLeonhardt** [comment]
The 1st warning is also a little strange... it's something inside of tfjs causing that.

**Comment by pyu10055** [comment]
@TylerLeonhardt what environment are you running in? seems both of the flags IS_BROWSER and IS_NODE are true.

```
export function isBrowser(): boolean {
  return (typeof window !== 'undefined' && window.document != null) ||
      //@ts-ignore
      (typeof WorkerGlobalScope !== 'undefined');
}

/** Whether we are in a browser (as versus, say, node.js) environment. */
ENV.registerFlag(
    'IS_NODE',
    () => (typeof process !== 'undefined') &&
        (typeof process.versions !== 'undefined') &&
        (typeof process.versions.node !== 'undefined'));
```

**Comment by TylerLeonhardt** [comment]
@pyu10055 within VS Code. My guess is that since it's an electron app... both return true.

**Comment by pyu10055** [comment]
@TylerLeonhardt in this case, you can just use webgl backend by not including tfjs-backend-cpu package.
in you deps, you can add only tfjs-core, tfjs-backend-webgl, tfjs-converter packages instead of tfjs union package.

**Comment by TylerLeonhardt** [comment]
@pyu10055 thanks for the pointer! I believe you said CPU is best in our use-case in the previous issue, so I'm trying that. 
Here's what I tried:

* Removing `@tensorflow/tfjs` from package.json
* Adding these to package.json:
  *  `"@tensorflow/tfjs-backend-cpu": "^3.8.0",`
  *  `"@tensorflow/tfjs-converter": "^3.8.0",`
  * `"@tensorflow/tfjs-core": "^3.8.0",`
* Changing this:
```
import { GraphModel, io, loadGraphModel, Rank, setBackend, tensor, Tensor } from '@tensorflow/tfjs';
```
to
```
import { Rank, tensor, Tensor, io, setBackend } from '@tensorflow/tfjs-core';
import { GraphModel, loadGraphModel } from '@tensorflow/tfjs-converter';
import '@tensorflow/tf-backend-cpu';
```

Unfortunately, this still yields the logs in the original screenshot.

For your reference, the code in question is found here: https://github.com/Microsoft/vscode-languagedetection
and is then loaded into vscode. The test in the vscode-languagedetection repo shows the "hi there 👋 " log.

**Comment by pyu10055** [comment]
@TylerLeonhardt can you try to set `IS_NODE` to false before you load the model?
```
tf.env().set('IS_NODE', false);
```

**Comment by TylerLeonhardt** [comment]
@pyu10055 That gets rid of the "hi there 👋 " log, great!

The last one that shows up is:
```
Platform browser has already been set. Overwriting the platform with [object Object].
```
which only shows up when running in VS Code... (in electron, I guess)... in my mocha tests in the vscode-languagedetection repo I do not see it.

**Comment by TylerLeonhardt** [comment]
Thanks for this @pyu10055!
