### ISSUE TITLE
Windows server 

### ISSUE THREAD

**Issue by Aserrano-rds** [tensorflow/tfjs#5354]
Im trying to use @tensorflow/tfjs-node  on windows server CPU is Intel(R) Xeon(R) Gold 6154 CPU, but i'm getting this error:

cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Marcas\BE\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node

node version: 14.16.1

**Comment by Aserrano-rds** [comment]
now I'm getting this error: 

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Marcas\BE\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node

**Comment by rthadur** [comment]
Can you please check a related issue here https://github.com/tensorflow/tfjs/issues/2619#issuecomment-712391683 , you need to manually copy dll to resolve this. Thank you

**Comment by Aserrano-rds** [comment]
@rthadur already did that but it didnt work, I tried installing the cuda and using the version with gpu enable and it didnt work also.
This is my current error 
Error: A dynamic link library (DLL) initialization routine failed.

I tried installing in a server that I have in aws and it worked without any problem so not sure what happened with this one :(

**Comment by pyu10055** [comment]
@Aserrano-rds did the installation of `tfjs-node` package failed with error messages?

**Comment by Aserrano-rds** [comment]
@pyu10055 no, everything seems to success

**Comment by pyu10055** [comment]
can you try to rebuild the addon in the tfjs-node directory:

```sh
cd node_module/\@tensorflow/tfjs-node/
yarn build-addon-from-source
```

**Comment by Aserrano-rds** [comment]
@pyu10055  as far as I remember yes I did it and that's when I get the error Error: A dynamic link library (DLL) initialization routine failed.

I will do it again just to double check!

**Comment by pyu10055** [comment]
if you are on node v 14.16, using napi-v5 seems to be too old, should be napi-v7.
can you check what is in the directory `node_modules/\@tensorflow/tfjs-node/lib/`?
