### ISSUE TITLE
When in wasm backend, tf.pool() with windowShape (filter size) 1x1 seems wrong.

### ISSUE THREAD

**Issue by ColorfulCakeChen** [tensorflow/tfjs#5355]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes (in the following gist)
- OS Platform and Distribution: Chrome OS 91.0.4472.147 (64 bits)
- Mobile device: ASUS ZenPhone Max Pro
- TensorFlow.js installed from: script link
- TensorFlow.js version: 3.8.0
- Browser version: Chrome 91.0.4472.147 (64 bits)

**Describe the current behavior**
  - When backend is WASM, the result of tf.pool() with windowShape (filter size) [ 1, 1 ] seems wrong (compared to backend cpu or webgl). However, if windowShape is not [ 1, 1 ] (e.g. [ 1, 2 ] or [ 2, 1 ] or [ 2, 2 ] or ...), the result is correct.

**Describe the expected behavior**
  - Even if windowShape is [ 1, 1 ], tf.pool() in backend WASM should produce the same result as in backend cpu or webgl.

**Standalone code to reproduce the issue**
  - https://gist.github.com/ColorfulCakeChen/23cc2b6ad89eac100e68150bb134ae1e
  - (The code could be pasted into any example console box of Tensorflow.js API web page (https://js.tensorflow.org/api/3.8.0/) to run.

**Other info / logs** 
<pre>
Loading "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"
windowShape = 1,1
backend = wasm
Tensor 
    [ [[0  , 0  , 200],],         // WRONG!

      [[201, 102, 210],]]         // WRONG!
backend = cpu
Tensor
    [ [[100, 101, 102],],

      [[300, 301, 302],]]
backend = webgl
Tensor
    [ [[100, 101, 102],],

      [[300, 301, 302],]]

windowShape = 1,2
backend = wasm
Tensor
    [ [[110, 111, 112],],

      [[310, 311, 312],]]
backend = cpu
Tensor
    [ [[110, 111, 112],],

      [[310, 311, 312],]]
backend = webgl
Tensor
    [ [[110, 111, 112],],

      [[310, 311, 312],]]

windowShape = 2,1
backend = wasm
Tensor
    [ [[200, 201, 102],],

      [[300, 301, 302],]]
backend = cpu
Tensor
    [ [[200, 201, 102],],

      [[300, 301, 302],]]
backend = webgl
Tensor
    [ [[200, 201, 102],],

      [[300, 301, 302],]]
</pre>

**Comment by gaikwadrahul8** [comment]
Hi, @ColorfulCakeChen 

Apologize for the delayed response and I tried to replicate the same issue with latest version of `@tensorflow/tfjs-backend-wasm` and it seems like code is working as expected and for your reference I have added screenshot below so could you please try it from your end and let us know whether your issue is resolving or not please ?

Here is code snippet :

```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-backend-wasm';
await tf.setBackend('wasm').then(() => main());

async function main() {
  let inputArray = [
      100, 101, 102,  110, 111, 112,
      200, 201, 102,  210, 211, 212,
      300, 301, 302,  310, 311, 312,
    ];

    let inputShape = [ 3, 2, 3 ];
    let windowShape = [1,1];

    let inputTensor = tf.tensor( inputArray, inputShape );

    //let windowShape = [ 1, 1 ];
    let poolingType = "max";//"avg";
    let pad = "same"; //"valid";
    let dilations = 1;
    let strides = 2;//1;

    let r = tf.pool( inputTensor, windowShape, poolingType, pad, dilations, strides );
    r.print();

  }
  main();
  console.log(`Backend loaded :`,tf.getBackend());
```

Here is output log :

```
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ node index.js
Platform node has already been set. Overwriting the platform with node.
Tensor
    [ [[100, 101, 102],],

      [[300, 301, 302],]]
Tensor
    [ [[100, 101, 102],],

      [[300, 301, 302],]]
Backend loaded : wasm
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ 
```
