### ISSUE TITLE
Error: The shape of dict[‘input_tensor’] provided in model.execute(dict) must be [1,-1,-1,3]

### ISSUE THREAD

**Issue by playground** [tensorflow/tfjs#5366]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
MacOS Big Sur
Node v15.7.0
NPM 7.20.0

I'm running @tensorflow/tfjs-node v 3.7.0

 I attempted to convert my saved model to friendly model json using tensorflowjs_converter
```
    tensorflowjs_converter \                            
    --input_format=tf_saved_model \   
    --output_format=tfjs_graph_model \    
    --saved_model_tags=serve \
    --signature_name=serving_default \
    /saved_model \
   /json-model
```
When run model.predict(), it's throwing these errors

```
Error: The shape of dict['input_tensor'] provided in model.execute(dict) must be [1,-1,-1,3], but was [1,600,800,4]
    at Object.assert (/object-detection/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:337:15)
    at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7478:28
    at Array.forEach (<anonymous>)
    at GraphExecutor.checkInputShapeAndType (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7470:29)
    at GraphExecutor.<anonymous> (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7272:34)
    at step (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:81:23)
    at Object.next (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:62:53)
    at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:55:71
    at new Promise (<anonymous>)
    at __awaiter (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:51:12) 
```

I have also tried model.executeAsync()  instead of model.predict(), executeAsync() 
NOTE:  When use with SavedModel(without the conversion) it works for both image types

for jpg image
```
Image: 1440000 bytes with shape: Tensor {
  kept: false,
  isDisposedInternal: false,
  shape: [ 1, 600, 800, 3 ],
  dtype: 'int32',
  size: 1440000,
  strides: [ 1440000, 2400, 3 ],
  dataId: {},
  id: 918,
  rankType: '4',
  scopeId: 2
}

Error: Invalid TF_Status: 3
Message: In[0] and In[1] has different ndims: [1,8,8,64,2] vs. [2,1]
```
for png image
```
Error: The shape of dict['input_tensor'] provided in model.execute(dict) must be [1,-1,-1,3], but was [1,600,800,4]

```

If I add ----control_flow_v2=True to do the conversion, it will fail to loadGraphModel.
```
I'm running @tensorflow/tfjs-node v 3.7.0 and I'm still getting this error "Cannot read property 'outputs' of undefined" when tried to load model json that was converted from saved model using tensorflowjs_converter.
When I changed to @tensorflow/tfjs-node@next, it would throw "Cannot read property 'children' of undefined"

model = await tf.loadGraphModel(modelPath);

2021-07-10 13:26:00.618147: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

TypeError: Cannot read property 'outputs' of undefined
at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3851:31
at Array.forEach ()
at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3848:29
at Array.forEach ()
at OperationMapper.mapFunction (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3846:18)
at /object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3679:56
at Array.reduce ()
at OperationMapper.transformGraph (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:3678:48)
at GraphModel.loadSync (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7763:68)
at GraphModel. (/object-detection/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:7737:52)

```

**Comment by rthadur** [comment]
Can you try to reshape like this `tensor = tensor.reshape([1, 224, 224, 3]); before you call predict ?
`

**Comment by playground** [comment]
Yes I did that too, that didn't help.

**Comment by playground** [comment]
Also with tfjs-node v3.8.0 seems to have broken the functionality for loadSavedModel() for MacOS.  Looks like a regression bug, I have posted that here https://github.com/tensorflow/tensorflow/issues/38260/#issuecomment-881928290

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code pen example or sample code to reproduce the issue. Thanks!

**Comment by playground** [comment]
Basically this is what I did
tfnode.loadGraphModel(modelUrl);
const image = fs.readFileSync(imageFile);
let decodedImage = tfnode.node.decodeImage(image);

tried both predict and executeAsync

I can share the converted model.json if that will help.

**Comment by rthadur** [comment]
sure, if possible a working codepen example or a git repo. Thank you

**Comment by playground** [comment]
Here is the converted model.json https://github.com/playground/tfjs-object-detection/tree/main/model-json-service/model

**Comment by playground** [comment]
@rthadur v3.8.0 seems to have broken for Mac for loadSavedModel, model.predict() is throwing this error

```
Error: Session fail to run with error: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/map/TensorArrayV2_1/_9__cf__9}}]]

```

**Comment by playground** [comment]
Any update?

**Comment by andresalvarezolmo** [comment]
Running into the same issue with a custom version of EfficientNetB4,

This is the snippet

    const model = await tf.loadGraphModel("file://src/ml/model.json");
    fs.readFile('src/ml/examples/example1.jpg', (err, buffer) => {
        if (err) {
          console.error(err);
          return;
        }
        const image = Buffer.from(buffer, 'base64')
        const tensor = tfnode.node.decodeImage(image)
        let prediction = model.predict(tensor).dataSync();
    });
})

Error code:
`Error: The shape of dict['input_1'] provided in model.execute(dict) must be [-1,-1,-1,3], but was [1024,1024,3]`

**Comment by gaikwadrahul8** [comment]
Hi, @playground 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by playground** [comment]
Yes, this issue still exists, please keep this open until it's resolved.

**Comment by pyu10055** [comment]
@gaikwadrahul8 I think you need to try the raw link of the model
https://raw.githubusercontent.com/playground/tfjs-object-detection/main/model-json-service/model/model.json

**Comment by gaikwadrahul8** [comment]
Hi, @playground 

Apologize for the delayed response and I tried to replicate the same issue from my end and it's giving similar error message so we'll have to dig more into this issue and will update you soon, thank you for noticing this issue I really appreciate your efforts and time. Thank you!

CC :@mattsoulanille 

Here error log output for your reference:

```
gaikwadrahul-macbookpro:test-5366 gaikwadrahul$ node index.js
/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:454
        throw new Error(typeof msg === 'string' ? msg : msg());
              ^

Error: The shape of dict['input_tensor'] provided in model.execute(dict) must be [1,-1,-1,3], but was [400,600,3]
    at Object.assert (/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:454:15)
    at /Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:31349:26
    at Array.forEach (<anonymous>)
    at GraphExecutor.checkInputShapeAndType (/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:31341:29)
    at GraphExecutor.execute (/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30855:14)
    at GraphModel.execute (/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:31913:36)
    at GraphModel.predict (/Users/gaikwadrahul/Desktop/TFJS/test-5366/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:31758:34)
    at file:///Users/gaikwadrahul/Desktop/TFJS/test-5366/index.js:9:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0
gaikwadrahul-macbookpro:test-5366 gaikwadrahul$ 
```

**Comment by playground** [comment]
Thanks @gaikwadrahul8 , I look forward to your update.  I also have this issue sitting out there for sometime https://github.com/tensorflow/tfjs/issues/7398#issuecomment-1503170942, can you please provide an update there too?

**Comment by nileshau-afk** [comment]
Hello @playground  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @playground, Thank you for your patience. We have reproduced the issue. It happens because PNG images decode with 4 channels by default (RGBA), while your model expects 3 channels (RGB). As a workaround, you can pass 3 as the second argument in your decodeImage function call to automatically strip the alpha channel. Could you please try this and let us know if it works for you?
