### ISSUE TITLE
Model.predict() behavior

### ISSUE THREAD

**Issue by axa2** [tensorflow/tfjs#537]
TensorFlow.js version: 0.12.3
Browser version: Chrome 67.0.3396.99

Hello, I'll try to be brief, if this is a non-known behavior I'll provide all the information needed to reproduce it. But if it's known, I would suggest to document it.

In my application main loop I call model.predict(...).
If later I call the resulting_tensor.data(), then model.predict takes around 10 miliseconds and tensor.data() around 300 miliseconds. So far so good.
However, if I don't call tensor.data(), and just dispose it, next time model.predict() is called, takes 300 miliseconds instead of 10 ms.

Is this expected? If so, any chance it can be documented?

```javascript
// test 1
let model = ...
let loop = () => {
    let input = tf.fromPixels(...)
    let t = model.predict(input) // 10ms
    t.data().then((data) => { // 300ms
        input.dispose()
        t.dispose()
        requestAnimationFrame(loop)
    })
}
loop()

// test 2
let model = ...
let loop = () => {
    let input = tf.fromPixels(...)
    let t = model.predict(input) // 300ms
    // use t
    input.dispose()
    t.dispose()
    requestAnimationFrame(loop)
}
loop()
```

**Comment by axa2** [comment]
Looking at the source I traced something interesting (?)

When calling tensor.data():

File: src/kernels/webgl/gpgpu_util.ts
At function downloadFloat32MatrixFromOutputTexture: line 323
At line 335:

```javascript
333  webgl_util.callAndCheck(
334      gl,
335      () => gl.readPixels(
336          0, 0, w, h, textureConfig.downloadTextureFormat, gl.FLOAT,
337          downloadTarget));
```

If gl.readPixels() is ommited, next time Model.predict() is called it takes 300ms instead of 10ms

My question again, is this somehow expected or should I provide an example program?

**Comment by justadudewhohacks** [comment]
Not sure if it helps to your question, but this kind of got me confused a while as well. At the moment you call `tensor.data()` it doesn't necessarily mean, that the graph is done executing yet. Thus the time you measure for `model.predict` might not reflect the actual execution time.

**Comment by axa2** [comment]
@justadudewhohacks,  hey! Thanks.
Now it makes sense.
I think there should be a way in the API to know what is still executing. (Listener Events?)

**Comment by bileschi** [comment]
+nsthorat for fromPixels expertise

**Comment by nsthorat** [comment]
@justadudewhohacks is correct. The time of actually calling "predict" or for that matter any ops is non-blocking. They simply enqueue programs to be run on the GPU. When you call `.data()`, that is when you introduce a sync between the CPU and the GPU, which means the timing you get after that call will be the "real" timing that it takes to execute that op.

Hope that helps.
