### ISSUE TITLE
concatenating datasets returns "this.lastRead.then is not a function"

### ISSUE THREAD

**Issue by bibs2091** [tensorflow/tfjs#5375]
**System information**
- Windows 10
- TensorFlow.js on node js
- "@tensorflow/tfjs": "^3.7.0",
    "@tensorflow/tfjs-node": "^3.7.0",
    "node-pre-gyp": "^0.17.0"

I have a tf.data.Dataset object, and i want to add a new row to that dataset, so i  created a tf.data.array and put the data in it, then tried dataset.concatenate(the_new_row)  to append the new row to the dataset, here's the code:

getting the dataset from a csv file
`
const csvDataset = (tf.data.csv(
    csvFile, {
    configuredColumnsOnly: true,
    columnConfigs: {
      user: {
        required: true,
        dtype: "float32"
      },
      movie: {
        required: true,
        dtype: "float32"
      },
      rating: {
        isLabel: true,
        dtype: "float32"
      }
    }
  })).batch(1024)
`

reshaping the original dataset
`
  const dataSet = csvDataset.map(x => ({ xs: { user: x.xs.user.reshape([-1, 1]), movie: x.xs.movie.reshape([-1, 1]) }, ys: x.ys }))
`

then trying to add a new row:
`
  let toAdd = tf.data.array([{ xs: { user: tf.tensor2d([[10]]), movie: tf.tensor2d([[10]]) }, ys: { rating: tf.tensor1d([10]) } }, ])
  `
` return dataSet.concatenate(toAdd);
`

finally when i try to print it, or train on it:
`
dataSet = the return value from the function 
`
`
dataSet.toArray().then(e => console.log(e))
`

i get the following error:
`(node:11856) UnhandledPromiseRejectionWarning: TypeError: this.lastRead.then is not a function
    at Object.<anonymous> (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:2185:47)
    at step (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:84:23)
    at Object.next (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:65:53)
    at C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:58:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:54:12)
    at Object.RowMajorBatchIterator.next (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:2178:16)
    at Object.<anonymous> (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:2280:64)
    at step (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:84:23)
    at Object.next (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-data\dist\tf-data.node.js:65:53)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)`

---

I even tried switching them
`  return toAdd .concatenate(dataSet);
`

or this:
`  return dataSet.concatenate(dataSet);
`

but ended up with the same error. Can you help me

**Comment by rthadur** [comment]
Concatenate is working as expecting , i see the problem when you try to print , please try below and let us know , thank you 
const a = tf.data.array([1, 2, 3]);
const b = tf.data.array([4, 5, 6]);
const c = a.concatenate(b);
await c.forEachAsync(e => console.log(e));

**Comment by bibs2091** [comment]
@rthadur  my case is bit different, instead of an array of integers, i have an array of objects

**Comment by rthadur** [comment]
can you please try using await c.forEachAsync(e => console.log(e)); to print the values and see , if that helps ?

**Comment by bibs2091** [comment]
i tried: 
`  await dataSet.concatenate(dataSet).forEachAsync(e => console.log(e));
`
same problem UnhandledPromiseRejectionWarning: TypeError: this.lastRead.then is not a function.

did u try to reproduce the same problem?

**Comment by rthadur** [comment]
@bibs2091 can you provide sample example for above so that i try ?

**Comment by bibs2091** [comment]
yes, here is an example edited from the tfjs docs:

```
const csvUrl =
'https://storage.googleapis.com/tfjs-examples/multivariate-linear-regression/data/boston-housing-train.csv';

async function run() {
   // We want to predict the column "medv", which represents a median value of
   // a home (in $1000s), so we mark it as a label.
   const csvDataset = tf.data.csv(
     csvUrl, {
       columnConfigs: {
         medv: {
           isLabel: true
         }
       }
     });

   // Number of features is the number of column names minus one for the label
   // column. 
   const numOfFeatures = (await csvDataset.columnNames()).length - 1;

   // Prepare the Dataset for training.
   const flattenedDataset =
     csvDataset
     .map(({xs, ys}) =>
       {
         // Convert xs(features) and ys(labels) from object form (keyed by
         // column name) to array form.
         return {xs:Object.values(xs), ys:Object.values(ys)};
       })
     .batch(10);
		
  	await flattenedDataset.concatenate(flattenedDataset).forEachAsync(e => console.log(e));
}

await run();
```

it return the same problem this.lastRead.then is not a function

**Comment by rthadur** [comment]
you need to first convert the dataset to tf.dataset.array then concatenate , I see a related issue in sf here https://stackoverflow.com/questions/61122054/loading-a-csv-to-perform-inference-in-tensorflow-js , please check , I do not see any issue with concatenate function.
cc @pyu10055

**Comment by bibs2091** [comment]
Hello @rthadur, i have been trying solutions for the past days and i couldn't, can you please show me a code snippet of how to work this out? the sf link wasn't related.

here's also a code that doesn't work:

```
csvUrl = 'https://storage.googleapis.com/tfjs-examples/multivariate-linear-regression/data/boston-housing-train.csv';
const a = tf.data.csv(
  csvUrl, {
    columnConfigs: {
      medv: {
        isLabel: true
      }
    }
  });
const b = tf.data.array([4, 5, 6]);
const c = a.concatenate(b);
await c.forEachAsync(e => console.log(e));
```
i still get the same error

**Comment by bibs2091** [comment]
@lina128 that's awesome my issue has been resolved, can you please tell me how to install the tf version with this PR with npm?

**Comment by jinjingforever** [comment]
@bibs2091 I think we will probably do a new release soon. In the meantime, you can try building it yourself:

```
$ cd tfjs-data
$ yarn
$ yarn build-deps
$ yarn build-npm
```

Then you can find the bundles (`tf-data.js`, `tf-data.min.js`, etc) in `tfjs-data/dist`. 

Thank you!
