### ISSUE TITLE
undefined, null instanceof Tensor throws Exception

### ISSUE THREAD

**Issue by justadudewhohacks** [tensorflow/tfjs#538]
#### Code to reproduce the bug
`undefined instanceof tf.Tensor` or `null instanceof tf.Tensor`

#### tfjs-core version 11.9
returns `false`

#### tfjs-core version 12.5
throws: `'Cannot read property 'shape' of undefined'`

**Comment by bileschi** [comment]
Should be a pretty simple fix.  Just need to update the `hasInstance` definition here to short-circuit to false if instance is undefined or null

https://github.com/tensorflow/tfjs-core/blob/master/src/tensor.ts#L1170
