### ISSUE TITLE
Predict data from a collection to determine a single object with the most used data

### ISSUE THREAD

**Issue by GlauberF** [tensorflow/tfjs#5380]
**System information**
- Linux Ubuntu 16.04
- TensorFlow Lite JS

**Description** 
I need to start from a set of objects, define a single object, with the most used data among the javascript object collection informed.

**Example of set of objects:**
```javascript
[{
    name: "Pedro",
    product: "Caneta"
}, {
    name: "Ana",
    product: "Caderno"
}, {
    name: "Maria",
    product: "Boracha"
}, {
    name: "Pedro",
    product: "Caneta"
}, {
    name: "Pedro",
    product: "Caneta"
}]
```

**Single object with the most used values in the above collections:**
```javascript
{
    name: "Pedro",
    product: "Caneta"
}
```

That's what I need, based on the javascript collections array you can see that the most used information for the fields (name and product), were `name: "Pedro"` and `product: "Caneta"`.
That kind of analysis I need.

What function or how could I do this using tensorflow javascript, if you have any examples I'm very grateful, because I'm new to this.

**Comment by rthadur** [comment]
This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) with tag tfjs since it is not a bug or feature request. There is also a larger community that reads questions there.
