### ISSUE TITLE
Unsupported Ops in the model before optimization UnsortedSegmentSum, RightShift, LeftShift

### ISSUE THREAD

**Issue by moono** [tensorflow/tfjs#5387]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): tensorflowjs==3.8.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
* I tried to convert pretrained tensorflow model from [here](https://github.com/soCzech/TransNetV2/tree/master/inference) to tfjs, but I get following error,
`ValueError: Unsupported Ops in the model before optimization
UnsortedSegmentSum, RightShift, LeftShift`
* So I used `--skip_op_check` option and converted as tfjs successfully, but when I run it on browser , I get following error.
  * with `webgl` backend: `Error: spaceToBatchND for rank > 4 with a WebGL backend not implemented yet`
  * with `cpu` backend: `TypeError: Unknown op 'LeftShift'`

**Will this change the current api? How?**
* The ops that stated above can be handled.

**Who will benefit with this feature?**
* Anyone who uses tfjs

**Any Other info.**
Thank you for this great work. 🙏 🙏

**Comment by rthadur** [comment]
@moono will you be interested in contributing ? if yes here are the guidelines https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md thank you

**Comment by gaikwadrahul8** [comment]
Hi, @moono 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I see we have implemented [tf.unsortedSegmentSum](https://js.tensorflow.org/api/latest/#unsortedSegmentSum) but it seems like we haven't implemented `RightShift`, `LeftShift` so May I know are you still looking to add those Ops in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
