### ISSUE TITLE
TFJS converter unsupported Ops "BatchMatMul"

### ISSUE THREAD

**Issue by Jylomaki** [tensorflow/tfjs#539]
Hello,
I was trying to export a model from tf to tfjs, but I run into this error with tfjs 0.5.2:

```
Multensorflowjs_converter --input_format=tf_saved_model
 --output_node_names='frozen_graph/my_model/full_output'
 --saved_model_tags=serve 
./tests/model_freezing/model_pipe_frozen/a2018-07-24_13-49-43/
./tests/export_tfjs


> Unsupported Ops in the model
BatchMatMul
```
It seems the op that create this issue is this one:
`tf.matmul(point_batch, mat_batch)`
The model work just fine in python.

The node is created by a `tf.Matmul`, and this op is said to be handled by tfjs converter.

**Comment by Jylomaki** [comment]
I made a workaround using:
```
def mult(mat):
            return tf.matmul(face_batch[0],mat)
multiplied = tf.map_fn(mult,mat_batch)
```
But it would still be nice to have this op handled.

**Comment by loretoparisi** [comment]
@Jylomaki good solution! I'm having the same issue with other operations like`MatrixBandPart, RandomShuffleQueueV2, QueueDequeueManyV2, BatchMatMul`. Any idea for these ones?

**Comment by Jylomaki** [comment]
Well I don't use those ops, so I quite know about those.

It won't fix your problem but have you made an issue about this? It seems, the op they handle implement are the ones asked by people.

**Comment by chrisdonahue** [comment]
I'm not sure if this is covered by this issue, but it would be nice if TFjs `matmul` behaved in the same way as the [Tensorflow `matmul`](https://www.tensorflow.org/api_docs/python/tf/matmul), which generalizes the operation to tensors of arbitrary dimensions:

> Multiplies matrix a by matrix b, producing a * b.
> The inputs must, following any transpositions, be tensors of rank >= 2 where the inner 2 dimensions specify valid matrix multiplication arguments, and any further outer dimensions match.

**Comment by dsmilkov** [comment]
Great point @chrisdonahue . Will keep this issue to track two things
1) generalizing tf.matMul in tfjs-core
2) Wiring the BatchMatMul op in the tfjs-converter to call the generalized tf.matMul() in core.

**Comment by chrisdonahue** [comment]
Awesome!! Thx so much

**Comment by tehZevo** [comment]
Been looking for a way to cleanly batch-matmul, thanks so much for this!

**Comment by loretoparisi** [comment]
just to add that `BatchMatMul` is fundamental to support layers for GRU, seq2seq, transformers, etc!

**Comment by pyu10055** [comment]
this op has been added.
