### ISSUE TITLE
[webgl] Bazel build includes tfjs-core

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#5398]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**
bundle size of webgl backend increased 1MB due to including tfjs-core files, there maybe also has a risk that we use different version of tfjs-core in one APP.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`cd tfjs-backend-webgl && yarn && yarn build`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
 ls -lh ../dist/bin/tfjs-backend-webgl/dist/tf-backend-webgl.js
-r--r--r-- 1 yf Domain Users 1.9M Jul 28 10:09 ../dist/bin/tfjs-backend-webgl/dist/tf-backend-webgl.js
```

**Comment by mattsoulanille** [comment]
We likely need to mark tfjs-core as external in the tfjs_web_bundle rule. I'm OOO today, but I can take a look on Monday. Thanks for catching this!
