### ISSUE TITLE
Generate table of op support and their backend implementation status

### ISSUE THREAD

**Issue by jasonmayes** [tensorflow/tfjs#5401]
As discussed, it would be very valuable to the community to have a point of reference somewhere for a table that summarizes all supported TFJS ops and on which backends each has been implemented or not, and if so, if that is full or partial support.

Something like this:

```
Op Name   |   JS   |   WASM   |   WebGL   |   React Native   |   Node.js   |   WebGPU   |   etc...
----------------------------------------------------------------------------------------------------
Relu           |  Yes   |   Partial   |      Yes       |           Yes          |      Yes       |         No       |    No
```

This would help requests like this to be able to identify the offending op:

https://discuss.tensorflow.org/t/weird-output-with-tfjs-on-wasm-backend-with-no-warnings/3326

**Comment by vladmandic** [comment]
@jinjingforever @rthadur why not dynamically generate document as part of release process?  
here's a simple gist that generates html table with format similar to one you've shared on google docs:  
<https://gist.github.com/vladmandic/fc5ac32235c4c76e0992dab2260d10b1>

**Comment by jinjingforever** [comment]
@vladmandic Thanks for the gist! We actually have an app script (similar to yours) embedded in the spreadsheet above that generates the content automatically. But your gist seems to be a better way to be integrated with the build/release process. I will discuss with the team about this. Thank you!

**Comment by rthadur** [comment]
Thank you @vladmandic , this is very useful.

**Comment by vladmandic** [comment]
btw, here's a live link on git pages: <https://vladmandic.github.io/tfjs-utils/src/kernels.html>

**Comment by jinjingforever** [comment]
@vladmandic this is awesome! Thank you!

**Comment by gyagp** [comment]
Question on kernel "FromPixels": Now it's implemented in WebGL and WebGPU backends, but the rest implementation is in tfjs-core (with some level of duplication in ). Why not make its implementation as normal as other kernels (i.e., in backends rather than in core)?

**Comment by jinjingforever** [comment]
@gyagp I think there is some historical reason behind this, but @pyu10055 might have more context on this.

**Comment by rthadur** [comment]
Closing this issue as the document is linked in [README](https://github.com/tensorflow/tfjs#various-ops-supported-in-different-backends).MD. Thank you
