### ISSUE TITLE
hub.kerasLayer support

### ISSUE THREAD

**Issue by jonathanlawhh** [tensorflow/tfjs#5409]
**System information**
- TensorFlow.js version (you are using): tfjs@2.0.0
- Are you willing to contribute it (Yes/No): Yes, however I do not have in depth knowledge of the inner workings of TF yet. Definitely would be happy to help out in testing.

**TensorflowJS converted model throwing “Cannot read property ‘producer’ of undefined” error**
[https://discuss.tensorflow.org/t/tensorflowjs-converted-model-throwing-cannot-read-property-producer-of-undefined-error/3132](https://discuss.tensorflow.org/t/tensorflowjs-converted-model-throwing-cannot-read-property-producer-of-undefined-error/3132)

The above issue is thrown when trying to load a model converted from:
https://www.tensorflow.org/text/tutorials/classify_text_with_bert

**Will this change the current api? How?**

**Who will benefit with this feature?**
People training models from TF Hub and converting it to TFJS for browser usage.

**Any Other info.**

**Comment by rthadur** [comment]
please check this tutorial as how to train and convert to tfjs for above model https://alexfi.dev/blog/tensorflowjs-bert-train.
