### ISSUE TITLE
With tfjs+tjfs-node, Error: Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by DABH** [tensorflow/tfjs#541]
#### TensorFlow.js version
0.12.3

#### Browser version
Node.js 10.6

#### Describe the problem or feature request
I'm trying to use tfjs with the CPU Node.js backend (tjfs-node), but when I do, I get errors like
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext 
```
from the `jsdom` module (which I guess `tfjs` depends on?).  If I add something like
```
HTMLCanvasElement.prototype.getContext = () => {};
```
to my code before importing any tf stuff, the error goes away, but that's rather hacky.  I don't care about running in the browser, I just want to run with the Node backend / from my terminal (no canvas) -- is there a way to prevent this error, and/or prevent tfjs from trying to do canvas/browser stuff when I'm in the terminal?  Thanks!

#### Code to reproduce the bug / link to feature request

```
import * as tf from '@tensorflow/tfjs';

// Node CPU backend
import '@tensorflow/tfjs-node';
```

**Comment by nkreeger** [comment]
@DABH is this related to https://github.com/tensorflow/tfjs/issues/540 ?

**Comment by DABH** [comment]
Potentially -- it is another error I'm getting with the same setup, but not sure if the root cause is the same or not.  (Is jsdom etc. only invoked from the webgl backend?)  Feel free to close and track just under #540 if you prefer :)

**Comment by DABH** [comment]
I've been investigating this further and am concluding the cause is basically the same as #540 -- I'll post my findings there in a bit.  Thanks!
