### ISSUE TITLE
Argument 'tensors[0]' passed to 'concat' must be a Tensor or TensorLike, but got 'null'

### ISSUE THREAD

**Issue by RJ-1998** [tensorflow/tfjs#5410]
I am trying to predict the results from the converted python keras model into tensorflow js, I have tried a lot of possible combinations to get the answer but it keeps throwing this error. The input shape it expects is [null,7] which I am providing it but still not working :-( Any help would be appreciated. Below is model and it's summary.
```
model = Sequential()        
model.add(Embedding(self.vocab_length, embed_dim, input_length=self.maxlen))
model.add(Flatten())
model.add(Dense(32,activation="relu"))
model.add(Dense(self.output_dim,activation="softmax"))  
# compile the model      
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(
    learning_rate=0.01, momentum=0.0, nesterov=False, name='SGD'), metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding_2 (Embedding)      (None, 7, 20)             1320      
_________________________________________________________________
flatten_2 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 32)                4512      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                330       
=================================================================
Total params: 6,162
Trainable params: 6,162
Non-trainable params: 0
```

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by RJ-1998** [comment]
Hello @rthadur ! Thanks for replying to my issue. Please find this [repo](https://github.com/RJ-1998/react-chatbot-nlp) containing all the code and model.json file whch I am using.

**Comment by rthadur** [comment]
I see this error while running the above code 

![image](https://user-images.githubusercontent.com/43972606/128782258-c9949d81-e7f0-424c-bbbf-bfee74c970d2.png)

can you please resolve this and also load the model from local folder like this 

`$( document ).ready(async function () {
	$('.progress-bar').show();
    console.log( "Loading model..." );
    model = await tf.loadGraphModel('model/model.json');
    console.log( "Model loaded." );
	$('.progress-bar').hide();
});`

**Comment by RJ-1998** [comment]
@rthadur I am using a cors extension in my browser and turning CORS extension on solves this error. You can use this extension in firefox [cors](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/)

**Comment by rthadur** [comment]
Same error please check below 
![image](https://user-images.githubusercontent.com/43972606/128928195-213bc4b4-be8f-4c67-9d5a-eb5d9bc6b81e.png)

**Comment by RJ-1998** [comment]
@rthadur Please check the following steps:-
1. In the parent directory run **npm install** it has libraries to run express server
2. Make sure you are able to open http://localhost:4001/static/model.json
3. Turn on cors.
If still not working please find below snapshot of the main error in tensorflow 
![Screenshot from 2021-08-11 22-31-11](https://user-images.githubusercontent.com/37022742/129071899-58421545-5945-4ffb-97fa-297aae1f6b1f.png)

**Comment by RJ-1998** [comment]
Hey Guys. Any updates on the issue?

**Comment by lina128** [comment]
Hi @RJ-1998 , why don't you pass in model from loadLayersModel directly in this line? https://github.com/RJ-1998/react-chatbot-nlp/blob/bf8680b120452979c2c7ff450feb7549864a4070/chatbot/src/App.js#L15

**Comment by RJ-1998** [comment]
Thanks @lina128 it worked!! Actually I was following one article that suggested the other way. I wish I knew it before.
