### ISSUE TITLE
Support for `ReverseSequence` in `tensorflowjs_converter`

### ISSUE THREAD

**Issue by cjbayron** [tensorflow/tfjs#5413]
Hi, I'm getting following error when trying to use `tensorflowjs_converter` to convert a Bidirectional LSTM-CRF model that uses the [CRF from TensorFlow addons](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/CRF):

Command:
```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model <tf_model> <tfjs_model>
```

Output:
```
tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 154, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
ReverseSequence
```
Can `tensorflowjs_converter` please support this operation? Thanks!

**Comment by gaikwadrahul8** [comment]
Hi, @cjbayron 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and it seems like we haven't implemented `ReverseSequence` Op yet if I'm not wrong so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
