### ISSUE TITLE
Error when dynamically importing tf.js from browser console

### ISSUE THREAD

**Issue by bearzx** [tensorflow/tfjs#543]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.0
#### Browser version
Chrome Version 67.0.3396.99 (Official Build) (64-bit) macOS
#### Describe the problem or feature request
When I tried to import tf.js using the import() function that chrome provides in the chrome console, an error occurred saying:
```
tfjs@0.12.0:2 Uncaught (in promise) TypeError: Cannot read property 'tf' of undefined
    at tfjs@0.12.0:2
    at tfjs@0.12.0:2
```
I then checked the tf.js source and see at the loading stage it has:
```javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (factory((global.tf = global.tf || {})));
}(this, (function (exports) { 'use strict';
...
// actual tf.js implementation
...
```
So apparently in a promise-based dynamic loading `this` is `undefined` instead of the `window` object. Simply change `this` to `window` on the last line will do the trick, but I guess that'll break in some other scenarios.
#### Code to reproduce the bug / link to feature request
Simply run `import('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.12.0').then((tf) => {})` in your chrome console.

**Comment by bileschi** [comment]
I've not had success using the `import` command from directly in the JS console.  

In the mean time, does the following workaround work for you?
```
var script = document.createElement("script");
script.type = 'text/javascript';
script.src = 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest';
document.head.appendChild(script);
```

**Comment by bearzx** [comment]
yeah I think this'll work, since the real problem seems to be the `this` context when tf is being loaded. Using the `<script>` tag method will make `this` to be the `window` object. But in the dynamic `import()` case `this` will be `undefined` before the importing Promise is resolved.

**Comment by bileschi** [comment]
Marking as closed.  Please reopen if this is still an issue.

**Comment by harsha7addanki** [comment]
not working for me!

**Comment by bileschi** [comment]
I just tried this in chrome and it appeared to work. Can you offer a more complete bug report?  Thanks.
