### ISSUE TITLE
MoveNet predictions are not being drawn at the right position on a custom sized camera

### ISSUE THREAD

**Issue by Sabit-Ahmed** [tensorflow/tfjs#5433]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).
What about the custom camera width and height? (Referring to this link: https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx)
If I try to use other value for camera height and width, model results are not showing properly. Which is dependent on which, it is so confusing.

Dependencies:
    "@mediapipe/pose": "^0.4.1624666670",
    "@react-native-community/async-storage": "^1.12.1",
    "@tensorflow-models/blazeface": "^0.0.7",
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow-models/pose-detection": "^0.0.3",
    "@tensorflow-models/posenet": "^2.2.2",
    "@tensorflow/tfjs": "^3.6.0",
    "@tensorflow/tfjs-react-native": "^0.5.0",
    "expo": "~41.0.1",
    "expo-camera": "^11.0.3",
    "expo-file-system": "^11.0.2",
    "expo-gl": "^10.2.0",
    "expo-gl-cpp": "^10.1.0",
    "expo-image-manipulator": "^9.1.0",
    "expo-image-picker": "^10.1.4",
    "expo-permissions": "^12.0.1",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "jasmine-core": "^3.7.1",
    "jpeg-js": "^0.4.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "^12.1.1",
    "react-native-unimodules": "^0.13.3",
    "react-native-web": "~0.13.12",
    "rn-fetch-blob": "^0.12.0"

![image_1](https://user-images.githubusercontent.com/27894159/128227614-059c7845-78bd-4dad-a4b6-ddbf383eafe6.png)
![image_2](https://user-images.githubusercontent.com/27894159/128227700-024835fa-d9e7-4835-bf75-577c98e9b6c2.png)

For the first image, parameters used:
inputTensorHeight: 200,
inputTensorWidth: 152,
cameraTextureHeight: 1200,
cameraTextureWidth: 1600,
cameraContainerHeight: 300,
cameraContainerWidth: 400,
modelResultsContainerHeght: 300,
modelResultsContainerWidth: 400

Exactly as the demo app in the link above.
But when I tried to change the camera shape, the output is not satisfactory:
inputTensorHeight: 200,
inputTensorWidth: 152,
cameraTextureHeight: 1200,
cameraTextureWidth: 1600,
cameraContainerHeight: '100%',
cameraContainerWidth: '100%',
modelResultsContainerHeght: '100%',
modelResultsContainerWidth: '100%'

**Comment by Sabit-Ahmed** [comment]
@tafsiri sorry to bother you, could you please look at it?

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Sabit-Ahmed** [comment]
**For first image:**   


    import React from 'react';
    import * as tf from '@tensorflow/tfjs';
    import '@tensorflow/tfjs-react-native';
    import {ActivityIndicator, Platform, SafeAreaView, StyleSheet, Text, TouchableHighlight, View} from 'react-native';
    import AsyncStorage from "@react-native-community/async-storage";
    import * as svgComponents from 'react-native-svg';
    import * as Permissions from 'expo-permissions';
    import {Camera} from 'expo-camera';
    import {ExpoWebGLRenderingContext} from 'expo-gl';
    import {cameraWithTensors} from '@tensorflow/tfjs-react-native';
    import * as poseNet from '@tensorflow-models/pose-detection';


    const BACKEND_TO_USE = 'rn-webgl';

    interface AppState {
        isTfReady: boolean;
        hasCameraPermission?: boolean;
        cameraType: any;
        isLoading: boolean;
        poseNetModel?: any;
        pose?: poseNet.Pose;
        skippedFrame: number,
        faceDetector?: any;
        modelName: string;
        totalPositionCount: number;
        isPosition: boolean;
        isFirstTime: boolean;
    }

    let squatCount = 0;
    let model;
    let modelType;
    const inputTensorWidth = 152;
    const inputTensorHeight = 200;
    const AUTO_RENDER = true;
    const TensorCamera = cameraWithTensors(Camera);

    class App extends React.Component<{}, AppState> {
        rafID?: number;

        constructor(props: {}) {
            super(props);
            this.state = {
                isTfReady: false,
                isLoading: true,
                cameraType: Camera.Constants.Type.front,
                modelName: 'moveNet',
                skippedFrame: 0,
                totalPositionCount: 0,
                isPosition: false,
                isFirstTime: true,
                poseNetModel: poseNet.SupportedModels.MoveNet,
            };
            this.handleImageTensorReady = this.handleImageTensorReady.bind(this);
        }

        async loadPoseNetModel() {
            model = poseNet.SupportedModels.MoveNet;
            modelType = poseNet.movenet.modelType.SINGLEPOSE_LIGHTNING;
            return await poseNet.createDetector(model, { modelType: modelType });
        }


        async handleImageTensorReady(
            images: IterableIterator<tf.Tensor3D>,
            updatePreview: () => void, gl: ExpoWebGLRenderingContext) {
            const loop = async () => {
                const {modelName} = this.state;
                if (!AUTO_RENDER) {
                    updatePreview();
                }

                if (modelName === 'moveNet') {
                    if (this.state.poseNetModel != null) {
                        let pose;
                        const imageTensor = images.next().value;
                        const flipHorizontal = Platform.OS !== 'ios';
                        const poses = await this.state.poseNetModel.estimatePoses(imageTensor, {
                            maxPoses: 1, //When maxPoses = 1, a single pose is detected
                            flipHorizontal: flipHorizontal
                        });
                        pose = poses[0];
                        // console.log(pose.keypoints)
                        this.setState({pose});
                        tf.dispose([imageTensor]);
                        this.setState({
                            isFirstTime: false
                        })
                        
                    }
                }

                if (!AUTO_RENDER) {
                    gl.endFrameEXP();
                }
                this.rafID = requestAnimationFrame(loop);

            };
            await loop();
        }


        async componentWillUnmount() {
            if (this.rafID) {
                cancelAnimationFrame(this.rafID);
            }
        }

        async componentDidMount() {
            await tf.setBackend(BACKEND_TO_USE);
            await tf.ready();
            const {status} = await Permissions.askAsync(Permissions.CAMERA);
            const [poseNetModel] = await Promise.all([this.loadPoseNetModel()]);
            this.setState({
                isTfReady: true,
                hasCameraPermission: status === 'granted',
                isLoading: false,
                poseNetModel,
            });
        }


        clearSquatCount() {
            // DO SOMETHING
        }

        switchCamera() {
            let type;

            if (this.state.cameraType === Camera.Constants.Type.front) {
                type = Camera.Constants.Type.back;
            } else {
                type = Camera.Constants.Type.front;
            }
            this.setState({cameraType: type});
        }


        renderPose() {
            const MIN_KEYPOINT_SCORE = 0.2;
            const {pose} = this.state;
            if (pose != null) {
                const keypoints = pose?.keypoints
                    .filter(k => k?.score > MIN_KEYPOINT_SCORE)
                    .map((k, i) => {
                        return <svgComponents.Circle
                            key={`skeletonkp_${i}`}
                            cx={k.x}
                            cy={k.y}
                            r='2'
                            strokeWidth='0'
                            fill='blue'
                        />;
                    });


                const adjacentKeyPoints = poseNet.util.getAdjacentPairs(model);
                const skeleton = adjacentKeyPoints?.map(([i, j]) => {
                    const kp1 = pose.keypoints[i];
                    const kp2 = pose.keypoints[j]; // If score is null, just show the keypoint.
                    const score1 = kp1?.score != null ? kp1?.score : 1;
                    const score2 = kp2?.score != null ? kp2?.score : 1;
                    const scoreThreshold = MIN_KEYPOINT_SCORE || 0;
        
                    if (score1 >= scoreThreshold && score2 >= scoreThreshold) {
                        return <svgComponents.Line
                            key={`skeletonls_${i}${j}`}
                            x1={kp1.x}
                            y1={kp1.y}
                            x2={kp2.x}
                            y2={kp2.y}
                            stroke='white'
                            strokeWidth='2'
                        />;
                    }
                });


                return <svgComponents.Svg height='100%' width='100%' scaleX={-1} scaleY={1}
                                        viewBox={`0 0 ${inputTensorWidth} ${inputTensorHeight}`}>
                    {skeleton}
                    {keypoints}
                    <svgComponents.Text
                        stroke="white"
                        fill="white"
                        fontSize="30"
                        fontWeight="bold"
                        x="80"
                        y="30"
                        textAnchor="middle"
                    >
                        {squatCount}
                    </svgComponents.Text>


                </svgComponents.Svg>;
            } else {
                return null;
            }
        }


        render() {
            const {isLoading, modelName} = this.state;

            // TODO File issue to be able get this from expo.
            // Caller will still need to account for orientation/phone rotation changes
            let textureDims: { width: number; height: number; };
            if (Platform.OS === 'ios') {
                textureDims = {
                    height: 1920,
                    width: 1080,
                };
            } else {
                textureDims = {
                    height: 1200,
                    width: 1600,
                };
            }

            const camView = <View style={styles.cameraContainer}>
                <View style={styles.cameraInnerContainer}>
                    <TensorCamera
                        // Standard Camera props
                        style={styles.camera}
                        type={this.state.cameraType}
                        zoom={0}
                        ratio={'4:3'}
                        // tensor related props
                        cameraTextureHeight={textureDims.height}
                        cameraTextureWidth={textureDims.width}
                        resizeHeight={inputTensorHeight}
                        resizeWidth={inputTensorWidth}
                        resizeDepth={3}
                        onReady={this.handleImageTensorReady}
                        autorender={AUTO_RENDER}
                    />
                    <View style={styles.modelResults}>
                        {modelName === 'moveNet' ? this.renderPose() : null}
                    </View>
                </View>

                <TouchableHighlight
                    style={styles.flipCameraBtn}
                    onPress={() => {
                        this.switchCamera();
                    }}
                    underlayColor='#FFDE03'>
                    <Text style={styles.textStyle}>
                        FLIP CAMERA
                    </Text>

                </TouchableHighlight>
                <TouchableHighlight
                    style={styles.resetBtn}
                    onPress={() => {
                        this.clearSquatCount();
                    }}
                    underlayColor='#FFDE03'>
                    <Text style={styles.textStyle}>
                        RESTART
                    </Text>

                </TouchableHighlight>
            </View>;

            return (
                <SafeAreaView style={styles.body}>

                    {
                        isLoading ?
                            <View style={styles.loadingIndicator}>
                                <ActivityIndicator size='large' color='#FF0266'/>
                            </View>
                            :
                            camView
                    }

                </SafeAreaView>
            );
        }
    }

    const styles = StyleSheet.create({
        body: {
            backgroundColor: 'white',
            width: '100%',
            height: '100%'
        },
        logoStyle: {
            alignItems: 'center',
            marginTop: 50,
            zIndex: 1
        },
        loadingIndicator: {
            position: 'relative',
            marginTop: 150,
            alignItems: 'center',
            zIndex: 200
        },
        cameraContainer: {
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            height: '100%',
            backgroundColor: '#fff',
        },

        cameraInnerContainer: {
            position: 'relative',
            flex: 1,
            width: '100%',
        },
        camera: {
            // position: 'absolute',
            left: 45,
            top: 40,
            width: 300,
            height: 400,
            // zIndex: 1,
            borderWidth: 1,
            borderColor: 'red',
            // borderRadius: 0,
        },
        modelResults: {
            position: 'absolute',
            left: 45,
            top: 40,
            width: 300,
            height: 400,
            zIndex: 20000,
            borderWidth: 1,
            borderColor: 'black',
            borderRadius: 0,
        },
        textStyle: {
            fontSize: 16,
            color: 'white',
        },
        flipCameraBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            justifyContent: 'center',

            alignItems: 'center',
            borderColor: 'blue'
        },
        resetBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            justifyContent: 'center',

            alignItems: 'center',
            borderColor: 'blue'
        },
        idealFrameBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            marginVertical: 10,
            justifyContent: 'center',
            alignItems: 'center',
            borderColor: 'blue'
        },

    });

    export default App


**For second image:** 


    import React from 'react';
    import * as tf from '@tensorflow/tfjs';
    import '@tensorflow/tfjs-react-native';
    import {ActivityIndicator, Platform, SafeAreaView, StyleSheet, Text, TouchableHighlight, View} from 'react-native';
    import AsyncStorage from "@react-native-community/async-storage";
    import * as svgComponents from 'react-native-svg';

    import * as Permissions from 'expo-permissions';
    import {Camera} from 'expo-camera';
    import {ExpoWebGLRenderingContext} from 'expo-gl';
    import {cameraWithTensors} from '@tensorflow/tfjs-react-native';
    import * as poseNet from '@tensorflow-models/pose-detection';


    const BACKEND_TO_USE = 'rn-webgl';

    interface AppState {
        isTfReady: boolean;
        hasCameraPermission?: boolean;
        cameraType: any;
        isLoading: boolean;
        poseNetModel?: any;
        pose?: poseNet.Pose;
        skippedFrame: number,
        faceDetector?: any;
        modelName: string;
        totalPositionCount: number;
        isPosition: boolean;
        isFirstTime: boolean;
    }

    let squatCount = 0;
    let model;
    let modelType;
    const inputTensorWidth = 152;
    const inputTensorHeight = 200;
    const AUTO_RENDER = true;
    const TensorCamera = cameraWithTensors(Camera);

    class App extends React.Component<{}, AppState> {
        rafID?: number;

        constructor(props: {}) {
            super(props);
            this.state = {
                isTfReady: false,
                isLoading: true,
                cameraType: Camera.Constants.Type.front,
                modelName: 'moveNet',
                skippedFrame: 0,
                totalPositionCount: 0,
                isPosition: false,
                isFirstTime: true,
                poseNetModel: poseNet.SupportedModels.MoveNet,
            };
            this.handleImageTensorReady = this.handleImageTensorReady.bind(this);
        }

        async loadPoseNetModel() {
            model = poseNet.SupportedModels.MoveNet;
            modelType = poseNet.movenet.modelType.SINGLEPOSE_LIGHTNING;
            return await poseNet.createDetector(model, { modelType: modelType });
        }


        async handleImageTensorReady(
            images: IterableIterator<tf.Tensor3D>,
            updatePreview: () => void, gl: ExpoWebGLRenderingContext) {
            const loop = async () => {
                const {modelName} = this.state;
                if (!AUTO_RENDER) {
                    updatePreview();
                }

                if (modelName === 'moveNet') {
                    if (this.state.poseNetModel != null) {
                        let pose;
                        const imageTensor = images.next().value;
                        const flipHorizontal = Platform.OS !== 'ios';
                        const poses = await this.state.poseNetModel.estimatePoses(imageTensor, {
                            maxPoses: 1, //When maxPoses = 1, a single pose is detected
                            flipHorizontal: flipHorizontal
                        });
                        pose = poses[0];
                        // console.log(pose.keypoints)
                        this.setState({pose});
                        tf.dispose([imageTensor]);
                        this.setState({
                            isFirstTime: false
                        })
                        
                    }
                }

                if (!AUTO_RENDER) {
                    gl.endFrameEXP();
                }
                this.rafID = requestAnimationFrame(loop);

            };
            await loop();
        }


        async componentWillUnmount() {
            if (this.rafID) {
                cancelAnimationFrame(this.rafID);
            }
        }

        async componentDidMount() {
            await tf.setBackend(BACKEND_TO_USE);
            await tf.ready();
            const {status} = await Permissions.askAsync(Permissions.CAMERA);
            const [poseNetModel] = await Promise.all([this.loadPoseNetModel()]);
            this.setState({
                isTfReady: true,
                hasCameraPermission: status === 'granted',
                isLoading: false,
                poseNetModel,
            });
        }


        clearSquatCount() {
            // DO SOMETHING
        }

        switchCamera() {
            let type;

            if (this.state.cameraType === Camera.Constants.Type.front) {
                type = Camera.Constants.Type.back;
            } else {
                type = Camera.Constants.Type.front;
            }
            this.setState({cameraType: type});
        }


        renderPose() {
            const MIN_KEYPOINT_SCORE = 0.2;
            const {pose} = this.state;
            if (pose != null) {
                const keypoints = pose?.keypoints
                    .filter(k => k?.score > MIN_KEYPOINT_SCORE)
                    .map((k, i) => {
                        return <svgComponents.Circle
                            key={`skeletonkp_${i}`}
                            cx={k.x}
                            cy={k.y}
                            r='2'
                            strokeWidth='0'
                            fill='blue'
                        />;
                    });


                const adjacentKeyPoints = poseNet.util.getAdjacentPairs(model);
                const skeleton = adjacentKeyPoints?.map(([i, j]) => {
                    const kp1 = pose.keypoints[i];
                    const kp2 = pose.keypoints[j]; // If score is null, just show the keypoint.
                    const score1 = kp1?.score != null ? kp1?.score : 1;
                    const score2 = kp2?.score != null ? kp2?.score : 1;
                    const scoreThreshold = MIN_KEYPOINT_SCORE || 0;
        
                    if (score1 >= scoreThreshold && score2 >= scoreThreshold) {
                        return <svgComponents.Line
                            key={`skeletonls_${i}${j}`}
                            x1={kp1.x}
                            y1={kp1.y}
                            x2={kp2.x}
                            y2={kp2.y}
                            stroke='white'
                            strokeWidth='2'
                        />;
                    }
                });


                return <svgComponents.Svg height='100%' width='100%' scaleX={-1} scaleY={1}
                                        viewBox={`0 0 ${inputTensorWidth} ${inputTensorHeight}`}>
                    {skeleton}
                    {keypoints}
                    <svgComponents.Text
                        stroke="white"
                        fill="white"
                        fontSize="30"
                        fontWeight="bold"
                        x="80"
                        y="30"
                        textAnchor="middle"
                    >
                        {squatCount}
                    </svgComponents.Text>


                </svgComponents.Svg>;
            } else {
                return null;
            }
        }


        render() {
            const {isLoading, modelName} = this.state;

            // TODO File issue to be able get this from expo.
            // Caller will still need to account for orientation/phone rotation changes
            let textureDims: { width: number; height: number; };
            if (Platform.OS === 'ios') {
                textureDims = {
                    height: 1920,
                    width: 1080,
                };
            } else {
                textureDims = {
                    height: 1200,
                    width: 1600,
                };
            }

            const camView = <View style={styles.cameraContainer}>
                <View style={styles.cameraInnerContainer}>
                    <TensorCamera
                        // Standard Camera props
                        style={styles.camera}
                        type={this.state.cameraType}
                        zoom={0}
                        ratio={'4:3'}
                        // tensor related props
                        cameraTextureHeight={textureDims.height}
                        cameraTextureWidth={textureDims.width}
                        resizeHeight={inputTensorHeight}
                        resizeWidth={inputTensorWidth}
                        resizeDepth={3}
                        onReady={this.handleImageTensorReady}
                        autorender={AUTO_RENDER}
                    />
                    <View style={styles.modelResults}>
                        {modelName === 'moveNet' ? this.renderPose() : null}
                    </View>
                </View>

                <TouchableHighlight
                    style={styles.flipCameraBtn}
                    onPress={() => {
                        this.switchCamera();
                    }}
                    underlayColor='#FFDE03'>
                    <Text style={styles.textStyle}>
                        FLIP CAMERA
                    </Text>

                </TouchableHighlight>
                <TouchableHighlight
                    style={styles.resetBtn}
                    onPress={() => {
                        this.clearSquatCount();
                    }}
                    underlayColor='#FFDE03'>
                    <Text style={styles.textStyle}>
                        RESTART
                    </Text>

                </TouchableHighlight>
            </View>;

            return (
                <SafeAreaView style={styles.body}>

                    {
                        isLoading ?
                            <View style={styles.loadingIndicator}>
                                <ActivityIndicator size='large' color='#FF0266'/>
                            </View>
                            :
                            camView
                    }

                </SafeAreaView>
            );
        }
    }

    const styles = StyleSheet.create({
        body: {
            backgroundColor: 'white',
            width: '100%',
            height: '100%'
        },
        logoStyle: {
            alignItems: 'center',
            marginTop: 50,
            zIndex: 1
        },
        loadingIndicator: {
            position: 'relative',
            marginTop: 150,
            alignItems: 'center',
            zIndex: 200
        },
        cameraContainer: {
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            height: '100%',
            backgroundColor: '#fff',
        },

        cameraInnerContainer: {
            position: 'relative',
            flex: 1,
            width: '100%',
        },
        camera: {
            // position: 'absolute',
            width: '100%',
            height: '100%',
            // zIndex: 1,
            borderWidth: 1,
            borderColor: 'red',
            // borderRadius: 0,
        },
        modelResults: {
            position: 'absolute',
            width: '100%',
            height: '100%',
            zIndex: 20000,
            borderWidth: 1,
            borderColor: 'black',
            borderRadius: 0,
        },
        textStyle: {
            fontSize: 16,
            color: 'white',
        },
        flipCameraBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            justifyContent: 'center',

            alignItems: 'center',
            borderColor: 'blue'
        },
        resetBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            justifyContent: 'center',

            alignItems: 'center',
            borderColor: 'blue'
        },
        idealFrameBtn: {
            backgroundColor: '#424242',
            width: '98%',
            marginHorizontal: '1%',
            padding: 10,
            marginVertical: 10,
            justifyContent: 'center',
            alignItems: 'center',
            borderColor: 'blue'
        },

    });

    export default App

**Comment by Sabit-Ahmed** [comment]
> 
> 
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

Done!

**Comment by jinjingforever** [comment]
Hi @Sabit-Ahmed, thanks for the report! It is indeed confusing to figure out how different dimensions work together. 

I created a demo for movenet + react native. Here is the [repo](https://github.com/jinjingforever/tfjs-react-native-pose-detection) you can check out. It should correctly render the results for any camera preview sizes ([screenshots](https://photos.app.goo.gl/JngVWy3DoN2DSx696)). Hopefully the comments in the code make sense. 

Please feel free to let me know if you have any questions. Thanks!

**Comment by wongway** [comment]
@jinjingforever - I've been having the same issue. I noticed that your sample code repo is no longer available. Would you be willing to share it again? Thanks in advance!

**Comment by jinjingforever** [comment]
@wongway Please see here: https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection
