### ISSUE TITLE
Can tensorflow.js decode MP4 video?

### ISSUE THREAD

**Issue by caggl** [tensorflow/tfjs#5441]
hello   Can tensorflow.js decode MP4 video?

**Comment by rthadur** [comment]
Please resubmit the issue using template and fill all the details.

To answer your question here is the steps you can follow to uses MP4 video 

`Take a look at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video for an example of how to load video into an HTMLVideoElement.

You should be able to pass a JavaScript reference to that DOM element to the posenet estimate* methods

That JavaScript reference should also allow you to control advancing the video etc.`
