### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by timekarma** [tensorflow/tfjs#5445]
data is not defined
await trainModel(model, inputs, labels);   //  gives an error saying Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

**Comment by bibs2091** [comment]
Hello, the trainModel function returns a promise it can be resolved either by then statement:
`trainModel(model, inputs, labels).then( console.log("done") )` .

or by putting it inside an async function and await:
```
async function name(){
 await trainModel(model, inputs, labels); 
}
```

**Comment by rthadur** [comment]
@bibs2091 thank you , yes please wrap your code inside a '`async`' function. Thank you
