### ISSUE TITLE
[wasm] failed to asynchronously prepare wasm

### ISSUE THREAD

**Issue by raffizulvian** [tensorflow/tfjs#5453]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04 WSL2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: v3.8.0
- CUDA/cuDNN version: N/A

**Describe the problem**
An error occurred in the build process in CI when sending a PR. The error appears at the wasm backend testing stage. Log says the error is `failed to asynchronously prepare wasm: RangeError: WebAssembly Instantiation: Out of memory: wasm memory
RangeError: WebAssembly Instantiation: Out of memory: wasm memory`. This problem was not encountered when testing on the local machine. I don't know what causes this. Could someone explain this?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Sumbit a PR.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Log:
```shell
failed to asynchronously prepare wasm: RangeError: WebAssembly Instantiation: Out of memory: wasm memory
RangeError: WebAssembly Instantiation: Out of memory: wasm memory
/workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:54
                throw ex;
                ^

RuntimeError: abort(RangeError: WebAssembly Instantiation: Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
    at abort (/workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:9:9596)
    at /workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:9:11594
error Command failed with exit code 7.
```

Code:
[[wasm] Add bincount kernel #5448](https://github.com/tensorflow/tfjs/pull/5448)

**Comment by rthadur** [comment]
@raffizulvian can you please check this related PR where '`sinh`' kernal was added https://github.com/tensorflow/tfjs/pull/4845 , I guess you are missing couple of files. Thank you

**Comment by rthadur** [comment]
Also please check you chrome version , I see there was an issue with chrome browser here earlier https://stackoverflow.com/questions/55039923/why-does-chrome-eventually-throw-out-of-memory-wasm-memory-after-repeatedly-r

**Comment by rthadur** [comment]
I assigned the PR to @lina128 , you can discuss at one place regarding the error . I will close this issue. Thank you
