### ISSUE TITLE
Collect kernels that are heavily used in models and call for uniforms

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#5460]
To resolve #5205, we are using uniforms instead of constants to reduce shader variants. There are two kinds of uniforms. One is shapes uniforms, which is behind a flag `WEBGL_USE_SHAPES_UNIFORMS` and is for shaders common parts used in `shader_compiler`. The other is the custom uniforms `customUniforms`, which is used for each kernel's `userCode` part. So to make a kernel whole uniform, we need to 1) enable shapes uniform 2) use custom uniforms. Currently, below kernels have supported whole uniform.
1. unary ops
2. binary ops
3. im2col program
4. encode/decode [packed] matrix program
5. depthwiseconv2d
6. reshape

Since webgl supports lots of kernels, we'd like to support the most frequently used kernels list instead of all of them. Once we confirm that uniforms do bring big warmup time advantages and small impact for the predict time, we will finish all of them and totally switch to uniforms by default. Here I'd like to collect the ops that are heavily used, but haven't been supported with uniforms.

matmul is the ono we are working on, but we met some [perf issue](https://github.com/tensorflow/tfjs/pull/5297/files#diff-ae73f9d8e507323398a73f338b6cba08e197afddf6595e7d9ab20161dcd526a1R88)

**Comment by qjia7** [comment]
@pyu10055 @lina128 @jinjingforever Please provide the ops that are heavily used in models and call for uniforms.

**Comment by gaikwadrahul8** [comment]
Hi, @qjia7 

Apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs/pull/5240 got merged so Is it taking care of this issue or are we still working on this issue ? Thank you!
