### ISSUE TITLE
Some benchmarks are using non-fused models

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#5461]
Open https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html and choose `bodypix`. The supported architectures are `MobileNetV1` and `ResNet50`. Both of them are non-fused models. Should we update it to use the fused one, for example, use mobilenetv2 instead mobilenetv1?
Other models like `posenet` have the similar problem.

**Comment by qjia7** [comment]
@pyu10055 FYI

**Comment by rthadur** [comment]
Will be closing this issue as we no longer support bodypix , we will be using new pose-detection model here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection , Thank you
