### ISSUE TITLE
webgpu backend incompatible with web workers

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5467]
trying out `tfjs-backend-webgpu`, there are quite a few instances in the code where it attempts to access **DOM** elements which are by definition *not available* in web workers:

```js
if (!(pixels instanceof HTMLVideoElement) ...
```

```log
Uncaught (in promise) ReferenceError: HTMLVideoElement is not defined
```

environment: chrome/94 canary, tfjs 3.8.0, tfjs-backend-webgpu 0.0.1-alpha.7

**Comment by shaoboyan** [comment]
Ah, yea. Thanks for catching this.

**Comment by shaoboyan** [comment]
@vladmandic  I've made a fix for this issue here https://github.com/tensorflow/tfjs/pull/5472 but I've got some problems to add a worker test to cover this in tfjs for now. I've checked the type checker part in some local framework in worker and it won't report the error.

And It is appreciate that if you could help to integrate this fix and build the latest tfjs webgpu backend to see whether there is other issues remain to run this backend in worker. 

cc @qjia7 too.

**Comment by vladmandic** [comment]
@shaoboyan solution looks ok, but unfortunately i cannot test in my existing code due to other unrelated webgpu blocking issues  
i'll start a new demo project just for webgpu testing soon

**Comment by vladmandic** [comment]
@shaoboyan i've tried building `tfjs-backend-webgpu` using your code, but it fails during build:

```log
src/kernels/FromPixels.ts:76:9 - error TS2322: Type 'HTMLVideoElement' is not assignable to type 'HTMLCanvasElement | ImageBitmap | OffscreenCanvas'.
  Type 'HTMLVideoElement' is missing the following properties from type 'HTMLCanvasElement': getContext, toBlob, toDataURL, transferControlToOffscreen

76         externalImage: pixels as HTMLVideoElement,
           ~~~~~~~~~~~~~

  src/kernels/FromPixelsExternalImage.ts:24:3
    24   externalImage: HTMLCanvasElement|ImageBitmap|OffscreenCanvas,
         ~~~~~~~~~~~~~
    The expected type comes from property 'externalImage' which is declared here on type '{ externalImage: HTMLCanvasElement | ImageBitmap | OffscreenCanvas; backend: WebGPUBackend; attrs: FromPixelsAttrs; }'

src/kernels/FromPixels.ts:106:7 - error TS2345: Argument of type '{ externalImage: HTMLCanvasElement | ImageBitmap; backend: WebGPUBackend; attrs: FromPixelsAttrs; useImport: boolean; }' is not assignable to parameter of type '{ externalImage: HTMLCanvasElement | ImageBitmap | OffscreenCanvas; backend: WebGPUBackend; attrs: FromPixelsAttrs; }'.
  Object literal may only specify known properties, and 'useImport' does not exist in type '{ externalImage: HTMLCanvasElement | ImageBitmap | OffscreenCanvas; backend: WebGPUBackend; attrs: FromPixelsAttrs; }'.

106       useImport: false
          ~~~~~~~~~~~~~~~~
```

**Comment by vladmandic** [comment]
@shaoboyan had some issues building new `tfjs-backend-webgpu` as i didn't realize that your patch is on top of your tree, not main. anyhow, all sorted and tested - it works!

**Comment by shaoboyan** [comment]
@vladmandic Big thanks!

**Comment by rthadur** [comment]
Thank you , closing this issue as the PR has been merged and latest changes will be available in next release.
