### ISSUE TITLE
webgpu backend does not support sync calls

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5468]
since this is documented in code as by-design, i'm flagging it as a feature request instead of a bug  
but in reality its a blocker for future `webgpu` adoption  

```js
const data = tensor.dataSync();
```

results in error:

```log
index.js:883 Error: WebGPU readSync is only available for CPU-resident tensors.
    at WebGPUBackend.readSync (backend_webgpu.ts:338)
    at Engine.readSync (engine.ts:1206)
    at Tensor.dataSync (tensor.ts:364)
```

i know same functionality can be achieved by using

```js
const data = await tensor.data();
```

but that requires quite a lot of changes to existing apps - so unless even when `webgpu` is widely available, it will not be able to use it as a plug-and-play instead of existing `webgl` backend  

even worse, `tf.tidy()` does not support async calls. which means that memory management became soo much more complicated.
and there are other JS functions that don't support async/await calls, for example `array.map()`, so any iterator would have to be reworked to use for loops.

also note that usage of `dataSync()` is not accidental to start with since its faster for very small tensors and where blocking main thread is irrelevant

all-in-all, support for sync calls is a must or webgpu is a non-starter.

environment: chrome/94 canary, tfjs 3.8.0, tfjs-backend-webgpu 0.0.1-alpha.7

**Comment by qjia7** [comment]
@vladmandic It is a known issue for us that webgpu does not support sync read. Another similar issue is #5092. Currently WebGPU spec only provides the async one `mapAsync`. There are some discussions whether to support a `readBuffer` API in WebGPU https://github.com/gpuweb/gpuweb/issues/1972. But it properly continues after the WebGPU MVP. We will follow up this issue and provide some inputs from TFJS side that we need the sync read API badly. For now, I'd suggest you try to use `data()` instead `dataSync` in your application. It's glad to know that you are trying the webgpu backend. Do you see any other problems that webgpu may be missing?

**Comment by vladmandic** [comment]
thanks for the reference link

i'll play with `webgpu` on a side, but i can't test it is any of my existing code due to extensive use of `tf.tidy` which doesn't support async calls.
and rewritting code to use `await tensor.data()` would not be trivial as main reason for `tf.tidy` is so i can use chained calls.

```js
const scores = tf.tidy(() => predictions.slice([0, 0], [-1, 1]).sigmoid().squeeze().dataSync());
```

or

```js
const data = tf.tidy(() => input.cast('float32').div(255).sub(0.5).expandDims(0).arraySync());
```

without `tf.tidy()` this would be 4 temp variables and later 4 calls to `tf.dispose()` - going from one-liner to 9 lines plus refactoring the caller functions to deal with async results  

without `webgpu` supporting sync reads, only option i see is enhancing `tf.tidy` so it works with async calls - not sure how feasible is that?  
and given the reluctance of `webgpu` team to implement sync reads, that may be what's needed...

`array.map` not supporting async calls (ok, it can be wrapped into `await promise.all`, but that is really not efficient) is a different story and not `tfjs` specific, so lets stick to `tfjs` specific issues.

**Comment by qjia7** [comment]
Resolved by https://github.com/tensorflow/tfjs/pull/7576.
