### ISSUE TITLE
Save model to file in Nodejs on Windows

### ISSUE THREAD

**Issue by wr1472** [tensorflow/tfjs#547]
#### TensorFlow.js version
0.12.3

#### Node version
6.9.4

#### Describe the problem or feature request
I am running TF via node on Windows 10. After traiing a model successfully when calling model.save("file:///./foo") I encounter the following error - 

Cannot find any save handlers for URL 'file:///foo'

Is saving to file when running on node supported on windows for @tfjs? Note I am not running tfjs-node and it is not really a viable option to do so.

**Comment by nkreeger** [comment]
This will be fixed in https://github.com/tensorflow/tfjs/issues/548

**Comment by nsthorat** [comment]
Closing this out since #548 was submitted.
