### ISSUE TITLE
BoundingBox MoveNet Tracker

### ISSUE THREAD

**Issue by emsoneal** [tensorflow/tfjs#5470]
I cannot figure out how to set the MoveNet tracking type to be a bounding box instead of keypoints. I can see it is an option in the source code, but have not been successful at setting it correctly in the detectorConfig. 
This is the code I have right now. How do I edit the detectorConfig variable to specify the bounding box tracker type?

`const detectorConfig = {modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING};
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig);`

**Comment by rthadur** [comment]
you can use in the similar to posnet bounding box specified here https://github.com/tensorflow/tfjs-models/blob/master/posenet/demo/demo_util.js#L132

**Comment by emsoneal** [comment]
I just want to only get the bounding box points (two shoulders and two hips). I don't want to call estimatePoses to get all the 17 key points. I am thinking that might increase the performace of my application.

**Comment by lina128** [comment]
Hi @emsoneal, do you need the bounding box for singlepose or multipose?

**Comment by emsoneal** [comment]
For singlepose!
