### ISSUE TITLE
Ship Windows support for Node.js bindings

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#548]
The `@tensorflow/tfjs-node` package currently only supports Mac and Linux binaries.  Several steps are required to make this happen:

1. Roll libtensorflow binaries
2. Extract symbols needed from DLLs
3. Update binding.gyp for windows
4. Re-write download scripts to be node-only (no zip/unzip/gzip on windows out-of-box)

**Comment by maulberto3** [comment]
I'd very much welcome Windows, and Node, support.

**Comment by wr1472** [comment]
@nkreeger thanks for linking my other ticket to this. Is there an ETA on when saving on windows will be released?

**Comment by greengis** [comment]
Very helpful +1

**Comment by talvasconcelos** [comment]
Any updates on this? Can't seem to install tfjs-node on windows...

**Comment by nkreeger** [comment]
@talvasconcelos Can you post the exception here? Node-gyp requires Python 2.7 FYI. We have CUDA and CPU available now.

**Comment by talvasconcelos** [comment]
from log file: 
693 verbose stack Error: @tensorflow/tfjs-node@0.1.15 install: `node scripts/install.js`
693 verbose stack Exit status 1
693 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
693 verbose stack     at EventEmitter.emit (events.js:182:13)
693 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
693 verbose stack     at ChildProcess.emit (events.js:182:13)
693 verbose stack     at maybeClose (internal/child_process.js:962:16)
693 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
694 verbose pkgid @tensorflow/tfjs-node@0.1.15
695 verbose cwd C:\Users\tvasconcelos\Desktop\DRL
696 verbose Windows_NT 6.1.7601
697 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
698 verbose node v10.10.0
699 verbose npm  v6.4.1
700 error code ELIFECYCLE
701 error errno 1
702 error @tensorflow/tfjs-node@0.1.15 install: `node scripts/install.js`
702 error Exit status 1
703 error Failed at the @tensorflow/tfjs-node@0.1.15 install script.
703 error This is probably not a problem with npm. There is likely additional logging output above.
704 verbose exit [ 1, true ]
 
also from cmd:

PS C:\Users\tvasconcelos\Desktop\DRL> npm i

> @tensorflow/tfjs-node@0.1.15 install C:\Users\tvasconcelos\Desktop\DRL\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

* Downloading libtensorflow
[==============================] 25825613/bps 100% 0.0s
* Building TensorFlow Node.js bindings
C:\Users\tvasconcelos\Desktop\DRL\node_modules\@tensorflow\tfjs-node\scripts\install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\tvasconcelos\Desktop\DRL\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at cp.exec (C:\Users\tvasconcelos\Desktop\DRL\node_modules\@tensorflow\tfjs-node\scripts\install.js:154:13)
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
npm WARN DRL@1.0.0 No description
npm WARN DRL@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.1.15 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tvasconcelos\AppData\Roaming\npm-cache\_logs\2018-09-11T15_01_52_399Z-debug.log

**Comment by nkreeger** [comment]
```
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
```

Python 3.xx is not supported by node-gyp which is required to build the TensorFlow.js bindings. The node-gyp README has some options that might work for you:
https://github.com/nodejs/node-gyp/blob/master/README.md
