### ISSUE TITLE
Blazeface result is not correct on WASM backend

### ISSUE THREAD

**Issue by deepanshusharma012** [tensorflow/tfjs#5486]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
  This is happening even in demo page for blazeface model (i.e. https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  Linux Ubuntu 18.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  Haven't checked yet on mobile, but probably it will exist in all the devices

- TensorFlow.js installed from (npm or script link):
  https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0

- TensorFlow.js version (use command below):
  3.1.0

- Browser version:
 Chrome 91

**Describe the current behavior**
  Open the blazeface model demo page on `https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html`. 
  It is detecting the face on hands kept in front of webcam. If the face is present in the frame, then it detects properly the face and results are as expected. But if we don't have any face in the frame, in that case the blazeface detection results shows that face exists while it is Hand/mobile, etc.

**Describe the expected behavior**
  It should show result of face detected only if any face is present in frame. If there is no face in frame, then there is no point to show face detected.

**Other info / logs** 
![Screenshot from 2021-08-13 11-03-57](https://user-images.githubusercontent.com/41855523/129309933-86df836d-f3b2-4e0b-8a15-8fab539dc4cf.png)
![Screenshot from 2021-08-13 11-04-43](https://user-images.githubusercontent.com/41855523/129309935-04ec7f13-ff90-4f0d-8b3a-586488615063.png)

**Comment by rthadur** [comment]
It tries to detect all the object but you need to check the probability , which will vary for actual face and some random objects. You can try to get the code locally and check for percentage accuracy.

This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by deepanshusharma012** [comment]
Can you please tell me whats the probability of face then?
