### ISSUE TITLE
Replace deprecated `setWasmPath` with `setWasmPaths`

### ISSUE THREAD

**Issue by kungfooman** [tensorflow/tfjs#5488]
Bad way (only uses `tfjs-backend-wasm.wasm`): 

https://github.com/tensorflow/tfjs-models/blob/8faa92d8933d8036deae63b034db399c09173a2e/facemesh/demo/index.js#L27

Good way (uses `tfjs-backend-wasm-simd.wasm` or `tfjs-backend-wasm-threaded-simd.wasm` if possible):

https://github.com/tensorflow/tfjs-models/blob/8faa92d8933d8036deae63b034db399c09173a2e/face-landmarks-detection/demo/index.js#L28

**Comment by rthadur** [comment]
Hi @kungfooman `facemesh` is no longer supported , please refer to `face-landmarks-detection `. Thank you 

![image](https://user-images.githubusercontent.com/43972606/129371594-f0bd395e-b5e7-45d6-ab4b-4d8279ed8536.png)

**Comment by kungfooman** [comment]
Well, too bad then, `facemesh` detects my face better than `face-landmarks-detection`.
