### ISSUE TITLE
Issues with tf.cast(x, 'int32') and tf.squaredDifference()

### ISSUE THREAD

**Issue by KimYoungBo** [tensorflow/tfjs#549]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.7
#### Browser version
chrome 67
#### Code to reproduce the bug / link to feature request
const x = tf.tensor1d([1.5, 2.5, 3]);
tf.cast(x, 'int32').print();
// result ==> [1, 2, 3]

console.log(x.dataSync());
x.data();   // same
// result ==> 1.5,  2.5, 3

**Comment by bileschi** [comment]
`tf.cast(x. 'int32');` returns a new tensor.  it does not modify x.

```
> const x = tf.tensor1d([1.5, 2.5, 3]);
> const y = tf.cast(x, 'int32');
> x.print();
> y.print();
```
prints
```
Tensor
    [1.5, 2.5, 3]
Tensor
    [1, 2, 3]
```

Does this solve your issue?

**Comment by KimYoungBo** [comment]
> To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).
> 
> #### TensorFlow.js version
> 0.12.7
> 
> #### Browser version
> chrome 67
> 
> #### Describe the problem or feature request
> #### Code to reproduce the bug / link to feature request
> const x = tf.tensor1d([1.5, 2.5, 3]);
> tf.cast(x, 'int32').print();
> // result ==> [1, 2, 3]
> 
> console.log(x.dataSync());
> x.data(); // same
> // result ==> 1.5, 2.5, 3
