### ISSUE TITLE
ssd mobilenet v3 10+ times slower than native app

### ISSUE THREAD

**Issue by Jove125** [tensorflow/tfjs#5491]
Hello,

I trained ssd mobilenet v3 (large minimalistic), non-quantized standard model (tflite).
The execution time of this model in a native android application (google pixel 4a 5g) is 15 ms.

Using tensorflow.js version 3.3.0 (on later versions the model doesn't work) the time is:
cpu backend - 2600 ms
webgl backend - 220 ms
wasm backend - 180 ms

I also tried the alpha version of tf-js tflite and it showed the best results - around 115-130 ms in any backend. But this is also very slow.

1. Is it possible to somehow speed up these models?
2. If not, what ssd models should be trained to have high performance on mobile phones?

Thanks.

**Comment by rthadur** [comment]
Have you tried using tflite for mobile version https://www.tensorflow.org/lite/examples/object_detection/overview ?

**Comment by Jove125** [comment]
rthadur,

I tried right now this model (COCO SSD MobileNet v1):
webgl backend - 1200 ms
wasm backend - 1100 ms

tf-js tflite - 570

In accordance with the Performance Benchmarks on Pixel 4 (https://www.tensorflow.org/lite/examples/object_detection/overview#performance_benchmarks), it should work 20 ms in a native application, and works on the web almost 30 times slower than the best option - tf-js tflite

**Comment by jinjingforever** [comment]
Sorry, I haven't looked into this.. Will keep this open for now and take a look when I have more bandwidth.

**Comment by jinjingforever** [comment]
Hi @Jove125, I had a brief chat with our TL. We do see some performance issues with self-trained ssd mobilenet models, and we probably need to invest more time on optimization. For now, you can take a look at [here](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd#technical-details-for-advanced-users) for some optimization ideas (for converted TFJS model). Thank you!

**Comment by Jove125** [comment]
> Hi @Jove125, I had a brief chat with our TL. We do see some performance issues with self-trained ssd mobilenet models, and we probably need to invest more time on optimization. For now, you can take a look at [here](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd#technical-details-for-advanced-users) for some optimization ideas (for converted TFJS model). Thank you!

jinjingforever, thanks, I've already seen these optimization ideas.
Are there any optimization ideas for the tflite model (for web)?
And are there any planned timelines to optimize the performance of this solution?
Thank you!

**Comment by jinjingforever** [comment]
Hi @Jove125, sorry we don't have a timeline for this work now. I will bring this up in our team meeting and hopefully it can be prioritized in the future.

**Comment by jinjingforever** [comment]
Will keep this open for now.

**Comment by Jove125** [comment]
> Hi @Jove125, sorry we don't have a timeline for this work now. I will bring this up in our team meeting and hopefully it can be prioritized in the future.

Hi @jinjingforever,
Are there any updates on this issue?

**Comment by jinjingforever** [comment]
Sorry @Jove125 not yet... Some of my teammates are exploring some ideas of optimizing the webgl backend in general. Hope that will help with this issue as well. But unfortunately I don't have a concrete timeline.

**Comment by gaikwadrahul8** [comment]
Hi, @Jove125 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs and `@tensorflow/tfjs-tflite@0.0.1-alpha.9` please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by Jove125** [comment]
Hello gaikwadrahul8,

Thanks!
Version 9 works much faster.
But the next version 10 stopped working altogether with the following error:
GET https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10/dist/tflite_web_api_cc_simd.js net::ERR_ABORTED 404 (Not Found)

tflite_web_api_client.js:2710 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_malloc')
    at $jscomp.generator.Engine_.program_ (tflite_web_api_client.js:2710:245)
    at $jscomp.generator.Engine_.nextStep_ (tflite_web_api_client.js:31:105)
    at $jscomp.generator.Engine_.next_ (tflite_web_api_client.js:27:234)
    at $jscomp.generator.Generator_.next (tflite_web_api_client.js:32:73)
    at t (tflite_web_api_client.js:33:73)

**Comment by Jove125** [comment]
There seems to be a problem with the file import paths. It try to get tflite_web_api_cc_simd.js from dist folder, but it is located in wasm folder.
If I download and move all files from the wasm folder to the dist folder, the error does not occur.
