### ISSUE TITLE
posibility of a 3.8.1 release with updated adm-zip

### ISSUE THREAD

**Issue by evansrobert** [tensorflow/tfjs#5492]
Hi, @lina128 @pyu10055, there is a high severity vulnerability introduced by package **adm-zip**:
### Issue Description

   I noticed that a vulnerability is introduced in **_@tensorflow/tfjs-node@3.8.0_**:
     Vulnerability **SNYK-JS-ADMZIP-1065796** (high severity) affects package **_adm-zip_** (versions:<0.5.2):  [https://snyk.io/vuln/SNYK-JS-ADMZIP-1065796](https://snyk.io/vuln/SNYK-JS-ADMZIP-1065796)
  The above vulnerable package is referenced by **_@tensorflow/tfjs-node@3.8.0_** via:
`@tensorflow/tfjs-node@3.8.0 ➔ adm-zip@0.4.16`

Since **_@tensorflow/tfjs-node@3.8.0_** ([2,176 downloads per week](https://www.npmjs.com/package/@tensorflow/tfjs-node/v/3.8.0?activeTab=versions)) is referenced by **18** downstream projects (e.g., [stills 21.3.6](https://www.npmjs.com/package/stills) (latest version), [node-red-contrib-facial-recognition 0.30.105](https://www.npmjs.com/package/node-red-contrib-facial-recognition) (latest version), [@nlpjs/open-question 4.22.0](https://www.npmjs.com/package/@nlpjs/open-question) (latest version), [twitterfollowerexplorer 3.1.11](https://www.npmjs.com/package/twitterfollowerexplorer) (latest version), [roboflow-node 0.2.16](https://www.npmjs.com/package/roboflow-node) (latest version)), the high severity vulnerability [**SNYK-JS-ADMZIP-1065796**](https://snyk.io/vuln/SNYK-JS-ADMZIP-1065796) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`stills@21.3.6 ➔ @tensorflow/tfjs-node@3.8.0 ➔ adm-zip@0.4.16`
(2)`twitterfollowerexplorer@3.1.11 ➔ @tensorflow/tfjs-node@3.8.0 ➔ adm-zip@0.4.16`
  **......**

If **_@tensorflow/tfjs-node@3.8.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from @tensorflow/tfjs-node@3.8.0 ?**

### Fixing suggestions

In **_@tensorflow/tfjs-node@3.8.1_**, maybe you can kindly try to perform the following upgrade(**not crossing major version**) :
`adm-zip ^0.4.11 ➔ ^0.5.2`; 

**Note:**
_**adm-zip@0.5.2**(>=0.5.2) has fixed the vulnerability [**SNYK-JS-ADMZIP-1065796**](https://snyk.io/vuln/SNYK-JS-ADMZIP-1065796)._

Thank you for your attention to this issue and welcome to share other ways to resolve the issue.

Best regards,
^_^

**Comment by rthadur** [comment]
Thank you @evansrobert , submitted a fix , let's wait for PR to get reviewed.

**Comment by evansrobert** [comment]
@rthadur Thanks for your feedback.
