### ISSUE TITLE
Kernel 'Unique' not registered for backend 'tensorflow'

### ISSUE THREAD

**Issue by bibs2091** [tensorflow/tfjs#5497]
**System information**
- OS Platform: windows 10
- TensorFlow.js version: tfjs-node": "^3.8.0"

when i try to apply tf.unique method on any tensor in tfjs-nodejs, per example:
```
const a = tf.tensor2d([[1, 0, 0], [1, 0, 0], [2, 0, 0]]);
const {values, indices} = tf.unique(a, 1)
```
I face this error line:
```
(node:13336) UnhandledPromiseRejectionWarning: Error: Kernel 'Unique' not registered for backend 'tensorflow'
    at Engine.runKernel (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-core\src\engine.ts:548:13)
    at unique_ (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-core\src\ops\unique.ts:85:9)
    at Object.unique__op [as unique] (C:\Users\bibs2091\Desktop\PFE\node_modules\@tensorflow\tfjs-core\src\ops\operation.ts:51:24)
    at DataBlock.fromTensor (C:\Users\bibs2091\Desktop\PFE\lib\DataBlock.ts:59:40)
    at C:\Users\bibs2091\Desktop\PFE\examples\basic.ts:10:10
    at step (C:\Users\bibs2091\Desktop\PFE\examples\basic.ts:33:23)
    at Object.next (C:\Users\bibs2091\Desktop\PFE\examples\basic.ts:14:53)
    at C:\Users\bibs2091\Desktop\PFE\examples\basic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\bibs2091\Desktop\PFE\examples\basic.ts:4:12)
```

Can you fix this please.

**Comment by rthadur** [comment]
tf.unique is not implemented in tfjs-node, right now it is implemented for `cpu` and `webgl` only , here is a feature request which already exist here https://github.com/tensorflow/tfjs/issues/4595 , please comment on #4595 so that we can prioritize accordingly. 

Thank you.

**Comment by ClaytonSmith** [comment]
Just wanted to point out @rthadur's comment is incorrect, `tf.unique` is not implemented for `webgl`. This issue should still be active

**Comment by gyagp** [comment]
tf.unique is already supported by WebGL backend, while it's still a gap for WebGPU. The API document (https://js.tensorflow.org/api/latest/#unique) takes WebGPU backend as default, but you may switch the backend with the arrow button. Any requirement to have it supported by WebGPU backend?

<img width="635" alt="unique" src="https://github.com/tensorflow/tfjs/assets/218432/f35ff544-df42-4cd5-b10b-442efe214faa">

**Comment by ClaytonSmith** [comment]
oh wow. It took way to long for me to notice `webgl` != `webgpu`. Big oof on my part haha 😅

> Any requirement to have it supported by WebGPU backend?
I can roll with `gl` or `gpu` but whichever has the most performance would be preferred. My use case is for real time data processing in a browser.  I'm attempting to manipulate several hundred MB of data in real team. While my use case does is not for training/running a model, the data processing capabilities of TF in a browser are second to none (that I know of).
