### ISSUE TITLE
Handling of Assert Ops ?

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#55]
_From @rodrigob on March 21, 2018 20:11_

The SavedModel I am trying to convert generated, amongst others; the following message:

> Unsupported Ops in the model: Assert

I am wondering if tfjs-converted should not simply ignore Assert ops, and at best generate a warning rather than an error ? (I guess the same would go for Print ops)

_Copied from original issue: tensorflow/tfjs-converter#42_

**Comment by dsmilkov** [comment]
_From @pyu10055 on March 21, 2018 20:50_

The Assert op is a control flow op which requires run-time eval of the tensor, which will be my goal to support with other control op (merge, switch, ...).
Can you tell what is your use case for Assert in inference mode, do you expect an error, or it is a by-product of the training setup?

**Comment by dsmilkov** [comment]
_From @pyu10055 on March 21, 2018 23:46_

I notice Assert is usually accompanied by Switch op, does your model only have the Assert op unsupported? If so, do you mind sharing the model, so I can investigate a bit more. Thanks.

**Comment by dsmilkov** [comment]
_From @pyu10055 on March 31, 2018 18:2_

We believe that the Assert op should not exist in the inference graph, we will remove the assert and other debug nodes from the graph during the conversion phase.

**Comment by chrisdonahue** [comment]
+1 on this issue. It would be extremely painful for me (requiring hundreds of lines of code changes) to manually remove all the assertions from my graph because they are generated by library code (e.g. DeepMind's `sonnet`)

**Comment by chrisdonahue** [comment]
Even core API calls such as `tf.nn.dynamic_rnn` contain asserts: https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/python/ops/rnn.py#L597
