### ISSUE TITLE
Investigate using integer textures with IEEE 754 float encoding.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#551]
Recently we disabled integer texture mode (which was using fixed point precision) in favor of half floats on iOS.

However, there are still many devices which do not support the OES_texture_float extension, like Raspberry Pis (see [this thread](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/kkRGiQy_lu0/PABzWktoCAAJ)) and Mali T720 GPUs like on Android (see this bug https://github.com/tensorflow/tfjs/issues/502).

We could reenable fixed point numbers, but the precision is quite terrible. The other option is to implement IEEE 754 in a shader. We already have a 32 bit float => 4, 8-bit float encoder [here](https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/encode_float_gpu.ts), we would just need to write the reverse. Even if performance is poor, it might be better than nothing.

**Comment by nkreeger** [comment]
Working on introducing half-float changes in the driver for vc4 (driver for Raspberry Pi) - some work tracked here: https://github.com/anholt/mesa/pull/115

**Comment by nsthorat** [comment]
I doubt we're going to do this since it's going to be very slow and we have solutions on most devices, especially with the WASM backend coming soon.
