### ISSUE TITLE
Neither LSTMCell nor RNNCell are exported in `.d.ts` file

### ISSUE THREAD

**Issue by indutny** [tensorflow/tfjs#552]
#### TensorFlow.js version

0.12.3

#### Browser version

Node 10.5.0

#### Describe the problem or feature request

Documentation says that `tf.RNNCell` is a return type of `tf.layers.lstmCell`. However, neither `RNNCell` nor `LSTMCell` are exported.

#### Code to reproduce the bug / link to feature request

```js
console.log(tf.RNNCell === undefined);
console.log(tf.LSTMCell === undefined);
```

**Comment by caisq** [comment]
@indutny Thanks for reporting this issue. We will export `RNNCell` as `tf.layers.RNNCell` and export `RNN` as `tf.layers.RNN`.

**Comment by indutny** [comment]
Thanks!
