### ISSUE TITLE
[tfjs-react-native] Image classification of Livestream in real-time

### ISSUE THREAD

**Issue by BILLXZY1215** [tensorflow/tfjs#5520]
**System information**
- TensorFlow.js version: 3.8.0
- tfjs-react-native version: 0.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I wonder if there is a way to analyze the Livestream in real-time. For example, I've got a task to classify a mini object, such that the mobile's camera is not capable of doing that. In this case, I have an IP camera, which could return a Livestream url for the app. However, currently, there is only the `decodeJpeg` method, which runs statically, not dynamically. Actually, I'm trying to snapshot on the Livestream frame and recursively calling `decodeJpeg` method, however, this is weird and I think the performance interacting with react-native is not good. 

**Will this change the current API? How?**

Yes, and I think it needs two steps:

1. Allowing dynamic video streams to be the input (e.g. a Livestream url) of a model (which possibly will be a new API).
2. Allowing a real-time callback function for result display.

**Who will benefit from this feature?**

For users that need to use other cameras instead of mobile native cameras, because not all types of objects or images taken by phones are suitable for particular cases, thanks a lot!

**Comment by rthadur** [comment]
You can use tf.data.webcam https://js.tensorflow.org/api/latest/#data.webcam to live stream , please check

**Comment by BILLXZY1215** [comment]
> You can use tf.data.webcam https://js.tensorflow.org/api/latest/#data.webcam to live stream , please check

Thanks a lot! This is cool, however, I notice that it is only working for webcams (usually link to PC by USB), instead of ip cameras (directly access live streams from a URL under the same network). I'm not quite sure if I could just input the live stream URL (such as RTSP, MJPEG) to `tf.data.webcam`, it seems that the method only accepts input of a DOM element such as `document.createElement('video')`.

**Comment by BILLXZY1215** [comment]
I think this is really close to the use of `cameraWithTensors`:

https://js.tensorflow.org/api_react_native/0.6.0/#cameraWithTensors

If the `onReady` function could be used for a Livestream URL, everything will be perfect. 🤔

**Comment by coucoseth** [comment]
anyone found a solution on how to load live stream from ip camera?
