### ISSUE TITLE
Migrate Typescript to 4.x

### ISSUE THREAD

**Issue by pyu10055** [tensorflow/tfjs#5522]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**Describe the problem**
To Sync up with the internal TS version, we should upgrade the monorepo to TS 4.x
There are some known issues with the migration:
- SpyOn no long works in TS4
- properties override access error
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @pyu10055 

If I'm not wrong we have migrated to `"typescript": "4.9.4"` and I checked multiple TFJs packages where typescript getting used and it's showing `"typescript": "4.9.4"` or Is this issue for internal monorepo migrate to TS 4.x ? Thank you!

**Comment by mattsoulanille** [comment]
This was done a year ago, and it looks like we forgot to close it. We're on 5.0.4 now.
