### ISSUE TITLE
Are there are any nightly version of tfjs-node?

### ISSUE THREAD

**Issue by bibs2091** [tensorflow/tfjs#5534]
Hello,

I want to install a version of tfjs/tfjs-node that contains the current bug fixes that are in the master **now** (or maybe in the future), are there are any **nightly tfjs** versions to install directly from npm (or any other way) so I can use it?

Thank you.

**Comment by mattsoulanille** [comment]
Hi @bibs2091, and thanks for the question! While we don't publish any nightly releases to npm right now, you can build a more recent release of tfjs and tfjs-node yourself and link them to your project. Details on how to build them are available in the [development doc](https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md#packaging-browser-and-npm), but the following commands should build each package:

In the tfjs-node directory: 
```
yarn
yarn build-deps
yarn build-npm
```
This creates the file `tensorflow-tfjs-node-0.0.0.tgz`, which can be `yarn add`ed or `npm install`ed into another package. Alternatively, you can [link the tfjs-node directory itself](https://classic.yarnpkg.com/en/docs/cli/add/) (see `yarn add link:/`).

In the tfjs directory:
```
yarn
yarn build-deps
yarn build-npm
```
This creates `tensorflow-tfjs-0.0.0.tgz`.

Feel free to @ me if you run into any trouble with this!
