### ISSUE TITLE
Support L2-Pooling.

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#5539]
Hi,
Is there any plan to support L2-Pooling?  Thanks.

Link https://github.com/webmachinelearning/webnn-polyfill/pull/112.

**Comment by pyu10055** [comment]
There are suggestion that you can decompose L2 pooling with following:
```
tf.sqrt(tf.avgPool(tf.square(h)) 
```

**Comment by BruceDai** [comment]
Thanks much @pyu10055. 
Close it.
