### ISSUE TITLE
tf.fused.conv2d doesn't support 'NCHW' data format

### ISSUE THREAD

**Issue by huningxin** [tensorflow/tfjs#5546]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.8.0
- TensorFlow.js version (use command below): 3.8.0
- Browser version:  Google Chrome  92.0.4515.159
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
This issue could be reproduced by following code snippet
```js
let x = tf.ones([1, 2, 5, 5]);  // `NCHW`
let filter = = tf.ones([3, 3, 2, 3]); // `HWIO`
let y = tf.fused.conv2d({x, filter, strides: 1, pad: 'same', dataFormat: 'NCHW'});
```
The error will be thrown:
```
Uncaught Error: Error in conv2d: depth of input (5) must match input depth for filter 2.
```

**Describe the expected behavior**

No error is thrown and the result is expected to be same as tf.conv2d.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

See above code snippet.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

See error message above.

cc @pyu10055 . Thanks.

**Comment by vladmandic** [comment]
Just my $0.02, almost none of TFJS ops support any other format than *NHWC* (which is defacto a standard for TF in general), not just `Conv2D`. And it's easy (and fast) to transpose tensor before using it. Even in TF itself (using Python bindings), very few ops support anything other than *NHWC* (although more than in TFJS).

**Comment by rthadur** [comment]
Support was added here https://github.com/tensorflow/tfjs/pull/6460 , closing this request. Thank you
