### ISSUE TITLE
Test cases missing for error detection in tfjs-layers (In many functions).

### ISSUE THREAD

**Issue by sourabh112** [tensorflow/tfjs#5550]
There are a lot of test cases missing for error detection in tfjs-layers. Some are already added as an issue but others are not yet reported. 
Are you willing to work on this: Yes
These are my initials findings for missing error detection test-cases:

- Check Input Data function
- Model.Summary
- Model.Compile
- standardizeDataIteratorOutput

**Comment by sourabh112** [comment]
I have made tests for the following functions. If anyone can confirm that these are missing. I will make a PR for these. And If anyone wants to add more missing test cases.

**Comment by sourabh112** [comment]
I don't see much movement on this issue. I think this issue might not be correctly portrayed by me. So, If there is no movement on it till tomorrow, I will close it.

**Comment by rthadur** [comment]
Hi @mattsoulanille can you please help with this request ?

**Comment by gaikwadrahul8** [comment]
Hi, @sourabh112 

Apologize for the delayed response and thank you for bringing this issue to our attention, It seems like we have done lot of changes till today so If I'm not wrong we have added test cases, please refer this [link](https://github.com/tensorflow/tfjs/tree/master/tfjs-layers/src).

If we have missed some test cases please point out with file references so we'll take look into those files and will add missing test cases if needed. Thank you!
