### ISSUE TITLE
Spelling mistake on js.tensorflow.org

### ISSUE THREAD

**Issue by WOLFI3654** [tensorflow/tfjs#556]
I hope that is the right place to put this discovery.
On the page [Model-save-load](https://js.tensorflow.org/tutorials/model-save-load.html) it says `"Trigger file **downlads** (Browser)"` under Saving tf.model
I think it is obvious that this should be _downloads_.

I was not able to find any reference to a Github page for the website so this repository was the closest thing I could find so it can be corrected.

**Comment by caisq** [comment]
@WOLFI3654 Thanks for reporting the issue. Feel free to send a pull request to fix it.

**Comment by hiyashichuka** [comment]
Excuse me for cutting in.
Please tell me where "Model-save-load  Page" is mentioned in the Github.
>I was not able to find any reference to a Github page for the website.
me too.

**Comment by tafsiri** [comment]
@WOLFI3654 @hiyashichuka, here is a link to the website repo https://github.com/tensorflow/tfjs-website, and to that page in particular if you want to make a pull request. https://github.com/tensorflow/tfjs-website/blob/master/source/tutorials/model-save-load.md

Thanks!

**Comment by hiyashichuka** [comment]
@tafsiri @caisq 
I sent a pull request. Please validate it
https://github.com/tensorflow/tfjs-website/pull/185
