### ISSUE TITLE
Is model bodypix support in reactnative expo android mobile app?

### ISSUE THREAD

**Issue by zhangsipeng** [tensorflow/tfjs#5569]
The problem above is challenging my projects critically? Please help if you could~

**Comment by zhangsipeng** [comment]
@tylerzhu-github  can you help me with this question? thanks

**Comment by rthadur** [comment]
You can use movenet instead of bodypix , please check out this demo https://github.com/jinjingforever/tfjs-react-native-pose-detection here , thank you
