### ISSUE TITLE
UglifyJs error during build

### ISSUE THREAD

**Issue by Firenze11** [tensorflow/tfjs#557]
I use tfjs in a Webpack project and got this error message during build:
```
ERROR in main-c0b5163b85a17b3c3caa.js from UglifyJs
Unexpected token: name ($oneOfFields) [./node_modules/@tensorflow/tfjs-converter/dist-es6/data/compiled_api.js:324,0][main-c0b5163b85a17b3c3caa.js:112140,12]
```
I don't have dependency on UglifyJs in my project, so I assume this is a problem internal to tfjs.

#### TensorFlow.js version
`"@tensorflow/tfjs": "^0.11.7"`

**Comment by 116050423** [comment]
Uglify is Webpack's default config in  'production' mode.
I think you should not build tfjs node_module, just ignore it ....
I also use webpack and it works well.

**Comment by 116050423** [comment]
@dsmilkov I think this issue can be closed.

**Comment by dsmilkov** [comment]
Thanks. Closed
