### ISSUE TITLE
getting error while using '@tensorflow-models/mobilenet' in bare react-native project.

### ISSUE THREAD

**Issue by suneeltechnew** [tensorflow/tfjs#5571]
I am getting error while using '@tensorflow-models/mobilenet' in bare react-native project.
I am referring this documentation: https://blog.tensorflow.org/2020/02/tensorflowjs-for-react-native-is-here.html
my code is as below :

```javascript
import React, { useEffect } from 'react';
import { View, Text } from 'react-native';
import * as mobilenet from '@tensorflow-models/mobilenet';

export default TensorflowLite = () => {
    const load = async () => {
        try {
            // Load mobilenet.
        const model = await mobilenet.load();
        console.log(model);
        } catch(err) {
            console.log(err);
        }
    }
    useEffect(() => {
        load();
    }, []);
    return <View>
       <Text>This is demo app.</Text>
    </View>
}
```
The error I am getting is:
![image](https://user-images.githubusercontent.com/88646798/131718300-0e2ecc88-0e11-4091-abb6-57281a505b51.png)

Please let me know How can I fix it.
Thanks in advance.

**Comment by rthadur** [comment]
please check here for related issue https://github.com/tensorflow/tfjs/issues/5167 , thank you

**Comment by suneeltechnew** [comment]
@rthadur , Thanks for your response.
but this was not solved my issue.
As mentioned in issue #5167 I have used installed required expo modules and "react-native-unimodules" as per below documentations.
[https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#step-1-create-your-react-native-app](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#step-1-create-your-react-native-app)
[https://docs.expo.dev/bare/installing-unimodules/](https://docs.expo.dev/bare/installing-unimodules/)
but it didn't worked for me.

**Comment by jinjingforever** [comment]
Hi @suneeltechnew, I think you need to add `tf.ready()` before loading the model. Something like:

```typescript
    const load = async () => {
      try {
        // Wait for the backend to be ready.
        await tf.ready();
        // Load mobilenet.
        const model = await mobilenet.load();
        console.log(model);
      } catch(err) {
        console.log(err);
      }
    }
```

Please give it a try. Thanks!

**Comment by suneeltechnew** [comment]
@jinjingforever , Thanks for the suggestion.
I have tried the above code, but still I am getting same error.

Please have a look at my code.
```javascript
import React, { useEffect, useState } from 'react';
import { View, Text, Image } from 'react-native';
import * as tf from '@tensorflow/tfjs';
import * as mobilenet from '@tensorflow-models/mobilenet';
// import { fetch, decodeJpeg } from '@tensorflow/tfjs-react-native';

export default TensorflowLite = () => {
    const [ isTfReady, setIsTfReady ] = useState(false);
    const load = async () => {
        try {
            // Load mobilenet.
        await tf.ready();
        setIsTfReady(true);
        const model = await mobilenet.load();
        console.log(model);
        // const image = require('../images/elon_musk.jpeg');
        // const imageAssetPath = Image.resolveAssetSource(image);
        // const response = await fetch(imageAssetPath.uri, {}, { isBinary: true });
        // // const response = await fetch('https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Elon_Musk_2015.jpg/612px-Elon_Musk_2015.jpg', {}, { isBinary: true });
        // console.log(response);
        // const imageDataArrayBuffer = await response.arrayBuffer();
        // const imageData = new Uint8Array(imageDataArrayBuffer);
        // console.log(imageData);
        // const imageTensor = decodeJpeg(imageData);
        // console.log(imageTensor);
        // const prediction = await model.classify(imageTensor);
        // console.log(prediction);
        } catch(err) {
            console.log(err);
        }
    }
    useEffect(() => {
        load();
    }, []);
    return <View>
        <Image source={require('../images/elon_musk.jpeg')}/>
        { isTfReady && <Text>tensorflow models are loaded</Text>}
    </View>
}
```
some times the app will close automatically when I am running this code without giving any warning/error.

**Comment by jinjingforever** [comment]
Hi @suneeltechnew, looks like the problem is the missing import for tfjs-react-native. Here are my imports which seem to work for your app:

```typescript
import React, { useEffect, useState } from 'react';
import { View, Text, Image } from 'react-native';
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';  // <-- This is important
import * as mobilenet from '@tensorflow-models/mobilenet';
```

Please give it a try. Thank you!

**Comment by suneeltechnew** [comment]
@jinjingforever , it didn't worked for me.

**Comment by jinjingforever** [comment]
@suneeltechnew, please check out this [repo](https://github.com/jinjingforever/tfjs-react-native-mobilenet) I created. I tested it on iPhone 12 Pro Max and Pixel 2. The only difference is that I am using `react-native 0.63.2`.  

Thank you!

**Comment by suneeltechnew** [comment]
@jinjingforever , the repo which you shared is using expo.
I want to run the code in pure react-native project.

**Comment by jinjingforever** [comment]
Hi @suneeltechnew, I updated the [repo](https://github.com/jinjingforever/tfjs-react-native-mobilenet) with an additional project generated from react native CLI. I found the problem to be the incompatibility between `react-native` 0.65.1 and `expo-gl` 10.4.2. I downgraded `react-native` to 0.63.2 and it works fine on my Pixel 2. (0.65.1 would crash my phone caused by GL context creation failure). 

Please give it a try. Thanks!

**Comment by suneeltechnew** [comment]
Thank you so much @jinjingforever 🤩. it is working for me.

**Comment by jinjingforever** [comment]
Hi @anhquan291 please see here: https://github.com/tensorflow/tfjs-examples/tree/master/react-native/image-classification/react-native-cli

**Comment by ShresthaPrajwal** [comment]
I'm on react native version 0.77.0.

Should I downgrade my react native version to solve this issue??
