### ISSUE TITLE
loadLayersModel crashes in React Native without an error

### ISSUE THREAD

**Issue by konstantinlois** [tensorflow/tfjs#5572]
I am trying to load a tensorflow model in React Native. If I use tfjs in normal React, everything works fine, but in React Native the app crashes (strangely without an error).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android emulator as well as physical device
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): "@tensorflow/tfjs": "^3.9.0", "@tensorflow/tfjs-react-native": "^0.6.0"
- React Native 'Flavour': React Native CLI

**Describe the current behavior**
When the code (example below) is executed, the app crashes, but no error is provided, leaving me wondering where to search for help.

**Describe the expected behavior**
Model is loaded.

**Standalone code to reproduce the issue**
```
import * as tf from '@tensorflow/tfjs'
import '@tensorflow/tfjs-react-native'
import { bundleResourceIO } from '@tensorflow/tfjs-react-native'

const modelJson = require('./model.json');
const modelWeights = require('./group1-shard1of1.bin');
console.log(modelJson)
console.log(modelWeights)
model = await tf.loadLayersModel(bundleResourceIO(modelJson, modelWeights));
```

Here are my model.json and group1-shard1of1.bin:
[model_files.zip](https://github.com/tensorflow/tfjs/files/7095160/model_files.zip)

Thank you for your help.

**Comment by konstantinlois** [comment]
I spend some time on debugging this. I created two completetly fresh projects:
1. one project with **npx react-native init**
2. one project with **npx create-react-native-app**

The project using create-react-native-app works, while the project with react-native init does not. For both projects I exactly followed the installation instructions. The only difference was, that create-react-native-app takes care of the installation of 'react-native-unimodules'. For the react-native init project I followed the instructions from the expo docs on how to install the [react-native-unimodules](https://docs.expo.dev/bare/installing-unimodules/). But still the result was: create-react-native-app works, while with react-native init the app crashes once tf code is executed at runtime.

Maybe this has something to do with the recent migration of the react-native-unimodules package indicated [here](https://github.com/unimodules/react-native-unimodules).

Note: As stated above this does not only affect loadLayersModel but seems to be a more general issue. The tests above were conducted using just the folowing code:

```
import React from 'react'
import { View, Text } from 'react-native'
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isTfReady: false,
    };
  }

  async componentDidMount() {
    // Wait for tf to be ready.
    await tf.ready();
    // Signal to the app that tensorflow.js can now be used.
    this.setState({
      isTfReady: true,
    });
  }


  render() {
    return <View>
      <Text>Test</Text>
    </View>
  }
}
```

**Comment by d-kls** [comment]
@konstantinlois i am facing same issue - did you figure out a fix or workaround to this problem?

**Comment by konstantinlois** [comment]
Hi there. This was a very long time ago and I can't really remember how I solved this. I think I went with create-react-native-app in the end.

Hope you solve your problem 👍

**Comment by shmishra99** [comment]
Hi @konstantinlois ,
Thanks for bringing the issue. Could you please confirm if your issue has been resolved or you are still looking for the solution ?

**Comment by konstantinlois** [comment]
For me the issue has been resolved 👍
