### ISSUE TITLE
Propagates NaNs failure on WebGL1

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#5573]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version: 95.0.4629.2 (Official Build) canary (64-bit) (cohort: Clang-64)
- Tensorflow.js Converter Version:

**Describe the current behavior**
Unit test has 14 failures on WebGL1 backend, most of them related to NaN propagation 

**Describe the expected behavior**
All passed

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
`cd tfjs-backend-webgl && yarn && yarn karma start --testEnv webgl1`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Chrome 95.0.4629.2 (Windows 10) step kernel webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} propagates NaNs FAILED
        Error: Arrays differ: actual[4] = 0, expected[4] = NaN.
            at <Jasmine>
            at expectArraysPredicate (C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:77834:23)
            at expectArraysClose (C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:77788:16)
            at C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:65502:28
            at step (C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:65425:23)
            at Object.next (C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:65406:53)
            at fulfilled (C:/Users/haoyunfe/AppData/Local/Temp/karma-typescript-bundle--14664-0rZftuXqFvZf-.js:65397:58)
......

```

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by shmishra99** [comment]
Hi @haoyunfeix 
Apology for the late response. Could you please let us know if your issue has been resolved or you are still looking for the solution ? In order to trouble-shoot the issue, please provide code snippet to reproduce. Thank You!!
