### ISSUE TITLE
How to convert microphone input(arraybuffer/blob/audio in javascript) to tensor for inference at browser?

### ISSUE THREAD

**Issue by neso613** [tensorflow/tfjs#5574]
Hi tensors,
I have recently started working on TensorflowJS. Agenda is to make web app for speech model.
But I am confused and getting stuck, How to preprocess speech(microphone) input?
In python, we have packages to preprocess the input. But how can I convert microphone input ( from browser, it is ArrayBuffer or Blob) into tensors. 

Some suggestions will be very appreciated. Thanks.

**Comment by rthadur** [comment]
please check this codelab https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab#0 , Thank you.
