### ISSUE TITLE
Codelab on Tensorflow js

### ISSUE THREAD

**Issue by timekarma** [tensorflow/tfjs#5575]
https://codelabs.developers.google.com/codelabs/tensorflowjs-nodejs-codelab/#2
Has references to link to tfjs-node is deprecated - this codelab needs to be updated
_Install Node.js and npm. For supported platforms and dependencies, please see the tfjs-node installation guide._

**Comment by rthadur** [comment]
Submitted the change internally , will be updated once the change is merged. Thank you so much
