### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization StringSplitV2, StaticRegexReplace, StringLower, RaggedTensorToTensor

### ISSUE THREAD

**Issue by Electric-Dragon** [tensorflow/tfjs#5577]
**My Environment**

Tensorflow.js version: 3.9.0

Environment: Google Colab GPU Instance

Imported libraries during conversion: tensorflow, tensorflowjs, tensorflow_io, tensorflow_text

---

**Model Structure**

```
model = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(input_dim=len(encoder.get_vocabulary()),output_dim=64,mask_zero=True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(7)
])
```

---

**The Problem**

I tried to convert a tensorflow saved model to a tensorflowjs model with
```
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    /content/drive/MyDrive/textClassificationModel4/ \
    /content/drive/MyDrive/JSModels/textClassificationJS
```

It failed due to unsupported ops

```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 691, in convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 154, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
StringSplitV2, RaggedTensorToTensor, StringLower, StaticRegexReplace
```

---

Can you please help me with this?

**Comment by vladmandic** [comment]
just my $0.02 - like it says, `tensorflowjs_converter` does not support kernel ops used by your model:  
`StringSplitV2`, `RaggedTensorToTensor`, `StringLower`, `StaticRegexReplace`

in reality, those methods are part of `tf.strings` namespace and intended mostly as string handling helper methods  
and not meant to be used inside compiled models

except for `RaggedTensorToTensor` which is part of brand new tensor type - [Ragged Tensor](https://www.tensorflow.org/guide/ragged_tensor) which would be nice to have in TFJS but likely a major effort
(best to open separate enhancement request for that)

**Comment by Electric-Dragon** [comment]
So what should I do now if I want to convert the model to TFJS?

**Comment by pyu10055** [comment]
@Electric-Dragon You can help to contribute these ops to TFJS, similar to these PRs:
https://github.com/tensorflow/tfjs/pull/5089
https://github.com/tensorflow/tfjs/pull/5052

**Comment by Electric-Dragon** [comment]
Any tips on how to contribute and build kernels for certain operations?

**Comment by gaikwadrahul8** [comment]
Hi, @Electric-Dragon 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I see we have implemented [tf.raggedTensorToTensor](https://js.tensorflow.org/api/4.4.0/#raggedTensorToTensor), [tf.staticRegexReplace](https://js.tensorflow.org/api/4.4.0/#staticRegexReplace) but other Ops like `StringSplitV2 `, `StringLower` are not implemented yet May I know are you still looking for `StringSplitV2 `, `StringLower` Ops in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do it and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
