### ISSUE TITLE
Feature Request: Simplify Keras model.fit early exit 

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#558]
Presently to exit a model.fit function you need to make a new class, and call it in the callbacks while training. See [Codepen](https://codepen.io/caisq/pen/xzMYZx?editors=1010) by @caisq 

Look for the code:

```
 class EarlyStoppingCallback extends tf.Callback {
  async onEpochEnd(epoch, logs) {
    status.value = `epoch ${epoch + 1}`;
    await tf.nextFrame();
    if (stopRequested) {
      this.model.stopTraining = true;
    }
  }
}
```

and then while training the code is 

```
  await model.fit(xs, ys, {
    epochs: 1e6,
    callbacks: new EarlyStoppingCallback()
  });
```

The main call from the new class is simply 

```
      this.model.stopTraining = true;
```

but that code does not work from a simple "onEpochEnd" callback from within training. Is a new class really needed to stop the model.fit, or can this functionality be made to work easier?

The code is in [tfjs-layers/src/engine/ training.ts](https://github.com/tensorflow/tfjs-layers/blob/1d0ef06c82cb5ba34bfebbc3b0c3058c2f3f27c4/src/engine/training.ts#L1451-L1464)

```
       if (this.stopTraining) {
            break;
          }
          // TODO(cais): return outs as list of Tensor.
        }

        epochIndexArray1D.dispose();
      }
      // TODO(cais): Run validation at the end of the epoch.
      await callbackList.onEpochEnd(epoch, epochLogs);
      if (this.stopTraining) {
        break;
      }
    }
```

The code allows for the loop to "break", but then the loop just continues.

If someone can suggest a way to simplify this basic ability, I would try to do the PR.

**Comment by caisq** [comment]
Thanks for filing this issue, @hpssjellis. I agree that this will be a worthy enhancement. I will work on this when I have cycles.
