### ISSUE TITLE
Silence CPU feature warnings?

### ISSUE THREAD

**Issue by DABH** [tensorflow/tfjs#559]
#### TensorFlow.js version

tfjs 0.12.3
tfjs-node 0.1.9

#### Browser version

Node 10.6.0

#### Describe the problem or feature request

When I run some code using tfjs+tfjs-node, I get warnings like
```
nsorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this Tenso
```
(sorry, for some reason my code is truncating the warnings).  I guess the point is that the tf build included with tfjs/tfjs-node isn't taking advantage of all the CPU features available on my machine.  Is there any way or option to (a) silence these kinds of warnings, or if not, (b) build and use my own local copy of tf (presumably with optimal compiler settings) and use that with tfjs/tfjs-node?  (I'd strongly prefer option (a)!)  Thanks for any ideas/suggestions!

**Comment by ashbeats** [comment]
you can set the env value before running the script. 

Disables TF's C++ logs: `TF_CPP_MIN_LOG_LEVEL=2`

If you're running node, then you might have another warning for n-api. 

To disable that, 
`node --no-warnings scriptname.js`
