### ISSUE TITLE
support Tensorflow branch control flow ops

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#56]
_From @pyu10055 on March 14, 2018 20:37_

merge https://www.tensorflow.org/versions/r1.2/api_docs/cc/class/tensorflow/ops/merge
switch https://www.tensorflow.org/versions/r1.2/api_docs/cc/class/tensorflow/ops/switch

_Copied from original issue: tensorflow/tfjs-converter#25_

**Comment by pyu10055** [comment]
control flow support is added for release 0.2.0
