### ISSUE TITLE
TFJS TFLite installation with script tags not working

### ISSUE THREAD

**Issue by ClementWalter** [tensorflow/tfjs#5607]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**

I have tried to use the "import via script tag" section from https://www.npmjs.com/package/@tensorflow/tfjs-tflite/v/0.0.1-alpha.2 in a very basic index.html as follows:

```
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>TFJS TFLite</title>
</head>

<body>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite"></script>
</body>

</html>
```

but the `tfjs-tflite` script raises an error:

```
Request URL: https://cdn.jsdelivr.net/npm/@tensorflow/tflite_web_api_cc_simd.js
Request Method: GET
Status Code: 404 
```

**Any other info / logs**

See https://replit.com/@ClementWalter/tfjs-tflite#index.html

**Comment by MartinKolarik** [comment]
This looks like a typical problem with relative path references. If the file loads another file, it needs to be loaded via a fully resolved URL, which in this case is https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.6/dist/tf-tflite.min.js or https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite/dist/tf-tflite.min.js if you don't request a specific version. Then, the requested relative path will be correctly resolved to https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.6/dist/tflite_web_api_cc_simd.js

**Comment by rthadur** [comment]
@MartinKolarik thats correct , please also refer to note here https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite#via-a-script-tag , thank you
