### ISSUE TITLE
Type Error: forwardFunc_1 is not a function

### ISSUE THREAD

**Issue by xczvvdbxgfh** [tensorflow/tfjs#5608]
Type Error: forwardFunc_1 is not a function
when im using toxicity model
this isn't working on node version 16+ but works on other node versions

**Comment by xczvvdbxgfh** [comment]
i managed to fix this

**Comment by alkaaf** [comment]
ummm... may i know what you did?

**Comment by xczvvdbxgfh** [comment]
> ummm... may i know what you did?

i reverted to a different version of npm and somehow this fixed the issue
