### ISSUE TITLE
How do I make a build that uses glibc 2.31

### ISSUE THREAD

**Issue by JosephBotros** [tensorflow/tfjs#5609]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Linux 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): I built tensorflow from source using instructions from https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source
- TensorFlow.js version: N/A
- CUDA/cuDNN version: N/A

**Describe the problem**
I am using a library in Node called face-api and this library is using @tensorflow/tfjs-node. On my local machine (Windows) the app is working fine but after I pushed the code to a VPS with the below information I get `Illegal instruction` when the app requires @tensorflow/tfjs-node. After some research I found that I need to build tensorflow from source. I followed instructions from https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source and after dealing with tons of issues I finally managed to make a build. I had to make the build on a VM because the VPS has low RAM 2GB and the build always fails there. My VPS information:
Processor information	QEMU Virtual CPU version 2.5+, 2 cores
Memory			        2GB
Operating system	        Ubuntu Linux 20.04
Kernel and CPU		Linux 5.4.0-84-generic on x86_64

After I replaced tensorflow in node_modules with the build I made I no longer get `Illegal instruction` but now I get:
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/dan/backend/passport-ai-backend/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/dan/backend/passport-ai-backend/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```
My VPS has glibc v2.31 and I read that it's not safe to just update it since a lot of packages depend on it and the safest way to solve this is to make a new build that uses glibc v2.31.
My problem is that I'm lost and don't know how to make bazel make a build that uses glibc v2.31

**Provide the exact sequence of commands / steps that you executed before running into the problem**
For `./configure` I chose no for all questions and for optimization flags I used `-mtune=generic -mno-avx` because I am building on a VM Virtualbox and I think -mtune=generic is the right flag (unless I'm wrong).
I am using bazel version 4.2.1

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@JosephBotros can you please check if this related isssue https://github.com/tensorflow/tfjs/issues/2872 ?

**Comment by JosephBotros** [comment]
@rthadur thank you, but I don't see how is the issue you tagged is related to my issue.

**Comment by mattsoulanille** [comment]
Hi @JosephBotros. This question seems more related to TensorFlow's build rather than TF.js. I think you'll get better answers from the [TensorFlow forum](https://discuss.tensorflow.org/) or the [TensorFlow GitHub](https://github.com/tensorflow/tensorflow/issues?q=is%3Aissue+is%3Aopen+glibc). 

I took a look at the TensorFlow docs, source code, and a few issues, and I wasn't able to find anything about changing the glibc version. The first thing I would probably try is to build TensorFlow using the same type of image you plan on deploying to, since that should make sure the glibc versions (and others) match.
