### ISSUE TITLE
Remove tslint:disable:max-line-length in tfjs-layers

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#561]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
HEAD

See tslint.json file at: https://github.com/tensorflow/tfjs-core/blob/master/tslint.json#L29

**Comment by hiyashichuka** [comment]
If there is no one else, I would like to work on this issue.

**Comment by hiyashichuka** [comment]
Sorry, Please let me make sure if my understanding in the following is correct.

example tfjs-layers/src/index.ts
 
`// This file lists all exports of TensorFlow.js Layers`
`// tslint:disable:max-line-length    → delete line `
`import * as constraints from './exports_constraints';`
`import * as initializers from './exports_initializers';`
`import * as layers from './exports_layers';`

Delete some line(`// tslint:disable:max-line-length`)  from the tfjs-layers repository
Is it correct?

**Comment by hiyashichuka** [comment]
@nsthorat Thank you! If there is no one else,  I would like to work on this issue.

**Comment by hiyashichuka** [comment]
@nsthorat Thank you! If there is no one else, I would like to work on this issue.

**Comment by nsthorat** [comment]
Go for it :)

**Comment by hiyashichuka** [comment]
@nsthorat @caisq

I sent a pull request. Please validate it

1. tfjs-core　
       - All checks have passed
          https://github.com/tensorflow/tfjs-core/pull/1195

2. tfjs-layers
       - Some checks were not successful　
       - Because 1 not merged
       - I'm sorry, Please tell me how to fix
`ERROR: (max-line-length) /home/travis/build/tensorflow/tfjs-layers/src/errors.ts[17, 1]: Exceeds maximum line length of 80` 

https://github.com/tensorflow/tfjs-layers/pull/276

**Comment by hiyashichuka** [comment]
@nsthorat Thank you.
I am sorry that I didn't understand your intentions correctly.

I would like to confirm the work plans.

1. Close pull request
tensorflow/tfjs-core#1195

2. change " tslint.json of layers" to  " tslint.json of HEAD in core".
modify pull request 
tensorflow/tfjs-layers#276

Is that correct？

**Comment by nsthorat** [comment]
Correct :)

**Comment by hiyashichuka** [comment]
@nsthorat 
I fixed the problems that you pointed out.
https://github.com/tensorflow/tfjs-layers/pull/276

**Comment by hiyashichuka** [comment]
@nsthorat
I got approval from @caisq.
Forgive me for stealing your time. Please validate it
tensorflow/tfjs-layers#276

**Comment by hiyashichuka** [comment]
@nsthorat
I fixed the problems that you pointed out.
Forgive me for stealing your time. Please validate it
tensorflow/tfjs-layers#276

**Comment by hiyashichuka** [comment]
@nsthorat
I removed `// tslint:enable:max-line-length` 
Please validate it
tensorflow/tfjs-layers#276

**Comment by caisq** [comment]
Fixed by https://github.com/tensorflow/tfjs-layers/pull/276

Thanks a lot, @hiyashichuka !
