### ISSUE TITLE
Installing qna model using npm doesn't NOT install the last version of the sources but older version with outdated version of tensorflow

### ISSUE THREAD

**Issue by fbx31** [tensorflow/tfjs#5612]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): tfjs-node
- TensorFlow.js version: 3.9.0
- CUDA/cuDNN version: NA

When installing qna model using npm install @tensorflow-models/qna, the package installed is referencing tensor v1.3.3 and NOT last major release v3.0.0 as indicated inside the last version of the source package.json. I assume NPM registry is NOT referencing the last commit of your sources.

Thanks

**Comment by mattsoulanille** [comment]
Thanks for the issue report, @fbx31. Can you please check that the version of `@tensorflow-models/qna` you've installed is `1.0.0`? `1.0.0` [lists `@tensorflow/tfjs-core` and `@tensorflow/tfjs-converter` as peer dependencies](https://github.com/tensorflow/tfjs-models/blob/master/qna/package.json#L15-L18), so you should be able to (and will need to) install a version of your choice of those packages to use automl.

It's also possible you're using another package that lists core and cpu as dependencies, and that may be why you're seeing them installed at an earlier version than expected.

**Comment by fbx31** [comment]
Hello,
Starting from fresh install, installing @tensorflow/tfjs-node (v3.9.0 OK), then installing qna model doing npm i @tensorflow-models/qna.
I have the version 1.0.0 of the package installed with following peer dependencies:   
  "peerDependencies": {
    "@tensorflow/tfjs-core": "^1.5.2",
    "@tensorflow/tfjs-converter": "^1.5.2"
  },

BUT in github, when i look the package.json in sources of qna, i have the following dependencies:
  "peerDependencies": {
    "@tensorflow/tfjs-converter": "^3.0.0",
    "@tensorflow/tfjs-core": "^3.0.0"
  }

That's why I said that nom package downloaded of qna seems to not be the last commit in github.

Thanks

**Comment by rthadur** [comment]
@fbx31 thats correct , we need a fresh build to npm , @mattsoulanille can you please help push a fresh build to npm ?

**Comment by mattsoulanille** [comment]
My bad! I should have checked the NPM package, not GitHub. We can publish an updated build to NPM.

**Comment by fbx31** [comment]
Thanks a lot, I;ll wait for the update instead of trying to rebuild it by myself :-)
Have a nice day.

**Comment by rthadur** [comment]
Latest changes have been deployed to npm https://www.npmjs.com/package/@tensorflow-models/qna . Please verify.
Thank you @mattsoulanille
