### ISSUE TITLE
tensor dimension need to be 2d

### ISSUE THREAD

**Issue by Cotex05** [tensorflow/tfjs#5613]
https://github.com/tensorflow/tfjs/blob/4dfcd782deda0a9fbe9f3cc5c60bbf4293e14577/tfjs-core/src/ops/diag.ts#L41-L43

Code snippet error on official docs of tensorflowjs [here](https://js.tensorflow.org/api/latest/#diag)

**It should be**
` const x = tf.tensor2d([1, 2, 3, 4, 5, 6, 6, 8], [4, 2])
 tf.diag(x).print()`

**Comment by rthadur** [comment]
Thanks for reporting , submitted a fix
