### ISSUE TITLE
[tfjs-react-native] Can't import tensorflow when creating project with react native CLI

### ISSUE THREAD

**Issue by mmilenkoski** [tensorflow/tfjs#5630]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel C API 30 (Emulator)
- TensorFlow.js installed from (npm or script link): https://www.npmjs.com/package/@tensorflow/tfjs
- TensorFlow.js version: @tensorflow/tfjs@3.9.0
- CUDA/cuDNN version: 11.1

**Describe the problem**
I tried following the instructions for installing tfjs-react-native on a completely new project created with React Native CLI: https://www.npmjs.com/package/@tensorflow/tfjs-react-native.

After completing the installation, I try to import tfjs with these lines in App.js:

`import * as tf from '@tensorflow/tfjs';`
`import '@tensorflow/tfjs-react-native';`

I get the following error:

` ERROR  Error: Cannot evaluate flag 'DEBUG': no evaluation function found.`

This does not happen when I set up the project with Expo instead of the React Native CLI. However, I need to find a fix for the problem because I need tfjs-react-native for an existing project that is not set up with Expo. I initially ran into the same issue on the original project, so this is why I created a blank project to investigate the issue. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Setting up the project:

`react-native init TestProject`
`cd TestProject`
`npm install react-native-unimodules`
`npm install expo-gl-cpp expo-gl`
`npm install expo-camera`
`npm install @react-native-async-storage/async-storage`
`npm i react-native-fs`
`npm install @tensorflow/tfjs`
`npm install @tensorflow/tfjs-react-native`

Then, I import tensorflow in App.js as mentioned above and run the app with:
`react-native run-android`

**Any other info / logs**
Error:
`ERROR  Error: Cannot evaluate flag 'DEBUG': no evaluation function found.`

**Comment by rthadur** [comment]
@mmilenkoski can you please check out similar issue here https://github.com/tensorflow/tfjs/issues/5179#issuecomment-864395043 ?

**Comment by mmilenkoski** [comment]
> @mmilenkoski can you please check out similar issue here [#5179 (comment)](https://github.com/tensorflow/tfjs/issues/5179#issuecomment-864395043) ?

@rthadur thank you for the response! That does solve the issue but is there a way to merge the original metro.config.js file and the changes required from tfjs? Here is my original content:

```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
}
```

**Comment by andrekovac** [comment]
> hey @rthadur, I discovered that the original issue occurs because of the line `inlineRequires: true` in the code from my last comment. My application crashes when I set `inlineRequires: false`, and tfjs fails with the error `ERROR Error: Cannot evaluate flag 'DEBUG': no evaluation function found.` when I set `inlineRequires: true`.
> 
> Is there a way to make tfjs work with `inlineRequires: true`?
> 
> I found this similar issue here: #3889
> 
> Here is how the merged `metro.config.js` looks like:
> 
> ```
> const { getDefaultConfig } = require('metro-config')
> 
> module.exports = (async () => {
>     const defaultConfig = await getDefaultConfig();
>     const { assetExts } = defaultConfig.resolver;
>     return {
>         transformer: {
>             getTransformOptions: async () => ({
>                 transform: {
>                     experimentalImportSupport: false,
>                     inlineRequires: true,
>                 },
>             }),
>         },
>         resolver: {
>             assetExts: [...assetExts, 'bin'],
>         },
>     }
> })()
> ```

Having the exactly same issue with the following versions:

```
"@tensorflow/tfjs": "^3.13.0",
"@tensorflow/tfjs-react-native": "^0.8.0",
```

**Comment by jinjingforever** [comment]
Hi @andrekovac unfortunately `inlineRequires: true` doesn't work for tfjs-react-native now... We will create a separate issue to track that. Thanks for your patience!

**Comment by andrekovac** [comment]
> 

Sounds good! But with `inlineRequires: false` or without the `transformer` field the app crashes as described by the others above.

I just want to get it to run, with or without `inlineRequires`...

**Comment by jinjingforever** [comment]
Hi @andrekovac , please see [here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection) for a working example. I recently updated various dependency versions and the current combination in that app seems to work (tested on iPhone 13 pro and Pixel 2)

**Comment by andrekovac** [comment]
> > @mmilenkoski can you please check out similar issue here [#5179 (comment)](https://github.com/tensorflow/tfjs/issues/5179#issuecomment-864395043) ?
> 
> @rthadur thank you for the response! That does solve the issue but is there a way to merge the original metro.config.js file and the changes required from tfjs? Here is my original content:
> 
> ```
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
>     }),
>   },
> }
> ```

@mmilenkoski Did it work for you with `inlineRequires: false`? I'm getting the same behavior as you do.

**Comment by bobanminic96** [comment]
I couldn't find a concrete answer to the question. Does tensorflow support react-native CLI, or it supports only EXPO projects ? Thanks!

**Comment by niembro64** [comment]
Has this been resolved? 

RN CLI
react-native 0.70.5
