### ISSUE TITLE
Can't run electron application - Getting Uncaught TypeError error message

### ISSUE THREAD

**Issue by gsvin99** [tensorflow/tfjs#5631]
Hi Team,
Kindly help me. I'm developing chatbot application using Angular10 and convert to desktop application using ElectronJS.
For offline chatbot experience, I used tensorflow/tfjs. it working in browser but we loading electron application i'm getting the below attached error message. 

Note: Enabled NodeIntegration (true) in electron application.

Please let me know, if need any other information.

![tensorflow error](https://user-images.githubusercontent.com/67852635/133645276-03f2a5ef-50bd-4af7-ad82-20d2ee1e002f.PNG)
![tensorflow platform](https://user-images.githubusercontent.com/67852635/133645279-fd5dde84-f0ab-4e65-914d-585b7c99d20f.PNG)

I'm using the below mentioned dependencies (package.json)
"dependencies": {
    "@angular/animations": "~10.0.6",
    "@angular/cdk": "^11.2.5",
    "@angular/common": "~10.0.6",
    "@angular/compiler": "~10.0.6",
    "@angular/core": "~10.0.6",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.0.6",
    "@angular/localize": "~10.0.6",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~10.0.6",
    "@angular/platform-browser-dynamic": "~10.0.6",
    "@angular/router": "~10.0.6",
    "@angular/service-worker": "~10.0.6",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "@ng-idle/core": "^10.0.0-beta.1",
    "@ng-select/ng-select": "^6.1.0",
    "@tensorflow/tfjs": "^3.9.0",
    "@types/webgl2": "0.0.6",
    "angularx-qrcode": "^10.0.12",
    "bootstrap": "^4.6.0",
    "compute-cosine-similarity": "^1.0.0",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.5.1",
    "jszip": "^3.5.0",
    "jszip-utils": "^0.1.0",
    "lodash.merge": "^4.6.2",
    "material-design-icons": "^3.0.1",
    "moment": "^2.29.1",
    "net": "^1.0.2",
    "ng-connection-service": "^1.0.4",
    "ng2-file-upload": "^1.3.0",
    "ngx-color-picker": "^11.0.0",
    "ngx-electron": "^2.2.0",
    "ngx-toastr": "^10.0.4",
    "node-jose": "^2.0.0",
    "popper.js": "^1.14.3",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.3.3",
    "sockjs-client": "^1.5.1",
    "stompjs": "^2.3.3",
    "stopwords": "0.0.9",
    "tslib": "^2.1.0",
    "uuid": "^8.3.2",
    "wink-lemmatizer": "^3.0.1",
    "wink-tokenizer": "^5.2.3",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.5",
    "@angular-devkit/build-ng-packagr": "~0.1000.8",
    "@angular/cli": "~10.0.5",
    "@angular/compiler-cli": "~10.0.6",
    "@angular/language-service": "~9.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash.merge": "^4.6.6",
    "@types/node": "^12.19.15",
    "@types/node-jose": "^1.1.5",
    "@types/uuid": "^8.3.0",
    "codelyzer": "^6.0.0",
    "csscomb": "^4.3.0",
    "electron": "^11.2.3",
    "electron-packager": "^15.2.0",
    "husky": "^4.3.8",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }

**Comment by rthadur** [comment]
Did you get chance to check this [link](https://stackoverflow.com/questions/65562209/this-util-textencoder-is-not-a-constructor-only-in-electron-app-works-in-chrome) ? if it does not help please provide a minimal reproduction code.

Thanks 
Rajesh

**Comment by gsvin99** [comment]
The stackoverflow link is not helped me.

While loading application, tensorflow try to set env().setPlatform('node', new PlatformNode());
Here require('util') return null and doesn't have TextEncoder function. It seems, require('util') not refer @type/node component.

export class PlatformNode {
    constructor() {
        // tslint:disable-next-line:no-require-imports
        this.util = require('util');       
        // According to the spec, the built-in encoder can do only UTF-8 encoding.
        // https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/TextEncoder
        this.textEncoder = new this.util.TextEncoder();
    }

**Comment by jinjingforever** [comment]
Hi @gsvin99, I am not super familiar with electron, but I think you probably need to turn off node integration in the renderer process so it can use browser js bundle instead of nodejs bundle. Also, it might help checking out this [tfjs electron example](https://github.com/tensorflow/tfjs-examples/tree/master/electron) (it has not been updated for the newer tfjs versions but its setup might help). It shows you how to use tfjs in renderer process and main process. Hope these can help you. Thanks!

**Comment by gsvin99** [comment]
Thanks @jinjingforever and @rthadur 
Electron application working, after upgrading newer version, disable node integration and enable context isolation.
