### ISSUE TITLE
[webgl] "Switching WebGL + CPU backends" Tests do not Run

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#5632]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 5.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): Local build
- TensorFlow.js version (use command below): Tried on [fe0dcb738daec71f950d93fd466825e21a915e25](https://github.com/tensorflow/tfjs/commit/fe0dcb738daec71f950d93fd466825e21a915e25) and [19ca872919c196787c2fbf9a8aa57000cd12dff0](https://github.com/tensorflow/tfjs/commit/19ca872919c196787c2fbf9a8aa57000cd12dff0).
- Browser version: Chrome 93
- Tensorflow.js Converter Version: n/a

**Describe the current behavior**
[Switching WebGL + CPU backends](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/engine_test.ts#L587-L601) tests do not run when running `karma start` (or `yarn test-dev`) in `tfjs-backend-webgl`. They seem to not run because `_engine.ENGINE.backendNames()` does not contain `webgl` even though the webgl tests are being run.

**Describe the expected behavior**
The above tests run.

**Standalone code to reproduce the issue**
In `tfjs-backend-webgl`, 
```
yarn build-deps
yarn karma start
```
Then, in the Chrome debugger, open `engine_test.js` and set a breakpoint in the `predicate` function of the `Switching WebGL + CPU backends` tests. Check `_engine.ENGINE.backendNames()` and you'll see that `webgl` is missing.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

![webgl-no-test](https://user-images.githubusercontent.com/1474501/133653885-d68894d7-b523-4344-84f3-723895a63ec4.png)

**Comment by pyu10055** [comment]
@mattsoulanille backend webgl register itself in the tfjs-backend-webgl/src/base.ts,
is that file included in the test suite?

**Comment by mattsoulanille** [comment]
@pyu10055 backend webgl does seem to register itself in `base.ts`, but this happens after the engine test runs, which seems to be the wrong order. I'll see if I can get it to run before.

**Comment by gaikwadrahul8** [comment]
Hi, @mattsoulanille 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now and I see this PR https://github.com/tensorflow/tfjs/pull/5562 got merged so May I know have we taken care of this bug with the help of this PR https://github.com/tensorflow/tfjs/pull/5562 please ? 

If yes, Could you please close this issue or have I missed something here ? Thank you!
