### ISSUE TITLE
Refactor the benchmark tool to take finer-grained test spec.

### ISSUE THREAD

**Issue by lina128** [tensorflow/tfjs#5633]
Refactor the preconfigured_browser.json benchmark field to an array of benchmarks, with each benchmark defining config for one model, such as
```
{
    “benchmarks”: [
        “1”: {
            “model”: “mobilenet_v2”,
            “backend”: “webgl”,
            “numRuns”: 10,
            “browsers”: []
        }
        ...
    ] 
}
```
According to this serialization, refactor the benchmarkAll function, which takes in the JSON object of the preconfigured_browser.json file. Make sure the benchmark test still works. And add a test for benchmarkAll to test it can return all results.

**Comment by bolajahmad** [comment]
is there a logic to grouping them togethere?? ... because the way the json object looks, there's nothing tying the models to their configs or backend fields... 

it's not straightforward to refactor this.

**Comment by bolajahmad** [comment]
okay, i think i have more understanding of this now... after reading though what the benchmarkAll function does, my bad i should probably have done that first. 

but then, if i have to pass an array of browsers into each benchmark, won't that make the code very much longer?

**Comment by rthadur** [comment]
Closing this issue as the request is no longer worked on.
