### ISSUE TITLE
Pack texture memory into RGBA instead of just using the R channel.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#564]
Currently, we only use the R channel when we write to memory. In WebGL 1.0, this means we waste 3 * 4 = 12 bytes for every value in our Tensor. In WebGL 2.0, we use R32F which only allocates memory for the R channel, however we don't optimally use the texture memory cache.

Charles wrote a prototype of a packed matrix multiple, where we use all 4 floating point color values in each pixels, packing data into 2x2 grids, to perform a matrix multiply. The packed matmul implementation is a custom shader which will vectorize dot products, but requires us to upload / download data differently for packed textures. Here is the implementation: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/mulmat_packed_gpu.ts

We should investigate packing memory into textures in the following way:
1. Write a pack shader and an unpack shader. When calling matMul, pack the input, call the packed matmul, then run the unpack shader. Let's profile this to see if there are wins in just doing this.

2. Keep all the existing shaders as is, update the shader compiler and samplers to understand how to read from a packed texture, and write to a packed texture. This means each fragment shader will have to do 4x the amount of work, but our memory footprint will be lower. If this is faster, we can explore using this across the board.

2. (alternative) Have packed versions of shaders, and have a bit on the backend texture data which determines the texture format, and when we're about to run a program that expects a packed input, pack the texture.

**Comment by annxingyuan** [comment]
I'm gonna consider this issue resolved by the https://github.com/tensorflow/tfjs-core/pull/1249 PR. Some of the ideas covered in the description have been pulled out into individual issues within the packing milestone: https://github.com/tensorflow/tfjs/milestone/1

But feel free to reopen if I missed something.
