### ISSUE TITLE
Add a complex64 dtype.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#565]
We need this dtype for signal processing, specifically for FFTs for audio, or 2D FFTs for images (if we ever want to do the new fancy decorrelated differential image transformations in this distill [paper](https://distill.pub/2018/differentiable-parameterizations/)).

Since we want this to work in Node.js, we will add a dtype for complex64.

All of the supporting logic will be pushed into the backend, as we want this to work in Node.

We will have to add:
- `tf.complex(real, imag)` taking a real tensor and an imaginary tensor to combine into a single complex64 type
- `tf.real` and `tf.imag` which return the real and imaginary parts respectively.
- `data` and `dataSync` will now returned a flattened array, looking like `[real0, imag0, real1, imag1, ...]`.

For this PR, we should support a simple op to show how it's done, implementing `tf.add` for complex numbers.

Inside the WebGL backend, we will store 2 textures for each of the complex and real parts, these will be cloned during a call to `tf.complex`.

When a shader program is run, we will simply have programs have two texture inputs, e.g. `AReal` and `AImag`, and all the rest of the samplers will work as expected.

**Comment by dsmilkov** [comment]
Would be great to implement a simple op along with this work. E.g. expand tf.add() to work with complex dtypes. This will help get a sense of the changes and how we gradually generalize existing ops.

**Comment by Lewuathe** [comment]
@nsthorat @dsmilkov Do you think this blocks https://github.com/tensorflow/tfjs-core/pull/1191? If so, I want to try this because it's related to spectral ops I implemented.

On the other hand, I think we can support `complex64` later in other ops. In this ticket, just providing a simple example how to generalize with `complex64` like you said for `tf.add()` is sufficient. So supporting `comlex64` can be done later for `tf.fft()` too. What do you think?

**Comment by nsthorat** [comment]
Yes, it blocks it. I am not quite done yet, there are a few things I haven't quite figured out. For this, I plan on supporting add, subtract, and multiply. tf.fft() should take a complex64 tensor and return a complex64 tensor, since this is what TensorFlow does (when we bind via Node.js, we need to have exact parity).

If you want to take a look at this now, you will likely model your complex FFT after the binaryop_complex_gpu, which reads both the real and imaginary parts to generate real and imaginary parts (these are run as two separate programs).

I hopefully will be done with this by tonight / tomorrow night!

**Comment by Lewuathe** [comment]
Thanks for letting me know the current information. I’ll take a look binaryop_complex_gpu then.

**Comment by nsthorat** [comment]
Oops, I actually thought you were commenting on my PR. Here it is: https://github.com/tensorflow/tfjs-core/pull/1213

**Comment by Lewuathe** [comment]
Ah I overlooked the PR. Thanks!

**Comment by nsthorat** [comment]
This is done.
