### ISSUE TITLE
Update to TypeScript 3.0 and modularize the build.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#566]
See blogpost about TS 3.0: https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

We can put a tsconfig in each directory, add `composite` and `references` fields, and we'll have a much faster build (this will be useful for unit test iteration).

**Comment by dsmilkov** [comment]
Let's hold off until we have internal support (google3 infra)

**Comment by nsthorat** [comment]
Update TS version in https://github.com/tensorflow/tfjs-core/pull/1616

Keeping this open to modularize the build.
