### ISSUE TITLE
interoperability - onxx exchange format

### ISSUE THREAD

**Issue by dberardo** [tensorflow/tfjs#5663]
i would like to pre-train network models on the backend using just any other library (i prefer using spark for this operations) band then use the results within the tensor.js Framework in the frontend ...

can this already be achieved somehow? i am talking about importing / deserialization

i think this feature would be a game changer for this library.

**Comment by vladmandic** [comment]
**onnx** provides python package that converts onnx model to tensorflow format,  
check onnx documentation (good starting point is <https://github.com/onnx/onnx-tensorflow/>)  

once model is in tensorflow format, use `tensorflowjs_converter` from python package (maintained by tfjs team) to convert from tf saved model format to tfjs graph model

**Comment by dberardo** [comment]
sounds like a promising approach. i will surely have a look. thanks for the advice. i have tried to find this information on. the official tensorflow.js doc but it seemed to me that only Json (de)serialization was possible, which is not true. . probably a note in the doc to this issue would be good for fiture readers.

**Comment by khanhlvg** [comment]
Here's the guide to convert from TensorFlow model to TF.js for serving in the frontend.
https://www.tensorflow.org/js/guide/conversion

**Comment by gaikwadrahul8** [comment]
Hi, @dberardo 

Apologize for the delayed response and we are re-visiting our older issues and checking whether those issues are resolved or not and May I know above workaround from @vladmandic resolved your issue or not ? 

You can refer our official documentation w.r.t [Model Conversion ](https://www.tensorflow.org/js/guide/conversion) and also refer official documentation of [TensorFlow.js converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) which will help you to resolve your issue and if issue still persists please let us know ? Thank you!
