### ISSUE TITLE
How to save the samples into sample.json and sample-1.webm using tfjs-models/speech-commands

### ISSUE THREAD

**Issue by CatchZeng** [tensorflow/tfjs#5679]
How to save the samples into sample.json and sample-1.webm using tfjs-models/speech-commands like https://teachablemachine.withgoogle.com/train/audio

<img width="691" alt="截屏2021-09-29 下午6 17 00" src="https://user-images.githubusercontent.com/10027281/135250208-9a8db2c0-b8b7-45fc-938e-7951d404991f.png">

<img width="390" alt="截屏2021-09-29 下午6 19 21" src="https://user-images.githubusercontent.com/10027281/135250723-aa8a7bce-5cf2-4c5d-ba41-dad558b318e2.png">

**Comment by ahmedsabie** [comment]
Hey @CatchZeng are you referring to the start / stop buttons in the demo? If so the samples are not stored internally, they are discarded live as predictions are made
