### ISSUE TITLE
Appends domain name when loading wights

### ISSUE THREAD

**Issue by seranus** [tensorflow/tfjs#568]
When loading weight json from a different domain, tensorflow will append the domain name of the site to the shard url, it becomes a issue when the wight files are stored on a different server

It only happens when the site is hosted not on localhost

**Comment by nsthorat** [comment]
Can you show the line of code you are using the load the model?

**Comment by seranus** [comment]
i found what's causing the error, // is being removed from the url so the urls changes to http:/url
