### ISSUE TITLE
inconsistent behavior of `tf.image.cropAndResize`

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5694]
inconsistent behavior of `tf.image.cropAndResize`

[tfjs documentation](https://js.tensorflow.org/api/latest/#image.cropAndResize) for `tf.image.cropAndResize` only states:

> boxes (tf.Tensor2D|TypedArray|Array) 2d float32 tensor of shape [numBoxes, 4]. Each entry is [y1, x1, y2, x2], where (y1, x1) and (y2, x2) are the normalized coordinates of the box in the boxInd[i]'th image in the batch

however, [tensorflow documentation](https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize) explicitly states additional functionality:

> Normalized coordinates outside the [0, 1] range are allowed, in which case we use extrapolation_value to extrapolate the input image values.

when this is attempted in tfjs, it silently does something, but resulting image is not what is expected - and if its later passed to a model for inference, results are wrong

so it should either explicitly guard against coordinates outside 0..1 range or implement it correctly. silently "working", but corrupting output leads to bugs that are difficult to trace

note that this functionality is highly desirable as it eliminates multiple extra steps with padding image before cropping it and even more steps when renormalizing outputs after inference.

environment: tfjs 3.9.0 with webgl backend

**Comment by ahmedsabie** [comment]
@vladmandic The TFJS code does currently support extrapolated coordinates so it might be an edge case, do you have sample input on which it fails by any chance?

**Comment by vladmandic** [comment]
i dont have an original reproduction anymore. i just tried another test and it seems to work - 
padding image and then resizing it produces same result as cropping it with negative values

closing as non-reproducible
