### ISSUE TITLE
When in WASM, tf.conv2d() with ( dtype = "float32" ) and ( dtype = "int32" ), seems wrong.

### ISSUE THREAD

**Issue by ColorfulCakeChen** [tensorflow/tfjs#5696]
**System information**
- Have I written custom code: Yes (in the following gist)
- OS Platform and Distribution: Chroms OS 93.0.4577.95 (64-bits)
- Mobile device (the issue happens on mobile device, too): ASUS ZenPhone Max Pro
- TensorFlow.js installed from: script link
- TensorFlow.js version: 3.9.0
- Browser version: Chroms OS 93.0.4577.95 (64-bits)

**Describe the current behavior**
- When tf.conv2d() with different dtype tensors (input tensor dtype = "float32", filter tensor dtype = "int32"), it seems wrong in backend WASM.
- The issue does not exist, if both input and filter tensors are dtype = "float32".
- The issue does not exist, if in backend CPU or WEBGL.

**Describe the expected behavior**
- Since backend CPU and WEBGL could handle tf.conv2d() with float32 and int32 mixed, backend WASM might also handle it in the same way.

**Standalone code to reproduce the issue**
- https://gist.github.com/ColorfulCakeChen/bd4a28f4610338e1f64980ce2f454bc5
- (The code could be pasted into any example console box of Tensorflow.js API web page (https://js.tensorflow.org/api/3.9.0/) to run.

**Other info / logs** 
<PRE>
filterDType = int32
backend = wasm
Tensor
     [ [[0],]]         // WRONG!
backend = cpu
Tensor
     [ [[100],]]
backend = webgl
Tensor
     [ [[100],]]

filterDType = float32
backend = wasm
Tensor
     [ [[100],]]
backend = cpu
Tensor
     [ [[100],]]
backend = webgl
Tensor
     [ [[100],]]
</PRE>

**Comment by rthadur** [comment]
Thanks for the reproduction code , I was able to reproduce the same.

**Comment by vladmandic** [comment]
possibly related to #5641 which is fixed in main branch.
