### ISSUE TITLE
Compatibility with newer version of react native and expo

### ISSUE THREAD

**Issue by BigZ** [tensorflow/tfjs#5698]
While installing tfjs-react-native on my expo project, i've got this error
```
➜  smartstudio-app git:(feat/A410) ✗ npm install @tensorflow/tfjs-react-native
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: expo-asset@8.3.3
npm ERR! node_modules/expo-asset
npm ERR!   expo-asset@"~8.3.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer expo-asset@"^7.0.0" from @tensorflow/tfjs-react-native@0.7.0
npm ERR! node_modules/@tensorflow/tfjs-react-native
npm ERR!   @tensorflow/tfjs-react-native@"*" from the root project

```
my config
```
   "expo": "^42.0.0",
    "expo-asset": "~8.3.3",
    "expo-auth-session": "~3.3.1",
    "expo-av": "~9.2.3",
    "expo-camera": "~11.2.2",
    "expo-constants": "~11.0.1",
```

i also believe this library not to be comptabile with expo-camera over version 7 while i have version 11.
forcing peer deps doesn't look like a good idea, but maybe we can write dependencies of tfjs-react-native like
    "expo-camera": ">=7.0.0",
if expo does not break api between major version

Thanks a lot for the good work, team !

**Comment by BigZ** [comment]
@byCedric yes, yarn or legacy peer deps work, but signify there should be a change in package.json
Do you think i should do a PR for the change i suggested in my original message ? (ie peerdeps using >= instead of ^)

**Comment by jinjingforever** [comment]
@BigZ that sounds good to me. Thank you!
