### ISSUE TITLE
Add a flag to tfjs-converter: --split_weights_by_layer

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#570]
**Problem**
We ran across a Keras model that has 174 tiny layers, resulting in 174 weight files of the form `group*-shard1of1`. This slows down model loading.

**Proposed solution**
By default, we should create only one weight group and add an optional boolean flag to the tfjs_converter script `--split_files_per_layer`.

```bash
tjs_converter --split_files_per_layer ...
# Will create a weight group for each layer
```

This flag will only be valid for a Keras model. Other suggestions welcome!

**Comment by nsthorat** [comment]
I actually wonder if this should be the default (not putting each layer in their own group). If someone wants to break up weights by layer, they can choose to do that explicitly. I think the case of downloading a subset of weights is much less important than not shipping 174 separate files.

And relevant link where this needs to be changed: 
https://github.com/tensorflow/tfjs-converter/blob/master/python/tensorflowjs/converters/keras_h5_conversion.py#L172-L177

**Comment by dsmilkov** [comment]
I agree with you! You have to be an advanced user with a unique user-case to want to split per layer :)

**Comment by caisq** [comment]
@dsmilkov Woah - 174 files is obviously too many. I agree this needs to be fixed. Thanks for filing this issue. We'll prioritize this.
