### ISSUE TITLE
GPU utilization is very poor on multi-process or concurrently trained models

### ISSUE THREAD

**Issue by asilvas** [tensorflow/tfjs#5704]
**System information**
- TensorFlow.js v3.9.0 (Windows 10), `tfjs-node-gpu`
- Are you willing to contribute it (Yes/No): Possibly if not overly complex changes

**Describe the feature and the current behavior/state.**

On average most model training greatly underutilizes the GPU, due to the nature of how GPU's scale. We all know that large models (tens or hundreds of millions of params) perform far more efficient (ops/watt) than smaller models (< 10M params), that is simply the nature of accelerators. The issue with tfjs is that there is no way for these smaller models to be trained in parallel (across multiple worker processes) OR concurrently with any significant benefits (more on this later).

Let's take a look at the state of parallel vs concurrent training in tensorflow:

**Multi-process**

Multi-process scales linearly in the case of multiple GPU's, but this story is about the utilization of each of those individual GPU's. Due to tfjs lack of memory allocation limits, multi-process training on a GPU is not possible today. The simple solution would be to add a [similar interface to manage memory in Tensorflow 2 core](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth)

**Concurrency**

Unlike multi-process training on a single GPU, concurrent training of models within a single process is actually possible today. In fact I've trained dozens and even hundreds of (<10M param) models, concurrently. While I can't speak to exactly why the performance and GPU utilization is so poor, I've run dozens of simple tests where-in at best I'll see 50-70% **increase** in GPU utilization (not to be confused with total utilization). While these benefits sound nice, it's quite devastating when we're talking sub 10% GPU utilization. It's not clear to me if this is a bug (or design flaw) in tfjs or tfcore, but I see no reason why we should not be able to fully utilize a GPU if we have enough models to saturate the GPU.

Consider this contrived example (based on actual testing):

* I can train a single ~130M param model to exceed 85% of GPU utilization (rtx 3080 ti for reference)
* But training two ~65M param models concurrently will utilize less than 55% of the GPU
* Adding additional ~65M param models may see slightly higher GPU utilization, but never more than 60%
* For even smaller models, any amount of concurrency (even in the hundreds) will never even see 25% utilization

The expectation is that so long as we've not run out of GPU memory, or have some sort of model or CPU inefficiency that prevents full utilization, we should be able to take full advantage of the GPU by running 2 or more models, concurrently.

**Will this change the current api? How?**

1. Enable multi-process GPU training by adding a [similar interface to manage memory in Tensorflow 2 core](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).
2. Resolve concurrency performance -- unclear if this would require an interface change or bug fix

**Who will benefit with this feature?**

This could benefit a lot of engineers, especially those that need to improve GPU utilization with smaller models.

**Any Other info.**

I've put hundreds of hours into tfjs and **love** it! Would love to make tfjs a more serious real-world training solution and a true first-class alternative to Python-based training. Thank you!

**Comment by asilvas** [comment]
Sure thing. Here's a contrived test: https://gist.github.com/asilvas/29c566709d0565a9638b7605ecf8e283

Produced results:

```
node gpu-concurrency-test.js 1
Training 1 x 24M param models took 25194ms, or 25194ms per model
node gpu-concurrency-test.js 2
Training 2 x 24M param models took 45338ms, or 22669ms per model
node gpu-concurrency-test.js 5
Training 5 x 24M param models took 102100ms, or 20420ms per model
node gpu-concurrency-test.js 10
Training 10 x 24M param models took 191775ms, or 19178ms per model
```

Despite using less than 5% of the GPU with a single model, training two concurrently netted only ~11% gains (despite a near idle GPU). Increasing concurrency slightly increases overall throughput, but by very insignificant gains.

I didn't do much testing as I wasn't worried about the usefulness of these test models, but the results were consistent with real-world tests I've done.

**Comment by gaikwadrahul8** [comment]
Hi, @asilvas 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
