### ISSUE TITLE
Is there a way to export the serialized posenet model, in order to import it into python tf

### ISSUE THREAD

**Issue by joaqo** [tensorflow/tfjs#572]
Hey, I've been tinkering with the amazing posenet webapp you guys released, and was recently trying to export the model in order to import it into python keras/tf. I could download the weights and the manifest file, but the latter is missing the `modelTopology` data, so I don't have information about the graph's structure.

I see that tensorflowjs seems to be strictly imperative, as I could not find any reference to a `graph` in tfjs, so I am kinda running out of ideas on how to export the model outside of rewriting it into python by hand.

Do any of you guys have any tips on how to export the model?

Cheers, and thanks for the great project!

**Comment by nsthorat** [comment]
There is no underlying tf.Model instance, we do a custom forward pass using loadWeights directly. This is because we cannot parameterize some of the arguments to the convolution at runtime (and thus have to have a custom forward pass to do so). cc @pyu10055 since we talked about this on another thread.

Unfortunately this means you'd have to do it "by hand", since we also did it "by hand". cc @oveddan who was talking about porting this to python with me yesterday.

**Comment by oveddan** [comment]
Soon after the time PoseNet was launched, @mbotsu created a converter back to Python, and got it working in CoreML:
https://github.com/infocom-tpo/PoseNet-CoreML

Look at [tfjs2python.py](https://github.com/infocom-tpo/PoseNet-CoreML/blob/master/converter/tfjs2python.py)

Once the input is fed forward on this converted model in python, either single or multiple poses needs to be decoded from the outputs.

See the tf.js functions [decodeSinglePose](https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/singlePose/decodeSinglePose.ts) and [decodeMultiplePoses](https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/multiPose/decodeMultiplePoses.ts)

In that same PoseNet-CoreML lib, they [converted it into swift](https://github.com/infocom-tpo/PoseNet-CoreML/tree/master/iOS/PoseNet/Sources)

So if you wanted to write a straight-up python implementation, you could follow the work here and then port the decoding functions to python.

**Comment by joaqo** [comment]
Thanks everyone! I will try and convert the tf.js functions to python and see if I can get mbotu's port working!

**Comment by rytrose** [comment]
Hi @joaqo ! Did you wind up implementing this? I'm about to do so, but if you already have it'll save me some time :)

**Comment by rytrose** [comment]
FWIW, here's a single pose decoder implementation, taking heatmap/offset numpy arrays as input. Sorry I can't link to it on Github, it's in a private repo for schoolwork...

[decode_single_pose.py.zip](https://github.com/tensorflow/tfjs/files/2466867/decode_single_pose.py.zip)

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by swatinair123** [comment]
Hi is there aan implementation for POSenet with tensorflow Python on windows without using core-ML

**Comment by karthee320** [comment]
@rytrose : have you tried the multi pose decoding functionality in python?

**Comment by rytrose** [comment]
@karthee320 I have not, unfortunately, it wasn't needed for my application. :/

**Comment by rwightman** [comment]
@karthee320 @rytrose I ported the multi-pose version to Python over the holidays. Just posted the repo. Seems to be doing something sane but I have not done extensive verification yet. 

https://github.com/rwightman/posenet-python

**Comment by julkar9** [comment]
> @rytrose if you want a script to download the weights, check this out:
> https://github.com/oveddan/posenet-for-installations/blob/master/client/downloadModels.js

is there any way to download new Restnet50 weights file.

**Comment by darcula1993** [comment]
tfjs-posenet model now using a new model format which is hard to extract weights by hand. Looking for some new way to do that............

**Comment by darcula1993** [comment]
> > @rytrose if you want a script to download the weights, check this out:
> > https://github.com/oveddan/posenet-for-installations/blob/master/client/downloadModels.js
> 
> is there any way to download new Restnet50 weights file.

Yes. They are here:

https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/model-stride16.json
https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/group1-shard1of23.bin
.......
https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/group1-shard23of23.bin

---------------------------------------------------------------------------------------------------
just not sure how to extract weights from those .bin files.

**Comment by julkar9** [comment]
> > > @rytrose if you want a script to download the weights, check this out:
> > > https://github.com/oveddan/posenet-for-installations/blob/master/client/downloadModels.js
> > 
> > 
> > is there any way to download new Restnet50 weights file.
> 
> Yes. They are here:
> 
> https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/model-stride16.json
> https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/group1-shard1of23.bin
> .......
> https://storage.googleapis.com/tfjs-models/savedmodel/posenet/resnet50/float/group1-shard23of23.bin
> 
> just not sure how to extract weights from those .bin files.

@oveddan  has done it MobileNetV1 , may be he would be able to help make it offline for ResNet50 weights files .

**Comment by b005t3r** [comment]
Was anyone able to download the single pose models? I feel like I tried every github project at this point and couldn't find a single one using the single-pose models.

**Comment by darcula1993** [comment]
> Was anyone able to download the single pose models? I feel like I tried every github project at this point and couldn't find a single one using the single-pose models.

single pose and multi-pose actually use same model. They just use different method to decode the ouput from that model.
