### ISSUE TITLE
Reducing the size of model 

### ISSUE THREAD

**Issue by NonlinearNimesh** [tensorflow/tfjs#5721]
Hi, I have a frozen model of 96mb and using "quantization 1" I have reduced it to 24MB.

Is there a way to reduce this size further, I want my size to be in between 10-12MB (Preferably 10MB)

Thanks

**Comment by pyu10055** [comment]
Hi @NonlinearNimesh The quantization mechanism of TFJS converter you have used is the main way to reduce the size of TFJS model.  Can you explain what is the purpose of the size reduction? are you looking for smaller transportation size or faster model inference?
If you are just looking for size reduction, and if your web server support gzip for static file serving, the quantized weight file should be reduced further.
