### ISSUE TITLE
Bodypix - Uncaught (in promise) Error: Could not initialize any backends, all backend initializations failed

### ISSUE THREAD

**Issue by drago888** [tensorflow/tfjs#5725]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No (Demo page from bodypix readme - https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu  20.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA (Laptop)
- TensorFlow.js installed from (npm or script link): suspect NPM
- TensorFlow.js version (use command below): 
- Browser version: Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
Javascript Error - Uncaught (in promise) Error: Could not initialize any backends, all backend initializations failed. 
And hang at Loading BodyPix model...

**Describe the expected behavior**
The loading Bodypix model... shall disappear and the webcam screen shall appear

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html

![error](https://user-images.githubusercontent.com/14855901/137252753-f62893f0-0f5f-4b60-bdef-e8545525beca.png)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by drago888** [comment]
Hi Vladmandic,

Thanks for your kind assistance.
It's confirmed to be the video card issue.
I tried loading up on windows 10 for same laptop and able to access same page without any issues.

Sorry that never tried investigating along that line as for another bodypix page, the demo is working on my ubuntu setup.
[](https://qumoptly.github.io/body-pix/)

**Comment by titusfx** [comment]
I've the same problem and It's not always the case.
I tested `Posenet` with `tensorflowjs` with `angular`, I use it on the `app.component`, and it worked. Then I move it to a service ( for obvious reasons, and now the error appears). Going back works perfectly. It looks like something with the bootstrap of the lib and the way they bootstrap with other enviroments.
