### ISSUE TITLE
Support GRU with reset_after=True

### ISSUE THREAD

**Issue by arnaud-secondlayer** [tensorflow/tfjs#5728]
Do you have any plan to support GRU with parameter `reset_after=True`?
The problem today is that tensorflow support only `reset_after=False`, and tensorflow supports only `reset_after=True` for training with GPU.
This means that if we want to use GRU with tensorflowjs, then it's slow to train.

**Comment by gaikwadrahul8** [comment]
Hi, @arnaud-secondlayer 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and if I'm not wrong we haven't implemented [tf.layers.gru](https://js.tensorflow.org/api/4.4.0/#layers.gru) with `reset_after=True` May I know are you still looking for this feature in TFJs ?

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
