### ISSUE TITLE
kMeans in tfjs

### ISSUE THREAD

**Issue by Firenze11** [tensorflow/tfjs#574]
I'm thinking about contributing some k-Means algorithm code I've written in tfjs. Since there are no existing clustering models in tfjs, I guess it could be helpful for users who don't want to write from scratch. Need some pointers about where this piece of code should live.

**Comment by caisq** [comment]
cc @dsmilkov @nsthorat I think having an implementation of the k-means clustering algorithms in tfjs will be nice and useful. I think the best place for it to live is probably the https://github.com/tensorflow/tfjs-models repo. The organization can be similar to the knn-classifier.

@Firenze11 thanks for the proposal. Are you thinking of an API similar to this? https://www.tensorflow.org/api_docs/python/tf/contrib/factorization/KMeansClustering

**Comment by dsmilkov** [comment]
+1. That would be very useful. You have my full support!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
Re-opening this since it's still a good idea :)

**Comment by Firenze11** [comment]
Sent a pull request to `tfjs-models` repo: https://github.com/tensorflow/tfjs-models/pull/407

**Comment by gaikwadrahul8** [comment]
Hi, @Firenze11 

Apologize for the delayed response and I see we have updated our official documentation w.r.t KNN Classifier in TFJs so you can refer our official documentation [here](https://www.tensorflow.org/js/models) and you will find source code for KNN Classifier [here](https://github.com/tensorflow/tfjs-models/tree/master/knn-classifier) if I'm not wrong you were looking the same and we implemented 

If have I missed something here please let me know ? if this feature request we implemented then please feel free to close this issue ? Thank you!
