### ISSUE TITLE
backend tfjs-backend-webgpu correctness is false on e2e|posenet|1024|ResNet50|image

### ISSUE THREAD

**Issue by xhcao** [tensorflow/tfjs#5742]
Steps:
Run Test correctness on e2e posenet model with 1024|ResNet50|image configuration.

Device:
Tiger-Lake.

Result:
Prediction matches GPU is false. actual[score] = 0.615322583793279, expected[score] = 0.6023533163482652

**Comment by rthadur** [comment]
`posenet` has been deprecated and new pose detection model is available [here](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection)  . Thank you
