### ISSUE TITLE
Unsupported Op request BatchMatMul, Prod, ListDiff

### ISSUE THREAD

**Issue by br3nd4n** [tensorflow/tfjs#579]
Per request to file in the documentation, and as a cursory search did not bear fruit; 
it would be lovely if the "BatchMatMul", "Prod" and "ListDiff" ops were implemented.
Thanks!

TensorFlow.js version: Github 2 weeks ago(?)
Describe the problem or feature request: My model uses unsupported ops so can't be converted
Code to reproduce the bug / link to feature request: Modified tacotron rnn, most issues in seq2seq matrix code
Tfjs-conv Output:
Unsupported Ops in the model
BatchMatMul, Prod, ListDiff

**Comment by rthadur** [comment]
Closing the issue as the commit has been pushed here https://github.com/tensorflow/tfjs-converter/pull/209, please feel free to reopen the issue if this has not been addressed.
