### ISSUE TITLE
Support for eye function in conversion

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#5803]
I have a model using tf.eye and it doesn't seem to convert 
https://colab.research.google.com/drive/1UqIRuVstYwOjxgX-sqY_qDJBw2rwpLSC?usp=sharing
Getting this issue ValueError: Unsupported Ops in the model before optimization
MatrixSetDiagV3.

**Comment by gaikwadrahul8** [comment]
Hi, @rohanmuplara 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and It seems like we haven't implemented this Op `MatrixSetDiagV3` yet, If I'm not wrong so May I know are you still looking for this `MatrixSetDiagV3` Op in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
