### ISSUE TITLE
`ModuleNotFoundError` when executing `tensorflowjs_wizard` on tensorflowjs 3.11.0

### ISSUE THREAD

**Issue by Rakagami** [tensorflow/tfjs#5805]
**System information**
- Manjaro Linux x86_64
- TensorFlow installed from anaconda (implicitly thorugh `pip install "tensorflowjs[wizard]"`)
- TensorFlow version : 2.6.0
- Python version: 3.6.13
- CUDA/cuDNN version: cuda_11.4.r11.4
- GPU model and memory: NVIDIA GeForce GTX 1660 Ti, 6GB memory

**Current Behavior**
When I execute `tensorflowjs_wizard`, I get the following output:

```
Traceback (most recent call last):
  File "/home/raka/.conda/envs/tfjs/bin/tensorflowjs_wizard", line 5, in <module>
    from tensorflowjs.converters.wizard import pip_main
ModuleNotFoundError: No module named 'tensorflowjs.converters.wizard'
```

**Expected Behavior**
The expected behavior is the output of the `tensorflowjs_wizard`  command as documented [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md)

**How I currently solved it for me**

Through downgrading tensorflowjs to 3.9.0 I was able to get the command `tensorflowjs_wizard` to **behave as expected**. I downgraded the python packages with the following command:

```
pip install --upgrade tensorflowjs==3.9.0
```

**[Contributing](https://www.tensorflow.org/community/contribute)**

I don't know how to fix this issue because how I solved my issue was through manual downgrading. Maybe someone who knows the code better knows what to do.

**Standalone code to reproduce the issue**

```bash
# Assuming you have already installed conda and are currently in no environment
conda create --name tfjs python=3.6
conda activate tfjs
pip install tensorflowjs[wizard]
# Here you have to refresh the terminal somehow
tensorflowjs_wizard
```

**Comment by pyu10055** [comment]
@Rakagami Thank you for reporting this, will be fixed in the next release.
