### ISSUE TITLE
is:issue is:open UnhandledPromiseRejectionWarning: TypeError: forwardFunc is not a function: need to update package.json version of @tensorflow/tfjs-node

### ISSUE THREAD

**Issue by basicemotions** [tensorflow/tfjs#5816]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
As the error suggests please update your package.json to latest version and include only `tfjs-node` in the packages.Finally run npm install.
