### ISSUE TITLE
Optimize CPU Backend

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#582]
There is a lot of low-hanging fruit in MathBackendCPU - any kernel that uses `tensor.get()` should use flat index to access values. max/avgPool is one example.

See https://github.com/tensorflow/tfjs-core/pull/1210 which optimizes conv2d and other ops for reference.

Here is an example that benchmarks matmul() (modify for your op):

```ts
const ns = [64, 128, 192, 256];
const RUNS = 100;

ns.forEach(n => {
  const a = tf.randomUniform([n, n]) as tf.Tensor2D;
  const b = tf.randomUniform([n, n]) as tf.Tensor2D;
  // Warmup.
  tf.matMul(a, b).dataSync();

  let res: tf.Tensor = null;
  const start = now();
  for (let i = 0; i < RUNS; i++) {
    res = tf.matMul(a, b);
  }
  res.dataSync();
  const elapsed = (now() - start) / RUNS;
  console.log(`N: ${n}: ${elapsed.toFixed(2)} ms`);
});
```

External contributions are welcome!

**Comment by jgartman** [comment]
I'm taking a look at LRN and LRNGrad

**Comment by jgartman** [comment]
I think I'll look at max and avg pool

**Comment by gaikwadrahul8** [comment]
Hi, @dsmilkov 

Apologize for the delayed response and If I'm not wrong we have taken care of this issue with the help of these 02 PR's https://github.com/tensorflow/tfjs-core/pull/1374 and https://github.com/tensorflow/tfjs-core/pull/1235, If have I missed something here, please let me know ? Thank you!
