### ISSUE TITLE
[Codelab]: TensorFlowJS Comment Spam Detection

### ISSUE THREAD

**Issue by SultaniSaid** [tensorflow/tfjs#5823]
Since the file were moved and renamed as to the instructions, this instruction seems outdated: "be sure to replace the MODEL_JSON_URL string value with the path of the model.json file you generated when you uploaded the file to your Glitch assets folder in the prior step"...?

**Comment by jasonmayes** [comment]
On Glitch you need to use the new URL it generates as the CDN is not a relative path to the HTML/CSS/JS app. This is only needed to be done on Glitch. If you are using your own web server eg Apache / Express etc than you can just upload the files without modifying anything and reference the model.json with a relative URL.
