### ISSUE TITLE
Support TFLite models in e2e benchmark

### ISSUE THREAD

**Issue by Honry** [tensorflow/tfjs#5829]
**System information**
- TensorFlow.js version (you are using): 3.11
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Thanks to the [tfjs-tflite API](https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite), we are able to run TFLite models on the Web, and people may want to evaluate the performance. So I suggest to support running TFLite models in e2e local benchmark by using tfjs-tflite API.

we can support [MobileNet V2](https://tfhub.dev/tensorflow/lite-model/mobilenet_v2_1.0_224/1/default/1) as start point. 

**Will this change the current api? How?**
 No

**Who will benefit with this feature?** 
People who want to benchmark the TFLite models / tfjs-tflite API on the Web.

**Any Other info.**
No

cc/ @pyu10055, @jinjingforever, @huningxin

**Comment by pyu10055** [comment]
@jinjingforever can you share your thoughts on what steps are needed to support tflite in benchmark? thanks

**Comment by jinjingforever** [comment]
Yes, I think it is a good idea and it should be possible to add it. Adding it to my TODO list for now. Thanks!

**Comment by Honry** [comment]
Thanks much @jinjingforever!
