### ISSUE TITLE
Cannot get WebGL context in Pop!_OS firefox

### ISSUE THREAD

**Issue by WhatDoor** [tensorflow/tfjs#5839]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes, but not relating to this bug
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pop!_OS 21.04
- TensorFlow.js installed from (npm or script link): HTML Tag
- TensorFlow.js version (use command below): tfjs 3.1.0
- Browser version: Firefox 94.0

**Describe the current behavior**
I am getting the below error: 
Error when getting WebGL context:  Error: Cannot create a canvas in this context

**Describe the expected behavior**
tfjs should be able to get to get WebGL context. I am able to run use my website on chrome on the same machine with no issues.

**Standalone code to reproduce the issue**
Error arises during initialization, so just import tfjs via html tag.

**Comment by josephrocca** [comment]
Unable to reproduce on PopOS 20.04 with Firefox v94:

![image](https://user-images.githubusercontent.com/1167575/141646188-28c938bc-dd35-4e97-9bce-80d747d815f6.png)

https://jsbin.com/wimogumana/edit?html,output

I'm not able to test PopOS 21.04 right now. Have you tried restarting your computer to see if the error persists? I sometimes get problems like this in Chrome (WebGL context lost), but restarting fixes it. I'm not sure whether it's a problem with tfjs or browser WebGL implementation, or nvidia linux drivers.

Are you using a nvidia card? If so, and if the problem persists after restarting, try switching to integrated graphics if available.

**Comment by vladmandic** [comment]
Modern Firefox disables WebGL by itself if it doesnt detect that GPU is adequate - so make sure you're running good display drivers as majority of Linux default ones are anything but ok  

And do a quick test by navigating to <https://get.webgl.org/webgl2/> and <https://webglreport.com/?v=2>

**Comment by WhatDoor** [comment]
Apologies, I made a mistake in the initial post. 

I'm actually having the error when importing tfjs in a webworker. 

`importScripts('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js');`

It is the line above, in a webworker that I have having the issue. 

I assume when it says "Error when getting WebGL context:  Error: Cannot create a canvas in this context", it is referring to the webworker context? I am unsure.

**Comment by vladmandic** [comment]
nothing to do with with **PopOs** or **TFJS**.
by definition, **DOM** is not available in web workers (and **Canvas** is a DOM object)  

alternative is `OffscreenCanvas` that TFJS is happy to use, but Firefox keeps that disabled  
(I have no idea why would they still keep it disabled since it was added years ago)  

navigate to `about:config` and enable `gfx.offscreencanvas.enabled`

**Comment by WhatDoor** [comment]
I've enabled `gfx.offscreencanvas.enabled` but now firefox is crashing whenever I open the page.

**Comment by vladmandic** [comment]
That's up to Firefox. Use some other browser if you want web workers to work.

**Comment by WhatDoor** [comment]
Alright then, thanks for your help.

**Comment by WhatDoor** [comment]
Alright then, thanks for your help.
