### ISSUE TITLE
Blazeface should automatically resize/downsample images before processing if they are bigger than the maximum WebGL texture size for the device

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#5841]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No (it's basically the same as the example code)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android v11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Any
- TensorFlow.js installed from (npm or script link): https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.11.0/dist/tf.js
- TensorFlow.js version (use command below): 3.11.0
- Browser version: Chrome Android v95
- Tensorflow.js Converter Version: 3.11.0

**Describe the current behavior**
An error is thrown if the input image is too big. For my Android device, the error is "Requested texture size [4170x4171] greater than WebGL maximum on this browser / GPU [4096x4096]."

![image](https://user-images.githubusercontent.com/1167575/141647031-9424b4c7-0e3d-41bb-adea-1ded81eb39c1.png)

Note that this is a problem because modern smartphones produce very large images. It's not uncommon for a phone's back camera to produce images with >4k pixels along at least one dimension.

Another type of problem that I get with larger images is a warning: `WebGL: INVALID_VALUE: texImage2D: width or height out of range`, but no error is thrown. Instead, zero face predictions are returned, even though the image has a very obvious face in it. This problem is also resolved by resizing the image to below 4k pixels on both dimensions.

![image](https://user-images.githubusercontent.com/1167575/141647758-02ad3405-b09d-4c8c-a81b-96dd7f2820d7.png)

I can repliably reproduce this but unfortunately I haven't yet made a minimal example to share (please let me know if one is needed). This type of error is worse than the first one because no error is thrown, and the (empty) prediction array is returned. Again, this is revolved by making the image smaller before passing it to Blazeface.

I haven't experienced any errors on my Ubuntu desktop machine. Only Android. I haven't tested iOS devices.

**Describe the expected behavior**
The image should be resized to fit within the device's WebGL limitations so that code reliably works across platforms/devices. For simplicity, it might be a good idea to just detect if it's running on a mobile browser, and in that case resize the image to <=3000px, or something like that. But I'm sure the Blazeface authors will have a better idea on the best approach here, since I don't know much about Blazeface's internals.

**Standalone code to reproduce the issue**
https://jsbin.com/yumutuxomo/edit?html,console,output

(I'm reporting this here since issues aren't enabled on the tfjs-models repo)

**Comment by rthadur** [comment]
Blazeface is deprecated in favor of face-detection model https://github.com/tensorflow/tfjs-models/tree/master/face-detection ,Please check the new model. Thank you
