### ISSUE TITLE
tf.gather is needlessly slow, CPU-intensive

### ISSUE THREAD

**Issue by rotu** [tensorflow/tfjs#5869]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 Home
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): [npm](https://unpkg.com/@tensorflow/tfjs@3.11.0/dist/tf.js)
- TensorFlow.js version (use command below): 3.11.0
- Browser version: Google Chrome 96.0.4664.45
- Tensorflow.js Converter Version: ???

**Describe the current behavior**
`tf.gather` seems disproportionately slow, taking  33x the wall time of `tf.cumsum` with comparably sized input and output. When viewing performance data, runtime seems dominated by uploading and downloading textures, with much of the CPU time spent looping over indices to merely check that they are within range.

It seems also that `tf.gatherND` does not suffer similar performance problems. So replacing ` tf.gather(x,ix)` with `tf.gatherND(x,ix.expandDims(1))` seems an appropriate workaround when gathering on the first axis.

**Describe the expected behavior**
I expect `tf.gather` to perform gathering on the GPU without synchronous operations. Any index checks (if necessary) should be done on GPU.

**Standalone code to reproduce the issue**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script crossorigin="anonymous" src=https://unpkg.com/@tensorflow/tfjs@3.11.0/dist/tf.js></script>
    <script>
        window.addEventListener("load",()=>{
            const x = tf.range(0, 10)
            const ix = tf.randomUniform([50000],0,10).cast('int32')
            for (let i=0; i<1000; ++i){
                tf.tidy(()=>{ tf.gather(x,ix);
                tf.cumsum(ix); })
            }
        })
    </script>
</body>
</html>
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

See screenshot and attached Chrome devtools profile.

![image](https://user-images.githubusercontent.com/119948/142503841-13f871df-ed34-46eb-9d8a-b293589b896a.png)
[Profile-20211118T172039.zip](https://github.com/tensorflow/tfjs/files/7566680/Profile-20211118T172039.zip)

**Comment by qjia7** [comment]
The slowness is caused by reading data back from gpu to cpu for out of bounds checking. We ever talked about it to skip this checking in production mode or do clamping in shader. @pyu10055

**Comment by rotu** [comment]
@qjia7 thanks. that makes sense. I don’t understand your last sentence though.

It would be nice to bring performance in line with `gatherND` by either eliminating bounds checking or doing it in the GPU kernel.
