### ISSUE TITLE
Add DeepTraffic to tensorflowjs website

### ISSUE THREAD

**Issue by MattKovtun** [tensorflow/tfjs#587]
How about creating something simmilar to this
[MIT DeepTraffic](https://selfdrivingcars.mit.edu/deeptraffic/)
and adding this to website

Please add label "website"

**Comment by tafsiri** [comment]
Cool project! I think this is something we probably don't have bandwidth for internally. However if you are interested in working on this @MattKovtun, and are looking for collaborators you could try emailing the mailing list (https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) to see if anyone is interested or working on something similar.
