### ISSUE TITLE
'TensorListFromTensor'

### ISSUE THREAD

**Issue by vdhakad888** [tensorflow/tfjs#5871]
Unhandled Rejection (TypeError): Unknown op 'TensorListFromTensor'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
▶ 22 stack frames were collapsed.
App._this.detectFrame
src/index.js:67
  64 | 
  65 | detectFrame = (video, model) => {
  66 |     tf.engine().startScope();
> 67 |     model.executeAsync(this.process_input(video)).then(predictions => {
     | ^  68 |     this.renderPredictions(predictions, video);
  69 |     requestAnimationFrame(() => {
  70 |       this.detectFrame(video, model);

**Comment by pyu10055** [comment]
@vdhakad888 To assist reproducing the problem, please provide an example in codepen. thanks.

**Comment by ElyorKHodjimetov** [comment]
Good afternoon
I had the same problem who was able to solve it×
Unhandled Rejection (TypeError): Unknown op 'TensorListFromTensor'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
▶ 22 stack frames were collapsed.
App._this.detectFrame
D:/TFJS-object-detection/src/index.js:66
  63 | 
  64 |    detectFrame = (video, model) => {
  65 |        tf.engine().startScope();
> 66 |        model.executeAsync(this.process_input(video)).then(predictions => {
     | ^  67 |        this.renderPredictions(predictions, video);
  68 |        requestAnimationFrame(() => {
  69 |          this.detectFrame(video, model);
View compiled
(anonymous function)
D:/TFJS-object-detection/src/index.js:56
  53 | 
  54 |      Promise.all([modelPromise, webCamPromise])
  55 |        .then(values => {
> 56 |          this.detectFrame(this.videoRef.current, values[0]);
     | ^  57 |        })
  58 |        .catch(error => {
  59 |          console.error(error);

**Comment by ElyorKHodjimetov** [comment]
who was able to solve this problem ? ×
Unhandled Rejection (TypeError): Unknown op 'TensorListFromTensor'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
▶ 22 stack frames were collapsed.
App._this.detectFrame
D:/TFJS-object-detection/src/index.js:66
  63 | 
  64 |    detectFrame = (video, model) => {
  65 |        tf.engine().startScope();
> 66 |        model.executeAsync(this.process_input(video)).then(predictions => {
     | ^  67 |        this.renderPredictions(predictions, video);
  68 |        requestAnimationFrame(() => {
  69 |          this.detectFrame(video, model);
View compiled
(anonymous function)
D:/TFJS-object-detection/src/index.js:56
  53 | 
  54 |      Promise.all([modelPromise, webCamPromise])
  55 |        .then(values => {
> 56 |          this.detectFrame(this.videoRef.current, values[0]);
     | ^  57 |        })
  58 |        .catch(error => {
  59 |          console.error(error);
