### ISSUE TITLE
Better error mesage when the json file is not found 

### ISSUE THREAD

**Issue by zaidalyafeai** [tensorflow/tfjs#588]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
latest
#### Describe the problem or feature request
Better error message when the json file is not found instead of 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
#### Code to reproduce the bug / link to feature request
tf.loadModel('model.json')

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
The error message is much better now as of https://github.com/tensorflow/tfjs-core/pull/1599
