### ISSUE TITLE
how to sole tensorflowjs converter error?

### ISSUE THREAD

**Issue by yunharyu** [tensorflow/tfjs#5888]
i try Keras model.h5 convert tensorflow but i got error
pls help me~
![111111](https://user-images.githubusercontent.com/94977105/143257605-69b33ca7-58f4-4c64-af0c-1b5d4cce023e.PNG)

**Comment by pyu10055** [comment]
@yunharyu looks like the kera h5 model file is not there `/tmp/model.h5`
Seems you are on a windows system, is the path correct for your model?
