### ISSUE TITLE
tfjs-examples/chrome-extension needs to migrate to manifest v3 (phase out begins Jan 17 2022)

### ISSUE THREAD

**Issue by chan1** [tensorflow/tfjs#5889]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
N/A, any OS (I'm using Ubuntu 20.04)
- TensorFlow.js installed from (npm or script link):
Any version used in the tfjs-examples/chrome-extension with  yarn / yarn build.

- Browser version:
Anything at or above Chrome 88

**Describe the current behavior**
This tfjs-example uses manifest v2: https://github.com/tensorflow/tfjs-examples/tree/master/chrome-extension
This blog post: https://developer.chrome.com/blog/mv2-transition/ states that the phase out for manifest V2 begins on January 17, 2022 when developers will no longer be able to submit extensions using manifest V2.

**Describe the expected behavior**
The tfjs-example/chrome-extension is migrated to manifest V3 and continues to work so that developers can continue to use it as a reference to build their own extensions that utilize TFJS. Note, this may require non-trivial work because manifest V3 deprecates background pages and requires service workers (which do not allow for the use of the global: "window"). 

**Standalone code to reproduce the issue**
See this file which states "manifest_version": 2. This now needs to read "manifest_version": 3 since V2 is phasing out starting on January 17, 2022. 
https://github.com/tensorflow/tfjs-examples/blob/master/chrome-extension/dist/manifest.json

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

See: https://github.com/tensorflow/tfjs-examples/tree/master/chrome-extension

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

See the phase out plan announced in this blog post: https://developer.chrome.com/blog/mv2-transition/

**Comment by AyushExel** [comment]
This would be very helpful. I'm trying to integrate tfjs in a chrome extension but manifest v3 doesn't allow using cdn scripts. It would be very helpful if there was a guide for using tfjs in real chrome extensions.

**Comment by jinjingforever** [comment]
Sorry for the delay:) I also added more info in the README. Hopefully it helps. Thank you!

**Comment by AyushExel** [comment]
@jinjingforever thanks! It'll be very helpful

**Comment by AyushExel** [comment]
@jinjingforever One question - can I test extensions without building them? Currently, I can only load an extension from `dist/` because import statements are not allowed in manifestv3

**Comment by jinjingforever** [comment]
Hi @AyushExel in this case you will have to build it first. Like you mentioned, the build process (the bundler) will "inline" those import statements and bundle everything in a single file. It is also possible to use es6 modules directly in the extension but that's not supported out of the box and I haven't tried it myself.
