### ISSUE TITLE
[Codelab]: TensorFlowJS Comment Spam Detection

### ISSUE THREAD

**Issue by jwklomp** [tensorflow/tfjs#5891]
At the end of step 9, when I'm supposed to see 2 numbers printed in the console, I don't see any numbers. I do see the comment I post in the console. (I'm using Glitch)

There are however 2 errors in the console. 

> 20:28:04.953 cdn.glitch.me/group1-shard1of1.bin?v=1637779856621:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> 
> 20:28:04.962 io_utils.js:169 Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
>     at new Float32Array (<anonymous>)
>     at yw (io_utils.js:169)
>     at oT (models.js:334)
>     at models.js:316
>     at u (runtime.js:45)
>     at Generator._invoke (runtime.js:274)
>     at Generator.forEach.t.<computed> [as next] (runtime.js:97)
>     at Wm (runtime.js:728)
>     at o (runtime.js:728)
>

**Comment by jasonmayes** [comment]
It seems your reference to the binary file is incorrect - you have a 404. Please double check the notes in the codelab which explain how to change the model.json file so it works on Glitch CDN - my guess is that this is why you are getting a 404.

Instructions I am referring to are here: https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#7

If you are still having issues after that, please check difference between my working version which can be found here:
https://glitch.com/edit/#!/comment-spam-detection-complete
