### ISSUE TITLE
Convert a Tensorflowjs created model to  TensorFlow Python

### ISSUE THREAD

**Issue by Leonardo16AM** [tensorflow/tfjs#5898]
**System information**
- TensorFlow.js version (you are using): 2.6
- Are you willing to contribute it (Yes/No): No  

**Describe the feature and the current behavior/state.**
Converting a Tensorflowjs created model to  TensorFlow SavedModel, TensorFlow Hub module, Keras HDF5 or tf.keras SavedModel

**Will this change the current api? How?**  
No, only new features  

**Who will benefit with this feature?**
People trying to make training in tensorflowjs

**Comment by rthadur** [comment]
You can convert using tfjs-converter with following command `tensorflowjs_converter --input_format=tfjs_layers_model --output_format=keras path/to/tfjs_files path/to/save_keras_hdf5
` , please check this [thread](https://stackoverflow.com/questions/54242701/how-to-convert-tensorflow-js-model-and-weights-to-standard-tensorflow) for more detailed explanation.
