### ISSUE TITLE
Pac-Man demo should disable training until there are training images. Also better explain what to do.

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#59]
_From @kspviswa on March 30, 2018 19:34_

I tried to clone `tfjs-examples`, installed `yarn` using `homebrew` and did `yarn build` & `yarn watch` to try the **pac-man** demo.

However when I attempt to **train**, I'm hit with below error in console.

![screen shot 2018-03-30 at 12 32 09 pm](https://user-images.githubusercontent.com/7476271/38151050-9259eda6-3416-11e8-81dc-36fcb01d06ea.png)

_Copied from original issue: tensorflow/tfjs-examples#44_

**Comment by dsmilkov** [comment]
_From @tafsiri on March 30, 2018 19:45_

Hi @kspviswa could you give us a bit more system information? What version of crhome and what version of mac os?

Did recording of the samples otherwise work?

**Comment by dsmilkov** [comment]
_From @kspviswa on March 30, 2018 20:13_

I'm using macOS sierra 10.12.5 . Chrome ver Version 65.0.3325.181 (Official Build) (64-bit).
4 GB RAM, 8 CPU.

Whenever hit **train** , am hit with error. What do you mean by "recording of the samples" ?

**Comment by dsmilkov** [comment]
_From @davidsoergel on March 30, 2018 20:15_

Aha, perhaps the UI is not clear enough: before hitting train, you need to first record images of yourself looking up, down, left, and right (or pointing, etc.) by clicking in the squares next to each control button.  Holding the mouse button down collects multiple images.  We see good performance with ~40 each.  Those images are the training data; once they're collected, you can click "train".

**Comment by dsmilkov** [comment]
_From @davidsoergel on March 30, 2018 20:17_

Confirmed if you click train without first collecting training images, you get the above error.

**Comment by dsmilkov** [comment]
_From @kspviswa on March 30, 2018 21:5_

It is taking lot of time to record just 10 samples. Also I'm getting "unresponsive notification" while moving to next direction.

Why does recording takes lot of time? AFAIK it just samples input stream and store an image rite?

Isn't 4GB enough for this example ?

**Comment by dsmilkov** [comment]
_From @nsthorat on March 31, 2018 16:41_

When you're actually recording we're passing it through MobileNet and storing the activation, which helps with the memory footprint as well as time to train.

What do you mean by moving to next direction?

**Comment by PratsBhatt** [comment]
Hello @dsmilkov ,

I hope you are having a good day. I wanted to ask as if this issue was still available?

If yes, then as per my understanding I am listing the work to be done. Kindly correct me if I am wrong.

- The training should only work once there are few images to train.

- Debug why it is taking too much time while collecting training data.

Awaiting your response.

Thanks.

**Comment by rthadur** [comment]
This is very old issue to be triage now , will be closing this. @PratsBhatt please open a new issue if you still same error.
