### ISSUE TITLE
The shape of the output tensor of the conv2d layer is [1,5,-2,-1] when backend is cpu

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5902]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version: 95.0.4638.69 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
On  backend CPU, When the input tensor shape is [1,3,3,1], and `dilationRate` is greater than the width and height of the input tensor (here, `dilationRate is [5,4]`), the shape of the output tensor is` [1,5,-2,-1]`, including `negative` numbers. 
Besides the webgl backend and wasm backend crashed as follows:
the error of webgl:
![image](https://user-images.githubusercontent.com/68681463/143690766-a7546919-24a6-4660-b5a8-f25350b162ca.png)

the error of wasm:
![image](https://user-images.githubusercontent.com/68681463/143690810-a1f4685b-295e-43bb-be73-baad4d71afb6.png)

**Describe the expected behavior**
The shape value of output tensor should be greater than 0. Or Tell everyone the value range of dilationRate.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
```
async function test(backend){
    await tf.setBackend(backend);
    await tf.ready()
    var kwargs={"filters":5,"kernelSize":2,"strides":1,"padding":"valid","dataFormat":"channelsFirst","dilationRate":[5,4]};
    var input_array=new Float32Array(27).fill(0.9);
    var input=tf.tensor(input_array,[1,3,3,3]);
    var layer=await tf.layers.conv2d(kwargs);
    var result= await layer.apply(input);
    console.log(result.shape);

}
async function run(){
    console.log("cpu result:")
    await test("cpu");
    console.log("wasm result:")
    await test("wasm");
    console.log("webgl result:")
    await test("webgl");

}
run();
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by shmishra99** [comment]
Hi @liliquan0118 ,
Apologies for the delay in my response. I was able to replicate the issue you reported using the latest version of `@tensorflow/tfjs@4.4.0`, and I encountered the same error. I have included the code below for reference:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
</head>
<body>
<script>
 async function test(backend){
    await tf.setBackend(backend);
   tf.ready()
    var kwargs={"filters":5,"kernelSize":2,"strides":1,"padding":"valid","dataFormat":"channelsLast","dilationRate":[5,4]};
    var input_array=new Float32Array(27).fill(0.9);
    var input=tf.tensor(input_array,[1,3,3,3]);
    var layer=await tf.layers.conv2d(kwargs);
    var result= await layer.apply(input);
    
    console.log(result.shape);

}
async function run(){
    
  console.log("cpu result:")
    await test("cpu");
    console.log("wasm result:")
    await test("wasm");
    console.log("webgl result:")
    await test("webgl");



}
run();
</script>
</body>
</html>

```
However, I was able to come up with some workarounds to resolve the error messages.
**For the Wasm backend error**, `tfjs-backend-wasm-simd.wasm:0x32a00 Uncaught (in promise) RuntimeError: memory access out of bounds` 
 Could You please change `dataFormat` from `channelsFirst` to `channelsLast` to resolve the error.

**For the Webgl backend error**, The WebGL backend of TensorFlow.js has some limitations, and one of them is that it cannot handle tensor shapes with negative dimensions. I could check the same code in the library. 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/124146945/236422564-be8c47b1-1de5-4270-9d78-6fb77956be96.png">

 I hope this helps! Please let me know if I missed anything or if you have any other questions. Thank you!
