### ISSUE TITLE
For input tensor with shape[1,5,-2,-1], tf.isNaN() can run normally on the cpu backend, while the webgl backend crashes

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5903]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version: chrome 95.0.4638.69 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
When the shape of the input tensor is `[1,5,-2,-1]`, `tf.isNaN() ` runs normally on the `cpu backend` and the `output result is [[],[],[],[],[]]` , And the webgl backend appears as follows crash
![image](https://user-images.githubusercontent.com/68681463/143691863-c56816b9-0891-4c6b-82ee-9af62cf35513.png)
```
async function test(){
    await tf.setBackend("cpu");
    await tf.ready()
    var kwargs={"filters":5,"kernelSize":2,"strides":1,"padding":"valid","dataFormat":"channelsFirst","dilationRate":[5,4]};
    var input_array=new Float32Array(27).fill(0.9);
    var input=tf.tensor(input_array,[1,3,3,3]);
    var layer=await tf.layers.conv2d(kwargs);
    var result= await layer.apply(input); 
    console.log("result shape:"); 
    console.log(result.shape); //[1,5,-2,-1]
    console.log("tf.isNaN result:")
    console.log(tf.isNaN(result).arraySync());
    await tf.setBackend("webgl");
     console.log(tf.isNaN(result).arraySync());
}
test();
```
Here, The tensor with shape [1,5,-2,-1] can be generated by the above code. Because we cannot use `tf.tensor` to generate a tensor whose shape contains negative numbers.  As mentioned in issue https://github.com/tensorflow/tfjs/issues/5902, the output of the conv2d layer, `i.e., result`, has the shape `[1,5,-2,-1]`, and then executes tf.isNaN(result), the `cpu runs normally` and outputs [[],[],[],[],[]], and `webgl crashes`.

You can also reproduce the bug with the following code
```
var tensor=tf.tensor([],[1,0,2,2]);
console.log(tf.isNaN(tensor).arraySync());
```
**Describe the expected behavior**

A reminder should be given that the shape of tensor cannot be negative

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
```
async function test(){
    await tf.setBackend("cpu");
    await tf.ready()
    var kwargs={"filters":5,"kernelSize":2,"strides":1,"padding":"valid","dataFormat":"channelsFirst","dilationRate":[5,4]};
    var input_array=new Float32Array(27).fill(0.9);
    var input=tf.tensor(input_array,[1,3,3,3]);
    var layer=await tf.layers.conv2d(kwargs);
    var result= await layer.apply(input); 
    console.log("result shape:"); 
    console.log(result.shape); //[1,5,-2,-1]
    console.log("tf.isNaN result:")
    console.log(tf.isNaN(result).arraySync());
    await tf.setBackend("webgl");
     console.log(tf.isNaN(result).arraySync());
}
test();
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
This feature has been implemented here https://github.com/tensorflow/tfjs/pull/6743 and will be available in next release. Thank you
