### ISSUE TITLE
The wasm backend crashed "memory out of bounds", while the backend tfjs-node and webgl  was running normally

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5904]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: ThinkPad
- TensorFlow.js installed from (npm or script link): npm and script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version:  Chrome | 95.0.4638.69 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
```
    var kwargs={"filters":2,"kernelSize":3,"strides":2,"padding":"valid","dataFormat":"channelsFirst","dilationRate":1};
    var input=tf.ones([1,3,5,2]);
    var layer =  tf.layers["conv2d"](kwargs);
    var prediction = await layer.apply(input);
```
For the above code, when running on `backend wasm`, it have a crash as follows:
![image](https://user-images.githubusercontent.com/68681463/143865518-a4157ff0-e329-4068-8432-7aed8dc6cbaa.png)

But the backend `webgl `, `cpu`and `tfjs-node` run normally and output the result as follows:
```
Tensor {
kept: false,  isDisposedInternal: false,  shape: [ 1, 2, 2, 0 ], dtype: 'float32', size: 0,strides: [ 0, 0, 0 ],dataId: {},id: 10,rankType: '4', scopeId: 1}
```
**Describe the expected behavior**

all Backends should have same behavior.

**Standalone code to reproduce the issue**
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">

</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"> </script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
<script>
  async function f(){
    await tf.setBackend("wasm");
    await tf.ready();
    var kwargs={"filters":2,"kernelSize":3,"strides":2,"padding":"valid","dataFormat":"channelsFirst","dilationRate":1};
    var input=tf.ones([1,3,5,2]);
    var layer =  tf.layers["conv2d"](kwargs);
    var prediction = await layer.apply(input);
    console.log(prediction);
  }
  f();
</script>
</body>
</html>
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by shmishra99** [comment]
Hi @liliquan0118 ,
Apologies for the delay in my response. i noticed that you are encountering the same issue as mentioned [#5902](https://github.com/tensorflow/tfjs/issues/5902). To resolve this issue, please change the dataFormat parameter in your code from "channelsFirst" to "channelsLast". This should fix the error. Thank you!!
