### ISSUE TITLE
 The output of tf.tensor() is different when dtype is int32 and float32

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5906]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):  script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version:  chrome  95.0.4638.69 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
For uninitialized input array, `tf.tensor(input,"int32")` returns 0, but `tf.tensor (input, "float32")` returns NaN.
```
    var data=new Array(5);
    var i32 = tf.tensor(data, [5], 'int32');
    var f32 = tf.tensor(data, [5], 'float32');
    console.log(i32.arraySync())
    console.log(f32.arraySync())
```
for example, the output of above code is:
![image](https://user-images.githubusercontent.com/68681463/144089486-1ee7a962-20ae-42b6-8f24-10a927e60e0a.png)

**Describe the expected behavior**
For any dtype, the returned result should be the same.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
@liliquan0118 Thank you for reporting this, this seems to be caused by javascript difference between Int32Array and Float32Array:
```
var data=new Array(5);
console.log(new Int32Array(data))
VM301:1 Int32Array(5) [0, 0, 0, 0, 0, buffer: ArrayBuffer(20), byteLength: 20, byteOffset: 0, length: 5]
undefined
console.log(new Float32Array(data))
VM360:1 Float32Array(5) [NaN, NaN, NaN, NaN, NaN, buffer: ArrayBuffer(20), byteLength: 20, byteOffset: 0, length: 5]
```
I would recommend not to use uninitialized array, since the behavior of the system is undefined.
