### ISSUE TITLE
Multiple independent inputs in one model

### ISSUE THREAD

**Issue by davlhd** [tensorflow/tfjs#5909]
This is a general question:
TensorflowJs is complaining that it can not 'Cannot compute the outputs' because its 'Missing the following inputs:'
I only want to execute one input and only get one output. Is this not possible with tensorflowJS?

Sadly my model is not open source so I can not share it with you.

Thanks!

**Comment by rthadur** [comment]
This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
