### ISSUE TITLE
[Feature Request] Ability to transfer tensor to web worker when tensor data is in GPU

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5918]
Typically, to perform TFJS processing inside web worker, I need to gather data in main thread as an array, send it to worker thread (as transferrable object) and then create tensor from it inside worker. And if result is a tensor, do the same in the opposite direction once processing is complete.

But in cases where data in the main thread is already a tensor and already in GPU memory, this creates download GPU->CPU and then re-upload CPU->GPU  

For example, if data is created using
> const image = tf.browser.fromPixels(input);

Feature request is ability to "export" a tensor metadata so it can be "created/imported" in the worker thread - thus creating a tensor that points to the same data already in GPU. Such newly created tensor inside a worker would effectively be a "view" and would not be eligible for deallocation within worker.

This would apply to `WebGL` and `WebGPU` backends when actual tensor data is within GPU memory.

This would enhance usability of web worker based solutions significantly as currently performing the round trip adds significant latency thus limiting processing rate that can be achieved (even if actual processing is really fast)

**Comment by qjia7** [comment]
@vladmandic We are designing a new API to provide an efficient way to expose tensor data to user. [One experimental one](https://github.com/tensorflow/tfjs/pull/5914) is like below:
`function kernelName(img:Tensor2D|Tensor3D|TensorLike):HTMLCanvasElement|OffscreenCanvas`

We will copy the tensor data to a canvas. Then users can use the canvas to do the thing they want. This is still not the final version. But our target is to avoid any gpu->cpu, cpu->gpu copying. Does it satisfy your requirement?

**Comment by vladmandic** [comment]
@qjia7 It's a nice API, but not really related to what i was asking for  

My feature request is about API to export tensor *metadata* so it can be imported by another instance of TFJS while still pointing to same data in GPU

**Comment by qjia7** [comment]
@vladmandic My understanding is you can transfer offscreenCanvas which holds the underlying tensor metadata between web workers. For example, in worker 1, you can use this new kernel API to save the tensor data to an offscreenCanvas. Then transfer the offscreenCanvas to worker 2, in worker 2, once you receive the offscreenCanvas, you can utilize fromPixels to get the tensor from offscreenCanvas. All of these only have gpu->gpu copying if your data is in GPU.

**Comment by vladmandic** [comment]
it's a great improvement, but it still a couple of unnecessary copies if intention (although much faster since its inside gpu) is only to work with tensor in a worker. also, `offscreencanvas` is still not enabled by default in firefox, so it wouldn't apply there.

**Comment by qjia7** [comment]
So is your requirement that webgl/webgpu backends directly expose the texture/buffer to users. And meanwhile the texture/buffer can be as transferrable objects to worker?

Personally I don't think we can do it without any gpu->gpu copying now. And currently both webgl and webgpu don't support transfer gpu resources directly. As far as I know, you have to wrap your gpu resource to an ImageBitmap or offscreenCanvas, then transfer ImageBitmap/offscreenCanvas to the web worker.
In future, when webgpu supports multi-threading, it may support transfer gpu resources to worker.
cc @kainino0x @pyu10055 @lina128

**Comment by vladmandic** [comment]
> So is your requirement that webgl/webgpu backends directly expose the texture/buffer to users. And meanwhile the texture/buffer can be as transferrable objects to worker?

yes. although, not "a requirement", more of "an idea how to make working with web workers with zero latency"

**Comment by vladmandic** [comment]
closing for now as i don't see how this could be implemented since webgl and webgpu context need to be part of canvas which is non-transferrable by definition. yes, offscreencanvas imagedata ownership can be transferred, but not actual context itself.
