### ISSUE TITLE
Instanceof check fails in tf.Model.compile if two different versions are imported

### ISSUE THREAD

**Issue by aman-tiwari** [tensorflow/tfjs#592]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
`~0.12`

#### Browser version
Chrome latest

#### Describe the problem or feature request

If I instantiate a model, and then pass it to a library that calls `model.compile`, passing in its own `tf.Optimizer`, the instanceof check in https://github.com/tensorflow/tfjs-layers/blob/de37e29133e2bc11defd3f5931e9e6afcacb7004/src/engine/training.ts#L745 fails as the library's `tf.Optimizer` is made from a different instantiation of `tfjs`. For some reason, even I'm using `@tensorflow/tfjs: "~0.12"` in both the library and the library consumer's package.jsons, I still get this error.

**Comment by nsthorat** [comment]
@caisq this can be fixed with the same trick we did for tensors https://github.com/tensorflow/tfjs-core/blob/master/src/tensor.ts#L1276

**Comment by caisq** [comment]
@nsthorat Let's chat about how to get this done in tfjs-layers.

**Comment by nsthorat** [comment]
tf.Optimizer is a core method, theoretically this should be solved: https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/optimizer.ts#L80

For any other layers classes, add the Symbol.hasInstance check to verify properties of the instance match what you'd expect on an object of that class.

**Comment by dsmilkov** [comment]
This is fixed by @nsthorat.
