### ISSUE TITLE
TFJS example

### ISSUE THREAD

**Issue by Mmasoud1** [tensorflow/tfjs#5924]
Hello!
May you please point for the right action to add [brainchop.org](https://github.com/neuroneural/neuroneural.github.io) to your examples.

[brainchop.org ](https://github.com/neuroneural/neuroneural.github.io) brings automatic 3D MRI segmentation   capability to neuroimaging  by running a deep learning models in the web-browser on the user side. We released its first version yesterday 06-Dec-2021. 

For online  demo please click [here](http://www.brainchop.org)
Sample data can be download  [here](https://drive.google.com/file/d/10KlnB4ykh_4WG5OmYt0m9BBSfeFCOcPT/view?usp=sharing)

Thank you

**Comment by rthadur** [comment]
Here is the gallery where you can add https://github.com/tensorflow/tfjs/blob/master/GALLERY.md , once it is approved by team.

cc @pyu10055 @jasonmayes

**Comment by jasonmayes** [comment]
Pretty neat demo! Quick question - I noticed when I tried it it takes a while to generate all the imagery - is it recalculating all images in advance? I wonder if it is better to do on the fly as I move my mouse around? Do you know what the inference time is for a single image frame?

While @pyu10055  decides if this is something for gallery.md, we are actually on the Developer Relations side moving new demos to be on https://devlibrary.withgoogle.com/products/ml  where I suggest you submit your demo / code to as well.

Ensure to submit under machine learning category and if asked sub category is "web".  You can see many folk have already submitted as this site is easier to search / find and indexable by search engines etc. Long term this is where we are asking people to add blog posts and demos so they are easier to find vs hidden away in an md file somewhere on a repo :-)

**Comment by Mmasoud1** [comment]
Thank you @jasonmayes for your question and feedback. For best accuracy in neuroimaging 3D MRI data we feed  MeshNet segmentation model with the MRI volume (i.e. 256x256x256) all at once or because of the browser resources limitation we divide this whole volume into sub-volumes or cubes (e.g. 38x38x38) and get the inference of each. Therefore the MeshNet model input layer is 5d e.g. [1, 38, 38, 38, 1]. We created a coordinate tracking algorithm for these cubes to concatenate their 3d output again from the segmentation model. 

We are exiting that we could make this 3D semantic segmentation possible in the browser with this neuroimaging application and using light weighted Meshnet Network. 

I guess and to the best of my knowledge this is could be the first time to run 3D Semantic Segmentation in the browser. We work also on posting a blog soon about the best practices  and challenges associated with that task in the browser.

**Comment by pyu10055** [comment]
@Mmasoud1 Very impressive demo, please feel free to create a PR that updates the gallery.md file with your project. Thanks!

**Comment by Mmasoud1** [comment]
Thank you @pyu10055

**Comment by jasonmayes** [comment]
Oh wow. That is cool! Yes you may indeed be the first to do 3D semantic segmentation in the browser - at least no other demos are coming to mind right now to me from the community that I can think of.

I am curious if it is possible to do say 256x256x1  so the inference is done as the user moves the mouse around the image in the demo and have it work in real time (as this is essentially a single plane ie 2d image) for the part of interest only vs the whole cube of data so to speak? 

I am not an expert in this medical data field though so please let me know if that is not possible - maybe you need some depth to it due to the way it was trained as it uses that in features? Curious to read the blog post to learn more about your design decisions / problems / solutions! Thank you for sharing. Do tag me on Twitter/LinkedIn once you have a blog post etc so I can share to the community.

**Comment by Mmasoud1** [comment]
Good question @jasonmayes. Actually we are not restricted to equal DHW dimensions, and it is possible to set depth to 1. Even though this is not  the best practice for 3D volumetric data such as MRI as you mentioned above,  your idea still can be  helpful with other applications.  

I guess the **difference** between 2D and 3D segmentation is similar to the **difference** between 2D connected components and 3D connected components. If we have a volume and we use 2D connected components with the volume slices it will end up missing many important parts of the volume that appear not connected at some slices while they are actually connected  at other slices. Therefore we have to use here 3D connected components with the volume to not miss these parts.

Thank you again @jasonmayes for that brainstorming, and once we post the blog I will forward to you to share with the community and please feel free to reach me out with my email or  our [feedback](https://docs.google.com/forms/d/e/1FAIpQLScC1UCPAgqwAtx69mi1y_7KmQJ1cV60-J0t4B_pFNehZ2e5Jg/viewform) form for any further questions.

**Comment by jasonmayes** [comment]
I see thank you for explaining! Good to learn new things. Would be great to detail this sort of stuff in your write up to visually show some of these edge use cases and why 3D segmentation is a better solution here that 2D would fail at etc for those of us with less medical/bio backgrounds :-) Thanks again and look forward to seeing the write up! If you share it on social tag it with #MadeWithTFJS so the wider community can find it!

**Comment by Mmasoud1** [comment]
@jasonmayes  We  submitted  also our demo / code to  https://devlibrary.withgoogle.com/products/ml based on your suggestion. Thank you for pointing us.

**Comment by jasonmayes** [comment]
Wonderful thank you!
