### ISSUE TITLE
Can't install @tensorflow/tfjs-node-gpu

### ISSUE THREAD

**Issue by ProgrammingLife** [tensorflow/tfjs#593]
#### TensorFlow.js version
Successfully installed: @tensorflow/tfjs-node@0.1.11
MacOS X 10.12.5
node v9.4.0

#### Describe the problem or feature request
When I run any node.js app that using tfjs I get:

> ============================
> Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
> ============================
But I've already have installed @tensorflow/tfjs-node@0.1.11 and it works fine. But when I try to install tfjs-node-gpu I get a message:
```
$ npm i @tensorflow/tfjs-node-gpu

> @tensorflow/tfjs-node-gpu@0.1.11 install /Users/user/node-projects/node_modules/@tensorflow/tfjs-node-gpu
> node-gyp rebuild

  ACTION binding_gyp_tfjs_binding_target_download_libtensorflow Release/libtensorflow.so
Please submit a valid platform
make: *** [Release/libtensorflow.so] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/node-projects/node_modules/@tensorflow/tfjs-node-gpu
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/user/node-projects/package.json'
npm WARN NewATHSignals No description
npm WARN NewATHSignals No repository field.
npm WARN NewATHSignals No README data
npm WARN NewATHSignals No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node-gpu@0.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node-gpu@0.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

#### Code to reproduce the bug / link to feature request
`$ npm i @tensorflow/tfjs-node-gpu`

**Comment by nkreeger** [comment]
Check the README: https://github.com/tensorflow/tfjs-node

Mac OS does not support CUDA - only Linux w/ CUDA drivers are supported for the @tensorflow/tfjs-node-gpu package.

**Comment by ProgrammingLife** [comment]
I use Hackintosh (with Nvidia GTX 980) so it have CUDA drivers installed and they are work in Adobe After Effects successfully.

**Comment by nkreeger** [comment]
We don't ship a pre-built libtensorflow for Mac OS that has CUDA support. You can roll your own by:

1. Building libtensorflow with CUDA for Mac:
https://www.tensorflow.org/install/install_sources

Bazel build target: 
```
bazel build --config=monolithic //tensorflow/tools/lib_package:libtensorflow
```

2. Updating the get_libtensorflow.js script to use your pre-built binary:
https://github.com/tensorflow/tfjs-node/blob/master/scripts/get_libtensorflow.js#L48

3.) Re-building using yarn.

We don't officially support Mac OS + GPU builds today. However, we are accepting patches to enable this functionality :-)

**Comment by nsthorat** [comment]
@ProgrammingLife did Nick's response answer your question?

**Comment by j2l** [comment]
> 
> 
> I use Hackintosh (with Nvidia GTX 980) so it has CUDA drivers installed and they are work in Adobe After Effects successfully.

I also have a hackintosh,
Could you please share how you installed drivers? 
Thanks @ProgrammingLife !

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
