### ISSUE TITLE
tfjs-v3.12.0 and Wasm 3.12.0 for tfjs-models/pose-detection/ MoveNet multipose wasm

### ISSUE THREAD

**Issue by Didi3333** [tensorflow/tfjs#5932]
When I try to run the demo of the model : tfjs-models/pose-detection/ : https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=movenet

With tfjs-v3.12.0 and Wasm 3.12.0 and configuration model MoveNet type Multipose and backend Wasm i got the following error :

Error: Kernel 'Reciprocal' not registered for backend 'wasm'

![145433791-63df6bdb-87a1-4e08-a7cb-b72e41773c18](https://user-images.githubusercontent.com/32233417/145442149-e4f4c8e7-6c06-417b-92a3-8b591a4b64b1.png)

The demo Woks well for the singlepose type (lightning).

Regards

**Comment by rthadur** [comment]
Hi Na , the demo needs to be updated to latest version https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=movenet and v3.12.0 is complaining about missing op 'Reciprocal'

**Comment by rthadur** [comment]
latest version has been deployed , please verify. I do not see above error for wasm backend.

**Comment by Didi3333** [comment]
Hi @rthadur , 

Issue still present with pose detection 1.0.1 and tfjs 3.13.0

This issue is only with model Movenet Multipose:

tf.setBackend('wasm')

modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING

Still got the pop up of Kernel 'Reciprocal' not registered for backend wasm

![145442149-e4f4c8e7-6c06-417b-92a3-8b591a4b64b1](https://user-images.githubusercontent.com/32233417/153558053-b22c9ee5-920c-4913-a00f-e596338baea0.png)


Please reopen this issue

**Comment by Didi3333** [comment]
Any news regarding this ? Still doesn't work with tfjs 3.15.0

**Comment by rthadur** [comment]
@Didi3333 `reciprocal` has been in this PR https://github.com/tensorflow/tfjs/pull/6992 , this change will be available in next release.
