### ISSUE TITLE
Use bodypix model on react native

### ISSUE THREAD

**Issue by omaraga12** [tensorflow/tfjs#5936]
Hello. I am trying to use tensorflow bodypix model on my app on react native, I want to use it for segment a body person from a local image. Could anyone say me how can I do it? Thank you so much

**Comment by rthadur** [comment]
You can use movenet instead of bodypix , please check out this demo https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection here , thank you

**Comment by omaraga12** [comment]
Thank you so much, I will try it
