### ISSUE TITLE
qna model fails with very short passages

### ISSUE THREAD

**Issue by dalelane** [tensorflow/tfjs#5946]
### recreate/demonstration of the bug

```js
const tfjs = require('@tensorflow/tfjs-node');
const qna = require('@tensorflow-models/qna');

const question = "Who did John see?";
const passage = "John saw Mary";

qna.load()
    .then((model) => {
        return model.findAnswers(question, passage);
    })
    .then((answers) => {
        console.log(answers);
    });
```

This fails with an uncaught exception:
```
(node:2393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'index' of undefined
    at QuestionAndAnswerImpl.convertBack (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:323:34)
    at QuestionAndAnswerImpl.getBestAnswers (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:282:27)
    at QuestionAndAnswerImpl.<anonymous> (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:227:47)
    at step (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:33:23)
    at Object.next (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:14:53)
    at fulfilled (./node_modules/@tensorflow-models/qna/dist/question_and_answer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The above recreate is for Node.js because that was simpler to demonstrate, but I have seen the same errors happen when running in browsers as well. 

For example, if you paste the same question ("Who did John see?") and passage ("John saw Mary") into https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html you'll get the same uncaught exception in your browser console.

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't[u].index')
	(anonymous function) (demo.20d541c6.js:1658:774)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### Expected behavior

This should return an answer (or at least successfully return an empty array).

### Cause

I think the problem is in a check (to see if the indexes are in the known tokens map) failing to take the output offset into account.
https://github.com/tensorflow/tfjs-models/blob/ccfcb2ab9b479b7e053f8eafaf68bd75a71c6551/qna/src/question_and_answer.ts#L277
```js
        if (tokenToOrigMap[start] && tokenToOrigMap[end] && end >= start) {
```

This means the later indexes into the tokens map are not guaranteed safe, and can return undefined. 
https://github.com/tensorflow/tfjs-models/blob/ccfcb2ab9b479b7e053f8eafaf68bd75a71c6551/qna/src/question_and_answer.ts#L336-L339

```js
    const shiftedStart = start + OUTPUT_OFFSET;
    const shiftedEnd = end + OUTPUT_OFFSET;
    const startIndex = tokenToOrigMap[shiftedStart];
    const endIndex = tokenToOrigMap[shiftedEnd];
```

### Suggested fix

I think updating the check to include the output offset should correct the problem. This protects entry into the `convertBack` function so that it is only called with values that will definitely be in `tokensToOrigMap`.

**Comment by dalelane** [comment]
I've put my suggested fix into a pull request in case that helps explain it better!

https://github.com/tensorflow/tfjs-models/pull/888

**Comment by rthadur** [comment]
Thank you @dalelane , I have assigned the reviewer for PR.

**Comment by rthadur** [comment]
Related PR has been merged , closing this issue. Please @mention to reopen if issue still persists.
