### ISSUE TITLE
fromPixels for HTMLVideoElement is slow in Firefox and Safari with WebGL backend

### ISSUE THREAD

**Issue by karelp** [tensorflow/tfjs#5948]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Big Sur, running on Intel i7 Mac Mini (2018), Intel UHD Graphics 630
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.12.0
- Browser version: Firefox 95, Safari 14.1.1
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
Currently when using `tf.browser.fromPixels` on a `HTMLVideoElement` with an mp4 source, this method takes a long time on the WebGL backend (around 7 ms on my machine). According to profiling information from Firefox, most of the time is spent on copying the video data to a temporary canvas. When I disabled this temporary canvas in a custom fork tfjs and sent `HTMLVideoElement` directly to `backend.gpgpu.uploadPixelDataToTexture`, `fromPixels` does not even register in the profiler anymore and overall FPS goes up from 22 to 40 for my use case. I observe the same behavior in Safari, Chrome does not suffer from this issue.

**Describe the expected behavior**
fromPixels does not take 7ms to complete.

**Standalone code to reproduce the issue**
Our team is hitting this problem with mocap4face (https://github.com/facemoji/mocap4face/tree/main/js-example), you can also check a running demo at https://facemoji.co/mocap4face/ and run the Firefox profiling there to see the issue (make sure to check Show Gecko Platform Data in the Profiler settings to better see the canvas copy).

**Other info / logs**
The issue seems to be gone when I comment out [lines 58 to 69 in tfjs-backend-webgl/src/kernels/FromPixels.ts](https://github.com/tensorflow/tfjs/blob/20baee0ac6a39da914c659526bdc67709d700f9d/tfjs-backend-webgl/src/kernels/FromPixels.ts#L58-L69) (the `if (isImage || isVideo) { ... }` ).
Note that the code seems to work fine without this extra condition in all the browsers I tested (even Windows and Mobile ones).

**Comment by rthadur** [comment]
related issue https://github.com/tensorflow/tfjs/issues/5947
