### ISSUE TITLE
Universal Sentence Encoder support for wasm backend

### ISSUE THREAD

**Issue by marcgreen** [tensorflow/tfjs#5950]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 3.11.0
- Are you willing to contribute it (Yes/No): yes, but I don't want to commit to doing it bc I don't yet understand how much work it requires.

**Describe the feature and the current behavior/state.**

I want to use the Universal Sentence Encoder model with a Wasm backend, because I don't have access to webgl and cpu is really slow. According to the [list of supported wasm models](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md), USE is not yet supported.

**Will this change the current api? How?**

I assume not but can't say for sure.

**Who will benefit with this feature?**

Anyone looking to use the USE model with a wasm backend.

**Any Other info.**

**Comment by rthadur** [comment]
@pyu10055 @jasonmayes

**Comment by pyu10055** [comment]
@marcgreen USE is supported by wasm, we will update the readme to reflect that. thanks!
