### ISSUE TITLE
Error: Random seed is not implemented for Orthogonal Initializer yet.

### ISSUE THREAD

**Issue by YagaoDirac** [tensorflow/tfjs#5955]
You probably forgot this.

code:
`let i = tf.initializers.orthogonal({gain:1, seed:12345});`

3.12.0

**Comment by rthadur** [comment]
This will be future request , could you please elaborate your use case.

**Comment by YagaoDirac** [comment]
> This will be future request , could you please elaborate your use case.

I'm still learning tensorflow. I mean, if this is very hard to implement, nvm. If it's not hard to implement, I guess you probably forgot it.

**Comment by gaikwadrahul8** [comment]
Hi, @YagaoDirac 

Apologize for the delayed response and It seems like this issue has been taken care by this PR [#7377 ](https://github.com/tensorflow/tfjs/pull/7377) and it already got merged so I'm closing this issue now, if you need any further assistance on this same issue, please feel free to post your comments or re-open this issue. Thank you for noticing this issue. Thank you!
