### ISSUE TITLE
'this is undefined' error during rollup building

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#5958]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**
When execute `yarn build` command under tfjs-backend-webgpu and tfjs-converter, get warning in cmd console:

```
bazel-out/k8-fastbuild/bin/tfjs-backend-webgpu/src/index.mjs → bazel-out/k8-fastbuild/bin/tfjs-backend-webgpu/tf-backend-webgpu.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
bazel-out/k8-fastbuild/bin/tfjs-backend-webgpu/src/index.mjs
50: }
51: export { webgpu };
52: //# 
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`cd tfjs-backend-webgpu && yarn build`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
Related PR has been merged closing this issue.

**Comment by sivarajakani** [comment]
I'm facing a similar issue.

I used `rollup` to build my JS library

Command: `rollup --config rollup.config.ts --configPlugin @rollup/plugin-typescript`

Tensorflow JS: v4.2.0

> (!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@tensorflow/tfjs-layers/dist/layers/convolutional_recurrent.js
 8:  * =============================================================================
 9:  */
10: var __rest = (this && this.__rest) || function (s, e) {
                  ^
11:     var t = {};
12:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)

Is anyone know to fix this warning?
