### ISSUE TITLE
Multi-Person Pose Estimation Shoulder Detection (problem: Low-Confidence level)

### ISSUE THREAD

**Issue by lugyin** [tensorflow/tfjs#596]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
Version live on PoseNet demo
https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html

#### Browser version
Version 67.0.3396.99 (Official Build) (64-bit)
#### Describe the problem or feature request
There seems to be a huge drop off in shoulders detection between "Single-Pose" and "Multi-Pose". "Single-Pose" is usually around 80% confidence level for shoulders detection but "Multi-Pose" runs at around 5-10% confidence level. Is there a good way to increase the confidence level detection of shoulders when using "Multi-Pose"?

reproduce: https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html

#### Code to reproduce the bug / link to feature request
https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html

**Comment by oveddan** [comment]
My response is here: https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/QnzyLaH_3C0

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
