### ISSUE TITLE
 TypeError: tf.fromPixels is not a function     at loadAndPredict (index.html:89)     

### ISSUE THREAD

**Issue by Shaukat456** [tensorflow/tfjs#5963]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet/ code pen example to reproduce the issue reported here. Thanks!

**Comment by rthadur** [comment]
tf.fromPixels is depreciated please use [tf.browser.fromPixels ](https://js.tensorflow.org/api/3.12.0/#browser.fromPixels) . Thank you
