### ISSUE TITLE
spaceToBatchND_ has non-actionable error message 

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tfjs#597]
I am trying my first model with dilated convolutions.
tfjs-converter worked without complaints, but when trying to run the model I get:

```
Error: input spatial dimensions must be divisible by blockShapes
```
 
looking at the code around it is unclear what action should be taken to fix the problem.

It would be useful to have the error message report the actual values in place, e.g:

```
Error: input spatial dimensions ${dimensions} must be divisible by blockShapes ${blockShapes}
```
and suggest what should be changed to have it fixed.

**Comment by rodrigob** [comment]
@dikatok 
@dsmilkov

**Comment by rodrigob** [comment]
ping ?

**Comment by dsmilkov** [comment]
Thanks - this is great feedback! Do you have some cycles to send us a PR?

**Comment by dikatok** [comment]
Whoops sorry, I missed this issue. Is this resolved yet? If not, I will look into it.

**Comment by rodrigob** [comment]
@dikatok looks like the issue is [still open](https://github.com/tensorflow/tfjs-core/blob/bc7dcbd783577c4f52c6010e34bb0e8da3596944/src/ops/array_ops.ts#L882). So your input is most welcome !

**Comment by dsmilkov** [comment]
Thanks @dikatok

**Comment by stefano-1981** [comment]
Can it be that the failing line
`return a && (b % blockShape[i - 1] === 0);`
should also account for the paddings as mentioned in the comments of the function?

**Comment by dikatok** [comment]
@stefano-1981 yup

I changed the error messages to be more elaborate and included the paddings in the assertion

**Comment by rodrigob** [comment]
Now that the fix is merged I think this issue can be closed.
