### ISSUE TITLE
Model.summary shows output shapes but not input layer shape

### ISSUE THREAD

**Issue by jasonmayes** [tensorflow/tfjs#5978]
Model.summary only shows OUTPUTS from each layer.  When I print model.summary from a model converted from Python it has an "inputs" layer which shows the expected input shape (with no trainable parameters). 

When I train my own model of exactly the same shape using the TFJS layers API (e.g. a single layer of neurons connected to an input, I only get the neuron layer shown in model summary and nothing about the expected input shape.

This is an issue for people trying to use other folks models that may lack documentation (quite common). How is a user expected to find the expected INPUT tensor shape if they did not make the model themselves? 

Instead model.summary should in addition to showing each layer's outputs, assume the input layer is a special case and show its shape too at the start for any model. Can be represented as an "input layer" and what its outputs would be to keep with the current table structure of the print out.

See the two prints of model summary below. First  one is a model made in tfjs in browser. The second one is a converted model from python with the same shape.

![unnamed](https://user-images.githubusercontent.com/4972997/148111230-cc3f1faa-9804-4670-b1ac-b39c1ed1c71e.png)

**TensorFlow.js version (you are using):** 3.11.0

**Will this change the current api? How?**
No. This is fixing existing code.

**Who will benefit with this feature?**
Everyone who is trying to use a model that does not have an explictly defined inputs layer (which is most models) and trying to understand what shape of Tensor to pass to it.

**Comment by pyu10055** [comment]
the feature has been added by @shivangchopra11
