### ISSUE TITLE
"Unknown op 'NonMaxSuppressionV5'. 

### ISSUE THREAD

**Issue by avinashnair02** [tensorflow/tfjs#5981]
![rednode](https://user-images.githubusercontent.com/48132861/148208358-fb188ca9-0071-420b-b3a8-84dd64378897.PNG)
![tensor](https://user-images.githubusercontent.com/48132861/148208629-b881eed2-871f-4757-9d19-c3f6cbfda152.PNG)

**Comment by avinashnair02** [comment]
Log details:


"Unknown op 'NonMaxSuppressionV5'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()"

**Comment by rthadur** [comment]
The above op is supported in all backends , which version of tfjs you are using ?

**Comment by psychopath811** [comment]
The tfjs version used  for training the model is 2.4.0 and the converter version was 3.12.0.

**Comment by avinashnair02** [comment]
The tfjs version is 1.5.1

**Comment by rthadur** [comment]
> nodered

please try to use latest latest version , this has been added to all backends , please check this [doc](https://docs.google.com/spreadsheets/d/1D25XtWaBrmUEErbGQB0QmNhH-xtwHo9LDl59w0TbxrI/edit#gid=0) for ops implemented in different background.
