### ISSUE TITLE
e.Hands is not a constructor when creating detector with hand pose detector model in tfjs and mediapipe runtime

### ISSUE THREAD

**Issue by cocoalasca** [tensorflow/tfjs#5996]
**System information**
Chrome Mac OS
Tensorflow.js and hand pose libraries imported through CDN

https://cdn.jsdelivr.net/npm/@mediapipe/hands
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl
https://cdn.jsdelivr.net/npm/@tensorflow-models/hand-pose-detection

**Describe the current behavior**

when I use the function handPoseDetection.createDetector using the mediapipe runtime chrome shows the following error on the console. 

promise error TypeError: e.Hands is not a constructor
    at new t (hand-pose-detection:17)
    at hand-pose-detection:17
    at hand-pose-detection:17
    at Object.next (hand-pose-detection:17)
    at hand-pose-detection:17
    at new Promise (<anonymous>)
    at o (hand-pose-detection:17)
    at l (hand-pose-detection:17)
    at Object.<anonymous> (hand-pose-detection:17)
    at hand-pose-detection:17

**Describe the expected behavior**

The detector is created without error

**Standalone code to reproduce the issue**

Import the following libraries through CDN:

<script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
 <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
 
 <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
 <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/hand-pose-detection"></script>

Run the following script:

let modelTemp = handPoseDetection.SupportedModels.MediaPipeHands;
      handPoseDetection.createDetector(modelTemp, {
        runtime: 'mediapipe', // or 'tfjs'
        maxHands:2,
        modelType:'full',
      }).then((detector)=>{
        console.log("promise response",detector);
      }).catch((err)=>{
        console.log("promise error",err);
      });

****Other Logs****
Im using the documentation from https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/src/mediapipe . Also when y run the code in tfjs runtime it works fine

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
