### ISSUE TITLE
Examples should generate ES6+ code.

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#60]
_From @nsthorat on March 16, 2018 19:57_

It would be nice to have examples generate ES6+ code so we can actually debug and not deal with async/await polyfills which make the call stack quite muddled.

_Copied from original issue: tensorflow/tfjs-examples#14_

**Comment by dsmilkov** [comment]
_From @QuantumInformation on March 31, 2018 8:33_

Aren't ts sourcemaps good enough?

**Comment by shiffman** [comment]
Just want to pop in here to say that at ITP we are working on a higher level library built on top of tensorflow.js called "ml5":

https://ml5js.github.io/

Right now the library is mostly a set of examples for using pre-trained models, but it's my goal with the library to integrate beginner friendly JS examples with both training and inference that address this barrier. Contributions to our repos are welcome!

**Comment by QuantumInformation** [comment]
@hpssjellis I think that most of this trouble will be felt by python devs migrating to the js ecosystem not used to the js tools like babel and webpack etc.

I have my own examples using webpack.

**Comment by QuantumInformation** [comment]
@tafsiri I tried using typescript to generate es6 modules that could be imported with type="module" but not sure if they implemented it yet.

Basically, I wanted `import foo from "foo"` to be outputted as `import foo from "foo.js"` maybe @kenhowardpdx knows.

**Comment by QuantumInformation** [comment]
I also tried debugging one of the tfjs-examples, but the sourcemaps worked poorly, I'm not sure if its the babel runtime. Webpack works fine.

**Comment by hpssjellis** [comment]
@tafsiri 

In reply to:

> @hpssjellis I think we will be adding at least one example which doesn't use a build system at all ... As @QuantumInformation has pointed out we are definitely getting some python devs who are new to web development and run into the same thing....one thing we have been targeting is allowing the examples to be written in modern javascript (const, async/await etc), while being able to run on a wide range of browsers (including some that don't natively support those features).... I personally see some advantages to using build tools,



I am fine with whatever you guys do. Your software is so amazing, however in your move to support old browsers and make modern Javascript and Python Developers comfortable, you might be losing many thousand regular Javascript programmers if you only support build tools.

As an example, I am very familiar with the Ubuntu operating system and use Cloud9 at  http://c9.io in my classroom. I tried and gave up several times to get Node.js to play nicely with Yarn.

Yarn was not working and I had to check the package.json to find out that it needed "node": ">=8.9.0"

It then took me several days of unsuccessful nodejs installs to find out that I simply needed the command 

`nvm install 8`

for Cloud 9 to allow node 8.11.1 to be activated, which was needed for yarn 1.5.1 to work.

 A typical self-taught Windows Javascript programmer would have given up hours before I did.


However, on a positive note, if you don't show many pure Javascript examples it gives @shiffman 's [ml5](https://ml5js.github.io/docs/getting-started.html) , [myself](http://rocksetta.com/) and a few others  a very nice little Pure Javascript Machine Learning niche.

My main Tensorflowjs Javascript site is at: 

https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/

**Comment by tafsiri** [comment]
Just updating this to say we just added a no transpile examples: https://github.com/tensorflow/tfjs-examples/tree/master/getting_started, you should be able to just edit the js file and open index.html in your browser. A local webserver is also available via yarn for when folks want to start getting local files into their pojects. Hope this helps!

Great observation on the niche it leaves other in the community to targeting/optimize for people of different experience and backgrounds! We def can't do this all on our own.
