### ISSUE TITLE
Use async functions in N-API

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#600]
All Node.js binding APIS are currently blocking - to take full advantage, the APIs should ship async and non-blocking.

**Comment by kgryte** [comment]
Is this implying that **all** Node.js APIs which call down into `libtensorflow` should be async? Or that such APIs should also be available in **both** sync and async flavors? If the former, this seems biased toward server contexts, where not blocking the main thread is of greater importance; however, such non-blocking behavior is less important in non-server analysis contexts (e.g., scripting) where procedural code is more desirable for reasons of readability and maintainability.
