### ISSUE TITLE
Update to the latest mediapipe facemesh model for tfjs?

### ISSUE THREAD

**Issue by hongzimao** [tensorflow/tfjs#6002]
**System information**
- TensorFlow.js version (you are using): 3.11.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The latest mediapipe facemesh model supports asymmetric facial expression and has a stunning performance on tracking the mouth area. Here's a quick demo as of Jan 10 2022: https://codepen.io/mediapipe/full/KKgVaPJ (turn on the refine landmarks option). This is a huge improvement over the current pretrained model on tfjs, which can't track the facial expression as lively: https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_facemesh. I notice that tfjs landmark detection has been more than 1 year old on npm. Since tfjs landmark detection is using mediapipe facemesh underneath (constructor API attached below), would be great if we can update to the latest model: 
```
const model = await faceLandmarksDetection.load(
    faceLandmarksDetection.SupportedPackages.mediapipeFacemesh)
```

**Will this change the current api? How?** 
No. It should be a swap of the underlying model to the latest one.

**Who will benefit with this feature?**
Everyone who uses the facemesh module with tfjs. As shown in the link above, the model performance is visually much much better with the latest mediapipe facemesh release. Yet the inference time is almost identical.

**Comment by rthadur** [comment]
I see the changes are already merged here https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/src and will pushed to npm soon. Thank you for your patience!

**Comment by vladmandic** [comment]
can you clarify?

last published `facemesh` model is quite old and hasn't changed  
- <https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1>

updated model is **facemesh-with-attention**, but afaik that is **tflite** only and requires *mediapipe's* **custom wasm backend** for inference as model relies on several custom ops to achieve attention  
- <https://mediapipe.readthedocs.io/en/latest/solutions/face_mesh.html#attention-mesh-model>

(specifically, ops are `transform_landmarks`, `transform_tensor_bilinear`, `landmarks_to_transform_matrix` and only implementation for them is C++ based one in mediapipe backend)

or did i miss something and there really is a new `facemesh` model that i cannot find?

**Comment by vladmandic** [comment]
I'll test them, but this is getting really confusing.

for example, "new" `facemesh-detection` models are called "short" and "full" and they are based on `blazeface` "front" and "back" models, but what are the differences? what is "new" about them?

and new `facemesh-landmarks-attention` model is produced how? original mediapipe model uses custom ops, so this is ported to tfjs somehow, but no notes whatever.

not to mention little notes there are not correct as model does not produce 478 points as stated in the model notes, but instead produces many many more as each attention step produces separate output tensor which then needs to be mapped over original points, but again no docs.

i hate doing so much reverse-engineering when dealing with anything from mediapipe as docs are non-existent or incorrect.

**Comment by vladmandic** [comment]
update:
- new `facemesh-detection-full` has LOWER resolution (192 vs 256) vs old `blazeface-back` and generates far noisier output (2304 vs 896 candidates). neither i consider positive, so unless there is clear documentation why its better i'm skipping it.
- new `facemesh-landmarks` seems identical in every way to the old one except its quantized to f16 by default
- new `facemesh-landmarks-attention` does work without custom kernel ops and it does so almost as fast as standard landmarks model. but model output is totally undocumented (each attention sub-model produces separate output tensor which maps to what?), so will take some time to reverse-engineer it to something useful.

**Comment by vladmandic** [comment]
Why is butter adding stale when correct status is waiting for TFJS team to provide information?

**Comment by ahmedsabie** [comment]
@vladmandic The relevant models for face mesh are [here](https://tfhub.dev/s?q=face_landmarks_detection). As you mentioned it does provide a large number of outputs, which is why we offer the high level [package](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection) to do the post processing.

If you have a specific issue about the documentation please create a new issue, the original issue was asking about the release of the package which is complete
