### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by sayem314** [tensorflow/tfjs#6007]
**Describe the current behavior**

Decoding image faling

**Describe the expected behavior**

Decoding image should work

**Standalone code to reproduce the issue**

```
import tfnode from '@tensorflow/tfjs-node';
const tfimage = tfnode.node.decodeImage(buffer) as tfnode.Tensor3D;
await model.detect(tfimage);
```

**Comment by rthadur** [comment]
please try to use `const tf = require('@tensorflow/tfjs-node');` to import node package.

**Comment by sayem314** [comment]
> please try to use `const tf = require('@tensorflow/tfjs-node');` to import node package.

I’m using typescript so cannot really do that

**Comment by sayem314** [comment]
> can you please check this [doc](https://www.tensorflow.org/js/tutorials/setup#typescript) , see if it helps.

Already tried and nothing

**Comment by rthadur** [comment]
Can you please share sample code to reproduce the error , and also please share your package.json. Thank you
