### ISSUE TITLE
@tensorflow-models/body-segmentation not available on NPM registry

### ISSUE THREAD

**Issue by alvaroschipper** [tensorflow/tfjs#6008]
I would like to try the new tfjs wrapper around mediapipe's Selfie Segmentation model [available now in the tfjs-models repo](https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation/src/selfie_segmentation_mediapipe). 

The installation steps ask you to install `@tensorflow-models/body-segmentation` into your project but this package doesn’t seem to be available on the NPM registry. So I'm wondering if I'm missing something or am I just a bit early to the party and it hasn’t been published as a package yet?

Please share any info you have on the status of this package, it would be greatly appreciated. 😃

**Comment by ahmedsabie** [comment]
We haven't released it yet, once you see it on the NPM site it will be ready to use :)

**Comment by alvaroschipper** [comment]
Alright, I will attempt to build the package myself in the meantime, thank you @ahmedsabie!
