### ISSUE TITLE
How to use data kept on GPU after model inference with tensorflow.js v3.13.0?

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [tensorflow/tfjs#6014]
Hi! I've just been aware of the new feature to keep data on GPU with tfjs v3.13.0 made by @lina128 and I am very excited to try it!

However, I'm a bit confused on how to use it, since I cannot use the texture directly in my shader. From what I understand, I need to provide the canvas on which I will run my shader to the declaration of the WebGL backend, but I currently don't declare any backend... Instead, I use the `setBackend(string)` method from `@tensorflow/tfjs-core`.

How should one declare the WebGL backend to which provide they would provide the canvas?

I've also created a question on StackOverflow, if that is the preferred way of proceeding.
https://stackoverflow.com/questions/70703710/how-to-use-data-kept-on-gpu-after-model-inference-with-tensorflow-js-v3-13-0

Thanks

**Comment by lina128** [comment]
Hi, we will provide an example in tfjs-example shortly. Likely next week.

**Comment by RaphaelRoyerRivard** [comment]
Thank you @lina128. I'm hoping I will be able to find out how to do it myself by then, since this is what is being prioritized at work at the moment. But if I can't, I will gladly read your example!

**Comment by RaphaelRoyerRivard** [comment]
Hi @lina128. I was able to create my own `MathBackendWebGL` and use it with
```
const customBackendName = 'custom-webgl';
const kernels = getKernelsForBackend('webgl');
kernels.forEach(kernelConfig => {
  const newKernelConfig = { ...kernelConfig, backendName: customBackendName };
  registerKernel(newKernelConfig);
});
const backend = new MathBackendWebGL(canvasForWebglBackend);
registerBackend(customBackendName, () => backend);
setBackend(customBackendName);
```
But when I try to bind the texture on the webgl context of the same canvas, I still get the error
```
WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context
```
Any idea why that might happen?

**Comment by RaphaelRoyerRivard** [comment]
I think I might have found the reason, my shaders use a `webgl` context, but tfjs might use a `webgl2` context. Is it the case?

**Comment by RaphaelRoyerRivard** [comment]
I was able to get the custom `MathBackendWebGL` to use my canvas' context by creating a `GPGPUContext`, but then the following error appears twice when loading the model.
```
[.WebGL-0x7fb0b16bc400]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: invalid internalformat/format/type combination GL_LUMINANCE/GL_LUMINANCE/GL_FLOAT
```
And then I get a texture on the first inference call, but it never gets updated on the following calls...
Do you have an ETA on when the documentation might be ready @lina128? I could really use it right now. Thanks

**Comment by lina128** [comment]
Hi @RaphaelRoyerRivard, the documentation should be ready by end of this week.
re: pass in canvas failure: I will look into this. Glad the other way (passing in context) works for you.
re: mix webgl and webgl2 context: You can only have one context per canvas.
re: GL_INVALID_OPERATION error: My context use this config and it works, can you try it?
const WEBGL_ATTRIBUTES = {
    alpha: false,
    antialias: false,  // has to be false, otherwise ERROR :GL_INVALID_OPERATION
    premultipliedAlpha: false,     // can be true or false
    preserveDrawingBuffer: false,  // can be true or  false
    depth: false,
    stencil: false,
    failIfMajorPerformanceCaveat: true,
    powerPreference: 'low-power'
  };

**Comment by RaphaelRoyerRivard** [comment]
Hi @lina128, thanks for your answer.
Unfortunately, when I use these attributes to create the `webgl2` context provided to the `GPGPUContext` used by the custom `MathBackendWebGL`, I get the same webgl error when loading the `EXT_color_buffer_float` webgl extension in the [constructor of `GPGPUContext`](https://github.com/lina128/tfjs/blob/6c6a3cf4235b560a90c7300c51ce795ef46c4e3c/tfjs-backend-webgl/src/gpgpu_context.ts#L89).

However, I am not sure if that causes my main issue, which is that the texture generated by the first model inference never gets updated on the subsequent inferences...

**Comment by lina128** [comment]
Each model inference generates use new texture, you need to dispose the old texture by tensor.dispose(). It will cache the texture for reuse.

**Comment by RaphaelRoyerRivard** [comment]
Hmmm, I am already disposing of the Tensor for which I call `dataToGPU`, but I dispose of it before I use the texture. Can this be a problem?

**Comment by lina128** [comment]
That's fine. You also need to call the tensor referenced by the result of dataToGPU, res.tensorRef.dispose().

**Comment by RaphaelRoyerRivard** [comment]
I am now also disposing of the tensorRef, but the texture still doesn't get updated unfortunately.

**Comment by lina128** [comment]
Let's try to rule out code error first. If you feed in a video stream, and just have a pass through shader and render on canvas, does it show the video (with changing contents)?

**Comment by RaphaelRoyerRivard** [comment]
Thanks a lot for your help, it is very appreciated.

I found the source of the error, which was caused by the creation of a texture in my code, but it's only showing the error when the context is webgl2 instead of webgl. I was able to avoid the error by using `gl.UNSIGNED_BYTE` instead of `gl.FLOAT` as the data type of the texture. I got confuse on what caused the error because I did not change my code to create textures and the errors shows up around 1 second after the code is ran.

What I feed the neural network with is a small OffscreenCanvas on which I draw a resized down version of the input stream. I am positive this part works well (at least with the default webgl backend). Then, previously I was calling `.data()` on the output tensor to get an array of data that get drawn onto a texture that get drawn on another OffscreenCanvas with a shader. Now, instead of calling data and drawing it on a texture, I use the texture generated by tfjs. However, it never updates.

**Comment by RaphaelRoyerRivard** [comment]
I found that if I stack 4 times my single channel output tensor before calling `dataToGPU({customTexShape: [height, width]})`, then I get the texture in the right format. So now the only thing that is left to fix is the texture that do not get updated.

**Comment by RaphaelRoyerRivard** [comment]
@lina128 please make sure you notify me when the documentation get released, I want to read it as soon as possible! :) Thanks

**Comment by RaphaelRoyerRivard** [comment]
After some more tests, I see that the `tensorRef` in the `GPUData` object returned by the `dataToGPU` call is not the same in the second inference as it is in the first, but the `texture` in the `GPUData` object is the same (validated with `===`). However, the `dataId` from which the texture gets fetched is not the same...

I have tried calling `dispose()` on the `tensorRef` before using the texture, also tried after, but to no avail. I also tried getting rid of the texture with `gl.deleteTexture`, still didn't help to get the texture to update between model inferences...

**Comment by lina128** [comment]
Hi @RaphaelRoyerRivard, you can reference this draft PR: https://github.com/tensorflow/tfjs-examples/pull/675

**Comment by RaphaelRoyerRivard** [comment]
Thanks Lina! I will try to change my shaders so they look more like yours.

**Comment by RaphaelRoyerRivard** [comment]
Got it working with your shader code! Hard to know what I was doing wrong before though since there were many different things between our shader programs. Thanks again :)

**Comment by lina128** [comment]
Glad it works. Good luck with your project, @RaphaelRoyerRivard !
