### ISSUE TITLE
npm install @tensorflow/tfjs-tflite for Reactjs project ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tfjs#6017]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version:  2.4.1
- CUDA/cuDNN version: 11.0

**Describe the problem**
I ran the command npm install @tensorflow/tfjs-tflite for an existing Reactjs project from VS code terminal but tfjs-tflite failed to install apparently due to dependency issue.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

npm install @tensorflow/tfjs-tflite
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @tensorflow/tfjs-core@3.6.0
npm ERR! node_modules/@tensorflow/tfjs-core
npm ERR!   peer @tensorflow/tfjs-core@"^3.3.0" from @tensorflow-models/coco-ssd@2.2.2
npm ERR!   node_modules/@tensorflow-models/coco-ssd
npm ERR!     @tensorflow-models/coco-ssd@"^2.2.2" from the root project
npm ERR!   peer @tensorflow/tfjs-core@"^3.6.0" from @tensorflow-models/pose-detection@0.0.1-rc.2
npm ERR!   node_modules/@tensorflow-models/pose-detection
npm ERR!     @tensorflow-models/pose-detection@"*" from the root project
npm ERR!   6 more (@tensorflow-models/posenet, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @tensorflow/tfjs-tflite@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @tensorflow/tfjs-core@3.11.0
npm ERR! node_modules/@tensorflow/tfjs-core
npm ERR!   peer @tensorflow/tfjs-core@"3.11.0" from @tensorflow/tfjs-tflite@0.0.1-alpha.8
npm ERR!   node_modules/@tensorflow/tfjs-tflite
npm ERR!     @tensorflow/tfjs-tflite@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\me\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Local\npm-cache\_logs\2022-01-14T08_10_49_432Z-debug.log

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

 C:\Users\me\AppData\Local\npm-cache\_logs\2022-01-14T08_10_49_432Z-debug.log:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '@tensorflow/tfjs-tflite'
0 verbose cli ]
1 info using npm@7.10.0
2 info using node@v16.0.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\me\Documents\proj\AI Service\ReactJS\Birdy\.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\me\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\me\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 7ms
18 timing npm:load:configload Completed in 7ms
19 timing npm:load:setTitle Completed in 1ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 14ms
25 timing config:load:flatten Completed in 2ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 809ms
28 timing idealTree:userRequests Completed in 3ms
29 silly idealTree buildDeps
30 silly fetch manifest @tensorflow/tfjs-tflite@*
31 timing arborist:ctor Completed in 0ms
32 http fetch GET 200 https://registry.npmjs.org/@tensorflow%2ftfjs-tflite 2669ms
33 silly fetch manifest @tensorflow/tfjs-core@^3.6.0
34 http fetch GET 200 https://registry.npmjs.org/@tensorflow%2ftfjs-core 7ms (from cache)
35 silly fetch manifest @tensorflow/tfjs-core@3.11.0
36 timing idealTree Completed in 3502ms
37 timing command:install Completed in 3513ms
38 verbose stack Error: unable to resolve dependency tree
38 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1210:25)
38 verbose stack     at Arborist.[placeDep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1313:32)
38 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:904:46
38 verbose stack     at Array.map (<anonymous>)
38 verbose stack     at Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:904:8)
38 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:217:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:134:5)
38 verbose stack     at async Install.install (C:\Program Files\nodejs\node_modules\npm\lib\install.js:137:5)
39 verbose cwd C:\Users\me\Documents\proj\AI Service\ReactJS\Birdy
40 verbose Windows_NT 10.0.19043
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@tensorflow/tfjs-tflite"
42 verbose node v16.0.0
43 verbose npm  v7.10.0
44 error code ERESOLVE
45 error ERESOLVE unable to resolve dependency tree
46 error
47 error Found: [1m@tensorflow/tfjs-core[22m@[1m3.6.0[22m[2m[22m
47 error [2mnode_modules/@tensorflow/tfjs-core[22m
47 error   [35mpeer[39m [1m@tensorflow/tfjs-core[22m@"[1m^3.3.0[22m" from [1m@tensorflow-models/coco-ssd[22m@[1m2.2.2[22m[2m[22m
47 error   [2mnode_modules/@tensorflow-models/coco-ssd[22m
47 error     [1m@tensorflow-models/coco-ssd[22m@"[1m^2.2.2[22m" from the root project
47 error   [35mpeer[39m [1m@tensorflow/tfjs-core[22m@"[1m^3.6.0[22m" from [1m@tensorflow-models/pose-detection[22m@[1m0.0.1-rc.2[22m[2m[22m
47 error   [2mnode_modules/@tensorflow-models/pose-detection[22m
47 error     [1m@tensorflow-models/pose-detection[22m@"[1m*[22m" from the root project
47 error   6 more (@tensorflow-models/posenet, ...)
47 error
47 error Could not resolve dependency:
47 error [1m@tensorflow/tfjs-tflite[22m@"[1m*[22m" from the root project
47 error
47 error Conflicting peer dependency: [1m@tensorflow/tfjs-core[22m@[1m3.11.0[22m[2m[22m
47 error [2mnode_modules/@tensorflow/tfjs-core[22m
47 error   [35mpeer[39m [1m@tensorflow/tfjs-core[22m@"[1m3.11.0[22m" from [1m@tensorflow/tfjs-tflite[22m@[1m0.0.1-alpha.8[22m[2m[22m
47 error   [2mnode_modules/@tensorflow/tfjs-tflite[22m
47 error     [1m@tensorflow/tfjs-tflite[22m@"[1m*[22m" from the root project
47 error
47 error Fix the upstream dependency conflict, or retry
47 error this command with --force, or --legacy-peer-deps
47 error to accept an incorrect (and potentially broken) dependency resolution.
47 error
47 error See C:\Users\me\AppData\Local\npm-cache\eresolve-report.txt for a full report.
48 verbose exit 1

**Comment by rthadur** [comment]
@FlyWong could please let us know what steps you have followed , can you check this [post](https://stackoverflow.com/questions/65549858/eresolve-unable-to-resolve-dependency-tree-when-installing-npm-react-facebook) for the error reported above . Thank you

**Comment by rthadur** [comment]
also please share your package.json . Thank you

**Comment by FlyWong** [comment]
Hi all,

running 'npm install @tensorflow/tfjs-tflite --legacy-peer-deps', in VS Code terminal works for me.

Thanks,
Raymond
________________________________

**Comment by FlyWong** [comment]
issue resolved
