### ISSUE TITLE
is:issue is:open It would be cool if you had a gpu acceleration option 

### ISSUE THREAD

**Issue by legitjumpingspider** [tensorflow/tfjs#6025]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by vladmandic** [comment]
?

it does, both for **node** (using `tensorflow` backend via `tfjs-node-gpu`) and **browser** (using `webgl or `webgpu` backends)

**Comment by rthadur** [comment]
please check here https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md for gpu acceleration. Thank you
