### ISSUE TITLE
"v[(b.tfliteWebApiName + "_ModuleFactory")] is not a function error" when trying to load tflite custom model with "await tflite.loadTFLiteModel('net_pass.tflite')"

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tfjs#6026]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: On Windows PC debugging from VS Code
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below):
- Browser version: Version 97.0.4692.71
- Tensorflow.js Converter Version: 3.13.0

**Describe the current behavior**

I am trying to load a custom tflite model into my ReactJS project. This custom tflite model is already in use in another Android App. I was in debugging mode when I noticed the error after the sample loading code was ran:

const tfliteModel = await tflite.loadTFLiteModel('net_pass.tflite');

Full error as below:

Uncaught TypeError: v[(b.tfliteWebApiName + "_ModuleFactory")] is not a function
<anonymous> @ c:\Users\path\ReactJS\proj\node_modules\@tensorflow\tfjs-tflite\dist\tflite_web_api_client.js:1683

push../node_modules/@tensorflow/tfjs-tflite/dist/tflite_web_api_client.js.$jscomp.generator.Engine_.nextStep_ @ c:\Users\path\ReactJS\proj\node_modules\@tensorflow\tfjs-tflite\dist\tflite_web_api_client.js:31
push../node_modules/@tensorflow/tfjs-tflite/dist/tflite_web_api_client.js.$jscomp.generator.Engine_.next_ @ c:\Users\path\ReactJS\proj\node_modules\@tensorflow\tfjs-tflite\dist\tflite_web_api_client.js:27
next @ c:\Users\path\ReactJS\proj\node_modules\@tensorflow\tfjs-tflite\dist\tflite_web_api_client.js:32
b @ c:\Users\path\ReactJS\proj\node_modules\@tensorflow\tfjs-tflite\dist\tflite_web_api_client.js:33
◀ await ▶
setupProgramParam @ c:\Users\path\ReactJS\proj\src\index.js:3723
app @ c:\Users\path\ReactJS\proj\src\index.js:4436
<anonymous> @ c:\Users\path\ReactJS\proj\src\index.js:4810
./src/index.js @ localhost꞉3000/static/js/main.chunk.js:3949:30
__webpack_require__ @ c:\Users\path\ReactJS\proj\webpack\bootstrap:851
fn @ c:\Users\path\ReactJS\proj\webpack\bootstrap:150
1 @ localhost꞉3000/static/js/main.chunk.js:4358:18
__webpack_require__ @ c:\Users\path\ReactJS\proj\webpack\bootstrap:851
checkDeferredModules @ c:\Users\path\ReactJS\proj\webpack\bootstrap:45
webpackJsonpCallback @ c:\Users\path\ReactJS\proj\webpack\bootstrap:32
<anonymous> @ localhost꞉3000/static/js/main.chunk.js:1:59

**Describe the expected behavior**

Custom model to be loaded and use in prediction for object appearing in  html <video> element

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

import * as tflite from '@tensorflow/tfjs-tflite';

const tfliteModel = await tflite.loadTFLiteModel('net_pass.tflite');

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

package.json:

{
  "name": "t-v",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@capacitor/android": "3.0.0",
    "@capacitor/cli": "^3.0.0",
    "@capacitor/core": "^3.0.0",
    "@tensorflow-models/coco-ssd": "^2.2.2",
    "@tensorflow-models/pose-detection": "*",
    "@tensorflow-models/posenet": "^2.2.2",
    "@tensorflow/tfjs": "^3.7.0",
    "@tensorflow/tfjs-backend-cpu": "^3.6.0",
    "@tensorflow/tfjs-backend-wasm": "^3.6.0",
    "@tensorflow/tfjs-backend-webgl": "^3.6.0",
    "@tensorflow/tfjs-converter": "^3.13.0",
    "@tensorflow/tfjs-core": "^3.6.0",
    "@tensorflow/tfjs-tflite": "*",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.1",
    "browserify-fs": "^1.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "stats-lite": "^2.2.0",
    "web-vitals": "^1.0.1",
    "write-file-p": "^1.0.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

tflite model file as attached
[net_pass.zip](https://github.com/tensorflow/tfjs/files/7878753/net_pass.zip)

**Comment by FlyWong** [comment]
Hi,

May I know what is the current status? Do I need to provide anymore information?

**Comment by jinjingforever** [comment]
Hi @FlyWong thank you for the report. The problem is in our internal build system. To fix this, we will work on moving that to open source which might take some time.. But it is on my todo list and will update this issue when there is progress. Thank you for your patience.

**Comment by FlyWong** [comment]
Hi Jing Jin,

we are hoping to use this in our demo in about 1 months' time. Do you think there is a realistic chance for the issue to be resolved?

If not, is there any alternative for us to import custom tflite models into tensor.js for object detection?

I am fine if the steps are more cumbersome or technical. We just want to get things moving here.

Thanks,
Raymond

________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong I will take a look at it this week. The main thing is that I need to spend some time learning ReactJs:) 

BTW, just to make sure: are there any custom ops in your model?

**Comment by jinjingforever** [comment]
Hi @FlyWong,

tfjs-tflite uses WASM behind the scene. **By default, it will try to load the wasm related files from the directory where the main bundled js file is served.** For now, this step will always happen (we plan to add an option to disable this behavior). Failing to load won't affect the rest of the program. The message you saw essentially means that it cannot find this file. If you go into the "network" tab, and you will see that the app is trying to load `http://localhost:3000/static/js/tflite_web_api_cc_simd.js` but failed.

To fix it, you need to let tfjs-tflite know where to load the WASM files by calling the `tflite.setWasmPath` function at the beginning of the app. After this path is set, `tflite.loadTFLiteModel` will load the wasm files from this path.

```js
import './App.css';
import { useEffect } from 'react';

import * as tflite from '@tensorflow/tfjs-tflite';

// Call this function.
tflite.setWasmPath(
   'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.8/dist/'
);

function App() {
  useEffect(async () => {
    const tfliteModel = await tflite.loadTFLiteModel(
      'https://tfhub.dev/sayakpaul/lite-model/cartoongan/fp16/1'
    );
    console.log(tfliteModel);
  }, []);

  return <div className='App'>test</div>;
}

export default App;
```

If you want to serve those wasm files from your own server, copy the following files to the `public` folder and call `tflite.setWasmPath` accordingly. For example:

```bash
mkdir -p public/tflite_wasm
cp -rf node_modules/@tensorflow/tfjs-tflite/dist/tflite_web* public/tflite_wasm
```

Then,
```js
tflite.setWasmPath('tflite_wasm/');
```

Again, the error message you saw will **still show up** in both of these solutions, and it is OK. If you want to completely get rid of the error message, you will just need to make sure those wasm files I mentioned are always put together with the main js file (after it is bundled), for both dev server and production server. I am sure there are some webpack magic out there that can make this happen:)

**Comment by FlyWong** [comment]
Hi,

May I know how to create WASM file? I don't know much about it. And since it seems optional previously, I ignored it :p

Thanks



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jinjingforever** [comment]
Hi, you don't need to create them. We have the compiled wasm files bundled in the npm package already. You can list them here:

```bash
ls node_modules/@tensorflow/tfjs-tflite/dist/tflite_web*
```

If you are talking about how to build them in general, check out https://emscripten.org/.

**Comment by jinjingforever** [comment]
Note that having these files ready for your app is a requirement (not optional) for tfjs-tflite to work. It is just that it will try to find them from a default path initially. Failing that doesn't matter.

**Comment by FlyWong** [comment]
Hi,

Thanks, I am able to move past the model loading stage after running

tflite.setWasmPath(
  ***@***.******@***.***/dist/'
);


I am still not able to confirm if the model is running correct as I got the following error after I continued with the example on

***@***.***/tfjs-tflite

I am running the codes from the Run Inference section

const img = tf.browser.fromPixels(document.querySelector('img'));
const input = tf.sub(tf.div(tf.expandDims(img), 127.5), 1);

// Run inference and get output tensors.
let outputTensor = tfliteModel.predict(input);

(do note I have to make a slight modification as I got compilation error when I tried to run 'let outputTensor = tfliteModel.predict(input) as tf.Tensor;' Compiler error was semicolon expected after tfliteModel.predict(input) )

However, I got this error:

Unhandled Rejection (Error): Input tensor shape mismatch: expect '1,384,384,3', got '1,1088,1920,3'.

TFLiteModel.setModelInputFromTensor
C:/Users/raywl/tfjs-tflite/src/tflite_model.ts:203
  200 | if (!tensor.shape.every(
  201 |         (dim, index) => modelInputShape[index] === -1 ||
  202 |             modelInputShape[index] === dim)) {
> 203 |   throw new Error(`Input tensor shape mismatch: expect '${
      | ^  204 |       modelInput.shape}', got '${tensor.shape.join(',')}'.`);
  205 | }
  206 |
View compiled
TFLiteModel.predict
C:/Users/raywl/tfjs-tflite/src/tflite_model.ts:104
  101 |         inputTensors.length})`);
  102 |   }
  103 |   for (let i = 0; i < modelInputs.length; i++) {
> 104 |     this.setModelInputFromTensor(modelInputs[i], inputTensors[i]);
      | ^  105 |   }
  106 | }
  107 | // Named tensors.
View compiled

I find the error a bit puzzling as I am reusing the image to train the model for this inference.  There should not be any issue with dimension.

Thanks.


________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong

When you call `tf.browser.fromPixels`, it uses the image's natural size, which is 1088x1920 in this case. You will have to resize it to 384x384, something like:

```js
tf.image.resizeBilinear(img, [384, 384])
```

I am not sure what your training pipeline looks like, but I suspect it might automatically crop/resize the image to 384x384. But during inference, you need to manually resize the input image to match the model input shape.

Btw the compiler error you were seeing is because the sample code is from typescript (the `as tf.Tensor` part) which cannot be used in javascript.

Thanks!

**Comment by FlyWong** [comment]
Hi,

I tried to do reshape with the resizeBilinear code,

    const tfliteModel = await tflite.loadTFLiteModel('net_pass.tflite');

    const img = tf.browser.fromPixels(document.getElementById('objDet'));

    const img2 =  tf.image.resizeBilinear(img, [384, 384]);

// Run inference and get output tensors.
    let outputTensor = tfliteModel.predict(img2);

However, I got a shape mismatch error:
Unhandled Rejection (Error): Input tensor shape mismatch: expect '1,384,384,3', got '384,384,3'.

I thought I can create a new dimension by adding a line of code from the sample:

const tfliteModel = await tflite.loadTFLiteModel('net_pass.tflite');

    const img = tf.browser.fromPixels(document.getElementById('objDet'));

    const img2 =  tf.image.resizeBilinear(img, [384, 384]);

// sample code added to create new dimension
    const input = tf.sub(tf.div(tf.expandDims(img2), 127.5), 1);


// Run inference and get output tensors.
    let outputTensor = tfliteModel.predict(input);

However I get Data type mismatch error:

Unhandled Rejection (Error): Data type mismatch: input tensor expects 'uint8', got 'float32'

Looks like we are very close to getting a prediction. May I know what is the proper way to shape the image correctly for prediction?

Thanks


________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong 

Looks like your model expects `int` input. That probably means you don't need to normalize the image. (Please check with your training code to see whether the input images got normalized or not).

If that's the case, try the following.

```js
const img = tf.browser.fromPixels(document.getElementById('objDet'));
const img2 =  tf.image.resizeBilinear(img, [384, 384]);
// Use tf.toInt to convert float32 to int
const img3 = tf.toInt(tf.expandDims(img2));
tfliteModel.predict(img3);
```

Hope it works!

**Comment by FlyWong** [comment]
Hi

when VS code tries to compile the new line

const img3 = tf.toInt(tf.expandDims(img2));

I got the compilation error:

Attempted import error: 'toInt' is not exported from ***@***.***/tfjs' (imported as 'tf').

I check my package.json and my

***@***.***/tfjs": "^3.7.0",

Is there any issue with my version?

My training code is very straight forward. Again taken from the samples with modification only to the path:

import numpy as np
import os
from tflite_model_maker.config import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector
import tensorflow as tf
assert tf.__version__.startswith('2')

tr_image_dir='C:\\Users\\proj\\tensorFlow\\workspace\\training_demo\\test\\tr'

val_image_dir='C:\\Users\\proj\\tensorFlow\\workspace\\training_demo\\test\\val'

label_map={1:'Nshuttle'}


c_dir = 'C:\\Users\\proj\\tensorFlow\\workspace\\cache'

train_ds = object_detector.DataLoader.from_pascal_voc(images_dir=tr_image_dir,
                                                      annotations_dir= tr_image_dir,
                                                      label_map=label_map,
                                                      cache_dir=c_dir)
val_ds = object_detector.DataLoader.from_pascal_voc(images_dir=val_image_dir,
                                                      annotations_dir= val_image_dir,
                                                      label_map=label_map,
                                                      cache_dir=c_dir)
print("Train dataset contains {} images".format(train_ds.__len__()))
print("Validation dataset contains {} images".format(val_ds.__len__()))

spec = model_spec.get("efficientdet_lite0")

model = object_detector.ObjectDetector.create(train_data=train_ds, #train dataset
                                             model_spec=spec, #model specification
                                             epochs=100, #training epochs
                                             validation_data = val_ds, #validation subset
                                             batch_size= 4,
                                             train_whole_model=True)
model.export(export_dir= 'C:\\Users\\proj\\tensorFlow\\workspace\\tflite',
             tflite_filename= 'net_pass.tflite'
             )

is there anything I can do to avoid such mismatch issue?

________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong 

Sorry, the correct code should be:

```js
tf.cast(tf.expandDims(img2), 'int32')
```

Sorry for the confusion!

I am not super familiar with the training process, sorry. But looks like you are basing on efficientdet which indeed accepts a non-normalized (int) input. See [here](https://tfhub.dev/tensorflow/efficientdet/d0/1).

Thanks!

**Comment by FlyWong** [comment]
Hi

Thanks! I am able to run the prediction now.

    const img3 = tf.cast(tf.expandDims(img2), 'int32');

    //tf.convert_to_tensor(img2, dtype=tf.int8)

// Run inference and get output tensors. uint8
    let outputTensor = tfliteModel.predict(img3);
    console.log(outputTensor.dataSync());


Currently having this error that dataSync() is not a function. Will look into it first.

Thanks
________________________________

**Comment by jinjingforever** [comment]
Glad you are making progress:) 

The error is probably because `tfliteModel.predict` returns an array of tensors in your case. You might need to check out the "output" section of [this page](https://tfhub.dev/tensorflow/efficientdet/d0/1) to get an idea about what output tensors look like. I also recommend [this app](https://netron.app/) that can help you visualize the model graph (use the `model.json` file), from which you can see all the output tensors.

**Comment by FlyWong** [comment]
Hi Jing Jin,

I cannot find the steps to install tensorflow hub for reactjs. Also, maybe it is good that we do not lose track of the big picture.

What I am trying to do here is to train a custom object detection model. As I have train TfLite models before ( Android project), I tried to use TfLite model for this reactjs project too.

this is my guiding document:

https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite#run-inference

[https://opengraph.githubassets.com/d6b0cb8e27981576c49b596b65dc2e87edee0898d521f58312402e4c4e02058d/tensorflow/tfjs]<https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite#run-inference>
tfjs/tfjs-tflite at master · tensorflow/tfjs<https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite#run-inference>
A WebGL accelerated JavaScript library for training and deploying ML models. - tfjs/tfjs-tflite at master · tensorflow/tfjs
github.com

However, I noticed that we are deviating away from the sample code by a bit now. I am wondering besides TFlite, is there a more established way to train custom models for reactjs using tensorflow?

Thanks,
Raymond



________________________________

**Comment by FlyWong** [comment]
Thanks. I will take a look at the tf model too

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FlyWong** [comment]
Hi,

I followed this guide to try to train a TF model for custom object detection:

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
Training Custom Object Detector - TensorFlow 2 Object Detection API tutorial — TensorFlow 2 Object Detection API tutorial documentation<https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html>
Partition the Dataset¶. Once you have finished annotating your image dataset, it is a general convention to use only part of it for training, and the rest is used for evaluation purposes (e.g. as discussed in Evaluating the Model (Optional)). Typically, the ratio is 9:1, i.e. 90% of the images are used for training and the rest 10% is maintained for testing, but you can chose whatever ratio ...
tensorflow-object-detection-api-tutorial.readthedocs.io


everything went well but when I ran the training,

python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config

I encountered out of memory issue. Attached is the out of memory error message. I am running on a machine with 16GB of RAM. The memory consumption is just 4GB when I start the training. I am wondering if there is anything I can optimized.

Attached also is my pipeline.config. I have reduced my training batch size to just 2.

The dataset I am training is the same one which I used to train successfully train a TFlite model which I was trying to use in my reactjs project. The training is done on the same machine.

Please advise how I can proceed. If TF model training is really too intensive, I will have to go back to try run the TFlite model in my reactjs project.

Thanks

________________________________

**Comment by FlyWong** [comment]
Hi Jing Jin and Ping Yu,

I have opened another case with regards to the my out of memory issue when training custom object detector.

Meanwhile, do you have sample codes for running prediction on TFlite model and then checking if detection has been made?

At the moment, we have managed to load the custom TFlite model, prepare the image so that predict can run and produce an output (see attached screen capture).  We are just left to interpret the output. If the output is correct, then the full process is successfully.

Please advise how can I go about with the interpretation.

We should expect a Nshuttle object to be detected as I am using one of the training images to test at the moment. When I loaded this TFLite model into an android project, the detection was successful.

Thanks
________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong 

The output of `tfliteModel.predict(img)` should be a tensor array, and it should have 4 elements (based on the "output" section [here](https://tfhub.dev/tensorflow/efficientdet/lite1/detection/1)). Not sure if they have descriptive names or not, but if not, you will have to guess which one is which. 

I think the "detection_boxes" should be easy to find since it has a shape of [N, 4]. The other 3 might also be possible to guess based on their meanings. Give it a try! 

Thanks

**Comment by FlyWong** [comment]
Hi Jing Jin,

based on my output (see attached), I have 4 StatefulPartitionedCall. 1 has shape of 1. 2 and 3 have shape [1,25]. StatefulPartitionedCall 3 has shape [1,25,4].

However, I cannot access the arrays. How can I convert them so that the values are accessible?

Thanks,
Raymond

________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong 

(For some reason I cannot see your attachments)

You can try something like:

```js
const tensors = model.predict(img);
// This will give you a (nested) array that contains the values. 
const values = tensors[0].arraySync();
```

**Comment by jinjingforever** [comment]
If possible, can you share the tflite model, using google drive maybe? I can run it here and see how it goes.

**Comment by FlyWong** [comment]
Will do that. Give me abt 40min.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jinjingforever** [comment]
Also the test image:) thanks!

**Comment by FlyWong** [comment]
Hi Jing Jin,

here:

https://drive.google.com/drive/folders/1gWa0Q1Mt4nGV7EIRHGECjedv38qQxbsd?usp=sharing

I have included the screen captures for StatefulPartitions too.

Let me know when else do you need

THanks,
Raymond

________________________________

**Comment by FlyWong** [comment]
Hi Jing Jin,

I added 2 more screen captures to the shared drive:


  1.  showing output[0] is undefined (outputArray0Undefined.png)
  2.  using the same tflite model and testing image, we can detect the passing shuttle on Android platform(detectedAndroid.png)

Hope these can help us get the final results!

Thanks,
Raymond
________________________________

**Comment by jinjingforever** [comment]
Hi @FlyWong 

It turns out the return value of `predict` is an named tensor map in this case, not an array. My bad. You can do the following to get the data:

```js
const tensors = model.predict(img3);
for (const name of Object.keys(tensors)) {
  const tensor = tensors[name];
  const values = tensor.arraySync();
  console.log(name, values);
}
```

I tried it and looks like:

- StatefulPartitionedCall:1. [1, 25]. Scores.
- StatefulPartitionedCall:3. [1, 25, 4]. Bounding boxes.
- StatefulPartitionedCall:0. [1]: number of detections
- StatefulPartitionedCall:2: [1, 25] label index for each detection

Please give it a try. Hopefully it works!

<img width="982" alt="Screen Shot 2022-02-09 at 4 55 17 PM" src="https://user-images.githubusercontent.com/8752427/153316763-9dee12be-9f21-4e09-b7c2-3cfe29b402a9.png">

**Comment by FlyWong** [comment]
Hi Jing Jin,

Thanks a million!!

looks promising now. I will run through more test and let you know again.

Thanks,
Raymond

________________________________
