### ISSUE TITLE
Error when running webcam-transler-learning example

### ISSUE THREAD

**Issue by thebeancounter** [tensorflow/tfjs#603]
I am using ubuntu 18 with yarn and node v 8.11.3 
When running the example [here]([url](https://js.tensorflow.org/tutorials/webcam-transfer-learning.html)) 
With the following shell commands
```
git clone https://github.com/tensorflow/tfjs-examples
cd tfjs-examples/webcam-transfer-learning
yarn
yarn watch
```

I am getting the following error when getting to the last line of code:

> yarn run v1.9.4
> $ cross-env NODE_ENV=development parcel index.html --no-hmr --open
> Server running at http://localhost:1234 
> ⏳  Building asyncToGenerator.js...
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: watch /home/user/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/core-js/modules/es6.math.fround.js ENOSPC
>     at _errnoException (util.js:992:11)
>     at FSWatcher.start (fs.js:1382:19)
>     at Object.fs.watch (fs.js:1408:11)
>     at createFsWatchInstance (/home/user/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/chokidar/lib/nodefs-handler.js:37:15)
>     at setFsWatchListener (/home/user/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/chokidar/lib/nodefs-handler.js:80:15)
>     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/chokidar/lib/nodefs-handler.js:232:14)
>     at FSWatcher.NodeFsHandler._handleFile (/home/uwer/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/chokidar/lib/nodefs-handler.js:259:21)
>     at FSWatcher.<anonymous> (/home/user/WebstormProjects/tfjs-examples/webcam-transfer-learning/node_modules/chokidar/lib/nodefs-handler.js:480:21)
>     at FSReqWrap.oncomplete (fs.js:153:5)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I had no luck finding anything about it. I tried changing the tfjs version with no luck I upgraded Node, and tried to downgrade it to earlier stable versions. We tried running this on a windows machine, and it worked.

We tried using the same versions that are working on a windows machine: npm 8.10 & yarn 5.04 with no luck

Thanks

**Comment by bileschi** [comment]
Hi @thebeancounter, I'm not sure this example works in node.  This is meant to be a browser example.

**Comment by thebeancounter** [comment]
@bileschi see the github instructions, they state using yarn and yarn watch. my friend did the exact same on a windows machine and it worked

**Comment by thebeancounter** [comment]
Well, 
I don't know why but using this in terminal solved the issue

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
sudo sysctl --system
```

can anyone explain why?

**Comment by nsthorat** [comment]
I have no clue why that fixed it! How did you find that? Maybe the filesystem is failing out on watching too many files?

**Comment by nsthorat** [comment]
Closing this out in favor of the SO question.
