### ISSUE TITLE
Environments where IS_BROWSER and IS_NODE are both true overwrite platform and log warnings

### ISSUE THREAD

**Issue by austintoot40** [tensorflow/tfjs#6030]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow.js installed from: npm
- TensorFlow.js version: 3.11.0
- Browser version: N/A for this example, but I've seen it happen in Electron 16
- Tensorflow.js Converter Version: 3.11.0

**Describe the current behavior**

When `import * as tf from '@tensorflow/tfjs';` is run in either a Jest test for a Vue component, or in the Vue component being tested, the message "[Platform browser has already been set. Overwriting the platform with [object Object].](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/environment.ts#L61)" is `console.warn`'ed out. 

This is due to this Jest/Vue environment being both a browser and a node environment, thus setting both the [IS_BROWSER](https://github.com/tensorflow/tfjs/blob/1d0c63f3bedb74f553382fbcefb355da9c951c35/tfjs-core/src/flags.ts#L39) and [IS_NODE](https://github.com/tensorflow/tfjs/blob/1d0c63f3bedb74f553382fbcefb355da9c951c35/tfjs-core/src/flags.ts#L42) flags to true, and each in turn calling `setPlatform` in their respective platform's modules. This causes the console to get spammed with warnings while running tests.

This is likely not isolated to the combo of Jest and Vue. I've seen this error in Electron/Vue environments as well, but it's much harder to make a reproducible example for that.

**Describe the expected behavior**

The warning isn't logged out, since there is nothing technically wrong with this use case.

I see a couple options to fix this:
- Handling the scenario where `IS_BROWSER` and `IS_NODE` are both true such that `setPlatform` is only called once.
- A way to disable this logging. Since it occurs on import, other methods of post-import configuration won't fix this, and the current IS_TEST and PROD env checks don't seem to be working here.

I would be happy to make a contribution to fix this, but I don't know enough about the side effects of messing with platform environments well enough to do so without some conversation.

**Standalone code to reproduce the issue**

1. Install vue-cli with `npm install -g @vue/cli`
2. Create a new Vue project with `vue create tftest`
3. Add tensorflow with `npm i @tensorflow/tfjs --save`
4. Add unit tests with `vue add unit-jest` and `npm i @vue/test-utils --save-dev`
5. Add the line `import * as tf from '@tensorflow/tfjs'` to `src/components/HelloWorld.vue` at line 34
6. Run the example test with `npm run test:unit`

The result:

![image](https://user-images.githubusercontent.com/42546787/149977234-1a243bb9-28b0-488f-a510-411f9b761063.png)

**Other info / logs**

This issue is similar #5349, but the particular warning brought up here was never solved.

**Comment by pyu10055** [comment]
@austintoot40 Thanks for reporting this, I think your first option seems reasonable. We could treat the case when both IS_BROWSER and IS_NODE flags are true as browser.

**Comment by austintoot40** [comment]
I can throw a quick branch together that only calls the node `setPlatform` if IS_BROWSER is also false. That seems like an easy starting place.
