### ISSUE TITLE
Load model we get through 'browserHTTPRequest' is not working 

### ISSUE THREAD

**Issue by joaopdss** [tensorflow/tfjs#6035]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): Npm
- TensorFlow.js version (use command below): 3.11
- Browser version: 97.0
- Tensorflow.js Converter Version: 3.11

Our ideia is to use an image classifier in browser using JS, but when we try through "browserHTTPRequest" is not working. When we are using in node, is not working either, only when we use "tf.io.fileSystem". 

**Describe the current behavior**
We're trying to load a model through "tf.io.browserHTTPRequest". If we open the model.json, the format is "graph-model", but when we get through "browserHTTPRequest" and load, the format is "layers-model". So when we execute the "loadGraphModel" with the handler we get through "browserHTTPRequest" the code is not working.

**Describe the expected behavior**
If we use "tf.io.fileSystem" and load it, the format returned is "graph-model" as expected. When we use "browserHTTPRequest" the returned format should be "graph-model" as well. 

**Standalone code to reproduce the issue**
```
import * as tf from '@tensorflow/tfjs-node-gpu';

const handler2 = tf.io.fileSystem('./model.json');
const handler = tf.io.browserHTTPRequest("http://localhost:8000/models/model.json");

async function test(){
    console.log(await handler.load());
    console.log(await handler2.load());
    const model = await tf.loadGraphModel(handler);
    console.log(model);
}

test()
```

**Other info / logs** 
[model.zip](https://github.com/tensorflow/tfjs/files/7897081/model.zip)

**Comment by pyu10055** [comment]
@joaopdss can you share the error you are getting?

**Comment by joaopdss** [comment]
> @joaopdss can you share the error you are getting?

We found the error, it was a big cache problem in our database, so we were getting an older version of our model.json. 
It was caused because we were trying to use a "graph-model" but the cache problem was giving to us an "layers-model". The error is below.
![a008eaca-90ad-441d-9237-67d5cc5368ce](https://user-images.githubusercontent.com/72708214/150333888-c521d43e-e4f4-4685-a767-44b36d83ab24.jpg)

But as I said, now is solved. Thanks for your attention :)
