### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by santosh898** [tensorflow/tfjs#605]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
```
tfjs-converter 0.5.7
tfjs-core 0.12.11
tfjs 0.12.4
```
#### Browser version
```
Ubuntu + Chrome 67.0.3396.87 (Official Build) (64-bit)
```
#### Describe the problem or feature request

> With the new release of tfjs-converter(0.5.7) #569 has gone 

Now the error below comes while running SSD_MOBILENET_V1
```
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at tf-converter.esm.js:17
    at Array.map (<anonymous>)
    at e.<anonymous> (tf-converter.esm.js:17)
    at tf-converter.esm.js:17
    at Object.next (tf-converter.esm.js:17)
    at s (tf-converter.esm.js:17)
```

#### Code to reproduce the bug / link to feature request
```
const MODEL_URL = 'http://localhost:3001/model.pb';
const WEIGHTS_URL = 'http://localhost:3001/weights.json';

const model = await loadFrozenModel(MODEL_URL, WEIGHTS_URL);
const img = document.getElementById('logo');
let tfImage=tf.fromPixels(img).expandDims(0);

let output=await model.executeAsync({image_tensor:image_normalized});
```

**Comment by pyu10055** [comment]
for Mobilenet you should use predict or execute method instead of executeAsync, since the model does not have any control flow ops. Can you try that first, see if it works for you.

**Comment by santosh898** [comment]
Mobilenet is working fine, No errors

**Comment by sandromario** [comment]
I am running into the same error with a model (custom-built using ONNX) which does have control flow ops. I hope there will be a fix.

**Comment by sandromario** [comment]
PS: This problem does not appear if an intermediate node is specified as the output node manually. However, what I want to get is the results for the output nodes (here: 3) specified by the model.

**Comment by pyu10055** [comment]
@sandromario This error may occur for couple reasons:
1. The output nodes you specified does not match the model's output nodes.
2. The model execution stop before reaching the output node.

If you can share the model with me, I might be able to debug the cause for you.

**Comment by sandromario** [comment]
Will do soon – could you give me an email address?
1. I haven't actually specified any output nodes at all, as suggested in the method docstring. I was expecting that the model's output nodes would then be used:

`* @param outputs output node name from the Tensorflow model, if no outputs
   * are specified, the default outputs of the model would be used. You can
   * inspect intermediate nodes of the model by adding them to the outputs
   * array.`

2. What could be the reason for this?

Thanks, and I'll be in touch soon.

**Comment by sandromario** [comment]
It was indeed reason 2. Apparently the model ran into some timeout as it took to long to compute. We've now slightly changed the model architecture such that each individual step is faster. Thanks again for your help!
