### ISSUE TITLE
Tensorflow Object Detection API ssd_mobilenet_v1_coco : Same Invalid Output on all inputs

### ISSUE THREAD

**Issue by AviKndr** [tensorflow/tfjs#607]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.5
#### Browser version
Windows 7 + 68.0.3440.106
#### Describe the problem or feature request
The changes made with 0.12.5 have made it possible to convert and execute ssd-mobilenet models from the tensorflow object detection api without errors, but still results in invalid output from SSD-Mobilenet-Coco when running executeAsync with either the webgl or cpu backends. I receive same output of all 0's for bounding boxes, classes, and num_detections and all 1's for scores regardless of input data with shapes of [100,4],[100,1],[100,1],[1] for detection_boxes, detection_classes, detection_scores, and num_detections respectively. Attached is an image of console.log of these Float32Arrays. 
![capture](https://user-images.githubusercontent.com/7812628/44108247-adb30fc0-9fae-11e8-8445-2b4a4451f80f.PNG)
#### Code to reproduce the bug / link to feature request
I used the ssd_mobilenet_v1_coco model from here : https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md 

I converted to tfjs frozen model using this code : `tensorflowjs_converter \ --input_format=tf_saved_model \ --output_node_names='detection_boxes,detection_classes,detection_scores,num_detections' \ --saved_model_tags=serve \ ~/workspace/model/saved_model \ ~/workspace/model/web_model`
Loaded model with `tf.loadFrozenModel(modelPath,weightsPath)` and ran inference using `const modelOutput = await model.executeAsync(input)` which resulted in the array of 4 Tensors described above and shown in the attached image. 

The same input was ran against yolo v3 trained on coco converted to regular tfjs model format with `model.predict(input)` and gave meaningful results.

**Comment by AviKndr** [comment]
Nevermind, I realized that the models from the tensorflow object detection api model zoo perform conversion to normalized floats and therefore the input image tensor should not be pre-processed manually. As of now, ssd-mobilenet seems to work as expected on tfjs.

**Comment by gulatisimran** [comment]
HI, I converted trained on custom dataset ssd_mobilenet_V1 to tfjs and I am getting a similar result, getting float numbers in range[0,1] 

Tensor [[[0.5446654, 0.4751714, 0.9186856, 0.802305 ], [0.2283817, 0.0216707, 0.8636419, 0.2391927], [0.727316 , 0.6683039, 0.9777313, 0.8424701], ..., [0.7610142, 0.6679996, 0.8904252, 0.7726711], [0.2950329, 0.00674 , 0.6716213, 0.0697103], [0.2889385, 0.1158738, 0.7966963, 0.3626493]]],Tensor [[0.9999716, 0.0029886, 0.0029876, ..., 0.0003309, 0.0003304, 0.0003296],],Tensor [[1, 1, 1, ..., 1, 1, 1],],Tensor [100]


Can you share the link of yolo v3 model file and its details to convert, as you mentioned above for which results were meaningful?

**Comment by gulatisimran** [comment]
Third Array i.e the array of all 1's is actually the class number of  Label Map File on which you have trained, I have tested the same on different images containing various classes
