### ISSUE TITLE
Unknown op 'EnsureShape'

### ISSUE THREAD

**Issue by caixiaoniweimar** [tensorflow/tfjs#6077]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 1804
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: [3.13.0](https://www.npmjs.com/package/@tensorflow/tfjs-node)
- CUDA/cuDNN version: 8.2

**Describe the problem**
Hello, I am training a [deeplab2 panoptic segmentation](https://github.com/google-research/deeplab2) model without custom code, and use tensorflowjs_converter --input_format=tf_saved_model .... to convert my model to TFJS web model, however, I got the error

```
Unsupported Ops in the model before Optimization
TensorListResize, EnsureShape, TensorListLength
```

I am wondering if it is a version thing? At the moment, are these ops not supported? Are there any other ways to convert my model to tfjs without modifying these ops? I need to use this model in NodeRed.  Thanks very much! I appreciate any help and hints!
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
This has been implemented in #6282 . Closing the request. Thank you

**Comment by AbhisKmr** [comment]
@rthadur what about the **EnsureShape** error Im still facing this do you have any suggestion about that

**Comment by AbhisKmr** [comment]
@caixiaoniweimar How you solve **EnsureShape ops** error?? Do you have any solution for this?
