### ISSUE TITLE
tf.wasm.setThreadsCount is not a function

### ISSUE THREAD

**Issue by Poufy** [tensorflow/tfjs#6079]
Importing wasm backend using the script tag and trying to use this function that was available in the documentation for the wasm-backend does not work. It says that the following is not a function. Was this function removed? What is the issue here?

**Comment by rthadur** [comment]
No it is removed , which version of tfjs you are using ?

**Comment by Poufy** [comment]
@rthadur Do you mean it is removed or it is not removed? 

This is my setup. I am using importscripts since I am working inside a web-worker

```js
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.9.0")
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow-models/blazeface")
tf.wasm.setWasmPaths('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.9.0/dist/');
tf.wasm.setThreadsCount(4);
```

**Comment by rthadur** [comment]
sorry I meant it is not removed , please try latest version(v3.13.0). Thank you

**Comment by Poufy** [comment]
> sorry I meant it is not removed , please try latest version(v3.13.0). Thank you

Thank you so much. That seemed to work. Should I delete this issue as it seems my question was rather trivial?

**Comment by rthadur** [comment]
We can close it.

**Comment by Poufy** [comment]
I would like to ask a follow-up question to that. If it requires opening another issue please let me know.

I have used the function like so without any issues.

```js
tf.wasm.setThreadsCount(2);
```

However, after I set the backend to wasm and print the number of threads it still appears to be 1, which I am assuming to be the default.

```js
tf.setBackend('wasm');
await tf.ready();
console.log("Num threads wasm is using", tf.wasm.getThreadsCount());
```
Any idea what could be the result of this?
