### ISSUE TITLE
pose detection estimatePoses() is running syncronously for too long

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [tensorflow/tfjs#6093]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Didn't test on mobile device
- TensorFlow.js installed from (npm or script link): [`@tensorflow/tfjs-core@3.13.0`](https://www.npmjs.com/package/@tensorflow/tfjs-core/v/3.13.0)
- TensorFlow.js version (use command below): 3.13.0
- Browser version: Microsoft Edge | 97.0.1072.76 (Official build) (64-bit)
- Tensorflow.js Converter Version: 3.13.0

**Describe the current behavior**
When doing `detector.estimatePoses()` for the first time, it blocks for 30 seconds, making the page unresponsive

**Describe the expected behavior**
`detector.estimatePoses()` can take some time *async*, but it shouldn't block *sync*

**Standalone code to reproduce the issue**
https://codesandbox.io/s/tensorflow-pose-detection-bug-3dbgi?file=/src/Canvas.tsx:1857-2199

**Comment by rthadur** [comment]
This might be due to warm up time which is required while loading the model , can you check this explanation regarding webgl and model loading #5045 (comment) .

**Comment by ChocolateLoverRaj** [comment]
@rthadur I think it _is_ from warm up time. What workaround should I use to not block the main thread during warmup? 

This is the workaround I am experimenting with: creating the detector in a worker and messaging the worker with the canvas image data, estimatePoses() in the worker, and then sending the results back. Will this method have any performance decrease?

**Comment by rthadur** [comment]
it should not impact the performance , please check this thread https://github.com/tensorflow/tfjs/issues/1715 regarding the same topic. Thank you

**Comment by ChocolateLoverRaj** [comment]
@rthadur The other issue doesn't really have a solution. I will just use the webworker method.

**Comment by rthadur** [comment]
sure. Can we close this issue ?
