### ISSUE TITLE
Error while troubleshooting

### ISSUE THREAD

**Issue by Vickpire** [tensorflow/tfjs#6095]
Hello, 

While using command node-gyp configure --verbose, I am encountering the following error: gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\path\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\path\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd C:\Users\path\.node-red\node_modules
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

If you could provide some tips on how to fix this, it would be helpful. I am trying to use the @tensorflow/tfjs-node for Node-RED dependency nodes. 

Thank you. 

Best regards,
Victoria

**Comment by rthadur** [comment]
We do not support node red , Here is the location where you could ask questions regarding the same  https://github.com/yhwang/node-red-contrib-tf-model/issues , Thank you
