### ISSUE TITLE
Not able to start electron app after build.

### ISSUE THREAD

**Issue by avestaHarsh** [tensorflow/tfjs#6096]
I have developed my electron app in windows 10 and it's working fine (during development as well as after building the electron app) in windows 10. But when I try to run this electron app (which is built-in windows 10) in **windows 7** it's not working.  

@kangyizhang @jasonmayes 
Can anyone guide me on what's I am doing wrong? I got the below error when I try to start this app in windows 7.

![error1](https://user-images.githubusercontent.com/16647220/152098176-b8c5af6c-9e17-4cd2-bff5-5d400b1c6414.PNG)

**System information**
- OS Platform (Windows 7 Ultimate 64bit operating system, RAM: 4 GB ):
- TensorFlow.js version (@tensorflow/tfjs-node": "3.9.0")

**Comment by jasonmayes** [comment]
@mattsoulanille Any thoughts on this one? Do we know of any electron issues on Windows? Related to the build issue in other bug maybe?

**Comment by rthadur** [comment]
I see you are using tfjs-node , I am not sure if this is supported for react native , can you please try to run this example https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection and see if it works.

**Comment by rthadur** [comment]
here is a similar issue reported https://github.com/tensorflow/tfjs/issues/5066

**Comment by avestaHarsh** [comment]
> here is a similar issue reported #5066

Thank you @rthadur for your response. I have gone through [#5066](https://github.com/tensorflow/tfjs/issues/5066). but I do have both x64 bit machines (one in which I had built my electron app (in Windows 10) and the second one in which I am trying to run that app(in windows 7)). 

Just want to let you know that the error which I am getting is 
![error1](https://user-images.githubusercontent.com/16647220/152295597-483b195c-bd2b-42a3-a2c9-57c10cbfaf08.PNG)

and at the same location tfjs_binding.node does exist. then why it's not able to read this file? Please correct me If I am doing anything wrong.
![location](https://user-images.githubusercontent.com/16647220/152295973-bb8cae94-a25a-43b6-bec8-29be9af5525a.PNG)

> I see you are using tfjs-node , I am not sure if this is supported for react native , can you please try to run this example https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection and see if it works.

I am not using React native at this moment. I am using @tensorflow/tfjs-node in my electron (version 12.0.18) app.

**Comment by sbeatz** [comment]
same issue here with Electron 17.1.2 Node Js 16.13.0
the file definitely exists in the folder
<img width="395" alt="image" src="https://user-images.githubusercontent.com/637878/158445352-10ead842-f400-4f36-bf71-ff6ba3c95e90.png">

**Comment by wszgrcy** [comment]
I have the same problem. In develop computer(win10 64) I can run successfully.but in other computer (win10 64),throw error. electron 22.0.3

**Comment by wszgrcy** [comment]
> I have the same problem. In develop computer(win10 64) I can run successfully.but in other computer (win10 64),throw error. electron 22.0.3

I resolved.install vs build tool can work....
but in production environment is to big......so what is the Minimum runtime?

**Comment by wszgrcy** [comment]
> > I have the same problem. In develop computer(win10 64) I can run successfully.but in other computer (win10 64),throw error. electron 22.0.3
> 
> I resolved.install vs build tool can work.... but in production environment is to big......so what is the Minimum runtime?

vc++ 2019(maybe your msvc build version?)

**Comment by shmishra99** [comment]
Hi @avestaHarsh ,
Apology for the late response. Could you please let us know if your issue has been resolved or you are still looking for the solution? I would suggest you to give a try with the latest version of `@tensorflow/tfjs@4.4.0` and check if your issue is resolving or not.
Thank You !!
