### ISSUE TITLE
I have the following problem

### ISSUE THREAD

**Issue by florpadilla** [tensorflow/tfjs#6097]
gyp: binding.gyp not found (cwd: C:\Users\FLORENCIA) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\FLORENCIA\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\FLORENCIA\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd C:\Users\FLORENCIA
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by rthadur** [comment]
Are you using on node red ? could you please elaborate the steps which you are following . Please check this document https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md for help with windows. Thank you
