### ISSUE TITLE
Error con ResizeNearestNeighbor en tfjs con modulo wasm

### ISSUE THREAD

**Issue by jorgeluis168** [tensorflow/tfjs#6099]
Hola buenas tardes!!!

Información del sistema

Plataforma: Windows 10
Versión de TensorFlow.js : 2.8.6
Versión del navegador: Chrome 98.0.4758.82 (Build oficial) (64 bits)
Versión TensorFlow.js Converter v3.9.0 - Generate by: 2.5.0
Versión Tfjs Backend Wasm: 2.8.6

Comportamiento actual
Cuando ejecuto con el backend WASM obtengo el siguiente error : 
"Error: Error running ResizeNearestNeighbor: Neither modular kernel nor forward func passed"
Tanto con backend webgl y cpu funciona perfecto.

**Comment by rthadur** [comment]
There is already a feature request opened here https://github.com/tensorflow/tfjs/issues/4766 for tracking , please comment there. Thank you
