### ISSUE TITLE
Feature Request: implement rot90

### ISSUE THREAD

**Issue by MauricePasternak** [tensorflow/tfjs#6102]
**System information**
- TensorFlow.js version (you are using):
3.13.0

- Are you willing to contribute it (Yes/No):
No

**Describe the feature and the current behavior/state.**
This feature currently exists in the Python Tensorflow codebase: https://www.tensorflow.org/api_docs/python/tf/image/rot90

Although, for generalizability, it would be great if the behavior followed more closely to numpy's approach: https://numpy.org/doc/stable/reference/generated/numpy.rot90.html

**Will this change the current api? How?**
It will add an additional API function and documentation needed for said function.

**Who will benefit with this feature?**
Generally benefits anyone who would like to perform precise 90/180/270 rotations on tensors/arrays for data prep and/or data augmentation purposes. Example use case, MRI voxel data loaded is often loaded differently between image types and it would be convenient to have a rotation function to standardize all loaded images.

**Comment by rthadur** [comment]
Similar implementation  has been made here https://github.com/tensorflow/tfjs/pull/3626 , please verify.

**Comment by MauricePasternak** [comment]
You are absolutely correct. Thank you for the link.
