### ISSUE TITLE
Uncaught (in promise) TypeError: Unknown op 'StringSplitV2'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()

### ISSUE THREAD

**Issue by JatuFaique** [tensorflow/tfjs#6103]
Hello,

I created a Bidirectional LSTM model, converted it using the tensorflowjs-converter command.
Please note, I have use Vectorization layer in model.

Loaded a graph model ,after loading,  tried using executeAsync.

**System information**
- TensorFlow.js version (you are using):13.3.0
![Screenshot from 2022-02-07 12-08-00](https://user-images.githubusercontent.com/52850100/152737417-c9e14f6e-a130-4387-84b9-e8b991bfa62c.png)

below is the error

![Screenshot from 2022-02-07 12-14-52](https://user-images.githubusercontent.com/52850100/152738180-78d4a868-055c-4973-abd6-84d2dac3017e.png)

Any help or guidance or a work around is really appreciated.

**Comment by rthadur** [comment]
Hi , there is an already feature request opened here https://github.com/tensorflow/tfjs/issues/5577 , will track there . please upvote the request there. Thank you
