### ISSUE TITLE
tfjs Selfie Segmentation incomplete model output 

### ISSUE THREAD

**Issue by dhlanm** [tensorflow/tfjs#6106]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 10.0.19042 Build 19042
- TensorFlow.js installed from (npm or script link): npm, but reproduced from script link in codepen below
- TensorFlow.js version (use command below): 3.13.0
- Browser version: Google Chrome 98.0.4758.82
- @tensorflow-models/body-segmentation version 0.0.1
- i5 4200U CPU

**Describe the current behavior**
On my (older) windows machine, output of the tfjs selfie segmentation model implementation is halved. The top half is correct, but the bottom half is simply nonexistent: 
![image](https://user-images.githubusercontent.com/4271200/153059401-a3bdf591-3ea4-40f5-8622-c7b9539b5b4e.png)

This is not the case if I use the mediapipe runtime of the same model, nor is it the case on my newer Macbook Pro. 
I tried a couple of input formats other than ImageBitmap (HTMLVideoElement, Tensor3D) and found no change in output behavior. 
Changing the backend from "webgl" to "cpu" also does not change anything. 

**Describe the expected behavior**
I expect to get a full output, such as: 
![image](https://user-images.githubusercontent.com/4271200/153059446-5118e1b8-6f8a-4d3c-abfe-bf47e48a0ab9.png)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

https://codepen.io/dhlanm/pen/bGYqEqr (apologies for the lack of CSS/UX. To get this to work, hit enable webcam, then once it loads, hit draw segmentation and wait a few moments for the segmentation output to load).

**Comment by rthadur** [comment]
I was not able to reproduce the same on windows machine , can you please check again , mine was windows 10 

![image](https://user-images.githubusercontent.com/43972606/153315095-6219eb86-05db-452a-9794-5c72b667641d.png)
