### ISSUE TITLE
Not able to install the Library

### ISSUE THREAD

**Issue by sshehab1** [tensorflow/tfjs#6110]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 11
- TensorFlow.js installed from (npm or script link): npm i puppeteer-hcaptcha

**Any other info / logs**
npm v 6.9.0
node v12.0.0
yarn v 1.22.17

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

@tensorflow/tfjs-node@3.13.0 install C:\projects\Repos\project\node_modules@tensorflow\tfjs-node
node scripts/install.js

CPU-windows-3.13.0.zip

Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.7.0.zip
[==============================] 631779/bps 100% 0.0s
Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/3.13.0/CPU-windows-3.13.0.zip
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@3.13.0 and node@12.0.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/3.13.0/CPU-windows-3.13.0.zip
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\ProgramData\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:196:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\ProgramData\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=C:\projects\Repos\project\node_modules\https://github.com/tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\projects\Repos\project\node_modules\https://github.com/tensorflow\tfjs-node\lib\napi-v4" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd C:\projects\Repos\project\node_modules@tensorflow\tfjs-node
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\ProgramData\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\Repos\project\node_modules@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\projects\Repos\project\node_modules@tensorflow\tfjs-node\lib\napi-v4 --napi_version=4 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
node-pre-gyp ERR! stack at ChildProcess. (C:\projects\Repos\project\node_moduleshttps://github.com/mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\projects\Repos\project\node_modules\@mapbox\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\Repos\project\node_modules@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v12.0.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.4
node-pre-gyp ERR! not ok
npm WARN project@1.0.0 No description
npm WARN project@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@3.13.0 install: node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@3.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\user\AppData\Roaming\npm-cache_logs\2022-02-08T21_53_29_638Z-debug.log`

**Comment by rthadur** [comment]
@sshehab1 did you get chance to check this steps https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md ?

**Comment by sshehab1** [comment]
@rthadur  I updated my node version and tried the steps but now I have another issue

npm ERR! code 1
npm ERR! path C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.13.0.zip
npm ERR! * Downloading libtensorflow
npm ERR! C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported system: cpu-win32-ia32
npm ERR!     at getPlatformLibtensorflowUri (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:106:11)
npm ERR!     at downloadLibtensorflow (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:139:15)
npm ERR!     at async run (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:208:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-11T11_12_25_737Z-debug-0.log
PS C:\projects\Repos\project> npm install puppeteer-hcaptcha
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\projects\\Repos\\project\\node_modules\\puppeteer-hcaptcha',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\projects\Repos\project\node_modules\puppeteer-hcaptcha\node_modules\puppeteer'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\projects\\Repos\\project\\node_modules\\puppeteer-hcaptcha\\node_modules\\puppeteer'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\projects\\Repos\\project\\node_modules\\puppeteer-hcaptcha',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\projects\Repos\project\node_modules\puppeteer-hcaptcha\node_modules\puppeteer'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\projects\\Repos\\project\\node_modules\\puppeteer-hcaptcha\\node_modules\\puppeteer'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.13.0.zip
npm ERR! * Downloading libtensorflow
npm ERR! C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported system: cpu-win32-ia32
npm ERR!     at getPlatformLibtensorflowUri (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:106:11)
npm ERR!     at downloadLibtensorflow (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:139:15)
npm ERR!     at async run (C:\projects\Repos\project\node_modules\@tensorflow\tfjs-node\scripts\install.js:208:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-11T11_18_24_416Z-debug-0.log

**Comment by sshehab1** [comment]
> is your system win32 ?

Honestly, I am not sure but it should be win64

System type: x64 based PC
System directory: C:/WINDOWS/system32

**Comment by rthadur** [comment]
We noticed several users are facing same issue on windows machine , here is the issue https://github.com/tensorflow/tfjs/issues/5942 which is opened , please comment in #5942

**Comment by sshehab1** [comment]
> We noticed several users are facing same issue on windows machine , here is the issue #5942 which is opened , please comment in #5942

I also tried it on my ubuntu machine and got the error
