### ISSUE TITLE
HandPoseDetection demo error on wasm backend

### ISSUE THREAD

**Issue by ybigus** [tensorflow/tfjs#6128]
**System information**
- I used hand-pose-detection from GitHub but added a tfjs-backend-wasm
- TensorFlow.js installed: npm
- TensorFlow.js version: tried 3.09 - 3.13

**Describe the current behavior**
Trying to run [HandPoseDetection](https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection) lib on TFJS WASM backend.
It works well with WebGL backend, but once I am switching to WebAssembly I get an error:
```
RuntimeError: memory access out of bounds
    at tfjs-backend-wasm-simd.wasm:0x8674
    at tfjs-backend-wasm-simd.wasm:0x3c25
    at tfjs-backend-wasm-simd.wasm:0x2444
    at BackendWasm.move (backend_wasm.ts:84)
    at BackendWasm.write (backend_wasm.ts:55)
    at BackendWasm.makeOutput (backend_wasm.ts:193)
    at Object.kernelFunc (binary_kernel.ts:54)
    at kernelFunc (engine.ts:644)
    at engine.ts:711
    at Engine.scopedRun (engine.ts:478)
```
Seems like it happens [after trying to detect palm](https://github.com/tensorflow/tfjs-models/blob/master/shared/calculators/detector_inference.ts#L31) but I am not sure, to be honest.

I tried multiple TFJS versions (3.09 - 3.13), and see an error on each.

**Describe the expected behavior**
The expected behavior is hand-pose-detection works with WASM like it works on WEBGL, CPU backends or [old hand pose library](https://github.com/tensorflow/tfjs-models/tree/master/handpose) (which is also works as expected on all backends)

**Standalone code to reproduce the issue**
I used [this demo](https://storage.googleapis.com/tfjs-models/demos/hand-pose-detection/index.html?model=mediapipe_hands), the stock source code is [here](https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/demos/live_video) just added tf-js-wasm-backend.

**Comment by rthadur** [comment]
did you get chance to check this issue https://github.com/tensorflow/tfjs/issues/5336 ?

**Comment by ybigus** [comment]
yep I saw it, the error looks similar, but I checked the WASM version and it was the same as the tfjs-wasm-bakend version.
you can see on the following line, that correct WASM version loading for each tfjs-wasm-backend version: https://github.com/tensorflow/tfjs-models/blob/master/hand-pose-detection/demos/live_video/src/index.js#L23
Also, I can reproduce this issue not only on Chrome but Firefox as well

**Comment by rthadur** [comment]
Can you please share your package.json , I was able to run the demo successfully on Macbook pro

Thanks

**Comment by ybigus** [comment]
Does it work for you on the WASM backend?
Simply, add WASM to the options panel, then choose WASM as backend in the demo:
https://github.com/tensorflow/tfjs-models/blob/master/hand-pose-detection/demos/shared/params.js#L72
```
export const MODEL_BACKEND_MAP = {
  [handdetection.SupportedModels.MediaPipeHands]: ['tfjs-wasm', 'mediapipe-gpu', 'tfjs-webgl']
}
```
Also install @tensorflow/tfjs-backend-wasm module.

Did you did these changes and does it works?

**Comment by rthadur** [comment]
I was able to reproduce the same but it happens as soon as i change to tfjs-wasm and I get this error 

> RuntimeError: memory access out of bounds

**Comment by ybigus** [comment]
Yeah, exactly, it works on WEBGL(also it works on CPU and mediapipe), but it fails on WASM backend. That is an issue:)

**Comment by corthiclem** [comment]
Hi! Same issue here but with the `FaceDetection` and `FaceLandmarksDetection` models: #6492

**Comment by rthadur** [comment]
@ybigus can you please try with latest version (3.2.0). Seems to be resolved. https://github.com/tensorflow/tfjs/issues/6492#issuecomment-1253777813

**Comment by ybigus** [comment]
@rthadur hi, yes it's working for me with 3.20.0, (but doesn't work with 3.9.0)!
thank you!
