### ISSUE TITLE
tensorflowjs_converter and scalars instead of tensors

### ISSUE THREAD

**Issue by icysapphire** [tensorflow/tfjs#615]
#### TensorFlow.js version
 {"tfjs-core": "0.12.11", "tfjs-layers": "0.7.4", "tfjs-converter": "0.5.7", tfjs: "0.12.5" }

#### Describe the problem
There's something wrong in the conversion process from frozenModels. In fact, when I actually created the model (in python - tensorflow) I wrote:

> self.scalarInput =  tf.placeholder(shape=[None,21168],dtype=tf.float32, name="main_scalarinput")

I correctly do predictions in a C++ Tensorflow-based application that uses a frozen version of this model. I'd like to do the same in a tfjs-based webapp. However, after running tensorflowjs_converter and writing the code to load the converted model, I am not able to feed data in the model, since it accepts only scalars.
Inspecting the model inputs I can see:
```
0: Object { name: "main_scalarinput", **shape: []**, dtype: "float32" }
1: Object { name: "main_batch_size", shape: [], dtype: "int32" }
2: Object { name: "main_train_length", shape: [], dtype: "int32" }
```
which is in contrast with the actual definition of the model.

.pb model here:
https://drive.google.com/file/d/1tU-6tYhXTGhFOjy6Eycqt2rwnOoOYmw6/view?usp=sharing

Any workaround?

**Comment by pyu10055** [comment]
@icysapphire I check your frozen model pb file, all the placeholders you mentioned have follow shape definition:
attr {
  key: "shape"
       value {
        shape {
         }
   }
 }
which indicates an scalar shape according to the proto definition 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_shape.proto

I ran your tensor in python, it should generate node def as following:
>>> scalarInput.op.node_def
name: "main_scalarinput"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 21168
      }
    }
  }
}

Can you try to re-save the model again?

**Comment by icysapphire** [comment]
Interesting, because this frozenmodel is perfectly working on a tensorflow-based C++ app.
However, I've tried re-saving the model. While running the model:
`tf.train.write_graph(sess.graph_def, path, graphdef_filename)`
Then:
```
input_graph_path = graphdef_filename
input_saver_def_path = ""
input_binary = False
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
clear_devices = False

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, input_checkpoint_path,
                          output_node_names, restore_op_name,
                          filename_tensor_name, output_graph_path, False, "")

```
[Now it shows the correct shape]
Finally:

> tensorflowjs_converter     --input_format=tf_frozen_model     --output_node_names='main_qout,main_state_out,main_predict'     --saved_model_tags=serve     model-fullgraphdef.pb   web_model

Now, running in the browser, it simply refuses to load!

> Unhandled promise rejection 
> Error
> columnNumber: 17
> fileName: "http://localhost:1234/ml4.29d6f37a.js"
> lineNumber: 30695
> message: "Based on the provided shape, [2048], the tensor should have 2048 values but has 1"
> stack: "assert@http://localhost:1234/ml4.29d6f37a.js:30695:17\ne@http://localhost:1234/ml4.29d6f37a.js:30909:78\nparcelRequire<[\"node_modules/@tensorflow/tfjs-core/dist/tf-core.esm.js\"]</Tensor</e.make@http://localhost:1234/ml4.29d6f37a.js:30911:12\ntensor@http://localhost:1234/ml4.29d6f37a.js:31643:490\no@http://localhost:1234/ml4.29d6f37a.js:35801:46\ndecodeWeights@http://localhost:1234/ml4.29d6f37a.js:35805:5\nparcelRequire<[\"node_modules/@tensorflow/tfjs-converter/dist/tf-converter.esm.js\"]</FrozenModel</e.prototype.load/</<@http://localhost:1234/ml4.29d6f37a.js:41983:174\ni/</<@http://localhost:1234/ml4.29d6f37a.js:40499:64\ni/<@http://localhost:1234/ml4.29d6f37a.js:40484:14\ns@http://localhost:1234/ml4.29d6f37a.js:40457:11\n"

What's wrong? Thanks for the support!

**Comment by pyu10055** [comment]
@icysapphire  This looks like the weight tensors data did not matched with the definition.

can you share the converted model and weight manifest files?

**Comment by pyu10055** [comment]
@icysapphire you are probably right about the browser caching, it is safe to always do a hard browser refresh if the model files are changed.

The rank of the input tensor does not match for main_scalarinput, you can use reshape op

tensor = tensor.reshape([1, 21168]) and use that as the value for 'main_scalarinput'.

**Comment by icysapphire** [comment]
@pyu10055 It doesn't work and it doesn't seem easily debbugable.
With code:
```
  predict(input) {
    const one = tf.scalar(1, 'int32');
    const t = tf.randomNormal([21168]);
    return this.model.executeAsync(
        {'main_scalarinput': t.reshape([1, 21168]), "main_train_length":one, "main_batch_size":one}, OUTPUT_NODE_NAME);
  }
```
I get 

> Promise {<pending>}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: TypeError: Cannot read property '0' of null
>     at e.getValuesFromTexture (http://localhost:1234/ml4.29d6f37a.js:27227:111)
>     at e.readSync (http://localhost:1234/ml4.29d6f37a.js:27213:81)
>     at e.readSync (http://localhost:1234/ml4.29d6f37a.js:25077:25)
>     at e.dataSync (http://localhost:1234/ml4.29d6f37a.js:24679:48)
>     at http://localhost:1234/ml4.29d6f37a.js:26388:61
>     at Array.forEach (<anonymous>)
>     at runProgram (http://localhost:1234/ml4.29d6f37a.js:26384:92)
>     at e.compileAndRun (http://localhost:1234/ml4.29d6f37a.js:27593:73)
>     at e.concat (http://localhost:1234/ml4.29d6f37a.js:27283:61)
>     at ENV.engine.runKernel.a (http://localhost:1234/ml4.29d6f37a.js:32996:14)
> tf-core.esm.js:17 Uncaught (in promise) TypeError: Cannot read property '0' of null
>     at e.getValuesFromTexture (tf-core.esm.js:17)
>     at e.readSync (tf-core.esm.js:17)
>     at e.readSync (tf-core.esm.js:17)
>     at e.dataSync (tf-core.esm.js:17)
>     at tf-core.esm.js:17
>     at Array.forEach (<anonymous>)
>     at runProgram (tf-core.esm.js:17)
>     at e.compileAndRun (tf-core.esm.js:17)
>     at e.concat (tf-core.esm.js:17)
>     at ENV.engine.runKernel.a (tf-core.esm.js:17)

**Comment by pyu10055** [comment]
I have a fix PR for your model, with that, I was able to complete the inference execution.

**Comment by icysapphire** [comment]
Great, @pyu10055, thanks a lot! I'm waiting for npmjs publish in order to try that! [ETA?]
In the meanwhile, I'd like to ask you for another problem with my unlucky model.. in my model there's a LSTM cell: in python (but also in the C++ tensorflow-based app) I am able to feed in the input tensor and also a particular rnn state, do inference, get back output and rnn state (to be used in the next inference execution with another input)..
however tfjs refuses input at node named "main_state_in" because it has already decided that this is not an input node. How can I specify in the tfjs conversion process that this particular node is input?

Here it is the graphdef:
[standard_DRQN_graphdef.pbtxt.zip](https://github.com/tensorflow/tfjs/files/2307505/standard_DRQN_graphdef.pbtxt.zip)

**Comment by allenwangcheng** [comment]
is your output of tf version code  same with your tfjs version code?
