### ISSUE TITLE
add tfjs_graph_model as input_format

### ISSUE THREAD

**Issue by yoch** [tensorflow/tfjs#6154]
**System information**
- TensorFlow.js version (you are using): 2
- Are you willing to contribute it (Yes/No): I don't think that I can contribute

**Describe the feature and the current behavior/state.**
The tfjs_graph_model is currently not supported ad an input format.
Sometimes it will be beneficial to be able to revert the conversion step, e.g. in keras format.

**Who will benefit with this feature?**
Users that doesn't use Tensorflow.js but interested to use some models with TF

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by gaikwadrahul8** [comment]
Hi, @yoch 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and it seems like we haven't implemented this feature yet and you can refer official documentation of [TensorFlow.js converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) so May I know are you still looking for this feature in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
