### ISSUE TITLE
tfjs-v3.13.0 and tfjs-backend-wasm 3.13.0 for  MoveNet multipose Backend WASM

### ISSUE THREAD

**Issue by Didi3333** [tensorflow/tfjs#6155]
With pose detection 1.0.1 and tfjs 3.13.0 and tfjs-backend-wasm 3.13.0

This issue is only with model Movenet Multipose:

![image](https://user-images.githubusercontent.com/32233417/154287432-523afee3-8273-47c8-87ef-28e41af521a7.png)

With this conf :

tf.setBackend('wasm')

modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING

This pop-up appear :  Kernel 'Reciprocal' not registered for backend wasm , this model work well but slowly with backend webgl

![145442149-e4f4c8e7-6c06-417b-92a3-8b591a4b64b1](https://user-images.githubusercontent.com/32233417/154288330-c8d6e90d-304c-4326-9432-53a831ddbdad.png)

With model type : movenet.modelType.SINGLEPOSE_LIGHTNING there is no issue with wasm

**Comment by rthadur** [comment]
Sorry for delay , original issue https://github.com/tensorflow/tfjs/issues/5932#event-6084917449 was reopened and will be addressed there.Closing this issue. Thank you
