### ISSUE TITLE
It should be easier to load a posenet checkpoint from a custom url.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#616]
Currently - there is no easy way to load a posenet model from a custom url.  In my case I want to be able to load it from a local file server so that it is available offline.

I suggest to either expose another api method to load which takes a url, or export more of the internal classes and types that make loading possible so that you can build your own model loader (for example the CheckpointLoader should be exported).

**Comment by rthadur** [comment]
Posenet will not be supported in future , please refer to movenet  model in future.
