### ISSUE TITLE
[webgpu] benchmark issues

### ISSUE THREAD

**Issue by songhn233** [tensorflow/tfjs#6160]
**Describe the current behavior**

Hi, I found benchmark scripts in `tfjs-backend-webgpu`, but they are running with errors due to missing `build-deps` script, is the webgpu version of benchmark still maintained?

```json
{
  "scripts": {
    "benchmark": "yarn && yarn build-deps && karma start --grep=benchmark --browsers=chrome_webgpu",
  }
}
```

I see that [TensorFlow.js Model Benchmark](https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html) is available, but it is model specific, I would like to know the performance comparison of basic tensors or operations.

**Comment by qjia7** [comment]
@songhn233 You are right. The benchmark scripts is outdated. We haven't updated it yet. You can use `yarn test` temporarily, which will run all tests including the ops benchmarks.
