### ISSUE TITLE
TFJS React Native giving random and wrong results on iOS

### ISSUE THREAD

**Issue by ducky777** [tensorflow/tfjs#6161]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows, iOS, Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 13, Samsung Galaxy Fold 3
- TensorFlow.js installed from (npm or script link): npm i @tensorflow/tfjs-react-native
- TensorFlow.js version (use command below): 3.13.0
- Browser version: -
- Tensorflow.js Converter Version: tensorflow 2.6.0 python

**Describe the current behavior**

i'm getting very random/wrong results when running tfjs rn on an iPhone. the following are the results which are wrong

```
Array [
  Array [
    0.97612903,
    0.01050567626953125,
    0.0007758140563964844,
    0.83837890625,
    0.276123046875,
    0.9267578125,
    0.00025463104248046875,
    0.000011324882507324219,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
  ],
]
```
model load function
```
await tf.ready();
if(modelJSON && modelWeights){
  const loadedModel = await loadGraphModel(bundleResourceIO(modelJSON, modelWeights));
  setModel(loadedModel)
}
```

inference function
```
const onReady = React.useCallback(
    (images) => {
      const loop = async () => {
        const nextImageTensor = tf.cast(images.next().value.reverse(1).reverse(-1).expandDims(0), 'float32').div(tf.scalar(255.0, "float32"));
        const predictions = await model.executeAsync(nextImageTensor);
        setPredictions({
          predictions: predictions,
          img: nextImageTensor
        });
        camRef.current = requestAnimationFrame(loop);
      };
      loop()
      // .catch((e) => {
      //   console.log("Caught error!")
      // })
    },
    [setPredictions]
  );
```

model i'm using is yolov5-nano

it works properly on android. 

**Describe the expected behavior**

on the same image i get the following on Android (samsung galaxy fold 3) which is the correct one
```
Array [
  Array [
    0.89697265625,
    0.928567626953125,
    0.77938091283,
    0.83837890625,
    0.99128372305,
    0.9267578125,
    0.27389136875,
    0.938228374,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
  ],
]
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
app was built using `expo`

**Comment by shmishra99** [comment]
Hi @ducky777
Apology for the late response. Could you please let us know if your issue has been resolved or you are still looking for the solution? I would suggest you to give a try with the latest version of `@tensorflow/tfjs@4.4.0` and check if your issue is resolving or not.
Thank You !!
