### ISSUE TITLE
tfjs-node on arm64

### ISSUE THREAD

**Issue by MincoMK** [tensorflow/tfjs#6162]
I'm on pi4 arm64. I run this command and I got an error.
```bash
npm i @tensorflow/tfjs-node
```
```error
npm ERR! Error: Unsupported system: cpu-linux-arm64
```
How to fix this? I want to use tfjs-node.
I'm on TensorFlow discord, and please dm me if you can. ([My discord profile](https://discord.com/users/590826711147347973))

**Comment by rthadur** [comment]
There is already issue opened for tracking the same request here https://github.com/tensorflow/tfjs/issues/5937 , please comment there. Thank you
