### ISSUE TITLE
Feature Request : tf.tensor.saveToComputer() tf.tensor.loadFromURL() 

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs#617]
I am doing some manipulation with the [CIFAR-10 binary files](https://www.cs.toronto.edu/~kriz/cifar.html) (Not much fun, but it's coming along. Each CIFAR binary is 10,000 items in this order: A label byte, then 32x32 bytes in this weird order: all the red, all the green, all the blue. Each file is 30,730,000 bytes long.). This file is not well organized for loading into a tensor. (Unless you have some secret trick.)

 I can probably save a reorganized Uint8ClampedArray() and then load that into a tensor, but it would be really useful for sharing data to be able to completely save a tensor.

Unlike saving a model with local storage etc, for a tensor you would only need 2 methods:

`tf.tensor.saveToComputer(myTensor, 'myTensorFileName.tfjs') `

Then upload your saved tensor to your website or github. Then anyone wanting to use it could just:

`tf.tensor.loadFromURL('https://myRepo/mySavedTensors/myTensorFileName.tfjs') `

(The person might have to put the file on their website to manage CORS issues.)

Note: [Model saving and loading](http://rocksetta.com/tensorflowjs/beginner-examples/tfjs11-load-weights.html) is really useful, however manipulating a loaded model is fairly complex. With Tensor saving and loading available, then people could fairly easily make new models using the old data.

It would be great to have a .tfjs file extension.

**Comment by caisq** [comment]
@hpssjellis You might be interested in checking out this library that @ry wrote: https://github.com/propelml/tfjs-npy/blob/master/npy.ts

It can serialize a TensorFlow.js tf.Tensor to an ArrayBuffer and do the reverse. From there, you can write your own IO code, depending on whether you are in the browser (in which case you presumably want to use local storage or IndexedDB) or in Node.js (in which case you probably want to use the native filesystem).

**Comment by hpssjellis** [comment]
> @hpssjellis You might be interested in checking out this library that @ry wrote: [https://github.com/propelml/tfjs-npy/blob/master/npy.ts](https://github.com/propelml/tfjs-npy/blob/master/npy.ts)


Thanks @caisq that is a much more robust library than what I am working on. However, the original request still stands, **Tensor saving and loading** would be a huge step for simplifying Tensorflowjs.

Data input, especially images, in Javascript is fairly cumbersome.

With Tensor saving and loading student's could simply load pre-made tensors, and run their own models, all very efficiently.

**Comment by hyun-yang** [comment]
@hpssjellis 
You might want to check following discussion.

[loadModel from url doesn't work in Node](https://github.com/tensorflow/tfjs/issues/410)
[tf.loadModel not working in ionic](https://github.com/tensorflow/tfjs/issues/272)

I'm still waiting for this feature :)

**Comment by caisq** [comment]
@hyun-yang I don't think the bugs you referred to are directly related to @hpssjellis's feature request, which is mainly about saving tensors that are not weights of a model.

Regarding saving/loading models in Node.js, the native filesystem route (file:// URL scheme) is already working in tfjs-node. Just make sure you import both the @tensorflow/tfjs and @tensorflow/tfjs-node packages in your Node.js program.

The http:// saving/loading route is "kinda" working in tfjs-node at this moment. You just need to depend on the node-fetch package and set the global fetch:  `global.fetch = require('node-fetch')`.

**Comment by hpssjellis** [comment]
I am fine closing this unless someone wants it to remain open.

**Comment by haganbt** [comment]
Hi all,

Im using a node.js microservices runtime whereby I cannot set `global.fetch`. Is there a workaround at all?

```javascript
const mobilenet = require('@tensorflow-models/mobilenet');
const model = await mobilenet.load();
```
Throws:

```
browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
```

I do have access to `node-fetch` but cannot set a global.

Can anyone advise?

**Comment by caisq** [comment]
@haganbt I don't know much about your node.js microservice. But instead of setting `global.fetch`, is it possible for you to set `fetch` (the implicit global one)?

**Comment by haganbt** [comment]
Thanks @caisq, afraid not. Here is my full function:

```javascript
const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');  
const mobilenet = require('@tensorflow-models/mobilenet');

const fetch = require('node-fetch');

async function onGet(context) {
    const model = await mobilenet.load();
}

module.exports = onGet;
```

If I just set `fetch = require('node-fetch');` then I get `fetch is not defined`.

**Comment by caisq** [comment]
@haganbt Thanks for the reply. I'm sorry that there is no simple workaround to this currently. This is related to https://github.com/tensorflow/tfjs/issues/479, which is on our TODO list.

Do you have access to the local filesystem in your microservice? If so, is it possible for you to use the node `http` module to download the required `model.json` and the sharded weight files to the local filesystem and them load the model from the local files with the file:// URL?

**Comment by haganbt** [comment]
Many thanks @caisq and no apology necessary; fully understand the TODO list is large ;)

I actually own the microservices platform ([eventn.com](eventn.com)) and im currently experimenting with adding support for tensorflow.js as i think it would be really nice to expose services via HTTP.

Im reluctant to go down the path of hosting the models. Reading #479, the description nails it in that these then can be maintained externally.

I'll watch #479 for updates. I think its a blocker for the platform until then.

Thanks again for the support.

**Comment by caisq** [comment]
@haganbt Got it! Thanks for letting us know. I'll prioritize fixing #479.

**Comment by haganbt** [comment]
@caisq - it looks like #479 has been closed. Would it be possible to reopen and prioritize as I cannot find an alternative to load a model remotely without this.
