### ISSUE TITLE
Downgrade dependencies to install tfjs-react-native?

### ISSUE THREAD

**Issue by JohnZcp** [tensorflow/tfjs#6170]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.6.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js react native version: 0.8.0

**Describe the problem**
I am trying to use the library tfjs-react-native, and somehow it ask me to downgrade my react version (from 0.67.1 to 0.59.10), and other dependencies(expo camera, expo-gl, and expo-pl-cpp needs to be 7.0.0). These versions are very old. Does anyone know what's wrong with it?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the install instruction in the readme file.

**Comment by mattsoulanille** [comment]
tfjs-react-native currently [has a peer dependency on react-native 0.58.0](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/package.json#L79), and it is [tested against react-native 0.59.10](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/package.json#L34) (and the expo versions you mention). It probably needs to be updated to work with newer versions of react native. I'll take a quick look tomorrow.

**Comment by mattsoulanille** [comment]
Hi @JohnZcp, and sorry for the late reply.

I tried porting our integration testing app to expo with React Native 0.64.3 and [I was successful](https://github.com/mattsoulanille/tfjs/tree/rn_expo_test/tfjs-react-native/integration_expo). When running yarn, there are a lot of warnings about wrong peer dependency versions like you saw, but the demos still work. Consequently, this is probably just an issue with our peer dependency version ranges, and we should update them to accept later versions without these warning messages. 

I'm pretty confident you should be able to use React Native 0.67.1 since I don't see any breaking changes from 0.64.3 that would affect tfjs-react-native in the [changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md).

Warning messages:
```
warning " > @tensorflow-models/blazeface@0.0.7" has unmet peer dependency "@tensorflow/tfjs-converter@^3.1.0".
warning " > @tensorflow-models/blazeface@0.0.7" has unmet peer dependency "@tensorflow/tfjs-core@^3.1.0".
warning " > @tensorflow-models/mobilenet@2.1.0" has unmet peer dependency "@tensorflow/tfjs-converter@^3.1.0".
warning " > @tensorflow-models/mobilenet@2.1.0" has unmet peer dependency "@tensorflow/tfjs-core@^3.1.0".
warning " > @tensorflow-models/posenet@2.2.2" has unmet peer dependency "@tensorflow/tfjs-converter@^3.0.0-rc.1".
warning " > @tensorflow-models/posenet@2.2.2" has unmet peer dependency "@tensorflow/tfjs-core@^3.0.0-rc.1".
warning "@tensorflow/tfjs > @tensorflow/tfjs-data@3.13.0" has unmet peer dependency "seedrandom@~2.4.3".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-backend-cpu@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-backend-webgl@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-core@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "expo-asset@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "expo-camera@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "expo-gl@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "react@^16.12.0".
warning "expo-camera > @koale/useworker@4.0.2" has incorrect peer dependency "react@^16.8.0".
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
```

**Comment by Enkomm** [comment]
@mattsoulanille I try both react-native 0.67.1 and 0.67.3, await tf.ready() is crashed. When I downgrade react-native to 0.64.3, it's worked.

**Comment by MSufyan7501** [comment]
@mattsoulanille i am trying to install tensorflow/tfjs-react-native package and i am using react native version 0.71.0 it is not being installed can you or any one please help me solving this issue
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: DermaCure@0.0.1
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!   peer react@"18.1.0" from react-native@0.70.0
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.70.0" from the root project
npm ERR!     peer react-native@">= 0.58.0" from @tensorflow/tfjs-react-native@0.8.0
npm ERR!     node_modules/@tensorflow/tfjs-react-native
npm ERR!       @tensorflow/tfjs-react-native@"*" from the root project
npm ERR!     1 more (@react-native-async-storage/async-storage)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from @tensorflow/tfjs-react-native@0.8.0
npm ERR! node_modules/@tensorflow/tfjs-react-native
npm ERR!   @tensorflow/tfjs-react-native@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\muham\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\muham\AppData\Local\npm-cache\_logs\2023-03-29T14_45_01_084Z-debug-0.log
