### ISSUE TITLE
The bug of building webcam real-time object detection with tfjs

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tfjs#6174]
I'm building a webcam object detection system with tfjs for the purpose of detecting objects in real time.

html part:

```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.13.0/dist/tf.min.js"></script>
```

Object detection main code part:

```javascript
async function detectFrame (video, model) {

  const input = tf.tidy(() => tf.image.resizeBilinear(tf.browser.fromPixels(video),
    [modelWeight, modelHeight]).div(255.0).expandDims(0));

  model.executeAsync(input).then(res => {
    renderPredictions(res); 

    tf.dispose(res); 

    requestAnimationFrame(() => {
      detectFrame(video, model); 
    });
  })
};
```

The program runs normally for about tens of seconds, and the following bugs appear:

![ksnip_20220224-070813](https://user-images.githubusercontent.com/41098760/155425652-e89921c6-1271-44cd-95a5-25d087298083.png)
![ksnip_20220224-070836](https://user-images.githubusercontent.com/41098760/155425663-544ea30b-ef89-422c-8747-24e2cb59cef2.png)
![ksnip_20220224-070850](https://user-images.githubusercontent.com/41098760/155425674-70e16887-3a47-4fe3-aabf-617b8922ee9b.png)
![ksnip_20220224-070901](https://user-images.githubusercontent.com/41098760/155425681-abd23894-ea3d-4656-be07-1b6cfcaa5499.png)

**Comment by rthadur** [comment]
You need to dispose both input and predictions as below : 

```
const prediction = await m.executeAsync(input);
prediction.dispose();
input.dispose();
```

can you please share a working example on codepen ?

**Comment by Zengyf-CVer** [comment]
@rthadur 
Thank you very much for your reply, I used your method and the problem is solved. thank you very much.
