### ISSUE TITLE
blazeface landmark doesn't return correct values for up-side-down image

### ISSUE THREAD

**Issue by nickticket2u** [tensorflow/tfjs#6175]
hi guys, if I call estimateFaces for upside down face image, the mouth coordinate Y value will still be larger than the eyes and nose. if I correct the image with correct face image, estimateFaces will also return mouth coordinate Y larger than eyes and nose, but a different value compared to the upside down orientation.

Is there a way to identify orientation from the values returned by estimateFaces ?

**Comment by rthadur** [comment]
did you try using 'FlipLeftRight' to reverse the image before passing it to estimateFaces ? 

https://js.tensorflow.org/api/latest/#image.flipLeftRight
