### ISSUE TITLE
Kernel 'PadV2' not registered for backend 'webgl'

### ISSUE THREAD

**Issue by rohanmohapatra** [tensorflow/tfjs#6178]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution: Mac OS
- TensorFlow.js installed from npm: Yes
- TensorFlow.js version (use command below):
```
  "@tensorflow-models/body-pix": "^2.2.0",
    "@tensorflow/tfjs": "^1.2",
```
- Browser version:Chrome Version 98.0.4758.109 (Official Build) 

**Describe the current behavior**
I tried to follow the bodyPix tutorial 
```
 const net = await bodyPix.load()
    const segmentation = await net.segmentPerson(videoRef.current, {
      flipHorizontal: true,
      internalResolution: 'medium',
      segmentationThreshold: 0.5,
    })
    drawBody(segmentation, canvas, videoRef.current)
```
I get an error ` Kernel 'PadV2' not registered for backend 'webgl'` at
```
const segmentation = await net.segmentPerson(videoRef.current, {
     | ^  35 |   flipHorizontal: true,
  36 |   internalResolution: 'medium',
  37 |   segmentationThreshold: 0.5,
```

**Describe the expected behavior**
Everything should work fine

**Other info / logs**
i am using CRA bundler for my react app.

**Comment by rthadur** [comment]
Please use latest version of tfjs, kernal 'PadV2' is added here https://github.com/tensorflow/tfjs/pull/5359 . Thank you
