### ISSUE TITLE
Setting of iou and nms thresholds of tf.js

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tfjs#6179]
How can I change the IoU and NMS thresholds in the .js file for object detection in tf.js?

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Zengyf-CVer** [comment]
@rthadur 
This is my main code snippet, how do I set the IoU and NMS thresholds of the model, and what parameters do I pass?

#### html file
```html
<script src=["https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.13.0/dist/tf.min.js"]()></script>
```

#### javascript file
```javascript
const video01 = document.getElementById("video-rt");
... ...
async function detectFrame(video, model) {
    
    let [modelWeight, modelHeight] = model.inputs[0].shape.slice(1, 3);

    
    let input = tf.tidy(() => tf.image.resizeBilinear(tf.browser.fromPixels(video), [modelWeight, modelHeight]).div(255.0).expandDims(0));

   
    await model.executeAsync(input).then(res => {

        renderPredictions(res); 

        requestAnimationFrame(() => {
            tf.dispose(res);
            input.dispose();

            
            detectFrame(video, model); 
        });
    });
}

```

**Comment by vladmandic** [comment]
in majority or models, IOU and NMS are done as post-processing tasks - so it's really up to you to run NMS and specify IOU and other params there.
  
if model had such functionality internally (rarely, but i've seen it), it would be part of the input passed to `execute` method.

**Comment by Zengyf-CVer** [comment]
@vladmandic 
I don't know what function to use or which parameter to adjust in tf.js to control the threshold of NMS and the threshold of IoU?

**Comment by vladmandic** [comment]
<https://js.tensorflow.org/api/latest/#image.nonMaxSuppressionAsync>

now, how do you use it depends on the output format of your model (e.g. what is `res` in your case).
