### ISSUE TITLE
yarn seems to be missing from dependencies

### ISSUE THREAD

**Issue by ljj7975** [tensorflow/tfjs#618]
#### Browser version : N/A

I tried to get local min.js version of jfjs from source by running `npm run build-npm`
However, even though I ran `npm install` to install all the dependencies listed in package.json, the script failed saying `./scripts/build-npm.sh: line 21: yarn: command not found`

after installing yarn explicitly, script worked fine.
when I checked package.json, yarn was missing.

Maybe it's good to add yarn as dependency unless this behaviour is intended?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
