### ISSUE TITLE
demos broken on master

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#62]
_From @physicsrob on March 30, 2018 17:54_

Demos are broken on master after moving some of the files out of the repo.  Also the 'yarn prep' command is gone, which means users need to run yarn from the root directory and the demos directory, which I don't think is particularly obvious.

I'm sure this is part of the big shuffle and will be resolved shortly.

One question:  Is there any sort of slack/irc channel for this project?  It'd be nice to be able to communicate in a less formal manner than creating issues.

_Copied from original issue: tensorflow/tfjs-core#911_

**Comment by dsmilkov** [comment]
_From @tafsiri on March 30, 2018 18:52_

Yes we will generally be removing demos from this repo, possibly porting some to @tensoflow/tfjs-examples (we want to centralize demos/examples there as much as we can). Some of the demos use now deprecated APIs so they might come back in future, but we'll look at this case by case.

Definitely hear you on the benchmarks keeping benchmarks available. We also have another benchmark here https://github.com/tensorflow/tfjs-layers/blob/master/integration_tests/benchmarks/index.html for the new higher level api (which depends on tfjs-core).

**Comment by dsmilkov** [comment]
_From @QuantumInformation on March 30, 2018 20:5_

@tafsiri We also have a discord server where people can get real-time info and interaction on tfjs.

https://discord.gg/64MVzQX

**Comment by tafsiri** [comment]
closing as we have removed demos and have separate issue for bringing back benchmarks
