### ISSUE TITLE
Why does getWeights shirnk the returning type to Tensor instead of using the orig type Variable?

### ISSUE THREAD

**Issue by lochbrunner** [tensorflow/tfjs#620]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.7.4
#### Browser version
Not relevant here.
#### Describe the problem or feature request

`Bidirectional.getWeights(bool)`
`Layer.getWeights(bool)`
`LayerVariable.batchGetValue(...)` and 
`LayerVariable.read()` are returning each an `Tensor` (respectively `Tensor[]` ) instead of the original type of the forwarded `LayerVariable.val` which is a `tfc.Variable`.

See https://github.com/tensorflow/tfjs-layers/blob/master/src/variables.ts#L81 
https://github.com/tensorflow/tfjs-layers/blob/master/src/variables.ts#L40 
https://github.com/tensorflow/tfjs-layers/blob/master/src/engine/topology.ts#L1167 and
https://github.com/tensorflow/tfjs-layers/blob/master/src/variables.ts#L309

Is there a reason for that?

If not, should I fix this?

**Comment by bileschi** [comment]
I suppose it is meant as a scoping and mutability hint to the caller.  If Layer.getWeights returned a Variable, and the user then changed the value of the variable, what behavior would we expect?  Should the layer also adopt the new value?  If the layer's value is updated then in some other way, say by a model.fit() call, should the changed state be visible in the user's view through the variable.

Returning a constant snapshot prevents having to worry about such action-at-a-distance concerns.  If the user needs to be able to alter the internals of the Layer, they could use layer.setWeights

**Comment by lochbrunner** [comment]
In my opinion `getWeights` is always a snapshot and should not change the internals of the layer.
I agree with @bileschi that setWeights should only update the weights.

For instance in may case I need the variables name. Which is present in Variable but not in Tensor. From the current typescripts point of view. But actually you have the name because getWeigths is returning a Variable, which might be confusing...
Currently I have something like

```typescript
const name = (layer.getWeights()[0] as Variable).name;
```
Which looks like a bad hack. It would be nicier to write it like

```typescript
const name = layer.getWeights()[0].name;
```

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
