### ISSUE TITLE
tfjs-backend-webgpu package is near obsolete

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6200]
last published version of `@tensorflow/tfjs-backend-webgpu` is **0.0.1-alpha.8** some 5 months ago  
and its built against `tfjs` **3.9.0** which is now 5 versions behind

please refresh the build

**Comment by qjia7** [comment]
@vladmandic Thanks for reporting this issue. We are considering how to regularly release tfjs-backend-webgpu together with other backends. The biggest issue is that webgpu is not well integrated into current testing frameworks. Currently, we have to release one manually on demand. @mattsoulanille is providing help on this. Thanks.

**Comment by vladmandic** [comment]
thanks @qjia7 
btw, its not an issue for me as i'm using `tfjs` from main branch anyhow  
but so much good work has gone into `tfjs-backend-webgpu` that has not been released

**Comment by qjia7** [comment]
A new one is here https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu. Thanks Matt's help.
