### ISSUE TITLE
npm 3.14.0 tf.setBackend("wasm") got error 'Uncaught SyntaxError: Invalid or unexpected token '

### ISSUE THREAD

**Issue by ironmangithub** [tensorflow/tfjs#6203]
The newest npm version 3.14.0 got error 'Uncaught SyntaxError: Invalid or unexpected token' when set backend to wasm. Is it a bug or not used properly? Thanks!

Codes:
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-backend-wasm';
await tf.setBackend('wasm');

npm version:
@tensorflow/tfjs: 3.14.0
@tensorflow/tfjs-backend-wasm: 3.14.0

**Comment by gyagp** [comment]
We met a similar issue at Intel. We use apache2 as http server to host e2e benchmark, and it couldn't load due to this issue. The strange thing is if we switch to python http server (python3 -mhttp.server), everything became fine.

**Comment by mattsoulanille** [comment]
I tried serving the e2e benchmarks with python3's http.server and with apache2 (serving the `e2e/benchmarks` dir), and I wasn't able to reproduce the issue. Can you send me some more details on your configuration?

Here's my config. I just changed the `DocumentRoot` from the default config.
/etc/apache2/sites-available/000-default.conf
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/tf/

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

I also copied the contents of `e2e/benchmarks` to /var/www/tf`.

**Comment by gyagp** [comment]
I dug a bit further. To enable multiple-threads support for WASM, I enabled COOP and COEP to set up a cross-origin isolated env, and this is the cause of this issue. My apache2 conf file is as below:

<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /workspace/server

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

    # Redirect HTTP to HTTPS
    #RewriteEngine On
    #RewriteCond %{HTTPS} !=on
    #RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    DocumentRoot /workspace/server
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    SSLEngine on
    SSLCertificateFile /etc/apache2/certificate/apache-certificate.crt
    SSLCertificateKeyFile /etc/apache2/certificate/apache.key

    # a2enmod headers
    Header set Cross-Origin-Embedder-Policy require-corp
    Header set Cross-Origin-Opener-Policy same-origin
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

Please pay attention to the 2 lines starting with "Header", which is the configuration to enable COOP and COEP. If I comment out these 2 lines and restart apache2 service, everything is fine (For sure, without COOP and COEP). This can explain why we didn't see the issue for the python http server.

To enable apache2 https support, I did the following before:
apt-get install apache2 openssl
a2enmod ssl
mkdir /etc/apache2/certificate
cd /etc/apache2/certificate
openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out apache-certificate.crt -keyout apache.key

**Comment by mattsoulanille** [comment]
@jinjingforever and I were able to find the cause of this error. in dist/tf-backend-wasm.js on line 823 in `wasmWorkerContents`, there's a `\n` in `if(ENVIRONMENT_IS_NODE){fs.writeSync(2,text+"\n")`. This is for some reason being expanded to a newline character, and since that character is in the middle of a string, the result is invalid JavaScript. Manually removing it fixes the benchmark tool.

Now I'm looking into why this "\n" is present and why it's being expanded into a newline.

**Comment by ironmangithub** [comment]
> @jinjingforever and I were able to find the cause of this error. in dist/tf-backend-wasm.js on line 823 in `wasmWorkerContents`, there's a `\n` in `if(ENVIRONMENT_IS_NODE){fs.writeSync(2,text+"\n")`. This is for some reason being expanded to a newline character, and since that character is in the middle of a string, the result is invalid JavaScript. Manually removing it fixes the benchmark tool.
> 
> Now I'm looking into why this "\n" is present and why it's being expanded into a newline.

this works for me. Thanks!
