### ISSUE TITLE
Layers - convert executeInternal from recursion to iteration

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#621]
Profiling a real model that is ~130 layers deep revealed that a significant time is spend on the recursive calls of `executeInternal`, where the call stack increases by 130 levels.

To allow execution of arbitrarily deep models, and improve performance, we should convert the `executeInternal` to an iterative approach, by implementing our own stack.

**Comment by bileschi** [comment]
How complicated would the implementation be?  Keep in mind that models in general are DAGs of layers, potentially with inputs/outputs at multiple depths, not only linear stacks.

What state needs to be maintained at each stack level?

**Comment by caisq** [comment]
This shouldn't be too difficult even for the general DAG case. A depth-first search with a stack keeping track of the current status should suffice.
