### ISSUE TITLE
Support cumprod

### ISSUE THREAD

**Issue by iislucas** [tensorflow/tfjs#6210]
**System information**
- TensorFlow.js version (you are using): 3.14
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**
`cumprod` is not currently supported, I need it for work I'm doing experimenting with visualising activation functions using TFJS.

**Will this change the current api? How?**
It will add `cumprod` to the API, which will mirror the tensorflow API, and be a lot like `cumsum`.

**Who will benefit with this feature?**
Anyone who wants to use the cumprod, or who uses a model that depends on it. 

**Any Other info.**
Initial implementation here: https://github.com/iislucas/tfjs/tree/iislucas-cumprod

**Comment by rthadur** [comment]
Related PR has merged and the changes are available in latest release(v3.18.0). Thank you @iislucas for contributing.
