### ISSUE TITLE
tfjs-node: make tfjs-node-gpu fall back to CPU on machines without CUDA GPUs

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#622]
The tensorflow's GPU shared library actually includes CPU kernels. The tensorflow-gpu package can be installed on machines without CUDA GPUs. It'll just fall back to the CPU kernels.

Currently tfjs-node-gpu can't even be installed on machines without CUDA GPUs. We should make the behavior more similar between Python and tfjs-node, i.e., allow install of tfjs-node-gpu even if there is no CUDA GPU; when the code runs, fall back to CPU kernels.

The benefit: when writing tfjs-node code, one wouldn't have to be constrained to the non-GPU tfjs-node anymore.

**Comment by caisq** [comment]
cc @nkreeger

**Comment by nkreeger** [comment]
Should fallback to CPU ops now.

**Comment by brannondorsey** [comment]
It would appear that in v0.1.17, it does indeed fallback to "cpu", however is this "tensorflow" accelerated "cpu" or the same "cpu" backend one would get from `@tensorflow/tfjs`? In other words, is this fallback equivalent to the exact same backend as one would receive by including `@tensorflow/tfjs-node`? If so, great! But the `tf.getBackend()` names differ ("cpu" vs "tensorflow"). If not, can that support be added so that the fallback still uses the "tensorflow" backend, just without GPU acceleration?

**Comment by kangyizhang** [comment]
Hi @brannondorsey , this fallback is the exact same backend as importing `@tensorflow/tfjs-node`.

For your original question(https://github.com/tensorflow/tfjs/issues/779), `tfjs-node` and `tfjs-node-gpu` require different libtensorflow which was downloaded and binded during installation. So you can not conditionally load the package after it is installed.

**Comment by brannondorsey** [comment]
Hi @kangyizhang, thanks for addressing this question. That is good to hear, although I'm a bit troubled that the backend name when using `tfjs-node` is always "tensorflow" while the fallback from `tfjs-node-gpu` is "cpu". If the fallback is equivalent why do the backend names differ?

```javascript
// run on a CPU-only machine with no CUDA
const tf = require('@tensorflow/tfjs')
require('@tensorflow/tfjs-node')
console.log(tf.getBackend())
// tensorflow
```

```javascript
// Run on a GPU machine with CUDA installed
const tf = require('@tensorflow/tfjs')
require('@tensorflow/tfjs-node-gpu')
console.log(tf.getBackend())
// tensorflow
```

```javascript
// Run on a CPU machine with no CUDA
const tf = require('@tensorflow/tfjs')
require('@tensorflow/tfjs-node-gpu')
console.log(tf.getBackend())
// cpu
```

**Comment by brannondorsey** [comment]
I also just noticed that the third code snippet ^ also throws this message:

```
============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
```

Which is either innacurate or means the fallback isn't working properly. I'm using `tfjs-node-gpu` v0.1.17.

**Comment by caisq** [comment]
@nkreeger Reopening the issue following off-line chat today.

**Comment by chenqing** [comment]
What's the final conclusion? just use tfjs-node-cpu when face both CPU and GPU env?

**Comment by caisq** [comment]
@nkreeger @chenqing This is not resolved yet. If you use tfjs-node-gpu naively on a CPU only environment without CUDA toolkit installed, the library will fall back all the way to the very slow JavaScript backend. We want it to fall back to the CPU backend...

**Comment by chenqing** [comment]
> @nkreeger @chenqing This is not resolved yet. If you use tfjs-node-gpu naively on a CPU only environment without CUDA toolkit installed, the library will fall back all the way to the very slow JavaScript backend. We want it to fall back to the CPU backend...

@caisq thx.
I think I may also create two packages one for CPU and one for GPU until the problem is solved.

**Comment by chenqing** [comment]
What progress have you made recently?

**Comment by xamarindevelopervietnam** [comment]
interesting

**Comment by gaikwadrahul8** [comment]
Hi, @caisq 

Apologize for the delayed response and I tried to install `@tensorflow/tfjs-node-gpu` without `CUDA` and it's installing without any error and I tried below code snippet of user where now it's showing backend `tensorflow` instead of `cpu` so it's seems like we have taken care of this issue if I'm not wrong here 

If Am I missing something here, please let me know ? Thank you!

```
// Previously it was showing the output `cpu` for below code for user.
// Run on a CPU-only machine with no CUDA
const tf = require('@tensorflow/tfjs')
require('@tensorflow/tfjs-node-gpu')
console.log(tf.getBackend())
// cpu
```

```
// Run on a CPU-only machine with no CUDA
const tf = require('@tensorflow/tfjs')
require('@tensorflow/tfjs-node-gpu')
console.log(tf.getBackend())

gaikwadrahul-macbookpro:test-622 gaikwadrahul$ node index.js
tensorflow
gaikwadrahul-macbookpro:test-622 gaikwadrahul$ 
```
