### ISSUE TITLE
cameraWithTensors() crashes the app immediatly on Android 11/12

### ISSUE THREAD

**Issue by GewoonJaap** [tensorflow/tfjs#6230]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android 11/12, no matter which device

- Installed NPM packages: 
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow/tfjs": "^3.14.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo-camera": "~12.1.2",

**Describe the current behavior**

The app crashes immediatly when calling `import { Camera } from 'expo-camera'; cameraWithTensors(Camera);` No error is thrown/can't catch the error with try catch

**Describe the expected behavior**
The app should not crash or atleast throw an error

**Standalone code to reproduce the issue**
https://pastebin.com/raw/JAMdvYTy

**Comment by Guerrero25** [comment]
I am having the same problem. App crashes with no catchable error right after call `await tf.ready()`

> Installed NPM packages:
>"@tensorflow-models/mobilenet": "^2.1.0",
>"@tensorflow/tfjs": "^3.14.0",
>"@tensorflow/tfjs-react-native": "^0.8.0",
>"expo-camera": "~12.1.2",

**Comment by lahiru-98** [comment]
I am having the same issue mentioned by @GewoonJaap  App crashes with no catchable error

**Comment by jinjingforever** [comment]
Hi,

Sorry for the delay. We finally got a phone that can run Android 12:)

Looks like this is a bug in expo-gl. See [here](https://github.com/expo/expo/issues/15811). The only workaround seems to be downgrading expo to 43.0.5 for now. This should fix the crash (tested on Pixel 6)

At this point, you might also notice that the key points no longer appear (or at seemingly random places). If so, add the following before loading the model:

```js
tf.env().set('WEBGL_PACK_DEPTHWISECONV', false);
```

Give it a try! Thanks
