### ISSUE TITLE
Unknown layer: InstanceNormalization

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#626]
#### TensorFlow.js version

0.12.5

#### Browser version

Google Chrome
Version 68.0.3440.106 (Official Build) (64-bit)

#### Describe the problem or feature request

When trying to load a Tensorflow saved model (obtained with the Tensorflow.js converter) in the browser, I get the following error message: 

```
    Error: Unknown layer: InstanceNormalization
```

#### Code to reproduce the bug / link to feature request

The Keras model is [here](https://github.com/bendangnuksung/Image-OutPainting). The code that triggers the error is the following:

```
    await tf.loadModel(MODEL_PATH);
```

**Comment by jeffin07** [comment]
Hello,
i get a similar error when i try to load YOLO model 
Error: Unknown layer: UpsampleLike
are there any updates on this
Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

Apologize for the delayed response and It seems like this issue has been taken care by this PR https://github.com/tensorflow/tfjs/pull/2114 If I'm not wrong, If yes could you please close this issue ? If have I missed something here please let me know ? Thank you!
