### ISSUE TITLE
Face landmark detection face rotation

### ISSUE THREAD

**Issue by rtm-1dyakonov** [tensorflow/tfjs#6261]
Hello!

I've been testing face-landmark-detection. I am really interested in figuring out, how to determine from predictions file whether a person turned his face right/left or not. I mean there 468 points, but how could we process them to identify face rotation?

**Comment by rthadur** [comment]
Thank you @vladmandic , we will be tracking this feature request here https://github.com/tensorflow/tfjs/issues/3835 and also in this issue https://github.com/tensorflow/tfjs/issues/3827 .
