### ISSUE TITLE
yarn install deps inside knn classifier

### ISSUE THREAD

**Issue by redbasecap** [tensorflow/tfjs#6262]
Tried to install dependencies with yarn but always receive this error: 

[1/5] Validating package.json...
[2/5] Resolving packages...
error Package "" refers to a non-existing file '"C:\\Users\\NicolaSpieser\\Documents\\GitHub\\tfjs-models\\knn-classifier\\dist"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

  },
  "dependencies": {
    "@tensorflow-models/knn-classifier": "file:../dist",
    "@tensorflow-models/mobilenet": "2.1.0",
    "@tensorflow/tfjs-backend-cpu": "^3.3.0",
    "@tensorflow/tfjs-backend-webgl": "^3.3.0",

i think the file:../dist is the prob here?

**Comment by rthadur** [comment]
Hi , I tried on my machine and it works well , just make sure there are no trailing spaces after you type `yarn`. Thank you
