### ISSUE TITLE
[WebGPU] Failed to run Depthwise 2D convolution test with dilations > 1 using DepthwiseConv2D3x3Program 

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#6263]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): build tfjs-backend-webgpu from source
- TensorFlow.js version (use command below): 3.14.0
- Browser version: 101.0.4951.7 (Official Build) dev

**Describe the current behavior**
Run [DepthwiseConv2d test](https://github.com/BruceDai/webnn-polyfill/blob/webgpu/test/ops/depthwiseConv2d.js) successfully by WebGPU backend as the same as by WebGL backend.

**Describe the expected behavior**
Failed to run [DepthwiseConv2d test](https://github.com/BruceDai/webnn-polyfill/blob/webgpu/test/ops/depthwiseConv2d.js) by WebGPU backend

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
[DepthwiseConv2d test](https://github.com/BruceDai/webnn-polyfill/blob/webgpu/test/ops/depthwiseConv2d.js) use input of shape [1,7,7,4], weights of shape [3,3,4,1], strides=1, pad='same', dataFormat='NHWC', dilations=2

@qjia7 PTAL, thanks.

**Comment by BruceDai** [comment]
This DepthwiseConv2d issue would lead run DeepLapv3 (dilated) model with incorrect result.

![image](https://user-images.githubusercontent.com/1531742/159936572-20be84a8-f1e0-445b-889c-b71cf35614c9.png)
![image](https://user-images.githubusercontent.com/1531742/159936822-e01d08e0-a9d4-4d77-881a-30211853bc21.png)

![image](https://user-images.githubusercontent.com/1531742/159403563-d7a195a3-f88b-404d-a5ae-85b52bf4f4a8.png)

**Comment by qjia7** [comment]
Fixed by #6264
