### ISSUE TITLE
Please publish @tensorflow-models/face-landmarks-detection 1.0.0 to npm

### ISSUE THREAD

**Issue by dalelane** [tensorflow/tfjs#6265]
It was updated to version 1.0.0 on 7th Jan

https://github.com/tensorflow/tfjs-models/commit/60ffe7596cf5046f235db0301a539c62351be28b#diff-5c09514e8bf64bba7eb91db115d85437f78b1cb8b6db0295374c65284fe61acaR3

But https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection still only has 0.0.3

Would you mind publishing a current build to npm please?

**Comment by rthadur** [comment]
@lina128 could you please help publish newer version to npm ?

**Comment by JoshuaeKaiser** [comment]
Seconded, please publish to NPM. Node of the demo code will run as the API has changed with the new version.

**Comment by rthadur** [comment]
@all new version has been published to npm https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection . Please check it out. Thank you
