### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization UnicodeDecode, RaggedTensorToTensor, UnicodeEncode

### ISSUE THREAD

**Issue by wadethegreat68** [tensorflow/tfjs#6269]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information** windows 10 i7 16 gb of ram
- TensorFlow.js version (you are using): 2.8.0 
- Are you willing to contribute it (Yes/No): Yes if its within my skill level(although that might not be too helpfull)

**Describe the feature and the current behavior/state.**
im trying to get this example running on tfjs 
https://www.tensorflow.org/text/tutorials/text_generation
I feel i am very close and currently have gotten nearly everything past exept the unsupported ops thing
the current behavior is it just saying "ValueError: Unsupported Ops in the model before optimization
UnicodeDecode, RaggedTensorToTensor, UnicodeEncode"
**Will this change the current api? How?**
this will change the current api by adding support for more language proccessing
**Who will benefit with this feature?**
people who want to do language proccessing simalar to this
**Any Other info.**

**Comment by rthadur** [comment]
This will be a feature request , did you get chance to check this lstm model https://github.com/tensorflow/tfjs-examples/tree/master/lstm-text-generation

**Comment by tempdeltavalue** [comment]
also experience this error...

**Comment by tempdeltavalue** [comment]
I'm experience this error , also ..
![Screenshot from 2022-05-31 17-52-29](https://user-images.githubusercontent.com/36921178/171203776-41c4d8e0-09ea-4c40-9a7d-cb4425c3fdc7.png)

**Comment by tempdeltavalue** [comment]
Also some note about this example 
https://github.com/tensorflow/tfjs-examples/tree/master/lstm-text-generation

Here's no explanation how to convert model from Keras to tfjs :( and it's pretty difficult to find some example of that ..

**Comment by tempdeltavalue** [comment]
one more thing , you can comment this line   
 # input_chars = tf.strings.unicode_split(inputs, 'UTF-8') 
 
(and change your code accordingly and you will be able to convert the model)

**Comment by compromyse** [comment]
@tempdeltavalue What exactly should I replace `tf.strings.unicode_split(inputs, 'UTF-8')`?

**Comment by gaikwadrahul8** [comment]
Hi, @wadethegreat68 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and it seems like we haven't implemented these Ops `UnicodeDecode`, `UnicodeEncode` and you can refer [tf.raggedTensorToTensor](https://js.tensorflow.org/api/4.4.0/#raggedTensorToTensor) so May I know are you still looking for missing Ops `UnicodeDecode`, `UnicodeEncode` in TFJs ? 

If someone wants to contribute for these missing Ops `UnicodeDecode`, `UnicodeEncode` then you're always welcome and please feel free to do it and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!
