### ISSUE TITLE
Add tf.pool modeled after tf.nn.pool in Python

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#627]
In Python, [tf.nn.pool](https://www.tensorflow.org/api_docs/python/tf/nn/pool) allows for dilation and strides, while `tf.nn.max_pool` and `tf.nn.avg_pool` have no dilation in their signature.

In TensorFlow.js, we have `tf.maxPool` and `tf.avgPool` but we lack `tf.pool` along with the ability for user-provided `dilation` and `strides`. Support for dilation and strides will require small changes in `pool_gpu.ts` shader, which shouldn't be hard - we already do this for Conv2D - see `conv_gpu.ts` for pointers.

To clarify, tf.maxPool and tf.avgPool's signatures should be unchanged. tf.pool() will be a new method that has additional attributes.

Dilation is needed to speed up inference for some models - see [discussion](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/Ap1yNDeAQuM/umyBFmKxEgAJ) for context.

**Comment by kedevked** [comment]
Hi @dsmilkov ! 
I will work on it. Could you please give the link to conv_gpu.ts and pool_gpu.ts ?

**Comment by kedevked** [comment]
Hi @dsmilkov !
I will try to work on it.
