### ISSUE TITLE
Publish @tensorflow-models/knn-classifier v1.2.3

### ISSUE THREAD

**Issue by JulesFrancoise** [tensorflow/tfjs#6273]
The current version of `@tensorflow-models/knn-classifier` published on npm is v1.2.2, which still relies on `@tensorflow/tfjs-core` v1.
It seems that the package has been [updated on Github](https://github.com/tensorflow/tfjs-models/blob/master/knn-classifier/package.json) in v1.2.3 to rely on `@tensorflow/tfjs-core` v3.

Would it be possible to publish this update to npm?

Thank you in advance!

**Comment by rthadur** [comment]
Thank you , will request to publish new version to npm.

**Comment by rthadur** [comment]
New version has been published to [npm](https://www.npmjs.com/package/@tensorflow-models/knn-classifier) , please verify.
