### ISSUE TITLE
Require support leakyRelu op by WebGPU backend

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#6286]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):3.14.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
Current WebGPU backend doesn't support leakyRelu op, so it is unable to run Object Detection sample with TinyYolo V2 NHWC model.

@qjia7 PTAL, thanks.

**Comment by qjia7** [comment]
Fixed by #6288.
