### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data #5

### ISSUE THREAD

**Issue by LuckyArd110** [tensorflow/tfjs#6294]
// Convert the data to a form we can use for training.
const tensorData = convertToTensor(data);
const {inputs, labels} = tensorData;

data is not defined

**Comment by rthadur** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by LuckyArd110** [comment]
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

any some async code in tutorial, but i has been fixed it
