### ISSUE TITLE
Add tf.confusion_matrix 

### ISSUE THREAD

**Issue by happyhj** [tensorflow/tfjs#630]
I'm working on training a multiclass classification model on a browser with tfjs.
However, I noticed that I need to compute the **confusion matrix** so that I can know the individual class accuracy.

Like tf.confusion_matrix in tensorflow
https://www.tensorflow.org/api_docs/python/tf/confusion_matrix

I'm currently working on implementing confusion matrix function in tfjs-core.
But is it worth it? 

I 'm not sure whether it should be implemented within tfjs, but I am developing it because it is a necessary function for me.

**Comment by bileschi** [comment]
I see this as a data-science or post-processing analysis, both of which are not well supported in JS in general at this point.  Not sure if this makes more sense in core or in a separate repo for now?  @nsthorat thoughts?

**Comment by caisq** [comment]
TensorFlow (Python) has tf.confusion_matrix: https://www.tensorflow.org/api_docs/python/tf/confusion_matrix

**Comment by tafsiri** [comment]
We'll have a util function that computes a confusion matrix as part of the upcoming vis library (coming soon, but that is what @nsthorat is referring to above—we also have support for rendering the confusion matrix). 

So I'd probably hold off on making this PR for now as I already have code for this. Once that comes in for review we can see if we want to move it in core.

**Comment by rthadur** [comment]
@happyhj  here is the link to pull request where confusion matrix is added to tfjs https://github.com/tensorflow/tfjs/issues/771 , so closing this issue.
