### ISSUE TITLE
TypeError: Unknown op 'Cumsum'

### ISSUE THREAD

**Issue by JasonCham-830** [tensorflow/tfjs#6300]
Uncaught (in promise) TypeError: Unknown op 'Cumsum'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()

Please help to add CumSum (Cummulative Sum) to tfjs.

**Comment by rthadur** [comment]
There is already feature request opened here https://github.com/tensorflow/tfjs/issues/6210 which will look lot like tensorflow `cumsum` . Please check above issue for updates. I will be closing this duplicate request. Thank you.
