### ISSUE TITLE
regression: `tfjs-backend-cpu` has an incorrect hard dependency on `tfjs-node`

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6315]
`@tensorflow/tfjs-backend-cpu` has an incorrect hard dependency on `@tensorflow/tfjs-node`  
this makes it impossible to use **tfjs** in pure online environments  

for example, see reproduction at <https://stackblitz.com/edit/typescript-blff19>  
just uncomment line that imports `tfjs-backend-cpu` and project will refuse to build  

(and since `@tensorflow/tfjs-backend-cpu` is included in bundle `@tensorflow/tfjs`, it also cannot be used)

none of the other modules (`core`, `data`, `layers`, `webgl`, `wasm`, `converter`) seem affected.

this is a newly introduced issue that was not present in **tfjs 3.13.0**, so it was introduced recently  
**tfjs 3.14.0** and **3.15.0** both seem affected.

quick scan does not show any obvious culprits other than trivial change via <https://github.com/tensorflow/tfjs/pull/6031>

**Comment by mattsoulanille** [comment]
Thanks for the bug report @vladmandic. To get a better idea of what's causing this, [I tried reproducing it locally](https://github.com/mattsoulanille/tfjs_6315_cpu_dep_on_node), once with esbuild and another time with rollup, however, the bug doesn't appear with either. 

This might be an issue with stackblitz, but that's surprising if the bug only appears after 3.13 (although I haven't been able to get it working with any version). Do you know what they use to build and serve projects?

**Comment by vladmandic** [comment]
@mattsoulanille i just spend an hour looking at this and i'm not much smarter because of it :(

seems that 3.13 vs 3.15 may be a red herring as that timeline seems to match some changes on stackblitz side (apparently new module parser when live in late january, but only way i can see that is browsing through old issues)  

regarding what they use - havent seen official docs - but looking at their generated code, it seems they're using `webpack`

anyhow, i've just created issue on stackblitz for them to take a look at it as well: <https://github.com/stackblitz/core/issues/1832>

**Comment by vladmandic** [comment]
root cause is a bug in SystemJS that entire module for require calls and doesn't ignore strings.
the PR is being submitted, but this is not uncommon issue - I suggest to remove code statements from comments.
specifically, in `@tensorflow/tfjs-backend-cpu`, there is:

```js
backend_util.warn('\n============================\n' +
    'Hi there 👋. Looks like you are running TensorFlow.js in ' +
    'Node.js. To speed things up dramatically, install our node ' +
    'backend, which binds to TensorFlow C++, by running ' +
    'npm i @tensorflow/tfjs-node, ' +
    'or npm i @tensorflow/tfjs-node-gpu if you have CUDA. ' +
    'Then call require(\'@tensorflow/tfjs-node\'); (-gpu ' +
    'suffix for CUDA) at the start of your program. ' +
    'Visit https://github.com/tensorflow/tfjs-node for more details.' +
    '\n============================');
```

anyhow, imo such comments belong in docs, not in warning messages while warning messages should be much shorter  
(not to mention usage of emojis which is just weird in warning messages)

**Comment by vladmandic** [comment]
confirm root issue as resolved. suggestion remains for `tfjs` to clean-up overly verbose console messages.

**Comment by rthadur** [comment]
submitted PR to fix the warn message. Thank you
