### ISSUE TITLE
Blazeface tfjs model does not return any results on a group image but works on cropped images!

### ISSUE THREAD

**Issue by anjomshoaa** [tensorflow/tfjs#6316]
I'm trying to use Blazeface tfjs model to detect faces in a static image including several persons but the estimateFaces method returns no results. I then cropped the same image and left 1-2 person in the image and surprisingly the results was OK. Are there any parameter settings to make it work for group images? 

As test image, I used this image from Wikipedia:  https://en.wikipedia.org/wiki/Situation_Room_(photograph)

**Comment by rthadur** [comment]
@anjomshoaa can you please share image size , usually front camera works good for image sizes 128px.

**Comment by anjomshoaa** [comment]
@rthadur I don't use the camera. I used this image:  https://en.wikipedia.org/wiki/Situation_Room_(photograph)

**Comment by anjomshoaa** [comment]
@rthadur 

I used the original file with pixel size 4096 × 2731. You may download it from here:

https://upload.wikimedia.org/wikipedia/commons/a/ac/Obama_and_Biden_await_updates_on_bin_Laden.jpg
