### ISSUE TITLE
Can I load model by extracting all the model.json and the sharded weights file from RNFS?

### ISSUE THREAD

**Issue by ShivaAryal** [tensorflow/tfjs#6318]
I have my model json file and sharded weights saved in local react-native-file-system(RNFS). Is there any means that this library provides me to load model by fetching the required parameteres from RNFS. 
P.S. I only found documentation to load model only if the parameters are bundle within the app itself.

**Comment by rthadur** [comment]
Hi , You can try to use [asyncStorageIO](https://js.tensorflow.org/api_react_native/0.2.1/#asyncStorageIO) to load from local RNFS
