### ISSUE TITLE
Error during build CRA app

### ISSUE THREAD

**Issue by havenchyk** [tensorflow/tfjs#6319]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

I'm not sure if it's a "build" type of issue, but it happens when I try to build the app 😄 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.13.0
- CUDA/cuDNN version:

**Describe the problem**

I use create-react-app based application and have inside. It used to work, but now I migrate to monorepo and node_modules are hoisted to the root, nothing else has changed.

During the default build command, I started getting the error:

> node_modules/@tensorflow/tfjs-converter/dist/operations/executors/control_executor.js: Couldn't find a Program

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
    "@tensorflow-models/body-pix": "2.2.0",
    "@tensorflow/tfjs": "3.13.0",
```

and I use it like

```
import "@tensorflow/tfjs";
import * as bodyPix from "@tensorflow-models/body-pix";
```

**Any other info / logs**

`node_modules/@tensorflow/tfjs-converter/dist/operations/executors/control_executor.js: Couldn't find a Program`

**Comment by havenchyk** [comment]
The reason was in different versions of babel/core used, nothing to do on tfjs side

**Comment by havenchyk** [comment]
Anyhow, the problem exists on babel later than 7.16.12, so 7.17.0 already breaks the build

**Comment by rthadur** [comment]
please use new pose-detection model here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection as we no longer support body pix. Thank you

**Comment by havenchyk** [comment]
I see, thanks
