### ISSUE TITLE
"Failed to load resource" when using Hand Pose Detection

### ISSUE THREAD

**Issue by umutreldem** [tensorflow/tfjs#6326]
**System information**
- OS Platform and Distribution OSX 11.5.2
- TensorFlow.js installed from script link
- Chrome Version 100.0.4896.75

**Describe the problem**
I am trying to use the Hand Pose Detection model in p5.js through the script tag and the code below as it is described on the [Tensorflow blog](https://blog.tensorflow.org/2021/11/3D-handpose.html). I encounter two problems:

- Creating an instance of the detector in sketch.js gives me the following error: 
`Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules`

- If I force the await command by using IIFE, I get the following errors: 
`hands:74          GET http://127.0.0.1:8887/hand_landmark_full.tflite 404 (Not Found)`
`hands:61          GET http://hands_solution_packed_assets_loader.js/ net::ERR_NAME_NOT_RESOLVED`
`hands:61          GET http://hands_solution_simd_wasm_bin.js/ net::ERR_NAME_NOT_RESOLVED`
`hands:74          GET http://127.0.0.1:8887/hands.binarypb 404 (Not Found)`
```
sketch.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'estimateHands')
    at setup (sketch.js:24:24)
    at _setup (p5.min.js:3:423972)
    at _runIfPreloadsAreDone (p5.min.js:3:423132)
    at _decrementPreload (p5.min.js:3:423304)
    at _.<anonymous> (p5.sound.min.js:2:98292)

```
```
hands:66 Uncaught (in promise) TypeError: n is not a function
    at pa.h (hands:66:412)
    at G (hands:20:296)
    at sa.next (hands:21:91)
    at hands:21:482
    at new Promise (<anonymous>)
    at ta (hands:21:375)
    at I (hands:22:22)
    at hands:66:289
    at async Promise.all (:8887/index 0)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Here is the HTML code:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Sketch</title>

    <link rel="stylesheet" type="text/css" href="style.css">

    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/hand-pose-detection"></script>
    <!-- Optional: Include below scripts if you want to use MediaPipe runtime. -->
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands"></script> 
    <script src="libraries/p5.min.js"></script>
    <script src="libraries/p5.sound.min.js"></script>

  </head>

  <body>
    <script src="sketch.js"></script>
  </body>
</html>
```

and the JS code:

```

let video;
let detector;

(async function main () {
    const handModel = handPoseDetection.SupportedModels.MediaPipeHands;
    const detectorConfig = {
    runtime: 'mediapipe',
    modelType: 'full'
    };
    detector = await handPoseDetection.createDetector(handModel, detectorConfig);
})();

function setup() {
  createCanvas(640, 480);
  video = createCapture(VIDEO);
  video.hide();

}

function draw() {
  background(220);
  image(video, 0, 0);
}



```

**Comment by MiroslavPetrik** [comment]
Hey @umutreldem,

The error 404 indicates that the app is trying to fetch the model from your local server.
Either (1) point the app to CDN, or (2) serve the files locally.

Solution 1: (didn't test)
```
const detectorConfig = {
  runtime: 'mediapipe',
  modelType: 'full',
  solutionPath: "https://cdn.jsdelivr.net/npm/@mediapipe/hands/"
};
```

Solution 2:

1. You'll need to [download the model](https://www.jsdelivr.com/package/npm/@mediapipe/hands) (pick version first, then click the download icon.
2. Add to your server public folder.
3. set the relatively e.g.  `solutionPath: "./public/model"`

The solution 2 works for me & your app is standalone.

**Comment by rthadur** [comment]
@MiroslavPetrik did you try using p5.js ?  Looking at the above error , error seems to be in p5.js. @umutreldem can you provide a repro code in [codepen](https://codepen.io/pen/) ?
