### ISSUE TITLE
Possibly invalid type for arraySync (or dataSync...)

### ISSUE THREAD

**Issue by twobitunicorn** [tensorflow/tfjs#6332]
Hi all.  I have run into an issue where arraySync will return a scalar and not an array.  The type for `arraySync()` includes `number` as part of its union types and will not type check using `map` because of the possible scalar type.  

However, even if this is assumed to be okay.  There seems to be a sync problem between `arraySync()` and `dataSync()`.

Given the code below, it appears that `arraySync()` and `dataSync()` treat a scalar differently.
> tf.scalar(1).arraySync()
1
> tf.scalar(1).dataSync()
Float32Array(1) [ 1 ]
> tf.zeros([1]).arraySync()
[ 0 ]
> tf.zeros([1]).dataSync()
Float32Array(1) [ 0 ]

Should these be the same results?  Should a scalar be returned from the `arraySync()` method?  

https://github.com/tensorflow/tfjs/blob/38f8462fe642011ff1b7bcbb52e018f3451be58b/tfjs-core/src/types.ts#L31

**Comment by rthadur** [comment]
Hi , I checked with the team and this is working as expected .
