### ISSUE TITLE
@tensorflow/tfjs-react-native version that is compatible with the new expo-modules

### ISSUE THREAD

**Issue by unit-002** [tensorflow/tfjs#6345]
Is it possible to have an updated version of React native tensorflow that is compatible with the new expo module version? @tensorflow/tfjs-react-native. Currently it is only compatible with React native unimodules and expo-gl and expo-gl-cpp which is already outdated.

**System information**
"@tensorflow/tfjs": "^3.9.0",
"@tensorflow/tfjs-react-native": "^0.7.0",
"react-native": "0.63.4",

**Describe the feature and the current behavior/state.**

With installed expo module, @tensorflow/tfjs-react-native expo-gl is still requiring 
`@unimodules/core, @unimodules/react-native-adapter and unimodules-app-loader `  and installing this packages will give conflict to the  `org.unimodules.adapters.react.apploader.RNHeadlessAppLoader` and `expo.modules.adapters.react.apploader.RNHeadlessAppLoader` that are both present on both packages.

**Who will benefit with this feature?**
Those who are using the new expo sdk.

**Any Other info.**
I have open an issue at expo github with deltailed error messages in case you want to check here is the link: 
https://github.com/expo/expo/issues/17094

**Comment by FelipeSchiavini** [comment]
I managed to install.
Here is my repository:
https://github.com/FelipeSchiavini/tensorflow_on_react_native

`
yarn add @react-native-async-storage/async-storage
npx install-expo-modules
 add package.json -> “expo”: “expo”
yarn expo install expo-gl
yarn expo install expo-gl-cpp
yarn expo install expo-camera
yarn expo doctor --fix-dependencies
made expo-camera setup :  https://github.com/expo/expo/tree/main/packages/expo-camera#configure-for-android
`

**Comment by FelipeSchiavini** [comment]
I managed to install.
Here is my repository:
https://github.com/FelipeSchiavini/tensorflow_on_react_native
--------------------------------------
yarn add @react-native-async-storage/async-storage 
npx install-expo-modules 
add package.json -> “expo”: “expo” 
yarn expo install expo-gl 
yarn expo install expo-gl-cpp 
yarn expo install expo-camera 
yarn expo doctor --fix-dependencies 
made expo-camera setup : https://github.com/expo/expo/tree/main/packages/expo-camera#configure-for-android

**Comment by FelipeSchiavini** [comment]
I managed to install.
Here is my repository:
https://github.com/FelipeSchiavini/tensorflow_on_react_native


yarn add @react-native-async-storage/async-storage
npx install-expo-modules
add package.json -> “expo”: “expo”
yarn expo install expo-gl
yarn expo install expo-gl-cpp
yarn expo install expo-camera
yarn expo doctor --fix-dependencies
made expo-camera setup : https://github.com/expo/expo/tree/main/packages/expo-camera#configure-for-android

**Comment by unit-002** [comment]
> I managed to install. Here is my repository: https://github.com/FelipeSchiavini/tensorflow_on_react_native
> 
> yarn add @react-native-async-storage/async-storage npx install-expo-modules add package.json -> “expo”: “expo” yarn expo install expo-gl yarn expo install expo-gl-cpp yarn expo install expo-camera yarn expo doctor --fix-dependencies made expo-camera setup : https://github.com/expo/expo/tree/main/packages/expo-camera#configure-for-android

Thanks, I got it working now with expo module.

**Comment by rthadur** [comment]
@unit-002 I see this got resolved , do we still need this feature request ?

**Comment by unit-002** [comment]
> @unit-002 I see this got resolved , do we still need this feature request ?

if it gets updated that would be nice because if I am using the latest version of expo packages I get a lot of deprecated warnings during builds so currently I am using packages that are from 6 or 7 months old same with the @tensorflow/tfjs-react-native version.

**Comment by unit-002** [comment]
update: some expo packages are also requiring JDK 11 and @tensorflow/tfjs-react-native expo-gl version requires JDK 8. Currently I'm back to using the deprecated react-native unimodule due to this.

**Comment by bekatd** [comment]
Will this get resolved ever? :|
