### ISSUE TITLE
[RN] - Measurements with Keypoints3d in BlazePose

### ISSUE THREAD

**Issue by eledahl** [tensorflow/tfjs#6347]

**Comment by eledahl** [comment]
Hi @jinjingforever @rthadur,

Can you confirm if this is a bug or my error in understanding how the world keypoints are represented?

--

Also, is there anything going on with the api? Since Friday, it does not open the camera. I've double-checked my dependencies and they match the README in the example [https://github.com/tensorflow/tfjs-examples/blob/master/react-native/README.md](Here). I also downloaded the pose example, yarn installed and it crashed when trying to open.

**Comment by eledahl** [comment]
The issue I mentioned above of the app crashing might be due to the Expo Go app. That is where I am testing it and there was an update that went out 5 days ago which is when the problem started. I am diving into what might have affected it but please let me know if you find anything that can fix it through Expo Go

**Comment by eledahl** [comment]
Is it advised to have the model on the backend/cloud for better accuracy or do you foresee this becoming more accurate on mobile in the near future?

I see Intel's 3DAT uses their cloud to do pose estimation and calculations. Curious if that is the better approach for BlazePose. Send videos from mobile device to backend for the computing. Would prefer to have it all on mobile device though.

**Comment by eledahl** [comment]
Hi @jinjingforever @rthadur,

Does tfjs-react-native have any support for [TensorFlow Lite GPU delegates](https://www.tensorflow.org/lite/performance/gpu)? Do you think this may solve the issue of accuracy?

**Comment by rthadur** [comment]
Please check face-detection https://github.com/tensorflow/tfjs-models/tree/master/face-detection model as blaze face depreciated. Thank you.
