### ISSUE TITLE
Mouse movement trajectory prediction.

### ISSUE THREAD

**Issue by MariasStory** [tensorflow/tfjs#635]
Hi, did someone try to predict mouse movement trajectory?

There was some rudimentary effort: https://github.com/BrainJS/brain.js/issues/61

Some better ideas?

It would be nice to see an indication for predicted movement of mouse based on trained/training network.

**Comment by tafsiri** [comment]
@MariasStory you might want to try the mailing list (https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) to see if anybody else is working on something similar. Else I don't think we have any particular plans to work on it.
