### ISSUE TITLE
[tfjs-react-native] Tensor data read back is slow

### ISSUE THREAD

**Issue by Looooong** [tensorflow/tfjs#6352]
I'm using MoveNet model on an Android device. The execution time is ranging from 200ms to 250ms, which is twice as much compared to running the MoveNet demo in the browser on the same device. After investigating the code, I found out that the Tensor read back time takes approximately half of the total execution time (90ms-140ms).

```ts
    // Only use asynchronous downloads when we really have to (WebGPU) because
    // that will poll for download completion using setTimeOut which introduces
    // extra latency.
    let inferenceResult;
    if (tf.getBackend() !== 'webgpu') {
      inferenceResult = outputTensor.dataSync();
    } else {
      inferenceResult = await outputTensor.data();
    }
```

From the code, I understand that tensor data have to be retrieved synchronously, which explains the slow read back. Is there anyway I can do to make it faster, or at least make it asynchronous and have the data ready after the next animation frame?

**Comment by Randhirjha17** [comment]
i faced the exact same issue, this is how I was able to reduce it to 100-150ms.

import { bundleResourceIO} from "@tensorflow/tfjs-react-native";
 const modelJson = require("./thunder/model.json");
  const modelWeights = require("./thunder/group1-shard1of3.bin");
  const modelWeights1 = require("./thunder/group1-shard2of3.bin");
  const modelWeights2 = require("./thunder/group1-shard3of3.bin");

        const detector = await tf.loadGraphModel(
            bundleResourceIO(modelJson, [modelWeights, modelWeights1,modelWeights2]),
        );

 poses = await myModel.predict(images);

**Comment by rthadur** [comment]
@Looooong are you facing the slowness when you execute first or it is the same in consecutive runs ? if not can you try loading the model locally ? Thank you

**Comment by Looooong** [comment]
> @Looooong are you facing the slowness when you execute first or it is the same in consecutive runs ? if not can you try loading the model locally ? Thank you

It's slow in consecutive runs.

**Comment by rthadur** [comment]
I believe the issue is with `datasync`  and this has been discussed here at length https://github.com/tensorflow/tfjs/issues/5468 , can you please check.

**Comment by Looooong** [comment]
What I want is to retrieve the result **asynchronously** (.i.e using `data()` method). `tfjs-react-native` is using a customized version of `webgl` backend which doesn't seem to support async read back.

**Comment by rthadur** [comment]
yes that's correct.
