### ISSUE TITLE
Glamor is Way Outdated. It May Be Time to Fork It For an Update or Look For Something Else

### ISSUE THREAD

**Issue by JeffMII** [tensorflow/tfjs#6359]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.16.0
- CUDA/cuDNN version: v11.6/v8.4

**Describe the problem**
`glamor` is causing high severity vulnerabilities because of how outdated it is. It still has `core-js@1.2.7` which is I believe is 6 years old. ES6 had just released with modules around that time. I think we're at ES13 now, and, from what I've been reading, ES6-style modules are not compatible with today's modules.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
npm install @tensorflow/tfjs-vis

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`npm install @tensorflow/tfjs-node-gpu`
`npm install @tensorflow/tfjs-vis`

```
npm WARN deprecated @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 130 packages, and audited 374 packages in 14s

21 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

also

`npx qode index.js`
```
(node:19636) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `qode --trace-warnings ...` to show where the warning was created)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\@tensorflow\tfjs-core\dist\public\chained_ops\register_all_chained_ops.js:17
import './abs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXX\node_modules\@tensorflow\tfjs-vis\dist\index.js:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
```

almost forgot, here is my `package.json`

```
{
  "name": "questgen-js-phase1-cnn-rnn",
  "version": "1.0.0",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "qode": "npx qode index.js",
    "node": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@nodegui/nodegui": "^0.50.0",
    "@tensorflow/tfjs": "^3.16.0",
    "@tensorflow/tfjs-node-gpu": "^3.16.0",
    "@tensorflow/tfjs-vis": "^1.5.1",
    "core-js": "^3.22.3",
    "node-fetch": "^3.2.4",
    "sass": "^1.51.0"
  }
}
```

I didn't have any deprecation or vulnerability warnings before I installed `tfjs-vis`, and this error never occurred either. And if you look at the error, you can tell the problem comes from the old ES6 `core-js`. For whatever reason, it thinks the modules are common js files. I am going to try to find a workaround for now by forking both projects and updating the `glamor` dependency.

**Comment by JeffMII** [comment]
I added `npm install @tensorflow/tfjs-node-gpu` because I think if I were using `tfjs-vis` by itself, it would work. i'm going to test that out as soon as I can today. If it does, I can just separate them to two projects and have them communicate with `express-js`. I'm still working on updating `glamor`. I'm just about finished I think, but I've never used `babel` in a project before so I'm having to learn some things. So, in the meantime, if `tfjs-vis` can run on it's own, setting up `express-js` will work fine.

**Comment by JeffMII** [comment]
So it looks like `tfjs-vis` does actually run by itself, with the `tfjs-core` it requires. However, the high severity vulnerabilities are still shown by `npm` because of the outdated `glamor` dependency.

**Comment by gaikwadrahul8** [comment]
Hi, @JeffMII 

Apologize for the delayed response and I was able to replicate the same issue with latest version of `@tensorflow/tfjs-vis@1.5.1` and it's throwing the same warning message as below and as far I know we can ignore this warning message unless and until our code is executing as expected and warning is not related with security/vulnerabilities. `glamor` package still using the 6 years ago package and I don't see any latest package published for `glamor` package 

If have I missed something here please let me know ?
```
npm WARN deprecated @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by JeffMII** [comment]
The problem isn't really the warnings, though they are an issue as well. The problem is you can't use `tfjs-node-gpu`
and `tfjs-vis` together. separately, they work, but when you `npm install` them in the same project, `tfjs-vis` causes the error I previously mentioned.
