### ISSUE TITLE
Add download progress bar for tf-hub converting

### ISSUE THREAD

**Issue by andresusanopinto** [tensorflow/tfjs#636]
E.g.:
 tensorflowjs_converter \
    --input_format=tf_hub \
    'https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/classification/1' \
    mobilenet/web_model

Does not outputs anything for sometime while downloading the module.

**Comment by andresusanopinto** [comment]
The next release version of tfhub should show a progress bar when using TFHUB_DOWNLOAD_PROGRESS=1 environment variable.

See https://github.com/tensorflow/hub/commit/3c36fef3ee5cc6709d6d76818789d6ec62d682f4#diff-7d939c5d51539f4d8c9eda5a85d96c09 for commit.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
