### ISSUE TITLE
Bug using tfjs-models/face-landmarks-detection

### ISSUE THREAD

**Issue by plantematthieu** [tensorflow/tfjs#6367]
Hello, 

I'm developping a program to sort images in a folder (if there is a face or not and if there is, get landmarks) and I'm facing a weird bug.
The model is missing some obvious faces in the loop (it doesn't return landmarks) but when I apply the model only on the obvious face, I got landmarks. So when a image is in the loop, I sometimes don't get the same results than when I apply the model on the image outside the loop.

One specificity of my program is that images can be rotated, so I need to rotate them till I detect a face.

Here is a simplified version of my code: 
[https://codepen.io/plantematt/pen/poaJRzQ](https://codepen.io/plantematt/pen/poaJRzQ)

Thanks for your help!

**Comment by rthadur** [comment]
Did you try to use use [dispose](https://www.tensorflow.org/js/guide/tensors_operations#memory) after each iteration ?

**Comment by plantematthieu** [comment]
I found a solution: using `console.log(tf.memory().numTensors)` I saw that the number of used tensors was increasing through iterations. 

So I declared the model and make `.estimateFaces` inside a `tf.engine().startScope()
tf.engine().endScope()`
