### ISSUE TITLE
How to convert custom Yolov5n Model to Wasm Format

### ISSUE THREAD

**Issue by Mas-Y** [tensorflow/tfjs#6382]
Hi Team,

Can you please let me know how can i convert custom **yolov5n** (https://github.com/ultralytics/yolov5) model to **wasm** format to use in mobile browser.

**Comment by rthadur** [comment]
Thank you , did you get chance to check this site as well https://www.aionlinecourse.com/blog/how-to-convert-yolov5-model-to-tensorflowjs ?

**Comment by Mas-Y** [comment]
> Thank you , did you get chance to check this site as well https://www.aionlinecourse.com/blog/how-to-convert-yolov5-model-to-tensorflowjs ?

Thank You @rthadur for the response. I am not looking for converting into tfjs (.bin and .json) . I am trying to convert into wasm (.data, .wasm, .js) format to make the model run faster in browser

**Comment by rthadur** [comment]
@Mas-Y got it. @mattsoulanille could you please assist with this request. Found a related issue here https://github.com/tensorflow/tfjs/issues/5684 but not sure they are saving the model wasm format.

**Comment by vladmandic** [comment]
@Mas-Y thats not how it works. tfjs uses graph model format (or layers, but thats a different story or even experimental tflite format) model, then you choose how its executed - in your case, you want to use wasm, so it would be using `@tensorflow/tfjs-backend-wasm`. you don't *convert* model to wasm as such.

**Comment by Mas-Y** [comment]
@vladmandic I am more confused now. My understanding is like how we convert our .pt models to .bin files for usage in tfjs in browser, we can convert into web assembly format for faster access in browser.

This is the reference link i found for my basic understanding https://github.com/nihui/ncnn-webassembly-yolov5

Please clarify

**Comment by vladmandic** [comment]
@Mas-Y that is how NCNN achieves things, every framework is different. How TensorFlow in general works is that models are abstract and backends define functions used in models.  

So if you convert model to TF Graph format (.bin + .json), its just a model definition and binary weights - there are is no actual implementation of each op used inside model included in the model.  

But then module such as `@tensorflow/tfjs-backend-wasm` provides implementation for ops used in model to be executed using `WASM`. or `@tensorflow/tfjs-backend-webgl` would do the same, but would execute model ops in `WebGL` on GPU, etc.

**Comment by Mas-Y** [comment]
@vladmandic Thank you for the explanation. Currently yolov5n model link which i mentioned doesn't seem have wasm support. So i guess as per your explanation i would not be able to use it as it is not supported.
Anyone can confirm my understanding.

**Comment by vladmandic** [comment]
@Mas-Y if model can be converted to TF Graph Model format (.bin + .json) (which it can and its documented), then its up to backend engine (`tfjs-backend-wasm`) to support or not support each individual kernel op used inside the model - how do you know "its not supported"?
