### ISSUE TITLE
Unsupported Ops: Prod

### ISSUE THREAD

**Issue by napa-sji** [tensorflow/tfjs#640]
Is there plan to support the Prod op in the near future? I'm trying to use tensorflowjs_converter to convert a model and got an error about "Prod".

**Comment by yhwang** [comment]
@caisq  @pyu10055 our team would like to volunteer to implement it and may need your help for suggestion/comment later. Are you okay that we work on this?

**Comment by caisq** [comment]
@yhwang I don't have objections to this. @pyu10055 your toughts?

**Comment by pyu10055** [comment]
@yhwang Thank you for volunteering to work on this.

**Comment by manrajgrover** [comment]
This was recently added in [tfjs-core](https://github.com/tensorflow/tfjs-core/pull/1279) and can now be supported in converter.

**Comment by pyu10055** [comment]
@manrajgrover thanks for pointing out the op has already been implemented by me. :)
