### ISSUE TITLE
Support for tensor4D in MoveNet

### ISSUE THREAD

**Issue by Fluxionsdx** [tensorflow/tfjs#6408]
I am working on an application that uses MoveNet and 3 cameras. I would like to pass all three images to MoveNet at once in a batch, but MoveNet only supports 3D tensors consisting of a single image, not a batched 4D tensor.

**Comment by rthadur** [comment]
cc @lina128 @ahmedsabie

**Comment by rthadur** [comment]
Spoke to the team and they were not inclined towards support for tensor4D , instead you can pass 3D tensors 3 times in order to achieve the same. Thank you.

**Comment by Fluxionsdx** [comment]
You can't use 3 different cameras with the same instance of movenet like that because of the temporal filtering and "intelligent cropping based on detections from the previous frame". I am making it work with 3 separate instances though and I can understand not wanting to work on this. Thanks for the consideration.

**Comment by lina128** [comment]
Hi @Fluxionsdx , using three instances sounds the right approach to do. In terms of computation, it should be comparable to batch. The pre/post processings are mostly CPU, it can't parallel anyway. The model itself runs on GPU, so you just get 3 times more textures to run on GPU and they are parallel.
