### ISSUE TITLE
evaluate, predict,fit,these methods crashed if specified a nonsense batchSize (zero or negative integer) .

### ISSUE THREAD

**Issue by zhongheng001** [tensorflow/tfjs#641]
TensorFlow.js API Version 0.12.5  
 Browser version (  Google Chrome  67.0.3396.87).

evaluate, predict,fit,these methods crashed if specified a nonsense batchSize (zero or negative integer) .

1.Test this situation,for example:
navigate  API Reference
https://js.tensorflow.org/api/0.12.5/#class:Model 

2. Edit predict method‘s test code and run it,such as:

const model = tf.sequential({
   layers: [tf.layers.dense({units: 1, inputShape: [10]})]
});
// specified a nonsense batchSize ,zero (or negative integer)
// run this code ,the brower crashed!
model.predict(tf.ones([8, 10]), {batchSize: 0}).print();

3,Other old API Version (e.g.  0.10.0) crash similarly.
  commonly,nobody inputs a nonsense value,but, it may be  a flaw.
4. more detail , https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/k8JUEXM_WSk

**Comment by caisq** [comment]
Thanks for filing the issue. I opened a PR for fixing this issue: https://github.com/tensorflow/tfjs/issues/641
