### ISSUE TITLE
`flipHorizontal` option of the `segmentPerson` method in bodyPix doesn't work

### ISSUE THREAD

**Issue by obadakhalili** [tensorflow/tfjs#6412]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WSL running Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm (yarn)
- TensorFlow.js version (use command below): 3.15.0
- Browser version: Chrome version 101.0.4951.67 (official build) (64-bit)
- Tensorflow.js Converter Version: 3.15.0

**Describe the current behavior**
The `segmentPerson` method of the bodyPix network doesn't consider the option `flipHorizontal`.

**Describe the expected behavior**
The image should be flipped horizontally before segmentation based on the boolean value of the `flipHorizontal` option.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
It's enough to try out the `segmentPerson` method with different values to see that it is not being considered.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
BodyPix version: 2.2.0

**Comment by obadakhalili** [comment]
> please use new pose-detection model here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection as we no longer support body pix. Thank you

It's weird why this is not mentioned anywhere. I already invested some time in bodyPix ...
Also, the main thing I need is the segmentation functionality. Does pose-detection support that?

**Comment by obadakhalili** [comment]
> > please use new pose-detection model here https://github.com/tensorflow/tfjs-models/tree/master/pose-detection as we no longer support body pix. Thank you
> 
> It's weird why this is not mentioned anywhere. I already invested some time in bodyPix ... Also, the main thing I need is the segmentation functionality. Does pose-detection support that?

It seems like the answer to that question is yes through [BlazePose-MediaPipe](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/blazepose_mediapipe). Thank you.

**Comment by rthadur** [comment]
We are in the process of updating the models to reference correct one. Apologies for the inconvenience . Glad it worked for you. Closing this request.
