### ISSUE TITLE
A few tfjs-models links are broken

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#6419]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
N/A

**Describe the current behavior**
Source links for the following models return 404: BodyPix, DeepLab v3, Face Landmark Detection.

Additionally, the Face Landmark Detection link shows "Cannot find model in the query string."
**Describe the expected behavior**
Links work correctly.

**Standalone code to reproduce the issue**
Click the links on https://github.com/tensorflow/tfjs-models.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@mattsoulanille can i work on it ?

**Comment by mattsoulanille** [comment]
Yes. Thank you!

**Comment by rthadur** [comment]
Thank you @mattsoulanille I have included all the changes here https://github.com/tensorflow/tfjs-models/pull/1020 , please help review the PR
