### ISSUE TITLE
Mac OS M1 support

### ISSUE THREAD

**Issue by avovetisa** [tensorflow/tfjs#6436]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):
"@tensorflow/tfjs-node": "^3.15.0",

- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
When you start using tfjs-node, with MACOS with the M1 chipset, you got this error :
illegal hardware instruction

**Will this change the current api? How?**
It would be great that the tfjs-node have a compiled version for the M1 chipset.

**Who will benefit with this feature?**
For all people that are using Mac with M1.

**Any Other info.**

**Comment by rthadur** [comment]
Thank you for the request , there is already issue for M1 chip support here https://github.com/tensorflow/tfjs/issues/6381 , please comment there, thank you
