### ISSUE TITLE
Cannot load tfjs model converted from .h5 to .json: [Error: Based on the provided shape, [7,7,1,64], the tensor should have 3136 values but has 44]

### ISSUE THREAD

**Issue by SMUEric1127** [tensorflow/tfjs#6441]
**System information**
- OS Platform and Distribution: Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Iphone 11
- tensorflow/tfjs version: 3.18.0
- tensorflow/tfjs-react-native: 0.8.0

**Describe the problem**
I'm converting a resnet model from *.h5 to *.json format using TensorFlow.js Converter v3.18.0 tool. However, when I try to load the model using ``` const model = await tf.loadGraphModel(MODEL_URL).catch((err) => console.log(err)); ```

It returns the error: [Error: Based on the provided shape, [7,7,1,64], the tensor should have 3136 values but has 44]

**Things I have tried**
I tried tf.loadGraphModel examples and it works fine, it just not working for my model

**Comment by SMUEric1127** [comment]
Here is my model.json url [https://api.jsonbin.io/b/628d3787402a5b38020be20a](url)

Thanks

**Comment by rthadur** [comment]
Above link is not working , could you please check and share a codepen example , so that we can reproduce the error.Thank you

**Comment by pyu10055** [comment]
@SMUEric1127 You might want to check the developer tool of the browser, see if the weight files are loaded properly in the network tab. This could be cause by the server side 4xx network responses for the weight files of the model.
