### ISSUE TITLE
Frompixels gets different values for the same input when repeat running

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#6444]
For both webgl and webgpu backend, when running image based model over e2e correctness manually
after a auto run, the test will fail. Example: benchmark=bodypix&backend=webgl, benchmark=
bodypix&backend=webgpu.

For cpu backend, this may fail with benchmark=bodypix&backend=cpu.

The root cause is, getImageData runs on different hardware (CPU, GPU).
See comments here: https://bugs.chromium.org/p/chromium/issues/detail?id=1239467

**Comment by rthadur** [comment]
Related PR #6445 has been merged , closing this issue. thank you
