### ISSUE TITLE
return process.dlopen(module, path.toNamespacedPath(filename));

### ISSUE THREAD

**Issue by saboorajat** [tensorflow/tfjs#6447]
OS: Windows 10
Node: 12.22.9
IDE: VS code

The issue is persistent even after changing the node version. Also to my surprise the @tensorflow/tfjs-node is not mentioned in package.json. Have tried all the mentioned workaround but it seems to be a problem that's not fixed. The same code is working fine on the ubuntu. Any help will be appreciated.   

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\F:\Commversion\api\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\Commversion\api\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rthadur** [comment]
@saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you

**Comment by saboorajat** [comment]
OS: Windows 10 pro 64 bit, Node : 12.22.9, NPM : 6.14.15, @tensorflow/tfjs : 3.6.0 are the specification.

have tried moving the dll file but it was already present in the napi-v8 folder which i replaced with the dll file present in lib that didn't work.

**Comment by rthadur** [comment]
@saboorajat can you please check here for similar issue here https://github.com/tensorflow/tfjs/issues/6413and let us know . Thank you

**Comment by saboorajat** [comment]
tried doing rebuild but no help. Can you provide any specific steps in which i can retry, because i have literally tried all the approaches. Same code is running on linux machine but here it's just a nightmare.

**Comment by saboorajat** [comment]
Any help will be appreciated.

**Comment by saboorajat** [comment]
Haven't got any solution to the above problem kindly help.

**Comment by aghast2crude** [comment]
Could you guys tell me how you guys overcame this issue?

**Comment by saboorajat** [comment]
Tried multiple things and few things might have worked for me. **Note below steps fixed it for windows and CPU configurations as i mentioned above**


**STEPS: Run CMD as administrator** 

**npm install --global --production windows-build-tools --vs2015**

**installed python 3.10.4**

**npm set config python "C:\Users\{YOUR_USER}\AppData\Local\Programs\Python\Python310\python.exe"**

**npm install -g appium**

**npm config set msvs_version 2017 --global**

Encountered this Error ------->
ERROR: I tensorflow/core/platform/cpu_feature_guard.cc:142] 
This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions
in performance-critical operations: AVX2 To enable them in other operations,
rebuild TensorFlow with the appropriate compiler flags. node js

Fixed it Command: set MKLDNN_VERBOSE=1

**Comment by RezaErfani67** [comment]
same error with win 11 node 18 , 20 , 21

**Comment by MrAmericanMike** [comment]
> @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you

In my case I had to copy the file `tensorflow.dll` from:

```
Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
```
into

```
Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
```

on version 4.17.0

Just leaving this as a reference in case it helps anyone.

**Comment by NYX1122** [comment]
> > @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

This worked for me on version 4.17.0 as well, THANK YOU ;-;

**Comment by maickonn** [comment]
> > @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

You have no idea how much you helped me. THANK YOU VERY MUCH!

**Comment by theoneandonlyshadow** [comment]
> > @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

This helped a lot, but, as a beginner, i have no clue why it is displaying this:
```
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

**Comment by vismaygamit** [comment]
> > @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

Thanks! working

**Comment by zhuKeFe** [comment]
> > @saboorajat could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

This is really helpful, it has been bothering me for two days. Thank you very much

**Comment by alvinphoebeartemis** [comment]
> > [@saboorajat](https://github.com/saboorajat) could you please try to copy the tendorflow.dll from `\@tensorflow\tfjs-node\deps\lib\tensorflow.dll to @tensorflow\tfjs-node\lib\napi-v6\` . Also please provide tfjs version and windows machine specifications . Thank you
> 
> In my case I had to copy the file `tensorflow.dll` from:
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v9
> ```
> 
> into
> 
> ```
> Tensor\node_modules\@tensorflow\tfjs-node\lib\napi-v8
> ```
> 
> on version 4.17.0
> 
> Just leaving this as a reference in case it helps anyone.

Works on me. Thanks.

tensorflow v4.22
Node v20.18.2
Python 3.10.11
