### ISSUE TITLE
Landmarks model returns NaN when refineLandmarks is used with tfjs runtime backend

### ISSUE THREAD

**Issue by remixer-dec** [tensorflow/tfjs#6449]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.12.0
- Browser version: Firefox 100 and Chromium 101
- Tensorflow.js Converter Version: Not used

**Describe the current behavior**
<img width="713" alt="изображение" src="https://user-images.githubusercontent.com/6587642/170333397-1ec27748-09b1-4088-a3b7-cf63263cf830.png">

**Describe the expected behavior**

<img width="713" alt="изображение" src="https://user-images.githubusercontent.com/6587642/170334932-55fae050-ebd5-4546-8198-8cda6dc0e0a5.png">

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
1. Go to the official [demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh) from tfjs-models
2. Switch the backend to tfjs-webgl
3. In browser's debugger, in file src.a2b27638.js put a breakpoint on line 97911 (when endEstimateFaceStats() is called)
4. In browser's console check the `faces` variable

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
It works correctly with mediapipe-gpu backend

**Comment by rthadur** [comment]
@remixer-dec thank for reporting , @ahmedsabie could you please help fixing the [demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh) , I see this link https://storage.googleapis.com/src.a2b27638.js.map is not working.

**Comment by ahmedsabie** [comment]
Fix PR is here: https://github.com/tensorflow/tfjs-models/pull/1035
