### ISSUE TITLE
The name tf.CustomCallbackConfig is not descriptive enough

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#645]
In tfjs, tf.CustomCallbackConfig comes from tfjs-layers. But the name doesn't reflect that fact and it's unclear what the config is for (it is for tf.Model.fit). It should be moved to a different name and/or different namespace to be clearer.

**Comment by caisq** [comment]
cc @dsmilkov

**Comment by caisq** [comment]
@bileschi , can you talk to @dsmilkov and @nsthorat about this?

**Comment by bileschi** [comment]
I got this, will talk to nikhil & daniel

**Comment by bileschi** [comment]
Opened discussion over Google internal e-mail

**Comment by dsmilkov** [comment]
With the improved doc generator, we now generate much better info about the possible callback fields, thus closing this issue.
