### ISSUE TITLE
Fix script tags for Posenet blogpost

### ISSUE THREAD

**Issue by rthadur** [tensorflow/tfjs#6459]
In the [blog](https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html) post there are two scripts tags for tfjs-core and tfjs-convereter , we should just only one script tag in order to load tfjs as this is a union package .

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/43972606/170586112-791df489-e175-48da-be65-3d4268d43e73.png">

**Comment by rthadur** [comment]
t

**Comment by jasonmayes** [comment]
Thanks for this - so I believe the reason for showing it in this manner is to be efficient on bundle size only using the modules required. You can however of course use the 1 script tag import if you prefer, but I believe we will keep the example as is for now.
