### ISSUE TITLE
[tfjs-node] Inconsistent behavior for `BatchMatMul` kernel

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6467]
kernel `BatchMatMul` does not have same functionality in **WebGL** and **NodeJS** backends  

This causes newer variation of **FaceMesh-with-Attention** model to fail when executing in **NodeJS** environments  

Official implementation for a model was added via issue <https://github.com/tensorflow/tfjs/issues/6002> and PR <https://github.com/tensorflow/tfjs-models/pull/1002>  
Reference model is <https://tfhub.dev/mediapipe/tfjs-model/face_landmarks_detection/attention_mesh/1>  

Error is:

```text
Message: In[0] and In[1] has different ndims: [1,4,4] vs. [4,4]
    at NodeJSKernelBackend.executeSingleOutput (@tensorflow+tfjs-node@3.18.0/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:214:43)
    at Object.kernelFunc (@tensorflow+tfjs-node@3.18.0/node_modules/@tensorflow/tfjs-node/dist/kernels/BatchMatMul.js:33:24)
    at kernelFunc (@tensorflow+tfjs-core@3.18.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4574:32)
```

Same model executes without issues in browser environments using `WebGL` backend

*Environment: TFJS 3.18.0 on Ubuntu 21.10 (WSL2) with NodeJS 16.15.0*

**Comment by Linchenn** [comment]
@vladmandic Thank you for finding this out! 

However, I cannot reproduce the error you mentioned through the following codes:
```javascript
const modelUrl = 'https://tfhub.dev/mediapipe/tfjs-model/face_landmarks_detection/attention_mesh/1';
const model = await tf.loadGraphModel(modelUrl, {fromTFHub: true});
console.log(model.execute(tf.ones([1, 192,192,3])));
```

Could you provide more details to reproduce this error? You could review my codes [here](https://codedamn.com/playground/v_G4uit2zzB4dciPdwkJy) by running `node index` in the terminal.

**Comment by vladmandic** [comment]
@Linchenn Please try using `@tensorflow/tfjs-node`, not `@tensorflow/tfjs`

**Comment by vladmandic** [comment]
thank you @Linchenn, feel free to close the issue as resolved.
