### ISSUE TITLE
can't execute npm run watch with example project Polynomial Regression 

### ISSUE THREAD

**Issue by Iteravse** [tensorflow/tfjs#6472]
the example link is [Polynomial Regression ](https://github.com/tensorflow/tfjs-examples/tree/master/polynomial-regression-core)
after install success,when i enter command `npm run watch ` with cmd on windows 10,it encounter the error:

 

> D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\@parcel\core\lib\Parcel.js:150
>   #requestTracker
>   ^
> 
> SyntaxError: Invalid or unexpected token
>     at new Script (vm.js:83:7)
>     at NativeCompileCache._moduleCompile (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
>     at Module._compile (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
>     at require (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
>     at Object.<anonymous> (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\@parcel\core\lib\index.js:81:39)
> D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\@parcel\logger\lib\Logger.js:41
>   #logEmitter
>   ^
> 
> SyntaxError: Invalid or unexpected token
>     at new Script (vm.js:83:7)
>     at NativeCompileCache._moduleCompile (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
>     at Module._compile (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at _logger (D:\Exhibition\Awakener\TensorDance\polynomial-regression-core\node_modules\parcel\lib\cli.js:54:16)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tfjs-examples-polynomial-regression-core@0.1.0 watch: `cross-env NODE_ENV=development parcel index.html --no-hmr --open`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tfjs-examples-polynomial-regression-core@0.1.0 watch script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Iteravse\AppData\Roaming\npm-cache\_logs\2022-05-31T03_34_41_210Z-debug.log
> 
> D:\Exhibition\Awakener\TensorDance\polynomial-regression-core>npm run start
> npm ERR! missing script: start
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Iteravse\AppData\Roaming\npm-cache\_logs\2022-05-31T03_35_16_960Z-debug.log

and this's the enviroment of npm and node:

> D:\Exhibition\Awakener\TensorDance\polynomial-regression-core>npm version
> { 'tfjs-examples-polynomial-regression-core': '0.1.0',
>   npm: '6.10.0',
>   ares: '1.15.0',
>   brotli: '1.0.7',
>   cldr: '35.1',
>   http_parser: '2.8.0',
>   icu: '64.2',
>   modules: '64',
>   napi: '4',
>   nghttp2: '1.34.0',
>   node: '10.16.0',
>   openssl: '1.1.1b',
>   tz: '2019a',
>   unicode: '12.1',
>   uv: '1.28.0',
>   v8: '6.8.275.32-node.52',
>   zlib: '1.2.11' }

**Comment by rthadur** [comment]
Sorry for the delay , this is working in Mac book pro , need to verify in Windows machine , will try and let you know.

**Comment by ahmedsabie** [comment]
@Iteravse Can you try the following: https://github.com/tejado/telegram-nearby-map/issues/26
