### ISSUE TITLE
Gradient of pow not yet supported for broadcasted shapes.

### ISSUE THREAD

**Issue by Iteravse** [tensorflow/tfjs#6474]
i just replace the  formula of [this example](https://github.com/tensorflow/tfjs-examples/tree/master/polynomial-regression-core)   like :
![img](https://user-images.githubusercontent.com/34048239/171161649-bdea2e25-f701-4160-997a-92f3afd477ad.png)
![img](https://user-images.githubusercontent.com/34048239/171161826-356835af-1b97-411c-b1ee-a7b8b4e286c8.png)

it encounter the error:
![img](https://user-images.githubusercontent.com/34048239/171162636-1131f43f-80eb-4e70-9d92-67819a2fba80.png)

any idea?
BTW the new formula like this:
![img](https://user-images.githubusercontent.com/34048239/171162135-a32b32e8-fc55-42cb-8f98-a1dad787faa9.png)

**Comment by Iteravse** [comment]
great! error is disappear,but why training result are NAN?
here's the out put 
![img](https://user-images.githubusercontent.com/34048239/171343027-ad1a27b8-8fd8-4822-b542-4b2cc91d593e.png)

**Comment by rthadur** [comment]
@Iteravse can you please provide a codepen example if possible , thank you

**Comment by Iteravse** [comment]
> @Iteravse can you please provide a codepen example if possible , thank you

@rthadur 
here's the example ,thanks for a lot
https://codepen.io/iteravse/pen/eYVKyyR

**Comment by Iteravse** [comment]
![Phenomena](https://user-images.githubusercontent.com/34048239/172524291-b44317ef-988b-4c84-82c7-a0aec4befab3.png)
here's result,any idea?
@ahmedsabie @rthadur

**Comment by Iteravse** [comment]
> @Iteravse The codepen you provided is a bit different from the screenshot, can you give the same code as screenshots and remove the irrelevant code? It will make it easier to understand and run the code, thanks!

the situation not change,please see the code pen result,it still return unmeaning value,here's null,NAN is chrome local test result,but question still exist
![image](https://user-images.githubusercontent.com/34048239/195244556-2b804e40-8d2f-44af-adac-95ebe2cb36f7.png)
