### ISSUE TITLE
face-landmarks-detection README refers to handPoseDetection instead of faceLandmarksDetection

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#6479]
In https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/src/tfjs it says:

Pass in **handPoseDetection**.SupportedModels.MediaPipeFaceMesh from the faceLandmarksDetection.SupportedModels enum list along with a detectorConfig to the createDetector method to load and initialize the model.

**Comment by rthadur** [comment]
Thank you submitted a fix .
