### ISSUE TITLE
WebGPU/WGSL: atomicCompareExchangeWeak now returns structure _atomic_compare_exchange_result<T>

### ISSUE THREAD

**Issue by amaiorano** [tensorflow/tfjs#6480]
Hello,

I'm a developer on the [Google Tint](https://dawn.googlesource.com/tint) team, and I wanted to let you know that we just landed a [breaking change](https://dawn-review.googlesource.com/c/dawn/+/91881) to `atomicCompareExchangeWeak` that will affect you [here](https://github.com/tensorflow/tfjs/blob/b38b5b959df300e1c2995a5dc43c5e66fa1821ef/tfjs-backend-webgpu/src/scatter_optimized_webgpu.ts#L101). Instead of returning a vec2, it now returns a struct, [as per the spec](https://gpuweb.github.io/gpuweb/wgsl/#atomic-rmw). Ideally, we minimize breaking changes like this with deprecation periods, but for builtin return types, this is difficult to do.

Please let me know if this is going to be a major problem for you. If so, perhaps we can work out a compile-time flag to bring back the old code path, if really necessary.

Calling out @qjia7 on this issue as per @kainino0x.

**Comment by qjia7** [comment]
Thanks for the reporting. I think we can release a new npm package with the fixing in #6484. So it's ok for TFJS without the old code path in tint.

**Comment by qjia7** [comment]
cc @mattsoulanille webgpu backend needs a new npm release so that it can work with latest chrome canary, thanks.
