### ISSUE TITLE
Add BatchMatMulV2 support in the converter

### ISSUE THREAD

**Issue by Linchenn** [tensorflow/tfjs#6483]
TensorFlow's `BatchMatMulV2` op performs the same behavior as the `BatchMatMul` op in all tfjs backends. We want to support `BatchMatMulV2` in the converter.

https://github.com/tensorflow/tfjs/pull/6477

**Comment by gaikwadrahul8** [comment]
Hi, @Linchenn 

Apologize for the delayed response and It seems like this PR https://github.com/tensorflow/tfjs/pull/6477 has taken care this issue if I'm not wrong so If this issue has resolved could you please close this issue now ? Thank you!
