### ISSUE TITLE
computeConv2DInfo: output shape incorrect wrt non-square effective filter size?

### ISSUE THREAD

**Issue by larrylindsey** [tensorflow/tfjs#649]
Calling computeConv2DInfo with a numeric pad results in a call to computeOutputShape3D (via [getPadAndOutInfo](https://github.com/tensorflow/tfjs-core/blob/a660a5427209923cf43582048efb058ac0f91718/src/ops/conv_util.ts#L209) that ignores the effective filter width. When using non-square filters or non-square dilation sizes, this results in an unexpected output size.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
