### ISSUE TITLE
Im facing the same issue with "@tensorflow/tfjs-core": "^3.18.0" when using it with reactjs. None of the above response have resolved the issue.

### ISSUE THREAD

**Issue by pistolla** [tensorflow/tfjs#6506]
Im facing the same issue with "@tensorflow/tfjs-core": "^3.18.0" when using it with reactjs. None of the above response have resolved the issue.

_Originally posted by @pistolla in https://github.com/tensorflow/tfjs/issues/4296#issuecomment-1146741148_

**Comment by rthadur** [comment]
These are the working examples https://github.com/tensorflow/tfjs-examples/tree/master/react-native/image-classification for react native , can you try running them ? Thank you

**Comment by pistolla** [comment]
Thanks for the reply. The issue im facing is not exactly related to reactjs framework. I have issue with weakmap used in tfjs and tfjs-core. They are inaccessible, in that, even using browser console i can dump the content of weakmap `_tfengine.state.tensorInfo` but when i try to reference a specific key the response is `undefined`. I'm wondering if this is a case of browser implementation of the weakmap or what is wrong? check the screenshots i shared in the referenced issue. I don't understand. Take a few minutes and check them. Thanks.

**Comment by rthadur** [comment]
is it possible to share reproducible code either codepen or git repo ? Thank you

**Comment by vanessaZh** [comment]
> Thanks for the reply. The issue im facing is not exactly related to reactjs framework. I have issue with weakmap used in tfjs and tfjs-core. They are inaccessible, in that, even using browser console i can dump the content of weakmap `_tfengine.state.tensorInfo` but when i try to reference a specific key the response is `undefined`. I'm wondering if this is a case of browser implementation of the weakmap or what is wrong? check the screenshots i shared in the referenced issue. I don't understand. Take a few minutes and check them. Thanks.

i found vue3 is not incompatible and will cause the same problem. the error seems to be caused by the fact that Vue3 wrapped my model attribute in a [Proxy object](https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes)
