### ISSUE TITLE
Batch size > 131 returns array of zeros

### ISSUE THREAD

**Issue by Shiv-Dhokia** [tensorflow/tfjs#6507]
**System information**
- OS Platform and Distribution: 16GB M1 Pro Macbook Pro running MacOS Monterey v12.3.1
- TensorFlow.js version: 3.16.0 
- tfjs-backend-webgpu version: 0.0.1-alpha.11
- Browser version: Chrome Canary Version 104.0.5095.0

**Describe the current behavior**
When using a dataset and using webgpu with tfjs an issue occurs when the batch size is > 131 the output ends up with a Float32Array of zeros after creating tensors with the shape 132, 4000, 1 and getting an output from the inference using the executeAsync method. 
An example of the output: 
Float32Array(33792000) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …]

```
async startInference(tensors) {
    const sessionOutput = await this.model.executeAsync(tensors);
    return sessionOutput;
  }

  async processOutput(logProbs) {
    let squeezed = await logProbs.squeeze();
    let probs = await squeezed.exp();
    return probs;
  }

  createTensor(slice, shape, type = "float32") {
    if (!slice || typeof shape !== "object")
      throw logger.error("badTensorShape");
    return tf.tensor(slice, shape, type);
  }

 async run() {
    const batchSize = 120;
    const tensorSize = 4000;
    let totalSamples = 0;

    await this.loadModel(
      "./models/dna_r9.4.1_e8_fast@v3.4-tfjs/model.json",
      "3.4",
      false
    );

    const data = [];

    this.msg("running...");

    setTimeout(async () => {
      const startTime = performance.now();
      //Random dataset
      const dataArr = [
        this.generateSignal(tensorSize, batchSize)
      ];
      console.log(dataArr);
      console.log("RUNNING");
      for (const [i, batch] of dataArr.entries()) {
        tf.engine().startScope();

        //inital batch size = 131
        //tensor size = 4000
        const samples = [...batch];
        const currentBatchSize = samples.length / tensorSize;
        console.log("currentBatchSize", currentBatchSize);

        const shape = [currentBatchSize, tensorSize, 1];

        const tensor = this.createTensor(samples, shape);

        const outputMap = await this.startInference(tensor);
        console.log("outputMap", await outputMap.data());
        const transposed = await this.processOutput(outputMap);

        data.push(await transposed.data());

        totalSamples += samples.length;
        this.msg(\`TOTAL SAMPLES: ${totalSamples}\`);
        console.log("total samples", totalSamples);
        tf.engine().endScope();
      }

      const endTime = performance.now();

      this.msg(`Done (${(endTime - startTime) / 1000} seconds)`);
      console.log(data);
    }, 300);
  }

  generateSignal(tensorSize, batchSize) {
    const arraySize = tensorSize * batchSize;
    const array = Float32Array.from({ length: arraySize }, () => Math.random());
    return array;
  }
```

Executing this on webgl, cpu and wasm returns data but webgpu returns zeros. 

**Describe the expected behavior**
Expected behaviour is that a Float32Array is output with data e.g. when batch size is < 131 :
Float32Array(528000) [0.49774274230003357, 0.6549861431121826, 0.2773461937904358, 0.5586902499198914, 0.807712197303, ...]

I have attached the model used and the js file that contains the code.

[Archive 2.zip](https://github.com/tensorflow/tfjs/files/8860609/Archive.2.zip)

**Comment by rthadur** [comment]
Did you enable " flag ": "enable-unsafe-webgpu" in chrome and try ?

**Comment by Shiv-Dhokia** [comment]
Yes that is enabled

**Comment by haoyunfeix** [comment]
This issue could also reproduce on Windows OS, I'll take a look.

**Comment by haoyunfeix** [comment]
During debugging, two errors were found:
1. Binding size (135168000) is larger than the maximum binding size (134217728).
2. The number of storage buffers (801) in the Compute stage exceeds the maximum per-stage limit (8).

Both could caused "returns array of zeros", root cause is the Concat operator used 800 input tensors (storage buffer) in compute stage. Below test could reproduce the error:
```
  it('kwlkejlkjg', async () => {
    const testArr = [];
    for (let i = 0; i < 800; i++) {
      testArr.push(tf.randomNormal([1, 132, 128]));
    }
    const result = tf.concat(testArr, 0);
    const a = await result.data();
  });
```
One possible solution is to merge the input tensors into a single input storage buffer, @qjia7 WDYT

**Comment by qjia7** [comment]
@haoyunfeix One quickly fixing is to reference WebGL's implementation https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/src/kernels/Concat_impl.ts#L98-L108. In the meantime, you can explore whether merging input tensors into a single input storage buffer or several input storage buffers can bring better  performance.

**Comment by haoyunfeix** [comment]
@qjia7 Thanks!
1. Binding size (135168000) is larger than the maximum binding size (134217728).
2. The number of storage buffers (801) in the Compute stage exceeds the maximum per-stage limit (8).

By adding two patches, https://github.com/tensorflow/tfjs/pull/6350 for (1) and https://github.com/tensorflow/tfjs/pull/6532 for (2), the attached demo could work by using self-built tfjs-backend-webgpu.
