### ISSUE TITLE
Provide esm file via jsdelivr

### ISSUE THREAD

**Issue by chrisdothtml** [tensorflow/tfjs#651]
Now that browsers are capable of importing es-modules natively, I write a lot of my hobby projects without a bundler. This should be easy (I think) since you're already generating an esm dist file

**Comment by nsthorat** [comment]
Does this not work?

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.12.6/dist/tf.esm.js

**Comment by chrisdothtml** [comment]
Sorry, thought I checked to see if there already were any already.

That would work for a bundler, but not for a browser, since the browser can't resolve npm package names (e.g. `@tensorflow/tfjs-core`).

Looks like [the way Ractive.js handles it](https://cdn.jsdelivr.net/npm/ractive@0.10.9/ractive.mjs) is by bundling everything into a single es-module. So maybe this _would_ require some extra work to generate

**Comment by nsthorat** [comment]
Ah yeah, we do this for core but haven't yet done it for the union package:

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@0.12.6/dist/tf-core.esm.js

We can keep this issue around to track that.

**Comment by chrisdothtml** [comment]
Sweet, thanks 👍

**Comment by nsthorat** [comment]
Union does this now: https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.1/dist/tf.esm.js
