### ISSUE TITLE
WASM backend doesn't work in a Web Worker

### ISSUE THREAD

**Issue by MatPoliquin** [tensorflow/tfjs#6517]
**System information**

- GPU :  ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
- OS: Windows 10
- BROWSER: Chrome Version 102.0.5005.63 (Official Build) (64-bit)
- TFJS VERSION: 3.18.0

**Describe the current behavior**
WASM backend doesn't seem to work with web workers.
I get these errors:

```
tf-backend-wasm.js:5325 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
tf-backend-wasm.js:5325 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
tf-backend-wasm.js:5325 Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f 
tf.min.js:17 Initialization of backend wasm failed
```

**Describe the expected behavior**
I got WASM to work in the main thread but not in a web worker.

**Standalone code to reproduce the issue**

I am unable to give standalone code but here is the init code. Please note that the web worker works with WEBGL and CPU backends

```
async function WorkerFunc() {

    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js");
    await tf.setBackend(backend);

}
```

**Comment by mattsoulanille** [comment]
It looks like the wasm backend doesn't know where to fetch the `.wasm` file from when it's instantiated in a webworker. We should fix this, or at least print a better warning message. For now, you can manually set the path to the `.wasm` files.

@MatPoliquin, this example should run if you paste it into the javascript console on [about:blank](http://about:blank).
```js
response = `async function WorkerFunc() {
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js");
    tf.wasm.setWasmPaths("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/wasm-out/");
    await tf.setBackend('wasm');

    console.log(tf.getBackend());
    const a = tf.tensor1d([1,2,3]);
    const b = tf.tensor1d([6,5,4]);
    a.add(b).print();
}

WorkerFunc();
`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob));
```
