### ISSUE TITLE
Model converter doesn't work with NASNetLarge and NASNetMobile in tf.keras.applications

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tfjs#652]
#### Describe the problem or feature request
I wanted to get out all ImageNet pretrained classifiers bundled with Keras for a web app demo I'm doing, but some of the models can't be converted automatically.

#### Code to reproduce the bug / link to feature request
```python
import os
import inspect

import tensorflow as tf
import tensorflowjs as tfjs

models = inspect.getmembers(tf.keras.applications, inspect.isfunction)
for model_name, model_fn in models:
    try:
        tf.keras.backend.clear_session()
        model = model_fn()
        model.compile('sgd', 'categorical_crossentropy')
        output_path = os.path.join('models', model_name)
        tfjs.converters.save_keras_model(model, output_path)
    except Exception as ex:
        print(f'{model_name} could not be converted.', ex)
```

```sh
Traceback (most recent call last):
  File "export_models.py", line 11, in <module>
    model = model_fn()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/nasnet.py", line 400, in NASNetLarge
    default_size=331)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/nasnet.py", line 321, in NASNet
    model.load_weights(weights_file)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1391, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 732, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 533 layers into a model with 527 layers.
```

**Comment by carlthome** [comment]
Thanks for the tip! So the exception happens already in `tf.keras` itself. This issue is probably related to recent refactoring of Keras, so maybe it would go away if `https://github.com/tensorflow/tfjs-converter/blob/master/python/requirements.txt#L5` was updated to a newer version?

`python -c "import tensorflow as tf; tf.keras.applications.nasnet.NASNetMobile().save('model.h5')"`

**Comment by caisq** [comment]
@carlthome I think updating the dependency versions is a good idea. Let me get that done first. Then we can see if this addresses your problem.

**Comment by rthadur** [comment]
Closing the issue as the commit has been pushed [here](https://github.com/tensorflow/tfjs-converter/pull/205), please feel free to reopen the issue if this has not been addressed.
