### ISSUE TITLE
tfjsmodel face_landmark_detection: error in "yarn watch" command

### ISSUE THREAD

**Issue by Sun1718** [tensorflow/tfjs#6527]
**System information**
- Linux Ubuntu 20.04:
- Nodejs v16.15.1
- TensorFlow.js 3.17.0

Hello every one,
I want to build tfjsmodel facelandmarkdetection sapmle in ubuntu server,but after "yarn watch" command, below error appear:

detection/demos/live_video# yarn watch
yarn run v1.22.18
warning ../../../../../package.json: No license field
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234 
✨  Built in 272ms.
Static path (file or directory) '/home/tfjs-models/face-landmarks-detection/demos/live_video/static' does not exist. Skipping.
Unexpected error while opening in browser: true
Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/tfjs-models/face-landmarks-detection/demos/live_video/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)

Any help appreciated.

**Comment by rthadur** [comment]
Did you try running all of the below commands ? I was able to run the demo on my Mac book pro

````
Go to the demo folder, e.g. cd live_video

Remove cache etc. rm -rf .cache dist node_modules

Build dependency. yarn build-dep

Install dependencies. yarn

Run the demo. yarn watch

The demo runs at localhost:1234. (Remember to provide URL model parameter e. g. localhost:1234/?model=mediapipe_face_mesh)`
```

**Comment by Sun1718** [comment]
Thanks for your reply,
I was able run the demo on my windows 10, but it has error on ubuntu 20.04.
I performed the steps in order. The output of each step is as follows:
1- "yarn build-dep":ndmarks-detection/demos/live_video# yarn build-dep
yarn run v1.22.18
warning ../../../../../package.json: No license field
$ cd ../../ && yarn && yarn build
warning ../../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @rollup/plugin-typescript@3.1.1" has incorrect peer dependency "rollup@^1.20.0".
warning " > @rollup/plugin-typescript@3.1.1" has unmet peer dependency "tslib@*".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.18".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
warning ../../../package.json: No license field
$ rimraf dist && tsc && yarn bundle
warning ../../../package.json: No license field
$ rollup -c

src/index.ts → dist/face-landmarks-detection.js...
created dist/face-landmarks-detection.js in 11.1s

src/index.ts → dist/face-landmarks-detection.min.js...
created dist/face-landmarks-detection.min.js in 9.9s

src/index.ts → dist/face-landmarks-detection.esm.js...
created dist/face-landmarks-detection.esm.js in 8.5s
Done in 70.61s.
2- "yarn" command:ndmarks-detection/demos/live_video# yarn
yarn install v1.22.18
warning ../../../../../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @tensorflow-models/face-detection@1.0.1" has unmet peer dependency "@mediapipe/face_detection@~0.4.0".
[5/5] Building fresh packages...
Done in 33.70s.
3- "yarn watch" command:root@ubuntu-g1-medium1-fr-1:/home/sobhasan/Documents/tfjs-modelsOriginal/face-landmarks-detection/demos/live_video# yarn watch
yarn run v1.22.18
warning ../../../../../package.json: No license field
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234 
⚠️  Could not load source file "../src/index.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/index.js".
⚠️  Could not load source file "../src/create_detector.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/create_detector.js".
⚠️  Could not load source file "../src/util.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/util.js".
⚠️  Could not load source file "../src/types.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/types.js".
⚠️  Could not load source file "../src/constants.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/constants.js".
⚠️  Could not load source file "../../src/tfjs/detector.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/tfjs/detector.js".
⚠️  Could not load source file "../../src/mediapipe/detector.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/mediapipe/detector.js".
⚠️  Could not load source file "../../../src/shared/calculators/image_utils.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/image_utils.js".
⚠️  Could not load source file "../../../src/shared/calculators/convert_image_to_tensor.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/convert_image_to_tensor.js".
⚠️  Could not load source file "../../src/mediapipe/detector_utils.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/mediapipe/detector_utils.js".
⚠️  Could not load source file "../../../src/shared/calculators/association_norm_rect.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/association_norm_rect.js".
⚠️  Could not load source file "../../../src/shared/calculators/detection_to_rect.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/detection_to_rect.js".
⚠️  Could not load source file "../../src/tfjs/constants.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/tfjs/constants.js".
⚠️  Could not load source file "../../src/tfjs/detector_utils.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/tfjs/detector_utils.js".
⚠️  Could not load source file "../../../src/shared/calculators/landmarks_refinement.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/landmarks_refinement.js".
⚠️  Could not load source file "../../../src/shared/calculators/landmarks_to_detection.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/landmarks_to_detection.js".
⚠️  Could not load source file "../../../src/shared/calculators/normalized_keypoints_to_keypoints.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/normalized_keypoints_to_keypoints.js".
⚠️  Could not load source file "../../../src/shared/calculators/transform_rect.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/transform_rect.js".
⚠️  Could not load source file "../../../src/shared/calculators/tensors_to_landmarks.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/tensors_to_landmarks.js".
⚠️  Could not load source file "../../../src/shared/calculators/calculate_landmark_projection.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/calculate_landmark_projection.js".
⚠️  Could not load source file "../../src/mediapipe/constants.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/mediapipe/constants.js".
⚠️  Could not load source file "../../../src/shared/calculators/sigmoid.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/sigmoid.js".
⚠️  Could not load source file "../../../src/shared/calculators/shift_image_value.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/shift_image_value.js".
⚠️  Could not load source file "../../../src/shared/calculators/get_rotated_sub_rect_to_rect_transformation_matrix.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/get_rotated_sub_rect_to_rect_transformation_matrix.js".
⚠️  Could not load source file "../../../src/shared/calculators/calculate_inverse_matrix.ts" in source map of "node_modules/@tensorflow-models/face-landmarks-detection/shared/calculators/calculate_inverse_matrix.js".
✨  Built in 26.64s.
Static path (file or directory) '/home/sobhasan/Documents/tfjs-modelsOriginal/face-landmarks-detection/demos/live_video/static' does not exist. Skipping.
Unexpected error while opening in browser: true
Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/sobhasan/Documents/tfjs-modelsOriginal/face-landmarks-detection/demos/live_video/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)

**Comment by Sun1718** [comment]
Yes, first I went to live_video folder and then run "rm -rf .cache dist node_modules" command for remove cache.
then run:
1-yarn build-dep
2-yarn
3-yarn watch

**Comment by Sun1718** [comment]
To make sure, I reinstalled a new version of Ubuntu 20.04.
And I did the following steps in order:

1- install nodejs version 16.15.1
2- install yarn
3- go to live_video folder
4- "rm -rf .cache dist node_modules"
5- "yarn build-dep"
6- "yarn"
7- "yarn watch"

But the errors were exactly repeated:

**Comment by mattsoulanille** [comment]
This seems to be an issue with Parcel not finding your browser. For convenience, Parcel will automatically open the demo page once it's done building, but in this case, it throws an error since it can't open the browser. While inconvenient, you should still be able to open the page manually by opening the http://localhost:1234/ link it printed before throwing the error. The error doesn't actually stop it from serving the files.
```
...
Server running at http://localhost:1234/
...
```

If you don't want to see the error, you can run parcel without the `--open` flag.
```
yarn cross-env NODE_ENV=development parcel index.html --no-hmr
```

**Comment by Sun1718** [comment]
Thanks for your reply,

Yes, the problem was the parcel. I can open the page manually by opening the http://localhost:1234/ 

Thanks again.

**Comment by rthadur** [comment]
@mattsoulanille do we plan to fix this as this is only Windows? Thank you.

**Comment by mattsoulanille** [comment]
@rthadur Probably not, since Parcel still bundles and serves the site correctly. It's just the browser launching that doesn't work.
