### ISSUE TITLE
404 not found — tfjs-converter@0.5.9

### ISSUE THREAD

**Issue by twalk4821** [tensorflow/tfjs#654]
This happens during npm install for the most recent version of tensorflow.

**Comment by twalk4821** [comment]
Actually I can’t npm install that package directly, either.

**Comment by caisq** [comment]
@twalk4821 Can you provide a little more details, like the command you used and your operation system?

I tried the following three commands on my linux machine and they all worked without any issue:
`npm i @tensorflow/tfjs`
`npm i @tensorflow/tfjs@0.12.6`
`npm i @tensorflow/tfjs@latest`
`npm i @tensorflow/tfjs-converter@0.5.9`

**Comment by twalk4821** [comment]
I’m behind a proxy so I wonder if that’s the issue, but let’s see. I ran npm install —save @tensorflow/tfjs, my operating system being Mac OS. All other npm packages install fine, though.

**Comment by twalk4821** [comment]
Thanks, I’m pretty sure this is a proxy issue. I’ll go ahead and close.
