### ISSUE TITLE
 [Error: The shape of dict['input_tensor'] provided in model.execute(dict) must be [1,-1,-1,3], but was [2,1280,720,3]] while using a model converted with tensorflowjs_convertor

### ISSUE THREAD

**Issue by TheRochVoices** [tensorflow/tfjs#6542]
I am trying to do batch inference with size 2 on my model and got the above error.
How can I fix this?
My guess is to somehow give input dimensions while exporting the model but I can't find the option to do that while using the tensorflowjs_convertor.

Basically, I want to  be able to do batch inference on my tfjs model. 
Appreciate any help.

**Comment by rthadur** [comment]
You can try to use `tensor = tensor.reshape([1, 224, 224, 3]);` to reshape the input.

**Comment by TheRochVoices** [comment]
@rthadur that i know. I actually want to infer on a batch of 2 images instead of 1.

**Comment by rthadur** [comment]
@TheRochVoices can you please share the model which you using ?

**Comment by TheRochVoices** [comment]
Hi @rthadur , It was an object detection model trained with tf object detection API and then exported to tfjs. During export, I came to realize that you can't have batchsize greater than 1 in an exported model.

**Comment by rthadur** [comment]
Thats true , if the original model does not support then tfjs will not be able to support.
