### ISSUE TITLE
TypeError: Unknown op 'CTCGreedyDecoder'

### ISSUE THREAD

**Issue by famy040326** [tensorflow/tfjs#6548]
Uncaught (in promise) TypeError: Unknown op 'CTCGreedyDecoder'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()

Please help to add CTCGreedyDecoder to tfjs.

**Comment by rthadur** [comment]
This will be a feature request . cc @pyu10055 @mattsoulanille

**Comment by famy040326** [comment]
TensorFlow version: 2.8.0
TensorFlow.js version : 3.18.0

**Comment by famy040326** [comment]
Please let me know if you need any other information.

**Comment by Napoleon-Jm** [comment]
+1 need this feature.

**Comment by gaikwadrahul8** [comment]
Hi, @famy040326 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and It seems like we haven't implemented `CTCGreedyDecoder `yet if I'm not wrong so May I know are you still looking for this Op in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by BrunoFelipe-react** [comment]
@gaikwadrahul8 
Any news on the implementation of this feature?
I really need this function in tfjs, I haven't been able to convert it in a conventional way...

**Comment by kieutrongthien** [comment]
Still waiting for this feature
