### ISSUE TITLE
Add tf.diagPart()

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#655]
Add tf.diagPart() modeled after [tf.diag_part()](https://www.tensorflow.org/api_docs/python/tf/diag_part) in Python. See [discussion](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/QOzq60A3n48/ZiaEcGLNEwAJ) for context.

**Comment by kedevked** [comment]
I will work on it

**Comment by kedevked** [comment]
Hello @dsmilkov ! 
Sorry for my late reply. Okay, I will resume working on this operator.
