### ISSUE TITLE
tfjs-converter documentation: effects of quantization

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#6551]
I would like to know what are the effects of quantization, however, could not find documentation for tfjs, only tflite
https://www.tensorflow.org/lite/performance/post_training_quantization

I would like to know if quantized models perform faster, or, is quantization in tfjs only done to reduce the model size-on-disk, and in fact when decoded, the model is converted back to float32 (from float16 or uint8)

**Comment by pyu10055** [comment]
For TFJS model, the quantized model does not perform faster, it is a weight compression mechanism to save storage and transportation cost. The weights are scaled back to float32 before computation.
Float16 is an interested case, where we do have float16 support (flag) on WebGL, you can see performance gain comparing to float32.

**Comment by AmitMY** [comment]
Thanks @pyu10055 
Is there any supported way to turn on that flag when supported, and also use float16 directly in `tfjs` without scaling the weights back?

Benefits may include: 
- faster transfer of the model to the gpu (`webgl`, `webgpu`)
- lower memory footprint
- faster model inference

**Comment by pyu10055** [comment]
the flag is there already, you can apply it as following
```
 env().set('WEBGL_FORCE_F16_TEXTURES', true);
```

**Comment by AmitMY** [comment]
Thanks. In my benchmark, using Chrome's performance tab, this flag has no impact on performance, which is strange to me. 

However, it does impact the model's output. 

Model is quantized to float16, normal inference: (correct output)

https://user-images.githubusercontent.com/5757359/175312151-38c4ffdf-2ce8-4284-bfe6-c07f9f8680fe.mp4



with [flag](https://github.com/sign/translate/blob/master/src/app/modules/pix2pix/pix2pix.worker.ts#L32): (output in weird shade)

https://user-images.githubusercontent.com/5757359/175311995-7c28fc42-2568-4ff0-a10e-6ff32d659bfc.mp4

*The model in question is keras pix2pix - https://www.tensorflow.org/tutorials/generative/pix2pix, and the weights are: https://github.com/sign/translate/tree/master/src/assets/models/pose-to-person 
*Inference code https://github.com/sign/translate/blob/master/src/app/modules/pix2pix/pix2pix.worker.ts#L51

**Comment by pyu10055** [comment]
@AmitMY I tried your model on our benchmark tool. As you have observed the performance difference is minimal (2%) when switching between force float16.
For the correctness of the output, one possibility is the intermediate tensor values might exceed float16 range, which could cause the final output to be different.

**Comment by pyu10055** [comment]
The tool is [here](https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html).
