### ISSUE TITLE
Beginner Issue related to dimensions

### ISSUE THREAD

**Issue by fromb2b** [tensorflow/tfjs#6553]
I am new to Tensorflow and have been struggling with running the model below :
 https://gist.github.com/fromb2b/b7c57b314e62eddaabf2f21b399fb58a 
I am getting  `Error:Error when checking input: expected lstm_LSTM1_input to have 3 dimension(s). but got array with shape 1606,73 `  as an error. 

 I can't figure out why. Can you assist me please.

**Comment by rthadur** [comment]
Please use `tf.reshape` to  reshape the input to have 3 demensions. Thank you.

**Comment by fromb2b** [comment]
> Please use `tf.reshape` to reshape the input to have 3 demensions. Thank you.

Thank you for your suggestion. 
I transformed the tensor's shape. However, I now get a new error in line 134:

`Error: Size(15987) must match the product of shape 3`

**Comment by rthadur** [comment]
This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
