### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2, `@tensorflow/tfjs-node` & Docker

### ISSUE THREAD

**Issue by zaida04** [tensorflow/tfjs#6556]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 Pro 19044.1766**, **Docker version 20.10.10, build b485636**
- TensorFlow.js installed from (npm or script link): **https://www.npmjs.com/package/@tensorflow/tfjs-node**
- TensorFlow.js version: **3.18.0**
- CUDA/cuDNN version: N/A

**Describe the problem**
When an application using the module is ran, an error is thrown:
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/app/PROJECT/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Done through a Dockerfile
```
FROM node:16-alpine
WORKDIR /opt/build

COPY ./services/PROJECT/package.json ./
RUN yarn install

COPY ./services/PROJECT/src/. ./src/

FROM node:16-alpine
WORKDIR /usr/app

COPY --from=0 ./opt/build/tsconfig.json .
COPY --from=0 ./opt/build/services/PROJECT/ services/PROJECT/

WORKDIR /usr/app/services/PROJECT
CMD ["yarn", "run", "start"]
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zaida04** [comment]
This issue occurs on _any_ docker image I use, ubuntu, regular node-16, alpine.

**Comment by rthadur** [comment]
You might probably missing libc, you might to run apt install libc-dev or build-essential , please check a related [so](https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li/51655643#51655643) question. Thank you

**Comment by zaida04** [comment]
Thank you! While I wasn't able to get alpine working, switching to the debian buster slim image and installing libc related packages worked!
