### ISSUE TITLE
The myth of `HTMLVideoElement.readyState` and `HTMLVideoElement.requestVideoFrameCallback`

### ISSUE THREAD

**Issue by hujiajie** [tensorflow/tfjs#6577]
I'm seeing this error when running latest TFJS unit tests with the WebGPU backend:

```
Chrome 105.0.0.0 (Windows 10) webgpu backend webgpu webgpu {"WEBGPU_CPU_FORWARD":false} should behave well if WEBGPU_USER_IMPORT is true or false FAILED
 Error: The video element has not loaded data yet. Please wait for `loadeddata` event on the <video> element.
     at fromPixels_ (tfjs-core/src/ops/browser.ts:115:13 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:5941:15)
     at Object.<anonymous> (tfjs-core/src/ops/browser.ts:279:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:6021:14)
     at <Jasmine>
     at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:52:64
     at <Jasmine>
     at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:36:12)
     at Object.fromPixelsAsync (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:6004:12)
     at ../../tfjs-backend-webgpu/src/backend_webgpu_test.ts:248:36 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:84990:47
     at <Jasmine>
     at fulfilled (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:39:27)
```

**OS:** Windows 10 (19044.1766)
**GPU:** Intel UHD 620 (driver version: 30.0.101.1994)
**Browser:** Chrome Canary (version: 105.0.5148.0)

What I don't understand is the readiness of the frame data has already been gated by `HTMLVideoElement.requestVideoFrameCallback`:

https://github.com/tensorflow/tfjs/blob/ca9799d16e23f7f31d4fdb15febb81d2eb4a2790/tfjs-backend-webgpu/src/backend_webgpu_test.ts#L243

How can the ready state be 1 (`HAVE_METADATA`) instead of 2 (`HAVE_CURRENT_DATA`) or higher here:

https://github.com/tensorflow/tfjs/blob/ca9799d16e23f7f31d4fdb15febb81d2eb4a2790/tfjs-core/src/ops/browser.ts#L112-L118

Am I misunderstanding anything? Thanks

cc @gyagp @qjia7 @shaoboyan

**Comment by qjia7** [comment]
@hujiajie Please file a chromium issue to see whether it's a chrome bug about the `readyState` and lint it here. Thanks.

**Comment by hujiajie** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1340433
