### ISSUE TITLE
tf.moments() has numeric issues and is flaky

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#658]
I was writing test and want to use test_util.expectNumbersClose, but it's not stable when checking mean and variance for big array with large numbers.

So I tried with test for tf.moments (https://github.com/tensorflow/tfjs-core/blob/v0.11.1/src/ops/reduction_ops_test.ts#L636):

```
it('basic', () => {
    // const a = tf.tensor2d([1, 2, 3, 0, 0, 1], [3, 2]);
    const a = tf.tensor1d([
      1, 2, 3, 0, 0, 1, 10, 100, 1000, 10000, 10000, 24, 34643, 1000000, 43053,
      24241
    ]);
    const {mean, variance} = tf.moments(a);
    expect(mean.dtype).toBe('float32');
    expect(variance.dtype).toBe('float32');
    // expectNumbersClose(mean.get(), 7 / 6);
    expectNumbersClose(
        mean.get(),
        70192.375,
    );
    expectNumbersClose(
        variance.get(), 57813172224  // 1.1389
    );
});
```

run this test for several times, sometimes variance is 57813172224, but sometimes it would show error:

```
Error: Numbers differ: actual === 57813176320, expected === 57813172224
	    at Object.expectNumbersClose (src/test_util.ts:123:10 <- src/test_util.js:88:15)
	    at UserContext.<anonymous> (src/ops/reduction_ops_test.ts:732:4 <- src/ops/reduction_ops_test.js:571:21)
	    at <Jasmine>
```

**Comment by dsmilkov** [comment]
Thanks for investigating this. This looks more like a problem of moments/variance, than a problem with expectNumbersClose().

Did you run this test several times on the same machine? Or several times on different machines?

**Comment by kangyizhang** [comment]
I ran this test several times on the same machine. 

I agree that this should be an issue with tf.moments(). I also met the same situation when I use moments for mean and variance elsewhere. tf.moments() is returning two possible results, such as the above example, first run it returns 57813172224, second run it returns  57813176320, and third run returns 57813172224 again.

**Comment by dsmilkov** [comment]
This can be a side-effect of how GPUs are storing floats and losing precision. I would avoid using large numbers - in practice all models are dealing with values that are bounded, otherwise all other sorts of numeric issues arise.

Now, outside machine learning, this tells me that we should not be using `tf.moments()` for pre-processing data, where precision matters. Or we should be doing it on the CPU.

cc @nsthorat @davidsoergel for visibility.

**Comment by dsmilkov** [comment]
Had some chat with other folks. We should keep using tf.moments() since it's only our WebGL backend that has flaky behavior with large numbers. I won't just avoid writing unit tests with such large numbers, or constrain the unit test to only run on CPU/nodejs backend.

**Comment by kangyizhang** [comment]
Got it. Thanks for the investigation!

**Comment by dsmilkov** [comment]
After investigation, we've concluded that these numerical issues arise due to the hardware limitations, thus closing this issue.
