### ISSUE TITLE
dataToGPU description is not updated to tensorflow api reference

### ISSUE THREAD

**Issue by xhcao** [tensorflow/tfjs#6595]
The description of dataToGPU api had been modified for webgpu backend in the https://github.com/tensorflow/tfjs/pull/6393, but the changes had not been updated the tensorflow api reference https://js.tensorflow.org/api/latest/#tf.Tensor.dataToGPU .

**Comment by xhcao** [comment]
@lina128 ,  could you take a look, thank you.

**Comment by rthadur** [comment]
Changes will be deployed in next release .
