### ISSUE TITLE
Is it possible  to use Tfjs-vis in NodeJS

### ISSUE THREAD

**Issue by fromb2b** [tensorflow/tfjs#6596]
Hi,

  I am a beginner in Tensorflow JS and was looking at ways of visualizing the trainning process (I do the processing in NodeJS).
I noticed that all tutorials of visualization talk about Tensorboard for Python.

Do you have any suggestions?

**Comment by rthadur** [comment]
please check the related discussion here https://groups.google.com/a/tensorflow.org/g/tfjs/c/wV5WHucHXao/m/fOJxNQXyCAAJ , there is no active development on this front.
