### ISSUE TITLE
[feature] Add Model.fitDataset

### ISSUE THREAD

**Issue by vmarkovtsev** [tensorflow/tfjs#660]
#### TensorFlow.js version
0.12.5

#### Browser version
N/A - Nodejs 10.9

#### Describe the problem or feature request
My dataset is so big that I cannot place it into memory. Keras has `fit_generator`
 to take batches from a callable but tfjs doesn't. Apart from super big datasets, it helps to reduce the memory requirements if you do image perturbations for example.
I suggest adding a similar function to `tf.Model`: `fitPartial`, `fitOnBatch`, `fitGenerator` or whatever you name it.

**Comment by bileschi** [comment]
FYI @davidsoergel @kangyizhang @dsmilkov

**Comment by davidsoergel** [comment]
How timely-- already in the works :)

**Comment by vmarkovtsev** [comment]
@davidsoergel Sweet! Any ETA?
