### ISSUE TITLE
This Node instance does not support builds for Node-API

### ISSUE THREAD

**Issue by fromb2b** [tensorflow/tfjs#6600]
Hi,

  I am new to Tensorflow JS.
 
I tried to replace @tensorflow/tfjs with @tensorflow/tfjs-node after installing Python in order to speed up the training process but I got this message when running the model:

`node-pre-gyp info This Node instance does not support builds for Node-API version 7
node-pre-gyp info This Node instance does not support builds for Node-API version 8
node-pre-gyp info This Node instance does not support builds for Node-API version 7
node-pre-gyp info This Node instance does not support builds for Node-API version 8
2022-07-03 21:58:49.916274: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Orthogonal initializer is being called on a matrix with more than 2000 (4096) elements: Slowness may result.` 

And then the training starts in a low pace.

Do you have any suggestions in order to fix this problem?

**Comment by rthadur** [comment]
Please check similar issue here https://github.com/tensorflow/tfjs/issues/5017 where napi 8 is supported .
