### ISSUE TITLE
Please upload latest master to npm for tfjs

### ISSUE THREAD

**Issue by kirkpa** [tensorflow/tfjs#6620]
**Describe the problem**
Current npm tfjs-node version does not include support for linux/arm64. Support for linux arm64 was recently merged into master
https://github.com/tensorflow/tfjs/pull/6564

Please update npm with latest master.
Thanks.

**Comment by rthadur** [comment]
@kirkpa change will be available in next release(TBD) , if you want you can clone the repo and get latest changes. Thank you
