### ISSUE TITLE
Cannot read property 'assertAndGetBroadcastShape' of undefined

### ISSUE THREAD

**Issue by senthilkumar-chandramohan** [tensorflow/tfjs#6628]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 Home 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.18.0
- Browser version: Node v10.14.2, was unable to install @tensorflow/tfjs-node
- Tensorflow.js Converter Version: 3.18.0

**Describe the current behavior**
tfjs errors out on executing tf.sequential().fit(), with pre-configured layers, optimizer and loss functions.

**Describe the expected behavior**
tf.sequential().fit() operation should train the model and provide training and validation loss details in result.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
The application code is available in https://github.com/senthilkumar-chandramohan/house-price-predictor, please follow steps in README to run it. Check server log (provided below) at step 7 to see the problem.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

(node:11452) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'assertAndGetBroadcastShape' of undefined
    at batchMatMul (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs-backend-cpu\dist\tf-backend-cpu.node.js:3118:53)
    at Object._fusedMatMul [as kernelFunc] (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs-backend-cpu\dist\tf-backend-cpu.node.js:3194:21)
    at kernelFunc (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4586:32)
    at D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4646:27
    at Engine.scopedRun (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4451:23)
    at Engine.runKernelFunc (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4642:14)
    at Engine.runKernel (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4515:21)
    at D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:21088:20
    at forwardFunc (D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5086:25)
    at D:\Projects\ml\house-price-predictor\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4625:55

**Comment by rthadur** [comment]
I was able to run above model with our errors on Mac book pro , can you please check again if this is related to Windows.

**Comment by senthilkumar-chandramohan** [comment]
@rthadur , that's correct, I was also able to run it without any errors in Macbook Pro, facing issue only in Windows 11.

**Comment by senthilkumar-chandramohan** [comment]
Hi @lina128 , I'm not facing the issue anymore, but when I did, I found error in this line:
![Issue](https://user-images.githubusercontent.com/47057220/181775047-84869504-6f40-4707-902e-1e5b95f4878c.png)

tfjsCore.broadcast_util was evaluating to undefined.

But it looks OK now, wonder how?
![Startup](https://user-images.githubusercontent.com/47057220/181775273-e34ef311-2f45-4368-96c9-4ad2ab42b58c.png)

**Comment by shmishra99** [comment]
Hi @senthilkumar-chandramohan ,
Apology for the late response. I have replicated the issue with the latest version of @tensorflow/tfjs@4.6.0. It is working as expected, as you mentioned.
load-model: 
<img width="638" alt="image" src="https://github.com/tensorflow/tfjs/assets/124146945/3c402a9e-fa02-4f7a-b539-fd75911cbf2c">
Prediction: 
<img width="948" alt="image" src="https://github.com/tensorflow/tfjs/assets/124146945/c8b20c13-f2e0-4a8c-96bc-3662fb8aedae">
It is possible that you were getting an error previously because your package download was corrupted or npm did not download all the dependency files.
 Thank You!
