### ISSUE TITLE
Run Google cloud vision model in Express js app

### ISSUE THREAD

**Issue by glorio-loopstudio** [tensorflow/tfjs#6632]
Hello guys! This is my situation. I train a classification image model in google cloud vision auto ml and I download it as tensor flow to install in my node js server.

I don't know how to implement this in my express js app.

Any help? Thanks

**Comment by rthadur** [comment]
This question is better asked on [Discourse-TF](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
