### ISSUE TITLE
Add chestxray.ai example to https://github.com/tensorflow/tfjs-examples

### ISSUE THREAD

**Issue by jordimassaguerpla** [tensorflow/tfjs#6673]
Hi!

I did this small project about predicting diseases based on a Chest X Ray, using tensorflowjs. I thought it could be a great example for your repository of examples.

![image](https://user-images.githubusercontent.com/1148215/180750703-0fe1b7cc-e1ee-41bf-9887-46b86bf076ef.png)

https://github.com/jordimassaguerpla/chestxray.ai

Could you please consider its addition?

Note I am not a javascript expert, so I am open to review the code, refactor, etc...

**Comment by pyu10055** [comment]
We are happy to promote your work, you can submit a PR to add your work to our gallery page.
Also feel free to reach out to our Developer relationship lead @jasonmayes to discuss more about details of your work.
