### ISSUE TITLE
model inference causes unresponsiveness and even system crash when using `webgl` backend

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6678]
model inference causes unresponsiveness and even system crash when using `webgl` backend  
while running perfectly fine using `tfjs-node`  

## using `webgl` in browser

gpu memory usage raises to >4GB although model is not that heavy at all  

inference time is measured as below 40 ms, but actual wall time between frames is closer to 3,000 ms!  

during that time browser is completely unresponsive (not just active tab)  
and overall system responsiveness is reduced  

and after just several frames it will result in either browser crash or webgl error logged in console  

it even resulted in a **system crash** - **BSOD** with stop code `VIDEO_SCHEDULER_INTERNAL_ERROR` !!!

*yes, its a client-side code that can result in a system crash - doesn't get much worse than that*  

*its almost like a some `webgl` call is causing something really bad to happen between browser and gpu drivers*  

## using `tfjs-node-gpu` in node

works without any problems  
low memory usage and inference time below 30ms  

even round-trip workflow (browser client talking via websockets to server that does processing) results in pretty good frame rate and no overall issues

## model

model itself is a simple **tfjs graph model** with 8.8MB weights  
it takes 720x720 image as input and produces 720x720 image as output  
converted from **tf saved model** with original at <https://systemerrorwang.github.io/White-box-Cartoonization/>  

## reproduction

full reproduction using <https://github.com/vladmandic/anime>

- **browser** code that causes problems is <https://github.com/vladmandic/anime/blob/main/src/anime-clientside.ts>  
- **nodejs** code entry point is <https://github.com/vladmandic/anime/blob/main/src/node.ts> (which works just fine)  

## environment

- tensorflow 3.19.0
- chome 103.0.1264.71
- windows 11 build 22621.436
- nvidia drivers 516.59

**Comment by vladmandic** [comment]
FYI, this is BSOD screenshot: 
![image](https://user-images.githubusercontent.com/57876960/181063083-40ba8919-ba5e-4bae-8af1-4d3939037ff6.png)

**Comment by pyu10055** [comment]
@vladmandic This is likely caused by our im2col algorithm that expand the conv2d inputs. Given the model has relatively large input and filter size, it could cause the intermediate texture exceeding the GPU texture limit and start to paging.
We have just pushed a change that implements a full packed version of conv2d, that should potentially eliminate the problem, we will benchmark your model and get back to you.

**Comment by vladmandic** [comment]
@pyu10055 sounds good - is the pr committed to main? if yes, i can try it.

**Comment by pyu10055** [comment]
@vladmandic we are seeing 10x improvement, this feature is in the master branch and behind a flag ('WEBGL_EXP_CONV') right now, you can build the webgl backend and try again. If you have question, @Linchenn can provide more details.

**Comment by vladmandic** [comment]
@pyu10055 confirmed!  

actually, its not 10x, its closer to 20x on my system plus no crashes

**Comment by vladmandic** [comment]
slightly off-topic, 90%+ of wall time is now spent in tensor data download from gpu memory as there is no optimized way to draw it on screen (`toPixels` has no optimized data paths unlike `fromPixels`) - i've created a feature request for that.

**Comment by vladmandic** [comment]
@pyu10055 @Linchenn there is still something really weird here...yes, new `conv2d` algorithm is much faster, but there is still a background issue. 

look at timings: preprocess input + run inference + process output + draw on canvas = ~10ms

but if i run a loop with `setImmediate()` or `requestAnimationFrame()`, browser becomes sluggish and overall refresh rate is visually much slower than calculated one (1000ms / ~10ms = 100fps)

even `HMTLVideoElement` that is bound to **WebCam** is not refreshing smoothly - and that is not done in JS code, that is pure browser item.

and if i open chrome frame rendering stats overlay, it shows 90% frames are dropped (which means only 1-in-10 frames actually gets drawn which is exactly why everything feels sluggish)

only way to get rid of "slugishness" is to introduce artificial delay in each pass - for example, using `setTimeout()` with 100ms delay. then everything works as expected.

this is exactly the same as originally reported, except then i needed to use artificial delay of 3000ms and with new algorithm delay of 100ms is sufficient.

i've also tried with latest chrome canary and its definitely faster up to a point i can reduce a delay down to 80ms without issues, but its still affected.

code: <https://github.com/vladmandic/anime/blob/main/src/anime.ts>  

note it currently uses `webgl` and `dataToGPU()` to draw texture to canvas, but that is not an issue as its exactly the same problem without it. you can even disable draw to canvas and pre and post processing and just run inference and its the same problem - it cannot run in an immediate loop without affecting the system (all other models i've ever seen take more or less time to execute, but there is never a problem to run them in a loop)

**Comment by Linchenn** [comment]
I just ran it locally, typically `t4 - t1` is small and `t4 - t0` is very large, which means the "slugishness" may come from the period between the calls to `runInference`, instead of model execution stuff.

Could you try `video.requestVideoFrameCallback(() => runInference(++frame2));` at [line84](https://github.com/vladmandic/anime/blob/main/src/anime.ts#L84). I am not sure if `requestAnimationFrame` caps the times to call this callback.

**Comment by vladmandic** [comment]
> I just ran it locally, typically t4 - t1 is small and t4 - t0 is very large, which means the "slugishness" may come from the period between the calls to runInference, instead of model execution stuff

On my system, both `t4-t1` and `t4-t0` are small which results in callback being executed too fast and stepping on each other  

That's why i don't see a problem when i'm using `setTimeout(() => runInference(++frame), 100);` (except fps is low as expected  

Difference between our result is that this time "outside" of actual processing on your system is blocking (thus large `t4-t0` time) and on my system is non-blocking (thus small `t4-t0` time, but overall slugishness as browser resources are busy and its dropping frames)

What is your test system? I'm running on Chrome on Windows 11 with nVidia GPU (details provided in the initial post)  

> I am not sure if requestAnimationFrame caps the times to call this callback

`requestAnimationFrame` sets a cap at 60FPS which is nowhere close what i'm getting  

> Could you try video.requestVideoFrameCallback(() => runInference(++frame));

Difference between `requestVideoFrameCallback` and `requestAnimationFrame` is that `requestVideoFrameCallback` would fire back at lower of video refresh rate and overall refresh rate of 60fps - so according to spec, it fires up to 60fps, never above.  

But...`requestVideoFrameCallback` does seem to perform extra browser paint synchronization step and thus my problematic non-blocking background op that causes slugishness turns into a blocking one and resulting frame rate is real frame rate (and `t4-t0` times suddenly appear larger).

This is a very weird one as i cannot pinpoint background op that causes issues - it doesn't show on js profiler (and turning on webgl profiling slows things too much that its no longer there)  

In general, I'm inclined to blame this on a chrome internal bug, but its weird its happening with this single model

**Comment by Linchenn** [comment]
I was running on a Windows desktop with 3060 card. By the way, using `setTimeout` here may cause system crash for some low-performance machines, when their `t4 - t1` is larger than 100ms.

**Comment by vladmandic** [comment]
setInterval would cause a crash due to exploding overlapping inference requests, but why would setTimeout cause any problems?

**Comment by pyu10055** [comment]
@vladmandic Your `runInference` method need to wait for all GL command completion before start processing a new frame.
Here is a way to create fencing and sync wait for gl command to finish. I am seeing the inference + drawing takes about 290ms on my M1.

```js
  ...
  const t2 = performance.now();
  t.data = t.norm.dataToGPU({ customTexShape: [resolution[0], resolution[1]] });
  drawTexture(canvas, t.data.texture);
  const fenceSync = backend().gpgpu.createAndWaitForFence();
  fenceSync.then(() => {
    dispose(t.data.tensorRef);
    const t3 = performance.now();
    for (const tensor2 of Object.keys(t))
      dispose(t[tensor2]);
    const t4 = performance.now();
    log6("frame", {
      frame: frame2,
      fps: Math.round(1e4 / (t4 - t0)) / 10,
      total: Math.round(t4 - t1),
      inference: Math.round(t2 - t1),
      download: Math.round(t3 - t2),
      draw: Math.round(t4 - t3),
      tensors: memory().numTensors,
      bytes: memory().numBytes,
      shape: t.squeeze.shape
    });
    t0 = t4;
    setTimeout(() => runInference(++frame2), 0);  
  });
```

**Comment by pyu10055** [comment]
cc @Linchenn @lina128

**Comment by Linchenn** [comment]
Thank you Ping! Yeah, we have to block not only on CPU, but also on GPU. Previously, even though we have waited on CPU, overlapping inference requests on GPU always happens, which causes my low-performance machine slow down. I just tried the new code snippet on a low-performance machine again: even though "slugishness" still exists (as expected), this no longer causes my computer slow down.

**Comment by vladmandic** [comment]
@pyu10055 thats exactly it - thanks!

but...shouldn't waiting for fence handled inside model execution?  
note that problem exists regardless of any use code and is purely due to `model.execute()` which is supposed to be a sync call.

to confirm, i've removed all user code and problem exists when using `setTimeout(() => runInference(), 0)`,  
and problem is resolved if i add `await tf.backend().gpgpu.createAndWaitForFence();` immediately after `model.execute(tensor)`  

i did a dump of kernel ops used by model and its a short one:  

> signature model/whitebox.json
```js
INFO:  graph model: /home/vlado/dev/anime/model/whitebox.json
INFO:  created on: 2022-07-25T16:05:04.303Z
INFO:  metadata: { generatedBy: 'https://github.com/SystemErrorWang/White-box-Cartoonization', convertedBy: 'https://github.com/vladmandic', version: '1087.undefined' }
INFO:  model inputs based on signature
 { name: 'input', dtype: 'DT_FLOAT', shape: [ 1, 720, 720, 3 ] }
INFO:  model outputs based on signature
 { id: 0, name: 'add_1', dytpe: 'DT_FLOAT', shape: [ 1, 720, 720, 3 ] }
INFO:  tensors: 51
DATA:  topology: { nodes: 102 }
DATA:  weights: {
  files: [ 'whitebox.bin' ],
  size: { disk: 9155292, memory: 18310568 },
  count: { total: 51, float32: 49, int32: 2 },
  quantized: { float16: 49, none: 2 },
  values: { total: 4577642, float32: 4577638, int32: 4 }
}
DATA:  kernel ops: {
  graph: [ 'Const' ],
  convolution: [ '_FusedConv2D', 'DepthwiseConv2dNative' ],
  basic_math: [ 'Square' ],
  arithmetic: [ 'Mul', 'Sub', 'Add', 'AddV2', 'RealDiv' ],
  image: [ 'ResizeBilinear' ]
}
DATA:  execution profile: { requireAsync: false, wallTime: 1368.66, kernelTime: 1047.38, numKernels: 99, peakBytes: 302393768 }
```

**Comment by pyu10055** [comment]
@vladmandic currently, the model execution does not wait for GPU completion.
It is the tensor.data() and tensor.dataSync() that provide different mechanism to do GPU/CPU sync.
Given that your pipeline is fully running on GPU, you need to throttle your frame rate to be the same as the GPU processing rate, which at the end of the pipeline (after rendering) you need to perform GPU/CPU sync.

**Comment by vladmandic** [comment]
@pyu10055 ok, that makes sense. with all the info provided, i'm closing the issue - thanks.
