### ISSUE TITLE
Surface tf.node.* API under the "Node" section in API docs

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#668]
tfjs-node specific API will live in the `tfjs-node` module. Those methods should be part of the API docs generation and should surface in `https://js.tensorflow.org/api/latest/` under the top-level `Node` section.

**Comment by dsmilkov** [comment]
cc @nkreeger @tafsiri

**Comment by tafsiri** [comment]
@nkreeger @dsmilkov could you point me to where some tfjs-node specific api lives? Does this get included in the union package? Not sure what the action item is here (e.g. adding some section metadata for those functions, adding build infrastructure etc).

**Comment by dsmilkov** [comment]
Sorry, I wasn't clear. This is me proactively filing the issue so we track it. At this point, there is no tfjs-node specific API, but there will be when the auto-generated op methods are checked in.

**Comment by nsthorat** [comment]
This is fixed.
