### ISSUE TITLE
Offline Model for Pose Detection

### ISSUE THREAD

**Issue by eledahl** [tensorflow/tfjs#6685]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone SE 2020
- TensorFlow.js installed from (npm or script link): npm 
- TensorFlow.js version: "^3.18.0"

**Describe the problem**
Trying to load BlazePose from the offline model but getting: 

`[Unhandled promise rejection: Error: The shape of dict['input'] provided in model.execute(dict) must be [1,192,192,3], but was [1,224,224,3]]`

I'm using the offline model from [here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection). Here is my code: 

```
const blazePoseModelConfig: posedetection.BlazePoseTfjsModelConfig = {
        runtime: "tfjs",
        enableSmoothing: true,
        modelType: "full",
      };
      if (LOAD_MODEL_FROM_BUNDLE) {
        const modelJson = require("./offline_model/model.json");
        const modelWeights1 = require("./offline_model/group1-shard1of2.bin");
        const modelWeights2 = require("./offline_model/group1-shard2of2.bin");
        blazePoseModelConfig.detectorModelUrl = bundleResourceIO(modelJson, [
          modelWeights1,
          modelWeights2,
        ]);
      }

      const model = posedetection.SupportedModels.BlazePose;

      const detector = await posedetection.createDetector(
        model,
        blazePoseModelConfig
      );
      setModel(detector);
```

Is this due to the weights being set for MoveNet? If so, where do I find them for BlazePose? I have searched in multiple places for no luck

**Comment by pyu10055** [comment]
@eledahl Your code snippet did not show inference part, but from the error message, you need to resize your input image accordingly.
```
const resizedImage = tf.image.resizeBilinear(image, [192,192])
```

**Comment by eledahl** [comment]
Hi @pyu10055, I've pretty much copied the code from [this example](https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection) but converted it to BlazePose. Everything works fine when loading model from  network for Movenet or BlazePose. Loading from offline model works fine for Movenet but not BlazePose. I'm not seeing anywhere for resizedImage in the example.

**Comment by pyu10055** [comment]
could be that blazepose and movenet models have different input size requirement, @jinjingforever is there input resizing happening somewhere in the RN example?

**Comment by jinjingforever** [comment]
Hi @eledahl 

The movenet model API will resize the input tensor automatically. If BlazePose requires certain input size, you need to make sure the following two parameters are set to the correct number (192 in this case per @pyu10055). 

https://github.com/tensorflow/tfjs-examples/blob/42f5ac384884c5ddde0b977434152a4308e5a183/react-native/pose-detection/App.tsx#L293-L294

Thanks!

**Comment by eledahl** [comment]
Hi @jinjingforever,  

Hmm I updated those parameters to be 192 and also tried changing `OUTPUT_TENSOR_WIDTH` to 192 as well. Still giving me the same error that input was ` [1,224,224,3]]`

**Comment by jinjingforever** [comment]
Oh, just realized that the offline model in the example is for movenet, not blazepose. They are two different models (but have the similar APIs). Behind the scene, the models are loaded from different places.

For blazepose model urls, see [here](https://github.com/tensorflow/tfjs-models/blob/debbbeac8fe54115d7f7fccea7b51614f17af3e9/pose-detection/src/blazepose_tfjs/constants.ts#L21-L24) (also [here](https://github.com/tensorflow/tfjs-models/blob/debbbeac8fe54115d7f7fccea7b51614f17af3e9/pose-detection/src/blazepose_tfjs/constants.ts#L51-L52)).

Thanks!

**Comment by eledahl** [comment]
That fixed it! Thank you @jinjingforever @pyu10055!
