### ISSUE TITLE
Tensorflow JS tf.data.webcam does never resolve

### ISSUE THREAD

**Issue by DanielHabenicht** [tensorflow/tfjs#6693]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Huawei P20 Pro
- TensorFlow.js installed from (npm or script link): https://js.tensorflow.org/api/latest/#data.webcam
- TensorFlow.js version (use command below): 3.19.0
- Browser version: Chrome (103.0.5060.129) 
- Tensorflow.js Converter Version: ---

**Describe the current behavior**
1. Visit https://js.tensorflow.org/api/latest/#data.webcam from a mobile device.
2. Click the "Run" Button on the "[tf.data.webcam](https://js.tensorflow.org/api/latest/#data.webcam)" Example. 
3. Allow Camera or any other Request to access it.
4. Nothing happens: 
![image](https://user-images.githubusercontent.com/13590797/181673184-3fbd6984-a080-465f-875a-45ddb45bf790.png)

**Describe the expected behavior**
It should work the same as when accessed from a PC: 
![image](https://user-images.githubusercontent.com/13590797/181672577-b5a29d91-427b-4170-b83e-033004e3cfac.png)

**Standalone code to reproduce the issue**
```js
const videoElement = document.createElement('video');
videoElement.width = 100;
videoElement.height = 100;
const cam = await tf.data.webcam(videoElement);
const img = await cam.capture();
img.print();
cam.stop();
```

**Other info / logs** Include any logs or source code that would be helpful to
It happened once, that there was a result displayed, but I could never reproduce it again. 
It also happened in custom code first and I just tried the demo to reproduce and it did.

**Comment by rthadur** [comment]
This is working in latest IOS and andriod devices as expected , we do not have Huawei to reproduce the same and support.

**Comment by DanielHabenicht** [comment]
Strange, it seems to work now. I revisited it today and couldn't make it reproduce anymore.
