### ISSUE TITLE
tf.stack corrupts every nth image tensor on my Mac browsers but not on my Chromebooks broswer 

### ISSUE THREAD

**Issue by ZackAkil** [tensorflow/tfjs#6695]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Bug on Chrome 103 on macOS (Catalina)

Works on Chrome 103 on Chrome OS 14816

- TensorFlow.js version : @3.18.0/dist/tf.min.js

**Describe the current behavior**

tf.stack corrupts every nth image tensor on my Mac browsers but not on my Chromebooks browser 

**Describe the expected behavior**

I expect it not to corrupt those images/tensors

**Standalone code to reproduce the issue**
https://jsfiddle.net/ofn05vsx/
screen shot of console output when running on my mac (https://drive.google.com/file/d/1SSbr-Y3dqWbhEmGLJQIbg-cKAbhDl5Wu/view?usp=sharing
)
On my chrome book the checksums are all zeros

**Comment by pyu10055** [comment]
@ZackAkil tf.stack op is quite simple op, the error you have observed seems to be very weird.
We have tested on both linux and macbook (intel and m1) we could not reproduce the problem.
catalina has been several years, we could not find any device to test on.
Can you verify on other version of macos for us? thanks

**Comment by ZackAkil** [comment]
Tested on different machine running macOS Monterey and it works 👍 I'll be updated my other system and testing it again
