### ISSUE TITLE
Add support for additional random tensors

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#67]
_From @jgartman on March 28, 2018 1:17_

TensorFlow.js currently supports tensors of random samples drawn from normal, truncated normal or uniform distributions and it looks like multinomial sampling is being added back to the api soon.  Tensorflow’s random_ops supports all of these as well as the [poisson](https://www.tensorflow.org/api_docs/python/tf/random_gamma), and [gamma](https://www.tensorflow.org/api_docs/python/tf/random_poisson) distributions.  I was wondering if it would be worthwhile to support these in TensorFlow.js as well?

Thanks

_Copied from original issue: tensorflow/tfjs-core#903_

**Comment by jgartman** [comment]
I'll give this a shot

**Comment by rthadur** [comment]
This has been fixed [here](https://github.com/tensorflow/tfjs-core/pull/1365/files) , so closing this issue.Thank you
