### ISSUE TITLE
Add the ability to specify gpu_options

### ISSUE THREAD

**Issue by vmarkovtsev** [tensorflow/tfjs#671]
#### TensorFlow.js version
0.12.6

#### Browser version
Node.js 10.9

#### Describe the problem or feature request
I am using tfjs-node-gpu and it allocates the whole memory of my GPU (the default TF behavior).
I request to have an ability to specify the backend options, particularly `gpu_options.allow_growth`.

**Comment by johnnyvf24** [comment]
I have also run into this limitation and would love a solution (even if it involves messing with the bindings).

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by vmarkovtsev** [comment]
@rthadur What?

**Comment by rthadur** [comment]
@vmarkovtsev  feel free to reopen if this is still an issue .

**Comment by vmarkovtsev** [comment]
@rthadur I cannot reopen. If a maintainer closes an issue, it's original author does not have the permission. It has always worked this way for all repos on GitHub.

![image](https://user-images.githubusercontent.com/2793551/49573759-11b30180-f93f-11e8-84ae-24e0cf1f65c3.png)

Anyway, I really like how you deal with the issues :+1:

**Comment by pavelkukov** [comment]
+1 for gpu_options, gpu_memory_fraction will be very useful when training smaller models

**Comment by single9** [comment]
+1 for gpu_options, gpu_memory_fraction

**Comment by cjue** [comment]
There appears to be a workaround for setting allow_growth through an environment variable. This works for my tfjs-node-gpu project:

```
#Limit GPU memory usage with an environment variable
export TF_FORCE_GPU_ALLOW_GROWTH=true
```

**Comment by 3lk0k0** [comment]
> 

> 
> 
> There appears to be a workaround for setting allow_growth through an environment variable. This works for my tfjs-node-gpu project:
> 
> ```
> #Limit GPU memory usage with an environment variable
> export TF_FORCE_GPU_ALLOW_GROWTH=true
> ```

where need to write these command ?

**Comment by Infinitay** [comment]
> > 
> 
> > There appears to be a workaround for setting allow_growth through an environment variable. This works for my tfjs-node-gpu project:
> > ```
> > #Limit GPU memory usage with an environment variable
> > export TF_FORCE_GPU_ALLOW_GROWTH=true
> > ```
> 
> where need to write these command ?

This is how I did it:

1. Install the package `dotenv` via `npm i dotenv`
2. Create a new file `.env`, **make sure you include the `.`**, within the root of your project's workspace
3. Add `TF_FORCE_GPU_ALLOW_GROWTH=true` to the file and save it
4. Add `require('dotenv').config();` in your code, somewhere where it can be executed _first_, and before requiring `tfjs` of course

**Comment by Infinitay** [comment]
I tried adding TF_FORCE_GPU_ALLOW_GROWTH=true as an environment variable, and it seemed to have worked briefly, but upon trying to run my program once more, the error started appearing again.

cc. https://github.com/tensorflow/tfjs/issues/1469#issuecomment-586091169

**Comment by 0EB** [comment]
I still get the error "Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED" after I set "TF_FORCE_GPU_ALLOW_GROWTH=true". And still, there is no option to specify gpu_options.

**Comment by cjue** [comment]
This is a mixture of a feature request and a bug, depending on the use-case.

There is currently no workaround to specify gpu_options like `gpu_memory_fraction`, which is required for some use-cases.
