### ISSUE TITLE
New keypoints in BlazePose model

### ISSUE THREAD

**Issue by DuKeM-CSGO** [tensorflow/tfjs#6714]
**System information**
- TensorFlow.js version (you are using): `tfjs-core` & `tfjs-backend-webgl` through the HTML <script> labels.
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
According to [this article](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection#keypoint-diagram), there're a few of keypoints that can be detected by BlazePose. But more keypoints are wanted such as neck, head(NOT the current "face" keypoints), left_clavicle, right_clavicle, pelvis, and so on.

**Will this change the current api? How?**
Most of them will not. Only the format of output will be change.

**Who will benefit with this feature?**
Pose detection users

**Comment by vladmandic** [comment]
article is not updated in a while as `blazepose` has 39 [keypoints](https://github.com/vladmandic/blazepose/blob/main/src/blazeposecoords.js), not 33

but in either case, this request should be toward [mediapipe](https://github.com/google/mediapipe) team as `tfjs` implements a js module around it, not a model itself

**Comment by rthadur** [comment]
Submitted a PR to update the same.
