### ISSUE TITLE
Issues classifying images that are slighly blurred

### ISSUE THREAD

**Issue by aw1875** [tensorflow/tfjs#6724]
This may not be considered a bug as the code may be functioning properly so I wanted to drop this here.

**System information**
- Tested on Ubuntu 22.04 and Windows 10
- TFJS installed via yarn
- TFJS version 3.19.0
- I have written custom code (see snippet below)

**Describe the current behavior**
It seems like TFJS paired with the cocossd model is having issues with images that are blurred or slightly blurry.

**Describe the expected behavior**
Expecting normal image classification as per usual.

**Code Snippet**
For reference, this code is ran in a try/catch so I can manually throw an error if the image arraybuffer request fails. This code is also written in TypeScript which is why I am casting the response from `decodeImage` to a `Tensor3D` object for coco to attempt to detect.
```typescript
import tf, { Tensor3D } from '@tensorflow/tfjs-node'
import cocossd from '@tensorflow-models/coco-ssd'
import axios from 'axios'

// Get Image as arraybuffer
const blob = await axios.get(uri, { responseType: 'arraybuffer' })
    .then((res) => res.data)
    .catch((err) => { throw err; });

// Load Model
const model = await cocossd.load();

// Get Predictions
const predictions = await model.detect(tf.node.decodeImage(blob) as Tensor3D) // Leaving the default boxes and confidence
return predictions;
```

**Comment by rthadur** [comment]
It is working on blurred images as well , here is one example , can you please share the images if possible which you are using , thank you

![image](https://user-images.githubusercontent.com/43972606/183766161-5329bb3a-953d-4ba6-ac44-aeafa55fa1f6.png)

**Comment by aw1875** [comment]
@rthadur It does work, but sometimes it has issues is just what I've noticed. I don't have a photo from my testing handy currently but I can try and grab out later as an example.

**Comment by rthadur** [comment]
sure , Thank you

**Comment by aw1875** [comment]
@rthadur Here's one of the examples from my testing:
![dog](https://user-images.githubusercontent.com/4970015/183778658-ed2c64c6-93ca-4698-9eb5-cdb1c004a554.jpeg)

**Comment by ahmedsabie** [comment]
@aw1875 Our package is a re-implementation of this tensorflow [code](https://github.com/tensorflow/models/blob/master/research/object_detection/README.md), it seems to be an issue with object detection models in general (see this [paper](https://www.jasonjsy.xyz/uploads/DeblurYOLO%20final%20paper.pdf))

**Comment by aw1875** [comment]
> @aw1875 Our package is a re-implementation of this tensorflow [code](https://github.com/tensorflow/models/blob/master/research/object_detection/README.md), it seems to be an issue with object detection models in general (see this [paper](https://www.jasonjsy.xyz/uploads/DeblurYOLO%20final%20paper.pdf))

Alright so it’s just a general issue for image detection as a whole, thank you for the information!
