### ISSUE TITLE
Problem with using converted model in tensorflowjs

### ISSUE THREAD

**Issue by DHosseiny** [tensorflow/tfjs#6731]
I want to use a pre-trained model for sentimental analysis. I started from [here](https://huggingface.co/siebert/sentiment-roberta-large-english/tree/main) and I converted the Keras([tf_model.h5](https://huggingface.co/siebert/sentiment-roberta-large-english/blob/main/tf_model.h5)) model with tensorflowjs_converter to model.json and other group...shard.bin files. But in [this example](https://github.com/tensorflow/tfjs-examples/tree/master/sentiment), there is a metadata file([here](https://github.com/tensorflow/tfjs-examples/blob/master/sentiment/index.js#L48) is loaded) that I don't know how to get/create. Can you clarify what is this metadata file and how to get/create it in my example?
Thanks

**Comment by Unal-Inanli** [comment]
After researching. it seems like this metadata file is specific to this imdb data set and is not a standard thing TFJS does. If you are following the sentiment analysis example provided by TFJS, the pre-generated metadata file is provided to you by default via remotely hosted URL and is downloaded after running the "yarn train" command. In conclusion, it is up to the model provider/user to generate their own custom metadata.

If i missed some critical information regarding the topic then forgive me.

**Comment by Unal-Inanli** [comment]
perhaps this is a good place to start, [](https://towardsdatascience.com/twitter-sentiment-analysis-with-node-js-ae1ed8dd8fa7). Its using the model trained on the IMDB dataset with the metadata but its the best example i could find. It's also a good idea to check the attributes of the model you are loading to see if there are any metadata worthy attributes you can use.

**Comment by rthadur** [comment]
Thank you , you can use example for toxicity and try to include the sentimental analysis model , https://glitch.com/~tfjs-learning-toxicity .
