### ISSUE TITLE
TensorFlow model convert to tfjs, run typeError: Unknown op 'TensorListLength'. 

### ISSUE THREAD

**Issue by hwangdeyu** [tensorflow/tfjs#6748]
Model can be run in tf but failed in tfjs after using `tensorflowjs.converters`.
Using tensorflowjs to convert tf frozen graph to tfjs.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- TensorFlow.js installed from (npm or script link): npm install @tensorflow/tfjs
- TensorFlow.js version (use command below): 3.19
- Tensorflow.js Converter Version:3.19

**Repro code**:
```python
from tensorflowjs.converters import converter
import subprocess

# relative path
graph_def_path = "test_tf.pb"
tfjs_path = "test_tfjs"
input_json_path = "input.json"

output_names = "i:0,output_ta:0"
converter.convert([graph_def_path, tfjs_path, '--input_format', 'tf_frozen_model',
                               '--output_node_names', output_names])

# node run_tfjs.js test_tfjs/model.json input.json output.json
command = ['node', 'run_tfjs.js', tfjs_path + '/model.json', input_json_path, 'output.json']
result = subprocess.run(command)

'''
RuntimeError: Failed to run tfjs model: TypeError: Unknown op 'TensorListLength'. 
File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, 
or register a custom execution with tf.registerOp()
'''
```
**Related model and code**:
[test_tensorListLength.zip](https://github.com/tensorflow/tfjs/files/9314985/test.zip)

The model is basically from https://github.com/onnx/tensorflow-onnx/blob/e9b6cb4fca61c87fcdaf4e9610535910c01ea4f9/tests/test_cond.py#L122.

**Describe the current behavior**

```
Unknown op 'TensorListLength'.
```
`TensorListLength` should be supported since [`tfjs 3.16.0`](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v3.16.0)

**Describe the expected behavior**
Script can be run without any error. Thanks!

**Comment by pyu10055** [comment]
@hwangdeyu If I understand correctly, you are trying to execution the model in node.js environment?
can you share the `run_tfjs.js` file, your test.zip does not contain that part. thanks

**Comment by hwangdeyu** [comment]
> @hwangdeyu If I understand correctly, you are trying to execution the model in node.js environment? can you share the `run_tfjs.js` file, your test.zip does not contain that part. thanks

Thanks for your reply. Sorry for forgetting the `run_tfjs.js`, this file is in https://github.com/onnx/tensorflow-onnx/blob/4debef7a9adb3991071d6f79813f710bed314421/tests/run_tfjs.js#L145. The function is about running the model.

**Comment by pyu10055** [comment]
thanks for providing the file, but I think also the `input.json` and tensorflow model `test_tf.pb` files are missing.
If you can provide the whole package would be very helpful.

**Comment by hwangdeyu** [comment]
> @hwangdeyu Deyu Huang FTE thanks for providing the file, but I think also the `input.json` and tensorflow model `test_tf.pb` files are missing. If you can provide the whole package would be very helpful.

Thanks @pyu10055 , they are under the `test.zip` file but outside the `test_tfjs` file. 
![image](https://user-images.githubusercontent.com/10047193/185594562-854a7826-7f21-4301-8d3c-2db6b2244ee6.png)

**Comment by pyu10055** [comment]
Thanks @hwangdeyu , I tried your example in 3.19.0, it returns result without error.
Can you try again? might be good to remove the node_modules directory to be sure.

**Comment by hwangdeyu** [comment]
Sorry @pyu10055 , why your result was good may come from missing a right `run_tfjs.js` file. I can reproduce it with all the tfjs >= 3.16 versions. tfjs 3.19 and 3.20 screenshot as below.
![image](https://user-images.githubusercontent.com/10047193/187152872-691b7bc9-6eb2-421b-8686-53f849d16263.png)

![image](https://user-images.githubusercontent.com/10047193/187151642-2239aaaa-5ee8-4470-853c-4bfa24e2202b.png)

I create a new `testjs.zip` file in the bottom that contains all the file in the same directory. Just go to the `testjs` path and run `test.py` can easily get the reproduction. Could you repro it again or I create a new issue if it's needed. Thanks!

[testjs.zip](https://github.com/tensorflow/tfjs/files/9443567/testjs.zip)
