### ISSUE TITLE
model.save() | ValueError: Cannot find any save handlers for URL

### ISSUE THREAD

**Issue by JiahuiChen99** [tensorflow/tfjs#6749]
**System information**
- OS Platform and Distribution: Linux Debian 5.15.5-2kali2
- TensorFlow.js installed from: npm
- TensorFlow.js version: ^3.19.0
- Node version: v16.13.1
- NPM version: 8.1.2

**Describe the current behavior**
I am trying to save the trained sequential model to the file system for later use. I have the same problem as the issues described in  #4280 and #723. I have tried to any possible solution suggested in those posts but could not solve it.
I am running an Electron application, the training code is called within the main process so it's backed by NodeJS.

```js
// Traning code
// ...

// Save model code
try {
    let saveResults = await model.save('file://./myModel');
    console.log(saveResults);
}catch ( e ) {
    console.log(e);
}
```

This is the error log

```sh
ValueError: Cannot find any save handlers for URL 'file://./myModel'
    at Sequential.save (webpack:///./node_modules/@tensorflow/tfjs-layers/dist/engine/training.js?:1561:23)
```

**Describe the expected behavior**
According to [Save and load models](https://www.tensorflow.org/js/guide/save_load#native_file_system_nodejs_only), the sequential tensorflow model files - **[model].json** & **[model].weights.bin**, should be saved in the file system.

**Comment by pyu10055** [comment]
@JiahuiChen99 are you importing tfjs-node package?
can you share what is return value of following snippet:
```
console.log(tf.env().getBool('IS_NODE'))
console.log(tf.env().getBool('IS_BROWSER'))
```

**Comment by JiahuiChen99** [comment]
I'm using @tensorflow/tfjs v3.19.0 and the return values are True for node and False for browser.
tfjs-node package seems to be deprecated/archived. I've tried it too, however, it throws lots of errors about missing packages (module not found: Error: Can't resolve 'fs' in @mapbox/node-pre-gyp/lib).

**Comment by vladmandic** [comment]
> fjs-node package seems to be deprecated/archived

its always published at the same time, its not deprecated in any way. and its necessary if you want to use `file://` namespace and it does require `fs` nodejs module to do so. you need to get it working, error mesage `cant resolve fs` is bad as fs is *always* resolvable in nodejs unless you're using some packager that gets confused (e.g. webpack or whatever).

**Comment by JiahuiChen99** [comment]
@vladmandic You're right, I got confused by the archived [tfjs-node](https://github.com/tensorflow/tfjs-node) monorepo. 
But still got lots of errors building the Electron application and don't know how to solve them 😬

**Comment by vladmandic** [comment]
Electron? That's not going to work like this as you cannot easily embed tfjs-node as it requires binary bindings to tensorflow shared libraries. 

Doable with custom loaders and bundlers, etc, but quite complicated. If you go down this part, read-up on electron and how it relates to node-gyp. 

I'd rather use tfjs in browser process (so it uses webgl backend insteas of binary bindings). And then implement your io handler that provides load/save to and from filesysten (also not trivial, but still easier).

**Comment by JiahuiChen99** [comment]
I've also tried to run tfjs in the renderer process (browser), it works perfectly. However when it comes to storing the model, I need to send it to the main process via Electron IPC, but it's not a [serializable object ](https://www.electronjs.org/docs/latest/tutorial/ipc#object-serialization) 🥲

**Comment by vladmandic** [comment]
if you really need a model in main process here's an idea for a silly workaround, but i don't see downsides to it...

from browser, you can store model to indexdb directly using tfjs model.save() (it has a built-in i/o handler for `indexdb://` namespace). and then transfer blob from there yourself (from browser to nodejs).

and when you want to load a model, do it the opposite way - fetch file from nodejs, send to browser, store in indexdb and then call tfjs to load model from indexdb.

and working with indexdb is pretty easy.

fyi, here's my wrapper method for `model.load` that loads from any url and uses indexdb for local cache to avoid future downloads. plus it has some extra stuff to provide metadata info and progress monitoring: <https://github.com/vladmandic/human/blob/main/src/tfjs/load.ts>

**Comment by JiahuiChen99** [comment]
For now, I'll just make the user download (`downloads://myModel`) and load the trained model files everytime they use the app. I really hope to get **tfjs-node** working. Does anyone @pyu10055, @vladmandic, @ahmedsabie  know how to solve those problems?

**Comment by vladmandic** [comment]
>  I really hope to get tfjs-node working

i really really wouldn't go down that path  

but if you insist, check how `package.json` `build.extraFiles` works for `electronjs`  
in short, you can use it to package `node_modules/@tensorflow/tfjs-node` which will include already built binary bindings for your platform. but if you need electron app built for anything but same platform as your dev system, no chance.

i've already suggested two much cleaner ideas
- use indexdb as model store and transfer to and from indexdb using electron ipc to nodejs main process. 
- implement your i/o handler for tfjs so `.save()` and `.load()` methods will actually use electron ipc to your nodejs main process

**Comment by JiahuiChen99** [comment]
@vladmandic I'll try all different ways you've suggested. Thank you so much for your help and suggestions! :+1:

**Comment by bitdom8** [comment]
not works
