### ISSUE TITLE
WASM backend fails on recent versions of Edge/Chromimum

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6752]
# WASM backend fails on recent versions of Edge/Chromimum  

Tested with
- Edge/Chromium 106.0.1349.0 (Canary)
- Edge/Chromium 104.0.1293.54 (Release) <- *this is a default browser on Windows 11 installs*

I don't know when issue first occured (it used to work), but now it fails on both release and canary versions  

No issues with **Chrome 106.0.5241.2** or **Firefox 103.0.2**

Actual issue is when attempting to set backend using `tf.setBackend('wasm')` it silently fails and uses first available backend.

## Investigation

Attempting to use `await tf.env().getAsync('WASM_HAS_MULTITHREAD_SUPPORT');`  
Returns `false` on Edge, but returns `true` on Chrome!

Attempting to use `await tf.env().getAsync('WASM_HAS_SIMD_SUPPORT');`  
Results in exception error on Edge, but returns `true` on Chrome!

```text
Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at Object.evaluationFn (tfjs.esm.js:66241:27)
    at Environment.evaluateFlag (tfjs.esm.js:5450:40)
    at Environment.getAsync (tfjs.esm.js:5411:39)
```

And since `tfjs-backend-wasm` uses both flags on its init, it fails

Actual evalulation functions in `src/tfjs-backend-wasm/src/flags_wasm.ts` have try/catch block around `WASM_HAS_SIMD_SUPPORT`, but no exception handling around `WASM_HAS_MULTITHREAD_SUPPORT` - first thing is to add such a block  

Proposed PR is in #6753

This results in at least sane behavior - TFJS reports warning message `Aborted(no native wasm support detected)` and continues working using next available backend  

## Actual root cause

There is a workaround - disable `Use enhanced security for this site` in Edge,  
Then both flags return true and WASM backend works just fine  

Per [this Microsoft article](https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d), this feature
1. Disables just-in-time (JIT) JavaScript compilation
2. Enables OS protections such as Hardware-enforced Stack Protection and Arbitrary Code Guard (ACG). 

And **Enhanced Security** feature is now enabled by default for any newly visited sites,  
but allows full functionality if site is re-visited multiple times (don't know exactly how many visits are needed)  

Bigger issue is that Microsoft pretty much disabled `WebAssembly` namespace if enhanced security is enabled - thats a really bad decision from MS, but not much I can do about that  

**I suggest that TFJS team opens a dialog with Edge team as this has pretty big consequences**  

## Environment

- TFJS 3.19.0
- Windows 11 (22H2 build 22622.575) (this is fully-updated Beta release, not RTM or Canary)

**Comment by vladmandic** [comment]
any updates? this is a week old without anyone taking a look and the same with the PR #6753 that goes with it.

**Comment by pyu10055** [comment]
@vladmandic We have reached out to the chrome WASM team trying to find out more about the best way to raise this issue with Edge team. cc @tlively

**Comment by vladmandic** [comment]
In case you're wondering on impact, even Microsoft's own VSCode for Web fails...

<img width="776" alt="image" src="https://user-images.githubusercontent.com/57876960/185972838-4d1988c1-195e-4242-a541-0119259f7f5b.png">

**Comment by vladmandic** [comment]
closing the issue as pr that detects wasm support has been merged. bigger issue on will edge keep blocking wasm on unverified sites remains, but that is beyond the scope of this issue.
