### ISSUE TITLE
Why mediapipe-gpu so much faster than tfjs ？

### ISSUE THREAD

**Issue by yohacai** [tensorflow/tfjs#6756]
Why mediapipe-gpu so much faster than tfjs ？

**Comment by vladmandic** [comment]
because it directly implements custom gpu methods for its internal functions, not using any abstraction layers or frameworks  
see <https://github.com/google/mediapipe/blob/master/docs/framework_concepts/gpu.md> for details

**Comment by yohacai** [comment]
> because it directly implements custom gpu methods for its internal functions, not using any abstraction layers or frameworks see https://github.com/google/mediapipe/blob/master/docs/framework_concepts/gpu.md for details

thx~
