### ISSUE TITLE
Add support for the Keras JSON object included in the updated SavedModel

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#676]
#### Describe the problem or feature request

tf.keras SavedModel now optionally includes the JSON Keras model representation [[as of this commit](https://github.com/tensorflow/tensorflow/commit/cda5ea80b86909fd20ff8a0f5ba914c5c03b876f)].  When converting from this type of SavedModel, it should be possible to access the Keras JSON so as to keep the modular structure.

**Comment by pyu10055** [comment]
This is supported with our tfjs converter for converting from saved model to layers model.
