### ISSUE TITLE
Missed Subtract function on exports_layers.js file line 19.

### ISSUE THREAD

**Issue by eltonl2020** [tensorflow/tfjs#6766]
Missed subtract function in all versions, cause of some NN model couldn't working.

**Comment by pyu10055** [comment]
Hi @eltonl2020, can you provide more details about the missing subtract function? Are you saying the Keras subtract layer is missing or there are existing functions we did not export?
If you can provide a link to the functions you need would be helpful. thanks.

**Comment by eltonl2020** [comment]
I have fixed ***@***.***/tfjs-layers/dist/layers/merge.js
 file by adding these lines, so I build tensorflowjs by myself

//========================================export class Sub extends Merge {    constructor(args) {        super(args);    }    mergeFunction(inputs) {        return tidy(() => {            let output = inputs[0].clone();            for (let i = 1; i < inputs.length; ++i) {                output = tfc.sub(output, inputs[i]);            }            return output;        });    }}Sub.className = 'Subtract';serialization.registerClass(Sub);export function sub(config) {    if (Array.isArray(config)) {        const layer = new Sub({});        return layer.apply(config);    }    else {        return new Sub(config);    }}//========================================





    On Monday, August 22, 2022 at 08:52:01 AM PDT, Ping Yu ***@***.***> wrote:  
 
 


Hi @eltonl2020, can you provide more details about the missing subtract function? Are you saying the Keras subtract layer is missing or there are existing functions we did not export?
If you can provide a link to the functions you need would be helpful. thanks.

**Comment by pyu10055** [comment]
@eltonl2020 thanks for trying it out yourself, it would be great that you can contribute your changes to TFJS so others can benefit.
Please feel free to create a PR. thanks
