### ISSUE TITLE
Error: Argument 'x' passed to 'conv2d' must be float32 tensor, but got int32 tensor, even if the input tensor is forced to tf.float32

### ISSUE THREAD

**Issue by andreariba** [tensorflow/tfjs#6773]
TensorFlow.js version
3.19.0

Browser version
Chrome Version 104.0.5112.79 (Official Build) (64-bit)

### Summary
I have a problem running predictions with a model developed and trained using Python and TensorFlow Keras into TensorFlow.js.

_Procedure_
I developed and trained a TF model with Python and then converted this Keras model into a TensorFlow.js model using:
`$ tensorflowjs_converter --input_format=tf_saved_model saved_model/alpha_zero_model/ models_js/alpha_zero_model`

I attached the folder of the model
[alpha_zero_model.zip](https://github.com/tensorflow/tfjs/files/9388301/alpha_zero_model.zip)

The loading of the model is fine
`tf_alpha_zero_model = await tf.loadGraphModel('http://localhost:8080/tf_models/TTT_models_js/alpha_zero_model/model.json')`
but ...

**Problem**
I get a problem when I try to predict with a test input using the following Javascript code:
`let test_output = await tf_alpha_zero_model.predict(tf.tensor2d([0.0, -1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1, 9], 'float32'))`
The error message is:
Uncaught (in promise) Error: Argument 'x' passed to 'conv2d' must be float32 tensor, but got int32 tensor

This is a bit puzzling since the definition of the input to the Conv2D layer is below, and as you can see it is float32 tensor
```
x = tf.cast(tf.one_hot(tf.cast(inputs + 1, tf.int32), 3), tf.float32)
x = tf.reshape(x, (-1, 3, 3, 3))
x = tf.keras.layers.Conv2D(
        filters=3**5, kernel_size=(3, 3), kernel_regularizer=kernel_regularizer
    )(x)
```

Details
My environment is as follows:
Ubuntu 22.04.1 LTS
Python 3.8.5
tensorflow 2.7.0

**Comment by andreariba** [comment]
anybody could give a feedback on this error? I'm not sure if it's a bug or some feature not implemented in tfjs

**Comment by pyu10055** [comment]
@andreariba TFJS right now only supports int32 output for onehot op, two PRs I submitted earlier with address this issue.
