### ISSUE TITLE
Bug in Sampler3D with shape uniforms enabled

### ISSUE THREAD

**Issue by shanumantesc** [tensorflow/tfjs#6787]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes, test case shared below
- Mobile device : Pixel 6 Pro (Reproduces on any android device with Mali GPU that I tried)
- TensorFlow.js installed from (npm or script link): 3.19.0
- Browser version: Chrome 103.0.5060.53

**Describe the current behavior**
https://github.com/tensorflow/tfjs/blob/256e59a/tfjs-backend-webgl/src/shader_compiler.ts#L1362 

this looks like a bug that we are using pre-calculated stride values instead of the ones computed by the shader. It leads to incorrect outputs in one of our networks for the pack program.

**Describe the expected behavior**
The code should be `int index = row * stride0 + col * stride1 + depth + ${offset};` instead of using pre-calculated stride0/stride1

**Comment by shanumantesc** [comment]
cc @Linchenn

**Comment by Linchenn** [comment]
@shanumantesc Thank you for finding it out! Yes, this should not be pre-calculated.

If convenient, could you locate which op produces wrong values at the beginning?

**Comment by shanumantesc** [comment]
@Linchenn it was caused by `PackProgram` - I haven't saved all the debug information unfortunately since the fix seemed obvious :)

**Comment by Linchenn** [comment]
@shanumantesc I just merged the fix for this ISSUE. If you want, you could local build it and try now.

**Comment by shanumantesc** [comment]
Yep, it works locally for us. Thanks!
