### ISSUE TITLE
tfjs-backend-webgpu does not have release cadence

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6791]
when can we expect `tfjs-backend-webgpu` to get into release lockstep with the rest of tfjs?  

for example, **tfjs 3.20.0** was just released and it contains more **webgpu** changes than the rest of **tfjs** combined,  
but yet - updated package for `tfjs-backend-webgpu` is not released

**Comment by pyu10055** [comment]
@vladmandic WebGPU requires more manually verification, and our currently gcloud CI infrastructure cannot support it directly.
The plan is to release WebGPU backend with the same cadence as other packages.
We are facing some issues on WebGPU for 3.20.0, that is why it is delayed.
