### ISSUE TITLE
Can't run tfjs Selfie Segmentation because of TypeError: (0, t.tidy) is not a function

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [tensorflow/tfjs#6795]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.5.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.20.0
- Browser version: Chromium v105.0.5195.19 (Developer Build) (x86_64)
- Tensorflow.js Converter Version: 3.20

**Describe the current behavior**
I can load the tfjs version of the Selfie Segmentation model (when I log the object, it shows plenty of information and none are suspicious), but I can't run the `segmentPeople` method. I get the following stack trace:
```
Uncaught (in promise) TypeError: (0 , t.tidy) is not a function
    at t.<anonymous> (body-segmentation.esm.js:17:40669)
    at body-segmentation.esm.js:17:2319
    at Object.next (body-segmentation.esm.js:17:1635)
    at body-segmentation.esm.js:17:1361
    at new Promise (<anonymous>)
    at D (body-segmentation.esm.js:17:1106)
    at t.segmentPeople (body-segmentation.esm.js:17:40427)
    at _callee$ (tfjs_client.js:21:36)
    at tryCatch (tfjs_client.js:2:1)
    at Generator._invoke (tfjs_client.js:2:1)
```

**Describe the expected behavior**
I was expecting the `segmentPeople` method to return a segmentation list.

**Standalone code to reproduce the issue**
I tried creating a codepen demo, but I'm unable to import any tfjs library.
Here is my code in which I get the error.

tfjs_client.js
```javascript
import '@tensorflow/tfjs-core';
import '@tensorflow/tfjs-backend-webgl';
import * as bodySegmentation from '@tensorflow-models/body-segmentation';
import '@tensorflow/tfjs-converter';

// This is a workaround to avoid the following error:
// Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules
(async () => {
    const config = {
        runtime: 'tfjs',
        modelType: 'landscape',
    };
    const mpss = bodySegmentation.SupportedModels.MediaPipeSelfieSegmentation;
    const model = await bodySegmentation.createSegmenter(mpss, config);
    console.log('Selfie Segmentation initialized');

    // The canvas contains a 256x144 image
    const canvas = document.getElementById('input');
    const people = await model.segmentPeople(canvas);  // code crashes here
    const maskImageData = await people[0].mask.toImageData();
    console.log(maskImageData);
});
```

client.html
```html
<!DOCTYPE html>
<html>
<body>
    <script src="./tfjs_client.js"></script>
    <div id="progress"></div>
    <canvas id="input"></canvas>
    <canvas id="output"></canvas>
</body>
</html>
```

And here are some of my dependencies in my package.json file.
```
"@mediapipe/selfie_segmentation": "^0.1.1632777926",
"@tensorflow-models/body-segmentation": "1.0.1",
"@tensorflow/tfjs-backend-webgl": "3.20.0",
"@tensorflow/tfjs-converter": "3.20.0",
"@tensorflow/tfjs-core": "3.20.0",
```

My project is a node server that spawns a Chromium window in which the html file is loaded up.

**Comment by rthadur** [comment]
Here is the codepen example  https://codepen.io/dhlanm/pen/bGYqEqr , this is working as expected can you please check and also you check here as well https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html

**Comment by RaphaelRoyerRivard** [comment]
For some reason that makes absolutely no sense to me, after adding
```
tf.setBackend('webgl');
await tf.ready();
```
before creating the segmenter and importing the required libraries via `script` tags instead of using the import statements in the script fixes the issue.
