### ISSUE TITLE
how to forward op execution to a different backend

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6800]
*this is not an issue or a feature request, but more of a question - but since its about tfjs, its not really fit for forums*

basically, how to forward kernel op execution to a different backend?  
or use implementation from a different backend to register op in  current backend.

example is `rotateWithOffset` kernel op which is implemented in **CPU**, **WebGL** and **WASM**, but not **NodeJS**.  

Since in my case, op execution performance is non-critical it would suffice to register op in `tensorflow` backend and use `cpu` implementation to actually execute it.

I've looked around **WebGL** handling of `shouldExecuteOnCPU` which shows how its possible in general, but that approach would require modifying tfjs sources as each op implementation needs to be statically imported.

also, i know about `registerKernel` to do custom implementation, but that is not the goal here - goal is to forward execution to a kernel implemented in different backend (`cpu` only to be precise as forwarding between tensors that are on `gpu` would be messy at best).

**Comment by pyu10055** [comment]
technically, the CPU forwarding is not running the op on the CPU backend (no backend switching happened there, only shared the same CPU implementation code).

You can try the [registerOp](https://js.tensorflow.org/api/latest/#registerOp) api, this allow you to implement a graph model op and within the op definition you can use 
```
const backend = tf.getBackened();
tf.setBackend('cpu') ;
...
tf.setBackend(backend);
```

**Comment by vladmandic** [comment]
thanks - i'm closing the issue
