### ISSUE TITLE
Purpose for TensorName validation regex

### ISSUE THREAD

**Issue by Dorfdude8** [tensorflow/tfjs#6804]
https://github.com/tensorflow/tfjs/blob/d86a6dba7486ec12c336b5ad527ddcc5d8069f86/tfjs-layers/src/common.ts#L111-L120

Hi, I would like to know what is the reason(s) for restricting tensor names with a specific regex, as linked above. My guess is that it is a safeguard to make sure that the model can be successfully exported to JSON.

What are the consequences of modifying it/removing it completely?

**Comment by lina128** [comment]
Hi @Dorfdude8, could be related to keras tensor name restriction. Do you have a use case where you need to modify or remove it completely?

**Comment by gaikwadrahul8** [comment]
Hi, @Dorfdude8 

Apologize for the delayed response and if I'm not wrong the purpose for TensorName validation regex is a helpful way to improve the readability and maintainability of `TensorFlow.js `code. By preventing users from creating tensor names that could be interpreted as JavaScript keywords or reserved words, the regex helps to ensure that TensorFlow.js code is more consistent and easier to understand.

If you pass a tensor name that does not match the regex, an error will be thrown. if I'm not wrong 

I hope it will help you to understand the purpose for TensorName validation regex. Thank you!
