### ISSUE TITLE
tensorflowjs_converter does not output GraphModel on M1 Mac

### ISSUE THREAD

**Issue by KawabataLemon** [tensorflow/tfjs#6845]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): ```pip install tensorflowjs_wizard```
- TensorFlow.js version (use command below):
- Browser version:N/A
- Tensorflow.js Converter Version: 
```
tensorflowjs_converter -v

tensorflowjs 3.20.0

Dependency versions:
  keras 2.9.0
  tensorflow 2.9.1
```

**Describe the current behavior**
Throw bus error when output GraphModel via tensorflowjs_converter.

**Describe the expected behavior**
Should output graphmodel properly.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

input following command via tensorflowjs_wizard.
(*please replace "./mnist.h5" to your origin model file.)

Layer Model exports properly, but Graph Model  output always failed.

Is there any solution to avoid this error?

```
Welcome to TensorFlow.js Converter.
? Please provide the path of model file or the directory that contains model files.
If you are converting TFHub module please provide the URL.  ./mnist.h5
? What is your input model format? (auto-detected format is marked with *)  Keras (HDF5) *
? What is your output format?  Tensorflow.js Graph Model
? Do you want to compress the model? (this will decrease the model precision.)  No compression (Higher accuracy)
? Please enter shard size (in bytes) of the weight files?  4194304
? Do you want to provide metadata?
Provide your own metadata in the form:
metadata_key:path/metadata.json
Separate multiple metadata by comma.
? Which directory do you want to save the converted model in?  t
converter command generated:
tensorflowjs_converter --input_format=keras --metadata= --output_format=tfjs_graph_model --weight_shard_size_bytes=4194304 ./mnist.h5 t



Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

zsh: bus error  tensorflowjs_wizard
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
tensorflow-metal              0.6.0
tensorflow-macos              2.8.0
tensorflow                    2.9.1
python                           3.9.10
```

M1 Pro Macbook.

**Comment by Linchenn** [comment]
@mattsoulanille Hi Matt, the `bus error` only appears for graph model, while not for layers model. I am not sure if this error is about loading the graph model. Do you have any ideas on this?

**Comment by mattsoulanille** [comment]
@Linchenn I'm not sure what's causing this. We should try to reproduce it on another M1 mac. Maybe @lina128 can try reproducing it since she has an M1. @KawabataLemon are you able to share the model file?

**Comment by KawabataLemon** [comment]
[mnist.h5.zip](https://github.com/tensorflow/tfjs/files/9630233/mnist.h5.zip)
@mattsoulanille Here is the model file.

**Comment by pyu10055** [comment]
@KawabataLemon If I understand you correctly, you are trying to convert keras H5 file to tfjs graph model, unfortunately that is not supported. H5 file can only be converter to tfjs layers model. tfjs graph model will need TensorFlow saved model as input.

**Comment by pyu10055** [comment]
@KawabataLemon I tried your model on an M1 machine, I had some trouble get tensorflow pip installed, but here are my steps to convert your model successfully:
```sh
pip install tensorflow-macos
pip install protobuf==3.19.4
pip install tensorflow_hub --no-dep
pip install flax
pip install tensorflowjs --no-deps
tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model mnist.h5 ./mnist/
```

Please let me know how you have installed tensorflow and if the above steps work for you.

**Comment by KawabataLemon** [comment]
thank you for helping. it worked.
