### ISSUE TITLE
Polynomial regression : parameter isn't updating

### ISSUE THREAD

**Issue by johhnry** [tensorflow/tfjs#685]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.5
#### Browser version
Google Chrome v68.0.3440.106
#### Describe the problem or feature request
Hey guys,

I am doing a really simple polynomial regression (inspired from this tutorial : https://www.youtube.com/watch?v=tIXDik5SGsI) and I have this problem : the c coefficient is not updated at the end of the training. I am using an adam optimizer and I really don't know what's going on.

#### Code to reproduce the bug / link to feature request
Here is my code : 

```js
let xcoords = [] , ycoords = [];
const learningRate = 0.5;
const optimizer = tf.train.adam(learningRate);

//Tensors declaration
let a = tf.variable(tf.scalar(Math.random()));
let b = tf.variable(tf.scalar(Math.random()));
let c = tf.variable(tf.scalar(Math.random()));

//Coordinates initialization
for(let i=0;i<10;i++){
	xcoords.push(Math.random());
	ycoords.push(Math.random());
}

//Optimize the parameters
a.print();
b.print();
c.print();

for(let iteration = 0;iteration<100;iteration++){
	tf.tidy(() => {
		 if (xcoords.length > 0) optimizer.minimize(() => loss(predict(xcoords), ycoords));
	});
}
console.log("TRAINING...");
a.print();
b.print();
c.print();

function predict(xs) {
    return tf.add(tf.tensor1d(xs).square().mul(a), tf.tensor1d(xs).mul(b), c);
}

function loss(pred, labels) {
    return pred.sub(tf.tensor1d(labels)).square().mean();
}
```

![image](https://user-images.githubusercontent.com/35373357/45173929-d3a42580-b209-11e8-9fe9-03226e9bb4da.png)

Thanks for helping me

Joseph

**Comment by tafsiri** [comment]
@johhnry I believe the issue is that in your `predict` function you are passing three arguments to `tf.add` when it expects only two. The third argument, c is ignored. 

Try

```
tf.add(tf.tensor1d(xs).square().mul(a), tf.tensor1d(xs).mul(b)).add(c);
```

**Comment by johhnry** [comment]
@tafsiri Thank you so much for your answer.
What a bad mistake, I'll be more careful about this in the future.

Have a nice day !
