### ISSUE TITLE
tfjs-node decode-jpeg memory leak

### ISSUE THREAD

**Issue by vh13294** [tensorflow/tfjs#6854]
**System information**
- Have I written custom code: NO
- OS Platform and Distribution: Intel Mac 2020 running macOS 12.6
- @tensorflow/tfjs-node installed from (npm or script link): npm i @tensorflow/tfjs-node
- @tensorflow/tfjs-node version (use command below): 3.20.0
- Node version v16.14.0
- NPM version v8.3.1

**Describe the current behavior**
```typescript
import * as tf from '@tensorflow/tfjs-node';
const tensor = tf.node.decodeJpeg(imageBuffer);
```

the decodeJpeg function cause memory leak.

**Standalone code to reproduce the issue**
https://github.com/vh13294/tfjs-node-decode-jpeg-leak

**Comment by mattsoulanille** [comment]
You can also wrap your synchronous allocations in [`tf.tidy(() => {/* allocations go here */});`](https://js.tensorflow.org/api/latest/#tidy) if you have a lot of intermediate tensors from pre / post processing. [Here's a random example from our handpose model](https://github.com/tensorflow/tfjs-models/blob/b5d49c0f5ba2057cc29b40317126c5f182495f96/handpose/src/hand.ts#L53-L68).

**Comment by vh13294** [comment]
Okay I got it fixed via tensor.dispose().
I thought node gc suppose to do it for me. : /

Thanks guys.

**Comment by mattsoulanille** [comment]
@vh13294 node gc will collect normal objects, but Tensors often store their data where it can't be garbage collected. For example, they can be stored in a WebGL texture, as a C++ object in WASM, or as a native TF Tensor in the node backend (the node addon case might actually be possible to GC, but I'm not sure). We're of course open to ideas on how to add automatic GC as long as it wouldn't hurt performance.
