### ISSUE TITLE
Support dump mode

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#6860]
Dump mode enchances model debug mode in three ways:

1. Support whole model dump in different dumpLevel: 0, dump close diffs. 1, dump any diffs. 2, dump all.
2. Support ops dump.
3. Support dumpLength: -1 means all.

**Comment by cesarvspr** [comment]
I think @axinging already worked on this issue, right?

**Comment by axinging** [comment]
> I think @axinging already worked on this issue, right?
@cesarvspr ,  Yes, the WIP pr: https://github.com/tensorflow/tfjs/pull/6850

**Comment by rthadur** [comment]
Related PR https://github.com/tensorflow/tfjs/pull/6850 has been merged , closing this issue.
