### ISSUE TITLE
Dump mode doesn't support tensor with type conversion

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#6861]
This is followup for https://github.com/tensorflow/tfjs/pull/6850.

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and I see this PR [#6850](https://github.com/tensorflow/tfjs/pull/6850) got merged to take care of this issue so could you please close this issue now if that PR has taken care of this issue. Thank you!
