### ISSUE TITLE
BodyPix demo broken

### ISSUE THREAD

**Issue by afeld** [tensorflow/tfjs#6886]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow.js installed from (npm or script link): NPM
- TensorFlow.js version (use command below): unknown
- Browser version: Chrome 105.0.5195.125 (Official Build) (arm64)
- Tensorflow.js Converter Version: unknown

**Describe the current behavior**

1.  Visit [BodyPix demo](https://storage.googleapis.com/tfjs-models/demos/body-segmentation/index.html?model=body_pix)
2. See alert saying `body_pix`
3. See nothing displayed (besides controls), and an error in the console saying:

```
dat.gui.min.js:13 Uncaught (in promise) Error: Object "[object Object]" has no property "model"
    at f (dat.gui.min.js:13:5450)
    at e.add (dat.gui.min.js:13:45174)
    at setupDatGui (src.a2b27638.js:105220:39)
    at app (src.a2b27638.js:105907:39)
```

**Describe the expected behavior**

Showing the body segmentation.

**Standalone code to reproduce the issue**

n/a

**Other info / logs** 

n/a

**Comment by rthadur** [comment]
@pyu10055 bodypix is [deprecated](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/README.md) , do we still want to support this ?

**Comment by afeld** [comment]
Heh, it was a bit unclear what is being maintained vs. not: [The `body-pix` package](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/README.md) states it's deprecated, and to see the `pose-detection` package instead, even though that doesn't seem to have a model that's comparable. [`body-segmentation`](https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation) refernces BodyPix, but doesn't say anything about it being deprecated.

**Comment by rthadur** [comment]
Correct deprecation message has beeb updated [here](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/README.md). Sorry for the confusion. Thank you!

**Comment by afeld** [comment]
> bodypix is deprecated

Just to confirm: this was referring to the package rather the model, correct?
