### ISSUE TITLE
Requested texture size 4800*4736 greater than webGL maximum on this browser 4096 * 4096

### ISSUE THREAD

**Issue by narensprinter** [tensorflow/tfjs#689]
I'm getting this error on "**Requested texture size 4800*4736 greater than webGL maximum on this browser 4096 * 4096**" while checking tfjs on mobile browser

**Comment by DavidGOrtega** [comment]
WoW, Im pretty interested on this, since my laptop can't handle images above 256x256 with vgg16. And sometimes part if the output is just missed probably due to memory. What kind of net are you running over that huge image?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ClemHlrdt** [comment]
Hey. I have a similar issue. I am trying to load my model but I get the following error:

Error: Requested texture size [2795x2795] greater than WebGL maximum on this browser / GPU [2048x2048].

This error appears in Firefox console but not on Chrome for some reason. Any idea what could cause the issue ? 

My model is Embedding layer => Convolution => MaxPooling => Dense layer.
Video card: GTX 1060 3Go

**Comment by ClemHlrdt** [comment]
The problem seems to be linked to the regular edition of Firefox.
I tried on my model on Edge, Chrome and Safari and it works. The error comes from WebGL .

On Chrome, Safari and Firefox Dev Edition: 
```
var canvas = document.createElement('canvas');
var gl = canvas.getContext('webgl');
gl.getParameter(gl.MAX_TEXTURE_SIZE); // 16 384
```

On Firefox: 
```
var canvas = document.createElement('canvas');
var gl = canvas.getContext('webgl');
gl.getParameter(gl.MAX_TEXTURE_SIZE); // 2048
```

**Comment by nsthorat** [comment]
Unfortunately there's not really much we can do, this is a fundamental limitation of Firefox. We do our best to reshape memory so that one dimension doesn't exceed the dimensions but if a single texture can't hold all the memory of the Tensor we're kind of out of luck :/

**Comment by rthadur** [comment]
closing this issue based on latest comments , thank you.
