### ISSUE TITLE
Bazel build failed on Windows

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#6914]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: x
- TensorFlow.js installed from (npm or script link): x
- TensorFlow.js version: x
- CUDA/cuDNN version: x

**Describe the problem**
Bazel build failed

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`cd tfjs-backend-webgpu && yarn build`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
haoyunfe@bjwdeotc009 MSYS /d/workspace/project/tfjs/tfjs-backend-webgpu (master)
$ yarn build
yarn run v1.22.5
$ yarn --cwd .. bazel build tfjs-backend-webgpu:tfjs-backend-webgpu_pkg
$ D:\workspace\project\tfjs\node_modules\.bin\bazel build tfjs-backend-webgpu:tfjs-backend-webgpu_pkg
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tfjs-backend-webgpu:tfjs-backend-webgpu_pkg (262 packages loaded, 6149 targets configured).
INFO: Found 1 target...
ERROR: 'sandboxed' was requested for default strategies but no strategy with that identifier was registered. Valid values are: [standalone, remote, worker, local]
```
Due to https://github.com/bazelbuild/bazel/issues/5136, sandboxing was not supported on Windows?

**Comment by qjia7** [comment]
@mattsoulanille Can you help take a look this issue? It's kind of blocked our development on windows.
