### ISSUE TITLE
Crisp Edge detection. 

### ISSUE THREAD

**Issue by sushilronghe99** [tensorflow/tfjs#6934]
Trying to detect a person from a single image and removing the background. Please see attached screenshots. When the threshold has increased the face (especially the ears ) pixels are also eaten up by the mask. 

**BodyPix Setting**
     architecture: 'ResNet50',
    outputStride: 16,
    quantBytes: 4
**Segmentation setting**
internalResolution: "full",
segmentationThreshold: dynamic, // 0.5, 0.7, 0.8,0.9
nmsRadius: 1

Question - How can we achieve near-perfect body detection around edges?  Is there any technique that should be applied or this the best that tfjs can do?
<img width="1664" alt="Screenshot 2022-10-13 at 6 38 56 PM" src="https://user-images.githubusercontent.com/104120825/195611097-25909159-2915-4b98-9e84-9823fca4a311.png">
<img width="1500" alt="Screenshot 2022-10-13 at 6 48 50 PM" src="https://user-images.githubusercontent.com/104120825/195611130-ad6b8bfc-43fc-4d6b-ae8e-faf40ab8f13b.png">

Sorry if does not fit into the bug definition, but I could not find anything on the internet that discuss this.

**Comment by vladmandic** [comment]
**bodypix** architecture is quite old and not really precise. google **selfie** and **meet** models are simpler and better, but best one i've found that works in real-time is **rvm** - my `tfjs` port is at <https://github.com/vladmandic/segmentation> (live demo is also included)

**Comment by rthadur** [comment]
@sushilronghe99 are you using https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation ?

**Comment by sushilronghe99** [comment]
I believe, everything is latest - here is the setup (I tried both wasm and webgl just to verify if there is any quality difference ) 
"@tensorflow-models/body-pix": "^2.2.0",
    "@tensorflow/tfjs": "^3.21.0",
    "@tensorflow/tfjs-backend-wasm": "^3.21.0",
    "@tensorflow/tfjs-backend-webgl": "^3.21.0",
    "@tensorflow/tfjs-converter": "^3.21.0",
    "@tensorflow/tfjs-core": "^3.21.0",

@vladmandic  I found openCV output with u2net model quite impressive but it would require a backend, so any possibility to improve the quality with tjfs would be worth a shot.

**Comment by rthadur** [comment]
We do not support body-pix anymore , please use body-segmentation model . Thank you !
