### ISSUE TITLE
invalid size error 169220804 when creating tensor from nested array

### ISSUE THREAD

**Issue by fmorgens** [tensorflow/tfjs#6956]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
Yes see code to reproduce
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Mint 20.3
- TensorFlow.js installed from (npm or script link):
npm package 
- TensorFlow.js version (use command below):
4.0.0

**Describe the current behavior**
When creating a tensor with more that ~112805641 total values from a nested array I get the following error:
```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x7ffc51630580
 1: 0xb76401  [node]
 2: 0x1c09824 V8_Fatal(char const*, ...) [node]
 3: 0xe7f0e8  [node]
 4: 0x102c992  [node]
 5: 0x102d2d6  [node]
 6: 0x11ed9d3 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x15f2099  [node]
Trace/breakpoint trap (core dumped)
```
This happens for example when creating a tensor with shape of [10622,10622] from nested array
But not with shape of [10621,10621]
I also tried with 3d tensor where it failed at [484,484,484]
Anything larger of course also doesn't work

Creating a tensor with tf.zeros or tf.ones with the same size or larger works as expected

**Describe the expected behavior**
return tensor of expected size containing the data from nested array without crashing

**Standalone code to reproduce the issue**
```
import tf from "@tensorflow/tfjs-node";

let size = 10622;

let data = [];
for(let i = 0; i < size;i++){
let array = new Array(size).fill(0);
data.push(array);
}

let test = tf.tensor(data);
test.print();

```

**Comment by ahmedsabie** [comment]
This is a javascript array size limit. When you call tensor, your 2D array is copied into a new 1D array so that's why you run out of memory. I believe node has some flags that let you change memory size if you need to  create such a large array.

**Comment by VicEsquivel** [comment]
Thanks for the reply @fmorgens . Yes, yesterday I ended up doing something like that. I was facing the problem because I was trying to initialize a tensor after a dataset was already been pre-processed as a JS array. However, since it was crashing in the call to `tf.tensor(2dLargeArray)` I decided to do the pre-processing of the data starting using tensors since the very beginning, when they were not large already. Replacing some `array.push()` with `tf.concat()`, and all within a `tf.tidy()`. In this way, I managed to make it work, even having larger arrays... 

I must say, that even if this is somehow a JS limit error, the fact that tf.tensor transforms the 2d array into a 1d array I dont think is the best way to go, understanding that the cause of this error is that exact thing... Maybe they could do it in a different way internally to avoid this issue.

**Comment by fmorgens** [comment]
@VicEsquivel 
> the fact that tf.tensor transforms the 2d array into a 1d array I dont think is the best way to go
This might be because the function can also reshape your data into a multi dimensional tensor for you. If you might have to reshape it anyway the easiest way to implement this is flatten it to 1d regardless of input shape and then go to the target shape.
For large arrays that would crash in 1d maybe a flag to skip this reshaping process would be useful. 

@tensorflowbutler @ahmedsabie Maybe it would be useful to open this issue again

**Comment by VicEsquivel** [comment]
@fmorgens I dont think they will open the issue back again... In any case I will paste here a piece of code I did, using the exact same code from the start of this thread. It patches the whole thing up. With it, you are able to create really big tensors from very large 2D arrays... It works best when the `row` variable is not a row itself, but an Uint8Array being read chunk by chunk from a file, in this way, it can process 1D arrays to whatever shape you want... I know, and I am 100% sure it can be optimized somehow, but I will leave it here, if someone wants to do it.

```javascript
const tf = require('@tensorflow/tfjs-node-gpu');

function createTensor(data, shape, type) {
  let firstTime = true;
  let buffer = tf.buffer(shape, type);
  let iterators = new Array(shape.length).fill(0);
  let iteratorsChanged = new Array(shape.length).fill(false);

  data.forEach((row) => {
    let uint8Array = new Uint8Array(row);
    let decimalArray = Array.from(uint8Array);
    decimalArray.forEach(value => {
      if ((iterators[0]+1) >= shape[shape.length-1]) {
        iterators[0] = 0;
        iteratorsChanged[0] = true;
      }
      else {
        if(!firstTime) {
          iterators[0] = iterators[0] + 1;
          iteratorsChanged[0] = false;
        }
        firstTime = false;
      }
      for(let i=1; i<iterators.length; i++) {
        if(iteratorsChanged[i-1]) {
          if((iterators[i]+1) >= shape[shape.length-1-i]) {
            iterators[i] = 0;
            iteratorsChanged[i] = true;
          }
          else {
            iterators[i] = iterators[i]+1;
            iteratorsChanged[i] = false;
          }
        }
        else {
          iterators[i] = iterators[i];
          iteratorsChanged[i] = false;
        }
      }
      let iteratorsArray = [];
      for(let i=iterators.length-1; i>=0; i--) {
        iteratorsArray.push(iterators[i]);
      }
      buffer.set(value, ...iteratorsArray);
    });
  });
  return buffer.toTensor();
}


function main() {
  let size = 10622;

  let data = [];
  for(let i = 0; i < size;i++){
    let array = new Array(size).fill(0);
    data.push(array);
  }

  let test = createTensor(data, [size, size], 'int32');
  test.print();
  console.log('Voila...');
}

main();
```
