### ISSUE TITLE
tfjs-backend-cpu: Test correctness failed when running e2e DeepLabV3 model on webgl and webgpu backends

### ISSUE THREAD

**Issue by xhcao** [tensorflow/tfjs#6965]
I had taken some investigation as below, but I was not familiar with tfjs-backend-cpu backend, so reported this bug.

The error reports “[pageerror] Error: Arrays are of different type. Actual: Int32Array. Expected: Float32Array”

Actually, the failed issue is caused by cpu backend. The dtype of model’s output tensor is `int32`, so it should return an Int32Array when reading output tensor, but cpu backend returns a Float32Array.

As we all know, the tensor data of webgl and webgpu backends is saved on the GPU side, and they are all Float32 type, if we want to read the tensor to CPU side, we should create an array object (Float32Array | Int32Array | Uint8Array | …) according to the tensor’s dtype (float32 | int32 | bool | …), and explicitly convert GPU float32 data to the right CPU float32 | int32 | uin8 data.
https://github.com/tensorflow/tfjs/blob/2eafff718d6df2ab5571f9778a1e09c6a517499d/tfjs-backend-webgl/src/backend_webgl.ts#L1198
https://github.com/tensorflow/tfjs/blob/2eafff718d6df2ab5571f9778a1e09c6a517499d/tfjs-backend-webgpu/src/backend_webgpu.ts#L429
Take DeepLabV3 for an example, on the webgl and webgpu backends, the dtype of the outputTensor is int32, so outputTensor.data() should return an Int32Array object. On the cpu backend, the dtype of the outputTensor is also int32, but it returns a Float32Array object. Then Error happens when comparing cpu and webgl | webgpu backends.

Unlike webgl and webgpu backends, the tensor data of cpu backend is saved on the CPU side, so we could directly use Float32Array | Int32Array | Uint8Array object to save tensor data, which is exactly same as dtype, when we want to read the outputTensor data, only need to return its related array object directly without type conversion.
https://github.com/tensorflow/tfjs/blob/2eafff718d6df2ab5571f9778a1e09c6a517499d/tfjs-backend-cpu/src/backend_cpu.ts#L142

But some operators of cpu backend does not handle the dtype and the array type of saving tensor’ values object correctly. Take DeepLabV3 for an example again, the error happens in the `ResizeNearestNeighbor` operator,
https://github.com/tensorflow/tfjs/blob/2eafff718d6df2ab5571f9778a1e09c6a517499d/tfjs-backend-cpu/src/kernels/ResizeNearestNeighbor.ts#L39
It directly creates a buffer with Float32Array without according to the dtype of input, actually, the output attribute of `ResizeNearestNeighbor` is {dtype: int32, Float32Array} in this example. We note it as an issued node of the model here.

Generally, if there are other nodes behind creating a new tensor, the model could run successfully. But unfortunately, the issued node is the third to last node, and the behind two nodes only incRef the tensor of the issued node.

**Comment by gaikwadrahul8** [comment]
Hi, @xhcao 

Apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs/pull/7044 got merged which was to take care of this issue if I'm not wrong, if yes could you please close this issue now because PR got merged ? Thank you!
