### ISSUE TITLE
@tensorflow/tfjs-tfdf install

### ISSUE THREAD

**Issue by felixdrp** [tensorflow/tfjs#6972]
**Describe the problem**

`npm install @tensorflow/tfjs-tfdf`
It doesn't work.

@tensorflow/tfjs-tfdf doesn't appears at npm.

Do you have any idea?

Many thanks for your work

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ahmedsabie** [comment]
The package is still in the process of development :) Expect the alpha release within a month.

**Comment by felixdrp** [comment]
Looking forward to trying it!
Many thanks for your work.

Cheers,
