### ISSUE TITLE
XNNPACK utilization for 2D matmul

### ISSUE THREAD

**Issue by shalvamist** [tensorflow/tfjs#6982]
Hi,

I have been looking at XNNAPCK recently and came across this piece of [code in TFJS](https://github.com/tensorflow/tfjs/blob/a82eee5f8ed9743e52095b9a376b3b42ccb4fa84/tfjs-backend-wasm/src/cc/batch_mat_mul_impl.cc#L295).
It seems like TFJS will utilize XNNPACK only for 1Dx1D MatMul, from reviewing XNNPACK code it seems to have support for higher dims of MatMul. Will this be added in the future ?

This is non-blocking issue; I am just curious if it's a limitation within XNNPACK.

Thanks

**Comment by pyu10055** [comment]
I believe XNNPack does not support MatMul op, we are using xnnpack fully_connect op for the single batch case.

**Comment by shalvamist** [comment]
Got it, so the condition is on the number of matrices in the batch.
Thanks for the quick response!
