### ISSUE TITLE
Increase BEFORE_PAGING_CONSTANT and enable users to disable paging

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#699]
See https://github.com/tensorflow/tfjs/issues/672 for context.

We should increase our constant that sets the paging threshold and probably also allow users to override it or disable it. Another idea I discussed with @nsthorat would be whether we could detect that a single tensor was larger than this threshold and disable paging if that occurs.

**Comment by nsthorat** [comment]
We increased the value and we now allow users to override it with `ENV.set('WEBGL_NUM_MB_BEFORE_PAGING', 1000);`
