### ISSUE TITLE
We are forced to use an Expo managed App, but react-native-fs does not support it

### ISSUE THREAD

**Issue by aymeric75** [tensorflow/tfjs#6996]
**System information**
- I use a minimal installation of a React Natice app, with Expo
- Windows 10
- Mobile device : not relevant for this problem

**Describe the current behavior**

There is this installation step :

- Install and configure [react-native-fs](https://www.npmjs.com/package/react-native-fs)

But React Native FS is not available for Expo managed app ( see this [post](https://github.com/itinance/react-native-fs/issues/688) )

And at the same time (before), there is this step:

- Install and configure [react-native-unimodules](https://github.com/unimodules/react-native-unimodules)

Leads to having a Managed Expo App (if you don't believe me, follow the links and you will see ;) )

**Describe the expected behavior**

So there is a big contradiction here...

Thanks

**Comment by rthadur** [comment]
Related https://github.com/tensorflow/tfjs/issues/6993

**Comment by aymeric75** [comment]
> Related #6993

Might be... but that does not answer the problem... thx

**Comment by gaikwadrahul8** [comment]
Hi, @aymeric75 

Apologize for the delayed response and It seems like we don't support `react-native-fs` at the moment if I'm not wrong and please check below **Expo compatibility** from our [official documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native#expo-compatibility) .

If you need any further clarification please let us know ? Thank you!

**Expo compatibility** :

This library relies on [expo-gl](https://github.com/expo/expo/tree/master/packages/expo-gl) and [expo-gl-cpp](https://github.com/expo/expo/tree/master/packages/expo-gl-cpp). Thus you must use a version of React Native that is supported by Expo.

Some parts of tfjs-react-native are not compatible with managed expo apps. You must use the bare workflow (or just plain react native) if you want to use the following functionality:

Loading local models using [bundleResourceIO](https://js.tensorflow.org/api_react_native/latest/#bundleResourceIO). You can instead load models from a webserver.

**Comment by DylanTet** [comment]
I am currently working with an Expo managed project and curious as to why bundleResourceIO isnt supported with Expo projects? This will allow me to make a better decision on whether ejecting from Expo or just making a request to a server is better to run my model.
