### ISSUE TITLE
Error: The dtype of dict['input_tensor'] provided in model.execute(dict)  must be int32, but was float32 

### ISSUE THREAD

**Issue by dubrovin-sudo** [tensorflow/tfjs#7004]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Used a stock example script provided in TensorFlow.js;
- TensorFlow.js installed from (npm or script link):
    `!pip install tensorflowjs`
- TensorFlow.js version 4.0.0;
- Google Chrome Version 107.0.5304.87 (Official Build) (64-bit);

**Describe the current behavior**
After the conversion, the input data type changed from float32 to int32

**Describe the expected behavior**
The data format remains the same

**Standalone code to reproduce the issue**
```
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    /content/gdrive/MyDrive/customTF2/data/inference_graph/saved_model \
    /content/gdrive/MyDrive/customTF2/models_to_prod/web_model_mobilenetv2_float32
```
Colab [link](https://colab.research.google.com/drive/1tFcVQ0sJMJ43Y3li_o2IsYwTATpd7F8k#scrollTo=ioHy5V1Qlo4f&line=6&uniqifier=1)

**Other info / logs** Include any logs or source code that would be helpful to

_TFmodel.signatures['serving_default'].output_dtypes_
`{'detection_anchor_indices': tf.float32,
 'raw_detection_scores': tf.float32,
 'detection_classes': tf.float32,
 'num_detections': tf.float32,
 'raw_detection_boxes': tf.float32,
 'detection_boxes': tf.float32,
 'detection_multiclass_scores': tf.float32,
 'detection_scores': tf.float32}`

**Comment by pyu10055** [comment]
@dubrovin-sudo thank you for reporting the issue, can you make the colab public accessible?

**Comment by dubrovin-sudo** [comment]
> @dubrovin-sudo thank you for reporting the issue, can you make the colab public accessible?

https://drive.google.com/file/d/1ltqLWOv-8EGIEe9ll7XQVyHDn7wFHSID/view?usp=sharing

**Comment by ahmedsabie** [comment]
@dubrovin-sudo You listed the output dtypes which are float32 but are the input dtypes also float32? Also can you provide the saved model so I can run the converter manually, I wasn't able to get the colab working

**Comment by dubrovin-sudo** [comment]
@ahmedsabie 
1. [SSD_Mobilenetv2_float32](https://drive.google.com/drive/folders/1-CUwlgClMpsY6nX00YDgA6p6oU567s6x?usp=sharing);
2. [SSD_Mobilenetv2_float16](https://drive.google.com/drive/folders/1-Q51tLZ20v6-bVKCep5BCUjVUMWYu1UF?usp=sharing)

**Comment by ahmedsabie** [comment]
@dubrovin-sudo Yes as I mentioned I believe you are mixing up inputs and outputs. The TFJS outputs are indeed float, same as your python model, but your python model inputs are as follows:
```console
>>>print(model.signatures['serving_default'].structured_input_signature)

((), {'input_tensor': TensorSpec(shape=(1, None, None, 3), dtype=tf.uint8, name='input_tensor')})
```
which is int
