### ISSUE TITLE
Ops in tf.feature_columns not supported

### ISSUE THREAD

**Issue by Arvinds-ds** [tensorflow/tfjs#701]
On models using the `tf.feature_columns`, many of ops are not supported in the latest version

`StringToHashBucketFast, AsString, GatherNd, SparseToDense`

Request support for `tf.feature_columns` ops.

**Comment by bileschi** [comment]
Also blocked by lack of string support : https://github.com/tensorflow/tfjs/issues/454

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
