### ISSUE TITLE
tf.concat and tf.stack throw a "Failed to compile fragment shader" error, for arrays of specific lengths

### ISSUE THREAD

**Issue by LKMason** [tensorflow/tfjs#7012]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.6.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): Script link
- TensorFlow.js version (use command below): 4.0.0
- Browser version: Chrome Version 107.0.5304.87
- Tensorflow.js Converter Version:

**Describe the current behavior**

When tf.concat or tf.stack are used on an array of tensors with size greater than or equal to 128, an error is thrown if there are 16*n + 1 tensors in the array. For example, ``tf.stack(Array.from({length: rows}, (_,i) => tf.ones([cols])))`` will fail if cols >= 128 and rows is 17, 33, 49, or 65, etc., but not for any other integers. The error message is "Error: Failed to compile fragment shader."

**Describe the expected behavior**

No error should be returned for this operation.

**Standalone code to reproduce the issue**

```js
// Fails
tf.concat(Array.from({length: 65}, (_,i) => tf.ones([128])))

// Succeeds
tf.concat(Array.from({length: 66}, (_,i) => tf.ones([128])))

// Succeeds
tf.concat(Array.from({length: 65}, (_,i) => tf.ones([127])))
```

Here is an Observable Notebook which shows this issue: https://observablehq.com/d/533ee1e7034d1402

**Other info / logs**

Attached the console log. [tfjs_concat_error.log](https://github.com/tensorflow/tfjs/files/9933069/tfjs_concat_error.log)

**Comment by Linchenn** [comment]
Hi @LKMason , this issue has been fixed in https://github.com/tensorflow/tfjs/pull/6930 and this https://github.com/tensorflow/tfjs/issues/6884 is similar with yours.

The fix will take effect in the next TFJS release. If you want to apply the fix now, you could TFJS locally.
