### ISSUE TITLE
React-Native: Tfjs model does not seem to be loaded in apk-release - only in dev mode

### ISSUE THREAD

**Issue by d-kls** [tensorflow/tfjs#7037]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 6 Emulator
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: @tensorflowjs/tfjs 4.0.0 /tfjs-react-native: 0.8.0
- CUDA/cuDNN version:

**Describe the problem**
After building the apk - the model does not seem to be able to be loaded. i am using context to show an activityindicator when the model has not yet been loaded on app start. this works fine when running `npm run android` from react-native init project. as soon as i run the release command `npx react-native run-android variant=release` the model does not ever load and im permanently stuck on the activity indicator. There are no error logs in the terminal executing metro or anywhere else. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`npx react-native run-android variant=release`

**Any other info / logs**
the model is inside the assets folder that is on the same level as the android, ios and other folders. 
Maybe im configuring something completely wrong - i would appreciate any help. I assume that the model is somehow not accessible for the release variant (i require the files inside js like any other)...maybe the model is not packaged with the apk?

**Comment by d-kls** [comment]
I am getting this log when using `react-native log-android` 

`TypeError: Cannot read property 'encode' of undefined`

my `model.json` seems to be loaded correctly. the assets do seem to be loaded correctly - logging both in dev vs release shows the same result.

image is result of error handling on loadGraphModel

```
const model: GraphModel = await tf
        .loadGraphModel(
            bundleResourceIO(modelJSON, [
                modelWeights1,
            ]),
        )
        .catch(e => {
            console.log('[LOADING ERROR] info:', e);
        });

```

![image](https://user-images.githubusercontent.com/68340074/201470354-8b35f84b-a2cd-4fc4-ab7d-cbca5fea19a0.png)

I don't get this error in dev mode - only in the release apk.

**Comment by d-kls** [comment]
tracing the source code in the repo - i assume the error is thrown here - not sure why:

https://github.com/tensorflow/tfjs/blob/fd34f6e25fcdd0aacb848452b6d45df26e9f28a2/tfjs-core/src/util.ts#L117

**Comment by d-kls** [comment]
Turns out the platform does not seem to be initialized correctly for some reason. Tracing further where the source code for setting the RN platform is happening - i found this file:

[file](https://github.com/tensorflow/tfjs/blob/fd34f6e25fcdd0aacb848452b6d45df26e9f28a2/tfjs-react-native/src/platform_react_native.ts)
![image](https://user-images.githubusercontent.com/68340074/201471627-92fb1822-2ba9-4a39-a7b7-ef2c48b15786.png)

importing this 

`import '@tensorflow/tfjs-react-native/dist/platform_react_native';`

at any point before loading the model will ensure the platform is set correctly.

**Comment by gaikwadrahul8** [comment]
Hi, @d-kls 

Apologize for the delayed response and May I know your issue got resolved or not ? It seems like there is some issue with `@tensorflow/tfjs-react-native@0.8.0` version and please check this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753) if you're trying with expo and if possible could you please try to downgrade the version of react-native to `@tensorflow/tfjs-react-native@0.7.0` and check whether the issue still exist or not ?

If issue still exists please let us know with error log and we'll dig more into this issue ? Thank you!
