### ISSUE TITLE
React Native:  null is not an object (evaluating 'opHandler.clone')

### ISSUE THREAD

**Issue by jan-far** [tensorflow/tfjs#7041]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Os 13
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Physical device Android 12 and iPhone 11
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): @tensorflowjs/tfjs 3.21.0 and /tfjs-react-native: 0.8.0
- Browser version: - 
- Tensorflow.js Converter Version: 3.21.0

**Describe the current behavior**

when `model.predict` function is called, `TypeError: null is not an object (evaluating 'opHandler.clone')` error is thrown and  the prediction is broken.

**Describe the expected behavior**

The model should return the result of the prediction base

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```

const getModel = async () => {
  try {
    // wait for Tf to load up
    await tf.ready();

    // import the model (from teachablemachine)
    const modelJson = require('@assets/model/model.json');
    const modelWeights = require('@assets/model/weights.bin');

    // load the model
    const loadedModel = await tf.loadLayersModel(
      bundleResourceIO(modelJson, modelWeights),
    );

    return loadedModel;
  } catch (error) {
    console.log('error loading model: ', error);
  }
};

  useEffect(() => {
    const init = async () => {

      try {
        // get loaded model
        const loadedModel = await getModel();

        // set loaded model
        setModel(loadedModel);

        // Ready!
        setIsTfReady(true);
      } catch (error) {
        console.log('error loading model: ', error);
      }
    };

    init();
  }, []);
```

const result = model?.predict(resizeImage)
** where `resizeImage` is the resized camera stream from TensorCamera

When the line above (model.predict) is executed, ` Possible Unhandled Promise Rejection (id: 9):
TypeError: null is not an object (evaluating 'opHandler.clone')` error is thrown and the code 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

No log is shown except from the promise rejection raised.

**Comment by jan-far** [comment]
After inspecting the code. I realized that the file `@tensorflow/tfjs/dist/tf.node.js` fails to set the opHandler with the `setOpHandler` function. The imported properties from `@tensorflow/tfjs-core/dist/tf-core.node.js` didn't include the opHandler in the file as it already called the `setOpHandler` in the tf-core

**Things tried out**

First, I tried calling the setOpHandler in the `@tensorflow/tfjs/dist/tf.node.js` file, it resolved the mentioned issue above but at the cost of dropping the camera stream performance. The camera was lagging so much (and on debugging the frame rate was between -2fps and -6fps). This was bad and too slow.

Second fix (a lot better) was to set the opHandler values based on the imported properties from `@tensorflow/tfjs-core/dist/tf-core.node.js`. It worked with the frame rate around 6 - 12fps. 

Kindly let me know if there is anything I am doing wrong or miss. Thank you

**Comment by KivraS** [comment]
I am having the same issue.  Either opHandler.clone or Tensor.clone are null. Any updates on this?
`    "@tensorflow/tfjs": "^4.1.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    `

**Comment by KivraS** [comment]
Ok i found the root cause of the issue. **react-native-unimodules**  was not installed correctly thus causing tensorflow to throw random errors due to null references in tensors etc. (Got also either InputTensor null error, or Tensor.Clone null reference exception) .

It's just not enough to run` npm install react-native-unimodules ` there is also some installation process which is missing from the npm page because unimodules is deprecated!.

On expo projects my code runs fine. 
Struggling now to install expo on my current project.

**Comment by jan-far** [comment]
Yes, you indeed would need react-native-unimodules if you're running bare React-native. I faced that issue and had to start a new expo project, ejected it and then moved my codes into it. 
That's when the above issue was encountered 

> Ok i found the root cause of the issue. **react-native-unimodules** was not installed correctly thus causing tensorflow to throw random errors due to null references in tensors etc. (Got also either InputTensor null error, or Tensor.Clone null reference exception) .
> 
> It's just not enough to run`npm install react-native-unimodules` there is also some installation process which is missing from the npm page because unimodules is deprecated!.
> 
> On expo projects my code runs fine. Struggling now to install expo on my current project.

**Comment by jecs89** [comment]
> After inspecting the code. I realized that the file `@tensorflow/tfjs/dist/tf.node.js` fails to set the opHandler with the `setOpHandler` function. The imported properties from `@tensorflow/tfjs-core/dist/tf-core.node.js` didn't include the opHandler in the file as it already called the `setOpHandler` in the tf-core
> 
> **Things tried out**
> 
> First, I tried calling the setOpHandler in the `@tensorflow/tfjs/dist/tf.node.js` file, it resolved the mentioned issue above but at the cost of dropping the camera stream performance. The camera was lagging so much (and on debugging the frame rate was between -2fps and -6fps). This was bad and too slow.
> 
> The second fix (a bit better) was to set the opHandler values based on the imported properties from `@tensorflow/tfjs-core/dist/tf-core.node.js`. It worked with a frame rate of around -2fps to 6fps.
> 
> #### Fixes:
> **Patch files**
> 
> **For @tensorflow/tfjs-core/dist/tf-core.node.js**
> 
> ```
> diff --git a/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js b/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
> index 6ada250..0feff64 100755
> --- a/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
> +++ b/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
> @@ -27941,6 +27941,7 @@ exports.oneHot = oneHot;
>  exports.ones = ones;
>  exports.onesLike = onesLike;
>  exports.op = op;
> +exports.opHandler = opHandler;
>  exports.outerProduct = outerProduct;
>  exports.pad = pad;
>  exports.pad1d = pad1d;
> ```
> 
> **For @tensorflow/tfjs/dist/tf.node.js**
> 
> ```
> diff --git a/node_modules/@tensorflow/tfjs/dist/tf.node.js b/node_modules/@tensorflow/tfjs/dist/tf.node.js
> index 415136a..3ca74dc 100644
> --- a/node_modules/@tensorflow/tfjs/dist/tf.node.js
> +++ b/node_modules/@tensorflow/tfjs/dist/tf.node.js
> @@ -32632,6 +32632,7 @@ var version$2 = {
>  };
>  
>  Object.keys(tfjsCore).forEach(function (k) {
> +    if (k === 'opHandler') { setOpHandler(tfjsCore[k]) }
>      if (k !== 'default') Object.defineProperty(exports, k, {
>          enumerable: true,
>          get: function () {
> ```
> 
> PS: The issue still persists in the latest version (4.0.0). Kindly let me know if there is anything I am doing wrong or missing. Thank you

The solution to overpass this issue is working.

**Comment by gaikwadrahul8** [comment]
Hi, @jan-far 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
