### ISSUE TITLE
tfjs release present on npmjs but missing on github

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#7067]
`tfjs` version **4.1.0** was published on [npmjs](https://www.npmjs.com/package/@tensorflow/tfjs/v/4.1.0) on 11/19/2022  
but its not published on [github](https://github.com/tensorflow/tfjs/releases)  
and release notes as such are not present  

cc: @mattsoulanille

**Comment by mattsoulanille** [comment]
Fixed. Thanks for the report!
