### ISSUE TITLE
`useDocsFrom`doesn't work for metrics in tfjs-layers

### ISSUE THREAD

**Issue by manrajgrover** [tensorflow/tfjs#710]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.0

#### Browser version
NA

#### Describe the problem or feature request
TensorFlow API Documentation doesn't generate docs for `metrics` namespace. Looks like `useDocsFrom` is being ignored.

#### Code to reproduce the bug / link to feature request

See: https://js.tensorflow.org/api/0.13.0/#metrics.binaryAccuracy

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by manrajgrover** [comment]
@rthadur This issue is yet to be fixed. Information shared in the initial issue description is complete to my knowledge. Someone needs to investigate and fix this.

**Comment by rthadur** [comment]
reopened the issue as per request

**Comment by tafsiri** [comment]
@nsthorat do you want to own this since its doc generator related?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
We still need to fix this!

**Comment by nsthorat** [comment]
Apologies, this is fixed.

**Comment by nsthorat** [comment]
https://js.tensorflow.org/api/1.2.10/#metrics.binaryAccuracy
