### ISSUE TITLE
Reactjs  tflite.loadTFLiteModel encounter 404 error (tflite_web_api_client.js:1741) when running on Windows Server. Working when testing locally in win 10 laptop

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tfjs#7105]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows server
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No. Issues consistent across all browsers from mobile to windows laptop 
- 
- TensorFlow.js installed from (npm or script link): npm 
- TensorFlow.js version (use command below):
- Browser version: Chrome 107.0.5304.122
- Tensorflow.js Converter Version: 3.13.0

**Describe the current behavior**

Execute of Web App hang after execution of command to load custom tflite file

tfliteModel = await tflite.loadTFLiteModel("rk221113.tflite");

Inspection of chrome developer tool found 404 error at tflite_web_api_client.js:1741 

see attachment for screen capture of error.
![cannotLoadTflite](https://user-images.githubusercontent.com/10432466/203961770-a90509c1-d97e-4de6-80b0-03ef2f8b191d.JPG)

we have verified that file rk221113.tflite is present in web folder.

**Describe the expected behavior**

During local testing, the custom tflite file can be loaded successfully. 

We are running the program from VS code.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

The problem can be repeated by visiting this url: 
https://rtc.achieversprofile.com/?state=demo

after clicking the start button, the error can be found in chrome developer tool console
![loadingHang](https://user-images.githubusercontent.com/10432466/203963403-f2ba85a1-c3e3-417b-afb9-b4f82da375a2.JPG)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by FlyWong** [comment]
Hi, do let me know if you need more information to troubleshoot. 

Please also let us know if any work around is available so that we can proceed with our deployment.

**Comment by mattsoulanille** [comment]
Thanks for the bug report. From the error message you posted, it looks to me like your production server is not serving the `rk221113.tflite` file. Can you verify that clicking the https://rtc.achieversprofile.com/rk221113.tflite url (as shown in the 404 error in the console) downloads the model file on your production server?

When I tried the link you sent, I saw a different error. I'm getting a 404 on the `tflite_web_api_cc_simd.js` file at this link: https://rtc.achieversprofile.com/static/js/tflite_web_api_cc_simd.js . If you want to host tfjs-tflite wasm files yourself, you will need to copy everything matching `tflite_web_api_cc*` in `node_modules/@tensorflow/tfjs-tflite/dist/` to your `static/js` directory (or wherever you set `tflite.setWasmPaths()`). Sorry this is a bit confusing, the tfjs-tflite package is still in alpha.

**Comment by FlyWong** [comment]
Yes the tflite_web_api_cc* are copied to the tflite_wasm folder and set using 

tflite.setWasmPath('tflite_wasm/');

![tflite_wasm](https://user-images.githubusercontent.com/10432466/204999300-c2e29d92-354d-4b71-8709-5d1138bd021b.JPG)

also verified that rk221113.tflite file is physically in the path 
![rkfile](https://user-images.githubusercontent.com/10432466/204999714-2bf41c7a-7efc-4c66-9815-e5efdb03701b.JPG)

with permission:

![rkPermission](https://user-images.githubusercontent.com/10432466/204999939-65913532-9c19-48bd-8b68-891afb676ad6.JPG)

However, if I try to access the file via 

https://rtc.achieversprofile.com/rk221113.tflite

I do get a error:

404 - File or directory not found.

Will check with server team and update soon1

**Comment by gaikwadrahul8** [comment]
Hi, @FlyWong 

May I know have you had a chance to check with your server team ? If so, has the issue been resolved ? 

If issue still persists please let us know with error log to do further investigation on your issue. Thank you!

**Comment by FlyWong** [comment]
Hi, the matter was resolved. Need to add the MIME type.

________________________________

**Comment by gaikwadrahul8** [comment]
Hi, @FlyWong 

I am glad to hear that your issue has been resolved. Please feel free to close this issue now. If you have any further questions or need assistance with any other issues, please do not hesitate to create a new issue and we will be happy to help. Thank you!
