### ISSUE TITLE
SparseConvolution Ops

### ISSUE THREAD

**Issue by lengoanhcat** [tensorflow/tfjs#7109]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 4.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Tensorflow.js does not seem to have sparse convolution ( for 3D pointcloud ) ops.

**Will this change the current api? How?**

I am not sure.

**Who will benefit with this feature?**

Any developer who needs to run object detection or semantic segmentation on 3D pointcloud data.

**Any Other info.**

Reference: https://github.com/mit-han-lab/torchsparse

**Comment by gaikwadrahul8** [comment]
Hi, @lengoanhcat 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and It seems like we haven't implemented `SparseConvolution` Op yet so May I know are you still looking for `SparseConvolution` Op in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by lengoanhcat** [comment]
@gaikwadrahul8: It is lucky that I probably have sometime for this. Let me check these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) out. Probably, I shall have a few questions as it is the first time I work on a PR for tfjs.

**Comment by lengoanhcat** [comment]
@gaikwadrahul8 : SparseConvOp is not supported in TF C++ API. Does it mean that a pull request for C++ implementation of the op should be done before writing a wrapper for its javascript wrapper ?

**Comment by gaikwadrahul8** [comment]
Hi, @lengoanhcat 

Apologize for the delayed response and you can refer this PR https://github.com/tensorflow/tfjs/pull/4963 which will help you how to submit PR for Op in TFJs. Thank you!
