### ISSUE TITLE
For some inputs, the outputs of the operator tf.dilation2d() are different between different backends (cpu,webgl and tensorflow))

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#7112]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):script link
- TensorFlow.js version (use command below):4.1.0
- Browser version:chrome 106.0.5249.119
- Tensorflow.js Converter Version:

**Describe the current behavior**
When calling the function ``tf.dilation2d`` and setting the parameter ``x:[[[[1,2,3],[4,5,6],[7,8,9]]]], filter:[[[2],[2],[2]]], strides:1, pad: same, dilation:[1,1]``
The output on the backend ``CPU`` is
![Selection_052](https://user-images.githubusercontent.com/68681463/204097949-bec60ce2-8612-46a4-8356-ea25deecd9c1.png)

The output on the backend ``WebGL`` is 
![Selection_054](https://user-images.githubusercontent.com/68681463/204098034-e8b64dde-b6bc-4e83-a028-4f7fc773a76e.png)

The output on the backend ``tensorflow`` with Nodejs: an ``error`` occurs with the message ``Message: input and filter must have the same depth: 3 vs 1`.
![Selection_055](https://user-images.githubusercontent.com/68681463/204098080-de8a5d02-c2ea-4484-b140-200fda1b6b10.png)

The output on the backend ``Wasm``:  an ``exception`` occurs with the message ``Uncaught (in promise) Error: Kernel 'Dilation2D' not registered for backend 'wasm'``
![Selection_053](https://user-images.githubusercontent.com/68681463/204097994-55a2ee93-5f2f-4b0a-8ffc-bca7c222b61e.png)

**Describe the expected behavior**

For any input, the results of the operator ``tf.dilation2d`` should be consistent or slightly different across all backends.  Specifically, the CPU backend and the WebGL backend should be aligned with the TensorFlow backend, **ensuring that input and filter have the same depth**. Alternatively, **the backends CPU, TensorFlow, and the WebGL should provide the same output**, allowing inputs and filters to have different depths.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bug</title>
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.js"> </script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
<script>
    function dilation2d(backend){
        tf.setBackend(backend);
        tf.ready().then(()=>{
            const output = tf.dilation2d([[[[1,2,3],[4,5,6],[7,8,9]]]],[[[2],[2],[2]]], 1, 'same',[1,1],"NHWC");
            output.print();
        })
    }
    async function run(){
        await dilation2d("webgl");
        await dilation2d("cpu");
    }
    run();
</script>
</body>
</html>
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

We debug the source code to analyze the reason why the ``CPU backend`` outputs  the abnormal results 
**``Tensor
    [[[[6, 4 , -9007199254740992],
       [9, 7 , 5                ],
       [9, 10, 8                ]]]]``.**

The results show that when running the kernel function  ``Dilation2D``  of the CPU backend (in source file ``tfjs-backend-cpu/src/kernels/Dilation2D.ts``),  the input and filter have different depths.  When calculating the output value corresponding to the position of the second input channel (**i.e., d===2**, see line 70),  the ``filterIndex=4`` (on line 79), which large than ``filterVals.length``, causing the ``val = NaN`` (on line 80). Thus, ``val < curVal`` and ``outputVals[outputIndex]=Number.MIN_SAFE_INTEGER`` (i.e., -9007199254740992).

```

                                 ...
65               for (var b = 0; b < batchSize; ++b) {
66 	      for (var hOut = 0; hOut < outHeight; ++hOut) {
67 	        var hBeg = hOut * strideHeight - padInfo.top;
68 	        for (var wOut = 0; wOut < outWidth; ++wOut) {
69 	          var wBeg = wOut * strideWidth - padInfo.left;
70	          for (var d = 0; d < inChannels; ++d) {  //when d===2, the outputVals===-9007199254740992
71. 	            var curVal = Number.MIN_SAFE_INTEGER;
72	            for (var h = 0; h < filterHeight; ++h) {
73 	              var hIn = hBeg + h * dilationHeight;
74 	              if (hIn >= 0 && hIn < inHeight) {
75 	                for (var w = 0; w < filterWidth; ++w) {
76 	                  var wIn = wBeg + w * dilationWidth;
77 	                  if (wIn >= 0 && wIn < inWidth) {
78 	                    var xIndex = locToIndex([b, hIn, wIn, d], xRank, computeStrides(x.shape));
79	                    var filterIndex = locToIndex([h, w, d], filterRank, computeStrides(filter.shape)); // filterIndex > filterVals.length
80 	                    var val = xVals[xIndex] + filterVals[filterIndex]; //NaN
81 	                    if (val > curVal) {
82	                      curVal = val;
83 	                    }
84 	                  }
85 	                }
86	              }
87 	            }
88  	            var outputIndex = locToIndex([b, hOut, wOut, d], outRank, computeStrides(outShape));
89 	            outputVals[outputIndex] = curVal;
90 	          }
91 	        }
92                                  ...

```
The detailed debugging process is as follows
![Selection_051](https://user-images.githubusercontent.com/68681463/204100234-69d68119-218a-48a9-b4c4-8b5ef2a1c5eb.png)

**Comment by Linchenn** [comment]
Thank you for reporting this!

The tensorflow backend's behavior is correct and I have sent out a fix for this.
