### ISSUE TITLE
Model.save does not save inout shape if initial layer is created as variable and input shape created as the.input

### ISSUE THREAD

**Issue by Kalevera** [tensorflow/tfjs#712]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

Version 13.0.0

#### Browser version

Chrome 68.0.344.106 (official build) 64bit
#### Describe the problem or feature request

When saving a sequential model using model.save('string'); 

The initial layer is not saved correctly for retrieval when using tf.loadModel('string');//throws error stating initial layer needs inputShape to initialize.

This is occurring when the initial layer is set to a variable and the input shape is a variable. Example below.

#### Code to reproduce the bug / link to feature request

Const model = tf.sequential();

let Dense1 = tf.dense({config}); //not including inputShape in config
let Dense1input = tf.input({shape:[2,2]});
Dense1.apply(Dense1input);
M
model.add(Dense1);

let saveResult = await model.save('indexeddb://my-model-1');

let loaded model = await tf.loadModel('indexeddb://my-model-1');

NOTE: 
If the inputShape is included within the config object when creating the initial layer the error is not thrown and the model will load. 

For some reason applying the shape to the first layer as opposed to including it in config creates the error.

**Comment by caisq** [comment]
Need to investigate if Python Keras shows the same behavior.
