### ISSUE TITLE
Loading saved AudioModel error 

### ISSUE THREAD

**Issue by hartonoda** [tensorflow/tfjs#7121]
Hi Im following tutorial to do Speech commands using soft fft ( https://www.youtube.com/watch?v=-1QGEQWhmSI ) 
I managed to get a model saved using model.save 

I have several questions: 
1. how do I load the same model and retrain it ? I have tried using const model = await tf.loadLayersModel('file://'+ args.filename);
but it gives me the error 'Type 'LayersModel' is missing the following properties from type 'AudioModel''

I tried to console log without converting the model and the saved filed is actually a sequential

2. Is it possible to load the already existing model with 'silence' and 'unknown' but using the soft fft technique ? so far I've seen transfer learning only by browser FFT

thanks!

**Comment by gaikwadrahul8** [comment]
Hi, @hartonoda 

Apologize for the delayed response and I would suggest you to go through this [TensorFlow.js - Audio recognition using transfer learning](https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab/index.html) codelab tutorial which will help you to solve your issue 

As per our [official documentation](https://github.com/tensorflow/tfjs-models/tree/master/speech-commands#online-streaming-recognition), we haven't implemented `SOFT_FFT` yet and we implemented `BROWSER_FFT`. Thank you!
