### ISSUE TITLE
Error in avgPool3d: Only NDHWC is currently supported, but got dataFormat of NCDHW

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#7123]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):script link
- TensorFlow.js version (use command below):4.1.0
- Browser version:chrome 106.0.5249.119
- Tensorflow.js Converter Version:

**Describe the current behavior**
The API document of Tensorflow.js states that the parameter ``dataFormat`` in operator ``tf.avgPool3d ``  ([https://js.tensorflow.org/api/4.0.0/#avgPool3d](https://js.tensorflow.org/api/4.0.0/#avgPool3d)) can be ``'NDHWC'|'NCDHW'``. But when setting the ``dataFormat`` to 'NCDHW', the error is thrown with the message "Error in avgPool3d: Only NDHWC is currently supported, but got dataFormat of NCDHW".
![Selection_062](https://user-images.githubusercontent.com/68681463/204562313-0375b732-f312-4f6b-8057-9e0475787028.png)

**Describe the expected behavior**

The implementation of ``tf.avgPool3d`` should be consistent across all backends and should be consistent with the description in the API documentation.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```
function avgPool3d(backend){
    tf.setBackend(backend);
    tf.ready().then(()=>{
        const output = tf.avgPool3d([[[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]]],[1,2,2], 1, "same","floor","NCDHW");
        output.print();
    })
}
async function run(){
    await avgPool3d("cpu");
    await avgPool3d("webgl");
    await avgPool3d("tensorflow");
}
run();
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
'NCDHW' is designed to be supported, so the API doc has it. However, if the backend haven't implemented 'NCDHW', you would see the error. So, the current behaviors are aligned with the expectation.
