### ISSUE TITLE
Mobilenet v2 on linux has significantly slower second inference times on v13 compared to v12.7

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#713]
On @pyu10055's linux machine, mobilenet v2 is 200ms for TFJS v13.0, but 30ms for TFJS v12.7. The difference between the two versions is packed matmul, and Daniel's change to send pointwise conv to matmul.

**Comment by rodrigob** [comment]
Is this a "linux" issue or a browser version issue ?

**Comment by annxingyuan** [comment]
@pyu10055 

Hey Ping, could you remind me whether you used the [benchmarking page](https://github.com/tensorflow/tfjs-core/blob/master/integration_tests/benchmarks/benchmark.html) to obtain these numbers?

When I benchmark on my Linux workstation with 100 inferences, I get 15ms per inference on master, and 26ms per inference on tfjs-core 0.12.15 (before packing). Would you mind running the same page on your machine and letting me know what you find?

**Comment by annxingyuan** [comment]
Ping and I investigated this further: it looks like the longer inference times only apply for the first few runs. When ping uses the standalone benchmarking page he gets similar numbers to me, but if he tests [only one subsequent inference](https://github.com/tensorflow/tfjs-converter/tree/master/demo/mobilenet) then inference times are significantly worse post-packing. 

We need to understand why the overhead created by packing seems to linger past the first inference.

cc @pyu10055

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available,Thanks!
