### ISSUE TITLE
Error in conv1d: got dataFormat of NCW but only NWC is currently supported.

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#7136]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):script link
- TensorFlow.js version (use command below):4.1.0
- Browser version:chrome 106.0.5249.119
- Tensorflow.js Converter Version:

**Describe the current behavior**
The API document of Tensorflow.js states that the parameter ``dataFormat`` in operator ``tf.conv1d ``  ([https://js.tensorflow.org/api/4.0.0/#conv1d](https://js.tensorflow.org/api/4.0.0/#conv1d)) can be ``'NWC'|'NCW'``. But when setting the ``dataFormat`` to 'NCW', the error is thrown with the message "Error in conv1d: got dataFormat of NCW but only NWC is currently supported."
![Selection_079](https://user-images.githubusercontent.com/68681463/205068262-8e75e4cf-d0ec-476c-a9d9-990a3cd4edf3.png)

**Describe the expected behavior**

The implementation of ``tf.conv1d`` should be consistent across all backends and should be consistent with the description in the API documentation.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```
function conv1d(backend){
    tf.setBackend(backend);
    tf.ready().then(()=>{
        var input=tf.fill([3,3,3],1,"float32");
        var filter=tf.fill([3,3,3],1,"float32");
        const result = tf.conv1d(input,filter, 1, 'same',"NCW",1);
    })
}
async function run(){
    await conv1d("cpu");
    await conv1d("webgl");
    await conv1d("tensorflow");
}
run();
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
The API doc mentions 'Only "NWC" is currently supported. ', so this behavior is aligned with expectation.
