### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by ravinsinghd** [tensorflow/tfjs#7151]
https://codelabs.developers.google.com/codelabs/tfjs-training-regression/index.html#6

 const [xs, preds] = tf.tidy(() => {

    const xs = tf.linspace(0, 1, 100);
    const preds = model.predict(xs.reshape([100, 1]));

    const unNormXs = xs
      .mul(inputMax.sub(inputMin))
      .add(inputMin);

    const unNormPreds = preds
      .mul(labelMax.sub(labelMin))
      .add(labelMin);

    // Un-normalize the data
    return [unNormXs.dataSync(), unNormPreds.dataSync()];
  });

There are two const variables with the same name. Even though it works it might confuse the user. Better to change the name for any one the variable

**Comment by jenperson** [comment]
Thank you for your feedback!

CL has been sent for review to change the variable name. I will close this issue once the CL is submitted.

**Comment by jenperson** [comment]
CL has been submitted
