### ISSUE TITLE
Movenet Model crashes on phones with MediaTek Chip.

### ISSUE THREAD

**Issue by Randhirjha17** [tensorflow/tfjs#7161]
I am using movenet with react native js which works well on iPhone and Android phones but when i run the same model on Android phones with MediaTek chipset it works fine for starting 30 seconds but then suddenly it starts to slow down and crashes the application.

**Comment by gaikwadrahul8** [comment]
Hi, @Randhirjha17 

Apologize for the delayed response, May I know your issue got resolved or still are you looking for help on this issue ? Thank you!
