### ISSUE TITLE
model.predict() the Array of Tensors that you are passing to your model is not the size the the model expected

### ISSUE THREAD

**Issue by playground** [tensorflow/tfjs#7164]
running node v16.15.1, tfjs-node v4.1.0 on Mac Big Sur

The model loaded with no error, failed on model.predict()
`ValueError: Error when checking model : the Array of Tensors that you are passing to your model is not the size the the model expected. Expected to see 1 Tensor(s), but instead got 0 Tensors(s).`

```
       model = await tfnode.loadLayersModel(`file://${modelPath}/model.json`)
       console.log(`loading time:  ${modelPath}, ${endTime-startTime}`);
       labels = jsonfile.readFileSync(`${modelPath}/assets/labels.json`);
       version = jsonfile.readFileSync(`${modelPath}/assets/version.json`);

       let outputTensor = model.predict({input_tensor: inputTensor});

```

**Comment by rthadur** [comment]
Please use reshape as shown below and try : 
`       let outputTensor = model.predict({input_tensor: inputTensor}).reshape([1,-1]);
`
