### ISSUE TITLE
Texture upload / download times from paging should not be included in op profiles

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#720]
With debug mode turned on, reported op performance includes time spent uploading / downloading textures from paging. Upload / download times should be logged separately.

**Comment by rthadur** [comment]
@annxingyuan is this fixed ?

**Comment by gaikwadrahul8** [comment]
Hi, @annxingyuan 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!
