### ISSUE TITLE
[Error: Operands could not be broadcast together with shapes 285 and 285,39.]

### ISSUE THREAD

**Issue by maxnuggets** [tensorflow/tfjs#7201]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 version 22H2 build 22621.963
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Using Iphone 8 and Oppo A9 2020 as simulator
- TensorFlow.js installed from (npm or script link): FROM NPM
- TensorFlow.js version (use command below): 3.3.0 (I have also used the lastest before, but from recent researches about my bug someone made it worked with 3.3.0 but I haven't when I tried)
- Browser version: Firefox 108.0.1 (64-bit)
- Tensorflow.js Converter Version: 3.3.0? same as TensorflowJS?

**Describe the current behavior**
I am a beginner in Machine Learning, I am currently doing this for my thesis application. I am trying to integrate MobilenetV3 with React-Native Expo. I trained my mobilenetv3 following this tutorial: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/tensorflow-1.14/training.html
inserting mobilenetv3 into the pipeline.config and adjusting steps and batches.

After succesfully training and exporting (from the tutorial), I then converted the exported files using tensorflowjs and tensorflowjs_converter. I followed the tutorial from: https://www.tensorflow.org/js/tutorials/conversion/import_saved_model
I have even tried both tf_frozen_model and tf_saved_model as input, and specified output_node_names. I have successfully converted on both types. I also successfully loaded (as far as I can understand) it when running in the mobile application. The problem is after putting an image in the loaded model it displays this error **[Error: Operands could not be broadcast together with shapes 285 and 285,39.]** I will be providing here the code of my Camera.js and Model.js
[CODES.zip](https://github.com/tensorflow/tfjs/files/10299711/CODES.zip)

**Describe the expected behavior**
The output should be properly predicted without error if im not mistaken in following tutorials and documentations.

**Standalone code to reproduce the issue**
See uploaded files

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
Hi @maxnuggets could you provide more information about the error? (a screenshot) Then I could locate the error.
