### ISSUE TITLE
TFJS : Error: All values in axis param must be in range [-4, 4) but got axis -272777233,-1074807361

### ISSUE THREAD

**Issue by ygf8** [tensorflow/tfjs#7202]
TensorFlow.js version:
    "@tensorflow/tfjs": "^4.1.0"

![Capture d’écran 2022-12-28 à 23 04 47](https://user-images.githubusercontent.com/89217866/209877018-88b81c57-4000-4ee7-9d28-58f3feaaba24.png)

I get this error message during prediction but the problem comes from the way the model was loaded. Indeed, when I load my model with tf.loadGraphModel and my model (.json + .bin) is on local or public server I have no problem.
when the model is loaded (without error message) from an external filesystem I get this problem. I'm sure that the .json has been loaded correctly and that it refers to the .bin weights. 
Where I have a doubt is on the encoding or format of the .bin that are returned through the filesystem.

However when I consult the responses to the requests, it seems that the .bin is complete:

(locally with predictions that work)
![Capture d’écran 2022-12-28 à 23 14 02](https://user-images.githubusercontent.com/89217866/209878612-bfff17e7-cf50-4393-8a06-d955073fcdea.png)
(locally with predictions KO)
![Capture d’écran 2022-12-28 à 23 13 22](https://user-images.githubusercontent.com/89217866/209878645-e79f9dd4-aa7b-42ab-b46e-804e889dc38e.png)

Please, Is there anything I missed?

(the filesystem extracts the data  "application/octet-stream" and I return the buffer (data.Body) as it seems to be done when the model is served locally) 

thank you in advance for your help

**Comment by Linchenn** [comment]
@ygf8 Do you mean if the files are on local or public server, the prediction also works as expected? If the files are on an external filesystem, the prediction throws an error you mentioned above?

If so, it looks like the problem is from the ed/de-coding of the external filesystem?

**Comment by ygf8** [comment]
@Linchenn Thank you for your response, yes I think it is from that. I can't detect where this encoding comes from. Obviously there is a difference on number of bytes / content-length

**Comment by Linchenn** [comment]
Then, where did you created/saved the model, from TFJS or converted from other platforms? 

From my perspective, when you save the model to a `.bin`, you invoke `encode`, while you invoke `decode` when you load the model. Maybe, the `encode` and `decode` you invoked are not paired?

**Comment by ygf8** [comment]
It was indeed an encoding problem, I managed to find a workaround by modifying the loader. Thank you @Linchenn

**Comment by CICCIOSGAMINO** [comment]
Can you show the solution because i'm experienced the same issue i think ....  get this error when the models are served from /public directory
