### ISSUE TITLE
tf.div presumably using too much memory space and leaking memory

### ISSUE THREAD

**Issue by Maveyyl** [tensorflow/tfjs#721]
#### TensorFlow.js version
0.13.0

#### Browser version
Google Chrome  69.0.3497.100  64 bits

#### Describe the problem or feature request
I am trying to load MNIST training images dataset.

The raw data is constituted of 47 040 000 (60 000 * 28 * 28) integers representing grey scale values between 0 and 255. My goal is to reshape this into a 4D tensor (60k * 28 * 28 * 1) and scale the values between 0 and 1.

Whenever I do a simple For loop through all 47 040 000 integers to divide them individually in the raw data array, the memory usage increases by something like 100 to 400 Mo. Whenever I try to divide the 4D tensor by a scalar using the function tf.div, I get several Go of ram used.

I hadn't the problem using the 0.10.0 version of tensorflow few months ago.

Am I doing something wrong?

#### Code to reproduce the bug / link to feature request
```javascript
        // data_raw is of size 47 040 000
	return tf.tidy(function(){
	        for(var i=0;i<data_raw.length;i++)
		        data_raw[i] = data_raw[i]/256.0;
	        return tf.tensor4d( data_raw, [60000, 28, 28, 1] );
         }
```

```javascript
        // data_raw is of size 47 040 000
	return tf.tidy(function(){
		var a = tf.tensor4d( data_raw, [60000, 28, 28, 1] );
		return a.div( tf.scalar(256) );
	});
```

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
