### ISSUE TITLE
js.tensorflow.org/api/latest/ documentation bug: scroll to bottom jumps to top. 

### ISSUE THREAD

**Issue by iislucas** [tensorflow/tfjs#7213]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 13.1
- TensorFlow.js installed from (npm or script link): N/A
- TensorFlow.js version (use command below): N/A
- Browser version: 108.0.5359.124 (Official Build) (x86_64)
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
When scrolling in the left hand contents part, going to the bottom of the documentation page, it jumps to the top of the documentation. This makes it super hard to read the last entry as I keep scrolling past it. 

**Describe the expected behavior**
Scrolling the contents stops at the top when scrolling up, and at the bottom when scrolling down.

**Standalone code to reproduce the issue**
Goto https://js.tensorflow.org/api/latest/ scroll to the bottom and keep scrolling. Observe it jumps to the top. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
No JS console logs.

**Comment by Linchenn** [comment]
@iislucas I cannot reproduce your issue, using my MacBook pro 2019, OS 13.1.
![image](https://user-images.githubusercontent.com/40653845/210280466-342844b2-4bd0-4fc1-b1da-ff32138f9f47.png)

Could you see this problem on other machines?

**Comment by iislucas** [comment]
Video showing how to make the bug happen and what it looks like... https://youtu.be/zLidnTnTEDk

**Comment by Linchenn** [comment]
Thank you @iislucas for reporting this! Have sent a fix and this would take effect when release a new version API doc.
