### ISSUE TITLE
Expo react native pose estimation not working from example repo

### ISSUE THREAD

**Issue by KingOfTNT10** [tensorflow/tfjs#7214]
**System information**
- OS Platform and Distribution: Windows 10
- Mobile device: Samsung note 10+ | Android 12

**Describe the current behavior**
Camera is running at 5 FPS and not showing markers in correct position (only on face and only in the middle of it, all markers get stacked on top of each other)

**Describe the expected behavior**
I expect it to work in at least 30 FPS as shown in https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection

**Standalone code to reproduce the issue**
I literally cloned and ran https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection

(No option to add issue on the https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection repo)

**Comment by sepretf** [comment]
Hello I had the same problem and created a solution I think you should check my article here https://medium.com/@fabrice_77308/real-time-human-body-detection-without-package-using-only-posturedetector-api-20-fps-ios-android-a7b95871f1c0
