### ISSUE TITLE
Unknown op 'EnsureShape'

### ISSUE THREAD

**Issue by AbhisKmr** [tensorflow/tfjs#7225]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): pip install tensorflowjs
- TensorFlow.js version (use command below): 3.19.0
- Browser version: Chrome 106.0.5249(64bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
Im training a custom object detection model along with keypoint-tracking for browsers using *CenterNet MobileNetV2 FPN Keypoints 512x512* and I have used 
*tensorflowjs_converter --control_flow_v2=True --input_format=tf_saved_model --metadata= --saved_model_tags=serve --signature_name=serving_default --strip_debug_ops=True --weight_shard_size_bytes=4194304 /saved_model /save_folder*
command to convert saved_model to tfjs model but got an error 
```
ValueError: Unsupported Ops in the model before optimization
EnsureShape
```

I don't know if it is a version problem or anything else, Is this ops not supported yet? Is there any other ways to convert my model to tfjs without modifying these ops? I need to use this model in Web browsers. I appreciate any help and hints!
Please provide any solution for my issue. THANK YOU

**Comment by mattsoulanille** [comment]
Hi @AbhisKmr. tfjs does not currently support the `ensure_shape` op. However, if you don't need the shape verification that `ensure_shape` provides (i.e. you are certain you will always have the expected shape) and want to end up with a fully defined shape, you can replace it with `tf.reshape`.
