### ISSUE TITLE
iOS 12 is producing NaNs for all ops.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#727]
When running snippets in the API docs, I'm getting all NaNs for ops that happen on the GPU.

**Comment by nsthorat** [comment]
Good question, I don't actually know if it's just the docs, I only tried it in docs + iOS 12.

**Comment by DavidGOrtega** [comment]
running on IOS over webview? its that possible?

**Comment by annxingyuan** [comment]
This was resolved with https://github.com/tensorflow/tfjs-core/pull/1346
