### ISSUE TITLE
TypeError: env().platform.isTypedArray is not a function. (In 'env().platform.isTypedArray(a)', 'env().platform.isTypedArray' is undefined)

### ISSUE THREAD

**Issue by anglo2333** [tensorflow/tfjs#7273]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by etosolo322** [comment]
use the previous version, for example @4.1.0

**Comment by asallem94** [comment]
I am running into this issue with a react-native project.

**Comment by Rhysjc** [comment]
Experiencing the same issue with a new react-native project.

**Comment by Rhysjc** [comment]
Having done some digging, I think #7181 had introduced this. I assume `isTypedArray` needs to be added to the [React Native platform](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/platform_react_native.ts)

**Comment by Rhysjc** [comment]
`tfjs-react-native` has `tfjs-core` as a peer dependency on version 3.7.0. I'm not too sure how the versioning of the packages here work, but assuming `tfjs` follows the same versions, downgrading `@tensorflow/tfjs` to `3.7.0` in your React Native project may resolve this. I don't have time to try it right now but I will do tomorrow. If this resolves it for anyone please comment.

**Comment by huhm** [comment]
> use the previous version, for example @4.1.0

it works for me.   I used the tsjs-node

**Comment by Rhysjc** [comment]
@huhm potentially I just needed to clear my metro cache and 4.1.0 would have worked. Though I think it's probably best to use the version `tfjs-react-native` has listed as a peer dependency

**Comment by Deeparaj-24** [comment]
> 4.1.0

After dowgrade ,getting same error bro

**Comment by ToonTalk** [comment]
4.1.0 fixed it for me - not using native react

**Comment by yousefamar** [comment]
React Native Expo standalone workflow developers: you need to create a new development build. Downgrading to 3.7.0 worked for me after doing that

**Comment by hrshlmeht** [comment]
> 

Hi , thanks for mentioning it. I am facing the same issue. Although my application is in NodeJs environment is this going to work? Because downgrading and having its repercussion on other working models can also be an issue later.

Please let me know

**Comment by abhik-wil** [comment]
> > 
> 
> Hi , thanks for mentioning it. I am facing the same issue. Although my application is in NodeJs environment is this going to work? Because downgrading and having its repercussion on other working models can also be an issue later.
> 
> Please let me know

Hey, so I am using Vite/React and downgrading to `3.7.0` worked for me.

**Comment by IvanKuchin** [comment]
Hi, 

There are many examples failing on TFJS API web-site.
Just as an example ([tfjs-vis](https://js.tensorflow.org/api_vis/1.5.1/#show.valuesDistribution)):
![image](https://user-images.githubusercontent.com/26530162/219740740-b80325ae-211e-4849-8204-a66534646074.png)

**Comment by DavidODonovan** [comment]
I had the same problem whilst using Vite/React app. Fixed it by downgrading to TFJS to version 3.7.0.
Thanks @Abhik Banerjee

**Comment by delirium15** [comment]
Also had same problem, but only when going to target page (containing tfjs logic) from another page. Reloading that page didn't produced that error. Using Nuxt3 / Vite. 
Downgrading from 4.2.0 to 4.1.0 didn't help, but to 3.7.0 solved problem.

**Comment by BruceDai** [comment]
Also had same problem of running tests by CPU backend, downgrading to 4.1.0 worked. 
Any update for this fixing, thanks.

**Comment by ianmaddox** [comment]
Had same issue trying to add an lstm layer to an empty model using 4.2.0:
`
    const model = tf.sequential();

    model.add(tf.layers.lstm({
        inputShape: [null, numFeatures],
        units: 64,
        returnSequences: true
    }));
`

generated the following error
`
/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2978
    return env().platform.isTypedArray(a);
                          ^

TypeError: env(...).platform.isTypedArray is not a function
    at isTypedArray (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2978:27)
    at inferShape (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5428:9)
    at tensor1d (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:18528:25)
    at /dir/node_modules/@tensorflow/tfjs-node/dist/kernels/SplitV.js:45:45
    at /dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4506:22
    at Engine.scopedRun (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4516:23)
    at Engine.tidy (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4505:21)
    at tidy (/dir/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8053:19)
    at Object.kernelFunc (/dir/node_modules/@tensorflow/tfjs-node/dist/kernels/SplitV.js:44:32)
`

Backing down to 4.1.0 fixed it.

**Comment by Merub-810** [comment]
@Rhysjc which version of react native you are using because in my case 3..7.0. is incompatible with my react native version

**Comment by JRfan123** [comment]
> @Rhysjc which version of react native you are using because in my case 3..7.0. is incompatible with my react native version

me too
