### ISSUE TITLE
WebGPU readSync is only available for CPU-resident tensors.

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7274]
I trained a model on the browser and used webgpu to load the model and reported an error：I trained a model on the browser and used webgpu to load the model and reported an error

**Comment by qjia7** [comment]
@lebron8dong Can you help to give an accessible case so that we can reproduce and debug this issue?

**Comment by lebron8dong** [comment]
> @lebron8dong Can you help to give an accessible case so that we can reproduce and debug this issue?

https://codelabs.developers.google.com/codelabs/tfjs-training-classfication?hl=zh-cn#2

**Comment by lebron8dong** [comment]
> @lebron8dong Can you help to give an accessible case so that we can reproduce and debug this issue?

https://codelabs.developers.google.com/codelabs/tfjs-training-classfication?hl=zh-cn#0   This is the official example, I reproduced the model, but reported the error when using webgpu as the backend.

**Comment by lebron8dong** [comment]
> @lebron8dong Can you help to give an accessible case so that we can reproduce and debug this issue?
I used cpu and webgl to train the model respectively, but when I used webgpu to load the model, both reported the same error：WebGPU readSync is only available for CPU-resident tensors.

**Comment by qjia7** [comment]
Can you directly share the complete webgpu case code so that I can try it locally? Or a very small case to reproduce your issue?

**Comment by lebron8dong** [comment]
> Can you directly share the complete webgpu case code so that I can try it locally? Or a very small case to reproduce your issue?

@qjia7 
https://github.com/lebron8dong/tfjs                 This is the file for training the model and loading the model with webgpu.

**Comment by lebron8dong** [comment]
> Can you directly share the complete webgpu case code so that I can try it locally? Or a very small case to reproduce your issue?
@qjia7 
https://github.com/lebron8dong/tfjs This is the folder for training the model and loading the model with webgpu.

**Comment by lebron8dong** [comment]
> Can you directly share the complete webgpu case code so that I can try it locally? Or a very small case to reproduce your issue?

@qjia7   source of error：
   // TODO: Remove once this is fixed:
  // https://github.com/tensorflow/tfjs/issues/1595
  override readSync(dataId: object): BackendValues {
    const tensorData = this.tensorMap.get(dataId);
    const {values} = tensorData;

    if (values == null) {
      throw new Error(
          'WebGPU readSync is only available for CPU-resident tensors.');
    }

    return values;
  }

**Comment by qjia7** [comment]
@lebron8dong Thanks for your information. I can reproduce it now. The main problem is that webgpu itself doesn't support synchronous read. However, there are still several places using `dataSync` in tfjs framework. The error in your case is triggered by https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/src/util/math.ts#L290.  I will check whether I can remove `dataSync` and use something else or workaround it in webgpu backend.

**Comment by lebron8dong** [comment]
> @lebron8dong Thanks for your information. I can reproduce it now. The main problem is that webgpu itself doesn't support synchronous read. However, there are still several places using `dataSync` in tfjs framework. The error in your case is triggered by https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/src/util/math.ts#L290. I will check whether I can remove `dataSync` and use something else or workaround it in webgpu backend.

@qjia7 
Thank you very much, I will wait for your good news.

**Comment by lebron8dong** [comment]
@qjia7  There is still the same error in my demo. Does my demo code need to be changed?

**Comment by qjia7** [comment]
You need to wait for the next release of tfjs-vis. Or build it by yourself from the source code https://github.com/tensorflow/tfjs/tree/master/tfjs-vis.  I tried it locally. The next issue you may meet is [platform.isTypedArray is not a function](https://github.com/tensorflow/tfjs/issues/7273). After some workarounds to void #7273, it works on webgpu.

**Comment by lebron8dong** [comment]
@qjia7 thank you very much,thank you very much.

**Comment by lebron8dong** [comment]
@qjia7 
const res = model.predict(test);
res. print()；
reported the same error：WebGPU readSync is only available for CPU-resident tensors.
Under the backend of webgpu, I want to print the result on the console, is this possible?

**Comment by qjia7** [comment]
@lebron8dong WebGPU only supports async read. Maybe try `const data = await res.data(); console.log(data)`
