### ISSUE TITLE
Kernel 'Log1p' not registered for backend 'wasm'

### ISSUE THREAD

**Issue by danielkhendricks** [tensorflow/tfjs#7282]
# Bug report

## System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A (Running in browser)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): "@tensorflow/tfjs": "^4.2.0", "@tensorflow/tfjs-backend-wasm": "^4.2.0"
- Browser version: N/A
- Tensorflow.js Converter Version: N/A

## Describe the current behavior
The following code:
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
<script>
tf.setBackend('wasm').then(() => {
  const x = tf.tensor1d([1, 2, Math.E - 1]);
  x.log1p().print();  // or tf.log1p(x)
});
</script>
```
throws the error "Kernel 'Log1p' not registered for backend 'wasm'"

## Describe the expected behavior

The code should run without error and print the log1p of the tensor.

##  Standalone code to reproduce the issue
Just copy and paste the code under "Describe the current behavior".

## Other info / logs

N/A

**Comment by chunnienc** [comment]
Hi @danielkhendricks,

Thanks for your report! We are actively improving the kernel coverage for wasm backend right now. I will keep this issue updated when there is any progress for wasm Log1p kernel, thanks!

**Comment by danielkhendricks** [comment]
@chunnienc, can you provide an update on the progress made towards solving this issue? I'm eagerly anticipating a resolution :)
