### ISSUE TITLE
Bug in Chrome extension tutorial

### ISSUE THREAD

**Issue by pcoet** [tensorflow/tfjs#7288]
The [Chrome extension tutorial](https://github.com/tensorflow/tfjs-examples/tree/master/chrome-extension) throws an error when I run it. It still works as expected, but the extension card shows an error, and when I click on it, I see this:

<img width="1792" alt="Screenshot 2023-01-18 at 5 00 19 PM" src="https://user-images.githubusercontent.com/5672572/213337318-c770d587-498c-47e8-96f7-c2d68e849c00.png">

service_worker.js: "Unchecked runtime.lastError: Cannot create item with duplicate id contextMenu0".

Maybe we need to dynamically generate [this string](https://github.com/tensorflow/tfjs-examples/blob/master/chrome-extension/src/service_worker.js#L53), e.g. `contextMenu${n}`?

@jenperson 

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jenperson** [comment]
Fixed issue. See pull request: https://github.com/tensorflow/tfjs-examples/pull/1016
