### ISSUE TITLE
handleCameraStream (TensorCamera onReady) not called until a rerender on Android

### ISSUE THREAD

**Issue by Rhysjc** [tensorflow/tfjs#7293]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 13.1 (M1)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung A27
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.7.0
- Browser version: N/A
- Tensorflow.js Converter Version: 4.2.0

**Describe the current behavior**
My `onReady` handler for `TensorCamera` isn't called on Android devices until a rerender is triggered. This can be done by rotating the orientation of the device.

**Describe the expected behavior**
`onReady` is called straight away as it is on iOS.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
Sorry about it, this may takes us a while to fix it. @Rhysjc

**Comment by Rhysjc** [comment]
Thanks @Linchenn . I have found a workaround in the meantime for anyone else who comes across this.
````
  const [showCamera, setShowCamera] = useState(false);

  // Fixes the camera not calling `onReady` till a re-render on Android
  // https://github.com/tensorflow/tfjs/issues/7293
  useEffect(() => {
    setShowCamera(true);

    return () => {
      setShowCamera(false);
    }
  }, []);

  return (
      {showCamera && (
        <TensorCamera
          style={styles.camera}
          type={CameraType.back}
          resizeHeight={224}
          resizeWidth={224}
          resizeDepth={3}
          autorender
          onReady={handleCameraStream}
          ratio={'4:3'}
        />
      )}
  );
```

**Comment by Linchenn** [comment]
Great, thank you!

**Comment by Rhysjc** [comment]
@Linchenn This seems to not actually be working. Interestingly if I back out of the screen with the camera on and then go back to it again, `onReady` starts getting called.

**Comment by Rhysjc** [comment]
This is not an issue with this package but with Expo, I've posted an issue here https://github.com/expo/expo/issues/21163

**Comment by krzychuuu132** [comment]
Some progress ?
