### ISSUE TITLE
GSoC'23

### ISSUE THREAD

**Issue by shivance** [tensorflow/tfjs#7296]
I'm interested in participating in gsoc in tf this year.

What are some potential projects? Should I start contributing right away?

**Comment by Neilblaze** [comment]
Hi @shivance, afaik we can start contributing right away. If you're into TFjs then you can start contributing from here itself, else there are other TF projects that you can explore. Even I'm in the same boat, & I'm exploring for the same to contribute.

If you're on discord, we can connect — [_**Neel#0242**_](https://discordapp.com/users/694942064131047461)

**Comment by parthbagda211** [comment]
I'm interested in participating in Gsoc'23 in  this year. I am familiar with TensorFlow and Keras Framework and I have some experience with them. Is any Good Project fit of me ?

**Comment by Realmbird** [comment]
@Neilblaze Is it fine if I contact you since it is 2 years later
