### ISSUE TITLE
Posenet video example - non node

### ISSUE THREAD

**Issue by kenlupo** [tensorflow/tfjs#730]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs@0.11.7

#### Browser version
Chrome 69.0.3
#### Describe the problem or feature request
Requesting more information on tfjs-models posenet example use with a video(not camera). Could you please provide a code example of output via console as well as html/javascript ?

#### Code to reproduce the bug / link to feature request
Here's what I have to get the data from an image. How do I see the overlay and how do I do this for a video?

<html>
  <head>
    
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.11.7"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet@0.1.2"></script>
 </head>

  <body>
    <img id='poseimage' crossorigin="anonymous"  src='/static/image.png'/>
  </body>
  
  <script>
    var imageScaleFactor = 0.5;
    var outputStride = 16;
    var flipHorizontal = false;

    var imageElement = document.getElementById('poseimage');

    posenet.load().then(function(net){
      return net.estimateSinglePose(imageElement, imageScaleFactor, flipHorizontal, outputStride)
    }).then(function(pose){
      console.log(pose);
    })
  </script>

**Comment by oveddan** [comment]
@kenlupo I agree - this would be great to show how to use with an existing video.  One of the strengths of pose estimation being done with an rgb image is it can be done on existing footage and doesnt need to be done live.

**Comment by kenlupo** [comment]
@oveddan - I've got it so I can split a video into images and then I'm working on running tfjs posenet over each image and putting it back together. Do you think there's a better way to do this with the video? I'm not aware of another way.

**Comment by ogamaxwell** [comment]
@kenlupo check out [p5](https://p5js.org/reference/#/p5/createVideo)! Ive been using it to draw video onto a canvas then apply pose net to that canvas. 

[ML5](https://ml5js.org/docs/posenet-webcam) has great resources on how to do this.
Its basically tensorflow for dummies (mean that in the nicest way, as i use it)

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
