### ISSUE TITLE
Object Detection (.predict) using tfjs-tflite with custom tflite model file results in memory leak and crash

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tfjs#7303]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): tfjs 3.7.0
- Browser version: 109.0.5414.76 
- Tensorflow.js Converter Version:  3.13.0

**Describe the current behavior**

I have a custom tflite model file (object detection) which I have tested to be running well in Android. I implemented the functionality in web App using tfjs-tflite and it was able to detect object over webcam. Below are some of the code snippets 

import * as tflite from '@tensorflow/tfjs-tflite';
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-backend-webgl';
import * as tfjsWasm from '@tensorflow/tfjs-backend-wasm';

....

tflite.setWasmPath('tflite_wasm/');

...

tfliteModel = await tflite.loadTFLiteModel(MyModelPath);

 var staticImg= tf.cast(tf.expandDims(tf.image.resizeBilinear(tf.browser.fromPixels(document.getElementById(s_canvasName)), [320, 320])), 'int32');

  var outputTensor = await tfliteModel.predict(staticImg);

  if (typeof outputTensor['StatefulPartitionedCall:0'] !== 'undefined'){
//successful
}

However, as test the function longer, we noticed that memory will keep building up until memory runs out and the program crash. From VS code debug console, there is warning of memory leak as well. 

**Describe the expected behavior**

Memory consumption should not build up. 

Please advise how can we release the memory eg. force dispose of variables?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

as above

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Screen capture of high memory warning in visual studio:
![HighMemGPU](https://user-images.githubusercontent.com/10432466/214843611-9cd93954-518c-484e-811a-6480b45a3cef.JPG)

Full error message on browser in development environment
[highMemRacket.pdf](https://github.com/tensorflow/tfjs/files/10509584/highMemRacket.pdf)

Memory ran out
![HighMem2](https://user-images.githubusercontent.com/10432466/214845734-6a6ac073-bb95-4302-98bd-d5216408cad6.JPG)

**Comment by pyu10055** [comment]
@FlyWong From your code it looks like there are memory leak from the intermediate tensors and output tensor you created during the inference
```
var staticImg= tf.tidy(() => tf.cast(tf.expandDims(tf.image.resizeBilinear(tf.browser.fromPixels(document.getElementById(s_canvasName)), [320, 320])), 'int32'));

// inference code ...

staticImg.dispose();

```

**Comment by FlyWong** [comment]
Thanks! The memory consumption is stable now!

**Comment by FlyWong** [comment]
Can close
