### ISSUE TITLE
tfjs-react-native package not updated and contains obsolete dependencies

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#7323]
The package `@tensorflow/tfjs-react-native` has the latest version **0.8.0** which was published in November 2021.  
It still contains dependencies on TFJS 3.11.0 as well as pretty much obsolete versions of React, Expo (-camera, -gl, etc.) and other key packages.

Last mentions are pointing towards demo project at <https://github.com/tensorflow/tfjs-examples/blob/master/react-native/image-classification/expo/package.json> to work around dependency issues.  

But a) using such old versions introduces many security vulnerabilities, b) its not compatible with many other newer components

Is the package still maintained?

**Comment by Linchenn** [comment]
@vladmandic Yes, it is still maintained, but we may do version updates in a couple of months later, since updating React and Expo may cause breaking.

**Comment by vladmandic** [comment]
i understand it may not be updated exactly at the same time as `tfjs-core`,  
but right now latest published version is 15 months old?

**Comment by Linchenn** [comment]
Yes, but we definitely will keep them up to date later.

**Comment by rbmdotdev** [comment]
^ I am currently blocked by this dependency issue, can we get this pr merged and pushed to npm?

**Comment by paradite** [comment]
While we wait for the PR to be merged, I want to share a walkaround I have been using for a few months:

Just copy the entire `platform_react_native.ts` file ([latest 4.2.0 version here](https://github.com/tensorflow/tfjs/pull/7415/files#diff-c117d2eecd67428a4e7bc46157769a45a54da43c97250da546a9c93feea83834)) into your project and initialize the RN runtime on your own in `App.tsx` with `import './xxx/platform_react_native';`.

It is only a few lines of changes and everything will work as expected with latest dependencies.

**Comment by ItamarGefen** [comment]
> While we wait for the PR to be merged, I want to share a walkaround I have been using for a few months:
> 
> Just copy the entire `platform_react_native.ts` file ([latest 4.2.0 version here](https://github.com/tensorflow/tfjs/pull/7415/files#diff-c117d2eecd67428a4e7bc46157769a45a54da43c97250da546a9c93feea83834)) into your project and initialize the RN runtime on your own in `App.tsx` with `import './xxx/platform_react_native';`.
> 
> It is only a few lines of changes and everything will work as expected with latest dependencies.

hey, I tried to do so but was facing the following error: TypeError: gl.texStorage2D is not a function. (In 'gl.texStorage2D(tex2d, 1, internalFormat, width, height)', 'gl.texStorage2D' is undefined)

TypeError: gl.texStorage2D is not a function. (In 'gl.texStorage2D(tex2d, 1, internalFormat, width, height)', 'gl.texStorage2D' is undefined)       
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:158821:31
callAndCheck@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:156571:27
createAndConfigureTexture@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:158820:19
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:162046:58
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:163218:45
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:162866:23
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:163198:62
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:163028:26
map@[native code]
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:163009:34
concatImpl@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:166994:41
kernelFunc@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:97981:36
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:98034:33
scopedRun@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:97870:22
runKernelFunc@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:98028:23
f2@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:127127:30      
f2@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:127127:30      
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:233123:39
generatorResume@[native code]
asyncGeneratorStep@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20670:26
_next@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20689:29    
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20694:14
tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25099:9
doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25230:25
Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25118:14  
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20686:25
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:233155:61
generatorResume@[native code]
asyncGeneratorStep@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20670:26
_next@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20689:29    
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20694:14
tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25099:9
doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25230:25
Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25118:14  
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:20686:25
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:95060:25
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25091:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:25172:27
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:26200:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:26119:17
_callReactNativeMicrotasksPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:26149:17
callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:26312:44
__callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:2407:46
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:2219:45
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:2391:15   
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.awesomeproject&modulesOnly=false&runModule=true:2218:21
flushedQueue@[native code]

The error occurs when I try to use a model after loading it with tf.loadGraphModel(bundleResourceIO(modelJson, modelWeights))

Any idea why it happens and how to fix it? @mattsoulanille 
(By the way, tf.print(a.concat(b)); does work)

**Comment by Haxfx** [comment]
Is there any expectation on when the PR will be merged?

**Comment by admbtlr** [comment]
> While we wait for the PR to be merged, I want to share a walkaround I have been using for a few months:
> 
> Just copy the entire `platform_react_native.ts` file ([latest 4.2.0 version here](https://github.com/tensorflow/tfjs/pull/7415/files#diff-c117d2eecd67428a4e7bc46157769a45a54da43c97250da546a9c93feea83834)) into your project and initialize the RN runtime on your own in `App.tsx` with `import './xxx/platform_react_native';`.
> 
> It is only a few lines of changes and everything will work as expected with latest dependencies.

Even easier is to use (patch-package)[https://github.com/ds300/patch-package] and add the extra two functions to `node_modules/@tensorflow/tfjs-react-native/dist/platform_react_native.js` in a patch:


```
    now() {
        //@ts-ignore
        if (global.nativePerformanceNow) {
            //@ts-ignore
            return global.nativePerformanceNow();
        }
        return Date.now();
    }

  // add these two functions below

    setTimeoutCustom() {
        throw new Error('react native does not support setTimeoutCustom');
    }

    isTypedArray(a) {
        return a instanceof Float32Array || a instanceof Int32Array ||
        a instanceof Uint8Array || a instanceof Uint8ClampedArray;
    }
```
