### ISSUE TITLE
Support quantization when converting a JAX model

### ISSUE THREAD

**Issue by thekevinscott** [tensorflow/tfjs#7330]
**System information**
- TensorFlow.js version (you are using): `4.2.0`
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

The [`convert_jax`](https://github.com/tensorflow/tfjs/blob/167fd6f572ddb0cf99284bc57c61607c45562d95/tfjs-converter/python/tensorflowjs/converters/jax_conversion.py#L57) does not currently support quantization settings or other conversion settings, as far as I can tell.

I'd propose directly passing `**kwargs` to [`convert_tf_saved_model`](https://github.com/tensorflow/tfjs/blob/167fd6f572ddb0cf99284bc57c61607c45562d95/tfjs-converter/python/tensorflowjs/converters/jax_conversion.py#L149), or specifying a dictionary that can be passed through.

**Will this change the current api? How?**

Purely additive, though I'm unclear whether Jax conversions will support all flags. Quantization and weight sharding at least seem like they should be supported.

**Who will benefit with this feature?**

Anyone converting a model from Jax to Tensorflow.js

**Any Other info.**

**Comment by mattsoulanille** [comment]
Good timing! I just wrote a PR for this.

**Comment by thekevinscott** [comment]
Ha, fantastic! Good on ya!

**Comment by mattsoulanille** [comment]
Fixed by #7331
