### ISSUE TITLE
Error: Session fail to run with error: Expects arg[0] to be float but int32 is provided

### ISSUE THREAD

**Issue by playground** [tensorflow/tfjs#7332]
running node v16.17.1, tfjs-node v4.2.0 on M1 MacOS Vertura 13.0.1

The model is trained and exported from https://www.kaggle.com/code/playbox21/fingers-savedmodel

          const image = readFileSync(imageFile);
          const decodedImage = tfnode.node.decodeImage(new Uint8Array(image), 3);
          const inputTensor = decodedImage.expandDims(0);
          this.model.predict({input_1: inputTensor});
```
Error: Session fail to run with error: Expects arg[0] to be float but int32 is provided
    at NodeJSKernelBackend.runSavedModel (/myapp/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:459:43)
    at TFSavedModel.predict (/myapp/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:364:52)
```

**Comment by vladmandic** [comment]
isn't the message clear? model expects `float` values as input and you're explicitly creating tensor using `uint8array`. you need to convert `decodedImage` to float (and probably normalize to range expected from model as most float models are expecting values 0..1 or -1..1, but that depends on your model).

**Comment by playground** [comment]
Hi @vladmandic, actually that code works for the efficientnet model I trained with my own dataset.  I was hoping I could use the dataset from Kaggle.  Can you shed some light on how I can get this to work?

**Comment by pyu10055** [comment]
@playground try this with the model, you might need to normalize as @vladmandic mentioned, it depends on the model input requirement: 
```
const inputTensor = decodedImage.expandDims(0).cast('float32');
```

**Comment by playground** [comment]
@pyu10055 that works, but the output doesn't have much info.  How to get bounding box coordinates? 

let outputTensor = this.model.predict(tensor);
                console.log(outputTensor)
`{
  dense: Tensor {
    kept: false,
    isDisposedInternal: false,
    shape: [ 1, 6 ],
    dtype: 'float32',
    size: 6,
    strides: [ 6 ],
    dataId: {},
    id: 6,
    rankType: '2'
  }
}`

**Comment by shmishra99** [comment]
Hi @playground ,
Apology for late in response. Could you please check the similar issue #2816 to get the bounding boxes from the custom trained models ? Which may help you to resolve your issue. 
If issue still persist please let us know.
Thank You !!
