### ISSUE TITLE
selfie_segmentation demo

### ISSUE THREAD

**Issue by pjotterplotter** [tensorflow/tfjs#7333]
The demo [selfie_segmentation ](https://storage.googleapis.com/tfjs-models/demos/body-segmentation/index.html?model=selfie_segmentation) shows some kind of inpainting of the mona lisa over your own face segmentation. I tried to play with this, but i cannot find any hints on how this is achieved. I tried  browsing through the source code, but it seems very generic and could not find anything specific for this particular effect (as if the mono lisa effect is encoded in the model itself?). Where should i look to try different face projections?

**Comment by gaikwadrahul8** [comment]
Hi, @pjotterplotter 

Apologize for the delayed response and I tried this [demo](https://storage.googleapis.com/tfjs-models/demos/body-segmentation/index.html?model=selfie_segmentation) from my end and it's working as expected so please give it try from your end and let us know whether your issue got resolved or not ? 

You can refer our these tfjs-models of face detection [face-detection ](https://github.com/tensorflow/tfjs-models/tree/master/face-detection), [face-landmarks-detection](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection)

If issue still persists please let us know ? Thank you!
