### ISSUE TITLE
Why so many Tensorflow version downloaded ?

### ISSUE THREAD

**Issue by Mr-LiuDC** [tensorflow/tfjs#7338]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: X
- TensorFlow.js installed from (npm or script link): X
- TensorFlow.js version: X
- CUDA/cuDNN version: 11.6

**Describe the problem**

I just want to convert onnx to tfjs and run command `pip install onnx onnx_tf tensorflowjs`

Why does it download many versions of tensorflow
![image](https://user-images.githubusercontent.com/18117854/216571669-117e35b0-acdc-4aa7-ba03-a5e21f554212.png)

**Comment by pyu10055** [comment]
@Mr-LiuDC I am not an expert on how pip resolve dependencies across packages, I think it downloads the different versions of tensorflow to figure out which version can best satisfy all dependency requirement across all packages.
TFJS has a rather broad range of version requirement for TensorFlow (>2.1 and < 3), which hopefully is not a blocker for the dependency resolver.

**Comment by gaikwadrahul8** [comment]
Hi, @Mr-LiuDC 

Apologize for the delayed response and I was able to replicate the same issue on Google Colab with latest Tensorflow version 2.12 and it's installing only TF2.12 which currently supports Google Colab by default and also check comment from @pyu10055 that may be the reason but I haven't observed same issue with latest TF2.12 so Could you please give it with latest TF2.12 and check whether it's downloading the one TF version

I have added [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/c5a7f3eb8d130141cb2274f1acb76a89/-7338.ipynb) for your reference and it did not observed that behaviour, If have I missed something here please let me know ? Thank you!
