### ISSUE TITLE
Tensorflowjs not working at all on Opera 94

### ISSUE THREAD

**Issue by becrespi** [tensorflow/tfjs#7347]
**System information**
- Windows 11
- Opera 94.0.4606.76
- tfjs@4.2.0
-  I have written a simple codepen that use tf.argMax

**Describe the current behavior**
Most tensorflowjs functions give 0 or unexpected result on Opera browser(chromium). There are no javascript errors just a 0 as the result(and same thing with model.predict for a classifier for example)

**Describe the expected behavior**
The output should be **2** like I have on chrome:
![image](https://user-images.githubusercontent.com/33726314/217102167-02d43b3d-5147-429b-9e24-2f1290ccbb66.png)
But sadly I just got 0:
![image](https://user-images.githubusercontent.com/33726314/217102644-9fe7c1a7-dcee-4739-a6d1-c6a767b69e86.png)

**Standalone code to reproduce the issue**
Here a simple codepen, with just two tensorflowjs commands:  https://codepen.io/becrespi1/pen/mdjgOYN

**Comment by pyu10055** [comment]
@becrespi I ran opera 94 and 95 versions on mac arm64, both are returning the correct result.
I will find a windows machine to check later.

**Comment by becrespi** [comment]
Hello sorry you have right !
My browser was kind of doomed or something because I just make a clean install of opera and all work without flaws.

**Comment by pyu10055** [comment]
thank you for confirming that.
