### ISSUE TITLE
Can't convert Keras hdf5 (URL provided)

### ISSUE THREAD

**Issue by santimirandarp** [tensorflow/tfjs#7349]
**System information**
- Have I written custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below): 4.2.0
- NodeJS version: 19 
- Tensorflow.js Converter Version: 2.11.0

**Describe the current behavior**

I downloaded the vgg16 from the same link used by keras i.e 

https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels.h5

And it won't convert. The error is :

     

> groups = conversion.h5_weights_to_tfjs_format(
>   File "/home/sm/.local/lib/python3.10/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 233, in h5_weights_to_tfjs_format
>     _check_version(h5file)
>   File "/home/sm/.local/lib/python3.10/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 100, in _check_version
>     keras_version = as_text(h5file.attrs['keras_version'])
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/home/sm/.local/lib/python3.10/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
>     attr = h5a.open(self._id, self._e(name))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5a.pyx", line 80, in h5py.h5a.open
> KeyError: "Can't open attribute (can't locate attribute: 'keras_version')"

**Describe the expected behavior**

Expected to be converted so I can load the Weights and use in my VGG16 net.

**Standalone code to reproduce the issue**

Download the file linked above and try to convert it using:

* `tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model vgg16_weights_tf_dim_ordering_tf_kernels.h5 ./converted`

**Comment by pyu10055** [comment]
The PR #7359 will allow the file converted, but be aware this is a weight only file, it contains no model topology.

**Comment by santimirandarp** [comment]
I think it is not solved, added why in the PR thread.

**Comment by VicEsquivel** [comment]
@santimirandarp So, which was the solution? I am also trying to convert that exact h5 model, and it throws the same error you describe. In the other PR thread you mentioned that it is solved if you hardcode version 2.0, but where is this to be hardcoded exactly? or is it a different / better fix for the issue?
