### ISSUE TITLE
Footer has broken website

### ISSUE THREAD

**Issue by nicholasess** [tensorflow/tfjs#735]
Hi Everyone!
I have a iPhone 5s and the footer has broken :/

If you have a website, Can I send a PR with changes :)

Thanks!

![captura de tela 2018-09-26 as 17 45 18](https://user-images.githubusercontent.com/3238901/46108293-1aa38c00-c1b4-11e8-8bcd-2fd05068f419.png)

**Comment by tafsiri** [comment]
@nicholasess Thanks for reporting. website repo is here (https://github.com/tensorflow/tfjs-website) if you want to make a PR (which would be welcome)!
