### ISSUE TITLE
Type expo.modules.gl.cpp.EXGL is defined multiple times

### ISSUE THREAD

**Issue by Filsufius** [tensorflow/tfjs#7357]
Kindly update documentation over on https://www.npmjs.com/package/@tensorflow/tfjs-react-native to reflect that fact that since expo-gl's version 12, expo-gl-cpp is not to be installed any more. I had been getting the error "Type expo.modules.gl.cpp.EXGL is defined multiple times" for a while before I realized that expo-gl had started including expo-gl-cpp.

**Comment by gaikwadrahul8** [comment]
Hi, @Filsufius 

Apologize for the delayed response and If I'm wrong it seems like we have updated our official documentation and removed `expo-gl-cpp` from dependancies from [here](https://www.npmjs.com/package/@tensorflow/tfjs-react-native).

If have I missed something here please let me know ? Thank you!
