### ISSUE TITLE
tfjs-vis.umd.min.js：build release of tfjs-vis 

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7361]
release of tfjs-vis  is not the latest，Can you  update the file on https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Apologize for the delayed response and I checked latest version of `@tensorflow/tfjs-vis` is 1.5.1 and It seems like it has been updated to latest version of `1.5.1`, you can check this [link ](https://www.jsdelivr.com/package/npm/@tensorflow/tfjs-vis) and I also checked above link which you shared there also it's showing version `1.5.1` if I'm not wrong. 

If have I missed something here please let me know ? Thank you!
