### ISSUE TITLE
Uncaught TypeError: tf.util.convertBackendValuesAndArrayBuffer is not a function

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7363]
Tensor.data()
backend：webgpu

**Comment by lebron8dong** [comment]
@qjia7  
this is the project： https://github.com/lebron8dong/tfjs
main code：
import {MnistData} from './data.js';

async function doPrediction(model, data, testDataSize = 3) {
  const IMAGE_WIDTH = 28;
  const IMAGE_HEIGHT = 28;
  const testData = data.nextTestBatch(testDataSize);
  const testxs = testData.xs.reshape([testDataSize, IMAGE_WIDTH, IMAGE_HEIGHT, 1]);
  const labels = testData.labels;
  const preds = model.predict(testxs);

  console.log(preds.data());//error:Uncaught TypeError: tf.util.convertBackendValuesAndArrayBuffer is not a function**
  
  testxs.dispose();
  labels.dispose();
  preds.dispose();
}

await tf.setBackend('webgpu');

const data = new MnistData();
await data.load();

const model = await tf.loadLayersModel('./tfmodel.json');
await doPrediction(model,data);

**Comment by qjia7** [comment]
@lebron8dong Please also update your tfjs-core to latest and have a try.

**Comment by lebron8dong** [comment]
thanks，it works for me.
