### ISSUE TITLE
Under the backend of webgpu, how to print the output of the model to the console？

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7368]
const res = model.predict(test);
res. print()；
error：WebGPU readSync is only available for CPU-resident tensors.
Under the backend of webgpu, I want to print the result on the console, is this possible?

**Comment by qjia7** [comment]
Try `const data = await res.data(); console.log(data)`.

**Comment by shmishra99** [comment]
Hi @lebron8dong ,

In addition to @qjia7's suggestion, here are a few other potential solutions that may help you to resolve your issue.
```
const modelUrl =
    'https://storage.googleapis.com/tfjs-models/savedmodel/mobilenet_v2_1.0_224/model.json';
const model = await tf.loadGraphModel(modelUrl);
const zeros = await tf.zeros([1, 224, 224, 3]);
const res = await model.predictAsync(zeros)
console.log("Backend",tf.getBackend())
 // or 
//const res =  model.predict(zeros)
res.print()
//or
//console.log(res)
```
The output will be printed as tensor:
```
Backend webgpu
Tensor
     [[-0.1800361, -0.4059966, 0.8190175, ..., -0.8953388, -1.084165, 1.2912748],]
```
Let me know if it works for you. Thank You!!

**Comment by qjia7** [comment]
@lebron8dong Your code should work since tfjs-backend-webgpu 4.6.0. We have added the readSync support by #7576.
