### ISSUE TITLE
Typo in https://github.com/tensorflow/tfjs-models/tree/master/speech-commands/README.md

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#737]
performs predicton

**Comment by thekevinscott** [comment]
https://github.com/tensorflow/tfjs-models/pull/78/files

**Comment by davidsoergel** [comment]
@thekevinscott Happy to accept the PR, but can't without your signing the CLA.  Sorry for the red tape-- I know it's silly in this case.  If you don't want to do it then we'll just recapitulate the fix, no problem.  Thanks!

**Comment by thekevinscott** [comment]
Ah my bad! One sec

**Comment by davidsoergel** [comment]
Thanks!

@thekevinscott fixed in tfjs-models#78.
