### ISSUE TITLE
webgl: the correctness usage of GLSL round function in ResizeNearestNeigborBackpropProgram kernel

### ISSUE THREAD

**Issue by xhcao** [tensorflow/tfjs#7373]
I have been implementing `ResizeNearestNeighborGrad` kernel on tfjs webgpu backend and referring cpu | webgl implementations. The cpu | webgl | webgpu backends all use the 'round(x)` function to implement this kernel with the similar code, but I found their behaviors were different on these backends when the fractional portion of `x` is exactly 0.5(halfway cases).

cpu backend
The `ResizeNearestNeighborGrad` kernel on cpu backend uses `round` function in [here](https://github.com/tensorflow/tfjs/blob/963589ec3f806e914c9779d0e32d0ba4a933698c/tfjs-backend-cpu/src/kernels/ResizeNearestNeighborGrad.ts#L97), [js spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) defines a clear behavior of `round(x)` if the fractional portion is exactly 0.5, the argument is rounded to the next integer in the direction of +∞.
so for example, round(1.5) = 2, round(2.5) = 3.

webgpu backend
[WGSL spec](https://www.w3.org/TR/WGSL/#round-builtin:~:text=or%20vecN%3CS%3E-,Description,-Result%20is%20the) also defines a clear behavior of `round(x)`, halfway cases are rounded to the nearest even. The behavior is different for cpu js `round(x)` behavior, we will use `floor(x + 0.5)` to work around this issue.

webgl backend
[GLSL spec](https://registry.khronos.org/OpenGL-Refpages/gl4/html/round.xhtml) DOES NOT define a clear behavior of `round(x)`, the fraction 0.5 will round in a direction chosen by the implementation, presumably the direction that is fastest. This includes the possibility that round(x) returns the same value as roundEven(x) for all values of x. In theory, fox example, round(1.5)=1|2, round(2.5)=2|3, there may be an error for the `ResizeNearestNeighborGrad` kernel on webgl backend when running on some machines.  If my investigation is correct, is there a bug on the webgl backend?

**Comment by xhcao** [comment]
There is no undefined behavior of `round` in webgl backend, because this backend had re-defined the built-in function in https://github.com/tensorflow/tfjs/blob/8c835f0ee5501fc1b053872ca8498fe5fc52ef84/tfjs-backend-webgl/src/glsl_version.ts#L83, it also used `floor(x + 0.5)` to simulate `round(x)`.
So I will close this issue.

**Comment by gyagp** [comment]
Great finding! Always using floor(x+0.5) for round half may be not ideal for some scenarios. For example, round to even is more suitable sometimes (https://blogs.sas.com/content/iml/2019/11/11/round-to-even.html has more details). 
Anyway, for this case, we have a unified and good behavior among backends.
