### ISSUE TITLE
[Codelab]: TensorFlowJS Retrain a comment spam detection model to handle edge cases -- file not found

### ISSUE THREAD

**Issue by ConkyTheGreat** [tensorflow/tfjs#7389]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): N/A
- TensorFlow.js version (use command below): N/A
- Browser version: N/A
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**

When working through [this codelab example](https://codelabs.developers.google.com/tensorflow-retraining-comment-spam-detection#3), it instructs the user to use the following code:

`data_file = tf.keras.utils.get_file(fname='comment-spam-extras.csv', origin='https://storage.googleapis.com/laurencemoroney-blog.appspot.com/jm_blog_comments_extras.csv', extract=False)`

Navigating to the link [https://storage.googleapis.com/laurencemoroney-blog.appspot.com/jm_blog_comments_extras.csv](https://storage.googleapis.com/laurencemoroney-blog.appspot.com/jm_blog_comments_extras.csv) results in a 404 not found error.

**Comment by tnc-tianwen** [comment]
Same here

**Comment by jasonmayes** [comment]
Thanks for this. For now please use:

https://storage.googleapis.com/jmstore/TensorFlowJS/EdX/code/6.5/jm_blog_comments_extras.csv  

I shall work on updating the codelab to use this instead.

**Comment by jasonmayes** [comment]
Fix has been set to publish shortly. For those having trouble right now please use my URL above which is what I will be updating the Codelab to.
