### ISSUE TITLE
Error: Kernel 'BinomialFilter' not registered for backend 'tensorflow'

### ISSUE THREAD

**Issue by torres-developer** [tensorflow/tfjs#7396]
**System information**
- OS Platform and Distribution: 
        - uname -a output: `Linux MrDestructoid 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux`.
        - OS: Arch Linux
        - CPU: AMD A8-4555M APU (4) @ 1.6GHz
        - RAM: 8GB
- TensorFlow.js installed from: npm with `yarn add @tensorflow/tfjs-node`
- TensorFlow.js version: ^3.7.0
- Node version: v19.6.1

I'm not running code I wrote, the code it's from [here](https://pictarize.com/image-analyzer/). The original code use the non-node version of the tensorflow. What I did with the code was a replacing all the tfjs imports to tfjs-node.

[log.txt](https://github.com/tensorflow/tfjs/files/10783446/log.txt)

I have no experience with tensorflow at all so sorry if this is an easy error to find a solution.

Thank you in advance :)

**Comment by srivatsan2607** [comment]
Any update or solution on this?

**Comment by torres-developer** [comment]
> Any update or solution on this?

I did not found a solution for this problem.

**Comment by gaikwadrahul8** [comment]
Hi, @torres-developer 

Apologize for the delayed response and could you please help me with the exact steps to replicate the same issue from my end ? 

Meanwhile, could you please give it try with latest version of `@tensorflow/tfjs-node@4.10.0` and see is it resolving your issue or not ? Thank you!
