### ISSUE TITLE
Webgl backend does not work with ios 16.4 beta on iphone 

### ISSUE THREAD

**Issue by sacha-6over6** [tensorflow/tfjs#7399]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Both custom code multiple projects and your demos
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 13 (probably all)
- TensorFlow.js installed from (npm or script link): npm 
- TensorFlow.js version (use command below): tested versions (@tensorflow/tfjs-backend-webgl@4.2.0, @tensorflow/tfjs@4.2.0), (@tensorflow/tfjs-backend-webgl@3.20.0, @tensorflow/tfjs@3.20.0)
- Browser version: safari 16.4
- Tensorflow.js Converter Version: @tensorflow/tfjs-converter@3.20.0, @tensorflow/tfjs-converter@4.2.0

**Describe the current behavior**
Can not estimateFaces or executeAsync it just freezes there

**Describe the expected behavior**
Should get results and flow should continue

**Standalone code to reproduce the issue**
-MAKE SURE ON WEBGL BACKEND basically any demo example or code I run has this issue
https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=posenet
https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh - switch to webgl backend

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
@sacha-6over6 When you open the demo or switch to WebGL backend, the UI is expected to be frorzen for a while because backend setup, model loading and model's first inference are all quite time-consuming.

I just tried the both examples on a iPhone XS (16.2 OS) and they work (frozen within 30 seconds).

**Comment by sacha-6over6** [comment]
Hi yes the problem is specific with iOS 16.4 all earlier versions are ok. It is currently in beta for release in March.

**Comment by Linchenn** [comment]
@sacha-6over6  Could you help verify if it works? We have submitted a fixed.
