### ISSUE TITLE
Importing Tensorflow Model - get_tensor_by_name

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#74]
_From @Neuroforge on March 23, 2018 2:11_

Hello,

When using an imported Tensorflow model is there a set of comparable instructions?

For instance, if in Python with Tensorflow you use get_tensor_by_name to return a tensor.

Is there a comparable approach in deepleanjs once you've imported the model?

Regards,

Daniel

_Copied from original issue: tensorflow/tfjs-core#885_

**Comment by dsmilkov** [comment]
_From @nsthorat on March 23, 2018 19:38_

Once you've imported the model the name that's used in get_tensor_by_name from TensorFlow should be the same name you use from the response of the CheckpointLoader call.

**Comment by dsmilkov** [comment]
Hi @Neuroforge,

First, we are excited to announce that deeplearn.js joined TensorFlow as TensorFlow.js. We just released a [tool](https://github.com/tensorflow/tfjs-converter) that can automatically convert a TensorFlow SavedModel and a Keras model to a format for TensorFlow.js, and we've moved the CheckpointLoader to the [pair-code/deeplearnjs-legacy-loader](https://github.com/PAIR-code/deeplearnjs-legacy-loader) repo.

I'm closing this thread for now, but feel free to reopen if you run into issues. Thanks!

**Comment by Neuroforge** [comment]
Thank you for your help.

I have used the checkpointloader to create the manifest.json and layer files. I could proceed to use deeplearnjs with the these files. Great!

I am interested in moving forward with TensorFlowJs....

So I have the graph.pb, graph_opt.pb and graph_freeze.pb files so i tried the new tensorflowjs-converter.

`tensorflowjs_converter --input_format=tf_saved_model mobilenet_thin output
`

(mobilenet_thin is a directory that contains graph.pb, graph_opt.pb and graph_freeze.pb)

I've used this but it returns an error....

> Hal:tfjs-converter daniel$ tensorflowjs_converter --input_format=tf_saved_model mobilenet_thin output
> /Users/daniel/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/Users/daniel/miniconda2/bin/tensorflowjs_converter", line 11, in <module>
>     sys.exit(main())
>   File "/Users/daniel/miniconda2/lib/python2.7/site-packages/tensorflowjs/converters/converter.py", line 125, in main
>     FLAGS.output_dir, saved_model_tags=FLAGS.saved_model_tags)
>   File "/Users/daniel/miniconda2/lib/python2.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 181, in convert_tf_saved_model
>     input_saved_model_dir=saved_model_dir)
>   File "/Users/daniel/miniconda2/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 229, in freeze_graph
>     input_saved_model_dir, saved_model_tags).graph_def
>   File "/Users/daniel/miniconda2/lib/python2.7/site-packages/tensorflow/python/tools/saved_model_utils.py", line 42, in get_meta_graph_def
>     saved_model = reader.read_saved_model(saved_model_dir)
>   File "/Users/daniel/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/saved_model/python/saved_model/reader.py", line 55, in read_saved_model
>     raise IOError("SavedModel file does not exist at: %s" % saved_model_dir)
> IOError: SavedModel file does not exist at: mobilenet_thin
> 

What am i doing wrong? Do you have any advice?

**Comment by nsthorat** [comment]
Ping, can you take a look?

**Comment by pyu10055** [comment]
@Neuroforge The converter only supports SavedModel format, not the checkpoint + metadata format, the latter is deprecated by Tensorflow.

You can take a look at TensorFlow document for SavedModel, https://www.tensorflow.org/programmers_guide/saved_model

**Comment by pyu10055** [comment]
closing this since the session bundle is supported.

**Comment by simonefrancia** [comment]
Hi, 
recently we tried to convert a tf SessionBundle to tfjs, but we got this problem. 

```tensorflowjs_converter --input_format=tf_session_bundle --output_node_names='output/dense/Tensordot/Reshape' --output_format=tensorflowjs /root/converter/input_model /root/converter/converted_model

Using TensorFlow backend.
Tensorflow has deprecated the Session Bundle format,  please migrate to SavedModel.
Loaded meta graph file '/root/converter/model1/model_epoch_20_gs_34060.meta
2018-07-27 12:44:30.703950: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Unsupported Ops in the model
MatrixBandPart, RandomShuffleQueueV2, QueueDequeueManyV2, BatchMatMul
```
Thanks
