### ISSUE TITLE
Docker M2 Macbook ARM invalid ELF header

### ISSUE THREAD

**Issue by maxmaxmaxmaxmaxmaxmax** [tensorflow/tfjs#7400]
I use a M2 MacBook.
We integrate tensorflow/tfjs into our nestJS backend. 
When I start the nestJS enviorment for itself, everthing is fine, and tensorflow works.
Wenn I use Docker to deploy it on a DigitalOcean Dropet, everything is fine and tensorflow works.

**Describe the problem**

When i use the same Dockerfile (which i use to deploy on digital ocean) to start it local on my M2, it crashs. 
```
NODE_OPTIONS='--max-old-space-size=3000' nest start
2023-02-20 18:21:41 Error: /usr/src/app/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: invalid ELF header
2023-02-20 18:21:41     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
2023-02-20 18:21:41     at Module.load (node:internal/modules/cjs/loader:1081:32)
2023-02-20 18:21:41     at Function.Module._load (node:internal/modules/cjs/loader:922:12)
2023-02-20 18:21:41     at Module.require (node:internal/modules/cjs/loader:1105:19)
2023-02-20 18:21:41     at require (node:internal/modules/cjs/helpers:103:18)
2023-02-20 18:21:41     at Object.<anonymous> (/usr/src/app/node_modules/@tensorflow/tfjs-node/dist/index.js:72:16)
2023-02-20 18:21:41     at Module._compile (node:internal/modules/cjs/loader:1218:14)
2023-02-20 18:21:41     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
2023-02-20 18:21:41     at Module.load (node:internal/modules/cjs/loader:1081:32)
2023-02-20 18:21:41     at Function.Module._load (node:internal/modules/cjs/loader:922:12)
2023-02-20 18:21:41 error Command failed with exit code 1.
```

### Dockerfile
```
FROM node:18.12.1

EXPOSE 8080

WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

CMD [ "yarn","start"]
```

### These were my previous solutions that did not work 

1. Add    ` platform: linux/amd64` to the correct place in the docker-compose file,  whit this result
<img width="118" alt="image" src="https://user-images.githubusercontent.com/125969421/220311961-6415f84c-2628-4408-85af-08befaa5e789.png">

Thanks for helping me :)

**Comment by maxmaxmaxmaxmaxmaxmax** [comment]
Hi @mattsoulanille can you help me?:)

**Comment by gaikwadrahul8** [comment]
Hi, @maxmaxmaxmaxmaxmaxmax 

Apologize for the delayed response and I found some similar issues on Stack-overflow and those are not exactly related with Docker M2 Mackbook but which may help you to solve your issue so please have look into these [Ref-1](https://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app), [Ref-2 ](https://forums.balena.io/t/help-to-debug-nodejs-docker-raspberrypi3-error-invalid-elf-header/4776)

To solve this problem for a Docker container you can do something like below if you haven't done because If you are running inside a docker container as I am, all you need is a `.dockerignore` with `node_modules` specified in it.Some libraries need to be compiled on the host machine and therefore your modules can be stale..

You can create a .dockerignore with this configuration :

```
node_modules/
dist/
```
Could you please give it try with above workaround and check whether your issue is resolving or not ? If issue still persists please let us know ? Thank you

**Comment by maxmaxmaxmaxmaxmaxmax** [comment]
Thanks for your help :)

I get the same problem:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/125969421/226599028-dc84ee4a-652e-4d40-8c3a-26499aa718f3.png">

Also if i add 
  platform: linux/amd64
to the docker-compose config

**Comment by gaikwadrahul8** [comment]
Hi, @maxmaxmaxmaxmaxmaxmax 

Apologize for the delayed response and thank you for trying above workaround. I'm not sure at the moment whether this issue  is specific to` M2 Mackbook ` or `tensorflow/tfjs `. We have seen similar error when users build docker image with local OS and trying to use with docker container in that case docker context is copying everything from root folder to destination container working directory `node_modules` (& loading mechanism as per host OS) is also copied to container working directory.

In that case we add  `.dockerignore` file and we add `node_modules` and `npm-debug.log`
And now when we will build container, it will build everything as per container's OS and we will not get `invalid ELF header error` 

It seem like we have to dig more into this issue so we'll update you soon. Thank you!

CC :@mattsoulanille

**Comment by boomsi** [comment]
Get the same problem.

Macos 13.3  M2pro 
Docker with node:16.19.1-slim

<img width="722" alt="image" src="https://user-images.githubusercontent.com/39713960/231040077-66f70f89-bb38-43be-b4b8-ef2d790a0cd5.png">

How to fix this?

**Comment by zeemo25** [comment]
+1 same problem

**Comment by MRDNZ** [comment]
+1 same problem

**Comment by gaikwadrahul8** [comment]
Hi, @maxmaxmaxmaxmaxmaxmax 

Apologize for the delayed response, Could you please help us with code example and steps to reproduce the same issue from our end ? It would be helpful to dig more into your issue. Thank you!

**Comment by malkevych** [comment]
I also have this issue

**Comment by esnayder421** [comment]
Tengo el mismo problema, estoy tratando de ejecutar el codigo en un cpanel y me sale el siguiente error: node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node: invalid ELF header

**Comment by pavelzubov** [comment]
Get the same problem.
Chip Apple M2 Pro
macOS Sonoma 14.6.1

**Comment by dariosalvi78** [comment]
same issue here!

**Comment by dariosalvi78** [comment]
ok got it to work by adding node_modules in the dockerignore file. This implies that you need to recompile tensorflow though! make sure to run the following in the Dockerfile

```
RUN npm rebuild @tensorflow/tfjs-node --build-from-source 
```

some dependencies are needed, including Python, so choose a relatively complete base image (like a full Debian)
