### ISSUE TITLE
The shape of dict['input'] provided in model.execute(dict) must be [-1,256,256,3], but was [1,300,300,3]

### ISSUE THREAD

**Issue by shuizhuyu1015** [tensorflow/tfjs#7406]
I have an error when using the load() method of coco-ssd.
`this.ssd = await cocossd.load({modelUrl: MODEL_URL});`

 Error: The shape of dict['input'] provided in model.execute(dict) must be [-1,256,256,3], but was [1,300,300,3]

How can I fix it, thanks!

**Comment by shmishra99** [comment]
Hi @shuizhuyu1015 ,
Can you please fill the issue [template](https://github.com/tensorflow/tfjs/issues/new/choose). It saves our overall time to understand and execute the issues. Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!
