### ISSUE TITLE
wasm backend kernel `Fill` dtype not optional

### ISSUE THREAD

**Issue by sklum** [tensorflow/tfjs#7408]
For the `Fill` kernel, the `webgl` backend [uses](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/src/kernels/Fill.ts#L29) `util.inferDtype` to determine data type which has the functionality described in the docs: `The type of an element in the resulting tensor. Defaults to 'float'.`

The `wasm` backend [does not use](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/src/kernels/Fill.ts#L24) `util.inferDtype`, and as written the `dtype` argument is not optional (you'll get an unrecognized dtype `undefined` error if unspecified).

Happy to open a PR that fixes this if that'd be helpful.

**Comment by chunnienc** [comment]
Hi @sklum,

Thanks for your report! I can confirm it's a bug as you described. Feel free to open a PR if you could!

**Comment by gaikwadrahul8** [comment]
Hi, @sklum 

Apologize for the delayed response and just to confirm, May I know do have workaround to take care of this issue ? If yes, would you like to submit PR from your end or do you want to take care of this issue from our end ? Thank you!

**Comment by sklum** [comment]
Hi @gaikwadrahul8.  I haven't had time to get a PR up although I expect to within a week or two.  Feel free to implement if you can get it done before then.

The workaround is simply to specify the `dtype` (i.e. treat the parameter as non-optional).

**Comment by gaikwadrahul8** [comment]
Hi, @sklum 

Please take your time and submit PR to take care of this issue from your end and our team will review your PR and if everything looks good team will merge your PR. Thank you!

**Comment by sklum** [comment]
Hi @chunnienc, sorry for the delay in fixing this.  Turns out you fixed it in another commit.  Please see the referenced PR and let me know if you'd like me do anything else.
