### ISSUE TITLE
Mismatched output shape using transfer learning with the Speech Command Recognizer

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#742]
#### TensorFlow.js version
{tfjs-core: "0.13.2", tfjs-layers: "0.8.1", tfjs-converter: "0.6.1", tfjs: "0.13.1"}

#### Browser version
Version 69.0.3497.92 (Official Build) (64-bit)

#### Describe the problem 
After copying the sample code in the Transfer Learning instructions from https://github.com/tensorflow/tfjs-models/tree/master/speech-commands and running it in Chrome I get the following error:

speech-commands.js:466 Uncaught (in promise) Error: Mismatch between the last dimension of model's output shape (20) and number of words (4).
    at TransferBrowserFftSpeechCommandRecognizer.<anonymous> (speech-commands.js:466)
    at step (speech-commands.js:65)
    at Object.next (speech-commands.js:46)
    at fulfilled (speech-commands.js:36)

#### Code to reproduce the bug / link to feature request
Transfer Learning instructions from https://github.com/tensorflow/tfjs-models/tree/master/speech-commands

**Comment by ToonTalk** [comment]
By adding 16 more (color) collectExamples the error goes away

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
