### ISSUE TITLE
React Native Expo 47 loadGraphModel undefined is not a function.

### ISSUE THREAD

**Issue by fbotalla** [tensorflow/tfjs#7421]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No, I just have up to date libraries. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacBook Pro Apple M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 12
- TensorFlow.js installed from (npm or script link): yes
- TensorFlow.js version (use command below):  
    "@tensorflow/tfjs": "^4.2.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
- Browser version: n/a
- Tensorflow.js Converter Version: n/a

**Describe the current behavior**
tf.ready() resolves, but then loadGraphModel undefined is not a function

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This is my current package.json
` "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-firebase/app": "14.1.0",
    "@tensorflow/tfjs": "^4.2.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo": "^47.0.0",
    "expo-camera": "~13.1.0",
    "expo-file-system": "~15.1.1",
    "expo-gl": "~12.0.1",
    "expo-gl-cpp": "^11.4.0",
    "expo-image-picker": "~14.0.2",
    "expo-modules-core": "~1.0.4 || ~1.1.1",
    "native-base": "^3.4.25",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-fs": "^2.20.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-svg": "12.1.1"`

**Comment by gaikwadrahul8** [comment]
Hi, @fbotalla 

Apologize for the delayed response and It's known issue to us which is package dependancies compatibility issue between `react-native` and `expo 47` and we're looking help from TFJs community to work on this issue 

You can refer simialar issue https://github.com/tensorflow/tfjs/issues/7853

If you don't have strong dependancy to use `Expo 47 `then if possible could you please try to downgrade the Expo version or else please try to add package dependancies which are mentioned in this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native). Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```
