### ISSUE TITLE
webgl shapes uniform causes some model results to be zero

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#7430]
as the subject line says, setting `tf.env().set('WEBGL_USE_SHAPES_UNIFORMS', true);` causes some strange model inference output results. specifically, [movenet-multipose](https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1) reports all ZEROs for `pose.score` (resulting tensor is array of 6 poses and `pose.score` is very last value of each pose). strangely, no other tensor values seem to be impacted.

setting `tf.env().set('WEBGL_USE_SHAPES_UNIFORMS', false);` results in expected values being returned (valid score values)

reproducible using built-in demo: <https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=movenet&type=multipose> once `USE_SHAPES_UNIFORMS` is enabled

*environment*: chrome 110 on windows 11 using tfjs 4.2.0

**Comment by qjia7** [comment]
@vladmandic I tested it on https://tfjs-benchmarks.web.app/local-benchmark/?task=correctness&benchmark=MoveNet-MultiPose&WEBGL_USE_SHAPES_UNIFORMS=true&backend=webgl and the result is `<html>
<body>


Prediction matches CPU | true
-- | --



</body>
</html>`

Do I miss anything? And what's your GPU device?

**Comment by vladmandic** [comment]
gpu is nvidia rtx3060 (and i have multiple users reporting same issue while using different gpus).
what are the values you see for `pose.score`? normal results would be 0.2-0.8 if anything is visible in input.
but when `WEBGL_USE_SHAPES_UNIFORMS` is enabled, results are 0 or near-zero (e.g. 0.001).

**Comment by qjia7** [comment]
The basic model `https://storage.googleapis.com/tfhub-tfjs-modules/google/tfjs-model/movenet/multipose/lightning/1/model.json` 's predict result is a tensor. From the above benchmark, we can see that the model's predict has no problem. So the error may happen during the post-processing from the predict data to get the `pose.score` or preprocessing for the model input.

**Comment by vladmandic** [comment]
@qjia7 thanks for trying to reproduce - i cannot explain why it seems to work on your system.

here are results from my app:

```js
const res = model.execute(input);
const data = await res.array();
console.log(data[0][0]); // print data for poseid=0 only, data is 17 keypoints [x,yscore] + box [y0,x0,y1,x1,score]
```

input is image, so no data variation. and no data post-processing (that happens later).  
everything else is exactly the same, only difference is uniforms on/off.  

> with WEBGL_USE_SHAPES_UNIFORMS=True

```json
[
    0.06291937828063965, 0.4957132041454315, 0,
    0.05064710974693298, 0.5142326354980469, 0,
    0.05513744801282883, 0.5142754316329956, 0,
    0.059041570872068405, 0.5562960505485535, 0,
    0.05972248688340187, 0.46609821915626526, 0,
    0.20758245885372162, 0.636425256729126, 0.0001393281709169969,
    0.19731391966342926, 0.4072492718696594, 0.00001283355595660396,
    0.331411212682724, 0.718897819519043, 0.002150086686015129,
    0.31960925459861755, 0.35317930579185486, 0.00010488666157471016,
    0.46474772691726685, 0.7711447477340698, 0,
    0.44408977031707764, 0.2565067708492279, 0,
    0.42969927191734314, 0.5220178961753845, 0,
    0.4305756092071533, 0.45760345458984375, 0,
    0.7566355466842651, 0.5221276879310608, 0,
    0.7071350812911987, 0.4616428315639496, 0,
    0.9442293047904968, 0.5520567297935486, 0,
    0.930330216884613, 0.45988771319389343, 0,
    0.007275611162185669, 0.17657437920570374, 0.988817572593689, 0.7982285022735596, 0
]
````

> with WEBGL_USE_SHAPES_UNIFORMS=False

```json
[
    0.09057106077671051, 0.4700106382369995, 0.7452993392944336,
    0.07174623757600784, 0.4958937168121338, 0.8412675857543945,
    0.07318592071533203, 0.4608907699584961, 0.8572373986244202,
    0.09064336866140366, 0.5357258319854736, 0.8364978432655334,
    0.08527234196662903, 0.463538259267807, 0.7937716245651245,
    0.18924307823181152, 0.5823675394058228, 0.905443012714386,
    0.1991117298603058, 0.4322003424167633, 0.93937748670578,
    0.31236758828163147, 0.6706163287162781, 0.9288367629051208,
    0.32263651490211487, 0.35593748092651367, 0.8821172714233398,
    0.4310790002346039, 0.7494174838066101, 0.8445347547531128,
    0.4145127534866333, 0.24147240817546844, 0.9300219416618347,
    0.43383148312568665, 0.5482231378555298, 0.8800678253173828,
    0.4325222373008728, 0.4511417746543884, 0.9096640348434448,
    0.688278317451477, 0.5492151379585266, 0.9255422353744507,
    0.6857750415802002, 0.4626540541648865, 0.9438669681549072,
    0.9114065766334534, 0.5597853064537048, 0.8775557279586792,
    0.8953736424446106, 0.48482516407966614, 0.9125415086746216,
    0.007275611162185669, 0.17657437920570374, 0.988817572593689, 0.7982285022735596, 0.8622878789901733
]
```

you can see that all values are different, but biggest difference is in the last column which is score  
with uniforms enabled, score is either 0 or near-zero for all points and box.
and with no uniforms, all scores are >75%.

any suggestion on how to proceed?

**Comment by qjia7** [comment]
I see the only difference is I am using a `const input = tf.zeros([1, 256, 256, 3], 'int32');` zero tensor as input to test. Can you share the steps to get the image tensor? 
How's your result to run `https://tfjs-benchmarks.web.app/local-benchmark/?task=correctness&benchmark=MoveNet-MultiPose&WEBGL_USE_SHAPES_UNIFORMS=true&backend=webgl `?

**Comment by vladmandic** [comment]
> Can you share the steps to get the image tensor?

load image -> draw on canvas -> read canvas using `tf.browser.fromPixelsAsync()`

> How's your result to run

pass.

i'll work to get a sharable reproduction with you.
it could be (again) that its combo of different settings that is triggering this, but disabling shapes-uniforms that solves it for me
if you have any other ideas, let me know.

**Comment by benoitparis** [comment]
I have tensor shape issues as well on this maybe related issue:

https://github.com/tensorflow/tfjs/issues/7448

**Comment by gaikwadrahul8** [comment]
Hi, @vladmandic 

Apologize for the delayed response and Just to confirm, are you working on this to share code with us to replicate the same issue from our end ? 

As you mentioned in your previous comment after setting `tf.env().set('WEBGL_USE_SHAPES_UNIFORMS', false);` your issue got solved so do you want to keep this issue open ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
