### ISSUE TITLE
Face tilt direction ( left | right | up | down | centre )

### ISSUE THREAD

**Issue by gauravmankotia** [tensorflow/tfjs#7435]
Hi there, 
In my react project, I am using @tensorflow/tfjs v4.2.0 and tensorflow-models/face-landmarks-detection v1.0.2 to detect face from webcam or any other input source. I am able to detect faces and get landmarks but I also want to know if the face is tilted in any direction ( left | right | up | down | centre ). I have searched many thread for the same but was not able to find any solution for the same. Can you please help me out with this?

**System information**
- Nodejs version: 19.7.0
- Reactjs version: 18.2.0
- TensorFlow.js version (you are using): 4.2.0
- Are you willing to contribute it (Yes/No): Yes

**Comment by vladmandic** [comment]
this is my implementation <https://github.com/vladmandic/human/blob/main/src/face/angles.ts>

**Comment by gauravmankotia** [comment]
Thank for reply @vladmandic ,
I tried implementing angles.ts as per your implementation, I am still unable to get the desired results. All the attributes are always 0 for angle, gaze and matrix.

```
angle: {pitch: 0, yaw: 0, roll: 0}
App.js:54 gaze: {bearing: 0, strength: 0}
App.js:55 matrix: (9) [1, 0, 0, 0, 1, 0, 0, 0, 1]
index.js:214 leftEye: (17) [263, 249, 390, 373, 374, 380, 381, 382, 263, 466, 388, 387, 386, 385, 384, 398, 362]
```

Will you please explain your code/logic or share a wrapper function in js while can directly do the work of calculation.
As of now I am able to get the face from face-landmark-detection node_module and can plot the bounding box and face mesh on it. Also have the contours but they do not update with respect to face direction. Please show me a way to implement it and what logic needs to be applied in order to get the expected result.

**Comment by gauravmankotia** [comment]
Thank for reply @vladmandic ,
I tried implementing angles.ts as per your implementation, I am still unable to get the desired results. All the attributes are always 0 for angle, gaze and matrix.

```
angle: {pitch: 0, yaw: 0, roll: 0}
App.js:54 gaze: {bearing: 0, strength: 0}
App.js:55 matrix: (9) [1, 0, 0, 0, 1, 0, 0, 0, 1]
index.js:214 leftEye: (17) [263, 249, 390, 373, 374, 380, 381, 382, 263, 466, 388, 387, 386, 385, 384, 398, 362]
```


Will you please explain your code/logic or share a wrapper function in js while can directly do the work of calculation.
As of now I am able to get the face from face-landmark-detection node_module and can plot the bounding box and face mesh on it. Also have the contours but they do not update with respect to face direction. Please show me a way to implement it and what logic needs to be applied in order to get the expected result.

**Comment by vladmandic** [comment]
i cannot provide implementation for you, but 99% chance your inputs are not in the same format.
my implementation requires input to be `face` object with `mesh` (468 or 478pt mesh points normalized to screen resolution) and `meshRaw` properties (468 or 478pt mesh points normalized to 0..1 range) and `imageSize` with [width,height] properties.

**Comment by gauravmankotia** [comment]
Hi @vladmandic ,
So, I am using your face-api (**https://cdn.jsdelivr.net/npm/@vladmandic/face-api/dist/face-api.js**) in web worker. But the problem I am facing now is that it's not loading the models and an exception is thrown "**face-api.js:4881 Uncaught (in promise) Error: getEnv - environment is not defined, check isNodejs() and isBrowser()**"


<img width="713" alt="Screenshot 2023-03-10 at 8 47 19 PM" src="https://user-images.githubusercontent.com/71925534/224353607-aed32dcc-5b1e-42cf-83fd-7af4165ff019.png">


Any idea how to handle it?

**Comment by vladmandic** [comment]
@gauravmankotia 

1. if you have issues with `face-api`, why post here - please open issue in that repository
2. `face-api` is an old code base and while its still maintained, it never claimed support for webworkers (and it cant due to heavy dependency on dom)
3. newer `human` library that i mentioned before fully supports webworkers.

**Comment by gauravmankotia** [comment]
Thanks for the quick reply. Yeah sure.
