### ISSUE TITLE
The tf.loadModel()  does not works for tensorflow keras models

### ISSUE THREAD

**Issue by Aryanr64x** [tensorflow/tfjs#744]
I am using tensorflow js to load a model from keras following [This Guideline](https://js.tensorflow.org/tutorials/import-keras.html) However on this line of code

`const model = await tf.loadModel('https://foo.bar/tfjs_artifacts/model.json');`
I am getting the error

**Error: Sequential.fromConfig called without an array of configs
at new t (app.js:26972)
at t.fromConfig (app.js:26972)
at deserializeKerasObject (app.js:26972)
at deserialize (app.js:26972)
at app.js:26972
at app.js:26972
at Object.next (app.js:26972)
at o (app.js:26972)**
I think this happens only with keras model  .

Note:I have enabled cors in my server so I don't think its a problem related to my server . I am using a localhost(Not the one mentioned in guideline) Also as mentioned in the docs I have used

tfjs.keras.converters.save_keras_model() in the python side

**Comment by davidsoergel** [comment]
Just want to point out here that although tensorflow/tfjs-layers#332 now allows reading the new format produced by TF 1.11 (Sequential config is a dict containing a 'layers' array), we are still *writing* the old format (Sequential config is itself the layers array).

At some point we should consider whether Sequential.getConfig() should also write the new format (ideally as part of a clear version compatibility story).

**Comment by cbasavaraj** [comment]
Hi, I still get an error on tf.loadModel(MODEL_URL):

> Unhandled Promise Rejection: Error: Sequential.fromConfig called without an array of configs

I have upgraded to the latest versions of Keras and tfjs. Am I missing anything? Thanks

**Comment by caisq** [comment]
@cbasavaraj What version of tensorflow.js are you using? If it is the latest version, can you provide your model.json for us to reproduce your error?

**Comment by cbasavaraj** [comment]
Hi, I am using tfjs 0.6.7. How do I share the model.json with you? It has 5k lines, but quite a simple model, a MobileNet classifier. Can I email it to you?

**Comment by nsthorat** [comment]
That is a very old version of tfjs, the newest is` 0.13.5`.

**Comment by caisq** [comment]
@cbasavaraj 0.6.7 seems to be the version of the tensorflowjs *python* package you are using. What is the version of the TensorFlow.js *JavaScript* library you are using? You can find that out by something like `console.log(tf.version)`.

To share the file, maybe you can drag and drop a zip file into GitHub comment boxes.

**Comment by cbasavaraj** [comment]
Hi @caisq, were you able to look at this again? I really need to fix this for a client, and can't find many other references to this issue on the Internet. Thanks

**Comment by caisq** [comment]
@cbasavaraj So you are using tfjs version 0.12.5, which is old. Can you use the latest version (0.13.5) which should have incorporated the fix to this known issue?

**Comment by cbasavaraj** [comment]
I did `pip install --upgrade tensorflowjs` which gives me 0.6.7 for the _python_ package. I built tensorflow from source (as I am using CUDA 9.1 on Ubuntu). How do I upgrade the _JavaScript_ library? Thanks!

**Comment by caisq** [comment]
@cbasavaraj The thread we are having here is going off-topic for this GitHub issue. Can we follow-up at this discussion board? https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs 

If you can post your question there, along with information on how you are using the JS part of TensorFlow.js currently (through script src? througn npm?), I'll be happy to continue helping you there.
