### ISSUE TITLE
how TensorFlow.js measures the running time of each layer of the model?

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7447]
how show the latency of each layer?

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Aplogize for the delay and As far I know, there is no straight forward way to measure running time for each layer of the model but I found some articles which will help you to get some idea [Ref-1](https://towardsdatascience.com/the-correct-way-to-measure-inference-time-of-deep-neural-networks-304a54e5187f), [Ref-2 ](https://stackoverflow.com/questions/57853386/problem-measuring-the-time-elapsed-executing-my-code-in-tensorflow-js/57854393#57854393) and if you're looking for better performance with `TFJS` model then I would suggest you to go through our [official documentation](https://www.tensorflow.org/js/guide/platform_environment). I hope it will help you to resolve your issue. Thank you!

**Comment by lebron8dong** [comment]
@gaikwadrahul8  I want to get the execution time of each layer on tfjs when inferring, and make the results into a bar graph for analysis.

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Apologize for the delayed response and It seems like similar feature request #7427 and we have already being tracked on this issue #7427 so if this issue is same feature request then could you please close this issue ? Thank you!
