### ISSUE TITLE
Which is the optimal way to measure the execution time of each layer on tfjs when inferring?

### ISSUE THREAD

**Issue by lebron8dong** [tensorflow/tfjs#7452]
I want to get the execution time of each layer on tfjs when inferring, and make the results into a bar graph for analysis.

**Comment by gaikwadrahul8** [comment]
Hi, @lebron8dong 

Apologize for the delayed response, It seems like similar issue [#7427](https://github.com/tensorflow/tfjs/issues/7427) so could you please refer this [comment](https://github.com/tensorflow/tfjs/issues/7427#issuecomment-1458070794). Thank you!

**Comment by EliasVansteenkiste** [comment]
This is flops / layer, not execution times.

**Comment by EliasVansteenkiste** [comment]
> This is flops / layer, not execution times.
