### ISSUE TITLE
No way to create new react-native app with tfjs-react-native because of dependency issues???

### ISSUE THREAD

**Issue by rbmdotdev** [tensorflow/tfjs#7454]
<details><summary>Click to expand!</summary> 
 
 <details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tfjs-react-native-0.8.0

### Custom Code

Yes

### OS Platform and Distribution

all

### Mobile device

all

### Current Behaviour?

```shell
I hope I have just missed something dumb but I don’t think so as I have been struggling to get tfjs-react-native working for the last two days.

version 0.8.0 of this library seems to be unacceptably out of date as far as its dependencies go resulting in it not being possible.....as far as I can tell.....to instantiate a new react-native / expo app and add it as a dependency.  You have to jump through some major hoops to find expo and react SDK versions that might possibly support the versions of react and react-native this library expects and even then it still won't work for me.

There is at least 1 other ticket #7323 mentioning the fact that the libraries dependencies are so out of date that it looks like the library is not maintained at all.

The response to that ticket seems to be 'no it is maintained we will update it sometime'.  Can this please get resolved?
```

### Standalone code to reproduce the issue

```shell
follow this tutorial to create a new expo app https://docs.expo.dev/get-started/create-a-new-app/

then do npm i @tensorflow/tfjs-react-native

It will refuse to install due to conflicting react and react-native dependencies
```

### Relevant log output

_No response_</details></details>

**Comment by gaikwadrahul8** [comment]
Hi, @rbmdotdev 

Apologize for the delayed response and I see this PR [#7451 ](https://github.com/tensorflow/tfjs/pull/7451) got merged but that PR does not attempt to update the demo app or any expo dependencies. These will be updated in a later PR. you can check this [comment](https://github.com/tensorflow/tfjs/pull/7451#issue-1612353879). Thank you!

**Comment by rbmdotdev** [comment]
Should the library work with just react-native and no expo right now?

**Comment by Episodex** [comment]
I have the same issue. Can we use this with some older versions of expo and other packages? I'm trying to find the sweet spot of packages versions but still no luck. Can somebody provide the versions of expo, react, react-native etc that can run 0.8.0?

**Comment by mattsoulanille** [comment]
Sorry about the lack of communication on this issue. I have a [commit](https://github.com/tensorflow/tfjs/tree/bae8fba083cb1a9f3c0a16f70227064f379da9be/tfjs-react-native) of @tensorflow/tfjs-react-native that works with expo 47 and react-native 0.70.5, but I need to make sure our continuous integration tests can run it. We're looking into whether we can test with expo, or whether we'll need to eject into a standalone react native app. I should have an update on this next week.

**Comment by ParshuramKh** [comment]
is the issue resolved with latest react native and tensorflow?

**Comment by Priyanshu88** [comment]
At least upgrade the npm versions of your tensorflow related to react-native package so that we can use it with out own configuration. please!
