### ISSUE TITLE
[e2e] Fail to run tflite backend with WASM multi-thread support

### ISSUE THREAD

**Issue by Honry** [tensorflow/tfjs#7456]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): 4.2.0
- Browser version: Chrome Stable 110.0.5481.178
- Tensorflow.js Converter Version: 4.2.0

**Describe the current behavior**
I setup [tf.js e2e benchmark](https://github.com/tensorflow/tfjs/tree/master/e2e/benchmarks/local-benchmark) locally with WASM multi-thread enabled, then I failed to run any tflite model behind tflite backend.

Error shows that: 
```
tf-backend-webgl.js:7589 Uncaught (in promise) Error: The texture is invalid. Also, please make sure the texture
and the TFJS WebGL backend are using the same canvas. If you want to use your own custom canvas, 
you have to create and use the custom TFJS WebGL backend created from the canvas through
'new tf.MathBackendWebGL(customCanvas)'.
    at MathBackendWebGL.createTensorFromGPUData (tf-backend-webgl.js:7589:23)
    at makeTensor (tf-core.js:5652:35)
    at Object.tensor (tf-core.js:5872:16)
    at TFLiteModel.predict (tflite_model.ts:152:11)
    at model_config.js:99:34
    at (index):429:46
    at timeInference (benchmark_util.js:251:23)
    at warmUpAndRecordTime ((index):429:26)
    at async runBenchmark ((index):769:7)
```

**Describe the expected behavior**
Able to run tflite model with WASM multi-thread enabled.

**Standalone code to reproduce the issue**
No

**Other info / logs** 

```
{
  "core": "4.2.0",
  "layers": "4.2.0",
  "converter": "4.2.0"
}
{
  CHECK_COMPUTATION_FOR_ERRORS: true
  DEBUG: false
  HAS_WEBGL: true
  IS_NODE: false
  IS_TEST: false
  KEEP_INTERMEDIATE_TENSORS: false
  TENSORLIKE_CHECK_SHAPE_CONSISTENCY: false
  WASM_HAS_MULTITHREAD_SUPPORT: true
  WASM_HAS_SIMD_SUPPORT: true
  WEBGL_CHECK_NUMERICAL_PROBLEMS: false
  WEBGL_CPU_FORWARD: true
  WEBGL_DISJOINT_QUERY_TIMER_EXTENSION_RELIABLE: true
  WEBGL_DISJOINT_QUERY_TIMER_EXTENSION_VERSION: 2
  WEBGL_FLUSH_THRESHOLD: -1
  WEBGL_FORCE_F16_TEXTURES: false
  WEBGL_PACK: true
  WEBGL_PACK_DEPTHWISECONV: true
  WEBGL_RENDER_FLOAT32_CAPABLE: true
  WEBGL_USE_SHAPES_UNIFORMS: false
  WEBGL_VERSION: 2
}
{
  GPU info: 
  ANGLE (Intel, Mesa Intel(R) UHD Graphics 630 (CFL GT2), OpenGL 4.6)
}
```

/cc @mattsoulanille

**Comment by shmishra99** [comment]
Hi @Honry ,
I apologize for the late response. I have been able to benchmark the `tflite model` and it is successfully running on the `wasm backend`. Here is the output I have received:

<img width="1437" alt="image" src="https://github.com/tensorflow/tfjs/assets/124146945/8c63568a-8653-4ccb-93cf-2758ca45c84e">


However, I am seeing that `WASM_HAS_MULTITHREAD_SUPPORT` is set to false. Could you please help me with how you enabled WASM multithreading for your benchmark? 
Additionally, I have found a similar issue (#7343) that has already been fixed.
Thank You!!

**Comment by Honry** [comment]
>Could you please help me with how you enabled WASM multithreading for your benchmark?

The server you setup should provide the required response headers to enable `SharedArrayBuffer`:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

> Additionally, I have found a similar issue (https://github.com/tensorflow/tfjs/issues/7343) that has already been fixed.

Thanks, I just verified latest code, this issue should be fixed in https://github.com/tensorflow/tfjs/issues/7343, let's close it.
