### ISSUE TITLE
Memory leak when encoding jpegs

### ISSUE THREAD

**Issue by bartbutenaers** [tensorflow/tfjs#7459]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry Pi Os on Raspberry Pi 4
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.21.0
- NodeJs version: 16.19.0
- Tfjs-node version: 3.21.1

**Describe the current behavior**
Decoding, resizing, object detection, ... works like a charm.  However as soon as I start encoding the raw images back to jpegs, then my RSS memory goes very fast high.  After about 20 seconds the 3.2 Gb ram of my Raspberry is full.

**Describe the expected behavior**
I would like the memory to be cleaned up and remain stable.

**Standalone code to reproduce the issue**
I have tried to reduce the code to a simple example.  The following code snippet downloads an image from the web, decodes it and encodes it (over and over again in a loop):

```
const tf = require('@tensorflow/tfjs-node');
const https = require('https');

https.get('https://images.unsplash.com/photo-1461800919507-79b16743b257', function(resp) {
    let chunks = [];

    resp.on('data', function(chunk) {
        chunks.push(chunk);
    });

    resp.on('end', async function() {
        const imageBuffer = Buffer.concat(chunks);

        for (let i = 0; i < 100; i++) {
            tf.engine().startScope();

            let imageTensor = tf.node.decodeJpeg(imageBuffer);
            let jpegData = await tf.node.encodeJpeg(imageTensor);

            tf.engine().endScope();

            let usedMemory = process.memoryUsage();
            let rss = Math.round((usedMemory.rss / 1024 / 1024) * 100) / 100;
            let arrayBuffers = Math.round((usedMemory.arrayBuffers / 1024 / 1024) * 100) / 100;

            console.log("rss = " + rss + " and arrayBuffers = " + arrayBuffers);
        }
    });
}).on("error", function(err) {
    console.log("Error: " + err.message);
});
```
When I put the encodeJpeg statement in comment, then everything goes fine.  But when I uncomment it, my RSS memory increases very fast:

![image](https://user-images.githubusercontent.com/14224149/223874448-81cc3a88-adeb-4501-8d33-10b1573945ac.png)

Perhaps I am doing something stupid, but can't see it after repeating my checks a few evenings in a row...

Hopefully anybody can spot the error.

Thanks!!!
Bart

**Comment by bartbutenaers** [comment]
BTW the startScope and endScope statements work very well in my real application, to cleanup all kind of image tensors that I am using.  Except when I encode jpegs.

**Comment by gaikwadrahul8** [comment]
Hi, @bartbutenaers 

Apologize for the delayed response and I think you can use `tf.tidy()` to avoid memory leaks, In general, wrap calls to operations in [tf.tidy()](https://js.tensorflow.org/api/latest/?_gl=1*k8p6kz*_ga*MTQ3MDY0NjMzNS4xNjY1NzUyMDY1*_ga_W0YLR4190T*MTY3ODY1MDg5NS40ODcuMS4xNjc4NjUzODE5LjAuMC4w#tidy) for automatic memory cleanup.

You have to do something like below code snippet, 

```
// y = 2 ^ 2 + 1
const y = tf.tidy(() => {
   // a, b, and one will be cleaned up when the tidy ends.
   const one = tf.scalar(1);
   const a = tf.scalar(2);
   const b = a.square();

   console.log('numTensors (in tidy): ' + tf.memory().numTensors);

   // The value returned inside the tidy function will return
   // through the tidy, in this case to the variable y.
   return b.add(one);
});

console.log('numTensors (outside tidy): ' + tf.memory().numTensors);
y.print();

```

I would suggest you to please try follow our [official documentation](https://js.tensorflow.org/api/latest/?_gl=1*k8p6kz*_ga*MTQ3MDY0NjMzNS4xNjY1NzUyMDY1*_ga_W0YLR4190T*MTY3ODY1MDg5NS40ODcuMS4xNjc4NjUzODE5LjAuMC4w#Performance-Memory) and check whether is it resolving your issue or not ? If issue still persists please let us know ? Thank you!

**Comment by bartbutenaers** [comment]
Hello @gaikwadrahul8,
Thanks for joining!

I have already spend a LOT of evenings to get rid of my memory leaks.  Tried all kind of experiments to solve it, but most of it failed.  Had all kind of issues that I could not explain, because comparing heap dumps only told me that the memory was allocated outside of the profiler's scope.  I had small growing leaks in the heap, and explosive growing of the RSS memory.

I also always measured the number of tensors after cleanup (via `tf.memory().numTensors`), and that was always nice constant.

At the end putting my code between `tf.engine().startScope()` and `tf.engine().startScope()` seemed to help.  It now runs all very smooth on my Raspberry: decoding jpeg images from my ip cams, resizing them, object detection (via a tfjs tflite model on a Coral tpu usb stick), converting to rgba, bounding box drawing, converting to rgb, and so on...  Finally no memory issues anymore.

The only thing that blows up my RSS memory is the encodeJpeg.  All other image tensors are nicely cleaned up.

Therefore I would really appreciate if somebody could have a look whether they can reproduce the same error as I have with my original code snippet above.  Because everything else works fine, so there must be something weird going on in that `encodeJpeg` fuction...

Thanks for you understanding!
Bart
