### ISSUE TITLE
Meshgrid is not a 1D vector

### ISSUE THREAD

**Issue by ghsanti** [tensorflow/tfjs#7472]
Bug is very simple to reproduce. There is a wrong type assigned to meshgrid elements:

```javascript
const xv = tf.range(0,10);
const yv = xv
const [X, Y] = tf.meshgrid(xv, yv);
```

If you hover over X or Y, you get this:

![image](https://user-images.githubusercontent.com/125615505/224676391-59d54724-0579-44d6-8d90-ea658a82a7dc.png)

**Comment by gaikwadrahul8** [comment]
Hi, @mahnehsilla 

Apologize for the delayed response and I was able to replicate the same issue and It seems like working as expected, for your reference I have added output screenshot and please refer our official documentation for[ tf.meshgrid](https://js.tensorflow.org/api/latest/?_gl=1*vkrlf8*_ga*MTQ3MDY0NjMzNS4xNjY1NzUyMDY1*_ga_W0YLR4190T*MTY3ODczNDI2OS40OTUuMS4xNjc4NzM3MzEyLjAuMC4w#meshgrid). If have I missed something here, please let me know? Thank you!

![image](https://user-images.githubusercontent.com/115997457/224820681-b4696d0e-6807-4742-a5da-6176778e4731.png)

**Comment by mahnehsilla** [comment]
Hi there, no problem. 

As said in post, and included in the image, the problem is the Typescript type returned which is 1D, and that seems 2D

**Comment by gaikwadrahul8** [comment]
Hi, @mahnehsilla 

Apologize for the delayed response and I tried the same code with `Typescript` and after hovering on `X` and `Y` const, it's showing Tensor 1D but as output it's showing Tensor 2D and for your reference I have added screenshot below and unless until it's working as expected( It means correct output with correct N-D Tensor). Thank you!

![image](https://user-images.githubusercontent.com/115997457/225661502-4237bef4-9372-4065-a07e-14d96521900e.png)

**Comment by mahnehsilla** [comment]
The output is `tf.Tensor2D[ ]`, that is the error @gaikwadrahul8 
 
Both `X` and `Y` are `tf.tensor2D`

**Comment by gaikwadrahul8** [comment]
Hi, @pyu10055 

Could you please look into this issue ? Thank you!
