### ISSUE TITLE
tfjs-react-native won't run rn-webgl

### ISSUE THREAD

**Issue by fitouch** [tensorflow/tfjs#7482]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- iPhone 14 Simulator
- "dependencies": {
    "@tensorflow/tfjs": "^4.2.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo-asset": "^8.9.1",
    "expo-camera": "^8.3.1",
    "expo-gl": "^8.4.0",
    "expo-gl-cpp": "^8.4.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.2",
    "react-native-fs": "^2.20.0",
    "tslib": "^2.3.0"
  }

**Describe the current behavior**
```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';

const [isTfReady, setTfReady] = useState(false);

useEffect(() => {
  async function waitForTensorFlowJs() {
  await tf.ready();
    setTfReady(true);
  }
  waitForTensorFlowJs();
}, []);

{isTfReady && <Text>{tf.getBackend()}</Text>}
```

**Describe the expected behavior**
I expected "rn-webgl" from tf.getBackend(). I got "cpu".

**Comment by fitouch** [comment]
> Hi, @fitouch
> 
> Apologize for the delayed response and It seems like similar issue [#4593](https://github.com/tensorflow/tfjs/issues/4593) so could you please try those workaround provided by users and I think there is some issue with `@tensorflow/tfjs-react-native` version with `expo` so could please try by downgrading these version and I tried to replicate the same issue from my end with same `package.json` dependencies and I was getting some different error, for your reference I have added screenshot below and If have I missed something here please let me know ? Thank you!
> 
> Here is screenshot for your reference:
> 
> ![image](https://user-images.githubusercontent.com/115997457/225649380-44a550a0-a66a-4463-9854-cf0f9c259bed.png)

The code that I gave above is partial code. I tried to keep it short for here. Also I tried those workaround too, nothing did work for me.

**Comment by gaikwadrahul8** [comment]
@fitouch 

Thank you for the confirmation, if possible could you please give me your code by using codepen or github repo link to clone your code so We'll try it from my end to figured out root cause for your issue ? Thank you!
