### ISSUE TITLE
Add  a 'weightsOnly' option for tf.io.SaveConfig (i.e., the optional, second arg for Model.save()) 

### ISSUE THREAD

**Issue by AlexChrisF** [tensorflow/tfjs#749]

**Comment by bileschi** [comment]
Can you add more detail?  How would you expect this to behave and what is the compelling use case?  Is there similar functionality in the python API?

**Comment by AlexChrisF** [comment]
I think it would be really nice to have an option to only download the weights file, since my model topology stays the same.

Something like: 
const saveResults = await model.save('downloads://my-model-1', "weightsOnly");

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
