### ISSUE TITLE
Can't pass `scale` and `alpha` for selu operation

### ISSUE THREAD

**Issue by BruceDai** [tensorflow/tfjs#7496]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow.js version (use command below): 4.2.0

**Describe the current behavior**
Current the definition for **selu** operation is much simple: [tf.selu](https://js.tensorflow.org/api/latest/#selu) (x), 
while elu computes scaled exponential linear element-wise using 
`x < 0 ? scale * alpha * (exp(x) - 1) : scale * x`,
can't pass `scale` and `alpha` by invoking **tf.selu(x)**

**Describe the expected behavior**
Can pass `scale` and `alpha` for **selu**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
@BruceDai the scale and alpha are predefined as specified here
https://www.tensorflow.org/api_docs/python/tf/keras/activations/selu

**Comment by BruceDai** [comment]
@pyu10055 Thanks for your clarification. 
And would it be more flexible for **selu** with given **scale** and **alpha** values?
