### ISSUE TITLE
Bug in the layers.getLayer()

### ISSUE THREAD

**Issue by mahnehsilla** [tensorflow/tfjs#7498]
(permalink at post' bottom)

This function has not been fully adapted to javascript, currently the TS definition is:

```
getLayer(name?:string, index?:string)
```

So the only way to get by index is 
```
getLayer(null, index)
```

## Suggestions

Very humble ideas, not a good coder.

Probably should be rewritten to
```
 getLayer(target:string|number)
```
Where target is name or index. 

Or an object of this kind:
```
 getLayer({name?:string, index?:number})
```
That errors out if the object keys length is 0.

-----------------------

## [Permalink to Code Bug](https://github.com/tensorflow/tfjs/blob/cce7f017759423f98f7add7a01c6f3d4b47b1633/tfjs-layers/src/engine/container.ts#L975-L996)

- TensorFlow.js version (use command below): 4.2.0

**Comment by mahnehsilla** [comment]
Yes, I normally switch bw python keras and tfjs for the documentation as well (the python one is far more complete imho.) For example, the `tf.loadWeights` function isnt even in the documention of tfjs. I reported this to the forums I think.

I thought about a few contributions but I thought adding the tests could be annoying (I dont have much time.) 

I will try to add it though, this software is fantastic, and the only numpy equivalent for JS apart from DL @pyu10055

**Comment by fengwuyao** [comment]
The issue has been fixed by https://github.com/tensorflow/tfjs/pull/7665
Thanks for pointing out! @mahnehsilla
