### ISSUE TITLE
tfjs-node installation error with anaconda3

### ISSUE THREAD

**Issue by JonasJW** [tensorflow/tfjs#750]
#### Describe the problem or feature request

I'm getting this error when I'm trying to install '@tensorflow/tfjs-node'. The wierd thing is this line: `Command failed: /Users/jonas/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];`.

What does anaconda3 to do with this? I think I started to get this error only once I installed anaconda.

Any ideas?

/Users/jonas/Projects/ML/tfjs-test/ng-tf-handwriting/node_modules/@tensorflow/tfjs-node/scripts/install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/jonas/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jonas/Projects/ML/tfjs-test/ng-tf-handwriting/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at cp.exec (/Users/jonas/Projects/ML/tfjs-test/ng-tf-handwriting/node_modules/@tensorflow/tfjs-node/scripts/install.js:154:13)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.1.17 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.1.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonas/.npm/_logs/2018-10-01T18_34_11_588Z-debug.log

**Comment by xcapt** [comment]
Hi there, I had this one:
node-gyp does not support python 3.x, try with python 2.7

**Comment by JonasJW** [comment]
Thank you @xcapt, seems to work not!
