### ISSUE TITLE
Trying to run example: TF complains about installing (outdated?) node backend

### ISSUE THREAD

**Issue by MarByteBeep** [tensorflow/tfjs#7512]
After installing TF using

```bash
npm i @tensorflow/tfjs
```

I tried to build and run the following example (taking from the main tfjs repo):

```js
import * as tf from '@tensorflow/tfjs';

// Define a model for linear regression.
const model = tf.sequential();
model.add(tf.layers.dense({units: 1, inputShape: [1]}));

// Prepare the model for training: Specify the loss and the optimizer.
model.compile({loss: 'meanSquaredError', optimizer: 'sgd'});

// Generate some synthetic data for training.
const xs = tf.tensor2d([1, 2, 3, 4], [4, 1]);
const ys = tf.tensor2d([1, 3, 5, 7], [4, 1]);

// Train the model using the data.
model.fit(xs, ys).then(() => {
  // Use the model to do inference on a data point the model hasn't seen before:
  model.predict(tf.tensor2d([5], [1, 1])).print();
});
```

It runs fine, but immediately after I add the layer to the model, I get the following output:

```
============================
Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details. 
============================
```

When browsing that repo, it actually mentioned that it's archived in favor of tfjs.

My dependencies:

```
@tensorflow/tfjs": "^4.2.0"
Node version: v18.14.0
```

Any thoughts?

**Comment by gaikwadrahul8** [comment]
Hi, @MarByteBeep 

I was able to replicate the same issue on my system and it's giving me same warning message `Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details.` with `@tensorflow/tfjs": "^4.2.0` dependancy.

**TensorFlow backend for TensorFlow.js via Node.js** provides native TensorFlow execution in backend JavaScript applications under the Node.js runtime, accelerated by the TensorFlow C binary under the hood. It provides the same API as [TensorFlow.js](https://js.tensorflow.org/api/latest/).

This package will work on Linux, Windows, and Mac platforms where TensorFlow is supported.

It seems like giving us suggestion or warning message to speed things up dramatically, install node backend with GPU support and you can refer our [official documentation ](https://github.com/tensorflow/tfjs/tree/master/tfjs-node)

As far I know unless and until our code is executing as expected with correct output we can ignore this warning or suggestion message. If have I missed something here please let me know ? Thank you!

For your reference I have added screenshot below:

![image](https://user-images.githubusercontent.com/115997457/227723306-20e0e43f-03f6-43ef-b7b6-4d337ffbb7df.png)

**Comment by MarByteBeep** [comment]
Thanks for your reply! Couple of questions here:

* why is it referring to an archived repo? 
* do we need to have these C bindings installed in order to have maximum performance? I was under the impression that with webgl and wasm etc, performance would already be good, so I won't have to go through the trouble setting up that C library. (Which apparently also includes installing multiple versions of Python)

**Comment by gaikwadrahul8** [comment]
Hi, @MarByteBeep 

Apologize for the delayed response and at the moment that link is pointing to old link so I think it should point to updated new link `https://github.com/tensorflow/tfjs/tree/master/tfjs-node` for that I'll submit PR soon it will be updated new link once that PR got merged.

As far I know you have to use only below command on `CPU` and provides native TensorFlow execution in backend JavaScript applications under the Node.js runtime, accelerated by the TensorFlow C binary under the hood. It provides the same API as [TensorFlow.js](https://js.tensorflow.org/api/latest/). You don't have to do set up for C library explicitly from your end and with below command it will take latest stable version of `Tensorflow` automatically, you don't have to install it explicitly if I'm not wrong.

```
npm install @tensorflow/tfjs-node
(or)
yarn add @tensorflow/tfjs-node

```
**Installing Linux/Windows GPU TensorFlow.js for Node:**

```
npm install @tensorflow/tfjs-node-gpu
(or)
yarn add @tensorflow/tfjs-node-gpu
```

If have I missed something here, please let me know ? Thank you!

**Comment by manztou** [comment]
I believe the problem still exists and it's confusing what the resolution should be. 
I've installed tensorflow for nodejs (Windows 10) as such: npm install @tensorflow/tfjs

And getting the following message when using it:

"Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details. "

**Comment by nomuppets** [comment]
tf.enableProdMode() 

> Running into this on a Pixelbook, where I have no confidence that tfjs-node will be supported for long, if at all (cf. eg [#8142](https://github.com/tensorflow/tfjs/issues/8142)).
> 
> Every time I run my application code on the commandline we see this message spewing out. Is there no way to suppress it?
