### ISSUE TITLE
Support print shader on webgpu backend

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7516]
This feature is from TVM, and this can behind a flag like WEBGPU_PRINT_SHADER.

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and I see to take care of this issue, this PR https://github.com/tensorflow/tfjs/pull/7523 was submitted and now that PR got merged so could you please confirm, have we taken care of this issue now ?

If issue still persists please let us know ? Thank you!
