### ISSUE TITLE
tensorflowjs_converter produces invalid model.json file

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#7519]
when using `tensorflowjs_converter` with quantization, the `model.json` file produced is invalid

for example, download saved model from <https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint_tf.tar>

convert **tf saved model** to **tfjs graph model** and specific tensor has signature as noted below:

```shell
tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model --strip_debug_ops=* --signature_name=predict --saved_model_tags=serve --weight_shard_size_bytes=16777216 detector_v2_base_checkpoint_tf base-int16
```

```json
{"name": "filtered_detections/map/while/non_max_suppression_3/score_threshold", "shape": [], "dtype": "float32"}
```

now re-run same command with quantization:

```shell
tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model --strip_debug_ops=* --signature_name=predict --saved_model_tags=serve --weight_shard_size_bytes=16777216 --quantize_int16=* detector_v2_base_checkpoint_tf base-fp32
```

```json
{"name": "filtered_detections/map/while/non_max_suppression_3/score_threshold", "shape": [], "dtype": "float32", "quantization": {"dtype": "uint16", "min": -Infinity, "scale": 1.0, "original_dtype": "float32"}}
```

note `-Infinity` - that is **NOT a valid JSON value** and causes runtime error when loading model:

> error loading graph model: file://model/base-i16/model.json
> SyntaxError: No number after minus sign in JSON at position 408999

environment: 
- ubuntu 22.04
- tensorflowjs_converter 4.2.0
- tensorflow 2.11.0

**Comment by gaikwadrahul8** [comment]
Hi, @mattsoulanille

Could you please look into this issue ? Thank you!

**Comment by mattsoulanille** [comment]
Thanks for the bug report and the detailed instructions for reproducing it! I'm able to reproduce this on the main branch. I'll take a look at why tfjs-converter is able to output `-Infinity`.

**Comment by gaikwadrahul8** [comment]
Hi, @vladmandic 

Apologize for the delayed response and It seems like we have updated our [official documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) w.r.t `tfjs_converter `and now there is no option of `--quantize_int16` as conversion Flags and I see there is `--quantize_uint16` conversion Flag option and I tried with that option and it's not producing the `-Infinity` values in `model.json` file, Please refer this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/e9cf06ebd38a8887eaf32d786c2c80eb/tfjs-7519.ipynb)

If have I missed something here please let me know ? Thank you!
