### ISSUE TITLE
TFJS modules are loaded twice in e2e

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7521]
Problem: 
In e2e, when 'https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection' is loaded, tfjs-backend-webgpu will be loaded twice.

Investigation: 
The production code will include code from other package when: package is imported(such as import * as tfwebgpu from '@tensorflow/tfjs-backend-webgpu';) and is non external in rollup.config.js

The production code of Pose-detection will include a copy of tfjs-backend-webgpu.js(it is imported and is non external). E2e also loads tfjs-backend-webgpu.js with <script> tag.  The two tfjs-backend-webgpu.js cannot be understood as the same package, so it will load twice. Webgl doesn't has this problem, because pose-detection doesn’t has code like this:  import * as tfwebgl from '@tensorflow/tfjs-backend-webgl'.

Solution:
Set tfjs-backend-webgpu as external:  https://github.com/tensorflow/tfjs-models/pull/1140

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and I see you've submitted one PR to address this issue and it will be taken care once that PR got merged after following our PR procedure. Thank you for noticing this issue and for submitting PR to address this issue. I really appreciate your valuable efforts and time. Thank you!
