### ISSUE TITLE
Face Landmark Detection return empty array

### ISSUE THREAD

**Issue by Lonoyaa** [tensorflow/tfjs#7529]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 22.04.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Huawei Nova 4
- TensorFlow.js installed from (npm or script link): yarn add @tensorflow/tfjs
- TensorFlow.js version (use command below):3.11.0
- Browser version:-
- Tensorflow.js Converter Version:3.11.0

**Describe the current behavior**
FaceLandmarkDetection.estimateFace(inputTensor3D) return empty array
**Describe the expected behavior**
estimateFace return face array contain box and keypoints
**Standalone code to reproduce the issue**
>
"dependencies": {

    "@mediapipe/face_detection": "^0.4.1646425229",
    "@mediapipe/face_mesh": "^0.4.1633559619",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@shopify/react-native-skia": "0.1.175",
    "@tensorflow-models/face-detection": "^1.0.1",
    "@tensorflow-models/face-landmarks-detection": "^1.0.2",
    "@tensorflow/tfjs": "^3.11.0",
    "@tensorflow/tfjs-backend-cpu": "~3.11.0",
    "@tensorflow/tfjs-backend-webgl": "~3.11.0",
    "@tensorflow/tfjs-converter": "^3.11.0",
    "@tensorflow/tfjs-core": "3.11.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "@types/react-native": "^0.71.3",
    "deprecated-react-native-prop-types": "^4.0.0",
    "expo-asset": "^7.0.0",
    "expo-camera": "^13.2.1",
    "expo-gl": "^10.2.1",
    "expo-gl-cpp": "10.4.1",
    "expo-image-loader": "2.1.1",
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-canvas": "^0.1.38",
    "react-native-fs": "^2.14.1",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "2",
    "react-native-unimodules": "^0.13.3",
    "react-native-vision-camera": "^2.15.4",
    "react-native-webview": "^11.26.1",
    "unimodules-barcode-scanner-interface": "^6.1.0"
 },"

const image = require('./assets/Face.jpeg');
const imageAssetPath = Image.resolveAssetSource(image);
            const response = await fetch(imageAssetPath.uri, {}, { isBinary: true });
            const imageDataArrayBuffer = await response.arrayBuffer();
            const imageData1 = new Uint8Array(imageDataArrayBuffer);
            const imageTensor1 = decodeJpeg(imageData1);
            const test = await modelReady?.estimateFaces(imageTensor1)
            console.log('test0',test)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

At the top, I call tf.setBackend('cpu') before tf.ready(), not sure if it's related

**Comment by Lonoyaa** [comment]
I rebuild the project with expo and manage to use rn-webgl as backend then it sucesses to return keypoint array. If I switch to cpu backend then it doesn't work.

So, it's not possible to use cpu backend?

**Comment by Lonoyaa** [comment]
I rebuild the project with expo and manage to use rn-webgl as backend then it sucesses to return keypoint array. If I switch to cpu backend then it doesn't work.

So, it's not possible to use cpu backend with react native (managed by react-native-cli)

**Comment by Lonoyaa** [comment]
Hi, @gaikwadrahul8 
Thank you for your answer, it works after I change the backend to rn-webgl.

**Comment by gaikwadrahul8** [comment]
Hi, @Lonoyaa 

Apologize for the delayed response and you're welcome, Good to hear that your issue got resolved so please feel free to close this issue if this issue got resolved for you. Thank you!
