### ISSUE TITLE
Uncaught (in promise) TypeError: n.iterator is not a function

### ISSUE THREAD

**Issue by humera811** [tensorflow/tfjs#7539]
<html>
<head></head>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script>
    <script lang="js">
        
        async function run(){
            const trainingUrl = '/data/wdbc-train.csv';
            
            // Take a look at the 'wdbc-train.csv' file and specify the column
            // that should be treated as the label in the space below.
            // HINT: Remember that you are trying to build a classifier that 
            // can predict from the data whether the diagnosis is malignant or benign.
            const trainingData = tf.data.csv(trainingUrl, {
                
                // YOUR CODE HERE
                columnConfigs: {
                    diagnosis: {
                        isLabel: true
                    }
                }
                
            });
            
            // Convert the training data into arrays in the space below.
            // Note: In this case, the labels are integers, not strings.
            // Therefore, there is no need to convert string labels into
            // a one-hot encoded array of label values like we did in the
            // Iris dataset example. 
            const convertedTrainingData = await trainingData.batch(10).toArray();
                  
            const testingUrl = '/data/wdbc-test.csv';
            
            // Take a look at the 'wdbc-test.csv' file and specify the column
            // that should be treated as the label in the space below..
            // HINT: Remember that you are trying to build a classifier that 
            // can predict from the data whether the diagnosis is malignant or benign.
            const testingData = tf.data.csv(testingUrl, {
                columnConfigs: {
                    diagnosis: {
                        isLabel: true
                    }
                }                
            });
            
            // Convert the testing data into arrays in the space below.
            // Note: In this case, the labels are integers, not strings.
            // Therefore, there is no need to convert string labels into
            // a one-hot encoded array of label values like we did in the
            // Iris dataset example. 
            const convertedTestingData = await testingData.batch(10).toArray();
                  

            // Specify the number of features in the space below.
            // HINT: You can get the number of features from the number of columns
            // and the number of labels in the training data. 
            const numOfFeatures = (await trainingData.columnNames()).length - 1;
            
                
            // In the space below create a neural network that predicts 1 if the diagnosis is malignant
            // and 0 if the diagnosis is benign. Your neural network should only use dense
            // layers and the output layer should only have a single output unit with a
            // sigmoid activation function. You are free to use as many hidden layers and
            // neurons as you like.  
            // HINT: Make sure your input layer has the correct input shape. We also suggest
            // using ReLu activation functions where applicable. For this dataset only a few
            // hidden layers should be enough to get a high accuracy.  
            const model = tf.sequential();
            model.add(tf.layers.dense({ inputShape: [numOfFeatures], units: 64, activation: 'relu' }));
            model.add(tf.layers.dense({ units: 32, activation: 'relu' }));
            model.add(tf.layers.dense({ units: 1, activation: 'sigmoid' }));

            model.summary();    

            // Compile the model using the binaryCrossentropy loss, 
            // the rmsprop optimizer, and accuracy for your metrics. 
            model.compile({
                loss: 'binaryCrossentropy',
                optimizer: 'rmsprop',
                metrics: ['accuracy']
              });
            
            
            await model.fitDataset(convertedTrainingData, 
                             {epochs:100,
                              validationData: convertedTestingData,
                              callbacks:{
                                  onEpochEnd: async(epoch, logs) =>{
                                      console.log("Epoch: " + epoch + " Loss: " + logs.loss + " Accuracy: " + logs.acc);
                                  }
                              }});
            await model.save('downloads://my_model');
        }
        run();
    </script>
<body>
</body>
</html>

I am getting the following error:

![Screenshot 2023-03-31 at 5 41 24 PM](https://user-images.githubusercontent.com/14123245/229257048-9a6c1443-fcbc-41a0-8d99-7385ac648c96.png)

**Comment by Neilblaze** [comment]
Technically, it shouldn't be a problem. But in this case, it seems like the error is something to do with the incompatibility of the `.batch()` method with the mentioned version of TFjs.

@gaikwadrahul8 can share some light over here.

**Comment by gaikwadrahul8** [comment]
Hi, @humera811 

Apologize for the delayed response and it seems like `convertedTrainingData` and `convertedTestingData` are `js array`, it needs to be converted either to a `tf.tensor` or to a` tf.data.Dataset`. I found similar issue on Stack-overflow so could you please try this [workaround](https://stackoverflow.com/questions/59519521/javascript-uncaught-in-promise-typeerror-e-iterator-is-not-a-function-how#:~:text=The%20error%20comes,using%20a%20generator.) and let us know whether is it resolving your issue or not ?

If issue still persists please let us know ? Thank you!
