### ISSUE TITLE
Error: The RNN cell should have an attribute `stateSize` when loading a model

### ISSUE THREAD

**Issue by kouohhashi** [tensorflow/tfjs#754]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
@tensorflow/tfjs: 0.12.3
@tensorflow/tfjs-node: 0.1.9
I updated tfjs-node to 0.1.17 but still got same error.

#### Browser version
node: v8.9.1

#### Describe the problem or feature request
```
const cells = [
   tf.layers.gruCell({units: 8}),
];
const rnn = tf.layers.rnn({
  cell: cells,
  returnSequences: true,
  // returnState: true,
});
const output3 = rnn.apply(output2);
```

I created a mode with tf.layers.rnn and  tf.layers.gruCell.
Trining itself was completed without any errors.

But with i load the model, 
```
const model1 = await tf.loadModel('<my path to model>');
```
I got an error like below.
```
Error: The RNN cell should have an attribute `stateSize` (tuple of integers, one integer per RNN state)
```

#### Code to reproduce the bug / link to feature request
create a model with  tf.layers.gruCell and tf.layers.rnn and load the model.

I tried returnState = true and false but no change.

Thanks for advance.

**Comment by davidsoergel** [comment]
One thing to try, per the [docs](https://js.tensorflow.org/api/0.13.0/#layers.gruCell): "To create an RNN consisting of only one GRUCell, use the tf.layers.gru."

If that fixes it, that suggests we should emit a warning/error on creation of RNN with a single GRUCell.  If not, I think it's a bug (that I don't fully understand yet).

Thanks for the report!

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Ahmfar19** [comment]
Did you found a solution to this problem? I have the same problem too
