### ISSUE TITLE
@tensorflow-models npm release

### ISSUE THREAD

**Issue by inventshah** [tensorflow/tfjs#7548]
Is there a schedule for publishing new tfjs-model releases on npm under `@tensorflow-models`? The GitHub repository appears to be ahead of the latest npm release by a year.

In particular, [@tensorflow-models/face-detection](https://www.npmjs.com/package/@tensorflow-models/face-detection) on npm uses tfjs-core v3.14 while the [tfjs-models](https://github.com/tensorflow/tfjs-models/blob/master/face-detection/package.json#L19) repository has already upgraded to tfjs-core v4.0.

Are there larger changes blocking a new release or would it be possible to publish a new release with these dependency bumps? To my knowledge, there is no way to npm install through git because of the monorepo structure.

**Comment by Neilblaze** [comment]
+1 for the same.

**Comment by gaikwadrahul8** [comment]
Hi, @inventshah 

Apologize for the delayed response and I checked npm `package.json` file for `@tensorflow-models/face-detection` and it's showing `"@tensorflow/tfjs-converter": "^3.14.0"` and in `Github Face Detection` it's showing `"@tensorflow/tfjs-core": "^4.0.0"` so it's seems like we have to update to `"@tensorflow/tfjs-core": "^4.0.0"` at the moment I'm not sure whether is there any blockers to update it but we'll update you soon. Thank you for noticing this and I really appreciate your time and efforts . Thank you!

**Comment by inventshah** [comment]
Hi, I just wanted to follow up to see if there is any progress on getting a new release. Is there a blocker I can help with? Thanks!

**Comment by fengwuyao** [comment]
@inventshah Hi, the new face-detection npm has been released and it has been updated to `"@tensorflow/tfjs-core": "^4.4.0".` Thanks!
