### ISSUE TITLE
Catching "CONTEXT_LOST_WEBGL"

### ISSUE THREAD

**Issue by justadudewhohacks** [tensorflow/tfjs#756]
Hello everyone,

It seems like **gl.CONTEXT_LOST_WEBGL** is being catched by the engine and then logged with console.warn. Is there any way for me to catch this error?

Usecase: When training models using the WebGL backend, it would be possible to catch the above mentioned error and save a backup of the current model weights, up to that point. 

With the current approach of logging a warning to the console, you wouldn't notice that error and simply keep on training garbage, which deforms the model weights and makes them unusable. Seems like already in the next iteration the model weights are unusable.

**Comment by bileschi** [comment]
@dsmilkov is this something we could surface?  Possibly as an option?

**Comment by dsmilkov** [comment]
Thanks @justadudewhohacks. This seems very reasonable and useful. We can allow the user to subscribe and be notified:
```ts
tf.webgl.onContextLost(() => {
  // Called when the context was lost.
});
```

https://www.khronos.org/webgl/wiki/HandlingContextLost gives us guidelines how to detect when the context was lost. (We might even be able to fully recover from it, but that would be a future step).

**Comment by DavidGOrtega** [comment]
@justadudewhohacks  if this works you have made my day.

**Comment by justadudewhohacks** [comment]
Thanks for the quick answer. @dsmilkov just to clarify, simply adding a event listener for 'webglcontextlost' to the canvas passed to `tf.fromPixels` probably won't make it, or should that already solve it? PS: I am not familar with WebGL at all.

**Comment by dsmilkov** [comment]
Just to clarify about the canvas, tfjs uses its own internal canvas ([link](https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/backend_webgl.ts#L470)), different from the user-provided canvas provided when calling `tf.fromPixels(userCanvas)`. So the event listener will be attached to the internal canvas.

**Comment by justadudewhohacks** [comment]
Ok, thanks for the hints. I will try to get this working and then submit a PR.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
I think we could still do this, WDYT @justadudewhohacks ?

**Comment by nsthorat** [comment]
Great! We actually had a fix recently which should dramatically reduce the context being lost (having a global singleton canvas).

I'll close this out -- if you see this again let us know and we'll reopen it.
