### ISSUE TITLE
Cannot install '@tensorflow/tfjs-backend-wasm' in NodeJS

### ISSUE THREAD

**Issue by reefagirl** [tensorflow/tfjs#7567]
When running npm i @tensorflow/tfjs-backend-wasm the below error appears.

![image](https://user-images.githubusercontent.com/21690818/230861807-5dbdd44a-f5ed-4c25-b78e-279af18c98ad.png)

**Comment by gaikwadrahul8** [comment]
Hi, @reefagirl 

I was able to replicate the same issue and I'm able to install `@tensorflow/tfjs-backend-wasm` without any error by using this command `npm i @tensorflow/tfjs-backend-wasm --force` so could you please try to install from your end now and let us know whether is it resolving your issue or not ?

For you reference I have added screenshot below, 

![image](https://user-images.githubusercontent.com/115997457/230877314-4d241360-ef35-4957-9e01-4b9e03726380.png)

If issue still persists please let us know with error log if you get different error log ? Thank you!

**Comment by pyu10055** [comment]
@reefagirl the face-detection is using a older version of TFJS, which cause deps conflict with the latest version of TFJS. should we update the models deps across? @mattsoulanille

**Comment by reefagirl** [comment]
hi @gaikwadrahul8, Thank you for you response. Previously when I ran it I got the below error
![image](https://user-images.githubusercontent.com/21690818/231098437-fe5f1e6e-72f5-4f4d-aa65-aef9f2ba5896.png)

This led me to remove the package and reinstall.

Per your suggestion I reinstalled using --force. Although it installed without errors. When a request comes to the application the below error appears.

![image](https://user-images.githubusercontent.com/21690818/231099262-41749910-4686-427a-ab5e-b371027ab5b7.png)

Hope this gives better clarity of the issue. Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @reefagirl 

Could you please refer above [comment](https://github.com/tensorflow/tfjs/issues/7567#issuecomment-1502092181) from @pyu10055 and May I know are you using any pre-trained model from [Tensorflow.js models ](https://github.com/tensorflow/tfjs-models) ? if yes then there may be some package dependancy issue with latest version of TFJS so I would suggest you to please check the `package.json` file for that respective pre-trained model and  try to install all `package.json` dependancies mentioned after copying all dependancies from that model `package.json` by using command `npm install` command. 

If you're not using any pre-trained model from [Tensorflow.js models ](https://github.com/tensorflow/tfjs-models) then please try to downgrade the version of `@tensorflow/tfjs-backend-wasm` to previous stable version and I see most downloaded versions are `4.2.0` or `3.21.0` so could you please try with those version and let us know whether is it resolving your issue or not ? 

If issue still persists please let us know ? Thank you!

**Comment by reefagirl** [comment]
Hi @gaikwadrahul8 ,

Yes I am using the face-landmarks-detection, Tensorflow pre-trained model. I will attempt to check on the package dependency issues.

Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @reefagirl 

Thank you for the confirmation and please try to go with mentioned dependancies in package.json file of face-landmarks-detection pre-trained model from [here](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/package.json) and it should work as expected 

If issues still persists please let us know ? Thank you!

**Comment by inventshah** [comment]
It looks like #7548 is related, although the [repo](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/package.json#L19) for the `face-landmarks-detection` model still uses tfjs `3.12.0` so a new npm release isn't sufficient. Looking at the git history for the other models that have upgraded to `4.x.x`, it appears a simple dependency bump works, but I haven't tested this particular model.
