### ISSUE TITLE
Use TypedArray to instantiate tensor - Doc/code inconsistency

### ISSUE THREAD

**Issue by jdmichaud** [tensorflow/tfjs#757]
#### TensorFlow.js version
tfjs-core: 0.13.2
tfjs-layers: 0.8.1
tfjs-converter: 0.6.1
tfjs: 0.13.1

#### Browser version
Chrome 69.0.3497.100 (Official Build) (64-bit)

#### Describe the problem or feature request
The doc says:
tf.tensor1d (values, dtype?)
values (TypedArray|Array) The values of the tensor. Can be array of numbers, or a TypedArray

However the code checks that values is either:
* Float32Array
* Int32Array
* Uint8Array

See https://github.com/tensorflow/tfjs-core/blob/fa37dd0e9f4729c78eceba7b89632cbbfcbde3cb/src/util.ts#L416

#### Code to reproduce the bug / link to feature request
Result: I have been scratching my head for an hour on this:
```
> tf.tensor1d(new Uint16Array([1, 2, 3, 4]))
tf-core.esm.js:17 Uncaught Error: tensor1d() requires values to be a flat/TypedArray
```
But this **IS** a TypedArray.

I would suggest to either:
1. Rework the doc so that TypedArray is replaced by the actual expected types or
2. Allow any kind of TypedArray (preferred solution of course).

**Comment by rthadur** [comment]
This has been fixed [here](https://github.com/tensorflow/tfjs-core/pull/1424)  , closing this issue , thank you

**Comment by jelling** [comment]
Error message should still be improved as passing an Int16Array will return a message saying that a typed array is required and int16array is a typed array.

**Comment by aknoerig** [comment]
Very confusing indeed. I just had the same issue with a Uint16Array. Either the documentation should be adapted to point out which sorts of TypedArray are accepted, or the constructor should be able to consume them all.

**Comment by rthadur** [comment]
@aknoerig @jelling would either of you like to contribute ?

**Comment by aknoerig** [comment]
Thanks, but I wouldn't feel comfortable to patch this in a solid way. :/
Btw, adapting the documentation would be sufficient as a first step: just explicitly name the supported types of `TypedArray`.
