### ISSUE TITLE
Local benchmark tool failed to support url parameter task=performance

### ISSUE THREAD

**Issue by gyagp** [tensorflow/tfjs#7574]
It seems PR https://github.com/tensorflow/tfjs/pull/7538 causes a regression to support url parameter "task=performance".
Before this change, if we designate a url like "https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html?task=performance", the performance test will run. But now state.run() couldn't be triggered. 

@Linchenn Do you happen to know the reason?

**Comment by Linchenn** [comment]
Fixed https://github.com/tensorflow/tfjs/pull/7575
