### ISSUE TITLE
Using tfjs with SyntaxNet/DraGNN on Service Fabric

### ISSUE THREAD

**Issue by manchuwook** [tensorflow/tfjs#758]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
Any

#### Browser version
Angular/Universal

#### Describe the problem or feature request
Is there a way to use SyntaxNet / Dragnn with tfjs?  I'm not super excited installing Python to connect it to a Service Fabric site.

#### Code to reproduce the bug / link to feature request
[https://github.com/tensorflow/models/tree/master/research/syntaxnet](url)

**Comment by davidsoergel** [comment]
SyntaxNet / Dragnn are not just TensorFlow models; they're complex libraries with hundreds of thousands of lines of C++ and Python code.  I know of no plans to port these to JS, but you could [ask the SyntaxNet team](https://github.com/tensorflow/models/tree/master/research/syntaxnet#contact).

In any case I think the most expedient solution is to run the existing code server-side as you suggest.

**Comment by davidsoergel** [comment]
Oh one more thing: I realize this is a different approach, but maybe the Google Natural Language API (https://cloud.google.com/natural-language/) could meet your needs?  That way you wouldn't have to run a service yourself.

**Comment by manchuwook** [comment]
I want to run a service myself because I don't want to pay per minute or by transaction.  I have my own servers for developing.
