### ISSUE TITLE
No way to clear shader cache : out of GPU memory

### ISSUE THREAD

**Issue by h-skibbe** [tensorflow/tfjs#7589]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow.js 4.4 (web, not nodejs)
- Browser version: chromium browser

**Describe the current behavior**

I am developing a web-tool that processes batches of images. Tensors are disposed correctly, but for each image with difference size, new webgltextures are being created. It turned out it is likely tensorflow creating caches.  An issue, for instance , was that every time "tf.browser.fromPixels(img); " was called with a new image with different extents, the number of webgltextures increases - until an out of memory error. The simplified code below produces a lot of textures.  

**Describe the expected behavior**
A way to clear the cache is needed. Thanks!

**Standalone code to reproduce the issue**
function make_leak3(s){
        const t_ =   tf.ones([s,s]);
        let r = tf.sum(t_)
        console.log(r)
        t_.dispose();
        r.dispose()
}
for (a=10;a<100;a++)make_leak3(a);

**Comment by h-skibbe** [comment]
Ok, it looks like setting 
tf.ENV.set('WEBGL_USE_SHAPES_UNIFORMS', true);
tf.ENV.set('WEBGL_DELETE_TEXTURE_THRESHOLD', 50);
somehow might have solved the issue. But would be nice to be able to explicitly clear the shader cache. Thanks!

**Comment by pyu10055** [comment]
@h-skibbe this is the flag to control how much texture you want to keep on the GPU, this number is in bytes `tf.ENV.set('WEBGL_DELETE_TEXTURE_THRESHOLD', 50);`
