### ISSUE TITLE
loadFrozenModel does not work in node

### ISSUE THREAD

**Issue by DavidGOrtega** [tensorflow/tfjs#759]
#### TensorFlow.js version
tfjs 0.13.1
tfjs-node 0.1.17
tfjs-converter 0.6.2
#### Browser version
node 10.5.0 on Windows 10
#### Describe the problem or feature request
```
Promise { <pending> }
(node:21296) UnhandledPromiseRejectionWarning: Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
    at new BrowserHTTPRequest (C:\nodetfjs\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:46:19)
    at Object.browserHTTPRequest (C:\nodetfjs\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:247:12)
    at FrozenModel.findIOHandler (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:99:38)
    at FrozenModel.<anonymous> (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:114:30)
    at step (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:32:23)
    at Object.next (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:13:53)
    at C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:3:12)
    at FrozenModel.load (C:\nodetfjs\node_modules\@tensorflow\tfjs-converter\dist\src\executor\frozen_model.js:109:16)
```
#### Code to reproduce the bug / link to feature request
```
require('@tensorflow/tfjs-node');
const tf = require('@tensorflow/tfjs');
const tfcv = require('@tensorflow/tfjs-converter');

const URI           = 'file://C:/pix2pix/models/facades_A2B/tfjs/';
const MODEL_URL     = URI + 'tensorflowjs_model.pb';
const WEIGHTS_URL   = URI + 'weights_manifest.json';
const model         = tfcv.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
```

you can try also with same results
```
const model         = tf.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
```

**Comment by caisq** [comment]
Did you try `global.fetch = require('node-fetch')` (with dependency on `node-fetch`)?

**Comment by DavidGOrtega** [comment]
Hi @caisq . Thanks for the reply!
Yeah that one was one of my initial try outs.
With the polyfill I can load from HTTP but not local models.

```
Only HTTP(S) protocols are supported
```

I 'm looking at the code. LoadfrozenModel is just
```
const model = new tf.FrozenModel(MODEL_URL, WEIGHTS_URL, {});
model.load()
```

However it depends on a handler that is going ALWAYS to be empty on node
```
const handlers = tfc.io.getLoadHandlers(path);
if (handlers.length === 0) {
        handlers.push(tfc.io.browserHTTPRequest(path, this.requestOption));
         }...
         
this.handler = this.handlers[0];
```

My options right now are
1 - Write my frozenModel that loads the model with it's own IOHandler
2 - Write just the fileLoader and polyfill tfc.io.getLoadHandlers to return my IOHandler
3 - Try to find a fetch polyfill that loads file://

What would you do?
;)

**Comment by caisq** [comment]
Sorry I overlooked an important problem in your code before. Please import tfjs-node after importing tfjs, i.e.:

```js
const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');
```

**Comment by caisq** [comment]
I see. I think you can remove @tensorflow/tfjs as a dependency from your package.json and keep  @tensorflow/tfjs-node. You are running into these issues due to multiple versions of @tensorflow/tfjs being pulled in.

**Comment by DavidGOrtega** [comment]
I can't!

```
"dependencies": {
    "@tensorflow/tfjs-node": "^0.1.17",
    "node-fetch": "^2.2.0",
  },
```

```
const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');
```

```
Error: Cannot find module '@tensorflow/tfjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by nkreeger** [comment]
Try deleting the node_modules directory and retry `npm install` or `yarn`

**Comment by DavidGOrtega** [comment]
@nkreeger thanks for the reply. I tried it and documented it #739 
I did swept the node-modules completely and just installed the @tensorflow/tfjs-node however did not worked for me. I needed to install the tfjs module.

**Comment by nkreeger** [comment]
@DavidGOrtega I think you have an old version of tfjs-node. Please try installing 0.1.18.

**Comment by DavidGOrtega** [comment]
@nkreeger thanks, that solved the problem of issue #739 ! I'm impressed how fast new versions come out! mine was a couple of days old?

**Comment by jtoy** [comment]
nice, I ran into same thing and found this thread. think we can close this thread.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
