### ISSUE TITLE
Retraining model

### ISSUE THREAD

**Issue by deno-source** [tensorflow/tfjs#7592]
At first, I trained a model, but the business keeps adding new data, which causes the model to be retrained by adding new data each time. Is there any way to continue the old model and add new data to train the new model?

**Comment by gaikwadrahul8** [comment]
Hi, @deno-source 

Apologize for the delayed response and As far I know if we already have the trained model and if similar data will be keep on adding in that case we can re-train the model with the help of [tf.LayersModel.fit](https://js.tensorflow.org/api/latest/#tf.LayersModel.fit) and if you're looking to keep old model `(which has already trained on old data) `as it is and want to re-train the model with new data by using `tf.LayersModel.fit` on `new data `in this case you'll have to save your old model and later you can load the same model again.

Please refer our official documentation for [Training models](https://www.tensorflow.org/js/guide/train_models) and [Save and load models](https://www.tensorflow.org/js/guide/save_load), If have I missed something here please let me know ? Thank you!
