### ISSUE TITLE
[Codelab]: TensorFlowJS Comment Spam Detection

### ISSUE THREAD

**Issue by tomoyanime** [tensorflow/tfjs#7597]
I don't know if this is the right place to issue, but the following code on Codelabs won't work

https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#9

```
import * as DICTIONARY from '/dictionary.js';

// The number of input elements the ML Model is expecting.
const ENCODING_LENGTH = 20;


/** 
 * Function that takes an array of words, converts words to tokens,
 * and then returns a Tensor representation of the tokenization that
 * can be used as input to the machine learning model.
 */
function tokenize(wordArray) {
  // Always start with the START token.
  let returnArray = [DICTIONARY.START];
  
  // Loop through the words in the sentence you want to encode.
  // If word is found in dictionary, add that number else
  // you add the UNKNOWN token.
  for (var i = 0; i < wordArray.length; i++) {
    let encoding = DICTIONARY.LOOKUP[wordArray[i]];
    returnArray.push(encoding === undefined ? DICTIONARY.UNKNOWN : encoding);
  }
  
  // Finally if the number of words was < the minimum encoding length
  // minus 1 (due to the start token), fill the rest with PAD tokens.
  while (i < ENCODING_LENGTH - 1) {
    returnArray.push(DICTIONARY.PAD);
    i++;
  }
  
  // Log the result to see what you made.
  console.log([returnArray]);
  
  // Convert to a TensorFlow Tensor and return that.
  return tf.tensor([returnArray]);
}
```
The if statement ```for (var i = 0; i < wordArray.length; i++) {``` should be ```for (var i = 0; i < wordArray.length && i < ENCODING_LENGTH - 1; i++) {``` otherwise it violates the rule of the ML Model and throws the error like `Error: Error when checking : expected input_1 to have shape [null,20] but got array with shape [1,99].` when a user posts huge comments.

**Comment by tomoyanime** [comment]
I just found out that the later tutorial mentions the problem. https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#11
I feel it's still helpful if you mention the problem on the page to avoid confusion, https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#9

**Comment by jasonmayes** [comment]
Thanks @tomoyanime indeed I actually bought this up later to explain the limitations to consider when working with such models and how the user would need to break down long sentences into shorter ones and then write some function to calculate the score for the overall sentence. This was intentional but noted for future colabs to bring it upfront - thank you for the feedback.
