### ISSUE TITLE
Add public API to let users set certain environment flags

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#760]
The flags at https://github.com/tensorflow/tfjs-core/blob/master/src/environment_util.ts#L18 have code comments, but are not otherwise documented.  Since they don't show up in the API docs or tutorials, users don't know that they can say `tf.ENV.set('DEBUG', true);` and so forth.

**Comment by nsthorat** [comment]
I don't think we should document the environment flags. Instead, we should provide public API for the functionality we want to expose.

Environment flags are internal, we should feel free to remove them when we're comfortable with permanently keeping them true. For ones that truly will never be set to true forever, we can add something like `tf.enableDebugMode()`.

**Comment by davidsoergel** [comment]
+1, renamed this bug to match that.  However, doesn't this view mean that tf.ENV.set() or tf.ENV itself should not be exposed?

**Comment by nsthorat** [comment]
It's useful for us to have it as part of the public API, but I don't think it should be documented in our /api page if that's what you're asking (we don't want to encourage users to be tinkering there, it's more for us to debug issues with the library).

**Comment by nsthorat** [comment]
We now enable tf.enableDebugMode(), tf.enableProdMode().

Going to close this out -- for any new flags we'll create public API methods like this.
