### ISSUE TITLE
Fail to run MobileNetV2 in TensorFlow.js Model Benchmark with tflite backend

### ISSUE THREAD

**Issue by huningxin** [tensorflow/tfjs#7602]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): TensorFlow.js Model Benchmark
- TensorFlow.js version (use command below): 4.4.0
- Browser version: Chrome 112.0.5615.121
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**

1. Launch TF.js model benchmark: https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/
2. Set backend to `tflite`
3. Set model to `MobileNetV2`
4. Click “Run benchmark"
5. The site reports error "Error: Please provide a loadTflite method for 'MobileNetV2' model.)"

**Describe the expected behavior**

The benchmark should run MobileNetV2 model by tflite backend and report performance numbers.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Console log:
```
Uncaught (in promise) Error: Please provide a loadTflite method for 'MobileNetV2' model.
    at loadModelAndRecordTime ((index):540:15)
    at loadModel ((index):735:15)
    at runBenchmark ((index):764:32)
```

**Comment by gaikwadrahul8** [comment]
Hi, @huningxin 

Apologize for the delayed response and I was able to replicate same issue and it's giving me the same error message which you've mentioned in above error log, For your reference I have added screenshot below and I see to take care of this issue PR https://github.com/tensorflow/tfjs/pull/7608 has submitted and it's in progress. Thank you!

![image](https://user-images.githubusercontent.com/115997457/233925838-f82eeeaa-f0f2-4b54-99fc-86d5c466de36.png)

**Comment by Linchenn** [comment]
@huningxin The fix has been merged. Please verify it and another ISSUSE your reported, when you get a chance. Thanks!

**Comment by huningxin** [comment]
I verify it has been fixed. Thanks much @Linchenn !
