### ISSUE TITLE
Create a page that displays results of benchmarks across layers, core, etc.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#761]
It would be great to have a dashboard that displayed live benchmarking results across different models / ops so we could easily know when there's been a performance regression.

**Comment by rodrigob** [comment]
Was this implemented or deprecated ? 
If implemented, a pointer to the page might help future visitors of this ticket.

**Comment by annxingyuan** [comment]
@rodrigob thanks that's a good point!

Note that @caisq has implemented this as an internal page for now.
