### ISSUE TITLE
[e2e] Support test windows on webgpu

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7616]
This is a followup for https://github.com/tensorflow/tfjs/pull/7543.

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and I see you have submitted PR https://github.com/tensorflow/tfjs/pull/7543 and this issue will be taken care once that PR got merged and thank you for submitting PR, I really appreciate your efforts and time. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

I see this PR https://github.com/tensorflow/tfjs/pull/7543 has been merged. Has this resolved the issue ? or Are we still working on this issue ? Thank you!
