### ISSUE TITLE
[e2e] saved_model_v2_with_tensorlist_ops failed on webgpu due to dataSync

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7619]
A todo from PR: 
https://github.com/tensorflow/tfjs/pull/7543

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and I see you've have submitted PR https://github.com/tensorflow/tfjs/pull/7543 to take care of this issue and it will be taken care once that PR got merged. Thank you submitting PR, I really appreciate your efforts and time. Thank you!

**Comment by axinging** [comment]
@gaikwadrahul8 Sorry, PR https://github.com/tensorflow/tfjs/pull/7543 is not a fix for this issue. This issue is a todo for PR https://github.com/tensorflow/tfjs/pull/7543. I updated the issue comments

**Comment by axinging** [comment]
This is fixed by : https://github.com/tensorflow/tfjs/pull/7576
