### ISSUE TITLE
[Codelab]: TensorFlowJS Make a smart webcam in JavaScript with a pre-trained ML model

### ISSUE THREAD

**Issue by VGONUL** [tensorflow/tfjs#7629]
![image](https://user-images.githubusercontent.com/122591055/234488411-d0153585-978b-4540-bd11-b0c41ec463b8.png)
I tried to code on Django ,but it shows like this How May I correct it?

**Comment by jasonmayes** [comment]
My original code on Codepen / Glitch still works so my guess is you did not copy some containing element / or css correctly from my tutorial. Please check your compiled source code with whatever you created in your own environment with the working code here: https://glitch.com/~tensorflow-js-object-detection
