### ISSUE TITLE
Support for aarch64?

### ISSUE THREAD

**Issue by rytrose** [tensorflow/tfjs#765]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.0
#### Browser version
Google Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
#### Describe the problem or feature request
I'm looking to implement PoseNet on a [Jetson TX2](https://developer.nvidia.com/embedded/develop/hardware), but I'm not sure tfjs is supported on aarch64 architectures. On `npm install`, it skips `incompatible libtensorflow`. Does tfjs support aarch64, and I'm failing at something, or does it not and are there any plans to support it?

**Comment by davidsoergel** [comment]
As far as I understand, there are currently no official libtensorflow builds for arm64/aarch64 (tensorflow/tensorflow#17850), but you might be able to build one yourself.  

Normally this requires Bazel per https://www.tensorflow.org/install/source.  If that's not practical, there is a community-supported Makefile approach at tensorflow/blob/master/tensorflow/contrib/makefile/README.md. That suggests iOS and Android-specific ARM builds; I don't know what will happen in your environment, but it might be worth a try.

I think this is primarily a question for the TensorFlow team.  i.e. if you can get a working libtensorflow one way or another, the TF.js Node bindings should work with it.

(See also tensorflow/tensorflow#18643, and tensorflow/tensorflow#21332, and maybe other similar issues in that repo.)
