### ISSUE TITLE
Different Result when saving model and predicting using keras

### ISSUE THREAD

**Issue by kamalkraj** [tensorflow/tfjs#766]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js
0.13.0
#### Browser version

Chrome Version 69.0.3497.100 (Official Build) (64-bit)

#### Describe the problem or feature request
![screenshot 2018-10-05 at 10 51 39 pm](https://user-images.githubusercontent.com/17096858/46550513-f2720680-c8f2-11e8-8bcb-7f4197a911ae.png)

![screenshot 2018-10-05 at 10 52 49 pm](https://user-images.githubusercontent.com/17096858/46550494-e2f2bd80-c8f2-11e8-9315-64bcdf655176.png)

keras 2.2.2
tensorflow 1.11.0

#### Code to reproduce the bug / link to feature request

**Comment by davidsoergel** [comment]
My understanding is that small numeric differences are common but usually insignificant.  This one does look larger than I'd expect.

We have a test for this at https://github.com/tensorflow/tfjs-layers/tree/master/integration_tests/tfjs2keras, which generally passes.  You can run it, if you like, by checking out the tfjs-layers repo and typing `yarn; yarn test-integ`.  That could help determine if there's something weird that's specific to your setup.

**Comment by caisq** [comment]
@kamalkraj Can you share the .h5 file for your model so that we can try reproducing the issue on our end?

**Comment by kamalkraj** [comment]
Weights and downloaded from tensorflow js and converted keras weights 
[model.zip](https://github.com/tensorflow/tfjs/files/2452786/model.zip)

**Comment by caisq** [comment]
@kamalkraj Thanks for providing the model files. I am not able to reproduce your issue. I tried it on my Linux laptop, in these environments:

* Node.js, using tfjs-node 0.1.18
* In the browser (Chrome and Firefox), using tfjs 0.13.1. 

They all give the result [[0.2324104],], i.e., the same as the Python result, but different from the 0.21 result you got in your browser. What's your operating system and device type?

**Comment by kamalkraj** [comment]
Thanks , 
Now it is working
