### ISSUE TITLE
 tf.setBackend makes node-tfjs ignore the bindings

### ISSUE THREAD

**Issue by DavidGOrtega** [tensorflow/tfjs#768]
#### TensorFlow.js version
tfjs-node 0.1.18
#### Browser version
node 10.5.0
#### Describe the problem or feature request
tf.setBackend('cpu', false); 
makes tfjs ignore the bindings
#### Code to reproduce the bug / link to feature request

```js
global.fetch = require('node-fetch');

const fs    = require('fs'),
PNG         = require('pngjs').PNG; 

const tf    = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');

async function run(opts)
{
    const URI           = 'http://localhost/pix2pix/models/facades_A2B/tfjs/';
    const MODEL_URL     = URI + 'tensorflowjs_model.pb';
    const WEIGHTS_URL   = URI + 'weights_manifest.json';
    const model         = await tf.loadFrozenModel(MODEL_URL, WEIGHTS_URL);
    console.log('model loaded');
    
     try
    {
            let img = 'C:/test.png';
            const cc = await fromPNG(img);
            const input     = preprocess( cc.toFloat() ) ;
            console.log('input ready', input);
            
            tf.setBackend('cpu', false); //if ran out of memory can test in on CPU
            //THIS LINE IS GOING TO MAKE TFJS IGNORE THE BINDING
            let ts = new Date().getTime();
            const X         = model.execute( {"input": input} );
            console.log( new Date().getTime() - ts );
            
            console.log('X!!', X);
            
            const output    = postprocess( X);

            toPNG(output, 'C:/out.png');

    }catch(e)
    {
        console.error(e);
    }
    
    //model.dispose();
    
    function preprocess(x)
    {
        return tf.tidy(()=>
        {
            // Normalize the image. (0, 255)->(-1, 1)
            const offset    = tf.scalar(127.5);
            const norm      = x.div(offset).sub( tf.scalar(1) );

            //[3,W,H] -> [1, 3, W, H]
            const batched   = norm.expandDims(0);
            
            return batched;
        });
    }

    function postprocess(x)
    { 
        return tf.tidy(()=>
        {
            const offset    = tf.scalar(127.5);
            const denorm    = x.mul(offset).add(offset).clipByValue(0, 255).toInt();

            //[1, 3, W, H] -> [3,W,H]
            const reduced   = denorm.squeeze();

            return reduced;
        });
    }
}

run();

```

**Comment by DavidGOrtega** [comment]
I can see that actually tfjs registers three backends being cpu and gpu the one in the V8 engine. So it's a matter of naming convention.

**Comment by davidsoergel** [comment]
Yep: the 'cpu' and 'webgl' options are the browser backends.  For node bindings, you need setBackend('tensorflow').  (See https://js.tensorflow.org/api/latest/#setBackend).

It sounds like you want to use the node bindings, but force the native TensorFlow backend to use only the CPU?  We can't do that using setBackend(), but you can do it by setting an environment variable:

    CUDA_VISIBLE_DEVICES="-1"

(Using -1 as opposed to 0 is a workaround for an old issue that TF was spuriously allocating GPU memory anyway; see tensorflow/tensorflow#2175 and tensorflow/tensorflow/16284.  Using -1 will result in a benign error message about CUDA_ERROR_NO_DEVICE.  I don't know if the memory allocation thing is still a problem; 0 may work).

It may be possible to apply that setting automatically via a different backend name, e.g. 'tensorflow-cpu'.  @nkreeger, any thoughts on whether that's worthwhile?

**Comment by nkreeger** [comment]
We've been evaluating a device-selector API and the design that we'd like to surface internally. These plans are still initial stage and we can share them when we're ready to cut over for this work. 

As for Node.js - V7 has been deprecated for a while, current LTS support is V8.x.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
