### ISSUE TITLE
Profiling webgpu backend

### ISSUE THREAD

**Issue by MatPoliquin** [tensorflow/tfjs#7683]
When using webgpu backend I get this error message:

`tf-backend-webgpu.js:1698 This device doesn't support timestamp-query-inside-passes extension. Start Chrome browser with flag --disable-dawn-features=disallow_unsafe_apis then try again. Otherwise, zero will be shown for the kernel time when profiling mode is enabled. Using performance.now is not workable for webgpu since it doesn't support synchronous data read from GPU.`

using this code:
`const profile_info = await tf.profile(() => {
            let res = tf.matMul(mat1, mat2);
            res.dataSync();
            res.dispose();
        });`

So how can one profile operations in WebGPU? Please note that this exact code works with WebGL backend

EDIT:
tf.js 4.5
Windows 11
Chrome 113.0.5672.93 64 bit

**Comment by qjia7** [comment]
@MatPoliquin What platform are you using? Currently, profiling on MacOS is still not supported. We are working on it. Expect it will be available on next 1~2 releases. Thanks.

**Comment by MatPoliquin** [comment]
@qjia7 I am using:
tf.js 4.5
Windows 11
Chrome 113.0.5672.93 64 bit

**Comment by qjia7** [comment]
Weird. Do you add the flag `--disable-dawn-features=disallow_unsafe_apis` when launching the chrome browser like below?
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-dawn-features=disallow_unsafe_apis
```

**Comment by MatPoliquin** [comment]
@qjia7 After adding the flag it works (hard to say if the profiling data is accurate though). Will it work without this flag eventually?

**Comment by qjia7** [comment]
Please feel free to file bugs if you see some performance issues.

>Will it work without this flag eventually?

It depends on chrome's support. You can file an [issue](https://bugs.chromium.org/p/chromium/issues/entry) there to ask the plan. My understanding is it's due to security issue that it's behind a flag.

**Comment by qjia7** [comment]
We have refactored our profiling code by #7714. Now both windows/MacOS should support it.
chrome stable with flag: `--disable-dawn-features=disallow_unsafe_apis`
chrome canary with flag: `--enable-dawn-features=allow_unsafe_apis`.
