### ISSUE TITLE
how can I save custom speech-command model from the eg. page?

### ISSUE THREAD

**Issue by mike8625** [tensorflow/tfjs#7684]
I am a beginner, I open the following page, and train a simple model 

[https://storage.googleapis.com/tfjs-speech-model-test/2019-01-03a/dist/index.html
![demo1](https://github.com/tensorflow/tfjs/assets/3270865/d8829d5c-23cc-4e49-a2b1-aff47307f87b)
](url)

I click the  "save model" button and it show "model saved", but where is it? How can I save the model to my computer?

**Comment by gaikwadrahul8** [comment]
Hi, @mike8625 

Apologize for the delayed response and May I know have you checked the `browser’s IndexedDB` and `downloads` folder whether model has downloaded or not ? please refer this [article](https://medium.com/@selvam85/saving-and-uploading-a-tensorflow-js-speech-model-fdb0eddf5dae) which may help you to solve your issue. Thank you!

**Comment by mike8625** [comment]
Apologize for the delayed response and I have solved the problem.  it saved on browser’s IndexedDB by default, I dont know how to convert it to a file. finally I  changed it to the download(find the code from the source, change 'indexeddb://my-model' to  downloads://my-model).
