### ISSUE TITLE
All tests in https://js.tensorflow.org/api/latest are broken

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#7688]
Steps to reproduce:
1. launch chrome and navigate to https://js.tensorflow.org/api/latest/#tensor
2. Click the `Run` button.

Expect get a result. However, below error message is shown. In face, it seems that all cases have this regression.
```
An error occured on line: 2
The highest priority backend 'webgpu' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods

**Comment by qjia7** [comment]
@mattsoulanille Please take a look, thanks.

**Comment by qjia7** [comment]
It seems that we missed an `await` before `tf.setBackend`. And not sure whether we need to change of priority of webgpu [here ](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/base.ts#L62) and adjust it to `2` to keep it same with webgl/wasm.

**Comment by Linchenn** [comment]
Pushed the fix to the website and it should work now.
