### ISSUE TITLE
WebGPU 4.6.0 version failed to compute kernels

### ISSUE THREAD

**Issue by Linchenn** [tensorflow/tfjs#7700]
With WebGPU 4.6.0, when running the following codes, you would get an error:
```js
a = tf.ones([100, 100]);
b = tf.ones([100, 100]);
tf.add(a, b);
```

Error:
![image](https://github.com/tensorflow/tfjs/assets/40653845/83b00d88-0ce2-420f-85ab-bfc7db0bc888)

**Comment by qjia7** [comment]
@Linchenn I can't reproduce it locally. It seems that two different webgpu versions are mixed together. Do you see any warning like that ` The kernel 'Add' for backend 'webgpu' is already registered`?

**Comment by Linchenn** [comment]
Thanks Jiajia, this is because the benchmark tool is not updated with new changes.

Updated the benchmark tool, using `./scripts/deploy-benchmarks.sh`.
