### ISSUE TITLE
Add tf.math.confusionMatrix

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#771]
The API may mirror tf.confusion_matrix in (Python) TensorFlow:
https://www.tensorflow.org/api_docs/python/tf/confusion_matrix

**Comment by caisq** [comment]
cc @dsmilkov @nsthorat  @tafsiri  Let me know whether it makes sense for it to be added the core and exposed under the public API tf.confusionMatrix. (I've mentioned this to some of you a couple of weeks back, but final I have an opportunity to get around to do it).

**Comment by tafsiri** [comment]
SGTM. I did want to share that some of the names are moving around for tf 2.0. According to https://github.com/tensorflow/community/pull/16/files#diff-98487f07a4b6b9300c29023357535f3fR195 tf.confusion_matrix => tf.train.confusion_matrix. I find the new namespace a bit surprising though as I'd imagine wanting to use confusion matrix outside of training.

**Comment by dsmilkov** [comment]
Good point about the names moving around tf 2.0 - we should follow that proposal going forward.

**Comment by bileschi** [comment]
Assuming that TF doesn't want to leave confusion matrix as a top-level element, is there a better existing choice than 'train'?  Does it belong in perhaps 'math'?

**Comment by caisq** [comment]
I also find the proposed namespace a little surprising. confusion matrix doesn't seem to belong under the `train` category. For example, one can evaluate the confusion matrix of a model even without training it. cc'ing @annarev

**Comment by caisq** [comment]
FYI, I commented on the TF RPC PR.

**Comment by caisq** [comment]
Update: @annarev has agreed to change the name path to tf.math.confusion_matrix in Python TensorFlow. So we'll do the "tf.math.confusionMatrix" in tfjs.

**Comment by dsmilkov** [comment]
Yay! Thank you for the quick resolve!
