### ISSUE TITLE
README says `node-gyp` supports only Python2.7 but `node-gyp` says it doesn't support it 

### ISSUE THREAD

**Issue by stephanzlatarev** [tensorflow/tfjs#7716]
https://github.com/tensorflow/tfjs/blob/f7fa5af8f7a6245ff9e0ab32714bb9e33448403f/tfjs-node/README.md?plain=1#L42-L44

The error message I receive from `node-gyp` contradicts the above:

```
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@16.20.0 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is "C:\tools\python2\python.exe"
npm ERR! gyp ERR! find Python - version is "2.7.0"
npm ERR! gyp ERR! find Python - version is 2.7.0 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
```

Is the README statement outdated, or am I doing something wrong?

**Comment by gaikwadrahul8** [comment]
Hi, @stephanzlatarev 

Apologize for the delayed response and I'll try to replicate the same issue from my end on windows machine with python version 2.7 and will check whether I'm also getting the same error message or I'm not sure at the moment whether have we done any changes w.r.t python version and we haven't updated our official documentation about python version which we support for` node-gyp`

We'll update soon and thank you for noticing this issue, I really appreciate your time and efforts. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @stephanzlatarev 

Apologize for the delayed response and at the moment we don't support python version `2.7 `so could you please try with python version `>=3.6.0` and we'll update our official documentation once we done testing with python version `>=3.6.0` and I tested with python version `3.11` and it's working as expected 

Could you please try from your end and let us know whether is it working as expected or not ? Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @stephanzlatarev 

We're doing the testing with python versions `>=3.6.0` at the moment and once we're done and everything works as expected, we'll definitely update our official documentation, I really appreciate your efforts and time for bringing this issue to our attention. 

Once we update our official documentation after testing with python version `>=3.6.0` will update you same here. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @stephanzlatarev 

I apologize for the delayed response and I tried to replicate the same issue from my end with `python 2.7` version on my `windows 10` machine and it's working as expected with Node.js versions `Node.js v19.9.0` and `Node.js v18.16.1` for reference I have added both the output log and I see `node-gyp ` updated their [official documentation](https://github.com/nodejs/node-gyp#configuring-python-dependency) with hyperlink [supported version python](https://devguide.python.org/versions/#supported-versions) which is `3.8` onwards

I see you were trying with Node.js version `16.20.0` and as per my current understanding with some Node.js version `python 2.7` is also working but as far I know we always recommend to use stable python 3.x versions with tfjs-node and it should work.

Our relavant team is working on to update our tfjs-node official documentation and soon will be updated so to confirm, do you want to keep this issue open ? if not, please feel free to close this issue.

Thank you for your understanding and patience.

1. Using `Node.js v18.16.1` :

```
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> node --version
v18.16.1
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> npm --version
9.8.0
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> pyenv which python
C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> npm install -g node-gyp --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe"   

changed 99 packages in 9s

14 packages are looking for funding
  run `npm fund` for details
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> npm install --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe" @tensorflow/tfjs-node

up to date, audited 122 packages in 2s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> node .\index.js
2023-11-30 14:07:23.824711: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1 / 3
eta=0.0 ==================================================================================>
3257ms 326us/step - MAE=0.335 loss=0.173 val_MAE=0.320 val_loss=0.157
Epoch 2 / 3
eta=0.0 ==================================================================================>
2434ms 243us/step - MAE=0.281 loss=0.115 val_MAE=0.281 val_loss=0.115
Epoch 3 / 3
eta=0.0 ==================================================================================>
2196ms 220us/step - MAE=0.261 loss=0.0954 val_MAE=0.262 val_loss=0.0960
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-2.7> 
```

2. Using `Node.js v19.9.0` :

```
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> node --version
v19.9.0
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> npm -v
9.6.3
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> pyenv which python
C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> npm install -g node-gyp --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe"   

changed 99 packages in 8s
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> npm install --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\2.7.5\python.exe" @tensorflow/tfjs-node

added 121 packages, and audited 122 packages in 2m

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-2.7> 

```

**Comment by questmapping** [comment]
Hi @gaikwadrahul8, I think I've got the same problem on Windows11. I used Anaconda Navigator to install python 3.11.6 and then opened an Admin cmd prompt with conda environment active. This is the result of my installation tryout:
```
node --version
v21.1.0

npm -v
10.2.3

where python
C:\Users\MightySocks777\anaconda3\envs\base3-11-6\python.exe
C:\Users\MightySocks777\anaconda3\python.exe
C:\Users\MightySocks777\AppData\Local\Microsoft\WindowsApps\python.exe

npm install -g node-gyp --python="C:\Users\MightySocks777\anaconda3\envs\base3-11-6\python.exe"

changed 99 packages in 6s

14 packages are looking for funding
  run `npm fund` for details


npm install --python="C:\Users\MightySocks777\anaconda3\envs\base3-11-6\python.exe" @tensorflow/tfjs-node
npm ERR! code 1
npm ERR! path C:\Node projects\rxdb\examples\vue\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-4.14.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
npm ERR!   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:289
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'C:\Node projects\rxdb\examples\vue\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'C:\Node projects\rxdb\examples\vue\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'C:\\Node projects\\rxdb\\examples\\vue\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'C:\\Node projects\\rxdb\\examples\\vue\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR! Node.js v21.1.0
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:422:12)
npm ERR!     at ChildProcess.emit (node:events:515:28)
npm ERR!     at maybeClose (node:internal/child_process:1105:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
npm ERR!   code: 1,
npm ERR!   killed: false,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
npm ERR! }

npm ERR! A complete log of this run can be found in: C:\Users\MightySocks777\AppData\Local\npm-cache\_logs\2023-12-07T17_34_38_704Z-debug-0.log
```
I'm attaching the full log
[2023-12-07T17_34_38_704Z-debug-0.log](https://github.com/tensorflow/tfjs/files/13603305/2023-12-07T17_34_38_704Z-debug-0.log)

**Comment by gaikwadrahul8** [comment]
Hi, @questmapping 

Thank you for providing the detailed error log and it's known issue it's happening with latest Node.js versions like `Node.js v21.1.0` and `20.10.0 LTS`, our relevant team is working on this issue and will update you soon. 

At the moment workaround is downgrading the Node.js version to either `v18.16.1` or `v19.9.0` so please give it try and let us know is it working as expected or not ? 

I would suggest you to create new [issue](https://github.com/tensorflow/tfjs/issues/new/choose) with your error log for issue tracking purpose on Windows 11 system and above workaround I have tested on Windows 10 system. 

Thank you for your understanding and patience.

**Comment by questmapping** [comment]
> At the moment workaround is downgrading the Node.js version to either `v18.16.1` or `v19.9.0` so please give it try and let us know is it working as expected or not ?

By Downgrading to v19.9.0 it works like a charm

**Comment by gaikwadrahul8** [comment]
Hi, @stephanzlatarev 

I apologize for the delay in my response. I have addressed the issue in Pull Request https://github.com/tensorflow/tfjs/pull/8101. Please note that due to the upcoming Christmas and New Year holidays, the review and merge process may take longer than usual. If you believe this PR resolves the issue, please feel free to close this issue.

Thank you for your patience and understanding.
