### ISSUE TITLE
Working react native empty project example

### ISSUE THREAD

**Issue by coucoseth** [tensorflow/tfjs#7718]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):4.6.0
- Are you willing to contribute it (Yes/No):no

**Describe the feature and the current behavior/state.**
I have spent a very long time(close to a month) trying to figure out the correct package versions to use, all the projects i created in this attempt have had this same package issue, a conflict between versions of expo-camera and @tensorflow/tfjs-react-native.
When installing @tensorflow/tfjs-react-native i have always got the error below
```
Found: expo-camera@12.3.0 from the root project
Could not resolve dependency:
 peer expo-camera@"^7.0.0" from @tensorflow/tfjs-react-native@0.8.0
 node_modules/@tensorflow/tfjs-react-native
  @tensorflow/tfjs-react-native@"0.8.0" from the root project

 Fix the upstream dependency conflict, or retry
 this command with --force or --legacy-peer-deps
 to accept an incorrect (and potentially broken) dependency resolution.
```

As suggested by the error logs, installing the dependencies using either --force or --legacy-peer-deps will get the packages in your project however they are always broken, forexample expo camera doesnot function as expected, please refer to [this issue](https://github.com/tensorflow/tfjs/issues/7708) for more info, other issues include build fails.
I am not sure if the package versions are just conflicting or its caused by the way i install expo in my bare react native projects. According to [these docs](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native), it states to use `react-native-unimodules` but that is deprecated so the command i use is `npx install-expo-modules`

I request for a bare react native empty project template with working dependencies that will require me to clone and run `npm install` to get started (i am really frustrated, please help)
Kindly note that i cloned the examples provided and using the pose-detection folder, i had the same dependency install issue, after using `npm i --legacy-peer-deps` , i failed to install pods and was getting the error
```
Invalid `Podfile` file: cannot load such file -- /Users/seth/Desktop/projects/pose-detection/node_modules/react-native-unimodules/cocoapods.rb.
```

**Will this change the current api? How?**
if the version of expo-camera in @tensorflow/tfjs-react-native is changed, then maybe there will be changes. Not sure
**Who will benefit with this feature?**
every react native developer
**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @coucoseth 

Apologize for the delayed response and I was trying to run this react native examples `tfjs-examples/react-native/pose-detection` and I was able to run that examples by following the same instructions which are mentioned in this [official documentation ](https://www.tensorflow.org/js/tutorials/applications/react_native) and I tried to run that examples with below package dependancies so for your reference I have added package.json file below so I would request you to please give it try from your end and let us know whether is it working as expected or not ? 

If issue still persists please let us know with error log ? Thank you!

```
{
  "name": "pose-detection-with-tfjs-react-native-expo",
  "main": "index.js",
  "version": "0.0.1",
  "license": "Apache-2.0",
  "scripts": {
    "build-dep": "cd ../../../tfjs/tfjs-react-native && yarn build-npm",
    "copy-dep": "rm -rf node_modules/@tensorflow/tfjs-react-native/dist/* && cp -rf ../../../tfjs/tfjs-react-native/dist/* node_modules/@tensorflow/tfjs-react-native/dist/",
    "start": "expo start"
  },
  "dependencies": {
    "@mediapipe/pose": "~0.4.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@tensorflow-models/pose-detection": "2.0.0",
    "@tensorflow/tfjs": "3.18.0",
    "@tensorflow/tfjs-react-native": "0.8.0",
    "expo": "~46.0.2",
    "expo-camera": "^12.5.0",
    "expo-file-system": "^14.1.0",
    "expo-gl": "^11.4.0",
    "expo-gl-cpp": "^11.4.0",
    "expo-screen-orientation": "~4.3.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.9",
    "react-native-fs": "2.14.1",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-svg": "12.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@expo/webpack-config": "^0.15.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.64.3",
    "babel-preset-expo": "~8.3.0",
    "jest-expo": "~41.0.0",
    "typescript": "~4.0.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

For your reference, I have added screenshot below :

```
gaikwadrahul-macbookpro:pose-detection gaikwadrahul$ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @tensorflow-models/pose-detection@2.0.0" has unmet peer dependency "@tensorflow/tfjs-converter@^3.13.0".
warning " > @tensorflow-models/pose-detection@2.0.0" has unmet peer dependency "@tensorflow/tfjs-core@^3.13.0".
warning " > @tensorflow-models/pose-detection@2.0.0" has unmet peer dependency "@tensorflow/tfjs-backend-webgl@^3.13.0".
warning " > @tensorflow-models/pose-detection@2.0.0" has unmet peer dependency "@tensorflow/tfjs-backend-wasm@^3.13.0".
warning "@tensorflow/tfjs > @tensorflow/tfjs-data@3.18.0" has unmet peer dependency "seedrandom@~2.4.3".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-backend-cpu@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-backend-webgl@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "@tensorflow/tfjs-core@~3.11.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has unmet peer dependency "expo-asset@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "expo-camera@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "expo-gl@^7.0.0".
warning " > @tensorflow/tfjs-react-native@0.8.0" has incorrect peer dependency "react@^16.12.0".
warning "expo-camera > @koale/useworker@4.0.2" has incorrect peer dependency "react@^16.8.0".
warning "react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning " > react-native-fs@2.14.1" has unmet peer dependency "prop-types@^15.6.0".
warning " > react-native-fs@2.14.1" has incorrect peer dependency "react@^16.2.0".
warning "jest-expo > react-test-renderer@16.11.0" has incorrect peer dependency "react@^16.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 17.64s.
gaikwadrahul-macbookpro:pose-detection gaikwadrahul$ yarn start
```

**Comment by coucoseth** [comment]
my problem has been  using npm to install dependencies, after switching to yarn. everything is running as expected. thanks @gaikwadrahul8

**Comment by anony-mouse1** [comment]
I'm having this same issue, and even after using your solution it has still not been resolved.
