### ISSUE TITLE
tfjs-react-native with expo

### ISSUE THREAD

**Issue by AREEG94FAHAD** [tensorflow/tfjs#7726]
I am trying to run a model in React Native using tfjs-react-native, but it is not compatible with the new version of Expo Can you update the tfjs-react-native.

**Comment by gaikwadrahul8** [comment]
Hi, @AREEG94FAHAD 

Apologize for the delayed response and It seems like at the moment we don't support latest version of Expo with react native  if I'm not wrong and please check this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753) and if you're looking tfjs-react-native with expo then I would suggest you to please try to use package dependancies which are mentioned below and also refer this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and we'll update soon about compatibility of tfjs-react-native with latest version of Expo. Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```

**Comment by Priyanshu88** [comment]
Hi @gaikwadrahul8. I had just cloned the repo and run it locally, and it is not working still. Please upgrade at least make the package compatible to  new expo version.

**Comment by lights9** [comment]
Hello @gaikwadrahul8,
I've tried the listed dependencies above, but unfortunately nothing seems to work, need to use this library for my project.. Is there any way I can make it work, considering the fact that the new Expo Go app , only supports recent expo sdk versions?? Does it work without issues if it is used in an app created using the react-native cli (but tfjs also depends on certain expo libraries)??

**Comment by AREEG94FAHAD** [comment]
> Hello @gaikwadrahul8, I've tried the listed dependencies above, but unfortunately nothing seems to work, need to use this library for my project.. Is there any way I can make it work, considering the fact that the new Expo Go app , only supports recent expo sdk versions?? Does it work without issues if it is used in an app created using the react-native cli (but tfjs also depends on certain expo libraries)??

I trained my model using Python, then I used an API to send my image/text for classification from the app. Because it does not work like yours, this can be an alternative until they make an update

**Comment by WesleyFrancis** [comment]
Doing any ai related project recently have been the bane of my existence as a dev with recent object detection projects. Versioning and dependency issues are abundant. What do other devs combine to get stuff working?

**Comment by gaikwadrahul8** [comment]
Hi, @AREEG94FAHAD, @Priyanshu88 , @lights9 , @WesleyFrancis 

I apologize for the delayed response and it seems like we have updated tfjs-react-native dependencies with the help of this PR [#8062](https://github.com/tensorflow/tfjs/pull/8062/files) and that PR got merged so could you please confirm from your end, is it working as expected ?

I would suggest you to check tfjs-sample-expo-app from [here](https://github.com/paradite/tfjs-sample-expo-app?tab=readme-ov-file#tfjs-sample-expo-app)

If issue still persists please let us know. Thank you for your cooperation and patience.

**Comment by EmePin** [comment]
Still not working :c

**Comment by zholmes1** [comment]
Is tfjs-react-native abandoned? You're forced to use expo packages that are over 2 years old which causes all sorts of problems with other dependencies, regardless of if you're using Expo Managed, Bare, or even CLI.
