### ISSUE TITLE
[webgpu] Support imageOptions.alpha for draw

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7727]

**Comment by gaikwadrahul8** [comment]
Hi, @axinging

Apologize for the delayed response and I found this [source code](https://github.com/tensorflow/tfjs/blob/7b84039560ef08bea1fbf45cc5453741dcc9e798/tfjs-backend-webgpu/src/draw_webgpu.ts) so I'm not sure whether are you looking the same thing or do you want to add `alpha` option for imageOptions.alpha for draw in webgpu ? If yes then this issue will be considered as feature request 

If possible could you please help us with code snippet or example where we can use alpha option for imageOptions for draw in webgpu ? Thank you!

**Comment by qjia7** [comment]
Fixed by #7749
