### ISSUE TITLE
Why are you going to run the same code twice?

### ISSUE THREAD

**Issue by KimYoungBo** [tensorflow/tfjs#773]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.7

#### Describe the problem or feature request
RMSPropOptimizer.prototype.applyGradients = function (variableGradients) {
  var _loop_1 = function (variableName) {
      tidy(function () {
          var newAccumulatedMeanSquare = _this.decayScalar.mul(accumulatedMeanSquare)
              .add(_this.oneMinusDecay.mul(gradient.square()));
          if (_this.centered) {
          } else {
             **_// The above code is the same._**
              var newAccumulatedMeanSquare_1 = _this.decayScalar.mul(accumulatedMeanSquare)
                  .add(_this.oneMinusDecay.mul(gradient.square()));
          }
      });
  };
};

**Comment by nsthorat** [comment]
That's just what the compiler decided to do, you can read the TypeScript code here: https://github.com/tensorflow/tfjs-core/blob/master/src/optimizers/rmsprop_optimizer.ts#L94
