### ISSUE TITLE
WebGpu backend fails where webGL doesn't.

### ISSUE THREAD

**Issue by Pensarfeo** [tensorflow/tfjs#7733]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- Windows 10
- Desktop
- TensorFlow.js installed from (npm or script link):
                "@tensorflow/tfjs-backend-cpu": "^4.5.0",
		"@tensorflow/tfjs-backend-wasm": "^4.6.0",
		"@tensorflow/tfjs-backend-webgl": "^4.6.0",
		"@tensorflow/tfjs-backend-webgpu": "^4.6.0",
		"@tensorflow/tfjs-converter": "^4.2.0",
		"@tensorflow/tfjs-core": "^4.6.0",
- TensorFlow.js version (use command below): 4.6.0
- Browser version: Version 113.0.5672.127 (Official Build) (64-bit)
- Tensorflow.js Converter Version: 4.2.0

**Describe the expected behavior**
The code bellow returns an array of zeroes when using webGpu backend vs webgl backend.

**Standalone code to reproduce the issue**

const div255Tensor = tf.add(zeros([modelWidth, modelHeight, 3]), 1/255)
const mul = tf.mul(div255Tensor, div255Tensor)
console.log(await div255Tensor.data()) // <== Array of 0s using webgpu
console.log(await mul.data()) // <== Array of 0s using webgpu

I tried using webGPU about a month ago and it worked, so I assume is something related to a chrome update

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by qjia7** [comment]
@Pensarfeo I used below code to verify, but I can't reproduce your issue.
Please note that I changed `zeros` to `tf.zeros` and use `224`, `224` as the `modelWidth` and `modelHeight` in your example.
```
await tf.setBackend('webgpu');
const div255Tensor = tf.add(tf.zeros([224, 224, 3]), 1/255)
const mul = tf.mul(div255Tensor, div255Tensor)
console.log(await div255Tensor.data())
console.log(await mul.data())
```
The console result is as below:
```
Float32Array(150528) [0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, 0.003921568859368563, ...
Float32Array(150528) [0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, 0.000015378702300949953, ...

**Comment by Pensarfeo** [comment]
Hi @qjia7 Thanks for the feedback
So, I tried your code, this is a bit weird, my backend gets set somewhere else in my code. If I set ```webgl``` as backend to start with, and then I run your example (resetting the backend to ```webgpu```), then it works, but if I start with webgpu then I get the error. could it be that I am running more than 1 model, I am using movenet together with a custom detector

**Comment by qjia7** [comment]
Can you paste your error log (including any warnings)? I think your errors happen in other places not the codes you pasted above. It will be great if you can provide a complete example to reproduce your issue. Thanks.

**Comment by Pensarfeo** [comment]
There are no errors

**Comment by Pensarfeo** [comment]
or warnings

**Comment by qjia7** [comment]
@Pensarfeo It's hard for me to fix it if I can't reproduce this issue. Can you help to give me a reproducible test case for debugging?

**Comment by Pensarfeo** [comment]
@qjia7 I understand, ill keep digging, to see if I can narrow it down!
Thanks for the help

**Comment by gaikwadrahul8** [comment]
Hi, @Pensarfeo 

I have also tried the same code given by @qjia7 and it's working as expected if I'm not wrong, For your reference I have added output screenshot below.

If issue still persists for you please let us know with error log and I would suggest you to please try above code in different browsers so we'll come to know whether this issue is specific to any browser. 

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

Here is output screenshot  :

![image](https://github.com/tensorflow/tfjs/assets/115997457/a60be0d9-13e0-4b8d-9de4-a3594665fb4b)

**Comment by Pensarfeo** [comment]
@gaikwadrahul8 Thanks for giving it a try, yep, I'll try a bunch of stuff and let you know!

**Comment by Pensarfeo** [comment]
I have not yet managed to test it on an other machine/browser, but I was playing with the code today and the problem seems to disappear if I remove this dependency ```'@tensorflow-models/pose-detection'```

```js
import '@tensorflow/tfjs-backend-webgl'
import '@tensorflow/tfjs-backend-webgpu' 
import {createDetector as makeDetector} from '@tensorflow-models/pose-detection'
import {setBackend, zeros, browser, image, expandDims, squeeze, mul, add, tidy} from '@tensorflow/tfjs-core'

const backend = navigator.gpu ? 'webgpu' : 'webgl'
console.log('backend:', backend)
// const backend = 'webgl'
setBackend(backend).then( async () => {

  const div255Tensor = add(zeros([224, 224, 3]), 1/255)
  const mult = mul(div255Tensor, div255Tensor)
  console.log(await div255Tensor.data())
  console.log(await mult.data())
})
```

the problem disappears if I comment out the line with this line:
```js 
import {createDetector as makeDetector} from '@tensorflow-models/pose-detection'
```

**Comment by qjia7** [comment]
This is a known issue and fixed by https://github.com/tensorflow/tfjs-models/pull/1140. However, `pose-detection` hasn't been released a new version with this fix.
@mattsoulanille Can you help release a new `pose-detection` version? Maybe we also need to upgrade the corresponding webgl/webgpu version.

**Comment by Pensarfeo** [comment]
@qjia7 Fantastic! Then this is a duplicated issue! Thanks for the help! I'll go ahead and close the issue.
