### ISSUE TITLE
[webgpu]Kernel 'ExpandDims' not registered for backend 'webgpu'

### ISSUE THREAD

**Issue by vacing** [tensorflow/tfjs#7736]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:

```js
                    const img = await webcam.capture();
                    console.log(img.shape)
                    const src = tf.tidy(() => img.expandDims(0).div(255)); // normalize input
```

I use official version from jsdeelivr, and test with chrome(114.0.5735.110):
>{
    "tfjs-core": "3.19.0",
    "tfjs-backend-cpu": "3.19.0",
    "tfjs-backend-webgl": "3.19.0",
    "tfjs-data": "3.19.0",
    "tfjs-layers": "3.19.0",
    "tfjs-converter": "3.19.0",
    "tfjs": "3.19.0"
}

**Describe the current behavior**
```
engine.js:548 Uncaught (in promise) Error: Kernel 'ExpandDims' not registered for backend 'webgpu'
    at t.runKernel (engine.js:548:13)
    at expandDims_ (expand_dims.js:53:17)
    at expandDims__op (operation.js:51:22)
    at Qw.expandDims (expand_dims.js:30:10)
    at index.html:54:51
    at engine.js:467:20
    at t.scopedRun (engine.js:478:19)
    at t.tidy (engine.js:465:17)
    at Object.pI [as tidy] (globals.js:192:17)
    at main (index.html:54:36)
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by qjia7** [comment]
@vacing Can you use the latest version `4.6.0` instead of `3.19.0`? I think `ExpandDims` has been supported in  `4.6.0`.

**Comment by vacing** [comment]
> Can you use the latest version `4.6.0` instead of `3.19.0`? I think `ExpandDims` has been supported in `4.6.0`.

oh, I make a mistake for specified tfjs version when import the js lib, remove the version makes it works fine now, thanks ^^
