### ISSUE TITLE
Error while loading Movinet  fine tuned model after converting it into tfjs file

### ISSUE THREAD

**Issue by FrIdAy-101-max** [tensorflow/tfjs#7738]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

Uncaught n Error: Unknown layer: MovinetClassifier. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().

**Comment by gaikwadrahul8** [comment]
Hi, @FrIdAy-101-max 

Thank you for reporting this issue, if possible could you please help us with your code and error log to replicate the same issue from our end ? 

At the moment, it seems like in your code you're using such layer which does not support in TFJs yet if that is the case then this issue will be considered as feature request but to cross verify please help us with code snippet and error log. Thank you!

**Comment by FrIdAy-101-max** [comment]
Its seems like when the Library is present in Python as which can be called and I wonder why can't be it added  and if there are any materials that are there to convert tfjs model with customization layer please provide it.

**Comment by gaikwadrahul8** [comment]
Hi, @FrIdAy-101-max 

Could you please help us with your codepen/code example or your Github repo link where you're getting below error message so we'll try to replicate the same issue from our end so we'll considered this issue as feature request ? Thank you!

```
Uncaught n Error: Unknown layer: MovinetClassifier. This may be due to one of the following reasons:

The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass(). 
```

**Comment by mattsoulanille** [comment]
If you only need to run model inference, you can try converting to a TFJS graph model instead of a layers model. That will decompose the model into lower level ops instead of layers, which are more likely to be supported.
