### ISSUE TITLE
Load all the model files from the local and serve them using my local express server for the tensorflow/handpose model

### ISSUE THREAD

**Issue by jhayush0502** [tensorflow/tfjs#7758]
I want to **load all the model files include model.json,anchor.js and all the shard files through my local server.**

I have downloaded all the files...
shard files include shard1of2,shard2of2 for handdetector and handskeleton and all.

But I am unable to find the way to load them from the server present locally. Anyone help me out in same ?!

**Comment by gaikwadrahul8** [comment]
Hi, @jhayush0502 

Thank you for contacting us and May I know exactly what steps are you following to load all the model files from local and serve them using your local express server please ?

May I know which API are you using to load model ? we have two API's to load models in TFJs and check out which type of model you're loading by checking `model.json` file in that it will be mentioned either `{"format": "graph-model"} `or `{"format": "layer-model"}` accordingly you'll have to use either [tf.loadGraphModel](https://js.tensorflow.org/api/latest/#loadGraphModel) or [tf.loadLayersModel](https://js.tensorflow.org/api/latest/#loadLayersModel) to load  model.

If I'm not wrong you'll have to do something like below, please try it out and let us know whether is it resolving your issue or not ? If issue still persists please let us know with error log and steps to replicate the same issue from our end ? Thank you!

```
const express = require('express');
const tf = require('@tensorflow/tfjs');

const app = express();

const model = await tf.loadLayersModel('path/to/model.json');

app.use('/models', express.static('path/to/models'));

app.listen(3000);

console.log('Model server started at http://localhost:3000/models');
```

**Comment by jhayush0502** [comment]
Hi @gaikwadrahul8 ,
I am using express server which runs at port 3001 and serve required files from the local. The server code is->

```
const express = require('express');
const app = express();
const path = require('path');
const cors = require('cors');

app.use(cors());
app.use(function (req, res, next) {
   
     res.header(
     "Access-Control-Allow-Methods",
     "GET, POST, OPTIONS, PUT, HEAD, DELETE"
   );
   res.header("Access-Control-Expose-Headers", "Content-Length");
   res.header(
     "Access-Control-Allow-Headers",
     "Origin, X-Requested-With, Content-Type, Accept, Authorization, Accept-Language"
   );
 
    next();
 });
const port = 3001;
app.use('/handModelDetector',express.static('HandModelDetector'));
app.use('/handModelSkeleton',express.static('HandModelSkeleton'));
app.use(express.static('HandModelSkeleton'))
app.listen(port, () => {
  console.log(`Express server is running on port ${port}`);
});
```
I observed that handpose models loads two model.json i.e handdetection & handskeleton thus I have put them into seperate folder structure and each contain there model.json and shard files as group1of2,group2of2 etc and the common anchors.json from one of the folder.

I have my react app for handpose model running at port 3000. In that I have loaded this models as ->

```
  const runHandpose = async () => {
const model1Url = 'http://localhost:3001/handModelDetector';
const model2Url = 'http://localhost:3001/handModelSkeleton';

const net = await handpose.load({
  model: {
    bundleUrl: `${model1Url}/bundle.js`,
    modelUrl: [`${model1Url}/model.json,${model2Url}/model.json`],
    anchorUrl: `${model1Url}/anchors.json`,
    shardUrls: [
      `${model1Url}/group1-shard1of2.bin`,
      `${model1Url}/group1-shard2of2.bin`,
      `${model2Url}/group1-shard1of2.bin`,
      `${model2Url}/group1-shard2of2.bin`,
    ],
  },
});
   // const net = await handpose.load()
    console.log('Handpose model loaded.')
    setInterval(() => {
      //for detecting hand in net
      detect(net)
    }, 100)
  }
  useEffect(() => {
    runHandpose()
  }, [])
```

I am not sure whether I have correct files to serve since I have downloaded them using network console. I am sharing the zipped version of my file structure ,please have a look to it once and also have comment that where I am getting wrong in this and what all the bundle.js is ....
[modelFiles.zip](https://github.com/tensorflow/tfjs/files/11770022/modelFiles.zip)

**Comment by gaikwadrahul8** [comment]
Hi, @jhayush0502 

Apologize for the delayed the response and I checked your model.json files for both the models, both are having `"format": "graph-model"` so you'll have to use [tf.loadGraphModel](https://js.tensorflow.org/api/latest/#loadGraphModel) to load your models something like below and just add absolute path to your models `model.json `file so could you please give it try and let us know whether is it resolving your issue or not ? 

```
const modelUrl =
    'https://storage.googleapis.com/tfjs-models/savedmodel/mobilenet_v2_1.0_224/model.json';
const model = await tf.loadGraphModel(modelUrl);
```


If issue still persists please let us know ? Thank you!

**Comment by jhayush0502** [comment]
Hello @gaikwadrahul8 , yes I tried what you explained above. It get solved but I am unable to load -> 
**anchors.json?tfjs-format=file
model.json?tfjs-format=file
model.json?tfjs-format=file**

How can I load these models ?

Please you help me out in this.....

**Comment by gaikwadrahul8** [comment]
Hi, @jhayush0502 

Apologize for the delayed response and just to confirm, May I know your issue got resolved or still are you looking for help on this issue ? Thank you!
