### ISSUE TITLE
Problem about first inference with tensorflow.js webgpu backend

### ISSUE THREAD

**Issue by jhl13** [tensorflow/tfjs#7768]
When I use a larger model and perform inference with the TensorFlow.js WebGPU backend, the first inference takes a long time and the Chrome UI will be blocked.

Has anyone else experienced a similar issue?

**Comment by gyagp** [comment]
For large models, usually there are many shaders that need to be compiled in series in the first inference, which results in a frozen main thread (UI thread). We have a way to enable parallel shader compile, and here is a sample (https://github.com/tensorflow/tfjs/pull/7755/files#diff-a70aa640d286e39c922aa79fc636e610cae6e3a50dd75b3960d0acbe543c3a49R316): 

// compile only
tf.env().set('WEBGPU_ENGINE_COMPILE_ONLY', true);
const compileRes = predict();
tf.env().set('WEBGPU_ENGINE_COMPILE_ONLY', false);
await tf.backend().checkCompileCompletionAsync();
tf.dispose(compileRes);

// do you first inference

The above code set the env variable 'WEBGPU_ENGINE_COMPILE_ONLY' to true to enable WebGPU parallel compile, which is compile only. Then you may do your inference as usual and you may see a speedup. Please let us know if this doesn't help.

**Comment by jhl13** [comment]
Thank you very mach! I tried this. but got 

"environment.ts:134 Uncaught (in promise) Error: Cannot set flag WEBGPU_ENGINE_COMPILE_ONLY as it has not been registered."

I printed tf.env() using console.log, and found no WEBGPU_ENGINE_COMPILE_ONLY

tfjs version: 4.8.0
tfjs webgpu backend version: 4.8.0

**Comment by jhl13** [comment]
In addition, I use model.predict() asynchronously in the worker thread. this still frozen the ui.

**Comment by jhl13** [comment]
Sorry, I forgot to delete the package-lock.json file. After deleting it, I updated tfjs version and it works！

**Comment by qjia7** [comment]
>But I still want to know why，I use model.predict() asynchronously in the worker thread. this still frozen the ui. (didn't use WebGPU parallel compile)

One possible reason is that the gpu process doesn't care the webgpu commands come from main thread or worker thread. If you don't use parallel compilation (multi-threads to compile), gpu process will execute them sequentially and probably block the gl commands from UI. 

Please let us know whether this issue has been resolved. Thanks!

**Comment by jhl13** [comment]
Thank you very much, the problem has been resolved, I will close the issue.
