### ISSUE TITLE
@tensorflow/tfjs-tflite@0.0.1-alpha.9" has incorrect peer dependency "@tensorflow/tfjs-core@3.20.0

### ISSUE THREAD

**Issue by Yongle-Fu** [tensorflow/tfjs#7789]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version:
- CUDA/cuDNN version:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @Yongle-Fu 

I checked the `package.json` file [here](https://www.npmjs.com/package/@tensorflow/tfjs-tflite/v/0.0.1-alpha.9?activeTab=code) in that it's showing the package dependancy of `@tensorflow/tfjs-core@3.20.0` at the moment. 

May I know are you facing any issues while using the `@tensorflow/tfjs-tflite@0.0.1-alpha.9` and it seems like we need to update `@tensorflow/tfjs-core` with latest version and at the moment I'm not sure whether we have plan to update `@tensorflow/tfjs-core` with latest version for `@tensorflow/tfjs-tflite@0.0.1-alpha.9` so we'll update you soon. thank you for noticing this issue, I really appreciate your efforts and time. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @Yongle-Fu 

May I know are you facing any issue while using `@tensorflow/tfjs-tflite@0.0.1-alpha.9` ? or Are you looking to update this package `@tensorflow/tfjs-tflite@0.0.1-alpha.9` with latest version of `@tensorflow/tfjs-core` ? Thank you!
