### ISSUE TITLE
If I use dataToGPU to prevent data from being downloaded to the CPU, how can I determine when model inference is complete?

### ISSUE THREAD

**Issue by jhl13** [tensorflow/tfjs#7800]
If I use dataToGPU to prevent data from being downloaded to the CPU, how can I determine when model inference is complete?

“.dataToGPU()” is very fast, and I guess that when it returns, the computation should not be finished yet.

**Comment by qjia7** [comment]
Currently, there is no such kind of API to check gpu's status in tfjs. Maybe we can provide one if many users want this.

For webgpu backend, a hacky way is to get device queue by `tf.backend().queue`. And then call `await queue.onSubmittedWorkDone()` to make sure the comptation is finished.

cc @Linchenn

**Comment by jhl13** [comment]
Thank you, this has helped me a lot. But I will be looking forward to tfjs having such an interface.

**Comment by Linchenn** [comment]
For WebGL backend, the `dataToGpu` returns a texture, you could use fenceSync and clientWaitSync, https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/clientWaitSync, to know when the computation is complete.
