### ISSUE TITLE
Webgl backend fails to initialise running on a worker on safari on Mac

### ISSUE THREAD

**Issue by Pensarfeo** [tensorflow/tfjs#7803]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution: Mac OS 13.4.1, safari version (16.5.1)
- Mobile device if the issue happens on mobile device: various devices running on emulator and Mac mini
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below):
I am using the latest version of webgl backend and tfjs-core
		"@tensorflow-models/pose-detection": "^2.1.0",
		"@tensorflow/tfjs-backend-cpu": "^4.6.0",
		"@tensorflow/tfjs-backend-wasm": "^4.6.0",
		"@tensorflow/tfjs-backend-webgl": "^4.8.0",
		"@tensorflow/tfjs-backend-webgpu": "^4.8.0",
		"@tensorflow/tfjs-converter": "^4.6.0",
		"@tensorflow/tfjs-core": "^4.8.0"- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
First of all I am not quite sure this is a but after reading #7436, but the webgl backend does initialise to work when running on a web worker. 

initialisation is done with the following code:
```js
    const backend = 'webgl'
    await setBackend(backend)
```
I get the following error: ```Could not initialize any backends, all backend initializations failed```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @Pensarfeo 

Thank you for bringing this issue to our attention and If I'm not wrong at the moment the only way to do this would be to use `OffscreenCanvas`. However looking at browser compatibility matrix [here](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas#browser_compatibility), it seems like there is partial support refers to only supporting `2D contexts`, not `WebGL `. Please refer this support [link](https://caniuse.com/offscreencanvas) and It appears this is not ready yet in  without enabling flag.

If have I missed something here please let me know ? Thank you!

**Comment by Pensarfeo** [comment]
Hi, @gaikwadrahul8 

Thanks for the clarification! I guess I can only wait until safari 17 comes out then :)

**Comment by ahmed0saber** [comment]
Hello @Pensarfeo , Is there something that says Safari 17 will support WebGL Backend ? also do you know when will this version get released ?
Thanks in advance.

**Comment by Pensarfeo** [comment]
Hi @ahmed0saber, check this link, https://caniuse.com/?search=offscreencanvas, it seems like safari 17 should support webgl backend. No idea when will it be released :)

Ciao

**Comment by ahmed0saber** [comment]
Hi @Pensarfeo , thank you so much
