### ISSUE TITLE
Support Rank > 1 Tensors for tf.spectral.fft

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#781]
Right now we only support Rank-1 Tensors, though TensorFlow supports any rank tensors (only computing the FFT over the inner most dimension).

**Comment by nsthorat** [comment]
@Lewuathe this is fixed for the webgl backend from this PR: https://github.com/tensorflow/tfjs-core/pull/1335

Keeping this open if you have cycles to fix the CPU backend! :)

**Comment by Lewuathe** [comment]
@nsthorat Great. Thanks! But it seems to support only 2-dimensional tensor. Isn't it necessary to support any dimensional tensor? (e.g. inner-most vector of 4-dimensional tensor.)

**Comment by nsthorat** [comment]
The op supports arbitrary rank, collapsing the batch dimensions into a single dimension before calling the kernel (the backend method). You just have to implement the 2D version and higher ranks are taken care of for you.

**Comment by Lewuathe** [comment]
@nsthorat Good to know. Thanks!

**Comment by nsthorat** [comment]
This is fixed.

**Comment by nsthorat** [comment]
Oh oops, sorry, keeping this open for CPU.

**Comment by nsthorat** [comment]
This is fixed, thanks @Lewuathe!
