### ISSUE TITLE
Support tf.spectral.ifft, tf.spectral.rfft and tf.spectral.irfft

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#782]
Currently we only support `tf.spectral.fft()`, we should support `tf.spectral.ifft`, `tf.spectral.rfft` and `tf.spectral.irfft`.

**Comment by nsthorat** [comment]
cc @Lewauthe

**Comment by nsthorat** [comment]
cc @Lewuathe

**Comment by Lewuathe** [comment]
As long as I understand correctly, `rfft` is just a subset of `fft`, while the other two may need separated implementation.

Anyway, I'm going to work on this.

**Comment by nsthorat** [comment]
Awesome @Lewuathe! BTW, we should fix this first (so it works for all the other ops too): https://github.com/tensorflow/tfjs/issues/781

**Comment by Lewuathe** [comment]
That makes sense. I'll take a look.

**Comment by nsthorat** [comment]
I'm going to knock these off since there's a Google team that wants these ops soon :)

**Comment by Lewuathe** [comment]
@nsthorat Are you working on `tf.spectral.rfft` and `tf.spectral.irfft` too?

**Comment by nsthorat** [comment]
@Lewuathe I haven't started yet! If you want to take this, go ahead if you think it will be in the near term future :) Note that this is not exactly the same as `real(fft(x))`.

**Comment by nsthorat** [comment]
This is done.

**Comment by faroit** [comment]
@nsthorat great news. Does this mean I could expect `signal.inverse_stft` to work on tfjs?

**Comment by nsthorat** [comment]
These ops aren't supported yet (just the ones listed on this issue).

I filed a new issue for those ops: https://github.com/tensorflow/tfjs/issues/1362
