### ISSUE TITLE
Need what dependencies for tfjs-react-native to work with expo 47 and rn .70

### ISSUE THREAD

**Issue by eledahl** [tensorflow/tfjs#7853]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone SE

**Describe the problem**
The current documentation only has the dependencies listed for expo 44 and react native .64. These are very outdated and I would like to try to implement this in my app with .70 RN and expo 47. I also might want to upgrade to .71 and 48 if it is possible to understand the dependencies for those as well.

This is current given:

"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",

**Comment by gaikwadrahul8** [comment]
Hi, @eledahl 

Thank you for bringing this issue to our attention and It seems like currently team is working on this issue so we'll update you soon and you can refer this [comment](https://github.com/tensorflow/tfjs/issues/7454#issuecomment-1478743753). Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @eledahl 

It seems like at the moment team is facing some challenges and we're unable to give any timeline or ETA about this issue but once I get the update from concerned team I'll update the same here. Thank you!

**Comment by gaikwadrahul8** [comment]
We're looking for contribution from TFJs community on this because we currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thank you!

**Comment by XcloudFance** [comment]
I also strongly need the upgrade on the supporting version of Expo. Hopefully it would be tackled agily

**Comment by lights9** [comment]
Yes, would be helpful if that is solved urgently ...

**Comment by gaikwadrahul8** [comment]
Hi, @eledahl, @XcloudFance, @lights9

I apologize for the delayed response and it seems like we have updated `tfjs-react-native` dependencies with the help of this PR [#8062](https://github.com/tensorflow/tfjs/pull/8062/files) and that PR got merged so could you please confirm from your end, is it working as expected ?

I would suggest you to check tfjs-sample-expo-app from [here](https://github.com/paradite/tfjs-sample-expo-app?tab=readme-ov-file#tfjs-sample-expo-app) 

If issue still persists please let us know. Thank you for your cooperation and patience.
