### ISSUE TITLE
tfjs-layers tests fail with new MAX_TEXTURE_SIZE environment flag

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#786]
@caisq @dsmilkov @nsthorat 

In https://github.com/tensorflow/tfjs-core/commit/fb395557e3b1e391ce67c920606d8ab3727c16ae we introduced an environment flag `WEBGL_MAX_TEXTURE_SIZE` so it would be easier to simulate small texture sizes for testing. However the environment flags get evaluated with every test in the tfjs-layers suite - so we are continuously querying `MAX_TEXTURE_SIZE`. This somehow causes the WebGL context to be lost at the Cropping2D test (https://github.com/tensorflow/tfjs-layers/blob/master/src/layers/convolutional_test.ts#L919) (WebGL context lost is the true error - Travis has been [reporting](https://travis-ci.org/tensorflow/tfjs-layers/jobs/440342080) otherwise but that's because `webGLDebugErrorCheckingEnabled` is false). Running the test in isolation does not cause the error. I'm not sure why this happens with the same test every time. If I cache `MAX_TEXTURE_SIZE` this no longer occurs. 

I'm not sure what the best solution here is - it would be nice to go back to our old setup without the `MAX_TEXTURE_SIZE` flag, but I can't figure out a good way to stub that value for unit testing. A quick fix would be to cache the value of `MAX_TEXTURE_SIZE` in our environment. What are your thoughts?

**Comment by caisq** [comment]
@annxingyuan Thank you for looking into the root cause of this issue. So this sounds like more of an issue with the tests? Is there a way to avoid continuously querying MAX_TEXTURE_SIZE?

**Comment by annxingyuan** [comment]
@bileschi MAX_TEXTURE_SIZE shouldn't change for users - we only created the flag so we could control it for testing. Just submitted a PR for caching - will try to create another tfjs-core release today!
