### ISSUE TITLE
Improve source map support for all packages, and built UMD bundle

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#787]
unminified / with source maps. Currently if there are exceptions in the lib when using

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.13.1/dist/tf.js"> </script>
```

These are harder to debug than when using 

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@0.13.5/dist/tf-core.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-layers@0.8.1/dist/tf-layers.js"> </script>    
```

(Note that in the above i explicitly load the non minified versions). The latter has sourcemap support and give a nice debugging experience.

**Comment by tafsiri** [comment]
Opening the scope of this to just more broadly improve sourcemap support given some recent issues we've had with debugging.

Leaving a breadcrumb here to pick up the investigation next week. But basically I think we may need to put the ts sources in our npm bundle, or we could re-write the sourcemap urls to the compiled js. However i think the latter is not as ideal as its not as readable as the ts.

I've made a branch in a side repo so that we can discuss it more easily https://github.com/tafsiri/tfjs/tree/sourcemap-experiments/node_modules/%40tensorflow, if you trace the sourcemap urls for the union package they eventually reference the original ts sources which are not actually in the npm package.

cc @dsmilkov just fyi for now.

**Comment by tafsiri** [comment]
Update: https://github.com/tensorflow/tfjs/pull/816 handles the umd bundle, while upgrading parcel fixes the issues we were having when bundling locally.

**Comment by tafsiri** [comment]
https://github.com/tensorflow/tfjs-website/pull/199 updates the default link on the homepage to one that will correctly load the sourcemaps for the umd bundle.

**Comment by tafsiri** [comment]
Fixed for tfjs-examples in https://github.com/tensorflow/tfjs-examples/pull/161

**Comment by tafsiri** [comment]
I've tested sourcemap support for core, layers and converter umd bundles and they are working. The only file i noticed without a sourcemap is https://github.com/tensorflow/tfjs-converter/blob/master/src/data/compiled_api.js (check your node_modules for an installed tfjs to see). Not sure how critical it is and if i remember correctly this is not a file we generate ourselves.

@dsmilkov Going to close this unless you can think of other places to check/things to look at.

**Comment by dsmilkov** [comment]
One last thing: Update the script tag in the README in the main tfjs repo: https://github.com/tensorflow/tfjs/blob/master/README.md

**Comment by dsmilkov** [comment]
Also merge the other PRs:
https://github.com/tensorflow/tfjs-website/pull/199
https://github.com/tensorflow/tfjs/pull/816

**Comment by tafsiri** [comment]
PRs have been merged.
