### ISSUE TITLE
tfjs-node invalid installation/setup no such file or directory

### ISSUE THREAD

**Issue by digimbyte** [tensorflow/tfjs#7881]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (Up to date)
- TensorFlow.js installed from (npm or script link): `npm`
- TensorFlow.js version: 4.9.0

**Describe the problem**
Installation stalls on ENOENT: no such file or directory

Output:
```
npm ERR! code 1
npm ERR! path E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-4.9.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
npm ERR!   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:289
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR! Node.js v20.3.1
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR!     at ChildProcess.emit (node:events:511:28)
npm ERR!     at maybeClose (node:internal/child_process:1098:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
npm ERR!   code: 1,
npm ERR!   killed: false,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
npm ERR! }
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`npm install @tensorflow/tfjs-node@latest`

**Any other info / logs**
Seems that its unable to extract/setup the file and dll in its intended structure, following the folder behavior, I noticed `./lib/napi-v8` being created rather than `./lib/napi-v9` and the dll files were not present in a visible manor.
output log: [Paste Bin](https://pastebin.com/P9WQGX27)

**Comment by gaikwadrahul8** [comment]
Hi, @digimbyte 

Thank you for bringing this issue to our attention and Please refer this similar issue https://github.com/tensorflow/tfjs/issues/7341 and this [comment](https://github.com/tensorflow/tfjs/issues/7341#issuecomment-1467971006), at the moment we don't have pre-built-binary for windows machine for latest version and last supported version is `pre-built-binary/napi-v8/3.18.0/CPU-windows-3.18.0.zip` please refer this [link](https://storage.googleapis.com/tf-builds/) 

At the moment workaround is to use older version `3.18 ` so please use below command, so I would request you to please try below command and see Is it working as expected or not ? 

If issue still persists with `@tensorflow/tfjs-node@3.18.0`, please let us know. Thank you!

`npm install --save-exact @tensorflow/tfjs-node@3.18.0`

**Comment by digimbyte** [comment]
I'm not a big brain when it comes to this stuff, for now I'll use the workaround. hopefully that gets fixed, even though my server is running Debian, working on Windows is just easier. perhaps some sort of catch can be implemented where those files are requested via user prompt or a secondary step.

**Comment by digimbyte** [comment]
unfortunately, it still failed with 3.18.0
```
397 timing reifyNode:node_modules/@tensorflow/tfjs-core/node_modules/seedrandom Completed in 893ms
398 timing reifyNode:node_modules/@tensorflow/tfjs-backend-webgl/node_modules/seedrandom Completed in 894ms
399 timing reifyNode:node_modules/@tensorflow/tfjs-backend-cpu/node_modules/seedrandom Completed in 893ms
400 timing reifyNode:node_modules/@tensorflow/tfjs/node_modules/yargs Completed in 913ms
401 timing reifyNode:node_modules/@tensorflow/tfjs-data Completed in 1001ms
402 timing reifyNode:node_modules/@tensorflow/tfjs-converter Completed in 1323ms
403 timing reifyNode:node_modules/@tensorflow/tfjs-backend-cpu Completed in 1499ms
404 timing reifyNode:node_modules/@tensorflow/tfjs-node Completed in 1544ms
405 timing reifyNode:node_modules/@tensorflow/tfjs-layers Completed in 1568ms
406 timing reifyNode:node_modules/@tensorflow/tfjs-backend-webgl Completed in 1720ms
407 timing reifyNode:node_modules/@tensorflow/tfjs Completed in 1997ms
408 timing reifyNode:node_modules/@tensorflow/tfjs-core Completed in 2575ms
409 timing reifyNode:node_modules/core-js Completed in 3239ms
410 timing reify:unpack Completed in 3242ms
411 timing reify:unretire Completed in 0ms
412 timing build:queue Completed in 2ms
413 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/mkdirp Completed in 7ms
414 timing build:link:node_modules/@mapbox/node-pre-gyp Completed in 8ms
415 timing build:link:node_modules/detect-libc Completed in 7ms
416 timing build:link:node_modules/@tensorflow/tfjs Completed in 7ms
417 timing build:link:node_modules/@tensorflow/tfjs-node/node_modules/rimraf Completed in 7ms
418 timing build:link:node_modules/nopt Completed in 7ms
419 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/rimraf Completed in 7ms
420 timing build:link Completed in 8ms
421 info run @tensorflow/tfjs-node@3.18.0 install node_modules/@tensorflow/tfjs-node node scripts/install.js
422 info run @tensorflow/tfjs-node@3.18.0 install { code: 1, signal: null }
423 warn cleanup Failed to remove some directories [
423 warn cleanup   [
423 warn cleanup     'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node',
423 warn cleanup     [Error: EPERM: operation not permitted, rmdir 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\deps\include\tensorflow'] {
423 warn cleanup       errno: -4048,
423 warn cleanup       code: 'EPERM',
423 warn cleanup       syscall: 'rmdir',
423 warn cleanup       path: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\deps\\include\\tensorflow'
423 warn cleanup     }
423 warn cleanup   ]
423 warn cleanup ]
424 timing reify:rollback:createSparse Completed in 456ms
425 timing reify:rollback:retireShallow Completed in 2ms
426 timing command:install Completed in 27351ms
427 verbose stack Error: command failed
427 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
427 verbose stack     at ChildProcess.emit (node:events:511:28)
427 verbose stack     at maybeClose (node:internal/child_process:1098:16)
427 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
428 verbose pkgid @tensorflow/tfjs-node@3.18.0
429 verbose cwd E:\Projects\backend-server
430 verbose Windows_NT 10.0.19045
431 verbose node v20.3.1
432 verbose npm  v9.6.7
433 error code 1
434 error path E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node
435 error command failed
436 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
437 error CPU-windows-3.18.0.zip
437 error https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.7.0.zip
438 error * Downloading libtensorflow
438 error
438 error * Building TensorFlow Node.js bindings
438 error symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
438 error   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
438 error node:internal/process/promises:289
438 error             triggerUncaughtException(err, true /* fromPromise */);
438 error             ^
438 error
438 error [Error: ENOENT: no such file or directory, copyfile 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
438 error   errno: -4058,
438 error   code: 'ENOENT',
438 error   syscall: 'copyfile',
438 error   path: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
438 error   dest: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
438 error }
438 error
438 error Node.js v20.3.1
438 error
438 error     at ChildProcess.exithandler (node:child_process:419:12)
438 error     at ChildProcess.emit (node:events:511:28)
438 error     at maybeClose (node:internal/child_process:1098:16)
438 error     at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
438 error   code: 1,
438 error   killed: false,
438 error   signal: null,
438 error   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
438 error }
439 verbose exit 1
440 timing npm Completed in 27675ms
441 verbose unfinished npm timer reify 1690786503855
442 verbose unfinished npm timer reify:build 1690786517075
443 verbose unfinished npm timer build 1690786517075
444 verbose unfinished npm timer build:deps 1690786517076
445 verbose unfinished npm timer build:run:install 1690786517086
446 verbose unfinished npm timer build:run:install:node_modules/@tensorflow/tfjs-node 1690786517086
447 verbose code 1
```

**Comment by gaikwadrahul8** [comment]
Hi, @digimbyte 

I see currently you're using the `Node.js v20.3.1` so could you please go with LTS node version for `Windows Installer node-v18.17.0-x64.msi` option ? 

Please refer this [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) for TensorFlow.js Node.js bindings Windows troubleshooting and `node-gyp - Node.js native addon build tool` instructions from [here](https://github.com/nodejs/node-gyp#:~:text=Developer%20Tools....-,On%20Windows,-Install%20the%20current) for `Windows` machine

`node-gyp` requires that you have installed a compatible version of Python, one of: `v3.7`, `v3.8`, `v3.9`, or `v3.10`.

Could you please try above instructions and let us know, Is it resolving your issue or not ? If now please share error log after following above instructions ? Thank you!

**Comment by digimbyte** [comment]
incrementally I rolled back the versions with the following:
```
E:\Projects\backend-server> python --version
Python 3.10.9
```
using `nvm` I rolled back to v18
```
E:\Projects\backend-server> node -v
v18.17.0
```
running command: `E:\Projects\backend-server> npm install --save-exact @tensorflow/tfjs-node@3.18.0`
```
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.18.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.7.0.zip
npm ERR! * Downloading libtensorflow
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
npm ERR!   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:288
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'E:\Projects\backend-server\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'E:\\Projects\\backend-server\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.0
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR!     at ChildProcess.emit (node:events:514:28)
npm ERR!     at maybeClose (node:internal/child_process:1091:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm ERR!   code: 1,
npm ERR!   killed: false,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
npm ERR! }
```

seems its failing on creation of the symbolic link to napi-v9, is it supposed to be v8? as earlier I saw that folder being generated

**Comment by digimbyte** [comment]
I did some version testing, earliest version I can install is 3.1.0 but 3.2.0 yields the same error:
```
npm ERR! code 1
npm ERR! path E:\Projects\TensorFlow\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.2.0.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
npm ERR!   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:288
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'E:\Projects\TensorFlow\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'E:\Projects\TensorFlow\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'E:\\Projects\\TensorFlow\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'E:\\Projects\\TensorFlow\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.0
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR!     at ChildProcess.emit (node:events:514:28)
npm ERR!     at maybeClose (node:internal/child_process:1091:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm ERR!   code: 1,
npm ERR!   killed: false,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
npm ERR! }
```

**Comment by digimbyte** [comment]
Python: 
`3.10.9`
node-gyp:
`9.4.0`
Node:
`18.17.0`
npm:
`9.6.7`
Windows 10:
`10.0.19045 Build 19045`

simple (empty) project, run npm command:
`npm install --save-exact @tensorflow/tfjs-node@3.1.0`

**Comment by gaikwadrahul8** [comment]
Hi, @digimbyte 

Thank you for helping us with above detailed details and will dig more into this issue. It's good to hear that it's working with `@tensorflow/tfjs-node@3.1.0`, if your issue got resolved please feel free to close this issue and for future update you can follow this issue https://github.com/tensorflow/tfjs/issues/7341 where we'll update once we got the new update from our concerned team with latest version of `@tensorflow/tfjs-node` for `Windows` machine. Thank you!

**Comment by laurens-vrh** [comment]
I have a similar problem. After downgrading to nodejs version 18.17.0 and using `npm install --save-exact @tensorflow/tfjs-node@3.1.0`, I was able to get it installed. However, when I run my project, I instantly get this error:
```
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\Documents\Programmeren\Projecten\tfjs-latijn\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\Programmeren\Projecten\tfjs-latijn\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I have no idea what this means. I tried rebuiling the package locally with `npm rebuild @tensorflow/tfjs-node --build-from-source`, which succeeded, but I still got the same error. Is there a solution to this?

**Comment by seongho-98** [comment]
I had been struggling with the same error, and I managed to resolve it. My system configuration is as follows:

Windows: 11
Node.js: 18.17.0
npm: 9.6.7
Python: 2.7

Here's what I did to fix the issue:

Installed node-gyp globally:
- npm install -g node-gyp

Installed a specific version of @tensorflow/tfjs-node to avoid compatibility issues:
- npm install --save-exact @tensorflow/tfjs-node@3.1.0
By following these steps, I was able to successfully overcome the error. This might help others who are facing similar issues.

**Comment by gaikwadrahul8** [comment]
Hi, @JijaProGamer 

Apologize for the delayed response, could you please try below workaround, let us know is it resolving your issue or not ?

Please refer this [comment](https://github.com/tensorflow/tfjs/issues/4116#issuecomment-719940801) where user was facing the similar issue and below solution worked so I would request you to please give it try from your end once.

`D:\TFJS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll `to `D:\TFJS\node_modules\@tensorflow\tfjs-node\lib\napi-v7\`

If issue still persists please let us know with error log, we'll try to investigate this issue further? Thank you!

**Comment by JijaProGamer** [comment]
> Hi, @JijaProGamer
> 
> Apologize for the delayed response, could you please try below workaround, let us know is it resolving your issue or not ?
> 
> Please refer this [comment](https://github.com/tensorflow/tfjs/issues/4116#issuecomment-719940801) where user was facing the similar issue and below solution worked so I would request you to please give it try from your end once.
> 
> `D:\TFJS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll `to `D:\TFJS\node_modules\@tensorflow\tfjs-node\lib\napi-v7\`
> 
> If issue still persists please let us know with error log, we'll try to investigate this issue further? Thank you!

Tried it, but still doesnt work. I read that tfjs-node required AVX processors, so that might be the problem.

**Comment by digimbyte** [comment]
> 
to clarify:
while it did install, copying; 
`node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll`
 to 
 `node_modules\@tensorflow\tfjs-node\lib\napi-v7\`
 is essential until a real version is supplied
 
 at the moment, I am using a script that copies the dll file on build/run so it is available in my docker image.

**Comment by gaikwadrahul8** [comment]
Hi, @JijaProGamer 

Apologize for the delayed response and Yes, `tfjs-node `requires AVX processors and tfjs-node library uses AVX instructions to improve the performance of its operations. If your CPU does not support AVX, you will not be able to use tfjs-node if I'm not wrong. Thank you!

**Comment by digimbyte** [comment]
> 

try the python version? otherwise don't hijack - you wouldn't like it if I stole your mother, don't steal this thread.

**Comment by Skeli789** [comment]
Something I found to work was renaming the `node_modules/@tensorflow/tfjs-node/lib/napi-v8` mid-installation to `napi-v9`. The `tensorflow.dll` is then copied correctly and node will work correctly once you sync the files between the `napi-v8` and `napi-v9` directories.

**Comment by saknarak** [comment]
I want to share my success installation with
- `node` == 20.11
- `@tensorflow/tfjs-node-gpu` == 4.16.0

1. `npm i  @tensorflow/tfjs-node`
2. during installing, open another console and run this script to rename `napi-v8` to `napi-v9` folder

```sh
node rename.js
```
 - `rename.js`
```js
import fs from 'fs'
// const fs = require('fs')
while (true) {
  try {
    // change tfjs-node-gpu to tfjs-node
    fs.renameSync('./node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v8', './node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v9')
    break
  } catch (e) {

  }
}
console.log('done')
```

3. after install success, make sure to move all files in `napi-v9` to `napi-v8`
`node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v8` should have both `tensorflow.dll` and `tfjs_binding.node` files

PS: Installation failed because of no target folder `napi-v9`, but create with `mkdir -p node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v9` before `npn install` is doesn't work, so I have to create during installation instead.

**Comment by hludens** [comment]
I have a similar problem



Node.js v20.11.1
npm 10.2.4
@tensorflow/tfjs-node@4.17.0 

when running the script it gives an error

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: D:\develop\nnet\node_serv\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node.

the rebuild is successful, but the error does not disappear
npm rebuild @tensorflow/tfjs-node --build-addon-from-source
rebuilt dependencies successfully

node_modules\@tensorflow\tfjs-node\lib\napi-v7 
folder is empty

Perhaps someone can tell me what to do?
