### ISSUE TITLE
npm @tensorflow/tfjs-tflite  Can't resolve './tflite_web_api_client'

### ISSUE THREAD

**Issue by Jwy-jump** [tensorflow/tfjs#7893]
when I npm install '@tensorflow/tfjs-tflite'
import * as tflite from '@tensorflow/tfjs-tflite';

npm run build:
ERROR in ./node_modules/@tensorflow/tfjs-tflite/dist/tflite_model.js 18:0-62
Module not found: Error: Can't resolve './tflite_web_api_client' in 'detector/node_modules/@tensorflow/tfjs-tflite/dist'
 @ ./node_modules/@tensorflow/tfjs-tflite/dist/index.js 17:0-31 17:0-31
 @ ./index.ts 54:0-50 67:41-63

**Comment by gaikwadrahul8** [comment]
Hi, @Jwy-jump 

Thank you for bringing this issue to our attention and Could you please try this version `@tensorflow/tfjs-tflite@0.0.1-alpha.9 ` with the help of this command `npm i @tensorflow/tfjs-tflite@0.0.1-alpha.9`, Please let us know whether is it resolving your  issue or not ? 

If issue still persists please let us know with error log to dig more into your issue. Thank you!

**Comment by acoffin-socure** [comment]
Hi @gaikwadrahul8, is there a timeline on when this will be fixed?

**Comment by gfeller** [comment]
Workaround:

Use CDN:
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>    
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite/dist/tf-tflite.min.js"></script>

```
For TypeScript:
1. Define Typings:  ai.d.ts
```
export {};

import type * as tfLiteTypes from "@tensorflow/tfjs-tflite/dist/index"
type tfLiteType = typeof tfLiteTypes

declare global {
    interface Window { tflite: tfLiteType; }
}
```
 
2. Use It
` await window.tflite.loadTFLiteModel(`assets/models/${model}`)`

**Comment by GXDEVGG** [comment]
> Workaround:
> 
> Use CDN:
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>    
> <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu"></script>
> <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite/dist/tf-tflite.min.js"></script>
> ```
> 
> For TypeScript:
> 
>     1. Define Typings:  ai.d.ts
> 
> 
> ```
> export {};
> 
> import type * as tfLiteTypes from "@tensorflow/tfjs-tflite/dist/index"
> type tfLiteType = typeof tfLiteTypes
> 
> declare global {
>     interface Window { tflite: tfLiteType; }
> }
> ```
> 
>     2. Use It
>        ` await window.tflite.loadTFLiteModel(`assets/models/${model}`)`

could you help me I have the project in react.js using next.js v14 but I don't know where to implement Define Typings: ai.d.ts in next.js v14

**Comment by kirill-konshin** [comment]
`@tensorflow/tfjs-tflite@0.0.1-alpha.8` had this file...
