### ISSUE TITLE
 node-gyp failed to rebuild 

### ISSUE THREAD

**Issue by eddev89** [tensorflow/tfjs#7895]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 (22H2 OS BUILD 22621.1992)
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version:     "@tensorflow/tfjs-node": "3.1.0",

LOGS:
✔ Checking your system
✔ Locating application
✔ Loading configuration
✖ Preparing native dependencies: 0 / 1
  › node-gyp failed to rebuild 'C:\Users\EduardoLGamer\customers\Logasa\projects\logasa-system\node_modules\@tensorflow\tfjs-node'
◼ Running generateAssets hook

› Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: …  
  Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
      at C…

An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild 'C:\Users\EduardoLGamer\customers\Logasa\projects\logasa-system\node_modules\@tensorflow\tfjs-node'
at ChildProcess.<anonymous> (C:\Users\EduardoLGamer\customers\Logasa\projects\logasa-system\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:118:24)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
error Command failed with exit code 1.

**Comment by gaikwadrahul8** [comment]
Hi, @eddev89 

Thank you for bringing this issue to our attention and I hope you're following this [official documentation ](https://github.com/nodejs/node-gyp#on-windows)for `Windows` machine and could you please try to install `node-gyp` globally by using this command `npm install -g node-gyp`

Please try to install this version of `@tensorflow/tfjs-node@3.1.0` by using this command `npm install --save-exact @tensorflow/tfjs-node@3.1.0`

You can refer similar issue https://github.com/tensorflow/tfjs/issues/7881 for `Windows` machine which may help you to solve your issue 

If issue still persists please let us know with below version information to dig more into your issue. Thank you!

```
Node.js: 
npm: 
Python: 
node-gyp:
```

**Comment by eddev89** [comment]
"After executing that command, another error appeared. This happened because I had multiple versions of Visual Studio installed. However, after deleting the 'msbuild_path', it worked correctly.

Thank you.
I had been dealing with this error for 4 days.

**Comment by eddev89** [comment]
@gaikwadrahul8 
I have another issue: when I start the Electron app, it shows that it can't find the "os-tmpdir" module, which is a dependency of @tensorflow/tfjs-nod

**Comment by gaikwadrahul8** [comment]
Hi, @eddev89 

Good to hear that your first issue got resolved so did you try to install that missing module with the help of npm install command and May I know which electron version are you using ? 

If possible could you please help us with your code example or Github repo link so I'll try to replicate the same issue from my end ? Thank you!

**Comment by eddev89** [comment]
Hi, finally I changed from "electron-forge" to "electron-builder".
Forge gave me too many problems, and with builder it was faster
