### ISSUE TITLE
Suggestions for improving the documentation on how to write custom ops

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#791]
It is great there is documentation on how to write custom ops. 
 https://js.tensorflow.org/tutorials/custom-webgl-op.html#stdlib

Some things would make it easier to follow:
* There should be typescript types in the sample code, or an option to see what the types are.  I'd like to know for example when reading the examples, `const squareAndAddBackpropKernel = inputShape => ({` what type `inputShape` is. 
* There should be examples on how to pass tensors as arguments to the shaders.

**Comment by bileschi** [comment]
Hi @oveddan ,  These are great suggestions!  If this is something you would be interested in contributing submissions are welcome at tensorflow/tfjs-website

The  file for this tutorial is https://github.com/tensorflow/tfjs-website/blob/master/source/tutorials/custom-webgl-op.md

I expect the maintainers would like to keep instructions for both raw JS as well as TypeScript, as many developers work directly in the raw JS.

**Comment by nsthorat** [comment]
Definitely agree about point #2, want to send a PR?

Regarding the type for inputShape, maybe it can just be a comment (since we want this to be for JS folks, as Stan mentions).

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nsthorat** [comment]
Reopening this since it would still be a good idea.
