### ISSUE TITLE
What webview version in android can support webgpu backend?

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tfjs#7910]
What webview version in android can support webgpu backend?The webview version  in my  phone is 96, it seems not support webgpu, I don‘t know if  webgpu  can be used in android ?

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

Thank you for bringing this issue to our attention and You can check if Android System WebView supports WebGPU by using the following steps:

1. Open the Chrome browser on your Android device.
2. Go to the following URL:
`chrome://flags/`
3. Search for the "WebGPU" flag.

If the `WebGPU` flag is not enabled, then Android System WebView does not support `WebGPU`. If the `WebGPU` flag is enabled, then Android System WebView supports `WebGPU`.

At the moment I'm not sure the exact which version of Android System WebView supports `WebGPU` but you can check with the help of above steps and I checked in my one plus mobile device in that I have `115.0.5790.138` ASW version and I'm able to enable `WebGPU`

Please refer this article which may help you to update [Android System WebView ](https://geekflare.com/android-system-webview/)

If have I missed something here, please let me know ? Thank you!

**Comment by libofei2004** [comment]
@gaikwadrahul8 Thank you, But Chrome has many different versions,  is Chrome  version the same as WebView version ?If I install Chrome 78, it has no  "WebGPU" flag, if I install Chrome 116, it has "WebGPU" flag, however the WebView version is still 96.

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

Apologize for the delayed response and as far I know, `WebView` is based on the Chromium open source project and the `Google Chrome version` and the `WebView` version are not always the same and `WebView` may be using an older version of Chromium than Chrome. This is because WebView needs to be stable and reliable, so it is not updated as frequently as Google Chrome.

I hope this help to resolve your issue and if I have missed something here please let me know. Thank you!

**Comment by libofei2004** [comment]
@gaikwadrahul8  thank you! but how can I know  what webview version can support webgpu ?

**Comment by gyagp** [comment]
The official support of WebGPU on Android Chrome would be available in M121 (https://groups.google.com/a/chromium.org/g/blink-dev/c/YFWuDlCKTP4/m/V8gQmGWTBQAJ?pli=1), which will be released on Jan 23 next year. As WebView is built based on Chrome code base, we may expect its readiness then.
