### ISSUE TITLE
Post-training integer quantization with int16 activations

### ISSUE THREAD

**Issue by dubrovin-sudo** [tensorflow/tfjs#7918]
Dear gentlemen,

I dont understand how to do post-training integer quantization with int16 activations in tfjs-conveter:

For example, i post-training integer quantization I did like this:
```
!tensorflowjs_converter \
            --input_format=tf_saved_model \
            --output_format=tfjs_graph_model \
            --signature_name=serving_default \
            --saved_model_tags=serve \
            --quantize_uint8=* \
            /content/gdrive/MyDrive/Unet/{str(model_path)} \
            /content/gdrive/MyDrive/Unet/{str(model_path)}/web_uint8
```
How can I convert activations to 16-bit integer values and weights to 8-bit integer values during model conversion from TensorFlow to TFJS format?

**Comment by gaikwadrahul8** [comment]
Hi, @dubrovin-sudo 

Thank you for bringing this issue to our attention and at the moment I'm not sure whether Tensorflow.js support converting activations to `16-bit integer` values and weights to `8-bit integer` values during model conversion from TensorFlow to TensorFlow.js like `TensorFlow Lite` please refer this Post-training integer quantization with int16 activations [official documentation](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8#:~:text=Download%20notebook-,Overview,the%20post%2Dtraining%20quantization%20include%3A)

Meanwhile you can refer [official documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) for `tfjs-converter `, I'll check with our concerned team and will update you soon. Thank you!

**Comment by pyu10055** [comment]
Our converter only supports quantization annotation based on the node name, node type support is not available.
Basically this means, you have to specify the node names (could be in regex) that needs to be in 16 or 8 bit integer, you cannot use the node op type (relu, conv2d, etc).
