### ISSUE TITLE
Proposed Contribution: Leafscan Project

### ISSUE THREAD

**Issue by Hassan-Shoayb** [tensorflow/tfjs#7921]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 4.10.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I'd like to propose the addition of the "Leafscan" project to the TensorFlow.js examples repository. "Leafscan" is a machine learning application designed for disease identification in tomato leaves using transfer learning techniques. It allows users to upload tomato leaf images and receive predictions about the presence of diseases, showcasing the capabilities of TensorFlow.js.

**Will this change the current api? How?**
The addition of the "Leafscan" project does not alter the existing TensorFlow.js API. Instead, it extends the collection of examples available to the community, demonstrating how to apply machine learning and transfer learning concepts within a web browser using TensorFlow.js.

**Who will benefit with this feature?**
This feature will benefit a wide range of individuals, including:
Aspiring data scientists and machine learning practitioners looking to learn about browser-based machine learning.
Educators seeking practical examples to teach TensorFlow.js concepts to students.
Researchers interested in plant disease identification and its application through deep learning models.
Developers interested in exploring the integration of machine learning models into web applications.

**Any Other info.**
The project repository can be found here: https://github.com/Hassan-Shoayb/leafscan

I'm excited about the opportunity to contribute this project to the TensorFlow.js examples repository and would be willing to collaborate to ensure it aligns with the repository's goals.

**Comment by gaikwadrahul8** [comment]
Hi, @Hassan-Shoayb 

Thank you for showing your interest to contribute in TensorFlow.js examples repository, I really appreciate your efforts and valuable time for this work, meanwhile please refer this official documentation for [How to Contribute](https://github.com/tensorflow/tfjs-examples/blob/master/CONTRIBUTING.md) and Running Presubmit Tests [here](https://github.com/tensorflow/tfjs-examples/blob/master/README.md#contributing). Thank you!
