### ISSUE TITLE
npm start  

### ISSUE THREAD

**Issue by kaopod99999** [tensorflow/tfjs#7922]
jowpodsocute@MacBook-Air-khxng-phuwit education % npm start            
Debugger attached.

> paper-dashboard-2@2.0.1 start
> node main.js

Debugger attached.
Waiting for the debugger to disconnect...
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/education/main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.5.1
Waiting for the debugger to disconnect...

**Comment by gaikwadrahul8** [comment]
Hi, @kaopod99999 

Thank you for bringing this issue to our attention, could you please help us with the exact steps to replicate the same issue from our end ?

If you're using `Node.js` project that has been configured for debugging please help us with Github repo if possible to replicate same error from our end

May I know are you using debugger to the `Node.js` project using `Chrome DevTools` or using `Visual Studio Code` ? Thank you!
