### ISSUE TITLE
running outside browser (google app script, "Error: Could not find a global object")

### ISSUE THREAD

**Issue by rpgit12** [tensorflow/tfjs#7938]
I'm trying to run v3.7.0 in google app scripts, of course the lack of global object makes that a problem. Any hints on existing use/options I may have to get this to run?

Thank you!!

**Comment by gaikwadrahul8** [comment]
Hi, @rpgit12 

Thank you for bringing this issue to our attention, could you please help me with the steps and re-producible code to replicate the same issue from my end ? Thank you!

**Comment by rpgit12** [comment]
Thank you @gaikwadrahul8 - I found that adding this line fixed the issue.

  let global = globalThis;

That being said - I found that running TFJS in google app scripts is less than ideal, so I'm moving on to colab instead. Thank you for your help! (The purpose is similar to Simple ML for Sheets, that is to run models/predictions against spreadsheet data.)
