### ISSUE TITLE
Browser crashes after loading Keras model with LSTM layers

### ISSUE THREAD

**Issue by jscriptcoder** [tensorflow/tfjs#794]
Hi there,

A month ago or so I reported an issue, https://github.com/tensorflow/tfjs/issues/738, which turned out to be a duplicate of https://github.com/tensorflow/tfjs/issues/218. Layer Dot seems to have been added to tfjs-layer in version 0.8.2, which is excellent news. Good job guys. This finally loads my model, but after a few seconds the browsers crashes. I get this warning on the console log: "_Orthogonal initializer is being called on a matrix with more than 2000 (4096) elements: Slowness may result._"

I'm using **TensorFlow.js 0.13.2**, in **Chrome 68**. The keras model trained can be found here: https://github.com/jscriptcoder/date-translator/tree/master/jupyter, ```dates_model.h5``` file, and the converted model is here: https://github.com/jscriptcoder/date-translator/tree/master/tfjsmodel. The Jupyter notebook with the training is here: https://bit.ly/2Oc14Ce.

I'm using **Tensorflow 1.10.0** as backend and **Keras 2.2.2**. To convert the model I used **Tensorflowjs 0.6.0**.

Thasnks a lot,
Fran

**Comment by caisq** [comment]
@jscriptcoder Thanks for reporting this issue. I am able to reproduce issue, in both the browser and node.js (tfjs-node). We'll look into this bug.
