### ISSUE TITLE
tensorflow-core Tensor instance methods unavailable ?

### ISSUE THREAD

**Issue by santimirandarp** [tensorflow/tfjs#7941]
After installing @tensorflow/tfjs-core (https://www.npmjs.com/package/@tensorflow/tfjs-core) which could replace tfjs in our use case, a few errors popped out.
 
Most functions i.e `.squeeze()`, `.gather()` can be called as `tf.squeeze(x)` and  not (anymore) from the tensor instance like `x.squeeze()`

Is this just a Typescript problem or are these methods not in the class but only in the namespace imported ? This would make the code a lot more verbose / less readable.

**Comment by gaikwadrahul8** [comment]
Hi, @santimirandarp 

Thank you for bringing this issue to our attention, yes, you are correct and with latest `Tensorflow.js` versions, the methods like `.squeeze()` and `.gather()` are not members of the tensor instance anymore as far I know. They are now in the global namespace, and can be called as `tf.squeeze(x)` and `tf.gather(x)`.

If I'm not wrong the reason for this change is to make the API more consistent with TensorFlow for other platforms,I agree that this makes the code more verbose and less readable. However, you can use the `import * as tf from '@tensorflow/tfjs-core'` syntax to import all of the` TensorFlow.js `functions into the `tf` namespace.

If Am I missing something here please let me know ? Thank you!
