### ISSUE TITLE
Suggestion for GALLERY.md

### ISSUE THREAD

**Issue by NormanTUD** [tensorflow/tfjs#7943]
For the last about 2 years I was working on a project called asanAI, which is basically a GUI for TensorFlow.js sequential models that allows you to create custom models, and train them on your own machine, on default data or your own data, images or CSV. It is freely available under and values your privacy (nothing of your training data it sent to our servers):

https://asanai.scads.ai/

![Screenshot 2023-09-05 at 20-06-11 asanAI](https://github.com/tensorflow/tfjs/assets/34073778/032d3562-8f2c-4a4a-bc02-430f99ebda6c)

I developed it for teaching, but it also assists in creating small neural networks on small data sets, and it can export to Python, so you can then use them locally.

It's a very complex one-man-project, so it may be buggy at times. But for our university, it has turned out a valuable teaching and playground-like tool for testing real AI models.

Maybe this, if you agree that this is kinda cool to achieve with TFJS, could be added to the list 😊

**Comment by gaikwadrahul8** [comment]
Hi, @NormanTUD 

Apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs/pull/7948 got merged so have we taken care of this issue , if yes please feel free to close this issue or I have missed something here. Thank you!
