### ISSUE TITLE
Error on win10 after installing @tensorflow/tfjs-node 

### ISSUE THREAD

**Issue by liokaiser** [tensorflow/tfjs#7945]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 Professionnel  (2.10 GHz 8.00Go)
- TensorFlow.js installed from: npm i @tensorflow/tfjs-node
- TensorFlow.js version: 4.10
- NodeJS v15.14.0

**Describe the problem**
after installing npm, with a script containing only the instantiation of tensorFlow, this error message appears: 
node:internal/modules/cjs/loader:1151
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Une routine d'initialisation d'une bibliothèque de liens dynamiques (DLL) a échoué.

\\?\c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\dist\index.js:72:16)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'ERR_DLOPEN_FAILED'
}

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I updated nodeJS from version 14 to 15 with nvm.
I then wanted to install tensorflow but after installation the error message appeared.
I uninstalled and reinstalled several times, but the problem persists.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gaikwadrahul8** [comment]
Hi, @liokaiser 

Thank you for bringing this issue to our attention and could you please try below commands to install `tfjs-node `on your `Windows` system and I believe you're following this [official documentation](https://github.com/nodejs/node-gyp#on-windows) for `node-gyp - Node.js native addon build tool` after following official documentation please follow steps :

1. `npm install -g node-gyp`
2. `npm install --save-exact @tensorflow/tfjs-node@3.1.0
`


If you're getting above error message which you mentioned in the issue template then please move `\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll` To `\node_modules\@tensorflow\tfjs-node\lib\napi-v8\`

Please try above workaround let us know, Is it working as expected or not ? If not, please help us with error log to investigate this issue further. Thank you!

**Comment by liokaiser** [comment]
thank you gaikwadrahul8, 

for your advice but unfortunately I get the same error message when instantiating tensorflow
`const tf = require('@tensorflow/tfjs-node')`
I updated Node JS to version 18, but without success.
There must be a problem accessing `tensorflow.dll` but I don't see how to solve it
here is the current error message:
```
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Une routine d'initialisation d'une bibliothèque de liens dynamiques (DLL) a échoué.

\\?\c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.17.1
```

**Comment by liokaiser** [comment]
from the console :
```
C:\WF\RESSOURCES\SCRIPTS>npm install @tensorflow/tfjs-node
npm ERR! code 1
npm ERR! path C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-4.10.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings
npm ERR! symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
npm ERR!   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
npm ERR! node:internal/process/promises:288
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, copyfile 'C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'copyfile',
npm ERR!   path: 'C:\\WF\\RESSOURCES\\SCRIPTS\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
npm ERR!   dest: 'C:\\WF\\RESSOURCES\\SCRIPTS\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.1
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR!     at ChildProcess.emit (node:events:514:28)
npm ERR!     at maybeClose (node:internal/child_process:1091:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm ERR!   code: 1,
npm ERR!   killed: false,
npm ERR!   signal: null,
npm ERR!   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
npm ERR! }

npm ERR! A complete log of this run can be found in: C:\Users\xxxxxx\AppData\Local\npm-cache\_logs\2023-09-06T19_12_01_763Z-debug-0.log
```

**Comment by gaikwadrahul8** [comment]
> thank you gaikwadrahul8,
> 
> for your advice but unfortunately I get the same error message when instantiating tensorflow `const tf = require('@tensorflow/tfjs-node')` I updated Node JS to version 18, but without success. There must be a problem accessing `tensorflow.dll` but I don't see how to solve it here is the current error message:
> 
> ```
> node:internal/modules/cjs/loader:1340
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: Une routine d'initialisation d'une bibliothèque de liens dynamiques (DLL) a échoué.
> 
> \\?\c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
>     at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
>     at require (node:internal/modules/cjs/helpers:121:18)
>     at Object.<anonymous> (c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12) {
>   code: 'ERR_DLOPEN_FAILED'
> }
> 
> Node.js v18.17.1
> ```

Hi, @liokaiser 

May I know did you try to move` \node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll` To `\node_modules\@tensorflow\tfjs-node\lib\napi-v7\` manually, if not please try it once and let us know, Is it working as expected or not ? Thank you!

Please try to install `@tensorflow/tfjs-node@3.1.0 `version 

1.` npm install -g node-gyp`
2. `npm install --save-exact @tensorflow/tfjs-node@3.1.0 
`

**Comment by liokaiser** [comment]
Hi @gaikwadrahul8,

yes I tried, after installing node-gyp et tensoflow@3.10, by copying
`C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll`
to
`C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v7`

but unfortunately I get the same error message when instantiating tensorflow `const tf = require('@tensorflow/tfjs-node')`

```
Debugger attached.
Waiting for the debugger to disconnect...
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Une routine dinitialisation dune bibliothèque de liens dynamiques (DLL) a échoué.

\\?\c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (c:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.17.1
```
Tank you for the help

**Comment by gaikwadrahul8** [comment]
Hi, @liokaiser 

Could you please run below command and help me with complete error log output after running this command `node-gyp configure` to investigate your issue further ? Thank you for your patience and understanding

Please follow below steps :
1. `npm install -g node-gyp` (Install `node-gyp` globally by using this command)
2. `node-gyp configure`

**Comment by liokaiser** [comment]
Hi @gaikwadrahul8 ,

I just did the 2 commands in the terminal.
This is the error message I receive:
```
PS C:\WF\RESSOURCES\SCRIPTS> npm install -g node-gyp

changed 129 packages in 33s
PS C:\WF\RESSOURCES\SCRIPTS> node-gyp configure     
node-gyp : Impossible de charger le fichier C:\Program Files\nodejs\node-gyp.ps1, car l’exécution de scripts est désactivée sur ce système. Pour plus d’informations, consultez about_Execution_Policies à 
l’adresse https://go.microsoft.com/fwlink/?LinkID=135170.
Au caractère Ligne:1 : 1
+ node-gyp configure
+ ~~~~~~~~
    + CategoryInfo          : Erreur de sécurité : (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\WF\RESSOURCES\SCRIPTS>
```

translation: "Unable to load file C:\Program Files\nodejs\node-gyp.ps1 because script execution is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

**Comment by gaikwadrahul8** [comment]
Hi, @liokaiser 

Thank you for providing the error log and as far I know by looking at above error message means that your Windows system has disabled the execution of scripts. This is a security measure to prevent malicious scripts from being run on your system.

To fix this error, you need to change the execution policy for your system. There are three levels of execution policy and you can refer this [link](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3) for more information :

1. `Restricted`: This is the default setting and prevents all scripts from being run.
2. `RemoteSigned`: This setting allows scripts to be run if they are signed by a trusted publisher.
3. `Unrestricted`: This setting allows all scripts to be run, regardless of their publisher.

To change the execution policy, open PowerShell as administrator and run the following command:
`Set-ExecutionPolicy <policy level>` and replace one of execution policy for your system 

For example, If you want to replace execution policy for your system to `RemoteSigned` then run the following command:

`Set-ExecutionPolicy RemoteSigned
`

I would suggest you to please check your windows system support AVX because tfjs-node unable to use if you don't have AVX processors so to check, 

1. Open the Start menu and search for "System Information".
2. Click on the top result to open the System Information tool.
3. In the System Summary section, look for the Processor line.
4. The value in the "Instruction Set" field will indicate whether your CPU supports AVX.

If the value in the "Instruction Set" field is "AVX", then your CPU supports AVX. If the value is "Not supported", then your CPU does not support AVX. I hope it helps to resolve your issue. 

Please follow the same instructions from previous comment once you follow above steps and confirm you've have AVX processor and set execution policy for your system

I hope this helps to resolve your issue. Thank you!

**Comment by liokaiser** [comment]
hi @gaikwadrahul8 
Oh I just noticed that the CPU of the Proxmox VM I'm using is not compatible with AVX instructions.
I thought it was compatible because it's a very recent version of proxmox.
Is there a particular way to install tensorFlow that overrides this limitation?
Thank You

**Comment by gaikwadrahul8** [comment]
Hi, @liokaiser 

Alright, thank you for the confirmation, this issue was happening because of AVX(processor) instructions on CPU of the Proxmox VM which you're using not compatible for AVX instructions so just to confirm, this issue got resolved for you or do you need any further help on this issue ? if not, please feel free to close this issue. Thank you!

**Comment by liokaiser** [comment]
Hi @gaikwadrahul8 

It's perfect, I managed to change the proxmox settings of the machine to make it AVX/AVX2 compatible.
The installation of tensorflow went smoothly and now I can use it correctly.

thanks a lot for your help
Lionel

**Comment by anshmourya** [comment]
> Hi @gaikwadrahul8
> 
> It's perfect, I managed to change the proxmox settings of the machine to make it AVX/AVX2 compatible. The installation of tensorflow went smoothly and now I can use it correctly.
> 
> thanks a lot for your help Lionel



hey what you did exactly. because i am facing the same issue.. can you help

**Comment by ChaudaryHammad** [comment]
Mine worked when I moved :
C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll
to
C:\WF\RESSOURCES\SCRIPTS\node_modules\@tensorflow\tfjs-node\lib\napi-v7

**Comment by san199332** [comment]
> Mine worked when I moved : C:\WF\RESSOURCES\SCRIPTS\node_modules@tensorflow\tfjs-node\deps\lib\tensorflow.dll to C:\WF\RESSOURCES\SCRIPTS\node_modules@tensorflow\tfjs-node\lib\napi-v7

Thank you! This helped me too.
