### ISSUE TITLE
Source map failed warning issue

### ISSUE THREAD

**Issue by siddiq-digival** [tensorflow/tfjs#7949]
WARNING in ./node_modules/face-api.js/build/es6/tinyYolov2/leaky.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '.\node_modules\face-api.js\src\tinyYolov2\leaky.ts' file: Error: ENOENT: no such file or directory, open 'D:\Security\DigiSchedulerWebApp\node_modules\face-api.js\src\tinyYolov2\leaky.ts'

actually file is not in this location " 'D:\Projects\node_modules\face-api.js\src\tinyYolov2\leaky.ts'" in node module. those files present in " 'D:\Projects\node_modules\face-api.js\build\es6\\tinyYolov2\leaky.d.ts'"

how to make this to locate correct location?

This is the issue after upgrading face-api. How to resolve it?

**Comment by gaikwadrahul8** [comment]
Hi, @siddiq-digival 

Thank you for bringing this issue to our attention, If possible, could you please provide us with a code snippet, your GitHub repo link, or CodePen example that replicates the issue? This will help us to troubleshoot the problem more quickly. 

In the meantime, please try downgrading to the previous version and see if that resolves the issue. Thank you for your cooperation.

Thank you

**Comment by siddiq-digival** [comment]
thanks for the response @gaikwadrahul8. 

I am using face-api version "^0.22.2",

these all the dependency i am using right now for my project. these only i can share it with you now

```json
    "@ckeditor/ckeditor5-build-classic": "^19.0.2",
    "@ckeditor/ckeditor5-react": "^6.1.0",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@fullcalendar/core": "^5.5.1",
    "@fullcalendar/daygrid": "^5.5.0",
    "@fullcalendar/interaction": "^5.5.0",
    "@fullcalendar/list": "^5.5.0",
    "@fullcalendar/react": "^5.5.0",
    "@fullcalendar/timegrid": "^5.5.1",
    "@mui/icons-material": "^5.10.9",
    "@mui/lab": "^5.0.0-alpha.107",
    "@mui/material": "^5.10.13",
    "@mui/styles": "^5.10.10",
    "@mui/x-date-pickers": "^5.0.19",
    "@szhsin/react-menu": "^1.3.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "apisauce": "^1.1.1",
    "axios": "^0.21.2",
    "bootstrap": "^4.4.1",
    "browserslist": "^4.12.0",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.9.0",
    "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
    "echarts": "^5.0.2",
    "echarts-for-react": "^3.0.1",
    "exceljs": "^4.3.0",
    "face-api.js": "^0.22.2",
    "file-saver": "^2.0.5",
    "font-awesome": "^4.7.0",
    "history": "^4.10.1",
    "html2canvas": "^1.0.0-rc.7",
    "i18next": "^21.6.3",
    "i18next-browser-languagedetector": "^6.1.2",
    "i18next-http-backend": "^1.3.1",
    "immutable": "^4.0.0-rc.12",
    "js-cookie": "^3.0.1",
    "jspdf": "^2.0.0",
    "jspdf-autotable": "^3.5.13",
    "moment": "^2.24.0",
    "multiselect-react-dropdown": "^1.6.1",
    "papaparse": "^5.2.0",
    "prop-types": "^15.8.0",
    "react": "^17.0.2",
    "react-bootstrap": "^1.4.0",
    "react-circular-progressbar": "^2.0.3",
    "react-color": "^2.19.3",
    "react-csv": "^2.0.3",
    "react-datepicker": "^4.16.0",
    "react-doc-viewer": "^0.1.5",
    "react-dom": "^17.0.2",
    "react-draft-wysiwyg": "^1.14.7",
    "react-ga4": "^1.0.6",
    "react-i18next": "^11.15.1",
    "react-image-lightbox": "^5.1.1",
    "react-infinite-scroll-hook": "^4.0.0",
    "react-multi-select-component": "^3.0.6",
    "react-notifications": "^1.6.0",
    "react-organizational-chart": "^2.2.0",
    "react-redux": "^7.2.2",
    "react-responsive-modal": "^6.0.1",
    "react-router-dom": "^5.3.4",
    "react-scripts": "^5.0.1",
    "react-select": "^4.3.0",
    "react-slick": "^0.28.1",
    "react-svg": "^15.1.7",
    "react-switch": "^6.0.0",
    "read-excel-file": "^5.0.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "styled-components": "^5.1.1",
    "sweetalert2": "^9.17.1",
    "webcam-easy": "^1.0.5",
    "xlsx": "^0.18.5"

**Comment by gaikwadrahul8** [comment]
Hi, @siddiq-digival 

I checked your package.json file and all the package dependancies mentioned above and you're using [face-api.js](https://github.com/justadudewhohacks/face-api.js) which is javascript module, built on top of [tensorflow.js core](https://github.com/tensorflow/tfjs-core), which implements several CNNs (Convolutional Neural Networks) to solve face detection, face recognition and face landmark detection, optimized for the web and for mobile devices.

I see there is no TFJs package dependancies so I believe this issue not related with tfjs packages so you can post this issue in `face-api.js` repo[ here](https://github.com/justadudewhohacks/face-api.js/issues/new) and please feel free to close this issue.

If I have missed something here please let me know ? Thank you!

**Comment by siddiq-digival** [comment]
Thanks for your support @gaikwadrahul8 .
