### ISSUE TITLE
Error Installing 

### ISSUE THREAD

**Issue by csj90** [tensorflow/tfjs#7950]
I get this error on linux ubuntu Ubuntu 22.04.3 LTS 

3245 timing build:link Completed in 32ms
3246 info run @napi-rs/canvas-linux-x64-gnu@0.1.44 install node_modules/@napi-rs/canvas-linux-x64-gnu node install.js
3247 info run @napi-rs/canvas-linux-x64-musl@0.1.44 install node_modules/@napi-rs/canvas-linux-x64-musl node install.js
3248 info run @tensorflow/tfjs-node@4.10.0 install node_modules/@tensorflow/tfjs-node node scripts/install.js
3249 info run @napi-rs/canvas-linux-x64-musl@0.1.44 install { code: 1, signal: null }
3250 verbose reify failed optional dependency /Api/node_modules/@napi-rs/canvas-linux-x64-musl
3251 silly reify mark deleted [ '/Api/node_modules/@napi-rs/canvas-linux-x64-musl' ]
3252 timing build:run:install:node_modules/@napi-rs/canvas-linux-x64-musl Completed in 163ms
3253 info run @napi-rs/canvas-linux-x64-gnu@0.1.44 install { code: 0, signal: null }
3254 timing build:run:install:node_modules/@napi-rs/canvas-linux-x64-gnu Completed in 228ms
3255 info run @tensorflow/tfjs-node@4.10.0 install { code: 1, signal: null }
3256 timing reify:rollback:createSparse Completed in 1866ms
3257 timing reify:rollback:retireShallow Completed in 0ms
3258 timing command:install Completed in 42373ms
3259 verbose stack Error: command failed
3259 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
3259 verbose stack     at ChildProcess.emit (node:events:512:28)
3259 verbose stack     at maybeClose (node:internal/child_process:1098:16)
3259 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
3260 verbose pkgid @tensorflow/tfjs-node@4.10.0
3261 verbose cwd /Api
3262 verbose Linux 5.15.0-83-generic
3263 verbose node v19.7.0
3264 verbose npm  v9.5.0
3265 error code 1
3266 error path /Api/node_modules/@tensorflow/tfjs-node
3267 error command failed
3268 error command sh -c node scripts/install.js
3269 error CPU-linux-4.10.0.tar.gz
3269 error https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz
3269 error node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
3269 error node-pre-gyp info it worked if it ends with ok
3269 error node-pre-gyp info using node-pre-gyp@1.0.9
3269 error node-pre-gyp info using node@19.7.0 | linux | x64
3269 error node-pre-gyp info check checked for "/Api/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" (not found)
3269 error node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.10.0/CPU-linux-4.10.0.tar.gz
3269 error node-pre-gyp ERR! install response status 403 Forbidden on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.10.0/CPU-linux-4.10.0.tar.gz 
3269 error node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.10.0 and node@19.7.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
3269 error node-pre-gyp WARN Hit error response status 403 Forbidden on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.10.0/CPU-linux-4.10.0.tar.gz 
3269 error gyp info it worked if it ends with ok
3269 error gyp info using node-gyp@9.3.1
3269 error gyp info using node@19.7.0 | linux | x64
3269 error gyp info ok 
3269 error gyp info it worked if it ends with ok
3269 error gyp info using node-gyp@9.3.1
3269 error gyp info using node@19.7.0 | linux | x64
3269 error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
3269 error gyp info spawn /usr/bin/python3
3269 error gyp info spawn args [
3269 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
3269 error gyp info spawn args   'binding.gyp',
3269 error gyp info spawn args   '-f',
3269 error gyp info spawn args   'make',
3269 error gyp info spawn args   '-I',
3269 error gyp info spawn args   '/Api/node_modules/@tensorflow/tfjs-node/build/config.gypi',
3269 error gyp info spawn args   '-I',
3269 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
3269 error gyp info spawn args   '-I',
3269 error gyp info spawn args   '/root/.cache/node-gyp/19.7.0/include/node/common.gypi',
3269 error gyp info spawn args   '-Dlibrary=shared_library',
3269 error gyp info spawn args   '-Dvisibility=default',
3269 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/19.7.0',
3269 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
3269 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/19.7.0/<(target_arch)/node.lib',
3269 error gyp info spawn args   '-Dmodule_root_dir=/Api/node_modules/@tensorflow/tfjs-node',
3269 error gyp info spawn args   '-Dnode_engine=v8',
3269 error gyp info spawn args   '--depth=.',
3269 error gyp info spawn args   '--no-parallel',
3269 error gyp info spawn args   '--generator-output',
3269 error gyp info spawn args   'build',
3269 error gyp info spawn args   '-Goutput_dir=.'
3269 error gyp info spawn args ]
3269 error gyp info ok 
3269 error gyp info it worked if it ends with ok
3269 error gyp info using node-gyp@9.3.1
3269 error gyp info using node@19.7.0 | linux | x64
3269 error gyp info spawn make
3269 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
3269 error In file included from ../binding/tfjs_backend.cc:18:
3269 error ../binding/tfjs_backend.h:25:10: fatal error: tensorflow/c/c_api.h: No such file or directory
3269 error    25 | #include "tensorflow/c/c_api.h"
3269 error       |          ^~~~~~~~~~~~~~~~~~~~~~
3269 error compilation terminated.
3269 error make: *** [tfjs_binding.target.mk:116: Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 1
3269 error gyp ERR! build error 
3269 error gyp ERR! stack Error: `make` failed with exit code: 2
3269 error gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
3269 error gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
3269 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
3269 error gyp ERR! System Linux 5.15.0-83-generic
3269 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Api/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/Api/node_modules/@tensorflow/tfjs-node/lib/napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
3269 error gyp ERR! cwd /Api/node_modules/@tensorflow/tfjs-node
3269 error gyp ERR! node -v v19.7.0
3269 error gyp ERR! node-gyp -v v9.3.1
3269 error gyp ERR! not ok 
3269 error node-pre-gyp ERR! build error 
3269 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Api/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node --module_name=tfjs_binding --module_path=/Api/node_modules/@tensorflow/tfjs-node/lib/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
3269 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Api/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
3269 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
3269 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
3269 error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
3269 error node-pre-gyp ERR! System Linux 5.15.0-83-generic
3269 error node-pre-gyp ERR! command "/usr/local/bin/node" "/Api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
3269 error node-pre-gyp ERR! cwd /Api/node_modules/@tensorflow/tfjs-node
3269 error node-pre-gyp ERR! node -v v19.7.0
3269 error node-pre-gyp ERR! node-pre-gyp -v v1.0.9
3269 error node-pre-gyp ERR! not ok
3270 error * Downloading libtensorflow
3270 error
3270 error * Building TensorFlow Node.js bindings
3271 verbose exit 1
3272 timing npm Completed in 42498ms
3273 verbose unfinished npm timer reify 1694473312475
3274 verbose unfinished npm timer reify:build 1694473350456
3275 verbose unfinished npm timer build 1694473350459
3276 verbose unfinished npm timer build:deps 1694473350460
3277 verbose unfinished npm timer build:run:install 1694473350685
3278 verbose unfinished npm timer build:run:install:node_modules/@tensorflow/tfjs-node 1694473350818
3279 verbose code 1
3280 error A complete log of this run can be found in:
3280 error     /root/.npm/_logs/2023-09-11T23_01_52_375Z-debug-0.log

**Comment by gaikwadrahul8** [comment]
Hi, @csj90 

Thank you for bringing this issue to our attention, could you please help me with error log after running below command to investigate this issue further ? Thank you!

1. `npm install -g node-gyp` ( Install node-gyp globally)
2. `npm install @tensorflow/tfjs-node@4.10.0`
3. ` node-gyp configure`  ( To see complete error log so please share error log after running this command)

**Comment by csj90** [comment]
root@server:/Api# node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@19.7.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Api/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/19.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/19.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/19.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Api',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Api) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.15.0-83-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Api
gyp ERR! node -v v19.7.0
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok

**Comment by gaikwadrahul8** [comment]
Hi, @csj90 

Apologize for the delayed response and just to confirm, have you installed GCC Compiler on your Linux machine ? if not please try below commands in your terminal :

1. `sudo apt-get update`
2. `sudo apt install build-essential`

 To verify it is installed correctly, check the version of the GCC by using this command `gcc --version`
 
 I see from your previous error log you're using Node version `19.7.0` so could you please try with `Node Latest LTS Version: 18.18.0 (includes npm 9.8.1) ` or Node version `18.17.0` and also try with different python versions because `node-gyp `requires that you have installed a compatible version of Python, one of: `v3.7, v3.8, v3.9, or v3.10.` , I see currently you're using Python version `3.10.12`
 
 Try to execute below commands :
 
1. `npm install -g node-gyp` ( Install node-gyp globally)
2. `npm install @tensorflow/tfjs-node`

After trying above workaround please let us know, Is it resolving your issue or not ? If issue still persists please help us with recent error log to investigate your issue further. 

Thank you for your support and patience!
