### ISSUE TITLE
WeChat mini-app NPM build doesn't work with TFJS

### ISSUE THREAD

**Issue by wangtz** [tensorflow/tfjs#796]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
latest
#### Browser version
wechat-mini app
#### Describe the problem or feature request
完成构建。耗时 3910 毫秒。
1. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/@types/long/index.js: 未找到npm包入口文件
2. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/@types/node/index.js: 未找到npm包入口文件
3. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/@types/seedrandom/index.js: 未找到npm包入口文件
4. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/@types/webgl-ext/index.js: 未找到npm包入口文件
5. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/@types/webgl2/index.js: 未找到npm包入口文件
6. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/cli/pbjs.js:9-9: 不允许require变量
7. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/cli/pbjs.js:164-164: 不允许require变量
8. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/cli/util.js:17-17: 不允许require变量
9. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/cli/util.js:41-41: 不允许require变量
10. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/cli/util.js:136-136: 不允许require变量
11. /Users/wangtz/Projects/working/wechat-mini-app/test1/node_modules/protobufjs/node_modules/@types/long/index.js: 未找到npm包入口文件
确定
iPhone 5
100%
WiFi
 WeChat
10:43
94%
WeChat

页面路径
pages/index/index

#### Code to reproduce the bug / link to feature request
npm install @tensorflow/tfjs
then use wechat mini-app developer tools to build the MPM

**Comment by nsthorat** [comment]
We now have an official tfjs-wechat repo here: https://github.com/tensorflow/tfjs-wechat
