### ISSUE TITLE
How can I load the weights of a local model weight that is too large?

### ISSUE THREAD

**Issue by kenhuang1964** [tensorflow/tfjs#7962]
I get this error when I tried to load the efficientnetv2 model in expo react native frontend:
error: src/models/effnetv2/effnetweights.bin: Cannot create a string longer than 0x1fffffe8 characters

Here is the code I am using:
```
const loadModel = async() => {
    const modelJson = require('./effnetv2/model.json');
    const modelWeights = require('./effnetv2/effnetweights.bin');
    model = await tf.loadLayersModel(bundleResourceIO(modelJson, modelWeights));
}
loadModel();
```

The model weight is around 940 MB.

**Comment by gaikwadrahul8** [comment]
Hi, @kenhuang1964 

Thank you for bringing this issue to our attention, could you please help me with your TFJs model in zip format and `package.json` file to replicate the same issue from my end ?

Meanwhile, please refer this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) may be there are package dependancies compatibility versions issue so please give it try with mentioned package versions or if you're trying latest package versions then please give it try by downgrading specifically `expo` and `react-native` versions. Thank you!
