### ISSUE TITLE
WeChat mini-app can't load local model 

### ISSUE THREAD

**Issue by lindow2009** [tensorflow/tfjs#7964]
TensorFlow.js version
0.2.0

Browser version
wechat mini app

Describe the problem or feature request

WAServiceMainContext.js:2 Error: MiniProgramError
{"errMsg":"request:fail invalid url \"./resources/model/yolov5n-seg.pt\""}
    at Object.errorReport (WAServiceMainContext.js:2)
    at r.thirdErrorReport (WAServiceMainContext.js:2)
    at Object.thirdErrorReport (WAServiceMainContext.js:2)
    at i (WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2)
    at Object.a [as cb] (WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2)
    at WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2
    at Array.forEach (<anonymous>)
    at n.emit (WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2)
    at t (WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2)
    at WASubContext.js?t=wechat&s=1695026135767&v=2.19.4:2(env: macOS,mp,1.06.2308310; lib: 2.19.4)

Try use  ”tfc.loadGraphModel“ to load local model from wechat mini app, you'll see this error message.

**Comment by lindow2009** [comment]
> Hi, @lindow2009
> 
> Thank you for bringing this issue to our attention, Could you please help me with `code-snippet/codepen-example` or your `Github repo` with steps to replicate the same issue from my end with `model zip file` to investigate this issue further ? Thank you!

this  is my code

var tfc = require('@tensorflow/tfjs-converter');
const model = tfc.loadGraphModel('./resources/model/yolov5n-seg.pt');

**Comment by gaikwadrahul8** [comment]
Hi, @lindow2009

If you're trying to convert any other format of the model into Tensorflow.js then please follow this [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md) to convert that model into Tensorflow.js with the help of tfjs-converter and once it's converted then you can load that Tensorflow.js model with the help of either [tf.loadGraphModel](https://js.tensorflow.org/api/latest/#loadGraphModel) or [tf.loadLayersModel](https://js.tensorflow.org/api/latest/#loadLayersModel) and to check the model format you can open `model.json` file and see which type of model you have it should be either `{ "format" :"graph-model"}` or `{ "format" :"layers-model"}
`

If you've `{ "format" :"graph-model"}` then please use this [tf.loadGraphModel](https://js.tensorflow.org/api/latest/#loadGraphModel) and for `{ "format" :"layers-model"}` use [tf.loadLayersModel](https://js.tensorflow.org/api/latest/#loadLayersModel) API 

I hope it will help you to resolve your issue or Am I missing something here ?

If issue still persists please let us know with your model in zip format to investigate your issue further. Thank you!
