### ISSUE TITLE
Platform node has already been set. Overwriting the platform with node. cpu backend was already registered. Reusing existing backend factory. Web app shutting down with this error.

### ISSUE THREAD

**Issue by FlyingTurkman** [tensorflow/tfjs#7969]
**System information**
- Windows 10
- TensorFlow.js installed from (npm or script link): @tensorflow/tfjs

I am trying to develop a web app with next.js 13.4. When I am trying to use @tensorflow/tfjs library but sometimes app down with this error "Platform node has already been set. Overwriting the platform with node.
cpu backend was already registered. Reusing existing backend factory." but moehow sometimes its working sometimes not working. I cant use @tensorflow/tfjs-node libarary because I cant install it node js is down when I am trying to install @tensorflow/tfjs-node

**Comment by gaikwadrahul8** [comment]
Hi, @FlyingTurkman 

Thank you for bringing this issue to our attention and it seems like you're also facing the same issue which mentioned in this issue https://github.com/tensorflow/tfjs/issues/7965 if I'm not wrong and I reproduced the same issue from my end in that issue so we'll have to dig more into this issue and will update you soon

If I have missed something here or you're referring different issue please help me with code-snippet/codepen-example or Github repo link to replicate the same behaviour from my end ? Thank you!

**Comment by FlyingTurkman** [comment]
Yes same problem thank you
