### ISSUE TITLE
WeChat mini-app can't load model as it doesn't support fetch method

### ISSUE THREAD

**Issue by wangtz** [tensorflow/tfjs#797]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.10.0
#### Browser version
wechat mini app
#### Describe the problem or feature request
Uncaught (in promise) TypeError: fetch is not a function
    at Object.<anonymous> (tfjs.js:1)
    at r (tfjs.js:1)
    at Object.next (tfjs.js:1)
    at tfjs.js:1
    at Promise (<anonymous>)
    at o (tfjs.js:1)
    at Object.n.loadModelInternal (tfjs.js:1)
    at Object.e.loadModel (tfjs.js:1)
    at index.js:10
    at require (WAService.js:19)
#### Code to reproduce the bug / link to feature request
Try load weight from wechat mini app, you'll see this error message.

**Comment by tafsiri** [comment]
@wangtz Is the model being served from an http server? If not you may be able to use a different load handler to load the model. See https://js.tensorflow.org/tutorials/model-save-load.html for examples of some of the load handlers that are supported. If you are trying to load a mode from an http server, and you are comfortable with how web requests work you could define your own global `fetch` function whose job is to get a resource from a server (https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch). 

@caisq I do see a pattern in issues like this that make me think we should better document how to implement a custom IO handler. Maybe we can augment the guide above to describe the interfaces and show an example of a custom IOHandler? What do you think?

**Comment by pyu10055** [comment]
@caisq WeChat mini app is not a wrapper for webview, it provides different API for http requests and local file access. It is also different from node.js as well. 
We should consider whether our repository should be the place for hosting those custom io handlers, for example, I would probably create two handlers for WeChat mini app, this list could grow with more third-party platforms we are supporting.

**Comment by mogoweb** [comment]
@pyu10055  how to define my own global **fetch** function in WeChat mini app? Is there an example?

**Comment by yinjun322** [comment]
> @pyu10055 how to define my own global **fetch** function in WeChat mini app? Is there an example?

我是直接用wx.request 和 wx.downloadFile 模拟 window.fetch 函数，模型可以加载成功，以及预测也可以 ,但是ios 的小游戏上面 predict 会卡一会，安卓没什么问题

**Comment by pyu10055** [comment]
this has been addressed with TFJS platform object, WeChat platform supplies the custom fetch method.
