### ISSUE TITLE
Enable importExternalTexture for webgpu-fromPixels

### ISSUE THREAD

**Issue by Linchenn** [tensorflow/tfjs#7972]
It seems we disabled `importExternalTexture` previously because of webgpu issue, https://github.com/tensorflow/tfjs/pull/6868, but I saw WebGPU is [advertising](https://pr-7324-static-dot-dcc-staging.uc.r.appspot.com/blog/from-webgl-to-webgpu/#video-frame-processing) this feature recently, so could we enable this feature too?

**Comment by Linchenn** [comment]
@gyagp @shaoboyan

**Comment by gyagp** [comment]
Yes, we can turn it on again. Just uploaded https://github.com/tensorflow/tfjs/pull/7976 to enable it and PTAL.
