### ISSUE TITLE
@tensorflow/tfjs-react-native fetch not working in expo react native?

### ISSUE THREAD

**Issue by kenhuang1964** [tensorflow/tfjs#7973]
Hey guys, I hope you are doing well. I am trying to use the fetch() from @tensorflow/tfjs-react-native but it doesn't seem to be working... can someone please help me?
My code:
```
const data = await cameraRef.current.takePictureAsync();
const croppedImage = await cropPicture(data, 380);
const response = await fetch(croppedImage.uri, {}, { isBinary: true }); 
const imageDataArrayBuffer = await response.arrayBuffer();
const uIntArray = new Uint8Array(imageDataArrayBuffer);
// decode a JPEG-encoded image to a 3D Tensor of dtype
const decodedImage = decodeJpeg(uIntArray, 3);
// reshape Tensor into a 4D array
return decodedImage.reshape([
    1,
    BITMAP_DIMENSION,
    BITMAP_DIMENSION,
    TENSORFLOW_CHANNEL,
]);
```
I am getting this error:
TypeError: Network request failed

**Comment by gaikwadrahul8** [comment]
Hi, @kenhuang1964 

Thank you for bringing this issue to our attention and If possible could you please help with `codepen-example/code-snippet or Github repo` link with complete steps to replicate the same issue from my end which will help to investigate this issue further

Meanwhile, I found one [stack-overflow answer](https://stackoverflow.com/questions/60639983/react-native-expo-fetch-throws-network-request-failed) which may help you to solve your issue. Thank you!
