### ISSUE TITLE
Support for hermes js engine?

### ISSUE THREAD

**Issue by kenhuang1964** [tensorflow/tfjs#7977]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 4.11
- Are you willing to contribute it (Yes/No): No (don't have the skills)

**Describe the feature and the current behavior/state.**
Tensorflow js currently doesn't work well with the hermes engine which is used for expo react native applications. Expo 49 doesn't work with jsc jsEngine, which means that I can't use tensorflow js... 
**Will this change the current api? How?**
Not sure.
**Who will benefit with this feature?**
Many people using expo for app development
**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @kenhuang1964

Thanks for your question about support for the `Hermes JS engine` in TensorFlow.js and Hermes JavaScript engine made the default in `Expo 49`, but you can still use JSC in `Expo 48` by setting the `jsEngine `field to `jsc` in your `app.config.js `file 

At the moment I'm not sure if the development team is actively working on `Hermes JS engine` support in `TensorFlow.js`, or if it is still under development. I will confirm with the relevant team and update you soon.

Thank you!

**Comment by kenhuang1964** [comment]
Hey @gaikwadrahul8 , I have tried using jsc in expo 48 and it doesn't work either.

**Comment by gaikwadrahul8** [comment]
Hi, @kenhuang1964 

I apologize for the delayed response, I see this PR https://github.com/tensorflow/tfjs/pull/7947 got merged, To confirm, have we taken care of this issue or still this issue persists ? Thank you!

**Comment by kenhuang1964** [comment]
Hey @gaikwadrahul8 thanks for the response! I'm not too sure... I looked into an alternative solution
