### ISSUE TITLE
Error: Kernel 'ExpandDims' not registered for backend 'rn-webgl'

### ISSUE THREAD

**Issue by YUFOHON** [tensorflow/tfjs#7979]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device:  Android Emulator Pixel_4_API_30
- TensorFlow.js installed from (npm or script link): yarn
- TensorFlow.js version (use command below): 4.11.0
- Browser version: Not using any Browser | on bare react native project
- Tensorflow.js Converter Version: no idea

**Describe the current behavior**
Error: Kernel 'ExpandDims' not registered for backend 'rn-webgl'
![image](https://github.com/tensorflow/tfjs/assets/117070313/7f6d1291-5e54-41ba-9728-d487e91b87f8)

**Describe the expected behavior**
No Errors

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: Kernel 'ExpandDims' not registered for backend 'rn-webgl'
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:108378:24
f2@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:109262:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:257809:97
step@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:257625:23
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:257548:73
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24972:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:25103:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24991:14
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:257530:36
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:92443:50
generatorResume@[native code]
asyncGeneratorStep@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20487:26
_next@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20506:29
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20511:14
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24972:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:25103:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24991:14
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20503:25
loop@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:92458:31
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:92461:13
generatorResume@[native code]
asyncGeneratorStep@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20487:26
_next@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20506:29
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20511:14
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24972:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:25103:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24991:14
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20503:25
handleCameraStream@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:92464:26
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:295287:31
generatorResume@[native code]
asyncGeneratorStep@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20487:26
_next@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:20506:29
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:24964:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:25045:27
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:26089:26
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:26008:17
_callReactNativeMicrotasksPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:26038:17
callReactNativeMicrotasks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:26201:44
__callReactNativeMicrotasks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:2505:46
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:2317:45
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:2489:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.babylonreactnativesample&modulesOnly=false&runModule=true:2316:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]

![image](https://github.com/tensorflow/tfjs/assets/117070313/865803f7-d812-4175-b614-735eeda0796a)

**Comment by YUFOHON** [comment]
![image](https://github.com/tensorflow/tfjs/assets/117070313/4a0b4959-2fa1-4552-b5f5-2abaaa4a478f)

**Comment by vemarav** [comment]
not resolved
