### ISSUE TITLE
why my tensorflow/tfjs-node cannot download or give loots of error 

### ISSUE THREAD

**Issue by adarsh12u** [tensorflow/tfjs#7980]

**Comment by gaikwadrahul8** [comment]
Hi, @adarsh12u

Thank you for bringing this issue to our attention, could you please help me with below details and error log screenshot to investigate this issue further. Thank you!

I believe you're following these official documentation for [node-gyp - Node.js native addon build tool](https://github.com/nodejs/node-gyp#node-gyp---nodejs-native-addon-build-tool), [TensorFlow backend for TensorFlow.js via Node.js](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#tensorflow-backend-for-tensorflowjs-via-nodejs) and [WINDOWS_TROUBLESHOOTING.md](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md)

1. On Which `OS` you're facing issue
2. `Node.js` version
3. which version of `@tensorflow/tfjs-node` you're trying
4. which `Python` version you're using

**Comment by adarsh12u** [comment]
1. Windows 11
2 .node version =  18.18.0
3. i am trying for current version of @tensorflow/tfjs-node
4. python version = 2.7.15
and i am not able to download windows-build-tools .  in my system so plz
tell me solution

**Comment by adarsh12u** [comment]
or node-gyp is necessary to know the path of python

**Comment by adarsh12u** [comment]
[image: errer.png][image: err2.png]

**Comment by gaikwadrahul8** [comment]
Hi, @adarsh12u 

Could you please follow below steps and let us know is it resolving your issue or not ? if not please help us with error log output after running this command `node-gyp configure` Thank you!

1. Edit the path user or system variable, ensure that the path to python is added to the ‘path’ variable.
2. Install Visual Studio community edition with desktop development with C++  [Link](https://visualstudio.microsoft.com/vs/community/)
3. Install visual studio build tools with the help of Visual Studio Installer
4. Ensure that `node-gyp` is available: `npm install -g node-gyp`
5. Install tfjs-node: `npm install @tensorflow/tfjs-node@3.2.0`
