### ISSUE TITLE
why @tensorflow/tfjs-node are not install or give loots of error

### ISSUE THREAD

**Issue by adarsh12u** [tensorflow/tfjs#7981]
why @tensorflow/tfjs-node are not install or give loots of error

**Comment by gaikwadrahul8** [comment]
Hi, @adarsh12u 

Thank you for bringing this issue to our attention, could you please help me with below details and error log screenshot to investigate this issue further. Thank you!

I believe you're following these official documentation for [node-gyp - Node.js native addon build tool](https://github.com/nodejs/node-gyp#node-gyp---nodejs-native-addon-build-tool), [TensorFlow backend for TensorFlow.js via Node.js](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#tensorflow-backend-for-tensorflowjs-via-nodejs) and [WINDOWS_TROUBLESHOOTING.md](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md)

1. On Which `OS` you're facing issue
2. `Node.js` version 
3. which version of `@tensorflow/tfjs-node` you're trying
3. which `Python` version you're using
