### ISSUE TITLE
".platform" empty in env() in react-native

### ISSUE THREAD

**Issue by ALexandreM75013** [tensorflow/tfjs#7991]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1, React-native bare app 0.72.5 (latest version)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung S10
- TensorFlow.js version: 4.11.0
- Tensorflow.js react-native version: ^0.8.0

Hi,

Whenever I call `tf.scalar(255);`, tensorflow is failling returning this error message : `Cannot read property 'isTypedArray' of undefined`.
After digging into the `scalar()` function in the @tensorflow node_modules folder, I see that there is a call to the `isTypedArray()` function which tries to access to the key "platform" from the env() variable and this is empty.

From tf.node.js:
```
function isTypedArray(a) {
    // TODO(mattsoulanille): Remove this fallback in 5.0.0
    if (env().platform.isTypedArray != null) {
        return env().platform.isTypedArray(a);
    }
    else {
        return isTypedArrayBrowser(a);
    }
}
```

`env()` is from the class `Environment `and in this class I see that  there is a function `setPlatform()` but it seems it is not called in react-native and it is not setting anything in the `platform/platformName` keys of the class Environment.

From tf.node.js:
```
class Environment {
    // tslint:disable-next-line: no-any
    constructor(global) {
        this.global = global;
        this.flags = {};
        this.flagRegistry = {};
        this.urlFlags = {};
        // Jasmine spies on this in 'environment_test.ts'
        this.getQueryParams = getQueryParams;
        this.populateURLFlags();
    }
    setPlatform(platformName, platform) {
        if (this.platform != null) {
            if (!(env().getBool('IS_TEST') || env().getBool('PROD'))) {
                console.warn(`Platform ${this.platformName} has already been set. ` +
                    `Overwriting the platform with ${platformName}.`);
            }
        }
        this.platformName = platformName;
        this.platform = platform;
    }
...
```

If I just do a console.log() of `tf.env()`, I see indeed that `platform/platformName` are not set but the other keys are well set (global /flags/flagRegistry...).

I was previously using the version 3.18.0 of Tensor and this check was not existing in the scalar() function.

This is my code in react-natice just to try the scalar() function : 

```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';

class App extends PureComponent {
  componentDidMount() {
    try {
      tf.ready(); => works
      const scalar = tf.scalar(255); => fails
    } catch (err) {
      console.log(err); => error Cannot read property 'isTypedArray' of undefined
    }
  }

```

**Comment by gaikwadrahul8** [comment]
Hi, @ALexandreM75013 

Thank you for reporting this issue. It appears that incompatible package versions may be the cause. Could you please try downgrading the `React Native` version to see if that resolves the issue? 

If possible, please provide us with your `package.json` file and steps to reproduce the issue on our end. Please also refer to the [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) for more information.

Thank you for your cooperation.

**Comment by ALexandreM75013** [comment]
Hi @gaikwadrahul8 
I have lowered the React-native version to 0.71.0, unfortunalely still exactly the same issue.
When calling tf.ready() no error, but when calling tf.scalar(255), I have an error.

Here is my package json for the tested app in react-native 0.71.0:
```
{
  "name": "Tensor",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@tensorflow/tfjs": "^4.11.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo": "^48.0.0",
    "expo-camera": "~13.2.1",
    "expo-gl": "~12.4.0",
    "react": "18.2.0",
    "react-native": "0.71.0",
    "react-native-fs": "^2.20.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.14.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.5",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by ALexandreM75013** [comment]
@gaikwadrahul8 gaikwadrahul8 

So small update on this issue. I finally managed to make it work on react-native with the library NSFWJS after making some modifications in tfjs library.

First of all, we need to call `setPlatform('react-native', new PlatformReactNative())` which is in platform_react_native.ts. This is actually working on lower version of tfjs (3.18.0 works), but starting version >4.0.0 it is not called anymore. So to make the call to this function I am calling fetch() from tfjs-react-native just to call `setPlatform('react-native', new PlatformReactNative())`.

```
import {
  fetch,
} from '@tensorflow/tfjs-react-native';

try {
      await fetch();
} catch (err) {
     //ALWAYS FAIL but will call setPlatform() in platform_react_native.ts
} 
```

Then I had to replace all `XXX instanceof Tensor` or `XXX instanceof tfc.Tensor` by `XXX instanceof getGlobalTensorClass()` in tf.node.js, tf-core.node.js and tf-layers.node.js.

Now it works in react-native latest version with latest version of tfjs and tfjs-react-native.

**Comment by gaikwadrahul8** [comment]
Hi, @ALexandreM75013

I am pleased to hear that you have managed to make NSFWJS work on React Native with the latest versions of `tfjs` and `tfjs-react-native`. It would be grateful if you would submit a pull request to share your workaround with the community to work react-native latest version with latest version of `tfjs` and `tfjs-react-native`. Thank you!

**Comment by JRfan123** [comment]
I have the same question

**Comment by JRfan123** [comment]
const imageTensor = decodeJpeg(u8arr);
      console.log('imageTensor====');
      const inputImage = tf
        .transpose(imageTensor, [2, 0, 1])
        .expandDims(0)
        .div(tf.scalar(255));
<img width="509" alt="image" src="https://github.com/tensorflow/tfjs/assets/158460447/e5a8e6f3-7c8b-4845-85d2-cddf6ebeeaad">


throws the error:  in decodeJpeg(u8arr)
