### ISSUE TITLE
WeChat mini-app save model permission denied

### ISSUE THREAD

**Issue by lindow2009** [tensorflow/tfjs#7997]
TensorFlow.js version
0.2.0

Browser version
wechat mini app

Describe the problem or feature request

Error: Error: mkdir:fail permission denied with path "http://usr/__plugins__/wx6afed118d9e81de3/tensorflowjs_models"
    at u.<anonymous> (VM7160 appservice.js:1173)
    at VM7160 appservice.js:1173
    at Object.next (VM7160 appservice.js:1173)
    at s (VM7160 appservice.js:1173)(env: macOS,mp,1.06.2308310; lib: 2.33.0)

Try use ”model.save“ to save model from wechat mini app, you'll see this error message.

**Comment by gaikwadrahul8** [comment]
Hi, @lindow2009 

I apologize for the delayed response and thank you for bringing this issue to our attention, at the moment there might be below reason for above issue `WeChat mini-app` does not have permission to create a directory at the specified path, The directory may not exist. The directory may exist, but the mini-app does not have write permission to it.

If you are still having problems, you can try saving the model to a different location.

Make sure that the mini-app has permission to write to the location where the model is being saved.

If you have tried all of the above and are still having problems, the issue may be with the WeChat mini-app itself. Please contact WeChat support for assistance. Thank you!

**Comment by lindow2009** [comment]
OK.thanks
