### ISSUE TITLE
Add deeplearn migration guide

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#8]
An MD file with instructions on how to migrate from deeplearn 0.5 and up

**Comment by silky** [comment]
so does this library supercede deeplearn js?

**Comment by QuantumInformation** [comment]
Yes

**Comment by QuantumInformation** [comment]
I changed a simple project from deeplearn to tfjs here:
https://github.com/QuantumInformation/tensorflowjs-playground/commit/ff5a848c103e9a342540a75165b77afc1d428a5f

**Comment by dsmilkov** [comment]
We have migration instructions in our release notes: https://github.com/tensorflow/tfjs-core/releases/tag/v0.6.0. I can add a sentence in the README.md to point to that.

**Comment by QuantumInformation** [comment]
I made a simple video of my migration experience

https://www.youtube.com/watch?v=ZjneMYde3Mo

**Comment by nsthorat** [comment]
Awesome stuff, hope it wasn't painful :)

**Comment by QuantumInformation** [comment]
Piece of cake
