### ISSUE TITLE
FR: Provide a mechanism to force enable/disable webGL

### ISSUE THREAD

**Issue by wangtz** [tensorflow/tfjs#800]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
all
#### Browser version
all
#### Describe the problem or feature request
I suggest this FR as I want to isolate performance and supportability issues. When webGL is forced enabled, it will fail when it can't. If webGL is forced disabled, it will use CPUs even when GPU accerleration is possible.

**Comment by DavidGOrtega** [comment]
tf.setBackend('cpu', false);

**Comment by pyu10055** [comment]
@wangtz as @DavidGOrtega suggested you can designate a backend by using setBackend('cpu').
But current we will always fallback to cpu if gpu is not available.

**Comment by DavidGOrtega** [comment]
something like this?

```js
function webgl_available()
{
    var canvas  = document.createElement("canvas");
    var gl      = canvas.getContext("webgl") || canvas.getContext("experimental-webgl");

    return gl && gl instanceof WebGLRenderingContext;
}
```

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
