### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'

### ISSUE THREAD

**Issue by vovarudykk** [tensorflow/tfjs#8004]
**System information**
- OS Platform and Distribution: Windows 11 22H2 22621.2428
- TensorFlow.js installed from: pip install tensorflowjs
- TensorFlow.js version:  3.18.0
- Tensorflow version: 2.14.0
- Python version: 3.11 (also try 3.12 and 2.7)

I want to use tensorflowjs to save my keras dnn model in tensorflowjs format for use in my nodejs backend. But I can't even import 

`import tensorflowjs as tfjs`

because I immediately get an error: 

`ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'`

Full error:

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 1
----> 1 import tensorflowjs as tfjs

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflowjs\__init__.py:21
     18 from __future__ import print_function
     20 # pylint: disable=unused-imports
---> 21 from tensorflowjs import converters
     22 from tensorflowjs import quantization
     23 from tensorflowjs import version

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflowjs\converters\__init__.py:21
     18 from __future__ import print_function
     20 # pylint: disable=unused-imports,line-too-long
---> 21 from tensorflowjs.converters.converter import convert
     22 from tensorflowjs.converters.keras_h5_conversion import save_keras_model
     23 from tensorflowjs.converters.keras_tfjs_loader import deserialize_keras_model

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflowjs\converters\converter.py:37
     35 from tensorflowjs.converters import keras_h5_conversion as conversion
     36 from tensorflowjs.converters import keras_tfjs_loader
---> 37 from tensorflowjs.converters import tf_saved_model_conversion_v2
     40 def dispatch_keras_h5_to_tfjs_layers_model_conversion(
     41     h5_path, output_dir=None, quantization_dtype_map=None,
     42     split_weights_by_layer=False,
     43     weight_shard_size_bytes=1024 * 1024 * 4,
     44     metadata=None):
     45   """Converts a Keras HDF5 saved-model file to TensorFlow.js format.
     46 
     47   Auto-detects saved_model versus weights-only and generates the correct
   (...)
     73       groups: an array of weight_groups as defined in tfjs weights_writer.
     74   """

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py:42
     40 from tensorflow.python.tools.saved_model_cli import get_signature_def_map
     41 from google.protobuf.json_format import MessageToDict
---> 42 import tensorflow_hub as hub
     44 from tensorflowjs import write_weights
     45 from tensorflowjs.converters import common

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\__init__.py:93
     91 from tensorflow_hub.feature_column import sparse_text_embedding_column
     92 from tensorflow_hub.feature_column import text_embedding_column
---> 93 from tensorflow_hub.feature_column_v2 import text_embedding_column_v2
     94 from tensorflow_hub.image_util import attach_image_module_info
     95 from tensorflow_hub.image_util import get_expected_image_size

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\feature_column_v2.py:24
     21 import collections
     23 import tensorflow as tf
---> 24 from tensorflow_hub import keras_layer
     26 # TODO(b/73987364): It is not possible to extend feature columns without
     27 # depending on TensorFlow internal implementation details.
     28 # pylint: disable=g-direct-tensorflow-import
     29 from tensorflow.python.feature_column import feature_column_v2

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\keras_layer.py:27
     25 # pylint: disable=g-direct-tensorflow-import
     26 from tensorflow.python.framework import smart_cond
---> 27 from tensorflow.python.training.tracking import data_structures
     28 from tensorflow.python.util import tf_inspect
     29 # pylint: enable=g-direct-tensorflow-import

ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'`

**Comment by gaikwadrahul8** [comment]
Hi, @vovarudykk 

Thank you for bringing this issue to our attention and I see currently you're using `python 3.11` version so could you please give it try with `python version 3.8` or `python 3.9 version`  ?

May I know what all steps you followed to install `Tensorflow.js` on your `Windows 11`  system ? Thank you!

**Comment by vovarudykk** [comment]
So I installed Python 3.8 and 3.9.

I tried to install tensorflowjs on a clean install, but 3.8 threw an error:

```
ERROR: Cannot install flax because these package versions have conflicting dependencies.

The conflict is caused by:
    optax 0.1.2 depends on jaxlib>=0.1.37
    optax 0.1.1 depends on jaxlib>=0.1.37
    optax 0.1.0 depends on jaxlib>=0.1.37
    optax 0.0.91 depends on jaxlib>=0.1.37
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37
    optax 0.0.5 depends on jaxlib>=0.1.37
    optax 0.0.3 depends on jaxlib>=0.1.37
    optax 0.0.2 depends on jaxlib>=0.1.37
    optax 0.0.1 depends on jaxlib>=0.1.37
```

I couldn't solve it, so I decided to try 3.9. Surprisingly the tensorflowjs import worked, so I installed all the other modules and tried to train the model I wanted to save. Then I noticed that the model.fit() method started to fight on my input:

`UnknownError: Graph execution error: [array with input data] not in index.`

Then I reinstalled tensorflowjs again and for some reason this time I got a new error when importing tensorflow (not js):

`ModuleNotFound Error: No module named tensorflow.security`

Then I again reinstalled all the necessary modules and at the end tensorflowjs. It worked, so now everything is working as it should. I don't know what the problem was, but I suspect that tensorflow, tensorflowjs, pandas, scikit-learn and something else need different versions of some modules. When installing them in a certain order, they replace the ones needed for tensorflowjs and cause problems. 

From time to time the following errors appeared in the console:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflowjs 3.21.0 requires packaging~=20.9, but you have packaging 23.2 which is incompatible.
tensorflowjs 3.21.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.4 which is incompatible.
```

Unfortunately, installing these versions of these modules did not help.

**Comment by gaikwadrahul8** [comment]
Hi, @vovarudykk 

Good to hear that somehow you managed to to install Tensorflow.js, I see you were trying to install `Tensorflowjs 3.21.0` so to confirm, did you try with latest version `tensorflowjs 4.11.0` because you've mentioned your `Tensorflow version 2.14.0` that is latest version of Tensorflow ? 

I would suggest you to avoid package conflicts between other installed libraries or packages on your `Windows 11` system please create virtual environments for your projects, please refer this [Installing packages using pip and virtual environments](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/)

If I have missed something here please let me know ? Thank you!

**Comment by themetzmeier** [comment]
I had this same exact issue, and downgrading from Python 3.11 to Python 3.9 did the trick.

**Comment by gaikwadrahul8** [comment]
Hi, @vovarudykk 

I have tried to import Tensorflow.Js like  `import tensorflowjs as tfjs` after installing  with `Python 3.9` environment and it's working as expected but it's throwing an error with `Python 3.11 ` and our relavant is working on this issue and will get fixed as soon as possible.

If your issue got resolved with `Python 3.9` please feel free to close this issue. Thank you for your understanding and patience.

```
(tfjs-convert-3.9) C:\Users\gaikwadrahul>python
Python 3.9.18 (main, Dec 19 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflowjs as tfjs
>>> tfjs.__version__
'3.21.0'
>>> exit()
```

**Comment by vovarudykk** [comment]
Yes, sorry for my silence. Changing the Python version to 3.9 solved the problem.

**Comment by Shabhareash** [comment]
please for the love of god please drop this tensorflow module , because you cannot keep up with the sheer amount of errors and terror that one must face when one wants to use your module either drop this or give it to some capable hands .
