### ISSUE TITLE
WeChat mini game console: WebGLTexture is not defined

### ISSUE THREAD

**Issue by wangtz** [tensorflow/tfjs#802]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.2
#### Browser version
wechat mini game developer console
#### Describe the problem or feature request
tf13.js:3164 Uncaught (in promise) ReferenceError: WebGLTexture is not defined
    at e.<anonymous> (tf13.js:3164)
    at tf13.js:80
    at Object.next (tf13.js:86)
    at i (tf13.js:38)
    at <anonymous>
#### Code to reproduce the bug / link to feature request
Code can be narrowed down to this line:

s = i instanceof WebGLTexture ? this.getValuesFromTexture(e) : this.gpgpu.downloadFloat32MatrixFromBuffer(i, a[0], a[1])

I wonder if this is only a limitation on wechat mini game console or it also applies to other browsers - does WebGLTexture always exist? If not we probably need to check if it exists first. Something like 
typeof WebGLTexture == "undefined" ?

**Comment by nsthorat** [comment]
We have an official tfjs-wechat repo here: https://github.com/tensorflow/tfjs-wechat
