### ISSUE TITLE
group1-shard1of2.bin file resource size is too large

### ISSUE THREAD

**Issue by September-9** [tensorflow/tfjs#8026]
group1-shard1of2.bin file resource size is too large，about4.2M，Causing the model to load too slowly，Please optimize this issue。
here is my code:
```
var modelUrl ='https://migugame.cmgame.com/banner/prod/tvdraw/miniCode/tfjs-model_movenet_singlepose/model.json' ;

detectorConfig = {
  modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
  modelUrl: modelUrl,
};
	
poseDetection
  .createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)
  .then((detector)=>{
     // wx.hideLoading()
    resolve();
  })
  .catch((err)=>{
    reject(err);
  });
});
```

**Comment by mattsoulanille** [comment]
It's possible that the model is just this large. If you're converting it yourself, you can try quantizing it (run `tensorflowjs_converter --help` for details). Alternatively, you can [cache the model](https://js.tensorflow.org/api/latest/#tf.GraphModel.save) in the user's browser cache using one of the save handlers. For example `model.save('indexeddb://your_model')`.
