### ISSUE TITLE
[Codelab]: TensorFlowJS Make a smart webcam in JavaScript with a pre-trained ML model

### ISSUE THREAD

**Issue by yadak2019** [tensorflow/tfjs#8039]
model is not defined

**Comment by gaikwadrahul8** [comment]
Hi, @yadak2019 

I apologize for the delayed response and I believe you're referring this Codelab [example](https://codelabs.developers.google.com/codelabs/tensorflowjs-object-detection?hl=en#0) and cocoSsd is an external object loaded from our `index.html` script tag like below 

```
<!-- Load the coco-ssd model to use to recognize things in images -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd"></script>
```

I would suggest you to please refer this [Youtube playlist ](https://www.youtube.com/watch?v=TuYbgZ59Kpg&list=PLOU2XLYxmsILr3HQpqjLAUkIPa5EaZiui)  which may help you understand how things work



If I have missed something here please let me know. Thank you!
