### ISSUE TITLE
tf-backend-webgpu + face-landmarks-detection does not find anything

### ISSUE THREAD

**Issue by nico-martin** [tensorflow/tfjs#8058]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): https://uploads.nico.dev/tfjs/webgpu-test.html
- OS Platform and Distribution: Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js
- TensorFlow.js version (use command below): N/A
- Browser version: 
- - Chrome 119.0.6045.106
- - Chrome Canary 121.0.6114.0
- - Firefox Nightly 121.0a1 (2023-11-07)
- Tensorflow.js Converter Version: N/A

If I want to recognize faces with the "estimateFaces" method of the face-landmarks-detection@1.0.5 model, I get an empty array with the WebGPU backend (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu/dist/tf-backend-webgpu.js) and the expected result with the WebGL backend (https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl).

I have created a simple demo here to isolate the problem:  
https://uploads.nico.dev/tfjs/webgpu-test.html

My expectation would be that it returns the exact same result, but faster.

**Standalone code to reproduce the issue**  
view-source of https://uploads.nico.dev/tfjs/webgpu-test.html

**Other info**
I am sure this did work with Chrome 114 and or 113 when I tried it the first time last spring.

**Comment by Linchenn** [comment]
Just tried your demo, but I could get the same results from WebGL and WebGPU on my MacBookPro2019, chrome119.
<img width="970" alt="image" src="https://github.com/tensorflow/tfjs/assets/40653845/44e62317-2ad3-4766-8f62-bd9f2f3afcee">

**Comment by nico-martin** [comment]
Ok, that's interresting. So maybe it is just an issue on Windows?

**Comment by beaufortfrancois** [comment]
@nico-martin I've just tried on Chrome for macOS and Android and both work great. Can you file a bug at crbug.com/new and let me know so that I can ping the team to have a look.

**Comment by beaufortfrancois** [comment]
FYI When trying over remote on a Windows machine with the `--enable-unsafe-webgpu` flag, I get this error:

![image](https://github.com/tensorflow/tfjs/assets/634478/a0609ada-7ee4-4a41-b5ae-1221a23726a2)

**Comment by nico-martin** [comment]
> @nico-martin I've just tried on Chrome for macOS and Android and both work great. Can you file a Chromium bug at https://crbug.com/new and let me know so that I can ping the team to have a look.

Done: https://bugs.chromium.org/p/chromium/issues/detail?id=1500533

**Comment by nico-martin** [comment]
> FYI When trying over remote on a Windows machine with Chrome Canary running the `--enable-unsafe-webgpu` and `--ignore-gpu-blocklist` flags, I get this error:
> 
> ![image](https://user-images.githubusercontent.com/634478/281317486-a0609ada-7ee4-4a41-b5ae-1221a23726a2.png)

Stange. I tried the same flags but nothing changed. Still just an empty array.

**Comment by beaufortfrancois** [comment]
Do you see more when enabling TF.js debug mode?
https://www.geeksforgeeks.org/tensorflow-js-tf-enabledebugmode-function/

**Comment by nico-martin** [comment]
Great advice!
Just added the debug mode and now I see some errors
![image](https://github.com/tensorflow/tfjs/assets/8424136/4d60c830-93cf-44e1-a893-6fc59730bc22)

**Comment by beaufortfrancois** [comment]
I also see those errors on macOs when it works fine sadly.

**Comment by gaikwadrahul8** [comment]
Hi, @nico-martin 

Thank you for bringing this issue to our attention and I tried to run the same demo on my MacOS `Apple M1 Pro` system with  Google chrome version  `119.0.6045.105 (Official Build) (arm64)` and I got below results. Thank you!

`With WebGL :`

![image](https://github.com/tensorflow/tfjs/assets/115997457/fa33d41a-d7c4-4b0b-bfd6-95b3dcbe25ef)

`with WebGPU :`

![image](https://github.com/tensorflow/tfjs/assets/115997457/acb3cced-4f48-4fb5-86c7-5efa65401f1f)

**Comment by Linchenn** [comment]
@nico-martin I just traced your codes of the demo page, but I saw you imported both `tf.min.js` and `tfjs-backend-webgpu`.

Actually, these are duplicated and I guess this causes your problem, because we added `tfjs-backend-webgpu` into `tfjs.min.js` this year.

If you don't mind bundle size, import `tf.min.js` is enough and WebGL and WebGPU are ready to use. I would recommand you to remove the following two lines:
```html
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu/dist/tf-backend-webgpu.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
```

**Comment by nico-martin** [comment]
Ah, I did not know that.
I uploaded a version where I removed the scripts. WebGL still works, but WebGPU throws an error:
`Error: Backend name 'webgpu' not found in registry`

https://uploads.nico.dev/tfjs/webgpu-test-noimport.html

**Comment by Linchenn** [comment]
Sorry, my memory was wrong, only webgl is integrated with tfjs union package now. We have to add webgpu separately now:
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu/dist/tf-backend-webgpu.js"></script>
```

I still could not reproduce the empty array you mentioned. If not in debuging mode, did you see some warning messages? It would be nice to see your console logs.

**Comment by nico-martin** [comment]
Ok, heres the console without debugging:
![image](https://github.com/tensorflow/tfjs/assets/8424136/fca3b687-56f7-47a2-89b8-3cdf0a6026cf)

Acording to the discussion the the chromium issue it might be related to the GPU I have in my Dell Laptop.
https://bugs.chromium.org/p/chromium/issues/detail?id=1500533#c9

I was able to reproduce it on another windows device (same problem), but it worked on my old Lenovo laptop.
So it seems that only certain Intel GPUs are affected.

**Comment by beaufortfrancois** [comment]
@qjia7 may be able to help us with https://bugs.chromium.org/p/chromium/issues/detail?id=1500533#c9

**Comment by qjia7** [comment]
@nico-martin Can you try to add ` --enable-dawn-features=allow_unsafe_apis,use_dxc` flags when you launch the chrome browser? (Please make sure you have dxc.dll in your system. You can have it by installing windows sdk) On one of my Intel machine, If I add those flags, I can get correct result. However, If I remove those flags, I get empty `[]`. One know issue is that fxc on intel has bug. So some kernels can't get correct result. Currently we use dxc to test webgpu. And I assume webgpu will support dxc by default soon.

**Comment by nico-martin** [comment]
@qjia7, yes, using `--enable-dawn-features=use_dxc` does solve the problem for me. In that case I'll just wait for a driver update and use the flag if needed. Thank you so much!

**Comment by EliasVansteenkiste** [comment]
Will DXC become the default in dawn in the future?
Anyone have any idea if this will happen soon?

**Comment by gyagp** [comment]
DXC is now 50% (among all the Windows devices) in Chrome Stable (also other channels, including Beta, Dev and Canary). If the rolling out is smooth, it will most likely hit 100% early next year.

**Comment by nico-martin** [comment]
Chrome 121 now uses DXC as default:
https://developer.chrome.com/blog/new-in-webgpu-121?hl=de
And I just checked it in Canary and it seems that this solves my issue.
