### ISSUE TITLE
Issue with version 4.13.0 - doesn't build anymore in Docker

### ISSUE THREAD

**Issue by stx-chris** [tensorflow/tfjs#8068]
**System information**
`@tensorflow/tfjs-node, Version 4.13.0`

**Describe the current behavior**
Using this package locally (on Mac) and in Docker. Up to version `4.12.0`, the package built fine using `yarn`. Starting with `4.13.0`, the yarn build process running in Docker will return a build error. We are using `node:18-slim` image.

**Describe the expected behavior**
Successful build, as up to `4.12.0`. Also successful build with `4.13.0` on local MacOS 14.2.

**Other info / logs** 
Log entry in Docker build on Google Cloud Platform:
`Step #2: ➤ YN0009: │ @tensorflow/tfjs-node@npm:4.13.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-be3caaee/build.log)`

Unfortunately, the log is inaccessible.

Is it possible that some package in `4.13.0` has been upgraded that requires another library not present in the `node:18-slim` Docker image?

**Comment by gaikwadrahul8** [comment]
Hi, @stx-chris 

Thank you for bringing this issue to our attention, if possible could you please help me with your Github repo/ code with steps to replicate the same behavior from my end which will help to us to investigate this issue further quickly ?

Thank you for your cooperation.

**Comment by stx-chris** [comment]
Sure. Further analysis showed that as of this release, `python3` is required in the Docker image since it runs `node-gyp` during build. 

Our workaround right now is switch to from the `node:18-slim` image to the `node:18-alpine` image and add python to the `Dockerfile`:

`RUN apk add make gcc g++ python3`

Then, `tfjs-node` will build successfully. This issue seems to be related to #8064.




Minimalistic `Dockerfile` to reproduce this issue:
```
FROM node:18-slim

COPY package.json .

RUN yarn 
```

Minimalistic `package.json` to reproduce this issue:
```
{
  "name": "tfjs-test",
  "version": "1.0.0",
  "main": "index.js",
  "author": "stx-chris",
  "license": "MIT",
  "dependencies": {
    "@tensorflow/tfjs-node": "4.13.0"
  }

**Comment by stx-chris** [comment]
Actually, I've updated the comment since we had to stick with node:18-slim regardless.

Even there, node-gyp was not required until 4.13.0. Now we added the required libs to the image, which resolves this issue for us. But it should be documented that node-gyp is now required to properly build.

**Comment by gaikwadrahul8** [comment]
Hi, @stx-chris 

Thank you for your observation and findings, I really appreciate your efforts and valuable time on this issue and definitely we'll update our official documentation our team is working on it to update outdated official documentation w.r.t` tfjs-node` 

Do you want to keep this issue open ? if not, please feel free to close this issue if your issue got resolved. 

Thank you for your understanding and patience.
