### ISSUE TITLE
I can't use model by convert with tensorflowjs_converter 

### ISSUE THREAD

**Issue by GangDevp** [tensorflow/tfjs#807]
#### I convert my model with tensorflowjs_converter  command.Tensorflowjs throw the error 'SyntaxError: Unexpected token < in JSON at position 0' when I load my model.
My convert command is 'tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='mobilenet_v1/Bottleneck/BatchNorm/batchnorm/add_1' --saved_model_tags=serve ./output_mb.pb ./web_model', and convert success.

#### My code

mobilent.js
`import * as tf from '@tensorflow/tfjs';
const MODEL_FILE_URL = '../jsmodel/webmodel/tensorflowjs_model.pb';
const WEIGHT_MANIFEST_FILE_URL = '../jsmodel/webmodel/weights_manifest.json';
const INPUT_NODE_NAME = 'ToFloat';
const OUTPUT_NODE_NAME = 'mobileNet_v1/Bottleneck/BatchNorm/batchnorm/add_1';

export class MobileNet {
  constructor() { }

  async load() {
    this.model = await tf.loadFrozenModel(MODEL_FILE_URL, WEIGHT_MANIFEST_FILE_URL);
  }

  dispose() {
    if (this.model) {
      this.model.dispose();
    }
  }
  predict(input) {
    return this.model.execute(
      { [INPUT_NODE_NAME]: input.asType('float32') }, OUTPUT_NODE_NAME);
  }
};`

index.js

`import * as tf from '@tensorflow/tfjs';
import {MobileNet} from './mobilenet.1';
import imageURL from './cat.jpg';

const cat = document.getElementById('cat');
cat.onload = async () => {
  const resultElement = document.getElementById('result');

  resultElement.innerText = 'Loading MobileNet...';

  const mobileNet = new MobileNet();
  console.time('Loading of model');
  await mobileNet.load();
  console.timeEnd('Loading of model');

  const pixels = tf.fromPixels(cat);
  console.log(pixels)

  console.time('First prediction');
  let result = mobileNet.predict(pixels);
  const topK = mobileNet.getTopKClasses(result, 5);
  console.timeEnd('First prediction');

  resultElement.innerText = '';
  topK.forEach(x => {
    resultElement.innerText += `${x.value.toFixed(3)}: ${x.label}\n`;
  });

  console.time('Subsequent predictions');
  result = mobileNet.predict(pixels);
  mobileNet.getTopKClasses(result, 5);
  console.timeEnd('Subsequent predictions');

  mobileNet.dispose();
};
cat.src = imageURL;
`

**Comment by caisq** [comment]
You wrote

> SyntaxError: Unexpected token < in JSON at position 0' when I load my model.

Can you make sure that the corresponding HTTP request has a response status of 200 (OK)?

**Comment by caisq** [comment]
@GangDevp If the response is 200, then what is body of the response? Can you confirm it is a valid JSON?

**Comment by GangDevp** [comment]
@ allenwangcheng  I have voiddate JSON data and it's right.

**Comment by caisq** [comment]
@GangDevp I saw you closed this issue. Is it because you somehow resolved the issue?
