### ISSUE TITLE
Loading local model.json and weight file not working with Expo project

### ISSUE THREAD

**Issue by DylanTet** [tensorflow/tfjs#8079]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 15
- TensorFlow.js installed from (npm or script link): `yarn add tensorflow/tfjs`
- TensorFlow.js version: `@tensorflow/tfjs": "^4.13.0`

The issue that I am currently facing is I am trying to utilize local model.json / weight.bin files within my React Native project that is currently managed with Expo. I had read that the bundleResourceIO() function doesnt work with Expo projects due to it utilizing RNFS, so I had written my custom bundler using expo file system below:
    
    const modelJSON = require('./model-assets/model.json');
    const modelWeights = require('./model-assets/group1-shard1of1.bin');

    class customIOHandler implements io.IOHandler {
        constructor(
            protected readonly modelJson: io.ModelJSON,
            protected readonly modelWeightsId: Array<string|number>) {
                if (modelJson == null || modelWeightsId == null) {
                    throw new Error(
                        'Must pass the model json object and the model weights path.'
                    );
                }
            }
    
    async load() : Promise<io.ModelArtifacts> {
        const weightAssets = this.modelWeightsId.map(id => Asset.fromModule(id));
        if (weightAssets[0].uri.match('^http')) {
            // In debug/dev mode RN will serve these assets over HTTP
            return this.loadViaHttp(weightAssets);
          } else {
            // In release mode the assets will be on the file system.
            return this.loadLocalAsset(weightAssets);
          }
    }

    async loadViaHttp(weights: Asset[]) : Promise<io.ModelArtifacts> {
        const modelJson = this.modelJson;
        const modelArtifacts: io.ModelArtifacts = Object.assign({}, modelJson);
        modelArtifacts.weightSpecs = modelJson.weightsManifest[0].weights;
        //@ts-ignore
        delete modelArtifacts.weightManifest;

        // Load the weights
        const weightsDataArray =
            await Promise.all(weights.map(async (weightAsset) => {
                const url = weightAsset.uri.split('?')[0];
                const requestInit: undefined = undefined;
                const response = await fetch(url, requestInit);
                const weightData = await response.arrayBuffer();
                return weightData;
            }));

        modelArtifacts.weightData = io.CompositeArrayBuffer.join(weightsDataArray);
        return modelArtifacts;
    }

    loadLocalAsset = async (weights : Asset[]) : Promise<io.ModelArtifacts> => {
        const modelJson = this.modelJson;
        const modelArtifacts: io.ModelArtifacts = Object.assign({}, modelJson);
        modelArtifacts.weightSpecs = modelJson.weightsManifest[0].weights;
        //@ts-ignore
        delete modelArtifacts.weightManifest;
    
        const weightsArray = await Promise.all(weights.map(async (weightAssets) => {
            let base64Weights: string;
            if (Platform.OS === 'android') {
                // On android we get a resource id instead of a regular path. We
                // need to load the weights from the res/raw folder using this id.
                const fileName = `${weightAssets.uri}.${weightAssets.type}`;
                try {
                  const returnedBase64Weights = await FileSystem.readAsStringAsync(fileName)
                  base64Weights = returnedBase64Weights[0];
                } catch (e) {
                  throw new Error(
                      `Error reading resource ${fileName}. Make sure the file is
                in located in the res/raw folder of the bundle`,
                  );
                }
            } else {
                try {
                  const returnedBase64Weights = await FileSystem.readAsStringAsync('./model-assets/group1-shard1of1.bin', { encoding: FileSystem.EncodingType.Base64 })
                  base64Weights = returnedBase64Weights;
                } catch (e) {
                  throw new Error(
                      `Error reading resource ${weightAssets.uri.split('?')[0]}.`,
                  );
                }
            }
            const weightData = util.encodeString(base64Weights, 'base64').buffer;
            return weightData;
        }));
    
        modelArtifacts.weightData = io.CompositeArrayBuffer.join(weightsArray);
        console.log(modelArtifacts);
        return modelArtifacts;
        }
    }

      const customBundleResourceIO = (modelJson: io.ModelJSON, modelWeightsId: number|number[]): io.IOHandler => {
          const modelWeightsIdArr = Array.isArray(modelWeightsId) ? modelWeightsId : [modelWeightsId];
          return new customIOHandler(modelJson, modelWeightsIdArr);
      }
      
      const loadModel = async () : Promise<void | tf.LayersModel> => {
          try {
              const model = await tf.loadLayersModel(customBundleResourceIO(modelJSON, modelWeights))
              return model;
          } catch(err) {
              console.log("There was an error loading the model", err);
          }
      }
However, it still seems to not work correctly when i try and load the model with `tf.loadLayersModel(customBundleRecource(modelJSON, modelWeights))` because it get the error `TypeError: Cannot convert undefined value to object` so that tells me that the IOHandler that is returned is undefined for some reason still. Has anyone faced this before? Here below is my metro.config file:

    // Learn more https://docs.expo.io/guides/customizing-metro
    const { getDefaultConfig } = require('expo/metro-config');
    
    const config = getDefaultConfig(__dirname);
    config.resolver.assetExts.push('bin');
    config.resolver.sourceExts.push('json');
    
    module.exports = config;

At this point I cant figure out what it could be and have pretty much tried everything to get this model working locally so the users dont need to have internet connection or detach from the expo project, but not sure if thats possible at this point?

**Comment by sameert89** [comment]
`bundleResourceIO` does work, you have to configure the metro config properly to support bin weights, here is an example:
```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig(__dirname);
  const { assetExts } = defaultConfig.resolver;
  return {
    resolver: {
      // Add bin to assetExts
      assetExts: [...assetExts, "bin"],
    },
    transformer: {
      // Enable inlineRequires
      inlineRequires: true,
    },
  };
})();

```

**Comment by gaikwadrahul8** [comment]
Hi, @DylanTet 

I apologize for the delay in responding. I kindly request you to refer to the workaround suggested by @sameert89. Could you please confirm whether that workaround addresses your issue? If not, I would recommend attempting to resolve the problem by downgrading the version of Expo and its associated dependencies. 

If issue still persists please help us with Github repo and complete steps to replicate the same issue from our end to investigate this issue further with model in zip file

Thank you for your understanding and cooperation.

**Comment by ZainabAlawneh** [comment]
still i am facing the same issue?
any advice please!

**Comment by devrayat000** [comment]
@DylanTet the issue here is with `expo-assets` package and how it handles bundled assets.

In my case, whenever I had `expo-updates` installed in my dependencies, I was getting this error. Seems like when `expo-updates` is installed, the `asset.uri` is undefined, but there is a `localUri` of the asset available. So, I changed the line to:
`tsx
// On android we get a resource id instead of a regular path. We
// need to load the weights from the res/raw folder using this id.
const fileName = weightAssets.uri ? `${weightAssets.uri}.${weightAssets.type}` : weightAssets.localUri;
`

This solved the bug for me. #
