### ISSUE TITLE
tfjs-node works, tfjs-node-gpu fails with: Resource exhausted: OOM when allocating tensor with shape[2048]

### ISSUE THREAD

**Issue by iacovlev-pavel** [tensorflow/tfjs#808]
#### TensorFlow.js version
tfjs-node-gpu: 0.1.18

#### Browser version
NodeJS v8.12.0, Windows 10, CUDA 9

#### Describe the problem or feature request
I have code in python which blurs an image, it works on Windows in Python on GPU.
I am trying to do the same from node, I have successfully converted the script to`tfjs-node` and it works and produces exactly the same results.
When I try to run `tfjs-node-gpu` I go OOM, with the following error:
`Resource exhausted: OOM when allocating tensor with shape[2048] and type float`
[log.txt](https://github.com/tensorflow/tfjs/files/2494671/log.txt)

Command used to convert my model:
`Miniconda3\Scripts\tensorflowjs_converter.exe --input_format=tf_frozen_model --output_node_names="image_tensor,detection_boxes,detection_scores,detection_classes,num_detections" --saved_model_tags=serve frozen_inference_graph.pb web_model`

Weights: [weights_manifest.json.txt](https://github.com/tensorflow/tfjs/files/2494685/weights_manifest.json.txt)

Sample code in python: [sample.py.txt](https://github.com/tensorflow/tfjs/files/2494686/sample.py.txt)

Sample code in js: [sample.js.txt](https://github.com/tensorflow/tfjs/files/2494694/sample.js.txt)

What I have tried:
1. Tried with a very small input image, still failed.

Thoughts:
Could this be a tensorflowjs_converter problem, where it expects the model to be ran in the browser, and converts to more generic types like int32 to store the data where the original code in python uses uint8.

This is how I pass the image to the model: `tf.tensor4d(values, outShape, 'int32');`, as I understand there is no uint8 support ? also for some reason this operation takes ~40ms, is this expected ?

**Comment by iacovlev-pavel** [comment]
Thank you for the reply.
Deleted node_modules folder, bumped the version in package.json, `npm install`.
Ran the test again still got the error:
```
Message: OOM when allocating tensor with shape[2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
    at NodeJSKernelBackend.executeMultipleOutputs (sblur\node_modules\@tensorflow\tfjs-node-gpu\dist\nodejs_kernel_backend.js:109:43)
    at NodeJSKernelBackend.batchNormalization (jsblur\node_modules\@tensorflow\tfjs-node-gpu\dist\nodejs_kernel_backend.js:866:21)
    at environment_1.ENV.engine.runKernel.$x (sblur\node_modules\@tensorflow\tfjs-core\dist\ops\batchnorm.js:194:86)
    at jsblur\node_modules\@tensorflow\tfjs-core\dist\engine.js:123:26
    at Engine.scopedRun (jsblur\node_modules\@tensorflow\tfjs-core\dist\engine.js:101:23)
    at Engine.runKernel (jsblur\node_modules\@tensorflow\tfjs-core\dist\engine.js:121:14)
    at batchNormalization_ (jsblur\node_modules\@tensorflow\tfjs-core\dist\ops\batchnorm.js:194:40)
    at Object.batchNormalization (jsblur\node_modules\@tensorflow\tfjs-core\dist\ops\operation.js:23:29)
    at Object.exports.executeOp (jsblur\node_modules\@tensorflow\tfjs-converter\dist\src\operations\executors\normalization_executor.js:8:25)
    at Object.executeOp (jsblur\node_modules\@tensorflow\tfjs-converter\dist\src\operations\operation_executor.js:43:34)
```
Can attach the entire log if needed.

**Comment by DavidGOrtega** [comment]
@iacovlev-pavel 
It's funny, I'm having the same issue. My first guess was that I'm running it in 32bits, having the 4GB memory limitation. I saw the task manager and effectively my node was handled by a 32bits console.

I have to try it in 64 bits to confirm this

**Comment by nkreeger** [comment]
@pyu10055 for reference. There is a converter patch coming that might help here: https://github.com/tensorflow/tfjs-converter/pull/216

Do you know how large your model is?

**Comment by nkreeger** [comment]
Also - can you provide more device information (Win10 right?) which NVIDIA card/CUDA/etc.

**Comment by iacovlev-pavel** [comment]
@nkreeger 
1. Windows 10
2. NVIDIA GTX 960M, 4GB VRAM
3. CUDA 9.0
4. CUDNN 7.3.1.20

frozen_inference_graph.pb - 181 MB (converted model is the same size but split in chunks).

NVIDIA GTX 1080 is available, can try on it Tomorrow.

**Comment by iacovlev-pavel** [comment]
Tried with a NVIDIA GTX 1080 8GB, it works, no OOM errors with `tfjs-node-gpu`.
``` 
localhost/replica:0/task:0/device:GPU:0 with 6363 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
```

On NVIDIA GTX 960M with 4GB
Python: Works
tfjs-node-gpu: Fails, OOM.

P.S. Is it possible to load the Tensorflow `frozen_inference_graph.pb` directly and avoid `tfjs-converter` ?

**Comment by iacovlev-pavel** [comment]
Tested with a NVIDIA GTX 1080 8GB, all works as expected, no OOM error with `tfjs-node-gpu`.

On NVIDIA GTX 960M 4GB:
Tensorflow Python: works.
tfjs-node-gpu: fails.

**Comment by nkreeger** [comment]
Are you using Python with eager mode on?

**Comment by iacovlev-pavel** [comment]
@nkreeger I don't.

The model which I am running is `faster_rcnn_resnet101`, I have tried `ssd_mobilenet_v2` and it seems that it does not have the memory issue.
Could it be that `tfjs-converter` does not efficiently convert some of the kernels or something among this line ?

**Comment by nkreeger** [comment]
We use TensorFlow's eager API for all execution (inference and training). It's possible that eager mode is not working well with certain GPUs. Non-eager (graph) mode builds a graph and can re-use Tensors. However, eager mode is easier to use but a cost of performance (each output must be re-alloc'd). 

We do have one memory fix coming in the converter - https://github.com/tensorflow/tfjs-converter/pull/214

**Comment by hypersolution1** [comment]
I'm running into the same issue. I'm running a frozen model for inference on a video stream. It works for about 2 minutes then I get a crash. It seems always to be after a period of time regardless of the inputs. The inference graph processes around 15 images per seconds.

Here is a relevent part (I hope) of my error:
```
Stats: 
Limit:                  7380579124
InUse:                  7380574720
MaxInUse:               7380574720
NumAllocs:                  856032
MaxAllocSize:            280559616
2018-10-28 14:32:12.367844: W tensorflow/core/common_runtime/bfc_allocator.cc:275] ****************************************************************************************************
2018-10-28 14:32:12.367860: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[1,187,103,4] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

```

It works with tfjs-node instead of tfjs-node-gpu. 

I'm using a GeForce GTX 1070

**Comment by nkreeger** [comment]
I'll take a look at what's going on here this week.

**Comment by iacovlev-pavel** [comment]
I no longer get this error using the latest version @tensorflow/tfjs-node-gpu: 0.1.21
