### ISSUE TITLE
MoveNet does not flip horizontal when the `flipHorizontal` option is `true`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [tensorflow/tfjs#8093]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora Silverblue 38
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.6.0
- Browser version: Firefox 120.0
- Tensorflow.js Converter Version: 4.6.0

**Describe the current behavior**
When I do
```js
const poses = await detector.estimatePoses(video, { flipHorizontal: true })
```
with a BlazePose detector, it flips the poses as expected. When I create a MoveNet detector, it doesn't flip the poses. 

**Describe the expected behavior**
### If MoveNet is supposed to flip poses
Then actually add pose-flipping code

### If MoveNet isn't actually supposed to flip poses
Then remove `flipHorizontal` from the TypeScript type for the MoveNet estimation config.

**Standalone code to reproduce the issue**
This isn't exactly a _minimum_ example, but it does show how the bug is specific to MoveNet and not BlazePose:
BlazePose (works): https://github.com/ChocolateLoverRaj/raise-hand-ai/tree/pose-nav
MoveNet (bug): https://github.com/ChocolateLoverRaj/raise-hand-ai/tree/pose-nav-move-net

**Other info / logs** Include any logs or source code that would be helpful to
Looks like all estimation config is just ignored by MoveNet: https://github.com/tensorflow/tfjs-models/blob/07ef0e7d5eb46e9414c94476e2e4eddfc5147ee0/pose-detection/src/movenet/detector.ts#L248

**Comment by shmishra99** [comment]
Appreciate you highlighting this. Both `BlazePose` and `MoveNet` utilize the `EstimationConfig` interface within `tfjs-models/pose-detection/src/types.ts`. 
While both models share the `EstimationConfig` interface, `MoveNet` currently bypasses its usage as per [comment](https://github.com/tensorflow/tfjs-models/blob/07ef0e7d5eb46e9414c94476e2e4eddfc5147ee0/pose-detection/src/movenet/detector.ts#L238).

**Comment by ChocolateLoverRaj** [comment]
You did not miss anything

**Comment by gaikwadrahul8** [comment]
Hi, @ChocolateLoverRaj 

As per this comment `@param config Optional. Currently not used. ` in this [file](https://github.com/tensorflow/tfjs-models/blob/07ef0e7d5eb46e9414c94476e2e4eddfc5147ee0/pose-detection/src/movenet/detector.ts#L238) at the moment `movenet` model is not using configuration options like `blazepose` model so to confirm, is it mandatory to use `flipHorizontal` option is `true`, if so then this issue will be considered as feature request and if you've workaround to use configuration options with `movenet` model PR will be welcomed from your end and our team will review your PR and will take appropriate action from their end. 

Thank you for understanding and patience.
