### ISSUE TITLE
Error compiling fragment shader in react native with tensorflowJs

### ISSUE THREAD

**Issue by Shure1** [tensorflow/tfjs#8095]
**I made a class whose objective is to predict the type of plant along with its disease, both models have the same structure and the first prediction on the type of plant I have no problems, the error that I still do not know what is due is when I do the predict of the second model (the disease of the plant)**

`async processImage(image, setPrediction) {
    try {
      if (!this.plantModel) {
        console.error("Model not loaded desde processImage");
        return;
      }

      const resizedUri = await this.resizePhoto(image, [128, 128]);

      const imgB64 = await FileSystem.readAsStringAsync(resizedUri, {
        encoding: FileSystem.EncodingType.Base64,
      });

      const imgBuffer = tf.util.encodeString(imgB64, "base64").buffer;
      const raw = new Uint8Array(imgBuffer);
      const imgTensor = decodeJpeg(raw);
      /* const imgTensor = tf.tensor3d(raw, [128, 128, 3], "float32").div(255.0); */
      const normalizedTensor = imgTensor.toFloat().div(tf.scalar(255));

      const processedTensor = tf.image.resizeBilinear(
        normalizedTensor,
        [128, 128]
      );
      const expandedTensor = tf.expandDims(processedTensor, 0);
      console.log(expandedTensor);
      const prediction = await this.plantModel.predict(expandedTensor);
      const resultArray = await prediction.array();

      const predictedClassIndex = tf.argMax(resultArray[0]).dataSync()[0];
      const predictedClass = this.classNames[predictedClassIndex];
      /* const predictedClass = this.enfermedades[0].Apple[predictedClassIndex]; */
      const confidence = resultArray[0][predictedClassIndex];
      setPrediction(predictedClass);

      console.log(
        `la clase predicha es ${predictedClass}, con una confianza de ${confidence}`
      );

      // Carga y predicción del modelo de enfermedad correspondiente

      await this.loadDiseaseModel(predictedClass);
      console.log(expandedTensor);

      // Predicción de la enfermedad
      const diseasePrediction = await this.modelEnfermedad.predict(
        expandedTensor
      );
      console.log(diseasePrediction);
      const diseaseResultArray = await diseasePrediction.array();
      console.log(diseaseResultArray);

      tf.dispose([
        imgTensor,
        normalizedTensor,
        processedTensor,
        expandedTensor,
        prediction,
      ]);

      /* setTimeout(() => {
        navigation.navigate("Plant");
      }, 3000); */
    } catch (error) {
      console.error("Error en la prediccion:", error);
    }
  }`

what I get on console is

Modelo de plantas cargado
 LOG  {"dataId": {"id": 118}, "dtype": "float32", "id": 118, "isDisposedInternal": false, "kept": false, "rankType": "4", "scopeId": 5, "shape": [1, 128, 128, 3], "size": 49152, "strides": [49152, 384, 3]}
 LOG  la clase predicha es Apple, con una confianza de 0.96142578125
 LOG  Predicted Class: Apple
 LOG  modelo de enfermedades de  Apple cargado
 LOG  {"dataId": {"id": 118}, "dtype": "float32", "id": 118, "isDisposedInternal": false, "kept": false, "rankType": "4", "scopeId": 5, "shape": [1, 128, 128, 3], "size": 49152, "strides": [49152, 384, 3]}

 LOG  ERROR: 0:133: '' : syntax error: ERROR___INTEGER_CONST_OVERFLOW
 LOG   133        int b = index / 62340447705453330;
 LOG  134        index -= b * 62340447705453330;
135
136        int r = 2 * (index / -55721349);
137        int c = imod(index, -55721349) * 2;
138
139        return ivec4(b2, b, r, c);
140      }
141
14
 ERROR  Error en la prediccion: [Error: Failed to compile fragment shader.]

**Comment by shmishra99** [comment]
Hi @Shure1 , 

Please provide the reproducible code and `Node modules` used. 

The error message indicates that your code is consuming too much memory. Here are some ways to address this:

1. Make sure you explicitly call `tf.dispose()` to free up memory once tensors are no longer needed.
2. If you're working with large images, consider resizing them to a smaller size to reduce memory consumption.
3. Set the CPU as a backend mentioned in the [SO](https://stackoverflow.com/questions/72565384/uncaught-in-promise-error-failed-to-compile-fragment-shader) thread.

If I have missed something here please let me know ? Thank You !!

**Comment by Shure1** [comment]
hi @shmishra99 here I give you all the information you need, it is the code of the class, I am developing the project with expo, I will try to apply your advice, thanks for your time.


repository: [https://github.com/Shure1/Tesis/blob/main/src/controllers/prediction.js](url)

dependences:

  "dependencies": {
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@tensorflow/tfjs": "^4.13.0",
    "@tensorflow/tfjs-converter": "^4.13.0",
    "@tensorflow/tfjs-react-native": "0.8.0",
    "@tensorflow/tfjs-tflite": "^0.0.1-alpha.10",
    "expo": "~49.0.8",
    "expo-camera": "~13.4.2",
    "expo-file-system": "~15.4.3",
    "expo-gl": "~13.0.1",
    "expo-gl-cpp": "^11.4.0",
    "expo-image-manipulator": "~11.3.0",
    "expo-image-picker": "~14.3.2",
    "expo-sqlite": "~11.3.3",
    "expo-status-bar": "~1.6.0",
    "jpeg-js": "^0.4.4",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "2.12.0",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "~3.22.0",
    "tflite-react-native": "^0.0.5"
  },

**Comment by Shure1** [comment]
@shmishra99 I followed the advice you gave me and the truth is that it no longer prints the error in the console about the shader, but now it prints the following error

 ERROR  error en la prediccion [RangeError: A negative value cannot be an index]
 
 
 I leave you the link to the repository where the class is hosted. `https://github.com/Shure1/Tesis/blob/main/src/controllers/prediction.js`

**Comment by gaikwadrahul8** [comment]
Hi, @Shure1 

I apologize for the delayed response and thank you for sharing your repository with us. Could you please help/guide me with complete steps to replicate the same behavior from my end that would help us to investigate this issue further and if possible resolve it as soon as possible ? Thank you for your understanding and patience.
