### ISSUE TITLE
Editable Documentation

### ISSUE THREAD

**Issue by nbardy** [tensorflow/tfjs#81]
The live examples in the documentation are great, it would be better if they're editable. I've done a little bit of this type of work before. I haven't had a look at how the build tools are set up for the code examples yet, but I assuming this wouldn't be too tall of a task.

**Comment by tafsiri** [comment]
I think this is definitely on our list! We didn't get to it before the launch day, but certainly something we have in mind.

**Comment by mimiohlt** [comment]
this is good
