### ISSUE TITLE
yarn add  @tensorflow/tfjs-node  error

### ISSUE THREAD

**Issue by pjocepwf** [tensorflow/tfjs#8104]
yarn add @tensorflow/tfjs-node error as follow:

 How can a Win11 computer be successfully installed?

PS E:\Dev\tensorflow_study> yarn add @tensorflow/tfjs-node
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@tensorflow/tfjs-node > @tensorflow/tfjs > @tensorflow/tfjs-data@4.15.0" has unmet peer dependency "seedrandom@^3.0.5".
[4/4] Building fresh packages...
[2/2] ⠐ @tensorflow/tfjs-node
error E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node
Output:
CPU-windows-4.15.0.zip
* Downloading libtensorflow
https://cdn.npmmirror.com/binaries/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip

* Building TensorFlow Node.js bindings
symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
  * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile 'E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll' -> 'E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: 'E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\deps\\lib\\tensorflow.dll',
  dest: 'E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v9\\tensorflow.dll'
}

Node.js v20.9.0

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
}

**Comment by gaikwadrahul8** [comment]
Hi, @pjocepwf 

Thank you for brining this issue to our attention and I'm able to install `tfjs-node` on my `windows 10 `system by following the instructions mentioned in my https://github.com/tensorflow/tfjs/issues/8081#issuecomment-1827814656 with these Node.js versions `Node.js v19.9.0` and `Node.js v18.16.1 `and at the moment it's not working as expected with `Node.js version v20.10.0 or later` and some `old Node.js` versions and our relevant team is working on this issue to fix it as soon as possible from their end.

You should able to install `tfjs-node` on your `windows` system with Node.js versions either `Node.js v19.9.0 `or `Node.js v18.16.1` so please give it try from your end, if you face any issue while installing `tfjs-node `after following above mentioned instructions with mentioned Node.js versions please feel free to reach out to us with your new error log and would be glad to help you further

Thank you for your understanding and patience.

1. With `Node.js v19.9.0` :

```
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> node -v
v19.9.0
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> npm -v
9.6.3
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> pyenv which python
C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> npm install -g node-gyp --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe”   

changed 99 packages in 6s
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> npm install --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe" @tensorflow/tfjs-node

changed 10 packages, and audited 120 packages in 51s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node19-py-3.10> 
```

2. with `Node.js v18.16.1 `:

```
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> node --version
v18.16.1
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> npm --version
9.8.0
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> pyenv which python
C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> npm install -g node-gyp --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe"   

changed 99 packages in 12s

14 packages are looking for funding
  run `npm fund` for details
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> npm install --python="C:\Users\gaikwadrahul\.pyenv\pyenv-win\versions\3.10.9\python.exe" @tensorflow/tfjs-node

added 121 packages, and audited 122 packages in 3m

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> node .\index.js
2023-11-30 15:04:31.614170: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1 / 3
eta=0.0 ==================================================================================> 
29686ms 2969us/step - MAE=0.332 loss=0.168 val_MAE=0.293 val_loss=0.126 
Epoch 2 / 3
eta=0.0 ==================================================================================>
9458ms 946us/step - MAE=0.279 loss=0.113 val_MAE=0.271 val_loss=0.106 
Epoch 3 / 3
eta=0.0 ==================================================================================> 
11791ms 1179us/step - MAE=0.258 loss=0.0940 val_MAE=0.275 val_loss=0.110 
PS C:\Users\gaikwadrahul\Desktop\tfjs-node-testing-for-doc\tfjs-node-3.10> 
```

**Comment by pjocepwf** [comment]
Replacing node with 19.9 still reports an error

PS E:\Dev\tensorflow_study> yarn add @tensorflow/tfjs-node
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@tensorflow/tfjs-node > @tensorflow/tfjs > @tensorflow/tfjs-data@4.15.0" has unmet peer dependency "seedrandom@^3.0.5".
[4/4] Building fresh packages...
[2/2] ⠄ @tensorflow/tfjs-node
error E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node
Output:
CPU-windows-4.15.0.zip
* Downloading libtensorflow
https://cdn.npmmirror.com/binaries/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip

* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@19.9.0 | win32 | x64
node-pre-gyp info check checked for "E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.15.0/CPU-windows-4.15.0.zip
node-pre-gyp ERR! install request to https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.15.0/CPU-windows-4.15.0.zip failed, reason: read ECONNRESET
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.15.0 and node@19.9.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error request to https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.15.0/CPU-windows-4.15.0.zip failed, reason: read ECONNRESET
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@19.9.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@19.9.0 | win32 | x64
gyp info find Python using Python version 3.12.1 found at "C:\Program Files\Python312\python.exe"
gyp info find VS using VS2022 (17.6.33723.286) found at:
gyp info find VS "d:\Program Files\Microsoft Visual Studio\2022\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python312\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Local\\node-gyp\\Cache\\19.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Admin\\AppData\\Local\\node-gyp\\Cache\\19.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\19.9.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
    import gyp.input
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=E:\\Dev\\tensorflow_study\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp ERR! cwd E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v19.9.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node\lib\napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Dev\tensorflow_study\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Windows_NT 10.0.22631
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Dev\\tensorflow_study\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\Dev\tensorflow_study\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v19.9.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok

**Comment by gaikwadrahul8** [comment]
Hi, @pjocepwf 

I see in your above error log you're using `Python 3.12 `version so please give it try with either `Python 3.10` or `Python 3.11 `and it should work with `Node.js v19.9.0`. 

If you face any issue please let us know with new error log to investigate your issue further. Thank you for your understanding and patience.

**Comment by Master-Tech271** [comment]
@gaikwadrahul8 Thanks for your valuable response but there is misunderstanding @pjocepwf mention the issues for the windows 11 and also I'm facing same issues.

**Comment by gaikwadrahul8** [comment]
Hi, @Master-Tech271 

I have tested above mentioned workaround on my `Windows 10` system with Node.js `v18.16.1` and `v19.9.0` with `Python 3.10.9` and it's working as expected as I added output log in my previous [comment](https://github.com/tensorflow/tfjs/issues/8104#issuecomment-1868314351)

If you tried with either Node.js `v18.16.1` or `v19.9.0` with either `Python 3.10.9` or `Python 3.11.6` on `Windows 11` system and still you're facing the same issue please feel free to create new issue with your error log so it will help us to track tfjs-node installation issues on `Windows 11` system.

Hi, @pjocepwf Could you please confirm, is it working with either Node.js `v18.16.1` or `v19.9.0` with `Python 3.10.9` on your `Windows 11` system ?

Thank you for your understanding and patience.

**Comment by Master-Tech271** [comment]
Hello, I resolved these issues on Windows 11 by following these steps to help someone.

Node Version -: 19.9.0
Npm Version -: 9.6.3
Python Version -: 3.11 (make sure environment path is set)
OS -: Windows 11

Step 1-: npm install -g node-gyp
Step 2-: Download the [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) and select the Desktop development C++ (no need to change any other setting keep it default)
![image](https://github.com/tensorflow/tfjs/assets/61062186/725f92e2-1587-4e2b-b1c3-196ac1ea1e3e)

Step 3 -: node-gyp configure --msvs_version=2022 (run this command)
Step 4-: set npm_config_python="C:\path\to\python.exe" (i'm using python 3.11.0)
Step 5-: go to your project path and try to install (npm install @tensorflow/tfjs-node)


I followed these steps and was able to resolve my issues. Thanks

**Comment by gaikwadrahul8** [comment]
Hi, @Master-Tech271 

Good to hear that you're able to install `tfjs-node` on your `Windows 11` system with `Python 3.11 `

Windows & OSX build support for `node-gyp` so you'll have to follow these [instructions](https://github.com/nodejs/node-gyp) as per your OS so for `Windows` you'll have to follow these [instructions](https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-windows) before installing `@tensorflow/tfjs-node` or `@tensorflow/tfjs-node-gpu`on your system.

Hi, @pjocepwf You should able to install tfjs-node on your `Windows 11` system with `Python 3.11` like @Master-Tech271 if you're following the exact steps which are mentioned by @Master-Tech271 then just try with `Python 3.11` instead of `Python 3.12 `and should able to install `tfjs-node` on your` Windows 11` system

At the moment I'm closing this issue if you face any issue while installing `tfjs-node` with `Python 3.11` on `Windows 11` system please feel free to post comments here with new error log to investigate your issue further.

If someone is facing issue while installing `tfjs-node` on `Windows 10` or `Windows 11` please feel free to create [new issue](https://github.com/tensorflow/tfjs/issues/new/choose) with your error log to investigate your issue as soon as possible. 

Thank you for your understanding and patience.
