### ISSUE TITLE
Initialization of backend wasm failed

### ISSUE THREAD

**Issue by DaiHaoguang3151** [tensorflow/tfjs#8119]
**code**

`import React, { useState, useRef } from "react";
import * as faceapi from 'face-api.js'
// import * as tf from '@tensorflow/tfjs-core';
import * as tf from '@tensorflow/tfjs';
import { setWasmPaths } from "@tensorflow/tfjs-backend-wasm";

const App = () => {
    const [session, setSession] = useState(null);
    const [loading, setLoading] = useState("Loading OpenCV.js...");

    async function init() {
        // setWasmPaths('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/');
        // setWasmPaths('../node_modules/@tensorflow/tfjs-backend-wasm/dist/');
        setWasmPaths(`${process.env.PUBLIC_URL}/static/js/`);
        await tf.setBackend('wasm');
        await tf.ready();
        console.log(tf.getBackend())  // webgl
    }
    init();
    
    cv["onRuntimeInitialized"] = async () => {
        await faceapi.nets.mtcnn.loadFromUri("/model");
        await faceapi.nets.faceLandmark68Net.loadFromUri("/model");
        await faceapi.nets.faceRecognitionNet.loadFromUri("/model");

        console.log("backend==> ", tf.getBackend())  // webgl
        setLoading(false);
    }
    
    console.log("here backend==> ", tf.getBackend())  // wasm

    return (
        <div className="App">
            
        </div>
    );
};

export default App;`

 "dependencies": {
    "@tensorflow/tfjs": "^4.15.0",
    "@tensorflow/tfjs-backend-wasm": "^4.15.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "face-api.js": "^0.22.2",
    "onnxruntime-web": "^1.11.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.0"
  }

I encountered the following issue while executing the above code

![image](https://github.com/tensorflow/tfjs/assets/131345009/c86f9409-2b74-4869-97e1-4612e42c5db8)

**Comment by gaikwadrahul8** [comment]
Hi, @DaiHaoguang3151 

Thank you for bringing this issue to our attention and if possible could you please help me with your Github repo which is easy to replicate the same behavior from my end and complete steps to execute your code ?

Thank you for your understanding and patience.

**Comment by DaiHaoguang3151** [comment]
My Github repo: https://github.com/DaiHaoguang3151/face-recognition-web_

**steps:**
1. yarn install
2. yarn start
3. check the console outputs

Thanks a lot !

**Comment by gaikwadrahul8** [comment]
Hi, @DaiHaoguang3151 

Thank you for sharing your Github repo to replicate the same behavior from my end and I have tried and Observed same behavior so we've to dig more into this issue and will update soon. Thank you for bringing this issue to our attention.

Please refer below output log for reference :

![image](https://github.com/tensorflow/tfjs/assets/115997457/15baa59f-3029-4143-b190-9d6a3aa2a1af)

**Comment by DaiHaoguang3151** [comment]
@gaikwadrahul8 
Thank you !

**Comment by DaiHaoguang3151** [comment]
Hi, @mattsoulanille @gaikwadrahul8 

I find that the problem is caused by face-api.js, which uses tfjs-core. I tried to uninstall face-api.js and replace it with @vladmandic/face-api. It works !

Thank you for your attention and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @DaiHaoguang3151 

I apologize for the delayed response and Good to hear that you're able to resolve your issue after uninstalling the `face-api.js` and replace it with `@vladmandic/face-api`, if your issue got resolved please feel free to close this issue.

If you need any further help please feel free to create new issue. Thank you.
