### ISSUE TITLE
Ryzen 8000 AI

### ISSUE THREAD

**Issue by borodadada** [tensorflow/tfjs#8139]
Hello! I'm using the node js version for CPU, will I get acceleration when using these processors with AI support?

**Comment by gaikwadrahul8** [comment]
Hi, @borodadada 

As far I know, Ryzen 8000 has AI-focused GPUs, TensorFlow.js on Node.js currently relies on WebGL for GPU acceleration, which doesn't directly utilize the Ryzen 8000 GPU or NPU and Ryzen 8000 AI fairly new processor and Ryzen 8000's performance with TensorFlow.js on Node.js is not yet throughly benchmarked. while their impact on Tensorflow.js using the Node.js performance specifically is still being evaluated.

If I'm not wrong there's currently no direct integration with Ryzen 8000's AI acceleration features in TensorFlow.js. I hope this explanation answered your question. 

If I have missed something here please let me know. Thank you for your cooperation and patience.
