### ISSUE TITLE
[Feature Request] tfjs-vis visor should show a "restore" button after it's hidden

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#814]
Currently, the tfjs-vis visor has a "hide" button, after clicking which the visor will be hidden. But there is no way for the user to restore the visor! So instead of hiding the entire visor, maybe there should be a button of some kind that stays at a corner of the page and allows the user to restore the visor by clicking it.

**Comment by tafsiri** [comment]
Just following up after a conversation with @caisq. I don't think this would work with the current design principle of making tfjs-vis unintrusive. If it stayed on screen then the user would have a harder time making tfjs-vis disappear when it is not needed. For not I'd say the solution is to programmatically repoen it, or for a user to add a control to their page that toggles the visor. Closing this for now.
