### ISSUE TITLE
Init function for tf

### ISSUE THREAD

**Issue by borodadada** [tensorflow/tfjs#8141]
Node JS version for CPU.
Hi! i use loop for training, and first result ~90% always better then next iterations + after ~100+ iteration ( or more ) tf down
I think it's possible fix if use init function for tf + to fix the memory leak I have to use
```
        //fix memory leak
        tf.engine().startScope()

        //fit
        await model.fit(data, item)
        
        //fix memory leak 
        tf.engine().endScope()
```
How can I get rid of all these problems? I need every iteration to be clean tf! This is very annoying! Thx!

**Comment by gaikwadrahul8** [comment]
Hi, @borodadada 

Thank you for bringing this issue to our attention and could you please help us with code snippet / Github repo with more explanation to understand your issue correctly and we're unable to provide definitive solutions without the full code to replicate the same behaviour from our end also. 

If possible please help us with `Node.js version`, `tjfs-node` version and `OS` platform. 

Thank you for your cooperation and patience.

**Comment by borodadada** [comment]
node js v19.9.0, intel 13700, 32gb, windows 11 x64
i use affinity windows for node, 4 cores on one copy
```
    "@tensorflow/tfjs": "^4.16.0",
    "@tensorflow/tfjs-node": "^4.16.0",
```
i created example
```
const tf = require('@tensorflow/tfjs-node');

const size = 10
const units = 100
let count = 0

const letsgo = async function(){

    const model = tf.sequential();
    model.add( tf.layers.dense({ inputShape: [units], units, activation: 'linear', useBias: true }));
    model.add( tf.layers.dense({ units, activation: 'linear', useBias: true }));
    model.add( tf.layers.dense({ units, activation: 'linear', useBias: true }));
    model.compile({ optimizer: tf.train.adam(0.005, 0.9, 0.999), loss: tf.losses.absoluteDifference });

    let a = []
    let b = []
    for (let i = 0; i < size; i++) {
        let aa = []
        let bb = []
        for (let ii = 0; ii < units; ii++) {
            aa.push( Math.random() )
            bb.push( Math.random() )
        }
        a.push(aa)
        b.push(bb)
    }

    let xs = tf.tensor2d( a );
    let ys = tf.tensor2d( b );

    await model.fit(xs, ys, {
        epochs: 100000,
        shuffle: false,
        verbose: 0,
        callbacks:{
            onTrainBegin: ()=>{
                console.log('start: ', count)
            },
            onTrainEnd: ()=>{
                console.log('done: ', count)
                count++
            },
            onEpochEnd: async (epoch, logs)=>{
                if( epoch % 100 === 0 )
                    console.log(epoch, logs.loss)
            }
        }
    })
}

const loop = async function(){
    for (let i = 0; i < 500; i++) {
        await letsgo()
        //now need init for tf, before new iteration
    }
}

loop()
```

after completing the first iteration, I need to bring the tf to its original state so that there are no memory leaks and no changes inside, what to do?

**Comment by borodadada** [comment]
model.fit need run in tf.tidy? I can not understand
