### ISSUE TITLE
node-gyp configure 错误

### ISSUE THREAD

**Issue by abcln** [tensorflow/tfjs#8144]
PS D:\webServer\temsorflow\tfjs-node-4.15\package> node-gyp configure --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@5.1.1
gyp info using node@18.16.1 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if the py launcher can be used to find Python 2
gyp verb find Python - executing "py.exe" to get Python 2 executable path
gyp verb find Python - executable path is "C:\Python27\python.exe"
gyp verb find Python - executing "C:\Python27\python.exe" to get version
gyp verb find Python - version is "2.7.12"
gyp info find Python using Python version 2.7.12 found at "C:\Python27\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 18.16.1
gyp verb command install [ '18.16.1' ]
gyp verb install input version string "18.16.1"
gyp verb install installing version: 18.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 18.16.1
gyp verb build dir attempting to create "build" dir: D:\webServer\temsorflow\tfjs-node-4.15\package\build
gyp verb build dir "build" dir needed to be created? D:\webServer\temsorflow\tfjs-node-4.15\package\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp verb find VS checking VS2017 (15.9.34118.181) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp info find VS using VS2017 (15.9.34118.181) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\webServer\temsorflow\tfjs-node-4.15\package\build\config.gypi
(node:13228) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp verb config.gypi checking for gypi file: D:\webServer\temsorflow\tfjs-node-4.15\package\config.gypi
gyp verb common.gypi checking for gypi file: D:\webServer\temsorflow\tfjs-node-4.15\package\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v18.16.1\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\webServer\\temsorflow\\tfjs-node-4.15\\package\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v18.16.1\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\18.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v18.16.1\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\webServer\\temsorflow\\tfjs-node-4.15\\package',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\webServer\\temsorflow\\tfjs-node-4.15\\package\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Users\Administrator\AppData\Roaming\nvm\v18.16.1\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd D:\webServer\temsorflow\tfjs-node-4.15\package
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok

**Comment by gaikwadrahul8** [comment]
Hi, @abcln 

Thank you for brining this issue to our attention and I see currently you're using Node.js version v18.16.1 and `Python 2.7.12` which is older Python version so I would suggest you to please go with Node.js version `v19.9.0`  with Python version `3.8`, `3.9`, `3.10` or `3.11 `( any one of the Python version ) and it should work, Make sure that you're following all the instructions mentioned in my https://github.com/tensorflow/tfjs/issues/8118#issuecomment-1876384098

If you've installed multiple Python version or Microsoft visual studio then you can set path to use specific Python and Microsoft visual studio with the help of below command :

1. **For Python:** `set npm_config_python="C:\path\to\python.exe"` Or `sudo set npm_config_python="C:\path\to\python.exe"`(Replace your python.exe path in double quotes)

2. **For Microsoft Visual Studio** : `node-gyp configure --msvs_version=2022` Or `sudo node-gyp configure --msvs_version=2022` ( Auto-detection fails for Visual C++ Build Tools 2022, if you want to use 2017 or 2019 just replace that number i.e 2017 or 2019 in the command)

I would request you to please give it try with above temporary workaround and see is it resolving your issue or not ? if issue still persists please let us know with error log to investigate your issue further after running this command `node-gyp configure`

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @abcln 

I'm following up on our previous conversation about installing `tfjs-node` on your `Windows` system. I'm curious if you had the opportunity to try the workaround I suggested earlier.

If you've attempted the workaround, please let me know if you were able to successfully install `tfjs-node`. If it resolved the issue, feel free to close this issue. 

If you need any further assistance with **Tensorflow.js** , please don't hesitate to create a new issue. We're always happy to help.

Thank you for your cooperation and patience.

**Comment by abcln** [comment]
Solved
