### ISSUE TITLE
tfjs-models/toxicity FetchError

### ISSUE THREAD

**Issue by jianyi-gronk** [tensorflow/tfjs#8145]
Hi, I encountered a problem about FetchError: request to https://storage.googleapis.com/tfjs-models/savedmodel/universal_sentence_encoder/vocab.json

I think maybe because some links does not work in china. I would like to ask if there is a link available so that I can access it. Or can I solve it in other ways?

**Comment by gaikwadrahul8** [comment]
Hi, @jianyi-gronk 

Thank you for bringing this issue to our attention. It would be helpful if you could please share the specific official documentation page where you encountered the link, so I can verify its functionality on my end and ensure it is working as intended.

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @jianyi-gronk 

I see you're trying to access **8k word piece** [vocabulary](https://storage.googleapis.com/tfjs-models/savedmodel/universal_sentence_encoder/vocab.json) from this Github [page](https://github.com/tensorflow/tfjs-models/blob/master/universal-sentence-encoder/README.md#universal-sentence-encoder-lite) so just to confirm, are you able to access **8k SentencePiece** [vocabulary](https://tfhub.dev/google/tfjs-model/universal-sentence-encoder-qa-ondevice/1/vocab.json?tfjs-format=file) link ?  meanwhile you can use a VPN I know it's not ideal solution till then I'll check alternative link or solution to help you access that necessary link. 

Thank you for your cooperation and patience.

**Comment by jianyi-gronk** [comment]
Hi, @gaikwadrahul8 

This link was obtained when I encountered an error while running the demo.
My code comes from https://github.com/tensorflow/tfjs-models/blob/master/toxicity/README.md
The specific details are as follows
```
const toxicity = require('@tensorflow-models/toxicity');

const threshold = 0.9;

toxicity.load(threshold).then(model => {
  const sentences = ['you suck'];

  model.classify(sentences).then(predictions => {

    console.log(predictions);
  });

});
```

When I use VPN, I can access the link through a browser, but the code still reports this FetchError.

So, I wonder if I can avoid this issue by using other links, be similar to this [issue](https://github.com/tensorflow/tfjs/issues/4394).

Thank you for your attention and reply.

**Comment by gaikwadrahul8** [comment]
Hi, @jianyi-gronk 

I tried from my end and it seems like working as expected, I'm using below code snippet in the `Node.js project`  by creating empty project with this command `npm init -y` after that I ran this command `npm install @tensorflow/tfjs @tensorflow-models/toxicity` to install required packages

```
const toxicity = require('@tensorflow-models/toxicity');

const threshold = 0.9;

toxicity.load(threshold).then(model => {
  const sentences = ['you suck'];

  model.classify(sentences).then(predictions => {

    predictions.forEach(prediction => {
        console.log("Label:", prediction.label);
        prediction.results.forEach(result => {
          for (const [key, value] of Object.entries(result)) {
            console.log("\t-", key, ":", value);
          }
        });
        console.log(); // Add an empty line between predictions
      });
  });

});
```

**Here is output of above code snippet :**

```
(base) gaikwadrahul-macbookpro:test-8145 gaikwadrahul$ node index.js

============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
Label: identity_attack
        - probabilities : Float32Array(2) [ 0.9659663438796997, 0.034033700823783875 ]
        - match : false

Label: insult
        - probabilities : Float32Array(2) [ 0.08124702423810959, 0.9187529683113098 ]
        - match : true

Label: obscene
        - probabilities : Float32Array(2) [ 0.3993152379989624, 0.6006847620010376 ]
        - match : null

Label: severe_toxicity
        - probabilities : Float32Array(2) [ 0.9970394968986511, 0.002960436511784792 ]
        - match : false

Label: sexual_explicit
        - probabilities : Float32Array(2) [ 0.7053251266479492, 0.2946748435497284 ]
        - match : null

Label: threat
        - probabilities : Float32Array(2) [ 0.9106737971305847, 0.08932614326477051 ]
        - match : false

Label: toxicity
        - probabilities : Float32Array(2) [ 0.031176716089248657, 0.9688233137130737 ]
        - match : true

(base) gaikwadrahul-macbookpro:test-8145 gaikwadrahul$ 
```

I have also tried in the Google chrome browser by creating html page (`index.html)` like below :

```
<html>
  <head>
    <!-- Load TensorFlow.js -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script> 
    <!-- Load toxicity -->
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/toxicity"></script>
 </head>
 
  <body>
    <h2>toxicity model </h2>
  </body>
  <!-- Place your code in the script tag below. You can also use an external .js file -->
  <script>
    // The minimum prediction confidence.
const threshold = 0.9;

// Load the model. Users optionally pass in a threshold and an array of
// labels to include.
toxicity.load(threshold).then(model => {
  const sentences = ['you suck'];

  model.classify(sentences).then(predictions => {
    
    console.log(predictions);
    
  });
});
  </script> 
</html>
```
**Here is output of `index.html `file :**

![image](https://github.com/tensorflow/tfjs/assets/115997457/d527281f-444e-4259-886e-6415148dea98)

If you're trying the exact same thing and still you're getting FetchError then most probably it's happening because of Great Firewall (GFW) Network Restrictions, GFW blocks access to certain foreign websites and services, including Google services like Google Cloud Storage (GCS), where many TensorFlow models are hosted if I'm not wrong

As per my current understanding either download models manually and host them locally or on accessible servers or any alternative mirroring model link if it is hosted on accessible server.

Hi, @mattsoulanille If you've any alternative mirroring model link on accessible server in China please help with it. 

Thank you for your cooperation and patience.

**Comment by jianyi-gronk** [comment]
Hi, @gaikwadrahul8 

I tried the same code, but still got FetchError. I downloaded the model and replaced the current link in node_modules with an accessible server link. So I can access it, thank you very much for your help. I can solve the problem now.

Thank you very much for your answer.
