### ISSUE TITLE
tensorflowjs_converter export an empty file without errors

### ISSUE THREAD

**Issue by Jove125** [tensorflow/tfjs#8155]
Hello,

I try to convert custom object detection (with concrete_function) saved model to tfjs_graph_model with the following command:
tensorflowjs_converter --input_format=tf_saved_model --saved_model_tags=serve --signature_name=serving_default --output_format=tfjs_graph_model ./SavedModel ./WebModel

The conversion completes without errors, but the result is almost empty files (16 bytes in group1-shard1of1.bin).

The same saved model converts well to a tflite format (therefore, the problem is not with the saved model).

Tensorflow.js Converter Version - 3.18

I have attached saved model to reproduce conversion.
[SavedModel.zip](https://github.com/tensorflow/tfjs/files/14074543/SavedModel.zip)

P.S.
A similar mobilenet model, but not for object detection (without concrete_function), is converted well. Apparently, this is the problem.

**Comment by gaikwadrahul8** [comment]
Hi, @Jove125

Thank you for bringing this issue to our attention and I tried to convert your given `SavedModel` into `Tensorflow.js ` and it's creating `group1-shard1of1.bin` and `model.json` files here is [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/1e96da339debea31bd935e1b82e601a3/test-8155.ipynb) but when I loaded converted Tensorflow.js model into [netron app ](https://netron.app/) so it seems like returning an empty file. if possible could you please help me with Google colab notebook where the same model converted successfully in TensorFlow Lite format ? 

Thank you for your cooperation and patience.

1. Here is output when I loaded `model.json` file into `netron app ` :
![image](https://github.com/tensorflow/tfjs/assets/115997457/026b38ff-bfde-4d32-aefc-c69417a8a70d)

2. Here is output when I loaded `saved_model.pb` file into `netron app ` :

![image](https://github.com/tensorflow/tfjs/assets/115997457/92a354ec-23a5-4ade-adc4-b3baeb33e350)

**Comment by Jove125** [comment]
Hi, @gaikwadrahul8 

The code for conversion to tflite and converted tflite model are given in [this](https://github.com/tensorflow/tfjs/issues/8124#issuecomment-1882876977) and [this](https://github.com/tensorflow/tfjs/issues/8124#issuecomment-1887187412) posts

**Comment by Jove125** [comment]
Hi, @gaikwadrahul8

Is there any progress on this issue?

I tried to convert model using the function in `tensorflowjs.converters.converter import tf_saved_model_conversion_v2`
The result was the same as when using tensorflowjs_converter

I found that the graph is completely cut off in the function `_run_grappler(config, graph_def, graph, signature_def)`
If this function is not called (it is called twice there), then the model is exported and not empty, but it always returns zeros on execution (return constants defined in dummy_post_processing). So it looks like it does not replace the dummy function with the NMS.
Do you have any object detection saved model (with same concrete_function) that is successfully converted to web model? - So can be find the differences?

P.S.
I tried to convert the model from here `http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz`
But got `ValueError: Unsupported Ops in the model before optimization`

**Comment by Jove125** [comment]
Custom SavedModel for SSD Object Detection should be exported like in
`https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_lib_v2.py`
but not like in
`https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_lib_tf2.py`

Second one is not supported by tensorflowjs_converter.
After exporting the SavedModel according to the example from the first link, the conversion to the tfjs format was successful.
