### ISSUE TITLE
Performance of webgpu

### ISSUE THREAD

**Issue by y-ich** [tensorflow/tfjs#8156]
Hi.

Thank you for your great project!

I tried a relatively light weight CNN on both webgl and webgpu.
Currently webgpu is slower than webgl, maybe 2/3.

How can I get better performance of webgpu?
Any tips are welcome.

**Comment by gaikwadrahul8** [comment]
Hi, @y-ich 

Thank you very much for your kind words! We're glad you find the project useful and I greatly appreciate your positive feedback on the project and please remember that [@tensorflow/tfjs-backend-webgpu](https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu/v/4.16.0) package adds a GPU accelerated [WebGPU](https://www.w3.org/TR/webgpu/) backend to TensorFlow.js and still under development in TensorFlow.js and performance might not be fully optimized yet

The mission of WebGPU backend is to achieve the best performance among all approaches. However, this target can not be met overnight, but we are committed to supporting it with rapid and continuous performance improvement. Many exciting features, like FP16, DP4A, will be brought in soon. Please refer [FAQ](https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu/v/4.16.0#when-should-i-use-the-webgpu-backend) section

Please try [@tensorflow/tfjs-node-gpu](https://www.npmjs.com/package/@tensorflow/tfjs-node-gpu) library which offers more experimental WebGPU features and might have better performance for specific configurations.

If possible please help us with your Github repo or Code snippet with complete steps to replicate the same behavior from our end. Thank you for your cooperation and patience.
