### ISSUE TITLE
tfjs-models/coco-ssd [TypeError: Cannot read property 'fetch' of undefined]

### ISSUE THREAD

**Issue by Softkeydel** [tensorflow/tfjs#8168]
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@tensorflow-models/coco-ssd": "^2.2.3",
    "@tensorflow-models/mobilenet": "^2.1.1",
    "@tensorflow/tfjs": "^4.16.0",
    "@tensorflow/tfjs-react-native": "^1.0.0",
    "@types/react-native-canvas": "^0.1.13",
    "expo": "^49.0.21",
    "expo-asset": "^9.0.2",
    "expo-camera": "^14.0.1",
    "expo-gl": "~13.0.1",
    "expo-modules-autolinking": "^1.10.2",
    "expo-modules-core": "^1.5.12",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-canvas": "^0.1.39",
    "react-native-fs": "^2.20.0",
    "react-native-webview": "^13.6.4"
  }

const loadModel = async () => {
    try {
      const model = await cocoSsd.load();
      // const model = await mobilenet.load();
      console.log("model loaded");
    } catch (err) {
      console.log("failed to load model ", err);
    }
  }

Trying to run in an React Native project. Always going into error block. Getting error
[TypeError: Cannot read property 'fetch' of undefined]

Please help ASAP

**Comment by gaikwadrahul8** [comment]
Hi, @Softkeydel

We kindly request that you complete the issue template provided at link to [template](https://github.com/tensorflow/tfjs/issues/new/choose). Filling out this template helps us diagnose the issue you're facing more efficiently. Specifically, providing information about your TensorFlow.js version the steps you took before encountering the error and a reproducible **code snippet, your Github repo, codepen example or Google colab** would be immensely helpful.

Now, if possible could you please help me with your **Github repo with complete steps or code snippet** which you followed before encountering the error so I'll go ahead and replicate the same behavior from my end also ?

Thank you for your cooperation!

**Comment by oardkgn** [comment]
Hi do you find any solition for this issue?

**Comment by YassineKADER** [comment]
> Hi do you find any solition for this issue?

This solved the problem for me. Follow these steps:

install @tensorflow/tfjs-react-native if you haven’t already:

    npm install @tensorflow/tfjs-react-native

import @tensorflow/tfjs-react-native at the top of your file. For example, in my case, I added it to my app.tsx file:

    import "@tensorflow/tfjs-react-native";

**Comment by Tarun24RN** [comment]
@YassineKADER I have implemented your code but still getting the same error.
