### ISSUE TITLE
Cannot install "@tensorflow/tfjs-node" package

### ISSUE THREAD

**Issue by KMerchant** [tensorflow/tfjs#8175]
**System information**
- MAC OS Sonoma
- TensorFlow.js installed from npm

**Describe the problem**
npm ERR! code 1
npm ERR! path /Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-darwin-4.17.0.tar.gz
npm ERR! https://storage.googleapis.com/tf-builds/libtensorflow_r2_7_darwin_arm64_cpu.tar.gz
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@21.6.2 | darwin | arm64
npm ERR! (node:16190) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp info check checked for "/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.17.0/CPU-darwin-4.17.0.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.17.0/CPU-darwin-4.17.0.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.17.0 and node@21.6.2 (node-v120 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.17.0/CPU-darwin-4.17.0.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.2 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.2 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.2 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/tahir/Library/Caches/node-gyp/21.6.2/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/Users/tahir/Library/Caches/node-gyp/21.6.2',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/Users/tahir/Library/Caches/node-gyp/21.6.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! <string>:38: SyntaxWarning: invalid escape sequence '\$'
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.2 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! clang: error: no such file or directory: 'node/node_modules/@tensorflow/tfjs-node/deps/include'
npm ERR! make: *** [Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
npm ERR! gyp ERR! System Darwin 23.2.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/lib/napi-v8" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
npm ERR! gyp ERR! cwd /Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node
npm ERR! gyp ERR! node -v v21.6.2
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node --module_name=tfjs_binding --module_path=/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node/lib/napi-v8 --napi_version=9 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 23.2.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/tahir/Desktop/Exercises/TensorFlowJs/New node/node_modules/@tensorflow/tfjs-node
npm ERR! node-pre-gyp ERR! node -v v21.6.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! * Downloading libtensorflow
npm ERR! 
npm ERR! * Building TensorFlow Node.js bindings

I get the error above

**Provide the exact sequence of commands / steps that you executed before running into the problem**
npm install @tensorflow/tfjs-node

**Comment by gaikwadrahul8** [comment]
Hi, @KMerchant 

I sincerely apologize for the delayed response and I see you're trying to install `@tensorflow/tfjs-node` with `python 3.12` so as far I know stable Tensorflow core only supports till `Python 3.11 ` so once Tensorflow core start supporting Python 3.12 then our Tensorflow.js will start working on to support `@tensorflow/tfjs-node` with `python 3.12` so as of now workaround is to downgrade Python version to any one these `3.11, 3.10,3.9,3.8,3.7,3.6` and it should work 

I have tried to install `@tensorflow/tfjs-node` with `Python 3.11` and it's working as expected even I tried with small training code for your reference I have added output log below :

```
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % node -v
v21.6.2
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % npm -v
10.2.4
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % npm i @tensorflow/tfjs-node

up to date, audited 122 packages in 2s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % node index.js 
Epoch 1 / 5
eta=0.0 ============================================================================================> 
310ms 31us/step - MAE=0.337 loss=0.173 val_MAE=0.305 val_loss=0.137 
Epoch 2 / 5
eta=0.0 ============================================================================================> 
247ms 25us/step - MAE=0.282 loss=0.115 val_MAE=0.276 val_loss=0.108 
Epoch 3 / 5
eta=0.0 ============================================================================================> 
231ms 23us/step - MAE=0.264 loss=0.0969 val_MAE=0.273 val_loss=0.106 
Epoch 4 / 5
eta=0.0 ============================================================================================> 
225ms 23us/step - MAE=0.255 loss=0.0890 val_MAE=0.266 val_loss=0.0982 
Epoch 5 / 5
eta=0.0 ============================================================================================> 
229ms 23us/step - MAE=0.254 loss=0.0874 val_MAE=0.258 val_loss=0.0912 
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % python
Python 3.11.6 (main, Nov 28 2023, 20:15:10) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
gaikwadrahul@gaikwadrahul-macbookpro test-tfjs-node-macos % 
```
I would request you to please give it try with above workaround and see is it working as expected or not ? if issue still persists please let us know with complete error log to investigate this issue further from our end.

If your issue got resolved after downgrading the Python version please feel free to close this issue. Thank you for your cooperation and patience.
