### ISSUE TITLE
Xeon support

### ISSUE THREAD

**Issue by lukemovement** [tensorflow/tfjs#8177]
I was wondering if there is any support for multi socket motherboards using Xeon processors within the tfjs package. Would I be able to train a model using multiple processors, or would I need to set up distribution using the Python library?

**Comment by gaikwadrahul8** [comment]
Hi, @lukemovement 

We haven't got confirmation from your end so now, May I know your issue got resolved ? if so please feel free to close this issue ? if you've any further questions please feel free to ask us

Thank you for your understanding and patience.
