### ISSUE TITLE
@types/webgl-ext conflicts with the TypeScript standard library

### ISSUE THREAD

**Issue by xiaodeaux** [tensorflow/tfjs#818]
#### TensorFlow.js version
`@tensorflow/tfjs-node-gpu@0.1.18`

#### Browser version
N/A as I'm only using Node at the moment

#### Describe the problem or feature request
> the `@types/webgl-ext` package (an indirect dependency of `@tensorflow/tfjs-node-gpu`) contains a declaration of the `getExtension` method of `WebGLRenderingContext` that is incompatible with the declaration of the `getExtension` method of `WebGLRenderingContextBase` in recent versions of the TypeScript standard library.

The issue has been discussed on StackOverflow here: https://stackoverflow.com/questions/52846622/error-ts2430-interface-webglrenderingcontext-incorrectly-extends-interface-w

And I created an issue for DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29897

#### Code to reproduce the bug / link to feature request
Install TypeScript and then install `tfjs-node-gpu` with `npm`. Then create a blank `.ts` file and run `tsc`.

**Comment by xiaodeaux** [comment]
@tafsiri Thank you.

The types package has been updated: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29897

**Comment by nkreeger** [comment]
Should be fixed in the next release of `@tensorflow/tfjs`

**Comment by xiaodeaux** [comment]
@nkreeger Do you have an ETA when the next version will be released? I think the current version was released only a few days ago.

Thank you! ❤
