### ISSUE TITLE
Error when running tfjs-automl in web worker due to old tfjs-core dependency

### ISSUE THREAD

**Issue by PrafulB** [tensorflow/tfjs#8186]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): tfjs-automl
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
tfjs-automl depends on tfjs-core v3.9.0 , which causes a ReferenceError when run inside a Web Worker. This is documented in issue #6922 .

**Describe the expected behavior**
Upgrading the dependency in the package.json to tfjs-core v4.0.0+ should resolve this issue. Tried setting the dependency to tfjs-core v4.9.0, and all tests complete successfully.

Happy to submit a PR with the above change if it helps.

**Comment by gaikwadrahul8** [comment]
Hi, @PrafulB

Thanks for bringing this issue to our attention! I understand that the current dependency on `tfjs-core v3.9.0` in `tfjs-automl `is causing a `ReferenceError` when running inside a Web Worker as mentioned in issue [#6922](https://github.com/tensorflow/tfjs/issues/6922). The library should function flawlessly within a Web Worker environment, without encountering any errors.

Upgrading the dependency in `package.json` to `tfjs-core v4.0.0+` is likely to resolve this issue. You've already mentioned that setting the dependency to `tfjs-core v4.9.0` successfully passed all tests which aligns with this proposal.

We appreciate your willingness to contribute and submit a pull request to address this issue. Our team will thoroughly review your PR and take appropriate action based on their assessment. Thank you again for your valuable contribution.

**Comment by PrafulB** [comment]
Apologies for not noticing your response earlier, @gaikwadrahul8 . I've created a PR ( https://github.com/tensorflow/tfjs/pull/8256 ) that updates the version of the tfjs-core dependency. All tests run successfully for me. 

Appreciate the help!
