### ISSUE TITLE
Issue while using tjfs node gpu in wsl2

### ISSUE THREAD

**Issue by sc0rp10n-py** [tensorflow/tfjs#8187]
I first installed cuda toolkit 12.3 in windows side, and then again installed it in wsl 2 side using the official docs

For both I kept getting this error
```
Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

now I also added the LD paths for my version.

So i manually went to that path and saw for myself, that there were these libcudart libcudnn etc dlls there, but the ending number was not matching, so I am guessing the tfjs doesn't suppport latest cuda yet, so can you tell me what version does it support

so i install that cuda toolkit on wsl2 side

**Comment by sc0rp10n-py** [comment]
@gaikwadrahul8 hi do you have any idea about it?

if you can tell me what cuda version does tfjs 4.17.0 support, because the files it is searching for (the DLL versions) are not there anymore in cuda 12.3

**Comment by gaikwadrahul8** [comment]
Hi, @sc0rp10n-py

I apologize for the delayed response and as per our [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md) <p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For GPU support, `tfjs-node-gpu@1.2.4 or later`requires the following NVIDIA® software installed on your system as per our tested build configuration and please make sure that you'll have `Python version 3.9 or later` in the `tfjs-node` official documentation it's stating it requires `Python 2.7` but that documentation is outdated and our relevant team working on it and we will update that official documentation soon :</p>
Name | Version
-- | --
NVIDIA® GPU drivers | >450.x
CUDA® Toolkit | 11.2
cuDNN SDK | 8.1.0

For [Windows WSL2](https://www.tensorflow.org/install/pip#windows-wsl2) software requirements are :

- Windows Native Requires [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads)

- Python 3.9–3.11

 **The following NVIDIA® software are only required for GPU support.**
- [NVIDIA® GPU drivers](https://www.nvidia.com/drivers) version 450.80.02 or higher.
- [CUDA® Toolkit 11.8](https://developer.nvidia.com/cuda-toolkit-archive).
- [cuDNN SDK 8.6.0](https://developer.nvidia.com/cudnn).

Note: GPU support on native-Windows is only available for 2.10 or earlier versions, starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin

Thank you for your understanding and patience.

**Comment by sc0rp10n-py** [comment]
yeah thanks, i was able to figure it out

**Comment by gaikwadrahul8** [comment]
Hi, @sc0rp10n-py 

We're glad to hear you were able to resolve your issue!, please feel free to close this issue if the issue has been resolved. if you need any further assistance please feel free to create new issue and we'll be happy to help you.

Thank your for your understanding and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @sc0rp10n-py

We haven't got confirmation from your end so now I'm closing this issue, if you need any further assistance please feel free to create new issue and we will be happy to help you with your issue.

Thank you for your understanding and patience.
