### ISSUE TITLE
tf.fft rfft return tensor filled with 0 when given tensor with more than 150k element.

### ISSUE THREAD

**Issue by simonliao98** [tensorflow/tfjs#8191]
I am using tf.fft to convert an  around 5 second long 48kHz recording of mls, and I found it always gives me a tensor filled with 0, then I tried to use 3 seconds long mls and found that it secceeds. I wonder why it failed with a larger array, my computer has 16gb ram and 48kHz x 5 would be 240k samples, which is is only around 8mb.
Here is the code:
            const payloadT = tf.tensor1d(mls);
            payloadT.print();
            const xfft = payloadT.rfft(); 
            xfft.array().then(array => {
              console.log("fft:", array);
              let setItem = new Set(array);
              console.log("all zero", setItem.size === 1 && setItem.has(0));
          });
        console.log("dimention:", xfft.shape);
tfjs version: "@tensorflow/tfjs": "^4.17.0"

**Comment by simonliao98** [comment]
![Uploading Screenshot 2024-03-01 at 11.45.18.png…]()

**Comment by simonliao98** [comment]
Works when its 1 second long.
![Uploading Screenshot 2024-03-01 at 11.45.18.png…]()

**Comment by simonliao98** [comment]
<img width="1728" alt="Screenshot 2024-03-01 at 11 45 18" src="https://github.com/tensorflow/tfjs/assets/50464557/6090a17d-9705-43d9-b0b9-e5dec4c26f5e">

**Comment by simonliao98** [comment]
Fails when mls is 5 second long, 240000 samples.
<img width="1728" alt="Screenshot 2024-03-01 at 11 50 07" src="https://github.com/tensorflow/tfjs/assets/50464557/e603ec67-247c-412c-8e7d-074ff84681f1">

**Comment by simonliao98** [comment]
Can you try this code snippet? I first create an array with 0, 1 or -1, and compute the fft. I also run in Node.js environment and this always gives me a sequence of 0s. 

function generateSequence(length) {
      const sequence = new Float32Array(length);
      for (let i = 0; i < length; i++) {
        sequence[i] = Math.floor(Math.random() * 3) - 1; 
      }
      return sequence;
    }
    
    let l = 480000; // Length of the sequence
    let uint32array = generateSequence(l);
    let payloadT = tf.tensor1d(uint32array);
    payloadT.print();
    let xfft = payloadT.rfft();  // tf.spe
    await xfft.array().then(array => {
      console.log("fft:", array);
      let setItem = new Set(array);
      console.log("all zero", setItem.size === 1 && setItem.has(0));
    });
    console.log("dimention:", xfft.shape);

**Comment by shmishra99** [comment]
Hi @simonliao98, I apologize for the delay in my response. The code snippet I run for 240k samples. I obtained non-zero tensors as output.  please share your system configuration including OS,NodeJs version. So I can help diagnose the issue.
Thank You!!

```
Tensor
    [1, 0, 0, ..., 1, 0, -1]
dimention: [ 120001 ]
fft: [
                 -213,                   0,   385.7972106933594,
  -119.29138946533203,   261.7189025878906,  41.473350524902344,
   -351.8073425292969,   -56.9022102355957,   859.8206787109375,
  -25.847209930419922,  147.05548095703125, -132.38165283203125,
    -204.999267578125,  209.37901306152344, -58.669132232666016,
  -134.04965209960938,   442.6009521484375, -285.78399658203125,
   135.80545043945312,  -364.8921813964844,   -294.107666015625,
   232.07803344726562,   283.1802062988281,  144.06210327148438,
   -439.2146301269531,  -47.44232177734375,  38.072261810302734,
      -67.17626953125,   467.9176940917969,  127.51599884033203,
     215.356689453125,   75.42316436767578, -159.41432189941406,
  -104.05785369873047,   77.09473419189453,  -251.0645294189453,
  -52.756805419921875,    153.696533203125,   246.9474334716797,
    144.0785369873047,   387.5783996582031,  -55.24141311645508,
   -455.7982482910156,   55.94731903076172, -12.474431991577148,
     -682.87646484375, -194.76019287109375,   200.8053741455078,
  -215.30186462402344, -21.360872268676758,  52.478721618652344,
   30.157474517822266, -170.50091552734375,  31.080097198486328,
   -87.38511657714844,  2.9110772609710693,   390.1818542480469,
    207.2793426513672, -106.80181121826172, -294.64080810546875,
    242.7520294189453,  -396.9320373535156, -53.521026611328125,
   -486.6830139160156,   19.05720329284668,  -413.3503723144531,
   -297.6334533691406, -132.23854064941406,  -39.02934646606445,
      -218.8896484375,   5.406161308288574, -251.50222778320312,
   -541.9608154296875,  352.13153076171875,  172.00997924804688,
  -134.77694702148438,   378.4018859863281,  -76.90174865722656,
   -693.0958862304688,    469.718017578125, -469.14373779296875,
    499.0782165527344,   251.3582763671875,  115.19245147705078,
   451.89642333984375,   348.6766052246094,   390.4464416503906,
   -320.9207763671875, -222.37466430664062,   198.2730712890625,
   184.30227661132812,   65.20264434814453,  -60.27225112915039,
   232.92018127441406,  15.067310333251953,  447.76605224609375,
  -20.118478775024414,  -7.621686935424805,  22.105928421020508,
  -193.08804321289062,
  ... 239902 more items
]
all zero false
```
