### ISSUE TITLE
Bundle Size Issues 

### ISSUE THREAD

**Issue by enszrlu** [tensorflow/tfjs#8196]
I am having trouble with the bundle size. Is there a way to reduce the tensorflow bundle size?

```
Large Dependencies                                                                     Uncompressed size  Compressed size
node_modules/.pnpm/@tensorflow+tfjs-node@4.17.0_seedrandom@3.0.5                               383.26 MB        109.22 MB
node_modules/.pnpm/canvas@2.11.2                                                               179.01 MB         46.58 MB
node_modules/.pnpm/@tensorflow+tfjs-layers@4.17.0_@tensorflow+tfjs-core@4.17.0                    1.4 MB        267.02 KB
node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0                                   770.88 KB        236.08 KB
node_modules/.pnpm/@tensorflow+tfjs-core@4.17.0                                                  1.14 MB        217.09 KB
node_modules/.pnpm/@tensorflow+tfjs@4.17.0_seedrandom@3.0.5                                      1.28 MB        208.18 KB
node_modules/.pnpm/@tensorflow+tfjs-converter@4.17.0_@tensorflow+tfjs-core@4.17.0                1.19 MB        191.73 KB
node_modules/.pnpm/@tensorflow+tfjs-backend-webgl@4.17.0_@tensorflow+tfjs-core@4.17.0          952.32 KB        147.14 KB
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0                                               546.21 KB        138.91 KB
.next/server/chunks                                                                            410.92 KB        117.33 KB
node_modules/.pnpm/@vladmandic+human@3.2.1                                                     317.31 KB         109.5 KB
All dependencies                                                                               572.98 MB        158.19 MB
Max serverless function size was exceeded for 1 function
Created all serverless functions in: 1:01.448 (m:ss.mmm)
Collected static files (public/, static/, .next/static): 5.607ms
Build Completed in /vercel/output [2m]
Deploying outputs...
Error: A Serverless Function has exceeded the unzipped maximum size of 250 MB. 
```

**Comment by shmishra99** [comment]
HI @enszrlu , 

Could you the follow the [comment](https://github.com/orgs/vercel/discussions/103#discussioncomment-6952635) it may resolve your issue. For debugging, please provide framework, deployment, and minimal reproducible code information.

Thank You!!

**Comment by enszrlu** [comment]
> HI @enszrlu ,
> 
> Could you the follow the [comment](https://github.com/orgs/vercel/discussions/103#discussioncomment-6952635) it may resolve your issue. For debugging, please provide framework, deployment, and minimal reproducible code information.
> 
> Thank You!!

I believe it is regarding puppeteer not tensorflow. Tensorflow bundle size is much higher then puppeteer. I have removed the canvas module from my dependencies but still tensorflow by itself exceeds the limit by double.

Is there a custom lighter version of tensorflow?

**Comment by shmishra99** [comment]
`tfjs-node` doesn't have a separate 'lite' version, there is workaround to reduce its footprint if you're deploying on `Vercel`, which has a package size limit of 250MB.  Instead of including `tfjs-node` in your Vercel deployment, you can host it on a separate server. Let me know if it helps. Thank You!!
