### ISSUE TITLE
BlazePoseTfjsEstimationConfig - flipHorizontal do not work

### ISSUE THREAD

**Issue by Al0ngsy** [tensorflow/tfjs#8197]
**System information**
- OS Platform and Distribution: Mac OS
- TensorFlow.js installed from: npm
- TensorFlow.js version: "^4.17.0"
- Browser version: Chrome Version 122.0.6261.112

**Describe the current behavior**
I follow the README and create a detector with the following config:
```
const bodyPoseNet = await bodyPoseDetection.createDetector(
    bodyPoseDetection.SupportedModels.BlazePose,
    {
      runtime: "tfjs",
      modelType: "full",
    } as bodyPoseDetection.BlazePoseTfjsModelConfig
  );
...
const body = await bodyPoseNet.estimatePoses(video, {
      flipHorizontal: true,
    } as bodyPoseDetection.BlazePoseTfjsEstimationConfig);
```

the returned keypoints however did not get flipped correctly. 
As you can see below the passed config for flipping did not working properly, as the left_eye values have almost the same coordinate.

![image](https://github.com/tensorflow/tfjs/assets/29375199/85d2a17c-569c-4e2d-8b19-6c41dc23f27e)

![image](https://github.com/tensorflow/tfjs/assets/29375199/5eded5a0-b3cd-425a-be97-ca034abbf567)

**Comment by gaikwadrahul8** [comment]
Hi, @Al0ngsy 

I apologize for the delayed response and thank you for bringing this issue to our attention, to confirm did you try `runtime: 'mediapipe'` and checked is it working as expected ?

Could you please help us with your complete code-snippet or Github repo with complete steps to run and replicate the same behaviour from our end which will help us to investigate this issue further from our end ? 

Thank you for your understanding and patience.
