### ISSUE TITLE
How should I do if I want to change the way keypoints connected? 

### ISSUE THREAD

**Issue by kunwuz** [tensorflow/tfjs#820]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
Cloned the latest code from repo https://github.com/tensorflow/tfjs-models
Followed the README of posenet demos
#### Browser version
Chrome Version 66.0.3359.181
#### Describe the problem or feature request
I'm a highschool student and not familiar with this. I want to change the way keypoints connected, for example, nose will be attached with eyes. And also add a new point representing neck. 

Here is the target image.

![0_0](https://user-images.githubusercontent.com/29473070/47352019-b1983100-d6eb-11e8-8025-592967446e1e.jpg)

I want to represent the neck with the midpoint between the two shoulders, but after 2 days studying the core, I still cannot find a useful way to achieve that. Could any one give me some suggestions? Thanks so much T T

#### Code to reproduce the bug / link to feature request
I'm looking for a way to achieve my goal, but still feel extremely puzzle.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
