### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by lklewis83** [tensorflow/tfjs#8230]
Could not read source map for file:////npm/%40tensorflow/tfjs%403.8.0/node_modules/%40tensorflow/tfjs-core/dist/backends/backend.js: UNC host 'npm' access is not allowed

* Are there instructions to do this locally? I tried and got other errors.

**Comment by gaikwadrahul8** [comment]
Hi, @lklewis83 

Thank you for bringing this issue to our attention and as far I know This error arises when the browser attempts to load a source map for the TensorFlow.js library file (backend.js) from an invalid location (file:////npm). Source maps provide debugging information by mapping code in a minified file back to its original human-readable form.

Browsers typically restrict access to files on remote servers (indicated by //npm) using UNC (Universal Naming Convention) paths. This is a security measure to prevent malicious code injection.

However, you can resolve that issue by running the codelab locally (e.g. in a development environment) set up a local web server (like `http-server`) to serve the codelab files. This allows the browser to access the files from a valid location (e.g., `http://localhost:8080/`).

Run the server command in your terminal : `http-server`

You'll need Node.js and npm (Node Package Manager) installed on your system. You can usually download them together from the official Node.js website : https://nodejs.org/en/download after that please follow below steps :

1. Install `http-server` globally by using this command `npm install -g http-server`
2. Navigate to the directory containing your TensorFlow.js codelab files (e.g., the directory where `index.html` resides) and run` http-server` from your terminal
3. By default, `http-server` runs on port `8080`. Open your web browser and navigate to: `http://localhost:8080`

Please try to run the codelab example locally with above steps and see is it working as expected or not ? 

If issue still persists please let us know with error log to investigate this issue further. 

Thank you for your understanding and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @lklewis83

We haven't got confirmation from your end so now I'm closing this issue, if you need any further assistance on this issue please feel free to post your comments so we'll re-open this issue once again to help you further and if you need any help on new issue please feel free to create [new issue](https://github.com/tensorflow/tfjs/issues/new/choose) and we will happy to help you further.

Thank you for your cooperation and patience.
