### ISSUE TITLE
Error installing @tensorflow/tfjs-node at WSL Ubuntu

### ISSUE THREAD

**Issue by PinKevin** [tensorflow/tfjs#8254]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04.3 LTS on Windows 10 WSL
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.21.1
- CUDA/cuDNN version: -

**Describe the problem**
When I tried to install the _tfjs-node_, it keeps return error that looks like this
```
npm ERR! code 1
npm ERR! path /mnt/d/KEVIN/KULIAH/SMT 6/Bangkit/Studi-Kasus-Penerapan-ML-pada-GCP/serta-mulia-be/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.21.1.tar.gz
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! node:events:495
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: getaddrinfo EAI_AGAIN storage.googleapis.com
npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
npm ERR! Emitted 'error' event on ClientRequest instance at:
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -3001,
npm ERR!   code: 'EAI_AGAIN',
npm ERR!   syscall: 'getaddrinfo',
npm ERR!   hostname: 'storage.googleapis.com'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.20.2

npm ERR! A complete log of this run can be found in: /home/kevin/.npm/_logs/2024-04-22T01_43_27_122Z-debug-0.log
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
At first, I installed the nvm like this
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm install 18
nvm use 18
```
Then, I tried to download the tfjs-node, and it keeps giving me error as mentioned. I tried to do some commands below:
```
sudo apt-get update
sudo apt-get install build-essential
npm rebuild @tensorflow/tfjs-node --build-from-source
```
But it keeps giving me the same errors

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Currently there is no other info and logs

**Comment by gaikwadrahul8** [comment]
Hi, @PinKevin

Thank you for bringing this issue to our attention and I see currently you're using Linux Ubuntu 22.04.3 LTS on Windows 10 WSL so could you please give it try with `Ubuntu 20.04 LTS` with Python version less than 3.12.x (`3.10.x or 3.11.x`) at the moment I'm not sure which Python version you're using ? 

Please give it try with `Node.js v20.10.0` and before installing `@tensorflow/tfjs-node` please run `npm install -g node-gyp`  then run `npm i @tensorflow/tfjs-node` and see is it working as expected or not ?

If issue still persists please let us know with error log after running this command `node-gyp configure --verbose`

Thank you for your cooperation and patience.

**Comment by PinKevin** [comment]
My problem already fixed. The solution that I done are:

1. Open file `resolv.conf` with `sudo nano /etc/resolv.conf `
2. After that, the file will look like this:
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/resolv.conf
# [network]
# generateResolvConf = false
nameserver xxx.xx.xx
```
3. Change the nameserver value to 8.8.8.8
