### ISSUE TITLE
Have the WebGL backend send certain ops to the CPU if it would be faster

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#826]
Develop a heuristic for identifying smaller ops that would always be faster on the CPU. In `backend_webgl:compileAndRun`, check whether the incoming op meets the criteria and if so send it to the CPU.

From Nikhil:

For small operations in WebGL, we currently upload them to textures and call a shader. This can be much slower than just running operations on the CPU.

It would be great to have a heuristic where an op that is executing on CPU-resident Tensors will simply execute on the CPU.

Let's run an experiment doing this with coco-ssd and see what kind of wins we get!

**Comment by rthadur** [comment]
looks like the related PR has been merged , so closing this issue.
