### ISSUE TITLE
I can't install  @tensorflow/tfjs-node in my project

### ISSUE THREAD

**Issue by wangchen2021** [tensorflow/tfjs#8276]
When I use **yarn add @tensorflow/tfjs-node** 

Error log below:

error C:\Users\17103\Desktop\version_chen\node_modules\@tensorflow\tfjs-node: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: C:\Users\17103\Desktop\version_chen\node_modules\@tensorflow\tfjs-node
Output:
CPU-windows-4.19.0.zip
* Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v20.9.0

**Comment by wangchen2021** [comment]
My system is window 11

**Comment by gaikwadrahul8** [comment]
Hi, @wangchen2021

I apologize for the delay in responding, following the instructions mentioned in my https://github.com/tensorflow/tfjs/issues/8081#issuecomment-1827814656 with these Node.js versions `Node.js v19.9.0 `and `Node.js v18.16.1` it should work with Python version 3.x and less than Python version 3.12.x (e.g 3.11.x,3.10.x or 3.9.x) and at the moment it's not working as expected with `Node.js v20.9.0`

I believe you're following these official documentation [Ref-1](https://github.com/tensorflow/tfjs/tree/master/tfjs-node), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) and [node-gyp - Node.js native addon build tool for Windows](https://github.com/nodejs/node-gyp#on-windows)

In general you'll have to follow below steps to install @tensorflow/tfjs-node on Windows system:

- Edit the path user or system variable, ensure that the path to python is added to the path variable.
- Install Visual Studio community edition with desktop development with C++ [Link](https://visualstudio.microsoft.com/vs/community/)
- Install visual studio build tools with the help of Visual Studio Installer
- Ensure that node-gyp is available: `npm install -g node-gyp`
- Install tfjs-node: `npm install @tensorflow/tfjs-node`

`tfjs-node` requires AVX processors and tfjs-node library uses AVX instructions to improve the performance of its operations. If your CPU does not support AVX, as far I know you will not be able to use tfjs-node if I'm not wrong so to check AVX support please follow below steps

- Right-click on the Start button and select "System Information."
- Expand the "Processor" category in the left-hand pane.
- Look for "Instruction Set" or "Extended Instructions" in the right-hand pane. If AVX is supported, you should see it listed there (e.g., "AVX2").

**NOTE :** If the above workaround does not work please try using your mobile phone's hotspot to connect your computer to the internet. This alternative connection might fix the installation issue.

Please let us know after trying the above steps is it resolving your issue or not ? if not please help us with the error log to investigate this issue further

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @wangchen2021 

To confirm, were you able to successfully install `tfjs-node` on your `Windows 11` system by following the provided instructions in my previous comment ? if so please feel free to close this issue from your end

If issue still persists please help us with new error log for further investigation after running this command `node-gyp configure` in the terminal.

Thank you for your cooperation and patience

**Comment by gaikwadrahul8** [comment]
Hi, @wangchen2021 

We haven't got confirmation from your end so now I'm closing this issue and after trying above workaround if issue still persists please feel free to post your comment with new error log and will re-open this issue.

Thank you for your understanding and patience.
