### ISSUE TITLE
npm install @tensorflow/tfjs-node error

### ISSUE THREAD

**Issue by 82318179** [tensorflow/tfjs#8282]
npm install @tensorflow/tfjs-node 

error as follows:

E:\tensorflow>npm install @tensorflow/tfjs-node  --registry http://mirrors.cloud.tencent.com/npm/
npm ERR! code 1
npm ERR! path E:\tensorflow\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-4.19.0.zip
npm ERR! https://registry.npmmirror.com/binary.html?path=tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! E:\tensorflow\node_modules\adm-zip\zipFile.js:102
npm ERR!         if (!~endOffset) throw new Error(Utils.Errors.INVALID_FORMAT);
npm ERR!                                ^
npm ERR!
npm ERR! Error: Invalid or unsupported zip format. No END header found
npm ERR!     at readMainHeader (E:\tensorflow\node_modules\adm-zip\zipFile.js:102:32)
npm ERR!     at new module.exports (E:\tensorflow\node_modules\adm-zip\zipFile.js:20:9)
npm ERR!     at new module.exports (E:\tensorflow\node_modules\adm-zip\adm-zip.js:62:18)
npm ERR!     at WriteStream.<anonymous> (E:\tensorflow\node_modules\@tensorflow\tfjs-node\scripts\resources.js:72:29)
npm ERR!     at WriteStream.emit (node:events:519:28)
npm ERR!     at emitCloseNT (node:internal/streams/destroy:147:10)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
npm ERR!
npm ERR! Node.js v20.13.1

npm ERR! A complete log of this run can be found in: C:\Users\XLY\AppData\Local\npm-cache\_logs\2024-05-23T04_48_31_712Z-debug-0.log

Is there a TFJS-NODE-BASE-URI address that can be used in China

**Comment by gaikwadrahul8** [comment]
Hi, @82318179 

I apologize for the delay in responding, following the instructions mentioned in my https://github.com/tensorflow/tfjs/issues/8081#issuecomment-1827814656 with these Node.js versions `Node.js v19.9.0 `and `Node.js v18.16.1` `it should work with Python version 3.x and less than Python version 3.12.x (e.g 3.11.x,3.10.x or 3.9.x) `and at the moment it's not working as expected with `Node.js v20.9.0`

I believe you're following these official documentation [Ref-1](https://github.com/tensorflow/tfjs/tree/master/tfjs-node), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) and [node-gyp - Node.js native addon build tool for Windows](https://github.com/nodejs/node-gyp#on-windows)

In general you'll have to follow below steps to install @tensorflow/tfjs-node on Windows system:

- Edit the path user or system variable, ensure that the path to python is added to the path variable.
- Install Visual Studio community edition with desktop development with C++ [Link](https://visualstudio.microsoft.com/vs/community/)
- Install visual studio build tools with the help of Visual Studio Installer
- Ensure that node-gyp is available: `npm install -g node-gyp`
- Install tfjs-node: `npm install @tensorflow/tfjs-node`

`tfjs-node` requires AVX processors and tfjs-node library uses AVX instructions to improve the performance of its operations. If your CPU does not support AVX, as far I know you will not be able to use tfjs-node if I'm not wrong so to check AVX support please follow below steps

- Right-click on the Start button and select "System Information."
- Expand the "Processor" category in the left-hand pane.
- Look for "Instruction Set" or "Extended Instructions" in the right-hand pane. If AVX is supported, you should see it listed there (e.g., "AVX2").

**NOTE :** **If the above workaround does not work please try using your mobile phone's hotspot to connect your computer to the internet. This alternative connection might fix the installation issue.**

Please let us know after trying the above steps is it resolving your issue or not ? if not please help us with the error log to investigate this issue further

Thank you for your cooperation and patience.

**Comment by 82318179** [comment]
Why does the node version must specify v19.9.0 and Node.js v18.16.1? Why is it not supported in versions 20 and above

**Comment by gaikwadrahul8** [comment]
Hi, @82318179 

I apologize for the delayed response and at the moment temporary workaround is to use `Node.js v19.9.0` and `Node.js v18.16.1` it should work with `Python version 3.x and less than Python version 3.12.x (e.g 3.11.x,3.10.x or 3.9.x)` and at the moment it's not working as expected with Node.js v20.x.x and our team is working on this issue and will update you soon.

Thank you for your cooperation and patience.

**Comment by siakc** [comment]
This issue should be open and tagged as bug I believe.
