### ISSUE TITLE
GPU setup guide

### ISSUE THREAD

**Issue by lukemovement** [tensorflow/tfjs#8291]
I was wondering if there is an up to date installation guide for setting up TensorFlow to work with the GPU? Installing cuda changes my driver version to an unsupported one, the docker image is no longer support, and there is no mention of using TensorFlow.js with nvidia container toolkit. It seems to me this isn't supported anymore?

**Comment by gaikwadrahul8** [comment]
Hi, @lukemovement 

To ensure compatibility, have you reviewed the [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md) for this process? If so, could you please share the **operating system (OS)** and the versions of **CUDA**, **cuDNN**, and the **NVIDIA GPU driver** you are using?  <p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For GPU support, tfjs-node-gpu@1.2.4 or later requires the following NVIDIA® software installed on your system:</p>
Name | Version
-- | --
NVIDIA® GPU drivers | >450.x
CUDA® Toolkit | 11.2
cuDNN SDK | 8.1.0

Thank you for your understanding and cooperation.

**Comment by lukemovement** [comment]
> Hi, @lukemovement
> 
> To ensure compatibility, have you reviewed the [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md) for this process? If so, could you please share the **operating system (OS)** and the versions of **CUDA**, **cuDNN**, and the **NVIDIA GPU driver** you are using?
> 
> For GPU support, tfjs-node-gpu@1.2.4 or later requires the following NVIDIA® software installed on your system:
> 
> Name 	Version
> NVIDIA® GPU drivers 	>450.x
> CUDA® Toolkit 	11.2
> cuDNN SDK 	8.1.0
> 
> Thank you for your understanding and cooperation.

Driver version is 535.171.04. I can also confirm those are the versions of CUDA and cuDNN that I have attempted this with. My OS is Ubuntu 22.04.4 LTS

After running `sudo apt-get -y install cuda` (from https://developer.nvidia.com/cuda-11.2.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=debnetwork) my driver version is then changed to a version around 520, which isn't listed when I setup/change driver version. I'm unsure are to the results of the local installation option but I have spent several days repeating this process so I am certain I ran into issues with it.

**Comment by gaikwadrahul8** [comment]
Hi, @lukemovement 

I appreciate your patience in awaiting a response.

Upon reviewing the **CUDA Toolkit 11.2 Downloads** page [link](https://developer.nvidia.com/cuda-11.2.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=debnetwork), it appears that `Ubuntu 22.04` is not currently listed as a supported operating system. Supported versions include `16.04, 18.04, and 20.04.`

To isolate the potential cause of the issue, would you be able to attempt installing TensorFlow with GPU support on a system running `Ubuntu 20.04`? This will help us determine if the incompatibility lies with `CUDA Toolkit 11.2` and `Ubuntu 22.04`.

If the issue persist even with `Ubuntu 20.04`, please let us know for further investigation from our end.

Thank you for your cooperation and patience.
