### ISSUE TITLE
tf.data.array() cannot consume a Tensor, despite the documentation claiming so

### ISSUE THREAD

**Issue by AdmiralSnyder** [tensorflow/tfjs#8300]
**System information**
- windows 11, edge
- TensorFlow.js -> script link to latest (as of 2024-06-10)
- Browser version: 125.0.2535.92 (Official build) (64-bit)
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
i am trying to create a dataset from a tensor, but that failed, see code:

**Describe the expected behavior**
the dataset should be create-able

**Standalone code to reproduce the issue**
```js
let myTensor = tf.randomUniform([100], -2, 2); // returns a tensor as docs claim
// myTensor.print(); // prints the random data in this tensor
let myDataset = tf.data.array(myTensor); // returns something null-y - definitely not a dataset made from this tensor, 
console.log(myDataset); // outputs this: r {size: null}
```

**Comment by gaikwadrahul8** [comment]
Hi, @AdmiralSnyder 

I apologize for the delayed response and I was trying to replicate the same behavior from my end with your code snippet and I'm getting same result for reference I have added screenshot below:

![image](https://github.com/tensorflow/tfjs/assets/115997457/1511b2f3-904b-41e2-b796-ea87d0c13739)

When I'm trying something like below it seems like working fine, if I've missed something here please let me know. Thank you for your cooperation and patience.

![image](https://github.com/tensorflow/tfjs/assets/115997457/323f2c27-89c6-467c-a55b-94b398bb4e4b)

**Comment by AdmiralSnyder** [comment]
Hey, the documentation clearly states that data.array should be able to consume a Tensor, rather than a Tensor[]:

![image](https://github.com/tensorflow/tfjs/assets/16213022/973bc1c3-c8d0-4fd4-93b6-602fe63e5185)
Quote:
Parameters:
items (tf.void|number|string|[TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray)|[tf.Tensor](https://js.tensorflow.org/api/latest/?_gl=1*11g9tc2*_ga*NjE3MzM4ODc5LjE3MTc4Njg3ODY.*_ga_W0YLR4190T*MTcxOTMxMTEyMC42LjAuMTcxOTMxMTEyMC4wLjAuMA..#class:Tensor)|[tf.Tensor](https://js.tensorflow.org/api/latest/?_gl=1*11g9tc2*_ga*NjE3MzM4ODc5LjE3MTc4Njg3ODY.*_ga_W0YLR4190T*MTcxOTMxMTEyMC42LjAuMTcxOTMxMTEyMC4wLjAuMA..#class:Tensor)[]|{[key: string]:[tf.Tensor](https://js.tensorflow.org/api/latest/?_gl=1*11g9tc2*_ga*NjE3MzM4ODc5LjE3MTc4Njg3ODY.*_ga_W0YLR4190T*MTcxOTMxMTEyMC42LjAuMTcxOTMxMTEyMC4wLjAuMA..#class:Tensor)|number|string}[]) An array of elements that will be parsed as items in a dataset.

which I read as:
data.array consumes these types of things:
- tf.void
- number
- string
- TypedArray
- tf.Tensor  --> a single tensor
- tf.Tensor[] --> an array of tensors
- an array of objects with key - value specifications where the key is a string and the value is either a tensor or a number or a string

-> and since the simple case where you enter the single tensor into the data.array function clearly doesn't work, this is either a bug in the implementation or in the documentation
-> the workaround of putting the tensor between square brackets is not acceptable.

**Comment by shmishra99** [comment]
Hi @AdmiralSnyder , 

I apologize for the delayed response. The documentation for `tf.data.array()` clearly states that the expected parameter is an array, as you can see in the code [here](https://github.com/tensorflow/tfjs/blob/tfjs-v4.21.0/tfjs-data/src/dataset.ts#L577) and the accompanying comment. It also describes this parameter as `An array of elements that will be parsed as items in a dataset.`

May be I'm misunderstanding your question. Could you please clarify what you're finding confusing? 

Thank You!!

**Comment by AdmiralSnyder** [comment]
Hi @shmishra99 my issue is with the documentation stating certain _types_ vs. the documentation saying something (the stuff you quoted) in prose - there's a discrepancy there (or at least, there was at the point in time when i created this issue).

**Comment by shmishra99** [comment]
Hi @AdmiralSnyder , 

There doesn't seem to be any documentation update related to this issue. Could you please provide me with the expected fix or solution? I'll review it and update the documentation accordingly.

Thank You!!
