### ISSUE TITLE
BlazePose doesn't work in Firefox for Android

### ISSUE THREAD

**Issue by Skizy** [tensorflow/tfjs#8303]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Xiaomi Mi 9
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.20.0
- Pose-detection library version: 2.1.3
- Browser version: Firefox for Android 127.0
- Tensorflow.js Converter Version: 4.20.0

**Describe the current behavior**
Using BlazePose as the model for pose detection always returns an empty array in Firefox on Android when passing a video element with src attribute (works correctly when using live camera and srcObject) (I should also add that it's an mp4 h.264 video file. I have also tried using webm, still doesn't work)
It also works correctly in Chrome for Android

**Describe the expected behavior**
It should return an array with a Pose object

**Standalone code to reproduce the issue**
```typescript
import * as poseDetection from "@tensorflow-models/pose-detection";
import * as tf from "@tensorflow/tfjs-core";
import "@tensorflow/tfjs-backend-webgl";

async function main() {
        document.body.innerHTML = '<div id="app"></div>';
        const container = document.getElementById("app")!;

	const video = document.createElement("video");
	video.src = "/public/yoga.mp4";
	video.muted = true;
	container.appendChild(video);

	const p = document.createElement("p");
	container.appendChild(p);

	await new Promise((resolve) => {
		video.addEventListener(
			"loadeddata",
			() => {
				video.width = video.videoWidth;
				video.height = video.videoHeight;

				resolve(null);
			},
			{ once: true },
		);
	});

	const detector = await createDetector();

	async function estimate() {
		const poses = await detector.estimatePoses(video);

		p.innerText = JSON.stringify(poses);

		requestAnimationFrame(estimate);
	}

	video.play();

	requestAnimationFrame(estimate);
}

async function createDetector() {
	await tf.setBackend("webgl");

	await tf.ready();

	const detector = await poseDetection.createDetector(
		poseDetection.SupportedModels.BlazePose,
		{
			runtime: "tfjs",
			modelType: "heavy",
		},
	);

	return detector;
}

main();
```

**Other info / logs**
The only log is a warning:
`Platform browser has already been set. Overwriting the platform with browser.`

**Comment by gaikwadrahul8** [comment]
Hi, @Skizy 

I apologize for the delayed response and I was trying to replicate the same behavior from my end with this [demo](https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=blazepose) with below options with `Firefox browser 127.0 (64-bit)` on desktop and it's working as expected :

**Model :BlazePose
Type: full
Runtime Backend :mediapipe-gpu, tfjs-webgl,tfjs-webgpu**

If possible could you please give it try with [BlazePose-MediaPipe](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/blazepose_mediapipe) and just change runtime to `runtime: "mediapipe"` and see is it working fine for `Firefox for Android 127.0`  ? also try by changing Firefox for Android version to lower than 127.0

```
const detector = await poseDetection.createDetector(
		poseDetection.SupportedModels.BlazePose,
		{
			runtime: "mediapipe",
			modelType: "heavy",
		},
	);

```

Thank you for your cooperation and patience.
