### ISSUE TITLE
tf.memory reports incorrect value for numBytesInGPU when using quantized weights

### ISSUE THREAD

**Issue by nrothGIT** [tensorflow/tfjs#831]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.2

### Browser version
Version 70.0.3538.67 (Official Build) (64-bit)

#### Describe the problem or feature request
I take a model trained in tensorflow, and run the tensorflowjs_converter with quantization_bytes=1. When doing so, I observe that the weights on disk are in fact 1/4 the size of the weights without quantization. Further, the output of the model when I run it does subtly change, confirming that the graph operations are being done in lower precision. However, the numBytesInGPU reported by tf.memory doesn't change, regardless of whether I quantize my model or not. 

I'm guessing(?) this is because the code to calculate bytes [https://github.com/tensorflow/tfjs-core/blob/v0.13.0/src/kernels/backend_webgl.ts#L1697](url) uses the dtype of the variable, which will be the original, pre-quantization value, i.e weight_manifest file looks like this:

{"dtype": "float32", "shape": [100], "name": "some/var", "quantization": {"dtype": "uint8", "scale": 0.1, "min": 0.75}}

Thanks for the help and working on the project!! It's super cool. 

Whereas we should be using the quantization type field.

**Comment by nsthorat** [comment]
Currently we only quantize over the wire, we immediately de-quantize on the other side (it's a network request latency optimization).

Soon we'll tackle activations themselves! Hope this answers the question.

**Comment by nrothGIT** [comment]
OK, that makes sense. Thanks for writing back 💯

**Comment by nsthorat** [comment]
Going to close this out, please re-open another issue if you are having any other problems :)
