### ISSUE TITLE
Accuracy issue

### ISSUE THREAD

**Issue by vish-n-u-k** [tensorflow/tfjs#8315]
I am having an issue with accuracy for my image recognition,
I am using teachable machine with tenserflowjs for my frontend app which can recognise image and categorize it accordingly,

It works perfectly in teachable machine web but I am facing issue when I use it in my app, what can I do to improve the accuracy of the prediction.

**Comment by gaikwadrahul8** [comment]
Hi, @vish-n-u-k 

I apologize for the delayed response and thank you for bringing this issue to our attention, could you please help us with your Github repo or code snippet along with complete steps to replicate the same behavior from our end to investigate this issue further as soon as possible ?

Thank you for your cooperation and patience.
