### ISSUE TITLE
tfjs.converters.save_keras_model producing model.json file that does not parse properly.

### ISSUE THREAD

**Issue by imcnaugh** [tensorflow/tfjs#8328]
**System information**
Ubuntu 24.04 LTS
Python 3.12.4
tensorflow 2.16.1
tensorflowjs 4.6.0

**Describe the current behavior**
models built in python and converted to tfjs models using `tfjs.converters.save_keras_model(model, 'tfjs-model')` are not loading properly.

**Describe the expected behavior**
I would expect to be able to load a model.json using `await tf.loadLayersModel()` file created with `tfjs.converters.save_keras_model()` in python to load and run properly in tfjs.

**Standalone code to reproduce the issue**
I have a github with a small demo project located [here](https://github.com/imcnaugh/tfjs_issue_demo)

**Other info / logs** Include any logs or source code that would be helpful to
I run into an issue when attempting to load a model.json file with `await tf.loadLayersModel()` The initial error i get is

ValueError: An InputLayer should be passed either a `batchInputShape` or an `inputShape`.

but there appears to be another issue as well.

in the [demo project](https://github.com/imcnaugh/tfjs_issue_demo) i have created I better explain how i am generating the model.json file and how i am loading it. as well as the issues I believe there to be and resolution steps I think should be taken. 

Effectively it boils down to 2 issues in the model.json that is saved, when using `tfjs.converters.save_keras_model()`

 - Nodes with the name `batch_shape` need to be renamed to `batch_input_shape`
 - The `inbound_nodes` array that are saved are to complex.
 
 The save method produces
 ```json
"inbound_nodes": [
  {
    "args": [
      {
        "class_name": "__keras_tensor__",
        "config": {
          "shape": [
            null,
            1
          ],
          "dtype": "float32",
          "keras_history": [
            "input_layer",
            0,
            0
          ]
        }
      }
    ],
    "kwargs": {}
  }
]
```

but when I modify it to look similar to the following: thing work
```json
"inbound_nodes": [
  [
    [
      "input_layer",
      0,
      0
    ]
  ]
]
```

**Comment by imcnaugh** [comment]
Also just to link other documentation, this issue was discussed on the [tensorflow.org forums](https://discuss.tensorflow.org/t/corrupted-configuration-and-batch-input-shape-loading-pre-trained-layers-model-in-tensorflow-js/24977)

**Comment by imcnaugh** [comment]
Sorry for the extra mess, on the Tensorflow forums I was pointed to more documentation that I was not reading,

the cause of this was Tensorflow 2.16.x pulls keras 3.x by default, but the converter needs keras 2.x

in the [keras docs here](https://keras.io/getting_started/) it recommends running python with the environment available `TF_USE_LEGACY_KERAS=1`, that solves my issue.

**Comment by doiko** [comment]
Hi there,
I do not believe that this a proper solution.
Do we expect a fix?

**Comment by imcnaugh** [comment]
Hello @doiko 

Could you provide some more information on your situation?

Did adding the environment variable `TF_USE_LEGACY_KERAS=1` when training your model not fix your issue?

**Comment by doiko** [comment]
Hello @imcnaugh,
Setting `TF_USE_LEGACY_KERAS=1` is akin to remaining in a TensorFlow environment earlier than version 2.16. We see no reason to move to 2.16 only to use such a flag. 
Ours production code is currently on `tensorflow` version 2.13 and we decided it was time to transition to `Keras 3`, which requires TensorFlow versions above 2.16. All our pipelines, training processes, and user model deployments in JS have been functioning well for the past four years. However, we are encountering significant challenges in upgrading to `TensorFlow > 2.16` and `Keras 3.4.x`. Although we have resolved many issues during this transition, the final hurdle remains converting models to JS, which we have yet to overcome.

**Comment by imcnaugh** [comment]
If I am reading kears documentation correctly, setting the enviorment varaible will tell kears to revert back to 2.x logic and not the 3.x version that is brough in by default from TF 2.16

I would need to dig a bit deeper to confirm, maybe somebody else can, but reading the code where that flag is read, it appears to confirm this. https://github.com/tensorflow/tensorflow/blob/e566986d52dc9d3678c03417fac5cb7fba6a02d0/tensorflow/python/util/lazy_loader.py#L129

It looks like we still get all the nifty-ness of TF 2.16, its just our kears wrapper is stuck in tf_kears world and we cant get kears 3 just yet.

All that said, ill bet it would be a simple fix to write a kears 3 model object to the json tfjs is expecting in the `loadLayersModel()` method. I documented the issues I found with the json in the first post of this issue. If I had to guess, it looks like some of the kears 3 objects have changed and are serilizing to json a bit different.

**Comment by doiko** [comment]
Hi @gaikwadrahul8,
Based on @imcnaugh's comments, do you think we'll see a Keras 3 model converter soon? Whether it supports the .h5 or .keras formats would be fine, although I've read that .h5 is now considered a legacy format. Any insights on this would be appreciated!
