### ISSUE TITLE
Could you please extend the tf.loadGraphModel that can load parsed JSON data ?

### ISSUE THREAD

**Issue by noma6386-duplicate** [tensorflow/tfjs#8332]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):  4.20.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
-> Using tfjs in chrome extension app,
     For security reasons, the model.json file needs to be encrypted.
     The encryption and decryption process is complete.
     However, 'loadGraphModel' only accepts a URL to load the model.json file.
     
  e.g.
     const encryptionKey = 'somesecuritykey'
     //  read a encrypted model.json file.
     const encryptedData = 'FERSTxcfvafxw243fasd==vcvsdf2sat';
     // decrypted.
     const decryptedBytes = CryptoJS.AES.decrypt(encryptedData, encryptionKey);
     //
     const decryptedData = JSON.parse(decryptedBytes.toString(CryptoJS.enc.Utf8));

    // It would be nice if we could load the decrypted JSON like this.
    this.model = await tf.loadGraphModel(decryptedData, { LoadingType: 'json' });

**Will this change the current api? How?**
  -> Currently it only accepts URL types.
  -> It would be nice if 'loadGraphModel' had a loading type like json.

**Who will benefit with this feature?**
  -> People who want to protect their AI model data.
  -> It should be encrypted for security reasons.
 
**Any Other info.**

thank you.

**Comment by noma6386-duplicate** [comment]
tried this... it gave me an error

// * Convert JSON Data to ArrayBuffer:
const jsonString = JSON.stringify(decryptedData);
const buffer = new TextEncoder().encode(jsonString);
const arrayBuffer = buffer.buffer;  // Get the ArrayBuffer from the buffer

async function loadModel() {
    try {
        const model = await tf.loadGraphModel(arrayBuffer);
        return model;
    } catch (error) {
        console.error('Error loading the model:', error);
        throw error; 
    }
}

this.loadModel(arrayBuffer).then(
               model => {
                  console.log('Model loaded successfully:', model);

                  this.model = model

                  tf.tidy(() => {
                     const [modelWidth, modelHeight] = this.model.inputs[0].shape.slice(1, 3)
                     //console.log("ref_size:", modelHeight)
                     ref_size = modelHeight;
                     this.model.predict(tf.zeros([1, ref_size, ref_size, 3]));

                     this.canvas.width = ref_size;
                     this.canvas.height = ref_size;
                  });

               }).catch(error => {
                  console.error('Error loading the model:', error);
               });

error was 
 -> TypeError: url.startsWith is not a function,  at the indexed_db.ts:234:36

**Comment by noma6386-duplicate** [comment]
Found the solution with custom IO loading method.

And found that I had to do JSON.parse() twice like below.

const stillString = JSON.parse(decryptedBytes.toString(CryptoJS.enc.Utf8));
const decryptedData = JSON.parse(stillString);


Thank you.

**Comment by gaikwadrahul8** [comment]
Hi, @noma6386-duplicate 

I apologize for the delay in my response and good to hear that your issue got resolved and You're right, currently `tf.loadGraphModel` in TensorFlow.js only accepts a URL to load the model. While there is not a built-in way to directly load parsed JSON data but there are a couple of workarounds you can consider for your Chrome extension app with encrypted model data the one you already found.

Another one is If I'm not wrong after decrypting the model JSON data you can try by creating a temporary file in your Chrome extension's storage using the `FileSystem` API and Write the decrypted JSON data to this temporary file after that load model from temporary file using `tf.loadGraphModel` with the URL pointing to the temporary file location within the extension's storage. 

Once the model is loaded, you can delete the temporary file. you can do something like below 

```
const encryptionKey = 'somesecuritykey';
const encryptedData = 'FERSTxcfvafxw243fasd==vcvsdf2sat';

// Decrypt and create temporary file
const decryptedBytes = CryptoJS.AES.decrypt(encryptedData, encryptionKey);
const decryptedData = JSON.parse(decryptedBytes.toString(CryptoJS.enc.Utf8));

chrome.storage.local.set({ modelJson: decryptedData }, () => {
    chrome.storage.local.get(['modelJson'], (data) => {
        const tempFilePath = URL.createObjectURL(new Blob([JSON.stringify(data.modelJson)], { type: 'application/json' }));
        tf.loadGraphModel(tempFilePath).then(model => {
            // Use the loaded model
            // ...
            chrome.storage.local.remove('modelJson'); // Cleanup temporary data
        });
    });
});

```

I'm glad you were able to find a workaround that addresses your issue! If everything is functioning as expected, please feel free to close this issue.  if you need further assistance with TensorFlow.js in the future, please don't hesitate to create a new [issue](https://github.com/tensorflow/tfjs/issues/new/choose).

Thank you for your cooperation and patience.

**Comment by noma6386-duplicate** [comment]
Thank you ~
