### ISSUE TITLE
How to save the model `@tensorflow-models/pose-detection` locally for offline use?

### ISSUE THREAD

**Issue by ZhongxuYang** [tensorflow/tfjs#8334]
I want to save the [tfjs-models](https://github.com/tensorflow/tfjs-models)'s models in the public dir of the frontend project, so that they can be used in a netless environment. How should I do it?

- I tried to [save model](https://www.tensorflow.org/js/guide/save_load#native_file_system_nodejs_only), but because `@tensorflow-models/pose-detection` does not provide a save function, I didn't know how to proceed.

**Comment by gaikwadrahul8** [comment]
Hi, @ZhongxuYang 

Thank you for bringing this issue to our attention and as far I know, you can download model from kaggle here is [link](https://www.kaggle.com/models?task=16713) and please make sure select only Model Variations as TensorFlow.js option and download whichever model you want to use and once model got downloaded then please try to load the model with the help of below code snippet and it should work

```
const tf = require('@tensorflow/tfjs-node');

const modelPath = '/path/to/your/model.json';
const handler = tf.io.fileSystem(modelPath);
const model = await tf.loadLayersModel(handler);
```
If issue still persists please let us know with error log for further investigation.

Thank you for your cooperation and patience.

**Comment by ZhongxuYang** [comment]
> Hi, @ZhongxuYang
> 
> Thank you for bringing this issue to our attention and as far I know, you can download model from kaggle here is [link](https://www.kaggle.com/models?task=16713) and please make sure select only Model Variations as TensorFlow.js option and download whichever model you want to use and once model got downloaded then please try to load the model with the help of below code snippet and it should work
> 
> ```
> const tf = require('@tensorflow/tfjs-node');
> 
> const modelPath = '/path/to/your/model.json';
> const handler = tf.io.fileSystem(modelPath);
> const model = await tf.loadLayersModel(handler);
> ```
> 
> You can also load a model composed of Layer objects, including its topology and optionally weights by below options also please refer to [tf.loadLayersModel](https://js.tensorflow.org/api/4.20.0/#loadLayersModel) for examples :
> 
> 1. Load a model from an HTTP server.
> 2. Save model's topology and weights to browser [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage); then load it back.
> 3. Saving model's topology and weights to browser [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API); then load it back.
> 4. Load a model from user-selected files from HTML [file input elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file).
> 
> If issue still persists please let us know with error log for further investigation.
> 
> Thank you for your cooperation and patience.

Thank you for your patient reply!

I have followed your tips to fulfill my needs. Proceed as follows:

1. download model from kaggle here is [link](https://www.kaggle.com/models?task=16713) 
2. Pass the `detectorConfig` argument to the `poseDetection.createDetector` function call.

```ts
const loadHandpose = async () => {
  const detectorConfig: MoveNetModelConfig = {
    modelUrl: '/your/public/path',
  }
  detector = await poseDetection.createDetector(model, detectorConfig)
  startDetect()
}
```
