### ISSUE TITLE
fresh react native install (18.2.0 / 0.74.3) and tfjs 4.20 issue

### ISSUE THREAD

**Issue by philippogol** [tensorflow/tfjs#8344]
I'm encountering a constant error while fresh starting a new project. These are the dependencies:

  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.24.0",
    "@tensorflow/tfjs": "^4.20.0",
    "@tensorflow/tfjs-react-native": "^1.0.0",
    "react": "18.2.0",
    "react-native": "0.74.3"
  }

Making a simple addition using or just loading the package library throws the error **"Cannot read property 'isTypedArray' of undefined**. I tried different things and is not working, has someone experienced something like this or has a solution? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @philippogol 

I apologize for the delay in my response and if possible could you please give it try with mentioned package dependancies [here](https://github.com/paradite/tfjs-sample-expo-app/blob/main/package.json) and see is it resolving your issue or not ? 

If issue still persists please help us with complete error log and steps with your Github repo to replicate the same behavior from our end to investigate this issue further.

Thank you for your cooperation and patience.

**Comment by shmishra99** [comment]
> hey @gaikwadrahul8 thanks for the coming back, its actually pretty forward and i think it should an easy fix. here are the steps and code im using for a simple tensorflow loading model (im avoiding expo since it should be possible to use tensorflow without any expo package)
> 
> 1. npx react-native init tensorflowApp
> 2. npm install @react-native-async-storage/async-storage @tensorflow/tfjs @tensorflow/tfjs-react-native
> 3. cd ios/ & pod install
> 4. all code in App.tsx (starting tensorflow and loading model, see in repo)
> 
> In get the error: "Console Warning Possible unhandled promise rejection (id: 0): TypeError: Cannot read property 'fetch' of undefined" (see attachment). ![IMG_3944](https://private-user-images.githubusercontent.com/5264966/354738435-79a281ef-9f46-4ed4-a3ff-c45f5ee2ba6f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njg2NTEsIm5iZiI6MTcyNDg2ODM1MSwicGF0aCI6Ii81MjY0OTY2LzM1NDczODQzNS03OWEyODFlZi05ZjQ2LTRlZDQtYTNmZi1jNDVmNWVlMmJhNmYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTgwNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzViOTBjNDQxY2Y1ZGRmNWIxZDE4YTMzZjRjYTNiZjNiZDI5MDhiMDJmMTQ5NmU2MTUzY2RmYjlhZGQwZTcwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LE4jAPE269lQio2n46KFtULGG8uMP7cqh7K07YuUs_g)
> 
> repo: https://github.com/philippogol/reactnative-tensorflow

Hi @philippogol , 

Apologies for the delayed response. I am unable to replicate the issue on my system, i'm encountering a different error. 

The warning message `Console Warning Possible unhandled promise rejection (id: 0): ` suggests that the promise from `await tf.ready()` might be rejected, which indicates that TensorFlow.js was not successfully initialized. This failure could be causing the error `TypeError: Cannot read property 'fetch' of undefined.`

You could use following set of code to check what exactly casuing the error. 

```
  tf.ready().then(async  ()=>{
    setIsTfReady(true);
    // Load the MobileNet model
    const model = await tf.loadLayersModel('https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json');
    setModel(model);
  }).catch(e=> console.log('Error while loading the tf dependencies.',e));

```
Let me know if it helps. Thank You!!!

**Comment by lucksp** [comment]
@philippogol @gaikwadrahul8 I am having similar issues, as logged in #8429 


> Could you please give it try with mentioned package dependancies [here](https://github.com/paradite/tfjs-sample-expo-app/blob/main/package.json) and see is it resolving your issue or not ?

I cannot downgrade my current environment, so it leads me to believe that there is some incompatibility with new versions of React Native

**Comment by haelsisy** [comment]
I have the same issue with `"react-native": "0.76.1"` "Cannot read property 'isTypedArray' of undefined

**Comment by khalid999devs** [comment]
Hi, in latest versions of react native and expo 53, while using, const TensorCamera = cameraWithTensors(CameraView); facing the error for CameraView. Want a solution please

<img width="690" height="21" alt="Image" src="https://github.com/user-attachments/assets/d520d527-f603-4b4b-a9fb-a9381c950679" />
