### ISSUE TITLE
 Error: The implicit shape can't be a fractional number.

### ISSUE THREAD

**Issue by songyanbei** [tensorflow/tfjs#8346]
System information

- TensorFlow.js version: 4.20.0

I'm encountering an error while feed a full zero tensor  into model, the INPUT_IMAGE_SIZE==640

![image](https://github.com/user-attachments/assets/68b63742-831b-4caa-8e92-f17bffd95115)
![image](https://github.com/user-attachments/assets/a1f22b96-c1e3-4fa5-9d5f-157a247d076c)

**Comment by songyanbei** [comment]
[test.html.zip](https://github.com/user-attachments/files/16468189/test.html.zip)
Hi,@gaikwadrahul8 
This is a test page. Extract it to your local machine and open it in a browser. Wait a few minutes for the model to finish downloading. You can see error messages in the console interface of the browser's developer mode.
![截屏2024-08-02 下午4 55 00](https://github.com/user-attachments/assets/6654e49d-8e61-4302-b101-f2ccae9554d3)

**Comment by gaikwadrahul8** [comment]
Hi, @songyanbei 

Thank you for providing the code snippet to reproduce the same behavior from our end and I'm able to replicate the same issue from my end so we'll have to dig more into this issue, thank you for bringing this issue to our attention, I really appreciate your valuable time and efforts.

For reference I have added screenshot below :

![image](https://github.com/user-attachments/assets/34fb6a0a-f0b1-4d95-8d66-9aa4531ea012)


Thank you for your cooperation and patience.

**Comment by Varun-S10** [comment]
Hi @songyanbei, Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @songyanbei, Thank you for raising this issue. We have reproduced the problem, which happens because the model expects the input shape as [1, 640, 640, 3] instead of [1, 3, 640, 640]. Changing the input tensor dimensions to [1, 640, 640, 3] and waiting for tf.ready() resolves the error. Could you please try this workaround and let us know if it works for you?
