### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'env().platform.encode')

### ISSUE THREAD

**Issue by gameveloster** [tensorflow/tfjs#8349]
I'm having issues using tfjs in Expo app.

Getting the error:

> TypeError: undefined is not an object (evaluating 'env().platform.encode')

when trying to use `tf.util.encodeString`:

```js
import * as tf from "@tensorflow/tfjs";
import * as ImageManipulator from "expo-image-manipulator";

export default function MyScreen() {
    const resizedImage = await ImageManipulator.manipulateAsync(
        imageUri,
        [{ resize: { width: 640, height: 640 } }],
        { format: ImageManipulator.SaveFormat.PNG, base64: true }
    );

    const imgBuffer = tf.util.encodeString(
        resizedImage.base64,
        "base64"
    ).buffer;

    // ...
}
```

Anyone encountered this before?

My app has installed `expo@51.0.13`, `@tensorflow/tfjs@4.20.0`

**Comment by shmishra99** [comment]
Hi @gameveloster, 

Apologies for the delayed response.

I was able to successfully convert the **base64 image string** into a base64 **Uint8Array**  using the code snippet you provided. Here is the code I used:

```
const resizedImage = await ImageManipulator.manipulateAsync(
  selectedImage,
  [{ resize: { width: 640, height: 640 } }],
  { format: ImageManipulator.SaveFormat.PNG, base64: true }
);
const resizedImagBase = resizedImage.base64 ??  ''; 
console.log("resizedImage..", resizedImagBase)
const imgBuffer = tf.util.encodeString( resizedImagBase
  , 'base64').buffer;
console.log("imgBuffer",imgBuffer)
```

This code results in a `Uint8Array`, as shown in the attached image.

<img width="945" alt="image" src="https://github.com/user-attachments/assets/901786f1-056f-41e9-b802-fe965b8f689c">

The error suggests that the env() function might not be properly initialized, as referenced in [environment.ts](https://github.com/tensorflow/tfjs/blob/tfjs-v4.20.0/tfjs-core/src/environment.ts#L212). 

Please try the following troubleshooting steps:

     1) Delete your node_modules folder.
     2) Remove the package-lock.json or yarn.lock file.
     3) Reinstall all dependencies using `npm install`.
     
Let me know if this resolves the issue.

Thank you!
