### ISSUE TITLE
Error Server

### ISSUE THREAD

**Issue by SinSethh** [tensorflow/tfjs#8354]
**Hello, I have this problem with tensorflow. Do you have a solution to offer me please ?**

My processor is AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, 2100 MHz --> AVX is ok

node:internal/modules/cjs/loader:1454
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\xxx\xxx\server\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\xxx\xxx\server\node_modules\@tensorflow\tfjs-node\dist\index.js:72:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.16.0

**package.json :** 

{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nestjs/common": "^10.3.10",
    "@nestjs/core": "^10.3.10",
    "@nestjs/platform-express": "^10.3.10",
    "@nestjs/platform-socket.io": "^10.3.10",
    "@nestjs/serve-static": "^4.0.2",
    "@nestjs/websockets": "^10.3.10",
    "@tensorflow/tfjs": "^4.20.0",
    "@tensorflow/tfjs-node": "^4.20.0",
    "@tensorflow/tfjs-node-gpu": "^4.20.0",
    "axios": "^1.7.3",
    "bcrypt": "^5.0.1",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "csv-writer": "^1.6.0",
    "dotenv": "^16.0.0",
    "engine.io": "^6.6.0",
    "express": "^4.19.2",
    "fast-csv": "^5.0.1",
    "mongodb": "^6.8.0",
    "mongoose": "^8.5.2",
    "node-fetch": "^3.3.2",
    "nodemon": "^3.1.4",
    "plotly": "^1.0.6",
    "sklearn": "^0.4.0",
    "socket.io": "^4.7.5",
    "socket.io-parser": "^3.3.4",
    "validator": "^13.7.0",
    "ws": "^8.18.0"
  }
}

**Comment by SinSethh** [comment]
I have move this tensorflow.dll from C:\Users\guewe\sinseth-sport\server\node_modules\@tensorflow\tfjs-node\deps\lib to C:\Users\guewe\sinseth-sport\server\node_modules\@tensorflow\tfjs-node\lib\napi-v8

**Comment by dotunlonge** [comment]
> I have move this tensorflow.dll from C:\Users\guewe\sinseth-sport\server\node_modules@tensorflow\tfjs-node\deps\lib to C:\Users\guewe\sinseth-sport\server\node_modules@tensorflow\tfjs-node\lib\napi-v8

Did this solve it ?

**Comment by gaikwadrahul8** [comment]
Hi, @SinSethh, @dotunlonge 

Thank you for bringing this issue to our attention, I see you're trying with Node.js version `v20.16.0` as far I know at the moment TensorFlow.js does not support Python Version 3.12.x so please try to use Python version from 3.7.x to 3.11.x and also downgrade Node.js version to either `v20.15.0` or `v19.9.0 ` 

 1. If you don't want to rebuild everything from scratch then please try to copy `tensorflow.dll` in this location `node_modules\@tensorflow\tfjs-node\lib\napi-v8\` (in `napi-v8` folder) you can try below command to copy `tensorflow.dll` into `napi-v8` folder.

`cp node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll node_modules\@tensorflow\tfjs-node\lib\napi-v8\`

2. If you're looking rebuild everything from scratch then please try below workaround :

```
npm install
npm update
npm rebuild bcrypt --build-from-source
npm rebuild @tensorflow/tfjs-node build-addon-from-source
```

Please give try it with above workaround and let us know is it working as expected or not ? 

Thank you for your understanding and patience.

**Comment by SinSethh** [comment]
> > I have move this tensorflow.dll from C:\Users\guewe\sinseth-sport\server\node_modules@tensorflow\tfjs-node\deps\lib to C:\Users\guewe\sinseth-sport\server\node_modules@tensorflow\tfjs-node\lib\napi-v8
> 
> Did this solve it ?

Yes it's solved

I use Python 3.11 and Node js 20 😉

**Comment by SinSethh** [comment]
> Salut,@SinSethh,@dotunlonge
> 
> Merci d'avoir attiré notre attention sur ce problème, je vois que vous essayez avec la version Node.js. `v20.16.0`Pour autant que je sache, pour le moment, TensorFlow.js ne prend pas en charge la version Python 3.12.x. Essayez donc d'utiliser la version Python de 3.7.x à 3.11.x et rétrogradez également la version Node.js vers l'une `v20.15.0`ou l'autre.`v19.9.0 `
> 
> 1. Si vous ne souhaitez pas tout reconstruire à partir de zéro, essayez de copier `tensorflow.dll`à cet emplacement `node_modules\@tensorflow\tfjs-node\lib\napi-v8\`(dans `napi-v8`le dossier), vous pouvez essayer la commande ci-dessous pour copier `tensorflow.dll`dans `napi-v8`le dossier.
> 
> `cp node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll node_modules\@tensorflow\tfjs-node\lib\napi-v8\`
> 
> 2. Si vous cherchez à tout reconstruire à partir de zéro, veuillez essayer la solution de contournement ci-dessous :
> 
> ```
> npm install
> npm update
> npm rebuild bcrypt --build-from-source
> npm rebuild @tensorflow/tfjs-node build-addon-from-source
> ```
> 
> Veuillez essayer la solution de contournement ci-dessus et faites-nous savoir si cela fonctionne comme prévu ou non ?
> 
> Merci pour votre compréhension et votre patience.

Thank you but it's solved. I moved tensorflow.dll

I use python 3.11 and Node 20 !

**Comment by gaikwadrahul8** [comment]
Hi, @SinSethh

We're glad to hear that moving the `tensorflow.dll` file to the `node_modules\@tensorflow\tfjs-node\lib\napi-v8\`  **(napi-v8)** directory resolved your issue. Please feel free to close this issue. If you encounter any further challenges with TensorFlow.js please don't hesitate to open a [new issue](https://github.com/tensorflow/tfjs/issues/new/choose).

Thank you for your cooperation and patience.

**Comment by kenzaflow** [comment]
Sorry but same here

doing the same as OP fixes the problem

why does this happen?
