### ISSUE TITLE
Converted Model Using TensorFlow.JS Converter Not Working

### ISSUE THREAD

**Issue by TheRealCasmat** [tensorflow/tfjs#8358]
Hey There!

I was following the [TFJS WebML YT Course from Jason Mayes](https://www.youtube.com/playlist?list=PLOU2XLYxmsILr3HQpqjLAUkIPa5EaZiui) and following along to the [TFJS Converter video](https://youtu.be/EODze80347w?si=tUr-AYzs2tY5kGRo), here's my notebook:
[Google Colab Notebook](https://colab.research.google.com/drive/1d_sy_wc31Fgewm-l6VdQmArsy3EFP7us?usp=sharing)

Basically it is an exact replica from the video and with a few extra warnings here and there, the model files were generated:
[MobileNetV2.zip](https://github.com/user-attachments/files/16571274/MobileNetV2.zip)

On my site, I used TFJS with `tf.loadLayersModel('URL OF MODEL.JSON')` but an error was given saying an InputLayer should have been passed either a `batchInputShape` or an `inputShape`. There is a `batch_shape` in the model.json though. TFJS is up to date, no clue whats going on.

I am trying to convert a MobileNetV3-Large actually but the same thing happened too and I was left with this (using same notebook as earlier but replacing `tf.keras.applications.MobileNetV2` with `tf.keras.applications.MobileNetV3Large`, but got same results as earlier):
[MobileNetV3-Large.zip](https://github.com/user-attachments/files/16571281/MobileNetV3-Large.zip)

Any help appreciated! This is probably just me stupid as I'm learning TF/TFJS and ML in general, so sorry in advance!

Have a good one,
-- @TheRealCasmat

**Comment by shmishra99** [comment]
Hi @TheRealCasmat , 

I have reproduced the error you are experiencing.

The error `Error loading model: Error: An InputLayer should be passed either a batchInputShape or an inputShape` indicates that the TensorFlow.js converter cannot determine the expected input shape for your model. This is because `model.save()` does not save the InputLayer explicitly, only the model architecture and weights. 

You can use the following code snippet to save your model:

```
import os
import tensorflow as tf
model = tf.keras.applications.MobileNetV2(
  input_shape=(224, 224, 3), weights='imagenet', classifier_activation='softmax'
)
tf.saved_model.save(model, 'sample_data/tf_model')
```

This will generate a graph model file. You can then convert your model to TensorFlow.js using:

```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model sample_data/tf_model/ sample_data/tfjs_model

```
You can then use this model like this:

```
async function loadModel() {
  const model = await tf.loadGraphModel('sample_data/tfjs_model/model.json')
  console.log("model...!!", model)
}
loadModel()

```

Output:

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/fbc1e318-ea9b-4fa4-b6cd-4cdbf1465106">



The [documentation](https://www.tensorflow.org/js/guide/conversion#:~:text=const%20model%20%3D%20await%20tf.loadGraphModel(%E2%80%98path/to/model.json%E2%80%99)%3B) provides more detailed information.. 

Let me know if this helps. Thanks You!!

**Comment by gaikwadrahul8** [comment]
Hi, @TheRealCasmat 

I tried to replicate to the same behavior from my end and I'm able to replicate the same behavior with your provided [colab notebook](https://colab.research.google.com/drive/1d_sy_wc31Fgewm-l6VdQmArsy3EFP7us?usp=sharing) but I see after installing the latest TensorFlow.js version, it's installing the `keras version 3` and as far I know `tfjs_converter` compatible with `keras 2 version` at the moment so I downgraded the TensorFlow version to `2.15.0` in which it will download `keras 2.15.0 version `which compatible for `tfjs_converter` and I converted model to TensorFlow.js format, it's working as expected please refer this [gist-file ](https://colab.sandbox.google.com/gist/gaikwadrahul8/096a2710166b7110e3693aae0fe8a260/test-issue-8358.ipynb), Please give it try from your end and it should work.

If issue still persists please let us know with error log to investigate this issue further from our end.

**For your reference I have added screenshot below :**

![image](https://github.com/user-attachments/assets/1dc3215e-2422-4089-ae63-4d58e56f330a)

Thank you for your cooperation and patience.

**Comment by TheRealCasmat** [comment]
Hey!

Sorry for the delayed response, but the MobileNetV3 cannot be converted with the gist-file you provided. When doing so, the console returns:
```
Uncaught (in promise) Error: Unknown layer: Rescaling. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at rD (generic_utils.js:243:13)
    at sM (serialization.js:31:10)
    at u (container.js:1206:11)
    at t.fromConfig (container.js:1234:7)
    at rD (generic_utils.js:278:11)
    at sM (serialization.js:31:10)
    at models.js:295:7
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
```

Thanks!
-- @TheRealCasmat

**Comment by shmishra99** [comment]
Hi @TheRealCasmat, 

I successfully converted the `MobileNetV3Large` model using tfjs_converter. Please follow the instructions in this [gist](https://colab.sandbox.google.com/gist/shmishra99/f5537b4346bef619ee6ad3724451ce24/test-issue-8358.ipynb#scrollTo=sp468uZSZFxT) to replicate the process.

Let me know if it works for you.

Thank you!

**Comment by TheRealCasmat** [comment]
Thanks @shmishra99!! Been stuck for days but now able to move on with my project! Thanks @gaikwadrahul8 for your help as well!

Thanks,
-- @TheRealCasmat

**Comment by nandikawis** [comment]
> Hi, @TheRealCasmat
> 
> I tried to replicate the same behavior from my end and I'm able to replicate the same behavior with your provided [colab notebook](https://colab.research.google.com/drive/1d_sy_wc31Fgewm-l6VdQmArsy3EFP7us?usp=sharing) but I see after installing the latest TensorFlow.js version, it's installing the `keras version 3` and as far I know `tfjs_converter` compatible with `keras 2 version` at the moment so I downgraded the TensorFlow version to `2.15.0` in which it will download `keras 2.15.0 version `which compatible for `tfjs_converter` and I converted model to TensorFlow.js format, it's working as expected please refer this [gist-file ](https://colab.sandbox.google.com/gist/gaikwadrahul8/096a2710166b7110e3693aae0fe8a260/test-issue-8358.ipynb), Please give it try from your end and it should work.
> 
> If issue still persists please let us know with error log to investigate this issue further from our end.
> 
> **For your reference I have added screenshot below :**
> 
> ![image](https://private-user-images.githubusercontent.com/115997457/357761602-1dc3215e-2422-4089-ae63-4d58e56f330a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDYwMjcsIm5iZiI6MTcyOTcwNTcyNywicGF0aCI6Ii8xMTU5OTc0NTcvMzU3NzYxNjAyLTFkYzMyMTVlLTI0MjItNDA4OS1hZTYzLTRkNThlNTZmMzMwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNzQ4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmE0OGI3NjI1YjMxOGRjY2NjZGRmYWViNDc2MDg1ZmEwNzgxMTI3NTFkZTgxNjc2NzU4NTIxMDM5NTEzNDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XItbTkb8UCKD4x1kn8eM18214epXIUNs512cXxt9Iao)
> 
> Thank you for your cooperation and patience.

Hi i wanna ask you about how we saved the model before we convert it into the tensorflow js, do we convert it into keras format or h5 format? Thank you

**Comment by TheRealCasmat** [comment]
Hey @nandikawis!

H5 is supported by TFJS converter, I don’t think keras extension is supported yet

**Comment by nevakrien** [comment]
similar issue the model is so straight forward i will write all the code here 

```python
vocab_size = len(vectorizer)  # Number of unique words in your vocabulary

embedding_dim = 340

seq_length = 340  # Max sequence length

num_classes = 1



inputs = Input(shape=(seq_length,))

embedding = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=seq_length)(inputs)

cnn = Conv1D(filters=128, kernel_size=5, activation='relu', padding='same')(embedding)

cnn = BatchNormalization()(cnn)

cnn = MaxPooling1D(pool_size=4)(cnn)

cnn = Conv1D(filters=256, kernel_size=3, activation='relu', padding='same')(cnn)

cnn = BatchNormalization()(cnn)

cnn = MaxPooling1D(pool_size=2)(cnn)

lstm = LSTM(128, return_sequences=True, dropout=0.3, recurrent_dropout=0.3)(cnn)

lstm = LSTM(64, return_sequences=False, dropout=0.3, recurrent_dropout=0.3)(lstm)

dense = Dense(256, activation='relu')(lstm)

dense = Dropout(0.5)(dense)

dense = Dense(128, activation='relu')(dense)

dense = Dropout(0.5)(dense)

dense = Dense(64, activation='relu')(dense)

outputs = Dense(num_classes, activation='sigmoid')(dense)



model = Model(inputs=inputs, outputs=outputs)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()
```

ran that trained it then tried to convert to js with both keras and h5 formats it fails miserbly and idk why

**Comment by BhairabMahanta** [comment]
> Hi, @TheRealCasmat
> 
> I tried to replicate the same behavior from my end and I'm able to replicate the same behavior with your provided [colab notebook](https://colab.research.google.com/drive/1d_sy_wc31Fgewm-l6VdQmArsy3EFP7us?usp=sharing) but I see after installing the latest TensorFlow.js version, it's installing the `keras version 3` and as far I know `tfjs_converter` compatible with `keras 2 version` at the moment so I downgraded the TensorFlow version to `2.15.0` in which it will download `keras 2.15.0 version `which compatible for `tfjs_converter` and I converted model to TensorFlow.js format, it's working as expected please refer this [gist-file ](https://colab.sandbox.google.com/gist/gaikwadrahul8/096a2710166b7110e3693aae0fe8a260/test-issue-8358.ipynb), Please give it try from your end and it should work.
> 
> If issue still persists please let us know with error log to investigate this issue further from our end.
> 
> **For your reference I have added screenshot below :**
> 
> ![image](https://github.com/user-attachments/assets/1dc3215e-2422-4089-ae63-4d58e56f330a)
> 
> Thank you for your cooperation and patience.



hey, i'd need a step by step tutorial on downgrading keras and tensorflow to 2.15 😭 its just not working for me no matter how much i try to downgrade, keras stays 3 and tensorflow 2.20
MUCH APPRECIATED ive been struggling since 3 days

**Comment by Sergio-Javier** [comment]
> > Hola, @TheRealCasmat
> > Intenté replicar el mismo comportamiento desde mi extremo y puedo replicar el mismo comportamiento con su [cuaderno colab](https://colab.research.google.com/drive/1d_sy_wc31Fgewm-l6VdQmArsy3EFP7us?usp=sharing) proporcionado , pero veo que después de instalar la última versión de TensorFlow.js, está instalando `keras version 3`y hasta donde sé `tfjs_converter`es compatible con `keras 2 version`en este momento, así que bajé la versión de TensorFlow a `2.15.0`en la que descargará `keras 2.15.0 version `cuál es compatible `tfjs_converter`y convertí el modelo al formato TensorFlow.js, está funcionando como se esperaba, consulte este [archivo gist](https://colab.sandbox.google.com/gist/gaikwadrahul8/096a2710166b7110e3693aae0fe8a260/test-issue-8358.ipynb) . Pruébelo desde su extremo y debería funcionar.
> > Si el problema persiste, infórmenos con el registro de errores para que podamos investigarlo más a fondo.
> > **Para su referencia, he agregado una captura de pantalla a continuación:**
> > ![image](https://github.com/user-attachments/assets/1dc3215e-2422-4089-ae63-4d58e56f330a)
> > Gracias por su cooperación y paciencia.
> 
> Hola, necesito un tutorial paso a paso sobre cómo degradar Keras y Tensorflow a 2.15 😭 simplemente no me funciona, no importa cuánto intente degradarlo, Keras permanece en 3 y Tensorflow en 2.20 MUY APRECIADO He estado luchando desde hace 3 días

encontraste una solucion? yo utilizo colab, y ya estoy hace dos semanas. no encuentro forma de obligar al modelo a agregar esta capa de entrada
