### ISSUE TITLE
Clarification regarding the latest mediapipe facemesh model for tfjs

### ISSUE THREAD

**Issue by sitamgithub-MSIT** [tensorflow/tfjs#8359]
So, I am using the TensorFlow face_landmarks_detection model with tfjs from this [link](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection/v/0.0.3). My use case is to effectively track iris points for our eye research software. Now, the problem is that our project repository is quite old. Our existing system is fully compatible with model version 0.0.3.

Before (0.0.3) Version:

```
const model = await faceLandmarksDetection.load(faceLandmarksDetection.SupportedPackages.mediapipeFacemesh);
```

Now I want the version to be updated with the most recent one. That is 1.0.5. I updated the version, and the model loaded successfully, but the predictions produced errors. We can solve the problem, but we need quick solutions for our research paper. Anyway, the point is that I specifically want the updated package for using the most recent model of media pipe face mesh.

After (1.0.5) Version:

```
const model = faceLandmarksDetection.SupportedModels.MediaPipeFaceMesh;
const detectorConfig = {
  runtime: 'mediapipe', // or 'tfjs'
  solutionPath: 'https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh',
}
const detector = await faceLandmarksDetection.createDetector(model, detectorConfig);
```

I saw this [issue](https://github.com/tensorflow/tfjs/issues/6002): keeping the API spec the same and just changing the underlying model. So my question is, with the 0.0.3 version, am I using the most recent facemesh model, or has something changed? I have found this face mesh v2 in mediapipe documentation [here](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20MediaPipe%20Face%20Mesh%20V2.pdf).

It would be helpful if someone could clarify!

**Comment by shmishra99** [comment]
Hi @sitamgithub-MSIT , 

I apologize for the delayed response.The package `@mediapipe/face_mesh` doesn't directly specify a specific MediaPipe FaceMesh version. Instead, it's a wrapper around the MediaPipe FaceMesh model and its dependencies

I've been able to successfully run the `face-landmark-detection` model using this [demo](https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/demos), updating it to use the latest version of face-landmarks-detection [1.0.5](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection/v/1.0.5?activeTab=versions).

To build the project, I'm using the following yarn commands:
```
yarn build-dep
yarn
yarn watch
```
To help me troubleshoot the issue, could you please share the commands you're using to run your code, as well as any error logs you're encountering?  Thank you!

**Comment by sitamgithub-MSIT** [comment]
I am asking that here I see the model card for my media pipe face mesh model: https://storage.googleapis.com/mediapipe-assets/Model%20Card%20MediaPipe%20Face%20Mesh%20V2.pdf

As you can see the date is "MODEL DATE: September 15, 2022". I am using the version 0.0.3 of the face_landmark_detection model. The recent version is 1.0.5. In both cases am I using the same updated model referred to in the model card? Or is there any change regarding that?

**Comment by shmishra99** [comment]
We currently don't have an official document specifying which MediaPipe FaceMesh model is in use. However, based on the version [ 1.0.5 ](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection/v/1.0.5?activeTab=versions), it detects 478 3D landmarks, which aligns with the MediaPipe FaceMesh v2 model, whereas the initial model detects 468 3D landmarks, as outlined in this [document](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview). Therefore, it seems likely that the model in use is the v2 model.

Please refer to the following snippet for reference:

<img width="648" alt="image" src="https://github.com/user-attachments/assets/9b05436f-2d8e-4ec3-80bb-dcdb6ac638b2">


Let me know if i have missed something. 

Thank You!!
