### ISSUE TITLE
Error: invalid wire error during loadFrozenModel

### ISSUE THREAD

**Issue by nickponline** [tensorflow/tfjs#837]
#### Describe the problem or feature request
I trained an SSD model with Tensorflow Object Detection API and then converted to a frozen_graph with:

```
python export_inference_graph.py  --input_type encoded_image_string_tensor  --pipeline_config_path pipeline.config --trained_checkpoint_prefix model.ckpt-50000  --output_directory ssd
```

Then to a web model with:

```
tensorflowjs_converter \
    --input_format=tf_saved_model --skip_op_check=SKIP_OP_CHECK \
    --output_node_names='detection_boxes,detection_scores,detection_classes,num_detections' \
    --saved_model_tags=serve \
    saved_model \
    web_model
```

But when loading it I get an exception:
![image](https://user-images.githubusercontent.com/590151/47526558-e4116d80-d854-11e8-803a-197193a3d96e.png)

```
import * as tf from '@tensorflow/tfjs';
import {loadFrozenModel} from '@tensorflow/tfjs-converter';


(async function () {
  const MODEL_URL = 'http://localhost:3000/web_model/web_model.pb';
  const WEIGHTS_URL = 'http://localhost:3000/web_model/weights_manifest.json';
 
  // this line throws invalid wire exception
  const model = await loadFrozenModel(MODEL_URL, WEIGHTS_URL);
  const tile = document.getElementById('tile');
  let response = model.execute({input: tf.fromPixels(tile)});
  console.log(response)
})();
```

Here is the web_model: https://www.dropbox.com/s/g82y010hyfv7uc9/web_model.zip?dl=0

**Comment by dsmilkov** [comment]
Hi, looking at the dropbox folder, looks like the .pb file is `tensorflowjs_model.pb` instead of `web_model.pb`. As a safety check, before even running your webpage, access the MODEL_URL and WEIGHTS_URL urls directly in the browser to make sure the 
server response is ok.

**Comment by nsthorat** [comment]
Assigning @pyu10055 to improve the error messaging when loading the model and there is an error.
