### ISSUE TITLE
Broken link on TensorFlow Tutorial > Upgrading to TensorFlow.js 3.0

### ISSUE THREAD

**Issue by sdkdeepa** [tensorflow/tfjs#8385]
This link is broken https://www.tensorflow.org/js/tutorials/size_optimized_bundles.

**Describe the current behavior**
Steps:
1. Visit https://www.tensorflow.org/js/tutorials/upgrading_to_3_0 
2. Inside the content on the right, "See this tutorial" hyperlink is broken
**We provide support for creating custom tfjs modules to support producing size optimized browser bundles. Ship less JavaScript to your users. To learn more about this, [see this tutorial](https://www.tensorflow.org/js/tutorials/size_optimized_bundles).**

<img width="1114" alt="Screenshot 2024-09-19 at 10 24 50 PM" src="https://github.com/user-attachments/assets/812cfa99-3487-457b-8e0c-f5d26e2325fa">

<img width="1182" alt="Screenshot 2024-09-19 at 10 20 08 PM" src="https://github.com/user-attachments/assets/c668f5cf-509b-4c51-8186-c02e8b4b3471">

<img width="980" alt="Screenshot 2024-09-19 at 10 24 06 PM" src="https://github.com/user-attachments/assets/53ce4c4f-0d0b-4c56-bccf-5c0f874c830d">

**System information**
- MacOS - Sonoma 14.4.1
- Browser version:  Chrome Version 128.0.6613.138 

**Describe the expected behavior** 
 This link takes the the right content - https://www.tensorflow.org/js/tutorials/size_optimized_bundles

**Other info / logs** Screenshot attached.

**Comment by shmishra99** [comment]
HI @sdkdeepa , 
Thank you for highlighting this issue! I'll check in with the team and update the [broken link](https://www.tensorflow.org/js/tutorials/size_optimized_bundles) to the [correct link](https://www.tensorflow.org/js/tutorials/deployment/size_optimized_bundles). In the meantime, you can use the following link: https://www.tensorflow.org/js/tutorials/deployment/size_optimized_bundles.
