### ISSUE TITLE
Add tf.io.browserFiles() to API docs

### ISSUE THREAD

**Issue by jeancochrane** [tensorflow/tfjs#839]
`tf.io.browserFiles` was super useful for helping me quickly test out different models, but I killed an hour or so debugging its behavior because the API isn't documented -- as far as I can tell it should be under [Models / Management](https://js.tensorflow.org/api/0.13.0/#Models-Management) with the rest of the `tf.io` methods, although I may have missed it elsewhere.

Would you accept a PR adding docs for this method? I'd be happy to pull it together if so. From reading the README it seems like the workflow for editing these docs would be be:

1. Fork `tfjs-core`
2. Add a docstring to https://github.com/tensorflow/tfjs-core/blob/master/src/io/browser_files.ts#L107 in the fork
3. Fork `tfjs-website`, point the submodule for `tfjs-core` to my fork, and use my local `tfjs-website` build to spot check doc changes
4. Once all looks good, open a PR on `tfjs-core` for the docstring changes
5. After the PR comes into `tfjs-core`, you guys will update and push a new production build of `tfjs-website` at your leisure

Sound about right? 

Thanks for the great work on tfjs! It's been a ton of fun to work with.

**Comment by dsmilkov** [comment]
Yes, that would be a great contribution. The workflow you proposed is great. Thanks!
