### ISSUE TITLE
Add public API for enabling prod mode.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#845]
Right now users must do `tf.ENV.set('PROD', true);` but we don't want to expose this API, how about we have `tf.enableProdMode();`

**Comment by DmitryRomaniuk** [comment]
@nsthorat @dsmilkov I think this issue can be closed

**Comment by dsmilkov** [comment]
Thanks @DmitryRomaniuk ! Closed in https://github.com/tensorflow/tfjs-core/pull/1458
