### ISSUE TITLE
When I use the self-trained model to predict, The prediction results I tried are obviously wrong.

### ISSUE THREAD

**Issue by sorry77** [tensorflow/tfjs#8458]
I want to use my own trained model, so I don't use coco-ssd. I exported Yolo11n to tensorflow.js format in UltralyticsHub.
After loading and recognizing the sample pictures, the program can run normally, but the results are obviously abnormal.

Expected a bus (class 5), four people (class 0), but the result is a large number of cell phones (class 67).Although there are some people in the results, their coordinates are obviously incorrect. 
This is my example code: https://editor.p5js.org/sorry77/sketches/8Chg_hQWm
And classList: https://aiwus.wupen.org/yolo11n/metadata.yaml

**Comment by shmishra99** [comment]
Hi @sorry77 , 

I have tested the code you shared with different images as well, and it's producing many predictions related to `class 67` with varying scores. However, these images don't contain any mobiles `(class 67)`, and the predictions are also missing people `(class 0).` Is the class list correct? Additionally, could you confirm if `YOLOv11n` is producing accurate predictions in other frameworks

Thank You!!!

**Comment by sorry77** [comment]
I found the problem, preprocess is wrong. The correct code is:
`
const tensorBus = tf.browser.fromPixels(bus)
const [h, w] = tensorBus.shape.slice(0, 2)
const maxSize = Math.max(w, h)
const imgPadded = tensorBus.pad([
  [0, maxSize - h],
  [0, maxSize - w],
  [0, 0],
])
const inputTensor = tf.image
    .resizeBilinear(imgPadded, [640, 640])
    .div(255.0)
    .expandDims(0)
`
