### ISSUE TITLE
[tfjs-tflite] Didn't find op for builtin opcode 'FULLY_CONNECTED' version '12'.

### ISSUE THREAD

**Issue by vonjackustc** [tensorflow/tfjs#8461]
My tfjs-tflite version is 0.0.1-alpha.10

<img width="941" alt="image" src="https://github.com/user-attachments/assets/e0bf7ce7-2f49-472c-acc9-8d5a43588658">

**Comment by shmishra99** [comment]
Hi @vonjackustc ,

The error suggests that the `FULLY_CONNECTED` operation in the model is not supported by `@tensorflow/tfjs-tflite`.

Could you please clarify how you converted your model to a `tflite` model or which `tflite` model you are using?

If you're using the Keras `tfllite` converter, ensure that you include `tf.lite.OpsSet.SELECT_TF_OPS` to support for operations like `FULLY_CONNECTED`.  [TargetSpec](https://www.tensorflow.org/api_docs/python/tf/lite/TargetSpec)

Please let me know if this works for you. Thank you.
