### ISSUE TITLE
Install not working with esbuild

### ISSUE THREAD

**Issue by davidstrahm** [tensorflow/tfjs#8476]
Minimal repro:

1. create a new angular appliation with esbuild packager using nx.
2. in a component, `import * as tf from '@tensorflow/tfjs';` or `import { tensor } from '@tensorflow/tfjs';` (same problem)
3. serve application.  

The following errors show up in the console:  
```
✘ [ERROR] The package "fs" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/@tensorflow/tfjs-data/dist/sources/file_data_source.js:43:25:
      43 │       const fs = require('fs');
         ╵                          ~~~~
✘ [ERROR]
 The package "util" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/@tensorflow/tfjs-core/dist/platforms/platform_node.js:38:24:
      38 │     this.util = require('util');
         ╵                         ~~~~~~
✘ [ERROR] The package "string_decoder" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/@tensorflow/tfjs-data/dist/util/deep_map.js:217:16:
      217 │     } = require('string_decoder');
          ╵                 ~~~~~~~~~~~~~~~~
✘ [ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]
    node_modules/seedrandom/seedrandom.js:265:27:
      265 │       nodecrypto = require(
'crypto');
```

4. The exact same code works fine with webpack

**System information**
- Windows 11
- [@tensorflow/tfjs:4.22.0](https://www.npmjs.com/package/@tensorflow/tfjs)

**Comment by shmishra99** [comment]
Hi @davidstrahm,

Could you please add ``` "browser": { "fs": false, "util": false, "string_decoder": false, "crypto": false } ``` to your` package.json` file and let me know if it resolves your issue?

Thank you!

**Comment by davidstrahm** [comment]
hi @shmishra99 
Thanks for your reply. No it doesn't solve the problem.  
However, i created a new angular app without NX, using the angular cli, and there the import works.

**Comment by davidstrahm** [comment]
I figured it out. It was fixed in a patch version of angular that was released yesterday and was not automatically installed with npm i. Thats why it works in a new project, even though package.json was identical 🫣
