### ISSUE TITLE
Document WebGPU backend for React Native?

### ISSUE THREAD

**Issue by wcandillon** [tensorflow/tfjs#8478]
We were very excited how easily tfjs can run on top of WebGPU in React Native. I was wondering if you would consider have it as the default backend for React Native or as a documented backend?
Here's the demo we've built: https://github.com/wcandillon/react-native-webgpu/pull/192/files#diff-8ab6e54e14bece6bf3935eba223fe7b9783a41fc2e73f19e886108d0de1f0a17

If there are documentation contributions that I could do, let me know, I would be happy to help.

**Comment by shmishra99** [comment]
Hi @wcandillon , 

I apologize for the late response. `WebGPU` is a latest, and some devices do not fully support it, or may require additional configuration for installation. The `CPU` is the default backend for all `tfjs` operations. You can refer to the [documentation](https://github.com/tensorflow/tfjs/blob/tfjs-v4.22.0/tfjs-backend-webgpu/README.md). If you have any suggestions or improvements for the documentation, feel free to submit them. 

Thank you!

**Comment by wcandillon** [comment]
thanks for your answer :)
