### ISSUE TITLE
Try and warn Windows users if they don't have Python 2.* installed

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#854]
The tool used for compiling the Node.js bindings strictly requires Python 2.* (3 is not supported). We should update our install.js script to help point out users to help avoid this issue (it is already on our README).

https://github.com/tensorflow/tfjs/issues/711#issuecomment-433642190

**Comment by xlcrr** [comment]
Same error on mac os when running npm install 

gyp ERR! stack Error: Command failed: /anaconda2/bin/python2 -c import platform; print(platform.python_version());

I have python2 installed, but default is python3.

```
knn-tf:python --version
Python 3.6.4 :: Anaconda custom (64-bit)

knn-tf:python2 --version
Python 2.7.14 :: Anaconda, Inc.

knn-tf:which python
/anaconda3/bin/python

```

**Comment by ttfreeman** [comment]
I have python 2.7.15 and can confirm that by python --version, however it won't still install

**Comment by nkreeger** [comment]
@ttfreeman check your $PATH in windows. If Python3 is first - this might fail. Can you provide a full stack trace? Also try running (might have to do this in a privileged terminal `npm install --production windows-build-tools`

**Comment by ttfreeman** [comment]
@nkreeger My issue was resolved after installing full Visual Studio. Thanks though.

**Comment by nkreeger** [comment]
Great closing for now - I curated a README with troubleshooting here: https://github.com/tensorflow/tfjs-node/blob/master/WINDOWS_TROUBLESHOOTING.md
