### ISSUE TITLE
JSDoc discrepency for range() in math_utils.ts in tfjs-layers

### ISSUE THREAD

**Issue by euler16** [tensorflow/tfjs#856]
#### Describe the problem or feature request
In tfjs-layers/utils folder, inside the math_utils.ts file, on line 133 (range() JSDoc), "inclusive" should be replaced by exclusive since the documentation says that range ouputs an array  in [begin, end)

**Comment by dsmilkov** [comment]
Hi euler16, would you like to send us a PR? Happy to take your contribution!
