### ISSUE TITLE
tf.loadFrozenModel does not give useful error messages when a model does not load.

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/tfjs#86]
A common problem with tfjs models is permissions issues when loading the model.
The current demonstration at
https://github.com/tensorflow/tfjs-converter/blob/master/demo/index.js

does not exemplify proper error handling when loading the model.
To give better guidance to beginners, I think this should be added.

**Comment by dasimandl** [comment]
I am running into an error while trying to convert a saved mobilenet model using tfjs-converter.
I copied the command line - I/O below.  I tried this using the full path and the relative path (shown below).  I also tried this as sudo and as current user.  Im sure this is some very simple error on my part, but after some time google searching I was unable to find a solution. Thank you.

```
sudo tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    --saved_model_tags=serve
    ./input-model \
    ./output-model
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: TensorFlow.js model converters. [-h] --input_format
                                       {tf_saved_model,keras}
                                       [--output_node_names OUTPUT_NODE_NAMES]
                                       [--saved_model_tags SAVED_MODEL_TAGS]
                                       input_path output_dir
TensorFlow.js model converters.: error: too few arguments
zsh: permission denied: ./input-model
```

**Comment by nsthorat** [comment]
The error messages are much better now. Closing this out unless you think there is still an issue.
