### ISSUE TITLE
tfjs-vis improve sourcemap experience

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#860]
moving over from https://github.com/tensorflow/tfjs-vis/issues/21

**Comment by tafsiri** [comment]
- [ ] Confirm sourcemaps work when using script tags
- [ ] Eliminate parcel warnings about not finding sourcemaps warnings importing tfjs-vis

**Comment by dsmilkov** [comment]
Added to the 1.0 project board to track this

**Comment by QuantumInformation** [comment]
I'm not having luck with sourcemaps here

https://github.com/QuantumInformation/tensorflowjs-playground/blob/master/api-examples/src/index.ts#L4

if I try to step into that line in the browser it takes me to minified code.


<img width="1013" alt="screenshot 2019-02-14 at 08 55 05" src="https://user-images.githubusercontent.com/216566/52774888-41b10c00-3036-11e9-8ea9-e8565cc7b68b.png">
