### ISSUE TITLE
Triggering download of a model fails in Firefox

### ISSUE THREAD

**Issue by KinarR** [tensorflow/tfjs#861]
#### TensorFlow.js version
0.13.3

#### Browser version
Firefox 63.0

#### Describe the problem or feature request

I happened to find a bug concerning triggering browser downloads to save a model (**weights manifest** and the **binary weights**) in Firefox. This happens when you attempt to save a model by 
invoking `model.save('downloads://model)`. 

I believe it is caused by Firefox only allowing the `click` event on input elements. 

https://github.com/tensorflow/tfjs-core/blob/92aa158ba5ba34ec021da15db2548ca50d133412/src/io/browser_files.ts#L85-L99

I believe it can be fixed by dispatching a mouse click event  as `dispatchEvent(new MouseEvent('click'))` on the anchors as follows instead of `click()`.

`jsonAnchor.dispatchEvent(new MouseEvent('click'));`
`weightDataAnchor.dispatchEvent(new MouseEvent('click'));`

#### Code to reproduce the bug / link to feature request

In light of reproducing the bug, you could try running **Example 3** in https://js.tensorflow.org/api/0.13.3/#tf.Model.save on Firefox which fails to download the model.

**Comment by rthadur** [comment]
@dsmilkov  I was able to reproduce the issue in firefox ,assigning it to you, meanwhile @KinarR we welcome you to send a pull request with the fix.

**Comment by dsmilkov** [comment]
Thanks! Reassigning to @caisq who wrote the model saving/loading logic
