### ISSUE TITLE
Cast to uint8 to improve tf.toPixels()

### ISSUE THREAD

**Issue by jaretburkett** [tensorflow/tfjs#865]
For larger images (>800x800), tf.toPixels takes much longer to run than every other stage of my models combined, when running on mobile devices. I also have noticed that on most mobile devices that I have tested on, tensor.data() appears to block the UI until it is complete in the same way that tensor.dataSync() does. I do not experience this behavior on desktop platforms. 

One idea I was going to try is cast the tensor to uint8 which should cut the download time in 1/4 from int32, but I noticed that tfjs does not allow types of uint8. Is there a reason why int types are limited to int32 while int16, and uint8 are unsupported? I am curious if it is a limitation of webgl or if it just currently not implemented for other reasons.

Allowing to cast a tensor into uint8 would be a great addition since rendering a tensor requires converting it from a typed Int32Array or Float32Array to a Uint8ClampedArray anyway. If one could cast the tensor to a uint8 type, most of the toPixels processing could happen on webgl without having to do all of the for loops currently being implemented to build the Uint8ClampedArray. 

An example of a new tf.toPixels with uint8 types would be like this:

```javascript
    async toPixels(tensor, canvas=null){
        const uint8Tensor = tf.cast(tensor, 'uint8');
        const [height, width] = uint8Tensor.shape.slice(0, 2);
        // convert from rgb to rgba
        const alpha = tf.fill([height, width, 1], 255, 'uint8');
        const rgba = tf.concat([uint8Tensor, alpha], 2);
        tf.dispose([alpha, tensor, uint8Tensor]);
        // get the data as Uint8Array
        const data = await rgba.data();
        if(canvas !== null){
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            const imageData = new ImageData(data, width, height);
            ctx.putImageData(imageData, 0, 0);
        }
        tf.dispose(rgba);
    }
```

**Comment by dsmilkov** [comment]
Hi @jaretburkett,

Adding supprt for `uint8` dtype requires a large refactoring of our webgl engine. The added complexity is not worth at this point -- `toPixels()` for large images will still be the bottleneck because of for loops in js. I'll leave this issue open in case we revisit this in the future with more info about benefits of adding uint8

**Comment by jaretburkett** [comment]
@dsmilkov Thank you for the reply. I built a custom toPixels that has sped up the process considerably for large images as it negates the need for the JS for loops. It helps get me by for now. It does not have all the safety checks of the original, the input needs to have a value of 0-255 and cast to int32, but you will get the gist. 

```javascript
async toPixels(tensor, canvas=null){
    const [height, width] = tensor.shape.slice(0, 2);
    // convert to rgba by adding alpha channel
    const alpha = tf.fill([height, width, 1], 255, 'int32');
    const rgba = tf.concat([tensor, alpha], 2);
    tf.dispose([alpha, tensor]);
    
    const bytes = await rgba.data();
    const pixelData = new Uint8ClampedArray(bytes);
    if (canvas !== null){
        const imageData = new ImageData(pixelData, width, height);
        const ctx = canvas.getContext('2d');
        ctx.putImageData(imageData, 0, 0);
    }
    tf.dispose(rgba);
    return bytes;
}
```

Basically adding the alpha channel  on the backend allows you to pull the data directly into the Uint8ClampedArray without the js for loop going over each pixel. I have planned to submit a pull request on this, but I have been so swamped on my current project, so I figured it might be easier to share on here.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
