### ISSUE TITLE
Add performance benchmark(s) for tfjs-node

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#874]

**Comment by caisq** [comment]
Background: We have benchmarks for the browser in tfjs-core and tfjs-layers. But there is no benchmark for tfjs-node currently.

**Comment by caisq** [comment]
cc @nkreeger

**Comment by justadudewhohacks** [comment]
Just out of curiosity, shouldn't the performance of tfjs-node be equivalent to the performance of the native tensorflow c++ library, since it simply exposes bindings to the ops of the compiled library on your system?

**Comment by caisq** [comment]
@justadudewhohacks Theoretically, our performance should be the same as eager-model TensorFlow in Python. However, there are some aspects that may make our performance differ from that
- the way in which the binding to C++ libtensorflow is written in tfjs-node
- the implementation of the high-level API (i.e., tfjs-layer), which is not a part of libtensorflow

@nkreeger may have more to add.

**Comment by caisq** [comment]
@justadudewhohacks Note that this issue is mainly about benchmarks of inference and training operations on entire models, and less about the benchmarks of individual ops.

**Comment by justadudewhohacks** [comment]
That makes sense, got it. Thanks for clarification!

**Comment by nkreeger** [comment]
@justadudewhohacks Yeah some of the differences in Tensor storage binding (Python TF shares some stuff with numpy) and our high-level API Op usages is sometimes different than Python TF.

**Comment by rthadur** [comment]
@caisq can we close this issue as the corresponding PR are merged.

**Comment by caisq** [comment]
@rthadur Done. Thanks for the reminder.
