### ISSUE TITLE
tf.dot(x,y) vs tf.mul(x,y).sum()

### ISSUE THREAD

**Issue by DirkToewe** [tensorflow/tfjs#881]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.3

#### Browser version
Any

#### Describe the problem or feature request
For vectors `x,y` of length `n`, `tf.dot(x,y)` is an `O(n)` operation while `tf.mul(x,y).sum()` is an `O(√n)` op which results in a massive perfomance difference between the two. `tf.dot` is more concise and idiomatic and it would be nice if it were to use `tf.mul(x,y).sum()` internally for vector-like inputs. Alternatively, matMul could be implemented as two-step operation similar to reduce on WebGL.

#### Code to reproduce the bug / link to feature request
You can find a live benchmark [here](https://dirktoewe.github.io/tfjs-experiments/tf_dot_vs_mulSum.html?version=f36af92). A word of warning: the test becomes quite demanding for larger sizes.

**Comment by dsmilkov** [comment]
Thanks Dirk! You are right about the speedup which shows up for large vectors since we implemented sum() via a divide-and-conquer algorithm. Would you like to send a PR that forwards to tf.mul(x, y).sum() for vectors? I would do the forward inside matmul(), and dot() calls matmul - this keeps the logic centralized in matmul.

**Comment by dsmilkov** [comment]
Actually, I'll take this one since this change is particular to the webgl backend.

**Comment by DirkToewe** [comment]
Thank You for the fast response. Whichever way is easier for You. I've had some more time to think about this and I could think of two situations where `mul().sum()` might be useful: Vector-matrix ([...,1,n] x [...,n,m]) and matrix-vector ([...,m,n] x [n,1]) multiplication. Additionally I believe there to be two weaking parameters:
  * If n is too small, `mul().sum()` doesn't make much sense. That decision should depend on the same threshold parameter as `backend_webgl.sum()`.
  * If `sizeOfShape([...,m])` is large enough, there is already enough parallelism and `matMul()` is the better choice. Such a threshold would also prevent memory problem with large matrices.

Hope this helps/makes sense...
