### ISSUE TITLE
Provide better error message for non-integer values for integer config parameters

### ISSUE THREAD

**Issue by jeffsaremi** [tensorflow/tfjs#882]
"@tensorflow/tfjs": "^0.13.3",
Google Chrome Version 70.0.3538.77 (Official Build) (64-bit) on Windows 10
This error and stack trace showing up in the console:
```
bundle.min.js:42 Uncaught Error: Failed to compile fragment shader.
    at Yn (bundle.min.js:42)
    at t.createProgram (bundle.min.js:42)
    at bundle.min.js:42
    at bundle.min.js:42
    at t.getAndSaveBinary (bundle.min.js:42)
    at t.compileAndRun (bundle.min.js:42)
    at t.maxPool (bundle.min.js:42)
    at vt.engine.runKernel.x (bundle.min.js:18)
    at bundle.min.js:42
    at t.scopedRun (bundle.min.js:42)
```

```
WARNING: 0:191: '/' : Divide by zero during constant folding
219          for (int wR = 0; wR < undefined;             
```  

And here's the rest of the shader code:
```

196        float getValue(int batch, int xR, int xC, int d) {
197          if (xC < 0 || xC >= 112) {
198            return initializationValue;
199          }
200          count += 1.0;
201          return getX(batch, xR, xC, d);
202        }
203  
204        void main() {
205          ivec4 coords = getOutputCoords();
206          int batch = coords[0];
207          int d = coords[3];
208  
209          ivec2 xRCCorner = coords.yz * strides - pads;
210          int xRCorner = xRCCorner.x;
211          int xCCorner = xRCCorner.y;
212  
213          // max/min x(?, ?, d) to get y(yR, yC, d).
214          // ? = to be determined
215          vec4 minMaxValue = vec4(-1.0 / 0.0);
216          float avgValue = 0.0;
217          count = 0.0;
218  
bundle.min.js:42 WARNING: 0:191: '/' : Divide by zero during constant folding
bundle.min.js:42  219          for (int wR = 0; wR < undefined;                                                         
bundle.min.js:42 220              wR += 1) {
221            int xR = xRCorner + wR;
222  
223            if (xR < 0 || xR >= 112) {
224              continue;
225            }
226  
227            for (int wC = 0; wC < 0; wC += 4) {
228              int xC = xCCorner + wC * 1;
229  
230              vec4 values = vec4(
231                getValue(batch, xR, xC, d),
232                getValue(batch, xR, xC + 1, d),
233                getValue(batch, xR, xC + 2 * 1, d),
234                getValue(batch, xR, xC + 3 * 1, d)
235              );
236  
237              
238        if (false) {
239          avgValue += dot(values, ones);
240        } else {
241          minMaxValue = max(values, minMaxValue);
242        }
243      
244            }
245  
246            int xC = xCCorner + 0;
247            if (false) {
248              vec4 values = vec4(
249                getValue(batch, xR, xC, d),
250                initializationValue,
251                initializationValue,
252                initializationValue
253              );
254  
255              
256        if (false) {
257          avgValue += dot(values, ones);
258        } else {
259          minMaxValue = max(values, minMaxValue);
260        }
261      
262            } else if (false) {
263              vec4 values = vec4(
264                getValue(batch, xR, xC, d),
265                getValue(batch, xR, xC + 1, d),
266                initializationValue,
267                initializationValue
268              );
269  
270              
271        if (false) {
272          avgValue += dot(values, ones);
273        } else {
274          minMaxValue = max(values, minMaxValue);
275        }
276      
277            } else if (true) {
278              vec4 values = vec4(
279                getValue(batch, xR, xC, d),
280                getValue(batch, xR, xC + 1, d),
281                getValue(batch, xR, xC + 2 * 1, d),
282                initializationValue
283              );
284  
285              
286        if (false) {
287          avgValue += dot(values, ones);
288        } else {
289          minMaxValue = max(values, minMaxValue);
290        }
291      
292            }
293          }
294          setOutput(max(max(max(minMaxValue[0], minMaxValue[1]), minMaxValue[2]), minMaxValue[3]));
295        }
```

**Comment by caisq** [comment]
@rthadur What task were you performing when you run into this error? Was it model loading, inference or training?

**Comment by jeffsaremi** [comment]
I was running a predict() on a Resnet50 model imported from Keras.
```
this.model = await tf.loadModel(modelPath)
this.model.predict(inputTensor)
```

**Comment by caisq** [comment]
cc @dsmilkov Does this look like what happens when the browser WebGL memory is exhausted?

**Comment by nsthorat** [comment]
This isn't from a WebGL memory exhaustion problem, it looks like one of the dimensions passed to pooling is undefined.

`effectiveFilterHeight` is undefined in the convInfo: https://github.com/tensorflow/tfjs-core/blob/master/src/kernels/webgl/pool_gpu.ts#L74

@jeffsaremi are you using the out-of-the-box resnet 50?

**Comment by nsthorat** [comment]
Could you host the model.json and weights somewhere and I can take a closer look at what's going on?

**Comment by ToonTalk** [comment]
I'm getting this error after running successfully running my program a couple times. Restarting Chrome enables me to run it 2 or 3 more times before it happens again. Refreshing the tab doesn't help.

Version 72.0.3626.81 (Official Build) (64-bit)
{tfjs-core: "0.14.5", tfjs-data: "0.1.7", tfjs-layers: "0.9.2", tfjs-converter: "0.7.2", tfjs: "0.14.2"}

This is occuring while I'm experimenting with optimizing hyperparameters using
https://cdn.jsdelivr.net/npm/hyperparameters@latest/dist/hyperparameters.min.js

"Error: Failed to compile fragment shader.
    at createFragmentShader (http://localhost:8080/ai/js/tfjs.js:2:161484)
    at e.createProgram (http://localhost:8080/ai/js/tfjs.js:2:181524)
    at compileProgram (http://localhost:8080/ai/js/tfjs.js:2:188595)
    at http://localhost:8080/ai/js/tfjs.js:2:290579
    at e.getAndSaveBinary (http://localhost:8080/ai/js/tfjs.js:2:291281)
    at e.compileAndRun (http://localhost:8080/ai/js/tfjs.js:2:290542)
    at e.batchMatMul (http://localhost:8080/ai/js/tfjs.js:2:267536)
    at ENV.engine.runKernel.$a (http://localhost:8080/ai/js/tfjs.js:2:312133)
    at http://localhost:8080/ai/js/tfjs.js:2:38887
    at e.scopedRun (http://localhost:8080/ai/js/tfjs.js:2:38380)"

Error at line 202 below

1    
2      precision highp float;
3      precision highp int;
4      varying vec2 resultUV;
5      const vec2 halfCR = vec2(0.5, 0.5);
6    
7      struct ivec5
8      {
9        int x;
10       int y;
11       int z;
12       int w;
13       int u;
14     };
15   
16     struct ivec6
17     {
18       int x;
19       int y;
20       int z;
21       int w;
22       int u;
23       int v;
24     };
25   
26     
27       bool isNaN(float val) {
28         return (val < 1.0 || 0.0 < val || val == 0.0) ? false : true;
29       }
30   
31       bool hasNaN(vec4 values) {
32         return any(bvec4(
33           isNaN(values.x),
34           isNaN(values.y),
35           isNaN(values.z),
36           isNaN(values.w)
37         ));
38       }
39     
40   
41     float getNaN(vec4 values) {
42       return dot(vec4(1), values);
43     }
44   
45     int round(float value) {
46       return int(floor(value + 0.5));
47     }
48   
49     int imod(int x, int y) {
50       return x - y * (x / y);
51     }
52   
53     //Based on the work of Dave Hoskins
54     //https://www.shadertoy.com/view/4djSRW
55     #define HASHSCALE1 443.8975
56     float random(float seed){
57       vec2 p = resultUV * seed;
58       vec3 p3  = fract(vec3(p.xyx) * HASHSCALE1);
59       p3 += dot(p3, p3.yzx + 19.19);
60       return fract((p3.x + p3.y) * p3.z);
61     }
62   
63     
64   vec2 UVfrom1D(int texNumR, int texNumC, int index) {
65     int texR = index / texNumC;
66     int texC = index - texR * texNumC;
67     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
68   }
69   vec2 packedUVfrom1D(int texNumR, int texNumC, int index) {
70     int texelIndex = index / 2;
71     int texR = texelIndex / texNumC;
72     int texC = texelIndex - texR * texNumC;
73     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
74   }
75   
76     
77   vec2 UVfrom2D(int texNumR, int texNumC, int numC, int row, int col) {
78     int index = row * numC + col;
79     int texR = index / texNumC;
80     int texC = index - texR * texNumC;
81     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
82   }
83   vec2 packedUVfrom2D(int texelsInLogicalRow, int texNumR,
84     int texNumC, int row, int col) {
85     int texelIndex = (row / 2) * texelsInLogicalRow + (col / 2);
86     int texR = texelIndex / texNumC;
87     int texC = texelIndex - texR * texNumC;
88     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
89   }
90   
91     
92   vec2 UVfrom3D(int texNumR, int texNumC, int stride0,
93       int stride1, int row, int col, int depth) {
94     // Explicitly use integer operations as dot() only works on floats.
95     int index = row * stride0 + col * stride1 + depth;
96     int texR = index / texNumC;
97     int texC = index - texR * texNumC;
98     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
99   }
100  vec2 packedUVfrom3D(int texNumR, int texNumC,
101      int texelsInBatch, int texelsInLogicalRow, int b,
102      int row, int col) {
103    int index = b * texelsInBatch + (row / 2) * texelsInLogicalRow + (col / 2);
104    int texR = index / texNumC;
105    int texC = index - texR * texNumC;
106    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
107  }
108  
109    
110  vec2 UVfrom4D(int texNumR, int texNumC, int stride0,
111      int stride1, int stride2, int row, int col, int depth,
112      int depth2) {
113    // Explicitly use integer operations as dot() only works on floats.
114    int index = row * stride0 + col * stride1 + depth * stride2 + depth2;
115    int texR = index / texNumC;
116    int texC = index - texR * texNumC;
117    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
118  }
119  vec2 packedUVfrom4D(int texNumR, int texNumC, int texelsInBatch2,
120      int texelsInBatch, int texelsInLogicalRow, int b2, int b,
121      int row, int col) {
122    int index = b2 * texelsInBatch2 + b * texelsInBatch +
123      (row / 2) * texelsInLogicalRow + (col / 2);
124    int texR = index / texNumC;
125    int texC = index - texR * texNumC;
126    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
127  }
128  
129    
130  vec2 UVfrom5D(int texNumR, int texNumC, int stride0,
131      int stride1, int stride2, int stride3, int row, int col, int depth,
132      int depth2, int depth3) {
133    // Explicitly use integer operations as dot() only works on floats.
134    int index = row * stride0 + col * stride1 +
135                depth * stride2 + depth2 * stride3 + depth3;
136    int texR = index / texNumC;
137    int texC = index - texR * texNumC;
138    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
139  }
140  
141    
142  vec2 UVfrom6D(int texNumR, int texNumC, int stride0,
143      int stride1, int stride2, int stride3, int stride4,
144      int row, int col, int depth, int depth2, int depth3, int depth4) {
145    // Explicitly use integer operations as dot() only works on floats.
146    int index = row * stride0 + col * stride1 + depth * stride2 + depth2 *
147      stride3 + depth3 * stride4 + depth4;
148    int texR = index / texNumC;
149    int texC = index - texR * texNumC;
150    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
151  }
152  
153  
154    float getChannel(vec4 frag, vec2 innerDims) {
155      vec2 modCoord = mod(innerDims, 2.);
156      return modCoord.x == 0. ?
157        (modCoord.y == 0. ? frag.r : frag.g) :
158        (modCoord.y == 0. ? frag.b : frag.a);
159    }
160    float getChannel(vec4 frag, int dim) {
161      float modCoord = mod(float(dim), 2.);
162      return modCoord == 0. ? frag.r : frag.g;
163    }
164  
165  
166    float sampleTexture(sampler2D textureSampler, vec2 uv) {
167      return texture2D(textureSampler, uv).r;
168    }
169  
170  
171    void setOutput(vec4 val) {
172      gl_FragColor = val;
173    }
174  
175  uniform sampler2D matrixA;
176  uniform sampler2D matrixB;
177  
178      ivec2 getOutputCoords() {
179        ivec2 resTexRC = ivec2(resultUV.yx *
180                               vec2(3, 95));
181  
182        int index = resTexRC.x * 95 + resTexRC.y;
183        int r = 2 * (index / 95);
184        int c = imod(index, 95) * 2;
185  
186        return ivec2(r, c);
187      }
188    
189  
190      float getMatrixAFlat(int index) {
191        vec2 uv = UVfrom1D(6, 2, index);
192        return sampleTexture(matrixA, uv);
193      }
194    
195      vec4 getMatrixA(int row, int col) {
196        vec2 uv = packedUVfrom2D(1, 3, 1, row, col);
197        return texture2D(matrixA, uv);
198      }
199    
200  
201      float getMatrixBFlat(int index) {
tfjs.js:2 ERROR: 0:202: 'UVfrom1D' : no matching overloaded function found
tfjs.js:2  202        vec2 uv = UVfrom1D(2, 189.57284311543992, index);                      
tfjs.js:2 203        return sampleTexture(matrixB, uv);
204      }
205    
206      vec4 getMatrixB(int row, int col) {
207        vec2 uv = packedUVfrom2D(95, 1, 95, row, col);
208        return texture2D(matrixB, uv);
209      }
210    
211  
212        const float sharedDimension = 1.0;
213  
214        vec4 dot2x2ARowBCol(ivec2 rc) {
215          vec4 result = vec4(0);
216          for (int i = 0; i < 1; i++) {
217            vec4 a = getMatrixA(rc.x, i * 2);
218            vec4 b = getMatrixB(i * 2, rc.y);
219  
220            result += (a.xxzz * b.xyxy) + (a.yyww * b.zwzw);
221          }
222          return result;
223        }
224  
225        void main() {
226          ivec2 rc = getOutputCoords();
227          setOutput(dot2x2ARowBCol(rc));
228        }
229

**Comment by ToonTalk** [comment]
Maybe this is due to a memory leak

tf.memory()
{unreliable: false, numBytesInGPU: 1206515.7845747396, numTensors: 338, numDataBuffers: 338, numBytes: 1334649.716558177}

Why are there fractional bytes?

**Comment by annxingyuan** [comment]
Hey @ToonTalk - could you try upgrading your version of tfjs-core to see whether that fixes the issue? I noticed the compilation error is for a function that we removed in the latest release.

**Comment by ToonTalk** [comment]
Thanks.

With {tfjs-core: "0.15.0", tfjs-data: "0.2.0", tfjs-layers: "0.10.0", tfjs-converter: "0.8.0", tfjs: "0.15.0"}

I'm getting the error on line 150

1    #version 300 es
2        precision highp float;
3        precision highp int;
4        precision highp sampler2D;
5        in vec2 resultUV;
6        out vec4 outputColor;
7        const vec2 halfCR = vec2(0.5, 0.5);
8    
9        struct ivec5
10       {
11         int x;
12         int y;
13         int z;
14         int w;
15         int u;
16       };
17   
18       struct ivec6
19       {
20         int x;
21         int y;
22         int z;
23         int w;
24         int u;
25         int v;
26       };
27   
28       
29         bool isNaN(float val) {
30           return (val < 1.0 || 0.0 < val || val == 0.0) ? false : true;
31         }
32   
33         bool hasNaN(vec4 values) {
34           return any(bvec4(
35             isNaN(values.x),
36             isNaN(values.y),
37             isNaN(values.z),
38             isNaN(values.w)
39           ));
40         }
41       
42   
43       float getNaN(vec4 values) {
44         return dot(vec4(1), values);
45       }
46   
47       
48         #define round(value) newRound(value)
49         int newRound(float value) {
50           return int(floor(value + 0.5));
51         }
52   
53         ivec4 newRound(vec4 value) {
54           return ivec4(floor(value + vec4(0.5)));
55         }
56       
57   
58       int imod(int x, int y) {
59         return x - y * (x / y);
60       }
61   
62       //Based on the work of Dave Hoskins
63       //https://www.shadertoy.com/view/4djSRW
64       #define HASHSCALE1 443.8975
65       float random(float seed){
66         vec2 p = resultUV * seed;
67         vec3 p3  = fract(vec3(p.xyx) * HASHSCALE1);
68         p3 += dot(p3, p3.yzx + 19.19);
69         return fract((p3.x + p3.y) * p3.z);
70       }
71   
72       
73   vec2 uvFromFlat(int texNumR, int texNumC, int index) {
74     int texR = index / texNumC;
75     int texC = index - texR * texNumC;
76     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
77   }
78   vec2 packedUVfrom1D(int texNumR, int texNumC, int index) {
79     int texelIndex = index / 2;
80     int texR = texelIndex / texNumC;
81     int texC = texelIndex - texR * texNumC;
82     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
83   }
84   
85       
86   vec2 packedUVfrom2D(int texelsInLogicalRow, int texNumR,
87     int texNumC, int row, int col) {
88     int texelIndex = (row / 2) * texelsInLogicalRow + (col / 2);
89     int texR = texelIndex / texNumC;
90     int texC = texelIndex - texR * texNumC;
91     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
92   }
93   
94       
95   vec2 packedUVfrom3D(int texNumR, int texNumC,
96       int texelsInBatch, int texelsInLogicalRow, int b,
97       int row, int col) {
98     int index = b * texelsInBatch + (row / 2) * texelsInLogicalRow + (col / 2);
99     int texR = index / texNumC;
100    int texC = index - texR * texNumC;
101    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
102  }
103  
104      
105  vec2 UVfrom5D(int texNumR, int texNumC, int stride0,
106      int stride1, int stride2, int stride3, int row, int col, int depth,
107      int depth2, int depth3) {
108    // Explicitly use integer operations as dot() only works on floats.
109    int index = row * stride0 + col * stride1 +
110                depth * stride2 + depth2 * stride3 + depth3;
111    int texR = index / texNumC;
112    int texC = index - texR * texNumC;
113    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
114  }
115  
116      
117  vec2 UVfrom6D(int texNumR, int texNumC, int stride0,
118      int stride1, int stride2, int stride3, int stride4,
119      int row, int col, int depth, int depth2, int depth3, int depth4) {
120    // Explicitly use integer operations as dot() only works on floats.
121    int index = row * stride0 + col * stride1 + depth * stride2 + depth2 *
122      stride3 + depth3 * stride4 + depth4;
123    int texR = index / texNumC;
124    int texC = index - texR * texNumC;
125    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
126  }
127  
128    
129  
130      float sampleTexture(sampler2D textureSampler, vec2 uv) {
131        return texture(textureSampler, uv).r;
132      }
133    
134  
135      void setOutput(float val) {
136        outputColor = vec4(val, 0, 0, 0);
137      }
138    
139  uniform sampler2D A;
140  uniform int offsetA;
141  uniform sampler2D B;
142  uniform int offsetB;
143  
144        ivec2 getOutputCoords() {
145          return ivec2(resultUV.yx * vec2(5, 159.90210999487337));
146        }
147      
148  
149      float getA(int row, int col) {
tfjs@latest:2 ERROR: 0:150: '159.90210999487337.0' : invalid number
tfjs@latest:2  150        vec2 uv = (vec2(col, row) + halfCR) / vec2(159.90210999487337.0, 5.0);       
tfjs@latest:2 151        return sampleTexture(A, uv);
152      }
153    
154        float getAAtOutCoords() {
155          return sampleTexture(A, resultUV);
156        }
157      
158  
159        float getB(int index) {
160          vec2 uv = vec2((float(index + offsetB) + 0.5) / 159.90210999487337.0, 0.5);
161          return sampleTexture(B, uv);
162        }
163      
164      float getBAtOutCoords() {
165        ivec2 coords = getOutputCoords();
166        
167        return getB(coords.y);
168      }
169    
170  
171        uniform float NAN;
172        float binaryOperation(float a, float b) {
173          return a + b;
174        }
175  
176        void main() {
177          float a = getAAtOutCoords();
178          float b = getBAtOutCoords();
179          setOutput(binaryOperation(a, b));
180        }

**Comment by ToonTalk** [comment]
I just discovered my bug so that randomly 1/6th of time it created a model with a dense layer whose size was a non-integer. Perhaps tf.layers.dense could throw an error in such a case.

**Comment by caisq** [comment]
@ToonTalk Ah - thanks for the info. Are you positive that the non-integer `units` value is the cause of your error? If so, we can very easily add a check for that sort of invalid values.

**Comment by ToonTalk** [comment]
I added Math.round(...) and the problem went away. I've run my program 4 or 5 times and for more iterations and unlike before no shader compilation errors.
