### ISSUE TITLE
Model name lost by tf.save

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#885]
#### TensorFlow.js version
0.13.3

#### Browser version
70.0.3538.77 (Official Build) (64-bit)

#### Describe the problem or feature request
Creating a model using `tf.sequential({name: name});` and then saving it and loading it the name becomes sequential-1 (..-2 if there already is one)

#### Code to reproduce the bug / link to feature request
```
const model = tf.sequential({name: name});
model.save('downloads://' + name);
// copy local file to URL
const saved_model = await tf.loadModel(URL);
console.log(saved_model.name);
```

**Comment by ran-j** [comment]
hey, How about 
```
const model = tf.sequential({name: name});
model.save('downloads://' + name).then(() => {
  const saved_model = await tf.loadModel(URL);
  console.log(saved_model.name);
}).catch(console.error)
```
