### ISSUE TITLE
Rename Person-Segmentation to BodyPix

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#890]
We had a brainstorm session and decided to rename the "PersonSegmentation" model to "BodyPix" to keep it short.

@oveddan let me know if this sounds good, and if you can take this one. Thank you!!

**Comment by dsmilkov** [comment]
cc @nsthorat @tafsiri

**Comment by tylerzhu-github** [comment]
Thanks for the update and the new name proposal sounds great. I like the new name BodyPix!
