### ISSUE TITLE
tf.norm and tf.abs(_: complex64) are not underflow-safe.

### ISSUE THREAD

**Issue by DirkToewe** [tensorflow/tfjs#895]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
v0.13.8

#### Browser version
Any

#### Describe the problem or feature request
One of the most important norm properties is the positive definiteness:
`|x|=0 <=> x=0`
The current implementation of `tf.abs(_: complex64)` and `tf.norm` do not satisfy that property for some fringe cases where underflow becomes an issue. `Math.fround(1e-23**2)` rounds down to `0` and therefore the norm would become zero. This can cause issues, e.g. when normalizing a complex number or a vector, or when trying to determine convergence of an optimization.

An underflow-safe implementation can be found [here](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot). In WebGL there is a [length](https://www.khronos.org/files/opengles_shading_language.pdf#page=74) function that can be used both for `tf.abs` as well for `tf.norm` as binary reduction operator.

#### Code to reproduce the bug / link to feature request
```ts
const x = tf.tensor1d([1e-23,0]);
x.norm().print();
// Output:
//   Tensor
//       0
```

**Comment by rthadur** [comment]
Closing this as the related PR has been merged, thank you.

**Comment by DirkToewe** [comment]
PR#1391 fixes underflow in `tf.abs` but *not* in `tf.norm`, I'm afraid. The latter is fixable with one or two lines of code but it will at least double the memory and computation overhead of the operation, I'm afraid. I can file a PR for that as soon as I get to implement it.

The performance and memory overhead could be avoided by adding an addtional reduction operation to the backend which should be even faster than the current `tf.norm`. That would however require bigger changes.

**Comment by gaikwadrahul8** [comment]
Hi, @DirkToewe 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by DirkToewe** [comment]
Both `tfjs-v4.11.0` and `master` use `sqrt(sum(square(x), axis))` to compute the 2-norm, where `square(x)` under-/overflows. The issue is still open.

**Comment by gaikwadrahul8** [comment]
Hi, @DirkToewe 

I apologize for the delayed response and I tried your above code snippet and it still return output as `Tensor 0` and I see you have submitted a PR https://github.com/tensorflow/tfjs/pull/2236 but your branch has conflicts that must be resolved so to confirm, are you still working on that PR ? Thank you.

Here is output for reference :

![image](https://github.com/tensorflow/tfjs/assets/115997457/b4a5a233-0286-4f1f-9d5a-0014aa99850b)
