### ISSUE TITLE
Add seed parameter to `tf.randomUniform`

### ISSUE THREAD

**Issue by DirkToewe** [tensorflow/tfjs#896]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.10

#### Browser version
Any

#### Describe the problem or feature request
For reproducability of tests and training it would be wery useful to have a seed parameter in `tf.randomUniform`.

#### Code to reproduce the bug / link to feature request
N/A

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
