### ISSUE TITLE
Calling executeAsync more than once fails

### ISSUE THREAD

**Issue by t-mullen** [tensorflow/tfjs#897]
#### TensorFlow.js version
0.13.4

#### Browser version
Chrome 70

#### Describe the problem or feature request
Any calls after the first to executeAsync will throw the error  `Error: Tensor is disposed.`. This happens when using the same input tensor, or a new one. 

I'm using a pre-trained object detection model converted using `tfjs-converter`. The model works fine, but only once.

#### Code to reproduce the bug / link to feature request
```javascript
const MODEL_URL = '/coco_model/web_model/tensorflowjs_model.pb';
const WEIGHTS_URL = '/coco_model/web_model/weights_manifest.json';

tf.loadFrozenModel(MODEL_URL, WEIGHTS_URL).then(async (model) => {
    const image_tensor = tf.expandDims(tf.fromPixels(inputVideoElement), 0)
    const result = await model.executeAsync({ image_tensor });
    const result2 = await model.executeAsync({ image_tensor }); // <- ERROR
})
```

**Comment by t-mullen** [comment]
My guess is that some intermediate tensors are being disposed of - but I'm not sure how to prevent that. I can't use `tidy` around `executeAsync`, nor can I call `keep` on tensors within a loaded model.

**Comment by t-mullen** [comment]
After digging through Github, I've found that sticking `await model.load()` before every call to `model. executeAsync` will avoid the issue. Unfortunately `model.load()` takes more than twice as long as the actual execution... I shouldn't need to reload the whole model every time, right?

**Comment by t-mullen** [comment]
I can also reproduce with no code of my own by running the demo in https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd. This demo "warms up" the model with a call the `executeAsync`, then makes additional calls to get results.

Seems something has broken with `executeAsync` in the past 2 months.

**Comment by t-mullen** [comment]
Calling `model.load()` actually requests the full model from the server again, so this isn't an acceptable workaround.

**Comment by t-mullen** [comment]
I can confirm that this error doesn't occur in version `0.13.1`, but does in `0.13.4`. Definitely a regression.

**Comment by pyu10055** [comment]
@t-mullen looks like the weights tensor might have been disposed prematurely, can you confirm if it works on 0.13.3? I notice this only happens on 0.13.4. Thanks!

**Comment by t-mullen** [comment]
Works, thanks! 👍
