### ISSUE TITLE
Investigate calling tf.nextFrame() in model.fit() between batches.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#9]
Calling tf.nextFrame() in a browser context will release the UI thread so the page can be responsive. This should have no impact on performance for medium-large sized models, though will negatively impact small models (where forward / backprop is < 16ms).

Some benchmarks from @cais 

## No tf.nextFrame() (today)
![image](https://user-images.githubusercontent.com/1100749/37559540-5b20a0c2-29fe-11e8-99ee-4934eaa7d4a6.png)

## tf.nextFrame() between batches
![image](https://user-images.githubusercontent.com/1100749/37559548-8658d4a8-29fe-11e8-9361-42e43913bf41.png)

Notice that there is no performance impact for rows 2+ (the first row slows down by about a frame, which is expected since the forward / backwards pass is sub-frame).

After launch, we can see what type of models people typically use and come back to this discussion.

**Comment by nsthorat** [comment]
I still think we should do this, even at the cost of smaller models. I've seen people have to add this in several places:
https://github.com/shiffman/Tensorflow-JS-Examples/blob/master/02_Color_Classifier/sketch.js#L83

Most models are larger than the tiny models we're talking about here, so let's go forward and do this automatically.

@caisq @dsmilkov @tafsiri thoughts?

**Comment by dsmilkov** [comment]
+1. No reservations.

**Comment by nsthorat** [comment]
One more person talking about this: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/754OcyLgfjg/X9rXT8IfBwAJ

@caisq would you prioritize this?

**Comment by nsthorat** [comment]
This is now fixed.
