### ISSUE TITLE
Tensor.concat Should Allow Tensor[]

### ISSUE THREAD

**Issue by dsanders11** [tensorflow/tfjs#919]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

0.13.4

#### Browser version

Chrome 70.0.3538.77

#### Describe the problem or feature request

There's an unexpected asymmetry between `tf.concat` and `Tensor.concat`, which the documentation doesn't make clear. The former takes a `Tensor[]`, the latter only a single `Tensor`. This means the following isn't equivalent:

```javascript
const a = tf.tensor1d([1, 2, 3]);
const b = tf.tensor1d([4, 5, 6]);
const c = tf.tensor1d([7, 8, 9]);

// a.concat throws error
a.concat([b, c]);
tf.concat([a, b, c]);
```

Suggested implementation would be:

```javascript
concat<T extends Tensor>(this: T, x: T|T[], axis = 0): T {
  this.throwIfDisposed();
  return opHandler.concat([this].concat(x), axis);
}
```

But TypeScript has some trouble with this, and I don't know TypeScript so I can't quite resolve that issue, otherwise I'd simply make a PR.

**Comment by nsthorat** [comment]
This should be fixed.
