### ISSUE TITLE
PoseNet single pose estimation returning NaN on iOS

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#921]
From a thread on the mailing list:

"I  am using posenet 2.3 and tjfs 13.2

tfjs: "0.13.2"
tfjs-converter: "0.6.4"
tfjs-core: "0.13.6"
tfjs-layers: "0.8.2"

Using the model with below configs:

multiplier = 0.5
imageScaleFactor = 0.8
const outputStride = 16
const flipHorizontal = false

It works perfect everywhere except iOS (only tested on 11) safari. I randomly get correct result and most of the time the return result is full of NaN. I was wondering if I am doing something wrong or if it is a known issue?

{score: 0.0008068085298873484, part: "nose", position: {x: -34.917220042717695, y: 9.333332061767578}}
1 {score: NaN, part: "leftEye", position: {x: NaN, y: NaN}}
2 {score: 0.0011739734327420592, part: "rightEye", position: {x: -9.884581822511496, y: -0.623046875}}
3 {score: NaN, part: "leftEar", position: {x: NaN, y: NaN}}
4 {score: 0.001707077375613153, part: "rightEar", position: {x: 7.165699032143223, y: 42.666666666666664}}
5 {score: NaN, part: "leftShoulder", position: {x: NaN, y: NaN}}
6 {score: 0.002199173206463456, part: "rightShoulder", position: {x: 1.8574051242374496, y: 50.541666666666664}}
7 {score: NaN, part: "leftElbow", position: {x: NaN, y: NaN}}
8 {score: NaN, part: "rightElbow", position: {x: NaN, y: NaN}}
9 {score: NaN, part: "leftWrist", position: {x: NaN, y: NaN}}
10 {score: 0.002471924526616931, part: "rightWrist", position: {x: -10.845653328611899, y: 30.24999745686849}}
11 {score: NaN, part: "leftHip", position: {x: NaN, y: NaN}}
12 {score: NaN, part: "rightHip", position: {x: NaN, y: NaN}}
13 {score: NaN, part: "leftKnee", position: {x: NaN, y: NaN}}
14 {score: NaN, part: "rightKnee", position: {x: NaN, y: NaN}}
15 {score: NaN, part: "leftAnkle", position: {x: NaN, y: NaN}}
16 {score: NaN, part: "rightAnkle", position: {x: NaN, y: NaN}}

Thank you very much!!"

**Comment by oveddan** [comment]
Same as #775 and #727

**Comment by oveddan** [comment]
Was this resolved in pr [1346](https://github.com/tensorflow/tfjs/pulls/1346)?

**Comment by nsthorat** [comment]
I thought it was, but this thread was started way after we fixed that bug and the core version listed should have the fix.

**Comment by oveddan** [comment]
I've deployed the camera demo with 0.13.2 tfjs here:
https://posenet-demos.netlify.com/

The great news is that this works again on my iphone with IOS12!  And even greater news - I'm not sure what you all have done with tf.js but it now gets around 16-20fps on my iphone xr, pretty friggin amazing!  Was it running on cpu and now on gpu? 

The demo uses multi-pose by default and currently you cant switch it on mobile. I would want to try this using single pose.  If it is just an issue with single pose than that should be fixable.

**Comment by nsthorat** [comment]
All amazing progress from @annxingyuan :)

Yeah I think it's just a single pose estimation thing.

**Comment by annxingyuan** [comment]
@nsthorat @oveddan 

For what it's worth, I've tested both single and multi-pose on iOS 11 (iPhone 6) and 12 (iPhone X) and everything appears to be working. I'll try to investigate this bug with the mailing list OP - maybe it's something unique to their environment.
