### ISSUE TITLE
model.predict() slow locally

### ISSUE THREAD

**Issue by christian-vorhemus** [tensorflow/tfjs#926]
#### TensorFlow.js version
0.13.5

#### Browser version
Chrome 70.0.3538.102

#### Describe the problem or feature request
I'm running a model I've trained in Keras in my browser. When testing in python, the model.predict() call takes roughly 300ms. When I run the model in the browser (I've saved it in a tfjs compatible format), it takes more than 10 seconds. Here is a codepen that illustrates the case: https://codepen.io/anon/pen/XygXRP

I'm not sure if this is normal behavior or if something is either wrong in my code or in tensorflow.js.

**Comment by nsthorat** [comment]
Just curious if you still see this in 1.0.2
