### ISSUE TITLE
devtoolsFormatters object formatter extension

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#93]
_From @tmcw on November 24, 2017 20:46_

Has anyone considered writing (or has anyone already written) a [custom object formatter](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview) for Chrome devtools in combination with deeplearn.js? This would make it possible to view Array2D data structures visually as the matrices that they represent mathematically.

_Copied from original issue: tensorflow/tfjs-core#382_

**Comment by nsthorat** [comment]
This is a really cool idea, I haven't heard of anyone working on this.

This would be a phenomenal contribution if anyone's up for it.

**Comment by gaikwadrahul8** [comment]
Hi, @nsthorat

We carefully reviewed this feature request and are not planning to implement this feature due to other priorities. We are closing this issue and If you require further assistance with this feature request, please feel free to re-open this issue. Thank you!
