### ISSUE TITLE
Converted model from Keras show 'model_config' of null error.

### ISSUE THREAD

**Issue by kouohhashi** [tensorflow/tfjs#931]
#### TensorFlow.js version
@tensorflow/tfjs": "^0.13.5" 
or 
"@tensorflow/tfjs-node": "^0.1.21",

#### Browser version
Google Chrome Version 70.0.3538.102

#### Describe the problem or feature request
I converted a Keras model into Tensorflowjs model with tensorflowjs_converter 
tensorflowjs_converter version: 
```
tensorflowjs_converter --version

Using TensorFlow backend.

tensorflowjs 0.6.7

Dependency versions:
  keras 2.2.2
  tensorflow 1.12.0
```

#### Code to reproduce the bug / link to feature request
I downloaded the Keras model [here](https://github.com/Tony607/keras-image-ocr).
The model is about text recognition with GRU and CTC loss.

When I try to load the model, 
```
const model1 = await tf.loadModel('Path to File');
```
I got the error says,
```
(node:26074) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'model_config' of null
    at ./node_modules/@tensorflow/tfjs-layers/src/models.ts:267:20
    at ./node_modules/@tensorflow/tfjs-layers/dist/models.js:42:23)
    at ./node_modules/@tensorflow/tfjs-layers/dist/models.js:23:53)
    at ,/node_modules/@tensorflow/tfjs-layers/dist/models.js:14:58)
    at <anonymous>
```

I got same error both from node.js and browser.

here is the model.json:
```
{
  "modelTopology": null,
  "weightsManifest": [
    {
      "paths": [
        "group1-shard1of5",
        "group1-shard2of5",
        "group1-shard3of5",
        "group1-shard4of5",
        "group1-shard5of5"
      ],
      "weights": [
        {
          "name": "conv1_1/kernel",
          "shape": [
            3,
            3,
            1,
            16
          ],
          "dtype": "float32"
        },
        {
          "name": "conv1_1/bias",
          "shape": [
            16
          ],
          "dtype": "float32"
        },
        {
          "name": "conv2_1/kernel",
          "shape": [
            3,
            3,
            16,
            16
          ],
          "dtype": "float32"
        },
        {
          "name": "conv2_1/bias",
          "shape": [
            16
          ],
          "dtype": "float32"
        },
        {
          "name": "dense1_1/kernel",
          "shape": [
            256,
            32
          ],
          "dtype": "float32"
        },
        {
          "name": "dense1_1/bias",
          "shape": [
            32
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_1/kernel",
          "shape": [
            32,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_1/recurrent_kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_1/bias",
          "shape": [
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_b_1/kernel",
          "shape": [
            32,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_b_1/recurrent_kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru1_b_1/bias",
          "shape": [
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_1/kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_1/recurrent_kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_1/bias",
          "shape": [
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_b_1/kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_b_1/recurrent_kernel",
          "shape": [
            512,
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "gru2_b_1/bias",
          "shape": [
            1536
          ],
          "dtype": "float32"
        },
        {
          "name": "dense2_1/kernel",
          "shape": [
            1024,
            28
          ],
          "dtype": "float32"
        },
        {
          "name": "dense2_1/bias",
          "shape": [
            28
          ],
          "dtype": "float32"
        }
      ]
    }
  ]
}
```

It looks modelTopology is null.

Is this the cause of error?
Is it because of CTC loss function or GRU?
Is there any way to avoid the error?

Thanks in advance.

**Comment by caisq** [comment]
@kouohhashi Is it possible for you to share a link to the saved keras model (in HDF5 format) with us so we can try reproducing the issue?

**Comment by kouohhashi** [comment]
I checked the code and realized the code saved weight only. 
My bad. Sorry about bothering you guys....

**Comment by josesuero** [comment]
I'm having the exact same problem, how where you able to fix it? what command did you use to correctly export the model?

**Comment by josesuero** [comment]
The problem was generating the model as @kouohhashi said, I was doing:
model.save_weights('fileName.h5')

and I has to do 

model.save("fileName.h5") this converted to tensorflow.js correctly and finally got nodejs to predict my image correctly

**Comment by lewis617** [comment]
@caisq I also have this problem, the h5 file I use is https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf.h5

**Comment by ioanacaramavrov** [comment]
> #### TensorFlow.js version
> @tensorflow/tfjs": "^0.13.5"
> or
> "@tensorflow/tfjs-node": "^0.1.21",
> 
> #### Browser version
> Google Chrome Version 70.0.3538.102
> 
> #### Describe the problem or feature request
> I converted a Keras model into Tensorflowjs model with tensorflowjs_converter
> tensorflowjs_converter version:
> 
> ```
> tensorflowjs_converter --version
> 
> Using TensorFlow backend.
> 
> tensorflowjs 0.6.7
> 
> Dependency versions:
>   keras 2.2.2
>   tensorflow 1.12.0
> ```
> 
> #### Code to reproduce the bug / link to feature request
> I downloaded the Keras model [here](https://github.com/Tony607/keras-image-ocr).
> The model is about text recognition with GRU and CTC loss.
> 
> When I try to load the model,
> 
> ```
> const model1 = await tf.loadModel('Path to File');
> ```
> 
> I got the error says,
> 
> ```
> (node:26074) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'model_config' of null
>     at ./node_modules/@tensorflow/tfjs-layers/src/models.ts:267:20
>     at ./node_modules/@tensorflow/tfjs-layers/dist/models.js:42:23)
>     at ./node_modules/@tensorflow/tfjs-layers/dist/models.js:23:53)
>     at ,/node_modules/@tensorflow/tfjs-layers/dist/models.js:14:58)
>     at <anonymous>
> ```
> 
> I got same error both from node.js and browser.
> 
> here is the model.json:
> 
> ```
> {
>   "modelTopology": null,
>   "weightsManifest": [
>     {
>       "paths": [
>         "group1-shard1of5",
>         "group1-shard2of5",
>         "group1-shard3of5",
>         "group1-shard4of5",
>         "group1-shard5of5"
>       ],
>       "weights": [
>         {
>           "name": "conv1_1/kernel",
>           "shape": [
>             3,
>             3,
>             1,
>             16
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "conv1_1/bias",
>           "shape": [
>             16
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "conv2_1/kernel",
>           "shape": [
>             3,
>             3,
>             16,
>             16
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "conv2_1/bias",
>           "shape": [
>             16
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "dense1_1/kernel",
>           "shape": [
>             256,
>             32
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "dense1_1/bias",
>           "shape": [
>             32
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_1/kernel",
>           "shape": [
>             32,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_1/recurrent_kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_1/bias",
>           "shape": [
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_b_1/kernel",
>           "shape": [
>             32,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_b_1/recurrent_kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru1_b_1/bias",
>           "shape": [
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_1/kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_1/recurrent_kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_1/bias",
>           "shape": [
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_b_1/kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_b_1/recurrent_kernel",
>           "shape": [
>             512,
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "gru2_b_1/bias",
>           "shape": [
>             1536
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "dense2_1/kernel",
>           "shape": [
>             1024,
>             28
>           ],
>           "dtype": "float32"
>         },
>         {
>           "name": "dense2_1/bias",
>           "shape": [
>             28
>           ],
>           "dtype": "float32"
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> It looks modelTopology is null.
> 
> Is this the cause of error?
> Is it because of CTC loss function or GRU?
> Is there any way to avoid the error?
> 
> Thanks in advance.

Hi, I have the same problem and I really don't know how to solve it. It is for my license programm for the university, can you please help me with this? Thank you!

**Comment by lebron8dong** [comment]
> @caisq I also have this problem, the h5 file I use is https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf.h5

Did you solve it?
