### ISSUE TITLE
Functionality for Training GANs

### ISSUE THREAD

**Issue by dsanders11** [tensorflow/tfjs#933]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Describe the problem or feature request

What functionality still needs to be implemented in TensorFlow.js to implement the equivalent of [this GAN example with Python TensorFlow](https://github.com/aadilh/blogs/blob/new/basic-gans/basic-gans/code/gan.py)?

I know that's a fairly open-ended question, but I'm having a bit of trouble matching up functionality between Python TensorFlow and TensorFlow.js due to differences in naming. So here's a couple guesses.

* `tf.variable_scope` - Not implemented in JS
* `tf.placeholder` - Not implemented in JS?
* `tf.reduce_mean` in Python == `tf.reduce` in JS?
* `tf.get_collection` - Not implemented in JS
* `tf.Session` - Not implemented in JS

It seems like the big functionality difference would be `tf.Session` and `tf.variable_scope`. I see that there's a `nameScope` in `tfjs-layers` although it doesn't look like it's part of the public API.

Is that functionality on the roadmap? Or is there similar functionality in TensorFlow.js currently which can be used to train a GAN like in the example?

**Comment by tafsiri** [comment]
Hi @dsanders11, I think some of the python concepts like `variable_scope`, `placeholder`, `get_collection` and `Session` have no equivalent in JS as they are graph related concepts and TensorFlow.js is [eager-mode](https://www.tensorflow.org/guide/eager) only (and we don't plan on adding a deferred execution graph mode). 

You could find an example in python that implements the GAN you are interested in eager mode and would probably have an easier time doing the code conversion (as those functions would also not be used in python eager mode). Or you can also check out the [gallery](https://github.com/tensorflow/tfjs/blob/master/GALLERY.md) as there are some folks who have implemented GANs in TensorFlow.js that might give you pointers. Including https://mwdchang.github.io/tfjs-gan/ and https://poloclub.github.io/ganlab/

**Comment by pyu10055** [comment]
Another way is to train the model in python, save the result in SavedModel
format and use tfjs-converter to import to tfjs.

**Comment by dsanders11** [comment]
@tafsiri, thanks for the explanations and examples. I hadn't seen the GANs in gallery, I had only looked in the tensorflow/tfjs-models. It sounds like the eager vs graph mode is the main difference I wasn't aware of.

**Comment by rthadur** [comment]
Hope this is answered and closing it , please feel free to reopen.
