### ISSUE TITLE
gradMode not documented in https://js.tensorflow.org/api/latest/#tidy

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#935]
Documentation for `tidy `mentions `gradMode` but provides no information (other than it is an optional boolean). The code for `tidy` has this comment "gradMode Primarily for internal use during backprop"

**Comment by nsthorat** [comment]
It's an internal API, we'll remove it in https://github.com/tensorflow/tfjs-core/pull/1414
