### ISSUE TITLE
Unsupported Ops in the model before optimization MirrorPad, DecodeRaw, RandomUniformInt, ParseSingleExample

### ISSUE THREAD

**Issue by steren** [tensorflow/tfjs#936]
I am trying to convert a model I trained in Python to a tensorflowjs-compatible model

When I run `tensorflowjs_converter` on my SavedModel, I get the following error due to operations not yet implemented (see [list](https://github.com/tensorflow/tfjs-converter/blob/master/docs/supported_ops.md)):

```
ValueError: Unsupported Ops in the model before optimization
MirrorPad, DecodeRaw, RandomUniformInt, ParseSingleExample
```

**Comment by steren** [comment]
After some more iteration using different TF methods to load out images, we managed to reduce the dependencies to `DecodeJpeg, ReadFile`.

And ultimately, we got rid of the issue. In our case, we used `build_raw_serving_input_receiver_fn`.

**Comment by pyu10055** [comment]
@steren Can you confirm that you have a work-around for the missing op issue? Thanks

**Comment by steren** [comment]
I confirm that I have refactored my Python code to not depend on these operations.

**Comment by rthadur** [comment]
Thank you , closing this issue , feel free to reopen the issue if it is not resolved.
