### ISSUE TITLE
Unable to access pre-trained frozen model layers and nodes in tensorflow-js

### ISSUE THREAD

**Issue by Raza25** [tensorflow/tfjs#942]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Describe the problem or feature request 
I trained a keras Seq2Seq model with tensorflow backend. Froze the model, then used GTT (google transform tool) for quantization and weights rounding. I did this to reduce the model size from 100 mb to 25 mb. The GTT also produces a resultant .pb model with quantized weights. 
After I load the aforementioned model in tensorflow-js, I am unable to access its layers and other nodes. Also there is not much help over the internet regarding inspecting the frozen model in tfjs.
1) Any steps for accessing the model layers
2) Way to convert this quantized .pb model into json

**Comment by pyu10055** [comment]
@Raza25 have you used the [tfjs-converter](https://github.com/tensorflow/tfjs-converter) to convert the frozen model to tfjs format? Here is a [tutorial](https://js.tensorflow.org/tutorials/import-saved-model.html) on how to do that.

**Comment by Raza25** [comment]
@pyu10055 yes, I have converted the model via tfjs-converter. My real concern is, how to inspect/diagnose or use the .pb model in tfjs. Json model architecture is easily accessible, however it is not the case with frozen model. I suppose the layers information is removed at the time of freezing a graph.

Note: I am working with RNN, thereby require layers information for inference model in tfjs.

**Comment by pyu10055** [comment]
@Raza25 Got it, I have created a pb to json script https://github.com/tensorflow/tfjs-converter/pull/256. You can try that with your model.

**Comment by Raza25** [comment]
@pyu10055 this script flawlessly converts .pb to .json, but in my case the quantized.pb file with size 18 MB was converted to quantized.json with an imprint of 247 MB. This really penalizes the entire struggle for reducing the size.  
As any model >50 mb doesn't load in tfjs and the web console dies.
Kindly look into it, would you!

**Comment by pyu10055** [comment]
@Raza25 the script converts the pb file to json, but the json file cannot be loaded by tfjs, since we don't support loading json frozen model format, it is meant to help to see what nodes the converter generates.
If your goal is to inspect layer information of the converted graph in run-time, unfortunately, the layer information are removed when you freeze the model, but the node name still has layer name prefixes.

To view the nodes of the graph in run-time you can do following:
```
const model = tf.loadFrozenModel(modelUrl, manifestUrl);
console.log(model.executor.graph.nodes); 
```

**Comment by Raza25** [comment]
@pyu10055 my very basic question or you can say 'concern' is how can I simply reduce the size of my keras RNN for seq2seq with footprint of 120 MB to less than 30 MB.
All of the quantization techniques available accept and produces .pb file to work on. 
The aforementioned .pb file isn't easy to work on in tfjs.
I just require a way to reduce the model.h5 size, convert the reduced model.h5 to (model.json + group-shard) using tfjs converter and finally loading it in tjfs via loadModel.
Thats about it, really!
