### ISSUE TITLE
How can I give the video input to PoseNet using TensorFlow.js without an HTML page?

### ISSUE THREAD

**Issue by swatinair123** [tensorflow/tfjs#943]
My aim is to save the extracted keypoints from a prerecorded video to a .json file. So is there a way i can give the video input directly to the camera.js without HTML so that i can run camera.js directly from cmd like node camera.js.Can anyone tell me how this can be done.? Currently i am able to extract the keypoints for the poses from a prerecorded video and display using console.

**Comment by nsthorat** [comment]
You could run it in Node.js to do that!

**Comment by nsthorat** [comment]
Also, this would be better on the tfjs community mailing list, we're using issues for problems with the library. Going to close this out :)
