### ISSUE TITLE
Implement SRU

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#95]
_From @MariasStory on December 30, 2017 22:11_

https://github.com/taolei87/sru

Training RNNs as Fast as CNNs (https://arxiv.org/abs/1709.02755)

_Copied from original issue: tensorflow/tfjs-core#493_

**Comment by caisq** [comment]
@MariasStory I added "help wanted" tag to this issue to indicate that contribution of SRU to tfjs is welcome :)

**Comment by gaikwadrahul8** [comment]
Hi, @nsthorat

We carefully reviewed this feature request and are not planning to implement this feature due to other priorities. We are closing this issue and If you require further assistance with this feature request, please feel free to re-open this issue. Thank you!
