### ISSUE TITLE
Some androids failure to compile fragment shader

### ISSUE THREAD

**Issue by asus4** [tensorflow/tfjs#952]
#### TensorFlow.js version
0.13.5

#### Browser version
- Android: 6.0.1
- Chrome: 70.0.3536.110
- Error Devices:
  - Xperia Z3 SO-01G
  - GALAXY S5 SC-04F
  - AQUOS EVER SH-04G

#### Describe the problem or feature request

Tested tfjs-examples on mobile and some android devices failure to compile fragment shader. if the gpu spec is low, it tend to failure. All failure devices threw following error. Do you have a minimum requirement?

| Link | QR | iPhone7 Plus | Xperia XZ2 | Xperia Z3 |
|------|-----|:------:|:------:|:-----:|
| [Posenet Sample](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html) | ![image](https://user-images.githubusercontent.com/357497/49208779-053d1f00-f3fc-11e8-87db-7788ec67faec.png) | OK | OK | Error |
| [Custom Layer](https://storage.googleapis.com/tfjs-examples/custom-layer/dist/index.html) | ![image](https://user-images.githubusercontent.com/357497/49209278-6adddb00-f3fd-11e8-8fed-cefbd671d749.png) | OK | OK | Error |

#### Error log

```
1    
2      precision highp float;
3      precision highp int;
4      varying vec2 resultUV;
5      const vec2 halfCR = vec2(0.5, 0.5);
6    
7      struct ivec5
8      {
9        int x;
10       int y;
11       int z;
Fragment shader compilation failed.
12       int w;                                                                   
13       int u;
14     };
15   
16     struct ivec6
17     {
18       int x;
19       int y;
20       int z;
21       int w;
22       int u;
23       int v;
24     };
25   
26     bool isNaN(float val) {
27       return (val < 0.0 || 0.0 < val || val == 0.0) ? false : true;
28     }
29   
30     bool hasNaN(vec4 values) {
31       vec4 v1 = values * values;
32       vec4 v2 = values * values;
33       return any(notEqual(v1, v2));
34     }
35   
36     float getNaN(vec4 values) {
37       return dot(vec4(1), values);
38     }
39   
40     int round(float value) {
41       return int(floor(value + 0.5));
42     }
43   
44     int imod(int x, int y) {
45       return x - y * (x / y);
46     }
47   
48     //Based on the work of Dave Hoskins
49     //https://www.shadertoy.com/view/4djSRW
50     #define HASHSCALE1 443.8975
51     float random(float seed){
52       vec2 p = resultUV * seed;
53       vec3 p3  = fract(vec3(p.xyx) * HASHSCALE1);
54       p3 += dot(p3, p3.yzx + 19.19);
55       return fract((p3.x + p3.y) * p3.z);
56     }
57   
58     
59   vec2 UVfrom1D(int texNumR, int texNumC, int index) {
60     int texR = index / texNumC;
61     int texC = index - texR * texNumC;
62     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
63   }
64   
65     
66   vec2 UVfrom2D(int texNumR, int texNumC, int numC, int row, int col) {
67     int index = row * numC + col;
68     int texR = index / texNumC;
69     int texC = index - texR * texNumC;
70     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
71   }
72   
73     
74   vec2 UVfrom3D(int texNumR, int texNumC, int stride0,
75       int stride1, int row, int col, int depth) {
76     // Explicitly use integer operations as dot() only works on floats.
77     int index = row * stride0 + col * stride1 + depth;
78     int texR = index / texNumC;
79     int texC = index - texR * texNumC;
80     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
81   }
82   
83     
84   vec2 UVfrom4D(int texNumR, int texNumC, int stride0,
85       int stride1, int stride2, int row, int col, int depth,
86       int depth2) {
87     // Explicitly use integer operations as dot() only works on floats.
88     int index = row * stride0 + col * stride1 + depth * stride2 + depth2;
89     int texR = index / texNumC;
90     int texC = index - texR * texNumC;
91     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
92   }
93   
94     
95   vec2 UVfrom5D(int texNumR, int texNumC, int stride0,
96       int stride1, int stride2, int stride3, int row, int col, int depth,
97       int depth2, int depth3) {
98     // Explicitly use integer operations as dot() only works on floats.
99     int index = row * stride0 + col * stride1 +
100                depth * stride2 + depth2 * stride3 + depth3;
101    int texR = index / texNumC;
102    int texC = index - texR * texNumC;
103    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
104  }
105  
106    
107  vec2 UVfrom6D(int texNumR, int texNumC, int stride0,
108      int stride1, int stride2, int stride3, int stride4,
109      int row, int col, int depth, int depth2, int depth3, int depth4) {
110    // Explicitly use integer operations as dot() only works on floats.
111    int index = row * stride0 + col * stride1 + depth * stride2 + depth2 *
112      stride3 + depth3 * stride4 + depth4;
113    int texR = index / texNumC;
114    int texC = index - texR * texNumC;
115    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
116  }
117  
118  
119  
120    float sampleTexture(sampler2D textureSampler, vec2 uv) {
121      return texture2D(textureSampler, uv).r;
122    }
123  
124  
125    void setOutput(float val) {
126      gl_FragColor = vec4(val, 0, 0, 0);
127    }
128  
129  uniform sampler2D A;
130  
131      ivec4 getOutputCoords() {
132        ivec2 resTexRC = ivec2(resultUV.yx *
133          vec2(241, 867));
134        int index = resTexRC.x * 867 + resTexRC.y;
135  
136        int r = index / 208947;
137        index -= r * 208947;
138  
139        int c = index / 867;
140        index -= c * 867;
141  
142        int d = index / 3;
143        int d2 = index - d * 3;
144  
145        return ivec4(r, c, d, d2);
146      }
147    
148  
149      float getAFlat(int index) {
150        vec2 uv = UVfrom1D(500, 1800, index);
151        return sampleTexture(A, uv);
152      }
153    
154        
155          float getA(int row, int col, int depth) {
156            int texR = row;
157            int texC = col * 3 + depth;
158            vec2 uv = (vec2(texC, texR) + halfCR) /
159                       vec2(1800.0, 500.0);
160            return sampleTexture(A, uv);
161          }
162        
163        float getA(int row, int col, int depth, int depth2) {
164          return getA(col, depth, depth2);
165        }
166      
167  
168        const vec2 effectiveInputOverOutputRatioRC = vec2(
169            2.074688796680498,
170            2.0761245674740483);
171        const vec2 inputShapeRC = vec2(500.0, 600.0);
172  
173        void main() {
174          ivec4 coords = getOutputCoords();
175          int b = coords[0];
176          int d = coords[3];
177          ivec2 yRC = coords.yz;
178  
179          // Fractional source index.
180          vec2 sourceFracIndexRC = vec2(yRC) * effectiveInputOverOutputRatioRC;
181  
182          // Compute the four integer indices.
183          ivec2 sourceFloorRC = ivec2(sourceFracIndexRC);
184          ivec2 sourceCeilRC = ivec2(
185            min(inputShapeRC - 1.0, ceil(sourceFracIndexRC)));
186  
187          float topLeft = getA(b, sourceFloorRC.x, sourceFloorRC.y, d);
188          float bottomLeft = getA(b, sourceCeilRC.x, sourceFloorRC.y, d);
189          float topRight = getA(b, sourceFloorRC.x, sourceCeilRC.y, d);
190          float bottomRight = getA(b, sourceCeilRC.x, sourceCeilRC.y, d);
191  
192          vec2 fracRC = sourceFracIndexRC - vec2(sourceFloorRC);
193  
194          float top = topLeft + (topRight - topLeft) * fracRC.y;
195          float bottom = bottomLeft + (bottomRight - bottomLeft) * fracRC.y;
196          float newValue = top + (bottom - top) * fracRC.x;
197  
198          setOutput(newValue);
199        }
200 
```

```
tf-core.esm.js:17 Uncaught Error: Failed to compile fragment shader.
    at createFragmentShader (tf-core.esm.js:17)
    at e.createProgram (tf-core.esm.js:17)
    at compileProgram (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at e.getAndSaveBinary (tf-core.esm.js:17)
    at e.compileAndRun (tf-core.esm.js:17)
    at e.slice (tf-core.esm.js:17)
    at ENV.engine.runKernel.$x (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at e.scopedRun (tf-core.esm.js:17)
createFragmentShader @ tf-core.esm.js:17
e.createProgram @ tf-core.esm.js:17
compileProgram @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
e.getAndSaveBinary @ tf-core.esm.js:17
e.compileAndRun @ tf-core.esm.js:17
e.slice @ tf-core.esm.js:17
ENV.engine.runKernel.$x @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
e.scopedRun @ tf-core.esm.js:17
e.runKernel @ tf-core.esm.js:17
slice_ @ tf-core.esm.js:17
slice @ tf-core.esm.js:17
e.slice @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
split @ tf-core.esm.js:17
e.split @ tf-core.esm.js:17
ENV.engine.runKernel.$x @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
e.scopedRun @ tf-core.esm.js:17
e.runKernel @ tf-core.esm.js:17
split_ @ tf-core.esm.js:17
slice @ tf-core.esm.js:17
customLayerDemo @ index.js:27
parcelRequire.3.babel-runtime/helpers/slicedToArray @ index.js:56
newRequire @ custom-layer.32c31cce.js:48
(anonymous) @ custom-layer.32c31cce.js:75
(anonymous) @ custom-layer.32c31cce.js:101
```

**Comment by justadudewhohacks** [comment]
Since it might be interesting, someone reported the same issue at face-api.js on a SONY Xperia A4 with Android 6.0.1: https://github.com/justadudewhohacks/face-api.js/issues/151

**Comment by kangyizhang** [comment]
Hi @asus4  and @justadudewhohacks , 

Yes we do have minimum requirement for webgl. If it's webgl1 it needs to have this extension https://www.khronos.org/registry/webgl/extensions/OES_texture_float/

**Comment by wukann** [comment]
@kangyizhang 
Hi, I'm SONY Xperia A4's owner. My device had the same error.
So I checked the WebGL feature supported by the device at http://webglreport.com/?v=1 .
My device seems to support OES_texture_float...?

![screenshot_20181203-150124](https://user-images.githubusercontent.com/3864473/49356011-81da4100-f70d-11e8-90b4-a6dd3b8500dc.png)

**Comment by asus4** [comment]
Xperia Z3 SO-01G also supports `OES_texture_float` according to WebGLReport.

**Comment by bryan-14four** [comment]
Same issue here running Chrome on both the Galaxy S4 and S5. The issue has been around for at least 6 months, so I'm surprised that this doesn't have more attention.

**Comment by bryan-14four** [comment]
Has anyone resolved this yet or have any insight? I wonder if the issue is really even related to fragment shader compilation at all. I have an old project using TFJS which is working on my Galaxy S4/S5 devices. My current project is also using TFJS via faceapi.js, but it is running into the fragment shader compilation issue mentioned above on those devices. I tried taking tfjs-core from my old project (v0.12.17) and putting it into the new project, but the same error is present even using the old version.

**Comment by bryan-14four** [comment]
I've done some additional testing of tfjs-examples on my Galaxy S5. I could not test some examples because they were broken for other reasons (in most cases the XHR loading data files failed because the resource no longer exists).

Hopefully this helps to better isolate the issue. I will try to build a reduced test case from it.

Here are the results:

| Example | Working? | Error Message | Notes |
| --- | --- | --- | --- |
| [addition-rnn](https://storage.googleapis.com/tfjs-examples/addition-rnn/dist/index.html) | ✅ |  |  |
| [boston-housing](https://storage.googleapis.com/tfjs-examples/boston-housing/dist/index.html) | ✅ |  | All three regressors work |
| [cart-pole](https://storage.googleapis.com/tfjs-examples/cart-pole/dist/index.html) | ✅ |  |  |
| [custom-layer](https://storage.googleapis.com/tfjs-examples/custom-layer/dist/index.html) | ❌ | Error: Failed to compile fragment shader. | Error shows immediately upon visiting the page |
| [iris-fitDataset](https://storage.googleapis.com/tfjs-examples/iris-fitDataset/dist/index.html) | ✅ |  |  |
| [iris](https://storage.googleapis.com/tfjs-examples/iris/dist/index.html) | ✅ |  |  |
| [lstm-text-generation](https://storage.googleapis.com/tfjs-examples/lstm-text-generation/dist/index.html) | ✅ |  |  |
| [mnist-core](https://storage.googleapis.com/tfjs-examples/mnist-core/dist/index.html) | ✅ |  |  |
| [mobilenet](https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html) | ❌ | Error: Failed to compile fragment shader. | Error shows immediately upon visiting the page |
| [polynomial-regression-core](https://storage.googleapis.com/tfjs-examples/polynomial-regression-core/dist/index.html) | ✅ |  |  |
| [polynomial-regression](https://storage.googleapis.com/tfjs-examples/polynomial-regression/dist/index.html) | ✅ |  |  |
| [sentiment](https://storage.googleapis.com/tfjs-examples/sentiment/dist/index.html) | ✅ |  |  |
| [translation](https://storage.googleapis.com/tfjs-examples/translation/dist/index.html) | ✅ |  |  |
| [tsne-mnist-canvas](https://storage.googleapis.com/tfjs-examples/tsne-mnist-canvas/dist/index.html) | ❌ | gl_util.ts:99 WebGL: INVALID_ENUM: texImage2D: invalid format<br/>gl_util.ts:99 WebGL: INVALID_ENUM: texImage2D: invalid format<br/>webgl_util.ts:91 ERROR: unsupported shader version <br/>index.html:1 [.WebGL-0x9d2b8a00]GL ERROR :GL_INVALID_VALUE : glTexImage2D: invalid internal_format GL_CLOSE_PATH_NV<br/>webgl_util.ts:92 Uncaught (in promise) Error: Failed to compile vertex shader. | Error shows when clicking "Start T-SNE" |
| [webcam-transfer-learning](https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html) | ❌ | Error: Failed to compile fragment shader. | Error shows upon allowing access to webcam |

**Comment by bryan-14four** [comment]
Here is a reduced test case, using Galaxy S5 running Chrome. Can anyone determine if this is either a device limitation or a bug in TFJS?

This code succeeds:
```
import * as tf from '@tensorflow/tfjs'

tf.split(tf.zeros([1, 65535, 1, 2]), 2, 3)
```

This code fails:
```
import * as tf from '@tensorflow/tfjs'

tf.split(tf.zeros([1, 65536, 1, 2]), 2, 3)
```

Full console output: 
![tfjs-error](https://user-images.githubusercontent.com/28308133/53522399-24952800-3a8f-11e9-8199-a8458be12c49.png)

**Comment by bryan-14four** [comment]
I have an update on this. The two code snippets above produce different shader code, where the test with the 65536 int fails on shader compilation inside of the getOutputCoords() function.

---
Success:
`tf.split(tf.zeros([1, 65535, 1, 2]), 2, 3)` -> 
```
ivec4 getOutputCoords() {
  ...
  int r = index / 65535;
  index -= r * 65535;
  ...
}
```
---
Failure:
`tf.split(tf.zeros([1, 65536, 1, 2]), 2, 3)` -> 
```
ivec4 getOutputCoords() {
  ...
  int r = index / 65536;
  index -= r * 65536;
  ...
}
```

---

I pulled these shader sources out manually and wrote some webGL code to run them. In the failing test, the shader compilation fails both on the `int r = ...` and `index -= ...` lines due to an "integer constant overflow". Interestingly, I've found a way to make the shader compile by replacing the function with this logically-equivalent one:

```
ivec4 getOutputCoords() {
  ...
  int aa = 256;
  int bb = 256;
  int r = index / (aa * bb);
  index -= r * (aa * bb);
  ...
}
```

I'm not sure if this code actually works as a fix, or if the integer primitive itself is limited to 16 bits on this device (a possibility is that the "aa * bb" portion is overflowing silently, whereas the constant "65536" fails with an error). I will do more testing and report back.

**Comment by bryan-14four** [comment]
In my case, the hack I posted above seems to actually work. I replaced the "getLogicalCoordinatesFromFlatIndex" function directly in tf-core.esm.js (I'm not working from source, so I've been directly editing from node_modules package). Here is what I replaced it with:

```
function getLogicalCoordinatesFromFlatIndex(coords, shape, index = 'index') {
  var strides = computeStrides(shape);
  var returnVal = `int aa = 0; ${strides.map((stride, i) => {
    var quantity = Math.floor(stride / 65535);
    var remainder = stride % 65535;
    var line0 = `aa = ${quantity}; aa = aa * 65535; aa = aa + ${remainder}`;
    var line1 = `int ${coords[i]} = ${index} / aa`;
    var line2 = i === strides.length - 1 ?
        `int ${coords[i + 1]} = ${index} - ${coords[i]} * aa` :
        `index -= ${coords[i]} * aa`;
    return `${line0}; ${line1}; ${line2};`;
  })
  .join('')}`;
  return returnVal;
}
```

It's definitely a hack, and I'm not sure of any side-effects of doing it this way, but for my use-case it seems to work. I'm done looking into this issue, so hopefully someone can take over where I left off and make a more meaningful contribution.

**Comment by witalobenicio** [comment]
@bryan-14four I'm using `faceapi.js` and the only package related to `tensorflow.js` that is installed is `tfjs-image-recognition-base` and it doesn't have this file.
Could be more specific about the location of this file?

**Comment by witalobenicio** [comment]
@bryan-14four sorry, I was looking in the wrong place.

**Comment by witalobenicio** [comment]
@bryan-14four I've updated the method directly in the file that you mentioned, but no success.
Do we have to run some command to apply changes or something?

**Comment by bryan-14four** [comment]
> @bryan-14four I've updated the method directly in the file that you mentioned, but no success.
Do we have to run some command to apply changes or something?

Here's what I did for my project. At the time I used face-api.js version ^0.18.0 which uses tfjs-core v0.14.2, so you'll have to set package.json deps to {"face-api.js": "^0.18.0"} (unless newer versions use the same version of tfjs). This solution uses `patch-package` to patch tfjs-core v0.14.2.

1. `npm i patch-package`
2. In package.json, add to "scripts" section: `"postinstall": "patch-package"`
3. Create a folder called `patches` in the root dir of the app (same place as package.json).
4. Extract the patch file I've included below to the `patches` folder.
5. Run `npm i` again and it should install the modules and apply the patch.

Patch file: [@tensorflow+tfjs-core+0.14.2.patch.zip](https://github.com/tensorflow/tfjs/files/3346704/%40tensorflow%2Btfjs-core%2B0.14.2.patch.zip)

Good luck!

**Comment by witalobenicio** [comment]
@bryan-14four I've tried locally here, and it worked. I'll try now with a builded version. But thanks in advance.

**Comment by thirukumars** [comment]
$(document).ready(function(){
run()
})
async function run(){
    await faceapi.loadMtcnnModel('./models');
    await faceapi.loadFaceRecognitionModel('./models');
    const videoEl=document.getElementById('inputVideo')
    navigator.getUserMedia(
        {video:{}},
        stream=>videoEl.srcObject=stream,
        err=>console.err(err)
    )
}
async function onPlay(videoEl){
    
    setInterval( async ()=>{console.log('it is running');

    const mtcnnForwardParams = {
        maxNumScales: 10,
        scaleFactor: 0.709,
        scoreThresholds: [0.6, 0.7, 0.7],
        minFaceSize: 200
      }
      const canvas=document.getElementById('overlay')
    const mtcnnResults=await faceapi.mtcnn(videoEl,mtcnnForwardParams)
    canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)
    faceapi.drawDetection(canvas, mtcnnResults.map(res => res.faceDetection), { withScore: false })
      faceapi.drawLandmarks(canvas, mtcnnResults.map(res => res.faceLandmarks), { lineWidth: 4, color: 'red' })
    },1000)
}

this is my javascript code,i got this error,please help to sort out

script2.js:27 Uncaught (in promise) TypeError: faceapi.drawDetection is not a function
    at script2.js:27

**Comment by rthadur** [comment]
@thirukumars please open a new isse here [New Issue Template](https://github.com/tensorflow/tfjs/issues/new) , closing this, thank you

**Comment by msj121** [comment]
> > @bryan-14four I've updated the method directly in the file that you mentioned, but no success.
> > Do we have to run some command to apply changes or something?
> 
> Here's what I did for my project. At the time I used face-api.js version ^0.18.0 which uses tfjs-core v0.14.2, so you'll have to set package.json deps to {"face-api.js": "^0.18.0"} (unless newer versions use the same version of tfjs). This solution uses `patch-package` to patch tfjs-core v0.14.2.
> 
> 1. `npm i patch-package`
> 2. In package.json, add to "scripts" section: `"postinstall": "patch-package"`
> 3. Create a folder called `patches` in the root dir of the app (same place as package.json).
> 4. Extract the patch file I've included below to the `patches` folder.
> 5. Run `npm i` again and it should install the modules and apply the patch.
> 
> Patch file: [@tensorflow+tfjs-core+0.14.2.patch.zip](https://github.com/tensorflow/tfjs/files/3346704/%40tensorflow%2Btfjs-core%2B0.14.2.patch.zip)
> 
> Good luck!

@bryan-14four Followed your instruction, I even got:

 

> npm i
> 
> > project@1.0.0 postinstall /project
> > patch-package
> 
> patch-package 6.1.2
> Applying patches...
> @tensorflow/tfjs-core@0.14.2 ✔
> npm WARN com.package@1.0.0 No repository field.
> 
> audited 1136 packages in 2.186s
> found 3 vulnerabilities (1 low, 2 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
> 

But still when I do "cordova run android" I get the same error as before:

> 1    
> 2        precision highp float;
> 3        precision highp int;
> 4        precision highp sampler2D;
> 5        varying vec2 resultUV;
> 6        
> 7        const vec2 halfCR = vec2(0.5, 0.5);
> 8    
> 9        struct ivec5
> 10       {
> 11         int x;
> 12         int y;
> 13         int z;
> 14         int w;
> 15         int u;
> 16       };
> 17   
> face-api.js:100 Fragment shader compilation failed.
> face-api.js:100  18       struct ivec6                                                             
> face-api.js:100 19       {
> 20         int x;
> 21         int y;

I appreciate any help or advice you can offer because I would greatly appreciate anything. Been stuck on this for a while now. tf-core.esm.js did look correct after patch. Am I missing something, can I just run "cordova run android" or do I need to do something first? I tried removing android platform and adding it again with no luck. I am running on Nexus 5 android 6.0.1

**Comment by lewisf** [comment]
Is there any reason why this patch hasn't become a pull request upstream? Wondering if there are next steps for `tfjs` as a whole rather than locally patching.

**Comment by IbrahimAliAsghar** [comment]
@bryan-14four  I am using tfjs direclty from browser by calling the face-api.js script, any idea how i can fix there. ?

**Comment by warrenseine** [comment]
Sharing an updated version of this patch which worked for Face Mesh:

```diff
diff --git a/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler.js b/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler.js
index 76e45ed..fbf38eb 100755
--- a/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler.js
+++ b/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler.js
@@ -457,8 +457,10 @@ function getOutputPacked3DCoords(shape, texShape, enableShapeUniforms) {
                              vec2(${packedTexShape[0]}, ${packedTexShape[1]}));
       int index = resTexRC.x * ${packedTexShape[1]} + resTexRC.y;
 
-      int b = index / ${texelsInBatch};
-      index -= b * ${texelsInBatch};
+      int a = ${texelsInLogicalRow};
+      int d = ${Math.ceil(shape[1] / 2)};
+      int b = index / (a * d);
+      index -= b * (a * d);
 
       int r = 2 * (index / ${texelsInLogicalRow});
       int c = imod(index, ${texelsInLogicalRow}) * 2;
@@ -1198,13 +1200,18 @@ function getPackedSamplerND(inputInfo, enableShapeUniforms) {
     let texelsInBatch = valuesPerRow * Math.ceil(shape[rank - 2] / 2);
     let params = `int b, int row, int col`;
     let index = `b * ${texelsInBatch} + (row / 2) * ${valuesPerRow} + (col / 2)`;
+    let line0 = `int s = ${texelsInBatch}; `;
+    for (let b = 2; b < rank - 1; b++) {
+        line0 += `int s${b} = ${shape[rank - b - 1]}; `
+    }
     for (let b = 2; b < rank - 1; b++) {
         params = `int b${b}, ` + params;
-        texelsInBatch *= shape[rank - b - 1];
+        texelsInBatch = `s${b} * ${texelsInBatch}`;
         index = `b${b} * ${texelsInBatch} + ` + index;
     }
     return `
     vec4 ${funcName}(${params}) {
+      ${line0}
       int index = ${index};
       int texR = index / ${texNumC};
       int texC = index - texR * ${texNumC};
diff --git a/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler_util.js b/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler_util.js
index b69f858..d254e51 100755
--- a/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler_util.js
+++ b/node_modules/@tensorflow/tfjs-backend-webgl/dist/shader_compiler_util.js
@@ -24,11 +24,15 @@ export function getLogicalCoordinatesFromFlatIndex(coords, shape, index = 'index
     const strides = util.computeStrides(shape);
     return strides
         .map((stride, i) => {
+        const quantity = Math.floor(stride / 65535);
+        const remainder = stride % 65535;
+        const line0 = `int a${i} = ${quantity}; a${i} = a${i} * 65535; a${i} = a${i} + ${remainder}`;
+        stride = `a${i}`;
         const line1 = `int ${coords[i]} = ${index} / ${stride}`;
         const line2 = i === strides.length - 1 ?
             `int ${coords[i + 1]} = ${index} - ${coords[i]} * ${stride}` :
             `index -= ${coords[i]} * ${stride}`;
-        return `${line1}; ${line2};`;
+        return `${line0}; ${line1}; ${line2};`;
     })
         .join('');
 }
@@ -106,10 +110,14 @@ export function dotify(x, y) {
  * Produces GLSL that computes the flat index from 3D coordinates.
  */
 export function getFlatIndexFrom3D(shape) {
-    const strides = util.computeStrides(shape).map(d => d.toString());
     return `
   int getFlatIndex(ivec3 coords) {
-    return coords.x * ${strides[0]} + coords.y * ${strides[1]} + coords.z;
+    ${util.computeStrides(shape).map((stride, i) => {
+      const quantity = Math.floor(stride / 65535);
+      const remainder = stride % 65535;
+      return `int a${i} = ${quantity}; a${i} = a${i} * 65535; a${i} = a${i} + ${remainder}`;
+    }).join(';')};
+    return coords.x * a0 + coords.y * a1 + coords.z;
   }
 `;
 }
```
