### ISSUE TITLE
Support GLSL ES300 to improve precision on Android devices where WebGL 2.0 is available.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#953]
We'll have to do a bit of wrangling to still support the older ES versions (WebGL 1.0), but this will improve precision on Android devices with WebGL 2.0 (iPhones are still on WebGL 1.0).

See the commit here: https://github.com/GreyZzzzzzXh/tfjs-core/commit/39a56bf75803ae9327bbf160189f0d08f8a06416

cc @GreyZzzzzzXh

**Comment by GreyZzzzzzXh** [comment]
This commit simply changed the version of GLSL so WebGL 1.0 doesn't work now.
Next i'll try to support multiple shading languages with your help and update it in https://github.com/tensorflow/tfjs-core/pull/1421.
Hope that will help you, thanks!

**Comment by rthadur** [comment]
@nsthorat i see the [PR](https://github.com/tensorflow/tfjs-core/pull/1421) is been merged , can we close this ?

**Comment by nsthorat** [comment]
Yes, this is fixed!
