### ISSUE TITLE
body-pix demo does not work on phones

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#955]
The predictions seem to be working but it looks like the overlay is not properly placed on the image.

cc @oveddan

**Comment by wangtz** [comment]
+1 on this bug 

I tried both Chrome on Pixel and Safari on IOS on portrait mode, none of them works due to the overlay placement issue. However everything seem to work fine on landscape mode.

**Comment by wangtz** [comment]
@huan

**Comment by wangtz** [comment]
Also this demo doesn't work on Chrome for IPhone. Error message: 

his browser does not support video capture,or this device does not have a camera

@airlrj

**Comment by huan** [comment]
I have a Pixel 2 XL and it seems that run this demo in chrome browser will have trouble when the phone in horizontal:

![image](https://user-images.githubusercontent.com/1361891/50437889-a3060a00-0926-11e9-981b-ae99353b8ca7.png)

But it works perfectly when the phone in vertical:

![image](https://user-images.githubusercontent.com/1361891/50437897-ab5e4500-0926-11e9-8c0e-0dab1223a134.png)

**Comment by oveddan** [comment]
Thanks for reporting.  I'll take a look.  

As far as chrome on ios - we haven't supported this on the demos because as far as I understand it is not possible to access the camera in chrome on ios.

**Comment by oveddan** [comment]
@huan @wangtz I've made a quick fix for safari ios, as well as all mobile. 

* The text at the bottom is responsive and doesn't appear on mobile.  
* The rendered video has the same size as the captured video.  This allows for full screen on mobile and gets rid of the bug you reported.

Can you please test?  Particularly on Android?  I tried on the IPhone XR and it works fine now.

In the future I want to add the ability to switch to the rear camera.

**Comment by wangtz** [comment]
@huan Huan, do you want to give it a try?

**Comment by huan** [comment]
I still have the same issue on my pixel 2 XL woth chrome in vertical mode.

**Comment by oveddan** [comment]
Sorry I forgot to give you the link to the demo with the fix, try going here:
https://body-pix-mobile-fix.netlify.com/

**Comment by huan** [comment]
With your new link, the vertical is ok but the horizontal comes with issue that the canvas position is not right.

**Comment by oveddan** [comment]
@huan the same issue that happened before for vertical?  Can you include a screenshot?

**Comment by oveddan** [comment]
I've been working on an improved responsive version of the demo.  It may have fixed the issues. Could you check the latest at:
https://body-pix-mobile-fix.netlify.com/
