### ISSUE TITLE
Unable to add issues on tfjs examples repo

### ISSUE THREAD

**Issue by TommyBs** [tensorflow/tfjs#963]
I'm raising this here as I can't seem to add issues to the tfjs examples repo at https://github.com/tensorflow/tfjs-examples/issues - it just redirects to pull requests even though the readme talks about adding issues and has a link to (the redirecting) issues page.

**Comment by rthadur** [comment]
cc @annxingyuan could you please advise.

**Comment by annxingyuan** [comment]
Hi @TommyBs - sorry for the confusion - could you please add an issue to the tfjs page? Here's the link: https://github.com/tensorflow/tfjs/issues You can add the comp:examples label to the issue which will help us organize.

Thanks so much!
