### ISSUE TITLE
Update FAQ with advice on when to install from NPM

### ISSUE THREAD

**Issue by rozim** [tensorflow/tfjs#965]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

all

#### Browser version

all

#### Describe the problem or feature request

As a new user reading the docs it says "There are two main ways to get TensorFlow.js in your JavaScript project.. (script tags...NPM)" but since script tags are such a low friction way
of using tfjs, it's not clear why one (esp a user that is not a big nodejs user) would use NPMs.

So, please give some guidance as to the tradeoffs e.g. is it because of custom model loading
from a local server? Or adding custom ops to a local server? Faster testing?

I suspect these 2 URLs would change:
https://js.tensorflow.org/faq/
https://js.tensorflow.org/#getting-started

#### Code to reproduce the bug / link to feature request

n/a

**Comment by tafsiri** [comment]
Thanks for the issue report. We deployed an update to the setup page https://js.tensorflow.org/setup/ and added a bit more guidance, but a lot of this comes to developer preference and workflow. It would be beyond the scope of that page to generally discuss the tradeoffs between the script tag workflow and using NPM.

**Comment by rozim** [comment]
Thanks, I understand what you are saying, but I was just going from the
point view (or "user journey")
of someone who can do simple frontend development (namely: JS in the
browser) and then
the "sudden" reference to NPMs is puzzling and the procedure has a fork in
it (script tag or npm)
and it's not clear to such a user if they could choose either fork, etc.

thx,
 Dave
