### ISSUE TITLE
`tfjs-converter` doesn't work with frozen tensorflow graphs

### ISSUE THREAD

**Issue by litenjacob** [tensorflow/tfjs#97]
#### TensorFlow.js version
TensorFlow.js version 0.6.1

#### Describe the problem or feature request
It seems pretty common to get frozen TensorFlow graphs (is that the correct term?!) when eg following the official [Image Retraining tutorial](https://www.tensorflow.org/tutorials/image_retraining) or the [TensorFlow for Poets CodeLab](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets), but it's quite hard to grasp how to use the output of these tutorials with `tfjs-converter` 😔

**Comment by pyu10055** [comment]
Unfortunately the inference graph format is deprecated, and you should be using the SavedModel.
And tfjs-converter only supports SavedModel format.
You can take a look at the [SavedModel document](https://www.tensorflow.org/programmers_guide/saved_model) on how to generate SavedModel.

**Comment by litenjacob** [comment]
Thanks for the quick answer! Ah, I thought it was the other way around 😳

Either way, I found the [emoji-scavenger-hunt Dockerfile](https://github.com/google/emoji-scavenger-hunt/blob/master/training/Dockerfile) which uses the official `retrain` script in a way supported by `tfjs-converter` 😄
