### ISSUE TITLE
tf.all() fails on Chrome on Windows for every 4 elements added to a 1D boolean tensor

### ISSUE THREAD

**Issue by sblabms** [tensorflow/tfjs#978]
Using Chrome Version 71.0.3578.80 (Official Build) (64-bit) in Windows 8

Start with a boolean 5 element 1D tensor. tf.all fails. Keep adding a 0 element. You will find that tf.all fails for every 4 elements (9, 13, 17, 21...) added to the 1D tensor. See image.
![tfallfailinchromeonwindows](https://user-images.githubusercontent.com/20588611/49707426-d6d7f480-fbf0-11e8-8704-cadc8fd965b1.png)

**Comment by sblabms** [comment]
found previous report on bug - goto #978

**Comment by somombo** [comment]
closed. Is duplicate of #968
