### ISSUE TITLE
Update sizeToSquarish to do approximate rectangles

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#983]
When we request a tensor with dimensions that are larger than the WebGL limit, we factorize that tensor into a rectangular grid that has the exact size as the requested size.

This means that tensors with size that factorizes into `SMALLER_FACTOR x LARGER_FACTOR` can't be allocated if `LARGER_FACTOR` doesn't fit the WebGL limit. This happens for prime numbers, but also generally for large tensors.

We should relax this constraint by padding the texture and reshaping it into `A x B` where: 
```js
A = Math.ceil(Math.sqrt(size))
B = Math.ceil(size / A)
```

**Comment by dsmilkov** [comment]
cc @nsthorat @annxingyuan

**Comment by nsthorat** [comment]
One thing that @annxingyuan mentioned to me is that it's actually faster to use textures with dimensions that are powers of two (even if they are larger). This is something we might want to do as well.
