### ISSUE TITLE
Upload shapes as uniforms wherever possible.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#987]
Where possible we should upload shapes to GPGPUPrograms as uniforms. This will give us much better shader cache utilization. A great example of this would be slice_gpu.

**Comment by dsmilkov** [comment]
To give a real-world context, when real-time data collection happens in the browser (e.g. [Audio recognition Codelab](https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab/index.html)), the number of examples collected is dynamic and causes recompilation of the shaders, slowing down the program significantly.

**Comment by rthadur** [comment]
New issue has been created here https://github.com/tensorflow/tfjs/issues/5205 to track , will close this issue.
