### ISSUE TITLE
Optimize slice() in WEBGL backend

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#990]
Slice is frequently used in data prepping, various layers (RNN cells) and ops (unstack, split, scatter, etc).

Right now each call to slice() results in running a shader program (in WebGL backend), and copying memory (in CPU backend).

We should instead maintain an offset index into the existing tensor making slicing effectively free.

**Comment by rthadur** [comment]
Related PR has been merged [here](https://github.com/tensorflow/tfjs-core/pull/1470) , so closing this issue.
