### ISSUE TITLE
Add API documentation example for custom IO handlers

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#993]
We've had a few people ask about this, it would be good to have an example inside the API docs.

**Comment by caisq** [comment]
cc @tafsiri

**Comment by tafsiri** [comment]
+1

related to https://github.com/tensorflow/tfjs/issues/1207

**Comment by rthadur** [comment]
Looks like this has been fixed [here](https://github.com/tensorflow/tfjs-website/pull/240) , so closing this issue.Thank you
