### ISSUE TITLE
Porting the weights stored in the TF using tf.train.Saver

### ISSUE THREAD

**Issue by PABCSoft** [tensorflow/tfjs#996]
Is it possible to port a checkpoint saved via tf.train.saver?

**Comment by pyu10055** [comment]
yes, the tfjs_converter supports session bundle format. https://github.com/tensorflow/tfjs-converter

**Comment by PABCSoft** [comment]
Thank you! Is it possible to run this on Windows?

**Comment by PABCSoft** [comment]
Who can convert these models: https://drive.google.com/drive/mobile/folders/1jTsAUAKrMiHO2gn7s-fFZ_zUSzgKoPyp?usp=drive_open? I cannot run the Converter on Windows.
