### ISSUE TITLE
Install issues Posenet on Mac

### ISSUE THREAD

**Issue by jdjddjdj** [tensorflow/tfjs#997]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
latest as of dec 2108

#### Browser version
Firefox 63.0.3
Chrome 71.0.3578.98

#### Describe the problem or feature request
Mac install problems with posenet

#### Code to reproduce the bug / link to feature request
Hello All!
Posenet came to my attention thru the Max/Msp forums, where a "code-widget" has been created to let posenet data come into Max. 
I have been playing with the web-demo of Posenet (which works perfectly in Chrome or Firefox for me btw ) and am **super** excited about being able to use this new tech. Thank you!!!!!

 I have had massive problems installing posenet from the Max project, and also from the install instructions at https://github.com/tensorflow/tfjs-models/tree/master/posenet

Here's what I do - is there some operator error involved here?
(I am a longterm Mac veteran - but pretty newby in command-line world)

I cd to the posenet directory, and use the command:
npm install @tensorflow-models/posenet

The problems I am seeing are that inside the Posenet directory, the installer creates a directory "node_modules/.staging" during install. For a brief few seconds i see the .staging folder populating with many many directories, then the directories disappear, leaving the node_modules directory completely empty.

I will put the error log that I get when I do this at the very end of the email - is quite large.
the very last line in the readout is bizzarro too..

If you can point me in the direction I need to be heading to get this resolved that would be MOST appreciated.

This is great tech, and will bypass my kinect needs for the interactives that I build. (cannnnnot wait : )

thanks much!
jd
Mac Mini Late 2012
2.5 ghz I5
16 gb ram
Os 10.13.5

************ Error report below **************

Mac-mini:~ PubMini2$ cd Documents
Mac-mini:Documents PubMini2$ cd max\ quicky\ stuff/
Mac-mini:max quicky stuff PubMini2$ cd n4m-examples-master
Mac-mini:n4m-examples-master PubMini2$ cd posenet
Mac-mini:posenet PubMini2$ npm install @tensorflow-models/posenet

WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/through2-cc5a0220/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/through2-cc5a0220/LICENSE.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/through2-cc5a0220/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/through2-cc5a0220/through2.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-dbb14d3e/lib/_stream_readable.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/removeUselessDefs.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/quote-stream-f653b792/test/simple.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/cleanupEnableBackground.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/func-name-matching.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/assets/ElmAsset.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/quote-stream-f653b792/test/unicode_separators.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/removeUselessStrokeAndFill.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/quote-stream-f653b792/test/whitespace.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/cleanupAttrs.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-7b2c307e/lib/internal/streams/stream.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-5547988c/lib/internal/streams/stream-browser.js'
WARN tarWARN ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-5547988c/lib/internal/streams/stream.js'
 tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/removeViewBox.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-28caa6e6/doc/wg-meetings/2015-01-30.md'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/addClassesToSVGElement.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/removeXMLNS.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/addAttributesToSVGElement.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/func-names.js'
WARN tarWARN ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/assets/WebManifestAsset.js'
 tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/stream-http-aa69fdf9/test/server/static/browserify.png'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/passthrough.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/func-style.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/assets/CoffeeScriptAsset.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/function-paren-newline.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/assets/YAMLAsset.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/assets/PugAsset.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/generator-star-spacing.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/workerfarm'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/getter-return.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/passthrough.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/workerfarm'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/readable-browser.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/global-require.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/readable.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/guard-for-in.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/workerfarm'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/handle-callback-err.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/transform.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/id-blacklist.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/parcel-bundler-7ca14012/lib/workerfarm'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/writable-browser.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/id-length.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-af0de92a/writable.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/id-match.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/implicit-arrow-linebreak.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/eslint-3b994413/lib/rules/indent-legacy.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/clang-format-6cc4b573/bin/git-clang-format'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/clang-format-6cc4b573/bin/linux_x64'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/removeXMLProcInst.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/expand-brackets-32e83784/changelog.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/_transforms.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/clang-format-6cc4b573/bin/win32'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/readable-browser.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/nanomatch-860201b1/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/readable.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/extglob-3a4adf63/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/nanomatch-860201b1/CHANGELOG.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/extglob-3a4adf63/changelog.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/nanomatch-860201b1/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/transform.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/extglob-3a4adf63/index.js'
WARN tarWARN ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/writable-browser.js'
 tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/sortAttrs.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/extglob-3a4adf63/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/use-2a79a1e5/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/readable-stream-c8a0a1c4/writable.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/extglob-3a4adf63/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/stream-http-aa69fdf9/test/server/static/test-polyfill.js'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/use-2a79a1e5/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/nanomatch-860201b1/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/nanomatch-860201b1/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-2eea755e/plugins/_path.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, lstat '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/svgo-a006018f/lib/svgo'
WARN tar ENOENT: no such file or directory, open '/Users/PubMini2/Documents/max quicky stuff/n4m-examples-master/posenet/node_modules/.staging/@tensorflow/tfjs-f0d28424/dist/tf.min.js'
npm ERR! Unexpected end of JSON input while parsing near '...ps://github.com/Learn'

**Comment by tafsiri** [comment]
@jdjddjdj Could you let us know what version of node and npm you are using? I see some issues on the npm repo that seem to have some similar behavior on older versions.

Also are you able to run the demos locally? See Setup section on https://github.com/tensorflow/tfjs-models/tree/master/posenet/demos

**Comment by jdjddjdj** [comment]
Hello Yannick!
thanks for your help - all this command-line stuff is a biiig learning
curve for me.
Haven't done much for many years... is a forest of info.

npm -v gives 6.4.1
node -v gives v10.14.2

This page runs great and would be plenty accurate for my needs
https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html
This one runs good too
https://ml5js.org/docs/posenet-webcam

I don't know if it was mentioned but i ended up here thru this page
https://cycling74.com/forums/skeleton-tracking-with-posenet-and-node-for-max

ALL of the Node demos here run well (except the posenet one) run well
https://github.com/Cycling74/n4m-examples

Am going to try the Max patches tomorrow on a PC to see if I can narrow
this to a Mac-specific issue.

thanks!!!!
jd

**Comment by jdjddjdj** [comment]
and here is the Max project page on github that explains the project
(not sure what info may/may not be helpful, sorry)

https://github.com/tensorflow/tfjs-models/tree/master/posenet

**Comment by jdjddjdj** [comment]
pasted wrong thing
Max github project
https://github.com/Cycling74/n4m-examples/tree/master/posenet

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
